%
% Status : main Dynare file
%
% Warning : this file is generated automatically by Dynare
%           from model file (.mod)

tic0 = tic;
% Save empty dates and dseries objects in memory.
dates('initialize');
dseries('initialize');
% Define global variables.
global M_ options_ oo_ estim_params_ bayestopt_ dataset_ dataset_info estimation_info ys0_ ex0_
options_ = [];
M_.fname = 'NK_CW09';
M_.dynare_version = '4.5.4';
oo_.dynare_version = '4.5.4';
options_.dynare_version = '4.5.4';
%
% Some global variables initialization
%
global_initialization;
diary off;
diary('NK_CW09.log');
M_.exo_names = 'e_C_bar_s';
M_.exo_names_tex = 'e\_C\_bar\_s';
M_.exo_names_long = 'e_C_bar_s';
M_.exo_names = char(M_.exo_names, 'e_C_bar_b');
M_.exo_names_tex = char(M_.exo_names_tex, 'e\_C\_bar\_b');
M_.exo_names_long = char(M_.exo_names_long, 'e_C_bar_b');
M_.exo_names = char(M_.exo_names, 'e_H_bar');
M_.exo_names_tex = char(M_.exo_names_tex, 'e\_H\_bar');
M_.exo_names_long = char(M_.exo_names_long, 'e_H_bar');
M_.exo_names = char(M_.exo_names, 'e_mu_w');
M_.exo_names_tex = char(M_.exo_names_tex, 'e\_mu\_w');
M_.exo_names_long = char(M_.exo_names_long, 'e_mu_w');
M_.exo_names = char(M_.exo_names, 'e_tau');
M_.exo_names_tex = char(M_.exo_names_tex, 'e\_tau');
M_.exo_names_long = char(M_.exo_names_long, 'e_tau');
M_.exo_names = char(M_.exo_names, 'e_Xi_tilde');
M_.exo_names_tex = char(M_.exo_names_tex, 'e\_Xi\_tilde');
M_.exo_names_long = char(M_.exo_names_long, 'e_Xi_tilde');
M_.exo_names = char(M_.exo_names, 'e_chi_tilde');
M_.exo_names_tex = char(M_.exo_names_tex, 'e\_chi\_tilde');
M_.exo_names_long = char(M_.exo_names_long, 'e_chi_tilde');
M_.exo_names = char(M_.exo_names, 'e_Z');
M_.exo_names_tex = char(M_.exo_names_tex, 'e\_Z');
M_.exo_names_long = char(M_.exo_names_long, 'e_Z');
M_.exo_names = char(M_.exo_names, 'e_b_g');
M_.exo_names_tex = char(M_.exo_names_tex, 'e\_b\_g');
M_.exo_names_long = char(M_.exo_names_long, 'e_b_g');
M_.exo_names = char(M_.exo_names, 'interest_');
M_.exo_names_tex = char(M_.exo_names_tex, 'interest\_');
M_.exo_names_long = char(M_.exo_names_long, 'interest_');
M_.exo_names = char(M_.exo_names, 'fiscal_');
M_.exo_names_tex = char(M_.exo_names_tex, 'fiscal\_');
M_.exo_names_long = char(M_.exo_names_long, 'fiscal_');
M_.endo_names = 'i_d';
M_.endo_names_tex = 'i\_d';
M_.endo_names_long = 'i_d';
M_.endo_names = char(M_.endo_names, 'i_d_hat_a');
M_.endo_names_tex = char(M_.endo_names_tex, 'i\_d\_hat\_a');
M_.endo_names_long = char(M_.endo_names_long, 'i_d_hat_a');
M_.endo_names = char(M_.endo_names, 'lambda_b');
M_.endo_names_tex = char(M_.endo_names_tex, 'lambda\_b');
M_.endo_names_long = char(M_.endo_names_long, 'lambda_b');
M_.endo_names = char(M_.endo_names, 'lambda_s');
M_.endo_names_tex = char(M_.endo_names_tex, 'lambda\_s');
M_.endo_names_long = char(M_.endo_names_long, 'lambda_s');
M_.endo_names = char(M_.endo_names, 'Pi');
M_.endo_names_tex = char(M_.endo_names_tex, 'Pi');
M_.endo_names_long = char(M_.endo_names_long, 'Pi');
M_.endo_names = char(M_.endo_names, 'Pi_hat_a');
M_.endo_names_tex = char(M_.endo_names_tex, 'Pi\_hat\_a');
M_.endo_names_long = char(M_.endo_names_long, 'Pi_hat_a');
M_.endo_names = char(M_.endo_names, 'Y');
M_.endo_names_tex = char(M_.endo_names_tex, 'Y');
M_.endo_names_long = char(M_.endo_names_long, 'Y');
M_.endo_names = char(M_.endo_names, 'K');
M_.endo_names_tex = char(M_.endo_names_tex, 'K');
M_.endo_names_long = char(M_.endo_names_long, 'K');
M_.endo_names = char(M_.endo_names, 'F');
M_.endo_names_tex = char(M_.endo_names_tex, 'F');
M_.endo_names_long = char(M_.endo_names_long, 'F');
M_.endo_names = char(M_.endo_names, 'Delta');
M_.endo_names_tex = char(M_.endo_names_tex, 'Delta');
M_.endo_names_long = char(M_.endo_names_long, 'Delta');
M_.endo_names = char(M_.endo_names, 'b');
M_.endo_names_tex = char(M_.endo_names_tex, 'b');
M_.endo_names_long = char(M_.endo_names_long, 'b');
M_.endo_names = char(M_.endo_names, 'G');
M_.endo_names_tex = char(M_.endo_names_tex, 'G');
M_.endo_names_long = char(M_.endo_names_long, 'G');
M_.endo_names = char(M_.endo_names, 'chi_tilde');
M_.endo_names_tex = char(M_.endo_names_tex, 'chi\_tilde');
M_.endo_names_long = char(M_.endo_names_long, 'chi_tilde');
M_.endo_names = char(M_.endo_names, 'omega_hat_a');
M_.endo_names_tex = char(M_.endo_names_tex, 'omega\_hat\_a');
M_.endo_names_long = char(M_.endo_names_long, 'omega_hat_a');
M_.endo_names = char(M_.endo_names, 'C_bar_s');
M_.endo_names_tex = char(M_.endo_names_tex, 'C\_bar\_s');
M_.endo_names_long = char(M_.endo_names_long, 'C_bar_s');
M_.endo_names = char(M_.endo_names, 'C_bar_b');
M_.endo_names_tex = char(M_.endo_names_tex, 'C\_bar\_b');
M_.endo_names_long = char(M_.endo_names_long, 'C_bar_b');
M_.endo_names = char(M_.endo_names, 'H_bar');
M_.endo_names_tex = char(M_.endo_names_tex, 'H\_bar');
M_.endo_names_long = char(M_.endo_names_long, 'H_bar');
M_.endo_names = char(M_.endo_names, 'mu_w');
M_.endo_names_tex = char(M_.endo_names_tex, 'mu\_w');
M_.endo_names_long = char(M_.endo_names_long, 'mu_w');
M_.endo_names = char(M_.endo_names, 'tau');
M_.endo_names_tex = char(M_.endo_names_tex, 'tau');
M_.endo_names_long = char(M_.endo_names_long, 'tau');
M_.endo_names = char(M_.endo_names, 'omega');
M_.endo_names_tex = char(M_.endo_names_tex, 'omega');
M_.endo_names_long = char(M_.endo_names_long, 'omega');
M_.endo_names = char(M_.endo_names, 'Z');
M_.endo_names_tex = char(M_.endo_names_tex, 'Z');
M_.endo_names_long = char(M_.endo_names_long, 'Z');
M_.endo_names = char(M_.endo_names, 'b_g');
M_.endo_names_tex = char(M_.endo_names_tex, 'b\_g');
M_.endo_names_long = char(M_.endo_names_long, 'b_g');
M_.endo_names = char(M_.endo_names, 'B');
M_.endo_names_tex = char(M_.endo_names_tex, 'B');
M_.endo_names_long = char(M_.endo_names_long, 'B');
M_.endo_names = char(M_.endo_names, 'Lambda');
M_.endo_names_tex = char(M_.endo_names_tex, 'Lambda');
M_.endo_names_long = char(M_.endo_names_long, 'Lambda');
M_.endo_names = char(M_.endo_names, 'lambda_tilde');
M_.endo_names_tex = char(M_.endo_names_tex, 'lambda\_tilde');
M_.endo_names_long = char(M_.endo_names_long, 'lambda_tilde');
M_.endo_names = char(M_.endo_names, 'i_d_hat');
M_.endo_names_tex = char(M_.endo_names_tex, 'i\_d\_hat');
M_.endo_names_long = char(M_.endo_names_long, 'i_d_hat');
M_.endo_names = char(M_.endo_names, 'lambda_b_hat');
M_.endo_names_tex = char(M_.endo_names_tex, 'lambda\_b\_hat');
M_.endo_names_long = char(M_.endo_names_long, 'lambda_b_hat');
M_.endo_names = char(M_.endo_names, 'lambda_s_hat');
M_.endo_names_tex = char(M_.endo_names_tex, 'lambda\_s\_hat');
M_.endo_names_long = char(M_.endo_names_long, 'lambda_s_hat');
M_.endo_names = char(M_.endo_names, 'Pi_hat');
M_.endo_names_tex = char(M_.endo_names_tex, 'Pi\_hat');
M_.endo_names_long = char(M_.endo_names_long, 'Pi_hat');
M_.endo_names = char(M_.endo_names, 'Y_hat');
M_.endo_names_tex = char(M_.endo_names_tex, 'Y\_hat');
M_.endo_names_long = char(M_.endo_names_long, 'Y_hat');
M_.endo_names = char(M_.endo_names, 'K_hat');
M_.endo_names_tex = char(M_.endo_names_tex, 'K\_hat');
M_.endo_names_long = char(M_.endo_names_long, 'K_hat');
M_.endo_names = char(M_.endo_names, 'F_hat');
M_.endo_names_tex = char(M_.endo_names_tex, 'F\_hat');
M_.endo_names_long = char(M_.endo_names_long, 'F_hat');
M_.endo_names = char(M_.endo_names, 'Delta_hat');
M_.endo_names_tex = char(M_.endo_names_tex, 'Delta\_hat');
M_.endo_names_long = char(M_.endo_names_long, 'Delta_hat');
M_.endo_names = char(M_.endo_names, 'b_hat');
M_.endo_names_tex = char(M_.endo_names_tex, 'b\_hat');
M_.endo_names_long = char(M_.endo_names_long, 'b_hat');
M_.endo_names = char(M_.endo_names, 'Xi_tilde_hat');
M_.endo_names_tex = char(M_.endo_names_tex, 'Xi\_tilde\_hat');
M_.endo_names_long = char(M_.endo_names_long, 'Xi_tilde_hat');
M_.endo_names = char(M_.endo_names, 'G_hat');
M_.endo_names_tex = char(M_.endo_names_tex, 'G\_hat');
M_.endo_names_long = char(M_.endo_names_long, 'G_hat');
M_.endo_names = char(M_.endo_names, 'chi_tilde_hat');
M_.endo_names_tex = char(M_.endo_names_tex, 'chi\_tilde\_hat');
M_.endo_names_long = char(M_.endo_names_long, 'chi_tilde_hat');
M_.endo_names = char(M_.endo_names, 'C_bar_s_hat');
M_.endo_names_tex = char(M_.endo_names_tex, 'C\_bar\_s\_hat');
M_.endo_names_long = char(M_.endo_names_long, 'C_bar_s_hat');
M_.endo_names = char(M_.endo_names, 'C_bar_b_hat');
M_.endo_names_tex = char(M_.endo_names_tex, 'C\_bar\_b\_hat');
M_.endo_names_long = char(M_.endo_names_long, 'C_bar_b_hat');
M_.endo_names = char(M_.endo_names, 'H_bar_hat');
M_.endo_names_tex = char(M_.endo_names_tex, 'H\_bar\_hat');
M_.endo_names_long = char(M_.endo_names_long, 'H_bar_hat');
M_.endo_names = char(M_.endo_names, 'mu_w_hat');
M_.endo_names_tex = char(M_.endo_names_tex, 'mu\_w\_hat');
M_.endo_names_long = char(M_.endo_names_long, 'mu_w_hat');
M_.endo_names = char(M_.endo_names, 'tau_hat');
M_.endo_names_tex = char(M_.endo_names_tex, 'tau\_hat');
M_.endo_names_long = char(M_.endo_names_long, 'tau_hat');
M_.endo_names = char(M_.endo_names, 'omega_hat');
M_.endo_names_tex = char(M_.endo_names_tex, 'omega\_hat');
M_.endo_names_long = char(M_.endo_names_long, 'omega_hat');
M_.endo_names = char(M_.endo_names, 'Z_hat');
M_.endo_names_tex = char(M_.endo_names_tex, 'Z\_hat');
M_.endo_names_long = char(M_.endo_names_long, 'Z_hat');
M_.endo_names = char(M_.endo_names, 'b_g_hat');
M_.endo_names_tex = char(M_.endo_names_tex, 'b\_g\_hat');
M_.endo_names_long = char(M_.endo_names_long, 'b_g_hat');
M_.endo_names = char(M_.endo_names, 'i_b_hat');
M_.endo_names_tex = char(M_.endo_names_tex, 'i\_b\_hat');
M_.endo_names_long = char(M_.endo_names_long, 'i_b_hat');
M_.endo_names = char(M_.endo_names, 'Lambda_hat');
M_.endo_names_tex = char(M_.endo_names_tex, 'Lambda\_hat');
M_.endo_names_long = char(M_.endo_names_long, 'Lambda_hat');
M_.endo_names = char(M_.endo_names, 'lambda_tilde_hat');
M_.endo_names_tex = char(M_.endo_names_tex, 'lambda\_tilde\_hat');
M_.endo_names_long = char(M_.endo_names_long, 'lambda_tilde_hat');
M_.endo_names = char(M_.endo_names, 'e_G');
M_.endo_names_tex = char(M_.endo_names_tex, 'e\_G');
M_.endo_names_long = char(M_.endo_names_long, 'e_G');
M_.endo_names = char(M_.endo_names, 'Y_n_hat');
M_.endo_names_tex = char(M_.endo_names_tex, 'Y\_n\_hat');
M_.endo_names_long = char(M_.endo_names_long, 'Y_n_hat');
M_.endo_names = char(M_.endo_names, 'interest');
M_.endo_names_tex = char(M_.endo_names_tex, 'interest');
M_.endo_names_long = char(M_.endo_names_long, 'interest');
M_.endo_names = char(M_.endo_names, 'inflation');
M_.endo_names_tex = char(M_.endo_names_tex, 'inflation');
M_.endo_names_long = char(M_.endo_names_long, 'inflation');
M_.endo_names = char(M_.endo_names, 'inflationq');
M_.endo_names_tex = char(M_.endo_names_tex, 'inflationq');
M_.endo_names_long = char(M_.endo_names_long, 'inflationq');
M_.endo_names = char(M_.endo_names, 'outputgap');
M_.endo_names_tex = char(M_.endo_names_tex, 'outputgap');
M_.endo_names_long = char(M_.endo_names_long, 'outputgap');
M_.endo_names = char(M_.endo_names, 'output');
M_.endo_names_tex = char(M_.endo_names_tex, 'output');
M_.endo_names_long = char(M_.endo_names_long, 'output');
M_.endo_names = char(M_.endo_names, 'fispol');
M_.endo_names_tex = char(M_.endo_names_tex, 'fispol');
M_.endo_names_long = char(M_.endo_names_long, 'fispol');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_78');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_78');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_78');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_82');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_82');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_82');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_86');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_86');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_86');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_113');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_113');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_113');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_117');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_117');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_117');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_121');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_121');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_121');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_148');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_148');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_148');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_152');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_152');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_152');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_156');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_156');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_156');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_28_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_28\_1');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_28_1');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_28_2');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_28\_2');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_28_2');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_54_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_54\_1');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_54_1');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_54_2');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_54\_2');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_54_2');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_54_3');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_54\_3');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_54_3');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_53_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_53\_1');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_53_1');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_53_2');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_53\_2');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_53_2');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_53_3');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_53\_3');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_53_3');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_50_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_50\_1');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_50_1');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_50_2');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_50\_2');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_50_2');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_50_3');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_50\_3');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_50_3');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_52_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_52\_1');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_52_1');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_52_2');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_52\_2');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_52_2');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_52_3');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_52\_3');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_52_3');
M_.endo_partitions = struct();
M_.param_names = 'cofintintb1';
M_.param_names_tex = 'cofintintb1';
M_.param_names_long = 'cofintintb1';
M_.param_names = char(M_.param_names, 'cofintintb2');
M_.param_names_tex = char(M_.param_names_tex, 'cofintintb2');
M_.param_names_long = char(M_.param_names_long, 'cofintintb2');
M_.param_names = char(M_.param_names, 'cofintintb3');
M_.param_names_tex = char(M_.param_names_tex, 'cofintintb3');
M_.param_names_long = char(M_.param_names_long, 'cofintintb3');
M_.param_names = char(M_.param_names, 'cofintintb4');
M_.param_names_tex = char(M_.param_names_tex, 'cofintintb4');
M_.param_names_long = char(M_.param_names_long, 'cofintintb4');
M_.param_names = char(M_.param_names, 'cofintinf0');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinf0');
M_.param_names_long = char(M_.param_names_long, 'cofintinf0');
M_.param_names = char(M_.param_names, 'cofintinfb1');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinfb1');
M_.param_names_long = char(M_.param_names_long, 'cofintinfb1');
M_.param_names = char(M_.param_names, 'cofintinfb2');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinfb2');
M_.param_names_long = char(M_.param_names_long, 'cofintinfb2');
M_.param_names = char(M_.param_names, 'cofintinfb3');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinfb3');
M_.param_names_long = char(M_.param_names_long, 'cofintinfb3');
M_.param_names = char(M_.param_names, 'cofintinfb4');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinfb4');
M_.param_names_long = char(M_.param_names_long, 'cofintinfb4');
M_.param_names = char(M_.param_names, 'cofintinff1');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinff1');
M_.param_names_long = char(M_.param_names_long, 'cofintinff1');
M_.param_names = char(M_.param_names, 'cofintinff2');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinff2');
M_.param_names_long = char(M_.param_names_long, 'cofintinff2');
M_.param_names = char(M_.param_names, 'cofintinff3');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinff3');
M_.param_names_long = char(M_.param_names_long, 'cofintinff3');
M_.param_names = char(M_.param_names, 'cofintinff4');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinff4');
M_.param_names_long = char(M_.param_names_long, 'cofintinff4');
M_.param_names = char(M_.param_names, 'cofintout');
M_.param_names_tex = char(M_.param_names_tex, 'cofintout');
M_.param_names_long = char(M_.param_names_long, 'cofintout');
M_.param_names = char(M_.param_names, 'cofintoutb1');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutb1');
M_.param_names_long = char(M_.param_names_long, 'cofintoutb1');
M_.param_names = char(M_.param_names, 'cofintoutb2');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutb2');
M_.param_names_long = char(M_.param_names_long, 'cofintoutb2');
M_.param_names = char(M_.param_names, 'cofintoutb3');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutb3');
M_.param_names_long = char(M_.param_names_long, 'cofintoutb3');
M_.param_names = char(M_.param_names, 'cofintoutb4');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutb4');
M_.param_names_long = char(M_.param_names_long, 'cofintoutb4');
M_.param_names = char(M_.param_names, 'cofintoutf1');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutf1');
M_.param_names_long = char(M_.param_names_long, 'cofintoutf1');
M_.param_names = char(M_.param_names, 'cofintoutf2');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutf2');
M_.param_names_long = char(M_.param_names_long, 'cofintoutf2');
M_.param_names = char(M_.param_names, 'cofintoutf3');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutf3');
M_.param_names_long = char(M_.param_names_long, 'cofintoutf3');
M_.param_names = char(M_.param_names, 'cofintoutf4');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutf4');
M_.param_names_long = char(M_.param_names_long, 'cofintoutf4');
M_.param_names = char(M_.param_names, 'cofintoutp');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutp');
M_.param_names_long = char(M_.param_names_long, 'cofintoutp');
M_.param_names = char(M_.param_names, 'cofintoutpb1');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpb1');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpb1');
M_.param_names = char(M_.param_names, 'cofintoutpb2');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpb2');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpb2');
M_.param_names = char(M_.param_names, 'cofintoutpb3');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpb3');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpb3');
M_.param_names = char(M_.param_names, 'cofintoutpb4');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpb4');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpb4');
M_.param_names = char(M_.param_names, 'cofintoutpf1');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpf1');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpf1');
M_.param_names = char(M_.param_names, 'cofintoutpf2');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpf2');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpf2');
M_.param_names = char(M_.param_names, 'cofintoutpf3');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpf3');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpf3');
M_.param_names = char(M_.param_names, 'cofintoutpf4');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpf4');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpf4');
M_.param_names = char(M_.param_names, 'std_r_');
M_.param_names_tex = char(M_.param_names_tex, 'std\_r\_');
M_.param_names_long = char(M_.param_names_long, 'std_r_');
M_.param_names = char(M_.param_names, 'std_r_quart');
M_.param_names_tex = char(M_.param_names_tex, 'std\_r\_quart');
M_.param_names_long = char(M_.param_names_long, 'std_r_quart');
M_.param_names = char(M_.param_names, 'coffispol');
M_.param_names_tex = char(M_.param_names_tex, 'coffispol');
M_.param_names_long = char(M_.param_names_long, 'coffispol');
M_.param_names = char(M_.param_names, 'beta');
M_.param_names_tex = char(M_.param_names_tex, 'beta');
M_.param_names_long = char(M_.param_names_long, 'beta');
M_.param_names = char(M_.param_names, 'phi');
M_.param_names_tex = char(M_.param_names_tex, 'phi');
M_.param_names_long = char(M_.param_names_long, 'phi');
M_.param_names = char(M_.param_names, 'delta');
M_.param_names_tex = char(M_.param_names_tex, 'delta');
M_.param_names_long = char(M_.param_names_long, 'delta');
M_.param_names = char(M_.param_names, 'pi_b');
M_.param_names_tex = char(M_.param_names_tex, 'pi\_b');
M_.param_names_long = char(M_.param_names_long, 'pi_b');
M_.param_names = char(M_.param_names, 'pi_s');
M_.param_names_tex = char(M_.param_names_tex, 'pi\_s');
M_.param_names_long = char(M_.param_names_long, 'pi_s');
M_.param_names = char(M_.param_names, 'mu_p');
M_.param_names_tex = char(M_.param_names_tex, 'mu\_p');
M_.param_names_long = char(M_.param_names_long, 'mu_p');
M_.param_names = char(M_.param_names, 'omega_y');
M_.param_names_tex = char(M_.param_names_tex, 'omega\_y');
M_.param_names_long = char(M_.param_names_long, 'omega_y');
M_.param_names = char(M_.param_names, 'nu');
M_.param_names_tex = char(M_.param_names_tex, 'nu');
M_.param_names_long = char(M_.param_names_long, 'nu');
M_.param_names = char(M_.param_names, 'theta');
M_.param_names_tex = char(M_.param_names_tex, 'theta');
M_.param_names_long = char(M_.param_names_long, 'theta');
M_.param_names = char(M_.param_names, 'alpha');
M_.param_names_tex = char(M_.param_names_tex, 'alpha');
M_.param_names_long = char(M_.param_names_long, 'alpha');
M_.param_names = char(M_.param_names, 'sigma_b');
M_.param_names_tex = char(M_.param_names_tex, 'sigma\_b');
M_.param_names_long = char(M_.param_names_long, 'sigma_b');
M_.param_names = char(M_.param_names, 'sigma_s');
M_.param_names_tex = char(M_.param_names_tex, 'sigma\_s');
M_.param_names_long = char(M_.param_names_long, 'sigma_s');
M_.param_names = char(M_.param_names, 'psi_b');
M_.param_names_tex = char(M_.param_names_tex, 'psi\_b');
M_.param_names_long = char(M_.param_names_long, 'psi_b');
M_.param_names = char(M_.param_names, 'psi_s');
M_.param_names_tex = char(M_.param_names_tex, 'psi\_s');
M_.param_names_long = char(M_.param_names_long, 'psi_s');
M_.param_names = char(M_.param_names, 'psi');
M_.param_names_tex = char(M_.param_names_tex, 'psi');
M_.param_names_long = char(M_.param_names_long, 'psi');
M_.param_names = char(M_.param_names, 'eta');
M_.param_names_tex = char(M_.param_names_tex, 'eta');
M_.param_names_long = char(M_.param_names_long, 'eta');
M_.param_names = char(M_.param_names, 'varchi');
M_.param_names_tex = char(M_.param_names_tex, 'varchi');
M_.param_names_long = char(M_.param_names_long, 'varchi');
M_.param_names = char(M_.param_names, 'phi_pi');
M_.param_names_tex = char(M_.param_names_tex, 'phi\_pi');
M_.param_names_long = char(M_.param_names_long, 'phi_pi');
M_.param_names = char(M_.param_names, 'phi_y');
M_.param_names_tex = char(M_.param_names_tex, 'phi\_y');
M_.param_names_long = char(M_.param_names_long, 'phi_y');
M_.param_names = char(M_.param_names, 'rho_C_bar_s');
M_.param_names_tex = char(M_.param_names_tex, 'rho\_C\_bar\_s');
M_.param_names_long = char(M_.param_names_long, 'rho_C_bar_s');
M_.param_names = char(M_.param_names, 'rho_C_bar_b');
M_.param_names_tex = char(M_.param_names_tex, 'rho\_C\_bar\_b');
M_.param_names_long = char(M_.param_names_long, 'rho_C_bar_b');
M_.param_names = char(M_.param_names, 'rho_G');
M_.param_names_tex = char(M_.param_names_tex, 'rho\_G');
M_.param_names_long = char(M_.param_names_long, 'rho_G');
M_.param_names = char(M_.param_names, 'rho_H_bar');
M_.param_names_tex = char(M_.param_names_tex, 'rho\_H\_bar');
M_.param_names_long = char(M_.param_names_long, 'rho_H_bar');
M_.param_names = char(M_.param_names, 'rho_mu_w');
M_.param_names_tex = char(M_.param_names_tex, 'rho\_mu\_w');
M_.param_names_long = char(M_.param_names_long, 'rho_mu_w');
M_.param_names = char(M_.param_names, 'rho_tau');
M_.param_names_tex = char(M_.param_names_tex, 'rho\_tau');
M_.param_names_long = char(M_.param_names_long, 'rho_tau');
M_.param_names = char(M_.param_names, 'rho_epsilon_m');
M_.param_names_tex = char(M_.param_names_tex, 'rho\_epsilon\_m');
M_.param_names_long = char(M_.param_names_long, 'rho_epsilon_m');
M_.param_names = char(M_.param_names, 'rho_Xi_tilde');
M_.param_names_tex = char(M_.param_names_tex, 'rho\_Xi\_tilde');
M_.param_names_long = char(M_.param_names_long, 'rho_Xi_tilde');
M_.param_names = char(M_.param_names, 'rho_chi_tilde');
M_.param_names_tex = char(M_.param_names_tex, 'rho\_chi\_tilde');
M_.param_names_long = char(M_.param_names_long, 'rho_chi_tilde');
M_.param_names = char(M_.param_names, 'rho_Z');
M_.param_names_tex = char(M_.param_names_tex, 'rho\_Z');
M_.param_names_long = char(M_.param_names_long, 'rho_Z');
M_.param_names = char(M_.param_names, 'rho_b_g');
M_.param_names_tex = char(M_.param_names_tex, 'rho\_b\_g');
M_.param_names_long = char(M_.param_names_long, 'rho_b_g');
M_.param_names = char(M_.param_names, 'Omega_bar');
M_.param_names_tex = char(M_.param_names_tex, 'Omega\_bar');
M_.param_names_long = char(M_.param_names_long, 'Omega_bar');
M_.param_names = char(M_.param_names, 'rho_b_g_ar');
M_.param_names_tex = char(M_.param_names_tex, 'rho\_b\_g\_ar');
M_.param_names_long = char(M_.param_names_long, 'rho_b_g_ar');
M_.param_names = char(M_.param_names, 'Y_bar');
M_.param_names_tex = char(M_.param_names_tex, 'Y\_bar');
M_.param_names_long = char(M_.param_names_long, 'Y_bar');
M_.param_names = char(M_.param_names, 'rho_b');
M_.param_names_tex = char(M_.param_names_tex, 'rho\_b');
M_.param_names_long = char(M_.param_names_long, 'rho_b');
M_.param_names = char(M_.param_names, 's_b');
M_.param_names_tex = char(M_.param_names_tex, 's\_b');
M_.param_names_long = char(M_.param_names_long, 's_b');
M_.param_names = char(M_.param_names, 's_s');
M_.param_names_tex = char(M_.param_names_tex, 's\_s');
M_.param_names_long = char(M_.param_names_long, 's_s');
M_.param_names = char(M_.param_names, 's_g');
M_.param_names_tex = char(M_.param_names_tex, 's\_g');
M_.param_names_long = char(M_.param_names_long, 's_g');
M_.param_names = char(M_.param_names, 's_c');
M_.param_names_tex = char(M_.param_names_tex, 's\_c');
M_.param_names_long = char(M_.param_names_long, 's_c');
M_.param_names = char(M_.param_names, 'i_d_bar');
M_.param_names_tex = char(M_.param_names_tex, 'i\_d\_bar');
M_.param_names_long = char(M_.param_names_long, 'i_d_bar');
M_.param_names = char(M_.param_names, 'omega_bar');
M_.param_names_tex = char(M_.param_names_tex, 'omega\_bar');
M_.param_names_long = char(M_.param_names_long, 'omega_bar');
M_.param_names = char(M_.param_names, 's_Xi');
M_.param_names_tex = char(M_.param_names_tex, 's\_Xi');
M_.param_names_long = char(M_.param_names_long, 's_Xi');
M_.param_names = char(M_.param_names, 'Xi_tilde_bar');
M_.param_names_tex = char(M_.param_names_tex, 'Xi\_tilde\_bar');
M_.param_names_long = char(M_.param_names_long, 'Xi_tilde_bar');
M_.param_names = char(M_.param_names, 'C_bar_b_bar');
M_.param_names_tex = char(M_.param_names_tex, 'C\_bar\_b\_bar');
M_.param_names_long = char(M_.param_names_long, 'C_bar_b_bar');
M_.param_names = char(M_.param_names, 'C_bar_s_bar');
M_.param_names_tex = char(M_.param_names_tex, 'C\_bar\_s\_bar');
M_.param_names_long = char(M_.param_names_long, 'C_bar_s_bar');
M_.param_names = char(M_.param_names, 'chi_tilde_bar');
M_.param_names_tex = char(M_.param_names_tex, 'chi\_tilde\_bar');
M_.param_names_long = char(M_.param_names_long, 'chi_tilde_bar');
M_.param_names = char(M_.param_names, 'mu_w_bar');
M_.param_names_tex = char(M_.param_names_tex, 'mu\_w\_bar');
M_.param_names_long = char(M_.param_names_long, 'mu_w_bar');
M_.param_names = char(M_.param_names, 'tau_bar');
M_.param_names_tex = char(M_.param_names_tex, 'tau\_bar');
M_.param_names_long = char(M_.param_names_long, 'tau_bar');
M_.param_names = char(M_.param_names, 'lambda_b_bar');
M_.param_names_tex = char(M_.param_names_tex, 'lambda\_b\_bar');
M_.param_names_long = char(M_.param_names_long, 'lambda_b_bar');
M_.param_names = char(M_.param_names, 'lambda_s_bar');
M_.param_names_tex = char(M_.param_names_tex, 'lambda\_s\_bar');
M_.param_names_long = char(M_.param_names_long, 'lambda_s_bar');
M_.param_names = char(M_.param_names, 'K_bar');
M_.param_names_tex = char(M_.param_names_tex, 'K\_bar');
M_.param_names_long = char(M_.param_names_long, 'K_bar');
M_.param_names = char(M_.param_names, 'F_bar');
M_.param_names_tex = char(M_.param_names_tex, 'F\_bar');
M_.param_names_long = char(M_.param_names_long, 'F_bar');
M_.param_names = char(M_.param_names, 'lambda_tilde_bar');
M_.param_names_tex = char(M_.param_names_tex, 'lambda\_tilde\_bar');
M_.param_names_long = char(M_.param_names_long, 'lambda_tilde_bar');
M_.param_names = char(M_.param_names, 'Lambda_bar');
M_.param_names_tex = char(M_.param_names_tex, 'Lambda\_bar');
M_.param_names_long = char(M_.param_names_long, 'Lambda_bar');
M_.param_names = char(M_.param_names, 'H_bar_bar');
M_.param_names_tex = char(M_.param_names_tex, 'H\_bar\_bar');
M_.param_names_long = char(M_.param_names_long, 'H_bar_bar');
M_.param_names = char(M_.param_names, 'Z_bar');
M_.param_names_tex = char(M_.param_names_tex, 'Z\_bar');
M_.param_names_long = char(M_.param_names_long, 'Z_bar');
M_.param_names = char(M_.param_names, 'Pi_bar');
M_.param_names_tex = char(M_.param_names_tex, 'Pi\_bar');
M_.param_names_long = char(M_.param_names_long, 'Pi_bar');
M_.param_names = char(M_.param_names, 'Delta_bar');
M_.param_names_tex = char(M_.param_names_tex, 'Delta\_bar');
M_.param_names_long = char(M_.param_names_long, 'Delta_bar');
M_.param_names = char(M_.param_names, 'B_bar');
M_.param_names_tex = char(M_.param_names_tex, 'B\_bar');
M_.param_names_long = char(M_.param_names_long, 'B_bar');
M_.param_names = char(M_.param_names, 'b_bar');
M_.param_names_tex = char(M_.param_names_tex, 'b\_bar');
M_.param_names_long = char(M_.param_names_long, 'b_bar');
M_.param_names = char(M_.param_names, 'b_g_bar');
M_.param_names_tex = char(M_.param_names_tex, 'b\_g\_bar');
M_.param_names_long = char(M_.param_names_long, 'b_g_bar');
M_.param_names = char(M_.param_names, 'G_bar');
M_.param_names_tex = char(M_.param_names_tex, 'G\_bar');
M_.param_names_long = char(M_.param_names_long, 'G_bar');
M_.param_names = char(M_.param_names, 's_diff');
M_.param_names_tex = char(M_.param_names_tex, 's\_diff');
M_.param_names_long = char(M_.param_names_long, 's_diff');
M_.param_names = char(M_.param_names, 'sigma_bar');
M_.param_names_tex = char(M_.param_names_tex, 'sigma\_bar');
M_.param_names_long = char(M_.param_names_long, 'sigma_bar');
M_.param_partitions = struct();
M_.exo_det_nbr = 0;
M_.exo_nbr = 11;
M_.endo_nbr = 79;
M_.param_nbr = 97;
M_.orig_endo_nbr = 56;
M_.aux_vars(1).endo_index = 57;
M_.aux_vars(1).type = 0;
M_.aux_vars(2).endo_index = 58;
M_.aux_vars(2).type = 0;
M_.aux_vars(3).endo_index = 59;
M_.aux_vars(3).type = 0;
M_.aux_vars(4).endo_index = 60;
M_.aux_vars(4).type = 0;
M_.aux_vars(5).endo_index = 61;
M_.aux_vars(5).type = 0;
M_.aux_vars(6).endo_index = 62;
M_.aux_vars(6).type = 0;
M_.aux_vars(7).endo_index = 63;
M_.aux_vars(7).type = 0;
M_.aux_vars(8).endo_index = 64;
M_.aux_vars(8).type = 0;
M_.aux_vars(9).endo_index = 65;
M_.aux_vars(9).type = 0;
M_.aux_vars(10).endo_index = 66;
M_.aux_vars(10).type = 1;
M_.aux_vars(10).orig_index = 29;
M_.aux_vars(10).orig_lead_lag = -1;
M_.aux_vars(11).endo_index = 67;
M_.aux_vars(11).type = 1;
M_.aux_vars(11).orig_index = 29;
M_.aux_vars(11).orig_lead_lag = -2;
M_.aux_vars(12).endo_index = 68;
M_.aux_vars(12).type = 1;
M_.aux_vars(12).orig_index = 55;
M_.aux_vars(12).orig_lead_lag = -1;
M_.aux_vars(13).endo_index = 69;
M_.aux_vars(13).type = 1;
M_.aux_vars(13).orig_index = 55;
M_.aux_vars(13).orig_lead_lag = -2;
M_.aux_vars(14).endo_index = 70;
M_.aux_vars(14).type = 1;
M_.aux_vars(14).orig_index = 55;
M_.aux_vars(14).orig_lead_lag = -3;
M_.aux_vars(15).endo_index = 71;
M_.aux_vars(15).type = 1;
M_.aux_vars(15).orig_index = 54;
M_.aux_vars(15).orig_lead_lag = -1;
M_.aux_vars(16).endo_index = 72;
M_.aux_vars(16).type = 1;
M_.aux_vars(16).orig_index = 54;
M_.aux_vars(16).orig_lead_lag = -2;
M_.aux_vars(17).endo_index = 73;
M_.aux_vars(17).type = 1;
M_.aux_vars(17).orig_index = 54;
M_.aux_vars(17).orig_lead_lag = -3;
M_.aux_vars(18).endo_index = 74;
M_.aux_vars(18).type = 1;
M_.aux_vars(18).orig_index = 51;
M_.aux_vars(18).orig_lead_lag = -1;
M_.aux_vars(19).endo_index = 75;
M_.aux_vars(19).type = 1;
M_.aux_vars(19).orig_index = 51;
M_.aux_vars(19).orig_lead_lag = -2;
M_.aux_vars(20).endo_index = 76;
M_.aux_vars(20).type = 1;
M_.aux_vars(20).orig_index = 51;
M_.aux_vars(20).orig_lead_lag = -3;
M_.aux_vars(21).endo_index = 77;
M_.aux_vars(21).type = 1;
M_.aux_vars(21).orig_index = 53;
M_.aux_vars(21).orig_lead_lag = -1;
M_.aux_vars(22).endo_index = 78;
M_.aux_vars(22).type = 1;
M_.aux_vars(22).orig_index = 53;
M_.aux_vars(22).orig_lead_lag = -2;
M_.aux_vars(23).endo_index = 79;
M_.aux_vars(23).type = 1;
M_.aux_vars(23).orig_index = 53;
M_.aux_vars(23).orig_lead_lag = -3;
M_.Sigma_e = zeros(11, 11);
M_.Correlation_matrix = eye(11, 11);
M_.H = 0;
M_.Correlation_matrix_ME = 1;
M_.sigma_e_is_diagonal = 1;
M_.det_shocks = [];
options_.block=0;
options_.bytecode=0;
options_.use_dll=0;
M_.hessian_eq_zero = 0;
erase_compiled_function('NK_CW09_static');
erase_compiled_function('NK_CW09_dynamic');
M_.orig_eq_nbr = 56;
M_.eq_nbr = 79;
M_.ramsey_eq_nbr = 0;
M_.set_auxiliary_variables = exist(['./' M_.fname '_set_auxiliary_variables.m'], 'file') == 2;
M_.lead_lag_incidence = [
 1 34 0;
 0 35 0;
 0 36 113;
 0 37 114;
 0 38 115;
 0 39 0;
 0 40 0;
 0 41 116;
 0 42 117;
 2 43 0;
 3 44 0;
 4 45 0;
 5 46 0;
 0 47 0;
 6 48 0;
 7 49 0;
 8 50 0;
 9 51 0;
 10 52 0;
 11 53 0;
 12 54 0;
 13 55 0;
 0 56 0;
 0 57 0;
 0 58 0;
 0 59 0;
 0 60 0;
 0 61 0;
 14 62 0;
 0 63 0;
 0 64 0;
 0 65 0;
 0 66 0;
 0 67 0;
 15 68 0;
 0 69 0;
 0 70 0;
 0 71 0;
 0 72 0;
 0 73 0;
 0 74 0;
 0 75 0;
 0 76 0;
 0 77 0;
 0 78 0;
 0 79 0;
 0 80 0;
 0 81 0;
 0 82 0;
 0 83 0;
 16 84 0;
 0 85 0;
 17 86 118;
 18 87 119;
 19 88 120;
 0 89 0;
 0 90 121;
 0 91 122;
 0 92 123;
 0 93 124;
 0 94 125;
 0 95 126;
 0 96 127;
 0 97 128;
 0 98 129;
 20 99 0;
 21 100 0;
 22 101 0;
 23 102 0;
 24 103 0;
 25 104 0;
 26 105 0;
 27 106 0;
 28 107 0;
 29 108 0;
 30 109 0;
 31 110 0;
 32 111 0;
 33 112 0;]';
M_.nstatic = 32;
M_.nfwrd   = 14;
M_.npred   = 30;
M_.nboth   = 3;
M_.nsfwrd   = 17;
M_.nspred   = 33;
M_.ndynamic   = 47;
M_.equations_tags = {
};
M_.static_and_dynamic_models_differ = 0;
M_.exo_names_orig_ord = [1:11];
M_.maximum_lag = 1;
M_.maximum_lead = 1;
M_.maximum_endo_lag = 1;
M_.maximum_endo_lead = 1;
oo_.steady_state = zeros(79, 1);
M_.maximum_exo_lag = 0;
M_.maximum_exo_lead = 0;
oo_.exo_steady_state = zeros(11, 1);
M_.params = NaN(97, 1);
M_.NNZDerivatives = [254; 204; -1];
M_.params( 54 ) = 0.9;
rho_C_bar_s = M_.params( 54 );
M_.params( 55 ) = 0.9;
rho_C_bar_b = M_.params( 55 );
M_.params( 56 ) = 0.9;
rho_G = M_.params( 56 );
M_.params( 57 ) = 0.9;
rho_H_bar = M_.params( 57 );
M_.params( 58 ) = 0.9;
rho_mu_w = M_.params( 58 );
M_.params( 59 ) = 0.9;
rho_tau = M_.params( 59 );
M_.params( 60 ) = 0.6;
rho_epsilon_m = M_.params( 60 );
M_.params( 61 ) = 0.9;
rho_Xi_tilde = M_.params( 61 );
M_.params( 62 ) = 0.9;
rho_chi_tilde = M_.params( 62 );
M_.params( 63 ) = 0.9;
rho_Z = M_.params( 63 );
M_.params( 66 ) = 0.9;
rho_b_g_ar = M_.params( 66 );
M_.params( 38 ) = 0.5;
pi_b = M_.params( 38 );
M_.params( 39 ) = 0.5;
pi_s = M_.params( 39 );
M_.params( 44 ) = 0.66;
alpha = M_.params( 44 );
M_.params( 43 ) = 7.666666666666667;
theta = M_.params( 43 );
M_.params( 42 ) = 0.1048;
nu = M_.params( 42 );
M_.params( 36 ) = 1.333333333333333;
phi = M_.params( 36 );
M_.params( 41 ) = M_.params(36)*(1+M_.params(42))-1;
omega_y = M_.params( 41 );
M_.params( 37 ) = 0.975;
delta = M_.params( 37 );
M_.params( 52 ) = 2;
phi_pi = M_.params( 52 );
M_.params( 53 ) = 0.25;
phi_y = M_.params( 53 );
M_.params( 51 ) = 0;
varchi = M_.params( 51 );
M_.params( 72 ) = 0.7;
s_c = M_.params( 72 );
M_.params( 97 ) = 6.25;
sigma_bar = M_.params( 97 );
M_.params( 40 ) = M_.params(43)/(M_.params(43)-1);
mu_p = M_.params( 40 );
M_.params( 45 ) = 13.8019;
sigma_b = M_.params( 45 );
M_.params( 46 ) = 2.7604;
sigma_s = M_.params( 46 );
M_.params( 64 ) = 0;
rho_b_g = M_.params( 64 );
M_.params( 68 ) = 3.2;
rho_b = M_.params( 68 );
M_.params( 67 ) = 1;
Y_bar = M_.params( 67 );
M_.params( 73 ) = 0.01;
i_d_bar = M_.params( 73 );
M_.params( 81 ) = 0.2;
tau_bar = M_.params( 81 );
M_.params( 93 ) = M_.params(68)*M_.params(67);
b_bar = M_.params( 93 );
M_.params( 74 ) = 0.004962931573204044;
omega_bar = M_.params( 74 );
M_.params( 50 ) = 1+0.25*(1+M_.params(74))/M_.params(74);
eta = M_.params( 50 );
M_.params( 35 ) = (1+M_.params(37)+M_.params(74)*(M_.params(37)+(1-M_.params(37))*M_.params(38))-sqrt((1+M_.params(37)+M_.params(74)*(M_.params(37)+(1-M_.params(37))*M_.params(38)))^2-(1+M_.params(74))*4*M_.params(37)))/((1+M_.params(74))*2*M_.params(37))/(1+M_.params(73));
beta = M_.params( 35 );
M_.params( 65 ) = (1-(1+M_.params(73))*M_.params(35)*(M_.params(37)+(1-M_.params(37))*(1-M_.params(38))))/(M_.params(38)*(1-M_.params(37))*(1+M_.params(73))*M_.params(35));
Omega_bar = M_.params( 65 );
M_.params( 48 ) = (0.5+0.5*M_.params(65)^((-1)/M_.params(42)))^M_.params(42);
psi_s = M_.params( 48 );
M_.params( 47 ) = M_.params(65)*M_.params(48);
psi_b = M_.params( 47 );
M_.params( 49 ) = (M_.params(38)*M_.params(47)^((-1)/M_.params(42))+(1-M_.params(38))*M_.params(48)^((-1)/M_.params(42)))^M_.params(42);
psi = M_.params( 49 );
M_.params( 96 ) = (M_.params(68)*(1+M_.params(74)*M_.params(38)-(1+M_.params(73))*(1+M_.params(74))*M_.params(37))+M_.params(38)*M_.params(64)*(1-M_.params(37)*(1+M_.params(73))))/(M_.params(38)*(1-M_.params(38)));
s_diff = M_.params( 96 );
M_.params( 70 ) = M_.params(72)-M_.params(38)*M_.params(96);
s_s = M_.params( 70 );
M_.params( 69 ) = M_.params(72)+(1-M_.params(38))*M_.params(96);
s_b = M_.params( 69 );
M_.params( 75 ) = M_.params(74)*M_.params(93)/M_.params(50);
s_Xi = M_.params( 75 );
M_.params( 71 ) = 1-M_.params(72)-M_.params(75);
s_g = M_.params( 71 );
M_.params( 90 ) = 1;
Pi_bar = M_.params( 90 );
M_.params( 91 ) = 1;
Delta_bar = M_.params( 91 );
M_.params( 80 ) = 1;
mu_w_bar = M_.params( 80 );
M_.params( 88 ) = 1;
H_bar_bar = M_.params( 88 );
M_.params( 89 ) = 1;
Z_bar = M_.params( 89 );
M_.params( 95 ) = M_.params(67)*M_.params(71);
G_bar = M_.params( 95 );
M_.params( 94 ) = M_.params(64);
b_g_bar = M_.params( 94 );
M_.params( 76 ) = M_.params(74)/(M_.params(50)*M_.params(93)^(M_.params(50)-1));
Xi_tilde_bar = M_.params( 76 );
M_.params( 79 ) = 0;
chi_tilde_bar = M_.params( 79 );
M_.params( 83 ) = M_.params(40)*(1+M_.params(41))*M_.params(80)*M_.params(88)^(-M_.params(42))*(1/M_.params(89))^(1+M_.params(41))/((1-M_.params(81))*((1-M_.params(38))*M_.params(48)^((-1)/M_.params(42))+M_.params(47)^((-1)/M_.params(42))*M_.params(38)*M_.params(65)^(1/M_.params(42)))^M_.params(42));
lambda_s_bar = M_.params( 83 );
M_.params( 82 ) = M_.params(65)*M_.params(83);
lambda_b_bar = M_.params( 82 );
M_.params( 77 ) = M_.params(67)*M_.params(69)*M_.params(82)^M_.params(45);
C_bar_b_bar = M_.params( 77 );
M_.params( 78 ) = M_.params(67)*M_.params(70)*M_.params(83)^M_.params(46);
C_bar_s_bar = M_.params( 78 );
M_.params( 87 ) = M_.params(38)*M_.params(82)+(1-M_.params(38))*M_.params(83);
Lambda_bar = M_.params( 87 );
M_.params( 86 ) = M_.params(49)*(M_.params(38)*(M_.params(82)/M_.params(47))^(1/M_.params(42))+(1-M_.params(38))*(M_.params(83)/M_.params(48))^(1/M_.params(42)))^M_.params(42);
lambda_tilde_bar = M_.params( 86 );
M_.params( 85 ) = (1-M_.params(81))*M_.params(87)/(1-M_.params(35)*M_.params(44));
F_bar = M_.params( 85 );
M_.params( 84 ) = (1/M_.params(89))^(1+M_.params(41))*M_.params(88)^(-M_.params(42))*M_.params(80)*M_.params(49)*(1+M_.params(41))*M_.params(40)*M_.params(87)*M_.params(86)^(-1)/(1-M_.params(35)*M_.params(44));
K_bar = M_.params( 84 );
M_.params( 92 ) = M_.params(77)*M_.params(82)^(-M_.params(45))-M_.params(78)*M_.params(83)^(-M_.params(46))-M_.params(80)*M_.params(88)^(-M_.params(42))*((M_.params(82)/M_.params(47))^(1/M_.params(42))-(M_.params(83)/M_.params(48))^(1/M_.params(42)))*(M_.params(86)/M_.params(49))^((-(1+M_.params(42)))/M_.params(42))*(M_.params(67)/M_.params(89))^(1+M_.params(41))*M_.params(91);
B_bar = M_.params( 92 );
thispath = cd;                                                           
cd('..');                                                                
load policy_param.mat;                                                   
for i=1:33                                                               
deep_parameter_name = M_.param_names(i,:);                           
eval(['M_.params(i)  = ' deep_parameter_name ' ;'])                  
end                                                                      
cd(thispath);                                                            
M_.params( 34 ) = 1;
coffispol = M_.params( 34 );
%
% INITVAL instructions
%
options_.initval_file = 0;
oo_.steady_state( 21 ) = M_.params(89);
oo_.steady_state( 17 ) = M_.params(88);
oo_.steady_state( 1 ) = M_.params(73);
oo_.steady_state( 18 ) = M_.params(80);
oo_.steady_state( 19 ) = M_.params(81);
oo_.steady_state( 4 ) = M_.params(83);
oo_.steady_state( 3 ) = M_.params(82);
oo_.steady_state( 24 ) = M_.params(87);
oo_.steady_state( 25 ) = M_.params(86);
oo_.steady_state( 5 ) = M_.params(90);
oo_.steady_state( 7 ) = M_.params(67);
oo_.steady_state( 8 ) = M_.params(84);
oo_.steady_state( 9 ) = M_.params(85);
oo_.steady_state( 10 ) = M_.params(91);
oo_.steady_state( 11 ) = M_.params(93);
oo_.steady_state( 12 ) = M_.params(95);
oo_.steady_state( 13 ) = M_.params(79);
oo_.steady_state( 20 ) = M_.params(74);
oo_.steady_state( 16 ) = M_.params(77);
oo_.steady_state( 15 ) = M_.params(78);
oo_.steady_state( 22 ) = M_.params(94);
oo_.steady_state( 23 ) = M_.params(92);
oo_.steady_state(57)=oo_.steady_state(53);
oo_.steady_state(58)=oo_.steady_state(57);
oo_.steady_state(59)=oo_.steady_state(58);
oo_.steady_state(60)=oo_.steady_state(54);
oo_.steady_state(61)=oo_.steady_state(60);
oo_.steady_state(62)=oo_.steady_state(61);
oo_.steady_state(63)=oo_.steady_state(55);
oo_.steady_state(64)=oo_.steady_state(63);
oo_.steady_state(65)=oo_.steady_state(64);
oo_.steady_state(66)=oo_.steady_state(29);
oo_.steady_state(67)=oo_.steady_state(66);
oo_.steady_state(68)=oo_.steady_state(55);
oo_.steady_state(69)=oo_.steady_state(68);
oo_.steady_state(70)=oo_.steady_state(69);
oo_.steady_state(71)=oo_.steady_state(54);
oo_.steady_state(72)=oo_.steady_state(71);
oo_.steady_state(73)=oo_.steady_state(72);
oo_.steady_state(74)=oo_.steady_state(51);
oo_.steady_state(75)=oo_.steady_state(74);
oo_.steady_state(76)=oo_.steady_state(75);
oo_.steady_state(77)=oo_.steady_state(53);
oo_.steady_state(78)=oo_.steady_state(77);
oo_.steady_state(79)=oo_.steady_state(78);
if M_.exo_nbr > 0
	oo_.exo_simul = ones(M_.maximum_lag,1)*oo_.exo_steady_state';
end
if M_.exo_det_nbr > 0
	oo_.exo_det_simul = ones(M_.maximum_lag,1)*oo_.exo_det_steady_state';
end
%
% SHOCKS instructions
%
M_.exo_det_length = 0;
M_.Sigma_e(1, 1) = M_.params(78)^2;
M_.Sigma_e(2, 2) = M_.params(77)^2;
M_.Sigma_e(3, 3) = 1;
M_.Sigma_e(4, 4) = 1;
M_.Sigma_e(5, 5) = 1;
M_.Sigma_e(6, 6) = 0.0001;
M_.Sigma_e(7, 7) = 1;
M_.Sigma_e(8, 8) = 1;
M_.Sigma_e(9, 9) = 16;
M_.Sigma_e(11, 11) = 1;
save('NK_CW09_results.mat', 'oo_', 'M_', 'options_');
if exist('estim_params_', 'var') == 1
  save('NK_CW09_results.mat', 'estim_params_', '-append');
end
if exist('bayestopt_', 'var') == 1
  save('NK_CW09_results.mat', 'bayestopt_', '-append');
end
if exist('dataset_', 'var') == 1
  save('NK_CW09_results.mat', 'dataset_', '-append');
end
if exist('estimation_info', 'var') == 1
  save('NK_CW09_results.mat', 'estimation_info', '-append');
end
if exist('dataset_info', 'var') == 1
  save('NK_CW09_results.mat', 'dataset_info', '-append');
end
if exist('oo_recursive_', 'var') == 1
  save('NK_CW09_results.mat', 'oo_recursive_', '-append');
end


disp(['Total computing time : ' dynsec2hms(toc(tic0)) ]);
if ~isempty(lastwarn)
  disp('Note: warning(s) encountered in MATLAB/Octave code')
end
diary off
