%
% Status : main Dynare file 
%
% Warning : this file is generated automatically by Dynare
%           from model file (.mod)

tic;
global M_ oo_ options_ ys0_ ex0_ estimation_info
options_ = [];
M_.fname = 'EA_SW03';
%
% Some global variables initialization
%
global_initialization;
diary off;
diary('EA_SW03.log');
M_.exo_names = 'ea';
M_.exo_names_tex = 'ea';
M_.exo_names_long = 'ea';
M_.exo_names = char(M_.exo_names, 'eb');
M_.exo_names_tex = char(M_.exo_names_tex, 'eb');
M_.exo_names_long = char(M_.exo_names_long, 'eb');
M_.exo_names = char(M_.exo_names, 'els');
M_.exo_names_tex = char(M_.exo_names_tex, 'els');
M_.exo_names_long = char(M_.exo_names_long, 'els');
M_.exo_names = char(M_.exo_names, 'eqs');
M_.exo_names_tex = char(M_.exo_names_tex, 'eqs');
M_.exo_names_long = char(M_.exo_names_long, 'eqs');
M_.exo_names = char(M_.exo_names, 'eps');
M_.exo_names_tex = char(M_.exo_names_tex, 'eps');
M_.exo_names_long = char(M_.exo_names_long, 'eps');
M_.exo_names = char(M_.exo_names, 'eas');
M_.exo_names_tex = char(M_.exo_names_tex, 'eas');
M_.exo_names_long = char(M_.exo_names_long, 'eas');
M_.exo_names = char(M_.exo_names, 'econs');
M_.exo_names_tex = char(M_.exo_names_tex, 'econs');
M_.exo_names_long = char(M_.exo_names_long, 'econs');
M_.exo_names = char(M_.exo_names, 'einv');
M_.exo_names_tex = char(M_.exo_names_tex, 'einv');
M_.exo_names_long = char(M_.exo_names_long, 'einv');
M_.exo_names = char(M_.exo_names, 'ey');
M_.exo_names_tex = char(M_.exo_names_tex, 'ey');
M_.exo_names_long = char(M_.exo_names_long, 'ey');
M_.exo_names = char(M_.exo_names, 'elab');
M_.exo_names_tex = char(M_.exo_names_tex, 'elab');
M_.exo_names_long = char(M_.exo_names_long, 'elab');
M_.exo_names = char(M_.exo_names, 'epinf');
M_.exo_names_tex = char(M_.exo_names_tex, 'epinf');
M_.exo_names_long = char(M_.exo_names_long, 'epinf');
M_.exo_names = char(M_.exo_names, 'ew');
M_.exo_names_tex = char(M_.exo_names_tex, 'ew');
M_.exo_names_long = char(M_.exo_names_long, 'ew');
M_.exo_names = char(M_.exo_names, 'em');
M_.exo_names_tex = char(M_.exo_names_tex, 'em');
M_.exo_names_long = char(M_.exo_names_long, 'em');
M_.exo_names = char(M_.exo_names, 'interest_');
M_.exo_names_tex = char(M_.exo_names_tex, 'interest\_');
M_.exo_names_long = char(M_.exo_names_long, 'interest_');
M_.exo_names = char(M_.exo_names, 'fiscal_');
M_.exo_names_tex = char(M_.exo_names_tex, 'fiscal\_');
M_.exo_names_long = char(M_.exo_names_long, 'fiscal_');
M_.endo_names = 'mcf';
M_.endo_names_tex = 'mcf';
M_.endo_names_long = 'mcf';
M_.endo_names = char(M_.endo_names, 'zcapf');
M_.endo_names_tex = char(M_.endo_names_tex, 'zcapf');
M_.endo_names_long = char(M_.endo_names_long, 'zcapf');
M_.endo_names = char(M_.endo_names, 'rkf');
M_.endo_names_tex = char(M_.endo_names_tex, 'rkf');
M_.endo_names_long = char(M_.endo_names_long, 'rkf');
M_.endo_names = char(M_.endo_names, 'kf');
M_.endo_names_tex = char(M_.endo_names_tex, 'kf');
M_.endo_names_long = char(M_.endo_names_long, 'kf');
M_.endo_names = char(M_.endo_names, 'pkf');
M_.endo_names_tex = char(M_.endo_names_tex, 'pkf');
M_.endo_names_long = char(M_.endo_names_long, 'pkf');
M_.endo_names = char(M_.endo_names, 'muf');
M_.endo_names_tex = char(M_.endo_names_tex, 'muf');
M_.endo_names_long = char(M_.endo_names_long, 'muf');
M_.endo_names = char(M_.endo_names, 'cf');
M_.endo_names_tex = char(M_.endo_names_tex, 'cf');
M_.endo_names_long = char(M_.endo_names_long, 'cf');
M_.endo_names = char(M_.endo_names, 'invef');
M_.endo_names_tex = char(M_.endo_names_tex, 'invef');
M_.endo_names_long = char(M_.endo_names_long, 'invef');
M_.endo_names = char(M_.endo_names, 'yf');
M_.endo_names_tex = char(M_.endo_names_tex, 'yf');
M_.endo_names_long = char(M_.endo_names_long, 'yf');
M_.endo_names = char(M_.endo_names, 'labf');
M_.endo_names_tex = char(M_.endo_names_tex, 'labf');
M_.endo_names_long = char(M_.endo_names_long, 'labf');
M_.endo_names = char(M_.endo_names, 'pinff');
M_.endo_names_tex = char(M_.endo_names_tex, 'pinff');
M_.endo_names_long = char(M_.endo_names_long, 'pinff');
M_.endo_names = char(M_.endo_names, 'wf');
M_.endo_names_tex = char(M_.endo_names_tex, 'wf');
M_.endo_names_long = char(M_.endo_names_long, 'wf');
M_.endo_names = char(M_.endo_names, 'pf');
M_.endo_names_tex = char(M_.endo_names_tex, 'pf');
M_.endo_names_long = char(M_.endo_names_long, 'pf');
M_.endo_names = char(M_.endo_names, 'emplf');
M_.endo_names_tex = char(M_.endo_names_tex, 'emplf');
M_.endo_names_long = char(M_.endo_names_long, 'emplf');
M_.endo_names = char(M_.endo_names, 'rrf');
M_.endo_names_tex = char(M_.endo_names_tex, 'rrf');
M_.endo_names_long = char(M_.endo_names_long, 'rrf');
M_.endo_names = char(M_.endo_names, 'effortf');
M_.endo_names_tex = char(M_.endo_names_tex, 'effortf');
M_.endo_names_long = char(M_.endo_names_long, 'effortf');
M_.endo_names = char(M_.endo_names, 'rf');
M_.endo_names_tex = char(M_.endo_names_tex, 'rf');
M_.endo_names_long = char(M_.endo_names_long, 'rf');
M_.endo_names = char(M_.endo_names, 'mc');
M_.endo_names_tex = char(M_.endo_names_tex, 'mc');
M_.endo_names_long = char(M_.endo_names_long, 'mc');
M_.endo_names = char(M_.endo_names, 'zcap');
M_.endo_names_tex = char(M_.endo_names_tex, 'zcap');
M_.endo_names_long = char(M_.endo_names_long, 'zcap');
M_.endo_names = char(M_.endo_names, 'rk');
M_.endo_names_tex = char(M_.endo_names_tex, 'rk');
M_.endo_names_long = char(M_.endo_names_long, 'rk');
M_.endo_names = char(M_.endo_names, 'k');
M_.endo_names_tex = char(M_.endo_names_tex, 'k');
M_.endo_names_long = char(M_.endo_names_long, 'k');
M_.endo_names = char(M_.endo_names, 'pk');
M_.endo_names_tex = char(M_.endo_names_tex, 'pk');
M_.endo_names_long = char(M_.endo_names_long, 'pk');
M_.endo_names = char(M_.endo_names, 'mu');
M_.endo_names_tex = char(M_.endo_names_tex, 'mu');
M_.endo_names_long = char(M_.endo_names_long, 'mu');
M_.endo_names = char(M_.endo_names, 'c');
M_.endo_names_tex = char(M_.endo_names_tex, 'c');
M_.endo_names_long = char(M_.endo_names_long, 'c');
M_.endo_names = char(M_.endo_names, 'inve');
M_.endo_names_tex = char(M_.endo_names_tex, 'inve');
M_.endo_names_long = char(M_.endo_names_long, 'inve');
M_.endo_names = char(M_.endo_names, 'y');
M_.endo_names_tex = char(M_.endo_names_tex, 'y');
M_.endo_names_long = char(M_.endo_names_long, 'y');
M_.endo_names = char(M_.endo_names, 'lab');
M_.endo_names_tex = char(M_.endo_names_tex, 'lab');
M_.endo_names_long = char(M_.endo_names_long, 'lab');
M_.endo_names = char(M_.endo_names, 'pinf');
M_.endo_names_tex = char(M_.endo_names_tex, 'pinf');
M_.endo_names_long = char(M_.endo_names_long, 'pinf');
M_.endo_names = char(M_.endo_names, 'w');
M_.endo_names_tex = char(M_.endo_names_tex, 'w');
M_.endo_names_long = char(M_.endo_names_long, 'w');
M_.endo_names = char(M_.endo_names, 'p');
M_.endo_names_tex = char(M_.endo_names_tex, 'p');
M_.endo_names_long = char(M_.endo_names_long, 'p');
M_.endo_names = char(M_.endo_names, 'empl');
M_.endo_names_tex = char(M_.endo_names_tex, 'empl');
M_.endo_names_long = char(M_.endo_names_long, 'empl');
M_.endo_names = char(M_.endo_names, 'ww');
M_.endo_names_tex = char(M_.endo_names_tex, 'ww');
M_.endo_names_long = char(M_.endo_names_long, 'ww');
M_.endo_names = char(M_.endo_names, 'effort');
M_.endo_names_tex = char(M_.endo_names_tex, 'effort');
M_.endo_names_long = char(M_.endo_names_long, 'effort');
M_.endo_names = char(M_.endo_names, 'pinf4');
M_.endo_names_tex = char(M_.endo_names_tex, 'pinf4');
M_.endo_names_long = char(M_.endo_names_long, 'pinf4');
M_.endo_names = char(M_.endo_names, 'r');
M_.endo_names_tex = char(M_.endo_names_tex, 'r');
M_.endo_names_long = char(M_.endo_names_long, 'r');
M_.endo_names = char(M_.endo_names, 'dr');
M_.endo_names_tex = char(M_.endo_names_tex, 'dr');
M_.endo_names_long = char(M_.endo_names_long, 'dr');
M_.endo_names = char(M_.endo_names, 'pinfLAG1');
M_.endo_names_tex = char(M_.endo_names_tex, 'pinfLAG1');
M_.endo_names_long = char(M_.endo_names_long, 'pinfLAG1');
M_.endo_names = char(M_.endo_names, 'pinfLAG2');
M_.endo_names_tex = char(M_.endo_names_tex, 'pinfLAG2');
M_.endo_names_long = char(M_.endo_names_long, 'pinfLAG2');
M_.endo_names = char(M_.endo_names, 'ygap');
M_.endo_names_tex = char(M_.endo_names_tex, 'ygap');
M_.endo_names_long = char(M_.endo_names_long, 'ygap');
M_.endo_names = char(M_.endo_names, 'a');
M_.endo_names_tex = char(M_.endo_names_tex, 'a');
M_.endo_names_long = char(M_.endo_names_long, 'a');
M_.endo_names = char(M_.endo_names, 'as');
M_.endo_names_tex = char(M_.endo_names_tex, 'as');
M_.endo_names_long = char(M_.endo_names_long, 'as');
M_.endo_names = char(M_.endo_names, 'b');
M_.endo_names_tex = char(M_.endo_names_tex, 'b');
M_.endo_names_long = char(M_.endo_names_long, 'b');
M_.endo_names = char(M_.endo_names, 'g');
M_.endo_names_tex = char(M_.endo_names_tex, 'g');
M_.endo_names_long = char(M_.endo_names_long, 'g');
M_.endo_names = char(M_.endo_names, 'ls');
M_.endo_names_tex = char(M_.endo_names_tex, 'ls');
M_.endo_names_long = char(M_.endo_names_long, 'ls');
M_.endo_names = char(M_.endo_names, 'qs');
M_.endo_names_tex = char(M_.endo_names_tex, 'qs');
M_.endo_names_long = char(M_.endo_names_long, 'qs');
M_.endo_names = char(M_.endo_names, 'ps');
M_.endo_names_tex = char(M_.endo_names_tex, 'ps');
M_.endo_names_long = char(M_.endo_names_long, 'ps');
M_.endo_names = char(M_.endo_names, 'ms');
M_.endo_names_tex = char(M_.endo_names_tex, 'ms');
M_.endo_names_long = char(M_.endo_names_long, 'ms');
M_.endo_names = char(M_.endo_names, 'scons');
M_.endo_names_tex = char(M_.endo_names_tex, 'scons');
M_.endo_names_long = char(M_.endo_names_long, 'scons');
M_.endo_names = char(M_.endo_names, 'sinv');
M_.endo_names_tex = char(M_.endo_names_tex, 'sinv');
M_.endo_names_long = char(M_.endo_names_long, 'sinv');
M_.endo_names = char(M_.endo_names, 'sy');
M_.endo_names_tex = char(M_.endo_names_tex, 'sy');
M_.endo_names_long = char(M_.endo_names_long, 'sy');
M_.endo_names = char(M_.endo_names, 'slab');
M_.endo_names_tex = char(M_.endo_names_tex, 'slab');
M_.endo_names_long = char(M_.endo_names_long, 'slab');
M_.endo_names = char(M_.endo_names, 'spinf');
M_.endo_names_tex = char(M_.endo_names_tex, 'spinf');
M_.endo_names_long = char(M_.endo_names_long, 'spinf');
M_.endo_names = char(M_.endo_names, 'sw');
M_.endo_names_tex = char(M_.endo_names_tex, 'sw');
M_.endo_names_long = char(M_.endo_names_long, 'sw');
M_.endo_names = char(M_.endo_names, 'kpf');
M_.endo_names_tex = char(M_.endo_names_tex, 'kpf');
M_.endo_names_long = char(M_.endo_names_long, 'kpf');
M_.endo_names = char(M_.endo_names, 'habf');
M_.endo_names_tex = char(M_.endo_names_tex, 'habf');
M_.endo_names_long = char(M_.endo_names_long, 'habf');
M_.endo_names = char(M_.endo_names, 'kp');
M_.endo_names_tex = char(M_.endo_names_tex, 'kp');
M_.endo_names_long = char(M_.endo_names_long, 'kp');
M_.endo_names = char(M_.endo_names, 'hab');
M_.endo_names_tex = char(M_.endo_names_tex, 'hab');
M_.endo_names_long = char(M_.endo_names_long, 'hab');
M_.endo_names = char(M_.endo_names, 'one');
M_.endo_names_tex = char(M_.endo_names_tex, 'one');
M_.endo_names_long = char(M_.endo_names_long, 'one');
M_.endo_names = char(M_.endo_names, 'eg');
M_.endo_names_tex = char(M_.endo_names_tex, 'eg');
M_.endo_names_long = char(M_.endo_names_long, 'eg');
M_.endo_names = char(M_.endo_names, 'interest');
M_.endo_names_tex = char(M_.endo_names_tex, 'interest');
M_.endo_names_long = char(M_.endo_names_long, 'interest');
M_.endo_names = char(M_.endo_names, 'inflation');
M_.endo_names_tex = char(M_.endo_names_tex, 'inflation');
M_.endo_names_long = char(M_.endo_names_long, 'inflation');
M_.endo_names = char(M_.endo_names, 'inflationq');
M_.endo_names_tex = char(M_.endo_names_tex, 'inflationq');
M_.endo_names_long = char(M_.endo_names_long, 'inflationq');
M_.endo_names = char(M_.endo_names, 'outputgap');
M_.endo_names_tex = char(M_.endo_names_tex, 'outputgap');
M_.endo_names_long = char(M_.endo_names_long, 'outputgap');
M_.endo_names = char(M_.endo_names, 'output');
M_.endo_names_tex = char(M_.endo_names_tex, 'output');
M_.endo_names_long = char(M_.endo_names_long, 'output');
M_.endo_names = char(M_.endo_names, 'fispol');
M_.endo_names_tex = char(M_.endo_names_tex, 'fispol');
M_.endo_names_long = char(M_.endo_names_long, 'fispol');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_72');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_72');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_72');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_76');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_76');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_76');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_80');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_80');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_80');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_107');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_107');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_107');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_111');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_111');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_111');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_115');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_115');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_115');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_142');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_142');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_142');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_146');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_146');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_146');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_150');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_150');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_150');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_63_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_63\_1');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_63_1');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_63_2');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_63\_2');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_63_2');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_63_3');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_63\_3');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_63_3');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_62_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_62\_1');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_62_1');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_62_2');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_62\_2');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_62_2');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_62_3');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_62\_3');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_62_3');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_59_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_59\_1');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_59_1');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_59_2');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_59\_2');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_59_2');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_59_3');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_59\_3');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_59_3');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_61_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_61\_1');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_61_1');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_61_2');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_61\_2');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_61_2');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_61_3');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_61\_3');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_61_3');
M_.param_names = 'cofintintb1';
M_.param_names_tex = 'cofintintb1';
M_.param_names_long = 'cofintintb1';
M_.param_names = char(M_.param_names, 'cofintintb2');
M_.param_names_tex = char(M_.param_names_tex, 'cofintintb2');
M_.param_names_long = char(M_.param_names_long, 'cofintintb2');
M_.param_names = char(M_.param_names, 'cofintintb3');
M_.param_names_tex = char(M_.param_names_tex, 'cofintintb3');
M_.param_names_long = char(M_.param_names_long, 'cofintintb3');
M_.param_names = char(M_.param_names, 'cofintintb4');
M_.param_names_tex = char(M_.param_names_tex, 'cofintintb4');
M_.param_names_long = char(M_.param_names_long, 'cofintintb4');
M_.param_names = char(M_.param_names, 'cofintinf0');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinf0');
M_.param_names_long = char(M_.param_names_long, 'cofintinf0');
M_.param_names = char(M_.param_names, 'cofintinfb1');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinfb1');
M_.param_names_long = char(M_.param_names_long, 'cofintinfb1');
M_.param_names = char(M_.param_names, 'cofintinfb2');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinfb2');
M_.param_names_long = char(M_.param_names_long, 'cofintinfb2');
M_.param_names = char(M_.param_names, 'cofintinfb3');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinfb3');
M_.param_names_long = char(M_.param_names_long, 'cofintinfb3');
M_.param_names = char(M_.param_names, 'cofintinfb4');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinfb4');
M_.param_names_long = char(M_.param_names_long, 'cofintinfb4');
M_.param_names = char(M_.param_names, 'cofintinff1');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinff1');
M_.param_names_long = char(M_.param_names_long, 'cofintinff1');
M_.param_names = char(M_.param_names, 'cofintinff2');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinff2');
M_.param_names_long = char(M_.param_names_long, 'cofintinff2');
M_.param_names = char(M_.param_names, 'cofintinff3');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinff3');
M_.param_names_long = char(M_.param_names_long, 'cofintinff3');
M_.param_names = char(M_.param_names, 'cofintinff4');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinff4');
M_.param_names_long = char(M_.param_names_long, 'cofintinff4');
M_.param_names = char(M_.param_names, 'cofintout');
M_.param_names_tex = char(M_.param_names_tex, 'cofintout');
M_.param_names_long = char(M_.param_names_long, 'cofintout');
M_.param_names = char(M_.param_names, 'cofintoutb1');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutb1');
M_.param_names_long = char(M_.param_names_long, 'cofintoutb1');
M_.param_names = char(M_.param_names, 'cofintoutb2');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutb2');
M_.param_names_long = char(M_.param_names_long, 'cofintoutb2');
M_.param_names = char(M_.param_names, 'cofintoutb3');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutb3');
M_.param_names_long = char(M_.param_names_long, 'cofintoutb3');
M_.param_names = char(M_.param_names, 'cofintoutb4');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutb4');
M_.param_names_long = char(M_.param_names_long, 'cofintoutb4');
M_.param_names = char(M_.param_names, 'cofintoutf1');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutf1');
M_.param_names_long = char(M_.param_names_long, 'cofintoutf1');
M_.param_names = char(M_.param_names, 'cofintoutf2');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutf2');
M_.param_names_long = char(M_.param_names_long, 'cofintoutf2');
M_.param_names = char(M_.param_names, 'cofintoutf3');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutf3');
M_.param_names_long = char(M_.param_names_long, 'cofintoutf3');
M_.param_names = char(M_.param_names, 'cofintoutf4');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutf4');
M_.param_names_long = char(M_.param_names_long, 'cofintoutf4');
M_.param_names = char(M_.param_names, 'cofintoutp');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutp');
M_.param_names_long = char(M_.param_names_long, 'cofintoutp');
M_.param_names = char(M_.param_names, 'cofintoutpb1');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpb1');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpb1');
M_.param_names = char(M_.param_names, 'cofintoutpb2');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpb2');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpb2');
M_.param_names = char(M_.param_names, 'cofintoutpb3');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpb3');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpb3');
M_.param_names = char(M_.param_names, 'cofintoutpb4');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpb4');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpb4');
M_.param_names = char(M_.param_names, 'cofintoutpf1');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpf1');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpf1');
M_.param_names = char(M_.param_names, 'cofintoutpf2');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpf2');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpf2');
M_.param_names = char(M_.param_names, 'cofintoutpf3');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpf3');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpf3');
M_.param_names = char(M_.param_names, 'cofintoutpf4');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpf4');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpf4');
M_.param_names = char(M_.param_names, 'std_r_');
M_.param_names_tex = char(M_.param_names_tex, 'std\_r\_');
M_.param_names_long = char(M_.param_names_long, 'std_r_');
M_.param_names = char(M_.param_names, 'std_r_quart');
M_.param_names_tex = char(M_.param_names_tex, 'std\_r\_quart');
M_.param_names_long = char(M_.param_names_long, 'std_r_quart');
M_.param_names = char(M_.param_names, 'coffispol');
M_.param_names_tex = char(M_.param_names_tex, 'coffispol');
M_.param_names_long = char(M_.param_names_long, 'coffispol');
M_.param_names = char(M_.param_names, 'calfa');
M_.param_names_tex = char(M_.param_names_tex, 'calfa');
M_.param_names_long = char(M_.param_names_long, 'calfa');
M_.param_names = char(M_.param_names, 'ctou');
M_.param_names_tex = char(M_.param_names_tex, 'ctou');
M_.param_names_long = char(M_.param_names_long, 'ctou');
M_.param_names = char(M_.param_names, 'cbeta');
M_.param_names_tex = char(M_.param_names_tex, 'cbeta');
M_.param_names_long = char(M_.param_names_long, 'cbeta');
M_.param_names = char(M_.param_names, 'chab');
M_.param_names_tex = char(M_.param_names_tex, 'chab');
M_.param_names_long = char(M_.param_names_long, 'chab');
M_.param_names = char(M_.param_names, 'ccs');
M_.param_names_tex = char(M_.param_names_tex, 'ccs');
M_.param_names_long = char(M_.param_names_long, 'ccs');
M_.param_names = char(M_.param_names, 'cinvs');
M_.param_names_tex = char(M_.param_names_tex, 'cinvs');
M_.param_names_long = char(M_.param_names_long, 'cinvs');
M_.param_names = char(M_.param_names, 'crelwage');
M_.param_names_tex = char(M_.param_names_tex, 'crelwage');
M_.param_names_long = char(M_.param_names_long, 'crelwage');
M_.param_names = char(M_.param_names, 'chabw');
M_.param_names_tex = char(M_.param_names_tex, 'chabw');
M_.param_names_long = char(M_.param_names_long, 'chabw');
M_.param_names = char(M_.param_names, 'clabeff');
M_.param_names_tex = char(M_.param_names_tex, 'clabeff');
M_.param_names_long = char(M_.param_names_long, 'clabeff');
M_.param_names = char(M_.param_names, 'chlab');
M_.param_names_tex = char(M_.param_names_tex, 'chlab');
M_.param_names_long = char(M_.param_names_long, 'chlab');
M_.param_names = char(M_.param_names, 'csadjcost');
M_.param_names_tex = char(M_.param_names_tex, 'csadjcost');
M_.param_names_long = char(M_.param_names_long, 'csadjcost');
M_.param_names = char(M_.param_names, 'csigma');
M_.param_names_tex = char(M_.param_names_tex, 'csigma');
M_.param_names_long = char(M_.param_names_long, 'csigma');
M_.param_names = char(M_.param_names, 'chabb');
M_.param_names_tex = char(M_.param_names_tex, 'chabb');
M_.param_names_long = char(M_.param_names_long, 'chabb');
M_.param_names = char(M_.param_names, 'cprobw');
M_.param_names_tex = char(M_.param_names_tex, 'cprobw');
M_.param_names_long = char(M_.param_names_long, 'cprobw');
M_.param_names = char(M_.param_names, 'clandaw');
M_.param_names_tex = char(M_.param_names_tex, 'clandaw');
M_.param_names_long = char(M_.param_names_long, 'clandaw');
M_.param_names = char(M_.param_names, 'csigl');
M_.param_names_tex = char(M_.param_names_tex, 'csigl');
M_.param_names_long = char(M_.param_names_long, 'csigl');
M_.param_names = char(M_.param_names, 'cprobp');
M_.param_names_tex = char(M_.param_names_tex, 'cprobp');
M_.param_names_long = char(M_.param_names_long, 'cprobp');
M_.param_names = char(M_.param_names, 'cindw');
M_.param_names_tex = char(M_.param_names_tex, 'cindw');
M_.param_names_long = char(M_.param_names_long, 'cindw');
M_.param_names = char(M_.param_names, 'cindp');
M_.param_names_tex = char(M_.param_names_tex, 'cindp');
M_.param_names_long = char(M_.param_names_long, 'cindp');
M_.param_names = char(M_.param_names, 'cfc');
M_.param_names_tex = char(M_.param_names_tex, 'cfc');
M_.param_names_long = char(M_.param_names_long, 'cfc');
M_.param_names = char(M_.param_names, 'cinvdyn');
M_.param_names_tex = char(M_.param_names_tex, 'cinvdyn');
M_.param_names_long = char(M_.param_names_long, 'cinvdyn');
M_.param_names = char(M_.param_names, 'czcap');
M_.param_names_tex = char(M_.param_names_tex, 'czcap');
M_.param_names_long = char(M_.param_names_long, 'czcap');
M_.param_names = char(M_.param_names, 'csadjlab');
M_.param_names_tex = char(M_.param_names_tex, 'csadjlab');
M_.param_names_long = char(M_.param_names_long, 'csadjlab');
M_.param_names = char(M_.param_names, 'crpi');
M_.param_names_tex = char(M_.param_names_tex, 'crpi');
M_.param_names_long = char(M_.param_names_long, 'crpi');
M_.param_names = char(M_.param_names, 'crdpi');
M_.param_names_tex = char(M_.param_names_tex, 'crdpi');
M_.param_names_long = char(M_.param_names_long, 'crdpi');
M_.param_names = char(M_.param_names, 'crr');
M_.param_names_tex = char(M_.param_names_tex, 'crr');
M_.param_names_long = char(M_.param_names_long, 'crr');
M_.param_names = char(M_.param_names, 'cry');
M_.param_names_tex = char(M_.param_names_tex, 'cry');
M_.param_names_long = char(M_.param_names_long, 'cry');
M_.param_names = char(M_.param_names, 'crdy');
M_.param_names_tex = char(M_.param_names_tex, 'crdy');
M_.param_names_long = char(M_.param_names_long, 'crdy');
M_.param_names = char(M_.param_names, 'crhoa');
M_.param_names_tex = char(M_.param_names_tex, 'crhoa');
M_.param_names_long = char(M_.param_names_long, 'crhoa');
M_.param_names = char(M_.param_names, 'crhoas');
M_.param_names_tex = char(M_.param_names_tex, 'crhoas');
M_.param_names_long = char(M_.param_names_long, 'crhoas');
M_.param_names = char(M_.param_names, 'crhob');
M_.param_names_tex = char(M_.param_names_tex, 'crhob');
M_.param_names_long = char(M_.param_names_long, 'crhob');
M_.param_names = char(M_.param_names, 'crhog');
M_.param_names_tex = char(M_.param_names_tex, 'crhog');
M_.param_names_long = char(M_.param_names_long, 'crhog');
M_.param_names = char(M_.param_names, 'crhols');
M_.param_names_tex = char(M_.param_names_tex, 'crhols');
M_.param_names_long = char(M_.param_names_long, 'crhols');
M_.param_names = char(M_.param_names, 'crhoqs');
M_.param_names_tex = char(M_.param_names_tex, 'crhoqs');
M_.param_names_long = char(M_.param_names_long, 'crhoqs');
M_.param_names = char(M_.param_names, 'crhops');
M_.param_names_tex = char(M_.param_names_tex, 'crhops');
M_.param_names_long = char(M_.param_names_long, 'crhops');
M_.param_names = char(M_.param_names, 'crhoms');
M_.param_names_tex = char(M_.param_names_tex, 'crhoms');
M_.param_names_long = char(M_.param_names_long, 'crhoms');
M_.param_names = char(M_.param_names, 'crhoy');
M_.param_names_tex = char(M_.param_names_tex, 'crhoy');
M_.param_names_long = char(M_.param_names_long, 'crhoy');
M_.param_names = char(M_.param_names, 'crhocons');
M_.param_names_tex = char(M_.param_names_tex, 'crhocons');
M_.param_names_long = char(M_.param_names_long, 'crhocons');
M_.param_names = char(M_.param_names, 'crhoinv');
M_.param_names_tex = char(M_.param_names_tex, 'crhoinv');
M_.param_names_long = char(M_.param_names_long, 'crhoinv');
M_.param_names = char(M_.param_names, 'crhopinf');
M_.param_names_tex = char(M_.param_names_tex, 'crhopinf');
M_.param_names_long = char(M_.param_names_long, 'crhopinf');
M_.param_names = char(M_.param_names, 'crhow');
M_.param_names_tex = char(M_.param_names_tex, 'crhow');
M_.param_names_long = char(M_.param_names_long, 'crhow');
M_.param_names = char(M_.param_names, 'crholab');
M_.param_names_tex = char(M_.param_names_tex, 'crholab');
M_.param_names_long = char(M_.param_names_long, 'crholab');
M_.param_names = char(M_.param_names, 'cscaleea');
M_.param_names_tex = char(M_.param_names_tex, 'cscaleea');
M_.param_names_long = char(M_.param_names_long, 'cscaleea');
M_.param_names = char(M_.param_names, 'cscaleeas');
M_.param_names_tex = char(M_.param_names_tex, 'cscaleeas');
M_.param_names_long = char(M_.param_names_long, 'cscaleeas');
M_.param_names = char(M_.param_names, 'cscaleeb');
M_.param_names_tex = char(M_.param_names_tex, 'cscaleeb');
M_.param_names_long = char(M_.param_names_long, 'cscaleeb');
M_.param_names = char(M_.param_names, 'cscaleeg');
M_.param_names_tex = char(M_.param_names_tex, 'cscaleeg');
M_.param_names_long = char(M_.param_names_long, 'cscaleeg');
M_.param_names = char(M_.param_names, 'cscaleels');
M_.param_names_tex = char(M_.param_names_tex, 'cscaleels');
M_.param_names_long = char(M_.param_names_long, 'cscaleels');
M_.param_names = char(M_.param_names, 'cscaleeqs');
M_.param_names_tex = char(M_.param_names_tex, 'cscaleeqs');
M_.param_names_long = char(M_.param_names_long, 'cscaleeqs');
M_.param_names = char(M_.param_names, 'cscaleeps');
M_.param_names_tex = char(M_.param_names_tex, 'cscaleeps');
M_.param_names_long = char(M_.param_names_long, 'cscaleeps');
M_.param_names = char(M_.param_names, 'cscaleem');
M_.param_names_tex = char(M_.param_names_tex, 'cscaleem');
M_.param_names_long = char(M_.param_names_long, 'cscaleem');
M_.param_names = char(M_.param_names, 'cscaleecons');
M_.param_names_tex = char(M_.param_names_tex, 'cscaleecons');
M_.param_names_long = char(M_.param_names_long, 'cscaleecons');
M_.param_names = char(M_.param_names, 'cscaleeinv');
M_.param_names_tex = char(M_.param_names_tex, 'cscaleeinv');
M_.param_names_long = char(M_.param_names_long, 'cscaleeinv');
M_.param_names = char(M_.param_names, 'cscaleey');
M_.param_names_tex = char(M_.param_names_tex, 'cscaleey');
M_.param_names_long = char(M_.param_names_long, 'cscaleey');
M_.param_names = char(M_.param_names, 'cscaleelab');
M_.param_names_tex = char(M_.param_names_tex, 'cscaleelab');
M_.param_names_long = char(M_.param_names_long, 'cscaleelab');
M_.param_names = char(M_.param_names, 'cscaleepinf');
M_.param_names_tex = char(M_.param_names_tex, 'cscaleepinf');
M_.param_names_long = char(M_.param_names_long, 'cscaleepinf');
M_.param_names = char(M_.param_names, 'cscaleew');
M_.param_names_tex = char(M_.param_names_tex, 'cscaleew');
M_.param_names_long = char(M_.param_names_long, 'cscaleew');
M_.param_names = char(M_.param_names, 'cscaleer');
M_.param_names_tex = char(M_.param_names_tex, 'cscaleer');
M_.param_names_long = char(M_.param_names_long, 'cscaleer');
M_.exo_det_nbr = 0;
M_.exo_nbr = 15;
M_.endo_nbr = 86;
M_.param_nbr = 91;
M_.orig_endo_nbr = 65;
M_.aux_vars(1).endo_index = 66;
M_.aux_vars(1).type = 0;
M_.aux_vars(2).endo_index = 67;
M_.aux_vars(2).type = 0;
M_.aux_vars(3).endo_index = 68;
M_.aux_vars(3).type = 0;
M_.aux_vars(4).endo_index = 69;
M_.aux_vars(4).type = 0;
M_.aux_vars(5).endo_index = 70;
M_.aux_vars(5).type = 0;
M_.aux_vars(6).endo_index = 71;
M_.aux_vars(6).type = 0;
M_.aux_vars(7).endo_index = 72;
M_.aux_vars(7).type = 0;
M_.aux_vars(8).endo_index = 73;
M_.aux_vars(8).type = 0;
M_.aux_vars(9).endo_index = 74;
M_.aux_vars(9).type = 0;
M_.aux_vars(10).endo_index = 75;
M_.aux_vars(10).type = 1;
M_.aux_vars(10).orig_index = 64;
M_.aux_vars(10).orig_lead_lag = -1;
M_.aux_vars(11).endo_index = 76;
M_.aux_vars(11).type = 1;
M_.aux_vars(11).orig_index = 64;
M_.aux_vars(11).orig_lead_lag = -2;
M_.aux_vars(12).endo_index = 77;
M_.aux_vars(12).type = 1;
M_.aux_vars(12).orig_index = 64;
M_.aux_vars(12).orig_lead_lag = -3;
M_.aux_vars(13).endo_index = 78;
M_.aux_vars(13).type = 1;
M_.aux_vars(13).orig_index = 63;
M_.aux_vars(13).orig_lead_lag = -1;
M_.aux_vars(14).endo_index = 79;
M_.aux_vars(14).type = 1;
M_.aux_vars(14).orig_index = 63;
M_.aux_vars(14).orig_lead_lag = -2;
M_.aux_vars(15).endo_index = 80;
M_.aux_vars(15).type = 1;
M_.aux_vars(15).orig_index = 63;
M_.aux_vars(15).orig_lead_lag = -3;
M_.aux_vars(16).endo_index = 81;
M_.aux_vars(16).type = 1;
M_.aux_vars(16).orig_index = 60;
M_.aux_vars(16).orig_lead_lag = -1;
M_.aux_vars(17).endo_index = 82;
M_.aux_vars(17).type = 1;
M_.aux_vars(17).orig_index = 60;
M_.aux_vars(17).orig_lead_lag = -2;
M_.aux_vars(18).endo_index = 83;
M_.aux_vars(18).type = 1;
M_.aux_vars(18).orig_index = 60;
M_.aux_vars(18).orig_lead_lag = -3;
M_.aux_vars(19).endo_index = 84;
M_.aux_vars(19).type = 1;
M_.aux_vars(19).orig_index = 62;
M_.aux_vars(19).orig_lead_lag = -1;
M_.aux_vars(20).endo_index = 85;
M_.aux_vars(20).type = 1;
M_.aux_vars(20).orig_index = 62;
M_.aux_vars(20).orig_lead_lag = -2;
M_.aux_vars(21).endo_index = 86;
M_.aux_vars(21).type = 1;
M_.aux_vars(21).orig_index = 62;
M_.aux_vars(21).orig_lead_lag = -3;
M_.Sigma_e = zeros(15, 15);
M_.Correlation_matrix = eye(15, 15);
M_.H = 0;
M_.Correlation_matrix_ME = 1;
M_.sigma_e_is_diagonal = 1;
options_.linear = 1;
options_.block=0;
options_.bytecode=0;
options_.use_dll=0;
erase_compiled_function('EA_SW03_static');
erase_compiled_function('EA_SW03_dynamic');
M_.lead_lag_incidence = [
 0 47 0;
 0 48 0;
 0 49 133;
 0 50 0;
 0 51 134;
 0 52 135;
 1 53 0;
 2 54 136;
 0 55 0;
 0 56 0;
 0 57 137;
 0 58 0;
 0 59 0;
 3 60 138;
 0 61 0;
 0 62 0;
 0 63 0;
 0 64 0;
 0 65 0;
 0 66 139;
 0 67 0;
 0 68 140;
 0 69 141;
 4 70 0;
 5 71 142;
 0 72 0;
 6 73 0;
 7 74 143;
 8 75 144;
 0 76 0;
 9 77 145;
 0 78 0;
 0 79 0;
 0 80 0;
 10 81 0;
 0 82 0;
 11 83 0;
 12 84 0;
 0 85 0;
 13 86 146;
 14 87 0;
 15 88 0;
 16 89 0;
 17 90 0;
 18 91 0;
 19 92 0;
 20 93 0;
 21 94 0;
 22 95 0;
 23 96 0;
 24 97 0;
 25 98 0;
 26 99 0;
 27 100 0;
 28 101 0;
 29 102 0;
 30 103 0;
 0 104 0;
 0 105 0;
 31 106 0;
 0 107 0;
 32 108 147;
 33 109 148;
 34 110 149;
 0 111 0;
 0 112 150;
 0 113 151;
 0 114 152;
 0 115 153;
 0 116 154;
 0 117 155;
 0 118 156;
 0 119 157;
 0 120 158;
 35 121 0;
 36 122 0;
 37 123 0;
 38 124 0;
 39 125 0;
 40 126 0;
 41 127 0;
 42 128 0;
 43 129 0;
 44 130 0;
 45 131 0;
 46 132 0;]';
M_.nstatic = 24;
M_.nfwrd   = 16;
M_.npred   = 36;
M_.nboth   = 10;
M_.nsfwrd   = 26;
M_.nspred   = 46;
M_.ndynamic   = 62;
M_.equations_tags = {
};
M_.static_and_dynamic_models_differ = 0;
M_.exo_names_orig_ord = [1:15];
M_.maximum_lag = 1;
M_.maximum_lead = 1;
M_.maximum_endo_lag = 1;
M_.maximum_endo_lead = 1;
oo_.steady_state = zeros(86, 1);
M_.maximum_exo_lag = 0;
M_.maximum_exo_lead = 0;
oo_.exo_steady_state = zeros(15, 1);
M_.params = NaN(91, 1);
M_.NNZDerivatives = zeros(3, 1);
M_.NNZDerivatives(1) = 294;
M_.NNZDerivatives(2) = 0;
M_.NNZDerivatives(3) = -1;
M_.params( 35 ) = 0.3;
calfa = M_.params( 35 );
M_.params( 36 ) = 0.025;
ctou = M_.params( 36 );
M_.params( 37 ) = 0.99;
cbeta = M_.params( 37 );
M_.params( 38 ) = 0;
chab = M_.params( 38 );
M_.params( 39 ) = 0.6;
ccs = M_.params( 39 );
M_.params( 40 ) = 0.22;
cinvs = M_.params( 40 );
M_.params( 41 ) = 0;
crelwage = M_.params( 41 );
M_.params( 42 ) = 0;
chabw = M_.params( 42 );
M_.params( 43 ) = 0;
clabeff = M_.params( 43 );
M_.params( 44 ) = 0;
chlab = M_.params( 44 );
M_.params( 45 ) = 6.7711;
csadjcost = M_.params( 45 );
M_.params( 46 ) = 1.3533;
csigma = M_.params( 46 );
M_.params( 47 ) = 0.5732;
chabb = M_.params( 47 );
M_.params( 48 ) = 0.7367;
cprobw = M_.params( 48 );
M_.params( 49 ) = 1.5;
clandaw = M_.params( 49 );
M_.params( 50 ) = 2.3995;
csigl = M_.params( 50 );
M_.params( 51 ) = 0.9082;
cprobp = M_.params( 51 );
M_.params( 52 ) = 0.7627;
cindw = M_.params( 52 );
M_.params( 53 ) = 0.4694;
cindp = M_.params( 53 );
M_.params( 54 ) = 1.4077;
cfc = M_.params( 54 );
M_.params( 55 ) = 1;
cinvdyn = M_.params( 55 );
M_.params( 56 ) = 0.1690;
czcap = M_.params( 56 );
M_.params( 57 ) = 0.5990;
csadjlab = M_.params( 57 );
M_.params( 58 ) = 1.6841;
crpi = M_.params( 58 );
M_.params( 59 ) = 0.1398;
crdpi = M_.params( 59 );
M_.params( 60 ) = 0.9613;
crr = M_.params( 60 );
M_.params( 61 ) = 0.0988;
cry = M_.params( 61 );
M_.params( 62 ) = 0.1586;
crdy = M_.params( 62 );
M_.params( 63 ) = 0.8232;
crhoa = M_.params( 63 );
M_.params( 64 ) = 0.9238;
crhoas = M_.params( 64 );
M_.params( 65 ) = 0.8545;
crhob = M_.params( 65 );
M_.params( 66 ) = 0.9493;
crhog = M_.params( 66 );
M_.params( 67 ) = 0.8894;
crhols = M_.params( 67 );
M_.params( 68 ) = 0.9273;
crhoqs = M_.params( 68 );
M_.params( 69 ) = 0;
crhops = M_.params( 69 );
M_.params( 70 ) = 0;
crhoms = M_.params( 70 );
M_.params( 71 ) = 0;
crhoy = M_.params( 71 );
M_.params( 72 ) = 0;
crhocons = M_.params( 72 );
M_.params( 73 ) = 0;
crhoinv = M_.params( 73 );
M_.params( 74 ) = 0;
crhopinf = M_.params( 74 );
M_.params( 75 ) = 0;
crhow = M_.params( 75 );
M_.params( 76 ) = 0;
crholab = M_.params( 76 );
M_.params( 77 ) = 0.5978;
cscaleea = M_.params( 77 );
M_.params( 78 ) = 0.0165;
cscaleeas = M_.params( 78 );
M_.params( 79 ) = 0.3361;
cscaleeb = M_.params( 79 );
M_.params( 80 ) = 0.3247;
cscaleeg = M_.params( 80 );
M_.params( 81 ) = 3.5197;
cscaleels = M_.params( 81 );
M_.params( 82 ) = 0.0851;
cscaleeqs = M_.params( 82 );
M_.params( 83 ) = 0;
cscaleeps = M_.params( 83 );
M_.params( 84 ) = 0.0808;
cscaleem = M_.params( 84 );
M_.params( 85 ) = 0;
cscaleecons = M_.params( 85 );
M_.params( 86 ) = 0.6043;
cscaleeinv = M_.params( 86 );
M_.params( 87 ) = 0;
cscaleey = M_.params( 87 );
M_.params( 88 ) = 0;
cscaleelab = M_.params( 88 );
M_.params( 89 ) = 0.1602;
cscaleepinf = M_.params( 89 );
M_.params( 90 ) = 0.2892;
cscaleew = M_.params( 90 );
M_.params( 91 ) = 0.081;
cscaleer = M_.params( 91 );
thispath = cd;                                                           
cd('..');                                                                
load policy_param.mat;                                                   
for i=1:33                                                               
deep_parameter_name = M_.param_names(i,:);                           
eval(['M_.params(i)  = ' deep_parameter_name ' ;'])                  
end                                                                      
cd(thispath);                                                            
M_.params( 34 ) = 1/M_.params(80);
coffispol = M_.params( 34 );
%
% SHOCKS instructions
%
make_ex_;
M_.exo_det_length = 0;
M_.Sigma_e(1, 1) = 1;
M_.Sigma_e(2, 2) = 1;
M_.Sigma_e(3, 3) = 1;
M_.Sigma_e(4, 4) = 1;
M_.Sigma_e(6, 6) = 1;
M_.Sigma_e(7, 7) = 1;
M_.Sigma_e(8, 8) = 1;
M_.Sigma_e(9, 9) = 1;
M_.Sigma_e(10, 10) = 1;
M_.Sigma_e(11, 11) = 1;
M_.Sigma_e(12, 12) = 1;
M_.Sigma_e(13, 13) = 1;
M_.Sigma_e(15, 15) = M_.params(80)^2;
save('EA_SW03_results.mat', 'oo_', 'M_', 'options_');
if exist('estim_params_', 'var') == 1
  save('EA_SW03_results.mat', 'estim_params_', '-append');
end
if exist('bayestopt_', 'var') == 1
  save('EA_SW03_results.mat', 'bayestopt_', '-append');
end
if exist('dataset_', 'var') == 1
  save('EA_SW03_results.mat', 'dataset_', '-append');
end
if exist('estimation_info', 'var') == 1
  save('EA_SW03_results.mat', 'estimation_info', '-append');
end


disp(['Total computing time : ' dynsec2hms(toc) ]);
if ~isempty(lastwarn)
  disp('Note: warning(s) encountered in MATLAB/Octave code')
end
diary off
