%
% Status : main Dynare file
%
% Warning : this file is generated automatically by Dynare
%           from model file (.mod)

if isoctave || matlab_ver_less_than('8.6')
    clear all
else
    clearvars -global
    clear_persistent_variables(fileparts(which('dynare')), false)
end
tic0 = tic;
% Save empty dates and dseries objects in memory.
dates('initialize');
dseries('initialize');
% Define global variables.
global M_ options_ oo_ estim_params_ bayestopt_ dataset_ dataset_info estimation_info ys0_ ex0_
options_ = [];
M_.fname = 'US_ACELt';
M_.dynare_version = '4.5.6';
oo_.dynare_version = '4.5.6';
options_.dynare_version = '4.5.6';
%
% Some global variables initialization
%
global_initialization;
diary off;
diary('US_ACELt.log');
M_.exo_names = 'epsilon_M_';
M_.exo_names_tex = 'epsilon\_M\_';
M_.exo_names_long = 'epsilon_M_';
M_.exo_names = char(M_.exo_names, 'eps_muz_');
M_.exo_names_tex = char(M_.exo_names_tex, 'eps\_muz\_');
M_.exo_names_long = char(M_.exo_names_long, 'eps_muz_');
M_.exo_names = char(M_.exo_names, 'eps_muups_');
M_.exo_names_tex = char(M_.exo_names_tex, 'eps\_muups\_');
M_.exo_names_long = char(M_.exo_names_long, 'eps_muups_');
M_.exo_names = char(M_.exo_names, 'epsilon_t_');
M_.exo_names_tex = char(M_.exo_names_tex, 'epsilon\_t\_');
M_.exo_names_long = char(M_.exo_names_long, 'epsilon_t_');
M_.exo_names = char(M_.exo_names, 'interest_');
M_.exo_names_tex = char(M_.exo_names_tex, 'interest\_');
M_.exo_names_long = char(M_.exo_names_long, 'interest_');
M_.endo_names = 'c_t';
M_.endo_names_tex = 'c\_t';
M_.endo_names_long = 'c_t';
M_.endo_names = char(M_.endo_names, 'wtilde_t');
M_.endo_names_tex = char(M_.endo_names_tex, 'wtilde\_t');
M_.endo_names_long = char(M_.endo_names_long, 'wtilde_t');
M_.endo_names = char(M_.endo_names, 'lambda_zstar_t');
M_.endo_names_tex = char(M_.endo_names_tex, 'lambda\_zstar\_t');
M_.endo_names_long = char(M_.endo_names_long, 'lambda_zstar_t');
M_.endo_names = char(M_.endo_names, 'm_t');
M_.endo_names_tex = char(M_.endo_names_tex, 'm\_t');
M_.endo_names_long = char(M_.endo_names_long, 'm_t');
M_.endo_names = char(M_.endo_names, 'pi_t');
M_.endo_names_tex = char(M_.endo_names_tex, 'pi\_t');
M_.endo_names_long = char(M_.endo_names_long, 'pi_t');
M_.endo_names = char(M_.endo_names, 'x_t');
M_.endo_names_tex = char(M_.endo_names_tex, 'x\_t');
M_.endo_names_long = char(M_.endo_names_long, 'x_t');
M_.endo_names = char(M_.endo_names, 's_t');
M_.endo_names_tex = char(M_.endo_names_tex, 's\_t');
M_.endo_names_long = char(M_.endo_names_long, 's_t');
M_.endo_names = char(M_.endo_names, 'i_t');
M_.endo_names_tex = char(M_.endo_names_tex, 'i\_t');
M_.endo_names_long = char(M_.endo_names_long, 'i_t');
M_.endo_names = char(M_.endo_names, 'h_t');
M_.endo_names_tex = char(M_.endo_names_tex, 'h\_t');
M_.endo_names_long = char(M_.endo_names_long, 'h_t');
M_.endo_names = char(M_.endo_names, 'kbar_t1');
M_.endo_names_tex = char(M_.endo_names_tex, 'kbar\_t1');
M_.endo_names_long = char(M_.endo_names_long, 'kbar_t1');
M_.endo_names = char(M_.endo_names, 'q_t');
M_.endo_names_tex = char(M_.endo_names_tex, 'q\_t');
M_.endo_names_long = char(M_.endo_names_long, 'q_t');
M_.endo_names = char(M_.endo_names, 'ytilde_t');
M_.endo_names_tex = char(M_.endo_names_tex, 'ytilde\_t');
M_.endo_names_long = char(M_.endo_names_long, 'ytilde_t');
M_.endo_names = char(M_.endo_names, 'R_t');
M_.endo_names_tex = char(M_.endo_names_tex, 'R\_t');
M_.endo_names_long = char(M_.endo_names_long, 'R_t');
M_.endo_names = char(M_.endo_names, 'mutilde_t');
M_.endo_names_tex = char(M_.endo_names_tex, 'mutilde\_t');
M_.endo_names_long = char(M_.endo_names_long, 'mutilde_t');
M_.endo_names = char(M_.endo_names, 'rhotilde_t');
M_.endo_names_tex = char(M_.endo_names_tex, 'rhotilde\_t');
M_.endo_names_long = char(M_.endo_names_long, 'rhotilde_t');
M_.endo_names = char(M_.endo_names, 'u_t');
M_.endo_names_tex = char(M_.endo_names_tex, 'u\_t');
M_.endo_names_long = char(M_.endo_names_long, 'u_t');
M_.endo_names = char(M_.endo_names, 'x_M_t');
M_.endo_names_tex = char(M_.endo_names_tex, 'x\_M\_t');
M_.endo_names_long = char(M_.endo_names_long, 'x_M_t');
M_.endo_names = char(M_.endo_names, 'eps_M_t');
M_.endo_names_tex = char(M_.endo_names_tex, 'eps\_M\_t');
M_.endo_names_long = char(M_.endo_names_long, 'eps_M_t');
M_.endo_names = char(M_.endo_names, 'mu_z_t');
M_.endo_names_tex = char(M_.endo_names_tex, 'mu\_z\_t');
M_.endo_names_long = char(M_.endo_names_long, 'mu_z_t');
M_.endo_names = char(M_.endo_names, 'eps_muz_t');
M_.endo_names_tex = char(M_.endo_names_tex, 'eps\_muz\_t');
M_.endo_names_long = char(M_.endo_names_long, 'eps_muz_t');
M_.endo_names = char(M_.endo_names, 'x_z_t');
M_.endo_names_tex = char(M_.endo_names_tex, 'x\_z\_t');
M_.endo_names_long = char(M_.endo_names_long, 'x_z_t');
M_.endo_names = char(M_.endo_names, 'mu_ups_t');
M_.endo_names_tex = char(M_.endo_names_tex, 'mu\_ups\_t');
M_.endo_names_long = char(M_.endo_names_long, 'mu_ups_t');
M_.endo_names = char(M_.endo_names, 'eps_muups_t');
M_.endo_names_tex = char(M_.endo_names_tex, 'eps\_muups\_t');
M_.endo_names_long = char(M_.endo_names_long, 'eps_muups_t');
M_.endo_names = char(M_.endo_names, 'x_ups_t');
M_.endo_names_tex = char(M_.endo_names_tex, 'x\_ups\_t');
M_.endo_names_long = char(M_.endo_names_long, 'x_ups_t');
M_.endo_names = char(M_.endo_names, 'cf_t');
M_.endo_names_tex = char(M_.endo_names_tex, 'cf\_t');
M_.endo_names_long = char(M_.endo_names_long, 'cf_t');
M_.endo_names = char(M_.endo_names, 'wtildef_t');
M_.endo_names_tex = char(M_.endo_names_tex, 'wtildef\_t');
M_.endo_names_long = char(M_.endo_names_long, 'wtildef_t');
M_.endo_names = char(M_.endo_names, 'lambda_zstarf_t');
M_.endo_names_tex = char(M_.endo_names_tex, 'lambda\_zstarf\_t');
M_.endo_names_long = char(M_.endo_names_long, 'lambda_zstarf_t');
M_.endo_names = char(M_.endo_names, 'mf_t');
M_.endo_names_tex = char(M_.endo_names_tex, 'mf\_t');
M_.endo_names_long = char(M_.endo_names_long, 'mf_t');
M_.endo_names = char(M_.endo_names, 'pif_t');
M_.endo_names_tex = char(M_.endo_names_tex, 'pif\_t');
M_.endo_names_long = char(M_.endo_names_long, 'pif_t');
M_.endo_names = char(M_.endo_names, 'xf_t');
M_.endo_names_tex = char(M_.endo_names_tex, 'xf\_t');
M_.endo_names_long = char(M_.endo_names_long, 'xf_t');
M_.endo_names = char(M_.endo_names, 'sf_t');
M_.endo_names_tex = char(M_.endo_names_tex, 'sf\_t');
M_.endo_names_long = char(M_.endo_names_long, 'sf_t');
M_.endo_names = char(M_.endo_names, 'if_t');
M_.endo_names_tex = char(M_.endo_names_tex, 'if\_t');
M_.endo_names_long = char(M_.endo_names_long, 'if_t');
M_.endo_names = char(M_.endo_names, 'hf_t');
M_.endo_names_tex = char(M_.endo_names_tex, 'hf\_t');
M_.endo_names_long = char(M_.endo_names_long, 'hf_t');
M_.endo_names = char(M_.endo_names, 'kbarf_t1');
M_.endo_names_tex = char(M_.endo_names_tex, 'kbarf\_t1');
M_.endo_names_long = char(M_.endo_names_long, 'kbarf_t1');
M_.endo_names = char(M_.endo_names, 'qf_t');
M_.endo_names_tex = char(M_.endo_names_tex, 'qf\_t');
M_.endo_names_long = char(M_.endo_names_long, 'qf_t');
M_.endo_names = char(M_.endo_names, 'ytildef_t');
M_.endo_names_tex = char(M_.endo_names_tex, 'ytildef\_t');
M_.endo_names_long = char(M_.endo_names_long, 'ytildef_t');
M_.endo_names = char(M_.endo_names, 'Rf_t');
M_.endo_names_tex = char(M_.endo_names_tex, 'Rf\_t');
M_.endo_names_long = char(M_.endo_names_long, 'Rf_t');
M_.endo_names = char(M_.endo_names, 'mutildef_t');
M_.endo_names_tex = char(M_.endo_names_tex, 'mutildef\_t');
M_.endo_names_long = char(M_.endo_names_long, 'mutildef_t');
M_.endo_names = char(M_.endo_names, 'rhotildef_t');
M_.endo_names_tex = char(M_.endo_names_tex, 'rhotildef\_t');
M_.endo_names_long = char(M_.endo_names_long, 'rhotildef_t');
M_.endo_names = char(M_.endo_names, 'uf_t');
M_.endo_names_tex = char(M_.endo_names_tex, 'uf\_t');
M_.endo_names_long = char(M_.endo_names_long, 'uf_t');
M_.endo_names = char(M_.endo_names, 'epsilon_t');
M_.endo_names_tex = char(M_.endo_names_tex, 'epsilon\_t');
M_.endo_names_long = char(M_.endo_names_long, 'epsilon_t');
M_.endo_names = char(M_.endo_names, 'interest');
M_.endo_names_tex = char(M_.endo_names_tex, 'interest');
M_.endo_names_long = char(M_.endo_names_long, 'interest');
M_.endo_names = char(M_.endo_names, 'inflation');
M_.endo_names_tex = char(M_.endo_names_tex, 'inflation');
M_.endo_names_long = char(M_.endo_names_long, 'inflation');
M_.endo_names = char(M_.endo_names, 'inflationq');
M_.endo_names_tex = char(M_.endo_names_tex, 'inflationq');
M_.endo_names_long = char(M_.endo_names_long, 'inflationq');
M_.endo_names = char(M_.endo_names, 'outputgap');
M_.endo_names_tex = char(M_.endo_names_tex, 'outputgap');
M_.endo_names_long = char(M_.endo_names_long, 'outputgap');
M_.endo_names = char(M_.endo_names, 'output');
M_.endo_names_tex = char(M_.endo_names_tex, 'output');
M_.endo_names_long = char(M_.endo_names_long, 'output');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_75');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_75');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_75');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_79');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_79');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_79');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_83');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_83');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_83');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_110');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_110');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_110');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_114');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_114');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_114');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_118');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_118');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_118');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_145');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_145');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_145');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_149');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_149');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_149');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_153');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_153');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_153');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_4_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_4\_1');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_4_1');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_4_2');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_4\_2');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_4_2');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_45_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_45\_1');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_45_1');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_45_2');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_45\_2');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_45_2');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_45_3');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_45\_3');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_45_3');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_44_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_44\_1');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_44_1');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_44_2');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_44\_2');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_44_2');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_44_3');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_44\_3');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_44_3');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_41_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_41\_1');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_41_1');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_41_2');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_41\_2');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_41_2');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_41_3');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_41\_3');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_41_3');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_43_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_43\_1');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_43_1');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_43_2');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_43\_2');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_43_2');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_43_3');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_43\_3');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_43_3');
M_.endo_partitions = struct();
M_.param_names = 'cofintintb1';
M_.param_names_tex = 'cofintintb1';
M_.param_names_long = 'cofintintb1';
M_.param_names = char(M_.param_names, 'cofintintb2');
M_.param_names_tex = char(M_.param_names_tex, 'cofintintb2');
M_.param_names_long = char(M_.param_names_long, 'cofintintb2');
M_.param_names = char(M_.param_names, 'cofintintb3');
M_.param_names_tex = char(M_.param_names_tex, 'cofintintb3');
M_.param_names_long = char(M_.param_names_long, 'cofintintb3');
M_.param_names = char(M_.param_names, 'cofintintb4');
M_.param_names_tex = char(M_.param_names_tex, 'cofintintb4');
M_.param_names_long = char(M_.param_names_long, 'cofintintb4');
M_.param_names = char(M_.param_names, 'cofintinf0');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinf0');
M_.param_names_long = char(M_.param_names_long, 'cofintinf0');
M_.param_names = char(M_.param_names, 'cofintinfb1');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinfb1');
M_.param_names_long = char(M_.param_names_long, 'cofintinfb1');
M_.param_names = char(M_.param_names, 'cofintinfb2');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinfb2');
M_.param_names_long = char(M_.param_names_long, 'cofintinfb2');
M_.param_names = char(M_.param_names, 'cofintinfb3');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinfb3');
M_.param_names_long = char(M_.param_names_long, 'cofintinfb3');
M_.param_names = char(M_.param_names, 'cofintinfb4');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinfb4');
M_.param_names_long = char(M_.param_names_long, 'cofintinfb4');
M_.param_names = char(M_.param_names, 'cofintinff1');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinff1');
M_.param_names_long = char(M_.param_names_long, 'cofintinff1');
M_.param_names = char(M_.param_names, 'cofintinff2');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinff2');
M_.param_names_long = char(M_.param_names_long, 'cofintinff2');
M_.param_names = char(M_.param_names, 'cofintinff3');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinff3');
M_.param_names_long = char(M_.param_names_long, 'cofintinff3');
M_.param_names = char(M_.param_names, 'cofintinff4');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinff4');
M_.param_names_long = char(M_.param_names_long, 'cofintinff4');
M_.param_names = char(M_.param_names, 'cofintout');
M_.param_names_tex = char(M_.param_names_tex, 'cofintout');
M_.param_names_long = char(M_.param_names_long, 'cofintout');
M_.param_names = char(M_.param_names, 'cofintoutb1');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutb1');
M_.param_names_long = char(M_.param_names_long, 'cofintoutb1');
M_.param_names = char(M_.param_names, 'cofintoutb2');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutb2');
M_.param_names_long = char(M_.param_names_long, 'cofintoutb2');
M_.param_names = char(M_.param_names, 'cofintoutb3');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutb3');
M_.param_names_long = char(M_.param_names_long, 'cofintoutb3');
M_.param_names = char(M_.param_names, 'cofintoutb4');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutb4');
M_.param_names_long = char(M_.param_names_long, 'cofintoutb4');
M_.param_names = char(M_.param_names, 'cofintoutf1');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutf1');
M_.param_names_long = char(M_.param_names_long, 'cofintoutf1');
M_.param_names = char(M_.param_names, 'cofintoutf2');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutf2');
M_.param_names_long = char(M_.param_names_long, 'cofintoutf2');
M_.param_names = char(M_.param_names, 'cofintoutf3');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutf3');
M_.param_names_long = char(M_.param_names_long, 'cofintoutf3');
M_.param_names = char(M_.param_names, 'cofintoutf4');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutf4');
M_.param_names_long = char(M_.param_names_long, 'cofintoutf4');
M_.param_names = char(M_.param_names, 'cofintoutp');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutp');
M_.param_names_long = char(M_.param_names_long, 'cofintoutp');
M_.param_names = char(M_.param_names, 'cofintoutpb1');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpb1');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpb1');
M_.param_names = char(M_.param_names, 'cofintoutpb2');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpb2');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpb2');
M_.param_names = char(M_.param_names, 'cofintoutpb3');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpb3');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpb3');
M_.param_names = char(M_.param_names, 'cofintoutpb4');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpb4');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpb4');
M_.param_names = char(M_.param_names, 'cofintoutpf1');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpf1');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpf1');
M_.param_names = char(M_.param_names, 'cofintoutpf2');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpf2');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpf2');
M_.param_names = char(M_.param_names, 'cofintoutpf3');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpf3');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpf3');
M_.param_names = char(M_.param_names, 'cofintoutpf4');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpf4');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpf4');
M_.param_names = char(M_.param_names, 'std_r_');
M_.param_names_tex = char(M_.param_names_tex, 'std\_r\_');
M_.param_names_long = char(M_.param_names_long, 'std_r_');
M_.param_names = char(M_.param_names, 'std_r_quart');
M_.param_names_tex = char(M_.param_names_tex, 'std\_r\_quart');
M_.param_names_long = char(M_.param_names_long, 'std_r_quart');
M_.param_names = char(M_.param_names, 'coffispol');
M_.param_names_tex = char(M_.param_names_tex, 'coffispol');
M_.param_names_long = char(M_.param_names_long, 'coffispol');
M_.param_names = char(M_.param_names, 'alpha');
M_.param_names_tex = char(M_.param_names_tex, 'alpha');
M_.param_names_long = char(M_.param_names_long, 'alpha');
M_.param_names = char(M_.param_names, 'b');
M_.param_names_tex = char(M_.param_names_tex, 'b');
M_.param_names_long = char(M_.param_names_long, 'b');
M_.param_names = char(M_.param_names, 'beta');
M_.param_names_tex = char(M_.param_names_tex, 'beta');
M_.param_names_long = char(M_.param_names_long, 'beta');
M_.param_names = char(M_.param_names, 'delta');
M_.param_names_tex = char(M_.param_names_tex, 'delta');
M_.param_names_long = char(M_.param_names_long, 'delta');
M_.param_names = char(M_.param_names, 'eps');
M_.param_names_tex = char(M_.param_names_tex, 'eps');
M_.param_names_long = char(M_.param_names_long, 'eps');
M_.param_names = char(M_.param_names, 'eta');
M_.param_names_tex = char(M_.param_names_tex, 'eta');
M_.param_names_long = char(M_.param_names_long, 'eta');
M_.param_names = char(M_.param_names, 'lambda_f');
M_.param_names_tex = char(M_.param_names_tex, 'lambda\_f');
M_.param_names_long = char(M_.param_names_long, 'lambda_f');
M_.param_names = char(M_.param_names, 'lambda_w');
M_.param_names_tex = char(M_.param_names_tex, 'lambda\_w');
M_.param_names_long = char(M_.param_names_long, 'lambda_w');
M_.param_names = char(M_.param_names, 'mu_ups');
M_.param_names_tex = char(M_.param_names_tex, 'mu\_ups');
M_.param_names_long = char(M_.param_names_long, 'mu_ups');
M_.param_names = char(M_.param_names, 'mu_z');
M_.param_names_tex = char(M_.param_names_tex, 'mu\_z');
M_.param_names_long = char(M_.param_names_long, 'mu_z');
M_.param_names = char(M_.param_names, 'nu');
M_.param_names_tex = char(M_.param_names_tex, 'nu');
M_.param_names_long = char(M_.param_names_long, 'nu');
M_.param_names = char(M_.param_names, 'psi_L');
M_.param_names_tex = char(M_.param_names_tex, 'psi\_L');
M_.param_names_long = char(M_.param_names_long, 'psi_L');
M_.param_names = char(M_.param_names, 'sigma_L');
M_.param_names_tex = char(M_.param_names_tex, 'sigma\_L');
M_.param_names_long = char(M_.param_names_long, 'sigma_L');
M_.param_names = char(M_.param_names, 'x');
M_.param_names_tex = char(M_.param_names_tex, 'x');
M_.param_names_long = char(M_.param_names_long, 'x');
M_.param_names = char(M_.param_names, 'xi_w');
M_.param_names_tex = char(M_.param_names_tex, 'xi\_w');
M_.param_names_long = char(M_.param_names_long, 'xi_w');
M_.param_names = char(M_.param_names, 'V');
M_.param_names_tex = char(M_.param_names_tex, 'V');
M_.param_names_long = char(M_.param_names_long, 'V');
M_.param_names = char(M_.param_names, 'kappa');
M_.param_names_tex = char(M_.param_names_tex, 'kappa');
M_.param_names_long = char(M_.param_names_long, 'kappa');
M_.param_names = char(M_.param_names, 'sigma_a');
M_.param_names_tex = char(M_.param_names_tex, 'sigma\_a');
M_.param_names_long = char(M_.param_names_long, 'sigma_a');
M_.param_names = char(M_.param_names, 'gamma');
M_.param_names_tex = char(M_.param_names_tex, 'gamma');
M_.param_names_long = char(M_.param_names_long, 'gamma');
M_.param_names = char(M_.param_names, 'squig');
M_.param_names_tex = char(M_.param_names_tex, 'squig');
M_.param_names_long = char(M_.param_names_long, 'squig');
M_.param_names = char(M_.param_names, 'vaartheta');
M_.param_names_tex = char(M_.param_names_tex, 'vaartheta');
M_.param_names_long = char(M_.param_names_long, 'vaartheta');
M_.param_names = char(M_.param_names, 'rho_M');
M_.param_names_tex = char(M_.param_names_tex, 'rho\_M');
M_.param_names_long = char(M_.param_names_long, 'rho_M');
M_.param_names = char(M_.param_names, 'theta_M');
M_.param_names_tex = char(M_.param_names_tex, 'theta\_M');
M_.param_names_long = char(M_.param_names_long, 'theta_M');
M_.param_names = char(M_.param_names, 'rho_muz');
M_.param_names_tex = char(M_.param_names_tex, 'rho\_muz');
M_.param_names_long = char(M_.param_names_long, 'rho_muz');
M_.param_names = char(M_.param_names, 'theta_muz');
M_.param_names_tex = char(M_.param_names_tex, 'theta\_muz');
M_.param_names_long = char(M_.param_names_long, 'theta_muz');
M_.param_names = char(M_.param_names, 'c_z');
M_.param_names_tex = char(M_.param_names_tex, 'c\_z');
M_.param_names_long = char(M_.param_names_long, 'c_z');
M_.param_names = char(M_.param_names, 'cp_z');
M_.param_names_tex = char(M_.param_names_tex, 'cp\_z');
M_.param_names_long = char(M_.param_names_long, 'cp_z');
M_.param_names = char(M_.param_names, 'rho_xz');
M_.param_names_tex = char(M_.param_names_tex, 'rho\_xz');
M_.param_names_long = char(M_.param_names_long, 'rho_xz');
M_.param_names = char(M_.param_names, 'rho_muups');
M_.param_names_tex = char(M_.param_names_tex, 'rho\_muups');
M_.param_names_long = char(M_.param_names_long, 'rho_muups');
M_.param_names = char(M_.param_names, 'theta_muups');
M_.param_names_tex = char(M_.param_names_tex, 'theta\_muups');
M_.param_names_long = char(M_.param_names_long, 'theta_muups');
M_.param_names = char(M_.param_names, 'c_ups');
M_.param_names_tex = char(M_.param_names_tex, 'c\_ups');
M_.param_names_long = char(M_.param_names_long, 'c_ups');
M_.param_names = char(M_.param_names, 'cp_ups');
M_.param_names_tex = char(M_.param_names_tex, 'cp\_ups');
M_.param_names_long = char(M_.param_names_long, 'cp_ups');
M_.param_names = char(M_.param_names, 'rho_xups');
M_.param_names_tex = char(M_.param_names_tex, 'rho\_xups');
M_.param_names_long = char(M_.param_names_long, 'rho_xups');
M_.param_names = char(M_.param_names, 'mu_zstar');
M_.param_names_tex = char(M_.param_names_tex, 'mu\_zstar');
M_.param_names_long = char(M_.param_names_long, 'mu_zstar');
M_.param_names = char(M_.param_names, 'rhotilde');
M_.param_names_tex = char(M_.param_names_tex, 'rhotilde');
M_.param_names_long = char(M_.param_names_long, 'rhotilde');
M_.param_names = char(M_.param_names, 'infl');
M_.param_names_tex = char(M_.param_names_tex, 'infl');
M_.param_names_long = char(M_.param_names_long, 'infl');
M_.param_names = char(M_.param_names, 'R');
M_.param_names_tex = char(M_.param_names_tex, 'R');
M_.param_names_long = char(M_.param_names_long, 'R');
M_.param_names = char(M_.param_names, 'eta_pr');
M_.param_names_tex = char(M_.param_names_tex, 'eta\_pr');
M_.param_names_long = char(M_.param_names_long, 'eta_pr');
M_.param_names = char(M_.param_names, 's');
M_.param_names_tex = char(M_.param_names_tex, 's');
M_.param_names_long = char(M_.param_names_long, 's');
M_.param_names = char(M_.param_names, 'R_nu');
M_.param_names_tex = char(M_.param_names_tex, 'R\_nu');
M_.param_names_long = char(M_.param_names_long, 'R_nu');
M_.param_names = char(M_.param_names, 'wtilde');
M_.param_names_tex = char(M_.param_names_tex, 'wtilde');
M_.param_names_long = char(M_.param_names_long, 'wtilde');
M_.param_names = char(M_.param_names, 'h_kbar');
M_.param_names_tex = char(M_.param_names_tex, 'h\_kbar');
M_.param_names_long = char(M_.param_names_long, 'h_kbar');
M_.param_names = char(M_.param_names, 'kbar');
M_.param_names_tex = char(M_.param_names_tex, 'kbar');
M_.param_names_long = char(M_.param_names_long, 'kbar');
M_.param_names = char(M_.param_names, 'h');
M_.param_names_tex = char(M_.param_names_tex, 'h');
M_.param_names_long = char(M_.param_names_long, 'h');
M_.param_names = char(M_.param_names, 'c');
M_.param_names_tex = char(M_.param_names_tex, 'c');
M_.param_names_long = char(M_.param_names_long, 'c');
M_.param_names = char(M_.param_names, 'q');
M_.param_names_tex = char(M_.param_names_tex, 'q');
M_.param_names_long = char(M_.param_names_long, 'q');
M_.param_names = char(M_.param_names, 'm');
M_.param_names_tex = char(M_.param_names_tex, 'm');
M_.param_names_long = char(M_.param_names_long, 'm');
M_.param_names = char(M_.param_names, 'ytilde');
M_.param_names_tex = char(M_.param_names_tex, 'ytilde');
M_.param_names_long = char(M_.param_names_long, 'ytilde');
M_.param_names = char(M_.param_names, 'phi');
M_.param_names_tex = char(M_.param_names_tex, 'phi');
M_.param_names_long = char(M_.param_names_long, 'phi');
M_.param_names = char(M_.param_names, 'sig_eta');
M_.param_names_tex = char(M_.param_names_tex, 'sig\_eta');
M_.param_names_long = char(M_.param_names_long, 'sig_eta');
M_.param_names = char(M_.param_names, 'i');
M_.param_names_tex = char(M_.param_names_tex, 'i');
M_.param_names_long = char(M_.param_names_long, 'i');
M_.param_names = char(M_.param_names, 'lambda_zstar');
M_.param_names_tex = char(M_.param_names_tex, 'lambda\_zstar');
M_.param_names_long = char(M_.param_names_long, 'lambda_zstar');
M_.param_names = char(M_.param_names, 'blewy');
M_.param_names_tex = char(M_.param_names_tex, 'blewy');
M_.param_names_long = char(M_.param_names_long, 'blewy');
M_.param_names = char(M_.param_names, 'b_w');
M_.param_names_tex = char(M_.param_names_tex, 'b\_w');
M_.param_names_long = char(M_.param_names_long, 'b_w');
M_.param_names = char(M_.param_names, 'ETA1');
M_.param_names_tex = char(M_.param_names_tex, 'ETA1');
M_.param_names_long = char(M_.param_names_long, 'ETA1');
M_.param_names = char(M_.param_names, 'ETA2');
M_.param_names_tex = char(M_.param_names_tex, 'ETA2');
M_.param_names_long = char(M_.param_names_long, 'ETA2');
M_.param_names = char(M_.param_names, 'ETA3');
M_.param_names_tex = char(M_.param_names_tex, 'ETA3');
M_.param_names_long = char(M_.param_names_long, 'ETA3');
M_.param_names = char(M_.param_names, 'ETA4');
M_.param_names_tex = char(M_.param_names_tex, 'ETA4');
M_.param_names_long = char(M_.param_names_long, 'ETA4');
M_.param_names = char(M_.param_names, 'ETA5');
M_.param_names_tex = char(M_.param_names_tex, 'ETA5');
M_.param_names_long = char(M_.param_names_long, 'ETA5');
M_.param_names = char(M_.param_names, 'ETA6');
M_.param_names_tex = char(M_.param_names_tex, 'ETA6');
M_.param_names_long = char(M_.param_names_long, 'ETA6');
M_.param_names = char(M_.param_names, 'ETA7');
M_.param_names_tex = char(M_.param_names_tex, 'ETA7');
M_.param_names_long = char(M_.param_names_long, 'ETA7');
M_.param_names = char(M_.param_names, 'ETA8');
M_.param_names_tex = char(M_.param_names_tex, 'ETA8');
M_.param_names_long = char(M_.param_names_long, 'ETA8');
M_.param_names = char(M_.param_names, 'ETA9');
M_.param_names_tex = char(M_.param_names_tex, 'ETA9');
M_.param_names_long = char(M_.param_names_long, 'ETA9');
M_.param_names = char(M_.param_names, 'ETA10');
M_.param_names_tex = char(M_.param_names_tex, 'ETA10');
M_.param_names_long = char(M_.param_names_long, 'ETA10');
M_.param_names = char(M_.param_names, 'bf_w');
M_.param_names_tex = char(M_.param_names_tex, 'bf\_w');
M_.param_names_long = char(M_.param_names_long, 'bf_w');
M_.param_names = char(M_.param_names, 'xif_w');
M_.param_names_tex = char(M_.param_names_tex, 'xif\_w');
M_.param_names_long = char(M_.param_names_long, 'xif_w');
M_.param_names = char(M_.param_names, 'ETA1f');
M_.param_names_tex = char(M_.param_names_tex, 'ETA1f');
M_.param_names_long = char(M_.param_names_long, 'ETA1f');
M_.param_names = char(M_.param_names, 'ETA2f');
M_.param_names_tex = char(M_.param_names_tex, 'ETA2f');
M_.param_names_long = char(M_.param_names_long, 'ETA2f');
M_.param_names = char(M_.param_names, 'ETA3f');
M_.param_names_tex = char(M_.param_names_tex, 'ETA3f');
M_.param_names_long = char(M_.param_names_long, 'ETA3f');
M_.param_names = char(M_.param_names, 'ETA4f');
M_.param_names_tex = char(M_.param_names_tex, 'ETA4f');
M_.param_names_long = char(M_.param_names_long, 'ETA4f');
M_.param_names = char(M_.param_names, 'ETA5f');
M_.param_names_tex = char(M_.param_names_tex, 'ETA5f');
M_.param_names_long = char(M_.param_names_long, 'ETA5f');
M_.param_names = char(M_.param_names, 'ETA6f');
M_.param_names_tex = char(M_.param_names_tex, 'ETA6f');
M_.param_names_long = char(M_.param_names_long, 'ETA6f');
M_.param_names = char(M_.param_names, 'ETA7f');
M_.param_names_tex = char(M_.param_names_tex, 'ETA7f');
M_.param_names_long = char(M_.param_names_long, 'ETA7f');
M_.param_names = char(M_.param_names, 'ETA8f');
M_.param_names_tex = char(M_.param_names_tex, 'ETA8f');
M_.param_names_long = char(M_.param_names_long, 'ETA8f');
M_.param_names = char(M_.param_names, 'ETA9f');
M_.param_names_tex = char(M_.param_names_tex, 'ETA9f');
M_.param_names_long = char(M_.param_names_long, 'ETA9f');
M_.param_names = char(M_.param_names, 'ETA10f');
M_.param_names_tex = char(M_.param_names_tex, 'ETA10f');
M_.param_names_long = char(M_.param_names_long, 'ETA10f');
M_.param_names = char(M_.param_names, 'rho_epsilon');
M_.param_names_tex = char(M_.param_names_tex, 'rho\_epsilon');
M_.param_names_long = char(M_.param_names_long, 'rho_epsilon');
M_.param_partitions = struct();
M_.exo_det_nbr = 0;
M_.exo_nbr = 5;
M_.endo_nbr = 69;
M_.param_nbr = 111;
M_.orig_endo_nbr = 46;
M_.aux_vars(1).endo_index = 47;
M_.aux_vars(1).type = 0;
M_.aux_vars(2).endo_index = 48;
M_.aux_vars(2).type = 0;
M_.aux_vars(3).endo_index = 49;
M_.aux_vars(3).type = 0;
M_.aux_vars(4).endo_index = 50;
M_.aux_vars(4).type = 0;
M_.aux_vars(5).endo_index = 51;
M_.aux_vars(5).type = 0;
M_.aux_vars(6).endo_index = 52;
M_.aux_vars(6).type = 0;
M_.aux_vars(7).endo_index = 53;
M_.aux_vars(7).type = 0;
M_.aux_vars(8).endo_index = 54;
M_.aux_vars(8).type = 0;
M_.aux_vars(9).endo_index = 55;
M_.aux_vars(9).type = 0;
M_.aux_vars(10).endo_index = 56;
M_.aux_vars(10).type = 1;
M_.aux_vars(10).orig_index = 5;
M_.aux_vars(10).orig_lead_lag = -1;
M_.aux_vars(11).endo_index = 57;
M_.aux_vars(11).type = 1;
M_.aux_vars(11).orig_index = 5;
M_.aux_vars(11).orig_lead_lag = -2;
M_.aux_vars(12).endo_index = 58;
M_.aux_vars(12).type = 1;
M_.aux_vars(12).orig_index = 46;
M_.aux_vars(12).orig_lead_lag = -1;
M_.aux_vars(13).endo_index = 59;
M_.aux_vars(13).type = 1;
M_.aux_vars(13).orig_index = 46;
M_.aux_vars(13).orig_lead_lag = -2;
M_.aux_vars(14).endo_index = 60;
M_.aux_vars(14).type = 1;
M_.aux_vars(14).orig_index = 46;
M_.aux_vars(14).orig_lead_lag = -3;
M_.aux_vars(15).endo_index = 61;
M_.aux_vars(15).type = 1;
M_.aux_vars(15).orig_index = 45;
M_.aux_vars(15).orig_lead_lag = -1;
M_.aux_vars(16).endo_index = 62;
M_.aux_vars(16).type = 1;
M_.aux_vars(16).orig_index = 45;
M_.aux_vars(16).orig_lead_lag = -2;
M_.aux_vars(17).endo_index = 63;
M_.aux_vars(17).type = 1;
M_.aux_vars(17).orig_index = 45;
M_.aux_vars(17).orig_lead_lag = -3;
M_.aux_vars(18).endo_index = 64;
M_.aux_vars(18).type = 1;
M_.aux_vars(18).orig_index = 42;
M_.aux_vars(18).orig_lead_lag = -1;
M_.aux_vars(19).endo_index = 65;
M_.aux_vars(19).type = 1;
M_.aux_vars(19).orig_index = 42;
M_.aux_vars(19).orig_lead_lag = -2;
M_.aux_vars(20).endo_index = 66;
M_.aux_vars(20).type = 1;
M_.aux_vars(20).orig_index = 42;
M_.aux_vars(20).orig_lead_lag = -3;
M_.aux_vars(21).endo_index = 67;
M_.aux_vars(21).type = 1;
M_.aux_vars(21).orig_index = 44;
M_.aux_vars(21).orig_lead_lag = -1;
M_.aux_vars(22).endo_index = 68;
M_.aux_vars(22).type = 1;
M_.aux_vars(22).orig_index = 44;
M_.aux_vars(22).orig_lead_lag = -2;
M_.aux_vars(23).endo_index = 69;
M_.aux_vars(23).type = 1;
M_.aux_vars(23).orig_index = 44;
M_.aux_vars(23).orig_lead_lag = -3;
M_.Sigma_e = zeros(5, 5);
M_.Correlation_matrix = eye(5, 5);
M_.H = 0;
M_.Correlation_matrix_ME = 1;
M_.sigma_e_is_diagonal = 1;
M_.det_shocks = [];
options_.linear = 1;
options_.block=0;
options_.bytecode=0;
options_.use_dll=0;
M_.hessian_eq_zero = 1;
erase_compiled_function('US_ACELt_static');
erase_compiled_function('US_ACELt_dynamic');
M_.orig_eq_nbr = 46;
M_.eq_nbr = 69;
M_.ramsey_eq_nbr = 0;
M_.set_auxiliary_variables = exist(['./' M_.fname '_set_auxiliary_variables.m'], 'file') == 2;
M_.lead_lag_incidence = [
 1 42 111;
 2 43 112;
 0 44 113;
 3 45 0;
 4 46 114;
 5 47 0;
 0 48 0;
 6 49 115;
 0 50 0;
 7 51 0;
 0 52 0;
 0 53 0;
 0 54 116;
 0 55 117;
 0 56 118;
 0 57 0;
 8 58 0;
 9 59 0;
 10 60 119;
 11 61 0;
 12 62 0;
 13 63 120;
 14 64 0;
 15 65 0;
 16 66 121;
 17 67 122;
 0 68 123;
 18 69 0;
 19 70 124;
 20 71 0;
 0 72 0;
 21 73 125;
 0 74 0;
 22 75 0;
 0 76 0;
 0 77 0;
 0 78 126;
 0 79 127;
 0 80 128;
 0 81 0;
 23 82 0;
 24 83 0;
 0 84 0;
 25 85 129;
 26 86 130;
 27 87 131;
 0 88 132;
 0 89 133;
 0 90 134;
 0 91 135;
 0 92 136;
 0 93 137;
 0 94 138;
 0 95 139;
 0 96 140;
 28 97 0;
 29 98 0;
 30 99 0;
 31 100 0;
 32 101 0;
 33 102 0;
 34 103 0;
 35 104 0;
 36 105 0;
 37 106 0;
 38 107 0;
 39 108 0;
 40 109 0;
 41 110 0;]';
M_.nstatic = 11;
M_.nfwrd   = 17;
M_.npred   = 28;
M_.nboth   = 13;
M_.nsfwrd   = 30;
M_.nspred   = 41;
M_.ndynamic   = 58;
M_.equations_tags = {
};
M_.static_and_dynamic_models_differ = 0;
M_.exo_names_orig_ord = [1:5];
M_.maximum_lag = 1;
M_.maximum_lead = 1;
M_.maximum_endo_lag = 1;
M_.maximum_endo_lead = 1;
oo_.steady_state = zeros(69, 1);
M_.maximum_exo_lag = 0;
M_.maximum_exo_lead = 0;
oo_.exo_steady_state = zeros(5, 1);
M_.params = NaN(111, 1);
M_.NNZDerivatives = [322; 0; -1];
M_.params( 111 ) = 0.9767;
rho_epsilon = M_.params( 111 );
M_.params( 35 ) = 0.3600;
alpha = M_.params( 35 );
M_.params( 36 ) = 0.7048;
b = M_.params( 36 );
M_.params( 37 ) = 0.9926;
beta = M_.params( 37 );
M_.params( 38 ) = 0.0250;
delta = M_.params( 38 );
epsilon     =   0.8004 ;
M_.params( 40 ) = 0.0360;
eta = M_.params( 40 );
M_.params( 41 ) = 1.0100;
lambda_f = M_.params( 41 );
M_.params( 42 ) = 1.0500;
lambda_w = M_.params( 42 );
M_.params( 43 ) = 1.0042;
mu_ups = M_.params( 43 );
M_.params( 44 ) = 1.0001;
mu_z = M_.params( 44 );
M_.params( 45 ) = 1.0000;
nu = M_.params( 45 );
M_.params( 46 ) = 1.0000;
psi_L = M_.params( 46 );
M_.params( 47 ) = 1.0000;
sigma_L = M_.params( 47 );
M_.params( 48 ) = 1.0170;
x = M_.params( 48 );
M_.params( 49 ) = 0.7234;
xi_w = M_.params( 49 );
M_.params( 100 ) = 0;
xif_w = M_.params( 100 );
M_.params( 50 ) = 0.4500;
V = M_.params( 50 );
M_.params( 51 ) = 3.2756;
kappa = M_.params( 51 );
M_.params( 52 ) = 2.0183;
sigma_a = M_.params( 52 );
M_.params( 53 ) = 0.0401;
gamma = M_.params( 53 );
M_.params( 54 ) = 1.0000;
squig = M_.params( 54 );
M_.params( 55 ) = 0.0000;
vaartheta = M_.params( 55 );
M_.params( 56 ) = (-0.0335);
rho_M = M_.params( 56 );
M_.params( 57 ) = 0.0000;
theta_M = M_.params( 57 );
M_.params( 58 ) = 0.9041;
rho_muz = M_.params( 58 );
M_.params( 59 ) = 0.0000;
theta_muz = M_.params( 59 );
M_.params( 60 ) = 2.9973;
c_z = M_.params( 60 );
M_.params( 61 ) = 1.4211;
cp_z = M_.params( 61 );
M_.params( 62 ) = 0.3276;
rho_xz = M_.params( 62 );
M_.params( 63 ) = 0.2414;
rho_muups = M_.params( 63 );
M_.params( 64 ) = 0.0000;
theta_muups = M_.params( 64 );
M_.params( 65 ) = 0.2461;
c_ups = M_.params( 65 );
M_.params( 66 ) = 0.1342;
cp_ups = M_.params( 66 );
M_.params( 67 ) = 0.8217;
rho_xups = M_.params( 67 );
M_.params( 68 ) = M_.params(43)^(M_.params(35)/(1-M_.params(35)))*M_.params(44);
mu_zstar = M_.params( 68 );
M_.params( 69 ) = M_.params(43)*M_.params(68)/M_.params(37)-(1-M_.params(38));
rhotilde = M_.params( 69 );
M_.params( 70 ) = M_.params(48)/M_.params(68);
infl = M_.params( 70 );
M_.params( 71 ) = M_.params(68)*M_.params(70)/M_.params(37);
R = M_.params( 71 );
M_.params( 72 ) = (M_.params(71)-1)/M_.params(50)^2;
eta_pr = M_.params( 72 );
M_.params( 84 ) = 1/((M_.params(71)-1)*4*epsilon)-2;
sig_eta = M_.params( 84 );
M_.params( 73 ) = 1/M_.params(41);
s = M_.params( 73 );
M_.params( 74 ) = 1+M_.params(71)*M_.params(45)-M_.params(45);
R_nu = M_.params( 74 );
M_.params( 75 ) = (1-M_.params(35))/M_.params(74)*M_.params(73)*(M_.params(69)/(M_.params(35)*M_.params(73)))^(M_.params(35)/(M_.params(35)-1));
wtilde = M_.params( 75 );
M_.params( 76 ) = (M_.params(69)/(M_.params(35)*M_.params(73)*(M_.params(43)*M_.params(68))^(1-M_.params(35))))^(1/(1-M_.params(35)));
h_kbar = M_.params( 76 );
M_.params( 77 ) = ((1+M_.params(40))*M_.params(75)/(M_.params(46)*M_.params(76)^M_.params(47))*(M_.params(68)-M_.params(37)*M_.params(36))/(M_.params(42)*(M_.params(68)-M_.params(36))*(1+M_.params(40)+M_.params(50)*M_.params(72)))/(1/M_.params(41)*1/(M_.params(43)*M_.params(68))^M_.params(35)*M_.params(76)^(1-M_.params(35))-(1-(1-M_.params(38))/(M_.params(43)*M_.params(68)))))^(1/(1+M_.params(47)));
kbar = M_.params( 77 );
M_.params( 78 ) = M_.params(76)*M_.params(77);
h = M_.params( 78 );
M_.params( 79 ) = (M_.params(68)-M_.params(37)*M_.params(36))*M_.params(75)*M_.params(77)^(-M_.params(47))/(M_.params(46)*M_.params(76)^M_.params(47))/(M_.params(42)*(M_.params(68)-M_.params(36))*(1+M_.params(40)+M_.params(50)*M_.params(72)));
c = M_.params( 79 );
M_.params( 80 ) = M_.params(79)/M_.params(50);
q = M_.params( 80 );
M_.params( 81 ) = (M_.params(45)*M_.params(75)*M_.params(78)+M_.params(80))/M_.params(48);
m = M_.params( 81 );
M_.params( 82 ) = M_.params(69)*M_.params(77)/(M_.params(43)*M_.params(68))+M_.params(78)*M_.params(74)*M_.params(75);
ytilde = M_.params( 82 );
M_.params( 83 ) = M_.params(82)*(M_.params(41)-1);
phi = M_.params( 83 );
M_.params( 85 ) = (1-(1-M_.params(38))/(M_.params(43)*M_.params(68)))*M_.params(77);
i = M_.params( 85 );
M_.params( 86 ) = (M_.params(68)-M_.params(37)*M_.params(36))/(M_.params(68)*M_.params(79)-M_.params(36)*M_.params(79))/(1+M_.params(40)+M_.params(50)*M_.params(72));
lambda_zstar = M_.params( 86 );
M_.params( 87 ) = 0;
blewy = M_.params( 87 );
M_.params( 88 ) = (M_.params(47)*M_.params(42)-(1-M_.params(42)))/((1-M_.params(49))*(1-M_.params(37)*M_.params(49)));
b_w = M_.params( 88 );
M_.params( 99 ) = (M_.params(47)*M_.params(42)-(1-M_.params(42)))/((1-M_.params(100))*(1-M_.params(37)*M_.params(100)));
bf_w = M_.params( 99 );
M_.params( 89 ) = M_.params(49)*M_.params(88);
ETA1 = M_.params( 89 );
M_.params( 90 ) = M_.params(47)*M_.params(42)+(-M_.params(88))*(1+M_.params(37)*M_.params(49)^2);
ETA2 = M_.params( 90 );
M_.params( 91 ) = M_.params(37)*M_.params(49)*M_.params(88);
ETA3 = M_.params( 91 );
M_.params( 92 ) = M_.params(49)*M_.params(88);
ETA4 = M_.params( 92 );
M_.params( 93 ) = M_.params(88)*(-M_.params(49))*(1+M_.params(37));
ETA5 = M_.params( 93 );
M_.params( 94 ) = M_.params(49)*M_.params(37)*M_.params(88);
ETA6 = M_.params( 94 );
M_.params( 95 ) = (-M_.params(47))*(1-M_.params(42));
ETA7 = M_.params( 95 );
M_.params( 96 ) = 1-M_.params(42);
ETA8 = M_.params( 96 );
M_.params( 97 ) = M_.params(49)*(-M_.params(88))*(1-M_.params(87));
ETA9 = M_.params( 97 );
M_.params( 98 ) = M_.params(49)*M_.params(37)*M_.params(88)*(1-M_.params(87));
ETA10 = M_.params( 98 );
M_.params( 101 ) = M_.params(100)*M_.params(99);
ETA1f = M_.params( 101 );
M_.params( 102 ) = M_.params(47)*M_.params(42)+(-M_.params(99))*(1+M_.params(37)*M_.params(100)^2);
ETA2f = M_.params( 102 );
M_.params( 103 ) = M_.params(37)*M_.params(100)*M_.params(99);
ETA3f = M_.params( 103 );
M_.params( 104 ) = M_.params(100)*M_.params(99);
ETA4f = M_.params( 104 );
M_.params( 105 ) = (1+M_.params(37))*M_.params(99)*(-M_.params(100));
ETA5f = M_.params( 105 );
M_.params( 106 ) = M_.params(100)*M_.params(37)*M_.params(99);
ETA6f = M_.params( 106 );
M_.params( 107 ) = (-M_.params(47))*(1-M_.params(42));
ETA7f = M_.params( 107 );
M_.params( 108 ) = 1-M_.params(42);
ETA8f = M_.params( 108 );
M_.params( 109 ) = (1-M_.params(87))*M_.params(100)*(-M_.params(99));
ETA9f = M_.params( 109 );
M_.params( 110 ) = (1-M_.params(87))*M_.params(100)*M_.params(37)*M_.params(99);
ETA10f = M_.params( 110 );
thispath = cd;                                                           
cd('..');                                                                
load policy_param.mat;                                                   
for i=1:33                                                               
deep_parameter_name = M_.param_names(i,:);                           
eval(['M_.params(i)  = ' deep_parameter_name ' ;'])                  
end                                                                      
cd(thispath);       
%
% SHOCKS instructions
%
M_.exo_det_length = 0;
M_.Sigma_e(1, 1) = (.3285)^2;
M_.Sigma_e(2, 2) = (.0673)^2;
M_.Sigma_e(3, 3) = (.3027)^2;
save('US_ACELt_results.mat', 'oo_', 'M_', 'options_');
if exist('estim_params_', 'var') == 1
  save('US_ACELt_results.mat', 'estim_params_', '-append');
end
if exist('bayestopt_', 'var') == 1
  save('US_ACELt_results.mat', 'bayestopt_', '-append');
end
if exist('dataset_', 'var') == 1
  save('US_ACELt_results.mat', 'dataset_', '-append');
end
if exist('estimation_info', 'var') == 1
  save('US_ACELt_results.mat', 'estimation_info', '-append');
end
if exist('dataset_info', 'var') == 1
  save('US_ACELt_results.mat', 'dataset_info', '-append');
end
if exist('oo_recursive_', 'var') == 1
  save('US_ACELt_results.mat', 'oo_recursive_', '-append');
end


disp(['Total computing time : ' dynsec2hms(toc(tic0)) ]);
if ~isempty(lastwarn)
  disp('Note: warning(s) encountered in MATLAB/Octave code')
end
diary off
