%
% Status : main Dynare file
%
% Warning : this file is generated automatically by Dynare
%           from model file (.mod)

tic0 = tic;
% Save empty dates and dseries objects in memory.
dates('initialize');
dseries('initialize');
% Define global variables.
global M_ options_ oo_ estim_params_ bayestopt_ dataset_ dataset_info estimation_info ys0_ ex0_
options_ = [];
M_.fname = 'NK_CDDL17';
M_.dynare_version = '4.5.4';
oo_.dynare_version = '4.5.4';
options_.dynare_version = '4.5.4';
%
% Some global variables initialization
%
global_initialization;
diary off;
diary('NK_CDDL17.log');
M_.exo_names = 'ez';
M_.exo_names_tex = 'ez';
M_.exo_names_long = 'ez';
M_.exo_names = char(M_.exo_names, 'et');
M_.exo_names_tex = char(M_.exo_names_tex, 'et');
M_.exo_names_long = char(M_.exo_names_long, 'et');
M_.exo_names = char(M_.exo_names, 'eps');
M_.exo_names_tex = char(M_.exo_names_tex, 'eps');
M_.exo_names_long = char(M_.exo_names_long, 'eps');
M_.exo_names = char(M_.exo_names, 'interest_');
M_.exo_names_tex = char(M_.exo_names_tex, 'interest\_');
M_.exo_names_long = char(M_.exo_names_long, 'interest_');
M_.endo_names = 'cnk';
M_.endo_names_tex = 'cnk';
M_.endo_names_long = 'cnk';
M_.endo_names = char(M_.endo_names, 'ynk');
M_.endo_names_tex = char(M_.endo_names_tex, 'ynk');
M_.endo_names_long = char(M_.endo_names_long, 'ynk');
M_.endo_names = char(M_.endo_names, 'ink');
M_.endo_names_tex = char(M_.endo_names_tex, 'ink');
M_.endo_names_long = char(M_.endo_names_long, 'ink');
M_.endo_names = char(M_.endo_names, 'knk');
M_.endo_names_tex = char(M_.endo_names_tex, 'knk');
M_.endo_names_long = char(M_.endo_names_long, 'knk');
M_.endo_names = char(M_.endo_names, 'hnk');
M_.endo_names_tex = char(M_.endo_names_tex, 'hnk');
M_.endo_names_long = char(M_.endo_names_long, 'hnk');
M_.endo_names = char(M_.endo_names, 'lnk');
M_.endo_names_tex = char(M_.endo_names_tex, 'lnk');
M_.endo_names_long = char(M_.endo_names_long, 'lnk');
M_.endo_names = char(M_.endo_names, 'psink');
M_.endo_names_tex = char(M_.endo_names_tex, 'psink');
M_.endo_names_long = char(M_.endo_names_long, 'psink');
M_.endo_names = char(M_.endo_names, 'pnnk');
M_.endo_names_tex = char(M_.endo_names_tex, 'pnnk');
M_.endo_names_long = char(M_.endo_names_long, 'pnnk');
M_.endo_names = char(M_.endo_names, 'pdnk');
M_.endo_names_tex = char(M_.endo_names_tex, 'pdnk');
M_.endo_names_long = char(M_.endo_names_long, 'pdnk');
M_.endo_names = char(M_.endo_names, 'dpnk');
M_.endo_names_tex = char(M_.endo_names_tex, 'dpnk');
M_.endo_names_long = char(M_.endo_names_long, 'dpnk');
M_.endo_names = char(M_.endo_names, 'dynk');
M_.endo_names_tex = char(M_.endo_names_tex, 'dynk');
M_.endo_names_long = char(M_.endo_names_long, 'dynk');
M_.endo_names = char(M_.endo_names, 'enk');
M_.endo_names_tex = char(M_.endo_names_tex, 'enk');
M_.endo_names_long = char(M_.endo_names_long, 'enk');
M_.endo_names = char(M_.endo_names, 'dnk');
M_.endo_names_tex = char(M_.endo_names_tex, 'dnk');
M_.endo_names_long = char(M_.endo_names_long, 'dnk');
M_.endo_names = char(M_.endo_names, 'Rsnk');
M_.endo_names_tex = char(M_.endo_names_tex, 'Rsnk');
M_.endo_names_long = char(M_.endo_names_long, 'Rsnk');
M_.endo_names = char(M_.endo_names, 'Rdnk');
M_.endo_names_tex = char(M_.endo_names_tex, 'Rdnk');
M_.endo_names_long = char(M_.endo_names_long, 'Rdnk');
M_.endo_names = char(M_.endo_names, 'Rrnk');
M_.endo_names_tex = char(M_.endo_names_tex, 'Rrnk');
M_.endo_names_long = char(M_.endo_names_long, 'Rrnk');
M_.endo_names = char(M_.endo_names, 'lbnk');
M_.endo_names_tex = char(M_.endo_names_tex, 'lbnk');
M_.endo_names_long = char(M_.endo_names_long, 'lbnk');
M_.endo_names = char(M_.endo_names, 'lsnk');
M_.endo_names_tex = char(M_.endo_names_tex, 'lsnk');
M_.endo_names_long = char(M_.endo_names_long, 'lsnk');
M_.endo_names = char(M_.endo_names, 'lrnk');
M_.endo_names_tex = char(M_.endo_names_tex, 'lrnk');
M_.endo_names_long = char(M_.endo_names_long, 'lrnk');
M_.endo_names = char(M_.endo_names, 'Util');
M_.endo_names_tex = char(M_.endo_names_tex, 'Util');
M_.endo_names_long = char(M_.endo_names_long, 'Util');
M_.endo_names = char(M_.endo_names, 'Welf');
M_.endo_names_tex = char(M_.endo_names_tex, 'Welf');
M_.endo_names_long = char(M_.endo_names_long, 'Welf');
M_.endo_names = char(M_.endo_names, 'cnk_f');
M_.endo_names_tex = char(M_.endo_names_tex, 'cnk\_f');
M_.endo_names_long = char(M_.endo_names_long, 'cnk_f');
M_.endo_names = char(M_.endo_names, 'ynk_f');
M_.endo_names_tex = char(M_.endo_names_tex, 'ynk\_f');
M_.endo_names_long = char(M_.endo_names_long, 'ynk_f');
M_.endo_names = char(M_.endo_names, 'ink_f');
M_.endo_names_tex = char(M_.endo_names_tex, 'ink\_f');
M_.endo_names_long = char(M_.endo_names_long, 'ink_f');
M_.endo_names = char(M_.endo_names, 'knk_f');
M_.endo_names_tex = char(M_.endo_names_tex, 'knk\_f');
M_.endo_names_long = char(M_.endo_names_long, 'knk_f');
M_.endo_names = char(M_.endo_names, 'hnk_f');
M_.endo_names_tex = char(M_.endo_names_tex, 'hnk\_f');
M_.endo_names_long = char(M_.endo_names_long, 'hnk_f');
M_.endo_names = char(M_.endo_names, 'lnk_f');
M_.endo_names_tex = char(M_.endo_names_tex, 'lnk\_f');
M_.endo_names_long = char(M_.endo_names_long, 'lnk_f');
M_.endo_names = char(M_.endo_names, 'psink_f');
M_.endo_names_tex = char(M_.endo_names_tex, 'psink\_f');
M_.endo_names_long = char(M_.endo_names_long, 'psink_f');
M_.endo_names = char(M_.endo_names, 'pnnk_f');
M_.endo_names_tex = char(M_.endo_names_tex, 'pnnk\_f');
M_.endo_names_long = char(M_.endo_names_long, 'pnnk_f');
M_.endo_names = char(M_.endo_names, 'pdnk_f');
M_.endo_names_tex = char(M_.endo_names_tex, 'pdnk\_f');
M_.endo_names_long = char(M_.endo_names_long, 'pdnk_f');
M_.endo_names = char(M_.endo_names, 'dynk_f');
M_.endo_names_tex = char(M_.endo_names_tex, 'dynk\_f');
M_.endo_names_long = char(M_.endo_names_long, 'dynk_f');
M_.endo_names = char(M_.endo_names, 'enk_f');
M_.endo_names_tex = char(M_.endo_names_tex, 'enk\_f');
M_.endo_names_long = char(M_.endo_names_long, 'enk_f');
M_.endo_names = char(M_.endo_names, 'dnk_f');
M_.endo_names_tex = char(M_.endo_names_tex, 'dnk\_f');
M_.endo_names_long = char(M_.endo_names_long, 'dnk_f');
M_.endo_names = char(M_.endo_names, 'Rsnk_f');
M_.endo_names_tex = char(M_.endo_names_tex, 'Rsnk\_f');
M_.endo_names_long = char(M_.endo_names_long, 'Rsnk_f');
M_.endo_names = char(M_.endo_names, 'Rdnk_f');
M_.endo_names_tex = char(M_.endo_names_tex, 'Rdnk\_f');
M_.endo_names_long = char(M_.endo_names_long, 'Rdnk_f');
M_.endo_names = char(M_.endo_names, 'Rrnk_f');
M_.endo_names_tex = char(M_.endo_names_tex, 'Rrnk\_f');
M_.endo_names_long = char(M_.endo_names_long, 'Rrnk_f');
M_.endo_names = char(M_.endo_names, 'lbnk_f');
M_.endo_names_tex = char(M_.endo_names_tex, 'lbnk\_f');
M_.endo_names_long = char(M_.endo_names_long, 'lbnk_f');
M_.endo_names = char(M_.endo_names, 'lsnk_f');
M_.endo_names_tex = char(M_.endo_names_tex, 'lsnk\_f');
M_.endo_names_long = char(M_.endo_names_long, 'lsnk_f');
M_.endo_names = char(M_.endo_names, 'lrnk_f');
M_.endo_names_tex = char(M_.endo_names_tex, 'lrnk\_f');
M_.endo_names_long = char(M_.endo_names_long, 'lrnk_f');
M_.endo_names = char(M_.endo_names, 'z');
M_.endo_names_tex = char(M_.endo_names_tex, 'z');
M_.endo_names_long = char(M_.endo_names_long, 'z');
M_.endo_names = char(M_.endo_names, 'etar');
M_.endo_names_tex = char(M_.endo_names_tex, 'etar');
M_.endo_names_long = char(M_.endo_names_long, 'etar');
M_.endo_names = char(M_.endo_names, 'psil');
M_.endo_names_tex = char(M_.endo_names_tex, 'psil');
M_.endo_names_long = char(M_.endo_names_long, 'psil');
M_.endo_names = char(M_.endo_names, 'kap');
M_.endo_names_tex = char(M_.endo_names_tex, 'kap');
M_.endo_names_long = char(M_.endo_names_long, 'kap');
M_.endo_names = char(M_.endo_names, 'qnk');
M_.endo_names_tex = char(M_.endo_names_tex, 'qnk');
M_.endo_names_long = char(M_.endo_names_long, 'qnk');
M_.endo_names = char(M_.endo_names, 'interest');
M_.endo_names_tex = char(M_.endo_names_tex, 'interest');
M_.endo_names_long = char(M_.endo_names_long, 'interest');
M_.endo_names = char(M_.endo_names, 'inflation');
M_.endo_names_tex = char(M_.endo_names_tex, 'inflation');
M_.endo_names_long = char(M_.endo_names_long, 'inflation');
M_.endo_names = char(M_.endo_names, 'inflationq');
M_.endo_names_tex = char(M_.endo_names_tex, 'inflationq');
M_.endo_names_long = char(M_.endo_names_long, 'inflationq');
M_.endo_names = char(M_.endo_names, 'outputgap');
M_.endo_names_tex = char(M_.endo_names_tex, 'outputgap');
M_.endo_names_long = char(M_.endo_names_long, 'outputgap');
M_.endo_names = char(M_.endo_names, 'output');
M_.endo_names_tex = char(M_.endo_names_tex, 'output');
M_.endo_names_long = char(M_.endo_names_long, 'output');
M_.endo_names = char(M_.endo_names, 'r_flex');
M_.endo_names_tex = char(M_.endo_names_tex, 'r\_flex');
M_.endo_names_long = char(M_.endo_names_long, 'r_flex');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_82');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_82');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_82');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_86');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_86');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_86');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_90');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_90');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_90');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_117');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_117');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_117');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_121');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_121');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_121');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_125');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_125');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_125');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_152');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_152');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_152');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_156');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_156');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_156');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_160');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_160');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_160');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_9_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_9\_1');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_9_1');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_9_2');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_9\_2');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_9_2');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_48_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_48\_1');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_48_1');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_48_2');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_48\_2');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_48_2');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_48_3');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_48\_3');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_48_3');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_47_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_47\_1');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_47_1');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_47_2');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_47\_2');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_47_2');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_47_3');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_47\_3');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_47_3');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_44_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_44\_1');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_44_1');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_44_2');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_44\_2');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_44_2');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_44_3');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_44\_3');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_44_3');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_46_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_46\_1');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_46_1');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_46_2');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_46\_2');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_46_2');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_46_3');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_46\_3');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_46_3');
M_.endo_partitions = struct();
M_.param_names = 'cofintintb1';
M_.param_names_tex = 'cofintintb1';
M_.param_names_long = 'cofintintb1';
M_.param_names = char(M_.param_names, 'cofintintb2');
M_.param_names_tex = char(M_.param_names_tex, 'cofintintb2');
M_.param_names_long = char(M_.param_names_long, 'cofintintb2');
M_.param_names = char(M_.param_names, 'cofintintb3');
M_.param_names_tex = char(M_.param_names_tex, 'cofintintb3');
M_.param_names_long = char(M_.param_names_long, 'cofintintb3');
M_.param_names = char(M_.param_names, 'cofintintb4');
M_.param_names_tex = char(M_.param_names_tex, 'cofintintb4');
M_.param_names_long = char(M_.param_names_long, 'cofintintb4');
M_.param_names = char(M_.param_names, 'cofintinf0');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinf0');
M_.param_names_long = char(M_.param_names_long, 'cofintinf0');
M_.param_names = char(M_.param_names, 'cofintinfb1');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinfb1');
M_.param_names_long = char(M_.param_names_long, 'cofintinfb1');
M_.param_names = char(M_.param_names, 'cofintinfb2');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinfb2');
M_.param_names_long = char(M_.param_names_long, 'cofintinfb2');
M_.param_names = char(M_.param_names, 'cofintinfb3');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinfb3');
M_.param_names_long = char(M_.param_names_long, 'cofintinfb3');
M_.param_names = char(M_.param_names, 'cofintinfb4');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinfb4');
M_.param_names_long = char(M_.param_names_long, 'cofintinfb4');
M_.param_names = char(M_.param_names, 'cofintinff1');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinff1');
M_.param_names_long = char(M_.param_names_long, 'cofintinff1');
M_.param_names = char(M_.param_names, 'cofintinff2');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinff2');
M_.param_names_long = char(M_.param_names_long, 'cofintinff2');
M_.param_names = char(M_.param_names, 'cofintinff3');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinff3');
M_.param_names_long = char(M_.param_names_long, 'cofintinff3');
M_.param_names = char(M_.param_names, 'cofintinff4');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinff4');
M_.param_names_long = char(M_.param_names_long, 'cofintinff4');
M_.param_names = char(M_.param_names, 'cofintout');
M_.param_names_tex = char(M_.param_names_tex, 'cofintout');
M_.param_names_long = char(M_.param_names_long, 'cofintout');
M_.param_names = char(M_.param_names, 'cofintoutb1');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutb1');
M_.param_names_long = char(M_.param_names_long, 'cofintoutb1');
M_.param_names = char(M_.param_names, 'cofintoutb2');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutb2');
M_.param_names_long = char(M_.param_names_long, 'cofintoutb2');
M_.param_names = char(M_.param_names, 'cofintoutb3');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutb3');
M_.param_names_long = char(M_.param_names_long, 'cofintoutb3');
M_.param_names = char(M_.param_names, 'cofintoutb4');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutb4');
M_.param_names_long = char(M_.param_names_long, 'cofintoutb4');
M_.param_names = char(M_.param_names, 'cofintoutf1');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutf1');
M_.param_names_long = char(M_.param_names_long, 'cofintoutf1');
M_.param_names = char(M_.param_names, 'cofintoutf2');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutf2');
M_.param_names_long = char(M_.param_names_long, 'cofintoutf2');
M_.param_names = char(M_.param_names, 'cofintoutf3');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutf3');
M_.param_names_long = char(M_.param_names_long, 'cofintoutf3');
M_.param_names = char(M_.param_names, 'cofintoutf4');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutf4');
M_.param_names_long = char(M_.param_names_long, 'cofintoutf4');
M_.param_names = char(M_.param_names, 'cofintoutp');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutp');
M_.param_names_long = char(M_.param_names_long, 'cofintoutp');
M_.param_names = char(M_.param_names, 'cofintoutpb1');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpb1');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpb1');
M_.param_names = char(M_.param_names, 'cofintoutpb2');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpb2');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpb2');
M_.param_names = char(M_.param_names, 'cofintoutpb3');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpb3');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpb3');
M_.param_names = char(M_.param_names, 'cofintoutpb4');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpb4');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpb4');
M_.param_names = char(M_.param_names, 'cofintoutpf1');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpf1');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpf1');
M_.param_names = char(M_.param_names, 'cofintoutpf2');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpf2');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpf2');
M_.param_names = char(M_.param_names, 'cofintoutpf3');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpf3');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpf3');
M_.param_names = char(M_.param_names, 'cofintoutpf4');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpf4');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpf4');
M_.param_names = char(M_.param_names, 'std_r_');
M_.param_names_tex = char(M_.param_names_tex, 'std\_r\_');
M_.param_names_long = char(M_.param_names_long, 'std_r_');
M_.param_names = char(M_.param_names, 'std_r_quart');
M_.param_names_tex = char(M_.param_names_tex, 'std\_r\_quart');
M_.param_names_long = char(M_.param_names_long, 'std_r_quart');
M_.param_names = char(M_.param_names, 'coffispol');
M_.param_names_tex = char(M_.param_names_tex, 'coffispol');
M_.param_names_long = char(M_.param_names_long, 'coffispol');
M_.param_names = char(M_.param_names, 'nbeta');
M_.param_names_tex = char(M_.param_names_tex, 'nbeta');
M_.param_names_long = char(M_.param_names_long, 'nbeta');
M_.param_names = char(M_.param_names, 'chi');
M_.param_names_tex = char(M_.param_names_tex, 'chi');
M_.param_names_long = char(M_.param_names_long, 'chi');
M_.param_names = char(M_.param_names, 'thh');
M_.param_names_tex = char(M_.param_names_tex, 'thh');
M_.param_names_long = char(M_.param_names_long, 'thh');
M_.param_names = char(M_.param_names, 'nu');
M_.param_names_tex = char(M_.param_names_tex, 'nu');
M_.param_names_long = char(M_.param_names_long, 'nu');
M_.param_names = char(M_.param_names, 'delta');
M_.param_names_tex = char(M_.param_names_tex, 'delta');
M_.param_names_long = char(M_.param_names_long, 'delta');
M_.param_names = char(M_.param_names, 'sigma');
M_.param_names_tex = char(M_.param_names_tex, 'sigma');
M_.param_names_long = char(M_.param_names_long, 'sigma');
M_.param_names = char(M_.param_names, 'mup');
M_.param_names_tex = char(M_.param_names_tex, 'mup');
M_.param_names_long = char(M_.param_names_long, 'mup');
M_.param_names = char(M_.param_names, 'xi');
M_.param_names_tex = char(M_.param_names_tex, 'xi');
M_.param_names_long = char(M_.param_names_long, 'xi');
M_.param_names = char(M_.param_names, 'dpss');
M_.param_names_tex = char(M_.param_names_tex, 'dpss');
M_.param_names_long = char(M_.param_names_long, 'dpss');
M_.param_names = char(M_.param_names, 'tau');
M_.param_names_tex = char(M_.param_names_tex, 'tau');
M_.param_names_long = char(M_.param_names_long, 'tau');
M_.param_names = char(M_.param_names, 'psilss');
M_.param_names_tex = char(M_.param_names_tex, 'psilss');
M_.param_names_long = char(M_.param_names_long, 'psilss');
M_.param_names = char(M_.param_names, 'gammass');
M_.param_names_tex = char(M_.param_names_tex, 'gammass');
M_.param_names_long = char(M_.param_names_long, 'gammass');
M_.param_names = char(M_.param_names, 'phiss');
M_.param_names_tex = char(M_.param_names_tex, 'phiss');
M_.param_names_long = char(M_.param_names_long, 'phiss');
M_.param_names = char(M_.param_names, 'rz');
M_.param_names_tex = char(M_.param_names_tex, 'rz');
M_.param_names_long = char(M_.param_names_long, 'rz');
M_.param_names = char(M_.param_names, 'rt');
M_.param_names_tex = char(M_.param_names_tex, 'rt');
M_.param_names_long = char(M_.param_names_long, 'rt');
M_.param_names = char(M_.param_names, 'rp');
M_.param_names_tex = char(M_.param_names_tex, 'rp');
M_.param_names_long = char(M_.param_names_long, 'rp');
M_.param_names = char(M_.param_names, 'etss');
M_.param_names_tex = char(M_.param_names_tex, 'etss');
M_.param_names_long = char(M_.param_names_long, 'etss');
M_.param_names = char(M_.param_names, 'xi_f');
M_.param_names_tex = char(M_.param_names_tex, 'xi\_f');
M_.param_names_long = char(M_.param_names_long, 'xi_f');
M_.param_names = char(M_.param_names, 'kpss');
M_.param_names_tex = char(M_.param_names_tex, 'kpss');
M_.param_names_long = char(M_.param_names_long, 'kpss');
M_.param_partitions = struct();
M_.exo_det_nbr = 0;
M_.exo_nbr = 4;
M_.endo_nbr = 73;
M_.param_nbr = 53;
M_.orig_endo_nbr = 50;
M_.aux_vars(1).endo_index = 51;
M_.aux_vars(1).type = 0;
M_.aux_vars(2).endo_index = 52;
M_.aux_vars(2).type = 0;
M_.aux_vars(3).endo_index = 53;
M_.aux_vars(3).type = 0;
M_.aux_vars(4).endo_index = 54;
M_.aux_vars(4).type = 0;
M_.aux_vars(5).endo_index = 55;
M_.aux_vars(5).type = 0;
M_.aux_vars(6).endo_index = 56;
M_.aux_vars(6).type = 0;
M_.aux_vars(7).endo_index = 57;
M_.aux_vars(7).type = 0;
M_.aux_vars(8).endo_index = 58;
M_.aux_vars(8).type = 0;
M_.aux_vars(9).endo_index = 59;
M_.aux_vars(9).type = 0;
M_.aux_vars(10).endo_index = 60;
M_.aux_vars(10).type = 1;
M_.aux_vars(10).orig_index = 10;
M_.aux_vars(10).orig_lead_lag = -1;
M_.aux_vars(11).endo_index = 61;
M_.aux_vars(11).type = 1;
M_.aux_vars(11).orig_index = 10;
M_.aux_vars(11).orig_lead_lag = -2;
M_.aux_vars(12).endo_index = 62;
M_.aux_vars(12).type = 1;
M_.aux_vars(12).orig_index = 49;
M_.aux_vars(12).orig_lead_lag = -1;
M_.aux_vars(13).endo_index = 63;
M_.aux_vars(13).type = 1;
M_.aux_vars(13).orig_index = 49;
M_.aux_vars(13).orig_lead_lag = -2;
M_.aux_vars(14).endo_index = 64;
M_.aux_vars(14).type = 1;
M_.aux_vars(14).orig_index = 49;
M_.aux_vars(14).orig_lead_lag = -3;
M_.aux_vars(15).endo_index = 65;
M_.aux_vars(15).type = 1;
M_.aux_vars(15).orig_index = 48;
M_.aux_vars(15).orig_lead_lag = -1;
M_.aux_vars(16).endo_index = 66;
M_.aux_vars(16).type = 1;
M_.aux_vars(16).orig_index = 48;
M_.aux_vars(16).orig_lead_lag = -2;
M_.aux_vars(17).endo_index = 67;
M_.aux_vars(17).type = 1;
M_.aux_vars(17).orig_index = 48;
M_.aux_vars(17).orig_lead_lag = -3;
M_.aux_vars(18).endo_index = 68;
M_.aux_vars(18).type = 1;
M_.aux_vars(18).orig_index = 45;
M_.aux_vars(18).orig_lead_lag = -1;
M_.aux_vars(19).endo_index = 69;
M_.aux_vars(19).type = 1;
M_.aux_vars(19).orig_index = 45;
M_.aux_vars(19).orig_lead_lag = -2;
M_.aux_vars(20).endo_index = 70;
M_.aux_vars(20).type = 1;
M_.aux_vars(20).orig_index = 45;
M_.aux_vars(20).orig_lead_lag = -3;
M_.aux_vars(21).endo_index = 71;
M_.aux_vars(21).type = 1;
M_.aux_vars(21).orig_index = 47;
M_.aux_vars(21).orig_lead_lag = -1;
M_.aux_vars(22).endo_index = 72;
M_.aux_vars(22).type = 1;
M_.aux_vars(22).orig_index = 47;
M_.aux_vars(22).orig_lead_lag = -2;
M_.aux_vars(23).endo_index = 73;
M_.aux_vars(23).type = 1;
M_.aux_vars(23).orig_index = 47;
M_.aux_vars(23).orig_lead_lag = -3;
M_.Sigma_e = zeros(4, 4);
M_.Correlation_matrix = eye(4, 4);
M_.H = 0;
M_.Correlation_matrix_ME = 1;
M_.sigma_e_is_diagonal = 1;
M_.det_shocks = [];
options_.block=0;
options_.bytecode=0;
options_.use_dll=0;
M_.hessian_eq_zero = 1;
erase_compiled_function('NK_CDDL17_static');
erase_compiled_function('NK_CDDL17_dynamic');
M_.orig_eq_nbr = 50;
M_.eq_nbr = 73;
M_.ramsey_eq_nbr = 0;
M_.set_auxiliary_variables = exist(['./' M_.fname '_set_auxiliary_variables.m'], 'file') == 2;
M_.lead_lag_incidence = [
 0 27 0;
 0 28 100;
 0 29 0;
 1 30 0;
 0 31 0;
 0 32 0;
 0 33 101;
 0 34 102;
 0 35 103;
 2 36 104;
 3 37 0;
 0 38 0;
 0 39 0;
 0 40 0;
 0 41 0;
 0 42 0;
 0 43 105;
 0 44 0;
 0 45 0;
 0 46 0;
 0 47 106;
 0 48 0;
 0 49 107;
 0 50 0;
 4 51 0;
 0 52 0;
 0 53 0;
 0 54 108;
 0 55 109;
 0 56 0;
 5 57 0;
 0 58 0;
 0 59 0;
 0 60 0;
 0 61 0;
 0 62 0;
 0 63 110;
 0 64 0;
 0 65 0;
 6 66 0;
 7 67 0;
 8 68 0;
 0 69 0;
 0 70 0;
 9 71 0;
 0 72 0;
 10 73 111;
 11 74 112;
 12 75 113;
 0 76 0;
 0 77 114;
 0 78 115;
 0 79 116;
 0 80 117;
 0 81 118;
 0 82 119;
 0 83 120;
 0 84 121;
 0 85 122;
 13 86 0;
 14 87 0;
 15 88 0;
 16 89 0;
 17 90 0;
 18 91 0;
 19 92 0;
 20 93 0;
 21 94 0;
 22 95 0;
 23 96 0;
 24 97 0;
 25 98 0;
 26 99 0;]';
M_.nstatic = 28;
M_.nfwrd   = 19;
M_.npred   = 22;
M_.nboth   = 4;
M_.nsfwrd   = 23;
M_.nspred   = 26;
M_.ndynamic   = 45;
M_.equations_tags = {
};
M_.static_and_dynamic_models_differ = 0;
M_.exo_names_orig_ord = [1:4];
M_.maximum_lag = 1;
M_.maximum_lead = 1;
M_.maximum_endo_lag = 1;
M_.maximum_endo_lead = 1;
oo_.steady_state = zeros(73, 1);
M_.maximum_exo_lag = 0;
M_.maximum_exo_lead = 0;
oo_.exo_steady_state = zeros(4, 1);
M_.params = NaN(53, 1);
M_.NNZDerivatives = [252; -1; -1];
M_.params( 35 ) = 0.9932166151679669;
nbeta = M_.params( 35 );
M_.params( 36 ) = 0.276;
chi = M_.params( 36 );
M_.params( 37 ) = 3.409;
thh = M_.params( 37 );
M_.params( 38 ) = 0.33;
nu = M_.params( 38 );
M_.params( 39 ) = 0.025;
delta = M_.params( 39 );
M_.params( 40 ) = 7;
sigma = M_.params( 40 );
M_.params( 41 ) = M_.params(40)/(M_.params(40)-1);
mup = M_.params( 41 );
M_.params( 42 ) = 0.779;
xi = M_.params( 42 );
M_.params( 52 ) = 0;
xi_f = M_.params( 52 );
psiss   = 1/mup; 
M_.params( 43 ) = 1;
dpss = M_.params( 43 );
M_.params( 44 ) = 0.0229;
tau = M_.params( 44 );
M_.params( 51 ) = 0.0123;
etss = M_.params( 51 );
M_.params( 53 ) = 0.12;
kpss = M_.params( 53 );
oms     = exp(0.0226/4);
M_.params( 45 ) = log(oms)-M_.params(44)*0.10/(1-M_.params(44));
psilss = M_.params( 45 );
M_.params( 47 ) = 0.0338099574025002;
phiss = M_.params( 47 );
omr     = exp(etss);
M_.params( 46 ) = M_.params(47)*((1-M_.params(44))*M_.params(45)+M_.params(53))/((1-M_.params(47))*(1-M_.params(44)+M_.params(44)*M_.params(53))*(omr-1)+omr*M_.params(45)*(1-M_.params(44))*(1-M_.params(47))-M_.params(47)*M_.params(53));
gammass = M_.params( 46 );
M_.params( 48 ) = 0.966230;
rz = M_.params( 48 );
M_.params( 49 ) = 0.905011;
rt = M_.params( 49 );
M_.params( 50 ) = 0.677908;
rp = M_.params( 50 );
sez     = 0.006799;
set     = 6.014478243327080e-04; 
sep     = 0; 3.573303779883895e-04;
KP      = 0.1;
for iexp=1:length(KP)
M_.params( 53 ) = KP(iexp);
kpss = M_.params( 53 );
Rdss    = dpss/nbeta;
Rsss    = oms*Rdss;
Rrss    = omr*Rsss;
ksy     = nu/(mup*(Rsss-(1-delta)));
lssy    = ksy/(1+gammass*exp(etss)*(1-phiss));
lrsy    = gammass*lssy;
lsy     = (1+gammass)*lssy;
isy     = lsy-(1-delta)*ksy; 
csy     = 1-isy-psilss*lssy; 
hss     = ((1-nu)/(mup*csy*thh))^(1/(1+chi));
yss     = ksy^(nu/(1-nu))*hss; 
css     = csy*yss; 
lbss    = 1/css; 
lbkss   = lbss; 
qxss    = 1; 
iss     = isy*yss; 
lsss    = lssy*yss;
lrss    = lrsy*yss;
lss     = lsss+lrss; 
kss     = ksy*yss;
pnss    = lbss*yss/(1-nbeta*xi); 
pdss    = pnss; 
dyss    = 1;
ess     = kpss*lss; 
dss     = lss-ess; 
qss     = nu/(mup*ksy)+1-delta;
wss     = (sigma-1)*(1-nu)*yss/(sigma*hss);
zss     = nu*wss*hss/((1-nu)*kss);
xss     = lss;
thispath = cd;                                                           
cd('..');                                                                
load policy_param.mat;                                                   
for i=1:33                                                               
deep_parameter_name = M_.param_names(i,:);                           
eval(['M_.params(i)  = ' deep_parameter_name ' ;'])                  
end                                                                      
cd(thispath);                                                            
M_.params( 34 ) = 1;
coffispol = M_.params( 34 );
resid; 
steady;
oo_.dr.eigval = check(M_,options_,oo_);
%
% SHOCKS instructions
%
M_.exo_det_length = 0;
M_.Sigma_e(1, 1) = (sez)^2;
M_.Sigma_e(2, 2) = (set)^2;
M_.Sigma_e(3, 3) = (sep)^2;
options_.irf = 20;
options_.nograph = 1;
options_.order = 1;
var_list_ = char();
info = stoch_simul(var_list_);
end
save('NK_CDDL17_results.mat', 'oo_', 'M_', 'options_');
if exist('estim_params_', 'var') == 1
  save('NK_CDDL17_results.mat', 'estim_params_', '-append');
end
if exist('bayestopt_', 'var') == 1
  save('NK_CDDL17_results.mat', 'bayestopt_', '-append');
end
if exist('dataset_', 'var') == 1
  save('NK_CDDL17_results.mat', 'dataset_', '-append');
end
if exist('estimation_info', 'var') == 1
  save('NK_CDDL17_results.mat', 'estimation_info', '-append');
end
if exist('dataset_info', 'var') == 1
  save('NK_CDDL17_results.mat', 'dataset_info', '-append');
end
if exist('oo_recursive_', 'var') == 1
  save('NK_CDDL17_results.mat', 'oo_recursive_', '-append');
end


disp(['Total computing time : ' dynsec2hms(toc(tic0)) ]);
disp('Note: 1 warning(s) encountered in the preprocessor')
if ~isempty(lastwarn)
  disp('Note: warning(s) encountered in MATLAB/Octave code')
end
diary off
