%
% Status : main Dynare file
%
% Warning : this file is generated automatically by Dynare
%           from model file (.mod)

if isoctave || matlab_ver_less_than('8.6')
    clear all
else
    clearvars -global
    clear_persistent_variables(fileparts(which('dynare')), false)
end
tic0 = tic;
% Save empty dates and dseries objects in memory.
dates('initialize');
dseries('initialize');
% Define global variables.
global M_ options_ oo_ estim_params_ bayestopt_ dataset_ dataset_info estimation_info ys0_ ex0_
options_ = [];
M_.fname = 'EA_CW05fm';
M_.dynare_version = '4.5.4';
oo_.dynare_version = '4.5.4';
options_.dynare_version = '4.5.4';
%
% Some global variables initialization
%
global_initialization;
diary off;
diary('EA_CW05fm.log');
M_.exo_names = 'e_cw';
M_.exo_names_tex = 'e\_cw';
M_.exo_names_long = 'e_cw';
M_.exo_names = char(M_.exo_names, 'e_d');
M_.exo_names_tex = char(M_.exo_names_tex, 'e\_d');
M_.exo_names_long = char(M_.exo_names_long, 'e_d');
M_.exo_names = char(M_.exo_names, 'interest_');
M_.exo_names_tex = char(M_.exo_names_tex, 'interest\_');
M_.exo_names_long = char(M_.exo_names_long, 'interest_');
M_.endo_names = 'q';
M_.endo_names_tex = 'q';
M_.endo_names_long = 'q';
M_.endo_names = char(M_.endo_names, 'lagq1');
M_.endo_names_tex = char(M_.endo_names_tex, 'lagq1');
M_.endo_names_long = char(M_.endo_names_long, 'lagq1');
M_.endo_names = char(M_.endo_names, 'cwp');
M_.endo_names_tex = char(M_.endo_names_tex, 'cwp');
M_.endo_names_long = char(M_.endo_names_long, 'cwp');
M_.endo_names = char(M_.endo_names, 'ldvindex1');
M_.endo_names_tex = char(M_.endo_names_tex, 'ldvindex1');
M_.endo_names_long = char(M_.endo_names_long, 'ldvindex1');
M_.endo_names = char(M_.endo_names, 'ldvindex2');
M_.endo_names_tex = char(M_.endo_names_tex, 'ldvindex2');
M_.endo_names_long = char(M_.endo_names_long, 'ldvindex2');
M_.endo_names = char(M_.endo_names, 'ldq1');
M_.endo_names_tex = char(M_.endo_names_tex, 'ldq1');
M_.endo_names_long = char(M_.endo_names_long, 'ldq1');
M_.endo_names = char(M_.endo_names, 'ldq2');
M_.endo_names_tex = char(M_.endo_names_tex, 'ldq2');
M_.endo_names_long = char(M_.endo_names_long, 'ldq2');
M_.endo_names = char(M_.endo_names, 'vindex');
M_.endo_names_tex = char(M_.endo_names_tex, 'vindex');
M_.endo_names_long = char(M_.endo_names_long, 'vindex');
M_.endo_names = char(M_.endo_names, 'lagcwp1');
M_.endo_names_tex = char(M_.endo_names_tex, 'lagcwp1');
M_.endo_names_long = char(M_.endo_names_long, 'lagcwp1');
M_.endo_names = char(M_.endo_names, 'lagcwp2');
M_.endo_names_tex = char(M_.endo_names_tex, 'lagcwp2');
M_.endo_names_long = char(M_.endo_names_long, 'lagcwp2');
M_.endo_names = char(M_.endo_names, 'pi1');
M_.endo_names_tex = char(M_.endo_names_tex, 'pi1');
M_.endo_names_long = char(M_.endo_names_long, 'pi1');
M_.endo_names = char(M_.endo_names, 'lagpi1');
M_.endo_names_tex = char(M_.endo_names_tex, 'lagpi1');
M_.endo_names_long = char(M_.endo_names_long, 'lagpi1');
M_.endo_names = char(M_.endo_names, 'lagpi2');
M_.endo_names_tex = char(M_.endo_names_tex, 'lagpi2');
M_.endo_names_long = char(M_.endo_names_long, 'lagpi2');
M_.endo_names = char(M_.endo_names, 'infl');
M_.endo_names_tex = char(M_.endo_names_tex, 'infl');
M_.endo_names_long = char(M_.endo_names_long, 'infl');
M_.endo_names = char(M_.endo_names, 'is');
M_.endo_names_tex = char(M_.endo_names_tex, 'is');
M_.endo_names_long = char(M_.endo_names_long, 'is');
M_.endo_names = char(M_.endo_names, 'dis');
M_.endo_names_tex = char(M_.endo_names_tex, 'dis');
M_.endo_names_long = char(M_.endo_names_long, 'dis');
M_.endo_names = char(M_.endo_names, 'il');
M_.endo_names_tex = char(M_.endo_names_tex, 'il');
M_.endo_names_long = char(M_.endo_names_long, 'il');
M_.endo_names = char(M_.endo_names, 'ldis1');
M_.endo_names_tex = char(M_.endo_names_tex, 'ldis1');
M_.endo_names_long = char(M_.endo_names_long, 'ldis1');
M_.endo_names = char(M_.endo_names, 'ldis2');
M_.endo_names_tex = char(M_.endo_names_tex, 'ldis2');
M_.endo_names_long = char(M_.endo_names_long, 'ldis2');
M_.endo_names = char(M_.endo_names, 'ldis3');
M_.endo_names_tex = char(M_.endo_names_tex, 'ldis3');
M_.endo_names_long = char(M_.endo_names_long, 'ldis3');
M_.endo_names = char(M_.endo_names, 'ldis4');
M_.endo_names_tex = char(M_.endo_names_tex, 'ldis4');
M_.endo_names_long = char(M_.endo_names_long, 'ldis4');
M_.endo_names = char(M_.endo_names, 'ldis5');
M_.endo_names_tex = char(M_.endo_names_tex, 'ldis5');
M_.endo_names_long = char(M_.endo_names_long, 'ldis5');
M_.endo_names = char(M_.endo_names, 'ldis6');
M_.endo_names_tex = char(M_.endo_names_tex, 'ldis6');
M_.endo_names_long = char(M_.endo_names_long, 'ldis6');
M_.endo_names = char(M_.endo_names, 'rl');
M_.endo_names_tex = char(M_.endo_names_tex, 'rl');
M_.endo_names_long = char(M_.endo_names_long, 'rl');
M_.endo_names = char(M_.endo_names, 'ldpi1');
M_.endo_names_tex = char(M_.endo_names_tex, 'ldpi1');
M_.endo_names_long = char(M_.endo_names_long, 'ldpi1');
M_.endo_names = char(M_.endo_names, 'ldpi2');
M_.endo_names_tex = char(M_.endo_names_tex, 'ldpi2');
M_.endo_names_long = char(M_.endo_names_long, 'ldpi2');
M_.endo_names = char(M_.endo_names, 'ldpi3');
M_.endo_names_tex = char(M_.endo_names_tex, 'ldpi3');
M_.endo_names_long = char(M_.endo_names_long, 'ldpi3');
M_.endo_names = char(M_.endo_names, 'ldpi4');
M_.endo_names_tex = char(M_.endo_names_tex, 'ldpi4');
M_.endo_names_long = char(M_.endo_names_long, 'ldpi4');
M_.endo_names = char(M_.endo_names, 'ldpi5');
M_.endo_names_tex = char(M_.endo_names_tex, 'ldpi5');
M_.endo_names_long = char(M_.endo_names_long, 'ldpi5');
M_.endo_names = char(M_.endo_names, 'ldpi6');
M_.endo_names_tex = char(M_.endo_names_tex, 'ldpi6');
M_.endo_names_long = char(M_.endo_names_long, 'ldpi6');
M_.endo_names = char(M_.endo_names, 'ldpi7');
M_.endo_names_tex = char(M_.endo_names_tex, 'ldpi7');
M_.endo_names_long = char(M_.endo_names_long, 'ldpi7');
M_.endo_names = char(M_.endo_names, 'interest');
M_.endo_names_tex = char(M_.endo_names_tex, 'interest');
M_.endo_names_long = char(M_.endo_names_long, 'interest');
M_.endo_names = char(M_.endo_names, 'inflation');
M_.endo_names_tex = char(M_.endo_names_tex, 'inflation');
M_.endo_names_long = char(M_.endo_names_long, 'inflation');
M_.endo_names = char(M_.endo_names, 'inflationq');
M_.endo_names_tex = char(M_.endo_names_tex, 'inflationq');
M_.endo_names_long = char(M_.endo_names_long, 'inflationq');
M_.endo_names = char(M_.endo_names, 'outputgap');
M_.endo_names_tex = char(M_.endo_names_tex, 'outputgap');
M_.endo_names_long = char(M_.endo_names_long, 'outputgap');
M_.endo_names = char(M_.endo_names, 'output');
M_.endo_names_tex = char(M_.endo_names_tex, 'output');
M_.endo_names_long = char(M_.endo_names_long, 'output');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_72');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_72');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_72');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_76');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_76');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_76');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_80');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_80');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_80');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_107');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_107');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_107');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_111');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_111');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_111');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_115');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_115');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_115');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_142');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_142');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_142');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_146');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_146');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_146');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_150');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_150');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_150');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_35_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_35\_1');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_35_1');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_35_2');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_35\_2');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_35_2');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_35_3');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_35\_3');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_35_3');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_34_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_34\_1');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_34_1');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_34_2');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_34\_2');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_34_2');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_34_3');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_34\_3');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_34_3');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_31_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_31\_1');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_31_1');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_31_2');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_31\_2');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_31_2');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_31_3');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_31\_3');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_31_3');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_33_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_33\_1');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_33_1');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_33_2');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_33\_2');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_33_2');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_33_3');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_33\_3');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_33_3');
M_.endo_partitions = struct();
M_.param_names = 'cofintintb1';
M_.param_names_tex = 'cofintintb1';
M_.param_names_long = 'cofintintb1';
M_.param_names = char(M_.param_names, 'cofintintb2');
M_.param_names_tex = char(M_.param_names_tex, 'cofintintb2');
M_.param_names_long = char(M_.param_names_long, 'cofintintb2');
M_.param_names = char(M_.param_names, 'cofintintb3');
M_.param_names_tex = char(M_.param_names_tex, 'cofintintb3');
M_.param_names_long = char(M_.param_names_long, 'cofintintb3');
M_.param_names = char(M_.param_names, 'cofintintb4');
M_.param_names_tex = char(M_.param_names_tex, 'cofintintb4');
M_.param_names_long = char(M_.param_names_long, 'cofintintb4');
M_.param_names = char(M_.param_names, 'cofintinf0');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinf0');
M_.param_names_long = char(M_.param_names_long, 'cofintinf0');
M_.param_names = char(M_.param_names, 'cofintinfb1');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinfb1');
M_.param_names_long = char(M_.param_names_long, 'cofintinfb1');
M_.param_names = char(M_.param_names, 'cofintinfb2');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinfb2');
M_.param_names_long = char(M_.param_names_long, 'cofintinfb2');
M_.param_names = char(M_.param_names, 'cofintinfb3');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinfb3');
M_.param_names_long = char(M_.param_names_long, 'cofintinfb3');
M_.param_names = char(M_.param_names, 'cofintinfb4');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinfb4');
M_.param_names_long = char(M_.param_names_long, 'cofintinfb4');
M_.param_names = char(M_.param_names, 'cofintinff1');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinff1');
M_.param_names_long = char(M_.param_names_long, 'cofintinff1');
M_.param_names = char(M_.param_names, 'cofintinff2');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinff2');
M_.param_names_long = char(M_.param_names_long, 'cofintinff2');
M_.param_names = char(M_.param_names, 'cofintinff3');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinff3');
M_.param_names_long = char(M_.param_names_long, 'cofintinff3');
M_.param_names = char(M_.param_names, 'cofintinff4');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinff4');
M_.param_names_long = char(M_.param_names_long, 'cofintinff4');
M_.param_names = char(M_.param_names, 'cofintout');
M_.param_names_tex = char(M_.param_names_tex, 'cofintout');
M_.param_names_long = char(M_.param_names_long, 'cofintout');
M_.param_names = char(M_.param_names, 'cofintoutb1');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutb1');
M_.param_names_long = char(M_.param_names_long, 'cofintoutb1');
M_.param_names = char(M_.param_names, 'cofintoutb2');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutb2');
M_.param_names_long = char(M_.param_names_long, 'cofintoutb2');
M_.param_names = char(M_.param_names, 'cofintoutb3');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutb3');
M_.param_names_long = char(M_.param_names_long, 'cofintoutb3');
M_.param_names = char(M_.param_names, 'cofintoutb4');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutb4');
M_.param_names_long = char(M_.param_names_long, 'cofintoutb4');
M_.param_names = char(M_.param_names, 'cofintoutf1');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutf1');
M_.param_names_long = char(M_.param_names_long, 'cofintoutf1');
M_.param_names = char(M_.param_names, 'cofintoutf2');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutf2');
M_.param_names_long = char(M_.param_names_long, 'cofintoutf2');
M_.param_names = char(M_.param_names, 'cofintoutf3');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutf3');
M_.param_names_long = char(M_.param_names_long, 'cofintoutf3');
M_.param_names = char(M_.param_names, 'cofintoutf4');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutf4');
M_.param_names_long = char(M_.param_names_long, 'cofintoutf4');
M_.param_names = char(M_.param_names, 'cofintoutp');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutp');
M_.param_names_long = char(M_.param_names_long, 'cofintoutp');
M_.param_names = char(M_.param_names, 'cofintoutpb1');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpb1');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpb1');
M_.param_names = char(M_.param_names, 'cofintoutpb2');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpb2');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpb2');
M_.param_names = char(M_.param_names, 'cofintoutpb3');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpb3');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpb3');
M_.param_names = char(M_.param_names, 'cofintoutpb4');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpb4');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpb4');
M_.param_names = char(M_.param_names, 'cofintoutpf1');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpf1');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpf1');
M_.param_names = char(M_.param_names, 'cofintoutpf2');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpf2');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpf2');
M_.param_names = char(M_.param_names, 'cofintoutpf3');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpf3');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpf3');
M_.param_names = char(M_.param_names, 'cofintoutpf4');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpf4');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpf4');
M_.param_names = char(M_.param_names, 'std_r_');
M_.param_names_tex = char(M_.param_names_tex, 'std\_r\_');
M_.param_names_long = char(M_.param_names_long, 'std_r_');
M_.param_names = char(M_.param_names, 'std_r_quart');
M_.param_names_tex = char(M_.param_names_tex, 'std\_r\_quart');
M_.param_names_long = char(M_.param_names_long, 'std_r_quart');
M_.param_names = char(M_.param_names, 'coffispol');
M_.param_names_tex = char(M_.param_names_tex, 'coffispol');
M_.param_names_long = char(M_.param_names_long, 'coffispol');
M_.param_names = char(M_.param_names, 's');
M_.param_names_tex = char(M_.param_names_tex, 's');
M_.param_names_long = char(M_.param_names_long, 's');
M_.param_names = char(M_.param_names, 'f0');
M_.param_names_tex = char(M_.param_names_tex, 'f0');
M_.param_names_long = char(M_.param_names_long, 'f0');
M_.param_names = char(M_.param_names, 'f1');
M_.param_names_tex = char(M_.param_names_tex, 'f1');
M_.param_names_long = char(M_.param_names_long, 'f1');
M_.param_names = char(M_.param_names, 'f2');
M_.param_names_tex = char(M_.param_names_tex, 'f2');
M_.param_names_long = char(M_.param_names_long, 'f2');
M_.param_names = char(M_.param_names, 'f3');
M_.param_names_tex = char(M_.param_names_tex, 'f3');
M_.param_names_long = char(M_.param_names_long, 'f3');
M_.param_names = char(M_.param_names, 'gamma1');
M_.param_names_tex = char(M_.param_names_tex, 'gamma1');
M_.param_names_long = char(M_.param_names_long, 'gamma1');
M_.param_names = char(M_.param_names, 'sigma_e_cw');
M_.param_names_tex = char(M_.param_names_tex, 'sigma\_e\_cw');
M_.param_names_long = char(M_.param_names_long, 'sigma_e_cw');
M_.param_names = char(M_.param_names, 'delta0');
M_.param_names_tex = char(M_.param_names_tex, 'delta0');
M_.param_names_long = char(M_.param_names_long, 'delta0');
M_.param_names = char(M_.param_names, 'delta1');
M_.param_names_tex = char(M_.param_names_tex, 'delta1');
M_.param_names_long = char(M_.param_names_long, 'delta1');
M_.param_names = char(M_.param_names, 'delta2');
M_.param_names_tex = char(M_.param_names_tex, 'delta2');
M_.param_names_long = char(M_.param_names_long, 'delta2');
M_.param_names = char(M_.param_names, 'delta3');
M_.param_names_tex = char(M_.param_names_tex, 'delta3');
M_.param_names_long = char(M_.param_names_long, 'delta3');
M_.param_names = char(M_.param_names, 'sigma_e_d');
M_.param_names_tex = char(M_.param_names_tex, 'sigma\_e\_d');
M_.param_names_long = char(M_.param_names_long, 'sigma_e_d');
M_.param_partitions = struct();
M_.exo_det_nbr = 0;
M_.exo_nbr = 3;
M_.endo_nbr = 57;
M_.param_nbr = 46;
M_.orig_endo_nbr = 36;
M_.aux_vars(1).endo_index = 37;
M_.aux_vars(1).type = 0;
M_.aux_vars(2).endo_index = 38;
M_.aux_vars(2).type = 0;
M_.aux_vars(3).endo_index = 39;
M_.aux_vars(3).type = 0;
M_.aux_vars(4).endo_index = 40;
M_.aux_vars(4).type = 0;
M_.aux_vars(5).endo_index = 41;
M_.aux_vars(5).type = 0;
M_.aux_vars(6).endo_index = 42;
M_.aux_vars(6).type = 0;
M_.aux_vars(7).endo_index = 43;
M_.aux_vars(7).type = 0;
M_.aux_vars(8).endo_index = 44;
M_.aux_vars(8).type = 0;
M_.aux_vars(9).endo_index = 45;
M_.aux_vars(9).type = 0;
M_.aux_vars(10).endo_index = 46;
M_.aux_vars(10).type = 1;
M_.aux_vars(10).orig_index = 36;
M_.aux_vars(10).orig_lead_lag = -1;
M_.aux_vars(11).endo_index = 47;
M_.aux_vars(11).type = 1;
M_.aux_vars(11).orig_index = 36;
M_.aux_vars(11).orig_lead_lag = -2;
M_.aux_vars(12).endo_index = 48;
M_.aux_vars(12).type = 1;
M_.aux_vars(12).orig_index = 36;
M_.aux_vars(12).orig_lead_lag = -3;
M_.aux_vars(13).endo_index = 49;
M_.aux_vars(13).type = 1;
M_.aux_vars(13).orig_index = 35;
M_.aux_vars(13).orig_lead_lag = -1;
M_.aux_vars(14).endo_index = 50;
M_.aux_vars(14).type = 1;
M_.aux_vars(14).orig_index = 35;
M_.aux_vars(14).orig_lead_lag = -2;
M_.aux_vars(15).endo_index = 51;
M_.aux_vars(15).type = 1;
M_.aux_vars(15).orig_index = 35;
M_.aux_vars(15).orig_lead_lag = -3;
M_.aux_vars(16).endo_index = 52;
M_.aux_vars(16).type = 1;
M_.aux_vars(16).orig_index = 32;
M_.aux_vars(16).orig_lead_lag = -1;
M_.aux_vars(17).endo_index = 53;
M_.aux_vars(17).type = 1;
M_.aux_vars(17).orig_index = 32;
M_.aux_vars(17).orig_lead_lag = -2;
M_.aux_vars(18).endo_index = 54;
M_.aux_vars(18).type = 1;
M_.aux_vars(18).orig_index = 32;
M_.aux_vars(18).orig_lead_lag = -3;
M_.aux_vars(19).endo_index = 55;
M_.aux_vars(19).type = 1;
M_.aux_vars(19).orig_index = 34;
M_.aux_vars(19).orig_lead_lag = -1;
M_.aux_vars(20).endo_index = 56;
M_.aux_vars(20).type = 1;
M_.aux_vars(20).orig_index = 34;
M_.aux_vars(20).orig_lead_lag = -2;
M_.aux_vars(21).endo_index = 57;
M_.aux_vars(21).type = 1;
M_.aux_vars(21).orig_index = 34;
M_.aux_vars(21).orig_lead_lag = -3;
M_.Sigma_e = zeros(3, 3);
M_.Correlation_matrix = eye(3, 3);
M_.H = 0;
M_.Correlation_matrix_ME = 1;
M_.sigma_e_is_diagonal = 1;
M_.det_shocks = [];
options_.linear = 1;
options_.block=0;
options_.bytecode=0;
options_.use_dll=0;
M_.hessian_eq_zero = 1;
erase_compiled_function('EA_CW05fm_static');
erase_compiled_function('EA_CW05fm_dynamic');
M_.orig_eq_nbr = 36;
M_.eq_nbr = 57;
M_.ramsey_eq_nbr = 0;
M_.set_auxiliary_variables = exist(['./' M_.fname '_set_auxiliary_variables.m'], 'file') == 2;
M_.lead_lag_incidence = [
 1 27 84;
 2 28 0;
 3 29 0;
 0 30 85;
 0 31 86;
 0 32 87;
 0 33 88;
 0 34 89;
 4 35 0;
 5 36 0;
 6 37 90;
 7 38 0;
 8 39 0;
 0 40 0;
 9 41 91;
 0 42 0;
 0 43 0;
 0 44 92;
 0 45 93;
 0 46 94;
 0 47 95;
 0 48 96;
 0 49 97;
 10 50 0;
 0 51 98;
 0 52 99;
 0 53 100;
 0 54 101;
 0 55 102;
 0 56 103;
 0 57 104;
 11 58 0;
 0 59 0;
 12 60 105;
 13 61 106;
 14 62 107;
 0 63 108;
 0 64 109;
 0 65 110;
 0 66 111;
 0 67 112;
 0 68 113;
 0 69 114;
 0 70 115;
 0 71 116;
 15 72 0;
 16 73 0;
 17 74 0;
 18 75 0;
 19 76 0;
 20 77 0;
 21 78 0;
 22 79 0;
 23 80 0;
 24 81 0;
 25 82 0;
 26 83 0;]';
M_.nstatic = 4;
M_.nfwrd   = 27;
M_.npred   = 20;
M_.nboth   = 6;
M_.nsfwrd   = 33;
M_.nspred   = 26;
M_.ndynamic   = 53;
M_.equations_tags = {
};
M_.static_and_dynamic_models_differ = 0;
M_.exo_names_orig_ord = [1:3];
M_.maximum_lag = 1;
M_.maximum_lead = 1;
M_.maximum_endo_lag = 1;
M_.maximum_endo_lead = 1;
oo_.steady_state = zeros(57, 1);
M_.maximum_exo_lag = 0;
M_.maximum_exo_lead = 0;
oo_.exo_steady_state = zeros(3, 1);
M_.params = NaN(46, 1);
M_.NNZDerivatives = [183; 0; -1];
M_.params( 35 ) = 0.0742;
s = M_.params( 35 );
M_.params( 36 ) = 0.25+1.5*M_.params(35);
f0 = M_.params( 36 );
M_.params( 37 ) = 0.25+M_.params(35)*0.5;
f1 = M_.params( 37 );
M_.params( 38 ) = 0.25+M_.params(35)*(-0.5);
f2 = M_.params( 38 );
M_.params( 39 ) = 0.25+M_.params(35)*(-1.5);
f3 = M_.params( 39 );
M_.params( 40 ) = 0.0212;
gamma1 = M_.params( 40 );
M_.params( 42 ) = 0.0027;
delta0 = M_.params( 42 );
M_.params( 43 ) = 1.1807;
delta1 = M_.params( 43 );
M_.params( 44 ) = (-0.2045);
delta2 = M_.params( 44 );
M_.params( 45 ) = (-0.0947);
delta3 = M_.params( 45 );
M_.params( 46 ) = 1.00;
sigma_e_d = M_.params( 46 );
M_.params( 41 ) = 1.00;
sigma_e_cw = M_.params( 41 );
thispath = cd;                                                           
cd('..');                                                                
load policy_param.mat;                                                   
for i=1:33                                                               
deep_parameter_name = M_.param_names(i,:);                           
eval(['M_.params(i)  = ' deep_parameter_name ' ;'])                  
end                                                                      
cd(thispath);
M_.params( 32 ) = 100;
std_r_ = M_.params( 32 );
%
% SHOCKS instructions
%
M_.exo_det_length = 0;
M_.Sigma_e(1, 1) = 8.45144083918118e-06;
M_.Sigma_e(2, 2) = 2.88771222057358e-05;
M_.Sigma_e(1, 2) = (-3.58636858025215e-06);
M_.Sigma_e(2, 1) = M_.Sigma_e(1, 2);
M_.sigma_e_is_diagonal = 0;
save('EA_CW05fm_results.mat', 'oo_', 'M_', 'options_');
if exist('estim_params_', 'var') == 1
  save('EA_CW05fm_results.mat', 'estim_params_', '-append');
end
if exist('bayestopt_', 'var') == 1
  save('EA_CW05fm_results.mat', 'bayestopt_', '-append');
end
if exist('dataset_', 'var') == 1
  save('EA_CW05fm_results.mat', 'dataset_', '-append');
end
if exist('estimation_info', 'var') == 1
  save('EA_CW05fm_results.mat', 'estimation_info', '-append');
end
if exist('dataset_info', 'var') == 1
  save('EA_CW05fm_results.mat', 'dataset_info', '-append');
end
if exist('oo_recursive_', 'var') == 1
  save('EA_CW05fm_results.mat', 'oo_recursive_', '-append');
end


disp(['Total computing time : ' dynsec2hms(toc(tic0)) ]);
if ~isempty(lastwarn)
  disp('Note: warning(s) encountered in MATLAB/Octave code')
end
diary off
