%
% Status : main Dynare file 
%
% Warning : this file is generated automatically by Dynare
%           from model file (.mod)

tic;
global M_ oo_ options_ ys0_ ex0_ estimation_info
options_ = [];
M_.fname = 'US_FMS134';
%
% Some global variables initialization
%
global_initialization;
diary off;
diary('US_FMS134.log');
M_.exo_names = 'zetaz';
M_.exo_names_tex = 'zetaz';
M_.exo_names_long = 'zetaz';
M_.exo_names = char(M_.exo_names, 'zetab');
M_.exo_names_tex = char(M_.exo_names_tex, 'zetab');
M_.exo_names_long = char(M_.exo_names_long, 'zetab');
M_.exo_names = char(M_.exo_names, 'zetax');
M_.exo_names_tex = char(M_.exo_names_tex, 'zetax');
M_.exo_names_long = char(M_.exo_names_long, 'zetax');
M_.exo_names = char(M_.exo_names, 'zetap');
M_.exo_names_tex = char(M_.exo_names_tex, 'zetap');
M_.exo_names_long = char(M_.exo_names_long, 'zetap');
M_.exo_names = char(M_.exo_names, 'zetaw');
M_.exo_names_tex = char(M_.exo_names_tex, 'zetaw');
M_.exo_names_long = char(M_.exo_names_long, 'zetaw');
M_.exo_names = char(M_.exo_names, 'interest_');
M_.exo_names_tex = char(M_.exo_names_tex, 'interest\_');
M_.exo_names_long = char(M_.exo_names_long, 'interest_');
M_.exo_names = char(M_.exo_names, 'fiscal_');
M_.exo_names_tex = char(M_.exo_names_tex, 'fiscal\_');
M_.exo_names_long = char(M_.exo_names_long, 'fiscal_');
M_.endo_names = 'dyobs';
M_.endo_names_tex = 'dyobs';
M_.endo_names_long = 'dyobs';
M_.endo_names = char(M_.endo_names, 'dcobs');
M_.endo_names_tex = char(M_.endo_names_tex, 'dcobs');
M_.endo_names_long = char(M_.endo_names_long, 'dcobs');
M_.endo_names = char(M_.endo_names, 'dxobs');
M_.endo_names_tex = char(M_.endo_names_tex, 'dxobs');
M_.endo_names_long = char(M_.endo_names_long, 'dxobs');
M_.endo_names = char(M_.endo_names, 'dwobs');
M_.endo_names_tex = char(M_.endo_names_tex, 'dwobs');
M_.endo_names_long = char(M_.endo_names_long, 'dwobs');
M_.endo_names = char(M_.endo_names, 'inflobs');
M_.endo_names_tex = char(M_.endo_names_tex, 'inflobs');
M_.endo_names_long = char(M_.endo_names_long, 'inflobs');
M_.endo_names = char(M_.endo_names, 'robs');
M_.endo_names_tex = char(M_.endo_names_tex, 'robs');
M_.endo_names_long = char(M_.endo_names_long, 'robs');
M_.endo_names = char(M_.endo_names, 'labobs2');
M_.endo_names_tex = char(M_.endo_names_tex, 'labobs2');
M_.endo_names_long = char(M_.endo_names_long, 'labobs2');
M_.endo_names = char(M_.endo_names, 'dgobs');
M_.endo_names_tex = char(M_.endo_names_tex, 'dgobs');
M_.endo_names_long = char(M_.endo_names_long, 'dgobs');
M_.endo_names = char(M_.endo_names, 'y');
M_.endo_names_tex = char(M_.endo_names_tex, 'y');
M_.endo_names_long = char(M_.endo_names_long, 'y');
M_.endo_names = char(M_.endo_names, 'c');
M_.endo_names_tex = char(M_.endo_names_tex, 'c');
M_.endo_names_long = char(M_.endo_names_long, 'c');
M_.endo_names = char(M_.endo_names, 'x');
M_.endo_names_tex = char(M_.endo_names_tex, 'x');
M_.endo_names_long = char(M_.endo_names_long, 'x');
M_.endo_names = char(M_.endo_names, 'w');
M_.endo_names_tex = char(M_.endo_names_tex, 'w');
M_.endo_names_long = char(M_.endo_names_long, 'w');
M_.endo_names = char(M_.endo_names, 'infl');
M_.endo_names_tex = char(M_.endo_names_tex, 'infl');
M_.endo_names_long = char(M_.endo_names_long, 'infl');
M_.endo_names = char(M_.endo_names, 'r');
M_.endo_names_tex = char(M_.endo_names_tex, 'r');
M_.endo_names_long = char(M_.endo_names_long, 'r');
M_.endo_names = char(M_.endo_names, 'labor');
M_.endo_names_tex = char(M_.endo_names_tex, 'labor');
M_.endo_names_long = char(M_.endo_names_long, 'labor');
M_.endo_names = char(M_.endo_names, 'cstar');
M_.endo_names_tex = char(M_.endo_names_tex, 'cstar');
M_.endo_names_long = char(M_.endo_names_long, 'cstar');
M_.endo_names = char(M_.endo_names, 'k');
M_.endo_names_tex = char(M_.endo_names_tex, 'k');
M_.endo_names_long = char(M_.endo_names_long, 'k');
M_.endo_names = char(M_.endo_names, 'u');
M_.endo_names_tex = char(M_.endo_names_tex, 'u');
M_.endo_names_long = char(M_.endo_names_long, 'u');
M_.endo_names = char(M_.endo_names, 'kp');
M_.endo_names_tex = char(M_.endo_names_tex, 'kp');
M_.endo_names_long = char(M_.endo_names_long, 'kp');
M_.endo_names = char(M_.endo_names, 'lambda');
M_.endo_names_tex = char(M_.endo_names_tex, 'lambda');
M_.endo_names_long = char(M_.endo_names_long, 'lambda');
M_.endo_names = char(M_.endo_names, 'q');
M_.endo_names_tex = char(M_.endo_names_tex, 'q');
M_.endo_names_long = char(M_.endo_names_long, 'q');
M_.endo_names = char(M_.endo_names, 'rk');
M_.endo_names_tex = char(M_.endo_names_tex, 'rk');
M_.endo_names_long = char(M_.endo_names_long, 'rk');
M_.endo_names = char(M_.endo_names, 'mc');
M_.endo_names_tex = char(M_.endo_names_tex, 'mc');
M_.endo_names_long = char(M_.endo_names_long, 'mc');
M_.endo_names = char(M_.endo_names, 'g');
M_.endo_names_tex = char(M_.endo_names_tex, 'g');
M_.endo_names_long = char(M_.endo_names_long, 'g');
M_.endo_names = char(M_.endo_names, 'mrs');
M_.endo_names_tex = char(M_.endo_names_tex, 'mrs');
M_.endo_names_long = char(M_.endo_names_long, 'mrs');
M_.endo_names = char(M_.endo_names, 'yf');
M_.endo_names_tex = char(M_.endo_names_tex, 'yf');
M_.endo_names_long = char(M_.endo_names_long, 'yf');
M_.endo_names = char(M_.endo_names, 'cf');
M_.endo_names_tex = char(M_.endo_names_tex, 'cf');
M_.endo_names_long = char(M_.endo_names_long, 'cf');
M_.endo_names = char(M_.endo_names, 'xf');
M_.endo_names_tex = char(M_.endo_names_tex, 'xf');
M_.endo_names_long = char(M_.endo_names_long, 'xf');
M_.endo_names = char(M_.endo_names, 'wf');
M_.endo_names_tex = char(M_.endo_names_tex, 'wf');
M_.endo_names_long = char(M_.endo_names_long, 'wf');
M_.endo_names = char(M_.endo_names, 'rf');
M_.endo_names_tex = char(M_.endo_names_tex, 'rf');
M_.endo_names_long = char(M_.endo_names_long, 'rf');
M_.endo_names = char(M_.endo_names, 'laborf');
M_.endo_names_tex = char(M_.endo_names_tex, 'laborf');
M_.endo_names_long = char(M_.endo_names_long, 'laborf');
M_.endo_names = char(M_.endo_names, 'kf');
M_.endo_names_tex = char(M_.endo_names_tex, 'kf');
M_.endo_names_long = char(M_.endo_names_long, 'kf');
M_.endo_names = char(M_.endo_names, 'uf');
M_.endo_names_tex = char(M_.endo_names_tex, 'uf');
M_.endo_names_long = char(M_.endo_names_long, 'uf');
M_.endo_names = char(M_.endo_names, 'kpf');
M_.endo_names_tex = char(M_.endo_names_tex, 'kpf');
M_.endo_names_long = char(M_.endo_names_long, 'kpf');
M_.endo_names = char(M_.endo_names, 'lambdaf');
M_.endo_names_tex = char(M_.endo_names_tex, 'lambdaf');
M_.endo_names_long = char(M_.endo_names_long, 'lambdaf');
M_.endo_names = char(M_.endo_names, 'qf');
M_.endo_names_tex = char(M_.endo_names_tex, 'qf');
M_.endo_names_long = char(M_.endo_names_long, 'qf');
M_.endo_names = char(M_.endo_names, 'rkf');
M_.endo_names_tex = char(M_.endo_names_tex, 'rkf');
M_.endo_names_long = char(M_.endo_names_long, 'rkf');
M_.endo_names = char(M_.endo_names, 'gf');
M_.endo_names_tex = char(M_.endo_names_tex, 'gf');
M_.endo_names_long = char(M_.endo_names_long, 'gf');
M_.endo_names = char(M_.endo_names, 'cstarf');
M_.endo_names_tex = char(M_.endo_names_tex, 'cstarf');
M_.endo_names_long = char(M_.endo_names_long, 'cstarf');
M_.endo_names = char(M_.endo_names, 'infl4');
M_.endo_names_tex = char(M_.endo_names_tex, 'infl4');
M_.endo_names_long = char(M_.endo_names_long, 'infl4');
M_.endo_names = char(M_.endo_names, 'ez');
M_.endo_names_tex = char(M_.endo_names_tex, 'ez');
M_.endo_names_long = char(M_.endo_names_long, 'ez');
M_.endo_names = char(M_.endo_names, 'eb');
M_.endo_names_tex = char(M_.endo_names_tex, 'eb');
M_.endo_names_long = char(M_.endo_names_long, 'eb');
M_.endo_names = char(M_.endo_names, 'ex');
M_.endo_names_tex = char(M_.endo_names_tex, 'ex');
M_.endo_names_long = char(M_.endo_names_long, 'ex');
M_.endo_names = char(M_.endo_names, 'ep');
M_.endo_names_tex = char(M_.endo_names_tex, 'ep');
M_.endo_names_long = char(M_.endo_names_long, 'ep');
M_.endo_names = char(M_.endo_names, 'eg');
M_.endo_names_tex = char(M_.endo_names_tex, 'eg');
M_.endo_names_long = char(M_.endo_names_long, 'eg');
M_.endo_names = char(M_.endo_names, 'ew');
M_.endo_names_tex = char(M_.endo_names_tex, 'ew');
M_.endo_names_long = char(M_.endo_names_long, 'ew');
M_.endo_names = char(M_.endo_names, 'zetag');
M_.endo_names_tex = char(M_.endo_names_tex, 'zetag');
M_.endo_names_long = char(M_.endo_names_long, 'zetag');
M_.endo_names = char(M_.endo_names, 'interest');
M_.endo_names_tex = char(M_.endo_names_tex, 'interest');
M_.endo_names_long = char(M_.endo_names_long, 'interest');
M_.endo_names = char(M_.endo_names, 'inflation');
M_.endo_names_tex = char(M_.endo_names_tex, 'inflation');
M_.endo_names_long = char(M_.endo_names_long, 'inflation');
M_.endo_names = char(M_.endo_names, 'inflationq');
M_.endo_names_tex = char(M_.endo_names_tex, 'inflationq');
M_.endo_names_long = char(M_.endo_names_long, 'inflationq');
M_.endo_names = char(M_.endo_names, 'outputgap');
M_.endo_names_tex = char(M_.endo_names_tex, 'outputgap');
M_.endo_names_long = char(M_.endo_names_long, 'outputgap');
M_.endo_names = char(M_.endo_names, 'output');
M_.endo_names_tex = char(M_.endo_names_tex, 'output');
M_.endo_names_long = char(M_.endo_names_long, 'output');
M_.endo_names = char(M_.endo_names, 'fispol');
M_.endo_names_tex = char(M_.endo_names_tex, 'fispol');
M_.endo_names_long = char(M_.endo_names_long, 'fispol');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_73');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_73');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_73');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_77');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_77');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_77');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_81');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_81');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_81');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_108');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_108');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_108');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_112');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_112');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_112');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_116');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_116');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_116');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_143');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_143');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_143');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_147');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_147');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_147');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_151');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_151');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_151');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_232');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_232');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_232');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_370');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_370');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_370');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_51_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_51\_1');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_51_1');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_51_2');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_51\_2');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_51_2');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_51_3');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_51\_3');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_51_3');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_50_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_50\_1');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_50_1');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_50_2');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_50\_2');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_50_2');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_50_3');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_50\_3');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_50_3');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_47_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_47\_1');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_47_1');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_47_2');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_47\_2');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_47_2');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_47_3');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_47\_3');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_47_3');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_49_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_49\_1');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_49_1');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_49_2');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_49\_2');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_49_2');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_49_3');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_49\_3');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_49_3');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_12_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_12\_1');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_12_1');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_12_2');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_12\_2');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_12_2');
M_.param_names = 'cofintintb1';
M_.param_names_tex = 'cofintintb1';
M_.param_names_long = 'cofintintb1';
M_.param_names = char(M_.param_names, 'cofintintb2');
M_.param_names_tex = char(M_.param_names_tex, 'cofintintb2');
M_.param_names_long = char(M_.param_names_long, 'cofintintb2');
M_.param_names = char(M_.param_names, 'cofintintb3');
M_.param_names_tex = char(M_.param_names_tex, 'cofintintb3');
M_.param_names_long = char(M_.param_names_long, 'cofintintb3');
M_.param_names = char(M_.param_names, 'cofintintb4');
M_.param_names_tex = char(M_.param_names_tex, 'cofintintb4');
M_.param_names_long = char(M_.param_names_long, 'cofintintb4');
M_.param_names = char(M_.param_names, 'cofintinf0');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinf0');
M_.param_names_long = char(M_.param_names_long, 'cofintinf0');
M_.param_names = char(M_.param_names, 'cofintinfb1');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinfb1');
M_.param_names_long = char(M_.param_names_long, 'cofintinfb1');
M_.param_names = char(M_.param_names, 'cofintinfb2');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinfb2');
M_.param_names_long = char(M_.param_names_long, 'cofintinfb2');
M_.param_names = char(M_.param_names, 'cofintinfb3');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinfb3');
M_.param_names_long = char(M_.param_names_long, 'cofintinfb3');
M_.param_names = char(M_.param_names, 'cofintinfb4');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinfb4');
M_.param_names_long = char(M_.param_names_long, 'cofintinfb4');
M_.param_names = char(M_.param_names, 'cofintinff1');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinff1');
M_.param_names_long = char(M_.param_names_long, 'cofintinff1');
M_.param_names = char(M_.param_names, 'cofintinff2');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinff2');
M_.param_names_long = char(M_.param_names_long, 'cofintinff2');
M_.param_names = char(M_.param_names, 'cofintinff3');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinff3');
M_.param_names_long = char(M_.param_names_long, 'cofintinff3');
M_.param_names = char(M_.param_names, 'cofintinff4');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinff4');
M_.param_names_long = char(M_.param_names_long, 'cofintinff4');
M_.param_names = char(M_.param_names, 'cofintout');
M_.param_names_tex = char(M_.param_names_tex, 'cofintout');
M_.param_names_long = char(M_.param_names_long, 'cofintout');
M_.param_names = char(M_.param_names, 'cofintoutb1');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutb1');
M_.param_names_long = char(M_.param_names_long, 'cofintoutb1');
M_.param_names = char(M_.param_names, 'cofintoutb2');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutb2');
M_.param_names_long = char(M_.param_names_long, 'cofintoutb2');
M_.param_names = char(M_.param_names, 'cofintoutb3');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutb3');
M_.param_names_long = char(M_.param_names_long, 'cofintoutb3');
M_.param_names = char(M_.param_names, 'cofintoutb4');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutb4');
M_.param_names_long = char(M_.param_names_long, 'cofintoutb4');
M_.param_names = char(M_.param_names, 'cofintoutf1');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutf1');
M_.param_names_long = char(M_.param_names_long, 'cofintoutf1');
M_.param_names = char(M_.param_names, 'cofintoutf2');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutf2');
M_.param_names_long = char(M_.param_names_long, 'cofintoutf2');
M_.param_names = char(M_.param_names, 'cofintoutf3');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutf3');
M_.param_names_long = char(M_.param_names_long, 'cofintoutf3');
M_.param_names = char(M_.param_names, 'cofintoutf4');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutf4');
M_.param_names_long = char(M_.param_names_long, 'cofintoutf4');
M_.param_names = char(M_.param_names, 'cofintoutp');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutp');
M_.param_names_long = char(M_.param_names_long, 'cofintoutp');
M_.param_names = char(M_.param_names, 'cofintoutpb1');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpb1');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpb1');
M_.param_names = char(M_.param_names, 'cofintoutpb2');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpb2');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpb2');
M_.param_names = char(M_.param_names, 'cofintoutpb3');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpb3');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpb3');
M_.param_names = char(M_.param_names, 'cofintoutpb4');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpb4');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpb4');
M_.param_names = char(M_.param_names, 'cofintoutpf1');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpf1');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpf1');
M_.param_names = char(M_.param_names, 'cofintoutpf2');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpf2');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpf2');
M_.param_names = char(M_.param_names, 'cofintoutpf3');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpf3');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpf3');
M_.param_names = char(M_.param_names, 'cofintoutpf4');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpf4');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpf4');
M_.param_names = char(M_.param_names, 'std_r_');
M_.param_names_tex = char(M_.param_names_tex, 'std\_r\_');
M_.param_names_long = char(M_.param_names_long, 'std_r_');
M_.param_names = char(M_.param_names, 'std_r_quart');
M_.param_names_tex = char(M_.param_names_tex, 'std\_r\_quart');
M_.param_names_long = char(M_.param_names_long, 'std_r_quart');
M_.param_names = char(M_.param_names, 'coffispol');
M_.param_names_tex = char(M_.param_names_tex, 'coffispol');
M_.param_names_long = char(M_.param_names_long, 'coffispol');
M_.param_names = char(M_.param_names, 'gammaz');
M_.param_names_tex = char(M_.param_names_tex, 'gammaz');
M_.param_names_long = char(M_.param_names_long, 'gammaz');
M_.param_names = char(M_.param_names, 'psiu');
M_.param_names_tex = char(M_.param_names_tex, 'psiu');
M_.param_names_long = char(M_.param_names_long, 'psiu');
M_.param_names = char(M_.param_names, 'etak');
M_.param_names_tex = char(M_.param_names_tex, 'etak');
M_.param_names_long = char(M_.param_names_long, 'etak');
M_.param_names = char(M_.param_names, 'hab');
M_.param_names_tex = char(M_.param_names_tex, 'hab');
M_.param_names_long = char(M_.param_names_long, 'hab');
M_.param_names = char(M_.param_names, 'omega');
M_.param_names_tex = char(M_.param_names_tex, 'omega');
M_.param_names_long = char(M_.param_names_long, 'omega');
M_.param_names = char(M_.param_names, 'thetaw');
M_.param_names_tex = char(M_.param_names_tex, 'thetaw');
M_.param_names_long = char(M_.param_names_long, 'thetaw');
M_.param_names = char(M_.param_names, 'thetap');
M_.param_names_tex = char(M_.param_names_tex, 'thetap');
M_.param_names_long = char(M_.param_names_long, 'thetap');
M_.param_names = char(M_.param_names, 'gammaw');
M_.param_names_tex = char(M_.param_names_tex, 'gammaw');
M_.param_names_long = char(M_.param_names_long, 'gammaw');
M_.param_names = char(M_.param_names, 'gammap');
M_.param_names_tex = char(M_.param_names_tex, 'gammap');
M_.param_names_long = char(M_.param_names_long, 'gammap');
M_.param_names = char(M_.param_names, 'lambdap');
M_.param_names_tex = char(M_.param_names_tex, 'lambdap');
M_.param_names_long = char(M_.param_names_long, 'lambdap');
M_.param_names = char(M_.param_names, 'lambdaw');
M_.param_names_tex = char(M_.param_names_tex, 'lambdaw');
M_.param_names_long = char(M_.param_names_long, 'lambdaw');
M_.param_names = char(M_.param_names, 'rhoinfl');
M_.param_names_tex = char(M_.param_names_tex, 'rhoinfl');
M_.param_names_long = char(M_.param_names_long, 'rhoinfl');
M_.param_names = char(M_.param_names, 'rhoy');
M_.param_names_tex = char(M_.param_names_tex, 'rhoy');
M_.param_names_long = char(M_.param_names_long, 'rhoy');
M_.param_names = char(M_.param_names, 'rhody');
M_.param_names_tex = char(M_.param_names_tex, 'rhody');
M_.param_names_long = char(M_.param_names_long, 'rhody');
M_.param_names = char(M_.param_names, 'rhoz');
M_.param_names_tex = char(M_.param_names_tex, 'rhoz');
M_.param_names_long = char(M_.param_names_long, 'rhoz');
M_.param_names = char(M_.param_names, 'rhow');
M_.param_names_tex = char(M_.param_names_tex, 'rhow');
M_.param_names_long = char(M_.param_names_long, 'rhow');
M_.param_names = char(M_.param_names, 'rhob');
M_.param_names_tex = char(M_.param_names_tex, 'rhob');
M_.param_names_long = char(M_.param_names_long, 'rhob');
M_.param_names = char(M_.param_names, 'rhox');
M_.param_names_tex = char(M_.param_names_tex, 'rhox');
M_.param_names_long = char(M_.param_names_long, 'rhox');
M_.param_names = char(M_.param_names, 'rhop');
M_.param_names_tex = char(M_.param_names_tex, 'rhop');
M_.param_names_long = char(M_.param_names_long, 'rhop');
M_.param_names = char(M_.param_names, 'rhog');
M_.param_names_tex = char(M_.param_names_tex, 'rhog');
M_.param_names_long = char(M_.param_names_long, 'rhog');
M_.param_names = char(M_.param_names, 'consteinfl');
M_.param_names_tex = char(M_.param_names_tex, 'consteinfl');
M_.param_names_long = char(M_.param_names_long, 'consteinfl');
M_.param_names = char(M_.param_names, 'constelabor');
M_.param_names_tex = char(M_.param_names_tex, 'constelabor');
M_.param_names_long = char(M_.param_names_long, 'constelabor');
M_.param_names = char(M_.param_names, 'conster');
M_.param_names_tex = char(M_.param_names_tex, 'conster');
M_.param_names_long = char(M_.param_names_long, 'conster');
M_.param_names = char(M_.param_names, 'delta');
M_.param_names_tex = char(M_.param_names_tex, 'delta');
M_.param_names_long = char(M_.param_names_long, 'delta');
M_.param_names = char(M_.param_names, 'alpha');
M_.param_names_tex = char(M_.param_names_tex, 'alpha');
M_.param_names_long = char(M_.param_names_long, 'alpha');
M_.param_names = char(M_.param_names, 'gsy');
M_.param_names_tex = char(M_.param_names_tex, 'gsy');
M_.param_names_long = char(M_.param_names_long, 'gsy');
M_.param_names = char(M_.param_names, 'beta');
M_.param_names_tex = char(M_.param_names_tex, 'beta');
M_.param_names_long = char(M_.param_names_long, 'beta');
M_.param_names = char(M_.param_names, 'alphag');
M_.param_names_tex = char(M_.param_names_tex, 'alphag');
M_.param_names_long = char(M_.param_names_long, 'alphag');
M_.param_names = char(M_.param_names, 'phig');
M_.param_names_tex = char(M_.param_names_tex, 'phig');
M_.param_names_long = char(M_.param_names_long, 'phig');
M_.param_names = char(M_.param_names, 'egamma');
M_.param_names_tex = char(M_.param_names_tex, 'egamma');
M_.param_names_long = char(M_.param_names_long, 'egamma');
M_.param_names = char(M_.param_names, 'rkbar');
M_.param_names_tex = char(M_.param_names_tex, 'rkbar');
M_.param_names_long = char(M_.param_names_long, 'rkbar');
M_.param_names = char(M_.param_names, 'wbar');
M_.param_names_tex = char(M_.param_names_tex, 'wbar');
M_.param_names_long = char(M_.param_names_long, 'wbar');
M_.param_names = char(M_.param_names, 'ksl');
M_.param_names_tex = char(M_.param_names_tex, 'ksl');
M_.param_names_long = char(M_.param_names_long, 'ksl');
M_.param_names = char(M_.param_names, 'fsl');
M_.param_names_tex = char(M_.param_names_tex, 'fsl');
M_.param_names_long = char(M_.param_names_long, 'fsl');
M_.param_names = char(M_.param_names, 'ysl');
M_.param_names_tex = char(M_.param_names_tex, 'ysl');
M_.param_names_long = char(M_.param_names_long, 'ysl');
M_.param_names = char(M_.param_names, 'fsy');
M_.param_names_tex = char(M_.param_names_tex, 'fsy');
M_.param_names_long = char(M_.param_names_long, 'fsy');
M_.param_names = char(M_.param_names, 'xsl');
M_.param_names_tex = char(M_.param_names_tex, 'xsl');
M_.param_names_long = char(M_.param_names_long, 'xsl');
M_.param_names = char(M_.param_names, 'xsy');
M_.param_names_tex = char(M_.param_names_tex, 'xsy');
M_.param_names_long = char(M_.param_names_long, 'xsy');
M_.param_names = char(M_.param_names, 'csy');
M_.param_names_tex = char(M_.param_names_tex, 'csy');
M_.param_names_long = char(M_.param_names_long, 'csy');
M_.param_names = char(M_.param_names, 'ksy');
M_.param_names_tex = char(M_.param_names_tex, 'ksy');
M_.param_names_long = char(M_.param_names_long, 'ksy');
M_.param_names = char(M_.param_names, 'kappa');
M_.param_names_tex = char(M_.param_names_tex, 'kappa');
M_.param_names_long = char(M_.param_names_long, 'kappa');
M_.param_names = char(M_.param_names, 'kappaw');
M_.param_names_tex = char(M_.param_names_tex, 'kappaw');
M_.param_names_long = char(M_.param_names_long, 'kappaw');
M_.param_names = char(M_.param_names, 'etau');
M_.param_names_tex = char(M_.param_names_tex, 'etau');
M_.param_names_long = char(M_.param_names_long, 'etau');
M_.exo_det_nbr = 0;
M_.exo_nbr = 7;
M_.endo_nbr = 78;
M_.param_nbr = 77;
M_.orig_endo_nbr = 53;
M_.aux_vars(1).endo_index = 54;
M_.aux_vars(1).type = 0;
M_.aux_vars(2).endo_index = 55;
M_.aux_vars(2).type = 0;
M_.aux_vars(3).endo_index = 56;
M_.aux_vars(3).type = 0;
M_.aux_vars(4).endo_index = 57;
M_.aux_vars(4).type = 0;
M_.aux_vars(5).endo_index = 58;
M_.aux_vars(5).type = 0;
M_.aux_vars(6).endo_index = 59;
M_.aux_vars(6).type = 0;
M_.aux_vars(7).endo_index = 60;
M_.aux_vars(7).type = 0;
M_.aux_vars(8).endo_index = 61;
M_.aux_vars(8).type = 0;
M_.aux_vars(9).endo_index = 62;
M_.aux_vars(9).type = 0;
M_.aux_vars(10).endo_index = 63;
M_.aux_vars(10).type = 0;
M_.aux_vars(11).endo_index = 64;
M_.aux_vars(11).type = 0;
M_.aux_vars(12).endo_index = 65;
M_.aux_vars(12).type = 1;
M_.aux_vars(12).orig_index = 52;
M_.aux_vars(12).orig_lead_lag = -1;
M_.aux_vars(13).endo_index = 66;
M_.aux_vars(13).type = 1;
M_.aux_vars(13).orig_index = 52;
M_.aux_vars(13).orig_lead_lag = -2;
M_.aux_vars(14).endo_index = 67;
M_.aux_vars(14).type = 1;
M_.aux_vars(14).orig_index = 52;
M_.aux_vars(14).orig_lead_lag = -3;
M_.aux_vars(15).endo_index = 68;
M_.aux_vars(15).type = 1;
M_.aux_vars(15).orig_index = 51;
M_.aux_vars(15).orig_lead_lag = -1;
M_.aux_vars(16).endo_index = 69;
M_.aux_vars(16).type = 1;
M_.aux_vars(16).orig_index = 51;
M_.aux_vars(16).orig_lead_lag = -2;
M_.aux_vars(17).endo_index = 70;
M_.aux_vars(17).type = 1;
M_.aux_vars(17).orig_index = 51;
M_.aux_vars(17).orig_lead_lag = -3;
M_.aux_vars(18).endo_index = 71;
M_.aux_vars(18).type = 1;
M_.aux_vars(18).orig_index = 48;
M_.aux_vars(18).orig_lead_lag = -1;
M_.aux_vars(19).endo_index = 72;
M_.aux_vars(19).type = 1;
M_.aux_vars(19).orig_index = 48;
M_.aux_vars(19).orig_lead_lag = -2;
M_.aux_vars(20).endo_index = 73;
M_.aux_vars(20).type = 1;
M_.aux_vars(20).orig_index = 48;
M_.aux_vars(20).orig_lead_lag = -3;
M_.aux_vars(21).endo_index = 74;
M_.aux_vars(21).type = 1;
M_.aux_vars(21).orig_index = 50;
M_.aux_vars(21).orig_lead_lag = -1;
M_.aux_vars(22).endo_index = 75;
M_.aux_vars(22).type = 1;
M_.aux_vars(22).orig_index = 50;
M_.aux_vars(22).orig_lead_lag = -2;
M_.aux_vars(23).endo_index = 76;
M_.aux_vars(23).type = 1;
M_.aux_vars(23).orig_index = 50;
M_.aux_vars(23).orig_lead_lag = -3;
M_.aux_vars(24).endo_index = 77;
M_.aux_vars(24).type = 1;
M_.aux_vars(24).orig_index = 13;
M_.aux_vars(24).orig_lead_lag = -1;
M_.aux_vars(25).endo_index = 78;
M_.aux_vars(25).type = 1;
M_.aux_vars(25).orig_index = 13;
M_.aux_vars(25).orig_lead_lag = -2;
M_.Sigma_e = zeros(7, 7);
M_.Correlation_matrix = eye(7, 7);
M_.H = 0;
M_.Correlation_matrix_ME = 1;
M_.sigma_e_is_diagonal = 1;
options_.linear = 1;
options_.block=0;
options_.bytecode=0;
options_.use_dll=0;
erase_compiled_function('US_FMS134_static');
erase_compiled_function('US_FMS134_dynamic');
M_.lead_lag_incidence = [
 0 37 0;
 0 38 0;
 0 39 0;
 0 40 0;
 0 41 0;
 0 42 0;
 0 43 0;
 0 44 0;
 1 45 0;
 2 46 0;
 3 47 115;
 4 48 116;
 5 49 117;
 0 50 0;
 0 51 0;
 6 52 118;
 0 53 0;
 0 54 0;
 7 55 0;
 0 56 0;
 0 57 119;
 0 58 120;
 0 59 0;
 8 60 0;
 0 61 0;
 9 62 0;
 0 63 0;
 10 64 121;
 0 65 0;
 0 66 0;
 0 67 0;
 0 68 0;
 0 69 0;
 11 70 0;
 0 71 0;
 0 72 122;
 0 73 123;
 0 74 0;
 12 75 124;
 0 76 0;
 13 77 125;
 14 78 0;
 15 79 0;
 16 80 0;
 17 81 0;
 18 82 0;
 0 83 0;
 19 84 0;
 0 85 0;
 20 86 126;
 21 87 127;
 22 88 128;
 0 89 0;
 0 90 129;
 0 91 130;
 0 92 131;
 0 93 132;
 0 94 133;
 0 95 134;
 0 96 135;
 0 97 136;
 0 98 137;
 0 99 138;
 0 100 139;
 23 101 0;
 24 102 0;
 25 103 0;
 26 104 0;
 27 105 0;
 28 106 0;
 29 107 0;
 30 108 0;
 31 109 0;
 32 110 0;
 33 111 0;
 34 112 0;
 35 113 0;
 36 114 0;]';
M_.nstatic = 27;
M_.nfwrd   = 15;
M_.npred   = 26;
M_.nboth   = 10;
M_.nsfwrd   = 25;
M_.nspred   = 36;
M_.ndynamic   = 51;
M_.equations_tags = {
};
M_.static_and_dynamic_models_differ = 0;
M_.exo_names_orig_ord = [1:7];
M_.maximum_lag = 1;
M_.maximum_lead = 1;
M_.maximum_endo_lag = 1;
M_.maximum_endo_lead = 1;
oo_.steady_state = zeros(78, 1);
M_.maximum_exo_lag = 0;
M_.maximum_exo_lead = 0;
oo_.exo_steady_state = zeros(7, 1);
M_.params = NaN(77, 1);
M_.NNZDerivatives = zeros(3, 1);
M_.NNZDerivatives(1) = 287;
M_.NNZDerivatives(2) = 0;
M_.NNZDerivatives(3) = -1;
M_.params( 61 ) = 0.99;
beta = M_.params( 61 );
M_.params( 58 ) = 0.025;
delta = M_.params( 58 );
M_.params( 60 ) = 0.20;
gsy = M_.params( 60 );
M_.params( 45 ) = 0.15;
lambdaw = M_.params( 45 );
M_.params( 63 ) = 0.7871;
phig = M_.params( 63 );
M_.params( 59 ) = 0.2037;
alpha = M_.params( 59 );
M_.params( 35 ) = 0.4475;
gammaz = M_.params( 35 );
M_.params( 62 ) = (-0.6743);
alphag = M_.params( 62 );
M_.params( 36 ) = 0.7275;
psiu = M_.params( 36 );
M_.params( 37 ) = 5.1673;
etak = M_.params( 37 );
M_.params( 39 ) = 2.9482;
omega = M_.params( 39 );
M_.params( 38 ) = 0.6287;
hab = M_.params( 38 );
M_.params( 40 ) = 0.8824;
thetaw = M_.params( 40 );
M_.params( 41 ) = 0.8635;
thetap = M_.params( 41 );
M_.params( 42 ) = 0.7153;
gammaw = M_.params( 42 );
M_.params( 43 ) = 0.0903;
gammap = M_.params( 43 );
M_.params( 44 ) = 0.2419;
lambdap = M_.params( 44 );
M_.params( 46 ) = 1.5189;
rhoinfl = M_.params( 46 );
M_.params( 47 ) = 0.0075;
rhoy = M_.params( 47 );
M_.params( 48 ) = 0.2394;
rhody = M_.params( 48 );
M_.params( 49 ) = 0.1667;
rhoz = M_.params( 49 );
M_.params( 51 ) = 0.8024;
rhob = M_.params( 51 );
M_.params( 52 ) = 0.9498;
rhox = M_.params( 52 );
M_.params( 53 ) = 0.8669;
rhop = M_.params( 53 );
M_.params( 54 ) = 0.9724;
rhog = M_.params( 54 );
M_.params( 50 ) = 0.2376;
rhow = M_.params( 50 );
M_.params( 55 ) = 0.7341;
consteinfl = M_.params( 55 );
M_.params( 56 ) = (-0.4306);
constelabor = M_.params( 56 );
M_.params( 57 ) = 1.2285;
conster = M_.params( 57 );
M_.params( 64 ) = exp(M_.params(35)/100);
egamma = M_.params( 64 );
M_.params( 65 ) = M_.params(64)/M_.params(61)-(1-M_.params(58));
rkbar = M_.params( 65 );
M_.params( 66 ) = (1/(1+M_.params(44))*M_.params(59)^M_.params(59)*(1-M_.params(59))^(1-M_.params(59))/M_.params(65)^M_.params(59))^(1/(1-M_.params(59)));
wbar = M_.params( 66 );
M_.params( 67 ) = M_.params(59)*M_.params(66)/M_.params(65)/(1-M_.params(59));
ksl = M_.params( 67 );
M_.params( 68 ) = M_.params(67)^M_.params(59)-M_.params(66)-M_.params(65)*M_.params(67);
fsl = M_.params( 68 );
M_.params( 69 ) = M_.params(67)^M_.params(59)-M_.params(68);
ysl = M_.params( 69 );
M_.params( 70 ) = M_.params(68)/M_.params(69);
fsy = M_.params( 70 );
M_.params( 71 ) = M_.params(67)*M_.params(64)*(1-(1-M_.params(58))/M_.params(64));
xsl = M_.params( 71 );
M_.params( 72 ) = M_.params(71)/M_.params(69);
xsy = M_.params( 72 );
M_.params( 73 ) = 1-M_.params(72)-M_.params(60);
csy = M_.params( 73 );
M_.params( 74 ) = M_.params(67)/M_.params(69);
ksy = M_.params( 74 );
M_.params( 75 ) = (1-M_.params(61)*M_.params(41))*(1-M_.params(41))/(M_.params(41)*(1+M_.params(61)*M_.params(43)));
kappa = M_.params( 75 );
M_.params( 76 ) = (1-M_.params(61)*M_.params(40))*(1-M_.params(40))/(M_.params(40)*(1+M_.params(61))*(1+M_.params(39)*(1+1/M_.params(45))));
kappaw = M_.params( 76 );
M_.params( 77 ) = (1-M_.params(36))/M_.params(36);
etau = M_.params( 77 );
thispath = cd;                                                           
cd('..');                                                                
load policy_param.mat;                                                   
for i=1:33                                                               
deep_parameter_name = M_.param_names(i,:);                           
eval(['M_.params(i)  = ' deep_parameter_name ' ;'])                  
end                                                                      
cd(thispath);                                                             
M_.params( 34 ) = 1/M_.params(60);
coffispol = M_.params( 34 );
%
% SHOCKS instructions
%
make_ex_;
M_.exo_det_length = 0;
M_.Sigma_e(1, 1) = (0.9400)^2;
M_.Sigma_e(2, 2) = (0.0389)^2;
M_.Sigma_e(3, 3) = (0.4370)^2;
M_.Sigma_e(4, 4) = (0.0589)^2;
M_.Sigma_e(5, 5) = (0.2431)^2;
M_.Sigma_e(7, 7) = (1.2199)^2;
save('US_FMS134_results.mat', 'oo_', 'M_', 'options_');
if exist('estim_params_', 'var') == 1
  save('US_FMS134_results.mat', 'estim_params_', '-append');
end
if exist('bayestopt_', 'var') == 1
  save('US_FMS134_results.mat', 'bayestopt_', '-append');
end
if exist('dataset_', 'var') == 1
  save('US_FMS134_results.mat', 'dataset_', '-append');
end
if exist('estimation_info', 'var') == 1
  save('US_FMS134_results.mat', 'estimation_info', '-append');
end


disp(['Total computing time : ' dynsec2hms(toc) ]);
if ~isempty(lastwarn)
  disp('Note: warning(s) encountered in MATLAB/Octave code')
end
diary off
