%
% Status : main Dynare file 
%
% Warning : this file is generated automatically by Dynare
%           from model file (.mod)

tic;
global M_ oo_ options_ ys0_ ex0_ estimation_info
options_ = [];
M_.fname = 'G2_SIGMA08';
%
% Some global variables initialization
%
global_initialization;
diary off;
diary('G2_SIGMA08.log');
M_.exo_names = 'erratp';
M_.exo_names_tex = 'erratp';
M_.exo_names_long = 'erratp';
M_.exo_names = char(M_.exo_names, 'erratt');
M_.exo_names_tex = char(M_.exo_names_tex, 'erratt');
M_.exo_names_long = char(M_.exo_names_long, 'erratt');
M_.exo_names = char(M_.exo_names, 'errgcxp');
M_.exo_names_tex = char(M_.exo_names_tex, 'errgcxp');
M_.exo_names_long = char(M_.exo_names_long, 'errgcxp');
M_.exo_names = char(M_.exo_names, 'errpitarp');
M_.exo_names_tex = char(M_.exo_names_tex, 'errpitarp');
M_.exo_names_long = char(M_.exo_names_long, 'errpitarp');
M_.exo_names = char(M_.exo_names, 'errpitart');
M_.exo_names_tex = char(M_.exo_names_tex, 'errpitart');
M_.exo_names_long = char(M_.exo_names_long, 'errpitart');
M_.exo_names = char(M_.exo_names, 'errconshkp');
M_.exo_names_tex = char(M_.exo_names_tex, 'errconshkp');
M_.exo_names_long = char(M_.exo_names_long, 'errconshkp');
M_.exo_names = char(M_.exo_names, 'errconshkt');
M_.exo_names_tex = char(M_.exo_names_tex, 'errconshkt');
M_.exo_names_long = char(M_.exo_names_long, 'errconshkt');
M_.exo_names = char(M_.exo_names, 'errtaxkp');
M_.exo_names_tex = char(M_.exo_names_tex, 'errtaxkp');
M_.exo_names_long = char(M_.exo_names_long, 'errtaxkp');
M_.exo_names = char(M_.exo_names, 'errtaxkt');
M_.exo_names_tex = char(M_.exo_names_tex, 'errtaxkt');
M_.exo_names_long = char(M_.exo_names_long, 'errtaxkt');
M_.exo_names = char(M_.exo_names, 'errtranshkp');
M_.exo_names_tex = char(M_.exo_names_tex, 'errtranshkp');
M_.exo_names_long = char(M_.exo_names_long, 'errtranshkp');
M_.exo_names = char(M_.exo_names, 'errtranshkt');
M_.exo_names_tex = char(M_.exo_names_tex, 'errtranshkt');
M_.exo_names_long = char(M_.exo_names_long, 'errtranshkt');
M_.exo_names = char(M_.exo_names, 'erratpf');
M_.exo_names_tex = char(M_.exo_names_tex, 'erratpf');
M_.exo_names_long = char(M_.exo_names_long, 'erratpf');
M_.exo_names = char(M_.exo_names, 'errattf');
M_.exo_names_tex = char(M_.exo_names_tex, 'errattf');
M_.exo_names_long = char(M_.exo_names_long, 'errattf');
M_.exo_names = char(M_.exo_names, 'errgcxpf');
M_.exo_names_tex = char(M_.exo_names_tex, 'errgcxpf');
M_.exo_names_long = char(M_.exo_names_long, 'errgcxpf');
M_.exo_names = char(M_.exo_names, 'errgcxtf');
M_.exo_names_tex = char(M_.exo_names_tex, 'errgcxtf');
M_.exo_names_long = char(M_.exo_names_long, 'errgcxtf');
M_.exo_names = char(M_.exo_names, 'errpitarpf');
M_.exo_names_tex = char(M_.exo_names_tex, 'errpitarpf');
M_.exo_names_long = char(M_.exo_names_long, 'errpitarpf');
M_.exo_names = char(M_.exo_names, 'errpitartf');
M_.exo_names_tex = char(M_.exo_names_tex, 'errpitartf');
M_.exo_names_long = char(M_.exo_names_long, 'errpitartf');
M_.exo_names = char(M_.exo_names, 'errconshkpf');
M_.exo_names_tex = char(M_.exo_names_tex, 'errconshkpf');
M_.exo_names_long = char(M_.exo_names_long, 'errconshkpf');
M_.exo_names = char(M_.exo_names, 'errconshktf');
M_.exo_names_tex = char(M_.exo_names_tex, 'errconshktf');
M_.exo_names_long = char(M_.exo_names_long, 'errconshktf');
M_.exo_names = char(M_.exo_names, 'errtaxkpf');
M_.exo_names_tex = char(M_.exo_names_tex, 'errtaxkpf');
M_.exo_names_long = char(M_.exo_names_long, 'errtaxkpf');
M_.exo_names = char(M_.exo_names, 'errtaxktf');
M_.exo_names_tex = char(M_.exo_names_tex, 'errtaxktf');
M_.exo_names_long = char(M_.exo_names_long, 'errtaxktf');
M_.exo_names = char(M_.exo_names, 'errtranshkpf');
M_.exo_names_tex = char(M_.exo_names_tex, 'errtranshkpf');
M_.exo_names_long = char(M_.exo_names_long, 'errtranshkpf');
M_.exo_names = char(M_.exo_names, 'errtranshktf');
M_.exo_names_tex = char(M_.exo_names_tex, 'errtranshktf');
M_.exo_names_long = char(M_.exo_names_long, 'errtranshktf');
M_.exo_names = char(M_.exo_names, 'errriskpp');
M_.exo_names_tex = char(M_.exo_names_tex, 'errriskpp');
M_.exo_names_long = char(M_.exo_names_long, 'errriskpp');
M_.exo_names = char(M_.exo_names, 'errriskpt');
M_.exo_names_tex = char(M_.exo_names_tex, 'errriskpt');
M_.exo_names_long = char(M_.exo_names_long, 'errriskpt');
M_.exo_names = char(M_.exo_names, 'errbetashk');
M_.exo_names_tex = char(M_.exo_names_tex, 'errbetashk');
M_.exo_names_long = char(M_.exo_names_long, 'errbetashk');
M_.exo_names = char(M_.exo_names, 'errbetashkf');
M_.exo_names_tex = char(M_.exo_names_tex, 'errbetashkf');
M_.exo_names_long = char(M_.exo_names_long, 'errbetashkf');
M_.exo_names = char(M_.exo_names, 'errimpshk');
M_.exo_names_tex = char(M_.exo_names_tex, 'errimpshk');
M_.exo_names_long = char(M_.exo_names_long, 'errimpshk');
M_.exo_names = char(M_.exo_names, 'errimpshkf');
M_.exo_names_tex = char(M_.exo_names_tex, 'errimpshkf');
M_.exo_names_long = char(M_.exo_names_long, 'errimpshkf');
M_.exo_names = char(M_.exo_names, 'errtaxlshk');
M_.exo_names_tex = char(M_.exo_names_tex, 'errtaxlshk');
M_.exo_names_long = char(M_.exo_names_long, 'errtaxlshk');
M_.exo_names = char(M_.exo_names, 'errtaxlshkpf');
M_.exo_names_tex = char(M_.exo_names_tex, 'errtaxlshkpf');
M_.exo_names_long = char(M_.exo_names_long, 'errtaxlshkpf');
M_.exo_names = char(M_.exo_names, 'errtaxlshktf');
M_.exo_names_tex = char(M_.exo_names_tex, 'errtaxlshktf');
M_.exo_names_long = char(M_.exo_names_long, 'errtaxlshktf');
M_.exo_names = char(M_.exo_names, 'interest_');
M_.exo_names_tex = char(M_.exo_names_tex, 'interest\_');
M_.exo_names_long = char(M_.exo_names_long, 'interest_');
M_.exo_names = char(M_.exo_names, 'fiscal_');
M_.exo_names_tex = char(M_.exo_names_tex, 'fiscal\_');
M_.exo_names_long = char(M_.exo_names_long, 'fiscal_');
M_.endo_names = 'cc';
M_.endo_names_tex = 'cc';
M_.endo_names_long = 'cc';
M_.endo_names = char(M_.endo_names, 'sp2gdp');
M_.endo_names_tex = char(M_.endo_names_tex, 'sp2gdp');
M_.endo_names_long = char(M_.endo_names_long, 'sp2gdp');
M_.endo_names = char(M_.endo_names, 'cc2gdp');
M_.endo_names_tex = char(M_.endo_names_tex, 'cc2gdp');
M_.endo_names_long = char(M_.endo_names_long, 'cc2gdp');
M_.endo_names = char(M_.endo_names, 'if');
M_.endo_names_tex = char(M_.endo_names_tex, 'if');
M_.endo_names_long = char(M_.endo_names_long, 'if');
M_.endo_names = char(M_.endo_names, 'if2gdp');
M_.endo_names_tex = char(M_.endo_names_tex, 'if2gdp');
M_.endo_names_long = char(M_.endo_names_long, 'if2gdp');
M_.endo_names = char(M_.endo_names, 'tobq');
M_.endo_names_tex = char(M_.endo_names_tex, 'tobq');
M_.endo_names_long = char(M_.endo_names_long, 'tobq');
M_.endo_names = char(M_.endo_names, 'kp');
M_.endo_names_tex = char(M_.endo_names_tex, 'kp');
M_.endo_names_long = char(M_.endo_names_long, 'kp');
M_.endo_names = char(M_.endo_names, 'kp1');
M_.endo_names_tex = char(M_.endo_names_tex, 'kp1');
M_.endo_names_long = char(M_.endo_names_long, 'kp1');
M_.endo_names = char(M_.endo_names, 'rentks');
M_.endo_names_tex = char(M_.endo_names_tex, 'rentks');
M_.endo_names_long = char(M_.endo_names_long, 'rentks');
M_.endo_names = char(M_.endo_names, 'gdp');
M_.endo_names_tex = char(M_.endo_names_tex, 'gdp');
M_.endo_names_long = char(M_.endo_names_long, 'gdp');
M_.endo_names = char(M_.endo_names, 'ccd');
M_.endo_names_tex = char(M_.endo_names_tex, 'ccd');
M_.endo_names_long = char(M_.endo_names_long, 'ccd');
M_.endo_names = char(M_.endo_names, 'ifd');
M_.endo_names_tex = char(M_.endo_names_tex, 'ifd');
M_.endo_names_long = char(M_.endo_names_long, 'ifd');
M_.endo_names = char(M_.endo_names, 'mgsni');
M_.endo_names_tex = char(M_.endo_names_tex, 'mgsni');
M_.endo_names_long = char(M_.endo_names_long, 'mgsni');
M_.endo_names = char(M_.endo_names, 'mgsnic');
M_.endo_names_tex = char(M_.endo_names_tex, 'mgsnic');
M_.endo_names_long = char(M_.endo_names_long, 'mgsnic');
M_.endo_names = char(M_.endo_names, 'mgsnii');
M_.endo_names_tex = char(M_.endo_names_tex, 'mgsnii');
M_.endo_names_long = char(M_.endo_names_long, 'mgsnii');
M_.endo_names = char(M_.endo_names, 'rmc');
M_.endo_names_tex = char(M_.endo_names_tex, 'rmc');
M_.endo_names_long = char(M_.endo_names_long, 'rmc');
M_.endo_names = char(M_.endo_names, 'rmi');
M_.endo_names_tex = char(M_.endo_names_tex, 'rmi');
M_.endo_names_long = char(M_.endo_names_long, 'rmi');
M_.endo_names = char(M_.endo_names, 'rs');
M_.endo_names_tex = char(M_.endo_names_tex, 'rs');
M_.endo_names_long = char(M_.endo_names_long, 'rs');
M_.endo_names = char(M_.endo_names, 'mcq');
M_.endo_names_tex = char(M_.endo_names_tex, 'mcq');
M_.endo_names_long = char(M_.endo_names_long, 'mcq');
M_.endo_names = char(M_.endo_names, 'mpl');
M_.endo_names_tex = char(M_.endo_names_tex, 'mpl');
M_.endo_names_long = char(M_.endo_names_long, 'mpl');
M_.endo_names = char(M_.endo_names, 'wmarkup');
M_.endo_names_tex = char(M_.endo_names_tex, 'wmarkup');
M_.endo_names_long = char(M_.endo_names_long, 'wmarkup');
M_.endo_names = char(M_.endo_names, 'mrs');
M_.endo_names_tex = char(M_.endo_names_tex, 'mrs');
M_.endo_names_long = char(M_.endo_names_long, 'mrs');
M_.endo_names = char(M_.endo_names, 'dpq');
M_.endo_names_tex = char(M_.endo_names_tex, 'dpq');
M_.endo_names_long = char(M_.endo_names_long, 'dpq');
M_.endo_names = char(M_.endo_names, 'pq');
M_.endo_names_tex = char(M_.endo_names_tex, 'pq');
M_.endo_names_long = char(M_.endo_names_long, 'pq');
M_.endo_names = char(M_.endo_names, 'dpmf');
M_.endo_names_tex = char(M_.endo_names_tex, 'dpmf');
M_.endo_names_long = char(M_.endo_names_long, 'dpmf');
M_.endo_names = char(M_.endo_names, 'pmf');
M_.endo_names_tex = char(M_.endo_names_tex, 'pmf');
M_.endo_names_long = char(M_.endo_names_long, 'pmf');
M_.endo_names = char(M_.endo_names, 'px');
M_.endo_names_tex = char(M_.endo_names_tex, 'px');
M_.endo_names_long = char(M_.endo_names_long, 'px');
M_.endo_names = char(M_.endo_names, 'dw');
M_.endo_names_tex = char(M_.endo_names_tex, 'dw');
M_.endo_names_long = char(M_.endo_names_long, 'dw');
M_.endo_names = char(M_.endo_names, 'w');
M_.endo_names_tex = char(M_.endo_names_tex, 'w');
M_.endo_names_long = char(M_.endo_names_long, 'w');
M_.endo_names = char(M_.endo_names, 'zetac');
M_.endo_names_tex = char(M_.endo_names_tex, 'zetac');
M_.endo_names_long = char(M_.endo_names_long, 'zetac');
M_.endo_names = char(M_.endo_names, 'zetap');
M_.endo_names_tex = char(M_.endo_names_tex, 'zetap');
M_.endo_names_long = char(M_.endo_names_long, 'zetap');
M_.endo_names = char(M_.endo_names, 'le');
M_.endo_names_tex = char(M_.endo_names_tex, 'le');
M_.endo_names_long = char(M_.endo_names_long, 'le');
M_.endo_names = char(M_.endo_names, 'rpmpq');
M_.endo_names_tex = char(M_.endo_names_tex, 'rpmpq');
M_.endo_names_long = char(M_.endo_names_long, 'rpmpq');
M_.endo_names = char(M_.endo_names, 'rpxpq');
M_.endo_names_tex = char(M_.endo_names_tex, 'rpxpq');
M_.endo_names_long = char(M_.endo_names_long, 'rpxpq');
M_.endo_names = char(M_.endo_names, 'rpmpx');
M_.endo_names_tex = char(M_.endo_names_tex, 'rpmpx');
M_.endo_names_long = char(M_.endo_names_long, 'rpmpx');
M_.endo_names = char(M_.endo_names, 'rpcpq');
M_.endo_names_tex = char(M_.endo_names_tex, 'rpcpq');
M_.endo_names_long = char(M_.endo_names_long, 'rpcpq');
M_.endo_names = char(M_.endo_names, 'rpipq');
M_.endo_names_tex = char(M_.endo_names_tex, 'rpipq');
M_.endo_names_long = char(M_.endo_names_long, 'rpipq');
M_.endo_names = char(M_.endo_names, 'dpc');
M_.endo_names_tex = char(M_.endo_names_tex, 'dpc');
M_.endo_names_long = char(M_.endo_names_long, 'dpc');
M_.endo_names = char(M_.endo_names, 'pc');
M_.endo_names_tex = char(M_.endo_names_tex, 'pc');
M_.endo_names_long = char(M_.endo_names_long, 'pc');
M_.endo_names = char(M_.endo_names, 'gdppot');
M_.endo_names_tex = char(M_.endo_names_tex, 'gdppot');
M_.endo_names_long = char(M_.endo_names_long, 'gdppot');
M_.endo_names = char(M_.endo_names, 'gdpgap');
M_.endo_names_tex = char(M_.endo_names_tex, 'gdpgap');
M_.endo_names_long = char(M_.endo_names_long, 'gdpgap');
M_.endo_names = char(M_.endo_names, 'rs1');
M_.endo_names_tex = char(M_.endo_names_tex, 'rs1');
M_.endo_names_long = char(M_.endo_names_long, 'rs1');
M_.endo_names = char(M_.endo_names, 'rs1f1');
M_.endo_names_tex = char(M_.endo_names_tex, 'rs1f1');
M_.endo_names_long = char(M_.endo_names_long, 'rs1f1');
M_.endo_names = char(M_.endo_names, 'rs1f2');
M_.endo_names_tex = char(M_.endo_names_tex, 'rs1f2');
M_.endo_names_long = char(M_.endo_names_long, 'rs1f2');
M_.endo_names = char(M_.endo_names, 'rs1f3');
M_.endo_names_tex = char(M_.endo_names_tex, 'rs1f3');
M_.endo_names_long = char(M_.endo_names_long, 'rs1f3');
M_.endo_names = char(M_.endo_names, 'rs1f4');
M_.endo_names_tex = char(M_.endo_names_tex, 'rs1f4');
M_.endo_names_long = char(M_.endo_names_long, 'rs1f4');
M_.endo_names = char(M_.endo_names, 'rs1f5');
M_.endo_names_tex = char(M_.endo_names_tex, 'rs1f5');
M_.endo_names_long = char(M_.endo_names_long, 'rs1f5');
M_.endo_names = char(M_.endo_names, 'rs1f6');
M_.endo_names_tex = char(M_.endo_names_tex, 'rs1f6');
M_.endo_names_long = char(M_.endo_names_long, 'rs1f6');
M_.endo_names = char(M_.endo_names, 'rs1f7');
M_.endo_names_tex = char(M_.endo_names_tex, 'rs1f7');
M_.endo_names_long = char(M_.endo_names_long, 'rs1f7');
M_.endo_names = char(M_.endo_names, 'rs1f8');
M_.endo_names_tex = char(M_.endo_names_tex, 'rs1f8');
M_.endo_names_long = char(M_.endo_names_long, 'rs1f8');
M_.endo_names = char(M_.endo_names, 'rs1f9');
M_.endo_names_tex = char(M_.endo_names_tex, 'rs1f9');
M_.endo_names_long = char(M_.endo_names_long, 'rs1f9');
M_.endo_names = char(M_.endo_names, 'rs1f10');
M_.endo_names_tex = char(M_.endo_names_tex, 'rs1f10');
M_.endo_names_long = char(M_.endo_names_long, 'rs1f10');
M_.endo_names = char(M_.endo_names, 'rs1f11');
M_.endo_names_tex = char(M_.endo_names_tex, 'rs1f11');
M_.endo_names_long = char(M_.endo_names_long, 'rs1f11');
M_.endo_names = char(M_.endo_names, 'rs1f12');
M_.endo_names_tex = char(M_.endo_names_tex, 'rs1f12');
M_.endo_names_long = char(M_.endo_names_long, 'rs1f12');
M_.endo_names = char(M_.endo_names, 'rs1f13');
M_.endo_names_tex = char(M_.endo_names_tex, 'rs1f13');
M_.endo_names_long = char(M_.endo_names_long, 'rs1f13');
M_.endo_names = char(M_.endo_names, 'rs1f14');
M_.endo_names_tex = char(M_.endo_names_tex, 'rs1f14');
M_.endo_names_long = char(M_.endo_names_long, 'rs1f14');
M_.endo_names = char(M_.endo_names, 'rs1f15');
M_.endo_names_tex = char(M_.endo_names_tex, 'rs1f15');
M_.endo_names_long = char(M_.endo_names_long, 'rs1f15');
M_.endo_names = char(M_.endo_names, 'rs1f16');
M_.endo_names_tex = char(M_.endo_names_tex, 'rs1f16');
M_.endo_names_long = char(M_.endo_names_long, 'rs1f16');
M_.endo_names = char(M_.endo_names, 'rs1f17');
M_.endo_names_tex = char(M_.endo_names_tex, 'rs1f17');
M_.endo_names_long = char(M_.endo_names_long, 'rs1f17');
M_.endo_names = char(M_.endo_names, 'rs1f18');
M_.endo_names_tex = char(M_.endo_names_tex, 'rs1f18');
M_.endo_names_long = char(M_.endo_names_long, 'rs1f18');
M_.endo_names = char(M_.endo_names, 'rs1f19');
M_.endo_names_tex = char(M_.endo_names_tex, 'rs1f19');
M_.endo_names_long = char(M_.endo_names_long, 'rs1f19');
M_.endo_names = char(M_.endo_names, 'ronereal');
M_.endo_names_tex = char(M_.endo_names_tex, 'ronereal');
M_.endo_names_long = char(M_.endo_names_long, 'ronereal');
M_.endo_names = char(M_.endo_names, 'r3real');
M_.endo_names_tex = char(M_.endo_names_tex, 'r3real');
M_.endo_names_long = char(M_.endo_names_long, 'r3real');
M_.endo_names = char(M_.endo_names, 'rratek');
M_.endo_names_tex = char(M_.endo_names_tex, 'rratek');
M_.endo_names_long = char(M_.endo_names_long, 'rratek');
M_.endo_names = char(M_.endo_names, 'nfa');
M_.endo_names_tex = char(M_.endo_names_tex, 'nfa');
M_.endo_names_long = char(M_.endo_names_long, 'nfa');
M_.endo_names = char(M_.endo_names, 'er');
M_.endo_names_tex = char(M_.endo_names_tex, 'er');
M_.endo_names_long = char(M_.endo_names_long, 'er');
M_.endo_names = char(M_.endo_names, 'rerpc');
M_.endo_names_tex = char(M_.endo_names_tex, 'rerpc');
M_.endo_names_long = char(M_.endo_names_long, 'rerpc');
M_.endo_names = char(M_.endo_names, 'rerpq');
M_.endo_names_tex = char(M_.endo_names_tex, 'rerpq');
M_.endo_names_long = char(M_.endo_names_long, 'rerpq');
M_.endo_names = char(M_.endo_names, 'dpql1');
M_.endo_names_tex = char(M_.endo_names_tex, 'dpql1');
M_.endo_names_long = char(M_.endo_names_long, 'dpql1');
M_.endo_names = char(M_.endo_names, 'dpql2');
M_.endo_names_tex = char(M_.endo_names_tex, 'dpql2');
M_.endo_names_long = char(M_.endo_names_long, 'dpql2');
M_.endo_names = char(M_.endo_names, 'dpql3');
M_.endo_names_tex = char(M_.endo_names_tex, 'dpql3');
M_.endo_names_long = char(M_.endo_names_long, 'dpql3');
M_.endo_names = char(M_.endo_names, 'dpcl1');
M_.endo_names_tex = char(M_.endo_names_tex, 'dpcl1');
M_.endo_names_long = char(M_.endo_names_long, 'dpcl1');
M_.endo_names = char(M_.endo_names, 'dpcl2');
M_.endo_names_tex = char(M_.endo_names_tex, 'dpcl2');
M_.endo_names_long = char(M_.endo_names_long, 'dpcl2');
M_.endo_names = char(M_.endo_names, 'dpcl3');
M_.endo_names_tex = char(M_.endo_names_tex, 'dpcl3');
M_.endo_names_long = char(M_.endo_names_long, 'dpcl3');
M_.endo_names = char(M_.endo_names, 'dgdp');
M_.endo_names_tex = char(M_.endo_names_tex, 'dgdp');
M_.endo_names_long = char(M_.endo_names_long, 'dgdp');
M_.endo_names = char(M_.endo_names, 'dgdpl1');
M_.endo_names_tex = char(M_.endo_names_tex, 'dgdpl1');
M_.endo_names_long = char(M_.endo_names_long, 'dgdpl1');
M_.endo_names = char(M_.endo_names, 'dgdpl2');
M_.endo_names_tex = char(M_.endo_names_tex, 'dgdpl2');
M_.endo_names_long = char(M_.endo_names_long, 'dgdpl2');
M_.endo_names = char(M_.endo_names, 'dgdpl3');
M_.endo_names_tex = char(M_.endo_names_tex, 'dgdpl3');
M_.endo_names_long = char(M_.endo_names_long, 'dgdpl3');
M_.endo_names = char(M_.endo_names, 'prabs');
M_.endo_names_tex = char(M_.endo_names_tex, 'prabs');
M_.endo_names_long = char(M_.endo_names_long, 'prabs');
M_.endo_names = char(M_.endo_names, 'prabsdt');
M_.endo_names_tex = char(M_.endo_names_tex, 'prabsdt');
M_.endo_names_long = char(M_.endo_names_long, 'prabsdt');
M_.endo_names = char(M_.endo_names, 'nshrgdefy');
M_.endo_names_tex = char(M_.endo_names_tex, 'nshrgdefy');
M_.endo_names_long = char(M_.endo_names_long, 'nshrgdefy');
M_.endo_names = char(M_.endo_names, 'nshrgy');
M_.endo_names_tex = char(M_.endo_names_tex, 'nshrgy');
M_.endo_names_long = char(M_.endo_names_long, 'nshrgy');
M_.endo_names = char(M_.endo_names, 'nshrcy');
M_.endo_names_tex = char(M_.endo_names_tex, 'nshrcy');
M_.endo_names_long = char(M_.endo_names_long, 'nshrcy');
M_.endo_names = char(M_.endo_names, 'nshriy');
M_.endo_names_tex = char(M_.endo_names_tex, 'nshriy');
M_.endo_names_long = char(M_.endo_names_long, 'nshriy');
M_.endo_names = char(M_.endo_names, 'nshrxy');
M_.endo_names_tex = char(M_.endo_names_tex, 'nshrxy');
M_.endo_names_long = char(M_.endo_names_long, 'nshrxy');
M_.endo_names = char(M_.endo_names, 'nshrmy');
M_.endo_names_tex = char(M_.endo_names_tex, 'nshrmy');
M_.endo_names_long = char(M_.endo_names_long, 'nshrmy');
M_.endo_names = char(M_.endo_names, 'ntby');
M_.endo_names_tex = char(M_.endo_names_tex, 'ntby');
M_.endo_names_long = char(M_.endo_names_long, 'ntby');
M_.endo_names = char(M_.endo_names, 'dpqyoy');
M_.endo_names_tex = char(M_.endo_names_tex, 'dpqyoy');
M_.endo_names_long = char(M_.endo_names_long, 'dpqyoy');
M_.endo_names = char(M_.endo_names, 'dpcyoy');
M_.endo_names_tex = char(M_.endo_names_tex, 'dpcyoy');
M_.endo_names_long = char(M_.endo_names_long, 'dpcyoy');
M_.endo_names = char(M_.endo_names, 'dgdpyoy');
M_.endo_names_tex = char(M_.endo_names_tex, 'dgdpyoy');
M_.endo_names_long = char(M_.endo_names_long, 'dgdpyoy');
M_.endo_names = char(M_.endo_names, 'dpqyoya4');
M_.endo_names_tex = char(M_.endo_names_tex, 'dpqyoya4');
M_.endo_names_long = char(M_.endo_names_long, 'dpqyoya4');
M_.endo_names = char(M_.endo_names, 'dpqyoya4l1');
M_.endo_names_tex = char(M_.endo_names_tex, 'dpqyoya4l1');
M_.endo_names_long = char(M_.endo_names_long, 'dpqyoya4l1');
M_.endo_names = char(M_.endo_names, 'dpqyoya4l2');
M_.endo_names_tex = char(M_.endo_names_tex, 'dpqyoya4l2');
M_.endo_names_long = char(M_.endo_names_long, 'dpqyoya4l2');
M_.endo_names = char(M_.endo_names, 'dpqyoya4l3');
M_.endo_names_tex = char(M_.endo_names_tex, 'dpqyoya4l3');
M_.endo_names_long = char(M_.endo_names_long, 'dpqyoya4l3');
M_.endo_names = char(M_.endo_names, 'dpqyoya4l4');
M_.endo_names_tex = char(M_.endo_names_tex, 'dpqyoya4l4');
M_.endo_names_long = char(M_.endo_names_long, 'dpqyoya4l4');
M_.endo_names = char(M_.endo_names, 'gdpgapa4');
M_.endo_names_tex = char(M_.endo_names_tex, 'gdpgapa4');
M_.endo_names_long = char(M_.endo_names_long, 'gdpgapa4');
M_.endo_names = char(M_.endo_names, 'gdpgapa4l1');
M_.endo_names_tex = char(M_.endo_names_tex, 'gdpgapa4l1');
M_.endo_names_long = char(M_.endo_names_long, 'gdpgapa4l1');
M_.endo_names = char(M_.endo_names, 'gdpgapa4l2');
M_.endo_names_tex = char(M_.endo_names_tex, 'gdpgapa4l2');
M_.endo_names_long = char(M_.endo_names_long, 'gdpgapa4l2');
M_.endo_names = char(M_.endo_names, 'gdpgapa4l3');
M_.endo_names_tex = char(M_.endo_names_tex, 'gdpgapa4l3');
M_.endo_names_long = char(M_.endo_names_long, 'gdpgapa4l3');
M_.endo_names = char(M_.endo_names, 'gdpgapa4l4');
M_.endo_names_tex = char(M_.endo_names_tex, 'gdpgapa4l4');
M_.endo_names_long = char(M_.endo_names_long, 'gdpgapa4l4');
M_.endo_names = char(M_.endo_names, 'pitartl1');
M_.endo_names_tex = char(M_.endo_names_tex, 'pitartl1');
M_.endo_names_long = char(M_.endo_names_long, 'pitartl1');
M_.endo_names = char(M_.endo_names, 'pitartl2');
M_.endo_names_tex = char(M_.endo_names_tex, 'pitartl2');
M_.endo_names_long = char(M_.endo_names_long, 'pitartl2');
M_.endo_names = char(M_.endo_names, 'pitartl3');
M_.endo_names_tex = char(M_.endo_names_tex, 'pitartl3');
M_.endo_names_long = char(M_.endo_names_long, 'pitartl3');
M_.endo_names = char(M_.endo_names, 'pitartl4');
M_.endo_names_tex = char(M_.endo_names_tex, 'pitartl4');
M_.endo_names_long = char(M_.endo_names_long, 'pitartl4');
M_.endo_names = char(M_.endo_names, 'glprod');
M_.endo_names_tex = char(M_.endo_names_tex, 'glprod');
M_.endo_names_long = char(M_.endo_names_long, 'glprod');
M_.endo_names = char(M_.endo_names, 'ccf');
M_.endo_names_tex = char(M_.endo_names_tex, 'ccf');
M_.endo_names_long = char(M_.endo_names_long, 'ccf');
M_.endo_names = char(M_.endo_names, 'cc2gdpf');
M_.endo_names_tex = char(M_.endo_names_tex, 'cc2gdpf');
M_.endo_names_long = char(M_.endo_names_long, 'cc2gdpf');
M_.endo_names = char(M_.endo_names, 'iff');
M_.endo_names_tex = char(M_.endo_names_tex, 'iff');
M_.endo_names_long = char(M_.endo_names_long, 'iff');
M_.endo_names = char(M_.endo_names, 'if2gdpf');
M_.endo_names_tex = char(M_.endo_names_tex, 'if2gdpf');
M_.endo_names_long = char(M_.endo_names_long, 'if2gdpf');
M_.endo_names = char(M_.endo_names, 'tobqf');
M_.endo_names_tex = char(M_.endo_names_tex, 'tobqf');
M_.endo_names_long = char(M_.endo_names_long, 'tobqf');
M_.endo_names = char(M_.endo_names, 'kpf');
M_.endo_names_tex = char(M_.endo_names_tex, 'kpf');
M_.endo_names_long = char(M_.endo_names_long, 'kpf');
M_.endo_names = char(M_.endo_names, 'kp1f');
M_.endo_names_tex = char(M_.endo_names_tex, 'kp1f');
M_.endo_names_long = char(M_.endo_names_long, 'kp1f');
M_.endo_names = char(M_.endo_names, 'rentksf');
M_.endo_names_tex = char(M_.endo_names_tex, 'rentksf');
M_.endo_names_long = char(M_.endo_names_long, 'rentksf');
M_.endo_names = char(M_.endo_names, 'gdpf');
M_.endo_names_tex = char(M_.endo_names_tex, 'gdpf');
M_.endo_names_long = char(M_.endo_names_long, 'gdpf');
M_.endo_names = char(M_.endo_names, 'ccdf');
M_.endo_names_tex = char(M_.endo_names_tex, 'ccdf');
M_.endo_names_long = char(M_.endo_names_long, 'ccdf');
M_.endo_names = char(M_.endo_names, 'ifdf');
M_.endo_names_tex = char(M_.endo_names_tex, 'ifdf');
M_.endo_names_long = char(M_.endo_names_long, 'ifdf');
M_.endo_names = char(M_.endo_names, 'mgsnif');
M_.endo_names_tex = char(M_.endo_names_tex, 'mgsnif');
M_.endo_names_long = char(M_.endo_names_long, 'mgsnif');
M_.endo_names = char(M_.endo_names, 'mgsnicf');
M_.endo_names_tex = char(M_.endo_names_tex, 'mgsnicf');
M_.endo_names_long = char(M_.endo_names_long, 'mgsnicf');
M_.endo_names = char(M_.endo_names, 'mgsniif');
M_.endo_names_tex = char(M_.endo_names_tex, 'mgsniif');
M_.endo_names_long = char(M_.endo_names_long, 'mgsniif');
M_.endo_names = char(M_.endo_names, 'rmcf');
M_.endo_names_tex = char(M_.endo_names_tex, 'rmcf');
M_.endo_names_long = char(M_.endo_names_long, 'rmcf');
M_.endo_names = char(M_.endo_names, 'rmif');
M_.endo_names_tex = char(M_.endo_names_tex, 'rmif');
M_.endo_names_long = char(M_.endo_names_long, 'rmif');
M_.endo_names = char(M_.endo_names, 'rsf');
M_.endo_names_tex = char(M_.endo_names_tex, 'rsf');
M_.endo_names_long = char(M_.endo_names_long, 'rsf');
M_.endo_names = char(M_.endo_names, 'mcqf');
M_.endo_names_tex = char(M_.endo_names_tex, 'mcqf');
M_.endo_names_long = char(M_.endo_names_long, 'mcqf');
M_.endo_names = char(M_.endo_names, 'mplf');
M_.endo_names_tex = char(M_.endo_names_tex, 'mplf');
M_.endo_names_long = char(M_.endo_names_long, 'mplf');
M_.endo_names = char(M_.endo_names, 'wmarkupf');
M_.endo_names_tex = char(M_.endo_names_tex, 'wmarkupf');
M_.endo_names_long = char(M_.endo_names_long, 'wmarkupf');
M_.endo_names = char(M_.endo_names, 'mrsf');
M_.endo_names_tex = char(M_.endo_names_tex, 'mrsf');
M_.endo_names_long = char(M_.endo_names_long, 'mrsf');
M_.endo_names = char(M_.endo_names, 'dpqf');
M_.endo_names_tex = char(M_.endo_names_tex, 'dpqf');
M_.endo_names_long = char(M_.endo_names_long, 'dpqf');
M_.endo_names = char(M_.endo_names, 'pqf');
M_.endo_names_tex = char(M_.endo_names_tex, 'pqf');
M_.endo_names_long = char(M_.endo_names_long, 'pqf');
M_.endo_names = char(M_.endo_names, 'dpm');
M_.endo_names_tex = char(M_.endo_names_tex, 'dpm');
M_.endo_names_long = char(M_.endo_names_long, 'dpm');
M_.endo_names = char(M_.endo_names, 'pm');
M_.endo_names_tex = char(M_.endo_names_tex, 'pm');
M_.endo_names_long = char(M_.endo_names_long, 'pm');
M_.endo_names = char(M_.endo_names, 'pxf');
M_.endo_names_tex = char(M_.endo_names_tex, 'pxf');
M_.endo_names_long = char(M_.endo_names_long, 'pxf');
M_.endo_names = char(M_.endo_names, 'dwf');
M_.endo_names_tex = char(M_.endo_names_tex, 'dwf');
M_.endo_names_long = char(M_.endo_names_long, 'dwf');
M_.endo_names = char(M_.endo_names, 'wf');
M_.endo_names_tex = char(M_.endo_names_tex, 'wf');
M_.endo_names_long = char(M_.endo_names_long, 'wf');
M_.endo_names = char(M_.endo_names, 'zetacf');
M_.endo_names_tex = char(M_.endo_names_tex, 'zetacf');
M_.endo_names_long = char(M_.endo_names_long, 'zetacf');
M_.endo_names = char(M_.endo_names, 'zetapf');
M_.endo_names_tex = char(M_.endo_names_tex, 'zetapf');
M_.endo_names_long = char(M_.endo_names_long, 'zetapf');
M_.endo_names = char(M_.endo_names, 'lef');
M_.endo_names_tex = char(M_.endo_names_tex, 'lef');
M_.endo_names_long = char(M_.endo_names_long, 'lef');
M_.endo_names = char(M_.endo_names, 'rpmpqf');
M_.endo_names_tex = char(M_.endo_names_tex, 'rpmpqf');
M_.endo_names_long = char(M_.endo_names_long, 'rpmpqf');
M_.endo_names = char(M_.endo_names, 'rpxpqf');
M_.endo_names_tex = char(M_.endo_names_tex, 'rpxpqf');
M_.endo_names_long = char(M_.endo_names_long, 'rpxpqf');
M_.endo_names = char(M_.endo_names, 'rpmpxf');
M_.endo_names_tex = char(M_.endo_names_tex, 'rpmpxf');
M_.endo_names_long = char(M_.endo_names_long, 'rpmpxf');
M_.endo_names = char(M_.endo_names, 'rpcpqf');
M_.endo_names_tex = char(M_.endo_names_tex, 'rpcpqf');
M_.endo_names_long = char(M_.endo_names_long, 'rpcpqf');
M_.endo_names = char(M_.endo_names, 'rpipqf');
M_.endo_names_tex = char(M_.endo_names_tex, 'rpipqf');
M_.endo_names_long = char(M_.endo_names_long, 'rpipqf');
M_.endo_names = char(M_.endo_names, 'dpcf');
M_.endo_names_tex = char(M_.endo_names_tex, 'dpcf');
M_.endo_names_long = char(M_.endo_names_long, 'dpcf');
M_.endo_names = char(M_.endo_names, 'pcf');
M_.endo_names_tex = char(M_.endo_names_tex, 'pcf');
M_.endo_names_long = char(M_.endo_names_long, 'pcf');
M_.endo_names = char(M_.endo_names, 'gdppotf');
M_.endo_names_tex = char(M_.endo_names_tex, 'gdppotf');
M_.endo_names_long = char(M_.endo_names_long, 'gdppotf');
M_.endo_names = char(M_.endo_names, 'gdpgapf');
M_.endo_names_tex = char(M_.endo_names_tex, 'gdpgapf');
M_.endo_names_long = char(M_.endo_names_long, 'gdpgapf');
M_.endo_names = char(M_.endo_names, 'rs1f');
M_.endo_names_tex = char(M_.endo_names_tex, 'rs1f');
M_.endo_names_long = char(M_.endo_names_long, 'rs1f');
M_.endo_names = char(M_.endo_names, 'dpql1f');
M_.endo_names_tex = char(M_.endo_names_tex, 'dpql1f');
M_.endo_names_long = char(M_.endo_names_long, 'dpql1f');
M_.endo_names = char(M_.endo_names, 'dpql2f');
M_.endo_names_tex = char(M_.endo_names_tex, 'dpql2f');
M_.endo_names_long = char(M_.endo_names_long, 'dpql2f');
M_.endo_names = char(M_.endo_names, 'dpql3f');
M_.endo_names_tex = char(M_.endo_names_tex, 'dpql3f');
M_.endo_names_long = char(M_.endo_names_long, 'dpql3f');
M_.endo_names = char(M_.endo_names, 'dpcl1f');
M_.endo_names_tex = char(M_.endo_names_tex, 'dpcl1f');
M_.endo_names_long = char(M_.endo_names_long, 'dpcl1f');
M_.endo_names = char(M_.endo_names, 'dpcl2f');
M_.endo_names_tex = char(M_.endo_names_tex, 'dpcl2f');
M_.endo_names_long = char(M_.endo_names_long, 'dpcl2f');
M_.endo_names = char(M_.endo_names, 'dpcl3f');
M_.endo_names_tex = char(M_.endo_names_tex, 'dpcl3f');
M_.endo_names_long = char(M_.endo_names_long, 'dpcl3f');
M_.endo_names = char(M_.endo_names, 'dpqyoyf');
M_.endo_names_tex = char(M_.endo_names_tex, 'dpqyoyf');
M_.endo_names_long = char(M_.endo_names_long, 'dpqyoyf');
M_.endo_names = char(M_.endo_names, 'dpcyoyf');
M_.endo_names_tex = char(M_.endo_names_tex, 'dpcyoyf');
M_.endo_names_long = char(M_.endo_names_long, 'dpcyoyf');
M_.endo_names = char(M_.endo_names, 'dgdpf');
M_.endo_names_tex = char(M_.endo_names_tex, 'dgdpf');
M_.endo_names_long = char(M_.endo_names_long, 'dgdpf');
M_.endo_names = char(M_.endo_names, 'dgdpl1f');
M_.endo_names_tex = char(M_.endo_names_tex, 'dgdpl1f');
M_.endo_names_long = char(M_.endo_names_long, 'dgdpl1f');
M_.endo_names = char(M_.endo_names, 'dgdpl2f');
M_.endo_names_tex = char(M_.endo_names_tex, 'dgdpl2f');
M_.endo_names_long = char(M_.endo_names_long, 'dgdpl2f');
M_.endo_names = char(M_.endo_names, 'dgdpl3f');
M_.endo_names_tex = char(M_.endo_names_tex, 'dgdpl3f');
M_.endo_names_long = char(M_.endo_names_long, 'dgdpl3f');
M_.endo_names = char(M_.endo_names, 'prabsf');
M_.endo_names_tex = char(M_.endo_names_tex, 'prabsf');
M_.endo_names_long = char(M_.endo_names_long, 'prabsf');
M_.endo_names = char(M_.endo_names, 'prabsdtf');
M_.endo_names_tex = char(M_.endo_names_tex, 'prabsdtf');
M_.endo_names_long = char(M_.endo_names_long, 'prabsdtf');
M_.endo_names = char(M_.endo_names, 'dgdpyoyf');
M_.endo_names_tex = char(M_.endo_names_tex, 'dgdpyoyf');
M_.endo_names_long = char(M_.endo_names_long, 'dgdpyoyf');
M_.endo_names = char(M_.endo_names, 'lamc');
M_.endo_names_tex = char(M_.endo_names_tex, 'lamc');
M_.endo_names_long = char(M_.endo_names_long, 'lamc');
M_.endo_names = char(M_.endo_names, 'ccopt');
M_.endo_names_tex = char(M_.endo_names_tex, 'ccopt');
M_.endo_names_long = char(M_.endo_names_long, 'ccopt');
M_.endo_names = char(M_.endo_names, 'cckey');
M_.endo_names_tex = char(M_.endo_names_tex, 'cckey');
M_.endo_names_long = char(M_.endo_names_long, 'cckey');
M_.endo_names = char(M_.endo_names, 'taxl');
M_.endo_names_tex = char(M_.endo_names_tex, 'taxl');
M_.endo_names_long = char(M_.endo_names_long, 'taxl');
M_.endo_names = char(M_.endo_names, 'debtg');
M_.endo_names_tex = char(M_.endo_names_tex, 'debtg');
M_.endo_names_long = char(M_.endo_names_long, 'debtg');
M_.endo_names = char(M_.endo_names, 'lamcf');
M_.endo_names_tex = char(M_.endo_names_tex, 'lamcf');
M_.endo_names_long = char(M_.endo_names_long, 'lamcf');
M_.endo_names = char(M_.endo_names, 'ccoptf');
M_.endo_names_tex = char(M_.endo_names_tex, 'ccoptf');
M_.endo_names_long = char(M_.endo_names_long, 'ccoptf');
M_.endo_names = char(M_.endo_names, 'cckeyf');
M_.endo_names_tex = char(M_.endo_names_tex, 'cckeyf');
M_.endo_names_long = char(M_.endo_names_long, 'cckeyf');
M_.endo_names = char(M_.endo_names, 'taxlf');
M_.endo_names_tex = char(M_.endo_names_tex, 'taxlf');
M_.endo_names_long = char(M_.endo_names_long, 'taxlf');
M_.endo_names = char(M_.endo_names, 'debtgf');
M_.endo_names_tex = char(M_.endo_names_tex, 'debtgf');
M_.endo_names_long = char(M_.endo_names_long, 'debtgf');
M_.endo_names = char(M_.endo_names, 'gtech');
M_.endo_names_tex = char(M_.endo_names_tex, 'gtech');
M_.endo_names_long = char(M_.endo_names_long, 'gtech');
M_.endo_names = char(M_.endo_names, 'gtechf');
M_.endo_names_tex = char(M_.endo_names_tex, 'gtechf');
M_.endo_names_long = char(M_.endo_names_long, 'gtechf');
M_.endo_names = char(M_.endo_names, 'at');
M_.endo_names_tex = char(M_.endo_names_tex, 'at');
M_.endo_names_long = char(M_.endo_names_long, 'at');
M_.endo_names = char(M_.endo_names, 'gat');
M_.endo_names_tex = char(M_.endo_names_tex, 'gat');
M_.endo_names_long = char(M_.endo_names_long, 'gat');
M_.endo_names = char(M_.endo_names, 'gatf1');
M_.endo_names_tex = char(M_.endo_names_tex, 'gatf1');
M_.endo_names_long = char(M_.endo_names_long, 'gatf1');
M_.endo_names = char(M_.endo_names, 'gatf2');
M_.endo_names_tex = char(M_.endo_names_tex, 'gatf2');
M_.endo_names_long = char(M_.endo_names_long, 'gatf2');
M_.endo_names = char(M_.endo_names, 'gatf3');
M_.endo_names_tex = char(M_.endo_names_tex, 'gatf3');
M_.endo_names_long = char(M_.endo_names_long, 'gatf3');
M_.endo_names = char(M_.endo_names, 'gatf4');
M_.endo_names_tex = char(M_.endo_names_tex, 'gatf4');
M_.endo_names_long = char(M_.endo_names_long, 'gatf4');
M_.endo_names = char(M_.endo_names, 'gcx');
M_.endo_names_tex = char(M_.endo_names_tex, 'gcx');
M_.endo_names_long = char(M_.endo_names_long, 'gcx');
M_.endo_names = char(M_.endo_names, 'pitar');
M_.endo_names_tex = char(M_.endo_names_tex, 'pitar');
M_.endo_names_long = char(M_.endo_names_long, 'pitar');
M_.endo_names = char(M_.endo_names, 'conshk');
M_.endo_names_tex = char(M_.endo_names_tex, 'conshk');
M_.endo_names_long = char(M_.endo_names_long, 'conshk');
M_.endo_names = char(M_.endo_names, 'taxk');
M_.endo_names_tex = char(M_.endo_names_tex, 'taxk');
M_.endo_names_long = char(M_.endo_names_long, 'taxk');
M_.endo_names = char(M_.endo_names, 'transhk');
M_.endo_names_tex = char(M_.endo_names_tex, 'transhk');
M_.endo_names_long = char(M_.endo_names_long, 'transhk');
M_.endo_names = char(M_.endo_names, 'atf');
M_.endo_names_tex = char(M_.endo_names_tex, 'atf');
M_.endo_names_long = char(M_.endo_names_long, 'atf');
M_.endo_names = char(M_.endo_names, 'gcxf');
M_.endo_names_tex = char(M_.endo_names_tex, 'gcxf');
M_.endo_names_long = char(M_.endo_names_long, 'gcxf');
M_.endo_names = char(M_.endo_names, 'pitarf');
M_.endo_names_tex = char(M_.endo_names_tex, 'pitarf');
M_.endo_names_long = char(M_.endo_names_long, 'pitarf');
M_.endo_names = char(M_.endo_names, 'conshkf');
M_.endo_names_tex = char(M_.endo_names_tex, 'conshkf');
M_.endo_names_long = char(M_.endo_names_long, 'conshkf');
M_.endo_names = char(M_.endo_names, 'taxkf');
M_.endo_names_tex = char(M_.endo_names_tex, 'taxkf');
M_.endo_names_long = char(M_.endo_names_long, 'taxkf');
M_.endo_names = char(M_.endo_names, 'transhkf');
M_.endo_names_tex = char(M_.endo_names_tex, 'transhkf');
M_.endo_names_long = char(M_.endo_names_long, 'transhkf');
M_.endo_names = char(M_.endo_names, 'riskp');
M_.endo_names_tex = char(M_.endo_names_tex, 'riskp');
M_.endo_names_long = char(M_.endo_names_long, 'riskp');
M_.endo_names = char(M_.endo_names, 'taxlshkf');
M_.endo_names_tex = char(M_.endo_names_tex, 'taxlshkf');
M_.endo_names_long = char(M_.endo_names_long, 'taxlshkf');
M_.endo_names = char(M_.endo_names, 'one');
M_.endo_names_tex = char(M_.endo_names_tex, 'one');
M_.endo_names_long = char(M_.endo_names_long, 'one');
M_.endo_names = char(M_.endo_names, 'gatp');
M_.endo_names_tex = char(M_.endo_names_tex, 'gatp');
M_.endo_names_long = char(M_.endo_names_long, 'gatp');
M_.endo_names = char(M_.endo_names, 'gatt');
M_.endo_names_tex = char(M_.endo_names_tex, 'gatt');
M_.endo_names_long = char(M_.endo_names_long, 'gatt');
M_.endo_names = char(M_.endo_names, 'gcxp');
M_.endo_names_tex = char(M_.endo_names_tex, 'gcxp');
M_.endo_names_long = char(M_.endo_names_long, 'gcxp');
M_.endo_names = char(M_.endo_names, 'gcxt');
M_.endo_names_tex = char(M_.endo_names_tex, 'gcxt');
M_.endo_names_long = char(M_.endo_names_long, 'gcxt');
M_.endo_names = char(M_.endo_names, 'pitarp');
M_.endo_names_tex = char(M_.endo_names_tex, 'pitarp');
M_.endo_names_long = char(M_.endo_names_long, 'pitarp');
M_.endo_names = char(M_.endo_names, 'pitart');
M_.endo_names_tex = char(M_.endo_names_tex, 'pitart');
M_.endo_names_long = char(M_.endo_names_long, 'pitart');
M_.endo_names = char(M_.endo_names, 'conshkp');
M_.endo_names_tex = char(M_.endo_names_tex, 'conshkp');
M_.endo_names_long = char(M_.endo_names_long, 'conshkp');
M_.endo_names = char(M_.endo_names, 'conshkt');
M_.endo_names_tex = char(M_.endo_names_tex, 'conshkt');
M_.endo_names_long = char(M_.endo_names_long, 'conshkt');
M_.endo_names = char(M_.endo_names, 'taxkp');
M_.endo_names_tex = char(M_.endo_names_tex, 'taxkp');
M_.endo_names_long = char(M_.endo_names_long, 'taxkp');
M_.endo_names = char(M_.endo_names, 'taxkpl1');
M_.endo_names_tex = char(M_.endo_names_tex, 'taxkpl1');
M_.endo_names_long = char(M_.endo_names_long, 'taxkpl1');
M_.endo_names = char(M_.endo_names, 'taxkpl2');
M_.endo_names_tex = char(M_.endo_names_tex, 'taxkpl2');
M_.endo_names_long = char(M_.endo_names_long, 'taxkpl2');
M_.endo_names = char(M_.endo_names, 'taxkt');
M_.endo_names_tex = char(M_.endo_names_tex, 'taxkt');
M_.endo_names_long = char(M_.endo_names_long, 'taxkt');
M_.endo_names = char(M_.endo_names, 'transhkp');
M_.endo_names_tex = char(M_.endo_names_tex, 'transhkp');
M_.endo_names_long = char(M_.endo_names_long, 'transhkp');
M_.endo_names = char(M_.endo_names, 'transhkt');
M_.endo_names_tex = char(M_.endo_names_tex, 'transhkt');
M_.endo_names_long = char(M_.endo_names_long, 'transhkt');
M_.endo_names = char(M_.endo_names, 'gatpf');
M_.endo_names_tex = char(M_.endo_names_tex, 'gatpf');
M_.endo_names_long = char(M_.endo_names_long, 'gatpf');
M_.endo_names = char(M_.endo_names, 'gattf');
M_.endo_names_tex = char(M_.endo_names_tex, 'gattf');
M_.endo_names_long = char(M_.endo_names_long, 'gattf');
M_.endo_names = char(M_.endo_names, 'gcxpf');
M_.endo_names_tex = char(M_.endo_names_tex, 'gcxpf');
M_.endo_names_long = char(M_.endo_names_long, 'gcxpf');
M_.endo_names = char(M_.endo_names, 'gcxtf');
M_.endo_names_tex = char(M_.endo_names_tex, 'gcxtf');
M_.endo_names_long = char(M_.endo_names_long, 'gcxtf');
M_.endo_names = char(M_.endo_names, 'pitarpf');
M_.endo_names_tex = char(M_.endo_names_tex, 'pitarpf');
M_.endo_names_long = char(M_.endo_names_long, 'pitarpf');
M_.endo_names = char(M_.endo_names, 'pitartf');
M_.endo_names_tex = char(M_.endo_names_tex, 'pitartf');
M_.endo_names_long = char(M_.endo_names_long, 'pitartf');
M_.endo_names = char(M_.endo_names, 'conshkpf');
M_.endo_names_tex = char(M_.endo_names_tex, 'conshkpf');
M_.endo_names_long = char(M_.endo_names_long, 'conshkpf');
M_.endo_names = char(M_.endo_names, 'conshktf');
M_.endo_names_tex = char(M_.endo_names_tex, 'conshktf');
M_.endo_names_long = char(M_.endo_names_long, 'conshktf');
M_.endo_names = char(M_.endo_names, 'taxkpf');
M_.endo_names_tex = char(M_.endo_names_tex, 'taxkpf');
M_.endo_names_long = char(M_.endo_names_long, 'taxkpf');
M_.endo_names = char(M_.endo_names, 'taxkpfl1');
M_.endo_names_tex = char(M_.endo_names_tex, 'taxkpfl1');
M_.endo_names_long = char(M_.endo_names_long, 'taxkpfl1');
M_.endo_names = char(M_.endo_names, 'taxkpfl2');
M_.endo_names_tex = char(M_.endo_names_tex, 'taxkpfl2');
M_.endo_names_long = char(M_.endo_names_long, 'taxkpfl2');
M_.endo_names = char(M_.endo_names, 'taxktf');
M_.endo_names_tex = char(M_.endo_names_tex, 'taxktf');
M_.endo_names_long = char(M_.endo_names_long, 'taxktf');
M_.endo_names = char(M_.endo_names, 'transhkpf');
M_.endo_names_tex = char(M_.endo_names_tex, 'transhkpf');
M_.endo_names_long = char(M_.endo_names_long, 'transhkpf');
M_.endo_names = char(M_.endo_names, 'transhktf');
M_.endo_names_tex = char(M_.endo_names_tex, 'transhktf');
M_.endo_names_long = char(M_.endo_names_long, 'transhktf');
M_.endo_names = char(M_.endo_names, 'riskpp');
M_.endo_names_tex = char(M_.endo_names_tex, 'riskpp');
M_.endo_names_long = char(M_.endo_names_long, 'riskpp');
M_.endo_names = char(M_.endo_names, 'riskpt');
M_.endo_names_tex = char(M_.endo_names_tex, 'riskpt');
M_.endo_names_long = char(M_.endo_names_long, 'riskpt');
M_.endo_names = char(M_.endo_names, 'betashk');
M_.endo_names_tex = char(M_.endo_names_tex, 'betashk');
M_.endo_names_long = char(M_.endo_names_long, 'betashk');
M_.endo_names = char(M_.endo_names, 'betashkf');
M_.endo_names_tex = char(M_.endo_names_tex, 'betashkf');
M_.endo_names_long = char(M_.endo_names_long, 'betashkf');
M_.endo_names = char(M_.endo_names, 'impshk');
M_.endo_names_tex = char(M_.endo_names_tex, 'impshk');
M_.endo_names_long = char(M_.endo_names_long, 'impshk');
M_.endo_names = char(M_.endo_names, 'impshkf');
M_.endo_names_tex = char(M_.endo_names_tex, 'impshkf');
M_.endo_names_long = char(M_.endo_names_long, 'impshkf');
M_.endo_names = char(M_.endo_names, 'taxlshk');
M_.endo_names_tex = char(M_.endo_names_tex, 'taxlshk');
M_.endo_names_long = char(M_.endo_names_long, 'taxlshk');
M_.endo_names = char(M_.endo_names, 'taxlshkpf');
M_.endo_names_tex = char(M_.endo_names_tex, 'taxlshkpf');
M_.endo_names_long = char(M_.endo_names_long, 'taxlshkpf');
M_.endo_names = char(M_.endo_names, 'taxlshktf');
M_.endo_names_tex = char(M_.endo_names_tex, 'taxlshktf');
M_.endo_names_long = char(M_.endo_names_long, 'taxlshktf');
M_.endo_names = char(M_.endo_names, 'errgcxt');
M_.endo_names_tex = char(M_.endo_names_tex, 'errgcxt');
M_.endo_names_long = char(M_.endo_names_long, 'errgcxt');
M_.endo_names = char(M_.endo_names, 'interest');
M_.endo_names_tex = char(M_.endo_names_tex, 'interest');
M_.endo_names_long = char(M_.endo_names_long, 'interest');
M_.endo_names = char(M_.endo_names, 'inflation');
M_.endo_names_tex = char(M_.endo_names_tex, 'inflation');
M_.endo_names_long = char(M_.endo_names_long, 'inflation');
M_.endo_names = char(M_.endo_names, 'inflationq');
M_.endo_names_tex = char(M_.endo_names_tex, 'inflationq');
M_.endo_names_long = char(M_.endo_names_long, 'inflationq');
M_.endo_names = char(M_.endo_names, 'output');
M_.endo_names_tex = char(M_.endo_names_tex, 'output');
M_.endo_names_long = char(M_.endo_names_long, 'output');
M_.endo_names = char(M_.endo_names, 'outputgap');
M_.endo_names_tex = char(M_.endo_names_tex, 'outputgap');
M_.endo_names_long = char(M_.endo_names_long, 'outputgap');
M_.endo_names = char(M_.endo_names, 'fispol');
M_.endo_names_tex = char(M_.endo_names_tex, 'fispol');
M_.endo_names_long = char(M_.endo_names_long, 'fispol');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_72');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_72');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_72');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_76');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_76');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_76');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_80');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_80');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_80');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_107');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_107');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_107');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_111');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_111');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_111');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_115');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_115');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_115');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_142');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_142');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_142');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_146');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_146');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_146');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_150');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_150');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_150');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_198');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_198');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_198');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_202');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_202');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_202');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_206');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_206');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_206');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_228');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_228');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_228');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_231');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_231');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_231');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_234');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_234');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_234');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_255');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_255');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_255');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_258');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_258');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_258');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_261');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_261');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_261');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_1813');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_1813');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_1813');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_1817');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_1817');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_1817');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_953');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_953');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_953');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_1826');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_1826');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_1826');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_1830');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_1830');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_1830');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_968');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_968');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_968');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_234_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_234\_1');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_234_1');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_234_2');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_234\_2');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_234_2');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_234_3');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_234\_3');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_234_3');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_235_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_235\_1');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_235_1');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_235_2');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_235\_2');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_235_2');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_235_3');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_235\_3');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_235_3');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_231_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_231\_1');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_231_1');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_231_2');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_231\_2');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_231_2');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_231_3');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_231\_3');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_231_3');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_233_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_233\_1');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_233_1');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_233_2');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_233\_2');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_233_2');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_233_3');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_233\_3');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_233_3');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_113_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_113\_1');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_113_1');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_113_2');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_113\_2');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_113_2');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_113_3');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_113\_3');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_113_3');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_144_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_144\_1');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_144_1');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_144_2');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_144\_2');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_144_2');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_144_3');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_144\_3');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_144_3');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_121_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_121\_1');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_121_1');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_121_2');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_121\_2');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_121_2');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_121_3');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_121\_3');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_121_3');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_126_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_126\_1');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_126_1');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_126_2');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_126\_2');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_126_2');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_126_3');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_126\_3');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_126_3');
M_.param_names = 'cofintintb1';
M_.param_names_tex = 'cofintintb1';
M_.param_names_long = 'cofintintb1';
M_.param_names = char(M_.param_names, 'cofintintb2');
M_.param_names_tex = char(M_.param_names_tex, 'cofintintb2');
M_.param_names_long = char(M_.param_names_long, 'cofintintb2');
M_.param_names = char(M_.param_names, 'cofintintb3');
M_.param_names_tex = char(M_.param_names_tex, 'cofintintb3');
M_.param_names_long = char(M_.param_names_long, 'cofintintb3');
M_.param_names = char(M_.param_names, 'cofintintb4');
M_.param_names_tex = char(M_.param_names_tex, 'cofintintb4');
M_.param_names_long = char(M_.param_names_long, 'cofintintb4');
M_.param_names = char(M_.param_names, 'cofintinf0');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinf0');
M_.param_names_long = char(M_.param_names_long, 'cofintinf0');
M_.param_names = char(M_.param_names, 'cofintinfb1');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinfb1');
M_.param_names_long = char(M_.param_names_long, 'cofintinfb1');
M_.param_names = char(M_.param_names, 'cofintinfb2');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinfb2');
M_.param_names_long = char(M_.param_names_long, 'cofintinfb2');
M_.param_names = char(M_.param_names, 'cofintinfb3');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinfb3');
M_.param_names_long = char(M_.param_names_long, 'cofintinfb3');
M_.param_names = char(M_.param_names, 'cofintinfb4');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinfb4');
M_.param_names_long = char(M_.param_names_long, 'cofintinfb4');
M_.param_names = char(M_.param_names, 'cofintinff1');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinff1');
M_.param_names_long = char(M_.param_names_long, 'cofintinff1');
M_.param_names = char(M_.param_names, 'cofintinff2');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinff2');
M_.param_names_long = char(M_.param_names_long, 'cofintinff2');
M_.param_names = char(M_.param_names, 'cofintinff3');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinff3');
M_.param_names_long = char(M_.param_names_long, 'cofintinff3');
M_.param_names = char(M_.param_names, 'cofintinff4');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinff4');
M_.param_names_long = char(M_.param_names_long, 'cofintinff4');
M_.param_names = char(M_.param_names, 'cofintout');
M_.param_names_tex = char(M_.param_names_tex, 'cofintout');
M_.param_names_long = char(M_.param_names_long, 'cofintout');
M_.param_names = char(M_.param_names, 'cofintoutb1');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutb1');
M_.param_names_long = char(M_.param_names_long, 'cofintoutb1');
M_.param_names = char(M_.param_names, 'cofintoutb2');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutb2');
M_.param_names_long = char(M_.param_names_long, 'cofintoutb2');
M_.param_names = char(M_.param_names, 'cofintoutb3');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutb3');
M_.param_names_long = char(M_.param_names_long, 'cofintoutb3');
M_.param_names = char(M_.param_names, 'cofintoutb4');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutb4');
M_.param_names_long = char(M_.param_names_long, 'cofintoutb4');
M_.param_names = char(M_.param_names, 'cofintoutf1');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutf1');
M_.param_names_long = char(M_.param_names_long, 'cofintoutf1');
M_.param_names = char(M_.param_names, 'cofintoutf2');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutf2');
M_.param_names_long = char(M_.param_names_long, 'cofintoutf2');
M_.param_names = char(M_.param_names, 'cofintoutf3');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutf3');
M_.param_names_long = char(M_.param_names_long, 'cofintoutf3');
M_.param_names = char(M_.param_names, 'cofintoutf4');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutf4');
M_.param_names_long = char(M_.param_names_long, 'cofintoutf4');
M_.param_names = char(M_.param_names, 'cofintoutp');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutp');
M_.param_names_long = char(M_.param_names_long, 'cofintoutp');
M_.param_names = char(M_.param_names, 'cofintoutpb1');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpb1');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpb1');
M_.param_names = char(M_.param_names, 'cofintoutpb2');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpb2');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpb2');
M_.param_names = char(M_.param_names, 'cofintoutpb3');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpb3');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpb3');
M_.param_names = char(M_.param_names, 'cofintoutpb4');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpb4');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpb4');
M_.param_names = char(M_.param_names, 'cofintoutpf1');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpf1');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpf1');
M_.param_names = char(M_.param_names, 'cofintoutpf2');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpf2');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpf2');
M_.param_names = char(M_.param_names, 'cofintoutpf3');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpf3');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpf3');
M_.param_names = char(M_.param_names, 'cofintoutpf4');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpf4');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpf4');
M_.param_names = char(M_.param_names, 'std_r_');
M_.param_names_tex = char(M_.param_names_tex, 'std\_r\_');
M_.param_names_long = char(M_.param_names_long, 'std_r_');
M_.param_names = char(M_.param_names, 'std_r_quart');
M_.param_names_tex = char(M_.param_names_tex, 'std\_r\_quart');
M_.param_names_long = char(M_.param_names_long, 'std_r_quart');
M_.param_names = char(M_.param_names, 'coffispol');
M_.param_names_tex = char(M_.param_names_tex, 'coffispol');
M_.param_names_long = char(M_.param_names_long, 'coffispol');
M_.param_names = char(M_.param_names, 'shrckey');
M_.param_names_tex = char(M_.param_names_tex, 'shrckey');
M_.param_names_long = char(M_.param_names_long, 'shrckey');
M_.param_names = char(M_.param_names, 'shrcy');
M_.param_names_tex = char(M_.param_names_tex, 'shrcy');
M_.param_names_long = char(M_.param_names_long, 'shrcy');
M_.param_names = char(M_.param_names, 'shrgy');
M_.param_names_tex = char(M_.param_names_tex, 'shrgy');
M_.param_names_long = char(M_.param_names_long, 'shrgy');
M_.param_names = char(M_.param_names, 'rbar');
M_.param_names_tex = char(M_.param_names_tex, 'rbar');
M_.param_names_long = char(M_.param_names_long, 'rbar');
M_.param_names = char(M_.param_names, 'gzbar');
M_.param_names_tex = char(M_.param_names_tex, 'gzbar');
M_.param_names_long = char(M_.param_names_long, 'gzbar');
M_.param_names = char(M_.param_names, 'popg');
M_.param_names_tex = char(M_.param_names_tex, 'popg');
M_.param_names_long = char(M_.param_names_long, 'popg');
M_.param_names = char(M_.param_names, 'delta');
M_.param_names_tex = char(M_.param_names_tex, 'delta');
M_.param_names_long = char(M_.param_names_long, 'delta');
M_.param_names = char(M_.param_names, 'shriy');
M_.param_names_tex = char(M_.param_names_tex, 'shriy');
M_.param_names_long = char(M_.param_names_long, 'shriy');
M_.param_names = char(M_.param_names, 'phik');
M_.param_names_tex = char(M_.param_names_tex, 'phik');
M_.param_names_long = char(M_.param_names_long, 'phik');
M_.param_names = char(M_.param_names, 'deltahat');
M_.param_names_tex = char(M_.param_names_tex, 'deltahat');
M_.param_names_long = char(M_.param_names_long, 'deltahat');
M_.param_names = char(M_.param_names, 'phii');
M_.param_names_tex = char(M_.param_names_tex, 'phii');
M_.param_names_long = char(M_.param_names_long, 'phii');
M_.param_names = char(M_.param_names, 'invfor');
M_.param_names_tex = char(M_.param_names_tex, 'invfor');
M_.param_names_long = char(M_.param_names_long, 'invfor');
M_.param_names = char(M_.param_names, 'inddelta');
M_.param_names_tex = char(M_.param_names_tex, 'inddelta');
M_.param_names_long = char(M_.param_names_long, 'inddelta');
M_.param_names = char(M_.param_names, 'tauk');
M_.param_names_tex = char(M_.param_names_tex, 'tauk');
M_.param_names_long = char(M_.param_names_long, 'tauk');
M_.param_names = char(M_.param_names, 'defspread');
M_.param_names_tex = char(M_.param_names_tex, 'defspread');
M_.param_names_long = char(M_.param_names_long, 'defspread');
M_.param_names = char(M_.param_names, 'cessub');
M_.param_names_tex = char(M_.param_names_tex, 'cessub');
M_.param_names_long = char(M_.param_names_long, 'cessub');
M_.param_names = char(M_.param_names, 'shrmy');
M_.param_names_tex = char(M_.param_names_tex, 'shrmy');
M_.param_names_long = char(M_.param_names_long, 'shrmy');
M_.param_names = char(M_.param_names, 'shrmc');
M_.param_names_tex = char(M_.param_names_tex, 'shrmc');
M_.param_names_long = char(M_.param_names_long, 'shrmc');
M_.param_names = char(M_.param_names, 'shrmi');
M_.param_names_tex = char(M_.param_names_tex, 'shrmi');
M_.param_names_long = char(M_.param_names_long, 'shrmi');
M_.param_names = char(M_.param_names, 'etamc');
M_.param_names_tex = char(M_.param_names_tex, 'etamc');
M_.param_names_long = char(M_.param_names_long, 'etamc');
M_.param_names = char(M_.param_names, 'phimc');
M_.param_names_tex = char(M_.param_names_tex, 'phimc');
M_.param_names_long = char(M_.param_names_long, 'phimc');
M_.param_names = char(M_.param_names, 'forswitch');
M_.param_names_tex = char(M_.param_names_tex, 'forswitch');
M_.param_names_long = char(M_.param_names_long, 'forswitch');
M_.param_names = char(M_.param_names, 'lovparm');
M_.param_names_tex = char(M_.param_names_tex, 'lovparm');
M_.param_names_long = char(M_.param_names_long, 'lovparm');
M_.param_names = char(M_.param_names, 'monlag');
M_.param_names_tex = char(M_.param_names_tex, 'monlag');
M_.param_names_long = char(M_.param_names_long, 'monlag');
M_.param_names = char(M_.param_names, 'gampi');
M_.param_names_tex = char(M_.param_names_tex, 'gampi');
M_.param_names_long = char(M_.param_names_long, 'gampi');
M_.param_names = char(M_.param_names, 'gamex');
M_.param_names_tex = char(M_.param_names_tex, 'gamex');
M_.param_names_long = char(M_.param_names_long, 'gamex');
M_.param_names = char(M_.param_names, 'gamy');
M_.param_names_tex = char(M_.param_names_tex, 'gamy');
M_.param_names_long = char(M_.param_names_long, 'gamy');
M_.param_names = char(M_.param_names, 'gamy4');
M_.param_names_tex = char(M_.param_names_tex, 'gamy4');
M_.param_names_long = char(M_.param_names_long, 'gamy4');
M_.param_names = char(M_.param_names, 'gamgap');
M_.param_names_tex = char(M_.param_names_tex, 'gamgap');
M_.param_names_long = char(M_.param_names_long, 'gamgap');
M_.param_names = char(M_.param_names, 'taul');
M_.param_names_tex = char(M_.param_names_tex, 'taul');
M_.param_names_long = char(M_.param_names_long, 'taul');
M_.param_names = char(M_.param_names, 'chi');
M_.param_names_tex = char(M_.param_names_tex, 'chi');
M_.param_names_long = char(M_.param_names_long, 'chi');
M_.param_names = char(M_.param_names, 'shrlab');
M_.param_names_tex = char(M_.param_names_tex, 'shrlab');
M_.param_names_long = char(M_.param_names_long, 'shrlab');
M_.param_names = char(M_.param_names, 'indexp');
M_.param_names_tex = char(M_.param_names_tex, 'indexp');
M_.param_names_long = char(M_.param_names_long, 'indexp');
M_.param_names = char(M_.param_names, 'kappap');
M_.param_names_tex = char(M_.param_names_tex, 'kappap');
M_.param_names_long = char(M_.param_names_long, 'kappap');
M_.param_names = char(M_.param_names, 'indexm');
M_.param_names_tex = char(M_.param_names_tex, 'indexm');
M_.param_names_long = char(M_.param_names_long, 'indexm');
M_.param_names = char(M_.param_names, 'kappax');
M_.param_names_tex = char(M_.param_names_tex, 'kappax');
M_.param_names_long = char(M_.param_names_long, 'kappax');
M_.param_names = char(M_.param_names, 'indexw');
M_.param_names_tex = char(M_.param_names_tex, 'indexw');
M_.param_names_long = char(M_.param_names_long, 'indexw');
M_.param_names = char(M_.param_names, 'kappaw');
M_.param_names_tex = char(M_.param_names_tex, 'kappaw');
M_.param_names_long = char(M_.param_names_long, 'kappaw');
M_.param_names = char(M_.param_names, 'qcapshr');
M_.param_names_tex = char(M_.param_names_tex, 'qcapshr');
M_.param_names_long = char(M_.param_names_long, 'qcapshr');
M_.param_names = char(M_.param_names, 'shrlaby');
M_.param_names_tex = char(M_.param_names_tex, 'shrlaby');
M_.param_names_long = char(M_.param_names_long, 'shrlaby');
M_.param_names = char(M_.param_names, 'rkbar');
M_.param_names_tex = char(M_.param_names_tex, 'rkbar');
M_.param_names_long = char(M_.param_names_long, 'rkbar');
M_.param_names = char(M_.param_names, 'shrckeyf');
M_.param_names_tex = char(M_.param_names_tex, 'shrckeyf');
M_.param_names_long = char(M_.param_names_long, 'shrckeyf');
M_.param_names = char(M_.param_names, 'shrcyf');
M_.param_names_tex = char(M_.param_names_tex, 'shrcyf');
M_.param_names_long = char(M_.param_names_long, 'shrcyf');
M_.param_names = char(M_.param_names, 'shriyf');
M_.param_names_tex = char(M_.param_names_tex, 'shriyf');
M_.param_names_long = char(M_.param_names_long, 'shriyf');
M_.param_names = char(M_.param_names, 'shrgyf');
M_.param_names_tex = char(M_.param_names_tex, 'shrgyf');
M_.param_names_long = char(M_.param_names_long, 'shrgyf');
M_.param_names = char(M_.param_names, 'shrmyf');
M_.param_names_tex = char(M_.param_names_tex, 'shrmyf');
M_.param_names_long = char(M_.param_names_long, 'shrmyf');
M_.param_names = char(M_.param_names, 'shrmcf');
M_.param_names_tex = char(M_.param_names_tex, 'shrmcf');
M_.param_names_long = char(M_.param_names_long, 'shrmcf');
M_.param_names = char(M_.param_names, 'shrmif');
M_.param_names_tex = char(M_.param_names_tex, 'shrmif');
M_.param_names_long = char(M_.param_names_long, 'shrmif');
M_.param_names = char(M_.param_names, 'etamcf');
M_.param_names_tex = char(M_.param_names_tex, 'etamcf');
M_.param_names_long = char(M_.param_names_long, 'etamcf');
M_.param_names = char(M_.param_names, 'etamif');
M_.param_names_tex = char(M_.param_names_tex, 'etamif');
M_.param_names_long = char(M_.param_names_long, 'etamif');
M_.param_names = char(M_.param_names, 'phimcf');
M_.param_names_tex = char(M_.param_names_tex, 'phimcf');
M_.param_names_long = char(M_.param_names_long, 'phimcf');
M_.param_names = char(M_.param_names, 'monlagf');
M_.param_names_tex = char(M_.param_names_tex, 'monlagf');
M_.param_names_long = char(M_.param_names_long, 'monlagf');
M_.param_names = char(M_.param_names, 'gamexf');
M_.param_names_tex = char(M_.param_names_tex, 'gamexf');
M_.param_names_long = char(M_.param_names_long, 'gamexf');
M_.param_names = char(M_.param_names, 'gamyf');
M_.param_names_tex = char(M_.param_names_tex, 'gamyf');
M_.param_names_long = char(M_.param_names_long, 'gamyf');
M_.param_names = char(M_.param_names, 'gamy4f');
M_.param_names_tex = char(M_.param_names_tex, 'gamy4f');
M_.param_names_long = char(M_.param_names_long, 'gamy4f');
M_.param_names = char(M_.param_names, 'gamgapf');
M_.param_names_tex = char(M_.param_names_tex, 'gamgapf');
M_.param_names_long = char(M_.param_names_long, 'gamgapf');
M_.param_names = char(M_.param_names, 'kappapf');
M_.param_names_tex = char(M_.param_names_tex, 'kappapf');
M_.param_names_long = char(M_.param_names_long, 'kappapf');
M_.param_names = char(M_.param_names, 'kappaxf');
M_.param_names_tex = char(M_.param_names_tex, 'kappaxf');
M_.param_names_long = char(M_.param_names_long, 'kappaxf');
M_.param_names = char(M_.param_names, 'kappawf');
M_.param_names_tex = char(M_.param_names_tex, 'kappawf');
M_.param_names_long = char(M_.param_names_long, 'kappawf');
M_.param_names = char(M_.param_names, 'sigma');
M_.param_names_tex = char(M_.param_names_tex, 'sigma');
M_.param_names_long = char(M_.param_names_long, 'sigma');
M_.param_names = char(M_.param_names, 'phic');
M_.param_names_tex = char(M_.param_names_tex, 'phic');
M_.param_names_long = char(M_.param_names_long, 'phic');
M_.param_names = char(M_.param_names, 'xsic');
M_.param_names_tex = char(M_.param_names_tex, 'xsic');
M_.param_names_long = char(M_.param_names_long, 'xsic');
M_.param_names = char(M_.param_names, 'phid1');
M_.param_names_tex = char(M_.param_names_tex, 'phid1');
M_.param_names_long = char(M_.param_names_long, 'phid1');
M_.param_names = char(M_.param_names, 'phid2');
M_.param_names_tex = char(M_.param_names_tex, 'phid2');
M_.param_names_long = char(M_.param_names_long, 'phid2');
M_.param_names = char(M_.param_names, 'taxlwedgeswitch');
M_.param_names_tex = char(M_.param_names_tex, 'taxlwedgeswitch');
M_.param_names_long = char(M_.param_names_long, 'taxlwedgeswitch');
M_.param_names = char(M_.param_names, 'taxwedgeswitch');
M_.param_names_tex = char(M_.param_names_tex, 'taxwedgeswitch');
M_.param_names_long = char(M_.param_names_long, 'taxwedgeswitch');
M_.param_names = char(M_.param_names, 'deltag');
M_.param_names_tex = char(M_.param_names_tex, 'deltag');
M_.param_names_long = char(M_.param_names_long, 'deltag');
M_.param_names = char(M_.param_names, 'switchg');
M_.param_names_tex = char(M_.param_names_tex, 'switchg');
M_.param_names_long = char(M_.param_names_long, 'switchg');
M_.param_names = char(M_.param_names, 'rho1p');
M_.param_names_tex = char(M_.param_names_tex, 'rho1p');
M_.param_names_long = char(M_.param_names_long, 'rho1p');
M_.param_names = char(M_.param_names, 'rho1t');
M_.param_names_tex = char(M_.param_names_tex, 'rho1t');
M_.param_names_long = char(M_.param_names_long, 'rho1t');
M_.param_names = char(M_.param_names, 'rho2p');
M_.param_names_tex = char(M_.param_names_tex, 'rho2p');
M_.param_names_long = char(M_.param_names_long, 'rho2p');
M_.param_names = char(M_.param_names, 'rho2t');
M_.param_names_tex = char(M_.param_names_tex, 'rho2t');
M_.param_names_long = char(M_.param_names_long, 'rho2t');
M_.param_names = char(M_.param_names, 'rho3p');
M_.param_names_tex = char(M_.param_names_tex, 'rho3p');
M_.param_names_long = char(M_.param_names_long, 'rho3p');
M_.param_names = char(M_.param_names, 'rho3t');
M_.param_names_tex = char(M_.param_names_tex, 'rho3t');
M_.param_names_long = char(M_.param_names_long, 'rho3t');
M_.param_names = char(M_.param_names, 'rho4p');
M_.param_names_tex = char(M_.param_names_tex, 'rho4p');
M_.param_names_long = char(M_.param_names_long, 'rho4p');
M_.param_names = char(M_.param_names, 'rho4t');
M_.param_names_tex = char(M_.param_names_tex, 'rho4t');
M_.param_names_long = char(M_.param_names_long, 'rho4t');
M_.param_names = char(M_.param_names, 'rho5p');
M_.param_names_tex = char(M_.param_names_tex, 'rho5p');
M_.param_names_long = char(M_.param_names_long, 'rho5p');
M_.param_names = char(M_.param_names, 'taxkgswitch');
M_.param_names_tex = char(M_.param_names_tex, 'taxkgswitch');
M_.param_names_long = char(M_.param_names_long, 'taxkgswitch');
M_.param_names = char(M_.param_names, 'rho5t');
M_.param_names_tex = char(M_.param_names_tex, 'rho5t');
M_.param_names_long = char(M_.param_names_long, 'rho5t');
M_.param_names = char(M_.param_names, 'rho11p');
M_.param_names_tex = char(M_.param_names_tex, 'rho11p');
M_.param_names_long = char(M_.param_names_long, 'rho11p');
M_.param_names = char(M_.param_names, 'rho11t');
M_.param_names_tex = char(M_.param_names_tex, 'rho11t');
M_.param_names_long = char(M_.param_names_long, 'rho11t');
M_.param_names = char(M_.param_names, 'rho13');
M_.param_names_tex = char(M_.param_names_tex, 'rho13');
M_.param_names_long = char(M_.param_names_long, 'rho13');
M_.param_names = char(M_.param_names, 'rho14');
M_.param_names_tex = char(M_.param_names_tex, 'rho14');
M_.param_names_long = char(M_.param_names_long, 'rho14');
M_.param_names = char(M_.param_names, 'rho15');
M_.param_names_tex = char(M_.param_names_tex, 'rho15');
M_.param_names_long = char(M_.param_names_long, 'rho15');
M_.param_names = char(M_.param_names, 'phid3');
M_.param_names_tex = char(M_.param_names_tex, 'phid3');
M_.param_names_long = char(M_.param_names_long, 'phid3');
M_.param_names = char(M_.param_names, 'phid4');
M_.param_names_tex = char(M_.param_names_tex, 'phid4');
M_.param_names_long = char(M_.param_names_long, 'phid4');
M_.param_names = char(M_.param_names, 'rho15p');
M_.param_names_tex = char(M_.param_names_tex, 'rho15p');
M_.param_names_long = char(M_.param_names_long, 'rho15p');
M_.param_names = char(M_.param_names, 'rho15t');
M_.param_names_tex = char(M_.param_names_tex, 'rho15t');
M_.param_names_long = char(M_.param_names_long, 'rho15t');
M_.param_names = char(M_.param_names, 'cesparm');
M_.param_names_tex = char(M_.param_names_tex, 'cesparm');
M_.param_names_long = char(M_.param_names_long, 'cesparm');
M_.param_names = char(M_.param_names, 'beta');
M_.param_names_tex = char(M_.param_names_tex, 'beta');
M_.param_names_long = char(M_.param_names_long, 'beta');
M_.param_names = char(M_.param_names, 'thetap');
M_.param_names_tex = char(M_.param_names_tex, 'thetap');
M_.param_names_long = char(M_.param_names_long, 'thetap');
M_.param_names = char(M_.param_names, 'thetaw');
M_.param_names_tex = char(M_.param_names_tex, 'thetaw');
M_.param_names_long = char(M_.param_names_long, 'thetaw');
M_.param_names = char(M_.param_names, 'taup');
M_.param_names_tex = char(M_.param_names_tex, 'taup');
M_.param_names_long = char(M_.param_names_long, 'taup');
M_.param_names = char(M_.param_names, 'phimi');
M_.param_names_tex = char(M_.param_names_tex, 'phimi');
M_.param_names_long = char(M_.param_names_long, 'phimi');
M_.param_names = char(M_.param_names, 'prodg');
M_.param_names_tex = char(M_.param_names_tex, 'prodg');
M_.param_names_long = char(M_.param_names_long, 'prodg');
M_.param_names = char(M_.param_names, 'etami');
M_.param_names_tex = char(M_.param_names_tex, 'etami');
M_.param_names_long = char(M_.param_names_long, 'etami');
M_.param_names = char(M_.param_names, 'psip');
M_.param_names_tex = char(M_.param_names_tex, 'psip');
M_.param_names_long = char(M_.param_names_long, 'psip');
M_.param_names = char(M_.param_names, 'psiw');
M_.param_names_tex = char(M_.param_names_tex, 'psiw');
M_.param_names_long = char(M_.param_names_long, 'psiw');
M_.param_names = char(M_.param_names, 'psixf');
M_.param_names_tex = char(M_.param_names_tex, 'psixf');
M_.param_names_long = char(M_.param_names_long, 'psixf');
M_.param_names = char(M_.param_names, 'popkey');
M_.param_names_tex = char(M_.param_names_tex, 'popkey');
M_.param_names_long = char(M_.param_names_long, 'popkey');
M_.param_names = char(M_.param_names, 'psipf');
M_.param_names_tex = char(M_.param_names_tex, 'psipf');
M_.param_names_long = char(M_.param_names_long, 'psipf');
M_.param_names = char(M_.param_names, 'psiwf');
M_.param_names_tex = char(M_.param_names_tex, 'psiwf');
M_.param_names_long = char(M_.param_names_long, 'psiwf');
M_.param_names = char(M_.param_names, 'psix');
M_.param_names_tex = char(M_.param_names_tex, 'psix');
M_.param_names_long = char(M_.param_names_long, 'psix');
M_.param_names = char(M_.param_names, 'thetapf');
M_.param_names_tex = char(M_.param_names_tex, 'thetapf');
M_.param_names_long = char(M_.param_names_long, 'thetapf');
M_.param_names = char(M_.param_names, 'thetawf');
M_.param_names_tex = char(M_.param_names_tex, 'thetawf');
M_.param_names_long = char(M_.param_names_long, 'thetawf');
M_.param_names = char(M_.param_names, 'phimitilde');
M_.param_names_tex = char(M_.param_names_tex, 'phimitilde');
M_.param_names_long = char(M_.param_names_long, 'phimitilde');
M_.param_names = char(M_.param_names, 'phimctilde');
M_.param_names_tex = char(M_.param_names_tex, 'phimctilde');
M_.param_names_long = char(M_.param_names_long, 'phimctilde');
M_.param_names = char(M_.param_names, 'phimif');
M_.param_names_tex = char(M_.param_names_tex, 'phimif');
M_.param_names_long = char(M_.param_names_long, 'phimif');
M_.exo_det_nbr = 0;
M_.exo_nbr = 34;
M_.endo_nbr = 285;
M_.param_nbr = 142;
M_.orig_endo_nbr = 237;
M_.aux_vars(1).endo_index = 238;
M_.aux_vars(1).type = 0;
M_.aux_vars(2).endo_index = 239;
M_.aux_vars(2).type = 0;
M_.aux_vars(3).endo_index = 240;
M_.aux_vars(3).type = 0;
M_.aux_vars(4).endo_index = 241;
M_.aux_vars(4).type = 0;
M_.aux_vars(5).endo_index = 242;
M_.aux_vars(5).type = 0;
M_.aux_vars(6).endo_index = 243;
M_.aux_vars(6).type = 0;
M_.aux_vars(7).endo_index = 244;
M_.aux_vars(7).type = 0;
M_.aux_vars(8).endo_index = 245;
M_.aux_vars(8).type = 0;
M_.aux_vars(9).endo_index = 246;
M_.aux_vars(9).type = 0;
M_.aux_vars(10).endo_index = 247;
M_.aux_vars(10).type = 0;
M_.aux_vars(11).endo_index = 248;
M_.aux_vars(11).type = 0;
M_.aux_vars(12).endo_index = 249;
M_.aux_vars(12).type = 0;
M_.aux_vars(13).endo_index = 250;
M_.aux_vars(13).type = 0;
M_.aux_vars(14).endo_index = 251;
M_.aux_vars(14).type = 0;
M_.aux_vars(15).endo_index = 252;
M_.aux_vars(15).type = 0;
M_.aux_vars(16).endo_index = 253;
M_.aux_vars(16).type = 0;
M_.aux_vars(17).endo_index = 254;
M_.aux_vars(17).type = 0;
M_.aux_vars(18).endo_index = 255;
M_.aux_vars(18).type = 0;
M_.aux_vars(19).endo_index = 256;
M_.aux_vars(19).type = 0;
M_.aux_vars(20).endo_index = 257;
M_.aux_vars(20).type = 0;
M_.aux_vars(21).endo_index = 258;
M_.aux_vars(21).type = 0;
M_.aux_vars(22).endo_index = 259;
M_.aux_vars(22).type = 0;
M_.aux_vars(23).endo_index = 260;
M_.aux_vars(23).type = 0;
M_.aux_vars(24).endo_index = 261;
M_.aux_vars(24).type = 0;
M_.aux_vars(25).endo_index = 262;
M_.aux_vars(25).type = 1;
M_.aux_vars(25).orig_index = 235;
M_.aux_vars(25).orig_lead_lag = -1;
M_.aux_vars(26).endo_index = 263;
M_.aux_vars(26).type = 1;
M_.aux_vars(26).orig_index = 235;
M_.aux_vars(26).orig_lead_lag = -2;
M_.aux_vars(27).endo_index = 264;
M_.aux_vars(27).type = 1;
M_.aux_vars(27).orig_index = 235;
M_.aux_vars(27).orig_lead_lag = -3;
M_.aux_vars(28).endo_index = 265;
M_.aux_vars(28).type = 1;
M_.aux_vars(28).orig_index = 236;
M_.aux_vars(28).orig_lead_lag = -1;
M_.aux_vars(29).endo_index = 266;
M_.aux_vars(29).type = 1;
M_.aux_vars(29).orig_index = 236;
M_.aux_vars(29).orig_lead_lag = -2;
M_.aux_vars(30).endo_index = 267;
M_.aux_vars(30).type = 1;
M_.aux_vars(30).orig_index = 236;
M_.aux_vars(30).orig_lead_lag = -3;
M_.aux_vars(31).endo_index = 268;
M_.aux_vars(31).type = 1;
M_.aux_vars(31).orig_index = 232;
M_.aux_vars(31).orig_lead_lag = -1;
M_.aux_vars(32).endo_index = 269;
M_.aux_vars(32).type = 1;
M_.aux_vars(32).orig_index = 232;
M_.aux_vars(32).orig_lead_lag = -2;
M_.aux_vars(33).endo_index = 270;
M_.aux_vars(33).type = 1;
M_.aux_vars(33).orig_index = 232;
M_.aux_vars(33).orig_lead_lag = -3;
M_.aux_vars(34).endo_index = 271;
M_.aux_vars(34).type = 1;
M_.aux_vars(34).orig_index = 234;
M_.aux_vars(34).orig_lead_lag = -1;
M_.aux_vars(35).endo_index = 272;
M_.aux_vars(35).type = 1;
M_.aux_vars(35).orig_index = 234;
M_.aux_vars(35).orig_lead_lag = -2;
M_.aux_vars(36).endo_index = 273;
M_.aux_vars(36).type = 1;
M_.aux_vars(36).orig_index = 234;
M_.aux_vars(36).orig_lead_lag = -3;
M_.aux_vars(37).endo_index = 274;
M_.aux_vars(37).type = 1;
M_.aux_vars(37).orig_index = 114;
M_.aux_vars(37).orig_lead_lag = -1;
M_.aux_vars(38).endo_index = 275;
M_.aux_vars(38).type = 1;
M_.aux_vars(38).orig_index = 114;
M_.aux_vars(38).orig_lead_lag = -2;
M_.aux_vars(39).endo_index = 276;
M_.aux_vars(39).type = 1;
M_.aux_vars(39).orig_index = 114;
M_.aux_vars(39).orig_lead_lag = -3;
M_.aux_vars(40).endo_index = 277;
M_.aux_vars(40).type = 1;
M_.aux_vars(40).orig_index = 145;
M_.aux_vars(40).orig_lead_lag = -1;
M_.aux_vars(41).endo_index = 278;
M_.aux_vars(41).type = 1;
M_.aux_vars(41).orig_index = 145;
M_.aux_vars(41).orig_lead_lag = -2;
M_.aux_vars(42).endo_index = 279;
M_.aux_vars(42).type = 1;
M_.aux_vars(42).orig_index = 145;
M_.aux_vars(42).orig_lead_lag = -3;
M_.aux_vars(43).endo_index = 280;
M_.aux_vars(43).type = 1;
M_.aux_vars(43).orig_index = 122;
M_.aux_vars(43).orig_lead_lag = -1;
M_.aux_vars(44).endo_index = 281;
M_.aux_vars(44).type = 1;
M_.aux_vars(44).orig_index = 122;
M_.aux_vars(44).orig_lead_lag = -2;
M_.aux_vars(45).endo_index = 282;
M_.aux_vars(45).type = 1;
M_.aux_vars(45).orig_index = 122;
M_.aux_vars(45).orig_lead_lag = -3;
M_.aux_vars(46).endo_index = 283;
M_.aux_vars(46).type = 1;
M_.aux_vars(46).orig_index = 127;
M_.aux_vars(46).orig_lead_lag = -1;
M_.aux_vars(47).endo_index = 284;
M_.aux_vars(47).type = 1;
M_.aux_vars(47).orig_index = 127;
M_.aux_vars(47).orig_lead_lag = -2;
M_.aux_vars(48).endo_index = 285;
M_.aux_vars(48).type = 1;
M_.aux_vars(48).orig_index = 127;
M_.aux_vars(48).orig_lead_lag = -3;
M_.Sigma_e = zeros(34, 34);
M_.Correlation_matrix = eye(34, 34);
M_.H = 0;
M_.Correlation_matrix_ME = 1;
M_.sigma_e_is_diagonal = 1;
options_.linear = 1;
options_.block=0;
options_.bytecode=0;
options_.use_dll=0;
erase_compiled_function('G2_SIGMA08_static');
erase_compiled_function('G2_SIGMA08_dynamic');
M_.lead_lag_incidence = [
 0 136 0;
 0 137 0;
 0 138 0;
 1 139 421;
 0 140 0;
 0 141 422;
 2 142 0;
 0 143 0;
 0 144 423;
 3 145 0;
 0 146 0;
 0 147 0;
 0 148 0;
 0 149 0;
 0 150 0;
 4 151 424;
 5 152 425;
 0 153 0;
 0 154 0;
 0 155 0;
 0 156 0;
 0 157 0;
 6 158 426;
 7 159 0;
 8 160 427;
 9 161 0;
 0 162 0;
 10 163 428;
 11 164 0;
 12 165 0;
 13 166 0;
 14 167 0;
 0 168 429;
 0 169 0;
 0 170 0;
 15 171 0;
 0 172 430;
 16 173 431;
 17 174 0;
 0 175 0;
 0 176 432;
 0 177 433;
 0 178 434;
 0 179 435;
 0 180 436;
 0 181 437;
 0 182 438;
 0 183 439;
 0 184 440;
 0 185 441;
 0 186 442;
 0 187 443;
 0 188 444;
 0 189 445;
 0 190 446;
 0 191 447;
 0 192 448;
 0 193 449;
 0 194 450;
 0 195 451;
 0 196 0;
 0 197 0;
 0 198 0;
 0 199 0;
 18 200 0;
 0 201 452;
 0 202 0;
 0 203 0;
 19 204 0;
 20 205 0;
 0 206 0;
 21 207 0;
 22 208 0;
 0 209 0;
 23 210 0;
 24 211 0;
 25 212 0;
 0 213 0;
 0 214 0;
 0 215 0;
 0 216 0;
 0 217 0;
 0 218 0;
 0 219 0;
 0 220 0;
 0 221 0;
 0 222 0;
 0 223 453;
 0 224 0;
 0 225 0;
 26 226 0;
 27 227 0;
 28 228 0;
 29 229 0;
 0 230 0;
 30 231 0;
 31 232 0;
 32 233 0;
 33 234 0;
 0 235 0;
 34 236 0;
 35 237 0;
 36 238 0;
 0 239 0;
 0 240 0;
 0 241 0;
 0 242 0;
 37 243 454;
 0 244 0;
 0 245 455;
 38 246 0;
 0 247 0;
 0 248 456;
 39 249 457;
 0 250 0;
 0 251 0;
 0 252 0;
 0 253 0;
 0 254 0;
 40 255 458;
 41 256 459;
 42 257 0;
 0 258 0;
 0 259 0;
 0 260 0;
 0 261 0;
 43 262 460;
 44 263 0;
 45 264 461;
 46 265 0;
 0 266 0;
 47 267 462;
 48 268 0;
 49 269 0;
 50 270 0;
 0 271 0;
 0 272 0;
 0 273 0;
 0 274 0;
 51 275 0;
 0 276 463;
 52 277 464;
 53 278 0;
 0 279 0;
 54 280 465;
 0 281 0;
 55 282 0;
 56 283 0;
 0 284 0;
 57 285 0;
 58 286 0;
 0 287 0;
 0 288 0;
 0 289 0;
 59 290 0;
 60 291 0;
 61 292 0;
 0 293 0;
 0 294 0;
 0 295 0;
 0 296 0;
 0 297 466;
 62 298 0;
 0 299 0;
 63 300 0;
 64 301 0;
 0 302 467;
 65 303 0;
 0 304 0;
 66 305 0;
 67 306 0;
 68 307 0;
 69 308 0;
 70 309 0;
 0 310 468;
 0 311 469;
 0 312 470;
 0 313 471;
 0 314 0;
 0 315 0;
 0 316 0;
 0 317 0;
 0 318 472;
 0 319 0;
 71 320 0;
 0 321 0;
 0 322 0;
 0 323 0;
 0 324 473;
 0 325 0;
 0 326 0;
 0 327 0;
 72 328 0;
 73 329 0;
 74 330 0;
 75 331 0;
 76 332 0;
 77 333 0;
 78 334 0;
 79 335 0;
 80 336 0;
 81 337 0;
 82 338 0;
 0 339 0;
 83 340 0;
 84 341 0;
 85 342 0;
 86 343 0;
 87 344 0;
 88 345 0;
 89 346 0;
 90 347 0;
 91 348 0;
 92 349 0;
 93 350 0;
 94 351 0;
 95 352 0;
 0 353 0;
 96 354 0;
 97 355 0;
 98 356 0;
 99 357 0;
 100 358 0;
 101 359 0;
 102 360 0;
 103 361 0;
 104 362 0;
 105 363 0;
 106 364 0;
 107 365 0;
 0 366 0;
 108 367 0;
 0 368 0;
 109 369 474;
 110 370 475;
 111 371 476;
 0 372 0;
 0 373 477;
 0 374 478;
 0 375 479;
 0 376 480;
 0 377 481;
 0 378 482;
 0 379 483;
 0 380 484;
 0 381 485;
 0 382 486;
 0 383 487;
 0 384 488;
 0 385 489;
 0 386 490;
 0 387 491;
 0 388 492;
 0 389 493;
 0 390 494;
 0 391 495;
 0 392 496;
 0 393 497;
 0 394 498;
 0 395 499;
 0 396 500;
 112 397 0;
 113 398 0;
 114 399 0;
 115 400 0;
 116 401 0;
 117 402 0;
 118 403 0;
 119 404 0;
 120 405 0;
 121 406 0;
 122 407 0;
 123 408 0;
 124 409 0;
 125 410 0;
 126 411 0;
 127 412 0;
 128 413 0;
 129 414 0;
 130 415 0;
 131 416 0;
 132 417 0;
 133 418 0;
 134 419 0;
 135 420 0;]';
M_.nstatic = 89;
M_.nfwrd   = 61;
M_.npred   = 116;
M_.nboth   = 19;
M_.nsfwrd   = 80;
M_.nspred   = 135;
M_.ndynamic   = 196;
M_.equations_tags = {
};
M_.static_and_dynamic_models_differ = 0;
M_.exo_names_orig_ord = [1:34];
M_.maximum_lag = 1;
M_.maximum_lead = 1;
M_.maximum_endo_lag = 1;
M_.maximum_endo_lead = 1;
oo_.steady_state = zeros(285, 1);
M_.maximum_exo_lag = 0;
M_.maximum_exo_lead = 0;
oo_.exo_steady_state = zeros(34, 1);
M_.params = NaN(142, 1);
M_.NNZDerivatives = zeros(3, 1);
M_.NNZDerivatives(1) = 976;
M_.NNZDerivatives(2) = 0;
M_.NNZDerivatives(3) = -1;
M_.params( 56 ) = 0;
forswitch = M_.params( 56 );
M_.params( 102 ) = 1;
switchg = M_.params( 102 );
M_.params( 112 ) = 1;
taxkgswitch = M_.params( 112 );
M_.params( 100 ) = 1;
taxwedgeswitch = M_.params( 100 );
M_.params( 99 ) = 1;
taxlwedgeswitch = M_.params( 99 );
M_.params( 46 ) = 1;
invfor = M_.params( 46 );
M_.params( 49 ) = 0;
defspread = M_.params( 49 );
M_.params( 57 ) = 0;
lovparm = M_.params( 57 );
M_.params( 40 ) = 0.0025;
popg = M_.params( 40 );
M_.params( 39 ) = 1.0037;
gzbar = M_.params( 39 );
M_.params( 123 ) = 1;
cesparm = M_.params( 123 );
M_.params( 50 ) = (-1);
cessub = M_.params( 50 );
M_.params( 48 ) = .3;
tauk = M_.params( 48 );
M_.params( 64 ) = .2;
taul = M_.params( 64 );
M_.params( 124 ) = .997;
beta = M_.params( 124 );
M_.params( 42 ) = 0.25;
shriy = M_.params( 42 );
M_.params( 37 ) = .18;
shrgy = M_.params( 37 );
M_.params( 52 ) = 0.052;
shrmc = M_.params( 52 );
M_.params( 53 ) = 0.36;
shrmi = M_.params( 53 );
M_.params( 95 ) = .8;
phic = M_.params( 95 );
M_.params( 96 ) = .01;
xsic = M_.params( 96 );
M_.params( 66 ) = .5;
shrlab = M_.params( 66 );
M_.params( 125 ) = .1;
thetap = M_.params( 125 );
M_.params( 126 ) = .1;
thetaw = M_.params( 126 );
M_.params( 127 ) = 0;
taup = M_.params( 127 );
M_.params( 94 ) = 2;
sigma = M_.params( 94 );
M_.params( 65 ) = 10;
chi = M_.params( 65 );
M_.params( 41 ) = .025;
delta = M_.params( 41 );
M_.params( 43 ) = 0;
phik = M_.params( 43 );
M_.params( 45 ) = 3;
phii = M_.params( 45 );
M_.params( 140 ) = 10;
phimitilde = M_.params( 140 );
M_.params( 141 ) = M_.params(140);
phimctilde = M_.params( 141 );
M_.params( 128 ) = M_.params(140)*(1-M_.params(53));
phimi = M_.params( 128 );
M_.params( 55 ) = M_.params(141)*(1-M_.params(52));
phimc = M_.params( 55 );
M_.params( 142 ) = M_.params(128);
phimif = M_.params( 142 );
M_.params( 85 ) = M_.params(55);
phimcf = M_.params( 85 );
M_.params( 129 ) = 0;
prodg = M_.params( 129 );
M_.params( 101 ) = .025;
deltag = M_.params( 101 );
M_.params( 54 ) = 1.5;
etamc = M_.params( 54 );
M_.params( 130 ) = 1.5;
etami = M_.params( 130 );
M_.params( 67 ) = 1;
indexp = M_.params( 67 );
M_.params( 71 ) = 1;
indexw = M_.params( 71 );
M_.params( 69 ) = 1;
indexm = M_.params( 69 );
M_.params( 131 ) = .75;
psip = M_.params( 131 );
M_.params( 132 ) = .75;
psiw = M_.params( 132 );
M_.params( 133 ) = 0.5;
psixf = M_.params( 133 );
M_.params( 134 ) = .5;
popkey = M_.params( 134 );
M_.params( 97 ) = .0001;
phid1 = M_.params( 97 );
M_.params( 98 ) = .01;
phid2 = M_.params( 98 );
M_.params( 119 ) = 0;
phid3 = M_.params( 119 );
M_.params( 120 ) = 0;
phid4 = M_.params( 120 );
M_.params( 118 ) = .98;
rho15 = M_.params( 118 );
M_.params( 121 ) = .98;
rho15p = M_.params( 121 );
M_.params( 122 ) = 0;
rho15t = M_.params( 122 );
M_.params( 58 ) = .8;
monlag = M_.params( 58 );
M_.params( 59 ) = 3;
gampi = M_.params( 59 );
M_.params( 60 ) = 0;
gamex = M_.params( 60 );
M_.params( 61 ) = 0;
gamy = M_.params( 61 );
M_.params( 63 ) = 0;
gamgap = M_.params( 63 );
M_.params( 62 ) = 1.4;
gamy4 = M_.params( 62 );
M_.params( 103 ) = .975;
rho1p = M_.params( 103 );
M_.params( 104 ) = 0;
rho1t = M_.params( 104 );
M_.params( 105 ) = .975;
rho2p = M_.params( 105 );
M_.params( 106 ) = 0;
rho2t = M_.params( 106 );
M_.params( 107 ) = .999;
rho3p = M_.params( 107 );
M_.params( 108 ) = 0;
rho3t = M_.params( 108 );
M_.params( 109 ) = .95;
rho4p = M_.params( 109 );
M_.params( 110 ) = .5;
rho4t = M_.params( 110 );
M_.params( 111 ) = .995;
rho5p = M_.params( 111 );
M_.params( 113 ) = .9;
rho5t = M_.params( 113 );
M_.params( 114 ) = .98;
rho11p = M_.params( 114 );
M_.params( 115 ) = .7;
rho11t = M_.params( 115 );
M_.params( 116 ) = .95;
rho13 = M_.params( 116 );
M_.params( 117 ) = .95;
rho14 = M_.params( 117 );
M_.params( 83 ) = M_.params(54);
etamcf = M_.params( 83 );
M_.params( 84 ) = M_.params(130);
etamif = M_.params( 84 );
M_.params( 36 ) = 1-M_.params(42)-M_.params(37);
shrcy = M_.params( 36 );
M_.params( 51 ) = M_.params(52)*M_.params(36)+M_.params(53)*M_.params(42);
shrmy = M_.params( 51 );
M_.params( 44 ) = M_.params(39)*(1+M_.params(40))-(1-M_.params(41));
deltahat = M_.params( 44 );
M_.params( 47 ) = M_.params(41);
inddelta = M_.params( 47 );
M_.params( 38 ) = M_.params(39)^M_.params(94)/M_.params(124)-1;
rbar = M_.params( 38 );
M_.params( 75 ) = (M_.params(41)+M_.params(38)-M_.params(48)*M_.params(47))/(1-M_.params(48));
rkbar = M_.params( 75 );
M_.params( 73 ) = M_.params(42)*(M_.params(41)+1/M_.params(124)-1)/M_.params(41);
qcapshr = M_.params( 73 );
M_.params( 74 ) = (1+M_.params(127))/(1+M_.params(125))-M_.params(73);
shrlaby = M_.params( 74 );
M_.params( 35 ) = M_.params(134)*1/M_.params(36)*(M_.params(74)+M_.params(48)*M_.params(73)*(1-M_.params(47)/M_.params(75))-M_.params(37));
shrckey = M_.params( 35 );
M_.params( 86 ) = M_.params(58);
monlagf = M_.params( 86 );
M_.params( 87 ) = M_.params(60);
gamexf = M_.params( 87 );
M_.params( 88 ) = M_.params(61);
gamyf = M_.params( 88 );
M_.params( 90 ) = M_.params(63);
gamgapf = M_.params( 90 );
M_.params( 89 ) = M_.params(62);
gamy4f = M_.params( 89 );
M_.params( 78 ) = M_.params(42);
shriyf = M_.params( 78 );
M_.params( 79 ) = M_.params(37);
shrgyf = M_.params( 79 );
M_.params( 77 ) = 1-M_.params(78)-M_.params(79);
shrcyf = M_.params( 77 );
M_.params( 81 ) = M_.params(52)/3;
shrmcf = M_.params( 81 );
M_.params( 82 ) = M_.params(53)/3;
shrmif = M_.params( 82 );
M_.params( 80 ) = M_.params(81)*M_.params(77)+M_.params(78)*M_.params(82);
shrmyf = M_.params( 80 );
M_.params( 135 ) = M_.params(131);
psipf = M_.params( 135 );
M_.params( 136 ) = M_.params(132);
psiwf = M_.params( 136 );
M_.params( 137 ) = M_.params(133);
psix = M_.params( 137 );
M_.params( 138 ) = M_.params(125);
thetapf = M_.params( 138 );
M_.params( 139 ) = M_.params(126);
thetawf = M_.params( 139 );
M_.params( 85 ) = M_.params(55);
phimcf = M_.params( 85 );
M_.params( 76 ) = M_.params(35);
shrckeyf = M_.params( 76 );
M_.params( 68 ) = (1-M_.params(131))*(1-M_.params(124)*M_.params(131))/M_.params(131);
kappap = M_.params( 68 );
M_.params( 72 ) = (1-M_.params(132))*(1-M_.params(124)*M_.params(132))/(M_.params(132)*(1+M_.params(65)*M_.params(66)*(1+M_.params(126))/M_.params(126)));
kappaw = M_.params( 72 );
M_.params( 70 ) = (1-M_.params(137))*(1-M_.params(124)*M_.params(137))/M_.params(137);
kappax = M_.params( 70 );
M_.params( 91 ) = (1-M_.params(135))*(1-M_.params(124)*M_.params(135))/M_.params(135);
kappapf = M_.params( 91 );
M_.params( 92 ) = (1-M_.params(133))*(1-M_.params(124)*M_.params(133))/M_.params(133);
kappaxf = M_.params( 92 );
M_.params( 93 ) = (1-M_.params(136))*(1-M_.params(124)*M_.params(136))/(M_.params(136)*(1+M_.params(65)*M_.params(66)*(1+M_.params(139))/M_.params(139)));
kappawf = M_.params( 93 );
thispath = cd;                                                           
cd('..');                                                                
load policy_param.mat;                                                   
for i=1:33                                                               
deep_parameter_name = M_.param_names(i,:);                           
eval(['M_.params(i)  = ' deep_parameter_name ' ;'])                  
end                                                                      
cd(thispath);   
M_.params( 34 ) = 1;
coffispol = M_.params( 34 );
%
% SHOCKS instructions
%
make_ex_;
M_.exo_det_length = 0;
M_.Sigma_e(1, 1) = 0;
M_.Sigma_e(2, 2) = 0;
M_.Sigma_e(3, 3) = 0;
M_.Sigma_e(4, 4) = 0;
M_.Sigma_e(5, 5) = 0;
M_.Sigma_e(6, 6) = 0;
M_.Sigma_e(7, 7) = 0;
M_.Sigma_e(8, 8) = 0;
M_.Sigma_e(9, 9) = 0;
M_.Sigma_e(10, 10) = 0;
M_.Sigma_e(11, 11) = 0;
M_.Sigma_e(12, 12) = 0;
M_.Sigma_e(13, 13) = 0;
M_.Sigma_e(14, 14) = 0;
M_.Sigma_e(15, 15) = 0;
M_.Sigma_e(16, 16) = 0;
M_.Sigma_e(17, 17) = 0;
M_.Sigma_e(18, 18) = 0;
M_.Sigma_e(19, 19) = 0;
M_.Sigma_e(20, 20) = 0;
M_.Sigma_e(21, 21) = 0;
M_.Sigma_e(22, 22) = 0;
M_.Sigma_e(23, 23) = 0;
M_.Sigma_e(24, 24) = 0;
M_.Sigma_e(25, 25) = 0;
M_.Sigma_e(26, 26) = 0;
M_.Sigma_e(27, 27) = 0;
M_.Sigma_e(28, 28) = 0;
M_.Sigma_e(29, 29) = 0;
M_.Sigma_e(30, 30) = 0;
M_.Sigma_e(31, 31) = 0;
M_.Sigma_e(32, 32) = 0;
M_.Sigma_e(33, 33) = 0;
M_.Sigma_e(34, 34) = 0;
save('G2_SIGMA08_results.mat', 'oo_', 'M_', 'options_');
if exist('estim_params_', 'var') == 1
  save('G2_SIGMA08_results.mat', 'estim_params_', '-append');
end
if exist('bayestopt_', 'var') == 1
  save('G2_SIGMA08_results.mat', 'bayestopt_', '-append');
end
if exist('dataset_', 'var') == 1
  save('G2_SIGMA08_results.mat', 'dataset_', '-append');
end
if exist('estimation_info', 'var') == 1
  save('G2_SIGMA08_results.mat', 'estimation_info', '-append');
end


disp(['Total computing time : ' dynsec2hms(toc) ]);
if ~isempty(lastwarn)
  disp('Note: warning(s) encountered in MATLAB/Octave code')
end
diary off
