%
% Status : main Dynare file 
%
% Warning : this file is generated automatically by Dynare
%           from model file (.mod)

tic;
global M_ oo_ options_ ys0_ ex0_ estimation_info
options_ = [];
M_.fname = 'US_FGKR15';
%
% Some global variables initialization
%
global_initialization;
diary off;
diary('US_FGKR15.log');
M_.exo_names = 'ect';
M_.exo_names_tex = 'ect';
M_.exo_names_long = 'ect';
M_.exo_names = char(M_.exo_names, 'edt');
M_.exo_names_tex = char(M_.exo_names_tex, 'edt');
M_.exo_names_long = char(M_.exo_names_long, 'edt');
M_.exo_names = char(M_.exo_names, 'ekt');
M_.exo_names_tex = char(M_.exo_names_tex, 'ekt');
M_.exo_names_long = char(M_.exo_names_long, 'ekt');
M_.exo_names = char(M_.exo_names, 'ewt');
M_.exo_names_tex = char(M_.exo_names_tex, 'ewt');
M_.exo_names_long = char(M_.exo_names_long, 'ewt');
M_.exo_names = char(M_.exo_names, 'ezt');
M_.exo_names_tex = char(M_.exo_names_tex, 'ezt');
M_.exo_names_long = char(M_.exo_names_long, 'ezt');
M_.exo_names = char(M_.exo_names, 'uct');
M_.exo_names_tex = char(M_.exo_names_tex, 'uct');
M_.exo_names_long = char(M_.exo_names_long, 'uct');
M_.exo_names = char(M_.exo_names, 'ugt');
M_.exo_names_tex = char(M_.exo_names_tex, 'ugt');
M_.exo_names_long = char(M_.exo_names_long, 'ugt');
M_.exo_names = char(M_.exo_names, 'ukt');
M_.exo_names_tex = char(M_.exo_names_tex, 'ukt');
M_.exo_names_long = char(M_.exo_names_long, 'ukt');
M_.exo_names = char(M_.exo_names, 'uwt');
M_.exo_names_tex = char(M_.exo_names_tex, 'uwt');
M_.exo_names_long = char(M_.exo_names_long, 'uwt');
M_.exo_names = char(M_.exo_names, 'interest_');
M_.exo_names_tex = char(M_.exo_names_tex, 'interest\_');
M_.exo_names_long = char(M_.exo_names_long, 'interest_');
M_.exo_names = char(M_.exo_names, 'fiscal_');
M_.exo_names_tex = char(M_.exo_names_tex, 'fiscal\_');
M_.exo_names_long = char(M_.exo_names_long, 'fiscal_');
M_.endo_names = 'bdt';
M_.endo_names_tex = 'bdt';
M_.endo_names_long = 'bdt';
M_.endo_names = char(M_.endo_names, 'ct');
M_.endo_names_tex = char(M_.endo_names_tex, 'ct');
M_.endo_names_long = char(M_.endo_names_long, 'ct');
M_.endo_names = char(M_.endo_names, 'dt');
M_.endo_names_tex = char(M_.endo_names_tex, 'dt');
M_.endo_names_long = char(M_.endo_names_long, 'dt');
M_.endo_names = char(M_.endo_names, 'gt');
M_.endo_names_tex = char(M_.endo_names_tex, 'gt');
M_.endo_names_long = char(M_.endo_names_long, 'gt');
M_.endo_names = char(M_.endo_names, 'ht');
M_.endo_names_tex = char(M_.endo_names_tex, 'ht');
M_.endo_names_long = char(M_.endo_names_long, 'ht');
M_.endo_names = char(M_.endo_names, 'inflt');
M_.endo_names_tex = char(M_.endo_names_tex, 'inflt');
M_.endo_names_long = char(M_.endo_names_long, 'inflt');
M_.endo_names = char(M_.endo_names, 'invt');
M_.endo_names_tex = char(M_.endo_names_tex, 'invt');
M_.endo_names_long = char(M_.endo_names_long, 'invt');
M_.endo_names = char(M_.endo_names, 'kt');
M_.endo_names_tex = char(M_.endo_names_tex, 'kt');
M_.endo_names_long = char(M_.endo_names_long, 'kt');
M_.endo_names = char(M_.endo_names, 'kbt');
M_.endo_names_tex = char(M_.endo_names_tex, 'kbt');
M_.endo_names_long = char(M_.endo_names_long, 'kbt');
M_.endo_names = char(M_.endo_names, 'lamt');
M_.endo_names_tex = char(M_.endo_names_tex, 'lamt');
M_.endo_names_long = char(M_.endo_names_long, 'lamt');
M_.endo_names = char(M_.endo_names, 'mct');
M_.endo_names_tex = char(M_.endo_names_tex, 'mct');
M_.endo_names_long = char(M_.endo_names_long, 'mct');
M_.endo_names = char(M_.endo_names, 'miut');
M_.endo_names_tex = char(M_.endo_names_tex, 'miut');
M_.endo_names_long = char(M_.endo_names_long, 'miut');
M_.endo_names = char(M_.endo_names, 'miubt');
M_.endo_names_tex = char(M_.endo_names_tex, 'miubt');
M_.endo_names_long = char(M_.endo_names_long, 'miubt');
M_.endo_names = char(M_.endo_names, 'proft');
M_.endo_names_tex = char(M_.endo_names_tex, 'proft');
M_.endo_names_long = char(M_.endo_names_long, 'proft');
M_.endo_names = char(M_.endo_names, 'Rt');
M_.endo_names_tex = char(M_.endo_names_tex, 'Rt');
M_.endo_names_long = char(M_.endo_names_long, 'Rt');
M_.endo_names = char(M_.endo_names, 'rkt');
M_.endo_names_tex = char(M_.endo_names_tex, 'rkt');
M_.endo_names_long = char(M_.endo_names_long, 'rkt');
M_.endo_names = char(M_.endo_names, 'tauct');
M_.endo_names_tex = char(M_.endo_names_tex, 'tauct');
M_.endo_names_long = char(M_.endo_names_long, 'tauct');
M_.endo_names = char(M_.endo_names, 'taukt');
M_.endo_names_tex = char(M_.endo_names_tex, 'taukt');
M_.endo_names_long = char(M_.endo_names_long, 'taukt');
M_.endo_names = char(M_.endo_names, 'tauwt');
M_.endo_names_tex = char(M_.endo_names_tex, 'tauwt');
M_.endo_names_long = char(M_.endo_names_long, 'tauwt');
M_.endo_names = char(M_.endo_names, 'utilt');
M_.endo_names_tex = char(M_.endo_names_tex, 'utilt');
M_.endo_names_long = char(M_.endo_names_long, 'utilt');
M_.endo_names = char(M_.endo_names, 'wt');
M_.endo_names_tex = char(M_.endo_names_tex, 'wt');
M_.endo_names_long = char(M_.endo_names_long, 'wt');
M_.endo_names = char(M_.endo_names, 'yt');
M_.endo_names_tex = char(M_.endo_names_tex, 'yt');
M_.endo_names_long = char(M_.endo_names_long, 'yt');
M_.endo_names = char(M_.endo_names, 'gzt');
M_.endo_names_tex = char(M_.endo_names_tex, 'gzt');
M_.endo_names_long = char(M_.endo_names_long, 'gzt');
M_.endo_names = char(M_.endo_names, 'gyt');
M_.endo_names_tex = char(M_.endo_names_tex, 'gyt');
M_.endo_names_long = char(M_.endo_names_long, 'gyt');
M_.endo_names = char(M_.endo_names, 'gct');
M_.endo_names_tex = char(M_.endo_names_tex, 'gct');
M_.endo_names_long = char(M_.endo_names_long, 'gct');
M_.endo_names = char(M_.endo_names, 'git');
M_.endo_names_tex = char(M_.endo_names_tex, 'git');
M_.endo_names_long = char(M_.endo_names_long, 'git');
M_.endo_names = char(M_.endo_names, 'gwt');
M_.endo_names_tex = char(M_.endo_names_tex, 'gwt');
M_.endo_names_long = char(M_.endo_names_long, 'gwt');
M_.endo_names = char(M_.endo_names, 'egt');
M_.endo_names_tex = char(M_.endo_names_tex, 'egt');
M_.endo_names_long = char(M_.endo_names_long, 'egt');
M_.endo_names = char(M_.endo_names, 'sigct');
M_.endo_names_tex = char(M_.endo_names_tex, 'sigct');
M_.endo_names_long = char(M_.endo_names_long, 'sigct');
M_.endo_names = char(M_.endo_names, 'siggt');
M_.endo_names_tex = char(M_.endo_names_tex, 'siggt');
M_.endo_names_long = char(M_.endo_names_long, 'siggt');
M_.endo_names = char(M_.endo_names, 'sigkt');
M_.endo_names_tex = char(M_.endo_names_tex, 'sigkt');
M_.endo_names_long = char(M_.endo_names_long, 'sigkt');
M_.endo_names = char(M_.endo_names, 'sigwt');
M_.endo_names_tex = char(M_.endo_names_tex, 'sigwt');
M_.endo_names_long = char(M_.endo_names_long, 'sigwt');
M_.endo_names = char(M_.endo_names, 'bdtF');
M_.endo_names_tex = char(M_.endo_names_tex, 'bdtF');
M_.endo_names_long = char(M_.endo_names_long, 'bdtF');
M_.endo_names = char(M_.endo_names, 'ctF');
M_.endo_names_tex = char(M_.endo_names_tex, 'ctF');
M_.endo_names_long = char(M_.endo_names_long, 'ctF');
M_.endo_names = char(M_.endo_names, 'gtF');
M_.endo_names_tex = char(M_.endo_names_tex, 'gtF');
M_.endo_names_long = char(M_.endo_names_long, 'gtF');
M_.endo_names = char(M_.endo_names, 'htF');
M_.endo_names_tex = char(M_.endo_names_tex, 'htF');
M_.endo_names_long = char(M_.endo_names_long, 'htF');
M_.endo_names = char(M_.endo_names, 'infltF');
M_.endo_names_tex = char(M_.endo_names_tex, 'infltF');
M_.endo_names_long = char(M_.endo_names_long, 'infltF');
M_.endo_names = char(M_.endo_names, 'invtF');
M_.endo_names_tex = char(M_.endo_names_tex, 'invtF');
M_.endo_names_long = char(M_.endo_names_long, 'invtF');
M_.endo_names = char(M_.endo_names, 'ktF');
M_.endo_names_tex = char(M_.endo_names_tex, 'ktF');
M_.endo_names_long = char(M_.endo_names_long, 'ktF');
M_.endo_names = char(M_.endo_names, 'kbtF');
M_.endo_names_tex = char(M_.endo_names_tex, 'kbtF');
M_.endo_names_long = char(M_.endo_names_long, 'kbtF');
M_.endo_names = char(M_.endo_names, 'lamtF');
M_.endo_names_tex = char(M_.endo_names_tex, 'lamtF');
M_.endo_names_long = char(M_.endo_names_long, 'lamtF');
M_.endo_names = char(M_.endo_names, 'mctF');
M_.endo_names_tex = char(M_.endo_names_tex, 'mctF');
M_.endo_names_long = char(M_.endo_names_long, 'mctF');
M_.endo_names = char(M_.endo_names, 'miutF');
M_.endo_names_tex = char(M_.endo_names_tex, 'miutF');
M_.endo_names_long = char(M_.endo_names_long, 'miutF');
M_.endo_names = char(M_.endo_names, 'miubtF');
M_.endo_names_tex = char(M_.endo_names_tex, 'miubtF');
M_.endo_names_long = char(M_.endo_names_long, 'miubtF');
M_.endo_names = char(M_.endo_names, 'proftF');
M_.endo_names_tex = char(M_.endo_names_tex, 'proftF');
M_.endo_names_long = char(M_.endo_names_long, 'proftF');
M_.endo_names = char(M_.endo_names, 'RtF');
M_.endo_names_tex = char(M_.endo_names_tex, 'RtF');
M_.endo_names_long = char(M_.endo_names_long, 'RtF');
M_.endo_names = char(M_.endo_names, 'rktF');
M_.endo_names_tex = char(M_.endo_names_tex, 'rktF');
M_.endo_names_long = char(M_.endo_names_long, 'rktF');
M_.endo_names = char(M_.endo_names, 'tauctF');
M_.endo_names_tex = char(M_.endo_names_tex, 'tauctF');
M_.endo_names_long = char(M_.endo_names_long, 'tauctF');
M_.endo_names = char(M_.endo_names, 'tauktF');
M_.endo_names_tex = char(M_.endo_names_tex, 'tauktF');
M_.endo_names_long = char(M_.endo_names_long, 'tauktF');
M_.endo_names = char(M_.endo_names, 'tauwtF');
M_.endo_names_tex = char(M_.endo_names_tex, 'tauwtF');
M_.endo_names_long = char(M_.endo_names_long, 'tauwtF');
M_.endo_names = char(M_.endo_names, 'utiltF');
M_.endo_names_tex = char(M_.endo_names_tex, 'utiltF');
M_.endo_names_long = char(M_.endo_names_long, 'utiltF');
M_.endo_names = char(M_.endo_names, 'wtF');
M_.endo_names_tex = char(M_.endo_names_tex, 'wtF');
M_.endo_names_long = char(M_.endo_names_long, 'wtF');
M_.endo_names = char(M_.endo_names, 'ytF');
M_.endo_names_tex = char(M_.endo_names_tex, 'ytF');
M_.endo_names_long = char(M_.endo_names_long, 'ytF');
M_.endo_names = char(M_.endo_names, 'gytF');
M_.endo_names_tex = char(M_.endo_names_tex, 'gytF');
M_.endo_names_long = char(M_.endo_names_long, 'gytF');
M_.endo_names = char(M_.endo_names, 'gctF');
M_.endo_names_tex = char(M_.endo_names_tex, 'gctF');
M_.endo_names_long = char(M_.endo_names_long, 'gctF');
M_.endo_names = char(M_.endo_names, 'gitF');
M_.endo_names_tex = char(M_.endo_names_tex, 'gitF');
M_.endo_names_long = char(M_.endo_names_long, 'gitF');
M_.endo_names = char(M_.endo_names, 'gwtF');
M_.endo_names_tex = char(M_.endo_names_tex, 'gwtF');
M_.endo_names_long = char(M_.endo_names_long, 'gwtF');
M_.endo_names = char(M_.endo_names, 'interest');
M_.endo_names_tex = char(M_.endo_names_tex, 'interest');
M_.endo_names_long = char(M_.endo_names_long, 'interest');
M_.endo_names = char(M_.endo_names, 'inflation');
M_.endo_names_tex = char(M_.endo_names_tex, 'inflation');
M_.endo_names_long = char(M_.endo_names_long, 'inflation');
M_.endo_names = char(M_.endo_names, 'inflationq');
M_.endo_names_tex = char(M_.endo_names_tex, 'inflationq');
M_.endo_names_long = char(M_.endo_names_long, 'inflationq');
M_.endo_names = char(M_.endo_names, 'output');
M_.endo_names_tex = char(M_.endo_names_tex, 'output');
M_.endo_names_long = char(M_.endo_names_long, 'output');
M_.endo_names = char(M_.endo_names, 'outputgap');
M_.endo_names_tex = char(M_.endo_names_tex, 'outputgap');
M_.endo_names_long = char(M_.endo_names_long, 'outputgap');
M_.endo_names = char(M_.endo_names, 'fispol');
M_.endo_names_tex = char(M_.endo_names_tex, 'fispol');
M_.endo_names_long = char(M_.endo_names_long, 'fispol');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_98');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_98');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_98');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_102');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_102');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_102');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_106');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_106');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_106');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_133');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_133');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_133');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_137');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_137');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_137');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_141');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_141');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_141');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_168');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_168');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_168');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_172');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_172');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_172');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_176');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_176');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_176');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_5_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_5\_1');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_5_1');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_5_2');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_5\_2');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_5_2');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_60_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_60\_1');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_60_1');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_60_2');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_60\_2');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_60_2');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_60_3');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_60\_3');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_60_3');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_61_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_61\_1');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_61_1');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_61_2');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_61\_2');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_61_2');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_61_3');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_61\_3');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_61_3');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_57_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_57\_1');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_57_1');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_57_2');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_57\_2');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_57_2');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_57_3');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_57\_3');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_57_3');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_59_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_59\_1');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_59_1');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_59_2');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_59\_2');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_59_2');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_59_3');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_59\_3');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_59_3');
M_.param_names = 'cofintintb1';
M_.param_names_tex = 'cofintintb1';
M_.param_names_long = 'cofintintb1';
M_.param_names = char(M_.param_names, 'cofintintb2');
M_.param_names_tex = char(M_.param_names_tex, 'cofintintb2');
M_.param_names_long = char(M_.param_names_long, 'cofintintb2');
M_.param_names = char(M_.param_names, 'cofintintb3');
M_.param_names_tex = char(M_.param_names_tex, 'cofintintb3');
M_.param_names_long = char(M_.param_names_long, 'cofintintb3');
M_.param_names = char(M_.param_names, 'cofintintb4');
M_.param_names_tex = char(M_.param_names_tex, 'cofintintb4');
M_.param_names_long = char(M_.param_names_long, 'cofintintb4');
M_.param_names = char(M_.param_names, 'cofintinf0');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinf0');
M_.param_names_long = char(M_.param_names_long, 'cofintinf0');
M_.param_names = char(M_.param_names, 'cofintinfb1');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinfb1');
M_.param_names_long = char(M_.param_names_long, 'cofintinfb1');
M_.param_names = char(M_.param_names, 'cofintinfb2');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinfb2');
M_.param_names_long = char(M_.param_names_long, 'cofintinfb2');
M_.param_names = char(M_.param_names, 'cofintinfb3');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinfb3');
M_.param_names_long = char(M_.param_names_long, 'cofintinfb3');
M_.param_names = char(M_.param_names, 'cofintinfb4');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinfb4');
M_.param_names_long = char(M_.param_names_long, 'cofintinfb4');
M_.param_names = char(M_.param_names, 'cofintinff1');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinff1');
M_.param_names_long = char(M_.param_names_long, 'cofintinff1');
M_.param_names = char(M_.param_names, 'cofintinff2');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinff2');
M_.param_names_long = char(M_.param_names_long, 'cofintinff2');
M_.param_names = char(M_.param_names, 'cofintinff3');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinff3');
M_.param_names_long = char(M_.param_names_long, 'cofintinff3');
M_.param_names = char(M_.param_names, 'cofintinff4');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinff4');
M_.param_names_long = char(M_.param_names_long, 'cofintinff4');
M_.param_names = char(M_.param_names, 'cofintout');
M_.param_names_tex = char(M_.param_names_tex, 'cofintout');
M_.param_names_long = char(M_.param_names_long, 'cofintout');
M_.param_names = char(M_.param_names, 'cofintoutb1');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutb1');
M_.param_names_long = char(M_.param_names_long, 'cofintoutb1');
M_.param_names = char(M_.param_names, 'cofintoutb2');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutb2');
M_.param_names_long = char(M_.param_names_long, 'cofintoutb2');
M_.param_names = char(M_.param_names, 'cofintoutb3');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutb3');
M_.param_names_long = char(M_.param_names_long, 'cofintoutb3');
M_.param_names = char(M_.param_names, 'cofintoutb4');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutb4');
M_.param_names_long = char(M_.param_names_long, 'cofintoutb4');
M_.param_names = char(M_.param_names, 'cofintoutf1');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutf1');
M_.param_names_long = char(M_.param_names_long, 'cofintoutf1');
M_.param_names = char(M_.param_names, 'cofintoutf2');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutf2');
M_.param_names_long = char(M_.param_names_long, 'cofintoutf2');
M_.param_names = char(M_.param_names, 'cofintoutf3');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutf3');
M_.param_names_long = char(M_.param_names_long, 'cofintoutf3');
M_.param_names = char(M_.param_names, 'cofintoutf4');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutf4');
M_.param_names_long = char(M_.param_names_long, 'cofintoutf4');
M_.param_names = char(M_.param_names, 'cofintoutp');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutp');
M_.param_names_long = char(M_.param_names_long, 'cofintoutp');
M_.param_names = char(M_.param_names, 'cofintoutpb1');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpb1');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpb1');
M_.param_names = char(M_.param_names, 'cofintoutpb2');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpb2');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpb2');
M_.param_names = char(M_.param_names, 'cofintoutpb3');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpb3');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpb3');
M_.param_names = char(M_.param_names, 'cofintoutpb4');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpb4');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpb4');
M_.param_names = char(M_.param_names, 'cofintoutpf1');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpf1');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpf1');
M_.param_names = char(M_.param_names, 'cofintoutpf2');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpf2');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpf2');
M_.param_names = char(M_.param_names, 'cofintoutpf3');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpf3');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpf3');
M_.param_names = char(M_.param_names, 'cofintoutpf4');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpf4');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpf4');
M_.param_names = char(M_.param_names, 'std_r_');
M_.param_names_tex = char(M_.param_names_tex, 'std\_r\_');
M_.param_names_long = char(M_.param_names_long, 'std_r_');
M_.param_names = char(M_.param_names, 'std_r_quart');
M_.param_names_tex = char(M_.param_names_tex, 'std\_r\_quart');
M_.param_names_long = char(M_.param_names_long, 'std_r_quart');
M_.param_names = char(M_.param_names, 'coffispol');
M_.param_names_tex = char(M_.param_names_tex, 'coffispol');
M_.param_names_long = char(M_.param_names_long, 'coffispol');
M_.param_names = char(M_.param_names, 'alph');
M_.param_names_tex = char(M_.param_names_tex, 'alph');
M_.param_names_long = char(M_.param_names_long, 'alph');
M_.param_names = char(M_.param_names, 'bds');
M_.param_names_tex = char(M_.param_names_tex, 'bds');
M_.param_names_long = char(M_.param_names_long, 'bds');
M_.param_names = char(M_.param_names, 'bet');
M_.param_names_tex = char(M_.param_names_tex, 'bet');
M_.param_names_long = char(M_.param_names_long, 'bet');
M_.param_names = char(M_.param_names, 'cs');
M_.param_names_tex = char(M_.param_names_tex, 'cs');
M_.param_names_long = char(M_.param_names_long, 'cs');
M_.param_names = char(M_.param_names, 'phisigk');
M_.param_names_tex = char(M_.param_names_tex, 'phisigk');
M_.param_names_long = char(M_.param_names_long, 'phisigk');
M_.param_names = char(M_.param_names, 'deductdepr');
M_.param_names_tex = char(M_.param_names_tex, 'deductdepr');
M_.param_names_long = char(M_.param_names_long, 'deductdepr');
M_.param_names = char(M_.param_names, 'nom_depreciation');
M_.param_names_tex = char(M_.param_names_tex, 'nom\_depreciation');
M_.param_names_long = char(M_.param_names_long, 'nom_depreciation');
M_.param_names = char(M_.param_names, 'delt');
M_.param_names_tex = char(M_.param_names_tex, 'delt');
M_.param_names_long = char(M_.param_names_long, 'delt');
M_.param_names = char(M_.param_names, 'eps');
M_.param_names_tex = char(M_.param_names_tex, 'eps');
M_.param_names_long = char(M_.param_names_long, 'eps');
M_.param_names = char(M_.param_names, 'epsw');
M_.param_names_tex = char(M_.param_names_tex, 'epsw');
M_.param_names_long = char(M_.param_names_long, 'epsw');
M_.param_names = char(M_.param_names, 'deltau');
M_.param_names_tex = char(M_.param_names_tex, 'deltau');
M_.param_names_long = char(M_.param_names_long, 'deltau');
M_.param_names = char(M_.param_names, 'etac');
M_.param_names_tex = char(M_.param_names_tex, 'etac');
M_.param_names_long = char(M_.param_names_long, 'etac');
M_.param_names = char(M_.param_names, 'etag');
M_.param_names_tex = char(M_.param_names_tex, 'etag');
M_.param_names_long = char(M_.param_names_long, 'etag');
M_.param_names = char(M_.param_names, 'etak');
M_.param_names_tex = char(M_.param_names_tex, 'etak');
M_.param_names_long = char(M_.param_names_long, 'etak');
M_.param_names = char(M_.param_names, 'etaw');
M_.param_names_tex = char(M_.param_names_tex, 'etaw');
M_.param_names_long = char(M_.param_names_long, 'etaw');
M_.param_names = char(M_.param_names, 'gamcb');
M_.param_names_tex = char(M_.param_names_tex, 'gamcb');
M_.param_names_long = char(M_.param_names_long, 'gamcb');
M_.param_names = char(M_.param_names, 'gamcy');
M_.param_names_tex = char(M_.param_names_tex, 'gamcy');
M_.param_names_long = char(M_.param_names_long, 'gamcy');
M_.param_names = char(M_.param_names, 'gamgb');
M_.param_names_tex = char(M_.param_names_tex, 'gamgb');
M_.param_names_long = char(M_.param_names_long, 'gamgb');
M_.param_names = char(M_.param_names, 'gamgy');
M_.param_names_tex = char(M_.param_names_tex, 'gamgy');
M_.param_names_long = char(M_.param_names_long, 'gamgy');
M_.param_names = char(M_.param_names, 'gamkb');
M_.param_names_tex = char(M_.param_names_tex, 'gamkb');
M_.param_names_long = char(M_.param_names_long, 'gamkb');
M_.param_names = char(M_.param_names, 'gamky');
M_.param_names_tex = char(M_.param_names_tex, 'gamky');
M_.param_names_long = char(M_.param_names_long, 'gamky');
M_.param_names = char(M_.param_names, 'gamwb');
M_.param_names_tex = char(M_.param_names_tex, 'gamwb');
M_.param_names_long = char(M_.param_names_long, 'gamwb');
M_.param_names = char(M_.param_names, 'gamwy');
M_.param_names_tex = char(M_.param_names_tex, 'gamwy');
M_.param_names_long = char(M_.param_names_long, 'gamwy');
M_.param_names = char(M_.param_names, 'gs');
M_.param_names_tex = char(M_.param_names_tex, 'gs');
M_.param_names_long = char(M_.param_names_long, 'gs');
M_.param_names = char(M_.param_names, 'hs');
M_.param_names_tex = char(M_.param_names_tex, 'hs');
M_.param_names_long = char(M_.param_names_long, 'hs');
M_.param_names = char(M_.param_names, 'infls');
M_.param_names_tex = char(M_.param_names_tex, 'infls');
M_.param_names_long = char(M_.param_names_long, 'infls');
M_.param_names = char(M_.param_names, 'invs');
M_.param_names_tex = char(M_.param_names_tex, 'invs');
M_.param_names_long = char(M_.param_names_long, 'invs');
M_.param_names = char(M_.param_names, 'ks');
M_.param_names_tex = char(M_.param_names_tex, 'ks');
M_.param_names_long = char(M_.param_names_long, 'ks');
M_.param_names = char(M_.param_names, 'kbs');
M_.param_names_tex = char(M_.param_names_tex, 'kbs');
M_.param_names_long = char(M_.param_names_long, 'kbs');
M_.param_names = char(M_.param_names, 'lams');
M_.param_names_tex = char(M_.param_names_tex, 'lams');
M_.param_names_long = char(M_.param_names_long, 'lams');
M_.param_names = char(M_.param_names, 'mcs');
M_.param_names_tex = char(M_.param_names_tex, 'mcs');
M_.param_names_long = char(M_.param_names_long, 'mcs');
M_.param_names = char(M_.param_names, 'mius');
M_.param_names_tex = char(M_.param_names_tex, 'mius');
M_.param_names_long = char(M_.param_names_long, 'mius');
M_.param_names = char(M_.param_names, 'miubs');
M_.param_names_tex = char(M_.param_names_tex, 'miubs');
M_.param_names_long = char(M_.param_names_long, 'miubs');
M_.param_names = char(M_.param_names, 'mius_lams');
M_.param_names_tex = char(M_.param_names_tex, 'mius\_lams');
M_.param_names_long = char(M_.param_names_long, 'mius_lams');
M_.param_names = char(M_.param_names, 'miubs_lams');
M_.param_names_tex = char(M_.param_names_tex, 'miubs\_lams');
M_.param_names_long = char(M_.param_names_long, 'miubs_lams');
M_.param_names = char(M_.param_names, 'nomw');
M_.param_names_tex = char(M_.param_names_tex, 'nomw');
M_.param_names_long = char(M_.param_names_long, 'nomw');
M_.param_names = char(M_.param_names, 'ome');
M_.param_names_tex = char(M_.param_names_tex, 'ome');
M_.param_names_long = char(M_.param_names_long, 'ome');
M_.param_names = char(M_.param_names, 'phibd');
M_.param_names_tex = char(M_.param_names_tex, 'phibd');
M_.param_names_long = char(M_.param_names_long, 'phibd');
M_.param_names = char(M_.param_names, 'phil');
M_.param_names_tex = char(M_.param_names_tex, 'phil');
M_.param_names_long = char(M_.param_names_long, 'phil');
M_.param_names = char(M_.param_names, 'phiprof');
M_.param_names_tex = char(M_.param_names_tex, 'phiprof');
M_.param_names_long = char(M_.param_names_long, 'phiprof');
M_.param_names = char(M_.param_names, 'phips');
M_.param_names_tex = char(M_.param_names_tex, 'phips');
M_.param_names_long = char(M_.param_names_long, 'phips');
M_.param_names = char(M_.param_names, 'phiR');
M_.param_names_tex = char(M_.param_names_tex, 'phiR');
M_.param_names_long = char(M_.param_names_long, 'phiR');
M_.param_names = char(M_.param_names, 'phiRot');
M_.param_names_tex = char(M_.param_names_tex, 'phiRot');
M_.param_names_long = char(M_.param_names_long, 'phiRot');
M_.param_names = char(M_.param_names, 'phiRotF');
M_.param_names_tex = char(M_.param_names_tex, 'phiRotF');
M_.param_names_long = char(M_.param_names_long, 'phiRotF');
M_.param_names = char(M_.param_names, 'phiRotw');
M_.param_names_tex = char(M_.param_names_tex, 'phiRotw');
M_.param_names_long = char(M_.param_names_long, 'phiRotw');
M_.param_names = char(M_.param_names, 'phiRotwF');
M_.param_names_tex = char(M_.param_names_tex, 'phiRotwF');
M_.param_names_long = char(M_.param_names_long, 'phiRotwF');
M_.param_names = char(M_.param_names, 'phiu1');
M_.param_names_tex = char(M_.param_names_tex, 'phiu1');
M_.param_names_long = char(M_.param_names_long, 'phiu1');
M_.param_names = char(M_.param_names, 'phiu2');
M_.param_names_tex = char(M_.param_names_tex, 'phiu2');
M_.param_names_long = char(M_.param_names_long, 'phiu2');
M_.param_names = char(M_.param_names, 'phiy');
M_.param_names_tex = char(M_.param_names_tex, 'phiy');
M_.param_names_long = char(M_.param_names_long, 'phiy');
M_.param_names = char(M_.param_names, 'profs');
M_.param_names_tex = char(M_.param_names_tex, 'profs');
M_.param_names_long = char(M_.param_names_long, 'profs');
M_.param_names = char(M_.param_names, 'rhoc');
M_.param_names_tex = char(M_.param_names_tex, 'rhoc');
M_.param_names_long = char(M_.param_names_long, 'rhoc');
M_.param_names = char(M_.param_names, 'rhod');
M_.param_names_tex = char(M_.param_names_tex, 'rhod');
M_.param_names_long = char(M_.param_names_long, 'rhod');
M_.param_names = char(M_.param_names, 'rhog');
M_.param_names_tex = char(M_.param_names_tex, 'rhog');
M_.param_names_long = char(M_.param_names_long, 'rhog');
M_.param_names = char(M_.param_names, 'rhogc');
M_.param_names_tex = char(M_.param_names_tex, 'rhogc');
M_.param_names_long = char(M_.param_names_long, 'rhogc');
M_.param_names = char(M_.param_names, 'rhogg');
M_.param_names_tex = char(M_.param_names_tex, 'rhogg');
M_.param_names_long = char(M_.param_names_long, 'rhogg');
M_.param_names = char(M_.param_names, 'rhogk');
M_.param_names_tex = char(M_.param_names_tex, 'rhogk');
M_.param_names_long = char(M_.param_names_long, 'rhogk');
M_.param_names = char(M_.param_names, 'rhogw');
M_.param_names_tex = char(M_.param_names_tex, 'rhogw');
M_.param_names_long = char(M_.param_names_long, 'rhogw');
M_.param_names = char(M_.param_names, 'rhok');
M_.param_names_tex = char(M_.param_names_tex, 'rhok');
M_.param_names_long = char(M_.param_names_long, 'rhok');
M_.param_names = char(M_.param_names, 'rhow');
M_.param_names_tex = char(M_.param_names_tex, 'rhow');
M_.param_names_long = char(M_.param_names_long, 'rhow');
M_.param_names = char(M_.param_names, 'rhoz');
M_.param_names_tex = char(M_.param_names_tex, 'rhoz');
M_.param_names_long = char(M_.param_names_long, 'rhoz');
M_.param_names = char(M_.param_names, 'rks');
M_.param_names_tex = char(M_.param_names_tex, 'rks');
M_.param_names_long = char(M_.param_names_long, 'rks');
M_.param_names = char(M_.param_names, 'Rs');
M_.param_names_tex = char(M_.param_names_tex, 'Rs');
M_.param_names_long = char(M_.param_names_long, 'Rs');
M_.param_names = char(M_.param_names, 'sigcs');
M_.param_names_tex = char(M_.param_names_tex, 'sigcs');
M_.param_names_long = char(M_.param_names_long, 'sigcs');
M_.param_names = char(M_.param_names, 'sigd');
M_.param_names_tex = char(M_.param_names_tex, 'sigd');
M_.param_names_long = char(M_.param_names_long, 'sigd');
M_.param_names = char(M_.param_names, 'siggs');
M_.param_names_tex = char(M_.param_names_tex, 'siggs');
M_.param_names_long = char(M_.param_names_long, 'siggs');
M_.param_names = char(M_.param_names, 'sigks');
M_.param_names_tex = char(M_.param_names_tex, 'sigks');
M_.param_names_long = char(M_.param_names_long, 'sigks');
M_.param_names = char(M_.param_names, 'sigms');
M_.param_names_tex = char(M_.param_names_tex, 'sigms');
M_.param_names_long = char(M_.param_names_long, 'sigms');
M_.param_names = char(M_.param_names, 'sigws');
M_.param_names_tex = char(M_.param_names_tex, 'sigws');
M_.param_names_long = char(M_.param_names_long, 'sigws');
M_.param_names = char(M_.param_names, 'sigz');
M_.param_names_tex = char(M_.param_names_tex, 'sigz');
M_.param_names_long = char(M_.param_names_long, 'sigz');
M_.param_names = char(M_.param_names, 'taucs');
M_.param_names_tex = char(M_.param_names_tex, 'taucs');
M_.param_names_long = char(M_.param_names_long, 'taucs');
M_.param_names = char(M_.param_names, 'tauks');
M_.param_names_tex = char(M_.param_names_tex, 'tauks');
M_.param_names_long = char(M_.param_names_long, 'tauks');
M_.param_names = char(M_.param_names, 'tauws');
M_.param_names_tex = char(M_.param_names_tex, 'tauws');
M_.param_names_long = char(M_.param_names_long, 'tauws');
M_.param_names = char(M_.param_names, 'taxprofits');
M_.param_names_tex = char(M_.param_names_tex, 'taxprofits');
M_.param_names_long = char(M_.param_names_long, 'taxprofits');
M_.param_names = char(M_.param_names, 'tbd');
M_.param_names_tex = char(M_.param_names_tex, 'tbd');
M_.param_names_long = char(M_.param_names_long, 'tbd');
M_.param_names = char(M_.param_names, 'thetp');
M_.param_names_tex = char(M_.param_names_tex, 'thetp');
M_.param_names_long = char(M_.param_names_long, 'thetp');
M_.param_names = char(M_.param_names, 'thetw');
M_.param_names_tex = char(M_.param_names_tex, 'thetw');
M_.param_names_long = char(M_.param_names_long, 'thetw');
M_.param_names = char(M_.param_names, 'ups');
M_.param_names_tex = char(M_.param_names_tex, 'ups');
M_.param_names_long = char(M_.param_names_long, 'ups');
M_.param_names = char(M_.param_names, 'ws');
M_.param_names_tex = char(M_.param_names_tex, 'ws');
M_.param_names_long = char(M_.param_names_long, 'ws');
M_.param_names = char(M_.param_names, 'ys');
M_.param_names_tex = char(M_.param_names_tex, 'ys');
M_.param_names_long = char(M_.param_names_long, 'ys');
M_.param_names = char(M_.param_names, 'habit');
M_.param_names_tex = char(M_.param_names_tex, 'habit');
M_.param_names_long = char(M_.param_names_long, 'habit');
M_.param_names = char(M_.param_names, 'kappa');
M_.param_names_tex = char(M_.param_names_tex, 'kappa');
M_.param_names_long = char(M_.param_names_long, 'kappa');
M_.param_names = char(M_.param_names, 'rspnd_y');
M_.param_names_tex = char(M_.param_names_tex, 'rspnd\_y');
M_.param_names_long = char(M_.param_names_long, 'rspnd_y');
M_.param_names = char(M_.param_names, 'rspnd_b');
M_.param_names_tex = char(M_.param_names_tex, 'rspnd\_b');
M_.param_names_long = char(M_.param_names_long, 'rspnd_b');
M_.param_names = char(M_.param_names, 'gzs');
M_.param_names_tex = char(M_.param_names_tex, 'gzs');
M_.param_names_long = char(M_.param_names_long, 'gzs');
M_.exo_det_nbr = 0;
M_.exo_nbr = 11;
M_.endo_nbr = 86;
M_.param_nbr = 118;
M_.orig_endo_nbr = 63;
M_.aux_vars(1).endo_index = 64;
M_.aux_vars(1).type = 0;
M_.aux_vars(2).endo_index = 65;
M_.aux_vars(2).type = 0;
M_.aux_vars(3).endo_index = 66;
M_.aux_vars(3).type = 0;
M_.aux_vars(4).endo_index = 67;
M_.aux_vars(4).type = 0;
M_.aux_vars(5).endo_index = 68;
M_.aux_vars(5).type = 0;
M_.aux_vars(6).endo_index = 69;
M_.aux_vars(6).type = 0;
M_.aux_vars(7).endo_index = 70;
M_.aux_vars(7).type = 0;
M_.aux_vars(8).endo_index = 71;
M_.aux_vars(8).type = 0;
M_.aux_vars(9).endo_index = 72;
M_.aux_vars(9).type = 0;
M_.aux_vars(10).endo_index = 73;
M_.aux_vars(10).type = 1;
M_.aux_vars(10).orig_index = 6;
M_.aux_vars(10).orig_lead_lag = -1;
M_.aux_vars(11).endo_index = 74;
M_.aux_vars(11).type = 1;
M_.aux_vars(11).orig_index = 6;
M_.aux_vars(11).orig_lead_lag = -2;
M_.aux_vars(12).endo_index = 75;
M_.aux_vars(12).type = 1;
M_.aux_vars(12).orig_index = 61;
M_.aux_vars(12).orig_lead_lag = -1;
M_.aux_vars(13).endo_index = 76;
M_.aux_vars(13).type = 1;
M_.aux_vars(13).orig_index = 61;
M_.aux_vars(13).orig_lead_lag = -2;
M_.aux_vars(14).endo_index = 77;
M_.aux_vars(14).type = 1;
M_.aux_vars(14).orig_index = 61;
M_.aux_vars(14).orig_lead_lag = -3;
M_.aux_vars(15).endo_index = 78;
M_.aux_vars(15).type = 1;
M_.aux_vars(15).orig_index = 62;
M_.aux_vars(15).orig_lead_lag = -1;
M_.aux_vars(16).endo_index = 79;
M_.aux_vars(16).type = 1;
M_.aux_vars(16).orig_index = 62;
M_.aux_vars(16).orig_lead_lag = -2;
M_.aux_vars(17).endo_index = 80;
M_.aux_vars(17).type = 1;
M_.aux_vars(17).orig_index = 62;
M_.aux_vars(17).orig_lead_lag = -3;
M_.aux_vars(18).endo_index = 81;
M_.aux_vars(18).type = 1;
M_.aux_vars(18).orig_index = 58;
M_.aux_vars(18).orig_lead_lag = -1;
M_.aux_vars(19).endo_index = 82;
M_.aux_vars(19).type = 1;
M_.aux_vars(19).orig_index = 58;
M_.aux_vars(19).orig_lead_lag = -2;
M_.aux_vars(20).endo_index = 83;
M_.aux_vars(20).type = 1;
M_.aux_vars(20).orig_index = 58;
M_.aux_vars(20).orig_lead_lag = -3;
M_.aux_vars(21).endo_index = 84;
M_.aux_vars(21).type = 1;
M_.aux_vars(21).orig_index = 60;
M_.aux_vars(21).orig_lead_lag = -1;
M_.aux_vars(22).endo_index = 85;
M_.aux_vars(22).type = 1;
M_.aux_vars(22).orig_index = 60;
M_.aux_vars(22).orig_lead_lag = -2;
M_.aux_vars(23).endo_index = 86;
M_.aux_vars(23).type = 1;
M_.aux_vars(23).orig_index = 60;
M_.aux_vars(23).orig_lead_lag = -3;
M_.Sigma_e = zeros(11, 11);
M_.Correlation_matrix = eye(11, 11);
M_.H = 0;
M_.Correlation_matrix_ME = 1;
M_.sigma_e_is_diagonal = 1;
options_.block=0;
options_.bytecode=0;
options_.use_dll=0;
erase_compiled_function('US_FGKR15_static');
erase_compiled_function('US_FGKR15_dynamic');
M_.lead_lag_incidence = [
 1 49 0;
 2 50 135;
 3 51 136;
 4 52 0;
 0 53 0;
 5 54 137;
 6 55 138;
 7 56 0;
 8 57 0;
 0 58 139;
 0 59 0;
 0 60 140;
 0 61 141;
 0 62 0;
 9 63 0;
 0 64 142;
 10 65 0;
 11 66 143;
 12 67 0;
 0 68 144;
 13 69 145;
 14 70 146;
 0 71 147;
 0 72 0;
 0 73 0;
 0 74 0;
 0 75 0;
 0 76 0;
 15 77 0;
 16 78 0;
 17 79 0;
 18 80 0;
 19 81 0;
 20 82 148;
 21 83 0;
 0 84 0;
 0 85 149;
 22 86 150;
 23 87 0;
 24 88 0;
 0 89 151;
 0 90 0;
 0 91 152;
 0 92 153;
 0 93 0;
 25 94 0;
 0 95 154;
 26 96 0;
 27 97 155;
 28 98 0;
 0 99 156;
 29 100 157;
 30 101 158;
 0 102 0;
 0 103 0;
 0 104 0;
 0 105 0;
 31 106 0;
 0 107 0;
 32 108 159;
 33 109 160;
 34 110 161;
 0 111 0;
 0 112 162;
 0 113 163;
 0 114 164;
 0 115 165;
 0 116 166;
 0 117 167;
 0 118 168;
 0 119 169;
 0 120 170;
 35 121 0;
 36 122 0;
 37 123 0;
 38 124 0;
 39 125 0;
 40 126 0;
 41 127 0;
 42 128 0;
 43 129 0;
 44 130 0;
 45 131 0;
 46 132 0;
 47 133 0;
 48 134 0;]';
M_.nstatic = 17;
M_.nfwrd   = 21;
M_.npred   = 33;
M_.nboth   = 15;
M_.nsfwrd   = 36;
M_.nspred   = 48;
M_.ndynamic   = 69;
M_.equations_tags = {
};
M_.static_and_dynamic_models_differ = 0;
M_.exo_names_orig_ord = [1:11];
M_.maximum_lag = 1;
M_.maximum_lead = 1;
M_.maximum_endo_lag = 1;
M_.maximum_endo_lead = 1;
oo_.steady_state = zeros(86, 1);
M_.maximum_exo_lag = 0;
M_.maximum_exo_lead = 0;
oo_.exo_steady_state = zeros(11, 1);
M_.params = NaN(118, 1);
M_.NNZDerivatives = zeros(3, 1);
M_.NNZDerivatives(1) = 445;
M_.NNZDerivatives(2) = 989;
M_.NNZDerivatives(3) = -1;
M_.params( 118 ) = 1.005;
gzs = M_.params( 118 );
M_.params( 71 ) = 2;
ome = M_.params( 71 );
M_.params( 37 ) = 0.9945*M_.params(118)^M_.params(71);
bet = M_.params( 37 );
M_.params( 111 ) = 1;
ups = M_.params( 111 );
M_.params( 110 ) = 0.75;
thetw = M_.params( 110 );
M_.params( 80 ) = 0;
phiRotwF = M_.params( 80 );
M_.params( 70 ) = 0;
nomw = M_.params( 70 );
M_.params( 43 ) = 21;
eps = M_.params( 43 );
M_.params( 114 ) = 0.75;
habit = M_.params( 114 );
M_.params( 82 ) = 0.01;
phiu2 = M_.params( 82 );
M_.params( 115 ) = 0.75;
kappa = M_.params( 115 );
M_.params( 35 ) = 0.36;
alph = M_.params( 35 );
M_.params( 42 ) = 0.010;
delt = M_.params( 42 );
M_.params( 45 ) = 0.010;
deltau = M_.params( 45 );
M_.params( 109 ) = 0.74;
thetp = M_.params( 109 );
M_.params( 78 ) = 0;
phiRotF = M_.params( 78 );
M_.params( 44 ) = 21;
epsw = M_.params( 44 );
M_.params( 74 ) = 0.00;
phiprof = M_.params( 74 );
M_.params( 60 ) = 1.0045;
infls = M_.params( 60 );
M_.params( 76 ) = 0.7;
phiR = M_.params( 76 );
M_.params( 75 ) = 1.35;
phips = M_.params( 75 );
M_.params( 83 ) = 0.25;
phiy = M_.params( 83 );
M_.params( 39 ) = (-0.025);
phisigk = M_.params( 39 );
M_.params( 72 ) = 0.0005;
phibd = M_.params( 72 );
M_.params( 58 ) = 0.2;
gs = M_.params( 58 );
M_.params( 87 ) = 0.99;
rhog = M_.params( 87 );
M_.params( 53 ) = (-0.004);
gamgy = M_.params( 53 );
M_.params( 52 ) = (-0.008);
gamgb = M_.params( 52 );
M_.params( 99 ) = (-6.20);
siggs = M_.params( 99 );
M_.params( 89 ) = 0.92;
rhogg = M_.params( 89 );
M_.params( 47 ) = 0.18;
etag = M_.params( 47 );
M_.params( 105 ) = 0.38;
tauks = M_.params( 105 );
M_.params( 92 ) = 0.98;
rhok = M_.params( 92 );
M_.params( 55 ) = 0.040;
gamky = M_.params( 55 );
M_.params( 54 ) = 0.003;
gamkb = M_.params( 54 );
M_.params( 100 ) = (-4.90);
sigks = M_.params( 100 );
M_.params( 90 ) = 0.65;
rhogk = M_.params( 90 );
M_.params( 48 ) = 0.40;
etak = M_.params( 48 );
M_.params( 104 ) = 0.080;
taucs = M_.params( 104 );
M_.params( 85 ) = 0.99;
rhoc = M_.params( 85 );
M_.params( 51 ) = 0.001;
gamcy = M_.params( 51 );
M_.params( 50 ) = 1e-4;
gamcb = M_.params( 50 );
M_.params( 97 ) = (-7.12);
sigcs = M_.params( 97 );
M_.params( 88 ) = 0.73;
rhogc = M_.params( 88 );
M_.params( 46 ) = 0.45;
etac = M_.params( 46 );
M_.params( 106 ) = 0.21;
tauws = M_.params( 106 );
M_.params( 93 ) = 0.99;
rhow = M_.params( 93 );
M_.params( 57 ) = 0.040;
gamwy = M_.params( 57 );
M_.params( 56 ) = 0.003;
gamwb = M_.params( 56 );
M_.params( 102 ) = (-6.0);
sigws = M_.params( 102 );
M_.params( 91 ) = 0.46;
rhogw = M_.params( 91 );
M_.params( 49 ) = 0.82;
etaw = M_.params( 49 );
M_.params( 101 ) = 0.004086771438464067;
sigms = M_.params( 101 );
M_.params( 86 ) = 0.18;
rhod = M_.params( 86 );
M_.params( 98 ) = 0.08;
sigd = M_.params( 98 );
M_.params( 94 ) = 0.95;
rhoz = M_.params( 94 );
M_.params( 103 ) = 0.001;
sigz = M_.params( 103 );
M_.params( 40 ) = 1;
deductdepr = M_.params( 40 );
M_.params( 107 ) = 0;
taxprofits = M_.params( 107 );
M_.params( 41 ) = 0;
nom_depreciation = M_.params( 41 );
M_.params( 116 ) = 1.0;
rspnd_y = M_.params( 116 );
M_.params( 117 ) = 1.0;
rspnd_b = M_.params( 117 );
M_.params( 96 ) = M_.params(118)^M_.params(71)*M_.params(60)/M_.params(37);
Rs = M_.params( 96 );
M_.params( 69 ) = M_.params(37)*M_.params(45)*M_.params(105)*M_.params(40)/(M_.params(118)^M_.params(71)*M_.params(60)^M_.params(41))/(1-M_.params(37)*(1-M_.params(45))/M_.params(60)^M_.params(41)/M_.params(118)^M_.params(71));
miubs_lams = M_.params( 69 );
M_.params( 68 ) = 1-M_.params(69);
mius_lams = M_.params( 68 );
M_.params( 95 ) = M_.params(118)^M_.params(71)*(1-M_.params(37)*(1-M_.params(42))/M_.params(118)^M_.params(71))*M_.params(68)/M_.params(37)/(1-M_.params(105));
rks = M_.params( 95 );
M_.params( 65 ) = (M_.params(43)-1)/M_.params(43);
mcs = M_.params( 65 );
M_.params( 77 ) = M_.params(43)*M_.params(65)/M_.params(60)^2*M_.params(109)/(1-M_.params(109))/(1-M_.params(37)*M_.params(109)*M_.params(118)^(1-M_.params(71)));
phiRot = M_.params( 77 );
koverls = gzs*(rks/alph/mcs)^(1/(alph-1)); 
M_.params( 112 ) = M_.params(65)*(1-M_.params(35))*koverls^M_.params(35)/M_.params(118)^M_.params(35);
ws = M_.params( 112 );
lk      = (1-alph)*rks/alph/ws/gzs ;
M_.params( 59 ) = 0.3333333333333333;
hs = M_.params( 59 );
M_.params( 113 ) = lk^(-M_.params(35))*M_.params(59)/M_.params(118)^M_.params(35)-M_.params(74);
ys = M_.params( 113 );
M_.params( 62 ) = M_.params(59)/lk;
ks = M_.params( 62 );
M_.params( 61 ) = (1-(1-M_.params(42))/M_.params(118))*M_.params(62);
invs = M_.params( 61 );
M_.params( 63 ) = M_.params(60)^M_.params(41)/(M_.params(60)^M_.params(41)-(1-M_.params(45))/M_.params(118))*M_.params(61);
kbs = M_.params( 63 );
M_.params( 38 ) = M_.params(113)-M_.params(113)*M_.params(58)-M_.params(61);
cs = M_.params( 38 );
M_.params( 64 ) = (1/(1-M_.params(114)/M_.params(118))^M_.params(71)-M_.params(37)*M_.params(114)/(M_.params(118)-M_.params(114))^M_.params(71))/M_.params(38)^M_.params(71)/(1+M_.params(104));
lams = M_.params( 64 );
M_.params( 66 ) = M_.params(68)*M_.params(64);
mius = M_.params( 66 );
M_.params( 67 ) = M_.params(69)*M_.params(64);
miubs = M_.params( 67 );
M_.params( 73 ) = M_.params(64)*M_.params(112)*(M_.params(44)-1)*(1-M_.params(106))/M_.params(44)/M_.params(59)^M_.params(111);
phil = M_.params( 73 );
utils   = 1 ;
M_.params( 81 ) = (1-M_.params(105))*M_.params(64)*M_.params(95)/M_.params(66);
phiu1 = M_.params( 81 );
M_.params( 36 ) = M_.params(113)*1.6;
bds = M_.params( 36 );
M_.params( 84 ) = M_.params(113)-M_.params(59)*M_.params(112)-M_.params(62)*M_.params(95)*utils/M_.params(118)-M_.params(74);
profs = M_.params( 84 );
M_.params( 108 ) = M_.params(113)*M_.params(58)-(M_.params(106)*M_.params(59)*M_.params(112)+M_.params(105)*M_.params(62)*(M_.params(95)*utils-M_.params(45)*M_.params(40)/M_.params(60)^M_.params(41))/M_.params(118)+M_.params(105)*M_.params(107)*M_.params(84)+M_.params(38)*M_.params(104)+M_.params(36)*(1-M_.params(96)/M_.params(60)/M_.params(118)));
tbd = M_.params( 108 );
M_.params( 79 ) = M_.params(44)*M_.params(73)*M_.params(59)^(1+M_.params(111))*M_.params(110)*(1+M_.params(44)*M_.params(111))/M_.params(113)/M_.params(64)/(1-M_.params(118)^(1-M_.params(71))*M_.params(37)*M_.params(110))/(1-M_.params(110))/M_.params(60)^M_.params(70)/M_.params(118)^2;
phiRotw = M_.params( 79 );
thispath = cd;                                                           
cd('..');                                                                
load policy_param.mat;                                                   
for i=1:33                                                               
deep_parameter_name = M_.param_names(i,:);                           
eval(['M_.params(i)  = ' deep_parameter_name ' ;'])                  
end                                                                      
cd(thispath);                                                            
M_.params( 34 ) = 1;
coffispol = M_.params( 34 );
%
% INITVAL instructions
%
options_.initval_file = 0;
oo_.steady_state( 2 ) = log(M_.params(38));
oo_.steady_state( 22 ) = log(M_.params(113));
oo_.steady_state( 16 ) = log(M_.params(95));
oo_.steady_state( 4 ) = M_.params(58);
oo_.steady_state( 8 ) = log(M_.params(62));
oo_.steady_state( 9 ) = log(M_.params(63));
oo_.steady_state( 5 ) = log(M_.params(59));
oo_.steady_state( 11 ) = log(M_.params(65));
oo_.steady_state( 21 ) = log(M_.params(112));
oo_.steady_state( 6 ) = log(M_.params(60));
oo_.steady_state( 15 ) = log(M_.params(96));
oo_.steady_state( 18 ) = M_.params(105);
oo_.steady_state( 19 ) = M_.params(106);
oo_.steady_state( 17 ) = M_.params(104);
oo_.steady_state( 10 ) = log(M_.params(64));
oo_.steady_state( 12 ) = log(M_.params(66));
oo_.steady_state( 13 ) = M_.params(67);
oo_.steady_state( 7 ) = log(M_.params(61));
oo_.steady_state( 20 ) = 0;
oo_.steady_state( 31 ) = M_.params(100);
oo_.steady_state( 32 ) = M_.params(102);
oo_.steady_state( 29 ) = M_.params(97);
oo_.steady_state( 30 ) = M_.params(99);
oo_.steady_state( 14 ) = M_.params(84);
oo_.steady_state( 1 ) = M_.params(36);
oo_.steady_state( 23 ) = log(M_.params(118));
oo_.steady_state( 3 ) = 0;
oo_.steady_state( 24 ) = log(M_.params(118));
oo_.steady_state( 25 ) = log(M_.params(118));
oo_.steady_state( 26 ) = log(M_.params(118));
oo_.steady_state( 27 ) = log(M_.params(118));
oo_.steady_state( 34 ) = log(M_.params(38));
oo_.steady_state( 53 ) = log(M_.params(113));
oo_.steady_state( 47 ) = log(M_.params(95));
oo_.steady_state( 35 ) = M_.params(58);
oo_.steady_state( 39 ) = log(M_.params(62));
oo_.steady_state( 40 ) = log(M_.params(63));
oo_.steady_state( 36 ) = log(M_.params(59));
oo_.steady_state( 42 ) = log(M_.params(65));
oo_.steady_state( 52 ) = log(M_.params(112));
oo_.steady_state( 37 ) = log(M_.params(60));
oo_.steady_state( 46 ) = log(M_.params(96));
oo_.steady_state( 49 ) = M_.params(105);
oo_.steady_state( 50 ) = M_.params(106);
oo_.steady_state( 48 ) = M_.params(104);
oo_.steady_state( 41 ) = log(M_.params(64));
oo_.steady_state( 43 ) = log(M_.params(66));
oo_.steady_state( 44 ) = M_.params(67);
oo_.steady_state( 38 ) = log(M_.params(61));
oo_.steady_state( 51 ) = 0;
oo_.steady_state( 45 ) = M_.params(84);
oo_.steady_state( 33 ) = M_.params(36);
oo_.steady_state( 54 ) = log(M_.params(118));
oo_.steady_state( 55 ) = log(M_.params(118));
oo_.steady_state( 56 ) = log(M_.params(118));
oo_.steady_state( 57 ) = log(M_.params(118));
oo_.steady_state( 58 ) = 0;
oo_.steady_state( 61 ) = 0;
oo_.steady_state( 60 ) = 0;
oo_.steady_state( 59 ) = 0;
oo_.steady_state(64)=oo_.steady_state(60);
oo_.steady_state(65)=oo_.steady_state(64);
oo_.steady_state(66)=oo_.steady_state(65);
oo_.steady_state(67)=oo_.steady_state(62);
oo_.steady_state(68)=oo_.steady_state(67);
oo_.steady_state(69)=oo_.steady_state(68);
oo_.steady_state(70)=oo_.steady_state(61);
oo_.steady_state(71)=oo_.steady_state(70);
oo_.steady_state(72)=oo_.steady_state(71);
oo_.steady_state(73)=oo_.steady_state(6);
oo_.steady_state(74)=oo_.steady_state(73);
oo_.steady_state(75)=oo_.steady_state(61);
oo_.steady_state(76)=oo_.steady_state(75);
oo_.steady_state(77)=oo_.steady_state(76);
oo_.steady_state(78)=oo_.steady_state(62);
oo_.steady_state(79)=oo_.steady_state(78);
oo_.steady_state(80)=oo_.steady_state(79);
oo_.steady_state(81)=oo_.steady_state(58);
oo_.steady_state(82)=oo_.steady_state(81);
oo_.steady_state(83)=oo_.steady_state(82);
oo_.steady_state(84)=oo_.steady_state(60);
oo_.steady_state(85)=oo_.steady_state(84);
oo_.steady_state(86)=oo_.steady_state(85);
if M_.exo_nbr > 0;
	oo_.exo_simul = [ones(M_.maximum_lag,1)*oo_.exo_steady_state'];
end;
if M_.exo_det_nbr > 0;
	oo_.exo_det_simul = [ones(M_.maximum_lag,1)*oo_.exo_det_steady_state'];
end;
%
% SHOCKS instructions
%
make_ex_;
M_.exo_det_length = 0;
M_.Sigma_e(1, 1) = 1;
M_.Sigma_e(2, 2) = M_.params(98)^2;
M_.Sigma_e(3, 3) = 1;
M_.Sigma_e(4, 4) = 1;
M_.Sigma_e(5, 5) = M_.params(103)^2;
M_.Sigma_e(6, 6) = 1;
M_.Sigma_e(7, 7) = 1;
M_.Sigma_e(8, 8) = 1;
M_.Sigma_e(9, 9) = 1;
M_.Sigma_e(10, 10) = 1;
M_.Sigma_e(11, 11) = 1;
save('US_FGKR15_results.mat', 'oo_', 'M_', 'options_');
if exist('estim_params_', 'var') == 1
  save('US_FGKR15_results.mat', 'estim_params_', '-append');
end
if exist('bayestopt_', 'var') == 1
  save('US_FGKR15_results.mat', 'bayestopt_', '-append');
end
if exist('dataset_', 'var') == 1
  save('US_FGKR15_results.mat', 'dataset_', '-append');
end
if exist('estimation_info', 'var') == 1
  save('US_FGKR15_results.mat', 'estimation_info', '-append');
end


disp(['Total computing time : ' dynsec2hms(toc) ]);
if ~isempty(lastwarn)
  disp('Note: warning(s) encountered in MATLAB/Octave code')
end
diary off
