%
% Status : main Dynare file
%
% Warning : this file is generated automatically by Dynare
%           from model file (.mod)

tic0 = tic;
% Save empty dates and dseries objects in memory.
dates('initialize');
dseries('initialize');
% Define global variables.
global M_ options_ oo_ estim_params_ bayestopt_ dataset_ dataset_info estimation_info ys0_ ex0_
options_ = [];
M_.fname = 'NK_GK13';
M_.dynare_version = '4.5.4';
oo_.dynare_version = '4.5.4';
options_.dynare_version = '4.5.4';
%
% Some global variables initialization
%
global_initialization;
diary off;
diary('NK_GK13.log');
M_.parameter_used_with_lead_lag = true;
M_.exo_names = 'e_a';
M_.exo_names_tex = 'e\_a';
M_.exo_names_long = 'e_a';
M_.exo_names = char(M_.exo_names, 'e_ksi');
M_.exo_names_tex = char(M_.exo_names_tex, 'e\_ksi');
M_.exo_names_long = char(M_.exo_names_long, 'e_ksi');
M_.exo_names = char(M_.exo_names, 'e_Ne');
M_.exo_names_tex = char(M_.exo_names_tex, 'e\_Ne');
M_.exo_names_long = char(M_.exo_names_long, 'e_Ne');
M_.exo_names = char(M_.exo_names, 'e_psi');
M_.exo_names_tex = char(M_.exo_names_tex, 'e\_psi');
M_.exo_names_long = char(M_.exo_names_long, 'e_psi');
M_.exo_names = char(M_.exo_names, 'e_Gamma');
M_.exo_names_tex = char(M_.exo_names_tex, 'e\_Gamma');
M_.exo_names_long = char(M_.exo_names_long, 'e_Gamma');
M_.exo_names = char(M_.exo_names, 'interest_');
M_.exo_names_tex = char(M_.exo_names_tex, 'interest\_');
M_.exo_names_long = char(M_.exo_names_long, 'interest_');
M_.exo_names = char(M_.exo_names, 'fiscal_');
M_.exo_names_tex = char(M_.exo_names_tex, 'fiscal\_');
M_.exo_names_long = char(M_.exo_names_long, 'fiscal_');
M_.endo_names = 'Ym';
M_.endo_names_tex = 'Ym';
M_.endo_names_long = 'Ym';
M_.endo_names = char(M_.endo_names, 'Y');
M_.endo_names_tex = char(M_.endo_names_tex, 'Y');
M_.endo_names_long = char(M_.endo_names_long, 'Y');
M_.endo_names = char(M_.endo_names, 'D');
M_.endo_names_tex = char(M_.endo_names_tex, 'D');
M_.endo_names_long = char(M_.endo_names_long, 'D');
M_.endo_names = char(M_.endo_names, 'K');
M_.endo_names_tex = char(M_.endo_names_tex, 'K');
M_.endo_names_long = char(M_.endo_names_long, 'K');
M_.endo_names = char(M_.endo_names, 'Keff');
M_.endo_names_tex = char(M_.endo_names_tex, 'Keff');
M_.endo_names_long = char(M_.endo_names_long, 'Keff');
M_.endo_names = char(M_.endo_names, 'L');
M_.endo_names_tex = char(M_.endo_names_tex, 'L');
M_.endo_names_long = char(M_.endo_names_long, 'L');
M_.endo_names = char(M_.endo_names, 'I');
M_.endo_names_tex = char(M_.endo_names_tex, 'I');
M_.endo_names_long = char(M_.endo_names_long, 'I');
M_.endo_names = char(M_.endo_names, 'C');
M_.endo_names_tex = char(M_.endo_names_tex, 'C');
M_.endo_names_long = char(M_.endo_names_long, 'C');
M_.endo_names = char(M_.endo_names, 'G');
M_.endo_names_tex = char(M_.endo_names_tex, 'G');
M_.endo_names_long = char(M_.endo_names_long, 'G');
M_.endo_names = char(M_.endo_names, 'Q');
M_.endo_names_tex = char(M_.endo_names_tex, 'Q');
M_.endo_names_long = char(M_.endo_names_long, 'Q');
M_.endo_names = char(M_.endo_names, 'varrho');
M_.endo_names_tex = char(M_.endo_names_tex, 'varrho');
M_.endo_names_long = char(M_.endo_names_long, 'varrho');
M_.endo_names = char(M_.endo_names, 'Lambda');
M_.endo_names_tex = char(M_.endo_names_tex, 'Lambda');
M_.endo_names_long = char(M_.endo_names_long, 'Lambda');
M_.endo_names = char(M_.endo_names, 'Z');
M_.endo_names_tex = char(M_.endo_names_tex, 'Z');
M_.endo_names_long = char(M_.endo_names_long, 'Z');
M_.endo_names = char(M_.endo_names, 'Ne');
M_.endo_names_tex = char(M_.endo_names_tex, 'Ne');
M_.endo_names_long = char(M_.endo_names_long, 'Ne');
M_.endo_names = char(M_.endo_names, 'Nn');
M_.endo_names_tex = char(M_.endo_names_tex, 'Nn');
M_.endo_names_long = char(M_.endo_names_long, 'Nn');
M_.endo_names = char(M_.endo_names, 'Rk');
M_.endo_names_tex = char(M_.endo_names_tex, 'Rk');
M_.endo_names_long = char(M_.endo_names_long, 'Rk');
M_.endo_names = char(M_.endo_names, 'Rb');
M_.endo_names_tex = char(M_.endo_names_tex, 'Rb');
M_.endo_names_long = char(M_.endo_names_long, 'Rb');
M_.endo_names = char(M_.endo_names, 'R');
M_.endo_names_tex = char(M_.endo_names_tex, 'R');
M_.endo_names_long = char(M_.endo_names_long, 'R');
M_.endo_names = char(M_.endo_names, 'qn');
M_.endo_names_tex = char(M_.endo_names_tex, 'qn');
M_.endo_names_long = char(M_.endo_names_long, 'qn');
M_.endo_names = char(M_.endo_names, 'mu_s');
M_.endo_names_tex = char(M_.endo_names_tex, 'mu\_s');
M_.endo_names_long = char(M_.endo_names_long, 'mu_s');
M_.endo_names = char(M_.endo_names, 'mu_b');
M_.endo_names_tex = char(M_.endo_names_tex, 'mu\_b');
M_.endo_names_long = char(M_.endo_names_long, 'mu_b');
M_.endo_names = char(M_.endo_names, 'nu');
M_.endo_names_tex = char(M_.endo_names_tex, 'nu');
M_.endo_names_long = char(M_.endo_names_long, 'nu');
M_.endo_names = char(M_.endo_names, 'phi');
M_.endo_names_tex = char(M_.endo_names_tex, 'phi');
M_.endo_names_long = char(M_.endo_names_long, 'phi');
M_.endo_names = char(M_.endo_names, 'x');
M_.endo_names_tex = char(M_.endo_names_tex, 'x');
M_.endo_names_long = char(M_.endo_names_long, 'x');
M_.endo_names = char(M_.endo_names, 'Omega');
M_.endo_names_tex = char(M_.endo_names_tex, 'Omega');
M_.endo_names_long = char(M_.endo_names_long, 'Omega');
M_.endo_names = char(M_.endo_names, 'Pm');
M_.endo_names_tex = char(M_.endo_names_tex, 'Pm');
M_.endo_names_long = char(M_.endo_names_long, 'Pm');
M_.endo_names = char(M_.endo_names, 'X');
M_.endo_names_tex = char(M_.endo_names_tex, 'X');
M_.endo_names_long = char(M_.endo_names_long, 'X');
M_.endo_names = char(M_.endo_names, 'F');
M_.endo_names_tex = char(M_.endo_names_tex, 'F');
M_.endo_names_long = char(M_.endo_names_long, 'F');
M_.endo_names = char(M_.endo_names, 'H');
M_.endo_names_tex = char(M_.endo_names_tex, 'H');
M_.endo_names_long = char(M_.endo_names_long, 'H');
M_.endo_names = char(M_.endo_names, 'ir');
M_.endo_names_tex = char(M_.endo_names_tex, 'ir');
M_.endo_names_long = char(M_.endo_names_long, 'ir');
M_.endo_names = char(M_.endo_names, 'ib');
M_.endo_names_tex = char(M_.endo_names_tex, 'ib');
M_.endo_names_long = char(M_.endo_names_long, 'ib');
M_.endo_names = char(M_.endo_names, 'prem_K');
M_.endo_names_tex = char(M_.endo_names_tex, 'prem\_K');
M_.endo_names_long = char(M_.endo_names_long, 'prem_K');
M_.endo_names = char(M_.endo_names, 'prem_B');
M_.endo_names_tex = char(M_.endo_names_tex, 'prem\_B');
M_.endo_names_long = char(M_.endo_names_long, 'prem_B');
M_.endo_names = char(M_.endo_names, 'w');
M_.endo_names_tex = char(M_.endo_names_tex, 'w');
M_.endo_names_long = char(M_.endo_names_long, 'w');
M_.endo_names = char(M_.endo_names, 'qn_rf');
M_.endo_names_tex = char(M_.endo_names_tex, 'qn\_rf');
M_.endo_names_long = char(M_.endo_names_long, 'qn_rf');
M_.endo_names = char(M_.endo_names, 'iir');
M_.endo_names_tex = char(M_.endo_names_tex, 'iir');
M_.endo_names_long = char(M_.endo_names_long, 'iir');
M_.endo_names = char(M_.endo_names, 'prem_ib');
M_.endo_names_tex = char(M_.endo_names_tex, 'prem\_ib');
M_.endo_names_long = char(M_.endo_names_long, 'prem_ib');
M_.endo_names = char(M_.endo_names, 'rb');
M_.endo_names_tex = char(M_.endo_names_tex, 'rb');
M_.endo_names_long = char(M_.endo_names_long, 'rb');
M_.endo_names = char(M_.endo_names, 'q');
M_.endo_names_tex = char(M_.endo_names_tex, 'q');
M_.endo_names_long = char(M_.endo_names_long, 'q');
M_.endo_names = char(M_.endo_names, 'qB');
M_.endo_names_tex = char(M_.endo_names_tex, 'qB');
M_.endo_names_long = char(M_.endo_names_long, 'qB');
M_.endo_names = char(M_.endo_names, 'N');
M_.endo_names_tex = char(M_.endo_names_tex, 'N');
M_.endo_names_long = char(M_.endo_names_long, 'N');
M_.endo_names = char(M_.endo_names, 'Kb');
M_.endo_names_tex = char(M_.endo_names_tex, 'Kb');
M_.endo_names_long = char(M_.endo_names_long, 'Kb');
M_.endo_names = char(M_.endo_names, 'Bb');
M_.endo_names_tex = char(M_.endo_names_tex, 'Bb');
M_.endo_names_long = char(M_.endo_names_long, 'Bb');
M_.endo_names = char(M_.endo_names, 'Dep');
M_.endo_names_tex = char(M_.endo_names_tex, 'Dep');
M_.endo_names_long = char(M_.endo_names_long, 'Dep');
M_.endo_names = char(M_.endo_names, 'Nbook');
M_.endo_names_tex = char(M_.endo_names_tex, 'Nbook');
M_.endo_names_long = char(M_.endo_names_long, 'Nbook');
M_.endo_names = char(M_.endo_names, 'phibook');
M_.endo_names_tex = char(M_.endo_names_tex, 'phibook');
M_.endo_names_long = char(M_.endo_names_long, 'phibook');
M_.endo_names = char(M_.endo_names, 'Kbook');
M_.endo_names_tex = char(M_.endo_names_tex, 'Kbook');
M_.endo_names_long = char(M_.endo_names_long, 'Kbook');
M_.endo_names = char(M_.endo_names, 'Qfair');
M_.endo_names_tex = char(M_.endo_names_tex, 'Qfair');
M_.endo_names_long = char(M_.endo_names_long, 'Qfair');
M_.endo_names = char(M_.endo_names, 'Qbook');
M_.endo_names_tex = char(M_.endo_names_tex, 'Qbook');
M_.endo_names_long = char(M_.endo_names_long, 'Qbook');
M_.endo_names = char(M_.endo_names, 'qnbook');
M_.endo_names_tex = char(M_.endo_names_tex, 'qnbook');
M_.endo_names_long = char(M_.endo_names_long, 'qnbook');
M_.endo_names = char(M_.endo_names, 'Kh');
M_.endo_names_tex = char(M_.endo_names_tex, 'Kh');
M_.endo_names_long = char(M_.endo_names_long, 'Kh');
M_.endo_names = char(M_.endo_names, 'Bh');
M_.endo_names_tex = char(M_.endo_names_tex, 'Bh');
M_.endo_names_long = char(M_.endo_names_long, 'Bh');
M_.endo_names = char(M_.endo_names, 'Welf');
M_.endo_names_tex = char(M_.endo_names_tex, 'Welf');
M_.endo_names_long = char(M_.endo_names_long, 'Welf');
M_.endo_names = char(M_.endo_names, 'a');
M_.endo_names_tex = char(M_.endo_names_tex, 'a');
M_.endo_names_long = char(M_.endo_names_long, 'a');
M_.endo_names = char(M_.endo_names, 'ksi');
M_.endo_names_tex = char(M_.endo_names_tex, 'ksi');
M_.endo_names_long = char(M_.endo_names_long, 'ksi');
M_.endo_names = char(M_.endo_names, 'g');
M_.endo_names_tex = char(M_.endo_names_tex, 'g');
M_.endo_names_long = char(M_.endo_names_long, 'g');
M_.endo_names = char(M_.endo_names, 'infl');
M_.endo_names_tex = char(M_.endo_names_tex, 'infl');
M_.endo_names_long = char(M_.endo_names_long, 'infl');
M_.endo_names = char(M_.endo_names, 'inflstar');
M_.endo_names_tex = char(M_.endo_names_tex, 'inflstar');
M_.endo_names_long = char(M_.endo_names_long, 'inflstar');
M_.endo_names = char(M_.endo_names, 'psi');
M_.endo_names_tex = char(M_.endo_names_tex, 'psi');
M_.endo_names_long = char(M_.endo_names_long, 'psi');
M_.endo_names = char(M_.endo_names, 'Gamma');
M_.endo_names_tex = char(M_.endo_names_tex, 'Gamma');
M_.endo_names_long = char(M_.endo_names_long, 'Gamma');
M_.endo_names = char(M_.endo_names, 'shock_psi');
M_.endo_names_tex = char(M_.endo_names_tex, 'shock\_psi');
M_.endo_names_long = char(M_.endo_names_long, 'shock_psi');
M_.endo_names = char(M_.endo_names, 'shock_Gamma');
M_.endo_names_tex = char(M_.endo_names_tex, 'shock\_Gamma');
M_.endo_names_long = char(M_.endo_names_long, 'shock_Gamma');
M_.endo_names = char(M_.endo_names, 'QKg_Y');
M_.endo_names_tex = char(M_.endo_names_tex, 'QKg\_Y');
M_.endo_names_long = char(M_.endo_names_long, 'QKg_Y');
M_.endo_names = char(M_.endo_names, 'qBg_Y');
M_.endo_names_tex = char(M_.endo_names_tex, 'qBg\_Y');
M_.endo_names_long = char(M_.endo_names_long, 'qBg_Y');
M_.endo_names = char(M_.endo_names, 'QKg_A');
M_.endo_names_tex = char(M_.endo_names_tex, 'QKg\_A');
M_.endo_names_long = char(M_.endo_names_long, 'QKg_A');
M_.endo_names = char(M_.endo_names, 'e_g');
M_.endo_names_tex = char(M_.endo_names_tex, 'e\_g');
M_.endo_names_long = char(M_.endo_names_long, 'e_g');
M_.endo_names = char(M_.endo_names, 'qBg_A');
M_.endo_names_tex = char(M_.endo_names_tex, 'qBg\_A');
M_.endo_names_long = char(M_.endo_names_long, 'qBg_A');
M_.endo_names = char(M_.endo_names, 'Ymf');
M_.endo_names_tex = char(M_.endo_names_tex, 'Ymf');
M_.endo_names_long = char(M_.endo_names_long, 'Ymf');
M_.endo_names = char(M_.endo_names, 'Yf');
M_.endo_names_tex = char(M_.endo_names_tex, 'Yf');
M_.endo_names_long = char(M_.endo_names_long, 'Yf');
M_.endo_names = char(M_.endo_names, 'Kf');
M_.endo_names_tex = char(M_.endo_names_tex, 'Kf');
M_.endo_names_long = char(M_.endo_names_long, 'Kf');
M_.endo_names = char(M_.endo_names, 'Kefff');
M_.endo_names_tex = char(M_.endo_names_tex, 'Kefff');
M_.endo_names_long = char(M_.endo_names_long, 'Kefff');
M_.endo_names = char(M_.endo_names, 'Lf');
M_.endo_names_tex = char(M_.endo_names_tex, 'Lf');
M_.endo_names_long = char(M_.endo_names_long, 'Lf');
M_.endo_names = char(M_.endo_names, 'If');
M_.endo_names_tex = char(M_.endo_names_tex, 'If');
M_.endo_names_long = char(M_.endo_names_long, 'If');
M_.endo_names = char(M_.endo_names, 'Cf');
M_.endo_names_tex = char(M_.endo_names_tex, 'Cf');
M_.endo_names_long = char(M_.endo_names_long, 'Cf');
M_.endo_names = char(M_.endo_names, 'Gf');
M_.endo_names_tex = char(M_.endo_names_tex, 'Gf');
M_.endo_names_long = char(M_.endo_names_long, 'Gf');
M_.endo_names = char(M_.endo_names, 'Qf');
M_.endo_names_tex = char(M_.endo_names_tex, 'Qf');
M_.endo_names_long = char(M_.endo_names_long, 'Qf');
M_.endo_names = char(M_.endo_names, 'varrhof');
M_.endo_names_tex = char(M_.endo_names_tex, 'varrhof');
M_.endo_names_long = char(M_.endo_names_long, 'varrhof');
M_.endo_names = char(M_.endo_names, 'Lambdaf');
M_.endo_names_tex = char(M_.endo_names_tex, 'Lambdaf');
M_.endo_names_long = char(M_.endo_names_long, 'Lambdaf');
M_.endo_names = char(M_.endo_names, 'Zf');
M_.endo_names_tex = char(M_.endo_names_tex, 'Zf');
M_.endo_names_long = char(M_.endo_names_long, 'Zf');
M_.endo_names = char(M_.endo_names, 'Nef');
M_.endo_names_tex = char(M_.endo_names_tex, 'Nef');
M_.endo_names_long = char(M_.endo_names_long, 'Nef');
M_.endo_names = char(M_.endo_names, 'Nnf');
M_.endo_names_tex = char(M_.endo_names_tex, 'Nnf');
M_.endo_names_long = char(M_.endo_names_long, 'Nnf');
M_.endo_names = char(M_.endo_names, 'Rkf');
M_.endo_names_tex = char(M_.endo_names_tex, 'Rkf');
M_.endo_names_long = char(M_.endo_names_long, 'Rkf');
M_.endo_names = char(M_.endo_names, 'Rbf');
M_.endo_names_tex = char(M_.endo_names_tex, 'Rbf');
M_.endo_names_long = char(M_.endo_names_long, 'Rbf');
M_.endo_names = char(M_.endo_names, 'Rf');
M_.endo_names_tex = char(M_.endo_names_tex, 'Rf');
M_.endo_names_long = char(M_.endo_names_long, 'Rf');
M_.endo_names = char(M_.endo_names, 'qnf');
M_.endo_names_tex = char(M_.endo_names_tex, 'qnf');
M_.endo_names_long = char(M_.endo_names_long, 'qnf');
M_.endo_names = char(M_.endo_names, 'mu_sf');
M_.endo_names_tex = char(M_.endo_names_tex, 'mu\_sf');
M_.endo_names_long = char(M_.endo_names_long, 'mu_sf');
M_.endo_names = char(M_.endo_names, 'mu_bf');
M_.endo_names_tex = char(M_.endo_names_tex, 'mu\_bf');
M_.endo_names_long = char(M_.endo_names_long, 'mu_bf');
M_.endo_names = char(M_.endo_names, 'nuf');
M_.endo_names_tex = char(M_.endo_names_tex, 'nuf');
M_.endo_names_long = char(M_.endo_names_long, 'nuf');
M_.endo_names = char(M_.endo_names, 'phif');
M_.endo_names_tex = char(M_.endo_names_tex, 'phif');
M_.endo_names_long = char(M_.endo_names_long, 'phif');
M_.endo_names = char(M_.endo_names, 'xf');
M_.endo_names_tex = char(M_.endo_names_tex, 'xf');
M_.endo_names_long = char(M_.endo_names_long, 'xf');
M_.endo_names = char(M_.endo_names, 'Omegaf');
M_.endo_names_tex = char(M_.endo_names_tex, 'Omegaf');
M_.endo_names_long = char(M_.endo_names_long, 'Omegaf');
M_.endo_names = char(M_.endo_names, 'ibf');
M_.endo_names_tex = char(M_.endo_names_tex, 'ibf');
M_.endo_names_long = char(M_.endo_names_long, 'ibf');
M_.endo_names = char(M_.endo_names, 'prem_Kf');
M_.endo_names_tex = char(M_.endo_names_tex, 'prem\_Kf');
M_.endo_names_long = char(M_.endo_names_long, 'prem_Kf');
M_.endo_names = char(M_.endo_names, 'prem_Bf');
M_.endo_names_tex = char(M_.endo_names_tex, 'prem\_Bf');
M_.endo_names_long = char(M_.endo_names_long, 'prem_Bf');
M_.endo_names = char(M_.endo_names, 'wf');
M_.endo_names_tex = char(M_.endo_names_tex, 'wf');
M_.endo_names_long = char(M_.endo_names_long, 'wf');
M_.endo_names = char(M_.endo_names, 'qn_rff');
M_.endo_names_tex = char(M_.endo_names_tex, 'qn\_rff');
M_.endo_names_long = char(M_.endo_names_long, 'qn_rff');
M_.endo_names = char(M_.endo_names, 'iirf');
M_.endo_names_tex = char(M_.endo_names_tex, 'iirf');
M_.endo_names_long = char(M_.endo_names_long, 'iirf');
M_.endo_names = char(M_.endo_names, 'prem_ibf');
M_.endo_names_tex = char(M_.endo_names_tex, 'prem\_ibf');
M_.endo_names_long = char(M_.endo_names_long, 'prem_ibf');
M_.endo_names = char(M_.endo_names, 'rbf');
M_.endo_names_tex = char(M_.endo_names_tex, 'rbf');
M_.endo_names_long = char(M_.endo_names_long, 'rbf');
M_.endo_names = char(M_.endo_names, 'qf');
M_.endo_names_tex = char(M_.endo_names_tex, 'qf');
M_.endo_names_long = char(M_.endo_names_long, 'qf');
M_.endo_names = char(M_.endo_names, 'qBf');
M_.endo_names_tex = char(M_.endo_names_tex, 'qBf');
M_.endo_names_long = char(M_.endo_names_long, 'qBf');
M_.endo_names = char(M_.endo_names, 'Nf');
M_.endo_names_tex = char(M_.endo_names_tex, 'Nf');
M_.endo_names_long = char(M_.endo_names_long, 'Nf');
M_.endo_names = char(M_.endo_names, 'Kbf');
M_.endo_names_tex = char(M_.endo_names_tex, 'Kbf');
M_.endo_names_long = char(M_.endo_names_long, 'Kbf');
M_.endo_names = char(M_.endo_names, 'Bbf');
M_.endo_names_tex = char(M_.endo_names_tex, 'Bbf');
M_.endo_names_long = char(M_.endo_names_long, 'Bbf');
M_.endo_names = char(M_.endo_names, 'Depf');
M_.endo_names_tex = char(M_.endo_names_tex, 'Depf');
M_.endo_names_long = char(M_.endo_names_long, 'Depf');
M_.endo_names = char(M_.endo_names, 'Nbookf');
M_.endo_names_tex = char(M_.endo_names_tex, 'Nbookf');
M_.endo_names_long = char(M_.endo_names_long, 'Nbookf');
M_.endo_names = char(M_.endo_names, 'phibookf');
M_.endo_names_tex = char(M_.endo_names_tex, 'phibookf');
M_.endo_names_long = char(M_.endo_names_long, 'phibookf');
M_.endo_names = char(M_.endo_names, 'Kbookf');
M_.endo_names_tex = char(M_.endo_names_tex, 'Kbookf');
M_.endo_names_long = char(M_.endo_names_long, 'Kbookf');
M_.endo_names = char(M_.endo_names, 'Qfairf');
M_.endo_names_tex = char(M_.endo_names_tex, 'Qfairf');
M_.endo_names_long = char(M_.endo_names_long, 'Qfairf');
M_.endo_names = char(M_.endo_names, 'Qbookf');
M_.endo_names_tex = char(M_.endo_names_tex, 'Qbookf');
M_.endo_names_long = char(M_.endo_names_long, 'Qbookf');
M_.endo_names = char(M_.endo_names, 'qnbookf');
M_.endo_names_tex = char(M_.endo_names_tex, 'qnbookf');
M_.endo_names_long = char(M_.endo_names_long, 'qnbookf');
M_.endo_names = char(M_.endo_names, 'Khf');
M_.endo_names_tex = char(M_.endo_names_tex, 'Khf');
M_.endo_names_long = char(M_.endo_names_long, 'Khf');
M_.endo_names = char(M_.endo_names, 'Bhf');
M_.endo_names_tex = char(M_.endo_names_tex, 'Bhf');
M_.endo_names_long = char(M_.endo_names_long, 'Bhf');
M_.endo_names = char(M_.endo_names, 'Welff');
M_.endo_names_tex = char(M_.endo_names_tex, 'Welff');
M_.endo_names_long = char(M_.endo_names_long, 'Welff');
M_.endo_names = char(M_.endo_names, 'af');
M_.endo_names_tex = char(M_.endo_names_tex, 'af');
M_.endo_names_long = char(M_.endo_names_long, 'af');
M_.endo_names = char(M_.endo_names, 'ksif');
M_.endo_names_tex = char(M_.endo_names_tex, 'ksif');
M_.endo_names_long = char(M_.endo_names_long, 'ksif');
M_.endo_names = char(M_.endo_names, 'gf');
M_.endo_names_tex = char(M_.endo_names_tex, 'gf');
M_.endo_names_long = char(M_.endo_names_long, 'gf');
M_.endo_names = char(M_.endo_names, 'psif');
M_.endo_names_tex = char(M_.endo_names_tex, 'psif');
M_.endo_names_long = char(M_.endo_names_long, 'psif');
M_.endo_names = char(M_.endo_names, 'Gammaf');
M_.endo_names_tex = char(M_.endo_names_tex, 'Gammaf');
M_.endo_names_long = char(M_.endo_names_long, 'Gammaf');
M_.endo_names = char(M_.endo_names, 'shock_psif');
M_.endo_names_tex = char(M_.endo_names_tex, 'shock\_psif');
M_.endo_names_long = char(M_.endo_names_long, 'shock_psif');
M_.endo_names = char(M_.endo_names, 'shock_Gammaf');
M_.endo_names_tex = char(M_.endo_names_tex, 'shock\_Gammaf');
M_.endo_names_long = char(M_.endo_names_long, 'shock_Gammaf');
M_.endo_names = char(M_.endo_names, 'QKg_Yf');
M_.endo_names_tex = char(M_.endo_names_tex, 'QKg\_Yf');
M_.endo_names_long = char(M_.endo_names_long, 'QKg_Yf');
M_.endo_names = char(M_.endo_names, 'qBg_Yf');
M_.endo_names_tex = char(M_.endo_names_tex, 'qBg\_Yf');
M_.endo_names_long = char(M_.endo_names_long, 'qBg_Yf');
M_.endo_names = char(M_.endo_names, 'QKg_Af');
M_.endo_names_tex = char(M_.endo_names_tex, 'QKg\_Af');
M_.endo_names_long = char(M_.endo_names_long, 'QKg_Af');
M_.endo_names = char(M_.endo_names, 'qBg_Af');
M_.endo_names_tex = char(M_.endo_names_tex, 'qBg\_Af');
M_.endo_names_long = char(M_.endo_names_long, 'qBg_Af');
M_.endo_names = char(M_.endo_names, 'interest');
M_.endo_names_tex = char(M_.endo_names_tex, 'interest');
M_.endo_names_long = char(M_.endo_names_long, 'interest');
M_.endo_names = char(M_.endo_names, 'inflation');
M_.endo_names_tex = char(M_.endo_names_tex, 'inflation');
M_.endo_names_long = char(M_.endo_names_long, 'inflation');
M_.endo_names = char(M_.endo_names, 'inflationq');
M_.endo_names_tex = char(M_.endo_names_tex, 'inflationq');
M_.endo_names_long = char(M_.endo_names_long, 'inflationq');
M_.endo_names = char(M_.endo_names, 'outputgap');
M_.endo_names_tex = char(M_.endo_names_tex, 'outputgap');
M_.endo_names_long = char(M_.endo_names_long, 'outputgap');
M_.endo_names = char(M_.endo_names, 'output');
M_.endo_names_tex = char(M_.endo_names_tex, 'output');
M_.endo_names_long = char(M_.endo_names_long, 'output');
M_.endo_names = char(M_.endo_names, 'fispol');
M_.endo_names_tex = char(M_.endo_names_tex, 'fispol');
M_.endo_names_long = char(M_.endo_names_long, 'fispol');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_78');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_78');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_78');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_82');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_82');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_82');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_86');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_86');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_86');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_113');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_113');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_113');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_117');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_117');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_117');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_121');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_121');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_121');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_148');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_148');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_148');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_152');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_152');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_152');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_156');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_156');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_156');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_56_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_56\_1');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_56_1');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_56_2');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_56\_2');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_56_2');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_129_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_129\_1');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_129_1');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_129_2');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_129\_2');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_129_2');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_129_3');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_129\_3');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_129_3');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_128_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_128\_1');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_128_1');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_128_2');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_128\_2');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_128_2');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_128_3');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_128\_3');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_128_3');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_125_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_125\_1');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_125_1');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_125_2');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_125\_2');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_125_2');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_125_3');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_125\_3');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_125_3');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_127_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_127\_1');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_127_1');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_127_2');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_127\_2');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_127_2');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_127_3');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_127\_3');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_127_3');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_60_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_60\_1');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_60_1');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_61_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_61\_1');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_61_1');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_119_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_119\_1');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_119_1');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_120_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_120\_1');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_120_1');
M_.endo_partitions = struct();
M_.param_names = 'cofintintb1';
M_.param_names_tex = 'cofintintb1';
M_.param_names_long = 'cofintintb1';
M_.param_names = char(M_.param_names, 'cofintintb2');
M_.param_names_tex = char(M_.param_names_tex, 'cofintintb2');
M_.param_names_long = char(M_.param_names_long, 'cofintintb2');
M_.param_names = char(M_.param_names, 'cofintintb3');
M_.param_names_tex = char(M_.param_names_tex, 'cofintintb3');
M_.param_names_long = char(M_.param_names_long, 'cofintintb3');
M_.param_names = char(M_.param_names, 'cofintintb4');
M_.param_names_tex = char(M_.param_names_tex, 'cofintintb4');
M_.param_names_long = char(M_.param_names_long, 'cofintintb4');
M_.param_names = char(M_.param_names, 'cofintinf0');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinf0');
M_.param_names_long = char(M_.param_names_long, 'cofintinf0');
M_.param_names = char(M_.param_names, 'cofintinfb1');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinfb1');
M_.param_names_long = char(M_.param_names_long, 'cofintinfb1');
M_.param_names = char(M_.param_names, 'cofintinfb2');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinfb2');
M_.param_names_long = char(M_.param_names_long, 'cofintinfb2');
M_.param_names = char(M_.param_names, 'cofintinfb3');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinfb3');
M_.param_names_long = char(M_.param_names_long, 'cofintinfb3');
M_.param_names = char(M_.param_names, 'cofintinfb4');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinfb4');
M_.param_names_long = char(M_.param_names_long, 'cofintinfb4');
M_.param_names = char(M_.param_names, 'cofintinff1');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinff1');
M_.param_names_long = char(M_.param_names_long, 'cofintinff1');
M_.param_names = char(M_.param_names, 'cofintinff2');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinff2');
M_.param_names_long = char(M_.param_names_long, 'cofintinff2');
M_.param_names = char(M_.param_names, 'cofintinff3');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinff3');
M_.param_names_long = char(M_.param_names_long, 'cofintinff3');
M_.param_names = char(M_.param_names, 'cofintinff4');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinff4');
M_.param_names_long = char(M_.param_names_long, 'cofintinff4');
M_.param_names = char(M_.param_names, 'cofintout');
M_.param_names_tex = char(M_.param_names_tex, 'cofintout');
M_.param_names_long = char(M_.param_names_long, 'cofintout');
M_.param_names = char(M_.param_names, 'cofintoutb1');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutb1');
M_.param_names_long = char(M_.param_names_long, 'cofintoutb1');
M_.param_names = char(M_.param_names, 'cofintoutb2');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutb2');
M_.param_names_long = char(M_.param_names_long, 'cofintoutb2');
M_.param_names = char(M_.param_names, 'cofintoutb3');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutb3');
M_.param_names_long = char(M_.param_names_long, 'cofintoutb3');
M_.param_names = char(M_.param_names, 'cofintoutb4');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutb4');
M_.param_names_long = char(M_.param_names_long, 'cofintoutb4');
M_.param_names = char(M_.param_names, 'cofintoutf1');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutf1');
M_.param_names_long = char(M_.param_names_long, 'cofintoutf1');
M_.param_names = char(M_.param_names, 'cofintoutf2');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutf2');
M_.param_names_long = char(M_.param_names_long, 'cofintoutf2');
M_.param_names = char(M_.param_names, 'cofintoutf3');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutf3');
M_.param_names_long = char(M_.param_names_long, 'cofintoutf3');
M_.param_names = char(M_.param_names, 'cofintoutf4');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutf4');
M_.param_names_long = char(M_.param_names_long, 'cofintoutf4');
M_.param_names = char(M_.param_names, 'cofintoutp');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutp');
M_.param_names_long = char(M_.param_names_long, 'cofintoutp');
M_.param_names = char(M_.param_names, 'cofintoutpb1');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpb1');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpb1');
M_.param_names = char(M_.param_names, 'cofintoutpb2');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpb2');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpb2');
M_.param_names = char(M_.param_names, 'cofintoutpb3');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpb3');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpb3');
M_.param_names = char(M_.param_names, 'cofintoutpb4');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpb4');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpb4');
M_.param_names = char(M_.param_names, 'cofintoutpf1');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpf1');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpf1');
M_.param_names = char(M_.param_names, 'cofintoutpf2');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpf2');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpf2');
M_.param_names = char(M_.param_names, 'cofintoutpf3');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpf3');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpf3');
M_.param_names = char(M_.param_names, 'cofintoutpf4');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpf4');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpf4');
M_.param_names = char(M_.param_names, 'std_r_');
M_.param_names_tex = char(M_.param_names_tex, 'std\_r\_');
M_.param_names_long = char(M_.param_names_long, 'std_r_');
M_.param_names = char(M_.param_names, 'std_r_quart');
M_.param_names_tex = char(M_.param_names_tex, 'std\_r\_quart');
M_.param_names_long = char(M_.param_names_long, 'std_r_quart');
M_.param_names = char(M_.param_names, 'coffispol');
M_.param_names_tex = char(M_.param_names_tex, 'coffispol');
M_.param_names_long = char(M_.param_names_long, 'coffispol');
M_.param_names = char(M_.param_names, 'betta');
M_.param_names_tex = char(M_.param_names_tex, 'betta');
M_.param_names_long = char(M_.param_names_long, 'betta');
M_.param_names = char(M_.param_names, 'sig');
M_.param_names_tex = char(M_.param_names_tex, 'sig');
M_.param_names_long = char(M_.param_names_long, 'sig');
M_.param_names = char(M_.param_names, 'hh');
M_.param_names_tex = char(M_.param_names_tex, 'hh');
M_.param_names_long = char(M_.param_names_long, 'hh');
M_.param_names = char(M_.param_names, 'varphi');
M_.param_names_tex = char(M_.param_names_tex, 'varphi');
M_.param_names_long = char(M_.param_names_long, 'varphi');
M_.param_names = char(M_.param_names, 'zetta');
M_.param_names_tex = char(M_.param_names_tex, 'zetta');
M_.param_names_long = char(M_.param_names_long, 'zetta');
M_.param_names = char(M_.param_names, 'theta');
M_.param_names_tex = char(M_.param_names_tex, 'theta');
M_.param_names_long = char(M_.param_names_long, 'theta');
M_.param_names = char(M_.param_names, 'Delta');
M_.param_names_tex = char(M_.param_names_tex, 'Delta');
M_.param_names_long = char(M_.param_names_long, 'Delta');
M_.param_names = char(M_.param_names, 'alfa');
M_.param_names_tex = char(M_.param_names_tex, 'alfa');
M_.param_names_long = char(M_.param_names_long, 'alfa');
M_.param_names = char(M_.param_names, 'delta');
M_.param_names_tex = char(M_.param_names_tex, 'delta');
M_.param_names_long = char(M_.param_names_long, 'delta');
M_.param_names = char(M_.param_names, 'G_over_Y');
M_.param_names_tex = char(M_.param_names_tex, 'G\_over\_Y');
M_.param_names_long = char(M_.param_names_long, 'G_over_Y');
M_.param_names = char(M_.param_names, 'eta_i');
M_.param_names_tex = char(M_.param_names_tex, 'eta\_i');
M_.param_names_long = char(M_.param_names_long, 'eta_i');
M_.param_names = char(M_.param_names, 'Psi');
M_.param_names_tex = char(M_.param_names_tex, 'Psi');
M_.param_names_long = char(M_.param_names_long, 'Psi');
M_.param_names = char(M_.param_names, 'Sigma');
M_.param_names_tex = char(M_.param_names_tex, 'Sigma');
M_.param_names_long = char(M_.param_names_long, 'Sigma');
M_.param_names = char(M_.param_names, 'kappa_s');
M_.param_names_tex = char(M_.param_names_tex, 'kappa\_s');
M_.param_names_long = char(M_.param_names_long, 'kappa_s');
M_.param_names = char(M_.param_names, 'kappa_b');
M_.param_names_tex = char(M_.param_names_tex, 'kappa\_b');
M_.param_names_long = char(M_.param_names_long, 'kappa_b');
M_.param_names = char(M_.param_names, 'switch_Kh_bar');
M_.param_names_tex = char(M_.param_names_tex, 'switch\_Kh\_bar');
M_.param_names_long = char(M_.param_names_long, 'switch_Kh_bar');
M_.param_names = char(M_.param_names, 'epsilon');
M_.param_names_tex = char(M_.param_names_tex, 'epsilon');
M_.param_names_long = char(M_.param_names_long, 'epsilon');
M_.param_names = char(M_.param_names, 'gam');
M_.param_names_tex = char(M_.param_names_tex, 'gam');
M_.param_names_long = char(M_.param_names_long, 'gam');
M_.param_names = char(M_.param_names, 'gam_P');
M_.param_names_tex = char(M_.param_names_tex, 'gam\_P');
M_.param_names_long = char(M_.param_names_long, 'gam_P');
M_.param_names = char(M_.param_names, 'kappa_pi');
M_.param_names_tex = char(M_.param_names_tex, 'kappa\_pi');
M_.param_names_long = char(M_.param_names_long, 'kappa_pi');
M_.param_names = char(M_.param_names, 'kappa_pi_ex');
M_.param_names_tex = char(M_.param_names_tex, 'kappa\_pi\_ex');
M_.param_names_long = char(M_.param_names_long, 'kappa_pi_ex');
M_.param_names = char(M_.param_names, 'kappa_y');
M_.param_names_tex = char(M_.param_names_tex, 'kappa\_y');
M_.param_names_long = char(M_.param_names_long, 'kappa_y');
M_.param_names = char(M_.param_names, 'rho_ir');
M_.param_names_tex = char(M_.param_names_tex, 'rho\_ir');
M_.param_names_long = char(M_.param_names_long, 'rho_ir');
M_.param_names = char(M_.param_names, 'rho_ir_DSGE');
M_.param_names_tex = char(M_.param_names_tex, 'rho\_ir\_DSGE');
M_.param_names_long = char(M_.param_names_long, 'rho_ir_DSGE');
M_.param_names = char(M_.param_names, 'rho_ir_QE2');
M_.param_names_tex = char(M_.param_names_tex, 'rho\_ir\_QE2');
M_.param_names_long = char(M_.param_names_long, 'rho_ir_QE2');
M_.param_names = char(M_.param_names, 'rho_ir_zlb');
M_.param_names_tex = char(M_.param_names_tex, 'rho\_ir\_zlb');
M_.param_names_long = char(M_.param_names_long, 'rho_ir_zlb');
M_.param_names = char(M_.param_names, 'rho_ir_zlb_ex');
M_.param_names_tex = char(M_.param_names_tex, 'rho\_ir\_zlb\_ex');
M_.param_names_long = char(M_.param_names_long, 'rho_ir_zlb_ex');
M_.param_names = char(M_.param_names, 'rho_ksi');
M_.param_names_tex = char(M_.param_names_tex, 'rho\_ksi');
M_.param_names_long = char(M_.param_names_long, 'rho_ksi');
M_.param_names = char(M_.param_names, 'sigma_ksi');
M_.param_names_tex = char(M_.param_names_tex, 'sigma\_ksi');
M_.param_names_long = char(M_.param_names_long, 'sigma_ksi');
M_.param_names = char(M_.param_names, 'rho_a');
M_.param_names_tex = char(M_.param_names_tex, 'rho\_a');
M_.param_names_long = char(M_.param_names_long, 'rho_a');
M_.param_names = char(M_.param_names, 'sigma_a');
M_.param_names_tex = char(M_.param_names_tex, 'sigma\_a');
M_.param_names_long = char(M_.param_names_long, 'sigma_a');
M_.param_names = char(M_.param_names, 'rho_g');
M_.param_names_tex = char(M_.param_names_tex, 'rho\_g');
M_.param_names_long = char(M_.param_names_long, 'rho_g');
M_.param_names = char(M_.param_names, 'sigma_g');
M_.param_names_tex = char(M_.param_names_tex, 'sigma\_g');
M_.param_names_long = char(M_.param_names_long, 'sigma_g');
M_.param_names = char(M_.param_names, 'sigma_Ne');
M_.param_names_tex = char(M_.param_names_tex, 'sigma\_Ne');
M_.param_names_long = char(M_.param_names_long, 'sigma_Ne');
M_.param_names = char(M_.param_names, 'sigma_ir');
M_.param_names_tex = char(M_.param_names_tex, 'sigma\_ir');
M_.param_names_long = char(M_.param_names_long, 'sigma_ir');
M_.param_names = char(M_.param_names, 'sigma_ir_ZLB');
M_.param_names_tex = char(M_.param_names_tex, 'sigma\_ir\_ZLB');
M_.param_names_long = char(M_.param_names_long, 'sigma_ir_ZLB');
M_.param_names = char(M_.param_names, 'rho1_shock_psi');
M_.param_names_tex = char(M_.param_names_tex, 'rho1\_shock\_psi');
M_.param_names_long = char(M_.param_names_long, 'rho1_shock_psi');
M_.param_names = char(M_.param_names, 'rho2_shock_psi');
M_.param_names_tex = char(M_.param_names_tex, 'rho2\_shock\_psi');
M_.param_names_long = char(M_.param_names_long, 'rho2_shock_psi');
M_.param_names = char(M_.param_names, 'ma1_shock_psi');
M_.param_names_tex = char(M_.param_names_tex, 'ma1\_shock\_psi');
M_.param_names_long = char(M_.param_names_long, 'ma1_shock_psi');
M_.param_names = char(M_.param_names, 'ma2_shock_psi');
M_.param_names_tex = char(M_.param_names_tex, 'ma2\_shock\_psi');
M_.param_names_long = char(M_.param_names_long, 'ma2_shock_psi');
M_.param_names = char(M_.param_names, 'sigma_psi');
M_.param_names_tex = char(M_.param_names_tex, 'sigma\_psi');
M_.param_names_long = char(M_.param_names_long, 'sigma_psi');
M_.param_names = char(M_.param_names, 'rho1_shock_Gamma');
M_.param_names_tex = char(M_.param_names_tex, 'rho1\_shock\_Gamma');
M_.param_names_long = char(M_.param_names_long, 'rho1_shock_Gamma');
M_.param_names = char(M_.param_names, 'rho2_shock_Gamma');
M_.param_names_tex = char(M_.param_names_tex, 'rho2\_shock\_Gamma');
M_.param_names_long = char(M_.param_names_long, 'rho2_shock_Gamma');
M_.param_names = char(M_.param_names, 'ma1_shock_Gamma');
M_.param_names_tex = char(M_.param_names_tex, 'ma1\_shock\_Gamma');
M_.param_names_long = char(M_.param_names_long, 'ma1_shock_Gamma');
M_.param_names = char(M_.param_names, 'ma2_shock_Gamma');
M_.param_names_tex = char(M_.param_names_tex, 'ma2\_shock\_Gamma');
M_.param_names_long = char(M_.param_names_long, 'ma2_shock_Gamma');
M_.param_names = char(M_.param_names, 'sigma_Gamma');
M_.param_names_tex = char(M_.param_names_tex, 'sigma\_Gamma');
M_.param_names_long = char(M_.param_names_long, 'sigma_Gamma');
M_.param_names = char(M_.param_names, 'rho_shock_ir');
M_.param_names_tex = char(M_.param_names_tex, 'rho\_shock\_ir');
M_.param_names_long = char(M_.param_names_long, 'rho_shock_ir');
M_.param_names = char(M_.param_names, 'nu_K');
M_.param_names_tex = char(M_.param_names_tex, 'nu\_K');
M_.param_names_long = char(M_.param_names_long, 'nu_K');
M_.param_names = char(M_.param_names, 'nu_B');
M_.param_names_tex = char(M_.param_names_tex, 'nu\_B');
M_.param_names_long = char(M_.param_names_long, 'nu_B');
M_.param_names = char(M_.param_names, 'rho_psi');
M_.param_names_tex = char(M_.param_names_tex, 'rho\_psi');
M_.param_names_long = char(M_.param_names_long, 'rho_psi');
M_.param_names = char(M_.param_names, 'rho_Gamma');
M_.param_names_tex = char(M_.param_names_tex, 'rho\_Gamma');
M_.param_names_long = char(M_.param_names_long, 'rho_Gamma');
M_.param_names = char(M_.param_names, 'tau');
M_.param_names_tex = char(M_.param_names_tex, 'tau');
M_.param_names_long = char(M_.param_names_long, 'tau');
M_.param_names = char(M_.param_names, 'w_book');
M_.param_names_tex = char(M_.param_names_tex, 'w\_book');
M_.param_names_long = char(M_.param_names_long, 'w_book');
M_.param_names = char(M_.param_names, 'omega');
M_.param_names_tex = char(M_.param_names_tex, 'omega');
M_.param_names_long = char(M_.param_names_long, 'omega');
M_.param_names = char(M_.param_names, 'lambda');
M_.param_names_tex = char(M_.param_names_tex, 'lambda');
M_.param_names_long = char(M_.param_names_long, 'lambda');
M_.param_names = char(M_.param_names, 'chi');
M_.param_names_tex = char(M_.param_names_tex, 'chi');
M_.param_names_long = char(M_.param_names_long, 'chi');
M_.param_names = char(M_.param_names, 'B');
M_.param_names_tex = char(M_.param_names_tex, 'B');
M_.param_names_long = char(M_.param_names_long, 'B');
M_.param_names = char(M_.param_names, 'Kh_bar');
M_.param_names_tex = char(M_.param_names_tex, 'Kh\_bar');
M_.param_names_long = char(M_.param_names_long, 'Kh_bar');
M_.param_names = char(M_.param_names, 'Bh_bar');
M_.param_names_tex = char(M_.param_names_tex, 'Bh\_bar');
M_.param_names_long = char(M_.param_names_long, 'Bh_bar');
M_.param_names = char(M_.param_names, 'b');
M_.param_names_tex = char(M_.param_names_tex, 'b');
M_.param_names_long = char(M_.param_names_long, 'b');
M_.param_names = char(M_.param_names, 'delta_c');
M_.param_names_tex = char(M_.param_names_tex, 'delta\_c');
M_.param_names_long = char(M_.param_names_long, 'delta_c');
M_.param_names = char(M_.param_names, 'Xi');
M_.param_names_tex = char(M_.param_names_tex, 'Xi');
M_.param_names_long = char(M_.param_names_long, 'Xi');
M_.param_names = char(M_.param_names, 'RkmR_ss');
M_.param_names_tex = char(M_.param_names_tex, 'RkmR\_ss');
M_.param_names_long = char(M_.param_names_long, 'RkmR_ss');
M_.param_names = char(M_.param_names, 'RbmR_ss');
M_.param_names_tex = char(M_.param_names_tex, 'RbmR\_ss');
M_.param_names_long = char(M_.param_names_long, 'RbmR_ss');
M_.param_names = char(M_.param_names, 'Ym_ss');
M_.param_names_tex = char(M_.param_names_tex, 'Ym\_ss');
M_.param_names_long = char(M_.param_names_long, 'Ym_ss');
M_.param_names = char(M_.param_names, 'Y_ss');
M_.param_names_tex = char(M_.param_names_tex, 'Y\_ss');
M_.param_names_long = char(M_.param_names_long, 'Y_ss');
M_.param_names = char(M_.param_names, 'D_ss');
M_.param_names_tex = char(M_.param_names_tex, 'D\_ss');
M_.param_names_long = char(M_.param_names_long, 'D_ss');
M_.param_names = char(M_.param_names, 'K_ss');
M_.param_names_tex = char(M_.param_names_tex, 'K\_ss');
M_.param_names_long = char(M_.param_names_long, 'K_ss');
M_.param_names = char(M_.param_names, 'Keff_ss');
M_.param_names_tex = char(M_.param_names_tex, 'Keff\_ss');
M_.param_names_long = char(M_.param_names_long, 'Keff_ss');
M_.param_names = char(M_.param_names, 'L_ss');
M_.param_names_tex = char(M_.param_names_tex, 'L\_ss');
M_.param_names_long = char(M_.param_names_long, 'L_ss');
M_.param_names = char(M_.param_names, 'I_ss');
M_.param_names_tex = char(M_.param_names_tex, 'I\_ss');
M_.param_names_long = char(M_.param_names_long, 'I_ss');
M_.param_names = char(M_.param_names, 'C_ss');
M_.param_names_tex = char(M_.param_names_tex, 'C\_ss');
M_.param_names_long = char(M_.param_names_long, 'C_ss');
M_.param_names = char(M_.param_names, 'G_ss');
M_.param_names_tex = char(M_.param_names_tex, 'G\_ss');
M_.param_names_long = char(M_.param_names_long, 'G_ss');
M_.param_names = char(M_.param_names, 'Q_ss');
M_.param_names_tex = char(M_.param_names_tex, 'Q\_ss');
M_.param_names_long = char(M_.param_names_long, 'Q_ss');
M_.param_names = char(M_.param_names, 'varrho_ss');
M_.param_names_tex = char(M_.param_names_tex, 'varrho\_ss');
M_.param_names_long = char(M_.param_names_long, 'varrho_ss');
M_.param_names = char(M_.param_names, 'Lambda_ss');
M_.param_names_tex = char(M_.param_names_tex, 'Lambda\_ss');
M_.param_names_long = char(M_.param_names_long, 'Lambda_ss');
M_.param_names = char(M_.param_names, 'Z_ss');
M_.param_names_tex = char(M_.param_names_tex, 'Z\_ss');
M_.param_names_long = char(M_.param_names_long, 'Z_ss');
M_.param_names = char(M_.param_names, 'Ne_ss');
M_.param_names_tex = char(M_.param_names_tex, 'Ne\_ss');
M_.param_names_long = char(M_.param_names_long, 'Ne_ss');
M_.param_names = char(M_.param_names, 'Nn_ss');
M_.param_names_tex = char(M_.param_names_tex, 'Nn\_ss');
M_.param_names_long = char(M_.param_names_long, 'Nn_ss');
M_.param_names = char(M_.param_names, 'Rk_ss');
M_.param_names_tex = char(M_.param_names_tex, 'Rk\_ss');
M_.param_names_long = char(M_.param_names_long, 'Rk_ss');
M_.param_names = char(M_.param_names, 'Rb_ss');
M_.param_names_tex = char(M_.param_names_tex, 'Rb\_ss');
M_.param_names_long = char(M_.param_names_long, 'Rb_ss');
M_.param_names = char(M_.param_names, 'R_ss');
M_.param_names_tex = char(M_.param_names_tex, 'R\_ss');
M_.param_names_long = char(M_.param_names_long, 'R_ss');
M_.param_names = char(M_.param_names, 'qn_ss');
M_.param_names_tex = char(M_.param_names_tex, 'qn\_ss');
M_.param_names_long = char(M_.param_names_long, 'qn_ss');
M_.param_names = char(M_.param_names, 'mu_s_ss');
M_.param_names_tex = char(M_.param_names_tex, 'mu\_s\_ss');
M_.param_names_long = char(M_.param_names_long, 'mu_s_ss');
M_.param_names = char(M_.param_names, 'mu_b_ss');
M_.param_names_tex = char(M_.param_names_tex, 'mu\_b\_ss');
M_.param_names_long = char(M_.param_names_long, 'mu_b_ss');
M_.param_names = char(M_.param_names, 'nu_ss');
M_.param_names_tex = char(M_.param_names_tex, 'nu\_ss');
M_.param_names_long = char(M_.param_names_long, 'nu_ss');
M_.param_names = char(M_.param_names, 'phi_ss');
M_.param_names_tex = char(M_.param_names_tex, 'phi\_ss');
M_.param_names_long = char(M_.param_names_long, 'phi_ss');
M_.param_names = char(M_.param_names, 'x_ss');
M_.param_names_tex = char(M_.param_names_tex, 'x\_ss');
M_.param_names_long = char(M_.param_names_long, 'x_ss');
M_.param_names = char(M_.param_names, 'Omega_ss');
M_.param_names_tex = char(M_.param_names_tex, 'Omega\_ss');
M_.param_names_long = char(M_.param_names_long, 'Omega_ss');
M_.param_names = char(M_.param_names, 'Pm_ss');
M_.param_names_tex = char(M_.param_names_tex, 'Pm\_ss');
M_.param_names_long = char(M_.param_names_long, 'Pm_ss');
M_.param_names = char(M_.param_names, 'X_ss');
M_.param_names_tex = char(M_.param_names_tex, 'X\_ss');
M_.param_names_long = char(M_.param_names_long, 'X_ss');
M_.param_names = char(M_.param_names, 'F_ss');
M_.param_names_tex = char(M_.param_names_tex, 'F\_ss');
M_.param_names_long = char(M_.param_names_long, 'F_ss');
M_.param_names = char(M_.param_names, 'H_ss');
M_.param_names_tex = char(M_.param_names_tex, 'H\_ss');
M_.param_names_long = char(M_.param_names_long, 'H_ss');
M_.param_names = char(M_.param_names, 'ir_ss');
M_.param_names_tex = char(M_.param_names_tex, 'ir\_ss');
M_.param_names_long = char(M_.param_names_long, 'ir_ss');
M_.param_names = char(M_.param_names, 'ib_ss');
M_.param_names_tex = char(M_.param_names_tex, 'ib\_ss');
M_.param_names_long = char(M_.param_names_long, 'ib_ss');
M_.param_names = char(M_.param_names, 'prem_K_ss');
M_.param_names_tex = char(M_.param_names_tex, 'prem\_K\_ss');
M_.param_names_long = char(M_.param_names_long, 'prem_K_ss');
M_.param_names = char(M_.param_names, 'prem_B_ss');
M_.param_names_tex = char(M_.param_names_tex, 'prem\_B\_ss');
M_.param_names_long = char(M_.param_names_long, 'prem_B_ss');
M_.param_names = char(M_.param_names, 'w_ss');
M_.param_names_tex = char(M_.param_names_tex, 'w\_ss');
M_.param_names_long = char(M_.param_names_long, 'w_ss');
M_.param_names = char(M_.param_names, 'qn_rf_ss');
M_.param_names_tex = char(M_.param_names_tex, 'qn\_rf\_ss');
M_.param_names_long = char(M_.param_names_long, 'qn_rf_ss');
M_.param_names = char(M_.param_names, 'iir_ss');
M_.param_names_tex = char(M_.param_names_tex, 'iir\_ss');
M_.param_names_long = char(M_.param_names_long, 'iir_ss');
M_.param_names = char(M_.param_names, 'prem_ib_ss');
M_.param_names_tex = char(M_.param_names_tex, 'prem\_ib\_ss');
M_.param_names_long = char(M_.param_names_long, 'prem_ib_ss');
M_.param_names = char(M_.param_names, 'rb_ss');
M_.param_names_tex = char(M_.param_names_tex, 'rb\_ss');
M_.param_names_long = char(M_.param_names_long, 'rb_ss');
M_.param_names = char(M_.param_names, 'q_ss');
M_.param_names_tex = char(M_.param_names_tex, 'q\_ss');
M_.param_names_long = char(M_.param_names_long, 'q_ss');
M_.param_names = char(M_.param_names, 'qB_ss');
M_.param_names_tex = char(M_.param_names_tex, 'qB\_ss');
M_.param_names_long = char(M_.param_names_long, 'qB_ss');
M_.param_names = char(M_.param_names, 'N_ss');
M_.param_names_tex = char(M_.param_names_tex, 'N\_ss');
M_.param_names_long = char(M_.param_names_long, 'N_ss');
M_.param_names = char(M_.param_names, 'Kb_ss');
M_.param_names_tex = char(M_.param_names_tex, 'Kb\_ss');
M_.param_names_long = char(M_.param_names_long, 'Kb_ss');
M_.param_names = char(M_.param_names, 'Bb_ss');
M_.param_names_tex = char(M_.param_names_tex, 'Bb\_ss');
M_.param_names_long = char(M_.param_names_long, 'Bb_ss');
M_.param_names = char(M_.param_names, 'Dep_ss');
M_.param_names_tex = char(M_.param_names_tex, 'Dep\_ss');
M_.param_names_long = char(M_.param_names_long, 'Dep_ss');
M_.param_names = char(M_.param_names, 'Nbook_ss');
M_.param_names_tex = char(M_.param_names_tex, 'Nbook\_ss');
M_.param_names_long = char(M_.param_names_long, 'Nbook_ss');
M_.param_names = char(M_.param_names, 'phibook_ss');
M_.param_names_tex = char(M_.param_names_tex, 'phibook\_ss');
M_.param_names_long = char(M_.param_names_long, 'phibook_ss');
M_.param_names = char(M_.param_names, 'Kbook_ss');
M_.param_names_tex = char(M_.param_names_tex, 'Kbook\_ss');
M_.param_names_long = char(M_.param_names_long, 'Kbook_ss');
M_.param_names = char(M_.param_names, 'Qfair_ss');
M_.param_names_tex = char(M_.param_names_tex, 'Qfair\_ss');
M_.param_names_long = char(M_.param_names_long, 'Qfair_ss');
M_.param_names = char(M_.param_names, 'Qbook_ss');
M_.param_names_tex = char(M_.param_names_tex, 'Qbook\_ss');
M_.param_names_long = char(M_.param_names_long, 'Qbook_ss');
M_.param_names = char(M_.param_names, 'qnbook_ss');
M_.param_names_tex = char(M_.param_names_tex, 'qnbook\_ss');
M_.param_names_long = char(M_.param_names_long, 'qnbook_ss');
M_.param_names = char(M_.param_names, 'Kh_ss');
M_.param_names_tex = char(M_.param_names_tex, 'Kh\_ss');
M_.param_names_long = char(M_.param_names_long, 'Kh_ss');
M_.param_names = char(M_.param_names, 'Bh_ss');
M_.param_names_tex = char(M_.param_names_tex, 'Bh\_ss');
M_.param_names_long = char(M_.param_names_long, 'Bh_ss');
M_.param_names = char(M_.param_names, 'irstar_ss');
M_.param_names_tex = char(M_.param_names_tex, 'irstar\_ss');
M_.param_names_long = char(M_.param_names_long, 'irstar_ss');
M_.param_names = char(M_.param_names, 'Welf_ss');
M_.param_names_tex = char(M_.param_names_tex, 'Welf\_ss');
M_.param_names_long = char(M_.param_names_long, 'Welf_ss');
M_.param_names = char(M_.param_names, 'a_ss');
M_.param_names_tex = char(M_.param_names_tex, 'a\_ss');
M_.param_names_long = char(M_.param_names_long, 'a_ss');
M_.param_names = char(M_.param_names, 'ksi_ss');
M_.param_names_tex = char(M_.param_names_tex, 'ksi\_ss');
M_.param_names_long = char(M_.param_names_long, 'ksi_ss');
M_.param_names = char(M_.param_names, 'g_ss');
M_.param_names_tex = char(M_.param_names_tex, 'g\_ss');
M_.param_names_long = char(M_.param_names_long, 'g_ss');
M_.param_names = char(M_.param_names, 'shock_ir_ss');
M_.param_names_tex = char(M_.param_names_tex, 'shock\_ir\_ss');
M_.param_names_long = char(M_.param_names_long, 'shock_ir_ss');
M_.param_names = char(M_.param_names, 'infl_ss');
M_.param_names_tex = char(M_.param_names_tex, 'infl\_ss');
M_.param_names_long = char(M_.param_names_long, 'infl_ss');
M_.param_names = char(M_.param_names, 'inflstar_ss');
M_.param_names_tex = char(M_.param_names_tex, 'inflstar\_ss');
M_.param_names_long = char(M_.param_names_long, 'inflstar_ss');
M_.param_names = char(M_.param_names, 'psi_ss');
M_.param_names_tex = char(M_.param_names_tex, 'psi\_ss');
M_.param_names_long = char(M_.param_names_long, 'psi_ss');
M_.param_names = char(M_.param_names, 'Gamma_ss');
M_.param_names_tex = char(M_.param_names_tex, 'Gamma\_ss');
M_.param_names_long = char(M_.param_names_long, 'Gamma_ss');
M_.param_names = char(M_.param_names, 'shock_psi_ss');
M_.param_names_tex = char(M_.param_names_tex, 'shock\_psi\_ss');
M_.param_names_long = char(M_.param_names_long, 'shock_psi_ss');
M_.param_names = char(M_.param_names, 'shock_Gamma_ss');
M_.param_names_tex = char(M_.param_names_tex, 'shock\_Gamma\_ss');
M_.param_names_long = char(M_.param_names_long, 'shock_Gamma_ss');
M_.param_names = char(M_.param_names, 'QKg_Y_ss');
M_.param_names_tex = char(M_.param_names_tex, 'QKg\_Y\_ss');
M_.param_names_long = char(M_.param_names_long, 'QKg_Y_ss');
M_.param_names = char(M_.param_names, 'qBg_Y_ss');
M_.param_names_tex = char(M_.param_names_tex, 'qBg\_Y\_ss');
M_.param_names_long = char(M_.param_names_long, 'qBg_Y_ss');
M_.param_names = char(M_.param_names, 'QKg_A_ss');
M_.param_names_tex = char(M_.param_names_tex, 'QKg\_A\_ss');
M_.param_names_long = char(M_.param_names_long, 'QKg_A_ss');
M_.param_names = char(M_.param_names, 'qBg_A_ss');
M_.param_names_tex = char(M_.param_names_tex, 'qBg\_A\_ss');
M_.param_names_long = char(M_.param_names_long, 'qBg_A_ss');
M_.param_names = char(M_.param_names, 'zlb_ss');
M_.param_names_tex = char(M_.param_names_tex, 'zlb\_ss');
M_.param_names_long = char(M_.param_names_long, 'zlb_ss');
M_.param_names = char(M_.param_names, 'Df');
M_.param_names_tex = char(M_.param_names_tex, 'Df');
M_.param_names_long = char(M_.param_names_long, 'Df');
M_.param_names = char(M_.param_names, 'Xf');
M_.param_names_tex = char(M_.param_names_tex, 'Xf');
M_.param_names_long = char(M_.param_names_long, 'Xf');
M_.param_names = char(M_.param_names, 'Pmf');
M_.param_names_tex = char(M_.param_names_tex, 'Pmf');
M_.param_names_long = char(M_.param_names_long, 'Pmf');
M_.param_names = char(M_.param_names, 'inflf');
M_.param_names_tex = char(M_.param_names_tex, 'inflf');
M_.param_names_long = char(M_.param_names_long, 'inflf');
M_.param_names = char(M_.param_names, 'inflstarf');
M_.param_names_tex = char(M_.param_names_tex, 'inflstarf');
M_.param_names_long = char(M_.param_names_long, 'inflstarf');
M_.param_partitions = struct();
M_.exo_det_nbr = 0;
M_.exo_nbr = 7;
M_.endo_nbr = 158;
M_.param_nbr = 172;
M_.orig_endo_nbr = 131;
M_.aux_vars(1).endo_index = 132;
M_.aux_vars(1).type = 0;
M_.aux_vars(2).endo_index = 133;
M_.aux_vars(2).type = 0;
M_.aux_vars(3).endo_index = 134;
M_.aux_vars(3).type = 0;
M_.aux_vars(4).endo_index = 135;
M_.aux_vars(4).type = 0;
M_.aux_vars(5).endo_index = 136;
M_.aux_vars(5).type = 0;
M_.aux_vars(6).endo_index = 137;
M_.aux_vars(6).type = 0;
M_.aux_vars(7).endo_index = 138;
M_.aux_vars(7).type = 0;
M_.aux_vars(8).endo_index = 139;
M_.aux_vars(8).type = 0;
M_.aux_vars(9).endo_index = 140;
M_.aux_vars(9).type = 0;
M_.aux_vars(10).endo_index = 141;
M_.aux_vars(10).type = 1;
M_.aux_vars(10).orig_index = 57;
M_.aux_vars(10).orig_lead_lag = -1;
M_.aux_vars(11).endo_index = 142;
M_.aux_vars(11).type = 1;
M_.aux_vars(11).orig_index = 57;
M_.aux_vars(11).orig_lead_lag = -2;
M_.aux_vars(12).endo_index = 143;
M_.aux_vars(12).type = 1;
M_.aux_vars(12).orig_index = 130;
M_.aux_vars(12).orig_lead_lag = -1;
M_.aux_vars(13).endo_index = 144;
M_.aux_vars(13).type = 1;
M_.aux_vars(13).orig_index = 130;
M_.aux_vars(13).orig_lead_lag = -2;
M_.aux_vars(14).endo_index = 145;
M_.aux_vars(14).type = 1;
M_.aux_vars(14).orig_index = 130;
M_.aux_vars(14).orig_lead_lag = -3;
M_.aux_vars(15).endo_index = 146;
M_.aux_vars(15).type = 1;
M_.aux_vars(15).orig_index = 129;
M_.aux_vars(15).orig_lead_lag = -1;
M_.aux_vars(16).endo_index = 147;
M_.aux_vars(16).type = 1;
M_.aux_vars(16).orig_index = 129;
M_.aux_vars(16).orig_lead_lag = -2;
M_.aux_vars(17).endo_index = 148;
M_.aux_vars(17).type = 1;
M_.aux_vars(17).orig_index = 129;
M_.aux_vars(17).orig_lead_lag = -3;
M_.aux_vars(18).endo_index = 149;
M_.aux_vars(18).type = 1;
M_.aux_vars(18).orig_index = 126;
M_.aux_vars(18).orig_lead_lag = -1;
M_.aux_vars(19).endo_index = 150;
M_.aux_vars(19).type = 1;
M_.aux_vars(19).orig_index = 126;
M_.aux_vars(19).orig_lead_lag = -2;
M_.aux_vars(20).endo_index = 151;
M_.aux_vars(20).type = 1;
M_.aux_vars(20).orig_index = 126;
M_.aux_vars(20).orig_lead_lag = -3;
M_.aux_vars(21).endo_index = 152;
M_.aux_vars(21).type = 1;
M_.aux_vars(21).orig_index = 128;
M_.aux_vars(21).orig_lead_lag = -1;
M_.aux_vars(22).endo_index = 153;
M_.aux_vars(22).type = 1;
M_.aux_vars(22).orig_index = 128;
M_.aux_vars(22).orig_lead_lag = -2;
M_.aux_vars(23).endo_index = 154;
M_.aux_vars(23).type = 1;
M_.aux_vars(23).orig_index = 128;
M_.aux_vars(23).orig_lead_lag = -3;
M_.aux_vars(24).endo_index = 155;
M_.aux_vars(24).type = 1;
M_.aux_vars(24).orig_index = 61;
M_.aux_vars(24).orig_lead_lag = -1;
M_.aux_vars(25).endo_index = 156;
M_.aux_vars(25).type = 1;
M_.aux_vars(25).orig_index = 62;
M_.aux_vars(25).orig_lead_lag = -1;
M_.aux_vars(26).endo_index = 157;
M_.aux_vars(26).type = 1;
M_.aux_vars(26).orig_index = 120;
M_.aux_vars(26).orig_lead_lag = -1;
M_.aux_vars(27).endo_index = 158;
M_.aux_vars(27).type = 1;
M_.aux_vars(27).orig_index = 121;
M_.aux_vars(27).orig_lead_lag = -1;
M_.Sigma_e = zeros(7, 7);
M_.Correlation_matrix = eye(7, 7);
M_.H = 0;
M_.Correlation_matrix_ME = 1;
M_.sigma_e_is_diagonal = 1;
M_.det_shocks = [];
options_.block=0;
options_.bytecode=0;
options_.use_dll=0;
M_.hessian_eq_zero = 0;
erase_compiled_function('NK_GK13_static');
erase_compiled_function('NK_GK13_dynamic');
M_.orig_eq_nbr = 131;
M_.eq_nbr = 158;
M_.ramsey_eq_nbr = 0;
M_.set_auxiliary_variables = exist(['./' M_.fname '_set_auxiliary_variables.m'], 'file') == 2;
M_.lead_lag_incidence = [
 0 61 0;
 0 62 0;
 1 63 0;
 2 64 0;
 0 65 0;
 0 66 0;
 3 67 219;
 4 68 220;
 0 69 0;
 5 70 221;
 6 71 222;
 0 72 0;
 0 73 223;
 0 74 0;
 0 75 0;
 0 76 224;
 0 77 225;
 7 78 0;
 8 79 226;
 0 80 227;
 0 81 0;
 0 82 228;
 9 83 0;
 10 84 0;
 0 85 0;
 0 86 0;
 0 87 0;
 0 88 229;
 0 89 230;
 0 90 0;
 0 91 0;
 0 92 0;
 0 93 0;
 0 94 0;
 0 95 231;
 0 96 0;
 0 97 0;
 0 98 0;
 0 99 232;
 0 100 0;
 11 101 0;
 0 102 0;
 0 103 0;
 0 104 0;
 0 105 0;
 0 106 0;
 12 107 0;
 0 108 233;
 0 109 0;
 0 110 0;
 0 111 0;
 0 112 0;
 0 113 234;
 13 114 0;
 14 115 235;
 15 116 0;
 16 117 236;
 0 118 0;
 17 119 0;
 18 120 0;
 19 121 0;
 20 122 0;
 0 123 0;
 0 124 0;
 0 125 0;
 0 126 0;
 0 127 0;
 0 128 0;
 0 129 0;
 21 130 0;
 0 131 0;
 0 132 0;
 22 133 237;
 23 134 238;
 0 135 0;
 24 136 239;
 25 137 240;
 0 138 0;
 0 139 241;
 0 140 0;
 0 141 0;
 0 142 242;
 0 143 243;
 26 144 0;
 27 145 244;
 0 146 245;
 0 147 0;
 0 148 246;
 28 149 0;
 29 150 0;
 0 151 0;
 0 152 0;
 0 153 0;
 0 154 0;
 0 155 0;
 0 156 247;
 0 157 0;
 0 158 0;
 0 159 0;
 0 160 248;
 0 161 0;
 30 162 0;
 0 163 0;
 0 164 0;
 0 165 0;
 0 166 0;
 0 167 0;
 31 168 0;
 0 169 249;
 0 170 0;
 0 171 0;
 0 172 0;
 0 173 0;
 0 174 250;
 32 175 0;
 33 176 251;
 34 177 0;
 35 178 0;
 36 179 0;
 37 180 0;
 38 181 0;
 0 182 0;
 0 183 0;
 0 184 0;
 0 185 0;
 39 186 0;
 0 187 0;
 40 188 252;
 41 189 253;
 42 190 254;
 0 191 0;
 0 192 255;
 0 193 256;
 0 194 257;
 0 195 258;
 0 196 259;
 0 197 260;
 0 198 261;
 0 199 262;
 0 200 263;
 43 201 0;
 44 202 0;
 45 203 0;
 46 204 0;
 47 205 0;
 48 206 0;
 49 207 0;
 50 208 0;
 51 209 0;
 52 210 0;
 53 211 0;
 54 212 0;
 55 213 0;
 56 214 0;
 57 215 0;
 58 216 0;
 59 217 0;
 60 218 0;]';
M_.nstatic = 69;
M_.nfwrd   = 29;
M_.npred   = 44;
M_.nboth   = 16;
M_.nsfwrd   = 45;
M_.nspred   = 60;
M_.ndynamic   = 89;
M_.equations_tags = {
};
M_.static_and_dynamic_models_differ = 0;
M_.exo_names_orig_ord = [1:7];
M_.maximum_lag = 1;
M_.maximum_lead = 1;
M_.maximum_endo_lag = 1;
M_.maximum_endo_lead = 1;
oo_.steady_state = zeros(158, 1);
M_.maximum_exo_lag = 0;
M_.maximum_exo_lead = 0;
oo_.exo_steady_state = zeros(7, 1);
M_.params = NaN(172, 1);
M_.NNZDerivatives = [621; 26; -1];
M_.params( 35 ) = 0.99500000;
betta = M_.params( 35 );
M_.params( 36 ) = 1.00000000;
sig = M_.params( 36 );
M_.params( 37 ) = 0.81500000;
hh = M_.params( 37 );
M_.params( 38 ) = 0.27600000;
varphi = M_.params( 38 );
M_.params( 39 ) = 7.20000000;
zetta = M_.params( 39 );
M_.params( 40 ) = 0.97155955;
theta = M_.params( 40 );
M_.params( 41 ) = 0.50000000;
Delta = M_.params( 41 );
M_.params( 42 ) = 0.33000000;
alfa = M_.params( 42 );
M_.params( 43 ) = 0.02500000;
delta = M_.params( 43 );
M_.params( 44 ) = 0.20000000;
G_over_Y = M_.params( 44 );
M_.params( 45 ) = 1.72800000;
eta_i = M_.params( 45 );
M_.params( 46 ) = 0.50000000;
Psi = M_.params( 46 );
M_.params( 47 ) = 0.75000000;
Sigma = M_.params( 47 );
M_.params( 48 ) = 1.00000000;
kappa_s = M_.params( 48 );
M_.params( 49 ) = 1.00000000;
kappa_b = M_.params( 49 );
M_.params( 50 ) = 0.00000000;
switch_Kh_bar = M_.params( 50 );
M_.params( 51 ) = 4.16700000;
epsilon = M_.params( 51 );
M_.params( 52 ) = 0.77900000;
gam = M_.params( 52 );
M_.params( 53 ) = 0.00000000;
gam_P = M_.params( 53 );
M_.params( 54 ) = 1.50000000;
kappa_pi = M_.params( 54 );
M_.params( 55 ) = 1.50000000;
kappa_pi_ex = M_.params( 55 );
M_.params( 56 ) = (-0.12500000);
kappa_y = M_.params( 56 );
M_.params( 57 ) = 0.00000000;
rho_ir = M_.params( 57 );
M_.params( 58 ) = 0.00000000;
rho_ir_DSGE = M_.params( 58 );
M_.params( 59 ) = 0.00000000;
rho_ir_QE2 = M_.params( 59 );
M_.params( 60 ) = 0.00000000;
rho_ir_zlb = M_.params( 60 );
M_.params( 61 ) = 0.00000000;
rho_ir_zlb_ex = M_.params( 61 );
M_.params( 62 ) = 0.70000000;
rho_ksi = M_.params( 62 );
M_.params( 63 ) = 0.04000000;
sigma_ksi = M_.params( 63 );
M_.params( 64 ) = 0.95000000;
rho_a = M_.params( 64 );
M_.params( 65 ) = 0.01000000;
sigma_a = M_.params( 65 );
M_.params( 66 ) = 0.95000000;
rho_g = M_.params( 66 );
M_.params( 67 ) = 0.01000000;
sigma_g = M_.params( 67 );
M_.params( 68 ) = 0.30000000;
sigma_Ne = M_.params( 68 );
M_.params( 69 ) = 0.00250000;
sigma_ir = M_.params( 69 );
M_.params( 70 ) = 0.00100000;
sigma_ir_ZLB = M_.params( 70 );
M_.params( 71 ) = 1.50000000;
rho1_shock_psi = M_.params( 71 );
M_.params( 72 ) = (-0.55000000);
rho2_shock_psi = M_.params( 72 );
M_.params( 73 ) = 0.00000000;
ma1_shock_psi = M_.params( 73 );
M_.params( 74 ) = 0.00000000;
ma2_shock_psi = M_.params( 74 );
M_.params( 75 ) = 0.00758333;
sigma_psi = M_.params( 75 );
M_.params( 76 ) = 1.50000000;
rho1_shock_Gamma = M_.params( 76 );
M_.params( 77 ) = (-0.55000000);
rho2_shock_Gamma = M_.params( 77 );
M_.params( 78 ) = 0.00000000;
ma1_shock_Gamma = M_.params( 78 );
M_.params( 79 ) = 0.00000000;
ma2_shock_Gamma = M_.params( 79 );
M_.params( 80 ) = 0.03159722;
sigma_Gamma = M_.params( 80 );
M_.params( 81 ) = 0.00000000;
rho_shock_ir = M_.params( 81 );
M_.params( 82 ) = 0.00000000;
nu_K = M_.params( 82 );
M_.params( 83 ) = 0.00000000;
nu_B = M_.params( 83 );
M_.params( 84 ) = 0.00000000;
rho_psi = M_.params( 84 );
M_.params( 85 ) = 0.00000000;
rho_Gamma = M_.params( 85 );
M_.params( 86 ) = 0.00100000;
tau = M_.params( 86 );
M_.params( 87 ) = 0.75000000;
w_book = M_.params( 87 );
M_.params( 88 ) = 0.00072872;
omega = M_.params( 88 );
M_.params( 89 ) = 0.34530233;
lambda = M_.params( 89 );
M_.params( 153 ) = 0;
a_ss = M_.params( 153 );
M_.params( 154 ) = 0;
ksi_ss = M_.params( 154 );
M_.params( 154 ) = 0;
ksi_ss = M_.params( 154 );
M_.params( 155 ) = 0;
g_ss = M_.params( 155 );
M_.params( 156 ) = 0;
shock_ir_ss = M_.params( 156 );
M_.params( 159 ) = 0;
psi_ss = M_.params( 159 );
M_.params( 160 ) = 0;
Gamma_ss = M_.params( 160 );
M_.params( 161 ) = 0;
shock_psi_ss = M_.params( 161 );
M_.params( 162 ) = 0;
shock_Gamma_ss = M_.params( 162 );
M_.params( 172 ) = 0;
inflstarf = M_.params( 172 );
M_.params( 163 ) = 0;
QKg_Y_ss = M_.params( 163 );
M_.params( 164 ) = 0;
qBg_Y_ss = M_.params( 164 );
M_.params( 165 ) = 0;
QKg_A_ss = M_.params( 165 );
M_.params( 166 ) = 0;
qBg_A_ss = M_.params( 166 );
M_.params( 167 ) = 0;
zlb_ss = M_.params( 167 );
M_.params( 104 ) = (-1.098612288668111);
L_ss = M_.params( 104 );
M_.params( 121 ) = 1.670062534250535;
phi_ss = M_.params( 121 );
M_.params( 97 ) = 0.002484411292921;
RkmR_ss = M_.params( 97 );
M_.params( 122 ) = (-2.120263536200091);
x_ss = M_.params( 122 );
M_.params( 108 ) = 0;
Q_ss = M_.params( 108 );
M_.params( 146 ) = 0;
Qfair_ss = M_.params( 146 );
M_.params( 147 ) = 0;
Qbook_ss = M_.params( 147 );
M_.params( 124 ) = log((M_.params(51)-1)/M_.params(51));
Pm_ss = M_.params( 124 );
M_.params( 125 ) = log(1/exp(M_.params(124)));
X_ss = M_.params( 125 );
M_.params( 101 ) = 0;
D_ss = M_.params( 101 );
M_.params( 110 ) = 0;
Lambda_ss = M_.params( 110 );
M_.params( 116 ) = log(1/M_.params(35));
R_ss = M_.params( 116 );
M_.params( 114 ) = M_.params(97)+M_.params(116);
Rk_ss = M_.params( 114 );
M_.params( 102 ) = log(((exp(M_.params(114))-(1-M_.params(43)))/(exp(M_.params(124))*M_.params(42)))^(1/(M_.params(42)-1))*exp(M_.params(104)));
K_ss = M_.params( 102 );
M_.params( 100 ) = log(exp(M_.params(102))^M_.params(42)*exp(M_.params(104))^(1-M_.params(42)));
Y_ss = M_.params( 100 );
M_.params( 99 ) = M_.params(100);
Ym_ss = M_.params( 99 );
M_.params( 105 ) = log(M_.params(43)*exp(M_.params(102)));
I_ss = M_.params( 105 );
M_.params( 107 ) = log(M_.params(44)*exp(M_.params(100)));
G_ss = M_.params( 107 );
M_.params( 106 ) = log(exp(M_.params(100))-exp(M_.params(105))-exp(M_.params(107)));
C_ss = M_.params( 106 );
M_.params( 109 ) = log((1-M_.params(35)*M_.params(37))*((1-M_.params(37))*exp(M_.params(106)))^(-M_.params(36)));
varrho_ss = M_.params( 109 );
M_.params( 115 ) = M_.params(114)*M_.params(41)+M_.params(116)*(1-M_.params(41));
Rb_ss = M_.params( 115 );
M_.params( 98 ) = M_.params(115)-M_.params(116);
RbmR_ss = M_.params( 98 );
M_.params( 96 ) = exp(M_.params(115))-1;
Xi = M_.params( 96 );
M_.params( 129 ) = log(1+M_.params(96));
ib_ss = M_.params( 129 );
M_.params( 136 ) = log(1+M_.params(96));
rb_ss = M_.params( 136 );
M_.params( 117 ) = log(M_.params(96)/(exp(M_.params(115))-1));
qn_ss = M_.params( 117 );
M_.params( 148 ) = M_.params(117);
qnbook_ss = M_.params( 148 );
M_.params( 137 ) = M_.params(117);
q_ss = M_.params( 137 );
M_.params( 132 ) = log(exp(M_.params(100))*exp(M_.params(124))*(1-M_.params(42))/exp(M_.params(104)));
w_ss = M_.params( 132 );
M_.params( 111 ) = log(exp(M_.params(124))*M_.params(42)*exp(M_.params(100))/exp(M_.params(102)));
Z_ss = M_.params( 111 );
M_.params( 90 ) = exp(M_.params(100))*exp(M_.params(124))*(1-M_.params(42))/exp(M_.params(104))/(1/exp(M_.params(109))*exp(M_.params(104))^M_.params(38));
chi = M_.params( 90 );
M_.params( 152 ) = (log((1-M_.params(37))*exp(M_.params(106)))-M_.params(90)*exp(M_.params(104))^(1+M_.params(38))/(1+M_.params(38)))/(1-M_.params(35));
Welf_ss = M_.params( 152 );
M_.params( 126 ) = log(exp(M_.params(124))*exp(M_.params(100))/(1-M_.params(35)*M_.params(52)));
F_ss = M_.params( 126 );
M_.params( 127 ) = log(exp(M_.params(100))/(1-M_.params(35)*M_.params(52)));
H_ss = M_.params( 127 );
M_.params( 157 ) = 0;
infl_ss = M_.params( 157 );
M_.params( 158 ) = 0;
inflstar_ss = M_.params( 158 );
M_.params( 128 ) = M_.params(116);
ir_ss = M_.params( 128 );
M_.params( 151 ) = M_.params(128);
irstar_ss = M_.params( 151 );
M_.params( 134 ) = M_.params(128);
iir_ss = M_.params( 134 );
M_.params( 133 ) = log(M_.params(96)/(exp(M_.params(128))-1));
qn_rf_ss = M_.params( 133 );
M_.params( 94 ) = exp(M_.params(124))*M_.params(42)*exp(M_.params(100))/exp(M_.params(102));
b = M_.params( 94 );
M_.params( 95 ) = M_.params(43)-M_.params(94)/(1+M_.params(39));
delta_c = M_.params( 95 );
M_.params( 91 ) = exp(M_.params(102))*exp(M_.params(122))*(1-M_.params(46))/(1-M_.params(47));
B = M_.params( 91 );
M_.params( 123 ) = log((1-M_.params(40))/(1-M_.params(40)-M_.params(97)*M_.params(35)*M_.params(40)*(1+M_.params(41)*exp(M_.params(122)))*exp(M_.params(121))));
Omega_ss = M_.params( 123 );
M_.params( 118 ) = log(M_.params(97)*M_.params(35)*exp(M_.params(123)));
mu_s_ss = M_.params( 118 );
M_.params( 119 ) = log(M_.params(35)*exp(M_.params(123))*M_.params(98));
mu_b_ss = M_.params( 119 );
M_.params( 120 ) = log(M_.params(35)*exp(M_.params(123))*exp(M_.params(116)));
nu_ss = M_.params( 120 );
M_.params( 139 ) = log(M_.params(88)*(exp(M_.params(102))+exp(M_.params(117))*M_.params(91))/(1-M_.params(40)*(exp(M_.params(116))+M_.params(97)*exp(M_.params(121))+exp(M_.params(122))*exp(M_.params(121))*M_.params(98))));
N_ss = M_.params( 139 );
M_.params( 112 ) = log(M_.params(40)*(exp(M_.params(116))+M_.params(97)*exp(M_.params(121))+exp(M_.params(122))*exp(M_.params(121))*M_.params(98))*exp(M_.params(139)));
Ne_ss = M_.params( 112 );
M_.params( 113 ) = log(M_.params(88)*(exp(M_.params(102))+exp(M_.params(117))*M_.params(91)));
Nn_ss = M_.params( 113 );
M_.params( 138 ) = log(M_.params(91)*exp(M_.params(137)));
qB_ss = M_.params( 138 );
M_.params( 92 ) = exp(M_.params(102))*M_.params(46)-M_.params(35)*M_.params(48)*(exp(M_.params(114))-exp(M_.params(116)));
Kh_bar = M_.params( 92 );
M_.params( 93 ) = M_.params(47)*M_.params(91)-(exp(M_.params(114))-exp(M_.params(116)))*M_.params(35)*M_.params(41)*M_.params(49);
Bh_bar = M_.params( 93 );
M_.params( 140 ) = log(exp(M_.params(102))-M_.params(92)-M_.params(35)*M_.params(48)*(exp(M_.params(114))-exp(M_.params(116))));
Kb_ss = M_.params( 140 );
M_.params( 141 ) = log(M_.params(91)-M_.params(93)-(exp(M_.params(114))-exp(M_.params(116)))*M_.params(35)*M_.params(41)*M_.params(49));
Bb_ss = M_.params( 141 );
M_.params( 149 ) = log(exp(M_.params(102))-exp(M_.params(140)));
Kh_ss = M_.params( 149 );
M_.params( 150 ) = log(M_.params(91)-exp(M_.params(141)));
Bh_ss = M_.params( 150 );
M_.params( 142 ) = log(exp(M_.params(140))+exp(M_.params(141))-exp(M_.params(139)));
Dep_ss = M_.params( 142 );
M_.params( 143 ) = M_.params(139);
Nbook_ss = M_.params( 143 );
M_.params( 144 ) = log(exp(M_.params(142))/exp(M_.params(143)));
phibook_ss = M_.params( 144 );
M_.params( 145 ) = M_.params(102);
Kbook_ss = M_.params( 145 );
M_.params( 103 ) = M_.params(102);
Keff_ss = M_.params( 103 );
M_.params( 130 ) = log(exp(M_.params(114))/exp(M_.params(116)));
prem_K_ss = M_.params( 130 );
M_.params( 131 ) = log(exp(M_.params(115))/exp(M_.params(116)));
prem_B_ss = M_.params( 131 );
M_.params( 135 ) = log(exp(M_.params(129))/exp(M_.params(134)));
prem_ib_ss = M_.params( 135 );
M_.params( 171 ) = 0;
inflf = M_.params( 171 );
inflfstarf =0;                 
M_.params( 170 ) = 0;
Pmf = M_.params( 170 );
M_.params( 169 ) = 0;
Xf = M_.params( 169 );
M_.params( 168 ) = 0;
Df = M_.params( 168 );
thispath	=	cd;                                                      
cd('..');                                                                
load	policy_param.mat;                                                
for	i=1:33                                                               
deep_parameter_name	=	M_.param_names(i,:);                         
eval(['M_.params(i)  =  ' deep_parameter_name '  ;'])                
end                                                                      
cd(thispath);                                                            
M_.params( 34 ) = (-1)/M_.params(44);
coffispol = M_.params( 34 );
%
% INITVAL instructions
%
options_.initval_file = 0;
oo_.steady_state( 1 ) = 0;
oo_.steady_state( 2 ) = 0;
oo_.steady_state( 3 ) = 0;
oo_.steady_state( 4 ) = 0.00000000;
oo_.steady_state( 5 ) = 0;
oo_.steady_state( 6 ) = 0;
oo_.steady_state( 7 ) = 0;
oo_.steady_state( 8 ) = 0;
oo_.steady_state( 9 ) = 0;
oo_.steady_state( 10 ) = 0;
oo_.steady_state( 11 ) = 0;
oo_.steady_state( 12 ) = 0;
oo_.steady_state( 13 ) = 0;
oo_.steady_state( 14 ) = 0;
oo_.steady_state( 15 ) = 0;
oo_.steady_state( 16 ) = 0;
oo_.steady_state( 17 ) = 0;
oo_.steady_state( 18 ) = 0;
oo_.steady_state( 19 ) = 0;
oo_.steady_state( 20 ) = 0;
oo_.steady_state( 21 ) = 0;
oo_.steady_state( 22 ) = 0;
oo_.steady_state( 23 ) = 0;
oo_.steady_state( 24 ) = 0;
oo_.steady_state( 25 ) = 0;
oo_.steady_state( 26 ) = 0;
oo_.steady_state( 27 ) = 0;
oo_.steady_state( 28 ) = 0;
oo_.steady_state( 29 ) = 0;
oo_.steady_state( 30 ) = 0;
oo_.steady_state( 31 ) = 0;
oo_.steady_state( 32 ) = 0;
oo_.steady_state( 33 ) = 0;
oo_.steady_state( 34 ) = 0;
oo_.steady_state( 35 ) = 0;
oo_.steady_state( 36 ) = 0;
oo_.steady_state( 37 ) = 0;
oo_.steady_state( 38 ) = 0;
oo_.steady_state( 39 ) = 0;
oo_.steady_state( 40 ) = 0;
oo_.steady_state( 41 ) = 0;
oo_.steady_state( 42 ) = 0;
oo_.steady_state( 43 ) = 0;
oo_.steady_state( 44 ) = 0;
oo_.steady_state( 45 ) = 0;
oo_.steady_state( 46 ) = 0;
oo_.steady_state( 47 ) = 0;
oo_.steady_state( 48 ) = 0;
oo_.steady_state( 49 ) = 0;
oo_.steady_state( 50 ) = 0;
oo_.steady_state( 51 ) = 0;
oo_.steady_state( 52 ) = 0;
oo_.steady_state( 53 ) = 0;
oo_.steady_state( 54 ) = 0;
oo_.steady_state( 55 ) = 0;
oo_.steady_state( 56 ) = 0;
oo_.steady_state( 57 ) = 0;
oo_.steady_state( 58 ) = 0;
oo_.steady_state( 59 ) = 0;
oo_.steady_state( 60 ) = 0;
oo_.steady_state( 61 ) = 0;
oo_.steady_state( 62 ) = 0;
oo_.steady_state( 63 ) = 0;
oo_.steady_state( 64 ) = 0;
oo_.steady_state( 65 ) = 0;
oo_.steady_state( 67 ) = 0;
oo_.exo_steady_state( 1 ) = 0;
oo_.exo_steady_state( 2 ) = 0;
oo_.steady_state( 66 ) = 0;
oo_.exo_steady_state( 3 ) = 0;
oo_.exo_steady_state( 4 ) = 0;
oo_.exo_steady_state( 5 ) = 0;
oo_.steady_state( 68 ) = 0;
oo_.steady_state( 69 ) = 0;
oo_.steady_state( 70 ) = 0.00000000;
oo_.steady_state( 71 ) = 0;
oo_.steady_state( 72 ) = 0;
oo_.steady_state( 73 ) = 0;
oo_.steady_state( 74 ) = 0;
oo_.steady_state( 75 ) = 0;
oo_.steady_state( 76 ) = 0;
oo_.steady_state( 77 ) = 0;
oo_.steady_state( 78 ) = 0;
oo_.steady_state( 79 ) = 0;
oo_.steady_state( 80 ) = 0;
oo_.steady_state( 81 ) = 0;
oo_.steady_state( 82 ) = 0;
oo_.steady_state( 83 ) = 0;
oo_.steady_state( 84 ) = 0;
oo_.steady_state( 85 ) = 0;
oo_.steady_state( 86 ) = 0;
oo_.steady_state( 87 ) = 0;
oo_.steady_state( 88 ) = 0;
oo_.steady_state( 89 ) = 0;
oo_.steady_state( 90 ) = 0;
oo_.steady_state( 91 ) = 0;
oo_.steady_state( 92 ) = 0;
oo_.steady_state( 93 ) = 0;
oo_.steady_state( 94 ) = 0;
oo_.steady_state( 95 ) = 0;
oo_.steady_state( 96 ) = 0;
oo_.steady_state( 97 ) = 0;
oo_.steady_state( 98 ) = 0;
oo_.steady_state( 99 ) = 0;
oo_.steady_state( 100 ) = 0;
oo_.steady_state( 101 ) = 0;
oo_.steady_state( 102 ) = 0;
oo_.steady_state( 103 ) = 0;
oo_.steady_state( 104 ) = 0;
oo_.steady_state( 105 ) = 0;
oo_.steady_state( 106 ) = 0;
oo_.steady_state( 107 ) = 0;
oo_.steady_state( 108 ) = 0;
oo_.steady_state( 109 ) = 0;
oo_.steady_state( 110 ) = 0;
oo_.steady_state( 111 ) = 0;
oo_.steady_state( 112 ) = 0;
oo_.steady_state( 113 ) = 0;
oo_.steady_state( 114 ) = 0;
oo_.steady_state( 115 ) = 0;
oo_.steady_state( 116 ) = 0;
oo_.steady_state( 117 ) = 0;
oo_.steady_state( 118 ) = 0;
oo_.steady_state( 119 ) = 0;
oo_.steady_state( 120 ) = 0;
oo_.steady_state( 121 ) = 0;
oo_.steady_state( 122 ) = 0;
oo_.steady_state( 123 ) = 0;
oo_.steady_state( 124 ) = 0;
oo_.steady_state( 125 ) = 0;
oo_.steady_state(132)=oo_.steady_state(128);
oo_.steady_state(133)=oo_.steady_state(132);
oo_.steady_state(134)=oo_.steady_state(133);
oo_.steady_state(135)=oo_.steady_state(129);
oo_.steady_state(136)=oo_.steady_state(135);
oo_.steady_state(137)=oo_.steady_state(136);
oo_.steady_state(138)=oo_.steady_state(130);
oo_.steady_state(139)=oo_.steady_state(138);
oo_.steady_state(140)=oo_.steady_state(139);
oo_.steady_state(141)=oo_.steady_state(57);
oo_.steady_state(142)=oo_.steady_state(141);
oo_.steady_state(143)=oo_.steady_state(130);
oo_.steady_state(144)=oo_.steady_state(143);
oo_.steady_state(145)=oo_.steady_state(144);
oo_.steady_state(146)=oo_.steady_state(129);
oo_.steady_state(147)=oo_.steady_state(146);
oo_.steady_state(148)=oo_.steady_state(147);
oo_.steady_state(149)=oo_.steady_state(126);
oo_.steady_state(150)=oo_.steady_state(149);
oo_.steady_state(151)=oo_.steady_state(150);
oo_.steady_state(152)=oo_.steady_state(128);
oo_.steady_state(153)=oo_.steady_state(152);
oo_.steady_state(154)=oo_.steady_state(153);
oo_.steady_state(155)=oo_.steady_state(61);
oo_.steady_state(156)=oo_.steady_state(62);
oo_.steady_state(157)=oo_.steady_state(120);
oo_.steady_state(158)=oo_.steady_state(121);
if M_.exo_nbr > 0
	oo_.exo_simul = ones(M_.maximum_lag,1)*oo_.exo_steady_state';
end
if M_.exo_det_nbr > 0
	oo_.exo_det_simul = ones(M_.maximum_lag,1)*oo_.exo_det_steady_state';
end
%
% SHOCKS instructions
%
M_.exo_det_length = 0;
M_.Sigma_e(1, 1) = M_.params(65)^2;
M_.Sigma_e(2, 2) = M_.params(63)^2;
M_.Sigma_e(3, 3) = M_.params(68)^2;
M_.Sigma_e(4, 4) = M_.params(75)^2;
M_.Sigma_e(5, 5) = M_.params(80)^2;
save('NK_GK13_results.mat', 'oo_', 'M_', 'options_');
if exist('estim_params_', 'var') == 1
  save('NK_GK13_results.mat', 'estim_params_', '-append');
end
if exist('bayestopt_', 'var') == 1
  save('NK_GK13_results.mat', 'bayestopt_', '-append');
end
if exist('dataset_', 'var') == 1
  save('NK_GK13_results.mat', 'dataset_', '-append');
end
if exist('estimation_info', 'var') == 1
  save('NK_GK13_results.mat', 'estimation_info', '-append');
end
if exist('dataset_info', 'var') == 1
  save('NK_GK13_results.mat', 'dataset_info', '-append');
end
if exist('oo_recursive_', 'var') == 1
  save('NK_GK13_results.mat', 'oo_recursive_', '-append');
end


disp(['Total computing time : ' dynsec2hms(toc(tic0)) ]);
disp('Note: 1 warning(s) encountered in the preprocessor')
if ~isempty(lastwarn)
  disp('Note: warning(s) encountered in MATLAB/Octave code')
end
diary off
