%
% Status : main Dynare file 
%
% Warning : this file is generated automatically by Dynare
%           from model file (.mod)

tic;
global M_ oo_ options_ ys0_ ex0_ estimation_info
options_ = [];
M_.fname = 'CL_MS07';
%
% Some global variables initialization
%
global_initialization;
diary off;
diary('CL_MS07.log');
M_.exo_names = 'eps_ah';
M_.exo_names_tex = 'eps\_ah';
M_.exo_names_long = 'eps_ah';
M_.exo_names = char(M_.exo_names, 'eps_ys');
M_.exo_names_tex = char(M_.exo_names_tex, 'eps\_ys');
M_.exo_names_long = char(M_.exo_names_long, 'eps_ys');
M_.exo_names = char(M_.exo_names, 'eps_prsF');
M_.exo_names_tex = char(M_.exo_names_tex, 'eps\_prsF');
M_.exo_names_long = char(M_.exo_names_long, 'eps_prsF');
M_.exo_names = char(M_.exo_names, 'eps_yF');
M_.exo_names_tex = char(M_.exo_names_tex, 'eps\_yF');
M_.exo_names_long = char(M_.exo_names_long, 'eps_yF');
M_.exo_names = char(M_.exo_names, 'eps_iF');
M_.exo_names_tex = char(M_.exo_names_tex, 'eps\_iF');
M_.exo_names_long = char(M_.exo_names_long, 'eps_iF');
M_.exo_names = char(M_.exo_names, 'eps_piF');
M_.exo_names_tex = char(M_.exo_names_tex, 'eps\_piF');
M_.exo_names_long = char(M_.exo_names_long, 'eps_piF');
M_.exo_names = char(M_.exo_names, 'eps_sh_w');
M_.exo_names_tex = char(M_.exo_names_tex, 'eps\_sh\_w');
M_.exo_names_long = char(M_.exo_names_long, 'eps_sh_w');
M_.exo_names = char(M_.exo_names, 'eps_sh_c');
M_.exo_names_tex = char(M_.exo_names_tex, 'eps\_sh\_c');
M_.exo_names_long = char(M_.exo_names_long, 'eps_sh_c');
M_.exo_names = char(M_.exo_names, 'eps_sh_i');
M_.exo_names_tex = char(M_.exo_names_tex, 'eps\_sh\_i');
M_.exo_names_long = char(M_.exo_names_long, 'eps_sh_i');
M_.exo_names = char(M_.exo_names, 'eps_prfF');
M_.exo_names_tex = char(M_.exo_names_tex, 'eps\_prfF');
M_.exo_names_long = char(M_.exo_names_long, 'eps_prfF');
M_.exo_names = char(M_.exo_names, 'eps_proF');
M_.exo_names_tex = char(M_.exo_names_tex, 'eps\_proF');
M_.exo_names_long = char(M_.exo_names_long, 'eps_proF');
M_.exo_names = char(M_.exo_names, 'eps_st');
M_.exo_names_tex = char(M_.exo_names_tex, 'eps\_st');
M_.exo_names_long = char(M_.exo_names_long, 'eps_st');
M_.exo_names = char(M_.exo_names, 'interest_');
M_.exo_names_tex = char(M_.exo_names_tex, 'interest\_');
M_.exo_names_long = char(M_.exo_names_long, 'interest_');
M_.exo_names = char(M_.exo_names, 'fiscal_');
M_.exo_names_tex = char(M_.exo_names_tex, 'fiscal\_');
M_.exo_names_long = char(M_.exo_names_long, 'fiscal_');
M_.endo_names = 'ah_hat';
M_.endo_names_tex = 'ah\_hat';
M_.endo_names_long = 'ah_hat';
M_.endo_names = char(M_.endo_names, 'bF_hat');
M_.endo_names_tex = char(M_.endo_names_tex, 'bF\_hat');
M_.endo_names_long = char(M_.endo_names_long, 'bF_hat');
M_.endo_names = char(M_.endo_names, 'bg_hat');
M_.endo_names_tex = char(M_.endo_names_tex, 'bg\_hat');
M_.endo_names_long = char(M_.endo_names_long, 'bg_hat');
M_.endo_names = char(M_.endo_names, 'c_hat');
M_.endo_names_tex = char(M_.endo_names_tex, 'c\_hat');
M_.endo_names_long = char(M_.endo_names_long, 'c_hat');
M_.endo_names = char(M_.endo_names, 'ca_y_hat');
M_.endo_names_tex = char(M_.endo_names_tex, 'ca\_y\_hat');
M_.endo_names_long = char(M_.endo_names_long, 'ca_y_hat');
M_.endo_names = char(M_.endo_names, 'cf_hat');
M_.endo_names_tex = char(M_.endo_names_tex, 'cf\_hat');
M_.endo_names_long = char(M_.endo_names_long, 'cf_hat');
M_.endo_names = char(M_.endo_names, 'ch_hat');
M_.endo_names_tex = char(M_.endo_names_tex, 'ch\_hat');
M_.endo_names_long = char(M_.endo_names_long, 'ch_hat');
M_.endo_names = char(M_.endo_names, 'chF_hat');
M_.endo_names_tex = char(M_.endo_names_tex, 'chF\_hat');
M_.endo_names_long = char(M_.endo_names_long, 'chF_hat');
M_.endo_names = char(M_.endo_names, 'dc_hat');
M_.endo_names_tex = char(M_.endo_names_tex, 'dc\_hat');
M_.endo_names_long = char(M_.endo_names_long, 'dc_hat');
M_.endo_names = char(M_.endo_names, 'de_hat');
M_.endo_names_tex = char(M_.endo_names_tex, 'de\_hat');
M_.endo_names_long = char(M_.endo_names_long, 'de_hat');
M_.endo_names = char(M_.endo_names, 'dinv_hat');
M_.endo_names_tex = char(M_.endo_names_tex, 'dinv\_hat');
M_.endo_names_long = char(M_.endo_names_long, 'dinv_hat');
M_.endo_names = char(M_.endo_names, 'dwr_hat');
M_.endo_names_tex = char(M_.endo_names_tex, 'dwr\_hat');
M_.endo_names_long = char(M_.endo_names_long, 'dwr_hat');
M_.endo_names = char(M_.endo_names, 'dy_hat');
M_.endo_names_tex = char(M_.endo_names_tex, 'dy\_hat');
M_.endo_names_long = char(M_.endo_names_long, 'dy_hat');
M_.endo_names = char(M_.endo_names, 'dyF_hat');
M_.endo_names_tex = char(M_.endo_names_tex, 'dyF\_hat');
M_.endo_names_long = char(M_.endo_names_long, 'dyF_hat');
M_.endo_names = char(M_.endo_names, 'dys_hat');
M_.endo_names_tex = char(M_.endo_names_tex, 'dys\_hat');
M_.endo_names_long = char(M_.endo_names_long, 'dys_hat');
M_.endo_names = char(M_.endo_names, 'g_hat');
M_.endo_names_tex = char(M_.endo_names_tex, 'g\_hat');
M_.endo_names_long = char(M_.endo_names_long, 'g_hat');
M_.endo_names = char(M_.endo_names, 'gex_hat');
M_.endo_names_tex = char(M_.endo_names_tex, 'gex\_hat');
M_.endo_names_long = char(M_.endo_names_long, 'gex_hat');
M_.endo_names = char(M_.endo_names, 'i_hat');
M_.endo_names_tex = char(M_.endo_names_tex, 'i\_hat');
M_.endo_names_long = char(M_.endo_names_long, 'i_hat');
M_.endo_names = char(M_.endo_names, 'iF_hat');
M_.endo_names_tex = char(M_.endo_names_tex, 'iF\_hat');
M_.endo_names_long = char(M_.endo_names_long, 'iF_hat');
M_.endo_names = char(M_.endo_names, 'iFax_hat');
M_.endo_names_tex = char(M_.endo_names_tex, 'iFax\_hat');
M_.endo_names_long = char(M_.endo_names_long, 'iFax_hat');
M_.endo_names = char(M_.endo_names, 'inv_hat');
M_.endo_names_tex = char(M_.endo_names_tex, 'inv\_hat');
M_.endo_names_long = char(M_.endo_names_long, 'inv_hat');
M_.endo_names = char(M_.endo_names, 'invf_hat');
M_.endo_names_tex = char(M_.endo_names_tex, 'invf\_hat');
M_.endo_names_long = char(M_.endo_names_long, 'invf_hat');
M_.endo_names = char(M_.endo_names, 'invh_hat');
M_.endo_names_tex = char(M_.endo_names_tex, 'invh\_hat');
M_.endo_names_long = char(M_.endo_names_long, 'invh_hat');
M_.endo_names = char(M_.endo_names, 'k_hat');
M_.endo_names_tex = char(M_.endo_names_tex, 'k\_hat');
M_.endo_names_long = char(M_.endo_names_long, 'k_hat');
M_.endo_names = char(M_.endo_names, 'klag_hat');
M_.endo_names_tex = char(M_.endo_names_tex, 'klag\_hat');
M_.endo_names_long = char(M_.endo_names_long, 'klag_hat');
M_.endo_names = char(M_.endo_names, 'l_hat');
M_.endo_names_tex = char(M_.endo_names_tex, 'l\_hat');
M_.endo_names_long = char(M_.endo_names_long, 'l_hat');
M_.endo_names = char(M_.endo_names, 'm_hat');
M_.endo_names_tex = char(M_.endo_names_tex, 'm\_hat');
M_.endo_names_long = char(M_.endo_names_long, 'm_hat');
M_.endo_names = char(M_.endo_names, 'mcrh_hat');
M_.endo_names_tex = char(M_.endo_names_tex, 'mcrh\_hat');
M_.endo_names_long = char(M_.endo_names_long, 'mcrh_hat');
M_.endo_names = char(M_.endo_names, 'mo_hat');
M_.endo_names_tex = char(M_.endo_names_tex, 'mo\_hat');
M_.endo_names_long = char(M_.endo_names_long, 'mo_hat');
M_.endo_names = char(M_.endo_names, 'oc_hat');
M_.endo_names_tex = char(M_.endo_names_tex, 'oc\_hat');
M_.endo_names_long = char(M_.endo_names_long, 'oc_hat');
M_.endo_names = char(M_.endo_names, 'oh_hat');
M_.endo_names_tex = char(M_.endo_names_tex, 'oh\_hat');
M_.endo_names_long = char(M_.endo_names_long, 'oh_hat');
M_.endo_names = char(M_.endo_names, 'pic_hat');
M_.endo_names_tex = char(M_.endo_names_tex, 'pic\_hat');
M_.endo_names_long = char(M_.endo_names_long, 'pic_hat');
M_.endo_names = char(M_.endo_names, 'picz_hat');
M_.endo_names_tex = char(M_.endo_names_tex, 'picz\_hat');
M_.endo_names_long = char(M_.endo_names_long, 'picz_hat');
M_.endo_names = char(M_.endo_names, 'pif_hat');
M_.endo_names_tex = char(M_.endo_names_tex, 'pif\_hat');
M_.endo_names_long = char(M_.endo_names_long, 'pif_hat');
M_.endo_names = char(M_.endo_names, 'pifF_hat');
M_.endo_names_tex = char(M_.endo_names_tex, 'pifF\_hat');
M_.endo_names_long = char(M_.endo_names_long, 'pifF_hat');
M_.endo_names = char(M_.endo_names, 'pihd_hat');
M_.endo_names_tex = char(M_.endo_names_tex, 'pihd\_hat');
M_.endo_names_long = char(M_.endo_names_long, 'pihd_hat');
M_.endo_names = char(M_.endo_names, 'pihf_hat');
M_.endo_names_tex = char(M_.endo_names_tex, 'pihf\_hat');
M_.endo_names_long = char(M_.endo_names_long, 'pihf_hat');
M_.endo_names = char(M_.endo_names, 'prf_hat');
M_.endo_names_tex = char(M_.endo_names_tex, 'prf\_hat');
M_.endo_names_long = char(M_.endo_names_long, 'prf_hat');
M_.endo_names = char(M_.endo_names, 'prfF_hat');
M_.endo_names_tex = char(M_.endo_names_tex, 'prfF\_hat');
M_.endo_names_long = char(M_.endo_names_long, 'prfF_hat');
M_.endo_names = char(M_.endo_names, 'prhd_hat');
M_.endo_names_tex = char(M_.endo_names_tex, 'prhd\_hat');
M_.endo_names_long = char(M_.endo_names_long, 'prhd_hat');
M_.endo_names = char(M_.endo_names, 'prhf_hat');
M_.endo_names_tex = char(M_.endo_names_tex, 'prhf\_hat');
M_.endo_names_long = char(M_.endo_names_long, 'prhf_hat');
M_.endo_names = char(M_.endo_names, 'pri_hat');
M_.endo_names_tex = char(M_.endo_names_tex, 'pri\_hat');
M_.endo_names_long = char(M_.endo_names_long, 'pri_hat');
M_.endo_names = char(M_.endo_names, 'prm_hat');
M_.endo_names_tex = char(M_.endo_names_tex, 'prm\_hat');
M_.endo_names_long = char(M_.endo_names_long, 'prm_hat');
M_.endo_names = char(M_.endo_names, 'proF_hat');
M_.endo_names_tex = char(M_.endo_names_tex, 'proF\_hat');
M_.endo_names_long = char(M_.endo_names_long, 'proF_hat');
M_.endo_names = char(M_.endo_names, 'prs_hat');
M_.endo_names_tex = char(M_.endo_names_tex, 'prs\_hat');
M_.endo_names_long = char(M_.endo_names_long, 'prs_hat');
M_.endo_names = char(M_.endo_names, 'prsa_hat');
M_.endo_names_tex = char(M_.endo_names_tex, 'prsa\_hat');
M_.endo_names_long = char(M_.endo_names_long, 'prsa_hat');
M_.endo_names = char(M_.endo_names, 'prsF_hat');
M_.endo_names_tex = char(M_.endo_names_tex, 'prsF\_hat');
M_.endo_names_long = char(M_.endo_names_long, 'prsF_hat');
M_.endo_names = char(M_.endo_names, 'prx_hat');
M_.endo_names_tex = char(M_.endo_names_tex, 'prx\_hat');
M_.endo_names_long = char(M_.endo_names_long, 'prx_hat');
M_.endo_names = char(M_.endo_names, 'pry_hat');
M_.endo_names_tex = char(M_.endo_names_tex, 'pry\_hat');
M_.endo_names_long = char(M_.endo_names_long, 'pry_hat');
M_.endo_names = char(M_.endo_names, 'qr_hat');
M_.endo_names_tex = char(M_.endo_names_tex, 'qr\_hat');
M_.endo_names_long = char(M_.endo_names_long, 'qr_hat');
M_.endo_names = char(M_.endo_names, 'r_hat');
M_.endo_names_tex = char(M_.endo_names_tex, 'r\_hat');
M_.endo_names_long = char(M_.endo_names_long, 'r_hat');
M_.endo_names = char(M_.endo_names, 'rer_hat');
M_.endo_names_tex = char(M_.endo_names_tex, 'rer\_hat');
M_.endo_names_long = char(M_.endo_names_long, 'rer_hat');
M_.endo_names = char(M_.endo_names, 'Rk_hat');
M_.endo_names_tex = char(M_.endo_names_tex, 'Rk\_hat');
M_.endo_names_long = char(M_.endo_names_long, 'Rk_hat');
M_.endo_names = char(M_.endo_names, 'sh_c_hat');
M_.endo_names_tex = char(M_.endo_names_tex, 'sh\_c\_hat');
M_.endo_names_long = char(M_.endo_names_long, 'sh_c_hat');
M_.endo_names = char(M_.endo_names, 'sh_i_hat');
M_.endo_names_tex = char(M_.endo_names_tex, 'sh\_i\_hat');
M_.endo_names_long = char(M_.endo_names_long, 'sh_i_hat');
M_.endo_names = char(M_.endo_names, 'sh_w_hat');
M_.endo_names_tex = char(M_.endo_names_tex, 'sh\_w\_hat');
M_.endo_names_long = char(M_.endo_names_long, 'sh_w_hat');
M_.endo_names = char(M_.endo_names, 'st_hat');
M_.endo_names_tex = char(M_.endo_names_tex, 'st\_hat');
M_.endo_names_long = char(M_.endo_names_long, 'st_hat');
M_.endo_names = char(M_.endo_names, 'tau_hat');
M_.endo_names_tex = char(M_.endo_names_tex, 'tau\_hat');
M_.endo_names_long = char(M_.endo_names_long, 'tau_hat');
M_.endo_names = char(M_.endo_names, 'u_hat');
M_.endo_names_tex = char(M_.endo_names_tex, 'u\_hat');
M_.endo_names_long = char(M_.endo_names_long, 'u_hat');
M_.endo_names = char(M_.endo_names, 'wr_hat');
M_.endo_names_tex = char(M_.endo_names_tex, 'wr\_hat');
M_.endo_names_long = char(M_.endo_names_long, 'wr_hat');
M_.endo_names = char(M_.endo_names, 'x_hat');
M_.endo_names_tex = char(M_.endo_names_tex, 'x\_hat');
M_.endo_names_long = char(M_.endo_names_long, 'x_hat');
M_.endo_names = char(M_.endo_names, 'y_hat');
M_.endo_names_tex = char(M_.endo_names_tex, 'y\_hat');
M_.endo_names_long = char(M_.endo_names_long, 'y_hat');
M_.endo_names = char(M_.endo_names, 'yF_hat');
M_.endo_names_tex = char(M_.endo_names_tex, 'yF\_hat');
M_.endo_names_long = char(M_.endo_names_long, 'yF_hat');
M_.endo_names = char(M_.endo_names, 'yFa_hat');
M_.endo_names_tex = char(M_.endo_names_tex, 'yFa\_hat');
M_.endo_names_long = char(M_.endo_names_long, 'yFa_hat');
M_.endo_names = char(M_.endo_names, 'yh_hat');
M_.endo_names_tex = char(M_.endo_names_tex, 'yh\_hat');
M_.endo_names_long = char(M_.endo_names_long, 'yh_hat');
M_.endo_names = char(M_.endo_names, 'ys_hat');
M_.endo_names_tex = char(M_.endo_names_tex, 'ys\_hat');
M_.endo_names_long = char(M_.endo_names_long, 'ys_hat');
M_.endo_names = char(M_.endo_names, 'ysa_hat');
M_.endo_names_tex = char(M_.endo_names_tex, 'ysa\_hat');
M_.endo_names_long = char(M_.endo_names_long, 'ysa_hat');
M_.endo_names = char(M_.endo_names, 'zr_hat');
M_.endo_names_tex = char(M_.endo_names_tex, 'zr\_hat');
M_.endo_names_long = char(M_.endo_names_long, 'zr_hat');
M_.endo_names = char(M_.endo_names, 'bF_flex');
M_.endo_names_tex = char(M_.endo_names_tex, 'bF\_flex');
M_.endo_names_long = char(M_.endo_names_long, 'bF_flex');
M_.endo_names = char(M_.endo_names, 'bg_flex');
M_.endo_names_tex = char(M_.endo_names_tex, 'bg\_flex');
M_.endo_names_long = char(M_.endo_names_long, 'bg_flex');
M_.endo_names = char(M_.endo_names, 'c_flex');
M_.endo_names_tex = char(M_.endo_names_tex, 'c\_flex');
M_.endo_names_long = char(M_.endo_names_long, 'c_flex');
M_.endo_names = char(M_.endo_names, 'ca_y_flex');
M_.endo_names_tex = char(M_.endo_names_tex, 'ca\_y\_flex');
M_.endo_names_long = char(M_.endo_names_long, 'ca_y_flex');
M_.endo_names = char(M_.endo_names, 'cf_flex');
M_.endo_names_tex = char(M_.endo_names_tex, 'cf\_flex');
M_.endo_names_long = char(M_.endo_names_long, 'cf_flex');
M_.endo_names = char(M_.endo_names, 'ch_flex');
M_.endo_names_tex = char(M_.endo_names_tex, 'ch\_flex');
M_.endo_names_long = char(M_.endo_names_long, 'ch_flex');
M_.endo_names = char(M_.endo_names, 'chF_flex');
M_.endo_names_tex = char(M_.endo_names_tex, 'chF\_flex');
M_.endo_names_long = char(M_.endo_names_long, 'chF_flex');
M_.endo_names = char(M_.endo_names, 'dc_flex');
M_.endo_names_tex = char(M_.endo_names_tex, 'dc\_flex');
M_.endo_names_long = char(M_.endo_names_long, 'dc_flex');
M_.endo_names = char(M_.endo_names, 'de_flex');
M_.endo_names_tex = char(M_.endo_names_tex, 'de\_flex');
M_.endo_names_long = char(M_.endo_names_long, 'de_flex');
M_.endo_names = char(M_.endo_names, 'dinv_flex');
M_.endo_names_tex = char(M_.endo_names_tex, 'dinv\_flex');
M_.endo_names_long = char(M_.endo_names_long, 'dinv_flex');
M_.endo_names = char(M_.endo_names, 'dwr_flex');
M_.endo_names_tex = char(M_.endo_names_tex, 'dwr\_flex');
M_.endo_names_long = char(M_.endo_names_long, 'dwr_flex');
M_.endo_names = char(M_.endo_names, 'dy_flex');
M_.endo_names_tex = char(M_.endo_names_tex, 'dy\_flex');
M_.endo_names_long = char(M_.endo_names_long, 'dy_flex');
M_.endo_names = char(M_.endo_names, 'dyF_flex');
M_.endo_names_tex = char(M_.endo_names_tex, 'dyF\_flex');
M_.endo_names_long = char(M_.endo_names_long, 'dyF_flex');
M_.endo_names = char(M_.endo_names, 'dys_flex');
M_.endo_names_tex = char(M_.endo_names_tex, 'dys\_flex');
M_.endo_names_long = char(M_.endo_names_long, 'dys_flex');
M_.endo_names = char(M_.endo_names, 'g_flex');
M_.endo_names_tex = char(M_.endo_names_tex, 'g\_flex');
M_.endo_names_long = char(M_.endo_names_long, 'g_flex');
M_.endo_names = char(M_.endo_names, 'i_flex');
M_.endo_names_tex = char(M_.endo_names_tex, 'i\_flex');
M_.endo_names_long = char(M_.endo_names_long, 'i_flex');
M_.endo_names = char(M_.endo_names, 'iFax_flex');
M_.endo_names_tex = char(M_.endo_names_tex, 'iFax\_flex');
M_.endo_names_long = char(M_.endo_names_long, 'iFax_flex');
M_.endo_names = char(M_.endo_names, 'inv_flex');
M_.endo_names_tex = char(M_.endo_names_tex, 'inv\_flex');
M_.endo_names_long = char(M_.endo_names_long, 'inv_flex');
M_.endo_names = char(M_.endo_names, 'invf_flex');
M_.endo_names_tex = char(M_.endo_names_tex, 'invf\_flex');
M_.endo_names_long = char(M_.endo_names_long, 'invf_flex');
M_.endo_names = char(M_.endo_names, 'invh_flex');
M_.endo_names_tex = char(M_.endo_names_tex, 'invh\_flex');
M_.endo_names_long = char(M_.endo_names_long, 'invh_flex');
M_.endo_names = char(M_.endo_names, 'k_flex');
M_.endo_names_tex = char(M_.endo_names_tex, 'k\_flex');
M_.endo_names_long = char(M_.endo_names_long, 'k_flex');
M_.endo_names = char(M_.endo_names, 'klag_flex');
M_.endo_names_tex = char(M_.endo_names_tex, 'klag\_flex');
M_.endo_names_long = char(M_.endo_names_long, 'klag_flex');
M_.endo_names = char(M_.endo_names, 'l_flex');
M_.endo_names_tex = char(M_.endo_names_tex, 'l\_flex');
M_.endo_names_long = char(M_.endo_names_long, 'l_flex');
M_.endo_names = char(M_.endo_names, 'm_flex');
M_.endo_names_tex = char(M_.endo_names_tex, 'm\_flex');
M_.endo_names_long = char(M_.endo_names_long, 'm_flex');
M_.endo_names = char(M_.endo_names, 'mcrh_flex');
M_.endo_names_tex = char(M_.endo_names_tex, 'mcrh\_flex');
M_.endo_names_long = char(M_.endo_names_long, 'mcrh_flex');
M_.endo_names = char(M_.endo_names, 'mo_flex');
M_.endo_names_tex = char(M_.endo_names_tex, 'mo\_flex');
M_.endo_names_long = char(M_.endo_names_long, 'mo_flex');
M_.endo_names = char(M_.endo_names, 'oc_flex');
M_.endo_names_tex = char(M_.endo_names_tex, 'oc\_flex');
M_.endo_names_long = char(M_.endo_names_long, 'oc_flex');
M_.endo_names = char(M_.endo_names, 'oh_flex');
M_.endo_names_tex = char(M_.endo_names_tex, 'oh\_flex');
M_.endo_names_long = char(M_.endo_names_long, 'oh_flex');
M_.endo_names = char(M_.endo_names, 'pic_flex');
M_.endo_names_tex = char(M_.endo_names_tex, 'pic\_flex');
M_.endo_names_long = char(M_.endo_names_long, 'pic_flex');
M_.endo_names = char(M_.endo_names, 'picz_flex');
M_.endo_names_tex = char(M_.endo_names_tex, 'picz\_flex');
M_.endo_names_long = char(M_.endo_names_long, 'picz_flex');
M_.endo_names = char(M_.endo_names, 'pif_flex');
M_.endo_names_tex = char(M_.endo_names_tex, 'pif\_flex');
M_.endo_names_long = char(M_.endo_names_long, 'pif_flex');
M_.endo_names = char(M_.endo_names, 'pihd_flex');
M_.endo_names_tex = char(M_.endo_names_tex, 'pihd\_flex');
M_.endo_names_long = char(M_.endo_names_long, 'pihd_flex');
M_.endo_names = char(M_.endo_names, 'pihf_flex');
M_.endo_names_tex = char(M_.endo_names_tex, 'pihf\_flex');
M_.endo_names_long = char(M_.endo_names_long, 'pihf_flex');
M_.endo_names = char(M_.endo_names, 'prf_flex');
M_.endo_names_tex = char(M_.endo_names_tex, 'prf\_flex');
M_.endo_names_long = char(M_.endo_names_long, 'prf_flex');
M_.endo_names = char(M_.endo_names, 'prhd_flex');
M_.endo_names_tex = char(M_.endo_names_tex, 'prhd\_flex');
M_.endo_names_long = char(M_.endo_names_long, 'prhd_flex');
M_.endo_names = char(M_.endo_names, 'prhf_flex');
M_.endo_names_tex = char(M_.endo_names_tex, 'prhf\_flex');
M_.endo_names_long = char(M_.endo_names_long, 'prhf_flex');
M_.endo_names = char(M_.endo_names, 'pri_flex');
M_.endo_names_tex = char(M_.endo_names_tex, 'pri\_flex');
M_.endo_names_long = char(M_.endo_names_long, 'pri_flex');
M_.endo_names = char(M_.endo_names, 'prm_flex');
M_.endo_names_tex = char(M_.endo_names_tex, 'prm\_flex');
M_.endo_names_long = char(M_.endo_names_long, 'prm_flex');
M_.endo_names = char(M_.endo_names, 'prs_flex');
M_.endo_names_tex = char(M_.endo_names_tex, 'prs\_flex');
M_.endo_names_long = char(M_.endo_names_long, 'prs_flex');
M_.endo_names = char(M_.endo_names, 'prsa_flex');
M_.endo_names_tex = char(M_.endo_names_tex, 'prsa\_flex');
M_.endo_names_long = char(M_.endo_names_long, 'prsa_flex');
M_.endo_names = char(M_.endo_names, 'prx_flex');
M_.endo_names_tex = char(M_.endo_names_tex, 'prx\_flex');
M_.endo_names_long = char(M_.endo_names_long, 'prx_flex');
M_.endo_names = char(M_.endo_names, 'pry_flex');
M_.endo_names_tex = char(M_.endo_names_tex, 'pry\_flex');
M_.endo_names_long = char(M_.endo_names_long, 'pry_flex');
M_.endo_names = char(M_.endo_names, 'qr_flex');
M_.endo_names_tex = char(M_.endo_names_tex, 'qr\_flex');
M_.endo_names_long = char(M_.endo_names_long, 'qr_flex');
M_.endo_names = char(M_.endo_names, 'r_flex');
M_.endo_names_tex = char(M_.endo_names_tex, 'r\_flex');
M_.endo_names_long = char(M_.endo_names_long, 'r_flex');
M_.endo_names = char(M_.endo_names, 'rer_flex');
M_.endo_names_tex = char(M_.endo_names_tex, 'rer\_flex');
M_.endo_names_long = char(M_.endo_names_long, 'rer_flex');
M_.endo_names = char(M_.endo_names, 'Rk_flex');
M_.endo_names_tex = char(M_.endo_names_tex, 'Rk\_flex');
M_.endo_names_long = char(M_.endo_names_long, 'Rk_flex');
M_.endo_names = char(M_.endo_names, 'tau_flex');
M_.endo_names_tex = char(M_.endo_names_tex, 'tau\_flex');
M_.endo_names_long = char(M_.endo_names_long, 'tau_flex');
M_.endo_names = char(M_.endo_names, 'u_flex');
M_.endo_names_tex = char(M_.endo_names_tex, 'u\_flex');
M_.endo_names_long = char(M_.endo_names_long, 'u_flex');
M_.endo_names = char(M_.endo_names, 'wr_flex');
M_.endo_names_tex = char(M_.endo_names_tex, 'wr\_flex');
M_.endo_names_long = char(M_.endo_names_long, 'wr_flex');
M_.endo_names = char(M_.endo_names, 'x_flex');
M_.endo_names_tex = char(M_.endo_names_tex, 'x\_flex');
M_.endo_names_long = char(M_.endo_names_long, 'x_flex');
M_.endo_names = char(M_.endo_names, 'y_flex');
M_.endo_names_tex = char(M_.endo_names_tex, 'y\_flex');
M_.endo_names_long = char(M_.endo_names_long, 'y_flex');
M_.endo_names = char(M_.endo_names, 'yFa_flex');
M_.endo_names_tex = char(M_.endo_names_tex, 'yFa\_flex');
M_.endo_names_long = char(M_.endo_names_long, 'yFa_flex');
M_.endo_names = char(M_.endo_names, 'yh_flex');
M_.endo_names_tex = char(M_.endo_names_tex, 'yh\_flex');
M_.endo_names_long = char(M_.endo_names_long, 'yh_flex');
M_.endo_names = char(M_.endo_names, 'ysa_flex');
M_.endo_names_tex = char(M_.endo_names_tex, 'ysa\_flex');
M_.endo_names_long = char(M_.endo_names_long, 'ysa_flex');
M_.endo_names = char(M_.endo_names, 'zr_flex');
M_.endo_names_tex = char(M_.endo_names_tex, 'zr\_flex');
M_.endo_names_long = char(M_.endo_names_long, 'zr_flex');
M_.endo_names = char(M_.endo_names, 'eps_gex');
M_.endo_names_tex = char(M_.endo_names_tex, 'eps\_gex');
M_.endo_names_long = char(M_.endo_names_long, 'eps_gex');
M_.endo_names = char(M_.endo_names, 'interest');
M_.endo_names_tex = char(M_.endo_names_tex, 'interest');
M_.endo_names_long = char(M_.endo_names_long, 'interest');
M_.endo_names = char(M_.endo_names, 'inflation');
M_.endo_names_tex = char(M_.endo_names_tex, 'inflation');
M_.endo_names_long = char(M_.endo_names_long, 'inflation');
M_.endo_names = char(M_.endo_names, 'inflationq');
M_.endo_names_tex = char(M_.endo_names_tex, 'inflationq');
M_.endo_names_long = char(M_.endo_names_long, 'inflationq');
M_.endo_names = char(M_.endo_names, 'output');
M_.endo_names_tex = char(M_.endo_names_tex, 'output');
M_.endo_names_long = char(M_.endo_names_long, 'output');
M_.endo_names = char(M_.endo_names, 'outputgap');
M_.endo_names_tex = char(M_.endo_names_tex, 'outputgap');
M_.endo_names_long = char(M_.endo_names_long, 'outputgap');
M_.endo_names = char(M_.endo_names, 'fispol');
M_.endo_names_tex = char(M_.endo_names_tex, 'fispol');
M_.endo_names_long = char(M_.endo_names_long, 'fispol');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_78');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_78');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_78');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_82');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_82');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_82');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_86');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_86');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_86');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_113');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_113');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_113');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_117');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_117');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_117');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_121');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_121');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_121');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_148');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_148');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_148');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_152');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_152');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_152');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_156');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_156');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_156');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_31_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_31\_1');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_31_1');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_31_2');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_31\_2');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_31_2');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_127_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_127\_1');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_127_1');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_127_2');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_127\_2');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_127_2');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_127_3');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_127\_3');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_127_3');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_128_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_128\_1');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_128_1');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_128_2');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_128\_2');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_128_2');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_128_3');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_128\_3');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_128_3');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_124_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_124\_1');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_124_1');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_124_2');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_124\_2');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_124_2');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_124_3');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_124\_3');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_124_3');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_126_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_126\_1');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_126_1');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_126_2');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_126\_2');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_126_2');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_126_3');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_126\_3');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_126_3');
M_.param_names = 'cofintintb1';
M_.param_names_tex = 'cofintintb1';
M_.param_names_long = 'cofintintb1';
M_.param_names = char(M_.param_names, 'cofintintb2');
M_.param_names_tex = char(M_.param_names_tex, 'cofintintb2');
M_.param_names_long = char(M_.param_names_long, 'cofintintb2');
M_.param_names = char(M_.param_names, 'cofintintb3');
M_.param_names_tex = char(M_.param_names_tex, 'cofintintb3');
M_.param_names_long = char(M_.param_names_long, 'cofintintb3');
M_.param_names = char(M_.param_names, 'cofintintb4');
M_.param_names_tex = char(M_.param_names_tex, 'cofintintb4');
M_.param_names_long = char(M_.param_names_long, 'cofintintb4');
M_.param_names = char(M_.param_names, 'cofintinf0');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinf0');
M_.param_names_long = char(M_.param_names_long, 'cofintinf0');
M_.param_names = char(M_.param_names, 'cofintinfb1');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinfb1');
M_.param_names_long = char(M_.param_names_long, 'cofintinfb1');
M_.param_names = char(M_.param_names, 'cofintinfb2');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinfb2');
M_.param_names_long = char(M_.param_names_long, 'cofintinfb2');
M_.param_names = char(M_.param_names, 'cofintinfb3');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinfb3');
M_.param_names_long = char(M_.param_names_long, 'cofintinfb3');
M_.param_names = char(M_.param_names, 'cofintinfb4');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinfb4');
M_.param_names_long = char(M_.param_names_long, 'cofintinfb4');
M_.param_names = char(M_.param_names, 'cofintinff1');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinff1');
M_.param_names_long = char(M_.param_names_long, 'cofintinff1');
M_.param_names = char(M_.param_names, 'cofintinff2');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinff2');
M_.param_names_long = char(M_.param_names_long, 'cofintinff2');
M_.param_names = char(M_.param_names, 'cofintinff3');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinff3');
M_.param_names_long = char(M_.param_names_long, 'cofintinff3');
M_.param_names = char(M_.param_names, 'cofintinff4');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinff4');
M_.param_names_long = char(M_.param_names_long, 'cofintinff4');
M_.param_names = char(M_.param_names, 'cofintout');
M_.param_names_tex = char(M_.param_names_tex, 'cofintout');
M_.param_names_long = char(M_.param_names_long, 'cofintout');
M_.param_names = char(M_.param_names, 'cofintoutb1');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutb1');
M_.param_names_long = char(M_.param_names_long, 'cofintoutb1');
M_.param_names = char(M_.param_names, 'cofintoutb2');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutb2');
M_.param_names_long = char(M_.param_names_long, 'cofintoutb2');
M_.param_names = char(M_.param_names, 'cofintoutb3');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutb3');
M_.param_names_long = char(M_.param_names_long, 'cofintoutb3');
M_.param_names = char(M_.param_names, 'cofintoutb4');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutb4');
M_.param_names_long = char(M_.param_names_long, 'cofintoutb4');
M_.param_names = char(M_.param_names, 'cofintoutf1');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutf1');
M_.param_names_long = char(M_.param_names_long, 'cofintoutf1');
M_.param_names = char(M_.param_names, 'cofintoutf2');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutf2');
M_.param_names_long = char(M_.param_names_long, 'cofintoutf2');
M_.param_names = char(M_.param_names, 'cofintoutf3');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutf3');
M_.param_names_long = char(M_.param_names_long, 'cofintoutf3');
M_.param_names = char(M_.param_names, 'cofintoutf4');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutf4');
M_.param_names_long = char(M_.param_names_long, 'cofintoutf4');
M_.param_names = char(M_.param_names, 'cofintoutp');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutp');
M_.param_names_long = char(M_.param_names_long, 'cofintoutp');
M_.param_names = char(M_.param_names, 'cofintoutpb1');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpb1');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpb1');
M_.param_names = char(M_.param_names, 'cofintoutpb2');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpb2');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpb2');
M_.param_names = char(M_.param_names, 'cofintoutpb3');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpb3');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpb3');
M_.param_names = char(M_.param_names, 'cofintoutpb4');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpb4');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpb4');
M_.param_names = char(M_.param_names, 'cofintoutpf1');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpf1');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpf1');
M_.param_names = char(M_.param_names, 'cofintoutpf2');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpf2');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpf2');
M_.param_names = char(M_.param_names, 'cofintoutpf3');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpf3');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpf3');
M_.param_names = char(M_.param_names, 'cofintoutpf4');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpf4');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpf4');
M_.param_names = char(M_.param_names, 'std_r_');
M_.param_names_tex = char(M_.param_names_tex, 'std\_r\_');
M_.param_names_long = char(M_.param_names_long, 'std_r_');
M_.param_names = char(M_.param_names, 'std_r_quart');
M_.param_names_tex = char(M_.param_names_tex, 'std\_r\_quart');
M_.param_names_long = char(M_.param_names_long, 'std_r_quart');
M_.param_names = char(M_.param_names, 'coffispol');
M_.param_names_tex = char(M_.param_names_tex, 'coffispol');
M_.param_names_long = char(M_.param_names_long, 'coffispol');
M_.param_names = char(M_.param_names, 'sigma_L');
M_.param_names_tex = char(M_.param_names_tex, 'sigma\_L');
M_.param_names_long = char(M_.param_names_long, 'sigma_L');
M_.param_names = char(M_.param_names, 'h');
M_.param_names_tex = char(M_.param_names_tex, 'h');
M_.param_names_long = char(M_.param_names_long, 'h');
M_.param_names = char(M_.param_names, 'phi_L');
M_.param_names_tex = char(M_.param_names_tex, 'phi\_L');
M_.param_names_long = char(M_.param_names_long, 'phi_L');
M_.param_names = char(M_.param_names, 'xi_L');
M_.param_names_tex = char(M_.param_names_tex, 'xi\_L');
M_.param_names_long = char(M_.param_names_long, 'xi_L');
M_.param_names = char(M_.param_names, 'eta_C');
M_.param_names_tex = char(M_.param_names_tex, 'eta\_C');
M_.param_names_long = char(M_.param_names_long, 'eta_C');
M_.param_names = char(M_.param_names, 'theta_I');
M_.param_names_tex = char(M_.param_names_tex, 'theta\_I');
M_.param_names_long = char(M_.param_names_long, 'theta_I');
M_.param_names = char(M_.param_names, 'S_I');
M_.param_names_tex = char(M_.param_names_tex, 'S\_I');
M_.param_names_long = char(M_.param_names_long, 'S_I');
M_.param_names = char(M_.param_names, 'phi_Hd');
M_.param_names_tex = char(M_.param_names_tex, 'phi\_Hd');
M_.param_names_long = char(M_.param_names_long, 'phi_Hd');
M_.param_names = char(M_.param_names, 'xi_Hd');
M_.param_names_tex = char(M_.param_names_tex, 'xi\_Hd');
M_.param_names_long = char(M_.param_names_long, 'xi_Hd');
M_.param_names = char(M_.param_names, 'phi_Hf');
M_.param_names_tex = char(M_.param_names_tex, 'phi\_Hf');
M_.param_names_long = char(M_.param_names_long, 'phi_Hf');
M_.param_names = char(M_.param_names, 'xi_Hf');
M_.param_names_tex = char(M_.param_names_tex, 'xi\_Hf');
M_.param_names_long = char(M_.param_names_long, 'xi_Hf');
M_.param_names = char(M_.param_names, 'phi_F');
M_.param_names_tex = char(M_.param_names_tex, 'phi\_F');
M_.param_names_long = char(M_.param_names_long, 'phi_F');
M_.param_names = char(M_.param_names, 'xi_F');
M_.param_names_tex = char(M_.param_names_tex, 'xi\_F');
M_.param_names_long = char(M_.param_names_long, 'xi_F');
M_.param_names = char(M_.param_names, 'omega_C');
M_.param_names_tex = char(M_.param_names_tex, 'omega\_C');
M_.param_names_long = char(M_.param_names_long, 'omega_C');
M_.param_names = char(M_.param_names, 'omega_H');
M_.param_names_tex = char(M_.param_names_tex, 'omega\_H');
M_.param_names_long = char(M_.param_names_long, 'omega_H');
M_.param_names = char(M_.param_names, 'mvarphi_i1');
M_.param_names_tex = char(M_.param_names_tex, 'mvarphi\_i1');
M_.param_names_long = char(M_.param_names_long, 'mvarphi_i1');
M_.param_names = char(M_.param_names, 'mvarphi_pi1');
M_.param_names_tex = char(M_.param_names_tex, 'mvarphi\_pi1');
M_.param_names_long = char(M_.param_names_long, 'mvarphi_pi1');
M_.param_names = char(M_.param_names, 'mvarphi_y1');
M_.param_names_tex = char(M_.param_names_tex, 'mvarphi\_y1');
M_.param_names_long = char(M_.param_names_long, 'mvarphi_y1');
M_.param_names = char(M_.param_names, 'mvarphi_rer1');
M_.param_names_tex = char(M_.param_names_tex, 'mvarphi\_rer1');
M_.param_names_long = char(M_.param_names_long, 'mvarphi_rer1');
M_.param_names = char(M_.param_names, 'mvarphi_i2');
M_.param_names_tex = char(M_.param_names_tex, 'mvarphi\_i2');
M_.param_names_long = char(M_.param_names_long, 'mvarphi_i2');
M_.param_names = char(M_.param_names, 'mvarphi_pi2');
M_.param_names_tex = char(M_.param_names_tex, 'mvarphi\_pi2');
M_.param_names_long = char(M_.param_names_long, 'mvarphi_pi2');
M_.param_names = char(M_.param_names, 'mvarphi_y2');
M_.param_names_tex = char(M_.param_names_tex, 'mvarphi\_y2');
M_.param_names_long = char(M_.param_names_long, 'mvarphi_y2');
M_.param_names = char(M_.param_names, 'eta_F');
M_.param_names_tex = char(M_.param_names_tex, 'eta\_F');
M_.param_names_long = char(M_.param_names_long, 'eta_F');
M_.param_names = char(M_.param_names, 'mvarrho');
M_.param_names_tex = char(M_.param_names_tex, 'mvarrho');
M_.param_names_long = char(M_.param_names_long, 'mvarrho');
M_.param_names = char(M_.param_names, 'rho_ah');
M_.param_names_tex = char(M_.param_names_tex, 'rho\_ah');
M_.param_names_long = char(M_.param_names_long, 'rho_ah');
M_.param_names = char(M_.param_names, 'rho_ys');
M_.param_names_tex = char(M_.param_names_tex, 'rho\_ys');
M_.param_names_long = char(M_.param_names_long, 'rho_ys');
M_.param_names = char(M_.param_names, 'rho_yF');
M_.param_names_tex = char(M_.param_names_tex, 'rho\_yF');
M_.param_names_long = char(M_.param_names_long, 'rho_yF');
M_.param_names = char(M_.param_names, 'rho_iF');
M_.param_names_tex = char(M_.param_names_tex, 'rho\_iF');
M_.param_names_long = char(M_.param_names_long, 'rho_iF');
M_.param_names = char(M_.param_names, 'rho_piF');
M_.param_names_tex = char(M_.param_names_tex, 'rho\_piF');
M_.param_names_long = char(M_.param_names_long, 'rho_piF');
M_.param_names = char(M_.param_names, 'rho_sh_w');
M_.param_names_tex = char(M_.param_names_tex, 'rho\_sh\_w');
M_.param_names_long = char(M_.param_names_long, 'rho_sh_w');
M_.param_names = char(M_.param_names, 'rho_sh_c');
M_.param_names_tex = char(M_.param_names_tex, 'rho\_sh\_c');
M_.param_names_long = char(M_.param_names_long, 'rho_sh_c');
M_.param_names = char(M_.param_names, 'rho_gex');
M_.param_names_tex = char(M_.param_names_tex, 'rho\_gex');
M_.param_names_long = char(M_.param_names_long, 'rho_gex');
M_.param_names = char(M_.param_names, 'rho_sh_i');
M_.param_names_tex = char(M_.param_names_tex, 'rho\_sh\_i');
M_.param_names_long = char(M_.param_names_long, 'rho_sh_i');
M_.param_names = char(M_.param_names, 'rho_prfF');
M_.param_names_tex = char(M_.param_names_tex, 'rho\_prfF');
M_.param_names_long = char(M_.param_names_long, 'rho_prfF');
M_.param_names = char(M_.param_names, 'rhoT');
M_.param_names_tex = char(M_.param_names_tex, 'rhoT');
M_.param_names_long = char(M_.param_names_long, 'rhoT');
M_.param_names = char(M_.param_names, 'sd_ah');
M_.param_names_tex = char(M_.param_names_tex, 'sd\_ah');
M_.param_names_long = char(M_.param_names_long, 'sd_ah');
M_.param_names = char(M_.param_names, 'sd_ys');
M_.param_names_tex = char(M_.param_names_tex, 'sd\_ys');
M_.param_names_long = char(M_.param_names_long, 'sd_ys');
M_.param_names = char(M_.param_names, 'sd_yF');
M_.param_names_tex = char(M_.param_names_tex, 'sd\_yF');
M_.param_names_long = char(M_.param_names_long, 'sd_yF');
M_.param_names = char(M_.param_names, 'sd_iF');
M_.param_names_tex = char(M_.param_names_tex, 'sd\_iF');
M_.param_names_long = char(M_.param_names_long, 'sd_iF');
M_.param_names = char(M_.param_names, 'sd_piF');
M_.param_names_tex = char(M_.param_names_tex, 'sd\_piF');
M_.param_names_long = char(M_.param_names_long, 'sd_piF');
M_.param_names = char(M_.param_names, 'sd_sh_m');
M_.param_names_tex = char(M_.param_names_tex, 'sd\_sh\_m');
M_.param_names_long = char(M_.param_names_long, 'sd_sh_m');
M_.param_names = char(M_.param_names, 'sd_sh_w');
M_.param_names_tex = char(M_.param_names_tex, 'sd\_sh\_w');
M_.param_names_long = char(M_.param_names_long, 'sd_sh_w');
M_.param_names = char(M_.param_names, 'sd_sh_c');
M_.param_names_tex = char(M_.param_names_tex, 'sd\_sh\_c');
M_.param_names_long = char(M_.param_names_long, 'sd_sh_c');
M_.param_names = char(M_.param_names, 'sd_gex');
M_.param_names_tex = char(M_.param_names_tex, 'sd\_gex');
M_.param_names_long = char(M_.param_names_long, 'sd_gex');
M_.param_names = char(M_.param_names, 'sd_sh_i');
M_.param_names_tex = char(M_.param_names_tex, 'sd\_sh\_i');
M_.param_names_long = char(M_.param_names_long, 'sd_sh_i');
M_.param_names = char(M_.param_names, 'sd_prfF');
M_.param_names_tex = char(M_.param_names_tex, 'sd\_prfF');
M_.param_names_long = char(M_.param_names_long, 'sd_prfF');
M_.param_names = char(M_.param_names, 'sdT');
M_.param_names_tex = char(M_.param_names_tex, 'sdT');
M_.param_names_long = char(M_.param_names_long, 'sdT');
M_.param_names = char(M_.param_names, 'rho_sh_m');
M_.param_names_tex = char(M_.param_names_tex, 'rho\_sh\_m');
M_.param_names_long = char(M_.param_names_long, 'rho_sh_m');
M_.param_names = char(M_.param_names, 'sigma_C');
M_.param_names_tex = char(M_.param_names_tex, 'sigma\_C');
M_.param_names_long = char(M_.param_names_long, 'sigma_C');
M_.param_names = char(M_.param_names, 'eps_L');
M_.param_names_tex = char(M_.param_names_tex, 'eps\_L');
M_.param_names_long = char(M_.param_names_long, 'eps_L');
M_.param_names = char(M_.param_names, 'alpha_C');
M_.param_names_tex = char(M_.param_names_tex, 'alpha\_C');
M_.param_names_long = char(M_.param_names_long, 'alpha_C');
M_.param_names = char(M_.param_names, 'eps_H');
M_.param_names_tex = char(M_.param_names_tex, 'eps\_H');
M_.param_names_long = char(M_.param_names_long, 'eps_H');
M_.param_names = char(M_.param_names, 'eps_F');
M_.param_names_tex = char(M_.param_names_tex, 'eps\_F');
M_.param_names_long = char(M_.param_names_long, 'eps_F');
M_.param_names = char(M_.param_names, 'delta_I');
M_.param_names_tex = char(M_.param_names_tex, 'delta\_I');
M_.param_names_long = char(M_.param_names_long, 'delta_I');
M_.param_names = char(M_.param_names, 'sigma_I');
M_.param_names_tex = char(M_.param_names_tex, 'sigma\_I');
M_.param_names_long = char(M_.param_names_long, 'sigma_I');
M_.param_names = char(M_.param_names, 'gamma_H');
M_.param_names_tex = char(M_.param_names_tex, 'gamma\_H');
M_.param_names_long = char(M_.param_names_long, 'gamma_H');
M_.param_names = char(M_.param_names, 'theta_H');
M_.param_names_tex = char(M_.param_names_tex, 'theta\_H');
M_.param_names_long = char(M_.param_names_long, 'theta_H');
M_.param_names = char(M_.param_names, 'eta_H');
M_.param_names_tex = char(M_.param_names_tex, 'eta\_H');
M_.param_names_long = char(M_.param_names_long, 'eta_H');
M_.param_names = char(M_.param_names, 'chi');
M_.param_names_tex = char(M_.param_names_tex, 'chi');
M_.param_names_long = char(M_.param_names_long, 'chi');
M_.param_names = char(M_.param_names, 'prsF_ref');
M_.param_names_tex = char(M_.param_names_tex, 'prsF\_ref');
M_.param_names_long = char(M_.param_names_long, 'prsF_ref');
M_.param_names = char(M_.param_names, 'n_prsF');
M_.param_names_tex = char(M_.param_names_tex, 'n\_prsF');
M_.param_names_long = char(M_.param_names_long, 'n_prsF');
M_.param_names = char(M_.param_names, 'NX_Y');
M_.param_names_tex = char(M_.param_names_tex, 'NX\_Y');
M_.param_names_long = char(M_.param_names_long, 'NX_Y');
M_.param_names = char(M_.param_names, 'Gh_Y');
M_.param_names_tex = char(M_.param_names_tex, 'Gh\_Y');
M_.param_names_long = char(M_.param_names_long, 'Gh_Y');
M_.param_names = char(M_.param_names, 'Ys_Y');
M_.param_names_tex = char(M_.param_names_tex, 'Ys\_Y');
M_.param_names_long = char(M_.param_names_long, 'Ys_Y');
M_.param_names = char(M_.param_names, 'CCq_Y');
M_.param_names_tex = char(M_.param_names_tex, 'CCq\_Y');
M_.param_names_long = char(M_.param_names_long, 'CCq_Y');
M_.param_names = char(M_.param_names, 'gamma_C');
M_.param_names_tex = char(M_.param_names_tex, 'gamma\_C');
M_.param_names_long = char(M_.param_names_long, 'gamma_C');
M_.param_names = char(M_.param_names, 'gamma_I');
M_.param_names_tex = char(M_.param_names_tex, 'gamma\_I');
M_.param_names_long = char(M_.param_names_long, 'gamma_I');
M_.param_names = char(M_.param_names, 'rho_prsF');
M_.param_names_tex = char(M_.param_names_tex, 'rho\_prsF');
M_.param_names_long = char(M_.param_names_long, 'rho_prsF');
M_.param_names = char(M_.param_names, 'sd_prsF');
M_.param_names_tex = char(M_.param_names_tex, 'sd\_prsF');
M_.param_names_long = char(M_.param_names_long, 'sd_prsF');
M_.param_names = char(M_.param_names, 'rho_proF');
M_.param_names_tex = char(M_.param_names_tex, 'rho\_proF');
M_.param_names_long = char(M_.param_names_long, 'rho_proF');
M_.param_names = char(M_.param_names, 'sd_proF');
M_.param_names_tex = char(M_.param_names_tex, 'sd\_proF');
M_.param_names_long = char(M_.param_names_long, 'sd_proF');
M_.param_names = char(M_.param_names, 'mvarrho_de');
M_.param_names_tex = char(M_.param_names_tex, 'mvarrho\_de');
M_.param_names_long = char(M_.param_names_long, 'mvarrho_de');
M_.param_names = char(M_.param_names, 'psi_mon');
M_.param_names_tex = char(M_.param_names_tex, 'psi\_mon');
M_.param_names_long = char(M_.param_names_long, 'psi_mon');
M_.param_names = char(M_.param_names, 'psi_tau');
M_.param_names_tex = char(M_.param_names_tex, 'psi\_tau');
M_.param_names_long = char(M_.param_names_long, 'psi_tau');
M_.param_names = char(M_.param_names, 'lambda');
M_.param_names_tex = char(M_.param_names_tex, 'lambda');
M_.param_names_long = char(M_.param_names_long, 'lambda');
M_.param_names = char(M_.param_names, 'premio_s');
M_.param_names_tex = char(M_.param_names_tex, 'premio\_s');
M_.param_names_long = char(M_.param_names_long, 'premio_s');
M_.param_names = char(M_.param_names, 'g_y');
M_.param_names_tex = char(M_.param_names_tex, 'g\_y');
M_.param_names_long = char(M_.param_names_long, 'g_y');
M_.param_names = char(M_.param_names, 'pi_C');
M_.param_names_tex = char(M_.param_names_tex, 'pi\_C');
M_.param_names_long = char(M_.param_names_long, 'pi_C');
M_.param_names = char(M_.param_names, 'n');
M_.param_names_tex = char(M_.param_names_tex, 'n');
M_.param_names_long = char(M_.param_names_long, 'n');
M_.param_names = char(M_.param_names, 'g_yF');
M_.param_names_tex = char(M_.param_names_tex, 'g\_yF');
M_.param_names_long = char(M_.param_names_long, 'g_yF');
M_.param_names = char(M_.param_names, 'nF');
M_.param_names_tex = char(M_.param_names_tex, 'nF');
M_.param_names_long = char(M_.param_names_long, 'nF');
M_.param_names = char(M_.param_names, 'piF');
M_.param_names_tex = char(M_.param_names_tex, 'piF');
M_.param_names_long = char(M_.param_names_long, 'piF');
M_.param_names = char(M_.param_names, 'r');
M_.param_names_tex = char(M_.param_names_tex, 'r');
M_.param_names_long = char(M_.param_names_long, 'r');
M_.param_names = char(M_.param_names, 'iF');
M_.param_names_tex = char(M_.param_names_tex, 'iF');
M_.param_names_long = char(M_.param_names_long, 'iF');
M_.param_names = char(M_.param_names, 'Prh');
M_.param_names_tex = char(M_.param_names_tex, 'Prh');
M_.param_names_long = char(M_.param_names_long, 'Prh');
M_.param_names = char(M_.param_names, 'Prf');
M_.param_names_tex = char(M_.param_names_tex, 'Prf');
M_.param_names_long = char(M_.param_names_long, 'Prf');
M_.param_names = char(M_.param_names, 'Wr');
M_.param_names_tex = char(M_.param_names_tex, 'Wr');
M_.param_names_long = char(M_.param_names_long, 'Wr');
M_.param_names = char(M_.param_names, 'RER');
M_.param_names_tex = char(M_.param_names_tex, 'RER');
M_.param_names_long = char(M_.param_names_long, 'RER');
M_.param_names = char(M_.param_names, 'PrFo');
M_.param_names_tex = char(M_.param_names_tex, 'PrFo');
M_.param_names_long = char(M_.param_names_long, 'PrFo');
M_.param_names = char(M_.param_names, 'PrFs');
M_.param_names_tex = char(M_.param_names_tex, 'PrFs');
M_.param_names_long = char(M_.param_names_long, 'PrFs');
M_.param_names = char(M_.param_names, 'Pro');
M_.param_names_tex = char(M_.param_names_tex, 'Pro');
M_.param_names_long = char(M_.param_names_long, 'Pro');
M_.param_names = char(M_.param_names, 'Prs');
M_.param_names_tex = char(M_.param_names_tex, 'Prs');
M_.param_names_long = char(M_.param_names_long, 'Prs');
M_.param_names = char(M_.param_names, 'Pri');
M_.param_names_tex = char(M_.param_names_tex, 'Pri');
M_.param_names_long = char(M_.param_names_long, 'Pri');
M_.param_names = char(M_.param_names, 'beta');
M_.param_names_tex = char(M_.param_names_tex, 'beta');
M_.param_names_long = char(M_.param_names_long, 'beta');
M_.param_names = char(M_.param_names, 'Theta_ss');
M_.param_names_tex = char(M_.param_names_tex, 'Theta\_ss');
M_.param_names_long = char(M_.param_names_long, 'Theta_ss');
M_.param_names = char(M_.param_names, 'Zr');
M_.param_names_tex = char(M_.param_names_tex, 'Zr');
M_.param_names_long = char(M_.param_names_long, 'Zr');
M_.param_names = char(M_.param_names, 'eBF_Y');
M_.param_names_tex = char(M_.param_names_tex, 'eBF\_Y');
M_.param_names_long = char(M_.param_names_long, 'eBF_Y');
M_.param_names = char(M_.param_names, 'Kh_Lh');
M_.param_names_tex = char(M_.param_names_tex, 'Kh\_Lh');
M_.param_names_long = char(M_.param_names_long, 'Kh_Lh');
M_.param_names = char(M_.param_names, 'Oh_Lh');
M_.param_names_tex = char(M_.param_names_tex, 'Oh\_Lh');
M_.param_names_long = char(M_.param_names_long, 'Oh_Lh');
M_.param_names = char(M_.param_names, 'agg_Lh');
M_.param_names_tex = char(M_.param_names_tex, 'agg\_Lh');
M_.param_names_long = char(M_.param_names_long, 'agg_Lh');
M_.param_names = char(M_.param_names, 'Gh_Lh');
M_.param_names_tex = char(M_.param_names_tex, 'Gh\_Lh');
M_.param_names_long = char(M_.param_names_long, 'Gh_Lh');
M_.param_names = char(M_.param_names, 'Yh_Lh');
M_.param_names_tex = char(M_.param_names_tex, 'Yh\_Lh');
M_.param_names_long = char(M_.param_names_long, 'Yh_Lh');
M_.param_names = char(M_.param_names, 'Gh_Kh');
M_.param_names_tex = char(M_.param_names_tex, 'Gh\_Kh');
M_.param_names_long = char(M_.param_names_long, 'Gh_Kh');
M_.param_names = char(M_.param_names, 'Ah');
M_.param_names_tex = char(M_.param_names_tex, 'Ah');
M_.param_names_long = char(M_.param_names_long, 'Ah');
M_.param_names = char(M_.param_names, 'Id_Kh');
M_.param_names_tex = char(M_.param_names_tex, 'Id\_Kh');
M_.param_names_long = char(M_.param_names_long, 'Id_Kh');
M_.param_names = char(M_.param_names, 'I_Y');
M_.param_names_tex = char(M_.param_names_tex, 'I\_Y');
M_.param_names_long = char(M_.param_names_long, 'I_Y');
M_.param_names = char(M_.param_names, 'C_Y');
M_.param_names_tex = char(M_.param_names_tex, 'C\_Y');
M_.param_names_long = char(M_.param_names_long, 'C_Y');
M_.param_names = char(M_.param_names, 'Mf_Y');
M_.param_names_tex = char(M_.param_names_tex, 'Mf\_Y');
M_.param_names_long = char(M_.param_names_long, 'Mf_Y');
M_.param_names = char(M_.param_names, 'VAh_Y');
M_.param_names_tex = char(M_.param_names_tex, 'VAh\_Y');
M_.param_names_long = char(M_.param_names_long, 'VAh_Y');
M_.param_names = char(M_.param_names, 'Y_Lh');
M_.param_names_tex = char(M_.param_names_tex, 'Y\_Lh');
M_.param_names_long = char(M_.param_names_long, 'Y_Lh');
M_.param_names = char(M_.param_names, 'Yh_Y');
M_.param_names_tex = char(M_.param_names_tex, 'Yh\_Y');
M_.param_names_long = char(M_.param_names_long, 'Yh_Y');
M_.param_names = char(M_.param_names, 'M_Y');
M_.param_names_tex = char(M_.param_names_tex, 'M\_Y');
M_.param_names_long = char(M_.param_names_long, 'M_Y');
M_.param_names = char(M_.param_names, 'X_Y');
M_.param_names_tex = char(M_.param_names_tex, 'X\_Y');
M_.param_names_long = char(M_.param_names_long, 'X_Y');
M_.param_names = char(M_.param_names, 'YhF_Y');
M_.param_names_tex = char(M_.param_names_tex, 'YhF\_Y');
M_.param_names_long = char(M_.param_names_long, 'YhF_Y');
M_.param_names = char(M_.param_names, 'Mo_M');
M_.param_names_tex = char(M_.param_names_tex, 'Mo\_M');
M_.param_names_long = char(M_.param_names_long, 'Mo_M');
M_.param_names = char(M_.param_names, 'Ys_X');
M_.param_names_tex = char(M_.param_names_tex, 'Ys\_X');
M_.param_names_long = char(M_.param_names_long, 'Ys_X');
M_.param_names = char(M_.param_names, 'BalG_Y');
M_.param_names_tex = char(M_.param_names_tex, 'BalG\_Y');
M_.param_names_long = char(M_.param_names_long, 'BalG_Y');
M_.param_names = char(M_.param_names, 'Tau_Y');
M_.param_names_tex = char(M_.param_names_tex, 'Tau\_Y');
M_.param_names_long = char(M_.param_names_long, 'Tau_Y');
M_.param_names = char(M_.param_names, 'bG_Y');
M_.param_names_tex = char(M_.param_names_tex, 'bG\_Y');
M_.param_names_long = char(M_.param_names_long, 'bG_Y');
M_.param_names = char(M_.param_names, 'Ren_Y');
M_.param_names_tex = char(M_.param_names_tex, 'Ren\_Y');
M_.param_names_long = char(M_.param_names_long, 'Ren_Y');
M_.param_names = char(M_.param_names, 'RenNs_Y');
M_.param_names_tex = char(M_.param_names_tex, 'RenNs\_Y');
M_.param_names_long = char(M_.param_names_long, 'RenNs_Y');
M_.exo_det_nbr = 0;
M_.exo_nbr = 14;
M_.endo_nbr = 153;
M_.param_nbr = 155;
M_.orig_endo_nbr = 130;
M_.aux_vars(1).endo_index = 131;
M_.aux_vars(1).type = 0;
M_.aux_vars(2).endo_index = 132;
M_.aux_vars(2).type = 0;
M_.aux_vars(3).endo_index = 133;
M_.aux_vars(3).type = 0;
M_.aux_vars(4).endo_index = 134;
M_.aux_vars(4).type = 0;
M_.aux_vars(5).endo_index = 135;
M_.aux_vars(5).type = 0;
M_.aux_vars(6).endo_index = 136;
M_.aux_vars(6).type = 0;
M_.aux_vars(7).endo_index = 137;
M_.aux_vars(7).type = 0;
M_.aux_vars(8).endo_index = 138;
M_.aux_vars(8).type = 0;
M_.aux_vars(9).endo_index = 139;
M_.aux_vars(9).type = 0;
M_.aux_vars(10).endo_index = 140;
M_.aux_vars(10).type = 1;
M_.aux_vars(10).orig_index = 32;
M_.aux_vars(10).orig_lead_lag = -1;
M_.aux_vars(11).endo_index = 141;
M_.aux_vars(11).type = 1;
M_.aux_vars(11).orig_index = 32;
M_.aux_vars(11).orig_lead_lag = -2;
M_.aux_vars(12).endo_index = 142;
M_.aux_vars(12).type = 1;
M_.aux_vars(12).orig_index = 128;
M_.aux_vars(12).orig_lead_lag = -1;
M_.aux_vars(13).endo_index = 143;
M_.aux_vars(13).type = 1;
M_.aux_vars(13).orig_index = 128;
M_.aux_vars(13).orig_lead_lag = -2;
M_.aux_vars(14).endo_index = 144;
M_.aux_vars(14).type = 1;
M_.aux_vars(14).orig_index = 128;
M_.aux_vars(14).orig_lead_lag = -3;
M_.aux_vars(15).endo_index = 145;
M_.aux_vars(15).type = 1;
M_.aux_vars(15).orig_index = 129;
M_.aux_vars(15).orig_lead_lag = -1;
M_.aux_vars(16).endo_index = 146;
M_.aux_vars(16).type = 1;
M_.aux_vars(16).orig_index = 129;
M_.aux_vars(16).orig_lead_lag = -2;
M_.aux_vars(17).endo_index = 147;
M_.aux_vars(17).type = 1;
M_.aux_vars(17).orig_index = 129;
M_.aux_vars(17).orig_lead_lag = -3;
M_.aux_vars(18).endo_index = 148;
M_.aux_vars(18).type = 1;
M_.aux_vars(18).orig_index = 125;
M_.aux_vars(18).orig_lead_lag = -1;
M_.aux_vars(19).endo_index = 149;
M_.aux_vars(19).type = 1;
M_.aux_vars(19).orig_index = 125;
M_.aux_vars(19).orig_lead_lag = -2;
M_.aux_vars(20).endo_index = 150;
M_.aux_vars(20).type = 1;
M_.aux_vars(20).orig_index = 125;
M_.aux_vars(20).orig_lead_lag = -3;
M_.aux_vars(21).endo_index = 151;
M_.aux_vars(21).type = 1;
M_.aux_vars(21).orig_index = 127;
M_.aux_vars(21).orig_lead_lag = -1;
M_.aux_vars(22).endo_index = 152;
M_.aux_vars(22).type = 1;
M_.aux_vars(22).orig_index = 127;
M_.aux_vars(22).orig_lead_lag = -2;
M_.aux_vars(23).endo_index = 153;
M_.aux_vars(23).type = 1;
M_.aux_vars(23).orig_index = 127;
M_.aux_vars(23).orig_lead_lag = -3;
M_.Sigma_e = zeros(14, 14);
M_.Correlation_matrix = eye(14, 14);
M_.H = 0;
M_.Correlation_matrix_ME = 1;
M_.sigma_e_is_diagonal = 1;
options_.linear = 1;
options_.block=0;
options_.bytecode=0;
options_.use_dll=0;
erase_compiled_function('CL_MS07_static');
erase_compiled_function('CL_MS07_dynamic');
M_.lead_lag_incidence = [
 1 72 0;
 2 73 0;
 3 74 0;
 4 75 225;
 0 76 0;
 0 77 0;
 0 78 0;
 0 79 0;
 0 80 0;
 0 81 226;
 0 82 0;
 0 83 0;
 0 84 0;
 0 85 0;
 0 86 0;
 0 87 0;
 5 88 0;
 0 89 0;
 6 90 0;
 7 91 0;
 8 92 227;
 0 93 0;
 0 94 0;
 9 95 0;
 0 96 0;
 10 97 228;
 0 98 0;
 0 99 0;
 0 100 0;
 0 101 0;
 0 102 0;
 11 103 229;
 0 104 0;
 12 105 230;
 13 106 0;
 14 107 231;
 15 108 232;
 16 109 0;
 17 110 0;
 18 111 0;
 19 112 0;
 0 113 0;
 0 114 0;
 20 115 0;
 0 116 0;
 0 117 0;
 21 118 0;
 0 119 0;
 22 120 233;
 23 121 234;
 0 122 0;
 24 123 0;
 0 124 0;
 25 125 0;
 26 126 0;
 27 127 0;
 28 128 0;
 29 129 235;
 0 130 0;
 30 131 236;
 0 132 0;
 31 133 237;
 32 134 0;
 33 135 0;
 0 136 0;
 34 137 0;
 35 138 0;
 0 139 238;
 36 140 0;
 37 141 0;
 38 142 239;
 0 143 0;
 0 144 0;
 0 145 0;
 0 146 0;
 0 147 0;
 0 148 240;
 0 149 0;
 0 150 0;
 0 151 0;
 0 152 0;
 0 153 0;
 0 154 0;
 0 155 0;
 39 156 0;
 40 157 241;
 0 158 0;
 0 159 0;
 41 160 0;
 0 161 0;
 42 162 242;
 0 163 0;
 0 164 0;
 0 165 0;
 0 166 0;
 0 167 0;
 0 168 243;
 0 169 0;
 0 170 0;
 0 171 0;
 0 172 0;
 43 173 0;
 44 174 0;
 45 175 0;
 0 176 0;
 0 177 0;
 0 178 0;
 0 179 0;
 0 180 0;
 46 181 244;
 47 182 245;
 0 183 0;
 48 184 0;
 0 185 0;
 49 186 246;
 0 187 0;
 50 188 247;
 0 189 0;
 51 190 248;
 52 191 0;
 0 192 0;
 53 193 0;
 0 194 249;
 0 195 0;
 54 196 0;
 0 197 0;
 55 198 250;
 56 199 251;
 57 200 252;
 0 201 0;
 0 202 253;
 0 203 254;
 0 204 255;
 0 205 256;
 0 206 257;
 0 207 258;
 0 208 259;
 0 209 260;
 0 210 261;
 58 211 0;
 59 212 0;
 60 213 0;
 61 214 0;
 62 215 0;
 63 216 0;
 64 217 0;
 65 218 0;
 66 219 0;
 67 220 0;
 68 221 0;
 69 222 0;
 70 223 0;
 71 224 0;]';
M_.nstatic = 68;
M_.nfwrd   = 14;
M_.npred   = 48;
M_.nboth   = 23;
M_.nsfwrd   = 37;
M_.nspred   = 71;
M_.ndynamic   = 85;
M_.equations_tags = {
};
M_.static_and_dynamic_models_differ = 0;
M_.exo_names_orig_ord = [1:14];
M_.maximum_lag = 1;
M_.maximum_lead = 1;
M_.maximum_endo_lag = 1;
M_.maximum_endo_lead = 1;
oo_.steady_state = zeros(153, 1);
M_.maximum_exo_lag = 0;
M_.maximum_exo_lead = 0;
oo_.exo_steady_state = zeros(14, 1);
M_.params = NaN(155, 1);
M_.NNZDerivatives = zeros(3, 1);
M_.NNZDerivatives(1) = 745;
M_.NNZDerivatives(2) = 0;
M_.NNZDerivatives(3) = -1;
M_.params( 107 ) = 1;
psi_mon = M_.params( 107 );
M_.params( 108 ) = 1;
psi_tau = M_.params( 108 );
M_.params( 94 ) = 0;
prsF_ref = M_.params( 94 );
M_.params( 106 ) = 0;
mvarrho_de = M_.params( 106 );
M_.params( 111 ) = 0.008637445997712989;
g_y = M_.params( 111 );
M_.params( 112 ) = 0.007417071777733097;
pi_C = M_.params( 112 );
M_.params( 96 ) = 0.02;
NX_Y = M_.params( 96 );
M_.params( 99 ) = (-0.018);
CCq_Y = M_.params( 99 );
M_.params( 128 ) = 0.999;
beta = M_.params( 128 );
M_.params( 85 ) = 0.015;
alpha_C = M_.params( 85 );
M_.params( 100 ) = 0.65;
gamma_C = M_.params( 100 );
M_.params( 101 ) = 0.5;
gamma_I = M_.params( 101 );
M_.params( 98 ) = 0.1;
Ys_Y = M_.params( 98 );
M_.params( 93 ) = 0.4;
chi = M_.params( 93 );
M_.params( 88 ) = 0.014194887410651;
delta_I = M_.params( 88 );
M_.params( 90 ) = 0.01;
gamma_H = M_.params( 90 );
M_.params( 92 ) = 0.66;
eta_H = M_.params( 92 );
M_.params( 84 ) = 11;
eps_L = M_.params( 84 );
M_.params( 86 ) = 11;
eps_H = M_.params( 86 );
M_.params( 87 ) = 11;
eps_F = M_.params( 87 );
M_.params( 102 ) = 0.95;
rho_prsF = M_.params( 102 );
M_.params( 104 ) = 0.97;
rho_proF = M_.params( 104 );
M_.params( 103 ) = 9;
sd_prsF = M_.params( 103 );
M_.params( 105 ) = 12;
sd_proF = M_.params( 105 );
M_.params( 113 ) = 0.003729088938092984;
n = M_.params( 113 );
M_.params( 109 ) = 0.5;
lambda = M_.params( 109 );
M_.params( 35 ) = 0.84;
sigma_L = M_.params( 35 );
M_.params( 36 ) = 0.65;
h = M_.params( 36 );
M_.params( 37 ) = 0.82;
phi_L = M_.params( 37 );
M_.params( 38 ) = 0.44;
xi_L = M_.params( 38 );
M_.params( 39 ) = 1.12;
eta_C = M_.params( 39 );
M_.params( 40 ) = 1.04;
theta_I = M_.params( 40 );
M_.params( 41 ) = 1.48;
S_I = M_.params( 41 );
M_.params( 42 ) = 0.74;
phi_Hd = M_.params( 42 );
M_.params( 43 ) = 0.34;
xi_Hd = M_.params( 43 );
M_.params( 44 ) = 0.59;
phi_Hf = M_.params( 44 );
M_.params( 45 ) = 0.31;
xi_Hf = M_.params( 45 );
M_.params( 46 ) = 0.66;
phi_F = M_.params( 46 );
M_.params( 47 ) = 0.28;
xi_F = M_.params( 47 );
M_.params( 48 ) = 0.3;
omega_C = M_.params( 48 );
M_.params( 49 ) = 0.3;
omega_H = M_.params( 49 );
M_.params( 50 ) = 0.73;
mvarphi_i1 = M_.params( 50 );
M_.params( 51 ) = 1.61;
mvarphi_pi1 = M_.params( 51 );
M_.params( 52 ) = 0.28;
mvarphi_y1 = M_.params( 52 );
M_.params( 53 ) = 0.02;
mvarphi_rer1 = M_.params( 53 );
M_.params( 54 ) = 0.74;
mvarphi_i2 = M_.params( 54 );
M_.params( 55 ) = 1.67;
mvarphi_pi2 = M_.params( 55 );
M_.params( 56 ) = 0.39;
mvarphi_y2 = M_.params( 56 );
M_.params( 57 ) = 0.79;
eta_F = M_.params( 57 );
M_.params( 58 ) = 0.01;
mvarrho = M_.params( 58 );
M_.params( 59 ) = 0.89;
rho_ah = M_.params( 59 );
M_.params( 60 ) = 0.77;
rho_ys = M_.params( 60 );
M_.params( 61 ) = 0.67;
rho_yF = M_.params( 61 );
M_.params( 62 ) = 0.87;
rho_iF = M_.params( 62 );
M_.params( 63 ) = 0.80;
rho_piF = M_.params( 63 );
M_.params( 64 ) = 0.89;
rho_sh_w = M_.params( 64 );
M_.params( 65 ) = 0.87;
rho_sh_c = M_.params( 65 );
M_.params( 66 ) = 0.65;
rho_gex = M_.params( 66 );
M_.params( 67 ) = 0.34;
rho_sh_i = M_.params( 67 );
M_.params( 68 ) = 0.9;
rho_prfF = M_.params( 68 );
M_.params( 69 ) = 0.73;
rhoT = M_.params( 69 );
M_.params( 70 ) = 1.43;
sd_ah = M_.params( 70 );
M_.params( 71 ) = 4.51;
sd_ys = M_.params( 71 );
M_.params( 72 ) = 3.57;
sd_yF = M_.params( 72 );
M_.params( 73 ) = 0.37;
sd_iF = M_.params( 73 );
M_.params( 74 ) = 0.28;
sd_piF = M_.params( 74 );
M_.params( 75 ) = 0.39;
sd_sh_m = M_.params( 75 );
M_.params( 76 ) = 1.01;
sd_sh_w = M_.params( 76 );
M_.params( 77 ) = 3.41;
sd_sh_c = M_.params( 77 );
M_.params( 78 ) = 1.01;
sd_gex = M_.params( 78 );
M_.params( 79 ) = 5.99;
sd_sh_i = M_.params( 79 );
M_.params( 80 ) = 4.16;
sd_prfF = M_.params( 80 );
M_.params( 81 ) = 0.4;
sdT = M_.params( 81 );
M_.params( 82 ) = 0;
rho_sh_m = M_.params( 82 );
M_.params( 97 ) = 0.12;
Gh_Y = M_.params( 97 );
M_.params( 114 ) = 0.004962931573204044;
g_yF = M_.params( 114 );
M_.params( 115 ) = (1+M_.params(111))*(1+M_.params(113))/(1+M_.params(114))-1;
nF = M_.params( 115 );
M_.params( 116 ) = 0.004962931573204044;
piF = M_.params( 116 );
M_.params( 117 ) = 0.01033856326183402;
r = M_.params( 117 );
M_.params( 118 ) = 0.01227223442903891;
iF = M_.params( 118 );
M_.params( 83 ) = 1;
sigma_C = M_.params( 83 );
M_.params( 91 ) = 1;
theta_H = M_.params( 91 );
M_.params( 95 ) = 40;
n_prsF = M_.params( 95 );
M_.params( 89 ) = 100000;
sigma_I = M_.params( 89 );
M_.params( 110 ) = 0;
premio_s = M_.params( 110 );
M_.params( 119 ) = 1;
Prh = M_.params( 119 );
M_.params( 120 ) = 1;
Prf = M_.params( 120 );
M_.params( 121 ) = 1;
Wr = M_.params( 121 );
M_.params( 122 ) = M_.params(120)*(M_.params(87)-1)/M_.params(87);
RER = M_.params( 122 );
M_.params( 123 ) = 1/M_.params(122);
PrFo = M_.params( 123 );
M_.params( 124 ) = 1/M_.params(122);
PrFs = M_.params( 124 );
M_.params( 125 ) = M_.params(122)*M_.params(123);
Pro = M_.params( 125 );
M_.params( 126 ) = M_.params(122)*M_.params(124);
Prs = M_.params( 126 );
M_.params( 127 ) = 1;
Pri = M_.params( 127 );
M_.params( 129 ) = (1+M_.params(117))/((1+M_.params(118))/(1+M_.params(116)));
Theta_ss = M_.params( 129 );
M_.params( 130 ) = ((1+M_.params(117))*(1+M_.params(110))-(1-M_.params(88)))*M_.params(127);
Zr = M_.params( 130 );
M_.params( 131 ) = (1+M_.params(118))*M_.params(99)*M_.params(129)/(1-1/((1+M_.params(111))*(1+M_.params(113))*(1+M_.params(116))));
eBF_Y = M_.params( 131 );
M_.params( 154 ) = M_.params(99)-M_.params(96)-M_.params(131)*(1-1/((1+M_.params(118))*M_.params(129)))/((1+M_.params(111))*(1+M_.params(113))*(1+M_.params(116)));
Ren_Y = M_.params( 154 );
M_.params( 155 ) = M_.params(154)+M_.params(126)*M_.params(98)*(1-M_.params(93));
RenNs_Y = M_.params( 155 );
M_.params( 132 ) = (M_.params(121)/M_.params(130))^M_.params(91)*(1-M_.params(92))/M_.params(92);
Kh_Lh = M_.params( 132 );
M_.params( 133 ) = (M_.params(121)/M_.params(125)/(M_.params(92)^(1/M_.params(91))*(M_.params(132)^(1-M_.params(92)))^(1/M_.params(91)-1/M_.params(49))))^M_.params(49)*M_.params(90)/(1-M_.params(90));
Oh_Lh = M_.params( 133 );
M_.params( 134 ) = ((1-M_.params(90))^(1/M_.params(49))*(M_.params(132)^(1-M_.params(92)))^((M_.params(49)-1)/M_.params(49))+M_.params(90)^(1/M_.params(49))*M_.params(133)^((M_.params(49)-1)/M_.params(49)))^(M_.params(49)/(M_.params(49)-1));
agg_Lh = M_.params( 134 );
M_.params( 135 ) = M_.params(132)^(1-M_.params(92));
Gh_Lh = M_.params( 135 );
M_.params( 136 ) = (M_.params(121)+M_.params(130)*M_.params(132)+M_.params(125)*M_.params(133))*M_.params(86)/(M_.params(86)-1);
Yh_Lh = M_.params( 136 );
M_.params( 137 ) = M_.params(135)/M_.params(132);
Gh_Kh = M_.params( 137 );
M_.params( 138 ) = M_.params(136)/M_.params(134);
Ah = M_.params( 138 );
M_.params( 139 ) = (1+M_.params(111))*(1+M_.params(113))-(1-M_.params(88));
Id_Kh = M_.params( 139 );
M_.params( 140 ) = M_.params(132)*M_.params(139)*(1-M_.params(98)-(1-M_.params(96)-M_.params(97))*(1-M_.params(100))*(M_.params(120)-M_.params(122)))/(M_.params(136)*M_.params(119)-M_.params(125)*M_.params(133)+M_.params(132)*M_.params(139)*(M_.params(120)-M_.params(122))*(M_.params(100)-M_.params(101)));
I_Y = M_.params( 140 );
M_.params( 141 ) = 1-M_.params(96)-M_.params(97)-M_.params(140);
C_Y = M_.params( 141 );
M_.params( 142 ) = (1-M_.params(100))*M_.params(141)*(1-M_.params(85))+M_.params(140)*(1-M_.params(101));
Mf_Y = M_.params( 142 );
M_.params( 143 ) = 1-M_.params(98)-(M_.params(120)-M_.params(122))*M_.params(142);
VAh_Y = M_.params( 143 );
M_.params( 144 ) = (M_.params(136)*M_.params(119)-M_.params(125)*M_.params(133))/M_.params(143);
Y_Lh = M_.params( 144 );
M_.params( 145 ) = M_.params(136)/M_.params(144);
Yh_Y = M_.params( 145 );
M_.params( 146 ) = M_.params(122)*M_.params(142)+M_.params(125)*(M_.params(133)/M_.params(144)+M_.params(141)*M_.params(85));
M_Y = M_.params( 146 );
M_.params( 147 ) = M_.params(96)+M_.params(146);
X_Y = M_.params( 147 );
M_.params( 148 ) = M_.params(147)-M_.params(98);
YhF_Y = M_.params( 148 );
M_.params( 149 ) = M_.params(125)*(M_.params(133)/M_.params(144)+M_.params(141)*M_.params(85))/M_.params(146);
Mo_M = M_.params( 149 );
M_.params( 150 ) = M_.params(98)/M_.params(147);
Ys_X = M_.params( 150 );
M_.params( 151 ) = 0.01;
BalG_Y = M_.params( 151 );
M_.params( 152 ) = 0.092;
Tau_Y = M_.params( 152 );
M_.params( 153 ) = (M_.params(97)-M_.params(152)-M_.params(98)*M_.params(93)+M_.params(151))*(1+M_.params(113))*(1+M_.params(111))*(1+M_.params(112))/(1-1/((1+M_.params(118))*M_.params(129)));
bG_Y = M_.params( 153 );
thispath = cd;                                                           
cd('..');                                                                
load policy_param.mat;                                                   
for i=1:33                                                               
deep_parameter_name = M_.param_names(i,:);                           
eval(['M_.params(i)  = ' deep_parameter_name ' ;'])                  
end                                                                      
cd(thispath);                                                            
M_.params( 34 ) = 1/M_.params(97);
coffispol = M_.params( 34 );
%
% SHOCKS instructions
%
make_ex_;
M_.exo_det_length = 0;
M_.Sigma_e(13, 13) = 0;
M_.Sigma_e(1, 1) = (M_.params(70))^2;
M_.Sigma_e(2, 2) = (M_.params(71))^2;
M_.Sigma_e(3, 3) = (M_.params(103))^2;
M_.Sigma_e(4, 4) = (M_.params(72))^2;
M_.Sigma_e(5, 5) = (M_.params(73))^2;
M_.Sigma_e(6, 6) = (M_.params(74))^2;
M_.Sigma_e(7, 7) = (M_.params(76))^2;
M_.Sigma_e(8, 8) = (M_.params(77))^2;
M_.Sigma_e(9, 9) = (M_.params(79))^2;
M_.Sigma_e(10, 10) = (M_.params(80))^2;
M_.Sigma_e(11, 11) = (M_.params(105))^2;
M_.Sigma_e(12, 12) = (M_.params(81))^2;
M_.Sigma_e(14, 14) = (M_.params(78))^2;
save('CL_MS07_results.mat', 'oo_', 'M_', 'options_');
if exist('estim_params_', 'var') == 1
  save('CL_MS07_results.mat', 'estim_params_', '-append');
end
if exist('bayestopt_', 'var') == 1
  save('CL_MS07_results.mat', 'bayestopt_', '-append');
end
if exist('dataset_', 'var') == 1
  save('CL_MS07_results.mat', 'dataset_', '-append');
end
if exist('estimation_info', 'var') == 1
  save('CL_MS07_results.mat', 'estimation_info', '-append');
end


disp(['Total computing time : ' dynsec2hms(toc) ]);
if ~isempty(lastwarn)
  disp('Note: warning(s) encountered in MATLAB/Octave code')
end
diary off
