%
% Status : main Dynare file
%
% Warning : this file is generated automatically by Dynare
%           from model file (.mod)

if isoctave || matlab_ver_less_than('8.6')
    clear all
else
    clearvars -global
    clear_persistent_variables(fileparts(which('dynare')), false)
end
tic0 = tic;
% Save empty dates and dseries objects in memory.
dates('initialize');
dseries('initialize');
% Define global variables.
global M_ options_ oo_ estim_params_ bayestopt_ dataset_ dataset_info estimation_info ys0_ ex0_
options_ = [];
M_.fname = 'NK_ET14';
M_.dynare_version = '4.5.4';
oo_.dynare_version = '4.5.4';
options_.dynare_version = '4.5.4';
%
% Some global variables initialization
%
global_initialization;
diary off;
diary('NK_ET14.log');
M_.exo_names = 'epsA';
M_.exo_names_tex = 'epsA';
M_.exo_names_long = 'epsA';
M_.exo_names = char(M_.exo_names, 'epsthet');
M_.exo_names_tex = char(M_.exo_names_tex, 'epsthet');
M_.exo_names_long = char(M_.exo_names_long, 'epsthet');
M_.exo_names = char(M_.exo_names, 'epsksi');
M_.exo_names_tex = char(M_.exo_names_tex, 'epsksi');
M_.exo_names_long = char(M_.exo_names_long, 'epsksi');
M_.exo_names = char(M_.exo_names, 'epsC');
M_.exo_names_tex = char(M_.exo_names_tex, 'epsC');
M_.exo_names_long = char(M_.exo_names_long, 'epsC');
M_.exo_names = char(M_.exo_names, 'epsL');
M_.exo_names_tex = char(M_.exo_names_tex, 'epsL');
M_.exo_names_long = char(M_.exo_names_long, 'epsL');
M_.exo_names = char(M_.exo_names, 'interest_');
M_.exo_names_tex = char(M_.exo_names_tex, 'interest\_');
M_.exo_names_long = char(M_.exo_names_long, 'interest_');
M_.exo_names = char(M_.exo_names, 'fiscal_');
M_.exo_names_tex = char(M_.exo_names_tex, 'fiscal\_');
M_.exo_names_long = char(M_.exo_names_long, 'fiscal_');
M_.endo_names = 'Y';
M_.endo_names_tex = 'Y';
M_.endo_names_long = 'Y';
M_.endo_names = char(M_.endo_names, 'C');
M_.endo_names_tex = char(M_.endo_names_tex, 'C');
M_.endo_names_long = char(M_.endo_names_long, 'C');
M_.endo_names = char(M_.endo_names, 's');
M_.endo_names_tex = char(M_.endo_names_tex, 's');
M_.endo_names_long = char(M_.endo_names_long, 's');
M_.endo_names = char(M_.endo_names, 'Ps');
M_.endo_names_tex = char(M_.endo_names_tex, 'Ps');
M_.endo_names_long = char(M_.endo_names_long, 'Ps');
M_.endo_names = char(M_.endo_names, 'Pss');
M_.endo_names_tex = char(M_.endo_names_tex, 'Pss');
M_.endo_names_long = char(M_.endo_names_long, 'Pss');
M_.endo_names = char(M_.endo_names, 'L');
M_.endo_names_tex = char(M_.endo_names_tex, 'L');
M_.endo_names_long = char(M_.endo_names_long, 'L');
M_.endo_names = char(M_.endo_names, 'w');
M_.endo_names_tex = char(M_.endo_names_tex, 'w');
M_.endo_names_long = char(M_.endo_names_long, 'w');
M_.endo_names = char(M_.endo_names, 'Pi');
M_.endo_names_tex = char(M_.endo_names_tex, 'Pi');
M_.endo_names_long = char(M_.endo_names_long, 'Pi');
M_.endo_names = char(M_.endo_names, 'F');
M_.endo_names_tex = char(M_.endo_names_tex, 'F');
M_.endo_names_long = char(M_.endo_names_long, 'F');
M_.endo_names = char(M_.endo_names, 'K');
M_.endo_names_tex = char(M_.endo_names_tex, 'K');
M_.endo_names_long = char(M_.endo_names_long, 'K');
M_.endo_names = char(M_.endo_names, 'PQ');
M_.endo_names_tex = char(M_.endo_names_tex, 'PQ');
M_.endo_names_long = char(M_.endo_names_long, 'PQ');
M_.endo_names = char(M_.endo_names, 'PB');
M_.endo_names_tex = char(M_.endo_names_tex, 'PB');
M_.endo_names_long = char(M_.endo_names_long, 'PB');
M_.endo_names = char(M_.endo_names, 'b');
M_.endo_names_tex = char(M_.endo_names_tex, 'b');
M_.endo_names_long = char(M_.endo_names_long, 'b');
M_.endo_names = char(M_.endo_names, 'q');
M_.endo_names_tex = char(M_.endo_names_tex, 'q');
M_.endo_names_long = char(M_.endo_names_long, 'q');
M_.endo_names = char(M_.endo_names, 'qCB');
M_.endo_names_tex = char(M_.endo_names_tex, 'qCB');
M_.endo_names_long = char(M_.endo_names_long, 'qCB');
M_.endo_names = char(M_.endo_names, 'qbar');
M_.endo_names_tex = char(M_.endo_names_tex, 'qbar');
M_.endo_names_long = char(M_.endo_names_long, 'qbar');
M_.endo_names = char(M_.endo_names, 'i');
M_.endo_names_tex = char(M_.endo_names_tex, 'i');
M_.endo_names_long = char(M_.endo_names_long, 'i');
M_.endo_names = char(M_.endo_names, 'iQ');
M_.endo_names_tex = char(M_.endo_names_tex, 'iQ');
M_.endo_names_long = char(M_.endo_names_long, 'iQ');
M_.endo_names = char(M_.endo_names, 'D');
M_.endo_names_tex = char(M_.endo_names_tex, 'D');
M_.endo_names_long = char(M_.endo_names_long, 'D');
M_.endo_names = char(M_.endo_names, 'A');
M_.endo_names_tex = char(M_.endo_names_tex, 'A');
M_.endo_names_long = char(M_.endo_names_long, 'A');
M_.endo_names = char(M_.endo_names, 'G');
M_.endo_names_tex = char(M_.endo_names_tex, 'G');
M_.endo_names_long = char(M_.endo_names_long, 'G');
M_.endo_names = char(M_.endo_names, 'theta');
M_.endo_names_tex = char(M_.endo_names_tex, 'theta');
M_.endo_names_long = char(M_.endo_names_long, 'theta');
M_.endo_names = char(M_.endo_names, 'ksi');
M_.endo_names_tex = char(M_.endo_names_tex, 'ksi');
M_.endo_names_long = char(M_.endo_names_long, 'ksi');
M_.endo_names = char(M_.endo_names, 'ChiC');
M_.endo_names_tex = char(M_.endo_names_tex, 'ChiC');
M_.endo_names_long = char(M_.endo_names_long, 'ChiC');
M_.endo_names = char(M_.endo_names, 'ChiL');
M_.endo_names_tex = char(M_.endo_names_tex, 'ChiL');
M_.endo_names_long = char(M_.endo_names_long, 'ChiL');
M_.endo_names = char(M_.endo_names, 'epsG');
M_.endo_names_tex = char(M_.endo_names_tex, 'epsG');
M_.endo_names_long = char(M_.endo_names_long, 'epsG');
M_.endo_names = char(M_.endo_names, 'Yf');
M_.endo_names_tex = char(M_.endo_names_tex, 'Yf');
M_.endo_names_long = char(M_.endo_names_long, 'Yf');
M_.endo_names = char(M_.endo_names, 'Gf');
M_.endo_names_tex = char(M_.endo_names_tex, 'Gf');
M_.endo_names_long = char(M_.endo_names_long, 'Gf');
M_.endo_names = char(M_.endo_names, 'interest');
M_.endo_names_tex = char(M_.endo_names_tex, 'interest');
M_.endo_names_long = char(M_.endo_names_long, 'interest');
M_.endo_names = char(M_.endo_names, 'inflation');
M_.endo_names_tex = char(M_.endo_names_tex, 'inflation');
M_.endo_names_long = char(M_.endo_names_long, 'inflation');
M_.endo_names = char(M_.endo_names, 'inflationq');
M_.endo_names_tex = char(M_.endo_names_tex, 'inflationq');
M_.endo_names_long = char(M_.endo_names_long, 'inflationq');
M_.endo_names = char(M_.endo_names, 'outputgap');
M_.endo_names_tex = char(M_.endo_names_tex, 'outputgap');
M_.endo_names_long = char(M_.endo_names_long, 'outputgap');
M_.endo_names = char(M_.endo_names, 'output');
M_.endo_names_tex = char(M_.endo_names_tex, 'output');
M_.endo_names_long = char(M_.endo_names_long, 'output');
M_.endo_names = char(M_.endo_names, 'fispol');
M_.endo_names_tex = char(M_.endo_names_tex, 'fispol');
M_.endo_names_long = char(M_.endo_names_long, 'fispol');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_94');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_94');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_94');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_98');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_98');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_98');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_102');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_102');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_102');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_129');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_129');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_129');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_133');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_133');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_133');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_137');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_137');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_137');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_164');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_164');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_164');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_168');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_168');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_168');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_172');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_172');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_172');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_7_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_7\_1');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_7_1');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_7_2');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_7\_2');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_7_2');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_32_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_32\_1');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_32_1');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_32_2');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_32\_2');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_32_2');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_32_3');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_32\_3');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_32_3');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_31_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_31\_1');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_31_1');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_31_2');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_31\_2');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_31_2');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_31_3');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_31\_3');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_31_3');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_28_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_28\_1');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_28_1');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_28_2');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_28\_2');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_28_2');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_28_3');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_28\_3');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_28_3');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_30_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_30\_1');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_30_1');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_30_2');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_30\_2');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_30_2');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_30_3');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_30\_3');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_30_3');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_13_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_13\_1');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_13_1');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_13_2');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_13\_2');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_13_2');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_13_3');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_13\_3');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_13_3');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_13_4');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_13\_4');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_13_4');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_7_3');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_7\_3');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_7_3');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_13_5');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_13\_5');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_13_5');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_7_4');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_7\_4');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_7_4');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_13_6');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_13\_6');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_13_6');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_7_5');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_7\_5');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_7_5');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_13_7');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_13\_7');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_13_7');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_7_6');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_7\_6');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_7_6');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_13_8');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_13\_8');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_13_8');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_7_7');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_7\_7');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_7_7');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_13_9');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_13\_9');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_13_9');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_7_8');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_7\_8');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_7_8');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_13_10');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_13\_10');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_13_10');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_7_9');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_7\_9');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_7_9');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_13_11');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_13\_11');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_13_11');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_7_10');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_7\_10');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_7_10');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_13_12');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_13\_12');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_13_12');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_7_11');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_7\_11');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_7_11');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_13_13');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_13\_13');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_13_13');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_7_12');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_7\_12');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_7_12');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_13_14');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_13\_14');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_13_14');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_7_13');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_7\_13');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_7_13');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_13_15');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_13\_15');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_13_15');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_7_14');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_7\_14');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_7_14');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_13_16');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_13\_16');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_13_16');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_7_15');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_7\_15');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_7_15');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_13_17');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_13\_17');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_13_17');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_7_16');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_7\_16');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_7_16');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_13_18');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_13\_18');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_13_18');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_7_17');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_7\_17');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_7_17');
M_.endo_partitions = struct();
M_.param_names = 'cofintintb1';
M_.param_names_tex = 'cofintintb1';
M_.param_names_long = 'cofintintb1';
M_.param_names = char(M_.param_names, 'cofintintb2');
M_.param_names_tex = char(M_.param_names_tex, 'cofintintb2');
M_.param_names_long = char(M_.param_names_long, 'cofintintb2');
M_.param_names = char(M_.param_names, 'cofintintb3');
M_.param_names_tex = char(M_.param_names_tex, 'cofintintb3');
M_.param_names_long = char(M_.param_names_long, 'cofintintb3');
M_.param_names = char(M_.param_names, 'cofintintb4');
M_.param_names_tex = char(M_.param_names_tex, 'cofintintb4');
M_.param_names_long = char(M_.param_names_long, 'cofintintb4');
M_.param_names = char(M_.param_names, 'cofintinf0');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinf0');
M_.param_names_long = char(M_.param_names_long, 'cofintinf0');
M_.param_names = char(M_.param_names, 'cofintinfb1');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinfb1');
M_.param_names_long = char(M_.param_names_long, 'cofintinfb1');
M_.param_names = char(M_.param_names, 'cofintinfb2');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinfb2');
M_.param_names_long = char(M_.param_names_long, 'cofintinfb2');
M_.param_names = char(M_.param_names, 'cofintinfb3');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinfb3');
M_.param_names_long = char(M_.param_names_long, 'cofintinfb3');
M_.param_names = char(M_.param_names, 'cofintinfb4');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinfb4');
M_.param_names_long = char(M_.param_names_long, 'cofintinfb4');
M_.param_names = char(M_.param_names, 'cofintinff1');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinff1');
M_.param_names_long = char(M_.param_names_long, 'cofintinff1');
M_.param_names = char(M_.param_names, 'cofintinff2');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinff2');
M_.param_names_long = char(M_.param_names_long, 'cofintinff2');
M_.param_names = char(M_.param_names, 'cofintinff3');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinff3');
M_.param_names_long = char(M_.param_names_long, 'cofintinff3');
M_.param_names = char(M_.param_names, 'cofintinff4');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinff4');
M_.param_names_long = char(M_.param_names_long, 'cofintinff4');
M_.param_names = char(M_.param_names, 'cofintout');
M_.param_names_tex = char(M_.param_names_tex, 'cofintout');
M_.param_names_long = char(M_.param_names_long, 'cofintout');
M_.param_names = char(M_.param_names, 'cofintoutb1');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutb1');
M_.param_names_long = char(M_.param_names_long, 'cofintoutb1');
M_.param_names = char(M_.param_names, 'cofintoutb2');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutb2');
M_.param_names_long = char(M_.param_names_long, 'cofintoutb2');
M_.param_names = char(M_.param_names, 'cofintoutb3');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutb3');
M_.param_names_long = char(M_.param_names_long, 'cofintoutb3');
M_.param_names = char(M_.param_names, 'cofintoutb4');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutb4');
M_.param_names_long = char(M_.param_names_long, 'cofintoutb4');
M_.param_names = char(M_.param_names, 'cofintoutf1');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutf1');
M_.param_names_long = char(M_.param_names_long, 'cofintoutf1');
M_.param_names = char(M_.param_names, 'cofintoutf2');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutf2');
M_.param_names_long = char(M_.param_names_long, 'cofintoutf2');
M_.param_names = char(M_.param_names, 'cofintoutf3');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutf3');
M_.param_names_long = char(M_.param_names_long, 'cofintoutf3');
M_.param_names = char(M_.param_names, 'cofintoutf4');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutf4');
M_.param_names_long = char(M_.param_names_long, 'cofintoutf4');
M_.param_names = char(M_.param_names, 'cofintoutp');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutp');
M_.param_names_long = char(M_.param_names_long, 'cofintoutp');
M_.param_names = char(M_.param_names, 'cofintoutpb1');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpb1');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpb1');
M_.param_names = char(M_.param_names, 'cofintoutpb2');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpb2');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpb2');
M_.param_names = char(M_.param_names, 'cofintoutpb3');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpb3');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpb3');
M_.param_names = char(M_.param_names, 'cofintoutpb4');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpb4');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpb4');
M_.param_names = char(M_.param_names, 'cofintoutpf1');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpf1');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpf1');
M_.param_names = char(M_.param_names, 'cofintoutpf2');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpf2');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpf2');
M_.param_names = char(M_.param_names, 'cofintoutpf3');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpf3');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpf3');
M_.param_names = char(M_.param_names, 'cofintoutpf4');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpf4');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpf4');
M_.param_names = char(M_.param_names, 'std_r_');
M_.param_names_tex = char(M_.param_names_tex, 'std\_r\_');
M_.param_names_long = char(M_.param_names_long, 'std_r_');
M_.param_names = char(M_.param_names, 'std_r_quart');
M_.param_names_tex = char(M_.param_names_tex, 'std\_r\_quart');
M_.param_names_long = char(M_.param_names_long, 'std_r_quart');
M_.param_names = char(M_.param_names, 'coffispol');
M_.param_names_tex = char(M_.param_names_tex, 'coffispol');
M_.param_names_long = char(M_.param_names_long, 'coffispol');
M_.param_names = char(M_.param_names, 'betta');
M_.param_names_tex = char(M_.param_names_tex, 'betta');
M_.param_names_long = char(M_.param_names_long, 'betta');
M_.param_names = char(M_.param_names, 'delta');
M_.param_names_tex = char(M_.param_names_tex, 'delta');
M_.param_names_long = char(M_.param_names_long, 'delta');
M_.param_names = char(M_.param_names, 'psii');
M_.param_names_tex = char(M_.param_names_tex, 'psii');
M_.param_names_long = char(M_.param_names_long, 'psii');
M_.param_names = char(M_.param_names, 'SStheta');
M_.param_names_tex = char(M_.param_names_tex, 'SStheta');
M_.param_names_long = char(M_.param_names_long, 'SStheta');
M_.param_names = char(M_.param_names, 'phi');
M_.param_names_tex = char(M_.param_names_tex, 'phi');
M_.param_names_long = char(M_.param_names_long, 'phi');
M_.param_names = char(M_.param_names, 'alfa');
M_.param_names_tex = char(M_.param_names_tex, 'alfa');
M_.param_names_long = char(M_.param_names_long, 'alfa');
M_.param_names = char(M_.param_names, 'alfaf');
M_.param_names_tex = char(M_.param_names_tex, 'alfaf');
M_.param_names_long = char(M_.param_names_long, 'alfaf');
M_.param_names = char(M_.param_names, 'SSPi');
M_.param_names_tex = char(M_.param_names_tex, 'SSPi');
M_.param_names_long = char(M_.param_names_long, 'SSPi');
M_.param_names = char(M_.param_names, 'tau');
M_.param_names_tex = char(M_.param_names_tex, 'tau');
M_.param_names_long = char(M_.param_names_long, 'tau');
M_.param_names = char(M_.param_names, 'gbar');
M_.param_names_tex = char(M_.param_names_tex, 'gbar');
M_.param_names_long = char(M_.param_names_long, 'gbar');
M_.param_names = char(M_.param_names, 'tpi');
M_.param_names_tex = char(M_.param_names_tex, 'tpi');
M_.param_names_long = char(M_.param_names_long, 'tpi');
M_.param_names = char(M_.param_names, 'f');
M_.param_names_tex = char(M_.param_names_tex, 'f');
M_.param_names_long = char(M_.param_names_long, 'f');
M_.param_names = char(M_.param_names, 'a1');
M_.param_names_tex = char(M_.param_names_tex, 'a1');
M_.param_names_long = char(M_.param_names_long, 'a1');
M_.param_names = char(M_.param_names, 'a2');
M_.param_names_tex = char(M_.param_names_tex, 'a2');
M_.param_names_long = char(M_.param_names_long, 'a2');
M_.param_names = char(M_.param_names, 'gB');
M_.param_names_tex = char(M_.param_names_tex, 'gB');
M_.param_names_long = char(M_.param_names_long, 'gB');
M_.param_names = char(M_.param_names, 'gQ');
M_.param_names_tex = char(M_.param_names_tex, 'gQ');
M_.param_names_long = char(M_.param_names_long, 'gQ');
M_.param_names = char(M_.param_names, 'rhoksi');
M_.param_names_tex = char(M_.param_names_tex, 'rhoksi');
M_.param_names_long = char(M_.param_names_long, 'rhoksi');
M_.param_names = char(M_.param_names, 'rhoC');
M_.param_names_tex = char(M_.param_names_tex, 'rhoC');
M_.param_names_long = char(M_.param_names_long, 'rhoC');
M_.param_names = char(M_.param_names, 'rhoL');
M_.param_names_tex = char(M_.param_names_tex, 'rhoL');
M_.param_names_long = char(M_.param_names_long, 'rhoL');
M_.param_names = char(M_.param_names, 'rhoG');
M_.param_names_tex = char(M_.param_names_tex, 'rhoG');
M_.param_names_long = char(M_.param_names_long, 'rhoG');
M_.param_names = char(M_.param_names, 'rhoA');
M_.param_names_tex = char(M_.param_names_tex, 'rhoA');
M_.param_names_long = char(M_.param_names_long, 'rhoA');
M_.param_names = char(M_.param_names, 'rhotheta');
M_.param_names_tex = char(M_.param_names_tex, 'rhotheta');
M_.param_names_long = char(M_.param_names_long, 'rhotheta');
M_.param_names = char(M_.param_names, 'gampi');
M_.param_names_tex = char(M_.param_names_tex, 'gampi');
M_.param_names_long = char(M_.param_names_long, 'gampi');
M_.param_names = char(M_.param_names, 'gamY');
M_.param_names_tex = char(M_.param_names_tex, 'gamY');
M_.param_names_long = char(M_.param_names_long, 'gamY');
M_.param_names = char(M_.param_names, 'gampiQE');
M_.param_names_tex = char(M_.param_names_tex, 'gampiQE');
M_.param_names_long = char(M_.param_names_long, 'gampiQE');
M_.param_names = char(M_.param_names, 'gamYQE');
M_.param_names_tex = char(M_.param_names_tex, 'gamYQE');
M_.param_names_long = char(M_.param_names_long, 'gamYQE');
M_.param_names = char(M_.param_names, 'vepsksi');
M_.param_names_tex = char(M_.param_names_tex, 'vepsksi');
M_.param_names_long = char(M_.param_names_long, 'vepsksi');
M_.param_names = char(M_.param_names, 'vepsC');
M_.param_names_tex = char(M_.param_names_tex, 'vepsC');
M_.param_names_long = char(M_.param_names_long, 'vepsC');
M_.param_names = char(M_.param_names, 'vepsL');
M_.param_names_tex = char(M_.param_names_tex, 'vepsL');
M_.param_names_long = char(M_.param_names_long, 'vepsL');
M_.param_names = char(M_.param_names, 'vepsG');
M_.param_names_tex = char(M_.param_names_tex, 'vepsG');
M_.param_names_long = char(M_.param_names_long, 'vepsG');
M_.param_names = char(M_.param_names, 'vepsA');
M_.param_names_tex = char(M_.param_names_tex, 'vepsA');
M_.param_names_long = char(M_.param_names_long, 'vepsA');
M_.param_names = char(M_.param_names, 'vepsthet');
M_.param_names_tex = char(M_.param_names_tex, 'vepsthet');
M_.param_names_long = char(M_.param_names_long, 'vepsthet');
M_.param_names = char(M_.param_names, 'vfiscal_');
M_.param_names_tex = char(M_.param_names_tex, 'vfiscal\_');
M_.param_names_long = char(M_.param_names_long, 'vfiscal_');
M_.param_partitions = struct();
M_.exo_det_nbr = 0;
M_.exo_nbr = 7;
M_.endo_nbr = 90;
M_.param_nbr = 67;
M_.orig_endo_nbr = 34;
M_.aux_vars(1).endo_index = 35;
M_.aux_vars(1).type = 0;
M_.aux_vars(2).endo_index = 36;
M_.aux_vars(2).type = 0;
M_.aux_vars(3).endo_index = 37;
M_.aux_vars(3).type = 0;
M_.aux_vars(4).endo_index = 38;
M_.aux_vars(4).type = 0;
M_.aux_vars(5).endo_index = 39;
M_.aux_vars(5).type = 0;
M_.aux_vars(6).endo_index = 40;
M_.aux_vars(6).type = 0;
M_.aux_vars(7).endo_index = 41;
M_.aux_vars(7).type = 0;
M_.aux_vars(8).endo_index = 42;
M_.aux_vars(8).type = 0;
M_.aux_vars(9).endo_index = 43;
M_.aux_vars(9).type = 0;
M_.aux_vars(10).endo_index = 44;
M_.aux_vars(10).type = 1;
M_.aux_vars(10).orig_index = 8;
M_.aux_vars(10).orig_lead_lag = -1;
M_.aux_vars(11).endo_index = 45;
M_.aux_vars(11).type = 1;
M_.aux_vars(11).orig_index = 8;
M_.aux_vars(11).orig_lead_lag = -2;
M_.aux_vars(12).endo_index = 46;
M_.aux_vars(12).type = 1;
M_.aux_vars(12).orig_index = 33;
M_.aux_vars(12).orig_lead_lag = -1;
M_.aux_vars(13).endo_index = 47;
M_.aux_vars(13).type = 1;
M_.aux_vars(13).orig_index = 33;
M_.aux_vars(13).orig_lead_lag = -2;
M_.aux_vars(14).endo_index = 48;
M_.aux_vars(14).type = 1;
M_.aux_vars(14).orig_index = 33;
M_.aux_vars(14).orig_lead_lag = -3;
M_.aux_vars(15).endo_index = 49;
M_.aux_vars(15).type = 1;
M_.aux_vars(15).orig_index = 32;
M_.aux_vars(15).orig_lead_lag = -1;
M_.aux_vars(16).endo_index = 50;
M_.aux_vars(16).type = 1;
M_.aux_vars(16).orig_index = 32;
M_.aux_vars(16).orig_lead_lag = -2;
M_.aux_vars(17).endo_index = 51;
M_.aux_vars(17).type = 1;
M_.aux_vars(17).orig_index = 32;
M_.aux_vars(17).orig_lead_lag = -3;
M_.aux_vars(18).endo_index = 52;
M_.aux_vars(18).type = 1;
M_.aux_vars(18).orig_index = 29;
M_.aux_vars(18).orig_lead_lag = -1;
M_.aux_vars(19).endo_index = 53;
M_.aux_vars(19).type = 1;
M_.aux_vars(19).orig_index = 29;
M_.aux_vars(19).orig_lead_lag = -2;
M_.aux_vars(20).endo_index = 54;
M_.aux_vars(20).type = 1;
M_.aux_vars(20).orig_index = 29;
M_.aux_vars(20).orig_lead_lag = -3;
M_.aux_vars(21).endo_index = 55;
M_.aux_vars(21).type = 1;
M_.aux_vars(21).orig_index = 31;
M_.aux_vars(21).orig_lead_lag = -1;
M_.aux_vars(22).endo_index = 56;
M_.aux_vars(22).type = 1;
M_.aux_vars(22).orig_index = 31;
M_.aux_vars(22).orig_lead_lag = -2;
M_.aux_vars(23).endo_index = 57;
M_.aux_vars(23).type = 1;
M_.aux_vars(23).orig_index = 31;
M_.aux_vars(23).orig_lead_lag = -3;
M_.aux_vars(24).endo_index = 58;
M_.aux_vars(24).type = 1;
M_.aux_vars(24).orig_index = 14;
M_.aux_vars(24).orig_lead_lag = -1;
M_.aux_vars(25).endo_index = 59;
M_.aux_vars(25).type = 1;
M_.aux_vars(25).orig_index = 14;
M_.aux_vars(25).orig_lead_lag = -2;
M_.aux_vars(26).endo_index = 60;
M_.aux_vars(26).type = 1;
M_.aux_vars(26).orig_index = 14;
M_.aux_vars(26).orig_lead_lag = -3;
M_.aux_vars(27).endo_index = 61;
M_.aux_vars(27).type = 1;
M_.aux_vars(27).orig_index = 14;
M_.aux_vars(27).orig_lead_lag = -4;
M_.aux_vars(28).endo_index = 62;
M_.aux_vars(28).type = 1;
M_.aux_vars(28).orig_index = 8;
M_.aux_vars(28).orig_lead_lag = -3;
M_.aux_vars(29).endo_index = 63;
M_.aux_vars(29).type = 1;
M_.aux_vars(29).orig_index = 14;
M_.aux_vars(29).orig_lead_lag = -5;
M_.aux_vars(30).endo_index = 64;
M_.aux_vars(30).type = 1;
M_.aux_vars(30).orig_index = 8;
M_.aux_vars(30).orig_lead_lag = -4;
M_.aux_vars(31).endo_index = 65;
M_.aux_vars(31).type = 1;
M_.aux_vars(31).orig_index = 14;
M_.aux_vars(31).orig_lead_lag = -6;
M_.aux_vars(32).endo_index = 66;
M_.aux_vars(32).type = 1;
M_.aux_vars(32).orig_index = 8;
M_.aux_vars(32).orig_lead_lag = -5;
M_.aux_vars(33).endo_index = 67;
M_.aux_vars(33).type = 1;
M_.aux_vars(33).orig_index = 14;
M_.aux_vars(33).orig_lead_lag = -7;
M_.aux_vars(34).endo_index = 68;
M_.aux_vars(34).type = 1;
M_.aux_vars(34).orig_index = 8;
M_.aux_vars(34).orig_lead_lag = -6;
M_.aux_vars(35).endo_index = 69;
M_.aux_vars(35).type = 1;
M_.aux_vars(35).orig_index = 14;
M_.aux_vars(35).orig_lead_lag = -8;
M_.aux_vars(36).endo_index = 70;
M_.aux_vars(36).type = 1;
M_.aux_vars(36).orig_index = 8;
M_.aux_vars(36).orig_lead_lag = -7;
M_.aux_vars(37).endo_index = 71;
M_.aux_vars(37).type = 1;
M_.aux_vars(37).orig_index = 14;
M_.aux_vars(37).orig_lead_lag = -9;
M_.aux_vars(38).endo_index = 72;
M_.aux_vars(38).type = 1;
M_.aux_vars(38).orig_index = 8;
M_.aux_vars(38).orig_lead_lag = -8;
M_.aux_vars(39).endo_index = 73;
M_.aux_vars(39).type = 1;
M_.aux_vars(39).orig_index = 14;
M_.aux_vars(39).orig_lead_lag = -10;
M_.aux_vars(40).endo_index = 74;
M_.aux_vars(40).type = 1;
M_.aux_vars(40).orig_index = 8;
M_.aux_vars(40).orig_lead_lag = -9;
M_.aux_vars(41).endo_index = 75;
M_.aux_vars(41).type = 1;
M_.aux_vars(41).orig_index = 14;
M_.aux_vars(41).orig_lead_lag = -11;
M_.aux_vars(42).endo_index = 76;
M_.aux_vars(42).type = 1;
M_.aux_vars(42).orig_index = 8;
M_.aux_vars(42).orig_lead_lag = -10;
M_.aux_vars(43).endo_index = 77;
M_.aux_vars(43).type = 1;
M_.aux_vars(43).orig_index = 14;
M_.aux_vars(43).orig_lead_lag = -12;
M_.aux_vars(44).endo_index = 78;
M_.aux_vars(44).type = 1;
M_.aux_vars(44).orig_index = 8;
M_.aux_vars(44).orig_lead_lag = -11;
M_.aux_vars(45).endo_index = 79;
M_.aux_vars(45).type = 1;
M_.aux_vars(45).orig_index = 14;
M_.aux_vars(45).orig_lead_lag = -13;
M_.aux_vars(46).endo_index = 80;
M_.aux_vars(46).type = 1;
M_.aux_vars(46).orig_index = 8;
M_.aux_vars(46).orig_lead_lag = -12;
M_.aux_vars(47).endo_index = 81;
M_.aux_vars(47).type = 1;
M_.aux_vars(47).orig_index = 14;
M_.aux_vars(47).orig_lead_lag = -14;
M_.aux_vars(48).endo_index = 82;
M_.aux_vars(48).type = 1;
M_.aux_vars(48).orig_index = 8;
M_.aux_vars(48).orig_lead_lag = -13;
M_.aux_vars(49).endo_index = 83;
M_.aux_vars(49).type = 1;
M_.aux_vars(49).orig_index = 14;
M_.aux_vars(49).orig_lead_lag = -15;
M_.aux_vars(50).endo_index = 84;
M_.aux_vars(50).type = 1;
M_.aux_vars(50).orig_index = 8;
M_.aux_vars(50).orig_lead_lag = -14;
M_.aux_vars(51).endo_index = 85;
M_.aux_vars(51).type = 1;
M_.aux_vars(51).orig_index = 14;
M_.aux_vars(51).orig_lead_lag = -16;
M_.aux_vars(52).endo_index = 86;
M_.aux_vars(52).type = 1;
M_.aux_vars(52).orig_index = 8;
M_.aux_vars(52).orig_lead_lag = -15;
M_.aux_vars(53).endo_index = 87;
M_.aux_vars(53).type = 1;
M_.aux_vars(53).orig_index = 14;
M_.aux_vars(53).orig_lead_lag = -17;
M_.aux_vars(54).endo_index = 88;
M_.aux_vars(54).type = 1;
M_.aux_vars(54).orig_index = 8;
M_.aux_vars(54).orig_lead_lag = -16;
M_.aux_vars(55).endo_index = 89;
M_.aux_vars(55).type = 1;
M_.aux_vars(55).orig_index = 14;
M_.aux_vars(55).orig_lead_lag = -18;
M_.aux_vars(56).endo_index = 90;
M_.aux_vars(56).type = 1;
M_.aux_vars(56).orig_index = 8;
M_.aux_vars(56).orig_lead_lag = -17;
M_.Sigma_e = zeros(7, 7);
M_.Correlation_matrix = eye(7, 7);
M_.H = 0;
M_.Correlation_matrix_ME = 1;
M_.sigma_e_is_diagonal = 1;
M_.det_shocks = [];
options_.block=0;
options_.bytecode=0;
options_.use_dll=0;
M_.hessian_eq_zero = 0;
erase_compiled_function('NK_ET14_static');
erase_compiled_function('NK_ET14_dynamic');
M_.orig_eq_nbr = 34;
M_.eq_nbr = 90;
M_.ramsey_eq_nbr = 0;
M_.set_auxiliary_variables = exist(['./' M_.fname '_set_auxiliary_variables.m'], 'file') == 2;
M_.lead_lag_incidence = [
 0 63 0;
 0 64 153;
 1 65 0;
 0 66 0;
 0 67 0;
 0 68 0;
 0 69 0;
 2 70 154;
 0 71 155;
 0 72 156;
 0 73 0;
 0 74 0;
 0 75 0;
 3 76 0;
 0 77 0;
 0 78 0;
 0 79 0;
 0 80 0;
 4 81 0;
 5 82 0;
 6 83 0;
 7 84 0;
 8 85 0;
 9 86 157;
 10 87 0;
 0 88 0;
 0 89 0;
 11 90 0;
 12 91 0;
 0 92 0;
 13 93 158;
 14 94 159;
 15 95 160;
 0 96 0;
 0 97 161;
 0 98 162;
 0 99 163;
 0 100 164;
 0 101 165;
 0 102 166;
 0 103 167;
 0 104 168;
 0 105 169;
 16 106 0;
 17 107 0;
 18 108 0;
 19 109 0;
 20 110 0;
 21 111 0;
 22 112 0;
 23 113 0;
 24 114 0;
 25 115 0;
 26 116 0;
 27 117 0;
 28 118 0;
 29 119 0;
 30 120 0;
 31 121 0;
 32 122 0;
 33 123 0;
 34 124 0;
 35 125 0;
 36 126 0;
 37 127 0;
 38 128 0;
 39 129 0;
 40 130 0;
 41 131 0;
 42 132 0;
 43 133 0;
 44 134 0;
 45 135 0;
 46 136 0;
 47 137 0;
 48 138 0;
 49 139 0;
 50 140 0;
 51 141 0;
 52 142 0;
 53 143 0;
 54 144 0;
 55 145 0;
 56 146 0;
 57 147 0;
 58 148 0;
 59 149 0;
 60 150 0;
 61 151 0;
 62 152 0;]';
M_.nstatic = 16;
M_.nfwrd   = 12;
M_.npred   = 57;
M_.nboth   = 5;
M_.nsfwrd   = 17;
M_.nspred   = 62;
M_.ndynamic   = 74;
M_.equations_tags = {
};
M_.static_and_dynamic_models_differ = 0;
M_.exo_names_orig_ord = [1:7];
M_.maximum_lag = 1;
M_.maximum_lead = 1;
M_.maximum_endo_lag = 1;
M_.maximum_endo_lead = 1;
oo_.steady_state = zeros(90, 1);
M_.maximum_exo_lag = 0;
M_.maximum_exo_lead = 0;
oo_.exo_steady_state = zeros(7, 1);
M_.params = NaN(67, 1);
M_.NNZDerivatives = [307; 1003; -1];
close all;
clc;
M_.params( 35 ) = 0.99;
betta = M_.params( 35 );
M_.params( 36 ) = 2;
delta = M_.params( 36 );
M_.params( 37 ) = 0.5;
psii = M_.params( 37 );
M_.params( 38 ) = 1.791759469228055;
SStheta = M_.params( 38 );
M_.params( 39 ) = 1.1;
phi = M_.params( 39 );
M_.params( 40 ) = 0.85;
alfa = M_.params( 40 );
M_.params( 41 ) = 0;
alfaf = M_.params( 41 );
M_.params( 42 ) = 0.004987541511038968;
SSPi = M_.params( 42 );
M_.params( 43 ) = 20;
tau = M_.params( 43 );
M_.params( 44 ) = 0.4;
gbar = M_.params( 44 );
M_.params( 45 ) = 0.5;
tpi = M_.params( 45 );
M_.params( 46 ) = 0.66;
f = M_.params( 46 );
M_.params( 47 ) = 0.95;
a1 = M_.params( 47 );
M_.params( 48 ) = 0;
a2 = M_.params( 48 );
M_.params( 49 ) = 10.21;
gB = M_.params( 49 );
M_.params( 50 ) = 0.59;
gQ = M_.params( 50 );
M_.params( 51 ) = 0.1;
rhoksi = M_.params( 51 );
M_.params( 52 ) = 0.1;
rhoC = M_.params( 52 );
M_.params( 53 ) = 0.7;
rhoL = M_.params( 53 );
M_.params( 54 ) = 0.1;
rhoG = M_.params( 54 );
M_.params( 55 ) = 0.7;
rhoA = M_.params( 55 );
M_.params( 56 ) = 0.95;
rhotheta = M_.params( 56 );
M_.params( 57 ) = 1.01;
gampi = M_.params( 57 );
M_.params( 58 ) = 0.3;
gamY = M_.params( 58 );
M_.params( 59 ) = 0;
gampiQE = M_.params( 59 );
M_.params( 60 ) = 60;
gamYQE = M_.params( 60 );
M_.params( 61 ) = 6.25e-06;
vepsksi = M_.params( 61 );
M_.params( 62 ) = 6.25e-06;
vepsC = M_.params( 62 );
M_.params( 63 ) = 6.25e-06;
vepsL = M_.params( 63 );
M_.params( 65 ) = 0.0001;
vepsA = M_.params( 65 );
M_.params( 66 ) = 0.0036;
vepsthet = M_.params( 66 );
M_.params( 67 ) = 2.5e-05;
vfiscal_ = M_.params( 67 );
thispath = pwd;
cd('..');
load policy_param.mat;
for i=1:33
deep_parameter_name = M_.param_names(i,:);
eval(['M_.params(i)  = ' deep_parameter_name ' ;'])
end
cd(thispath);
M_.params( 32 ) = 100;
std_r_ = M_.params( 32 );
M_.params( 34 ) = 1;
coffispol = M_.params( 34 );
%
% SHOCKS instructions
%
M_.exo_det_length = 0;
M_.Sigma_e(1, 1) = M_.params(65);
M_.Sigma_e(2, 2) = M_.params(66);
M_.Sigma_e(3, 3) = M_.params(61);
M_.Sigma_e(4, 4) = M_.params(62);
M_.Sigma_e(5, 5) = M_.params(63);
M_.Sigma_e(7, 7) = M_.params(67);
save('NK_ET14_results.mat', 'oo_', 'M_', 'options_');
if exist('estim_params_', 'var') == 1
  save('NK_ET14_results.mat', 'estim_params_', '-append');
end
if exist('bayestopt_', 'var') == 1
  save('NK_ET14_results.mat', 'bayestopt_', '-append');
end
if exist('dataset_', 'var') == 1
  save('NK_ET14_results.mat', 'dataset_', '-append');
end
if exist('estimation_info', 'var') == 1
  save('NK_ET14_results.mat', 'estimation_info', '-append');
end
if exist('dataset_info', 'var') == 1
  save('NK_ET14_results.mat', 'dataset_info', '-append');
end
if exist('oo_recursive_', 'var') == 1
  save('NK_ET14_results.mat', 'oo_recursive_', '-append');
end


disp(['Total computing time : ' dynsec2hms(toc(tic0)) ]);
if ~isempty(lastwarn)
  disp('Note: warning(s) encountered in MATLAB/Octave code')
end
diary off
