%
% Status : main Dynare file
%
% Warning : this file is generated automatically by Dynare
%           from model file (.mod)

if isoctave || matlab_ver_less_than('8.6')
    clear all
else
    clearvars -global
    clear_persistent_variables(fileparts(which('dynare')), false)
end
tic0 = tic;
% Save empty dates and dseries objects in memory.
dates('initialize');
dseries('initialize');
% Define global variables.
global M_ options_ oo_ estim_params_ bayestopt_ dataset_ dataset_info estimation_info ys0_ ex0_
options_ = [];
M_.fname = 'HK_FP13';
M_.dynare_version = '4.5.6';
oo_.dynare_version = '4.5.6';
options_.dynare_version = '4.5.6';
%
% Some global variables initialization
%
global_initialization;
diary off;
diary('HK_FP13.log');
M_.exo_names = 'epsa_c';
M_.exo_names_tex = 'epsa\_c';
M_.exo_names_long = 'epsa_c';
M_.exo_names = char(M_.exo_names, 'epsa_d');
M_.exo_names_tex = char(M_.exo_names_tex, 'epsa\_d');
M_.exo_names_long = char(M_.exo_names_long, 'epsa_d');
M_.exo_names = char(M_.exo_names, 'epsmu_c');
M_.exo_names_tex = char(M_.exo_names_tex, 'epsmu\_c');
M_.exo_names_long = char(M_.exo_names_long, 'epsmu_c');
M_.exo_names = char(M_.exo_names, 'epsmu_d');
M_.exo_names_tex = char(M_.exo_names_tex, 'epsmu\_d');
M_.exo_names_long = char(M_.exo_names_long, 'epsmu_d');
M_.exo_names = char(M_.exo_names, 'epsLTV');
M_.exo_names_tex = char(M_.exo_names_tex, 'epsLTV');
M_.exo_names_long = char(M_.exo_names_long, 'epsLTV');
M_.exo_names = char(M_.exo_names, 'epsd_b');
M_.exo_names_tex = char(M_.exo_names_tex, 'epsd\_b');
M_.exo_names_long = char(M_.exo_names_long, 'epsd_b');
M_.exo_names = char(M_.exo_names, 'epsd_s');
M_.exo_names_tex = char(M_.exo_names_tex, 'epsd\_s');
M_.exo_names_long = char(M_.exo_names_long, 'epsd_s');
M_.exo_names = char(M_.exo_names, 'epsc_ast');
M_.exo_names_tex = char(M_.exo_names_tex, 'epsc\_ast');
M_.exo_names_long = char(M_.exo_names_long, 'epsc_ast');
M_.exo_names = char(M_.exo_names, 'epsd_ast');
M_.exo_names_tex = char(M_.exo_names_tex, 'epsd\_ast');
M_.exo_names_long = char(M_.exo_names_long, 'epsd_ast');
M_.exo_names = char(M_.exo_names, 'epsd_stern');
M_.exo_names_tex = char(M_.exo_names_tex, 'epsd\_stern');
M_.exo_names_long = char(M_.exo_names_long, 'epsd_stern');
M_.exo_names = char(M_.exo_names, 'epsp_c_ast');
M_.exo_names_tex = char(M_.exo_names_tex, 'epsp\_c\_ast');
M_.exo_names_long = char(M_.exo_names_long, 'epsp_c_ast');
M_.exo_names = char(M_.exo_names, 'epsp_d_ast');
M_.exo_names_tex = char(M_.exo_names_tex, 'epsp\_d\_ast');
M_.exo_names_long = char(M_.exo_names_long, 'epsp_d_ast');
M_.exo_names = char(M_.exo_names, 'interest_');
M_.exo_names_tex = char(M_.exo_names_tex, 'interest\_');
M_.exo_names_long = char(M_.exo_names_long, 'interest_');
M_.exo_names = char(M_.exo_names, 'fiscal_');
M_.exo_names_tex = char(M_.exo_names_tex, 'fiscal\_');
M_.exo_names_long = char(M_.exo_names_long, 'fiscal_');
M_.endo_names = 'y';
M_.endo_names_tex = 'y';
M_.endo_names_long = 'y';
M_.endo_names = char(M_.endo_names, 'pi_d_h');
M_.endo_names_tex = char(M_.endo_names_tex, 'pi\_d\_h');
M_.endo_names_long = char(M_.endo_names_long, 'pi_d_h');
M_.endo_names = char(M_.endo_names, 'r');
M_.endo_names_tex = char(M_.endo_names_tex, 'r');
M_.endo_names_long = char(M_.endo_names_long, 'r');
M_.endo_names = char(M_.endo_names, 'pi_c');
M_.endo_names_tex = char(M_.endo_names_tex, 'pi\_c');
M_.endo_names_long = char(M_.endo_names_long, 'pi_c');
M_.endo_names = char(M_.endo_names, 'c');
M_.endo_names_tex = char(M_.endo_names_tex, 'c');
M_.endo_names_long = char(M_.endo_names_long, 'c');
M_.endo_names = char(M_.endo_names, 'n');
M_.endo_names_tex = char(M_.endo_names_tex, 'n');
M_.endo_names_long = char(M_.endo_names_long, 'n');
M_.endo_names = char(M_.endo_names, 'd');
M_.endo_names_tex = char(M_.endo_names_tex, 'd');
M_.endo_names_long = char(M_.endo_names_long, 'd');
M_.endo_names = char(M_.endo_names, 'd_b');
M_.endo_names_tex = char(M_.endo_names_tex, 'd\_b');
M_.endo_names_long = char(M_.endo_names_long, 'd_b');
M_.endo_names = char(M_.endo_names, 'd_s');
M_.endo_names_tex = char(M_.endo_names_tex, 'd\_s');
M_.endo_names_long = char(M_.endo_names_long, 'd_s');
M_.endo_names = char(M_.endo_names, 'b_b');
M_.endo_names_tex = char(M_.endo_names_tex, 'b\_b');
M_.endo_names_long = char(M_.endo_names_long, 'b_b');
M_.endo_names = char(M_.endo_names, 'p_dc');
M_.endo_names_tex = char(M_.endo_names_tex, 'p\_dc');
M_.endo_names_long = char(M_.endo_names_long, 'p_dc');
M_.endo_names = char(M_.endo_names, 'c_b');
M_.endo_names_tex = char(M_.endo_names_tex, 'c\_b');
M_.endo_names_long = char(M_.endo_names_long, 'c_b');
M_.endo_names = char(M_.endo_names, 'c_s');
M_.endo_names_tex = char(M_.endo_names_tex, 'c\_s');
M_.endo_names_long = char(M_.endo_names_long, 'c_s');
M_.endo_names = char(M_.endo_names, 'psi');
M_.endo_names_tex = char(M_.endo_names_tex, 'psi');
M_.endo_names_long = char(M_.endo_names_long, 'psi');
M_.endo_names = char(M_.endo_names, 'pi_c_h');
M_.endo_names_tex = char(M_.endo_names_tex, 'pi\_c\_h');
M_.endo_names_long = char(M_.endo_names_long, 'pi_c_h');
M_.endo_names = char(M_.endo_names, 's_c');
M_.endo_names_tex = char(M_.endo_names_tex, 's\_c');
M_.endo_names_long = char(M_.endo_names_long, 's_c');
M_.endo_names = char(M_.endo_names, 's_d');
M_.endo_names_tex = char(M_.endo_names_tex, 's\_d');
M_.endo_names_long = char(M_.endo_names_long, 's_d');
M_.endo_names = char(M_.endo_names, 'y_c');
M_.endo_names_tex = char(M_.endo_names_tex, 'y\_c');
M_.endo_names_long = char(M_.endo_names_long, 'y_c');
M_.endo_names = char(M_.endo_names, 'y_d');
M_.endo_names_tex = char(M_.endo_names_tex, 'y\_d');
M_.endo_names_long = char(M_.endo_names_long, 'y_d');
M_.endo_names = char(M_.endo_names, 'mc_c');
M_.endo_names_tex = char(M_.endo_names_tex, 'mc\_c');
M_.endo_names_long = char(M_.endo_names_long, 'mc_c');
M_.endo_names = char(M_.endo_names, 'mc_d');
M_.endo_names_tex = char(M_.endo_names_tex, 'mc\_d');
M_.endo_names_long = char(M_.endo_names_long, 'mc_d');
M_.endo_names = char(M_.endo_names, 'n_c');
M_.endo_names_tex = char(M_.endo_names_tex, 'n\_c');
M_.endo_names_long = char(M_.endo_names_long, 'n_c');
M_.endo_names = char(M_.endo_names, 'n_d');
M_.endo_names_tex = char(M_.endo_names_tex, 'n\_d');
M_.endo_names_long = char(M_.endo_names_long, 'n_d');
M_.endo_names = char(M_.endo_names, 'wp_d');
M_.endo_names_tex = char(M_.endo_names_tex, 'wp\_d');
M_.endo_names_long = char(M_.endo_names_long, 'wp_d');
M_.endo_names = char(M_.endo_names, 'wp_c');
M_.endo_names_tex = char(M_.endo_names_tex, 'wp\_c');
M_.endo_names_long = char(M_.endo_names_long, 'wp_c');
M_.endo_names = char(M_.endo_names, 'n_c_b');
M_.endo_names_tex = char(M_.endo_names_tex, 'n\_c\_b');
M_.endo_names_long = char(M_.endo_names_long, 'n_c_b');
M_.endo_names = char(M_.endo_names, 'n_d_b');
M_.endo_names_tex = char(M_.endo_names_tex, 'n\_d\_b');
M_.endo_names_long = char(M_.endo_names_long, 'n_d_b');
M_.endo_names = char(M_.endo_names, 'n_c_s');
M_.endo_names_tex = char(M_.endo_names_tex, 'n\_c\_s');
M_.endo_names_long = char(M_.endo_names_long, 'n_c_s');
M_.endo_names = char(M_.endo_names, 'n_d_s');
M_.endo_names_tex = char(M_.endo_names_tex, 'n\_d\_s');
M_.endo_names_long = char(M_.endo_names_long, 'n_d_s');
M_.endo_names = char(M_.endo_names, 'e');
M_.endo_names_tex = char(M_.endo_names_tex, 'e');
M_.endo_names_long = char(M_.endo_names_long, 'e');
M_.endo_names = char(M_.endo_names, 'yf');
M_.endo_names_tex = char(M_.endo_names_tex, 'yf');
M_.endo_names_long = char(M_.endo_names_long, 'yf');
M_.endo_names = char(M_.endo_names, 'rf');
M_.endo_names_tex = char(M_.endo_names_tex, 'rf');
M_.endo_names_long = char(M_.endo_names_long, 'rf');
M_.endo_names = char(M_.endo_names, 'cf');
M_.endo_names_tex = char(M_.endo_names_tex, 'cf');
M_.endo_names_long = char(M_.endo_names_long, 'cf');
M_.endo_names = char(M_.endo_names, 'nf');
M_.endo_names_tex = char(M_.endo_names_tex, 'nf');
M_.endo_names_long = char(M_.endo_names_long, 'nf');
M_.endo_names = char(M_.endo_names, 'df');
M_.endo_names_tex = char(M_.endo_names_tex, 'df');
M_.endo_names_long = char(M_.endo_names_long, 'df');
M_.endo_names = char(M_.endo_names, 'd_bf');
M_.endo_names_tex = char(M_.endo_names_tex, 'd\_bf');
M_.endo_names_long = char(M_.endo_names_long, 'd_bf');
M_.endo_names = char(M_.endo_names, 'd_sf');
M_.endo_names_tex = char(M_.endo_names_tex, 'd\_sf');
M_.endo_names_long = char(M_.endo_names_long, 'd_sf');
M_.endo_names = char(M_.endo_names, 'b_bf');
M_.endo_names_tex = char(M_.endo_names_tex, 'b\_bf');
M_.endo_names_long = char(M_.endo_names_long, 'b_bf');
M_.endo_names = char(M_.endo_names, 'c_bf');
M_.endo_names_tex = char(M_.endo_names_tex, 'c\_bf');
M_.endo_names_long = char(M_.endo_names_long, 'c_bf');
M_.endo_names = char(M_.endo_names, 'c_sf');
M_.endo_names_tex = char(M_.endo_names_tex, 'c\_sf');
M_.endo_names_long = char(M_.endo_names_long, 'c_sf');
M_.endo_names = char(M_.endo_names, 'psif');
M_.endo_names_tex = char(M_.endo_names_tex, 'psif');
M_.endo_names_long = char(M_.endo_names_long, 'psif');
M_.endo_names = char(M_.endo_names, 'y_cf');
M_.endo_names_tex = char(M_.endo_names_tex, 'y\_cf');
M_.endo_names_long = char(M_.endo_names_long, 'y_cf');
M_.endo_names = char(M_.endo_names, 'y_df');
M_.endo_names_tex = char(M_.endo_names_tex, 'y\_df');
M_.endo_names_long = char(M_.endo_names_long, 'y_df');
M_.endo_names = char(M_.endo_names, 'n_cf');
M_.endo_names_tex = char(M_.endo_names_tex, 'n\_cf');
M_.endo_names_long = char(M_.endo_names_long, 'n_cf');
M_.endo_names = char(M_.endo_names, 'n_df');
M_.endo_names_tex = char(M_.endo_names_tex, 'n\_df');
M_.endo_names_long = char(M_.endo_names_long, 'n_df');
M_.endo_names = char(M_.endo_names, 'wp_df');
M_.endo_names_tex = char(M_.endo_names_tex, 'wp\_df');
M_.endo_names_long = char(M_.endo_names_long, 'wp_df');
M_.endo_names = char(M_.endo_names, 'wp_cf');
M_.endo_names_tex = char(M_.endo_names_tex, 'wp\_cf');
M_.endo_names_long = char(M_.endo_names_long, 'wp_cf');
M_.endo_names = char(M_.endo_names, 'n_c_bf');
M_.endo_names_tex = char(M_.endo_names_tex, 'n\_c\_bf');
M_.endo_names_long = char(M_.endo_names_long, 'n_c_bf');
M_.endo_names = char(M_.endo_names, 'n_d_bf');
M_.endo_names_tex = char(M_.endo_names_tex, 'n\_d\_bf');
M_.endo_names_long = char(M_.endo_names_long, 'n_d_bf');
M_.endo_names = char(M_.endo_names, 'n_c_sf');
M_.endo_names_tex = char(M_.endo_names_tex, 'n\_c\_sf');
M_.endo_names_long = char(M_.endo_names_long, 'n_c_sf');
M_.endo_names = char(M_.endo_names, 'n_d_sf');
M_.endo_names_tex = char(M_.endo_names_tex, 'n\_d\_sf');
M_.endo_names_long = char(M_.endo_names_long, 'n_d_sf');
M_.endo_names = char(M_.endo_names, 'epsg');
M_.endo_names_tex = char(M_.endo_names_tex, 'epsg');
M_.endo_names_long = char(M_.endo_names_long, 'epsg');
M_.endo_names = char(M_.endo_names, 'a_c');
M_.endo_names_tex = char(M_.endo_names_tex, 'a\_c');
M_.endo_names_long = char(M_.endo_names_long, 'a_c');
M_.endo_names = char(M_.endo_names, 'a_d');
M_.endo_names_tex = char(M_.endo_names_tex, 'a\_d');
M_.endo_names_long = char(M_.endo_names_long, 'a_d');
M_.endo_names = char(M_.endo_names, 'shock_mu_c');
M_.endo_names_tex = char(M_.endo_names_tex, 'shock\_mu\_c');
M_.endo_names_long = char(M_.endo_names_long, 'shock_mu_c');
M_.endo_names = char(M_.endo_names, 'shock_mu_d');
M_.endo_names_tex = char(M_.endo_names_tex, 'shock\_mu\_d');
M_.endo_names_long = char(M_.endo_names_long, 'shock_mu_d');
M_.endo_names = char(M_.endo_names, 'epsmu_c_aux');
M_.endo_names_tex = char(M_.endo_names_tex, 'epsmu\_c\_aux');
M_.endo_names_long = char(M_.endo_names_long, 'epsmu_c_aux');
M_.endo_names = char(M_.endo_names, 'epsmu_d_aux');
M_.endo_names_tex = char(M_.endo_names_tex, 'epsmu\_d\_aux');
M_.endo_names_long = char(M_.endo_names_long, 'epsmu_d_aux');
M_.endo_names = char(M_.endo_names, 'LTV');
M_.endo_names_tex = char(M_.endo_names_tex, 'LTV');
M_.endo_names_long = char(M_.endo_names_long, 'LTV');
M_.endo_names = char(M_.endo_names, 'shock_d_b');
M_.endo_names_tex = char(M_.endo_names_tex, 'shock\_d\_b');
M_.endo_names_long = char(M_.endo_names_long, 'shock_d_b');
M_.endo_names = char(M_.endo_names, 'shock_d_s');
M_.endo_names_tex = char(M_.endo_names_tex, 'shock\_d\_s');
M_.endo_names_long = char(M_.endo_names_long, 'shock_d_s');
M_.endo_names = char(M_.endo_names, 'shock_d_stern');
M_.endo_names_tex = char(M_.endo_names_tex, 'shock\_d\_stern');
M_.endo_names_long = char(M_.endo_names_long, 'shock_d_stern');
M_.endo_names = char(M_.endo_names, 'c_ast');
M_.endo_names_tex = char(M_.endo_names_tex, 'c\_ast');
M_.endo_names_long = char(M_.endo_names_long, 'c_ast');
M_.endo_names = char(M_.endo_names, 'd_ast');
M_.endo_names_tex = char(M_.endo_names_tex, 'd\_ast');
M_.endo_names_long = char(M_.endo_names_long, 'd_ast');
M_.endo_names = char(M_.endo_names, 'g');
M_.endo_names_tex = char(M_.endo_names_tex, 'g');
M_.endo_names_long = char(M_.endo_names_long, 'g');
M_.endo_names = char(M_.endo_names, 'p_dc_ast');
M_.endo_names_tex = char(M_.endo_names_tex, 'p\_dc\_ast');
M_.endo_names_long = char(M_.endo_names_long, 'p_dc_ast');
M_.endo_names = char(M_.endo_names, 'p_d_ast');
M_.endo_names_tex = char(M_.endo_names_tex, 'p\_d\_ast');
M_.endo_names_long = char(M_.endo_names_long, 'p_d_ast');
M_.endo_names = char(M_.endo_names, 'p_c_ast');
M_.endo_names_tex = char(M_.endo_names_tex, 'p\_c\_ast');
M_.endo_names_long = char(M_.endo_names_long, 'p_c_ast');
M_.endo_names = char(M_.endo_names, 'pi_c_f');
M_.endo_names_tex = char(M_.endo_names_tex, 'pi\_c\_f');
M_.endo_names_long = char(M_.endo_names_long, 'pi_c_f');
M_.endo_names = char(M_.endo_names, 'i_d_ast');
M_.endo_names_tex = char(M_.endo_names_tex, 'i\_d\_ast');
M_.endo_names_long = char(M_.endo_names_long, 'i_d_ast');
M_.endo_names = char(M_.endo_names, 'interest');
M_.endo_names_tex = char(M_.endo_names_tex, 'interest');
M_.endo_names_long = char(M_.endo_names_long, 'interest');
M_.endo_names = char(M_.endo_names, 'inflation');
M_.endo_names_tex = char(M_.endo_names_tex, 'inflation');
M_.endo_names_long = char(M_.endo_names_long, 'inflation');
M_.endo_names = char(M_.endo_names, 'inflationq');
M_.endo_names_tex = char(M_.endo_names_tex, 'inflationq');
M_.endo_names_long = char(M_.endo_names_long, 'inflationq');
M_.endo_names = char(M_.endo_names, 'outputgap');
M_.endo_names_tex = char(M_.endo_names_tex, 'outputgap');
M_.endo_names_long = char(M_.endo_names_long, 'outputgap');
M_.endo_names = char(M_.endo_names, 'output');
M_.endo_names_tex = char(M_.endo_names_tex, 'output');
M_.endo_names_long = char(M_.endo_names_long, 'output');
M_.endo_names = char(M_.endo_names, 'fispol');
M_.endo_names_tex = char(M_.endo_names_tex, 'fispol');
M_.endo_names_long = char(M_.endo_names_long, 'fispol');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_83');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_83');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_83');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_87');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_87');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_87');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_91');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_91');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_91');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_118');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_118');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_118');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_122');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_122');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_122');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_126');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_126');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_126');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_153');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_153');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_153');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_157');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_157');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_157');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_161');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_161');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_161');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_3_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_3\_1');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_3_1');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_3_2');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_3\_2');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_3_2');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_74_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_74\_1');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_74_1');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_74_2');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_74\_2');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_74_2');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_74_3');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_74\_3');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_74_3');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_73_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_73\_1');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_73_1');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_73_2');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_73\_2');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_73_2');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_73_3');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_73\_3');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_73_3');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_70_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_70\_1');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_70_1');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_70_2');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_70\_2');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_70_2');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_70_3');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_70\_3');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_70_3');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_72_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_72\_1');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_72_1');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_72_2');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_72\_2');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_72_2');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_72_3');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_72\_3');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_72_3');
M_.endo_partitions = struct();
M_.param_names = 'cofintintb1';
M_.param_names_tex = 'cofintintb1';
M_.param_names_long = 'cofintintb1';
M_.param_names = char(M_.param_names, 'cofintintb2');
M_.param_names_tex = char(M_.param_names_tex, 'cofintintb2');
M_.param_names_long = char(M_.param_names_long, 'cofintintb2');
M_.param_names = char(M_.param_names, 'cofintintb3');
M_.param_names_tex = char(M_.param_names_tex, 'cofintintb3');
M_.param_names_long = char(M_.param_names_long, 'cofintintb3');
M_.param_names = char(M_.param_names, 'cofintintb4');
M_.param_names_tex = char(M_.param_names_tex, 'cofintintb4');
M_.param_names_long = char(M_.param_names_long, 'cofintintb4');
M_.param_names = char(M_.param_names, 'cofintinf0');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinf0');
M_.param_names_long = char(M_.param_names_long, 'cofintinf0');
M_.param_names = char(M_.param_names, 'cofintinfb1');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinfb1');
M_.param_names_long = char(M_.param_names_long, 'cofintinfb1');
M_.param_names = char(M_.param_names, 'cofintinfb2');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinfb2');
M_.param_names_long = char(M_.param_names_long, 'cofintinfb2');
M_.param_names = char(M_.param_names, 'cofintinfb3');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinfb3');
M_.param_names_long = char(M_.param_names_long, 'cofintinfb3');
M_.param_names = char(M_.param_names, 'cofintinfb4');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinfb4');
M_.param_names_long = char(M_.param_names_long, 'cofintinfb4');
M_.param_names = char(M_.param_names, 'cofintinff1');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinff1');
M_.param_names_long = char(M_.param_names_long, 'cofintinff1');
M_.param_names = char(M_.param_names, 'cofintinff2');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinff2');
M_.param_names_long = char(M_.param_names_long, 'cofintinff2');
M_.param_names = char(M_.param_names, 'cofintinff3');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinff3');
M_.param_names_long = char(M_.param_names_long, 'cofintinff3');
M_.param_names = char(M_.param_names, 'cofintinff4');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinff4');
M_.param_names_long = char(M_.param_names_long, 'cofintinff4');
M_.param_names = char(M_.param_names, 'cofintout');
M_.param_names_tex = char(M_.param_names_tex, 'cofintout');
M_.param_names_long = char(M_.param_names_long, 'cofintout');
M_.param_names = char(M_.param_names, 'cofintoutb1');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutb1');
M_.param_names_long = char(M_.param_names_long, 'cofintoutb1');
M_.param_names = char(M_.param_names, 'cofintoutb2');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutb2');
M_.param_names_long = char(M_.param_names_long, 'cofintoutb2');
M_.param_names = char(M_.param_names, 'cofintoutb3');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutb3');
M_.param_names_long = char(M_.param_names_long, 'cofintoutb3');
M_.param_names = char(M_.param_names, 'cofintoutb4');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutb4');
M_.param_names_long = char(M_.param_names_long, 'cofintoutb4');
M_.param_names = char(M_.param_names, 'cofintoutf1');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutf1');
M_.param_names_long = char(M_.param_names_long, 'cofintoutf1');
M_.param_names = char(M_.param_names, 'cofintoutf2');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutf2');
M_.param_names_long = char(M_.param_names_long, 'cofintoutf2');
M_.param_names = char(M_.param_names, 'cofintoutf3');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutf3');
M_.param_names_long = char(M_.param_names_long, 'cofintoutf3');
M_.param_names = char(M_.param_names, 'cofintoutf4');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutf4');
M_.param_names_long = char(M_.param_names_long, 'cofintoutf4');
M_.param_names = char(M_.param_names, 'cofintoutp');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutp');
M_.param_names_long = char(M_.param_names_long, 'cofintoutp');
M_.param_names = char(M_.param_names, 'cofintoutpb1');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpb1');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpb1');
M_.param_names = char(M_.param_names, 'cofintoutpb2');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpb2');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpb2');
M_.param_names = char(M_.param_names, 'cofintoutpb3');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpb3');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpb3');
M_.param_names = char(M_.param_names, 'cofintoutpb4');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpb4');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpb4');
M_.param_names = char(M_.param_names, 'cofintoutpf1');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpf1');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpf1');
M_.param_names = char(M_.param_names, 'cofintoutpf2');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpf2');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpf2');
M_.param_names = char(M_.param_names, 'cofintoutpf3');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpf3');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpf3');
M_.param_names = char(M_.param_names, 'cofintoutpf4');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpf4');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpf4');
M_.param_names = char(M_.param_names, 'std_r_');
M_.param_names_tex = char(M_.param_names_tex, 'std\_r\_');
M_.param_names_long = char(M_.param_names_long, 'std_r_');
M_.param_names = char(M_.param_names, 'std_r_quart');
M_.param_names_tex = char(M_.param_names_tex, 'std\_r\_quart');
M_.param_names_long = char(M_.param_names_long, 'std_r_quart');
M_.param_names = char(M_.param_names, 'coffispol');
M_.param_names_tex = char(M_.param_names_tex, 'coffispol');
M_.param_names_long = char(M_.param_names_long, 'coffispol');
M_.param_names = char(M_.param_names, 'gamma');
M_.param_names_tex = char(M_.param_names_tex, 'gamma');
M_.param_names_long = char(M_.param_names_long, 'gamma');
M_.param_names = char(M_.param_names, 'xi');
M_.param_names_tex = char(M_.param_names_tex, 'xi');
M_.param_names_long = char(M_.param_names_long, 'xi');
M_.param_names = char(M_.param_names, 'beta_s');
M_.param_names_tex = char(M_.param_names_tex, 'beta\_s');
M_.param_names_long = char(M_.param_names_long, 'beta_s');
M_.param_names = char(M_.param_names, 'delta');
M_.param_names_tex = char(M_.param_names_tex, 'delta');
M_.param_names_long = char(M_.param_names_long, 'delta');
M_.param_names = char(M_.param_names, 'h_c');
M_.param_names_tex = char(M_.param_names_tex, 'h\_c');
M_.param_names_long = char(M_.param_names_long, 'h_c');
M_.param_names = char(M_.param_names, 'beta_b');
M_.param_names_tex = char(M_.param_names_tex, 'beta\_b');
M_.param_names_long = char(M_.param_names_long, 'beta_b');
M_.param_names = char(M_.param_names, 'chi');
M_.param_names_tex = char(M_.param_names_tex, 'chi');
M_.param_names_long = char(M_.param_names_long, 'chi');
M_.param_names = char(M_.param_names, 'alpha_c');
M_.param_names_tex = char(M_.param_names_tex, 'alpha\_c');
M_.param_names_long = char(M_.param_names_long, 'alpha_c');
M_.param_names = char(M_.param_names, 'alpha_d');
M_.param_names_tex = char(M_.param_names_tex, 'alpha\_d');
M_.param_names_long = char(M_.param_names_long, 'alpha_d');
M_.param_names = char(M_.param_names, 'vartheta_c');
M_.param_names_tex = char(M_.param_names_tex, 'vartheta\_c');
M_.param_names_long = char(M_.param_names_long, 'vartheta_c');
M_.param_names = char(M_.param_names, 'vartheta_d');
M_.param_names_tex = char(M_.param_names_tex, 'vartheta\_d');
M_.param_names_long = char(M_.param_names_long, 'vartheta_d');
M_.param_names = char(M_.param_names, 'omega');
M_.param_names_tex = char(M_.param_names_tex, 'omega');
M_.param_names_long = char(M_.param_names_long, 'omega');
M_.param_names = char(M_.param_names, 'big_phi_c');
M_.param_names_tex = char(M_.param_names_tex, 'big\_phi\_c');
M_.param_names_long = char(M_.param_names_long, 'big_phi_c');
M_.param_names = char(M_.param_names, 'theta_c');
M_.param_names_tex = char(M_.param_names_tex, 'theta\_c');
M_.param_names_long = char(M_.param_names_long, 'theta_c');
M_.param_names = char(M_.param_names, 'tau_c');
M_.param_names_tex = char(M_.param_names_tex, 'tau\_c');
M_.param_names_long = char(M_.param_names_long, 'tau_c');
M_.param_names = char(M_.param_names, 'kappa_c');
M_.param_names_tex = char(M_.param_names_tex, 'kappa\_c');
M_.param_names_long = char(M_.param_names_long, 'kappa_c');
M_.param_names = char(M_.param_names, 'big_phi_d');
M_.param_names_tex = char(M_.param_names_tex, 'big\_phi\_d');
M_.param_names_long = char(M_.param_names_long, 'big_phi_d');
M_.param_names = char(M_.param_names, 'theta_d');
M_.param_names_tex = char(M_.param_names_tex, 'theta\_d');
M_.param_names_long = char(M_.param_names_long, 'theta_d');
M_.param_names = char(M_.param_names, 'tau_d');
M_.param_names_tex = char(M_.param_names_tex, 'tau\_d');
M_.param_names_long = char(M_.param_names_long, 'tau_d');
M_.param_names = char(M_.param_names, 'kappa_d');
M_.param_names_tex = char(M_.param_names_tex, 'kappa\_d');
M_.param_names_long = char(M_.param_names_long, 'kappa_d');
M_.param_names = char(M_.param_names, 'phi');
M_.param_names_tex = char(M_.param_names_tex, 'phi');
M_.param_names_long = char(M_.param_names_long, 'phi');
M_.param_names = char(M_.param_names, 'zeta_c');
M_.param_names_tex = char(M_.param_names_tex, 'zeta\_c');
M_.param_names_long = char(M_.param_names_long, 'zeta_c');
M_.param_names = char(M_.param_names, 'zeta_d');
M_.param_names_tex = char(M_.param_names_tex, 'zeta\_d');
M_.param_names_long = char(M_.param_names_long, 'zeta_d');
M_.param_names = char(M_.param_names, 'eta_c');
M_.param_names_tex = char(M_.param_names_tex, 'eta\_c');
M_.param_names_long = char(M_.param_names_long, 'eta_c');
M_.param_names = char(M_.param_names, 'eta_d');
M_.param_names_tex = char(M_.param_names_tex, 'eta\_d');
M_.param_names_long = char(M_.param_names_long, 'eta_d');
M_.param_names = char(M_.param_names, 'mu_c');
M_.param_names_tex = char(M_.param_names_tex, 'mu\_c');
M_.param_names_long = char(M_.param_names_long, 'mu_c');
M_.param_names = char(M_.param_names, 'mu_d');
M_.param_names_tex = char(M_.param_names_tex, 'mu\_d');
M_.param_names_long = char(M_.param_names_long, 'mu_d');
M_.param_names = char(M_.param_names, 'Lambda_b');
M_.param_names_tex = char(M_.param_names_tex, 'Lambda\_b');
M_.param_names_long = char(M_.param_names_long, 'Lambda_b');
M_.param_names = char(M_.param_names, 'Lambda_s');
M_.param_names_tex = char(M_.param_names_tex, 'Lambda\_s');
M_.param_names_long = char(M_.param_names_long, 'Lambda_s');
M_.param_names = char(M_.param_names, 'biggamma');
M_.param_names_tex = char(M_.param_names_tex, 'biggamma');
M_.param_names_long = char(M_.param_names_long, 'biggamma');
M_.param_names = char(M_.param_names, 'sigma');
M_.param_names_tex = char(M_.param_names_tex, 'sigma');
M_.param_names_long = char(M_.param_names_long, 'sigma');
M_.param_names = char(M_.param_names, 'rho_a_c');
M_.param_names_tex = char(M_.param_names_tex, 'rho\_a\_c');
M_.param_names_long = char(M_.param_names_long, 'rho_a_c');
M_.param_names = char(M_.param_names, 'rho_a_d');
M_.param_names_tex = char(M_.param_names_tex, 'rho\_a\_d');
M_.param_names_long = char(M_.param_names_long, 'rho_a_d');
M_.param_names = char(M_.param_names, 'rho_mu_c1');
M_.param_names_tex = char(M_.param_names_tex, 'rho\_mu\_c1');
M_.param_names_long = char(M_.param_names_long, 'rho_mu_c1');
M_.param_names = char(M_.param_names, 'rho_mu_c2');
M_.param_names_tex = char(M_.param_names_tex, 'rho\_mu\_c2');
M_.param_names_long = char(M_.param_names_long, 'rho_mu_c2');
M_.param_names = char(M_.param_names, 'rho_mu_d1');
M_.param_names_tex = char(M_.param_names_tex, 'rho\_mu\_d1');
M_.param_names_long = char(M_.param_names_long, 'rho_mu_d1');
M_.param_names = char(M_.param_names, 'rho_mu_d2');
M_.param_names_tex = char(M_.param_names_tex, 'rho\_mu\_d2');
M_.param_names_long = char(M_.param_names_long, 'rho_mu_d2');
M_.param_names = char(M_.param_names, 'rho_LTV');
M_.param_names_tex = char(M_.param_names_tex, 'rho\_LTV');
M_.param_names_long = char(M_.param_names_long, 'rho_LTV');
M_.param_names = char(M_.param_names, 'rho_d_b');
M_.param_names_tex = char(M_.param_names_tex, 'rho\_d\_b');
M_.param_names_long = char(M_.param_names_long, 'rho_d_b');
M_.param_names = char(M_.param_names, 'rho_d_s');
M_.param_names_tex = char(M_.param_names_tex, 'rho\_d\_s');
M_.param_names_long = char(M_.param_names_long, 'rho_d_s');
M_.param_names = char(M_.param_names, 'rho_d_stern');
M_.param_names_tex = char(M_.param_names_tex, 'rho\_d\_stern');
M_.param_names_long = char(M_.param_names_long, 'rho_d_stern');
M_.param_names = char(M_.param_names, 'rho_c_ast');
M_.param_names_tex = char(M_.param_names_tex, 'rho\_c\_ast');
M_.param_names_long = char(M_.param_names_long, 'rho_c_ast');
M_.param_names = char(M_.param_names, 'rho_d_ast');
M_.param_names_tex = char(M_.param_names_tex, 'rho\_d\_ast');
M_.param_names_long = char(M_.param_names_long, 'rho_d_ast');
M_.param_names = char(M_.param_names, 'rho_g');
M_.param_names_tex = char(M_.param_names_tex, 'rho\_g');
M_.param_names_long = char(M_.param_names_long, 'rho_g');
M_.param_names = char(M_.param_names, 'rho_gac');
M_.param_names_tex = char(M_.param_names_tex, 'rho\_gac');
M_.param_names_long = char(M_.param_names_long, 'rho_gac');
M_.param_names = char(M_.param_names, 'rho_gad');
M_.param_names_tex = char(M_.param_names_tex, 'rho\_gad');
M_.param_names_long = char(M_.param_names_long, 'rho_gad');
M_.param_names = char(M_.param_names, 'rho_p_c_ast');
M_.param_names_tex = char(M_.param_names_tex, 'rho\_p\_c\_ast');
M_.param_names_long = char(M_.param_names_long, 'rho_p_c_ast');
M_.param_names = char(M_.param_names, 'rho_p_d_ast');
M_.param_names_tex = char(M_.param_names_tex, 'rho\_p\_d\_ast');
M_.param_names_long = char(M_.param_names_long, 'rho_p_d_ast');
M_.param_names = char(M_.param_names, 'CBDB');
M_.param_names_tex = char(M_.param_names_tex, 'CBDB');
M_.param_names_long = char(M_.param_names_long, 'CBDB');
M_.param_names = char(M_.param_names, 'PDC');
M_.param_names_tex = char(M_.param_names_tex, 'PDC');
M_.param_names_long = char(M_.param_names_long, 'PDC');
M_.param_names = char(M_.param_names, 'CSDS');
M_.param_names_tex = char(M_.param_names_tex, 'CSDS');
M_.param_names_long = char(M_.param_names_long, 'CSDS');
M_.param_names = char(M_.param_names, 'CBC');
M_.param_names_tex = char(M_.param_names_tex, 'CBC');
M_.param_names_long = char(M_.param_names_long, 'CBC');
M_.param_names = char(M_.param_names, 'CSC');
M_.param_names_tex = char(M_.param_names_tex, 'CSC');
M_.param_names_long = char(M_.param_names_long, 'CSC');
M_.param_names = char(M_.param_names, 'DBD');
M_.param_names_tex = char(M_.param_names_tex, 'DBD');
M_.param_names_long = char(M_.param_names_long, 'DBD');
M_.param_names = char(M_.param_names, 'DSD');
M_.param_names_tex = char(M_.param_names_tex, 'DSD');
M_.param_names_long = char(M_.param_names_long, 'DSD');
M_.param_names = char(M_.param_names, 'BHCB');
M_.param_names_tex = char(M_.param_names_tex, 'BHCB');
M_.param_names_long = char(M_.param_names_long, 'BHCB');
M_.param_names = char(M_.param_names, 'DBCB');
M_.param_names_tex = char(M_.param_names_tex, 'DBCB');
M_.param_names_long = char(M_.param_names_long, 'DBCB');
M_.param_names = char(M_.param_names, 'DB');
M_.param_names_tex = char(M_.param_names_tex, 'DB');
M_.param_names_long = char(M_.param_names_long, 'DB');
M_.param_names = char(M_.param_names, 'CB');
M_.param_names_tex = char(M_.param_names_tex, 'CB');
M_.param_names_long = char(M_.param_names_long, 'CB');
M_.param_names = char(M_.param_names, 'DS');
M_.param_names_tex = char(M_.param_names_tex, 'DS');
M_.param_names_long = char(M_.param_names_long, 'DS');
M_.param_names = char(M_.param_names, 'CS');
M_.param_names_tex = char(M_.param_names_tex, 'CS');
M_.param_names_long = char(M_.param_names_long, 'CS');
M_.param_names = char(M_.param_names, 'N');
M_.param_names_tex = char(M_.param_names_tex, 'N');
M_.param_names_long = char(M_.param_names_long, 'N');
M_.param_names = char(M_.param_names, 'ND');
M_.param_names_tex = char(M_.param_names_tex, 'ND');
M_.param_names_long = char(M_.param_names_long, 'ND');
M_.param_names = char(M_.param_names, 'NC');
M_.param_names_tex = char(M_.param_names_tex, 'NC');
M_.param_names_long = char(M_.param_names_long, 'NC');
M_.param_names = char(M_.param_names, 'C');
M_.param_names_tex = char(M_.param_names_tex, 'C');
M_.param_names_long = char(M_.param_names_long, 'C');
M_.param_names = char(M_.param_names, 'D');
M_.param_names_tex = char(M_.param_names_tex, 'D');
M_.param_names_long = char(M_.param_names_long, 'D');
M_.param_names = char(M_.param_names, 'NCCB');
M_.param_names_tex = char(M_.param_names_tex, 'NCCB');
M_.param_names_long = char(M_.param_names_long, 'NCCB');
M_.param_names = char(M_.param_names, 'NDCB');
M_.param_names_tex = char(M_.param_names_tex, 'NDCB');
M_.param_names_long = char(M_.param_names_long, 'NDCB');
M_.param_partitions = struct();
M_.exo_det_nbr = 0;
M_.exo_nbr = 14;
M_.endo_nbr = 99;
M_.param_nbr = 102;
M_.orig_endo_nbr = 76;
M_.aux_vars(1).endo_index = 77;
M_.aux_vars(1).type = 0;
M_.aux_vars(2).endo_index = 78;
M_.aux_vars(2).type = 0;
M_.aux_vars(3).endo_index = 79;
M_.aux_vars(3).type = 0;
M_.aux_vars(4).endo_index = 80;
M_.aux_vars(4).type = 0;
M_.aux_vars(5).endo_index = 81;
M_.aux_vars(5).type = 0;
M_.aux_vars(6).endo_index = 82;
M_.aux_vars(6).type = 0;
M_.aux_vars(7).endo_index = 83;
M_.aux_vars(7).type = 0;
M_.aux_vars(8).endo_index = 84;
M_.aux_vars(8).type = 0;
M_.aux_vars(9).endo_index = 85;
M_.aux_vars(9).type = 0;
M_.aux_vars(10).endo_index = 86;
M_.aux_vars(10).type = 1;
M_.aux_vars(10).orig_index = 4;
M_.aux_vars(10).orig_lead_lag = -1;
M_.aux_vars(11).endo_index = 87;
M_.aux_vars(11).type = 1;
M_.aux_vars(11).orig_index = 4;
M_.aux_vars(11).orig_lead_lag = -2;
M_.aux_vars(12).endo_index = 88;
M_.aux_vars(12).type = 1;
M_.aux_vars(12).orig_index = 75;
M_.aux_vars(12).orig_lead_lag = -1;
M_.aux_vars(13).endo_index = 89;
M_.aux_vars(13).type = 1;
M_.aux_vars(13).orig_index = 75;
M_.aux_vars(13).orig_lead_lag = -2;
M_.aux_vars(14).endo_index = 90;
M_.aux_vars(14).type = 1;
M_.aux_vars(14).orig_index = 75;
M_.aux_vars(14).orig_lead_lag = -3;
M_.aux_vars(15).endo_index = 91;
M_.aux_vars(15).type = 1;
M_.aux_vars(15).orig_index = 74;
M_.aux_vars(15).orig_lead_lag = -1;
M_.aux_vars(16).endo_index = 92;
M_.aux_vars(16).type = 1;
M_.aux_vars(16).orig_index = 74;
M_.aux_vars(16).orig_lead_lag = -2;
M_.aux_vars(17).endo_index = 93;
M_.aux_vars(17).type = 1;
M_.aux_vars(17).orig_index = 74;
M_.aux_vars(17).orig_lead_lag = -3;
M_.aux_vars(18).endo_index = 94;
M_.aux_vars(18).type = 1;
M_.aux_vars(18).orig_index = 71;
M_.aux_vars(18).orig_lead_lag = -1;
M_.aux_vars(19).endo_index = 95;
M_.aux_vars(19).type = 1;
M_.aux_vars(19).orig_index = 71;
M_.aux_vars(19).orig_lead_lag = -2;
M_.aux_vars(20).endo_index = 96;
M_.aux_vars(20).type = 1;
M_.aux_vars(20).orig_index = 71;
M_.aux_vars(20).orig_lead_lag = -3;
M_.aux_vars(21).endo_index = 97;
M_.aux_vars(21).type = 1;
M_.aux_vars(21).orig_index = 73;
M_.aux_vars(21).orig_lead_lag = -1;
M_.aux_vars(22).endo_index = 98;
M_.aux_vars(22).type = 1;
M_.aux_vars(22).orig_index = 73;
M_.aux_vars(22).orig_lead_lag = -2;
M_.aux_vars(23).endo_index = 99;
M_.aux_vars(23).type = 1;
M_.aux_vars(23).orig_index = 73;
M_.aux_vars(23).orig_lead_lag = -3;
M_.Sigma_e = zeros(14, 14);
M_.Correlation_matrix = eye(14, 14);
M_.H = 0;
M_.Correlation_matrix_ME = 1;
M_.sigma_e_is_diagonal = 1;
M_.det_shocks = [];
options_.linear = 1;
options_.block=0;
options_.bytecode=0;
options_.use_dll=0;
M_.hessian_eq_zero = 1;
erase_compiled_function('HK_FP13_static');
erase_compiled_function('HK_FP13_dynamic');
M_.orig_eq_nbr = 76;
M_.eq_nbr = 99;
M_.ramsey_eq_nbr = 0;
M_.set_auxiliary_variables = exist(['./' M_.fname '_set_auxiliary_variables.m'], 'file') == 2;
M_.lead_lag_incidence = [
 0 56 0;
 1 57 155;
 2 58 0;
 3 59 0;
 4 60 0;
 0 61 0;
 5 62 0;
 6 63 156;
 0 64 157;
 7 65 0;
 8 66 158;
 9 67 159;
 10 68 160;
 0 69 0;
 11 70 161;
 12 71 162;
 13 72 163;
 0 73 0;
 0 74 0;
 0 75 0;
 0 76 0;
 0 77 0;
 0 78 0;
 0 79 0;
 0 80 0;
 0 81 0;
 0 82 0;
 0 83 0;
 0 84 0;
 14 85 0;
 0 86 0;
 15 87 0;
 16 88 0;
 0 89 0;
 17 90 0;
 18 91 164;
 0 92 165;
 19 93 0;
 20 94 166;
 21 95 167;
 0 96 0;
 0 97 0;
 0 98 0;
 0 99 0;
 0 100 0;
 0 101 0;
 0 102 0;
 0 103 0;
 0 104 0;
 0 105 0;
 0 106 0;
 0 107 0;
 22 108 0;
 23 109 0;
 24 110 0;
 25 111 0;
 26 112 0;
 27 113 0;
 28 114 0;
 29 115 0;
 30 116 0;
 31 117 0;
 32 118 0;
 33 119 0;
 34 120 0;
 0 121 0;
 35 122 0;
 36 123 0;
 0 124 0;
 37 125 0;
 38 126 0;
 0 127 0;
 39 128 168;
 40 129 169;
 41 130 170;
 0 131 0;
 0 132 171;
 0 133 172;
 0 134 173;
 0 135 174;
 0 136 175;
 0 137 176;
 0 138 177;
 0 139 178;
 0 140 179;
 42 141 0;
 43 142 0;
 44 143 0;
 45 144 0;
 46 145 0;
 47 146 0;
 48 147 0;
 49 148 0;
 50 149 0;
 51 150 0;
 52 151 0;
 53 152 0;
 54 153 0;
 55 154 0;]';
M_.nstatic = 33;
M_.nfwrd   = 11;
M_.npred   = 41;
M_.nboth   = 14;
M_.nsfwrd   = 25;
M_.nspred   = 55;
M_.ndynamic   = 66;
M_.equations_tags = {
};
M_.static_and_dynamic_models_differ = 0;
M_.exo_names_orig_ord = [1:14];
M_.maximum_lag = 1;
M_.maximum_lead = 1;
M_.maximum_endo_lag = 1;
M_.maximum_endo_lead = 1;
oo_.steady_state = zeros(99, 1);
M_.maximum_exo_lag = 0;
M_.maximum_exo_lead = 0;
oo_.exo_steady_state = zeros(14, 1);
M_.params = NaN(102, 1);
M_.NNZDerivatives = [473; 0; -1];
M_.params( 42 ) = 0.87;
alpha_c = M_.params( 42 );
M_.params( 43 ) = 0.45;
alpha_d = M_.params( 43 );
M_.params( 36 ) = 0.1;
xi = M_.params( 36 );
M_.params( 35 ) = 0.39;
gamma = M_.params( 35 );
M_.params( 60 ) = 0.1;
mu_c = M_.params( 60 );
M_.params( 61 ) = 0.1;
mu_d = M_.params( 61 );
M_.params( 37 ) = 0.99;
beta_s = M_.params( 37 );
M_.params( 38 ) = 0.01;
delta = M_.params( 38 );
M_.params( 39 ) = 0.03;
h_c = M_.params( 39 );
M_.params( 40 ) = 0.96;
beta_b = M_.params( 40 );
M_.params( 41 ) = 0.4;
chi = M_.params( 41 );
M_.params( 46 ) = 0.15;
omega = M_.params( 46 );
M_.params( 55 ) = 12.25;
phi = M_.params( 55 );
M_.params( 56 ) = 2;
zeta_c = M_.params( 56 );
M_.params( 58 ) = 2;
eta_c = M_.params( 58 );
M_.params( 57 ) = 2;
zeta_d = M_.params( 57 );
M_.params( 59 ) = 2;
eta_d = M_.params( 59 );
M_.params( 44 ) = M_.params(56)+(1-M_.params(42))*M_.params(58);
vartheta_c = M_.params( 44 );
M_.params( 45 ) = M_.params(57)+(1-M_.params(43))*M_.params(59);
vartheta_d = M_.params( 45 );
M_.params( 65 ) = 0.98;
sigma = M_.params( 65 );
M_.params( 48 ) = 0.50;
theta_c = M_.params( 48 );
M_.params( 49 ) = 0.21;
tau_c = M_.params( 49 );
M_.params( 47 ) = (M_.params(48)+M_.params(49)*(1-M_.params(48)*(1-M_.params(37))))^(-1);
big_phi_c = M_.params( 47 );
M_.params( 50 ) = (1-M_.params(49))*(1-M_.params(48))*(1-M_.params(48)*M_.params(37))*M_.params(47);
kappa_c = M_.params( 50 );
M_.params( 52 ) = 0.29;
theta_d = M_.params( 52 );
M_.params( 53 ) = 0.25;
tau_d = M_.params( 53 );
M_.params( 51 ) = (M_.params(52)+M_.params(53)*(1-(1-M_.params(37))*M_.params(52)))^(-1);
big_phi_d = M_.params( 51 );
M_.params( 54 ) = (1-M_.params(53))*(1-M_.params(52))*(1-M_.params(37)*M_.params(52))*M_.params(51);
kappa_d = M_.params( 54 );
M_.params( 64 ) = (M_.params(65)+(1-M_.params(65))*M_.params(35))/(1-M_.params(39));
biggamma = M_.params( 64 );
M_.params( 76 ) = 0.7;
rho_c_ast = M_.params( 76 );
M_.params( 77 ) = 0.7;
rho_d_ast = M_.params( 77 );
M_.params( 74 ) = 0.89;
rho_d_s = M_.params( 74 );
M_.params( 73 ) = 0.74;
rho_d_b = M_.params( 73 );
M_.params( 75 ) = 0.42;
rho_d_stern = M_.params( 75 );
M_.params( 78 ) = 0.59;
rho_g = M_.params( 78 );
M_.params( 79 ) = 0;
rho_gac = M_.params( 79 );
M_.params( 80 ) = 0;
rho_gad = M_.params( 80 );
M_.params( 66 ) = 0.65;
rho_a_c = M_.params( 66 );
M_.params( 67 ) = 0.31;
rho_a_d = M_.params( 67 );
M_.params( 68 ) = 0.77;
rho_mu_c1 = M_.params( 68 );
M_.params( 69 ) = 0.07;
rho_mu_c2 = M_.params( 69 );
M_.params( 70 ) = 0.3;
rho_mu_d1 = M_.params( 70 );
M_.params( 71 ) = 0.3;
rho_mu_d2 = M_.params( 71 );
M_.params( 72 ) = 0.3;
rho_LTV = M_.params( 72 );
M_.params( 81 ) = 0.98;
rho_p_c_ast = M_.params( 81 );
M_.params( 82 ) = 0.39;
rho_p_d_ast = M_.params( 82 );
M_.params( 96 ) = 0.3;
N = M_.params( 96 );
M_.params( 84 ) = (1+M_.params(61))/(1+M_.params(60));
PDC = M_.params( 84 );
M_.params( 83 ) = (1-M_.params(35))/M_.params(35)*(1-M_.params(40)*(1-M_.params(38))-(1-M_.params(38))*(1-M_.params(41))*(M_.params(37)-M_.params(40)))/(1-M_.params(39))*M_.params(84);
CBDB = M_.params( 83 );
M_.params( 85 ) = M_.params(84)*(1-M_.params(35))/M_.params(35)*(1-M_.params(37)*(1-M_.params(38)))/(1-M_.params(39));
CSDS = M_.params( 85 );
M_.params( 91 ) = 1/M_.params(83);
DBCB = M_.params( 91 );
M_.params( 90 ) = M_.params(84)*M_.params(37)*(1-M_.params(38))*(1-M_.params(41))*M_.params(91);
BHCB = M_.params( 90 );
M_.params( 92 ) = 1/(1+M_.params(60))*M_.params(96)/(M_.params(83)+M_.params(84)*(M_.params(38)-(1-M_.params(38))*(1-M_.params(41))*(M_.params(37)-1)));
DB = M_.params( 92 );
M_.params( 93 ) = M_.params(83)*M_.params(92);
CB = M_.params( 93 );
M_.params( 97 ) = (M_.params(92)*M_.params(38)*M_.params(46)*1/(M_.params(38)*(1-M_.params(46)))+1/((1-M_.params(46))*M_.params(85))*(1/(1+M_.params(60))*M_.params(96)-M_.params(46)*M_.params(93)))/(1/(1+M_.params(60))*1/((1-M_.params(46))*M_.params(85))+1/(M_.params(38)*(1-M_.params(46)))*1/(1+M_.params(61)));
ND = M_.params( 97 );
M_.params( 98 ) = M_.params(96)-M_.params(97);
NC = M_.params( 98 );
M_.params( 94 ) = 1/(M_.params(38)*(1-M_.params(46)))*(M_.params(97)-M_.params(92)*M_.params(38)*M_.params(46));
DS = M_.params( 94 );
M_.params( 95 ) = M_.params(85)*M_.params(94);
CS = M_.params( 95 );
M_.params( 99 ) = M_.params(98);
C = M_.params( 99 );
M_.params( 100 ) = M_.params(97)*1/M_.params(38);
D = M_.params( 100 );
M_.params( 86 ) = M_.params(93)/M_.params(99);
CBC = M_.params( 86 );
M_.params( 87 ) = M_.params(95)/M_.params(99);
CSC = M_.params( 87 );
M_.params( 88 ) = M_.params(92)/M_.params(100);
DBD = M_.params( 88 );
M_.params( 89 ) = M_.params(94)/M_.params(100);
DSD = M_.params( 89 );
M_.params( 101 ) = M_.params(98)/M_.params(93);
NCCB = M_.params( 101 );
M_.params( 102 ) = M_.params(97)/M_.params(93);
NDCB = M_.params( 102 );
M_.params( 62 ) = M_.params(83)*M_.params(35)*(1-M_.params(39))/(1-M_.params(35))^2*M_.params(84)^(-1)-(1-M_.params(38))*M_.params(40)*(1-M_.params(73))*((1-M_.params(65))*M_.params(35)*(log(M_.params(92))-log((1-M_.params(39))*M_.params(93)))-M_.params(35)/(1-M_.params(35)));
Lambda_b = M_.params( 62 );
M_.params( 63 ) = M_.params(84)^(-1)*M_.params(85)*M_.params(35)*(1-M_.params(39))/(1-M_.params(35))^2-(1-M_.params(38))*M_.params(37)*(1-M_.params(74))*((1-M_.params(65))*M_.params(35)*(log(M_.params(94))-log((1-M_.params(39))*M_.params(95)))-M_.params(35)/(1-M_.params(35)));
Lambda_s = M_.params( 63 );
thispath = cd;                                                           
cd('..');                                                                
load policy_param.mat;                                                   
for i=1:33                                                               
deep_parameter_name = M_.param_names(i,:);                           
eval(['M_.params(i)  = ' deep_parameter_name ' ;'])                  
end                                                                      
cd(thispath);  
M_.params( 34 ) = 1;
coffispol = M_.params( 34 );
%
% INITVAL instructions
%
options_.initval_file = 0;
oo_.steady_state( 15 ) = 0;
oo_.steady_state( 2 ) = 0;
oo_.steady_state( 30 ) = 0;
oo_.steady_state(77)=oo_.steady_state(73);
oo_.steady_state(78)=oo_.steady_state(77);
oo_.steady_state(79)=oo_.steady_state(78);
oo_.steady_state(80)=oo_.steady_state(74);
oo_.steady_state(81)=oo_.steady_state(80);
oo_.steady_state(82)=oo_.steady_state(81);
oo_.steady_state(83)=oo_.steady_state(75);
oo_.steady_state(84)=oo_.steady_state(83);
oo_.steady_state(85)=oo_.steady_state(84);
oo_.steady_state(86)=oo_.steady_state(4);
oo_.steady_state(87)=oo_.steady_state(86);
oo_.steady_state(88)=oo_.steady_state(75);
oo_.steady_state(89)=oo_.steady_state(88);
oo_.steady_state(90)=oo_.steady_state(89);
oo_.steady_state(91)=oo_.steady_state(74);
oo_.steady_state(92)=oo_.steady_state(91);
oo_.steady_state(93)=oo_.steady_state(92);
oo_.steady_state(94)=oo_.steady_state(71);
oo_.steady_state(95)=oo_.steady_state(94);
oo_.steady_state(96)=oo_.steady_state(95);
oo_.steady_state(97)=oo_.steady_state(73);
oo_.steady_state(98)=oo_.steady_state(97);
oo_.steady_state(99)=oo_.steady_state(98);
if M_.exo_nbr > 0
	oo_.exo_simul = ones(M_.maximum_lag,1)*oo_.exo_steady_state';
end
if M_.exo_det_nbr > 0
	oo_.exo_det_simul = ones(M_.maximum_lag,1)*oo_.exo_det_steady_state';
end
%
% SHOCKS instructions
%
M_.exo_det_length = 0;
M_.Sigma_e(1, 1) = (2.10)^2;
M_.Sigma_e(2, 2) = (0.67)^2;
M_.Sigma_e(3, 3) = (4.21)^2;
M_.Sigma_e(4, 4) = (0.92)^2;
M_.Sigma_e(5, 5) = (0.94)^2;
M_.Sigma_e(6, 6) = (10.70)^2;
M_.Sigma_e(7, 7) = (3.17)^2;
M_.Sigma_e(8, 8) = (0.55)^2;
M_.Sigma_e(9, 9) = (0.91)^2;
M_.Sigma_e(10, 10) = (1.42)^2;
M_.Sigma_e(11, 11) = (0.41)^2;
M_.Sigma_e(12, 12) = (0.72)^2;
M_.Sigma_e(14, 14) = (1.87)^2;
save('HK_FP13_results.mat', 'oo_', 'M_', 'options_');
if exist('estim_params_', 'var') == 1
  save('HK_FP13_results.mat', 'estim_params_', '-append');
end
if exist('bayestopt_', 'var') == 1
  save('HK_FP13_results.mat', 'bayestopt_', '-append');
end
if exist('dataset_', 'var') == 1
  save('HK_FP13_results.mat', 'dataset_', '-append');
end
if exist('estimation_info', 'var') == 1
  save('HK_FP13_results.mat', 'estimation_info', '-append');
end
if exist('dataset_info', 'var') == 1
  save('HK_FP13_results.mat', 'dataset_info', '-append');
end
if exist('oo_recursive_', 'var') == 1
  save('HK_FP13_results.mat', 'oo_recursive_', '-append');
end


disp(['Total computing time : ' dynsec2hms(toc(tic0)) ]);
if ~isempty(lastwarn)
  disp('Note: warning(s) encountered in MATLAB/Octave code')
end
diary off
