%
% Status : main Dynare file
%
% Warning : this file is generated automatically by Dynare
%           from model file (.mod)

if isoctave || matlab_ver_less_than('8.6')
    clear all
else
    clearvars -global
    clear_persistent_variables(fileparts(which('dynare')), false)
end
tic0 = tic;
% Save empty dates and dseries objects in memory.
dates('initialize');
dseries('initialize');
% Define global variables.
global M_ options_ oo_ estim_params_ bayestopt_ dataset_ dataset_info estimation_info ys0_ ex0_
options_ = [];
M_.fname = 'BRA_SAMBA08';
M_.dynare_version = '4.5.7';
oo_.dynare_version = '4.5.7';
options_.dynare_version = '4.5.7';
%
% Some global variables initialization
%
global_initialization;
diary off;
diary('BRA_SAMBA08.log');
M_.exo_names = 'pibar_';
M_.exo_names_tex = 'pibar\_';
M_.exo_names_long = 'pibar_';
M_.exo_names = char(M_.exo_names, 'gbar_');
M_.exo_names_tex = char(M_.exo_names_tex, 'gbar\_');
M_.exo_names_long = char(M_.exo_names_long, 'gbar_');
M_.exo_names = char(M_.exo_names, 'c_');
M_.exo_names_tex = char(M_.exo_names_tex, 'c\_');
M_.exo_names_long = char(M_.exo_names_long, 'c_');
M_.exo_names = char(M_.exo_names, 'n_');
M_.exo_names_tex = char(M_.exo_names_tex, 'n\_');
M_.exo_names_long = char(M_.exo_names_long, 'n_');
M_.exo_names = char(M_.exo_names, 'i_');
M_.exo_names_tex = char(M_.exo_names_tex, 'i\_');
M_.exo_names_long = char(M_.exo_names_long, 'i_');
M_.exo_names = char(M_.exo_names, 'fiistar_');
M_.exo_names_tex = char(M_.exo_names_tex, 'fiistar\_');
M_.exo_names_long = char(M_.exo_names_long, 'fiistar_');
M_.exo_names = char(M_.exo_names, 'fii_');
M_.exo_names_tex = char(M_.exo_names_tex, 'fii\_');
M_.exo_names_long = char(M_.exo_names_long, 'fii_');
M_.exo_names = char(M_.exo_names, 'a_');
M_.exo_names_tex = char(M_.exo_names_tex, 'a\_');
M_.exo_names_long = char(M_.exo_names_long, 'a_');
M_.exo_names = char(M_.exo_names, 'mstar_');
M_.exo_names_tex = char(M_.exo_names_tex, 'mstar\_');
M_.exo_names_long = char(M_.exo_names_long, 'mstar_');
M_.exo_names = char(M_.exo_names, 'pistar_');
M_.exo_names_tex = char(M_.exo_names_tex, 'pistar\_');
M_.exo_names_long = char(M_.exo_names_long, 'pistar_');
M_.exo_names = char(M_.exo_names, 'rstar_');
M_.exo_names_tex = char(M_.exo_names_tex, 'rstar\_');
M_.exo_names_long = char(M_.exo_names_long, 'rstar_');
M_.exo_names = char(M_.exo_names, 'r_');
M_.exo_names_tex = char(M_.exo_names_tex, 'r\_');
M_.exo_names_long = char(M_.exo_names_long, 'r_');
M_.exo_names = char(M_.exo_names, 'interest_');
M_.exo_names_tex = char(M_.exo_names_tex, 'interest\_');
M_.exo_names_long = char(M_.exo_names_long, 'interest_');
M_.exo_names = char(M_.exo_names, 'fiscal_');
M_.exo_names_tex = char(M_.exo_names_tex, 'fiscal\_');
M_.exo_names_long = char(M_.exo_names_long, 'fiscal_');
M_.endo_names = 'co';
M_.endo_names_tex = 'co';
M_.endo_names_long = 'co';
M_.endo_names = char(M_.endo_names, 'crot');
M_.endo_names_tex = char(M_.endo_names_tex, 'crot');
M_.endo_names_long = char(M_.endo_names_long, 'crot');
M_.endo_names = char(M_.endo_names, 'c');
M_.endo_names_tex = char(M_.endo_names_tex, 'c');
M_.endo_names_long = char(M_.endo_names_long, 'c');
M_.endo_names = char(M_.endo_names, 'no');
M_.endo_names_tex = char(M_.endo_names_tex, 'no');
M_.endo_names_long = char(M_.endo_names_long, 'no');
M_.endo_names = char(M_.endo_names, 'nrot');
M_.endo_names_tex = char(M_.endo_names_tex, 'nrot');
M_.endo_names_long = char(M_.endo_names_long, 'nrot');
M_.endo_names = char(M_.endo_names, 'n');
M_.endo_names_tex = char(M_.endo_names_tex, 'n');
M_.endo_names_long = char(M_.endo_names_long, 'n');
M_.endo_names = char(M_.endo_names, 'q');
M_.endo_names_tex = char(M_.endo_names_tex, 'q');
M_.endo_names_long = char(M_.endo_names_long, 'q');
M_.endo_names = char(M_.endo_names, 'wr');
M_.endo_names_tex = char(M_.endo_names_tex, 'wr');
M_.endo_names_long = char(M_.endo_names_long, 'wr');
M_.endo_names = char(M_.endo_names, 'k');
M_.endo_names_tex = char(M_.endo_names_tex, 'k');
M_.endo_names_long = char(M_.endo_names_long, 'k');
M_.endo_names = char(M_.endo_names, 'u');
M_.endo_names_tex = char(M_.endo_names_tex, 'u');
M_.endo_names_long = char(M_.endo_names_long, 'u');
M_.endo_names = char(M_.endo_names, 'fii');
M_.endo_names_tex = char(M_.endo_names_tex, 'fii');
M_.endo_names_long = char(M_.endo_names_long, 'fii');
M_.endo_names = char(M_.endo_names, 'qi');
M_.endo_names_tex = char(M_.endo_names_tex, 'qi');
M_.endo_names_long = char(M_.endo_names_long, 'qi');
M_.endo_names = char(M_.endo_names, 'i');
M_.endo_names_tex = char(M_.endo_names_tex, 'i');
M_.endo_names_long = char(M_.endo_names_long, 'i');
M_.endo_names = char(M_.endo_names, 'x');
M_.endo_names_tex = char(M_.endo_names_tex, 'x');
M_.endo_names_long = char(M_.endo_names_long, 'x');
M_.endo_names = char(M_.endo_names, 'm');
M_.endo_names_tex = char(M_.endo_names_tex, 'm');
M_.endo_names_long = char(M_.endo_names_long, 'm');
M_.endo_names = char(M_.endo_names, 'rk');
M_.endo_names_tex = char(M_.endo_names_tex, 'rk');
M_.endo_names_long = char(M_.endo_names_long, 'rk');
M_.endo_names = char(M_.endo_names, 'mc');
M_.endo_names_tex = char(M_.endo_names_tex, 'mc');
M_.endo_names_long = char(M_.endo_names_long, 'mc');
M_.endo_names = char(M_.endo_names, 'pi');
M_.endo_names_tex = char(M_.endo_names_tex, 'pi');
M_.endo_names_long = char(M_.endo_names_long, 'pi');
M_.endo_names = char(M_.endo_names, 'bystar');
M_.endo_names_tex = char(M_.endo_names_tex, 'bystar');
M_.endo_names_long = char(M_.endo_names_long, 'bystar');
M_.endo_names = char(M_.endo_names, 'nxy');
M_.endo_names_tex = char(M_.endo_names_tex, 'nxy');
M_.endo_names_long = char(M_.endo_names_long, 'nxy');
M_.endo_names = char(M_.endo_names, 'r');
M_.endo_names_tex = char(M_.endo_names_tex, 'r');
M_.endo_names_long = char(M_.endo_names_long, 'r');
M_.endo_names = char(M_.endo_names, 'gy');
M_.endo_names_tex = char(M_.endo_names_tex, 'gy');
M_.endo_names_long = char(M_.endo_names_long, 'gy');
M_.endo_names = char(M_.endo_names, 'syhat');
M_.endo_names_tex = char(M_.endo_names_tex, 'syhat');
M_.endo_names_long = char(M_.endo_names_long, 'syhat');
M_.endo_names = char(M_.endo_names, 'bby');
M_.endo_names_tex = char(M_.endo_names_tex, 'bby');
M_.endo_names_long = char(M_.endo_names_long, 'bby');
M_.endo_names = char(M_.endo_names, 'g');
M_.endo_names_tex = char(M_.endo_names_tex, 'g');
M_.endo_names_long = char(M_.endo_names_long, 'g');
M_.endo_names = char(M_.endo_names, 'y');
M_.endo_names_tex = char(M_.endo_names_tex, 'y');
M_.endo_names_long = char(M_.endo_names_long, 'y');
M_.endo_names = char(M_.endo_names, 'yva');
M_.endo_names_tex = char(M_.endo_names_tex, 'yva');
M_.endo_names_long = char(M_.endo_names_long, 'yva');
M_.endo_names = char(M_.endo_names, 'piva');
M_.endo_names_tex = char(M_.endo_names_tex, 'piva');
M_.endo_names_long = char(M_.endo_names_long, 'piva');
M_.endo_names = char(M_.endo_names, 'pibar');
M_.endo_names_tex = char(M_.endo_names_tex, 'pibar');
M_.endo_names_long = char(M_.endo_names_long, 'pibar');
M_.endo_names = char(M_.endo_names, 'sgbar');
M_.endo_names_tex = char(M_.endo_names_tex, 'sgbar');
M_.endo_names_long = char(M_.endo_names_long, 'sgbar');
M_.endo_names = char(M_.endo_names, 'zc');
M_.endo_names_tex = char(M_.endo_names_tex, 'zc');
M_.endo_names_long = char(M_.endo_names_long, 'zc');
M_.endo_names = char(M_.endo_names, 'zn');
M_.endo_names_tex = char(M_.endo_names_tex, 'zn');
M_.endo_names_long = char(M_.endo_names_long, 'zn');
M_.endo_names = char(M_.endo_names, 'zi');
M_.endo_names_tex = char(M_.endo_names_tex, 'zi');
M_.endo_names_long = char(M_.endo_names_long, 'zi');
M_.endo_names = char(M_.endo_names, 'zfiistar');
M_.endo_names_tex = char(M_.endo_names_tex, 'zfiistar');
M_.endo_names_long = char(M_.endo_names_long, 'zfiistar');
M_.endo_names = char(M_.endo_names, 'zfii');
M_.endo_names_tex = char(M_.endo_names_tex, 'zfii');
M_.endo_names_long = char(M_.endo_names_long, 'zfii');
M_.endo_names = char(M_.endo_names, 'a');
M_.endo_names_tex = char(M_.endo_names_tex, 'a');
M_.endo_names_long = char(M_.endo_names_long, 'a');
M_.endo_names = char(M_.endo_names, 'zr');
M_.endo_names_tex = char(M_.endo_names_tex, 'zr');
M_.endo_names_long = char(M_.endo_names_long, 'zr');
M_.endo_names = char(M_.endo_names, 'zg');
M_.endo_names_tex = char(M_.endo_names_tex, 'zg');
M_.endo_names_long = char(M_.endo_names_long, 'zg');
M_.endo_names = char(M_.endo_names, 'mstar');
M_.endo_names_tex = char(M_.endo_names_tex, 'mstar');
M_.endo_names_long = char(M_.endo_names_long, 'mstar');
M_.endo_names = char(M_.endo_names, 'pistar');
M_.endo_names_tex = char(M_.endo_names_tex, 'pistar');
M_.endo_names_long = char(M_.endo_names_long, 'pistar');
M_.endo_names = char(M_.endo_names, 'rstar');
M_.endo_names_tex = char(M_.endo_names_tex, 'rstar');
M_.endo_names_long = char(M_.endo_names_long, 'rstar');
M_.endo_names = char(M_.endo_names, 'g_');
M_.endo_names_tex = char(M_.endo_names_tex, 'g\_');
M_.endo_names_long = char(M_.endo_names_long, 'g_');
M_.endo_names = char(M_.endo_names, 'interest');
M_.endo_names_tex = char(M_.endo_names_tex, 'interest');
M_.endo_names_long = char(M_.endo_names_long, 'interest');
M_.endo_names = char(M_.endo_names, 'inflation');
M_.endo_names_tex = char(M_.endo_names_tex, 'inflation');
M_.endo_names_long = char(M_.endo_names_long, 'inflation');
M_.endo_names = char(M_.endo_names, 'inflationq');
M_.endo_names_tex = char(M_.endo_names_tex, 'inflationq');
M_.endo_names_long = char(M_.endo_names_long, 'inflationq');
M_.endo_names = char(M_.endo_names, 'outputgap');
M_.endo_names_tex = char(M_.endo_names_tex, 'outputgap');
M_.endo_names_long = char(M_.endo_names_long, 'outputgap');
M_.endo_names = char(M_.endo_names, 'output');
M_.endo_names_tex = char(M_.endo_names_tex, 'output');
M_.endo_names_long = char(M_.endo_names_long, 'output');
M_.endo_names = char(M_.endo_names, 'fispol');
M_.endo_names_tex = char(M_.endo_names_tex, 'fispol');
M_.endo_names_long = char(M_.endo_names_long, 'fispol');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_88');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_88');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_88');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_92');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_92');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_92');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_96');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_96');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_96');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_123');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_123');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_123');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_127');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_127');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_127');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_131');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_131');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_131');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_158');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_158');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_158');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_162');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_162');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_162');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_166');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_166');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_166');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_17_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_17\_1');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_17_1');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_17_2');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_17\_2');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_17_2');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_46_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_46\_1');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_46_1');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_46_2');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_46\_2');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_46_2');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_46_3');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_46\_3');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_46_3');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_45_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_45\_1');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_45_1');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_45_2');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_45\_2');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_45_2');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_45_3');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_45\_3');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_45_3');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_42_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_42\_1');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_42_1');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_42_2');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_42\_2');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_42_2');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_42_3');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_42\_3');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_42_3');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_44_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_44\_1');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_44_1');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_44_2');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_44\_2');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_44_2');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_44_3');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_44\_3');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_44_3');
M_.endo_partitions = struct();
M_.param_names = 'cofintintb1';
M_.param_names_tex = 'cofintintb1';
M_.param_names_long = 'cofintintb1';
M_.param_names = char(M_.param_names, 'cofintintb2');
M_.param_names_tex = char(M_.param_names_tex, 'cofintintb2');
M_.param_names_long = char(M_.param_names_long, 'cofintintb2');
M_.param_names = char(M_.param_names, 'cofintintb3');
M_.param_names_tex = char(M_.param_names_tex, 'cofintintb3');
M_.param_names_long = char(M_.param_names_long, 'cofintintb3');
M_.param_names = char(M_.param_names, 'cofintintb4');
M_.param_names_tex = char(M_.param_names_tex, 'cofintintb4');
M_.param_names_long = char(M_.param_names_long, 'cofintintb4');
M_.param_names = char(M_.param_names, 'cofintinf0');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinf0');
M_.param_names_long = char(M_.param_names_long, 'cofintinf0');
M_.param_names = char(M_.param_names, 'cofintinfb1');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinfb1');
M_.param_names_long = char(M_.param_names_long, 'cofintinfb1');
M_.param_names = char(M_.param_names, 'cofintinfb2');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinfb2');
M_.param_names_long = char(M_.param_names_long, 'cofintinfb2');
M_.param_names = char(M_.param_names, 'cofintinfb3');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinfb3');
M_.param_names_long = char(M_.param_names_long, 'cofintinfb3');
M_.param_names = char(M_.param_names, 'cofintinfb4');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinfb4');
M_.param_names_long = char(M_.param_names_long, 'cofintinfb4');
M_.param_names = char(M_.param_names, 'cofintinff1');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinff1');
M_.param_names_long = char(M_.param_names_long, 'cofintinff1');
M_.param_names = char(M_.param_names, 'cofintinff2');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinff2');
M_.param_names_long = char(M_.param_names_long, 'cofintinff2');
M_.param_names = char(M_.param_names, 'cofintinff3');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinff3');
M_.param_names_long = char(M_.param_names_long, 'cofintinff3');
M_.param_names = char(M_.param_names, 'cofintinff4');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinff4');
M_.param_names_long = char(M_.param_names_long, 'cofintinff4');
M_.param_names = char(M_.param_names, 'cofintout');
M_.param_names_tex = char(M_.param_names_tex, 'cofintout');
M_.param_names_long = char(M_.param_names_long, 'cofintout');
M_.param_names = char(M_.param_names, 'cofintoutb1');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutb1');
M_.param_names_long = char(M_.param_names_long, 'cofintoutb1');
M_.param_names = char(M_.param_names, 'cofintoutb2');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutb2');
M_.param_names_long = char(M_.param_names_long, 'cofintoutb2');
M_.param_names = char(M_.param_names, 'cofintoutb3');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutb3');
M_.param_names_long = char(M_.param_names_long, 'cofintoutb3');
M_.param_names = char(M_.param_names, 'cofintoutb4');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutb4');
M_.param_names_long = char(M_.param_names_long, 'cofintoutb4');
M_.param_names = char(M_.param_names, 'cofintoutf1');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutf1');
M_.param_names_long = char(M_.param_names_long, 'cofintoutf1');
M_.param_names = char(M_.param_names, 'cofintoutf2');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutf2');
M_.param_names_long = char(M_.param_names_long, 'cofintoutf2');
M_.param_names = char(M_.param_names, 'cofintoutf3');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutf3');
M_.param_names_long = char(M_.param_names_long, 'cofintoutf3');
M_.param_names = char(M_.param_names, 'cofintoutf4');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutf4');
M_.param_names_long = char(M_.param_names_long, 'cofintoutf4');
M_.param_names = char(M_.param_names, 'cofintoutp');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutp');
M_.param_names_long = char(M_.param_names_long, 'cofintoutp');
M_.param_names = char(M_.param_names, 'cofintoutpb1');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpb1');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpb1');
M_.param_names = char(M_.param_names, 'cofintoutpb2');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpb2');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpb2');
M_.param_names = char(M_.param_names, 'cofintoutpb3');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpb3');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpb3');
M_.param_names = char(M_.param_names, 'cofintoutpb4');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpb4');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpb4');
M_.param_names = char(M_.param_names, 'cofintoutpf1');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpf1');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpf1');
M_.param_names = char(M_.param_names, 'cofintoutpf2');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpf2');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpf2');
M_.param_names = char(M_.param_names, 'cofintoutpf3');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpf3');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpf3');
M_.param_names = char(M_.param_names, 'cofintoutpf4');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpf4');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpf4');
M_.param_names = char(M_.param_names, 'std_r_');
M_.param_names_tex = char(M_.param_names_tex, 'std\_r\_');
M_.param_names_long = char(M_.param_names_long, 'std_r_');
M_.param_names = char(M_.param_names, 'std_r_quart');
M_.param_names_tex = char(M_.param_names_tex, 'std\_r\_quart');
M_.param_names_long = char(M_.param_names_long, 'std_r_quart');
M_.param_names = char(M_.param_names, 'coffispol');
M_.param_names_tex = char(M_.param_names_tex, 'coffispol');
M_.param_names_long = char(M_.param_names_long, 'coffispol');
M_.param_names = char(M_.param_names, 'beta');
M_.param_names_tex = char(M_.param_names_tex, 'beta');
M_.param_names_long = char(M_.param_names_long, 'beta');
M_.param_names = char(M_.param_names, 'alpha');
M_.param_names_tex = char(M_.param_names_tex, 'alpha');
M_.param_names_long = char(M_.param_names_long, 'alpha');
M_.param_names = char(M_.param_names, 'sigma');
M_.param_names_tex = char(M_.param_names_tex, 'sigma');
M_.param_names_long = char(M_.param_names_long, 'sigma');
M_.param_names = char(M_.param_names, 'pessi');
M_.param_names_tex = char(M_.param_names_tex, 'pessi');
M_.param_names_long = char(M_.param_names_long, 'pessi');
M_.param_names = char(M_.param_names, 'kappa');
M_.param_names_tex = char(M_.param_names_tex, 'kappa');
M_.param_names_long = char(M_.param_names_long, 'kappa');
M_.param_names = char(M_.param_names, 'h');
M_.param_names_tex = char(M_.param_names_tex, 'h');
M_.param_names_long = char(M_.param_names_long, 'h');
M_.param_names = char(M_.param_names, 'omegabarb');
M_.param_names_tex = char(M_.param_names_tex, 'omegabarb');
M_.param_names_long = char(M_.param_names_long, 'omegabarb');
M_.param_names = char(M_.param_names, 'tet');
M_.param_names_tex = char(M_.param_names_tex, 'tet');
M_.param_names_long = char(M_.param_names_long, 'tet');
M_.param_names = char(M_.param_names, 'nuu');
M_.param_names_tex = char(M_.param_names_tex, 'nuu');
M_.param_names_long = char(M_.param_names_long, 'nuu');
M_.param_names = char(M_.param_names, 'kuu');
M_.param_names_tex = char(M_.param_names_tex, 'kuu');
M_.param_names_long = char(M_.param_names_long, 'kuu');
M_.param_names = char(M_.param_names, 'vi');
M_.param_names_tex = char(M_.param_names_tex, 'vi');
M_.param_names_long = char(M_.param_names_long, 'vi');
M_.param_names = char(M_.param_names, 'del');
M_.param_names_tex = char(M_.param_names_tex, 'del');
M_.param_names_long = char(M_.param_names_long, 'del');
M_.param_names = char(M_.param_names, 'dela');
M_.param_names_tex = char(M_.param_names_tex, 'dela');
M_.param_names_long = char(M_.param_names_long, 'dela');
M_.param_names = char(M_.param_names, 'dels');
M_.param_names_tex = char(M_.param_names_tex, 'dels');
M_.param_names_long = char(M_.param_names_long, 'dels');
M_.param_names = char(M_.param_names, 'sc');
M_.param_names_tex = char(M_.param_names_tex, 'sc');
M_.param_names_long = char(M_.param_names_long, 'sc');
M_.param_names = char(M_.param_names, 'si');
M_.param_names_tex = char(M_.param_names_tex, 'si');
M_.param_names_long = char(M_.param_names_long, 'si');
M_.param_names = char(M_.param_names, 'sg');
M_.param_names_tex = char(M_.param_names_tex, 'sg');
M_.param_names_long = char(M_.param_names_long, 'sg');
M_.param_names = char(M_.param_names, 'sm');
M_.param_names_tex = char(M_.param_names_tex, 'sm');
M_.param_names_long = char(M_.param_names_long, 'sm');
M_.param_names = char(M_.param_names, 'sx');
M_.param_names_tex = char(M_.param_names_tex, 'sx');
M_.param_names_long = char(M_.param_names_long, 'sx');
M_.param_names = char(M_.param_names, 'sva');
M_.param_names_tex = char(M_.param_names_tex, 'sva');
M_.param_names_long = char(M_.param_names_long, 'sva');
M_.param_names = char(M_.param_names, 'sd');
M_.param_names_tex = char(M_.param_names_tex, 'sd');
M_.param_names_long = char(M_.param_names_long, 'sd');
M_.param_names = char(M_.param_names, 'omegabarc');
M_.param_names_tex = char(M_.param_names_tex, 'omegabarc');
M_.param_names_long = char(M_.param_names_long, 'omegabarc');
M_.param_names = char(M_.param_names, 'omegabarn');
M_.param_names_tex = char(M_.param_names_tex, 'omegabarn');
M_.param_names_long = char(M_.param_names_long, 'omegabarn');
M_.param_names = char(M_.param_names, 'iok');
M_.param_names_tex = char(M_.param_names_tex, 'iok');
M_.param_names_long = char(M_.param_names_long, 'iok');
M_.param_names = char(M_.param_names, 'fiistar');
M_.param_names_tex = char(M_.param_names_tex, 'fiistar');
M_.param_names_long = char(M_.param_names_long, 'fiistar');
M_.param_names = char(M_.param_names, 'rstarC');
M_.param_names_tex = char(M_.param_names_tex, 'rstarC');
M_.param_names_long = char(M_.param_names_long, 'rstarC');
M_.param_names = char(M_.param_names, 'bystarC');
M_.param_names_tex = char(M_.param_names_tex, 'bystarC');
M_.param_names_long = char(M_.param_names_long, 'bystarC');
M_.param_names = char(M_.param_names, 'rC');
M_.param_names_tex = char(M_.param_names_tex, 'rC');
M_.param_names_long = char(M_.param_names_long, 'rC');
M_.param_names = char(M_.param_names, 'byC');
M_.param_names_tex = char(M_.param_names_tex, 'byC');
M_.param_names_long = char(M_.param_names_long, 'byC');
M_.param_names = char(M_.param_names, 'gamar');
M_.param_names_tex = char(M_.param_names_tex, 'gamar');
M_.param_names_long = char(M_.param_names_long, 'gamar');
M_.param_names = char(M_.param_names, 'gamapi');
M_.param_names_tex = char(M_.param_names_tex, 'gamapi');
M_.param_names_long = char(M_.param_names_long, 'gamapi');
M_.param_names = char(M_.param_names, 'gamay');
M_.param_names_tex = char(M_.param_names_tex, 'gamay');
M_.param_names_long = char(M_.param_names_long, 'gamay');
M_.param_names = char(M_.param_names, 'gamag');
M_.param_names_tex = char(M_.param_names_tex, 'gamag');
M_.param_names_long = char(M_.param_names_long, 'gamag');
M_.param_names = char(M_.param_names, 'gamas');
M_.param_names_tex = char(M_.param_names_tex, 'gamas');
M_.param_names_long = char(M_.param_names_long, 'gamas');
M_.param_names = char(M_.param_names, 'gamab');
M_.param_names_tex = char(M_.param_names_tex, 'gamab');
M_.param_names_long = char(M_.param_names_long, 'gamab');
M_.param_names = char(M_.param_names, 'rhoa');
M_.param_names_tex = char(M_.param_names_tex, 'rhoa');
M_.param_names_long = char(M_.param_names_long, 'rhoa');
M_.param_names = char(M_.param_names, 'rhoc');
M_.param_names_tex = char(M_.param_names_tex, 'rhoc');
M_.param_names_long = char(M_.param_names_long, 'rhoc');
M_.param_names = char(M_.param_names, 'rhoi');
M_.param_names_tex = char(M_.param_names_tex, 'rhoi');
M_.param_names_long = char(M_.param_names_long, 'rhoi');
M_.param_names = char(M_.param_names, 'rhon');
M_.param_names_tex = char(M_.param_names_tex, 'rhon');
M_.param_names_long = char(M_.param_names_long, 'rhon');
M_.param_names = char(M_.param_names, 'rhoq');
M_.param_names_tex = char(M_.param_names_tex, 'rhoq');
M_.param_names_long = char(M_.param_names_long, 'rhoq');
M_.param_names = char(M_.param_names, 'rhor');
M_.param_names_tex = char(M_.param_names_tex, 'rhor');
M_.param_names_long = char(M_.param_names_long, 'rhor');
M_.param_names = char(M_.param_names, 'rhog');
M_.param_names_tex = char(M_.param_names_tex, 'rhog');
M_.param_names_long = char(M_.param_names_long, 'rhog');
M_.param_names = char(M_.param_names, 'rhosbar');
M_.param_names_tex = char(M_.param_names_tex, 'rhosbar');
M_.param_names_long = char(M_.param_names_long, 'rhosbar');
M_.param_names = char(M_.param_names, 'rhopi');
M_.param_names_tex = char(M_.param_names_tex, 'rhopi');
M_.param_names_long = char(M_.param_names_long, 'rhopi');
M_.param_names = char(M_.param_names, 'rhofii');
M_.param_names_tex = char(M_.param_names_tex, 'rhofii');
M_.param_names_long = char(M_.param_names_long, 'rhofii');
M_.param_names = char(M_.param_names, 'rhofiistar');
M_.param_names_tex = char(M_.param_names_tex, 'rhofiistar');
M_.param_names_long = char(M_.param_names_long, 'rhofiistar');
M_.param_names = char(M_.param_names, 'rhomstar');
M_.param_names_tex = char(M_.param_names_tex, 'rhomstar');
M_.param_names_long = char(M_.param_names_long, 'rhomstar');
M_.param_names = char(M_.param_names, 'rhorstar');
M_.param_names_tex = char(M_.param_names_tex, 'rhorstar');
M_.param_names_long = char(M_.param_names_long, 'rhorstar');
M_.param_names = char(M_.param_names, 'rhopistar');
M_.param_names_tex = char(M_.param_names_tex, 'rhopistar');
M_.param_names_long = char(M_.param_names_long, 'rhopistar');
M_.param_partitions = struct();
M_.exo_det_nbr = 0;
M_.exo_nbr = 14;
M_.endo_nbr = 71;
M_.param_nbr = 83;
M_.orig_endo_nbr = 48;
M_.aux_vars(1).endo_index = 49;
M_.aux_vars(1).type = 0;
M_.aux_vars(2).endo_index = 50;
M_.aux_vars(2).type = 0;
M_.aux_vars(3).endo_index = 51;
M_.aux_vars(3).type = 0;
M_.aux_vars(4).endo_index = 52;
M_.aux_vars(4).type = 0;
M_.aux_vars(5).endo_index = 53;
M_.aux_vars(5).type = 0;
M_.aux_vars(6).endo_index = 54;
M_.aux_vars(6).type = 0;
M_.aux_vars(7).endo_index = 55;
M_.aux_vars(7).type = 0;
M_.aux_vars(8).endo_index = 56;
M_.aux_vars(8).type = 0;
M_.aux_vars(9).endo_index = 57;
M_.aux_vars(9).type = 0;
M_.aux_vars(10).endo_index = 58;
M_.aux_vars(10).type = 1;
M_.aux_vars(10).orig_index = 18;
M_.aux_vars(10).orig_lead_lag = -1;
M_.aux_vars(11).endo_index = 59;
M_.aux_vars(11).type = 1;
M_.aux_vars(11).orig_index = 18;
M_.aux_vars(11).orig_lead_lag = -2;
M_.aux_vars(12).endo_index = 60;
M_.aux_vars(12).type = 1;
M_.aux_vars(12).orig_index = 47;
M_.aux_vars(12).orig_lead_lag = -1;
M_.aux_vars(13).endo_index = 61;
M_.aux_vars(13).type = 1;
M_.aux_vars(13).orig_index = 47;
M_.aux_vars(13).orig_lead_lag = -2;
M_.aux_vars(14).endo_index = 62;
M_.aux_vars(14).type = 1;
M_.aux_vars(14).orig_index = 47;
M_.aux_vars(14).orig_lead_lag = -3;
M_.aux_vars(15).endo_index = 63;
M_.aux_vars(15).type = 1;
M_.aux_vars(15).orig_index = 46;
M_.aux_vars(15).orig_lead_lag = -1;
M_.aux_vars(16).endo_index = 64;
M_.aux_vars(16).type = 1;
M_.aux_vars(16).orig_index = 46;
M_.aux_vars(16).orig_lead_lag = -2;
M_.aux_vars(17).endo_index = 65;
M_.aux_vars(17).type = 1;
M_.aux_vars(17).orig_index = 46;
M_.aux_vars(17).orig_lead_lag = -3;
M_.aux_vars(18).endo_index = 66;
M_.aux_vars(18).type = 1;
M_.aux_vars(18).orig_index = 43;
M_.aux_vars(18).orig_lead_lag = -1;
M_.aux_vars(19).endo_index = 67;
M_.aux_vars(19).type = 1;
M_.aux_vars(19).orig_index = 43;
M_.aux_vars(19).orig_lead_lag = -2;
M_.aux_vars(20).endo_index = 68;
M_.aux_vars(20).type = 1;
M_.aux_vars(20).orig_index = 43;
M_.aux_vars(20).orig_lead_lag = -3;
M_.aux_vars(21).endo_index = 69;
M_.aux_vars(21).type = 1;
M_.aux_vars(21).orig_index = 45;
M_.aux_vars(21).orig_lead_lag = -1;
M_.aux_vars(22).endo_index = 70;
M_.aux_vars(22).type = 1;
M_.aux_vars(22).orig_index = 45;
M_.aux_vars(22).orig_lead_lag = -2;
M_.aux_vars(23).endo_index = 71;
M_.aux_vars(23).type = 1;
M_.aux_vars(23).orig_index = 45;
M_.aux_vars(23).orig_lead_lag = -3;
M_.Sigma_e = zeros(14, 14);
M_.Correlation_matrix = eye(14, 14);
M_.H = 0;
M_.Correlation_matrix_ME = 1;
M_.sigma_e_is_diagonal = 1;
M_.det_shocks = [];
options_.linear = 1;
options_.block=0;
options_.bytecode=0;
options_.use_dll=0;
M_.hessian_eq_zero = 1;
erase_compiled_function('BRA_SAMBA08_static');
erase_compiled_function('BRA_SAMBA08_dynamic');
M_.orig_eq_nbr = 48;
M_.eq_nbr = 71;
M_.ramsey_eq_nbr = 0;
M_.set_auxiliary_variables = exist(['./' M_.fname '_set_auxiliary_variables.m'], 'file') == 2;
M_.lead_lag_incidence = [
 1 43 114;
 2 44 0;
 0 45 0;
 0 46 0;
 0 47 0;
 0 48 0;
 3 49 115;
 0 50 0;
 4 51 0;
 0 52 0;
 0 53 0;
 0 54 116;
 5 55 117;
 0 56 0;
 0 57 0;
 0 58 118;
 0 59 0;
 6 60 119;
 7 61 0;
 0 62 0;
 0 63 0;
 8 64 0;
 9 65 0;
 10 66 0;
 0 67 0;
 0 68 0;
 11 69 0;
 0 70 0;
 12 71 0;
 13 72 0;
 14 73 0;
 15 74 0;
 16 75 0;
 17 76 0;
 18 77 0;
 19 78 0;
 20 79 0;
 21 80 0;
 22 81 0;
 23 82 120;
 24 83 0;
 0 84 0;
 25 85 0;
 0 86 0;
 26 87 121;
 27 88 122;
 28 89 123;
 0 90 0;
 0 91 124;
 0 92 125;
 0 93 126;
 0 94 127;
 0 95 128;
 0 96 129;
 0 97 130;
 0 98 131;
 0 99 132;
 29 100 0;
 30 101 0;
 31 102 0;
 32 103 0;
 33 104 0;
 34 105 0;
 35 106 0;
 36 107 0;
 37 108 0;
 38 109 0;
 39 110 0;
 40 111 0;
 41 112 0;
 42 113 0;]';
M_.nstatic = 18;
M_.nfwrd   = 11;
M_.npred   = 34;
M_.nboth   = 8;
M_.nsfwrd   = 19;
M_.nspred   = 42;
M_.ndynamic   = 53;
M_.equations_tags = {
};
M_.static_and_dynamic_models_differ = 0;
M_.exo_names_orig_ord = [1:14];
M_.maximum_lag = 1;
M_.maximum_lead = 1;
M_.maximum_endo_lag = 1;
M_.maximum_endo_lead = 1;
oo_.steady_state = zeros(71, 1);
M_.maximum_exo_lag = 0;
M_.maximum_exo_lead = 0;
oo_.exo_steady_state = zeros(14, 1);
M_.params = NaN(83, 1);
M_.NNZDerivatives = [261; 0; -1];
M_.params( 35 ) = 0.98;
beta = M_.params( 35 );
M_.params( 36 ) = 0.4;
alpha = M_.params( 36 );
M_.params( 37 ) = 0.823;
sigma = M_.params( 37 );
M_.params( 38 ) = 0.04;
pessi = M_.params( 38 );
M_.params( 39 ) = 1.014;
kappa = M_.params( 39 );
M_.params( 40 ) = 0.218;
h = M_.params( 40 );
M_.params( 41 ) = 0.239;
omegabarb = M_.params( 41 );
M_.params( 42 ) = 0.906;
tet = M_.params( 42 );
M_.params( 43 ) = 0.338;
nuu = M_.params( 43 );
M_.params( 44 ) = 1.406;
kuu = M_.params( 44 );
M_.params( 45 ) = 0.672;
vi = M_.params( 45 );
M_.params( 46 ) = 0.025;
del = M_.params( 46 );
M_.params( 47 ) = 1;
dela = M_.params( 47 );
M_.params( 48 ) = 3.997;
dels = M_.params( 48 );
M_.params( 49 ) = 0.555;
sc = M_.params( 49 );
M_.params( 50 ) = 0.147;
si = M_.params( 50 );
M_.params( 51 ) = 0.176;
sg = M_.params( 51 );
M_.params( 52 ) = 0.109;
sm = M_.params( 52 );
M_.params( 53 ) = 0.121;
sx = M_.params( 53 );
M_.params( 54 ) = 0.891;
sva = M_.params( 54 );
M_.params( 55 ) = 0.891;
sd = M_.params( 55 );
M_.params( 56 ) = 0.4;
omegabarc = M_.params( 56 );
M_.params( 57 ) = 0.8;
omegabarn = M_.params( 57 );
M_.params( 58 ) = 0.03;
iok = M_.params( 58 );
M_.params( 59 ) = 1.016;
fiistar = M_.params( 59 );
M_.params( 60 ) = 1.009;
rstarC = M_.params( 60 );
M_.params( 61 ) = 0.033;
bystarC = M_.params( 61 );
M_.params( 62 ) = 1.042;
rC = M_.params( 62 );
M_.params( 63 ) = 1.028;
byC = M_.params( 63 );
M_.params( 64 ) = 0.682;
gamar = M_.params( 64 );
M_.params( 65 ) = 1.523;
gamapi = M_.params( 65 );
M_.params( 66 ) = 0.839;
gamay = M_.params( 66 );
M_.params( 67 ) = 0.695;
gamag = M_.params( 67 );
M_.params( 68 ) = 0.465;
gamas = M_.params( 68 );
M_.params( 69 ) = 0.17;
gamab = M_.params( 69 );
M_.params( 70 ) = 0.985;
rhoa = M_.params( 70 );
M_.params( 71 ) = 0.7;
rhoc = M_.params( 71 );
M_.params( 72 ) = 0.28;
rhoi = M_.params( 72 );
M_.params( 73 ) = 0.74;
rhon = M_.params( 73 );
M_.params( 74 ) = 0.0;
rhoq = M_.params( 74 );
M_.params( 75 ) = 0.0;
rhor = M_.params( 75 );
M_.params( 76 ) = 0.0;
rhog = M_.params( 76 );
M_.params( 77 ) = 0.915;
rhosbar = M_.params( 77 );
M_.params( 78 ) = 0.937;
rhopi = M_.params( 78 );
M_.params( 79 ) = 0.867;
rhofii = M_.params( 79 );
M_.params( 80 ) = 0.64;
rhofiistar = M_.params( 80 );
M_.params( 81 ) = 0.257;
rhomstar = M_.params( 81 );
M_.params( 82 ) = 0.848;
rhorstar = M_.params( 82 );
M_.params( 83 ) = (-0.139);
rhopistar = M_.params( 83 );
thispath = pwd;
cd('..');
load policy_param.mat;
for i=1:33
deep_parameter_name = M_.param_names(i,:);
eval(['M_.params(i)  = ' deep_parameter_name ' ;'])
end
cd(thispath);
M_.params( 32 ) = 100;
std_r_ = M_.params( 32 );
M_.params( 34 ) = 1;
coffispol = M_.params( 34 );
%
% SHOCKS instructions
%
M_.exo_det_length = 0;
M_.Sigma_e(1, 1) = 0;
M_.Sigma_e(2, 2) = 0;
M_.Sigma_e(3, 3) = 0.006561;
M_.Sigma_e(4, 4) = 0.000121;
M_.Sigma_e(5, 5) = 0.0576;
M_.Sigma_e(6, 6) = 1.6e-005;
M_.Sigma_e(7, 7) = 1e-006;
M_.Sigma_e(8, 8) = 0.0004839999999999999;
M_.Sigma_e(9, 9) = 0.000169;
M_.Sigma_e(10, 10) = 4e-006;
M_.Sigma_e(11, 11) = 0;
M_.Sigma_e(12, 12) = 9e-006;
M_.Sigma_e(14, 14) = 2.5e-005;
save('BRA_SAMBA08_results.mat', 'oo_', 'M_', 'options_');
if exist('estim_params_', 'var') == 1
  save('BRA_SAMBA08_results.mat', 'estim_params_', '-append');
end
if exist('bayestopt_', 'var') == 1
  save('BRA_SAMBA08_results.mat', 'bayestopt_', '-append');
end
if exist('dataset_', 'var') == 1
  save('BRA_SAMBA08_results.mat', 'dataset_', '-append');
end
if exist('estimation_info', 'var') == 1
  save('BRA_SAMBA08_results.mat', 'estimation_info', '-append');
end
if exist('dataset_info', 'var') == 1
  save('BRA_SAMBA08_results.mat', 'dataset_info', '-append');
end
if exist('oo_recursive_', 'var') == 1
  save('BRA_SAMBA08_results.mat', 'oo_recursive_', '-append');
end


disp(['Total computing time : ' dynsec2hms(toc(tic0)) ]);
if ~isempty(lastwarn)
  disp('Note: warning(s) encountered in MATLAB/Octave code')
end
diary off
