function [R]=menu_AL_select_states()

global R;
S.fh = figure('units','pixels',...
              'menubar','none',...
              'position',[200 500 120 150],...
              'name','',...
              'numbertitle','off',...
              'resize','off');
S.t= uicontrol('style','text', ...
               'unit','pix', ...
               'position',[10 100 100 40], ...
               'string','How many states to select for AL?');
S.r(1)= uicontrol('style','rad', ...
                  'unit','pix',...
                  'position',[10 70 100 20],...
                  'string','All (MSV set)');
S.r(2)= uicontrol('style','rad', ...
                  'unit','pix',...
                  'position',[10 40 100 20],...
                  'string','Select subset');
S.pb= uicontrol('style','push', ...
                  'unit','pix',...
                  'position',[10 10 100 20],...
                  'string','Continue', ...
                  'callback', {@funeval_states,S});
uiwait;
end