%
% Status : main Dynare file 
%
% Warning : this file is generated automatically by Dynare
%           from model file (.mod)

tic;
global M_ oo_ options_ ys0_ ex0_ estimation_info
options_ = [];
M_.fname = 'US_RS99';
%
% Some global variables initialization
%
global_initialization;
diary off;
diary('US_RS99.log');
M_.exo_names = 'eps';
M_.exo_names_tex = 'eps';
M_.exo_names_long = 'eps';
M_.exo_names = char(M_.exo_names, 'eta');
M_.exo_names_tex = char(M_.exo_names_tex, 'eta');
M_.exo_names_long = char(M_.exo_names_long, 'eta');
M_.exo_names = char(M_.exo_names, 'interest_');
M_.exo_names_tex = char(M_.exo_names_tex, 'interest\_');
M_.exo_names_long = char(M_.exo_names_long, 'interest_');
M_.endo_names = 'pi';
M_.endo_names_tex = 'pi';
M_.endo_names_long = 'pi';
M_.endo_names = char(M_.endo_names, 'y');
M_.endo_names_tex = char(M_.endo_names_tex, 'y');
M_.endo_names_long = char(M_.endo_names_long, 'y');
M_.endo_names = char(M_.endo_names, 'i');
M_.endo_names_tex = char(M_.endo_names_tex, 'i');
M_.endo_names_long = char(M_.endo_names_long, 'i');
M_.endo_names = char(M_.endo_names, 'pibar');
M_.endo_names_tex = char(M_.endo_names_tex, 'pibar');
M_.endo_names_long = char(M_.endo_names_long, 'pibar');
M_.endo_names = char(M_.endo_names, 'ibar');
M_.endo_names_tex = char(M_.endo_names_tex, 'ibar');
M_.endo_names_long = char(M_.endo_names_long, 'ibar');
M_.endo_names = char(M_.endo_names, 'interest');
M_.endo_names_tex = char(M_.endo_names_tex, 'interest');
M_.endo_names_long = char(M_.endo_names_long, 'interest');
M_.endo_names = char(M_.endo_names, 'inflation');
M_.endo_names_tex = char(M_.endo_names_tex, 'inflation');
M_.endo_names_long = char(M_.endo_names_long, 'inflation');
M_.endo_names = char(M_.endo_names, 'inflationq');
M_.endo_names_tex = char(M_.endo_names_tex, 'inflationq');
M_.endo_names_long = char(M_.endo_names_long, 'inflationq');
M_.endo_names = char(M_.endo_names, 'outputgap');
M_.endo_names_tex = char(M_.endo_names_tex, 'outputgap');
M_.endo_names_long = char(M_.endo_names_long, 'outputgap');
M_.endo_names = char(M_.endo_names, 'output');
M_.endo_names_tex = char(M_.endo_names_tex, 'output');
M_.endo_names_long = char(M_.endo_names_long, 'output');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_73');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_73');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_73');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_77');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_77');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_77');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_81');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_81');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_81');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_108');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_108');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_108');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_112');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_112');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_112');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_116');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_116');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_116');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_143');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_143');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_143');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_147');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_147');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_147');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_151');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_151');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_151');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_0_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_0\_1');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_0_1');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_0_2');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_0\_2');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_0_2');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_9_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_9\_1');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_9_1');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_9_2');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_9\_2');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_9_2');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_9_3');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_9\_3');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_9_3');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_8_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_8\_1');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_8_1');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_8_2');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_8\_2');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_8_2');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_8_3');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_8\_3');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_8_3');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_5_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_5\_1');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_5_1');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_5_2');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_5\_2');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_5_2');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_5_3');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_5\_3');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_5_3');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_7_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_7\_1');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_7_1');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_7_2');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_7\_2');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_7_2');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_7_3');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_7\_3');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_7_3');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_0_3');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_0\_3');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_0_3');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_1_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_1\_1');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_1_1');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_2_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_2\_1');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_2_1');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_2_2');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_2\_2');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_2_2');
M_.param_names = 'cofintintb1';
M_.param_names_tex = 'cofintintb1';
M_.param_names_long = 'cofintintb1';
M_.param_names = char(M_.param_names, 'cofintintb2');
M_.param_names_tex = char(M_.param_names_tex, 'cofintintb2');
M_.param_names_long = char(M_.param_names_long, 'cofintintb2');
M_.param_names = char(M_.param_names, 'cofintintb3');
M_.param_names_tex = char(M_.param_names_tex, 'cofintintb3');
M_.param_names_long = char(M_.param_names_long, 'cofintintb3');
M_.param_names = char(M_.param_names, 'cofintintb4');
M_.param_names_tex = char(M_.param_names_tex, 'cofintintb4');
M_.param_names_long = char(M_.param_names_long, 'cofintintb4');
M_.param_names = char(M_.param_names, 'cofintinf0');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinf0');
M_.param_names_long = char(M_.param_names_long, 'cofintinf0');
M_.param_names = char(M_.param_names, 'cofintinfb1');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinfb1');
M_.param_names_long = char(M_.param_names_long, 'cofintinfb1');
M_.param_names = char(M_.param_names, 'cofintinfb2');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinfb2');
M_.param_names_long = char(M_.param_names_long, 'cofintinfb2');
M_.param_names = char(M_.param_names, 'cofintinfb3');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinfb3');
M_.param_names_long = char(M_.param_names_long, 'cofintinfb3');
M_.param_names = char(M_.param_names, 'cofintinfb4');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinfb4');
M_.param_names_long = char(M_.param_names_long, 'cofintinfb4');
M_.param_names = char(M_.param_names, 'cofintinff1');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinff1');
M_.param_names_long = char(M_.param_names_long, 'cofintinff1');
M_.param_names = char(M_.param_names, 'cofintinff2');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinff2');
M_.param_names_long = char(M_.param_names_long, 'cofintinff2');
M_.param_names = char(M_.param_names, 'cofintinff3');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinff3');
M_.param_names_long = char(M_.param_names_long, 'cofintinff3');
M_.param_names = char(M_.param_names, 'cofintinff4');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinff4');
M_.param_names_long = char(M_.param_names_long, 'cofintinff4');
M_.param_names = char(M_.param_names, 'cofintout');
M_.param_names_tex = char(M_.param_names_tex, 'cofintout');
M_.param_names_long = char(M_.param_names_long, 'cofintout');
M_.param_names = char(M_.param_names, 'cofintoutb1');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutb1');
M_.param_names_long = char(M_.param_names_long, 'cofintoutb1');
M_.param_names = char(M_.param_names, 'cofintoutb2');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutb2');
M_.param_names_long = char(M_.param_names_long, 'cofintoutb2');
M_.param_names = char(M_.param_names, 'cofintoutb3');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutb3');
M_.param_names_long = char(M_.param_names_long, 'cofintoutb3');
M_.param_names = char(M_.param_names, 'cofintoutb4');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutb4');
M_.param_names_long = char(M_.param_names_long, 'cofintoutb4');
M_.param_names = char(M_.param_names, 'cofintoutf1');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutf1');
M_.param_names_long = char(M_.param_names_long, 'cofintoutf1');
M_.param_names = char(M_.param_names, 'cofintoutf2');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutf2');
M_.param_names_long = char(M_.param_names_long, 'cofintoutf2');
M_.param_names = char(M_.param_names, 'cofintoutf3');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutf3');
M_.param_names_long = char(M_.param_names_long, 'cofintoutf3');
M_.param_names = char(M_.param_names, 'cofintoutf4');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutf4');
M_.param_names_long = char(M_.param_names_long, 'cofintoutf4');
M_.param_names = char(M_.param_names, 'cofintoutp');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutp');
M_.param_names_long = char(M_.param_names_long, 'cofintoutp');
M_.param_names = char(M_.param_names, 'cofintoutpb1');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpb1');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpb1');
M_.param_names = char(M_.param_names, 'cofintoutpb2');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpb2');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpb2');
M_.param_names = char(M_.param_names, 'cofintoutpb3');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpb3');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpb3');
M_.param_names = char(M_.param_names, 'cofintoutpb4');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpb4');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpb4');
M_.param_names = char(M_.param_names, 'cofintoutpf1');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpf1');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpf1');
M_.param_names = char(M_.param_names, 'cofintoutpf2');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpf2');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpf2');
M_.param_names = char(M_.param_names, 'cofintoutpf3');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpf3');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpf3');
M_.param_names = char(M_.param_names, 'cofintoutpf4');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpf4');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpf4');
M_.param_names = char(M_.param_names, 'std_r_');
M_.param_names_tex = char(M_.param_names_tex, 'std\_r\_');
M_.param_names_long = char(M_.param_names_long, 'std_r_');
M_.param_names = char(M_.param_names, 'std_r_quart');
M_.param_names_tex = char(M_.param_names_tex, 'std\_r\_quart');
M_.param_names_long = char(M_.param_names_long, 'std_r_quart');
M_.param_names = char(M_.param_names, 'coffispol');
M_.param_names_tex = char(M_.param_names_tex, 'coffispol');
M_.param_names_long = char(M_.param_names_long, 'coffispol');
M_.param_names = char(M_.param_names, 'alphapi1');
M_.param_names_tex = char(M_.param_names_tex, 'alphapi1');
M_.param_names_long = char(M_.param_names_long, 'alphapi1');
M_.param_names = char(M_.param_names, 'alphapi2');
M_.param_names_tex = char(M_.param_names_tex, 'alphapi2');
M_.param_names_long = char(M_.param_names_long, 'alphapi2');
M_.param_names = char(M_.param_names, 'alphapi3');
M_.param_names_tex = char(M_.param_names_tex, 'alphapi3');
M_.param_names_long = char(M_.param_names_long, 'alphapi3');
M_.param_names = char(M_.param_names, 'alphapi4');
M_.param_names_tex = char(M_.param_names_tex, 'alphapi4');
M_.param_names_long = char(M_.param_names_long, 'alphapi4');
M_.param_names = char(M_.param_names, 'alphay');
M_.param_names_tex = char(M_.param_names_tex, 'alphay');
M_.param_names_long = char(M_.param_names_long, 'alphay');
M_.param_names = char(M_.param_names, 'betay1');
M_.param_names_tex = char(M_.param_names_tex, 'betay1');
M_.param_names_long = char(M_.param_names_long, 'betay1');
M_.param_names = char(M_.param_names, 'betay2');
M_.param_names_tex = char(M_.param_names_tex, 'betay2');
M_.param_names_long = char(M_.param_names_long, 'betay2');
M_.param_names = char(M_.param_names, 'betar');
M_.param_names_tex = char(M_.param_names_tex, 'betar');
M_.param_names_long = char(M_.param_names_long, 'betar');
M_.exo_det_nbr = 0;
M_.exo_nbr = 3;
M_.endo_nbr = 37;
M_.param_nbr = 42;
M_.orig_endo_nbr = 10;
M_.aux_vars(1).endo_index = 11;
M_.aux_vars(1).type = 0;
M_.aux_vars(2).endo_index = 12;
M_.aux_vars(2).type = 0;
M_.aux_vars(3).endo_index = 13;
M_.aux_vars(3).type = 0;
M_.aux_vars(4).endo_index = 14;
M_.aux_vars(4).type = 0;
M_.aux_vars(5).endo_index = 15;
M_.aux_vars(5).type = 0;
M_.aux_vars(6).endo_index = 16;
M_.aux_vars(6).type = 0;
M_.aux_vars(7).endo_index = 17;
M_.aux_vars(7).type = 0;
M_.aux_vars(8).endo_index = 18;
M_.aux_vars(8).type = 0;
M_.aux_vars(9).endo_index = 19;
M_.aux_vars(9).type = 0;
M_.aux_vars(10).endo_index = 20;
M_.aux_vars(10).type = 1;
M_.aux_vars(10).orig_index = 1;
M_.aux_vars(10).orig_lead_lag = -1;
M_.aux_vars(11).endo_index = 21;
M_.aux_vars(11).type = 1;
M_.aux_vars(11).orig_index = 1;
M_.aux_vars(11).orig_lead_lag = -2;
M_.aux_vars(12).endo_index = 22;
M_.aux_vars(12).type = 1;
M_.aux_vars(12).orig_index = 10;
M_.aux_vars(12).orig_lead_lag = -1;
M_.aux_vars(13).endo_index = 23;
M_.aux_vars(13).type = 1;
M_.aux_vars(13).orig_index = 10;
M_.aux_vars(13).orig_lead_lag = -2;
M_.aux_vars(14).endo_index = 24;
M_.aux_vars(14).type = 1;
M_.aux_vars(14).orig_index = 10;
M_.aux_vars(14).orig_lead_lag = -3;
M_.aux_vars(15).endo_index = 25;
M_.aux_vars(15).type = 1;
M_.aux_vars(15).orig_index = 9;
M_.aux_vars(15).orig_lead_lag = -1;
M_.aux_vars(16).endo_index = 26;
M_.aux_vars(16).type = 1;
M_.aux_vars(16).orig_index = 9;
M_.aux_vars(16).orig_lead_lag = -2;
M_.aux_vars(17).endo_index = 27;
M_.aux_vars(17).type = 1;
M_.aux_vars(17).orig_index = 9;
M_.aux_vars(17).orig_lead_lag = -3;
M_.aux_vars(18).endo_index = 28;
M_.aux_vars(18).type = 1;
M_.aux_vars(18).orig_index = 6;
M_.aux_vars(18).orig_lead_lag = -1;
M_.aux_vars(19).endo_index = 29;
M_.aux_vars(19).type = 1;
M_.aux_vars(19).orig_index = 6;
M_.aux_vars(19).orig_lead_lag = -2;
M_.aux_vars(20).endo_index = 30;
M_.aux_vars(20).type = 1;
M_.aux_vars(20).orig_index = 6;
M_.aux_vars(20).orig_lead_lag = -3;
M_.aux_vars(21).endo_index = 31;
M_.aux_vars(21).type = 1;
M_.aux_vars(21).orig_index = 8;
M_.aux_vars(21).orig_lead_lag = -1;
M_.aux_vars(22).endo_index = 32;
M_.aux_vars(22).type = 1;
M_.aux_vars(22).orig_index = 8;
M_.aux_vars(22).orig_lead_lag = -2;
M_.aux_vars(23).endo_index = 33;
M_.aux_vars(23).type = 1;
M_.aux_vars(23).orig_index = 8;
M_.aux_vars(23).orig_lead_lag = -3;
M_.aux_vars(24).endo_index = 34;
M_.aux_vars(24).type = 1;
M_.aux_vars(24).orig_index = 1;
M_.aux_vars(24).orig_lead_lag = -3;
M_.aux_vars(25).endo_index = 35;
M_.aux_vars(25).type = 1;
M_.aux_vars(25).orig_index = 2;
M_.aux_vars(25).orig_lead_lag = -1;
M_.aux_vars(26).endo_index = 36;
M_.aux_vars(26).type = 1;
M_.aux_vars(26).orig_index = 3;
M_.aux_vars(26).orig_lead_lag = -1;
M_.aux_vars(27).endo_index = 37;
M_.aux_vars(27).type = 1;
M_.aux_vars(27).orig_index = 3;
M_.aux_vars(27).orig_lead_lag = -2;
M_.Sigma_e = zeros(3, 3);
M_.Correlation_matrix = eye(3, 3);
M_.H = 0;
M_.Correlation_matrix_ME = 1;
M_.sigma_e_is_diagonal = 1;
options_.linear = 1;
options_.block=0;
options_.bytecode=0;
options_.use_dll=0;
erase_compiled_function('US_RS99_static');
erase_compiled_function('US_RS99_dynamic');
M_.lead_lag_incidence = [
 1 28 0;
 2 29 0;
 3 30 0;
 4 31 0;
 5 32 0;
 6 33 0;
 0 34 0;
 7 35 65;
 8 36 66;
 9 37 67;
 0 38 68;
 0 39 69;
 0 40 70;
 0 41 71;
 0 42 72;
 0 43 73;
 0 44 74;
 0 45 75;
 0 46 76;
 10 47 0;
 11 48 0;
 12 49 0;
 13 50 0;
 14 51 0;
 15 52 0;
 16 53 0;
 17 54 0;
 18 55 0;
 19 56 0;
 20 57 0;
 21 58 0;
 22 59 0;
 23 60 0;
 24 61 0;
 25 62 0;
 26 63 0;
 27 64 0;]';
M_.nstatic = 1;
M_.nfwrd   = 9;
M_.npred   = 24;
M_.nboth   = 3;
M_.nsfwrd   = 12;
M_.nspred   = 27;
M_.ndynamic   = 36;
M_.equations_tags = {
};
M_.static_and_dynamic_models_differ = 0;
M_.exo_names_orig_ord = [1:3];
M_.maximum_lag = 1;
M_.maximum_lead = 1;
M_.maximum_endo_lag = 1;
M_.maximum_endo_lead = 1;
oo_.steady_state = zeros(37, 1);
M_.maximum_exo_lag = 0;
M_.maximum_exo_lead = 0;
oo_.exo_steady_state = zeros(3, 1);
M_.params = NaN(42, 1);
M_.NNZDerivatives = zeros(3, 1);
M_.NNZDerivatives(1) = 123;
M_.NNZDerivatives(2) = 0;
M_.NNZDerivatives(3) = -1;
M_.params( 35 ) = .7;
alphapi1 = M_.params( 35 );
M_.params( 36 ) = (-.1);
alphapi2 = M_.params( 36 );
M_.params( 37 ) = .28;
alphapi3 = M_.params( 37 );
M_.params( 38 ) = .12;
alphapi4 = M_.params( 38 );
M_.params( 39 ) = .14;
alphay = M_.params( 39 );
M_.params( 40 ) = 1.16;
betay1 = M_.params( 40 );
M_.params( 41 ) = (-.25);
betay2 = M_.params( 41 );
M_.params( 42 ) = .10;
betar = M_.params( 42 );
thispath = cd;                                                           
cd('..');                                                                
load policy_param.mat;                                                   
for i=1:33                                                               
deep_parameter_name = M_.param_names(i,:);                           
eval(['M_.params(i)  = ' deep_parameter_name ' ;'])                  
end                                                                      
cd(thispath);    
%
% SHOCKS instructions
%
make_ex_;
M_.exo_det_length = 0;
M_.Sigma_e(1, 1) = 1.018081;
M_.Sigma_e(2, 2) = 0.6707609999999999;
save('US_RS99_results.mat', 'oo_', 'M_', 'options_');
if exist('estim_params_', 'var') == 1
  save('US_RS99_results.mat', 'estim_params_', '-append');
end
if exist('bayestopt_', 'var') == 1
  save('US_RS99_results.mat', 'bayestopt_', '-append');
end
if exist('dataset_', 'var') == 1
  save('US_RS99_results.mat', 'dataset_', '-append');
end
if exist('estimation_info', 'var') == 1
  save('US_RS99_results.mat', 'estimation_info', '-append');
end


disp(['Total computing time : ' dynsec2hms(toc) ]);
if ~isempty(lastwarn)
  disp('Note: warning(s) encountered in MATLAB/Octave code')
end
diary off
