%
% Status : main Dynare file
%
% Warning : this file is generated automatically by Dynare
%           from model file (.mod)

if isoctave || matlab_ver_less_than('8.6')
    clear all
else
    clearvars -global
    clear_persistent_variables(fileparts(which('dynare')), false)
end
tic0 = tic;
% Save empty dates and dseries objects in memory.
dates('initialize');
dseries('initialize');
% Define global variables.
global M_ options_ oo_ estim_params_ bayestopt_ dataset_ dataset_info estimation_info ys0_ ex0_
options_ = [];
M_.fname = 'US_LTW17';
M_.dynare_version = '4.5.7';
oo_.dynare_version = '4.5.7';
options_.dynare_version = '4.5.7';
%
% Some global variables initialization
%
global_initialization;
diary off;
diary('US_LTW17.log');
M_.exo_names = 'euz';
M_.exo_names_tex = 'euz';
M_.exo_names_long = 'euz';
M_.exo_names = char(M_.exo_names, 'eua');
M_.exo_names_tex = char(M_.exo_names_tex, 'eua');
M_.exo_names_long = char(M_.exo_names_long, 'eua');
M_.exo_names = char(M_.exo_names, 'eub');
M_.exo_names_tex = char(M_.exo_names_tex, 'eub');
M_.exo_names_long = char(M_.exo_names_long, 'eub');
M_.exo_names = char(M_.exo_names, 'eum');
M_.exo_names_tex = char(M_.exo_names_tex, 'eum');
M_.exo_names_long = char(M_.exo_names_long, 'eum');
M_.exo_names = char(M_.exo_names, 'eui');
M_.exo_names_tex = char(M_.exo_names_tex, 'eui');
M_.exo_names_long = char(M_.exo_names_long, 'eui');
M_.exo_names = char(M_.exo_names, 'euw');
M_.exo_names_tex = char(M_.exo_names_tex, 'euw');
M_.exo_names_long = char(M_.exo_names_long, 'euw');
M_.exo_names = char(M_.exo_names, 'eup');
M_.exo_names_tex = char(M_.exo_names_tex, 'eup');
M_.exo_names_long = char(M_.exo_names_long, 'eup');
M_.exo_names = char(M_.exo_names, 'interest_');
M_.exo_names_tex = char(M_.exo_names_tex, 'interest\_');
M_.exo_names_long = char(M_.exo_names_long, 'interest_');
M_.exo_names = char(M_.exo_names, 'fiscal_');
M_.exo_names_tex = char(M_.exo_names_tex, 'fiscal\_');
M_.exo_names_long = char(M_.exo_names_long, 'fiscal_');
M_.endo_names = 'cs';
M_.endo_names_tex = 'cs';
M_.endo_names_long = 'cs';
M_.endo_names = char(M_.endo_names, 'cn');
M_.endo_names_tex = char(M_.endo_names_tex, 'cn');
M_.endo_names_long = char(M_.endo_names_long, 'cn');
M_.endo_names = char(M_.endo_names, 'R');
M_.endo_names_tex = char(M_.endo_names_tex, 'R');
M_.endo_names_long = char(M_.endo_names_long, 'R');
M_.endo_names = char(M_.endo_names, 'i');
M_.endo_names_tex = char(M_.endo_names_tex, 'i');
M_.endo_names_long = char(M_.endo_names_long, 'i');
M_.endo_names = char(M_.endo_names, 'k');
M_.endo_names_tex = char(M_.endo_names_tex, 'k');
M_.endo_names_long = char(M_.endo_names_long, 'k');
M_.endo_names = char(M_.endo_names, 'v');
M_.endo_names_tex = char(M_.endo_names_tex, 'v');
M_.endo_names_long = char(M_.endo_names_long, 'v');
M_.endo_names = char(M_.endo_names, 'l');
M_.endo_names_tex = char(M_.endo_names_tex, 'l');
M_.endo_names_long = char(M_.endo_names_long, 'l');
M_.endo_names = char(M_.endo_names, 'y');
M_.endo_names_tex = char(M_.endo_names_tex, 'y');
M_.endo_names_long = char(M_.endo_names_long, 'y');
M_.endo_names = char(M_.endo_names, 'gc');
M_.endo_names_tex = char(M_.endo_names_tex, 'gc');
M_.endo_names_long = char(M_.endo_names_long, 'gc');
M_.endo_names = char(M_.endo_names, 'c');
M_.endo_names_tex = char(M_.endo_names_tex, 'c');
M_.endo_names_long = char(M_.endo_names_long, 'c');
M_.endo_names = char(M_.endo_names, 'q');
M_.endo_names_tex = char(M_.endo_names_tex, 'q');
M_.endo_names_long = char(M_.endo_names_long, 'q');
M_.endo_names = char(M_.endo_names, 'rk');
M_.endo_names_tex = char(M_.endo_names_tex, 'rk');
M_.endo_names_long = char(M_.endo_names_long, 'rk');
M_.endo_names = char(M_.endo_names, 'w');
M_.endo_names_tex = char(M_.endo_names_tex, 'w');
M_.endo_names_long = char(M_.endo_names_long, 'w');
M_.endo_names = char(M_.endo_names, 'pi');
M_.endo_names_tex = char(M_.endo_names_tex, 'pi');
M_.endo_names_long = char(M_.endo_names_long, 'pi');
M_.endo_names = char(M_.endo_names, 'b');
M_.endo_names_tex = char(M_.endo_names_tex, 'b');
M_.endo_names_long = char(M_.endo_names_long, 'b');
M_.endo_names = char(M_.endo_names, 'sb');
M_.endo_names_tex = char(M_.endo_names_tex, 'sb');
M_.endo_names_long = char(M_.endo_names_long, 'sb');
M_.endo_names = char(M_.endo_names, 'tauk');
M_.endo_names_tex = char(M_.endo_names_tex, 'tauk');
M_.endo_names_long = char(M_.endo_names_long, 'tauk');
M_.endo_names = char(M_.endo_names, 'taul');
M_.endo_names_tex = char(M_.endo_names_tex, 'taul');
M_.endo_names_long = char(M_.endo_names_long, 'taul');
M_.endo_names = char(M_.endo_names, 'tauc');
M_.endo_names_tex = char(M_.endo_names_tex, 'tauc');
M_.endo_names_long = char(M_.endo_names_long, 'tauc');
M_.endo_names = char(M_.endo_names, 'r');
M_.endo_names_tex = char(M_.endo_names_tex, 'r');
M_.endo_names_long = char(M_.endo_names_long, 'r');
M_.endo_names = char(M_.endo_names, 'z');
M_.endo_names_tex = char(M_.endo_names_tex, 'z');
M_.endo_names_long = char(M_.endo_names_long, 'z');
M_.endo_names = char(M_.endo_names, 'mc');
M_.endo_names_tex = char(M_.endo_names_tex, 'mc');
M_.endo_names_long = char(M_.endo_names_long, 'mc');
M_.endo_names = char(M_.endo_names, 'kbar');
M_.endo_names_tex = char(M_.endo_names_tex, 'kbar');
M_.endo_names_long = char(M_.endo_names_long, 'kbar');
M_.endo_names = char(M_.endo_names, 'lambda');
M_.endo_names_tex = char(M_.endo_names_tex, 'lambda');
M_.endo_names_long = char(M_.endo_names_long, 'lambda');
M_.endo_names = char(M_.endo_names, 'Pb');
M_.endo_names_tex = char(M_.endo_names_tex, 'Pb');
M_.endo_names_long = char(M_.endo_names_long, 'Pb');
M_.endo_names = char(M_.endo_names, 'cstar');
M_.endo_names_tex = char(M_.endo_names_tex, 'cstar');
M_.endo_names_long = char(M_.endo_names_long, 'cstar');
M_.endo_names = char(M_.endo_names, 'piL');
M_.endo_names_tex = char(M_.endo_names_tex, 'piL');
M_.endo_names_long = char(M_.endo_names_long, 'piL');
M_.endo_names = char(M_.endo_names, 'rL');
M_.endo_names_tex = char(M_.endo_names_tex, 'rL');
M_.endo_names_long = char(M_.endo_names_long, 'rL');
M_.endo_names = char(M_.endo_names, 'S');
M_.endo_names_tex = char(M_.endo_names_tex, 'S');
M_.endo_names_long = char(M_.endo_names_long, 'S');
M_.endo_names = char(M_.endo_names, 'rb');
M_.endo_names_tex = char(M_.endo_names_tex, 'rb');
M_.endo_names_long = char(M_.endo_names_long, 'rb');
M_.endo_names = char(M_.endo_names, 'Tk');
M_.endo_names_tex = char(M_.endo_names_tex, 'Tk');
M_.endo_names_long = char(M_.endo_names_long, 'Tk');
M_.endo_names = char(M_.endo_names, 'Tl');
M_.endo_names_tex = char(M_.endo_names_tex, 'Tl');
M_.endo_names_long = char(M_.endo_names_long, 'Tl');
M_.endo_names = char(M_.endo_names, 'Tc');
M_.endo_names_tex = char(M_.endo_names_tex, 'Tc');
M_.endo_names_long = char(M_.endo_names_long, 'Tc');
M_.endo_names = char(M_.endo_names, 'cobs');
M_.endo_names_tex = char(M_.endo_names_tex, 'cobs');
M_.endo_names_long = char(M_.endo_names_long, 'cobs');
M_.endo_names = char(M_.endo_names, 'iobs');
M_.endo_names_tex = char(M_.endo_names_tex, 'iobs');
M_.endo_names_long = char(M_.endo_names_long, 'iobs');
M_.endo_names = char(M_.endo_names, 'gcobs');
M_.endo_names_tex = char(M_.endo_names_tex, 'gcobs');
M_.endo_names_long = char(M_.endo_names_long, 'gcobs');
M_.endo_names = char(M_.endo_names, 'wobs');
M_.endo_names_tex = char(M_.endo_names_tex, 'wobs');
M_.endo_names_long = char(M_.endo_names_long, 'wobs');
M_.endo_names = char(M_.endo_names, 'bobs');
M_.endo_names_tex = char(M_.endo_names_tex, 'bobs');
M_.endo_names_long = char(M_.endo_names_long, 'bobs');
M_.endo_names = char(M_.endo_names, 'Robs');
M_.endo_names_tex = char(M_.endo_names_tex, 'Robs');
M_.endo_names_long = char(M_.endo_names_long, 'Robs');
M_.endo_names = char(M_.endo_names, 'Piobs');
M_.endo_names_tex = char(M_.endo_names_tex, 'Piobs');
M_.endo_names_long = char(M_.endo_names_long, 'Piobs');
M_.endo_names = char(M_.endo_names, 'Lobs');
M_.endo_names_tex = char(M_.endo_names_tex, 'Lobs');
M_.endo_names_long = char(M_.endo_names_long, 'Lobs');
M_.endo_names = char(M_.endo_names, 'ugc');
M_.endo_names_tex = char(M_.endo_names_tex, 'ugc');
M_.endo_names_long = char(M_.endo_names_long, 'ugc');
M_.endo_names = char(M_.endo_names, 'uz');
M_.endo_names_tex = char(M_.endo_names_tex, 'uz');
M_.endo_names_long = char(M_.endo_names_long, 'uz');
M_.endo_names = char(M_.endo_names, 'ua');
M_.endo_names_tex = char(M_.endo_names_tex, 'ua');
M_.endo_names_long = char(M_.endo_names_long, 'ua');
M_.endo_names = char(M_.endo_names, 'ub');
M_.endo_names_tex = char(M_.endo_names_tex, 'ub');
M_.endo_names_long = char(M_.endo_names_long, 'ub');
M_.endo_names = char(M_.endo_names, 'um');
M_.endo_names_tex = char(M_.endo_names_tex, 'um');
M_.endo_names_long = char(M_.endo_names_long, 'um');
M_.endo_names = char(M_.endo_names, 'ui');
M_.endo_names_tex = char(M_.endo_names_tex, 'ui');
M_.endo_names_long = char(M_.endo_names_long, 'ui');
M_.endo_names = char(M_.endo_names, 'uw');
M_.endo_names_tex = char(M_.endo_names_tex, 'uw');
M_.endo_names_long = char(M_.endo_names_long, 'uw');
M_.endo_names = char(M_.endo_names, 'up');
M_.endo_names_tex = char(M_.endo_names_tex, 'up');
M_.endo_names_long = char(M_.endo_names_long, 'up');
M_.endo_names = char(M_.endo_names, 'csf');
M_.endo_names_tex = char(M_.endo_names_tex, 'csf');
M_.endo_names_long = char(M_.endo_names_long, 'csf');
M_.endo_names = char(M_.endo_names, 'cnf');
M_.endo_names_tex = char(M_.endo_names_tex, 'cnf');
M_.endo_names_long = char(M_.endo_names_long, 'cnf');
M_.endo_names = char(M_.endo_names, 'if');
M_.endo_names_tex = char(M_.endo_names_tex, 'if');
M_.endo_names_long = char(M_.endo_names_long, 'if');
M_.endo_names = char(M_.endo_names, 'kf');
M_.endo_names_tex = char(M_.endo_names_tex, 'kf');
M_.endo_names_long = char(M_.endo_names_long, 'kf');
M_.endo_names = char(M_.endo_names, 'vf');
M_.endo_names_tex = char(M_.endo_names_tex, 'vf');
M_.endo_names_long = char(M_.endo_names_long, 'vf');
M_.endo_names = char(M_.endo_names, 'lf');
M_.endo_names_tex = char(M_.endo_names_tex, 'lf');
M_.endo_names_long = char(M_.endo_names_long, 'lf');
M_.endo_names = char(M_.endo_names, 'yf');
M_.endo_names_tex = char(M_.endo_names_tex, 'yf');
M_.endo_names_long = char(M_.endo_names_long, 'yf');
M_.endo_names = char(M_.endo_names, 'gcf');
M_.endo_names_tex = char(M_.endo_names_tex, 'gcf');
M_.endo_names_long = char(M_.endo_names_long, 'gcf');
M_.endo_names = char(M_.endo_names, 'cf');
M_.endo_names_tex = char(M_.endo_names_tex, 'cf');
M_.endo_names_long = char(M_.endo_names_long, 'cf');
M_.endo_names = char(M_.endo_names, 'qf');
M_.endo_names_tex = char(M_.endo_names_tex, 'qf');
M_.endo_names_long = char(M_.endo_names_long, 'qf');
M_.endo_names = char(M_.endo_names, 'rkf');
M_.endo_names_tex = char(M_.endo_names_tex, 'rkf');
M_.endo_names_long = char(M_.endo_names_long, 'rkf');
M_.endo_names = char(M_.endo_names, 'wf');
M_.endo_names_tex = char(M_.endo_names_tex, 'wf');
M_.endo_names_long = char(M_.endo_names_long, 'wf');
M_.endo_names = char(M_.endo_names, 'bf');
M_.endo_names_tex = char(M_.endo_names_tex, 'bf');
M_.endo_names_long = char(M_.endo_names_long, 'bf');
M_.endo_names = char(M_.endo_names, 'sbf');
M_.endo_names_tex = char(M_.endo_names_tex, 'sbf');
M_.endo_names_long = char(M_.endo_names_long, 'sbf');
M_.endo_names = char(M_.endo_names, 'taukf');
M_.endo_names_tex = char(M_.endo_names_tex, 'taukf');
M_.endo_names_long = char(M_.endo_names_long, 'taukf');
M_.endo_names = char(M_.endo_names, 'taulf');
M_.endo_names_tex = char(M_.endo_names_tex, 'taulf');
M_.endo_names_long = char(M_.endo_names_long, 'taulf');
M_.endo_names = char(M_.endo_names, 'taucf');
M_.endo_names_tex = char(M_.endo_names_tex, 'taucf');
M_.endo_names_long = char(M_.endo_names_long, 'taucf');
M_.endo_names = char(M_.endo_names, 'rf');
M_.endo_names_tex = char(M_.endo_names_tex, 'rf');
M_.endo_names_long = char(M_.endo_names_long, 'rf');
M_.endo_names = char(M_.endo_names, 'zf');
M_.endo_names_tex = char(M_.endo_names_tex, 'zf');
M_.endo_names_long = char(M_.endo_names_long, 'zf');
M_.endo_names = char(M_.endo_names, 'mcf');
M_.endo_names_tex = char(M_.endo_names_tex, 'mcf');
M_.endo_names_long = char(M_.endo_names_long, 'mcf');
M_.endo_names = char(M_.endo_names, 'kbarf');
M_.endo_names_tex = char(M_.endo_names_tex, 'kbarf');
M_.endo_names_long = char(M_.endo_names_long, 'kbarf');
M_.endo_names = char(M_.endo_names, 'lambdaf');
M_.endo_names_tex = char(M_.endo_names_tex, 'lambdaf');
M_.endo_names_long = char(M_.endo_names_long, 'lambdaf');
M_.endo_names = char(M_.endo_names, 'cstarf');
M_.endo_names_tex = char(M_.endo_names_tex, 'cstarf');
M_.endo_names_long = char(M_.endo_names_long, 'cstarf');
M_.endo_names = char(M_.endo_names, 'Sf');
M_.endo_names_tex = char(M_.endo_names_tex, 'Sf');
M_.endo_names_long = char(M_.endo_names_long, 'Sf');
M_.endo_names = char(M_.endo_names, 'rbf');
M_.endo_names_tex = char(M_.endo_names_tex, 'rbf');
M_.endo_names_long = char(M_.endo_names_long, 'rbf');
M_.endo_names = char(M_.endo_names, 'Tkf');
M_.endo_names_tex = char(M_.endo_names_tex, 'Tkf');
M_.endo_names_long = char(M_.endo_names_long, 'Tkf');
M_.endo_names = char(M_.endo_names, 'Tlf');
M_.endo_names_tex = char(M_.endo_names_tex, 'Tlf');
M_.endo_names_long = char(M_.endo_names_long, 'Tlf');
M_.endo_names = char(M_.endo_names, 'Tcf');
M_.endo_names_tex = char(M_.endo_names_tex, 'Tcf');
M_.endo_names_long = char(M_.endo_names_long, 'Tcf');
M_.endo_names = char(M_.endo_names, 'cobsf');
M_.endo_names_tex = char(M_.endo_names_tex, 'cobsf');
M_.endo_names_long = char(M_.endo_names_long, 'cobsf');
M_.endo_names = char(M_.endo_names, 'iobsf');
M_.endo_names_tex = char(M_.endo_names_tex, 'iobsf');
M_.endo_names_long = char(M_.endo_names_long, 'iobsf');
M_.endo_names = char(M_.endo_names, 'gcobsf');
M_.endo_names_tex = char(M_.endo_names_tex, 'gcobsf');
M_.endo_names_long = char(M_.endo_names_long, 'gcobsf');
M_.endo_names = char(M_.endo_names, 'wobsf');
M_.endo_names_tex = char(M_.endo_names_tex, 'wobsf');
M_.endo_names_long = char(M_.endo_names_long, 'wobsf');
M_.endo_names = char(M_.endo_names, 'bobsf');
M_.endo_names_tex = char(M_.endo_names_tex, 'bobsf');
M_.endo_names_long = char(M_.endo_names_long, 'bobsf');
M_.endo_names = char(M_.endo_names, 'Lobsf');
M_.endo_names_tex = char(M_.endo_names_tex, 'Lobsf');
M_.endo_names_long = char(M_.endo_names_long, 'Lobsf');
M_.endo_names = char(M_.endo_names, 'interest');
M_.endo_names_tex = char(M_.endo_names_tex, 'interest');
M_.endo_names_long = char(M_.endo_names_long, 'interest');
M_.endo_names = char(M_.endo_names, 'inflation');
M_.endo_names_tex = char(M_.endo_names_tex, 'inflation');
M_.endo_names_long = char(M_.endo_names_long, 'inflation');
M_.endo_names = char(M_.endo_names, 'inflationq');
M_.endo_names_tex = char(M_.endo_names_tex, 'inflationq');
M_.endo_names_long = char(M_.endo_names_long, 'inflationq');
M_.endo_names = char(M_.endo_names, 'outputgap');
M_.endo_names_tex = char(M_.endo_names_tex, 'outputgap');
M_.endo_names_long = char(M_.endo_names_long, 'outputgap');
M_.endo_names = char(M_.endo_names, 'output');
M_.endo_names_tex = char(M_.endo_names_tex, 'output');
M_.endo_names_long = char(M_.endo_names_long, 'output');
M_.endo_names = char(M_.endo_names, 'fispol');
M_.endo_names_tex = char(M_.endo_names_tex, 'fispol');
M_.endo_names_long = char(M_.endo_names_long, 'fispol');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_83');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_83');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_83');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_87');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_87');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_87');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_91');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_91');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_91');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_118');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_118');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_118');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_122');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_122');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_122');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_126');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_126');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_126');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_153');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_153');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_153');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_157');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_157');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_157');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_161');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_161');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_161');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_13_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_13\_1');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_13_1');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_13_2');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_13\_2');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_13_2');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_87_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_87\_1');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_87_1');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_87_2');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_87\_2');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_87_2');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_87_3');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_87\_3');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_87_3');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_86_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_86\_1');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_86_1');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_86_2');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_86\_2');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_86_2');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_86_3');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_86\_3');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_86_3');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_83_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_83\_1');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_83_1');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_83_2');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_83\_2');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_83_2');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_83_3');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_83\_3');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_83_3');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_85_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_85\_1');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_85_1');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_85_2');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_85\_2');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_85_2');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_85_3');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_85\_3');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_85_3');
M_.endo_partitions = struct();
M_.param_names = 'cofintintb1';
M_.param_names_tex = 'cofintintb1';
M_.param_names_long = 'cofintintb1';
M_.param_names = char(M_.param_names, 'cofintintb2');
M_.param_names_tex = char(M_.param_names_tex, 'cofintintb2');
M_.param_names_long = char(M_.param_names_long, 'cofintintb2');
M_.param_names = char(M_.param_names, 'cofintintb3');
M_.param_names_tex = char(M_.param_names_tex, 'cofintintb3');
M_.param_names_long = char(M_.param_names_long, 'cofintintb3');
M_.param_names = char(M_.param_names, 'cofintintb4');
M_.param_names_tex = char(M_.param_names_tex, 'cofintintb4');
M_.param_names_long = char(M_.param_names_long, 'cofintintb4');
M_.param_names = char(M_.param_names, 'cofintinf0');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinf0');
M_.param_names_long = char(M_.param_names_long, 'cofintinf0');
M_.param_names = char(M_.param_names, 'cofintinfb1');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinfb1');
M_.param_names_long = char(M_.param_names_long, 'cofintinfb1');
M_.param_names = char(M_.param_names, 'cofintinfb2');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinfb2');
M_.param_names_long = char(M_.param_names_long, 'cofintinfb2');
M_.param_names = char(M_.param_names, 'cofintinfb3');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinfb3');
M_.param_names_long = char(M_.param_names_long, 'cofintinfb3');
M_.param_names = char(M_.param_names, 'cofintinfb4');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinfb4');
M_.param_names_long = char(M_.param_names_long, 'cofintinfb4');
M_.param_names = char(M_.param_names, 'cofintinff1');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinff1');
M_.param_names_long = char(M_.param_names_long, 'cofintinff1');
M_.param_names = char(M_.param_names, 'cofintinff2');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinff2');
M_.param_names_long = char(M_.param_names_long, 'cofintinff2');
M_.param_names = char(M_.param_names, 'cofintinff3');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinff3');
M_.param_names_long = char(M_.param_names_long, 'cofintinff3');
M_.param_names = char(M_.param_names, 'cofintinff4');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinff4');
M_.param_names_long = char(M_.param_names_long, 'cofintinff4');
M_.param_names = char(M_.param_names, 'cofintout');
M_.param_names_tex = char(M_.param_names_tex, 'cofintout');
M_.param_names_long = char(M_.param_names_long, 'cofintout');
M_.param_names = char(M_.param_names, 'cofintoutb1');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutb1');
M_.param_names_long = char(M_.param_names_long, 'cofintoutb1');
M_.param_names = char(M_.param_names, 'cofintoutb2');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutb2');
M_.param_names_long = char(M_.param_names_long, 'cofintoutb2');
M_.param_names = char(M_.param_names, 'cofintoutb3');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutb3');
M_.param_names_long = char(M_.param_names_long, 'cofintoutb3');
M_.param_names = char(M_.param_names, 'cofintoutb4');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutb4');
M_.param_names_long = char(M_.param_names_long, 'cofintoutb4');
M_.param_names = char(M_.param_names, 'cofintoutf1');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutf1');
M_.param_names_long = char(M_.param_names_long, 'cofintoutf1');
M_.param_names = char(M_.param_names, 'cofintoutf2');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutf2');
M_.param_names_long = char(M_.param_names_long, 'cofintoutf2');
M_.param_names = char(M_.param_names, 'cofintoutf3');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutf3');
M_.param_names_long = char(M_.param_names_long, 'cofintoutf3');
M_.param_names = char(M_.param_names, 'cofintoutf4');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutf4');
M_.param_names_long = char(M_.param_names_long, 'cofintoutf4');
M_.param_names = char(M_.param_names, 'cofintoutp');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutp');
M_.param_names_long = char(M_.param_names_long, 'cofintoutp');
M_.param_names = char(M_.param_names, 'cofintoutpb1');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpb1');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpb1');
M_.param_names = char(M_.param_names, 'cofintoutpb2');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpb2');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpb2');
M_.param_names = char(M_.param_names, 'cofintoutpb3');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpb3');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpb3');
M_.param_names = char(M_.param_names, 'cofintoutpb4');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpb4');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpb4');
M_.param_names = char(M_.param_names, 'cofintoutpf1');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpf1');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpf1');
M_.param_names = char(M_.param_names, 'cofintoutpf2');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpf2');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpf2');
M_.param_names = char(M_.param_names, 'cofintoutpf3');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpf3');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpf3');
M_.param_names = char(M_.param_names, 'cofintoutpf4');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpf4');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpf4');
M_.param_names = char(M_.param_names, 'std_r_');
M_.param_names_tex = char(M_.param_names_tex, 'std\_r\_');
M_.param_names_long = char(M_.param_names_long, 'std_r_');
M_.param_names = char(M_.param_names, 'std_r_quart');
M_.param_names_tex = char(M_.param_names_tex, 'std\_r\_quart');
M_.param_names_long = char(M_.param_names_long, 'std_r_quart');
M_.param_names = char(M_.param_names, 'coffispol');
M_.param_names_tex = char(M_.param_names_tex, 'coffispol');
M_.param_names_long = char(M_.param_names_long, 'coffispol');
M_.param_names = char(M_.param_names, 'AD');
M_.param_names_tex = char(M_.param_names_tex, 'AD');
M_.param_names_long = char(M_.param_names_long, 'AD');
M_.param_names = char(M_.param_names, 'bet');
M_.param_names_tex = char(M_.param_names_tex, 'bet');
M_.param_names_long = char(M_.param_names_long, 'bet');
M_.param_names = char(M_.param_names, 'delt');
M_.param_names_tex = char(M_.param_names_tex, 'delt');
M_.param_names_long = char(M_.param_names_long, 'delt');
M_.param_names = char(M_.param_names, 'alph');
M_.param_names_tex = char(M_.param_names_tex, 'alph');
M_.param_names_long = char(M_.param_names_long, 'alph');
M_.param_names = char(M_.param_names, 'etaw');
M_.param_names_tex = char(M_.param_names_tex, 'etaw');
M_.param_names_long = char(M_.param_names_long, 'etaw');
M_.param_names = char(M_.param_names, 'etap');
M_.param_names_tex = char(M_.param_names_tex, 'etap');
M_.param_names_long = char(M_.param_names_long, 'etap');
M_.param_names = char(M_.param_names, 'gamm100');
M_.param_names_tex = char(M_.param_names_tex, 'gamm100');
M_.param_names_long = char(M_.param_names_long, 'gamm100');
M_.param_names = char(M_.param_names, 'xi');
M_.param_names_tex = char(M_.param_names_tex, 'xi');
M_.param_names_long = char(M_.param_names_long, 'xi');
M_.param_names = char(M_.param_names, 'muHH');
M_.param_names_tex = char(M_.param_names_tex, 'muHH');
M_.param_names_long = char(M_.param_names_long, 'muHH');
M_.param_names = char(M_.param_names, 'omegaw');
M_.param_names_tex = char(M_.param_names_tex, 'omegaw');
M_.param_names_long = char(M_.param_names_long, 'omegaw');
M_.param_names = char(M_.param_names, 'omegap');
M_.param_names_tex = char(M_.param_names_tex, 'omegap');
M_.param_names_long = char(M_.param_names_long, 'omegap');
M_.param_names = char(M_.param_names, 'gpsi');
M_.param_names_tex = char(M_.param_names_tex, 'gpsi');
M_.param_names_long = char(M_.param_names_long, 'gpsi');
M_.param_names = char(M_.param_names, 's');
M_.param_names_tex = char(M_.param_names_tex, 's');
M_.param_names_long = char(M_.param_names_long, 's');
M_.param_names = char(M_.param_names, 'chiw');
M_.param_names_tex = char(M_.param_names_tex, 'chiw');
M_.param_names_long = char(M_.param_names_long, 'chiw');
M_.param_names = char(M_.param_names, 'chip');
M_.param_names_tex = char(M_.param_names_tex, 'chip');
M_.param_names_long = char(M_.param_names_long, 'chip');
M_.param_names = char(M_.param_names, 'phipi');
M_.param_names_tex = char(M_.param_names_tex, 'phipi');
M_.param_names_long = char(M_.param_names_long, 'phipi');
M_.param_names = char(M_.param_names, 'phiy');
M_.param_names_tex = char(M_.param_names_tex, 'phiy');
M_.param_names_long = char(M_.param_names_long, 'phiy');
M_.param_names = char(M_.param_names, 'gammgc');
M_.param_names_tex = char(M_.param_names_tex, 'gammgc');
M_.param_names_long = char(M_.param_names_long, 'gammgc');
M_.param_names = char(M_.param_names, 'gammtk');
M_.param_names_tex = char(M_.param_names_tex, 'gammtk');
M_.param_names_long = char(M_.param_names_long, 'gammtk');
M_.param_names = char(M_.param_names, 'gammtl');
M_.param_names_tex = char(M_.param_names_tex, 'gammtl');
M_.param_names_long = char(M_.param_names_long, 'gammtl');
M_.param_names = char(M_.param_names, 'gammz');
M_.param_names_tex = char(M_.param_names_tex, 'gammz');
M_.param_names_long = char(M_.param_names_long, 'gammz');
M_.param_names = char(M_.param_names, 'rhoa');
M_.param_names_tex = char(M_.param_names_tex, 'rhoa');
M_.param_names_long = char(M_.param_names_long, 'rhoa');
M_.param_names = char(M_.param_names, 'rhob');
M_.param_names_tex = char(M_.param_names_tex, 'rhob');
M_.param_names_long = char(M_.param_names_long, 'rhob');
M_.param_names = char(M_.param_names, 'rhor');
M_.param_names_tex = char(M_.param_names_tex, 'rhor');
M_.param_names_long = char(M_.param_names_long, 'rhor');
M_.param_names = char(M_.param_names, 'rhoi');
M_.param_names_tex = char(M_.param_names_tex, 'rhoi');
M_.param_names_long = char(M_.param_names_long, 'rhoi');
M_.param_names = char(M_.param_names, 'rhow');
M_.param_names_tex = char(M_.param_names_tex, 'rhow');
M_.param_names_long = char(M_.param_names_long, 'rhow');
M_.param_names = char(M_.param_names, 'rhop');
M_.param_names_tex = char(M_.param_names_tex, 'rhop');
M_.param_names_long = char(M_.param_names_long, 'rhop');
M_.param_names = char(M_.param_names, 'rhogc');
M_.param_names_tex = char(M_.param_names_tex, 'rhogc');
M_.param_names_long = char(M_.param_names_long, 'rhogc');
M_.param_names = char(M_.param_names, 'rhotk');
M_.param_names_tex = char(M_.param_names_tex, 'rhotk');
M_.param_names_long = char(M_.param_names_long, 'rhotk');
M_.param_names = char(M_.param_names, 'rhotl');
M_.param_names_tex = char(M_.param_names_tex, 'rhotl');
M_.param_names_long = char(M_.param_names_long, 'rhotl');
M_.param_names = char(M_.param_names, 'rhotc');
M_.param_names_tex = char(M_.param_names_tex, 'rhotc');
M_.param_names_long = char(M_.param_names_long, 'rhotc');
M_.param_names = char(M_.param_names, 'rhoz');
M_.param_names_tex = char(M_.param_names_tex, 'rhoz');
M_.param_names_long = char(M_.param_names_long, 'rhoz');
M_.param_names = char(M_.param_names, 'siga');
M_.param_names_tex = char(M_.param_names_tex, 'siga');
M_.param_names_long = char(M_.param_names_long, 'siga');
M_.param_names = char(M_.param_names, 'sigb');
M_.param_names_tex = char(M_.param_names_tex, 'sigb');
M_.param_names_long = char(M_.param_names_long, 'sigb');
M_.param_names = char(M_.param_names, 'sigm');
M_.param_names_tex = char(M_.param_names_tex, 'sigm');
M_.param_names_long = char(M_.param_names_long, 'sigm');
M_.param_names = char(M_.param_names, 'sigi');
M_.param_names_tex = char(M_.param_names_tex, 'sigi');
M_.param_names_long = char(M_.param_names_long, 'sigi');
M_.param_names = char(M_.param_names, 'sigw');
M_.param_names_tex = char(M_.param_names_tex, 'sigw');
M_.param_names_long = char(M_.param_names_long, 'sigw');
M_.param_names = char(M_.param_names, 'sigp');
M_.param_names_tex = char(M_.param_names_tex, 'sigp');
M_.param_names_long = char(M_.param_names_long, 'sigp');
M_.param_names = char(M_.param_names, 'siggc');
M_.param_names_tex = char(M_.param_names_tex, 'siggc');
M_.param_names_long = char(M_.param_names_long, 'siggc');
M_.param_names = char(M_.param_names, 'sigz');
M_.param_names_tex = char(M_.param_names_tex, 'sigz');
M_.param_names_long = char(M_.param_names_long, 'sigz');
M_.param_names = char(M_.param_names, 'thet');
M_.param_names_tex = char(M_.param_names_tex, 'thet');
M_.param_names_long = char(M_.param_names_long, 'thet');
M_.param_names = char(M_.param_names, 'alphag');
M_.param_names_tex = char(M_.param_names_tex, 'alphag');
M_.param_names_long = char(M_.param_names_long, 'alphag');
M_.param_names = char(M_.param_names, 'rhoem');
M_.param_names_tex = char(M_.param_names_tex, 'rhoem');
M_.param_names_long = char(M_.param_names_long, 'rhoem');
M_.param_names = char(M_.param_names, 'rhoeg');
M_.param_names_tex = char(M_.param_names_tex, 'rhoeg');
M_.param_names_long = char(M_.param_names_long, 'rhoeg');
M_.param_names = char(M_.param_names, 'rhoez');
M_.param_names_tex = char(M_.param_names_tex, 'rhoez');
M_.param_names_long = char(M_.param_names_long, 'rhoez');
M_.param_names = char(M_.param_names, 'Lbar');
M_.param_names_tex = char(M_.param_names_tex, 'Lbar');
M_.param_names_long = char(M_.param_names_long, 'Lbar');
M_.param_names = char(M_.param_names, 'Pibar');
M_.param_names_tex = char(M_.param_names_tex, 'Pibar');
M_.param_names_long = char(M_.param_names_long, 'Pibar');
M_.param_names = char(M_.param_names, 'lamprice');
M_.param_names_tex = char(M_.param_names_tex, 'lamprice');
M_.param_names_long = char(M_.param_names_long, 'lamprice');
M_.param_names = char(M_.param_names, 'lamwage');
M_.param_names_tex = char(M_.param_names_tex, 'lamwage');
M_.param_names_long = char(M_.param_names_long, 'lamwage');
M_.param_names = char(M_.param_names, 'sbss');
M_.param_names_tex = char(M_.param_names_tex, 'sbss');
M_.param_names_long = char(M_.param_names_long, 'sbss');
M_.param_names = char(M_.param_names, 'taulss');
M_.param_names_tex = char(M_.param_names_tex, 'taulss');
M_.param_names_long = char(M_.param_names_long, 'taulss');
M_.param_names = char(M_.param_names, 'taukss');
M_.param_names_tex = char(M_.param_names_tex, 'taukss');
M_.param_names_long = char(M_.param_names_long, 'taukss');
M_.param_names = char(M_.param_names, 'taucss');
M_.param_names_tex = char(M_.param_names_tex, 'taucss');
M_.param_names_long = char(M_.param_names_long, 'taucss');
M_.param_names = char(M_.param_names, 'Rhoss');
M_.param_names_tex = char(M_.param_names_tex, 'Rhoss');
M_.param_names_long = char(M_.param_names_long, 'Rhoss');
M_.param_names = char(M_.param_names, 'gammss');
M_.param_names_tex = char(M_.param_names_tex, 'gammss');
M_.param_names_long = char(M_.param_names_long, 'gammss');
M_.param_names = char(M_.param_names, 'expgss');
M_.param_names_tex = char(M_.param_names_tex, 'expgss');
M_.param_names_long = char(M_.param_names_long, 'expgss');
M_.param_names = char(M_.param_names, 'Rss');
M_.param_names_tex = char(M_.param_names_tex, 'Rss');
M_.param_names_long = char(M_.param_names_long, 'Rss');
M_.param_names = char(M_.param_names, 'Rbarss');
M_.param_names_tex = char(M_.param_names_tex, 'Rbarss');
M_.param_names_long = char(M_.param_names_long, 'Rbarss');
M_.param_names = char(M_.param_names, 'Pbss');
M_.param_names_tex = char(M_.param_names_tex, 'Pbss');
M_.param_names_long = char(M_.param_names_long, 'Pbss');
M_.param_names = char(M_.param_names, 'Rkss');
M_.param_names_tex = char(M_.param_names_tex, 'Rkss');
M_.param_names_long = char(M_.param_names_long, 'Rkss');
M_.param_names = char(M_.param_names, 'psi1ss');
M_.param_names_tex = char(M_.param_names_tex, 'psi1ss');
M_.param_names_long = char(M_.param_names_long, 'psi1ss');
M_.param_names = char(M_.param_names, 'mcss');
M_.param_names_tex = char(M_.param_names_tex, 'mcss');
M_.param_names_long = char(M_.param_names_long, 'mcss');
M_.param_names = char(M_.param_names, 'wss');
M_.param_names_tex = char(M_.param_names_tex, 'wss');
M_.param_names_long = char(M_.param_names_long, 'wss');
M_.param_names = char(M_.param_names, 'KLss');
M_.param_names_tex = char(M_.param_names_tex, 'KLss');
M_.param_names_long = char(M_.param_names_long, 'KLss');
M_.param_names = char(M_.param_names, 'OmegLss');
M_.param_names_tex = char(M_.param_names_tex, 'OmegLss');
M_.param_names_long = char(M_.param_names_long, 'OmegLss');
M_.param_names = char(M_.param_names, 'YLss');
M_.param_names_tex = char(M_.param_names_tex, 'YLss');
M_.param_names_long = char(M_.param_names_long, 'YLss');
M_.param_names = char(M_.param_names, 'ILss');
M_.param_names_tex = char(M_.param_names_tex, 'ILss');
M_.param_names_long = char(M_.param_names_long, 'ILss');
M_.param_names = char(M_.param_names, 'CLss');
M_.param_names_tex = char(M_.param_names_tex, 'CLss');
M_.param_names_long = char(M_.param_names_long, 'CLss');
M_.param_names = char(M_.param_names, 'rkss');
M_.param_names_tex = char(M_.param_names_tex, 'rkss');
M_.param_names_long = char(M_.param_names_long, 'rkss');
M_.param_names = char(M_.param_names, 'ZLss');
M_.param_names_tex = char(M_.param_names_tex, 'ZLss');
M_.param_names_long = char(M_.param_names_long, 'ZLss');
M_.param_names = char(M_.param_names, 'ZnLss');
M_.param_names_tex = char(M_.param_names_tex, 'ZnLss');
M_.param_names_long = char(M_.param_names_long, 'ZnLss');
M_.param_names = char(M_.param_names, 'CnLss');
M_.param_names_tex = char(M_.param_names_tex, 'CnLss');
M_.param_names_long = char(M_.param_names_long, 'CnLss');
M_.param_names = char(M_.param_names, 'CsLss');
M_.param_names_tex = char(M_.param_names_tex, 'CsLss');
M_.param_names_long = char(M_.param_names_long, 'CsLss');
M_.param_names = char(M_.param_names, 'CstarLss');
M_.param_names_tex = char(M_.param_names_tex, 'CstarLss');
M_.param_names_long = char(M_.param_names_long, 'CstarLss');
M_.param_names = char(M_.param_names, 'lss');
M_.param_names_tex = char(M_.param_names_tex, 'lss');
M_.param_names_long = char(M_.param_names_long, 'lss');
M_.param_names = char(M_.param_names, 'csss');
M_.param_names_tex = char(M_.param_names_tex, 'csss');
M_.param_names_long = char(M_.param_names_long, 'csss');
M_.param_names = char(M_.param_names, 'cnss');
M_.param_names_tex = char(M_.param_names_tex, 'cnss');
M_.param_names_long = char(M_.param_names_long, 'cnss');
M_.param_names = char(M_.param_names, 'yss');
M_.param_names_tex = char(M_.param_names_tex, 'yss');
M_.param_names_long = char(M_.param_names_long, 'yss');
M_.param_names = char(M_.param_names, 'kss');
M_.param_names_tex = char(M_.param_names_tex, 'kss');
M_.param_names_long = char(M_.param_names_long, 'kss');
M_.param_names = char(M_.param_names, 'Omegss');
M_.param_names_tex = char(M_.param_names_tex, 'Omegss');
M_.param_names_long = char(M_.param_names_long, 'Omegss');
M_.param_names = char(M_.param_names, 'css');
M_.param_names_tex = char(M_.param_names_tex, 'css');
M_.param_names_long = char(M_.param_names_long, 'css');
M_.param_names = char(M_.param_names, 'invss');
M_.param_names_tex = char(M_.param_names_tex, 'invss');
M_.param_names_long = char(M_.param_names_long, 'invss');
M_.param_names = char(M_.param_names, 'zss');
M_.param_names_tex = char(M_.param_names_tex, 'zss');
M_.param_names_long = char(M_.param_names_long, 'zss');
M_.param_names = char(M_.param_names, 'bss');
M_.param_names_tex = char(M_.param_names_tex, 'bss');
M_.param_names_long = char(M_.param_names_long, 'bss');
M_.param_names = char(M_.param_names, 'gcss');
M_.param_names_tex = char(M_.param_names_tex, 'gcss');
M_.param_names_long = char(M_.param_names_long, 'gcss');
M_.param_names = char(M_.param_names, 'kyss');
M_.param_names_tex = char(M_.param_names_tex, 'kyss');
M_.param_names_long = char(M_.param_names_long, 'kyss');
M_.param_names = char(M_.param_names, 'cyss');
M_.param_names_tex = char(M_.param_names_tex, 'cyss');
M_.param_names_long = char(M_.param_names_long, 'cyss');
M_.param_names = char(M_.param_names, 'lyss');
M_.param_names_tex = char(M_.param_names_tex, 'lyss');
M_.param_names_long = char(M_.param_names_long, 'lyss');
M_.param_names = char(M_.param_names, 'TKss');
M_.param_names_tex = char(M_.param_names_tex, 'TKss');
M_.param_names_long = char(M_.param_names_long, 'TKss');
M_.param_names = char(M_.param_names, 'TLss');
M_.param_names_tex = char(M_.param_names_tex, 'TLss');
M_.param_names_long = char(M_.param_names_long, 'TLss');
M_.param_names = char(M_.param_names, 'TCss');
M_.param_names_tex = char(M_.param_names_tex, 'TCss');
M_.param_names_long = char(M_.param_names_long, 'TCss');
M_.param_names = char(M_.param_names, 'Sss');
M_.param_names_tex = char(M_.param_names_tex, 'Sss');
M_.param_names_long = char(M_.param_names_long, 'Sss');
M_.param_names = char(M_.param_names, 'sgcss');
M_.param_names_tex = char(M_.param_names_tex, 'sgcss');
M_.param_names_long = char(M_.param_names_long, 'sgcss');
M_.param_names = char(M_.param_names, 'lampricef');
M_.param_names_tex = char(M_.param_names_tex, 'lampricef');
M_.param_names_long = char(M_.param_names_long, 'lampricef');
M_.param_names = char(M_.param_names, 'lamwagef');
M_.param_names_tex = char(M_.param_names_tex, 'lamwagef');
M_.param_names_long = char(M_.param_names_long, 'lamwagef');
M_.param_partitions = struct();
M_.exo_det_nbr = 0;
M_.exo_nbr = 9;
M_.endo_nbr = 112;
M_.param_nbr = 129;
M_.orig_endo_nbr = 89;
M_.aux_vars(1).endo_index = 90;
M_.aux_vars(1).type = 0;
M_.aux_vars(2).endo_index = 91;
M_.aux_vars(2).type = 0;
M_.aux_vars(3).endo_index = 92;
M_.aux_vars(3).type = 0;
M_.aux_vars(4).endo_index = 93;
M_.aux_vars(4).type = 0;
M_.aux_vars(5).endo_index = 94;
M_.aux_vars(5).type = 0;
M_.aux_vars(6).endo_index = 95;
M_.aux_vars(6).type = 0;
M_.aux_vars(7).endo_index = 96;
M_.aux_vars(7).type = 0;
M_.aux_vars(8).endo_index = 97;
M_.aux_vars(8).type = 0;
M_.aux_vars(9).endo_index = 98;
M_.aux_vars(9).type = 0;
M_.aux_vars(10).endo_index = 99;
M_.aux_vars(10).type = 1;
M_.aux_vars(10).orig_index = 14;
M_.aux_vars(10).orig_lead_lag = -1;
M_.aux_vars(11).endo_index = 100;
M_.aux_vars(11).type = 1;
M_.aux_vars(11).orig_index = 14;
M_.aux_vars(11).orig_lead_lag = -2;
M_.aux_vars(12).endo_index = 101;
M_.aux_vars(12).type = 1;
M_.aux_vars(12).orig_index = 88;
M_.aux_vars(12).orig_lead_lag = -1;
M_.aux_vars(13).endo_index = 102;
M_.aux_vars(13).type = 1;
M_.aux_vars(13).orig_index = 88;
M_.aux_vars(13).orig_lead_lag = -2;
M_.aux_vars(14).endo_index = 103;
M_.aux_vars(14).type = 1;
M_.aux_vars(14).orig_index = 88;
M_.aux_vars(14).orig_lead_lag = -3;
M_.aux_vars(15).endo_index = 104;
M_.aux_vars(15).type = 1;
M_.aux_vars(15).orig_index = 87;
M_.aux_vars(15).orig_lead_lag = -1;
M_.aux_vars(16).endo_index = 105;
M_.aux_vars(16).type = 1;
M_.aux_vars(16).orig_index = 87;
M_.aux_vars(16).orig_lead_lag = -2;
M_.aux_vars(17).endo_index = 106;
M_.aux_vars(17).type = 1;
M_.aux_vars(17).orig_index = 87;
M_.aux_vars(17).orig_lead_lag = -3;
M_.aux_vars(18).endo_index = 107;
M_.aux_vars(18).type = 1;
M_.aux_vars(18).orig_index = 84;
M_.aux_vars(18).orig_lead_lag = -1;
M_.aux_vars(19).endo_index = 108;
M_.aux_vars(19).type = 1;
M_.aux_vars(19).orig_index = 84;
M_.aux_vars(19).orig_lead_lag = -2;
M_.aux_vars(20).endo_index = 109;
M_.aux_vars(20).type = 1;
M_.aux_vars(20).orig_index = 84;
M_.aux_vars(20).orig_lead_lag = -3;
M_.aux_vars(21).endo_index = 110;
M_.aux_vars(21).type = 1;
M_.aux_vars(21).orig_index = 86;
M_.aux_vars(21).orig_lead_lag = -1;
M_.aux_vars(22).endo_index = 111;
M_.aux_vars(22).type = 1;
M_.aux_vars(22).orig_index = 86;
M_.aux_vars(22).orig_lead_lag = -2;
M_.aux_vars(23).endo_index = 112;
M_.aux_vars(23).type = 1;
M_.aux_vars(23).orig_index = 86;
M_.aux_vars(23).orig_lead_lag = -3;
M_.Sigma_e = zeros(9, 9);
M_.Correlation_matrix = eye(9, 9);
M_.H = 0;
M_.Correlation_matrix_ME = 1;
M_.sigma_e_is_diagonal = 1;
M_.det_shocks = [];
options_.linear = 1;
options_.block=0;
options_.bytecode=0;
options_.use_dll=0;
M_.hessian_eq_zero = 1;
erase_compiled_function('US_LTW17_static');
erase_compiled_function('US_LTW17_dynamic');
M_.orig_eq_nbr = 89;
M_.eq_nbr = 112;
M_.ramsey_eq_nbr = 0;
M_.set_auxiliary_variables = exist(['./' M_.fname '_set_auxiliary_variables.m'], 'file') == 2;
M_.lead_lag_incidence = [
 0 53 0;
 0 54 0;
 0 55 0;
 1 56 165;
 0 57 0;
 0 58 0;
 0 59 0;
 0 60 0;
 2 61 0;
 3 62 0;
 0 63 166;
 0 64 167;
 4 65 168;
 5 66 169;
 6 67 0;
 7 68 0;
 8 69 170;
 9 70 0;
 10 71 0;
 0 72 0;
 11 73 0;
 0 74 0;
 12 75 0;
 0 76 171;
 13 77 172;
 14 78 0;
 0 79 0;
 0 80 173;
 0 81 0;
 0 82 0;
 0 83 0;
 0 84 0;
 0 85 0;
 0 86 0;
 0 87 0;
 0 88 0;
 0 89 0;
 0 90 0;
 0 91 0;
 0 92 0;
 0 93 0;
 0 94 0;
 15 95 0;
 16 96 0;
 17 97 0;
 18 98 0;
 19 99 0;
 20 100 0;
 21 101 0;
 0 102 0;
 0 103 0;
 22 104 174;
 0 105 0;
 0 106 0;
 0 107 0;
 0 108 0;
 23 109 0;
 24 110 0;
 0 111 175;
 0 112 176;
 25 113 0;
 26 114 0;
 27 115 0;
 28 116 177;
 29 117 0;
 30 118 0;
 0 119 0;
 31 120 0;
 0 121 0;
 32 122 0;
 0 123 178;
 33 124 0;
 0 125 0;
 34 126 0;
 0 127 0;
 0 128 0;
 0 129 0;
 0 130 0;
 0 131 0;
 0 132 0;
 0 133 0;
 0 134 0;
 0 135 0;
 35 136 0;
 0 137 0;
 36 138 179;
 37 139 180;
 38 140 181;
 0 141 0;
 0 142 182;
 0 143 183;
 0 144 184;
 0 145 185;
 0 146 186;
 0 147 187;
 0 148 188;
 0 149 189;
 0 150 190;
 39 151 0;
 40 152 0;
 41 153 0;
 42 154 0;
 43 155 0;
 44 156 0;
 45 157 0;
 46 158 0;
 47 159 0;
 48 160 0;
 49 161 0;
 50 162 0;
 51 163 0;
 52 164 0;]';
M_.nstatic = 44;
M_.nfwrd   = 16;
M_.npred   = 42;
M_.nboth   = 10;
M_.nsfwrd   = 26;
M_.nspred   = 52;
M_.ndynamic   = 68;
M_.equations_tags = {
};
M_.static_and_dynamic_models_differ = 0;
M_.exo_names_orig_ord = [1:9];
M_.maximum_lag = 1;
M_.maximum_lead = 1;
M_.maximum_endo_lag = 1;
M_.maximum_endo_lead = 1;
oo_.steady_state = zeros(112, 1);
M_.maximum_exo_lag = 0;
M_.maximum_exo_lead = 0;
oo_.exo_steady_state = zeros(9, 1);
M_.params = NaN(129, 1);
M_.NNZDerivatives = [444; 0; -1];
M_.params( 35 ) = 20;
AD = M_.params( 35 );
M_.params( 36 ) = 0.99;
bet = M_.params( 36 );
M_.params( 37 ) = 0.025;
delt = M_.params( 37 );
M_.params( 38 ) = 0.33;
alph = M_.params( 38 );
M_.params( 39 ) = 0.14;
etaw = M_.params( 39 );
M_.params( 40 ) = 0.14;
etap = M_.params( 40 );
M_.params( 127 ) = 0.11;
sgcss = M_.params( 127 );
M_.params( 84 ) = 1.47;
sbss = M_.params( 84 );
M_.params( 85 ) = 0.186;
taulss = M_.params( 85 );
M_.params( 86 ) = 0.218;
taukss = M_.params( 86 );
M_.params( 87 ) = 0.023;
taucss = M_.params( 87 );
M_.params( 41 ) = 0.242968973360760;
gamm100 = M_.params( 41 );
M_.params( 42 ) = 1.540098680199818;
xi = M_.params( 42 );
M_.params( 43 ) = 0;
muHH = M_.params( 43 );
M_.params( 44 ) = 0.873633441786572;
omegaw = M_.params( 44 );
M_.params( 45 ) = 0.889634877904653;
omegap = M_.params( 45 );
M_.params( 46 ) = 0.126297919145076;
gpsi = M_.params( 46 );
M_.params( 47 ) = 5.213147230492578;
s = M_.params( 47 );
M_.params( 48 ) = 0.089393160044567;
chiw = M_.params( 48 );
M_.params( 49 ) = 0.060355303068460;
chip = M_.params( 49 );
M_.params( 50 ) = 1.142492263502070;
phipi = M_.params( 50 );
M_.params( 51 ) = 0.178225311630840;
phiy = M_.params( 51 );
M_.params( 52 ) = 0.214956274043740;
gammgc = M_.params( 52 );
M_.params( 53 ) = 0;
gammtk = M_.params( 53 );
M_.params( 54 ) = 0;
gammtl = M_.params( 54 );
M_.params( 55 ) = (-0.028247874637231);
gammz = M_.params( 55 );
M_.params( 56 ) = 0.251431768280169;
rhoa = M_.params( 56 );
M_.params( 57 ) = 0.314713788054350;
rhob = M_.params( 57 );
M_.params( 58 ) = 0.756483804459602;
rhor = M_.params( 58 );
M_.params( 59 ) = 0.511411853483883;
rhoi = M_.params( 59 );
M_.params( 60 ) = 0.326894727384245;
rhow = M_.params( 60 );
M_.params( 61 ) = 0.724249353191094;
rhop = M_.params( 61 );
M_.params( 62 ) = 0.984047962915516;
rhogc = M_.params( 62 );
M_.params( 63 ) = 0;
rhotk = M_.params( 63 );
M_.params( 64 ) = 0;
rhotl = M_.params( 64 );
M_.params( 65 ) = 0;
rhotc = M_.params( 65 );
M_.params( 66 ) = 0.98;
rhoz = M_.params( 66 );
M_.params( 67 ) = 1.03292319884557;
siga = M_.params( 67 );
M_.params( 68 ) = 42.6559249998644;
sigb = M_.params( 68 );
M_.params( 69 ) = 0.231187433032408;
sigm = M_.params( 69 );
M_.params( 70 ) = 0.978941599253400;
sigi = M_.params( 70 );
M_.params( 71 ) = 0.250356962066959;
sigw = M_.params( 71 );
M_.params( 72 ) = 0.0988174659346631;
sigp = M_.params( 72 );
M_.params( 73 ) = 1.83235871273796;
siggc = M_.params( 73 );
M_.params( 74 ) = 2.68115974402062;
sigz = M_.params( 74 );
M_.params( 75 ) = 0.989468754445726;
thet = M_.params( 75 );
M_.params( 76 ) = (-0.185909020087479);
alphag = M_.params( 76 );
M_.params( 77 ) = 0.336277752958210;
rhoem = M_.params( 77 );
M_.params( 78 ) = 0.126568144141410;
rhoeg = M_.params( 78 );
M_.params( 79 ) = 0.8;
rhoez = M_.params( 79 );
M_.params( 80 ) = 475.202534563017;
Lbar = M_.params( 80 );
M_.params( 81 ) = 0.643991271663901;
Pibar = M_.params( 81 );
M_.params( 82 ) = (1+M_.params(36)*M_.params(49))*M_.params(45)/((1-M_.params(36)*M_.params(45))*(1-M_.params(45)));
lamprice = M_.params( 82 );
M_.params( 83 ) = M_.params(44)*(1+M_.params(36))*(1+M_.params(42)*(1+1/M_.params(39)))/((1-M_.params(36)*M_.params(44))*(1-M_.params(44)));
lamwage = M_.params( 83 );
M_.params( 128 ) = 0;
lampricef = M_.params( 128 );
M_.params( 129 ) = 0;
lamwagef = M_.params( 129 );
M_.params( 88 ) = (1-1/M_.params(35))*1/M_.params(36);
Rhoss = M_.params( 88 );
M_.params( 89 ) = M_.params(41)/100;
gammss = M_.params( 89 );
M_.params( 90 ) = exp(M_.params(89));
expgss = M_.params( 90 );
M_.params( 91 ) = M_.params(90)/M_.params(36);
Rss = M_.params( 91 );
M_.params( 92 ) = 100*(M_.params(91)-1);
Rbarss = M_.params( 92 );
M_.params( 93 ) = 1/(M_.params(91)-M_.params(88));
Pbss = M_.params( 93 );
M_.params( 94 ) = (exp(M_.params(89))/M_.params(36)-1+M_.params(37))/(1-M_.params(86));
Rkss = M_.params( 94 );
M_.params( 95 ) = (1-M_.params(86))*M_.params(94);
psi1ss = M_.params( 95 );
M_.params( 96 ) = 1/(1+M_.params(40));
mcss = M_.params( 96 );
M_.params( 97 ) = (M_.params(96)*(1-M_.params(38))^(1-M_.params(38))*M_.params(38)^M_.params(38)*M_.params(94)^(-M_.params(38)))^(1/(1-M_.params(38)));
wss = M_.params( 97 );
M_.params( 98 ) = M_.params(38)*M_.params(97)/M_.params(94)/(1-M_.params(38));
KLss = M_.params( 98 );
M_.params( 99 ) = M_.params(98)^M_.params(38)-M_.params(94)*M_.params(98)-M_.params(97);
OmegLss = M_.params( 99 );
M_.params( 100 ) = M_.params(98)^M_.params(38)-M_.params(99);
YLss = M_.params( 100 );
M_.params( 101 ) = M_.params(98)*M_.params(90)*(1-(1-M_.params(37))*exp((-M_.params(89))));
ILss = M_.params( 101 );
M_.params( 102 ) = M_.params(100)*(1-M_.params(127))-M_.params(101);
CLss = M_.params( 102 );
M_.params( 103 ) = M_.params(94);
rkss = M_.params( 103 );
M_.params( 104 ) = M_.params(100)*((1-M_.params(91)*exp((-M_.params(89))))*M_.params(84)-M_.params(127))+M_.params(87)*M_.params(102)+M_.params(97)*M_.params(85)+M_.params(98)*M_.params(86)*M_.params(103);
ZLss = M_.params( 104 );
M_.params( 105 ) = M_.params(104);
ZnLss = M_.params( 105 );
M_.params( 106 ) = (M_.params(97)*(1-M_.params(85))+M_.params(105))/(1+M_.params(87));
CnLss = M_.params( 106 );
M_.params( 107 ) = (M_.params(102)-M_.params(43)*M_.params(106))/(1-M_.params(43));
CsLss = M_.params( 107 );
M_.params( 108 ) = M_.params(107)+M_.params(100)*M_.params(127)*M_.params(76);
CstarLss = M_.params( 108 );
M_.params( 109 ) = (M_.params(97)*(1-M_.params(85))/((1+M_.params(87))*(1+M_.params(39)))*1/((1-exp((-M_.params(89)))*M_.params(75))*M_.params(108)))^(1/(1+M_.params(42)));
lss = M_.params( 109 );
M_.params( 110 ) = M_.params(107)*M_.params(109);
csss = M_.params( 110 );
M_.params( 111 ) = M_.params(106)*M_.params(109);
cnss = M_.params( 111 );
M_.params( 112 ) = M_.params(100)*M_.params(109);
yss = M_.params( 112 );
M_.params( 113 ) = M_.params(98)*M_.params(109);
kss = M_.params( 113 );
M_.params( 114 ) = M_.params(99)*M_.params(109);
Omegss = M_.params( 114 );
M_.params( 115 ) = M_.params(102)*M_.params(109);
css = M_.params( 115 );
M_.params( 116 ) = M_.params(101)*M_.params(109);
invss = M_.params( 116 );
M_.params( 117 ) = M_.params(104)*M_.params(109);
zss = M_.params( 117 );
M_.params( 118 ) = M_.params(84)*M_.params(112);
bss = M_.params( 118 );
M_.params( 119 ) = M_.params(127)*M_.params(112);
gcss = M_.params( 119 );
M_.params( 120 ) = M_.params(113)/M_.params(112);
kyss = M_.params( 120 );
M_.params( 121 ) = M_.params(115)/M_.params(112);
cyss = M_.params( 121 );
M_.params( 122 ) = M_.params(109)/M_.params(112);
lyss = M_.params( 122 );
M_.params( 123 ) = M_.params(86)*M_.params(103)*M_.params(113);
TKss = M_.params( 123 );
M_.params( 124 ) = M_.params(97)*M_.params(85)*M_.params(109);
TLss = M_.params( 124 );
M_.params( 125 ) = M_.params(87)*M_.params(115);
TCss = M_.params( 125 );
M_.params( 126 ) = M_.params(87)*M_.params(115)+M_.params(86)*M_.params(103)*M_.params(113)+M_.params(97)*M_.params(85)*M_.params(109)-M_.params(119)-M_.params(117);
Sss = M_.params( 126 );
thispath = cd;                                                           
cd('..');                                                                
load policy_param.mat;                                                   
for i=1:33                                                               
deep_parameter_name = M_.param_names(i,:);                           
eval(['M_.params(i)  = ' deep_parameter_name ' ;'])                  
end                                                                      
cd(thispath);       
M_.params( 34 ) = 1/M_.params(127);
coffispol = M_.params( 34 );
%
% SHOCKS instructions
%
M_.exo_det_length = 0;
M_.Sigma_e(1, 1) = M_.params(74)^2;
M_.Sigma_e(2, 2) = M_.params(67)^2;
M_.Sigma_e(3, 3) = M_.params(68)^2;
M_.Sigma_e(4, 4) = 0.0625;
M_.Sigma_e(5, 5) = M_.params(70)^2;
M_.Sigma_e(6, 6) = M_.params(71)^2;
M_.Sigma_e(7, 7) = M_.params(72)^2;
save('US_LTW17_results.mat', 'oo_', 'M_', 'options_');
if exist('estim_params_', 'var') == 1
  save('US_LTW17_results.mat', 'estim_params_', '-append');
end
if exist('bayestopt_', 'var') == 1
  save('US_LTW17_results.mat', 'bayestopt_', '-append');
end
if exist('dataset_', 'var') == 1
  save('US_LTW17_results.mat', 'dataset_', '-append');
end
if exist('estimation_info', 'var') == 1
  save('US_LTW17_results.mat', 'estimation_info', '-append');
end
if exist('dataset_info', 'var') == 1
  save('US_LTW17_results.mat', 'dataset_info', '-append');
end
if exist('oo_recursive_', 'var') == 1
  save('US_LTW17_results.mat', 'oo_recursive_', '-append');
end


disp(['Total computing time : ' dynsec2hms(toc(tic0)) ]);
if ~isempty(lastwarn)
  disp('Note: warning(s) encountered in MATLAB/Octave code')
end
diary off
