%
% Status : main Dynare file 
%
% Warning : this file is generated automatically by Dynare
%           from model file (.mod)

tic;
global M_ oo_ options_ ys0_ ex0_ estimation_info
options_ = [];
M_.fname = 'US_CD08';
%
% Some global variables initialization
%
global_initialization;
diary off;
diary('US_CD08.log');
M_.exo_names = 'u_x';
M_.exo_names_tex = 'u\_x';
M_.exo_names_long = 'u_x';
M_.exo_names = char(M_.exo_names, 'u_a');
M_.exo_names_tex = char(M_.exo_names_tex, 'u\_a');
M_.exo_names_long = char(M_.exo_names_long, 'u_a');
M_.exo_names = char(M_.exo_names, 'u_e');
M_.exo_names_tex = char(M_.exo_names_tex, 'u\_e');
M_.exo_names_long = char(M_.exo_names_long, 'u_e');
M_.exo_names = char(M_.exo_names, 'u_b');
M_.exo_names_tex = char(M_.exo_names_tex, 'u\_b');
M_.exo_names_long = char(M_.exo_names_long, 'u_b');
M_.exo_names = char(M_.exo_names, 'interest_');
M_.exo_names_tex = char(M_.exo_names_tex, 'interest\_');
M_.exo_names_long = char(M_.exo_names_long, 'interest_');
M_.endo_names = 'lambda';
M_.endo_names_tex = 'lambda';
M_.endo_names_long = 'lambda';
M_.endo_names = char(M_.endo_names, 'c');
M_.endo_names_tex = char(M_.endo_names_tex, 'c');
M_.endo_names_long = char(M_.endo_names_long, 'c');
M_.endo_names = char(M_.endo_names, 'b');
M_.endo_names_tex = char(M_.endo_names_tex, 'b');
M_.endo_names_long = char(M_.endo_names_long, 'b');
M_.endo_names = char(M_.endo_names, 'm');
M_.endo_names_tex = char(M_.endo_names_tex, 'm');
M_.endo_names_long = char(M_.endo_names_long, 'm');
M_.endo_names = char(M_.endo_names, 'e');
M_.endo_names_tex = char(M_.endo_names_tex, 'e');
M_.endo_names_long = char(M_.endo_names_long, 'e');
M_.endo_names = char(M_.endo_names, 'r');
M_.endo_names_tex = char(M_.endo_names_tex, 'r');
M_.endo_names_long = char(M_.endo_names_long, 'r');
M_.endo_names = char(M_.endo_names, 'h');
M_.endo_names_tex = char(M_.endo_names_tex, 'h');
M_.endo_names_long = char(M_.endo_names_long, 'h');
M_.endo_names = char(M_.endo_names, 'w');
M_.endo_names_tex = char(M_.endo_names_tex, 'w');
M_.endo_names_long = char(M_.endo_names_long, 'w');
M_.endo_names = char(M_.endo_names, 'y');
M_.endo_names_tex = char(M_.endo_names_tex, 'y');
M_.endo_names_long = char(M_.endo_names_long, 'y');
M_.endo_names = char(M_.endo_names, 'k');
M_.endo_names_tex = char(M_.endo_names_tex, 'k');
M_.endo_names_long = char(M_.endo_names_long, 'k');
M_.endo_names = char(M_.endo_names, 'a');
M_.endo_names_tex = char(M_.endo_names_tex, 'a');
M_.endo_names_long = char(M_.endo_names_long, 'a');
M_.endo_names = char(M_.endo_names, 'i');
M_.endo_names_tex = char(M_.endo_names_tex, 'i');
M_.endo_names_long = char(M_.endo_names_long, 'i');
M_.endo_names = char(M_.endo_names, 'cost');
M_.endo_names_tex = char(M_.endo_names_tex, 'cost');
M_.endo_names_long = char(M_.endo_names_long, 'cost');
M_.endo_names = char(M_.endo_names, 'z');
M_.endo_names_tex = char(M_.endo_names_tex, 'z');
M_.endo_names_long = char(M_.endo_names_long, 'z');
M_.endo_names = char(M_.endo_names, 'mu');
M_.endo_names_tex = char(M_.endo_names_tex, 'mu');
M_.endo_names_long = char(M_.endo_names_long, 'mu');
M_.endo_names = char(M_.endo_names, 'pi');
M_.endo_names_tex = char(M_.endo_names_tex, 'pi');
M_.endo_names_long = char(M_.endo_names_long, 'pi');
M_.endo_names = char(M_.endo_names, 'q');
M_.endo_names_tex = char(M_.endo_names_tex, 'q');
M_.endo_names_long = char(M_.endo_names_long, 'q');
M_.endo_names = char(M_.endo_names, 'x');
M_.endo_names_tex = char(M_.endo_names_tex, 'x');
M_.endo_names_long = char(M_.endo_names_long, 'x');
M_.endo_names = char(M_.endo_names, 'f');
M_.endo_names_tex = char(M_.endo_names_tex, 'f');
M_.endo_names_long = char(M_.endo_names_long, 'f');
M_.endo_names = char(M_.endo_names, 'n');
M_.endo_names_tex = char(M_.endo_names_tex, 'n');
M_.endo_names_long = char(M_.endo_names_long, 'n');
M_.endo_names = char(M_.endo_names, 'rp');
M_.endo_names_tex = char(M_.endo_names_tex, 'rp');
M_.endo_names_long = char(M_.endo_names_long, 'rp');
M_.endo_names = char(M_.endo_names, 'lambda_f');
M_.endo_names_tex = char(M_.endo_names_tex, 'lambda\_f');
M_.endo_names_long = char(M_.endo_names_long, 'lambda_f');
M_.endo_names = char(M_.endo_names, 'c_f');
M_.endo_names_tex = char(M_.endo_names_tex, 'c\_f');
M_.endo_names_long = char(M_.endo_names_long, 'c_f');
M_.endo_names = char(M_.endo_names, 'm_f');
M_.endo_names_tex = char(M_.endo_names_tex, 'm\_f');
M_.endo_names_long = char(M_.endo_names_long, 'm_f');
M_.endo_names = char(M_.endo_names, 'r_f');
M_.endo_names_tex = char(M_.endo_names_tex, 'r\_f');
M_.endo_names_long = char(M_.endo_names_long, 'r_f');
M_.endo_names = char(M_.endo_names, 'h_f');
M_.endo_names_tex = char(M_.endo_names_tex, 'h\_f');
M_.endo_names_long = char(M_.endo_names_long, 'h_f');
M_.endo_names = char(M_.endo_names, 'w_f');
M_.endo_names_tex = char(M_.endo_names_tex, 'w\_f');
M_.endo_names_long = char(M_.endo_names_long, 'w_f');
M_.endo_names = char(M_.endo_names, 'y_f');
M_.endo_names_tex = char(M_.endo_names_tex, 'y\_f');
M_.endo_names_long = char(M_.endo_names_long, 'y_f');
M_.endo_names = char(M_.endo_names, 'k_f');
M_.endo_names_tex = char(M_.endo_names_tex, 'k\_f');
M_.endo_names_long = char(M_.endo_names_long, 'k_f');
M_.endo_names = char(M_.endo_names, 'i_f');
M_.endo_names_tex = char(M_.endo_names_tex, 'i\_f');
M_.endo_names_long = char(M_.endo_names_long, 'i_f');
M_.endo_names = char(M_.endo_names, 'z_f');
M_.endo_names_tex = char(M_.endo_names_tex, 'z\_f');
M_.endo_names_long = char(M_.endo_names_long, 'z_f');
M_.endo_names = char(M_.endo_names, 'q_f');
M_.endo_names_tex = char(M_.endo_names_tex, 'q\_f');
M_.endo_names_long = char(M_.endo_names_long, 'q_f');
M_.endo_names = char(M_.endo_names, 'f_f');
M_.endo_names_tex = char(M_.endo_names_tex, 'f\_f');
M_.endo_names_long = char(M_.endo_names_long, 'f_f');
M_.endo_names = char(M_.endo_names, 'n_f');
M_.endo_names_tex = char(M_.endo_names_tex, 'n\_f');
M_.endo_names_long = char(M_.endo_names_long, 'n_f');
M_.endo_names = char(M_.endo_names, 'interest');
M_.endo_names_tex = char(M_.endo_names_tex, 'interest');
M_.endo_names_long = char(M_.endo_names_long, 'interest');
M_.endo_names = char(M_.endo_names, 'inflation');
M_.endo_names_tex = char(M_.endo_names_tex, 'inflation');
M_.endo_names_long = char(M_.endo_names_long, 'inflation');
M_.endo_names = char(M_.endo_names, 'inflationq');
M_.endo_names_tex = char(M_.endo_names_tex, 'inflationq');
M_.endo_names_long = char(M_.endo_names_long, 'inflationq');
M_.endo_names = char(M_.endo_names, 'output');
M_.endo_names_tex = char(M_.endo_names_tex, 'output');
M_.endo_names_long = char(M_.endo_names_long, 'output');
M_.endo_names = char(M_.endo_names, 'outputgap');
M_.endo_names_tex = char(M_.endo_names_tex, 'outputgap');
M_.endo_names_long = char(M_.endo_names_long, 'outputgap');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_80');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_80');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_80');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_84');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_84');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_84');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_88');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_88');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_88');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_115');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_115');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_115');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_119');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_119');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_119');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_123');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_123');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_123');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_150');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_150');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_150');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_154');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_154');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_154');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_158');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_158');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_158');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_15_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_15\_1');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_15_1');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_15_2');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_15\_2');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_15_2');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_37_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_37\_1');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_37_1');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_37_2');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_37\_2');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_37_2');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_37_3');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_37\_3');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_37_3');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_38_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_38\_1');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_38_1');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_38_2');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_38\_2');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_38_2');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_38_3');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_38\_3');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_38_3');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_34_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_34\_1');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_34_1');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_34_2');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_34\_2');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_34_2');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_34_3');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_34\_3');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_34_3');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_36_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_36\_1');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_36_1');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_36_2');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_36\_2');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_36_2');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_36_3');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_36\_3');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_36_3');
M_.param_names = 'cofintintb1';
M_.param_names_tex = 'cofintintb1';
M_.param_names_long = 'cofintintb1';
M_.param_names = char(M_.param_names, 'cofintintb2');
M_.param_names_tex = char(M_.param_names_tex, 'cofintintb2');
M_.param_names_long = char(M_.param_names_long, 'cofintintb2');
M_.param_names = char(M_.param_names, 'cofintintb3');
M_.param_names_tex = char(M_.param_names_tex, 'cofintintb3');
M_.param_names_long = char(M_.param_names_long, 'cofintintb3');
M_.param_names = char(M_.param_names, 'cofintintb4');
M_.param_names_tex = char(M_.param_names_tex, 'cofintintb4');
M_.param_names_long = char(M_.param_names_long, 'cofintintb4');
M_.param_names = char(M_.param_names, 'cofintinf0');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinf0');
M_.param_names_long = char(M_.param_names_long, 'cofintinf0');
M_.param_names = char(M_.param_names, 'cofintinfb1');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinfb1');
M_.param_names_long = char(M_.param_names_long, 'cofintinfb1');
M_.param_names = char(M_.param_names, 'cofintinfb2');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinfb2');
M_.param_names_long = char(M_.param_names_long, 'cofintinfb2');
M_.param_names = char(M_.param_names, 'cofintinfb3');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinfb3');
M_.param_names_long = char(M_.param_names_long, 'cofintinfb3');
M_.param_names = char(M_.param_names, 'cofintinfb4');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinfb4');
M_.param_names_long = char(M_.param_names_long, 'cofintinfb4');
M_.param_names = char(M_.param_names, 'cofintinff1');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinff1');
M_.param_names_long = char(M_.param_names_long, 'cofintinff1');
M_.param_names = char(M_.param_names, 'cofintinff2');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinff2');
M_.param_names_long = char(M_.param_names_long, 'cofintinff2');
M_.param_names = char(M_.param_names, 'cofintinff3');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinff3');
M_.param_names_long = char(M_.param_names_long, 'cofintinff3');
M_.param_names = char(M_.param_names, 'cofintinff4');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinff4');
M_.param_names_long = char(M_.param_names_long, 'cofintinff4');
M_.param_names = char(M_.param_names, 'cofintout');
M_.param_names_tex = char(M_.param_names_tex, 'cofintout');
M_.param_names_long = char(M_.param_names_long, 'cofintout');
M_.param_names = char(M_.param_names, 'cofintoutb1');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutb1');
M_.param_names_long = char(M_.param_names_long, 'cofintoutb1');
M_.param_names = char(M_.param_names, 'cofintoutb2');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutb2');
M_.param_names_long = char(M_.param_names_long, 'cofintoutb2');
M_.param_names = char(M_.param_names, 'cofintoutb3');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutb3');
M_.param_names_long = char(M_.param_names_long, 'cofintoutb3');
M_.param_names = char(M_.param_names, 'cofintoutb4');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutb4');
M_.param_names_long = char(M_.param_names_long, 'cofintoutb4');
M_.param_names = char(M_.param_names, 'cofintoutf1');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutf1');
M_.param_names_long = char(M_.param_names_long, 'cofintoutf1');
M_.param_names = char(M_.param_names, 'cofintoutf2');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutf2');
M_.param_names_long = char(M_.param_names_long, 'cofintoutf2');
M_.param_names = char(M_.param_names, 'cofintoutf3');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutf3');
M_.param_names_long = char(M_.param_names_long, 'cofintoutf3');
M_.param_names = char(M_.param_names, 'cofintoutf4');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutf4');
M_.param_names_long = char(M_.param_names_long, 'cofintoutf4');
M_.param_names = char(M_.param_names, 'cofintoutp');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutp');
M_.param_names_long = char(M_.param_names_long, 'cofintoutp');
M_.param_names = char(M_.param_names, 'cofintoutpb1');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpb1');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpb1');
M_.param_names = char(M_.param_names, 'cofintoutpb2');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpb2');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpb2');
M_.param_names = char(M_.param_names, 'cofintoutpb3');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpb3');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpb3');
M_.param_names = char(M_.param_names, 'cofintoutpb4');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpb4');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpb4');
M_.param_names = char(M_.param_names, 'cofintoutpf1');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpf1');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpf1');
M_.param_names = char(M_.param_names, 'cofintoutpf2');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpf2');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpf2');
M_.param_names = char(M_.param_names, 'cofintoutpf3');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpf3');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpf3');
M_.param_names = char(M_.param_names, 'cofintoutpf4');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpf4');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpf4');
M_.param_names = char(M_.param_names, 'std_r_');
M_.param_names_tex = char(M_.param_names_tex, 'std\_r\_');
M_.param_names_long = char(M_.param_names_long, 'std_r_');
M_.param_names = char(M_.param_names, 'std_r_quart');
M_.param_names_tex = char(M_.param_names_tex, 'std\_r\_quart');
M_.param_names_long = char(M_.param_names_long, 'std_r_quart');
M_.param_names = char(M_.param_names, 'coffispol');
M_.param_names_tex = char(M_.param_names_tex, 'coffispol');
M_.param_names_long = char(M_.param_names_long, 'coffispol');
M_.param_names = char(M_.param_names, 'gamma');
M_.param_names_tex = char(M_.param_names_tex, 'gamma');
M_.param_names_long = char(M_.param_names_long, 'gamma');
M_.param_names = char(M_.param_names, 'alpha');
M_.param_names_tex = char(M_.param_names_tex, 'alpha');
M_.param_names_long = char(M_.param_names_long, 'alpha');
M_.param_names = char(M_.param_names, 'rho_pi');
M_.param_names_tex = char(M_.param_names_tex, 'rho\_pi');
M_.param_names_long = char(M_.param_names_long, 'rho_pi');
M_.param_names = char(M_.param_names, 'rho_y');
M_.param_names_tex = char(M_.param_names_tex, 'rho\_y');
M_.param_names_long = char(M_.param_names_long, 'rho_y');
M_.param_names = char(M_.param_names, 'rho_mu');
M_.param_names_tex = char(M_.param_names_tex, 'rho\_mu');
M_.param_names_long = char(M_.param_names_long, 'rho_mu');
M_.param_names = char(M_.param_names, 'delta');
M_.param_names_tex = char(M_.param_names_tex, 'delta');
M_.param_names_long = char(M_.param_names_long, 'delta');
M_.param_names = char(M_.param_names, 'chi');
M_.param_names_tex = char(M_.param_names_tex, 'chi');
M_.param_names_long = char(M_.param_names_long, 'chi');
M_.param_names = char(M_.param_names, 'beta');
M_.param_names_tex = char(M_.param_names_tex, 'beta');
M_.param_names_long = char(M_.param_names_long, 'beta');
M_.param_names = char(M_.param_names, 'phi');
M_.param_names_tex = char(M_.param_names_tex, 'phi');
M_.param_names_long = char(M_.param_names_long, 'phi');
M_.param_names = char(M_.param_names, 'psi');
M_.param_names_tex = char(M_.param_names_tex, 'psi');
M_.param_names_long = char(M_.param_names_long, 'psi');
M_.param_names = char(M_.param_names, 'nu');
M_.param_names_tex = char(M_.param_names_tex, 'nu');
M_.param_names_long = char(M_.param_names_long, 'nu');
M_.param_names = char(M_.param_names, 'rho_a');
M_.param_names_tex = char(M_.param_names_tex, 'rho\_a');
M_.param_names_long = char(M_.param_names_long, 'rho_a');
M_.param_names = char(M_.param_names, 'rho_e');
M_.param_names_tex = char(M_.param_names_tex, 'rho\_e');
M_.param_names_long = char(M_.param_names_long, 'rho_e');
M_.param_names = char(M_.param_names, 'rho_x');
M_.param_names_tex = char(M_.param_names_tex, 'rho\_x');
M_.param_names_long = char(M_.param_names_long, 'rho_x');
M_.param_names = char(M_.param_names, 'rho_b');
M_.param_names_tex = char(M_.param_names_tex, 'rho\_b');
M_.param_names_long = char(M_.param_names_long, 'rho_b');
M_.param_names = char(M_.param_names, 'c1');
M_.param_names_tex = char(M_.param_names_tex, 'c1');
M_.param_names_long = char(M_.param_names_long, 'c1');
M_.param_names = char(M_.param_names, 'm1');
M_.param_names_tex = char(M_.param_names_tex, 'm1');
M_.param_names_long = char(M_.param_names_long, 'm1');
M_.param_names = char(M_.param_names, 'r1');
M_.param_names_tex = char(M_.param_names_tex, 'r1');
M_.param_names_long = char(M_.param_names_long, 'r1');
M_.param_names = char(M_.param_names, 'h1');
M_.param_names_tex = char(M_.param_names_tex, 'h1');
M_.param_names_long = char(M_.param_names_long, 'h1');
M_.param_names = char(M_.param_names, 'cy1');
M_.param_names_tex = char(M_.param_names_tex, 'cy1');
M_.param_names_long = char(M_.param_names_long, 'cy1');
M_.param_names = char(M_.param_names, 'iy1');
M_.param_names_tex = char(M_.param_names_tex, 'iy1');
M_.param_names_long = char(M_.param_names_long, 'iy1');
M_.param_names = char(M_.param_names, 'f1');
M_.param_names_tex = char(M_.param_names_tex, 'f1');
M_.param_names_long = char(M_.param_names_long, 'f1');
M_.param_names = char(M_.param_names, 'z1');
M_.param_names_tex = char(M_.param_names_tex, 'z1');
M_.param_names_long = char(M_.param_names_long, 'z1');
M_.param_names = char(M_.param_names, 'kn1');
M_.param_names_tex = char(M_.param_names_tex, 'kn1');
M_.param_names_long = char(M_.param_names_long, 'kn1');
M_.param_names = char(M_.param_names, 'pi_ss');
M_.param_names_tex = char(M_.param_names_tex, 'pi\_ss');
M_.param_names_long = char(M_.param_names_long, 'pi_ss');
M_.param_names = char(M_.param_names, 'r_ss');
M_.param_names_tex = char(M_.param_names_tex, 'r\_ss');
M_.param_names_long = char(M_.param_names_long, 'r_ss');
M_.param_names = char(M_.param_names, 'xi_ss');
M_.param_names_tex = char(M_.param_names_tex, 'xi\_ss');
M_.param_names_long = char(M_.param_names_long, 'xi_ss');
M_.param_names = char(M_.param_names, 'f_ss');
M_.param_names_tex = char(M_.param_names_tex, 'f\_ss');
M_.param_names_long = char(M_.param_names_long, 'f_ss');
M_.param_names = char(M_.param_names, 'z_ss');
M_.param_names_tex = char(M_.param_names_tex, 'z\_ss');
M_.param_names_long = char(M_.param_names_long, 'z_ss');
M_.param_names = char(M_.param_names, 'lambda_c');
M_.param_names_tex = char(M_.param_names_tex, 'lambda\_c');
M_.param_names_long = char(M_.param_names_long, 'lambda_c');
M_.param_names = char(M_.param_names, 'lambda_m');
M_.param_names_tex = char(M_.param_names_tex, 'lambda\_m');
M_.param_names_long = char(M_.param_names_long, 'lambda_m');
M_.param_names = char(M_.param_names, 'k__y');
M_.param_names_tex = char(M_.param_names_tex, 'k\_\_y');
M_.param_names_long = char(M_.param_names_long, 'k__y');
M_.param_names = char(M_.param_names, 'c__y');
M_.param_names_tex = char(M_.param_names_tex, 'c\_\_y');
M_.param_names_long = char(M_.param_names_long, 'c__y');
M_.param_names = char(M_.param_names, 'w_h_y');
M_.param_names_tex = char(M_.param_names_tex, 'w\_h\_y');
M_.param_names_long = char(M_.param_names_long, 'w_h_y');
M_.param_names = char(M_.param_names, 'h_ss');
M_.param_names_tex = char(M_.param_names_tex, 'h\_ss');
M_.param_names_long = char(M_.param_names_long, 'h_ss');
M_.param_names = char(M_.param_names, 'i__y');
M_.param_names_tex = char(M_.param_names_tex, 'i\_\_y');
M_.param_names_long = char(M_.param_names_long, 'i__y');
M_.param_names = char(M_.param_names, 'b_ss');
M_.param_names_tex = char(M_.param_names_tex, 'b\_ss');
M_.param_names_long = char(M_.param_names_long, 'b_ss');
M_.param_names = char(M_.param_names, 'k__n');
M_.param_names_tex = char(M_.param_names_tex, 'k\_\_n');
M_.param_names_long = char(M_.param_names_long, 'k__n');
M_.param_names = char(M_.param_names, 'S');
M_.param_names_tex = char(M_.param_names_tex, 'S');
M_.param_names_long = char(M_.param_names_long, 'S');
M_.exo_det_nbr = 0;
M_.exo_nbr = 5;
M_.endo_nbr = 62;
M_.param_nbr = 73;
M_.orig_endo_nbr = 39;
M_.aux_vars(1).endo_index = 40;
M_.aux_vars(1).type = 0;
M_.aux_vars(2).endo_index = 41;
M_.aux_vars(2).type = 0;
M_.aux_vars(3).endo_index = 42;
M_.aux_vars(3).type = 0;
M_.aux_vars(4).endo_index = 43;
M_.aux_vars(4).type = 0;
M_.aux_vars(5).endo_index = 44;
M_.aux_vars(5).type = 0;
M_.aux_vars(6).endo_index = 45;
M_.aux_vars(6).type = 0;
M_.aux_vars(7).endo_index = 46;
M_.aux_vars(7).type = 0;
M_.aux_vars(8).endo_index = 47;
M_.aux_vars(8).type = 0;
M_.aux_vars(9).endo_index = 48;
M_.aux_vars(9).type = 0;
M_.aux_vars(10).endo_index = 49;
M_.aux_vars(10).type = 1;
M_.aux_vars(10).orig_index = 16;
M_.aux_vars(10).orig_lead_lag = -1;
M_.aux_vars(11).endo_index = 50;
M_.aux_vars(11).type = 1;
M_.aux_vars(11).orig_index = 16;
M_.aux_vars(11).orig_lead_lag = -2;
M_.aux_vars(12).endo_index = 51;
M_.aux_vars(12).type = 1;
M_.aux_vars(12).orig_index = 38;
M_.aux_vars(12).orig_lead_lag = -1;
M_.aux_vars(13).endo_index = 52;
M_.aux_vars(13).type = 1;
M_.aux_vars(13).orig_index = 38;
M_.aux_vars(13).orig_lead_lag = -2;
M_.aux_vars(14).endo_index = 53;
M_.aux_vars(14).type = 1;
M_.aux_vars(14).orig_index = 38;
M_.aux_vars(14).orig_lead_lag = -3;
M_.aux_vars(15).endo_index = 54;
M_.aux_vars(15).type = 1;
M_.aux_vars(15).orig_index = 39;
M_.aux_vars(15).orig_lead_lag = -1;
M_.aux_vars(16).endo_index = 55;
M_.aux_vars(16).type = 1;
M_.aux_vars(16).orig_index = 39;
M_.aux_vars(16).orig_lead_lag = -2;
M_.aux_vars(17).endo_index = 56;
M_.aux_vars(17).type = 1;
M_.aux_vars(17).orig_index = 39;
M_.aux_vars(17).orig_lead_lag = -3;
M_.aux_vars(18).endo_index = 57;
M_.aux_vars(18).type = 1;
M_.aux_vars(18).orig_index = 35;
M_.aux_vars(18).orig_lead_lag = -1;
M_.aux_vars(19).endo_index = 58;
M_.aux_vars(19).type = 1;
M_.aux_vars(19).orig_index = 35;
M_.aux_vars(19).orig_lead_lag = -2;
M_.aux_vars(20).endo_index = 59;
M_.aux_vars(20).type = 1;
M_.aux_vars(20).orig_index = 35;
M_.aux_vars(20).orig_lead_lag = -3;
M_.aux_vars(21).endo_index = 60;
M_.aux_vars(21).type = 1;
M_.aux_vars(21).orig_index = 37;
M_.aux_vars(21).orig_lead_lag = -1;
M_.aux_vars(22).endo_index = 61;
M_.aux_vars(22).type = 1;
M_.aux_vars(22).orig_index = 37;
M_.aux_vars(22).orig_lead_lag = -2;
M_.aux_vars(23).endo_index = 62;
M_.aux_vars(23).type = 1;
M_.aux_vars(23).orig_index = 37;
M_.aux_vars(23).orig_lead_lag = -3;
M_.Sigma_e = zeros(5, 5);
M_.Correlation_matrix = eye(5, 5);
M_.H = 0;
M_.Correlation_matrix_ME = 1;
M_.sigma_e_is_diagonal = 1;
options_.linear = 1;
options_.block=0;
options_.bytecode=0;
options_.use_dll=0;
erase_compiled_function('US_CD08_static');
erase_compiled_function('US_CD08_dynamic');
M_.lead_lag_incidence = [
 0 33 95;
 0 34 0;
 1 35 0;
 2 36 0;
 3 37 0;
 4 38 0;
 0 39 0;
 0 40 0;
 0 41 0;
 5 42 0;
 6 43 0;
 0 44 0;
 0 45 0;
 0 46 0;
 0 47 0;
 7 48 96;
 8 49 0;
 9 50 0;
 0 51 97;
 10 52 0;
 0 53 0;
 0 54 98;
 0 55 0;
 0 56 0;
 11 57 0;
 0 58 0;
 0 59 0;
 0 60 0;
 12 61 0;
 0 62 0;
 0 63 0;
 13 64 0;
 0 65 99;
 14 66 0;
 15 67 0;
 0 68 0;
 16 69 100;
 17 70 101;
 18 71 102;
 0 72 103;
 0 73 104;
 0 74 105;
 0 75 106;
 0 76 107;
 0 77 108;
 0 78 109;
 0 79 110;
 0 80 111;
 19 81 0;
 20 82 0;
 21 83 0;
 22 84 0;
 23 85 0;
 24 86 0;
 25 87 0;
 26 88 0;
 27 89 0;
 28 90 0;
 29 91 0;
 30 92 0;
 31 93 0;
 32 94 0;]';
M_.nstatic = 17;
M_.nfwrd   = 13;
M_.npred   = 28;
M_.nboth   = 4;
M_.nsfwrd   = 17;
M_.nspred   = 32;
M_.ndynamic   = 45;
M_.equations_tags = {
};
M_.static_and_dynamic_models_differ = 0;
M_.exo_names_orig_ord = [1:5];
M_.maximum_lag = 1;
M_.maximum_lead = 1;
M_.maximum_endo_lag = 1;
M_.maximum_endo_lead = 1;
oo_.steady_state = zeros(62, 1);
M_.maximum_exo_lag = 0;
M_.maximum_exo_lead = 0;
oo_.exo_steady_state = zeros(5, 1);
M_.params = NaN(73, 1);
M_.NNZDerivatives = zeros(3, 1);
M_.NNZDerivatives(1) = 225;
M_.NNZDerivatives(2) = 0;
M_.NNZDerivatives(3) = -1;
M_.params( 35 ) = 0.0598;
gamma = M_.params( 35 );
M_.params( 36 ) = 0.3384;
alpha = M_.params( 36 );
M_.params( 37 ) = 1.4059;
rho_pi = M_.params( 37 );
M_.params( 38 ) = 0.2947;
rho_y = M_.params( 38 );
M_.params( 39 ) = 0.6532;
rho_mu = M_.params( 39 );
M_.params( 40 ) = 0.025;
delta = M_.params( 40 );
M_.params( 71 ) = 0.062;
b_ss = M_.params( 71 );
M_.params( 41 ) = 0.5882;
chi = M_.params( 41 );
M_.params( 42 ) = 0.9928;
beta = M_.params( 42 );
eta=1.315;
M_.params( 43 ) = 0.7418;
phi = M_.params( 43 );
M_.params( 44 ) = 0.042;
psi = M_.params( 44 );
M_.params( 45 ) = 0.9728;
nu = M_.params( 45 );
M_.params( 46 ) = 0.7625;
rho_a = M_.params( 46 );
M_.params( 47 ) = 0.6156;
rho_e = M_.params( 47 );
M_.params( 48 ) = 0.6562;
rho_x = M_.params( 48 );
M_.params( 49 ) = 0.7206;
rho_b = M_.params( 49 );
M_.params( 59 ) = 1.0079;
pi_ss = M_.params( 59 );
M_.params( 61 ) = 0.8333333333333334;
xi_ss = M_.params( 61 );
M_.params( 72 ) = 2;
k__n = M_.params( 72 );
M_.params( 73 ) = 1.0075;
S = M_.params( 73 );
M_.params( 60 ) = M_.params(59)/M_.params(42);
r_ss = M_.params( 60 );
M_.params( 62 ) = M_.params(73)*M_.params(60)/M_.params(59);
f_ss = M_.params( 62 );
M_.params( 63 ) = M_.params(62)+M_.params(40)-1;
z_ss = M_.params( 63 );
M_.params( 64 ) = (1+M_.params(71)*(M_.params(59)/(M_.params(59)-M_.params(42)))^(M_.params(35)-1))^(-1);
lambda_c = M_.params( 64 );
M_.params( 65 ) = M_.params(71)*M_.params(64)*(M_.params(59)/(M_.params(59)-M_.params(42)))^M_.params(35);
lambda_m = M_.params( 65 );
M_.params( 66 ) = M_.params(36)*M_.params(61)/M_.params(63);
k__y = M_.params( 66 );
M_.params( 67 ) = 1-M_.params(40)*M_.params(66);
c__y = M_.params( 67 );
M_.params( 68 ) = M_.params(61)*M_.params(64)*(1-M_.params(36))/M_.params(67);
w_h_y = M_.params( 68 );
M_.params( 69 ) = M_.params(68)/(M_.params(68)+eta);
h_ss = M_.params( 69 );
M_.params( 70 ) = 1-M_.params(67);
i__y = M_.params( 70 );
thispath = cd;                                                           
cd('..');                                                                
load policy_param.mat;                                                   
for i=1:33                                                               
deep_parameter_name = M_.param_names(i,:);                           
eval(['M_.params(i)  = ' deep_parameter_name ' ;'])                  
end                                                                      
cd(thispath);       
M_.params( 32 ) = 100;
std_r_ = M_.params( 32 );
M_.params( 34 ) = 1;
coffispol = M_.params( 34 );
%
% SHOCKS instructions
%
make_ex_;
M_.exo_det_length = 0;
M_.Sigma_e(1, 1) = (0.0331)^2;
M_.Sigma_e(2, 2) = (0.0096)^2;
M_.Sigma_e(3, 3) = (0.0073)^2;
M_.Sigma_e(4, 4) = (0.0103)^2;
save('US_CD08_results.mat', 'oo_', 'M_', 'options_');
if exist('estim_params_', 'var') == 1
  save('US_CD08_results.mat', 'estim_params_', '-append');
end
if exist('bayestopt_', 'var') == 1
  save('US_CD08_results.mat', 'bayestopt_', '-append');
end
if exist('dataset_', 'var') == 1
  save('US_CD08_results.mat', 'dataset_', '-append');
end
if exist('estimation_info', 'var') == 1
  save('US_CD08_results.mat', 'estimation_info', '-append');
end


disp(['Total computing time : ' dynsec2hms(toc) ]);
if ~isempty(lastwarn)
  disp('Note: warning(s) encountered in MATLAB/Octave code')
end
diary off
