%
% Status : main Dynare file
%
% Warning : this file is generated automatically by Dynare
%           from model file (.mod)

tic0 = tic;
% Save empty dates and dseries objects in memory.
dates('initialize');
dseries('initialize');
% Define global variables.
global M_ options_ oo_ estim_params_ bayestopt_ dataset_ dataset_info estimation_info ys0_ ex0_
options_ = [];
M_.fname = 'NK_RA16';
M_.dynare_version = '4.5.4';
oo_.dynare_version = '4.5.4';
options_.dynare_version = '4.5.4';
%
% Some global variables initialization
%
global_initialization;
diary off;
diary('NK_RA16.log');
M_.exo_names = 'e_a';
M_.exo_names_tex = 'e\_a';
M_.exo_names_long = 'e_a';
M_.exo_names = char(M_.exo_names, 'interest_');
M_.exo_names_tex = char(M_.exo_names_tex, 'interest\_');
M_.exo_names_long = char(M_.exo_names_long, 'interest_');
M_.exo_names = char(M_.exo_names, 'fiscal_');
M_.exo_names_tex = char(M_.exo_names_tex, 'fiscal\_');
M_.exo_names_long = char(M_.exo_names_long, 'fiscal_');
M_.endo_names = 'interest';
M_.endo_names_tex = 'interest';
M_.endo_names_long = 'interest';
M_.endo_names = char(M_.endo_names, 'inflation');
M_.endo_names_tex = char(M_.endo_names_tex, 'inflation');
M_.endo_names_long = char(M_.endo_names_long, 'inflation');
M_.endo_names = char(M_.endo_names, 'inflationq');
M_.endo_names_tex = char(M_.endo_names_tex, 'inflationq');
M_.endo_names_long = char(M_.endo_names_long, 'inflationq');
M_.endo_names = char(M_.endo_names, 'outputgap');
M_.endo_names_tex = char(M_.endo_names_tex, 'outputgap');
M_.endo_names_long = char(M_.endo_names_long, 'outputgap');
M_.endo_names = char(M_.endo_names, 'output');
M_.endo_names_tex = char(M_.endo_names_tex, 'output');
M_.endo_names_long = char(M_.endo_names_long, 'output');
M_.endo_names = char(M_.endo_names, 'fispol');
M_.endo_names_tex = char(M_.endo_names_tex, 'fispol');
M_.endo_names_long = char(M_.endo_names_long, 'fispol');
M_.endo_names = char(M_.endo_names, 'Y');
M_.endo_names_tex = char(M_.endo_names_tex, 'Y');
M_.endo_names_long = char(M_.endo_names_long, 'Y');
M_.endo_names = char(M_.endo_names, 'GDP');
M_.endo_names_tex = char(M_.endo_names_tex, 'GDP');
M_.endo_names_long = char(M_.endo_names_long, 'GDP');
M_.endo_names = char(M_.endo_names, 'I');
M_.endo_names_tex = char(M_.endo_names_tex, 'I');
M_.endo_names_long = char(M_.endo_names_long, 'I');
M_.endo_names = char(M_.endo_names, 'K');
M_.endo_names_tex = char(M_.endo_names_tex, 'K');
M_.endo_names_long = char(M_.endo_names_long, 'K');
M_.endo_names = char(M_.endo_names, 'l');
M_.endo_names_tex = char(M_.endo_names_tex, 'l');
M_.endo_names_long = char(M_.endo_names_long, 'l');
M_.endo_names = char(M_.endo_names, 'U');
M_.endo_names_tex = char(M_.endo_names_tex, 'U');
M_.endo_names_long = char(M_.endo_names_long, 'U');
M_.endo_names = char(M_.endo_names, 'Cp');
M_.endo_names_tex = char(M_.endo_names_tex, 'Cp');
M_.endo_names_long = char(M_.endo_names_long, 'Cp');
M_.endo_names = char(M_.endo_names, 'C');
M_.endo_names_tex = char(M_.endo_names_tex, 'C');
M_.endo_names_long = char(M_.endo_names_long, 'C');
M_.endo_names = char(M_.endo_names, 'Ce');
M_.endo_names_tex = char(M_.endo_names_tex, 'Ce');
M_.endo_names_long = char(M_.endo_names_long, 'Ce');
M_.endo_names = char(M_.endo_names, 'Cb');
M_.endo_names_tex = char(M_.endo_names_tex, 'Cb');
M_.endo_names_long = char(M_.endo_names_long, 'Cb');
M_.endo_names = char(M_.endo_names, 'varrho');
M_.endo_names_tex = char(M_.endo_names_tex, 'varrho');
M_.endo_names_long = char(M_.endo_names_long, 'varrho');
M_.endo_names = char(M_.endo_names, 'R');
M_.endo_names_tex = char(M_.endo_names_tex, 'R');
M_.endo_names_long = char(M_.endo_names_long, 'R');
M_.endo_names = char(M_.endo_names, 'Rk');
M_.endo_names_tex = char(M_.endo_names_tex, 'Rk');
M_.endo_names_long = char(M_.endo_names_long, 'Rk');
M_.endo_names = char(M_.endo_names, 'rk');
M_.endo_names_tex = char(M_.endo_names_tex, 'rk');
M_.endo_names_long = char(M_.endo_names_long, 'rk');
M_.endo_names = char(M_.endo_names, 'Rb');
M_.endo_names_tex = char(M_.endo_names_tex, 'Rb');
M_.endo_names_long = char(M_.endo_names_long, 'Rb');
M_.endo_names = char(M_.endo_names, 'Rl');
M_.endo_names_tex = char(M_.endo_names_tex, 'Rl');
M_.endo_names_long = char(M_.endo_names_long, 'Rl');
M_.endo_names = char(M_.endo_names, 'w');
M_.endo_names_tex = char(M_.endo_names_tex, 'w');
M_.endo_names_long = char(M_.endo_names_long, 'w');
M_.endo_names = char(M_.endo_names, 'a');
M_.endo_names_tex = char(M_.endo_names_tex, 'a');
M_.endo_names_long = char(M_.endo_names_long, 'a');
M_.endo_names = char(M_.endo_names, 'Q');
M_.endo_names_tex = char(M_.endo_names_tex, 'Q');
M_.endo_names_long = char(M_.endo_names_long, 'Q');
M_.endo_names = char(M_.endo_names, 'Pi');
M_.endo_names_tex = char(M_.endo_names_tex, 'Pi');
M_.endo_names_long = char(M_.endo_names_long, 'Pi');
M_.endo_names = char(M_.endo_names, 'mc');
M_.endo_names_tex = char(M_.endo_names_tex, 'mc');
M_.endo_names_long = char(M_.endo_names_long, 'mc');
M_.endo_names = char(M_.endo_names, 'N');
M_.endo_names_tex = char(M_.endo_names_tex, 'N');
M_.endo_names_long = char(M_.endo_names_long, 'N');
M_.endo_names = char(M_.endo_names, 'V');
M_.endo_names_tex = char(M_.endo_names_tex, 'V');
M_.endo_names_long = char(M_.endo_names_long, 'V');
M_.endo_names = char(M_.endo_names, 'phi_e');
M_.endo_names_tex = char(M_.endo_names_tex, 'phi\_e');
M_.endo_names_long = char(M_.endo_names_long, 'phi_e');
M_.endo_names = char(M_.endo_names, 'omega_bar_prime');
M_.endo_names_tex = char(M_.endo_names_tex, 'omega\_bar\_prime');
M_.endo_names_long = char(M_.endo_names_long, 'omega_bar_prime');
M_.endo_names = char(M_.endo_names, 'L');
M_.endo_names_tex = char(M_.endo_names_tex, 'L');
M_.endo_names_long = char(M_.endo_names_long, 'L');
M_.endo_names = char(M_.endo_names, 'Lr');
M_.endo_names_tex = char(M_.endo_names_tex, 'Lr');
M_.endo_names_long = char(M_.endo_names_long, 'Lr');
M_.endo_names = char(M_.endo_names, 'Le');
M_.endo_names_tex = char(M_.endo_names_tex, 'Le');
M_.endo_names_long = char(M_.endo_names_long, 'Le');
M_.endo_names = char(M_.endo_names, 'g');
M_.endo_names_tex = char(M_.endo_names_tex, 'g');
M_.endo_names_long = char(M_.endo_names_long, 'g');
M_.endo_names = char(M_.endo_names, 'Nb');
M_.endo_names_tex = char(M_.endo_names_tex, 'Nb');
M_.endo_names_long = char(M_.endo_names_long, 'Nb');
M_.endo_names = char(M_.endo_names, 'phi_b');
M_.endo_names_tex = char(M_.endo_names_tex, 'phi\_b');
M_.endo_names_long = char(M_.endo_names_long, 'phi_b');
M_.endo_names = char(M_.endo_names, 'z');
M_.endo_names_tex = char(M_.endo_names_tex, 'z');
M_.endo_names_long = char(M_.endo_names_long, 'z');
M_.endo_names = char(M_.endo_names, 'Lambda');
M_.endo_names_tex = char(M_.endo_names_tex, 'Lambda');
M_.endo_names_long = char(M_.endo_names_long, 'Lambda');
M_.endo_names = char(M_.endo_names, 'spread_RlR');
M_.endo_names_tex = char(M_.endo_names_tex, 'spread\_RlR');
M_.endo_names_long = char(M_.endo_names_long, 'spread_RlR');
M_.endo_names = char(M_.endo_names, 'spread_RkR');
M_.endo_names_tex = char(M_.endo_names_tex, 'spread\_RkR');
M_.endo_names_long = char(M_.endo_names_long, 'spread_RkR');
M_.endo_names = char(M_.endo_names, 'spread_RbR');
M_.endo_names_tex = char(M_.endo_names_tex, 'spread\_RbR');
M_.endo_names_long = char(M_.endo_names_long, 'spread_RbR');
M_.endo_names = char(M_.endo_names, 'spread_RkRb');
M_.endo_names_tex = char(M_.endo_names_tex, 'spread\_RkRb');
M_.endo_names_long = char(M_.endo_names_long, 'spread_RkRb');
M_.endo_names = char(M_.endo_names, 'R4');
M_.endo_names_tex = char(M_.endo_names_tex, 'R4');
M_.endo_names_long = char(M_.endo_names_long, 'R4');
M_.endo_names = char(M_.endo_names, 'Pi4');
M_.endo_names_tex = char(M_.endo_names_tex, 'Pi4');
M_.endo_names_long = char(M_.endo_names_long, 'Pi4');
M_.endo_names = char(M_.endo_names, 'e_g');
M_.endo_names_tex = char(M_.endo_names_tex, 'e\_g');
M_.endo_names_long = char(M_.endo_names_long, 'e_g');
M_.endo_names = char(M_.endo_names, 'Y_fe');
M_.endo_names_tex = char(M_.endo_names_tex, 'Y\_fe');
M_.endo_names_long = char(M_.endo_names_long, 'Y_fe');
M_.endo_names = char(M_.endo_names, 'GDP_fe');
M_.endo_names_tex = char(M_.endo_names_tex, 'GDP\_fe');
M_.endo_names_long = char(M_.endo_names_long, 'GDP_fe');
M_.endo_names = char(M_.endo_names, 'I_fe');
M_.endo_names_tex = char(M_.endo_names_tex, 'I\_fe');
M_.endo_names_long = char(M_.endo_names_long, 'I_fe');
M_.endo_names = char(M_.endo_names, 'K_fe');
M_.endo_names_tex = char(M_.endo_names_tex, 'K\_fe');
M_.endo_names_long = char(M_.endo_names_long, 'K_fe');
M_.endo_names = char(M_.endo_names, 'l_fe');
M_.endo_names_tex = char(M_.endo_names_tex, 'l\_fe');
M_.endo_names_long = char(M_.endo_names_long, 'l_fe');
M_.endo_names = char(M_.endo_names, 'U_fe');
M_.endo_names_tex = char(M_.endo_names_tex, 'U\_fe');
M_.endo_names_long = char(M_.endo_names_long, 'U_fe');
M_.endo_names = char(M_.endo_names, 'Cp_fe');
M_.endo_names_tex = char(M_.endo_names_tex, 'Cp\_fe');
M_.endo_names_long = char(M_.endo_names_long, 'Cp_fe');
M_.endo_names = char(M_.endo_names, 'C_fe');
M_.endo_names_tex = char(M_.endo_names_tex, 'C\_fe');
M_.endo_names_long = char(M_.endo_names_long, 'C_fe');
M_.endo_names = char(M_.endo_names, 'Ce_fe');
M_.endo_names_tex = char(M_.endo_names_tex, 'Ce\_fe');
M_.endo_names_long = char(M_.endo_names_long, 'Ce_fe');
M_.endo_names = char(M_.endo_names, 'Cb_fe');
M_.endo_names_tex = char(M_.endo_names_tex, 'Cb\_fe');
M_.endo_names_long = char(M_.endo_names_long, 'Cb_fe');
M_.endo_names = char(M_.endo_names, 'varrho_fe');
M_.endo_names_tex = char(M_.endo_names_tex, 'varrho\_fe');
M_.endo_names_long = char(M_.endo_names_long, 'varrho_fe');
M_.endo_names = char(M_.endo_names, 'R_fe');
M_.endo_names_tex = char(M_.endo_names_tex, 'R\_fe');
M_.endo_names_long = char(M_.endo_names_long, 'R_fe');
M_.endo_names = char(M_.endo_names, 'Rk_fe');
M_.endo_names_tex = char(M_.endo_names_tex, 'Rk\_fe');
M_.endo_names_long = char(M_.endo_names_long, 'Rk_fe');
M_.endo_names = char(M_.endo_names, 'rk_fe');
M_.endo_names_tex = char(M_.endo_names_tex, 'rk\_fe');
M_.endo_names_long = char(M_.endo_names_long, 'rk_fe');
M_.endo_names = char(M_.endo_names, 'Rb_fe');
M_.endo_names_tex = char(M_.endo_names_tex, 'Rb\_fe');
M_.endo_names_long = char(M_.endo_names_long, 'Rb_fe');
M_.endo_names = char(M_.endo_names, 'Rl_fe');
M_.endo_names_tex = char(M_.endo_names_tex, 'Rl\_fe');
M_.endo_names_long = char(M_.endo_names_long, 'Rl_fe');
M_.endo_names = char(M_.endo_names, 'w_fe');
M_.endo_names_tex = char(M_.endo_names_tex, 'w\_fe');
M_.endo_names_long = char(M_.endo_names_long, 'w_fe');
M_.endo_names = char(M_.endo_names, 'Q_fe');
M_.endo_names_tex = char(M_.endo_names_tex, 'Q\_fe');
M_.endo_names_long = char(M_.endo_names_long, 'Q_fe');
M_.endo_names = char(M_.endo_names, 'Pi_fe');
M_.endo_names_tex = char(M_.endo_names_tex, 'Pi\_fe');
M_.endo_names_long = char(M_.endo_names_long, 'Pi_fe');
M_.endo_names = char(M_.endo_names, 'mc_fe');
M_.endo_names_tex = char(M_.endo_names_tex, 'mc\_fe');
M_.endo_names_long = char(M_.endo_names_long, 'mc_fe');
M_.endo_names = char(M_.endo_names, 'N_fe');
M_.endo_names_tex = char(M_.endo_names_tex, 'N\_fe');
M_.endo_names_long = char(M_.endo_names_long, 'N_fe');
M_.endo_names = char(M_.endo_names, 'V_fe');
M_.endo_names_tex = char(M_.endo_names_tex, 'V\_fe');
M_.endo_names_long = char(M_.endo_names_long, 'V_fe');
M_.endo_names = char(M_.endo_names, 'phi_e_fe');
M_.endo_names_tex = char(M_.endo_names_tex, 'phi\_e\_fe');
M_.endo_names_long = char(M_.endo_names_long, 'phi_e_fe');
M_.endo_names = char(M_.endo_names, 'omega_bar_prime_fe');
M_.endo_names_tex = char(M_.endo_names_tex, 'omega\_bar\_prime\_fe');
M_.endo_names_long = char(M_.endo_names_long, 'omega_bar_prime_fe');
M_.endo_names = char(M_.endo_names, 'L_fe');
M_.endo_names_tex = char(M_.endo_names_tex, 'L\_fe');
M_.endo_names_long = char(M_.endo_names_long, 'L_fe');
M_.endo_names = char(M_.endo_names, 'Lr_fe');
M_.endo_names_tex = char(M_.endo_names_tex, 'Lr\_fe');
M_.endo_names_long = char(M_.endo_names_long, 'Lr_fe');
M_.endo_names = char(M_.endo_names, 'Le_fe');
M_.endo_names_tex = char(M_.endo_names_tex, 'Le\_fe');
M_.endo_names_long = char(M_.endo_names_long, 'Le_fe');
M_.endo_names = char(M_.endo_names, 'Nb_fe');
M_.endo_names_tex = char(M_.endo_names_tex, 'Nb\_fe');
M_.endo_names_long = char(M_.endo_names_long, 'Nb_fe');
M_.endo_names = char(M_.endo_names, 'phi_b_fe');
M_.endo_names_tex = char(M_.endo_names_tex, 'phi\_b\_fe');
M_.endo_names_long = char(M_.endo_names_long, 'phi_b_fe');
M_.endo_names = char(M_.endo_names, 'z_fe');
M_.endo_names_tex = char(M_.endo_names_tex, 'z\_fe');
M_.endo_names_long = char(M_.endo_names_long, 'z_fe');
M_.endo_names = char(M_.endo_names, 'Lambda_fe');
M_.endo_names_tex = char(M_.endo_names_tex, 'Lambda\_fe');
M_.endo_names_long = char(M_.endo_names_long, 'Lambda_fe');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_417');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_417');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_417');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_421');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_421');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_421');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_425');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_425');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_425');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_452');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_452');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_452');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_456');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_456');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_456');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_460');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_460');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_460');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_487');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_487');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_487');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_491');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_491');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_491');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_495');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_495');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_495');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_2_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_2\_1');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_2_1');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_2_2');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_2\_2');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_2_2');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_4_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_4\_1');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_4_1');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_4_2');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_4\_2');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_4_2');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_4_3');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_4\_3');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_4_3');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_3_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_3\_1');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_3_1');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_3_2');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_3\_2');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_3_2');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_3_3');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_3\_3');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_3_3');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_0_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_0\_1');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_0_1');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_0_2');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_0\_2');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_0_2');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_0_3');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_0\_3');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_0_3');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_2_3');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_2\_3');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_2_3');
M_.endo_partitions = struct();
M_.param_names = 'cofintintb1';
M_.param_names_tex = 'cofintintb1';
M_.param_names_long = 'cofintintb1';
M_.param_names = char(M_.param_names, 'cofintintb2');
M_.param_names_tex = char(M_.param_names_tex, 'cofintintb2');
M_.param_names_long = char(M_.param_names_long, 'cofintintb2');
M_.param_names = char(M_.param_names, 'cofintintb3');
M_.param_names_tex = char(M_.param_names_tex, 'cofintintb3');
M_.param_names_long = char(M_.param_names_long, 'cofintintb3');
M_.param_names = char(M_.param_names, 'cofintintb4');
M_.param_names_tex = char(M_.param_names_tex, 'cofintintb4');
M_.param_names_long = char(M_.param_names_long, 'cofintintb4');
M_.param_names = char(M_.param_names, 'cofintinf0');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinf0');
M_.param_names_long = char(M_.param_names_long, 'cofintinf0');
M_.param_names = char(M_.param_names, 'cofintinfb1');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinfb1');
M_.param_names_long = char(M_.param_names_long, 'cofintinfb1');
M_.param_names = char(M_.param_names, 'cofintinfb2');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinfb2');
M_.param_names_long = char(M_.param_names_long, 'cofintinfb2');
M_.param_names = char(M_.param_names, 'cofintinfb3');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinfb3');
M_.param_names_long = char(M_.param_names_long, 'cofintinfb3');
M_.param_names = char(M_.param_names, 'cofintinfb4');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinfb4');
M_.param_names_long = char(M_.param_names_long, 'cofintinfb4');
M_.param_names = char(M_.param_names, 'cofintinff1');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinff1');
M_.param_names_long = char(M_.param_names_long, 'cofintinff1');
M_.param_names = char(M_.param_names, 'cofintinff2');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinff2');
M_.param_names_long = char(M_.param_names_long, 'cofintinff2');
M_.param_names = char(M_.param_names, 'cofintinff3');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinff3');
M_.param_names_long = char(M_.param_names_long, 'cofintinff3');
M_.param_names = char(M_.param_names, 'cofintinff4');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinff4');
M_.param_names_long = char(M_.param_names_long, 'cofintinff4');
M_.param_names = char(M_.param_names, 'cofintout');
M_.param_names_tex = char(M_.param_names_tex, 'cofintout');
M_.param_names_long = char(M_.param_names_long, 'cofintout');
M_.param_names = char(M_.param_names, 'cofintoutb1');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutb1');
M_.param_names_long = char(M_.param_names_long, 'cofintoutb1');
M_.param_names = char(M_.param_names, 'cofintoutb2');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutb2');
M_.param_names_long = char(M_.param_names_long, 'cofintoutb2');
M_.param_names = char(M_.param_names, 'cofintoutb3');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutb3');
M_.param_names_long = char(M_.param_names_long, 'cofintoutb3');
M_.param_names = char(M_.param_names, 'cofintoutb4');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutb4');
M_.param_names_long = char(M_.param_names_long, 'cofintoutb4');
M_.param_names = char(M_.param_names, 'cofintoutf1');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutf1');
M_.param_names_long = char(M_.param_names_long, 'cofintoutf1');
M_.param_names = char(M_.param_names, 'cofintoutf2');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutf2');
M_.param_names_long = char(M_.param_names_long, 'cofintoutf2');
M_.param_names = char(M_.param_names, 'cofintoutf3');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutf3');
M_.param_names_long = char(M_.param_names_long, 'cofintoutf3');
M_.param_names = char(M_.param_names, 'cofintoutf4');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutf4');
M_.param_names_long = char(M_.param_names_long, 'cofintoutf4');
M_.param_names = char(M_.param_names, 'cofintoutp');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutp');
M_.param_names_long = char(M_.param_names_long, 'cofintoutp');
M_.param_names = char(M_.param_names, 'cofintoutpb1');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpb1');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpb1');
M_.param_names = char(M_.param_names, 'cofintoutpb2');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpb2');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpb2');
M_.param_names = char(M_.param_names, 'cofintoutpb3');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpb3');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpb3');
M_.param_names = char(M_.param_names, 'cofintoutpb4');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpb4');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpb4');
M_.param_names = char(M_.param_names, 'cofintoutpf1');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpf1');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpf1');
M_.param_names = char(M_.param_names, 'cofintoutpf2');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpf2');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpf2');
M_.param_names = char(M_.param_names, 'cofintoutpf3');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpf3');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpf3');
M_.param_names = char(M_.param_names, 'cofintoutpf4');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpf4');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpf4');
M_.param_names = char(M_.param_names, 'std_r_');
M_.param_names_tex = char(M_.param_names_tex, 'std\_r\_');
M_.param_names_long = char(M_.param_names_long, 'std_r_');
M_.param_names = char(M_.param_names, 'std_r_quart');
M_.param_names_tex = char(M_.param_names_tex, 'std\_r\_quart');
M_.param_names_long = char(M_.param_names_long, 'std_r_quart');
M_.param_names = char(M_.param_names, 'coffispol');
M_.param_names_tex = char(M_.param_names_tex, 'coffispol');
M_.param_names_long = char(M_.param_names_long, 'coffispol');
M_.param_names = char(M_.param_names, 'beta');
M_.param_names_tex = char(M_.param_names_tex, 'beta');
M_.param_names_long = char(M_.param_names_long, 'beta');
M_.param_names = char(M_.param_names, 'varphi');
M_.param_names_tex = char(M_.param_names_tex, 'varphi');
M_.param_names_long = char(M_.param_names_long, 'varphi');
M_.param_names = char(M_.param_names, 'h');
M_.param_names_tex = char(M_.param_names_tex, 'h');
M_.param_names_long = char(M_.param_names_long, 'h');
M_.param_names = char(M_.param_names, 'alpha');
M_.param_names_tex = char(M_.param_names_tex, 'alpha');
M_.param_names_long = char(M_.param_names_long, 'alpha');
M_.param_names = char(M_.param_names, 'delta');
M_.param_names_tex = char(M_.param_names_tex, 'delta');
M_.param_names_long = char(M_.param_names_long, 'delta');
M_.param_names = char(M_.param_names, 'eta_i');
M_.param_names_tex = char(M_.param_names_tex, 'eta\_i');
M_.param_names_long = char(M_.param_names_long, 'eta_i');
M_.param_names = char(M_.param_names, 'epsilon');
M_.param_names_tex = char(M_.param_names_tex, 'epsilon');
M_.param_names_long = char(M_.param_names_long, 'epsilon');
M_.param_names = char(M_.param_names, 'xi_p');
M_.param_names_tex = char(M_.param_names_tex, 'xi\_p');
M_.param_names_long = char(M_.param_names_long, 'xi_p');
M_.param_names = char(M_.param_names, 'theta');
M_.param_names_tex = char(M_.param_names_tex, 'theta');
M_.param_names_long = char(M_.param_names_long, 'theta');
M_.param_names = char(M_.param_names, 'psi_L');
M_.param_names_tex = char(M_.param_names_tex, 'psi\_L');
M_.param_names_long = char(M_.param_names_long, 'psi_L');
M_.param_names = char(M_.param_names, 'psi_K');
M_.param_names_tex = char(M_.param_names_tex, 'psi\_K');
M_.param_names_long = char(M_.param_names_long, 'psi_K');
M_.param_names = char(M_.param_names, 'sigma');
M_.param_names_tex = char(M_.param_names_tex, 'sigma');
M_.param_names_long = char(M_.param_names_long, 'sigma');
M_.param_names = char(M_.param_names, 'mu');
M_.param_names_tex = char(M_.param_names_tex, 'mu');
M_.param_names_long = char(M_.param_names_long, 'mu');
M_.param_names = char(M_.param_names, 'gamma');
M_.param_names_tex = char(M_.param_names_tex, 'gamma');
M_.param_names_long = char(M_.param_names_long, 'gamma');
M_.param_names = char(M_.param_names, 'lambda');
M_.param_names_tex = char(M_.param_names_tex, 'lambda');
M_.param_names_long = char(M_.param_names_long, 'lambda');
M_.param_names = char(M_.param_names, 'N_nb');
M_.param_names_tex = char(M_.param_names_tex, 'N\_nb');
M_.param_names_long = char(M_.param_names_long, 'N_nb');
M_.param_names = char(M_.param_names, 'psi_pi');
M_.param_names_tex = char(M_.param_names_tex, 'psi\_pi');
M_.param_names_long = char(M_.param_names_long, 'psi_pi');
M_.param_names = char(M_.param_names, 'psi_y');
M_.param_names_tex = char(M_.param_names_tex, 'psi\_y');
M_.param_names_long = char(M_.param_names_long, 'psi_y');
M_.param_names = char(M_.param_names, 'rho_i');
M_.param_names_tex = char(M_.param_names_tex, 'rho\_i');
M_.param_names_long = char(M_.param_names_long, 'rho_i');
M_.param_names = char(M_.param_names, 'rho_a');
M_.param_names_tex = char(M_.param_names_tex, 'rho\_a');
M_.param_names_long = char(M_.param_names_long, 'rho_a');
M_.param_names = char(M_.param_names, 'sigma_i');
M_.param_names_tex = char(M_.param_names_tex, 'sigma\_i');
M_.param_names_long = char(M_.param_names_long, 'sigma_i');
M_.param_names = char(M_.param_names, 'sigma_a');
M_.param_names_tex = char(M_.param_names_tex, 'sigma\_a');
M_.param_names_long = char(M_.param_names_long, 'sigma_a');
M_.param_names = char(M_.param_names, 'G_over_Y');
M_.param_names_tex = char(M_.param_names_tex, 'G\_over\_Y');
M_.param_names_long = char(M_.param_names_long, 'G_over_Y');
M_.param_names = char(M_.param_names, 'brate');
M_.param_names_tex = char(M_.param_names_tex, 'brate');
M_.param_names_long = char(M_.param_names_long, 'brate');
M_.param_names = char(M_.param_names, 'omega_bar_ss');
M_.param_names_tex = char(M_.param_names_tex, 'omega\_bar\_ss');
M_.param_names_long = char(M_.param_names_long, 'omega_bar_ss');
M_.param_names = char(M_.param_names, 'F_ss');
M_.param_names_tex = char(M_.param_names_tex, 'F\_ss');
M_.param_names_long = char(M_.param_names_long, 'F_ss');
M_.param_names = char(M_.param_names, 'F1_ss');
M_.param_names_tex = char(M_.param_names_tex, 'F1\_ss');
M_.param_names_long = char(M_.param_names_long, 'F1_ss');
M_.param_names = char(M_.param_names, 'G_ss');
M_.param_names_tex = char(M_.param_names_tex, 'G\_ss');
M_.param_names_long = char(M_.param_names_long, 'G_ss');
M_.param_names = char(M_.param_names, 'G1_ss');
M_.param_names_tex = char(M_.param_names_tex, 'G1\_ss');
M_.param_names_long = char(M_.param_names_long, 'G1_ss');
M_.param_names = char(M_.param_names, 'G11_ss');
M_.param_names_tex = char(M_.param_names_tex, 'G11\_ss');
M_.param_names_long = char(M_.param_names_long, 'G11_ss');
M_.param_names = char(M_.param_names, 'Gamma_ss');
M_.param_names_tex = char(M_.param_names_tex, 'Gamma\_ss');
M_.param_names_long = char(M_.param_names_long, 'Gamma_ss');
M_.param_names = char(M_.param_names, 'Gamma1_ss');
M_.param_names_tex = char(M_.param_names_tex, 'Gamma1\_ss');
M_.param_names_long = char(M_.param_names_long, 'Gamma1_ss');
M_.param_names = char(M_.param_names, 'Gamma11_ss');
M_.param_names_tex = char(M_.param_names_tex, 'Gamma11\_ss');
M_.param_names_long = char(M_.param_names_long, 'Gamma11_ss');
M_.param_names = char(M_.param_names, 'rho_g');
M_.param_names_tex = char(M_.param_names_tex, 'rho\_g');
M_.param_names_long = char(M_.param_names_long, 'rho_g');
M_.param_names = char(M_.param_names, 'xi_ss');
M_.param_names_tex = char(M_.param_names_tex, 'xi\_ss');
M_.param_names_long = char(M_.param_names_long, 'xi_ss');
M_.param_names = char(M_.param_names, 'spread_RkRb_ss');
M_.param_names_tex = char(M_.param_names_tex, 'spread\_RkRb\_ss');
M_.param_names_long = char(M_.param_names_long, 'spread_RkRb_ss');
M_.param_names = char(M_.param_names, 'phi_e_ss');
M_.param_names_tex = char(M_.param_names_tex, 'phi\_e\_ss');
M_.param_names_long = char(M_.param_names_long, 'phi_e_ss');
M_.param_names = char(M_.param_names, 'Pi_ss');
M_.param_names_tex = char(M_.param_names_tex, 'Pi\_ss');
M_.param_names_long = char(M_.param_names_long, 'Pi_ss');
M_.param_names = char(M_.param_names, 'R_ss');
M_.param_names_tex = char(M_.param_names_tex, 'R\_ss');
M_.param_names_long = char(M_.param_names_long, 'R_ss');
M_.param_names = char(M_.param_names, 'Rl_ss');
M_.param_names_tex = char(M_.param_names_tex, 'Rl\_ss');
M_.param_names_long = char(M_.param_names_long, 'Rl_ss');
M_.param_names = char(M_.param_names, 'Rk_ss');
M_.param_names_tex = char(M_.param_names_tex, 'Rk\_ss');
M_.param_names_long = char(M_.param_names_long, 'Rk_ss');
M_.param_names = char(M_.param_names, 'Rb_ss');
M_.param_names_tex = char(M_.param_names_tex, 'Rb\_ss');
M_.param_names_long = char(M_.param_names_long, 'Rb_ss');
M_.param_names = char(M_.param_names, 'X_ss');
M_.param_names_tex = char(M_.param_names_tex, 'X\_ss');
M_.param_names_long = char(M_.param_names_long, 'X_ss');
M_.param_names = char(M_.param_names, 'mc_ss');
M_.param_names_tex = char(M_.param_names_tex, 'mc\_ss');
M_.param_names_long = char(M_.param_names_long, 'mc_ss');
M_.param_names = char(M_.param_names, 'Q_ss');
M_.param_names_tex = char(M_.param_names_tex, 'Q\_ss');
M_.param_names_long = char(M_.param_names_long, 'Q_ss');
M_.param_names = char(M_.param_names, 'rk_ss');
M_.param_names_tex = char(M_.param_names_tex, 'rk\_ss');
M_.param_names_long = char(M_.param_names_long, 'rk_ss');
M_.param_names = char(M_.param_names, 'K_over_l');
M_.param_names_tex = char(M_.param_names_tex, 'K\_over\_l');
M_.param_names_long = char(M_.param_names_long, 'K_over_l');
M_.param_names = char(M_.param_names, 'w_ss');
M_.param_names_tex = char(M_.param_names_tex, 'w\_ss');
M_.param_names_long = char(M_.param_names_long, 'w_ss');
M_.param_names = char(M_.param_names, 'l_ss');
M_.param_names_tex = char(M_.param_names_tex, 'l\_ss');
M_.param_names_long = char(M_.param_names_long, 'l_ss');
M_.param_names = char(M_.param_names, 'K_ss');
M_.param_names_tex = char(M_.param_names_tex, 'K\_ss');
M_.param_names_long = char(M_.param_names_long, 'K_ss');
M_.param_names = char(M_.param_names, 'Y_ss');
M_.param_names_tex = char(M_.param_names_tex, 'Y\_ss');
M_.param_names_long = char(M_.param_names_long, 'Y_ss');
M_.param_names = char(M_.param_names, 'Gov_ss');
M_.param_names_tex = char(M_.param_names_tex, 'Gov\_ss');
M_.param_names_long = char(M_.param_names_long, 'Gov_ss');
M_.param_names = char(M_.param_names, 'I_ss');
M_.param_names_tex = char(M_.param_names_tex, 'I\_ss');
M_.param_names_long = char(M_.param_names_long, 'I_ss');
M_.param_names = char(M_.param_names, 'omega_bar_prime_ss');
M_.param_names_tex = char(M_.param_names_tex, 'omega\_bar\_prime\_ss');
M_.param_names_long = char(M_.param_names_long, 'omega_bar_prime_ss');
M_.param_names = char(M_.param_names, 'V_ss');
M_.param_names_tex = char(M_.param_names_tex, 'V\_ss');
M_.param_names_long = char(M_.param_names_long, 'V_ss');
M_.param_names = char(M_.param_names, 'N_ss');
M_.param_names_tex = char(M_.param_names_tex, 'N\_ss');
M_.param_names_long = char(M_.param_names_long, 'N_ss');
M_.param_names = char(M_.param_names, 'Le_ss');
M_.param_names_tex = char(M_.param_names_tex, 'Le\_ss');
M_.param_names_long = char(M_.param_names_long, 'Le_ss');
M_.param_names = char(M_.param_names, 'Lr_ss');
M_.param_names_tex = char(M_.param_names_tex, 'Lr\_ss');
M_.param_names_long = char(M_.param_names_long, 'Lr_ss');
M_.param_names = char(M_.param_names, 'L_ss');
M_.param_names_tex = char(M_.param_names_tex, 'L\_ss');
M_.param_names_long = char(M_.param_names_long, 'L_ss');
M_.param_names = char(M_.param_names, 'phi_ss');
M_.param_names_tex = char(M_.param_names_tex, 'phi\_ss');
M_.param_names_long = char(M_.param_names_long, 'phi_ss');
M_.param_names = char(M_.param_names, 'Ce_ss');
M_.param_names_tex = char(M_.param_names_tex, 'Ce\_ss');
M_.param_names_long = char(M_.param_names_long, 'Ce_ss');
M_.param_names = char(M_.param_names, 'phi_b_ss');
M_.param_names_tex = char(M_.param_names_tex, 'phi\_b\_ss');
M_.param_names_long = char(M_.param_names_long, 'phi_b_ss');
M_.param_names = char(M_.param_names, 'z_ss');
M_.param_names_tex = char(M_.param_names_tex, 'z\_ss');
M_.param_names_long = char(M_.param_names_long, 'z_ss');
M_.param_names = char(M_.param_names, 'x_ss');
M_.param_names_tex = char(M_.param_names_tex, 'x\_ss');
M_.param_names_long = char(M_.param_names_long, 'x_ss');
M_.param_names = char(M_.param_names, 'eta_ss');
M_.param_names_tex = char(M_.param_names_tex, 'eta\_ss');
M_.param_names_long = char(M_.param_names_long, 'eta_ss');
M_.param_names = char(M_.param_names, 'nu_ss');
M_.param_names_tex = char(M_.param_names_tex, 'nu\_ss');
M_.param_names_long = char(M_.param_names_long, 'nu_ss');
M_.param_names = char(M_.param_names, 'Nb_ss');
M_.param_names_tex = char(M_.param_names_tex, 'Nb\_ss');
M_.param_names_long = char(M_.param_names_long, 'Nb_ss');
M_.param_names = char(M_.param_names, 'Nb_e_ss');
M_.param_names_tex = char(M_.param_names_tex, 'Nb\_e\_ss');
M_.param_names_long = char(M_.param_names_long, 'Nb_e_ss');
M_.param_names = char(M_.param_names, 'Cb_ss');
M_.param_names_tex = char(M_.param_names_tex, 'Cb\_ss');
M_.param_names_long = char(M_.param_names_long, 'Cb_ss');
M_.param_names = char(M_.param_names, 'C_ss');
M_.param_names_tex = char(M_.param_names_tex, 'C\_ss');
M_.param_names_long = char(M_.param_names_long, 'C_ss');
M_.param_names = char(M_.param_names, 'Cp_ss');
M_.param_names_tex = char(M_.param_names_tex, 'Cp\_ss');
M_.param_names_long = char(M_.param_names_long, 'Cp_ss');
M_.param_names = char(M_.param_names, 'GDP_ss');
M_.param_names_tex = char(M_.param_names_tex, 'GDP\_ss');
M_.param_names_long = char(M_.param_names_long, 'GDP_ss');
M_.param_names = char(M_.param_names, 'varrho_ss');
M_.param_names_tex = char(M_.param_names_tex, 'varrho\_ss');
M_.param_names_long = char(M_.param_names_long, 'varrho_ss');
M_.param_names = char(M_.param_names, 'chi');
M_.param_names_tex = char(M_.param_names_tex, 'chi');
M_.param_names_long = char(M_.param_names_long, 'chi');
M_.param_names = char(M_.param_names, 'gamma_p');
M_.param_names_tex = char(M_.param_names_tex, 'gamma\_p');
M_.param_names_long = char(M_.param_names_long, 'gamma_p');
M_.param_names = char(M_.param_names, 'tr_omega_bar_ss');
M_.param_names_tex = char(M_.param_names_tex, 'tr\_omega\_bar\_ss');
M_.param_names_long = char(M_.param_names_long, 'tr_omega_bar_ss');
M_.param_names = char(M_.param_names, 'spread_RbR_ss');
M_.param_names_tex = char(M_.param_names_tex, 'spread\_RbR\_ss');
M_.param_names_long = char(M_.param_names_long, 'spread_RbR_ss');
M_.param_names = char(M_.param_names, 'chi_e');
M_.param_names_tex = char(M_.param_names_tex, 'chi\_e');
M_.param_names_long = char(M_.param_names_long, 'chi_e');
M_.param_names = char(M_.param_names, 'c_U');
M_.param_names_tex = char(M_.param_names_tex, 'c\_U');
M_.param_names_long = char(M_.param_names_long, 'c_U');
M_.param_names = char(M_.param_names, 'xi_p_fe');
M_.param_names_tex = char(M_.param_names_tex, 'xi\_p\_fe');
M_.param_names_long = char(M_.param_names_long, 'xi_p_fe');
M_.param_partitions = struct();
M_.exo_det_nbr = 0;
M_.exo_nbr = 3;
M_.endo_nbr = 98;
M_.param_nbr = 114;
M_.orig_endo_nbr = 77;
M_.aux_vars(1).endo_index = 78;
M_.aux_vars(1).type = 0;
M_.aux_vars(2).endo_index = 79;
M_.aux_vars(2).type = 0;
M_.aux_vars(3).endo_index = 80;
M_.aux_vars(3).type = 0;
M_.aux_vars(4).endo_index = 81;
M_.aux_vars(4).type = 0;
M_.aux_vars(5).endo_index = 82;
M_.aux_vars(5).type = 0;
M_.aux_vars(6).endo_index = 83;
M_.aux_vars(6).type = 0;
M_.aux_vars(7).endo_index = 84;
M_.aux_vars(7).type = 0;
M_.aux_vars(8).endo_index = 85;
M_.aux_vars(8).type = 0;
M_.aux_vars(9).endo_index = 86;
M_.aux_vars(9).type = 0;
M_.aux_vars(10).endo_index = 87;
M_.aux_vars(10).type = 1;
M_.aux_vars(10).orig_index = 3;
M_.aux_vars(10).orig_lead_lag = -1;
M_.aux_vars(11).endo_index = 88;
M_.aux_vars(11).type = 1;
M_.aux_vars(11).orig_index = 3;
M_.aux_vars(11).orig_lead_lag = -2;
M_.aux_vars(12).endo_index = 89;
M_.aux_vars(12).type = 1;
M_.aux_vars(12).orig_index = 5;
M_.aux_vars(12).orig_lead_lag = -1;
M_.aux_vars(13).endo_index = 90;
M_.aux_vars(13).type = 1;
M_.aux_vars(13).orig_index = 5;
M_.aux_vars(13).orig_lead_lag = -2;
M_.aux_vars(14).endo_index = 91;
M_.aux_vars(14).type = 1;
M_.aux_vars(14).orig_index = 5;
M_.aux_vars(14).orig_lead_lag = -3;
M_.aux_vars(15).endo_index = 92;
M_.aux_vars(15).type = 1;
M_.aux_vars(15).orig_index = 4;
M_.aux_vars(15).orig_lead_lag = -1;
M_.aux_vars(16).endo_index = 93;
M_.aux_vars(16).type = 1;
M_.aux_vars(16).orig_index = 4;
M_.aux_vars(16).orig_lead_lag = -2;
M_.aux_vars(17).endo_index = 94;
M_.aux_vars(17).type = 1;
M_.aux_vars(17).orig_index = 4;
M_.aux_vars(17).orig_lead_lag = -3;
M_.aux_vars(18).endo_index = 95;
M_.aux_vars(18).type = 1;
M_.aux_vars(18).orig_index = 1;
M_.aux_vars(18).orig_lead_lag = -1;
M_.aux_vars(19).endo_index = 96;
M_.aux_vars(19).type = 1;
M_.aux_vars(19).orig_index = 1;
M_.aux_vars(19).orig_lead_lag = -2;
M_.aux_vars(20).endo_index = 97;
M_.aux_vars(20).type = 1;
M_.aux_vars(20).orig_index = 1;
M_.aux_vars(20).orig_lead_lag = -3;
M_.aux_vars(21).endo_index = 98;
M_.aux_vars(21).type = 1;
M_.aux_vars(21).orig_index = 3;
M_.aux_vars(21).orig_lead_lag = -3;
M_.Sigma_e = zeros(3, 3);
M_.Correlation_matrix = eye(3, 3);
M_.H = 0;
M_.Correlation_matrix_ME = 1;
M_.sigma_e_is_diagonal = 1;
M_.det_shocks = [];
options_.linear = 1;
options_.block=0;
options_.bytecode=0;
options_.use_dll=0;
M_.hessian_eq_zero = 1;
erase_compiled_function('NK_RA16_static');
erase_compiled_function('NK_RA16_dynamic');
M_.orig_eq_nbr = 77;
M_.eq_nbr = 98;
M_.ramsey_eq_nbr = 0;
M_.set_auxiliary_variables = exist(['./' M_.fname '_set_auxiliary_variables.m'], 'file') == 2;
M_.lead_lag_incidence = [
 1 43 0;
 0 44 0;
 2 45 141;
 3 46 142;
 4 47 143;
 0 48 0;
 0 49 0;
 0 50 0;
 5 51 144;
 6 52 0;
 0 53 0;
 0 54 0;
 0 55 0;
 7 56 145;
 0 57 0;
 0 58 0;
 8 59 0;
 9 60 0;
 0 61 146;
 0 62 0;
 0 63 147;
 0 64 0;
 0 65 0;
 10 66 0;
 11 67 0;
 12 68 148;
 0 69 0;
 13 70 0;
 0 71 0;
 14 72 0;
 15 73 0;
 0 74 0;
 0 75 0;
 0 76 0;
 16 77 0;
 17 78 0;
 18 79 149;
 0 80 0;
 0 81 150;
 0 82 0;
 0 83 0;
 0 84 0;
 0 85 0;
 0 86 0;
 0 87 0;
 0 88 0;
 0 89 0;
 0 90 0;
 19 91 151;
 20 92 0;
 0 93 0;
 0 94 0;
 0 95 0;
 21 96 152;
 0 97 0;
 0 98 0;
 22 99 0;
 23 100 0;
 0 101 153;
 0 102 0;
 0 103 154;
 0 104 0;
 0 105 0;
 24 106 0;
 25 107 155;
 0 108 0;
 26 109 0;
 0 110 0;
 27 111 0;
 28 112 0;
 0 113 0;
 0 114 0;
 0 115 0;
 29 116 0;
 30 117 156;
 0 118 0;
 0 119 157;
 0 120 158;
 0 121 159;
 0 122 160;
 0 123 161;
 0 124 162;
 0 125 163;
 0 126 164;
 0 127 165;
 0 128 166;
 31 129 0;
 32 130 0;
 33 131 0;
 34 132 0;
 35 133 0;
 36 134 0;
 37 135 0;
 38 136 0;
 39 137 0;
 40 138 0;
 41 139 0;
 42 140 0;]';
M_.nstatic = 41;
M_.nfwrd   = 15;
M_.npred   = 31;
M_.nboth   = 11;
M_.nsfwrd   = 26;
M_.nspred   = 42;
M_.ndynamic   = 57;
M_.equations_tags = {
};
M_.static_and_dynamic_models_differ = 0;
M_.exo_names_orig_ord = [1:3];
M_.maximum_lag = 1;
M_.maximum_lead = 1;
M_.maximum_endo_lag = 1;
M_.maximum_endo_lead = 1;
oo_.steady_state = zeros(98, 1);
M_.maximum_exo_lag = 0;
M_.maximum_exo_lead = 0;
oo_.exo_steady_state = zeros(3, 1);
M_.params = NaN(114, 1);
M_.NNZDerivatives = [357; 0; -1];
thispath = cd;                                                           
cd('..');                                                                
load policy_param.mat;                                                   
for i=1:33                                                               
deep_parameter_name = M_.param_names(i,:);                           
eval(['M_.params(i)  = ' deep_parameter_name ' ;'])                  
end                                                                      
cd(thispath);   
M_.params( 32 ) = 100;
std_r_ = M_.params( 32 );
M_.params( 34 ) = 5;
coffispol = M_.params( 34 );
M_.params( 35 ) = 0.9958;
beta = M_.params( 35 );
M_.params( 37 ) = 0.6;
h = M_.params( 37 );
M_.params( 36 ) = 0.25;
varphi = M_.params( 36 );
M_.params( 38 ) = 0.33;
alpha = M_.params( 38 );
M_.params( 39 ) = 0.025;
delta = M_.params( 39 );
M_.params( 113 ) = 100;
c_U = M_.params( 113 );
M_.params( 40 ) = 4;
eta_i = M_.params( 40 );
M_.params( 41 ) = 6;
epsilon = M_.params( 41 );
M_.params( 42 ) = 0.67;
xi_p = M_.params( 42 );
M_.params( 114 ) = 0.00000001;
xi_p_fe = M_.params( 114 );
M_.params( 109 ) = 0;
gamma_p = M_.params( 109 );
M_.params( 44 ) = 1;
psi_L = M_.params( 44 );
M_.params( 45 ) = 1;
psi_K = M_.params( 45 );
M_.params( 46 ) = 0.35;
sigma = M_.params( 46 );
M_.params( 47 ) = 0.298122852301025;
mu = M_.params( 47 );
M_.params( 48 ) = 0.975;
gamma = M_.params( 48 );
M_.params( 43 ) = 0.9915;
theta = M_.params( 43 );
M_.params( 51 ) = 1.5;
psi_pi = M_.params( 51 );
M_.params( 52 ) = 0.125;
psi_y = M_.params( 52 );
M_.params( 53 ) = 0.8;
rho_i = M_.params( 53 );
M_.params( 54 ) = 0.9;
rho_a = M_.params( 54 );
M_.params( 68 ) = 0.9;
rho_g = M_.params( 68 );
M_.params( 55 ) = 0.16;
sigma_i = M_.params( 55 );
M_.params( 56 ) = 1.2;
sigma_a = M_.params( 56 );
sigma_g = 1;        
M_.params( 57 ) = 0.2;
G_over_Y = M_.params( 57 );
M_.params( 58 ) = 0.0075;
brate = M_.params( 58 );
M_.params( 72 ) = 1.005528976378204;
Pi_ss = M_.params( 72 );
M_.params( 73 ) = M_.params(72)/M_.params(35);
R_ss = M_.params( 73 );
M_.params( 111 ) = 1.000499625436899;
spread_RbR_ss = M_.params( 111 );
M_.params( 76 ) = M_.params(111)*M_.params(73);
Rb_ss = M_.params( 76 );
M_.params( 96 ) = 8;
phi_b_ss = M_.params( 96 );
M_.params( 59 ) = exp(M_.params(46)*norminv(M_.params(58),0,1)-0.5*M_.params(46)^2);
omega_bar_ss = M_.params( 59 );
M_.params( 110 ) = (0.5*M_.params(46)^2+log(M_.params(59)))/M_.params(46);
tr_omega_bar_ss = M_.params( 110 );
M_.params( 60 ) = normcdf(M_.params(110),0,1);
F_ss = M_.params( 60 );
M_.params( 61 ) = 1/(M_.params(46)*M_.params(59))*normpdf(M_.params(110),0,1);
F1_ss = M_.params( 61 );
F11_ss= -F1_ss/omega_bar_ss*(1+(log(omega_bar_ss)+0.5*sigma^2)/sigma^2); 
M_.params( 62 ) = normcdf(M_.params(110)-M_.params(46),0,1);
G_ss = M_.params( 62 );
M_.params( 63 ) = M_.params(59)*M_.params(61);
G1_ss = M_.params( 63 );
M_.params( 64 ) = M_.params(61)+M_.params(59)*F11_ss;
G11_ss = M_.params( 64 );
M_.params( 65 ) = M_.params(59)*(1-M_.params(60))+M_.params(62);
Gamma_ss = M_.params( 65 );
M_.params( 66 ) = 1-M_.params(60);
Gamma1_ss = M_.params( 66 );
M_.params( 67 ) = (-M_.params(61));
Gamma11_ss = M_.params( 67 );
F12_ss    =   -F1_ss/sigma*(1+(0.25*sigma^4-(log(omega_bar_ss))^2)/sigma^2);
F2_ss     =   (0.5*sigma^2-log(omega_bar_ss))/sigma^2*normpdf(tr_omega_bar_ss,0,1);
G12_ss    =   omega_bar_ss*F12_ss;
G2_ss     =   ((0.5*sigma^2-log(omega_bar_ss))/sigma^2-1)*normpdf(tr_omega_bar_ss-sigma,0,1);
Gamma2_ss   =   -omega_bar_ss*F2_ss+G2_ss;
Gamma12_ss  =   -F2_ss;
M_.params( 69 ) = M_.params(66)/(M_.params(66)-M_.params(47)*M_.params(63));
xi_ss = M_.params( 69 );
M_.params( 70 ) = M_.params(66)/(M_.params(66)-M_.params(47)*(M_.params(63)*(1-M_.params(65))+M_.params(62)*M_.params(66)));
spread_RkRb_ss = M_.params( 70 );
M_.params( 71 ) = 1/(1-(M_.params(65)-M_.params(62)*M_.params(47))*M_.params(70));
phi_e_ss = M_.params( 71 );
M_.params( 76 ) = M_.params(111)*M_.params(73);
Rb_ss = M_.params( 76 );
M_.params( 75 ) = M_.params(70)*M_.params(76);
Rk_ss = M_.params( 75 );
M_.params( 74 ) = M_.params(59)*M_.params(75)/(1-1/M_.params(71));
Rl_ss = M_.params( 74 );
M_.params( 77 ) = M_.params(41)/(M_.params(41)-1);
X_ss = M_.params( 77 );
M_.params( 78 ) = (M_.params(41)-1)/M_.params(41);
mc_ss = M_.params( 78 );
M_.params( 79 ) = 1;
Q_ss = M_.params( 79 );
M_.params( 80 ) = M_.params(75)/M_.params(72)-(1-M_.params(39));
rk_ss = M_.params( 80 );
M_.params( 81 ) = (M_.params(38)/(M_.params(77)*(1+M_.params(45)*(M_.params(73)-1))*M_.params(80)))^(1/(1-M_.params(38)));
K_over_l = M_.params( 81 );
M_.params( 82 ) = (1-M_.params(38))*M_.params(81)^M_.params(38)/(M_.params(77)*(1+(M_.params(73)-1)*M_.params(44)));
w_ss = M_.params( 82 );
Y_over_K = X_ss/alpha*(rk_ss)*(1+psi_K*(R_ss-1));      
M_.params( 83 ) = 0.3333333333333333;
l_ss = M_.params( 83 );
M_.params( 84 ) = M_.params(81)*M_.params(83);
K_ss = M_.params( 84 );
M_.params( 85 ) = Y_over_K*M_.params(84);
Y_ss = M_.params( 85 );
M_.params( 86 ) = M_.params(57)*M_.params(85);
Gov_ss = M_.params( 86 );
M_.params( 87 ) = M_.params(39)*M_.params(84);
I_ss = M_.params( 87 );
YK_ss   =   X_ss/alpha*(rk_ss)*(1+psi_K*(R_ss-1));
M_.params( 88 ) = M_.params(59)*M_.params(75);
omega_bar_prime_ss = M_.params( 88 );
M_.params( 89 ) = (1-M_.params(65))*M_.params(75)*M_.params(84)/M_.params(72);
V_ss = M_.params( 89 );
M_.params( 90 ) = M_.params(84)/M_.params(71);
N_ss = M_.params( 90 );
M_.params( 91 ) = M_.params(84)-M_.params(90);
Le_ss = M_.params( 91 );
M_.params( 92 ) = M_.params(83)*M_.params(44)*M_.params(82)+M_.params(84)*M_.params(45)*M_.params(80);
Lr_ss = M_.params( 92 );
M_.params( 93 ) = M_.params(91)+M_.params(92);
L_ss = M_.params( 93 );
M_.params( 94 ) = (M_.params(90)+M_.params(93))/M_.params(90);
phi_ss = M_.params( 94 );
We = N_ss-gamma*V_ss;                       
M_.params( 95 ) = (1-M_.params(48))*M_.params(89);
Ce_ss = M_.params( 95 );
M_.params( 97 ) = (M_.params(73)+(M_.params(76)-M_.params(73))*M_.params(96))/M_.params(72);
z_ss = M_.params( 97 );
M_.params( 98 ) = M_.params(97);
x_ss = M_.params( 98 );
M_.params( 99 ) = (1-M_.params(43))/(1-M_.params(35)*M_.params(43)*M_.params(98));
eta_ss = M_.params( 99 );
M_.params( 100 ) = (1-M_.params(43))*(M_.params(76)-M_.params(73))/M_.params(73)/(1-M_.params(97)*M_.params(35)*M_.params(43));
nu_ss = M_.params( 100 );
M_.params( 49 ) = (M_.params(99)+M_.params(96)*M_.params(100))/M_.params(96);
lambda = M_.params( 49 );
M_.params( 101 ) = M_.params(91)/M_.params(96);
Nb_ss = M_.params( 101 );
M_.params( 102 ) = M_.params(97)*M_.params(43)*M_.params(101);
Nb_e_ss = M_.params( 102 );
M_.params( 50 ) = M_.params(101)-M_.params(102);
N_nb = M_.params( 50 );
M_.params( 103 ) = M_.params(101)*M_.params(97)*(1-M_.params(43));
Cb_ss = M_.params( 103 );
M_.params( 104 ) = M_.params(85)-M_.params(87)-M_.params(95)-M_.params(103)-M_.params(86)-M_.params(84)*M_.params(62)*M_.params(47)*M_.params(75)/M_.params(72);
C_ss = M_.params( 104 );
M_.params( 105 ) = M_.params(103)+M_.params(95)+M_.params(104);
Cp_ss = M_.params( 105 );
M_.params( 106 ) = M_.params(86)+M_.params(87)+M_.params(105);
GDP_ss = M_.params( 106 );
M_.params( 107 ) = (-1)/(M_.params(104)-M_.params(104)*M_.params(37));
varrho_ss = M_.params( 107 );
M_.params( 108 ) = M_.params(82)*M_.params(107)/M_.params(83)^M_.params(36);
chi = M_.params( 108 );
Upsilon     =   1-Gamma_ss+xi_ss*(Gamma_ss-mu*G_ss); 
domegabards1=-(Gamma_ss-mu*G_ss)/((Gamma1_ss-mu*G1_ss)*spread_RkRb_ss);
domegabardphi_e=(1-(Gamma_ss-mu*G_ss)*spread_RkRb_ss)/((Gamma1_ss-mu*G1_ss)*spread_RkRb_ss*phi_e_ss);
domegabardsigma=-(Gamma2_ss-mu*G2_ss)/(Gamma1_ss-mu*G1_ss);
psi_1  =   mu*(Gamma1_ss*G11_ss-Gamma11_ss*G1_ss)/((Gamma1_ss-mu*G1_ss)^2);
psi_2  =   mu*(Gamma1_ss*G12_ss-Gamma12_ss*G1_ss)/((Gamma1_ss-mu*G1_ss)^2);
Upsilon_1   =   psi_1*(Gamma_ss-mu*G_ss);
Upsilon_2   =   -Gamma2_ss+psi_2*(Gamma_ss-mu*G_ss)+xi_ss*(Gamma2_ss-mu*G2_ss);
dphi_eds1=((spread_RkRb_ss*Upsilon_1-psi_1)*domegabards1+Upsilon)/((psi_1-spread_RkRb_ss*Upsilon_1)*domegabardphi_e);
M_.params( 112 ) = M_.params(71)/dphi_eds1*1/M_.params(70);
chi_e = M_.params( 112 );
%
% INITVAL instructions
%
options_.initval_file = 0;
oo_.steady_state( 7 ) = 0;
oo_.steady_state( 8 ) = 0;
oo_.steady_state( 9 ) = 0;
oo_.steady_state( 10 ) = 0;
oo_.steady_state( 11 ) = 0;
oo_.steady_state( 14 ) = 0;
oo_.steady_state( 15 ) = 0;
oo_.steady_state( 13 ) = 0;
oo_.steady_state( 16 ) = 0;
oo_.steady_state( 17 ) = 0;
oo_.steady_state( 18 ) = 0;
oo_.steady_state( 19 ) = 0;
oo_.steady_state( 20 ) = 0;
oo_.steady_state( 21 ) = 0;
oo_.steady_state( 22 ) = 0;
oo_.steady_state( 23 ) = 0;
oo_.steady_state( 24 ) = 0;
oo_.steady_state( 25 ) = 0;
oo_.steady_state( 26 ) = 0;
oo_.steady_state( 27 ) = 0;
oo_.steady_state( 28 ) = 0;
oo_.steady_state( 29 ) = 0;
oo_.steady_state( 30 ) = 0;
oo_.steady_state( 31 ) = 0;
oo_.steady_state( 32 ) = 0;
oo_.steady_state( 33 ) = 0;
oo_.steady_state( 34 ) = 0;
oo_.steady_state( 36 ) = 0;
oo_.steady_state( 37 ) = 0;
oo_.steady_state( 38 ) = 0;
oo_.steady_state( 40 ) = 0;
oo_.steady_state( 41 ) = 0;
oo_.steady_state( 42 ) = 0;
oo_.steady_state( 43 ) = 0;
oo_.steady_state( 39 ) = 0;
oo_.steady_state( 46 ) = 0;
oo_.steady_state(78)=oo_.steady_state(3);
oo_.steady_state(79)=oo_.steady_state(78);
oo_.steady_state(80)=oo_.steady_state(79);
oo_.steady_state(81)=oo_.steady_state(4);
oo_.steady_state(82)=oo_.steady_state(81);
oo_.steady_state(83)=oo_.steady_state(82);
oo_.steady_state(84)=oo_.steady_state(5);
oo_.steady_state(85)=oo_.steady_state(84);
oo_.steady_state(86)=oo_.steady_state(85);
oo_.steady_state(87)=oo_.steady_state(3);
oo_.steady_state(88)=oo_.steady_state(87);
oo_.steady_state(89)=oo_.steady_state(5);
oo_.steady_state(90)=oo_.steady_state(89);
oo_.steady_state(91)=oo_.steady_state(90);
oo_.steady_state(92)=oo_.steady_state(4);
oo_.steady_state(93)=oo_.steady_state(92);
oo_.steady_state(94)=oo_.steady_state(93);
oo_.steady_state(95)=oo_.steady_state(1);
oo_.steady_state(96)=oo_.steady_state(95);
oo_.steady_state(97)=oo_.steady_state(96);
oo_.steady_state(98)=oo_.steady_state(88);
if M_.exo_nbr > 0
	oo_.exo_simul = ones(M_.maximum_lag,1)*oo_.exo_steady_state';
end
if M_.exo_det_nbr > 0
	oo_.exo_det_simul = ones(M_.maximum_lag,1)*oo_.exo_det_steady_state';
end
%
% SHOCKS instructions
%
M_.exo_det_length = 0;
M_.Sigma_e(1, 1) = 1;
M_.Sigma_e(2, 2) = 1;
M_.Sigma_e(3, 3) = 1;
save('NK_RA16_results.mat', 'oo_', 'M_', 'options_');
if exist('estim_params_', 'var') == 1
  save('NK_RA16_results.mat', 'estim_params_', '-append');
end
if exist('bayestopt_', 'var') == 1
  save('NK_RA16_results.mat', 'bayestopt_', '-append');
end
if exist('dataset_', 'var') == 1
  save('NK_RA16_results.mat', 'dataset_', '-append');
end
if exist('estimation_info', 'var') == 1
  save('NK_RA16_results.mat', 'estimation_info', '-append');
end
if exist('dataset_info', 'var') == 1
  save('NK_RA16_results.mat', 'dataset_info', '-append');
end
if exist('oo_recursive_', 'var') == 1
  save('NK_RA16_results.mat', 'oo_recursive_', '-append');
end


disp(['Total computing time : ' dynsec2hms(toc(tic0)) ]);
disp('Note: 1 warning(s) encountered in the preprocessor')
if ~isempty(lastwarn)
  disp('Note: warning(s) encountered in MATLAB/Octave code')
end
diary off
