%
% Status : main Dynare file
%
% Warning : this file is generated automatically by Dynare
%           from model file (.mod)

if isoctave || matlab_ver_less_than('8.6')
    clear all
else
    clearvars -global
    clear_persistent_variables(fileparts(which('dynare')), false)
end
tic0 = tic;
% Save empty dates and dseries objects in memory.
dates('initialize');
dseries('initialize');
% Define global variables.
global M_ options_ oo_ estim_params_ bayestopt_ dataset_ dataset_info estimation_info ys0_ ex0_
options_ = [];
M_.fname = 'NK_RW97';
M_.dynare_version = '4.5.6';
oo_.dynare_version = '4.5.6';
options_.dynare_version = '4.5.6';
%
% Some global variables initialization
%
global_initialization;
diary off;
diary('NK_RW97.log');
M_.exo_names = 'u_';
M_.exo_names_tex = 'u\_';
M_.exo_names_long = 'u_';
M_.exo_names = char(M_.exo_names, 'interest_');
M_.exo_names_tex = char(M_.exo_names_tex, 'interest\_');
M_.exo_names_long = char(M_.exo_names_long, 'interest_');
M_.exo_names = char(M_.exo_names, 'fiscal_');
M_.exo_names_tex = char(M_.exo_names_tex, 'fiscal\_');
M_.exo_names_long = char(M_.exo_names_long, 'fiscal_');
M_.endo_names = 'pi';
M_.endo_names_tex = 'pi';
M_.endo_names_long = 'pi';
M_.endo_names = char(M_.endo_names, 'y');
M_.endo_names_tex = char(M_.endo_names_tex, 'y');
M_.endo_names_long = char(M_.endo_names_long, 'y');
M_.endo_names = char(M_.endo_names, 'ynat');
M_.endo_names_tex = char(M_.endo_names_tex, 'ynat');
M_.endo_names_long = char(M_.endo_names_long, 'ynat');
M_.endo_names = char(M_.endo_names, 'rnat');
M_.endo_names_tex = char(M_.endo_names_tex, 'rnat');
M_.endo_names_long = char(M_.endo_names_long, 'rnat');
M_.endo_names = char(M_.endo_names, 'i');
M_.endo_names_tex = char(M_.endo_names_tex, 'i');
M_.endo_names_long = char(M_.endo_names_long, 'i');
M_.endo_names = char(M_.endo_names, 'x');
M_.endo_names_tex = char(M_.endo_names_tex, 'x');
M_.endo_names_long = char(M_.endo_names_long, 'x');
M_.endo_names = char(M_.endo_names, 'u');
M_.endo_names_tex = char(M_.endo_names_tex, 'u');
M_.endo_names_long = char(M_.endo_names_long, 'u');
M_.endo_names = char(M_.endo_names, 'g');
M_.endo_names_tex = char(M_.endo_names_tex, 'g');
M_.endo_names_long = char(M_.endo_names_long, 'g');
M_.endo_names = char(M_.endo_names, 'g_');
M_.endo_names_tex = char(M_.endo_names_tex, 'g\_');
M_.endo_names_long = char(M_.endo_names_long, 'g_');
M_.endo_names = char(M_.endo_names, 'interest');
M_.endo_names_tex = char(M_.endo_names_tex, 'interest');
M_.endo_names_long = char(M_.endo_names_long, 'interest');
M_.endo_names = char(M_.endo_names, 'inflation');
M_.endo_names_tex = char(M_.endo_names_tex, 'inflation');
M_.endo_names_long = char(M_.endo_names_long, 'inflation');
M_.endo_names = char(M_.endo_names, 'inflationq');
M_.endo_names_tex = char(M_.endo_names_tex, 'inflationq');
M_.endo_names_long = char(M_.endo_names_long, 'inflationq');
M_.endo_names = char(M_.endo_names, 'outputgap');
M_.endo_names_tex = char(M_.endo_names_tex, 'outputgap');
M_.endo_names_long = char(M_.endo_names_long, 'outputgap');
M_.endo_names = char(M_.endo_names, 'output');
M_.endo_names_tex = char(M_.endo_names_tex, 'output');
M_.endo_names_long = char(M_.endo_names_long, 'output');
M_.endo_names = char(M_.endo_names, 'fispol');
M_.endo_names_tex = char(M_.endo_names_tex, 'fispol');
M_.endo_names_long = char(M_.endo_names_long, 'fispol');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_82');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_82');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_82');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_86');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_86');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_86');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_90');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_90');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_90');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_117');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_117');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_117');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_121');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_121');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_121');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_125');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_125');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_125');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_152');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_152');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_152');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_156');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_156');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_156');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_160');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_160');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_160');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_0_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_0\_1');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_0_1');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_0_2');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_0\_2');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_0_2');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_13_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_13\_1');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_13_1');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_13_2');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_13\_2');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_13_2');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_13_3');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_13\_3');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_13_3');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_12_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_12\_1');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_12_1');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_12_2');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_12\_2');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_12_2');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_12_3');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_12\_3');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_12_3');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_9_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_9\_1');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_9_1');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_9_2');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_9\_2');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_9_2');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_9_3');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_9\_3');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_9_3');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_11_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_11\_1');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_11_1');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_11_2');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_11\_2');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_11_2');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_11_3');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_11\_3');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_11_3');
M_.endo_partitions = struct();
M_.param_names = 'cofintintb1';
M_.param_names_tex = 'cofintintb1';
M_.param_names_long = 'cofintintb1';
M_.param_names = char(M_.param_names, 'cofintintb2');
M_.param_names_tex = char(M_.param_names_tex, 'cofintintb2');
M_.param_names_long = char(M_.param_names_long, 'cofintintb2');
M_.param_names = char(M_.param_names, 'cofintintb3');
M_.param_names_tex = char(M_.param_names_tex, 'cofintintb3');
M_.param_names_long = char(M_.param_names_long, 'cofintintb3');
M_.param_names = char(M_.param_names, 'cofintintb4');
M_.param_names_tex = char(M_.param_names_tex, 'cofintintb4');
M_.param_names_long = char(M_.param_names_long, 'cofintintb4');
M_.param_names = char(M_.param_names, 'cofintinf0');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinf0');
M_.param_names_long = char(M_.param_names_long, 'cofintinf0');
M_.param_names = char(M_.param_names, 'cofintinfb1');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinfb1');
M_.param_names_long = char(M_.param_names_long, 'cofintinfb1');
M_.param_names = char(M_.param_names, 'cofintinfb2');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinfb2');
M_.param_names_long = char(M_.param_names_long, 'cofintinfb2');
M_.param_names = char(M_.param_names, 'cofintinfb3');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinfb3');
M_.param_names_long = char(M_.param_names_long, 'cofintinfb3');
M_.param_names = char(M_.param_names, 'cofintinfb4');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinfb4');
M_.param_names_long = char(M_.param_names_long, 'cofintinfb4');
M_.param_names = char(M_.param_names, 'cofintinff1');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinff1');
M_.param_names_long = char(M_.param_names_long, 'cofintinff1');
M_.param_names = char(M_.param_names, 'cofintinff2');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinff2');
M_.param_names_long = char(M_.param_names_long, 'cofintinff2');
M_.param_names = char(M_.param_names, 'cofintinff3');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinff3');
M_.param_names_long = char(M_.param_names_long, 'cofintinff3');
M_.param_names = char(M_.param_names, 'cofintinff4');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinff4');
M_.param_names_long = char(M_.param_names_long, 'cofintinff4');
M_.param_names = char(M_.param_names, 'cofintout');
M_.param_names_tex = char(M_.param_names_tex, 'cofintout');
M_.param_names_long = char(M_.param_names_long, 'cofintout');
M_.param_names = char(M_.param_names, 'cofintoutb1');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutb1');
M_.param_names_long = char(M_.param_names_long, 'cofintoutb1');
M_.param_names = char(M_.param_names, 'cofintoutb2');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutb2');
M_.param_names_long = char(M_.param_names_long, 'cofintoutb2');
M_.param_names = char(M_.param_names, 'cofintoutb3');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutb3');
M_.param_names_long = char(M_.param_names_long, 'cofintoutb3');
M_.param_names = char(M_.param_names, 'cofintoutb4');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutb4');
M_.param_names_long = char(M_.param_names_long, 'cofintoutb4');
M_.param_names = char(M_.param_names, 'cofintoutf1');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutf1');
M_.param_names_long = char(M_.param_names_long, 'cofintoutf1');
M_.param_names = char(M_.param_names, 'cofintoutf2');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutf2');
M_.param_names_long = char(M_.param_names_long, 'cofintoutf2');
M_.param_names = char(M_.param_names, 'cofintoutf3');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutf3');
M_.param_names_long = char(M_.param_names_long, 'cofintoutf3');
M_.param_names = char(M_.param_names, 'cofintoutf4');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutf4');
M_.param_names_long = char(M_.param_names_long, 'cofintoutf4');
M_.param_names = char(M_.param_names, 'cofintoutp');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutp');
M_.param_names_long = char(M_.param_names_long, 'cofintoutp');
M_.param_names = char(M_.param_names, 'cofintoutpb1');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpb1');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpb1');
M_.param_names = char(M_.param_names, 'cofintoutpb2');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpb2');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpb2');
M_.param_names = char(M_.param_names, 'cofintoutpb3');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpb3');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpb3');
M_.param_names = char(M_.param_names, 'cofintoutpb4');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpb4');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpb4');
M_.param_names = char(M_.param_names, 'cofintoutpf1');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpf1');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpf1');
M_.param_names = char(M_.param_names, 'cofintoutpf2');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpf2');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpf2');
M_.param_names = char(M_.param_names, 'cofintoutpf3');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpf3');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpf3');
M_.param_names = char(M_.param_names, 'cofintoutpf4');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpf4');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpf4');
M_.param_names = char(M_.param_names, 'std_r_');
M_.param_names_tex = char(M_.param_names_tex, 'std\_r\_');
M_.param_names_long = char(M_.param_names_long, 'std_r_');
M_.param_names = char(M_.param_names, 'std_r_quart');
M_.param_names_tex = char(M_.param_names_tex, 'std\_r\_quart');
M_.param_names_long = char(M_.param_names_long, 'std_r_quart');
M_.param_names = char(M_.param_names, 'coffispol');
M_.param_names_tex = char(M_.param_names_tex, 'coffispol');
M_.param_names_long = char(M_.param_names_long, 'coffispol');
M_.param_names = char(M_.param_names, 'beta');
M_.param_names_tex = char(M_.param_names_tex, 'beta');
M_.param_names_long = char(M_.param_names_long, 'beta');
M_.param_names = char(M_.param_names, 'sigma');
M_.param_names_tex = char(M_.param_names_tex, 'sigma');
M_.param_names_long = char(M_.param_names_long, 'sigma');
M_.param_names = char(M_.param_names, 'alpha');
M_.param_names_tex = char(M_.param_names_tex, 'alpha');
M_.param_names_long = char(M_.param_names_long, 'alpha');
M_.param_names = char(M_.param_names, 'theta');
M_.param_names_tex = char(M_.param_names_tex, 'theta');
M_.param_names_long = char(M_.param_names_long, 'theta');
M_.param_names = char(M_.param_names, 'omega');
M_.param_names_tex = char(M_.param_names_tex, 'omega');
M_.param_names_long = char(M_.param_names_long, 'omega');
M_.param_names = char(M_.param_names, 'kappa');
M_.param_names_tex = char(M_.param_names_tex, 'kappa');
M_.param_names_long = char(M_.param_names_long, 'kappa');
M_.param_names = char(M_.param_names, 'rhou');
M_.param_names_tex = char(M_.param_names_tex, 'rhou');
M_.param_names_long = char(M_.param_names_long, 'rhou');
M_.param_names = char(M_.param_names, 'rhog');
M_.param_names_tex = char(M_.param_names_tex, 'rhog');
M_.param_names_long = char(M_.param_names_long, 'rhog');
M_.param_names = char(M_.param_names, 'stdinflation_');
M_.param_names_tex = char(M_.param_names_tex, 'stdinflation\_');
M_.param_names_long = char(M_.param_names_long, 'stdinflation_');
M_.param_names = char(M_.param_names, 'stdfiscal_');
M_.param_names_tex = char(M_.param_names_tex, 'stdfiscal\_');
M_.param_names_long = char(M_.param_names_long, 'stdfiscal_');
M_.param_partitions = struct();
M_.exo_det_nbr = 0;
M_.exo_nbr = 3;
M_.endo_nbr = 38;
M_.param_nbr = 44;
M_.orig_endo_nbr = 15;
M_.aux_vars(1).endo_index = 16;
M_.aux_vars(1).type = 0;
M_.aux_vars(2).endo_index = 17;
M_.aux_vars(2).type = 0;
M_.aux_vars(3).endo_index = 18;
M_.aux_vars(3).type = 0;
M_.aux_vars(4).endo_index = 19;
M_.aux_vars(4).type = 0;
M_.aux_vars(5).endo_index = 20;
M_.aux_vars(5).type = 0;
M_.aux_vars(6).endo_index = 21;
M_.aux_vars(6).type = 0;
M_.aux_vars(7).endo_index = 22;
M_.aux_vars(7).type = 0;
M_.aux_vars(8).endo_index = 23;
M_.aux_vars(8).type = 0;
M_.aux_vars(9).endo_index = 24;
M_.aux_vars(9).type = 0;
M_.aux_vars(10).endo_index = 25;
M_.aux_vars(10).type = 1;
M_.aux_vars(10).orig_index = 1;
M_.aux_vars(10).orig_lead_lag = -1;
M_.aux_vars(11).endo_index = 26;
M_.aux_vars(11).type = 1;
M_.aux_vars(11).orig_index = 1;
M_.aux_vars(11).orig_lead_lag = -2;
M_.aux_vars(12).endo_index = 27;
M_.aux_vars(12).type = 1;
M_.aux_vars(12).orig_index = 14;
M_.aux_vars(12).orig_lead_lag = -1;
M_.aux_vars(13).endo_index = 28;
M_.aux_vars(13).type = 1;
M_.aux_vars(13).orig_index = 14;
M_.aux_vars(13).orig_lead_lag = -2;
M_.aux_vars(14).endo_index = 29;
M_.aux_vars(14).type = 1;
M_.aux_vars(14).orig_index = 14;
M_.aux_vars(14).orig_lead_lag = -3;
M_.aux_vars(15).endo_index = 30;
M_.aux_vars(15).type = 1;
M_.aux_vars(15).orig_index = 13;
M_.aux_vars(15).orig_lead_lag = -1;
M_.aux_vars(16).endo_index = 31;
M_.aux_vars(16).type = 1;
M_.aux_vars(16).orig_index = 13;
M_.aux_vars(16).orig_lead_lag = -2;
M_.aux_vars(17).endo_index = 32;
M_.aux_vars(17).type = 1;
M_.aux_vars(17).orig_index = 13;
M_.aux_vars(17).orig_lead_lag = -3;
M_.aux_vars(18).endo_index = 33;
M_.aux_vars(18).type = 1;
M_.aux_vars(18).orig_index = 10;
M_.aux_vars(18).orig_lead_lag = -1;
M_.aux_vars(19).endo_index = 34;
M_.aux_vars(19).type = 1;
M_.aux_vars(19).orig_index = 10;
M_.aux_vars(19).orig_lead_lag = -2;
M_.aux_vars(20).endo_index = 35;
M_.aux_vars(20).type = 1;
M_.aux_vars(20).orig_index = 10;
M_.aux_vars(20).orig_lead_lag = -3;
M_.aux_vars(21).endo_index = 36;
M_.aux_vars(21).type = 1;
M_.aux_vars(21).orig_index = 12;
M_.aux_vars(21).orig_lead_lag = -1;
M_.aux_vars(22).endo_index = 37;
M_.aux_vars(22).type = 1;
M_.aux_vars(22).orig_index = 12;
M_.aux_vars(22).orig_lead_lag = -2;
M_.aux_vars(23).endo_index = 38;
M_.aux_vars(23).type = 1;
M_.aux_vars(23).orig_index = 12;
M_.aux_vars(23).orig_lead_lag = -3;
M_.Sigma_e = zeros(3, 3);
M_.Correlation_matrix = eye(3, 3);
M_.H = 0;
M_.Correlation_matrix_ME = 1;
M_.sigma_e_is_diagonal = 1;
M_.det_shocks = [];
options_.linear = 1;
options_.block=0;
options_.bytecode=0;
options_.use_dll=0;
M_.hessian_eq_zero = 1;
erase_compiled_function('NK_RW97_static');
erase_compiled_function('NK_RW97_dynamic');
M_.orig_eq_nbr = 15;
M_.eq_nbr = 38;
M_.ramsey_eq_nbr = 0;
M_.set_auxiliary_variables = exist(['./' M_.fname '_set_auxiliary_variables.m'], 'file') == 2;
M_.lead_lag_incidence = [
 1 22 60;
 0 23 0;
 0 24 61;
 0 25 0;
 0 26 0;
 0 27 62;
 2 28 0;
 3 29 63;
 0 30 0;
 4 31 0;
 0 32 0;
 5 33 64;
 6 34 65;
 7 35 66;
 0 36 0;
 0 37 67;
 0 38 68;
 0 39 69;
 0 40 70;
 0 41 71;
 0 42 72;
 0 43 73;
 0 44 74;
 0 45 75;
 8 46 0;
 9 47 0;
 10 48 0;
 11 49 0;
 12 50 0;
 13 51 0;
 14 52 0;
 15 53 0;
 16 54 0;
 17 55 0;
 18 56 0;
 19 57 0;
 20 58 0;
 21 59 0;]';
M_.nstatic = 6;
M_.nfwrd   = 11;
M_.npred   = 16;
M_.nboth   = 5;
M_.nsfwrd   = 16;
M_.nspred   = 21;
M_.ndynamic   = 32;
M_.equations_tags = {
};
M_.static_and_dynamic_models_differ = 0;
M_.exo_names_orig_ord = [1:3];
M_.maximum_lag = 1;
M_.maximum_lead = 1;
M_.maximum_endo_lag = 1;
M_.maximum_endo_lead = 1;
oo_.steady_state = zeros(38, 1);
M_.maximum_exo_lag = 0;
M_.maximum_exo_lead = 0;
oo_.exo_steady_state = zeros(3, 1);
M_.params = NaN(44, 1);
M_.NNZDerivatives = [121; 0; -1];
M_.params( 35 ) = 0.9913258983890954;
beta = M_.params( 35 );
M_.params( 36 ) = 6.25;
sigma = M_.params( 36 );
M_.params( 37 ) = 0.66;
alpha = M_.params( 37 );
M_.params( 38 ) = 7.66;
theta = M_.params( 38 );
M_.params( 39 ) = 0.47;
omega = M_.params( 39 );
M_.params( 40 ) = (1-M_.params(37))*(1-M_.params(37)*M_.params(35))/M_.params(37)*(1/M_.params(36)+M_.params(39))/(1+M_.params(39)*M_.params(38));
kappa = M_.params( 40 );
M_.params( 41 ) = 0;
rhou = M_.params( 41 );
M_.params( 43 ) = 0.154;
stdinflation_ = M_.params( 43 );
M_.params( 42 ) = 0.8;
rhog = M_.params( 42 );
M_.params( 44 ) = 1.524;
stdfiscal_ = M_.params( 44 );
thispath = cd;                                                           
cd('..');                                                                
load policy_param.mat;                                                   
for i=1:33                                                               
deep_parameter_name = M_.param_names(i,:);                           
eval(['M_.params(i)  = ' deep_parameter_name ' ;'])                  
end                                                                      
cd(thispath);                                                            
M_.params( 34 ) = 1;
coffispol = M_.params( 34 );
%
% SHOCKS instructions
%
M_.exo_det_length = 0;
M_.Sigma_e(1, 1) = 0.023716;
M_.Sigma_e(3, 3) = 2.322576;
save('NK_RW97_results.mat', 'oo_', 'M_', 'options_');
if exist('estim_params_', 'var') == 1
  save('NK_RW97_results.mat', 'estim_params_', '-append');
end
if exist('bayestopt_', 'var') == 1
  save('NK_RW97_results.mat', 'bayestopt_', '-append');
end
if exist('dataset_', 'var') == 1
  save('NK_RW97_results.mat', 'dataset_', '-append');
end
if exist('estimation_info', 'var') == 1
  save('NK_RW97_results.mat', 'estimation_info', '-append');
end
if exist('dataset_info', 'var') == 1
  save('NK_RW97_results.mat', 'dataset_info', '-append');
end
if exist('oo_recursive_', 'var') == 1
  save('NK_RW97_results.mat', 'oo_recursive_', '-append');
end


disp(['Total computing time : ' dynsec2hms(toc(tic0)) ]);
if ~isempty(lastwarn)
  disp('Note: warning(s) encountered in MATLAB/Octave code')
end
diary off
