%
% Status : main Dynare file 
%
% Warning : this file is generated automatically by Dynare
%           from model file (.mod)

tic;
global M_ oo_ options_ ys0_ ex0_ estimation_info
options_ = [];
M_.fname = 'US_CPS10';
%
% Some global variables initialization
%
global_initialization;
diary off;
diary('US_CPS10.log');
M_.exo_names = 'zs';
M_.exo_names_tex = 'zs';
M_.exo_names_long = 'zs';
M_.exo_names = char(M_.exo_names, 'lambddaps');
M_.exo_names_tex = char(M_.exo_names_tex, 'lambddaps');
M_.exo_names_long = char(M_.exo_names_long, 'lambddaps');
M_.exo_names = char(M_.exo_names, 'bs');
M_.exo_names_tex = char(M_.exo_names_tex, 'bs');
M_.exo_names_long = char(M_.exo_names_long, 'bs');
M_.exo_names = char(M_.exo_names, 'pits');
M_.exo_names_tex = char(M_.exo_names_tex, 'pits');
M_.exo_names_long = char(M_.exo_names_long, 'pits');
M_.exo_names = char(M_.exo_names, 'interest_');
M_.exo_names_tex = char(M_.exo_names_tex, 'interest\_');
M_.exo_names_long = char(M_.exo_names_long, 'interest_');
M_.endo_names = 'p';
M_.endo_names_tex = 'p';
M_.endo_names_long = 'p';
M_.endo_names = char(M_.endo_names, 'y');
M_.endo_names_tex = char(M_.endo_names_tex, 'y');
M_.endo_names_long = char(M_.endo_names_long, 'y');
M_.endo_names = char(M_.endo_names, 'lambdda');
M_.endo_names_tex = char(M_.endo_names_tex, 'lambdda');
M_.endo_names_long = char(M_.endo_names_long, 'lambdda');
M_.endo_names = char(M_.endo_names, 'w');
M_.endo_names_tex = char(M_.endo_names_tex, 'w');
M_.endo_names_long = char(M_.endo_names_long, 'w');
M_.endo_names = char(M_.endo_names, 'R');
M_.endo_names_tex = char(M_.endo_names_tex, 'R');
M_.endo_names_long = char(M_.endo_names_long, 'R');
M_.endo_names = char(M_.endo_names, 'z');
M_.endo_names_tex = char(M_.endo_names_tex, 'z');
M_.endo_names_long = char(M_.endo_names_long, 'z');
M_.endo_names = char(M_.endo_names, 'lambddap');
M_.endo_names_tex = char(M_.endo_names_tex, 'lambddap');
M_.endo_names_long = char(M_.endo_names_long, 'lambddap');
M_.endo_names = char(M_.endo_names, 'b');
M_.endo_names_tex = char(M_.endo_names_tex, 'b');
M_.endo_names_long = char(M_.endo_names_long, 'b');
M_.endo_names = char(M_.endo_names, 'pit');
M_.endo_names_tex = char(M_.endo_names_tex, 'pit');
M_.endo_names_long = char(M_.endo_names_long, 'pit');
M_.endo_names = char(M_.endo_names, 'ystar');
M_.endo_names_tex = char(M_.endo_names_tex, 'ystar');
M_.endo_names_long = char(M_.endo_names_long, 'ystar');
M_.endo_names = char(M_.endo_names, 'lambddastar');
M_.endo_names_tex = char(M_.endo_names_tex, 'lambddastar');
M_.endo_names_long = char(M_.endo_names_long, 'lambddastar');
M_.endo_names = char(M_.endo_names, 'wstar');
M_.endo_names_tex = char(M_.endo_names_tex, 'wstar');
M_.endo_names_long = char(M_.endo_names_long, 'wstar');
M_.endo_names = char(M_.endo_names, 'Rstar');
M_.endo_names_tex = char(M_.endo_names_tex, 'Rstar');
M_.endo_names_long = char(M_.endo_names_long, 'Rstar');
M_.endo_names = char(M_.endo_names, 'interest');
M_.endo_names_tex = char(M_.endo_names_tex, 'interest');
M_.endo_names_long = char(M_.endo_names_long, 'interest');
M_.endo_names = char(M_.endo_names, 'inflation');
M_.endo_names_tex = char(M_.endo_names_tex, 'inflation');
M_.endo_names_long = char(M_.endo_names_long, 'inflation');
M_.endo_names = char(M_.endo_names, 'inflationq');
M_.endo_names_tex = char(M_.endo_names_tex, 'inflationq');
M_.endo_names_long = char(M_.endo_names_long, 'inflationq');
M_.endo_names = char(M_.endo_names, 'outputgap');
M_.endo_names_tex = char(M_.endo_names_tex, 'outputgap');
M_.endo_names_long = char(M_.endo_names_long, 'outputgap');
M_.endo_names = char(M_.endo_names, 'output');
M_.endo_names_tex = char(M_.endo_names_tex, 'output');
M_.endo_names_long = char(M_.endo_names_long, 'output');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_77');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_77');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_77');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_81');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_81');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_81');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_85');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_85');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_85');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_112');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_112');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_112');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_116');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_116');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_116');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_120');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_120');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_120');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_147');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_147');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_147');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_151');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_151');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_151');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_155');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_155');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_155');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_0_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_0\_1');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_0_1');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_0_2');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_0\_2');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_0_2');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_17_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_17\_1');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_17_1');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_17_2');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_17\_2');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_17_2');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_17_3');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_17\_3');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_17_3');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_16_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_16\_1');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_16_1');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_16_2');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_16\_2');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_16_2');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_16_3');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_16\_3');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_16_3');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_13_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_13\_1');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_13_1');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_13_2');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_13\_2');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_13_2');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_13_3');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_13\_3');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_13_3');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_15_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_15\_1');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_15_1');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_15_2');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_15\_2');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_15_2');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_15_3');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_15\_3');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_15_3');
M_.param_names = 'cofintintb1';
M_.param_names_tex = 'cofintintb1';
M_.param_names_long = 'cofintintb1';
M_.param_names = char(M_.param_names, 'cofintintb2');
M_.param_names_tex = char(M_.param_names_tex, 'cofintintb2');
M_.param_names_long = char(M_.param_names_long, 'cofintintb2');
M_.param_names = char(M_.param_names, 'cofintintb3');
M_.param_names_tex = char(M_.param_names_tex, 'cofintintb3');
M_.param_names_long = char(M_.param_names_long, 'cofintintb3');
M_.param_names = char(M_.param_names, 'cofintintb4');
M_.param_names_tex = char(M_.param_names_tex, 'cofintintb4');
M_.param_names_long = char(M_.param_names_long, 'cofintintb4');
M_.param_names = char(M_.param_names, 'cofintinf0');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinf0');
M_.param_names_long = char(M_.param_names_long, 'cofintinf0');
M_.param_names = char(M_.param_names, 'cofintinfb1');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinfb1');
M_.param_names_long = char(M_.param_names_long, 'cofintinfb1');
M_.param_names = char(M_.param_names, 'cofintinfb2');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinfb2');
M_.param_names_long = char(M_.param_names_long, 'cofintinfb2');
M_.param_names = char(M_.param_names, 'cofintinfb3');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinfb3');
M_.param_names_long = char(M_.param_names_long, 'cofintinfb3');
M_.param_names = char(M_.param_names, 'cofintinfb4');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinfb4');
M_.param_names_long = char(M_.param_names_long, 'cofintinfb4');
M_.param_names = char(M_.param_names, 'cofintinff1');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinff1');
M_.param_names_long = char(M_.param_names_long, 'cofintinff1');
M_.param_names = char(M_.param_names, 'cofintinff2');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinff2');
M_.param_names_long = char(M_.param_names_long, 'cofintinff2');
M_.param_names = char(M_.param_names, 'cofintinff3');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinff3');
M_.param_names_long = char(M_.param_names_long, 'cofintinff3');
M_.param_names = char(M_.param_names, 'cofintinff4');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinff4');
M_.param_names_long = char(M_.param_names_long, 'cofintinff4');
M_.param_names = char(M_.param_names, 'cofintout');
M_.param_names_tex = char(M_.param_names_tex, 'cofintout');
M_.param_names_long = char(M_.param_names_long, 'cofintout');
M_.param_names = char(M_.param_names, 'cofintoutb1');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutb1');
M_.param_names_long = char(M_.param_names_long, 'cofintoutb1');
M_.param_names = char(M_.param_names, 'cofintoutb2');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutb2');
M_.param_names_long = char(M_.param_names_long, 'cofintoutb2');
M_.param_names = char(M_.param_names, 'cofintoutb3');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutb3');
M_.param_names_long = char(M_.param_names_long, 'cofintoutb3');
M_.param_names = char(M_.param_names, 'cofintoutb4');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutb4');
M_.param_names_long = char(M_.param_names_long, 'cofintoutb4');
M_.param_names = char(M_.param_names, 'cofintoutf1');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutf1');
M_.param_names_long = char(M_.param_names_long, 'cofintoutf1');
M_.param_names = char(M_.param_names, 'cofintoutf2');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutf2');
M_.param_names_long = char(M_.param_names_long, 'cofintoutf2');
M_.param_names = char(M_.param_names, 'cofintoutf3');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutf3');
M_.param_names_long = char(M_.param_names_long, 'cofintoutf3');
M_.param_names = char(M_.param_names, 'cofintoutf4');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutf4');
M_.param_names_long = char(M_.param_names_long, 'cofintoutf4');
M_.param_names = char(M_.param_names, 'cofintoutp');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutp');
M_.param_names_long = char(M_.param_names_long, 'cofintoutp');
M_.param_names = char(M_.param_names, 'cofintoutpb1');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpb1');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpb1');
M_.param_names = char(M_.param_names, 'cofintoutpb2');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpb2');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpb2');
M_.param_names = char(M_.param_names, 'cofintoutpb3');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpb3');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpb3');
M_.param_names = char(M_.param_names, 'cofintoutpb4');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpb4');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpb4');
M_.param_names = char(M_.param_names, 'cofintoutpf1');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpf1');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpf1');
M_.param_names = char(M_.param_names, 'cofintoutpf2');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpf2');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpf2');
M_.param_names = char(M_.param_names, 'cofintoutpf3');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpf3');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpf3');
M_.param_names = char(M_.param_names, 'cofintoutpf4');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpf4');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpf4');
M_.param_names = char(M_.param_names, 'std_r_');
M_.param_names_tex = char(M_.param_names_tex, 'std\_r\_');
M_.param_names_long = char(M_.param_names_long, 'std_r_');
M_.param_names = char(M_.param_names, 'std_r_quart');
M_.param_names_tex = char(M_.param_names_tex, 'std\_r\_quart');
M_.param_names_long = char(M_.param_names_long, 'std_r_quart');
M_.param_names = char(M_.param_names, 'coffispol');
M_.param_names_tex = char(M_.param_names_tex, 'coffispol');
M_.param_names_long = char(M_.param_names_long, 'coffispol');
M_.param_names = char(M_.param_names, 'niu');
M_.param_names_tex = char(M_.param_names_tex, 'niu');
M_.param_names_long = char(M_.param_names_long, 'niu');
M_.param_names = char(M_.param_names, 'lambddapss');
M_.param_names_tex = char(M_.param_names_tex, 'lambddapss');
M_.param_names_long = char(M_.param_names_long, 'lambddapss');
M_.param_names = char(M_.param_names, 'iotap');
M_.param_names_tex = char(M_.param_names_tex, 'iotap');
M_.param_names_long = char(M_.param_names_long, 'iotap');
M_.param_names = char(M_.param_names, 'gamma100');
M_.param_names_tex = char(M_.param_names_tex, 'gamma100');
M_.param_names_long = char(M_.param_names_long, 'gamma100');
M_.param_names = char(M_.param_names, 'pss100');
M_.param_names_tex = char(M_.param_names_tex, 'pss100');
M_.param_names_long = char(M_.param_names_long, 'pss100');
M_.param_names = char(M_.param_names, 'Fbeta');
M_.param_names_tex = char(M_.param_names_tex, 'Fbeta');
M_.param_names_long = char(M_.param_names_long, 'Fbeta');
M_.param_names = char(M_.param_names, 'hparam');
M_.param_names_tex = char(M_.param_names_tex, 'hparam');
M_.param_names_long = char(M_.param_names_long, 'hparam');
M_.param_names = char(M_.param_names, 'xip');
M_.param_names_tex = char(M_.param_names_tex, 'xip');
M_.param_names_long = char(M_.param_names_long, 'xip');
M_.param_names = char(M_.param_names, 'rhoz');
M_.param_names_tex = char(M_.param_names_tex, 'rhoz');
M_.param_names_long = char(M_.param_names_long, 'rhoz');
M_.param_names = char(M_.param_names, 'rholambddap');
M_.param_names_tex = char(M_.param_names_tex, 'rholambddap');
M_.param_names_long = char(M_.param_names_long, 'rholambddap');
M_.param_names = char(M_.param_names, 'rhob');
M_.param_names_tex = char(M_.param_names_tex, 'rhob');
M_.param_names_long = char(M_.param_names_long, 'rhob');
M_.param_names = char(M_.param_names, 'sdz');
M_.param_names_tex = char(M_.param_names_tex, 'sdz');
M_.param_names_long = char(M_.param_names_long, 'sdz');
M_.param_names = char(M_.param_names, 'sdlambddap');
M_.param_names_tex = char(M_.param_names_tex, 'sdlambddap');
M_.param_names_long = char(M_.param_names_long, 'sdlambddap');
M_.param_names = char(M_.param_names, 'sdb');
M_.param_names_tex = char(M_.param_names_tex, 'sdb');
M_.param_names_long = char(M_.param_names_long, 'sdb');
M_.param_names = char(M_.param_names, 'gamma');
M_.param_names_tex = char(M_.param_names_tex, 'gamma');
M_.param_names_long = char(M_.param_names_long, 'gamma');
M_.param_names = char(M_.param_names, 'betta');
M_.param_names_tex = char(M_.param_names_tex, 'betta');
M_.param_names_long = char(M_.param_names_long, 'betta');
M_.param_names = char(M_.param_names, 'rss');
M_.param_names_tex = char(M_.param_names_tex, 'rss');
M_.param_names_long = char(M_.param_names_long, 'rss');
M_.param_names = char(M_.param_names, 'rss100');
M_.param_names_tex = char(M_.param_names_tex, 'rss100');
M_.param_names_long = char(M_.param_names_long, 'rss100');
M_.param_names = char(M_.param_names, 'expg');
M_.param_names_tex = char(M_.param_names_tex, 'expg');
M_.param_names_long = char(M_.param_names_long, 'expg');
M_.param_names = char(M_.param_names, 'rhopit');
M_.param_names_tex = char(M_.param_names_tex, 'rhopit');
M_.param_names_long = char(M_.param_names_long, 'rhopit');
M_.param_names = char(M_.param_names, 'sdpit');
M_.param_names_tex = char(M_.param_names_tex, 'sdpit');
M_.param_names_long = char(M_.param_names_long, 'sdpit');
M_.exo_det_nbr = 0;
M_.exo_nbr = 5;
M_.endo_nbr = 41;
M_.param_nbr = 55;
M_.orig_endo_nbr = 18;
M_.aux_vars(1).endo_index = 19;
M_.aux_vars(1).type = 0;
M_.aux_vars(2).endo_index = 20;
M_.aux_vars(2).type = 0;
M_.aux_vars(3).endo_index = 21;
M_.aux_vars(3).type = 0;
M_.aux_vars(4).endo_index = 22;
M_.aux_vars(4).type = 0;
M_.aux_vars(5).endo_index = 23;
M_.aux_vars(5).type = 0;
M_.aux_vars(6).endo_index = 24;
M_.aux_vars(6).type = 0;
M_.aux_vars(7).endo_index = 25;
M_.aux_vars(7).type = 0;
M_.aux_vars(8).endo_index = 26;
M_.aux_vars(8).type = 0;
M_.aux_vars(9).endo_index = 27;
M_.aux_vars(9).type = 0;
M_.aux_vars(10).endo_index = 28;
M_.aux_vars(10).type = 1;
M_.aux_vars(10).orig_index = 1;
M_.aux_vars(10).orig_lead_lag = -1;
M_.aux_vars(11).endo_index = 29;
M_.aux_vars(11).type = 1;
M_.aux_vars(11).orig_index = 1;
M_.aux_vars(11).orig_lead_lag = -2;
M_.aux_vars(12).endo_index = 30;
M_.aux_vars(12).type = 1;
M_.aux_vars(12).orig_index = 18;
M_.aux_vars(12).orig_lead_lag = -1;
M_.aux_vars(13).endo_index = 31;
M_.aux_vars(13).type = 1;
M_.aux_vars(13).orig_index = 18;
M_.aux_vars(13).orig_lead_lag = -2;
M_.aux_vars(14).endo_index = 32;
M_.aux_vars(14).type = 1;
M_.aux_vars(14).orig_index = 18;
M_.aux_vars(14).orig_lead_lag = -3;
M_.aux_vars(15).endo_index = 33;
M_.aux_vars(15).type = 1;
M_.aux_vars(15).orig_index = 17;
M_.aux_vars(15).orig_lead_lag = -1;
M_.aux_vars(16).endo_index = 34;
M_.aux_vars(16).type = 1;
M_.aux_vars(16).orig_index = 17;
M_.aux_vars(16).orig_lead_lag = -2;
M_.aux_vars(17).endo_index = 35;
M_.aux_vars(17).type = 1;
M_.aux_vars(17).orig_index = 17;
M_.aux_vars(17).orig_lead_lag = -3;
M_.aux_vars(18).endo_index = 36;
M_.aux_vars(18).type = 1;
M_.aux_vars(18).orig_index = 14;
M_.aux_vars(18).orig_lead_lag = -1;
M_.aux_vars(19).endo_index = 37;
M_.aux_vars(19).type = 1;
M_.aux_vars(19).orig_index = 14;
M_.aux_vars(19).orig_lead_lag = -2;
M_.aux_vars(20).endo_index = 38;
M_.aux_vars(20).type = 1;
M_.aux_vars(20).orig_index = 14;
M_.aux_vars(20).orig_lead_lag = -3;
M_.aux_vars(21).endo_index = 39;
M_.aux_vars(21).type = 1;
M_.aux_vars(21).orig_index = 16;
M_.aux_vars(21).orig_lead_lag = -1;
M_.aux_vars(22).endo_index = 40;
M_.aux_vars(22).type = 1;
M_.aux_vars(22).orig_index = 16;
M_.aux_vars(22).orig_lead_lag = -2;
M_.aux_vars(23).endo_index = 41;
M_.aux_vars(23).type = 1;
M_.aux_vars(23).orig_index = 16;
M_.aux_vars(23).orig_lead_lag = -3;
M_.Sigma_e = zeros(5, 5);
M_.Correlation_matrix = eye(5, 5);
M_.H = 0;
M_.Correlation_matrix_ME = 1;
M_.sigma_e_is_diagonal = 1;
options_.linear = 1;
options_.block=0;
options_.bytecode=0;
options_.use_dll=0;
erase_compiled_function('US_CPS10_static');
erase_compiled_function('US_CPS10_dynamic');
M_.lead_lag_incidence = [
 1 26 67;
 2 27 68;
 0 28 69;
 0 29 0;
 0 30 0;
 3 31 0;
 4 32 0;
 5 33 0;
 6 34 0;
 7 35 70;
 0 36 71;
 0 37 0;
 0 38 0;
 8 39 0;
 0 40 0;
 9 41 72;
 10 42 73;
 11 43 74;
 0 44 75;
 0 45 76;
 0 46 77;
 0 47 78;
 0 48 79;
 0 49 80;
 0 50 81;
 0 51 82;
 0 52 83;
 12 53 0;
 13 54 0;
 14 55 0;
 15 56 0;
 16 57 0;
 17 58 0;
 18 59 0;
 19 60 0;
 20 61 0;
 21 62 0;
 22 63 0;
 23 64 0;
 24 65 0;
 25 66 0;]';
M_.nstatic = 5;
M_.nfwrd   = 11;
M_.npred   = 19;
M_.nboth   = 6;
M_.nsfwrd   = 17;
M_.nspred   = 25;
M_.ndynamic   = 36;
M_.equations_tags = {
};
M_.static_and_dynamic_models_differ = 0;
M_.exo_names_orig_ord = [1:5];
M_.maximum_lag = 1;
M_.maximum_lead = 1;
M_.maximum_endo_lag = 1;
M_.maximum_endo_lead = 1;
oo_.steady_state = zeros(41, 1);
M_.maximum_exo_lag = 0;
M_.maximum_exo_lead = 0;
oo_.exo_steady_state = zeros(5, 1);
M_.params = NaN(55, 1);
M_.NNZDerivatives = zeros(3, 1);
M_.NNZDerivatives(1) = 141;
M_.NNZDerivatives(2) = 0;
M_.NNZDerivatives(3) = -1;
M_.params( 35 ) = 2;
niu = M_.params( 35 );
M_.params( 36 ) = 0.1;
lambddapss = M_.params( 36 );
M_.params( 37 ) = 0;
iotap = M_.params( 37 );
M_.params( 54 ) = 0.995;
rhopit = M_.params( 54 );
M_.params( 38 ) = 0.484;
gamma100 = M_.params( 38 );
M_.params( 39 ) = 0.516;
pss100 = M_.params( 39 );
M_.params( 40 ) = 0.255;
Fbeta = M_.params( 40 );
M_.params( 41 ) = 0.526;
hparam = M_.params( 41 );
M_.params( 42 ) = 0.800;
xip = M_.params( 42 );
M_.params( 43 ) = 0.297;
rhoz = M_.params( 43 );
M_.params( 44 ) = 0.255;
rholambddap = M_.params( 44 );
M_.params( 45 ) = 0.876;
rhob = M_.params( 45 );
M_.params( 46 ) = 0.493;
sdz = M_.params( 46 );
M_.params( 47 ) = 0.126;
sdlambddap = M_.params( 47 );
M_.params( 55 ) = 0.049;
sdpit = M_.params( 55 );
M_.params( 48 ) = 2.429;
sdb = M_.params( 48 );
M_.params( 49 ) = M_.params(38)/100;
gamma = M_.params( 49 );
M_.params( 50 ) = 100/(100+M_.params(40));
betta = M_.params( 50 );
M_.params( 51 ) = exp(M_.params(49))/M_.params(50)-1;
rss = M_.params( 51 );
M_.params( 52 ) = 100*M_.params(51);
rss100 = M_.params( 52 );
M_.params( 53 ) = exp(M_.params(49));
expg = M_.params( 53 );
thispath = cd;                                                           
cd('..');                                                                
load policy_param.mat;                                                   
for i=1:33                                                               
deep_parameter_name = M_.param_names(i,:);                           
eval(['M_.params(i)  = ' deep_parameter_name ' ;'])                  
end                                                                      
cd(thispath);       
%
% SHOCKS instructions
%
make_ex_;
M_.exo_det_length = 0;
M_.Sigma_e(1, 1) = M_.params(46)^2;
M_.Sigma_e(2, 2) = M_.params(47)^2;
M_.Sigma_e(3, 3) = M_.params(48)^2;
M_.Sigma_e(4, 4) = 1;
save('US_CPS10_results.mat', 'oo_', 'M_', 'options_');
if exist('estim_params_', 'var') == 1
  save('US_CPS10_results.mat', 'estim_params_', '-append');
end
if exist('bayestopt_', 'var') == 1
  save('US_CPS10_results.mat', 'bayestopt_', '-append');
end
if exist('dataset_', 'var') == 1
  save('US_CPS10_results.mat', 'dataset_', '-append');
end
if exist('estimation_info', 'var') == 1
  save('US_CPS10_results.mat', 'estimation_info', '-append');
end


disp(['Total computing time : ' dynsec2hms(toc) ]);
if ~isempty(lastwarn)
  disp('Note: warning(s) encountered in MATLAB/Octave code')
end
diary off
