%
% Status : main Dynare file
%
% Warning : this file is generated automatically by Dynare
%           from model file (.mod)

if isoctave || matlab_ver_less_than('8.6')
    clear all
else
    clearvars -global
    clear_persistent_variables(fileparts(which('dynare')), false)
end
tic0 = tic;
% Save empty dates and dseries objects in memory.
dates('initialize');
dseries('initialize');
% Define global variables.
global M_ options_ oo_ estim_params_ bayestopt_ dataset_ dataset_info estimation_info ys0_ ex0_
options_ = [];
M_.fname = 'US_VMDno';
M_.dynare_version = '4.5.6';
oo_.dynare_version = '4.5.6';
options_.dynare_version = '4.5.6';
%
% Some global variables initialization
%
global_initialization;
diary off;
diary('US_VMDno.log');
M_.exo_names = 'interest_';
M_.exo_names_tex = 'interest\_';
M_.exo_names_long = 'interest_';
M_.endo_names = 'piU';
M_.endo_names_tex = 'piU';
M_.endo_names_long = 'piU';
M_.endo_names = char(M_.endo_names, 'iU');
M_.endo_names_tex = char(M_.endo_names_tex, 'iU');
M_.endo_names_long = char(M_.endo_names_long, 'iU');
M_.endo_names = char(M_.endo_names, 'omegabarSU');
M_.endo_names_tex = char(M_.endo_names_tex, 'omegabarSU');
M_.endo_names_long = char(M_.endo_names_long, 'omegabarSU');
M_.endo_names = char(M_.endo_names, 'RkSXU');
M_.endo_names_tex = char(M_.endo_names_tex, 'RkSXU');
M_.endo_names_long = char(M_.endo_names_long, 'RkSXU');
M_.endo_names = char(M_.endo_names, 'nSU');
M_.endo_names_tex = char(M_.endo_names_tex, 'nSU');
M_.endo_names_long = char(M_.endo_names_long, 'nSU');
M_.endo_names = char(M_.endo_names, 'qU');
M_.endo_names_tex = char(M_.endo_names_tex, 'qU');
M_.endo_names_long = char(M_.endo_names_long, 'qU');
M_.endo_names = char(M_.endo_names, 'cU');
M_.endo_names_tex = char(M_.endo_names_tex, 'cU');
M_.endo_names_long = char(M_.endo_names_long, 'cU');
M_.endo_names = char(M_.endo_names, 'wU');
M_.endo_names_tex = char(M_.endo_names_tex, 'wU');
M_.endo_names_long = char(M_.endo_names_long, 'wU');
M_.endo_names = char(M_.endo_names, 'rkSU');
M_.endo_names_tex = char(M_.endo_names_tex, 'rkSU');
M_.endo_names_long = char(M_.endo_names_long, 'rkSU');
M_.endo_names = char(M_.endo_names, 'kbarBU');
M_.endo_names_tex = char(M_.endo_names_tex, 'kbarBU');
M_.endo_names_long = char(M_.endo_names_long, 'kbarBU');
M_.endo_names = char(M_.endo_names, 'hU');
M_.endo_names_tex = char(M_.endo_names_tex, 'hU');
M_.endo_names_long = char(M_.endo_names_long, 'hU');
M_.endo_names = char(M_.endo_names, 'kbarSU');
M_.endo_names_tex = char(M_.endo_names_tex, 'kbarSU');
M_.endo_names_long = char(M_.endo_names_long, 'kbarSU');
M_.endo_names = char(M_.endo_names, 'ReXU');
M_.endo_names_tex = char(M_.endo_names_tex, 'ReXU');
M_.endo_names_long = char(M_.endo_names_long, 'ReXU');
M_.endo_names = char(M_.endo_names, 'FpXU');
M_.endo_names_tex = char(M_.endo_names_tex, 'FpXU');
M_.endo_names_long = char(M_.endo_names_long, 'FpXU');
M_.endo_names = char(M_.endo_names, 'FwXU');
M_.endo_names_tex = char(M_.endo_names_tex, 'FwXU');
M_.endo_names_long = char(M_.endo_names_long, 'FwXU');
M_.endo_names = char(M_.endo_names, 'RcouponXU');
M_.endo_names_tex = char(M_.endo_names_tex, 'RcouponXU');
M_.endo_names_long = char(M_.endo_names_long, 'RcouponXU');
M_.endo_names = char(M_.endo_names, 'uSU');
M_.endo_names_tex = char(M_.endo_names_tex, 'uSU');
M_.endo_names_long = char(M_.endo_names_long, 'uSU');
M_.endo_names = char(M_.endo_names, 'uBU');
M_.endo_names_tex = char(M_.endo_names_tex, 'uBU');
M_.endo_names_long = char(M_.endo_names_long, 'uBU');
M_.endo_names = char(M_.endo_names, 'KwXU');
M_.endo_names_tex = char(M_.endo_names_tex, 'KwXU');
M_.endo_names_long = char(M_.endo_names_long, 'KwXU');
M_.endo_names = char(M_.endo_names, 'KpXU');
M_.endo_names_tex = char(M_.endo_names_tex, 'KpXU');
M_.endo_names_long = char(M_.endo_names_long, 'KpXU');
M_.endo_names = char(M_.endo_names, 'chiU');
M_.endo_names_tex = char(M_.endo_names_tex, 'chiU');
M_.endo_names_long = char(M_.endo_names_long, 'chiU');
M_.endo_names = char(M_.endo_names, 'KtotU');
M_.endo_names_tex = char(M_.endo_names_tex, 'KtotU');
M_.endo_names_long = char(M_.endo_names_long, 'KtotU');
M_.endo_names = char(M_.endo_names, 'YU');
M_.endo_names_tex = char(M_.endo_names_tex, 'YU');
M_.endo_names_long = char(M_.endo_names_long, 'YU');
M_.endo_names = char(M_.endo_names, 'eps_analystU');
M_.endo_names_tex = char(M_.endo_names_tex, 'eps\_analystU');
M_.endo_names_long = char(M_.endo_names_long, 'eps_analystU');
M_.endo_names = char(M_.endo_names, 'eps_couponU');
M_.endo_names_tex = char(M_.endo_names_tex, 'eps\_couponU');
M_.endo_names_long = char(M_.endo_names_long, 'eps_couponU');
M_.endo_names = char(M_.endo_names, 'RanalystXU');
M_.endo_names_tex = char(M_.endo_names_tex, 'RanalystXU');
M_.endo_names_long = char(M_.endo_names_long, 'RanalystXU');
M_.endo_names = char(M_.endo_names, 'nBU');
M_.endo_names_tex = char(M_.endo_names_tex, 'nBU');
M_.endo_names_long = char(M_.endo_names_long, 'nBU');
M_.endo_names = char(M_.endo_names, 'stockcapitalU');
M_.endo_names_tex = char(M_.endo_names_tex, 'stockcapitalU');
M_.endo_names_long = char(M_.endo_names_long, 'stockcapitalU');
M_.endo_names = char(M_.endo_names, 'ntotU');
M_.endo_names_tex = char(M_.endo_names_tex, 'ntotU');
M_.endo_names_long = char(M_.endo_names_long, 'ntotU');
M_.endo_names = char(M_.endo_names, 'RkBXU');
M_.endo_names_tex = char(M_.endo_names_tex, 'RkBXU');
M_.endo_names_long = char(M_.endo_names_long, 'RkBXU');
M_.endo_names = char(M_.endo_names, 'btotAU');
M_.endo_names_tex = char(M_.endo_names_tex, 'btotAU');
M_.endo_names_long = char(M_.endo_names_long, 'btotAU');
M_.endo_names = char(M_.endo_names, 'btotBU');
M_.endo_names_tex = char(M_.endo_names_tex, 'btotBU');
M_.endo_names_long = char(M_.endo_names_long, 'btotBU');
M_.endo_names = char(M_.endo_names, 'btotSU');
M_.endo_names_tex = char(M_.endo_names_tex, 'btotSU');
M_.endo_names_long = char(M_.endo_names_long, 'btotSU');
M_.endo_names = char(M_.endo_names, 'levAU');
M_.endo_names_tex = char(M_.endo_names_tex, 'levAU');
M_.endo_names_long = char(M_.endo_names_long, 'levAU');
M_.endo_names = char(M_.endo_names, 'levBU');
M_.endo_names_tex = char(M_.endo_names_tex, 'levBU');
M_.endo_names_long = char(M_.endo_names_long, 'levBU');
M_.endo_names = char(M_.endo_names, 'levSU');
M_.endo_names_tex = char(M_.endo_names_tex, 'levSU');
M_.endo_names_long = char(M_.endo_names_long, 'levSU');
M_.endo_names = char(M_.endo_names, 'CostFinancingSU');
M_.endo_names_tex = char(M_.endo_names_tex, 'CostFinancingSU');
M_.endo_names_long = char(M_.endo_names_long, 'CostFinancingSU');
M_.endo_names = char(M_.endo_names, 'SpreadU');
M_.endo_names_tex = char(M_.endo_names_tex, 'SpreadU');
M_.endo_names_long = char(M_.endo_names_long, 'SpreadU');
M_.endo_names = char(M_.endo_names, 'lambdanU');
M_.endo_names_tex = char(M_.endo_names_tex, 'lambdanU');
M_.endo_names_long = char(M_.endo_names_long, 'lambdanU');
M_.endo_names = char(M_.endo_names, 'PextSU');
M_.endo_names_tex = char(M_.endo_names_tex, 'PextSU');
M_.endo_names_long = char(M_.endo_names_long, 'PextSU');
M_.endo_names = char(M_.endo_names, 'piflexU');
M_.endo_names_tex = char(M_.endo_names_tex, 'piflexU');
M_.endo_names_long = char(M_.endo_names_long, 'piflexU');
M_.endo_names = char(M_.endo_names, 'iflexU');
M_.endo_names_tex = char(M_.endo_names_tex, 'iflexU');
M_.endo_names_long = char(M_.endo_names_long, 'iflexU');
M_.endo_names = char(M_.endo_names, 'omegabarSflexU');
M_.endo_names_tex = char(M_.endo_names_tex, 'omegabarSflexU');
M_.endo_names_long = char(M_.endo_names_long, 'omegabarSflexU');
M_.endo_names = char(M_.endo_names, 'RkSXflexU');
M_.endo_names_tex = char(M_.endo_names_tex, 'RkSXflexU');
M_.endo_names_long = char(M_.endo_names_long, 'RkSXflexU');
M_.endo_names = char(M_.endo_names, 'nSflexU');
M_.endo_names_tex = char(M_.endo_names_tex, 'nSflexU');
M_.endo_names_long = char(M_.endo_names_long, 'nSflexU');
M_.endo_names = char(M_.endo_names, 'qflexU');
M_.endo_names_tex = char(M_.endo_names_tex, 'qflexU');
M_.endo_names_long = char(M_.endo_names_long, 'qflexU');
M_.endo_names = char(M_.endo_names, 'cflexU');
M_.endo_names_tex = char(M_.endo_names_tex, 'cflexU');
M_.endo_names_long = char(M_.endo_names_long, 'cflexU');
M_.endo_names = char(M_.endo_names, 'wflexU');
M_.endo_names_tex = char(M_.endo_names_tex, 'wflexU');
M_.endo_names_long = char(M_.endo_names_long, 'wflexU');
M_.endo_names = char(M_.endo_names, 'rkSflexU');
M_.endo_names_tex = char(M_.endo_names_tex, 'rkSflexU');
M_.endo_names_long = char(M_.endo_names_long, 'rkSflexU');
M_.endo_names = char(M_.endo_names, 'kbarBflexU');
M_.endo_names_tex = char(M_.endo_names_tex, 'kbarBflexU');
M_.endo_names_long = char(M_.endo_names_long, 'kbarBflexU');
M_.endo_names = char(M_.endo_names, 'hflexU');
M_.endo_names_tex = char(M_.endo_names_tex, 'hflexU');
M_.endo_names_long = char(M_.endo_names_long, 'hflexU');
M_.endo_names = char(M_.endo_names, 'kbarSflexU');
M_.endo_names_tex = char(M_.endo_names_tex, 'kbarSflexU');
M_.endo_names_long = char(M_.endo_names_long, 'kbarSflexU');
M_.endo_names = char(M_.endo_names, 'ReXflexU');
M_.endo_names_tex = char(M_.endo_names_tex, 'ReXflexU');
M_.endo_names_long = char(M_.endo_names_long, 'ReXflexU');
M_.endo_names = char(M_.endo_names, 'FpXflexU');
M_.endo_names_tex = char(M_.endo_names_tex, 'FpXflexU');
M_.endo_names_long = char(M_.endo_names_long, 'FpXflexU');
M_.endo_names = char(M_.endo_names, 'FwXflexU');
M_.endo_names_tex = char(M_.endo_names_tex, 'FwXflexU');
M_.endo_names_long = char(M_.endo_names_long, 'FwXflexU');
M_.endo_names = char(M_.endo_names, 'RcouponXflexU');
M_.endo_names_tex = char(M_.endo_names_tex, 'RcouponXflexU');
M_.endo_names_long = char(M_.endo_names_long, 'RcouponXflexU');
M_.endo_names = char(M_.endo_names, 'uSflexU');
M_.endo_names_tex = char(M_.endo_names_tex, 'uSflexU');
M_.endo_names_long = char(M_.endo_names_long, 'uSflexU');
M_.endo_names = char(M_.endo_names, 'uBflexU');
M_.endo_names_tex = char(M_.endo_names_tex, 'uBflexU');
M_.endo_names_long = char(M_.endo_names_long, 'uBflexU');
M_.endo_names = char(M_.endo_names, 'KwXflexU');
M_.endo_names_tex = char(M_.endo_names_tex, 'KwXflexU');
M_.endo_names_long = char(M_.endo_names_long, 'KwXflexU');
M_.endo_names = char(M_.endo_names, 'KpXflexU');
M_.endo_names_tex = char(M_.endo_names_tex, 'KpXflexU');
M_.endo_names_long = char(M_.endo_names_long, 'KpXflexU');
M_.endo_names = char(M_.endo_names, 'chiflexU');
M_.endo_names_tex = char(M_.endo_names_tex, 'chiflexU');
M_.endo_names_long = char(M_.endo_names_long, 'chiflexU');
M_.endo_names = char(M_.endo_names, 'KtotflexU');
M_.endo_names_tex = char(M_.endo_names_tex, 'KtotflexU');
M_.endo_names_long = char(M_.endo_names_long, 'KtotflexU');
M_.endo_names = char(M_.endo_names, 'YflexU');
M_.endo_names_tex = char(M_.endo_names_tex, 'YflexU');
M_.endo_names_long = char(M_.endo_names_long, 'YflexU');
M_.endo_names = char(M_.endo_names, 'eps_analystflexU');
M_.endo_names_tex = char(M_.endo_names_tex, 'eps\_analystflexU');
M_.endo_names_long = char(M_.endo_names_long, 'eps_analystflexU');
M_.endo_names = char(M_.endo_names, 'eps_couponflexU');
M_.endo_names_tex = char(M_.endo_names_tex, 'eps\_couponflexU');
M_.endo_names_long = char(M_.endo_names_long, 'eps_couponflexU');
M_.endo_names = char(M_.endo_names, 'RanalystXflexU');
M_.endo_names_tex = char(M_.endo_names_tex, 'RanalystXflexU');
M_.endo_names_long = char(M_.endo_names_long, 'RanalystXflexU');
M_.endo_names = char(M_.endo_names, 'nBflexU');
M_.endo_names_tex = char(M_.endo_names_tex, 'nBflexU');
M_.endo_names_long = char(M_.endo_names_long, 'nBflexU');
M_.endo_names = char(M_.endo_names, 'stockcapitalflexU');
M_.endo_names_tex = char(M_.endo_names_tex, 'stockcapitalflexU');
M_.endo_names_long = char(M_.endo_names_long, 'stockcapitalflexU');
M_.endo_names = char(M_.endo_names, 'ntotflexU');
M_.endo_names_tex = char(M_.endo_names_tex, 'ntotflexU');
M_.endo_names_long = char(M_.endo_names_long, 'ntotflexU');
M_.endo_names = char(M_.endo_names, 'RkBXflexU');
M_.endo_names_tex = char(M_.endo_names_tex, 'RkBXflexU');
M_.endo_names_long = char(M_.endo_names_long, 'RkBXflexU');
M_.endo_names = char(M_.endo_names, 'btotAflexU');
M_.endo_names_tex = char(M_.endo_names_tex, 'btotAflexU');
M_.endo_names_long = char(M_.endo_names_long, 'btotAflexU');
M_.endo_names = char(M_.endo_names, 'btotBflexU');
M_.endo_names_tex = char(M_.endo_names_tex, 'btotBflexU');
M_.endo_names_long = char(M_.endo_names_long, 'btotBflexU');
M_.endo_names = char(M_.endo_names, 'btotSflexU');
M_.endo_names_tex = char(M_.endo_names_tex, 'btotSflexU');
M_.endo_names_long = char(M_.endo_names_long, 'btotSflexU');
M_.endo_names = char(M_.endo_names, 'levAflexU');
M_.endo_names_tex = char(M_.endo_names_tex, 'levAflexU');
M_.endo_names_long = char(M_.endo_names_long, 'levAflexU');
M_.endo_names = char(M_.endo_names, 'levBflexU');
M_.endo_names_tex = char(M_.endo_names_tex, 'levBflexU');
M_.endo_names_long = char(M_.endo_names_long, 'levBflexU');
M_.endo_names = char(M_.endo_names, 'levSflexU');
M_.endo_names_tex = char(M_.endo_names_tex, 'levSflexU');
M_.endo_names_long = char(M_.endo_names_long, 'levSflexU');
M_.endo_names = char(M_.endo_names, 'CostFinancingSflexU');
M_.endo_names_tex = char(M_.endo_names_tex, 'CostFinancingSflexU');
M_.endo_names_long = char(M_.endo_names_long, 'CostFinancingSflexU');
M_.endo_names = char(M_.endo_names, 'SpreadflexU');
M_.endo_names_tex = char(M_.endo_names_tex, 'SpreadflexU');
M_.endo_names_long = char(M_.endo_names_long, 'SpreadflexU');
M_.endo_names = char(M_.endo_names, 'lambdanflexU');
M_.endo_names_tex = char(M_.endo_names_tex, 'lambdanflexU');
M_.endo_names_long = char(M_.endo_names_long, 'lambdanflexU');
M_.endo_names = char(M_.endo_names, 'PextSflexU');
M_.endo_names_tex = char(M_.endo_names_tex, 'PextSflexU');
M_.endo_names_long = char(M_.endo_names_long, 'PextSflexU');
M_.endo_names = char(M_.endo_names, 'interest');
M_.endo_names_tex = char(M_.endo_names_tex, 'interest');
M_.endo_names_long = char(M_.endo_names_long, 'interest');
M_.endo_names = char(M_.endo_names, 'inflation');
M_.endo_names_tex = char(M_.endo_names_tex, 'inflation');
M_.endo_names_long = char(M_.endo_names_long, 'inflation');
M_.endo_names = char(M_.endo_names, 'inflationq');
M_.endo_names_tex = char(M_.endo_names_tex, 'inflationq');
M_.endo_names_long = char(M_.endo_names_long, 'inflationq');
M_.endo_names = char(M_.endo_names, 'outputgap');
M_.endo_names_tex = char(M_.endo_names_tex, 'outputgap');
M_.endo_names_long = char(M_.endo_names_long, 'outputgap');
M_.endo_names = char(M_.endo_names, 'output');
M_.endo_names_tex = char(M_.endo_names_tex, 'output');
M_.endo_names_long = char(M_.endo_names_long, 'output');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_93');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_93');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_93');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_97');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_97');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_97');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_101');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_101');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_101');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_128');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_128');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_128');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_132');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_132');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_132');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_136');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_136');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_136');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_163');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_163');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_163');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_167');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_167');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_167');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_171');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_171');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_171');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_82_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_82\_1');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_82_1');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_82_2');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_82\_2');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_82_2');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_84_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_84\_1');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_84_1');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_84_2');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_84\_2');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_84_2');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_84_3');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_84\_3');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_84_3');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_83_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_83\_1');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_83_1');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_83_2');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_83\_2');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_83_2');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_83_3');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_83\_3');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_83_3');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_80_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_80\_1');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_80_1');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_80_2');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_80\_2');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_80_2');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_80_3');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_80\_3');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_80_3');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_82_3');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_82\_3');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_82_3');
M_.endo_partitions = struct();
M_.param_names = 'KtotUU';
M_.param_names_tex = 'KtotUU';
M_.param_names_long = 'KtotUU';
M_.param_names = char(M_.param_names, 'ntotUU');
M_.param_names_tex = char(M_.param_names_tex, 'ntotUU');
M_.param_names_long = char(M_.param_names_long, 'ntotUU');
M_.param_names = char(M_.param_names, 'KwXUU');
M_.param_names_tex = char(M_.param_names_tex, 'KwXUU');
M_.param_names_long = char(M_.param_names_long, 'KwXUU');
M_.param_names = char(M_.param_names, 'KpXUU');
M_.param_names_tex = char(M_.param_names_tex, 'KpXUU');
M_.param_names_long = char(M_.param_names_long, 'KpXUU');
M_.param_names = char(M_.param_names, 'RcouponXUU');
M_.param_names_tex = char(M_.param_names_tex, 'RcouponXUU');
M_.param_names_long = char(M_.param_names_long, 'RcouponXUU');
M_.param_names = char(M_.param_names, 'eps_couponUU');
M_.param_names_tex = char(M_.param_names_tex, 'eps\_couponUU');
M_.param_names_long = char(M_.param_names_long, 'eps_couponUU');
M_.param_names = char(M_.param_names, 'levBUU');
M_.param_names_tex = char(M_.param_names_tex, 'levBUU');
M_.param_names_long = char(M_.param_names_long, 'levBUU');
M_.param_names = char(M_.param_names, 'btotBUU');
M_.param_names_tex = char(M_.param_names_tex, 'btotBUU');
M_.param_names_long = char(M_.param_names_long, 'btotBUU');
M_.param_names = char(M_.param_names, 'btotSUU');
M_.param_names_tex = char(M_.param_names_tex, 'btotSUU');
M_.param_names_long = char(M_.param_names_long, 'btotSUU');
M_.param_names = char(M_.param_names, 'levSUU');
M_.param_names_tex = char(M_.param_names_tex, 'levSUU');
M_.param_names_long = char(M_.param_names_long, 'levSUU');
M_.param_names = char(M_.param_names, 'piUU');
M_.param_names_tex = char(M_.param_names_tex, 'piUU');
M_.param_names_long = char(M_.param_names_long, 'piUU');
M_.param_names = char(M_.param_names, 'sUU');
M_.param_names_tex = char(M_.param_names_tex, 'sUU');
M_.param_names_long = char(M_.param_names_long, 'sUU');
M_.param_names = char(M_.param_names, 'rkSUU');
M_.param_names_tex = char(M_.param_names_tex, 'rkSUU');
M_.param_names_long = char(M_.param_names_long, 'rkSUU');
M_.param_names = char(M_.param_names, 'rkBUU');
M_.param_names_tex = char(M_.param_names_tex, 'rkBUU');
M_.param_names_long = char(M_.param_names_long, 'rkBUU');
M_.param_names = char(M_.param_names, 'iUU');
M_.param_names_tex = char(M_.param_names_tex, 'iUU');
M_.param_names_long = char(M_.param_names_long, 'iUU');
M_.param_names = char(M_.param_names, 'uSUU');
M_.param_names_tex = char(M_.param_names_tex, 'uSUU');
M_.param_names_long = char(M_.param_names_long, 'uSUU');
M_.param_names = char(M_.param_names, 'uBUU');
M_.param_names_tex = char(M_.param_names_tex, 'uBUU');
M_.param_names_long = char(M_.param_names_long, 'uBUU');
M_.param_names = char(M_.param_names, 'omegabarSUU');
M_.param_names_tex = char(M_.param_names_tex, 'omegabarSUU');
M_.param_names_long = char(M_.param_names_long, 'omegabarSUU');
M_.param_names = char(M_.param_names, 'RkSXUU');
M_.param_names_tex = char(M_.param_names_tex, 'RkSXUU');
M_.param_names_long = char(M_.param_names_long, 'RkSXUU');
M_.param_names = char(M_.param_names, 'RkBXUU');
M_.param_names_tex = char(M_.param_names_tex, 'RkBXUU');
M_.param_names_long = char(M_.param_names_long, 'RkBXUU');
M_.param_names = char(M_.param_names, 'nSUU');
M_.param_names_tex = char(M_.param_names_tex, 'nSUU');
M_.param_names_long = char(M_.param_names_long, 'nSUU');
M_.param_names = char(M_.param_names, 'nBUU');
M_.param_names_tex = char(M_.param_names_tex, 'nBUU');
M_.param_names_long = char(M_.param_names_long, 'nBUU');
M_.param_names = char(M_.param_names, 'qUU');
M_.param_names_tex = char(M_.param_names_tex, 'qUU');
M_.param_names_long = char(M_.param_names_long, 'qUU');
M_.param_names = char(M_.param_names, 'lambdanUU');
M_.param_names_tex = char(M_.param_names_tex, 'lambdanUU');
M_.param_names_long = char(M_.param_names_long, 'lambdanUU');
M_.param_names = char(M_.param_names, 'cUU');
M_.param_names_tex = char(M_.param_names_tex, 'cUU');
M_.param_names_long = char(M_.param_names_long, 'cUU');
M_.param_names = char(M_.param_names, 'wUU');
M_.param_names_tex = char(M_.param_names_tex, 'wUU');
M_.param_names_long = char(M_.param_names_long, 'wUU');
M_.param_names = char(M_.param_names, 'hUU');
M_.param_names_tex = char(M_.param_names_tex, 'hUU');
M_.param_names_long = char(M_.param_names_long, 'hUU');
M_.param_names = char(M_.param_names, 'kbarSUU');
M_.param_names_tex = char(M_.param_names_tex, 'kbarSUU');
M_.param_names_long = char(M_.param_names_long, 'kbarSUU');
M_.param_names = char(M_.param_names, 'kbarBUU');
M_.param_names_tex = char(M_.param_names_tex, 'kbarBUU');
M_.param_names_long = char(M_.param_names_long, 'kbarBUU');
M_.param_names = char(M_.param_names, 'ReXUU');
M_.param_names_tex = char(M_.param_names_tex, 'ReXUU');
M_.param_names_long = char(M_.param_names_long, 'ReXUU');
M_.param_names = char(M_.param_names, 'FpXUU');
M_.param_names_tex = char(M_.param_names_tex, 'FpXUU');
M_.param_names_long = char(M_.param_names_long, 'FpXUU');
M_.param_names = char(M_.param_names, 'FwXUU');
M_.param_names_tex = char(M_.param_names_tex, 'FwXUU');
M_.param_names_long = char(M_.param_names_long, 'FwXUU');
M_.param_names = char(M_.param_names, 'PextSUU');
M_.param_names_tex = char(M_.param_names_tex, 'PextSUU');
M_.param_names_long = char(M_.param_names_long, 'PextSUU');
M_.param_names = char(M_.param_names, 'YUU');
M_.param_names_tex = char(M_.param_names_tex, 'YUU');
M_.param_names_long = char(M_.param_names_long, 'YUU');
M_.param_names = char(M_.param_names, 'eps_analystUU');
M_.param_names_tex = char(M_.param_names_tex, 'eps\_analystUU');
M_.param_names_long = char(M_.param_names_long, 'eps_analystUU');
M_.param_names = char(M_.param_names, 'RanalystXUU');
M_.param_names_tex = char(M_.param_names_tex, 'RanalystXUU');
M_.param_names_long = char(M_.param_names_long, 'RanalystXUU');
M_.param_names = char(M_.param_names, 'chiUU');
M_.param_names_tex = char(M_.param_names_tex, 'chiUU');
M_.param_names_long = char(M_.param_names_long, 'chiUU');
M_.param_names = char(M_.param_names, 'eps_biasedUU');
M_.param_names_tex = char(M_.param_names_tex, 'eps\_biasedUU');
M_.param_names_long = char(M_.param_names_long, 'eps_biasedUU');
M_.param_names = char(M_.param_names, 'RbiasedXUU');
M_.param_names_tex = char(M_.param_names_tex, 'RbiasedXUU');
M_.param_names_long = char(M_.param_names_long, 'RbiasedXUU');
M_.param_names = char(M_.param_names, 'gammaSUU');
M_.param_names_tex = char(M_.param_names_tex, 'gammaSUU');
M_.param_names_long = char(M_.param_names_long, 'gammaSUU');
M_.param_names = char(M_.param_names, 'gammaBUU');
M_.param_names_tex = char(M_.param_names_tex, 'gammaBUU');
M_.param_names_long = char(M_.param_names_long, 'gammaBUU');
M_.param_names = char(M_.param_names, 'sigmaSUU');
M_.param_names_tex = char(M_.param_names_tex, 'sigmaSUU');
M_.param_names_long = char(M_.param_names_long, 'sigmaSUU');
M_.param_names = char(M_.param_names, 'sigmaCUU');
M_.param_names_tex = char(M_.param_names_tex, 'sigmaCUU');
M_.param_names_long = char(M_.param_names_long, 'sigmaCUU');
M_.param_names = char(M_.param_names, 'levAUU');
M_.param_names_tex = char(M_.param_names_tex, 'levAUU');
M_.param_names_long = char(M_.param_names_long, 'levAUU');
M_.param_names = char(M_.param_names, 'btotAUU');
M_.param_names_tex = char(M_.param_names_tex, 'btotAUU');
M_.param_names_long = char(M_.param_names_long, 'btotAUU');
M_.param_names = char(M_.param_names, 'CostFinancingSUU');
M_.param_names_tex = char(M_.param_names_tex, 'CostFinancingSUU');
M_.param_names_long = char(M_.param_names_long, 'CostFinancingSUU');
M_.param_names = char(M_.param_names, 'SpreadUU');
M_.param_names_tex = char(M_.param_names_tex, 'SpreadUU');
M_.param_names_long = char(M_.param_names_long, 'SpreadUU');
M_.param_names = char(M_.param_names, 'stockcapitalUU');
M_.param_names_tex = char(M_.param_names_tex, 'stockcapitalUU');
M_.param_names_long = char(M_.param_names_long, 'stockcapitalUU');
M_.param_names = char(M_.param_names, 'gUU');
M_.param_names_tex = char(M_.param_names_tex, 'gUU');
M_.param_names_long = char(M_.param_names_long, 'gUU');
M_.param_names = char(M_.param_names, 'lambdawUU');
M_.param_names_tex = char(M_.param_names_tex, 'lambdawUU');
M_.param_names_long = char(M_.param_names_long, 'lambdawUU');
M_.param_names = char(M_.param_names, 'sigmaLXUU');
M_.param_names_tex = char(M_.param_names_tex, 'sigmaLXUU');
M_.param_names_long = char(M_.param_names_long, 'sigmaLXUU');
M_.param_names = char(M_.param_names, 'betaUU');
M_.param_names_tex = char(M_.param_names_tex, 'betaUU');
M_.param_names_long = char(M_.param_names_long, 'betaUU');
M_.param_names = char(M_.param_names, 'xiwUU');
M_.param_names_tex = char(M_.param_names_tex, 'xiwUU');
M_.param_names_long = char(M_.param_names_long, 'xiwUU');
M_.param_names = char(M_.param_names, 'bUU');
M_.param_names_tex = char(M_.param_names_tex, 'bUU');
M_.param_names_long = char(M_.param_names_long, 'bUU');
M_.param_names = char(M_.param_names, 'lambdafUU');
M_.param_names_tex = char(M_.param_names_tex, 'lambdafUU');
M_.param_names_long = char(M_.param_names_long, 'lambdafUU');
M_.param_names = char(M_.param_names, 'psiLXUU');
M_.param_names_tex = char(M_.param_names_tex, 'psiLXUU');
M_.param_names_long = char(M_.param_names_long, 'psiLXUU');
M_.param_names = char(M_.param_names, 'iotaw1UU');
M_.param_names_tex = char(M_.param_names_tex, 'iotaw1UU');
M_.param_names_long = char(M_.param_names_long, 'iotaw1UU');
M_.param_names = char(M_.param_names, 'weSUU');
M_.param_names_tex = char(M_.param_names_tex, 'weSUU');
M_.param_names_long = char(M_.param_names_long, 'weSUU');
M_.param_names = char(M_.param_names, 'weBUU');
M_.param_names_tex = char(M_.param_names_tex, 'weBUU');
M_.param_names_long = char(M_.param_names_long, 'weBUU');
M_.param_names = char(M_.param_names, 'sigmaaSUU');
M_.param_names_tex = char(M_.param_names_tex, 'sigmaaSUU');
M_.param_names_long = char(M_.param_names_long, 'sigmaaSUU');
M_.param_names = char(M_.param_names, 'sigmaaBUU');
M_.param_names_tex = char(M_.param_names_tex, 'sigmaaBUU');
M_.param_names_long = char(M_.param_names_long, 'sigmaaBUU');
M_.param_names = char(M_.param_names, 'SdouprXUU');
M_.param_names_tex = char(M_.param_names_tex, 'SdouprXUU');
M_.param_names_long = char(M_.param_names_long, 'SdouprXUU');
M_.param_names = char(M_.param_names, 'alphaUU');
M_.param_names_tex = char(M_.param_names_tex, 'alphaUU');
M_.param_names_long = char(M_.param_names_long, 'alphaUU');
M_.param_names = char(M_.param_names, 'deltaUU');
M_.param_names_tex = char(M_.param_names_tex, 'deltaUU');
M_.param_names_long = char(M_.param_names_long, 'deltaUU');
M_.param_names = char(M_.param_names, 'xipUU');
M_.param_names_tex = char(M_.param_names_tex, 'xipUU');
M_.param_names_long = char(M_.param_names_long, 'xipUU');
M_.param_names = char(M_.param_names, 'iota1UU');
M_.param_names_tex = char(M_.param_names_tex, 'iota1UU');
M_.param_names_long = char(M_.param_names_long, 'iota1UU');
M_.param_names = char(M_.param_names, 'etagUU');
M_.param_names_tex = char(M_.param_names_tex, 'etagUU');
M_.param_names_long = char(M_.param_names_long, 'etagUU');
M_.param_names = char(M_.param_names, 'muUU');
M_.param_names_tex = char(M_.param_names_tex, 'muUU');
M_.param_names_long = char(M_.param_names_long, 'muUU');
M_.param_names = char(M_.param_names, 'aptilUU');
M_.param_names_tex = char(M_.param_names_tex, 'aptilUU');
M_.param_names_long = char(M_.param_names_long, 'aptilUU');
M_.param_names = char(M_.param_names, 'aytilUU');
M_.param_names_tex = char(M_.param_names_tex, 'aytilUU');
M_.param_names_long = char(M_.param_names_long, 'aytilUU');
M_.param_names = char(M_.param_names, 'rhotilUU');
M_.param_names_tex = char(M_.param_names_tex, 'rhotilUU');
M_.param_names_long = char(M_.param_names_long, 'rhotilUU');
M_.param_names = char(M_.param_names, 'rhoEIS');
M_.param_names_tex = char(M_.param_names_tex, 'rhoEIS');
M_.param_names_long = char(M_.param_names_long, 'rhoEIS');
M_.param_names = char(M_.param_names, 'etaSE');
M_.param_names_tex = char(M_.param_names_tex, 'etaSE');
M_.param_names_long = char(M_.param_names_long, 'etaSE');
M_.param_names = char(M_.param_names, 'rho_chi');
M_.param_names_tex = char(M_.param_names_tex, 'rho\_chi');
M_.param_names_long = char(M_.param_names_long, 'rho_chi');
M_.param_names = char(M_.param_names, 'OMEGA');
M_.param_names_tex = char(M_.param_names_tex, 'OMEGA');
M_.param_names_long = char(M_.param_names_long, 'OMEGA');
M_.param_names = char(M_.param_names, 'alpha3');
M_.param_names_tex = char(M_.param_names_tex, 'alpha3');
M_.param_names_long = char(M_.param_names_long, 'alpha3');
M_.param_names = char(M_.param_names, 'alpha4');
M_.param_names_tex = char(M_.param_names_tex, 'alpha4');
M_.param_names_long = char(M_.param_names_long, 'alpha4');
M_.param_names = char(M_.param_names, 'KwXflexUU');
M_.param_names_tex = char(M_.param_names_tex, 'KwXflexUU');
M_.param_names_long = char(M_.param_names_long, 'KwXflexUU');
M_.param_names = char(M_.param_names, 'KpXflexUU');
M_.param_names_tex = char(M_.param_names_tex, 'KpXflexUU');
M_.param_names_long = char(M_.param_names_long, 'KpXflexUU');
M_.param_names = char(M_.param_names, 'FpXflexUU');
M_.param_names_tex = char(M_.param_names_tex, 'FpXflexUU');
M_.param_names_long = char(M_.param_names_long, 'FpXflexUU');
M_.param_names = char(M_.param_names, 'FwXflexUU');
M_.param_names_tex = char(M_.param_names_tex, 'FwXflexUU');
M_.param_names_long = char(M_.param_names_long, 'FwXflexUU');
M_.param_names = char(M_.param_names, 'cofintintb1');
M_.param_names_tex = char(M_.param_names_tex, 'cofintintb1');
M_.param_names_long = char(M_.param_names_long, 'cofintintb1');
M_.param_names = char(M_.param_names, 'cofintintb2');
M_.param_names_tex = char(M_.param_names_tex, 'cofintintb2');
M_.param_names_long = char(M_.param_names_long, 'cofintintb2');
M_.param_names = char(M_.param_names, 'cofintintb3');
M_.param_names_tex = char(M_.param_names_tex, 'cofintintb3');
M_.param_names_long = char(M_.param_names_long, 'cofintintb3');
M_.param_names = char(M_.param_names, 'cofintintb4');
M_.param_names_tex = char(M_.param_names_tex, 'cofintintb4');
M_.param_names_long = char(M_.param_names_long, 'cofintintb4');
M_.param_names = char(M_.param_names, 'cofintinf0');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinf0');
M_.param_names_long = char(M_.param_names_long, 'cofintinf0');
M_.param_names = char(M_.param_names, 'cofintinfb1');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinfb1');
M_.param_names_long = char(M_.param_names_long, 'cofintinfb1');
M_.param_names = char(M_.param_names, 'cofintinfb2');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinfb2');
M_.param_names_long = char(M_.param_names_long, 'cofintinfb2');
M_.param_names = char(M_.param_names, 'cofintinfb3');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinfb3');
M_.param_names_long = char(M_.param_names_long, 'cofintinfb3');
M_.param_names = char(M_.param_names, 'cofintinfb4');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinfb4');
M_.param_names_long = char(M_.param_names_long, 'cofintinfb4');
M_.param_names = char(M_.param_names, 'cofintinff1');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinff1');
M_.param_names_long = char(M_.param_names_long, 'cofintinff1');
M_.param_names = char(M_.param_names, 'cofintinff2');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinff2');
M_.param_names_long = char(M_.param_names_long, 'cofintinff2');
M_.param_names = char(M_.param_names, 'cofintinff3');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinff3');
M_.param_names_long = char(M_.param_names_long, 'cofintinff3');
M_.param_names = char(M_.param_names, 'cofintinff4');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinff4');
M_.param_names_long = char(M_.param_names_long, 'cofintinff4');
M_.param_names = char(M_.param_names, 'cofintout');
M_.param_names_tex = char(M_.param_names_tex, 'cofintout');
M_.param_names_long = char(M_.param_names_long, 'cofintout');
M_.param_names = char(M_.param_names, 'cofintoutb1');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutb1');
M_.param_names_long = char(M_.param_names_long, 'cofintoutb1');
M_.param_names = char(M_.param_names, 'cofintoutb2');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutb2');
M_.param_names_long = char(M_.param_names_long, 'cofintoutb2');
M_.param_names = char(M_.param_names, 'cofintoutb3');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutb3');
M_.param_names_long = char(M_.param_names_long, 'cofintoutb3');
M_.param_names = char(M_.param_names, 'cofintoutb4');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutb4');
M_.param_names_long = char(M_.param_names_long, 'cofintoutb4');
M_.param_names = char(M_.param_names, 'cofintoutf1');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutf1');
M_.param_names_long = char(M_.param_names_long, 'cofintoutf1');
M_.param_names = char(M_.param_names, 'cofintoutf2');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutf2');
M_.param_names_long = char(M_.param_names_long, 'cofintoutf2');
M_.param_names = char(M_.param_names, 'cofintoutf3');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutf3');
M_.param_names_long = char(M_.param_names_long, 'cofintoutf3');
M_.param_names = char(M_.param_names, 'cofintoutf4');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutf4');
M_.param_names_long = char(M_.param_names_long, 'cofintoutf4');
M_.param_names = char(M_.param_names, 'cofintoutp');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutp');
M_.param_names_long = char(M_.param_names_long, 'cofintoutp');
M_.param_names = char(M_.param_names, 'cofintoutpb1');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpb1');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpb1');
M_.param_names = char(M_.param_names, 'cofintoutpb2');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpb2');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpb2');
M_.param_names = char(M_.param_names, 'cofintoutpb3');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpb3');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpb3');
M_.param_names = char(M_.param_names, 'cofintoutpb4');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpb4');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpb4');
M_.param_names = char(M_.param_names, 'cofintoutpf1');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpf1');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpf1');
M_.param_names = char(M_.param_names, 'cofintoutpf2');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpf2');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpf2');
M_.param_names = char(M_.param_names, 'cofintoutpf3');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpf3');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpf3');
M_.param_names = char(M_.param_names, 'cofintoutpf4');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpf4');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpf4');
M_.param_names = char(M_.param_names, 'std_r_');
M_.param_names_tex = char(M_.param_names_tex, 'std\_r\_');
M_.param_names_long = char(M_.param_names_long, 'std_r_');
M_.param_names = char(M_.param_names, 'std_r_quart');
M_.param_names_tex = char(M_.param_names_tex, 'std\_r\_quart');
M_.param_names_long = char(M_.param_names_long, 'std_r_quart');
M_.param_partitions = struct();
M_.exo_det_nbr = 0;
M_.exo_nbr = 1;
M_.endo_nbr = 106;
M_.param_nbr = 114;
M_.orig_endo_nbr = 85;
M_.aux_vars(1).endo_index = 86;
M_.aux_vars(1).type = 0;
M_.aux_vars(2).endo_index = 87;
M_.aux_vars(2).type = 0;
M_.aux_vars(3).endo_index = 88;
M_.aux_vars(3).type = 0;
M_.aux_vars(4).endo_index = 89;
M_.aux_vars(4).type = 0;
M_.aux_vars(5).endo_index = 90;
M_.aux_vars(5).type = 0;
M_.aux_vars(6).endo_index = 91;
M_.aux_vars(6).type = 0;
M_.aux_vars(7).endo_index = 92;
M_.aux_vars(7).type = 0;
M_.aux_vars(8).endo_index = 93;
M_.aux_vars(8).type = 0;
M_.aux_vars(9).endo_index = 94;
M_.aux_vars(9).type = 0;
M_.aux_vars(10).endo_index = 95;
M_.aux_vars(10).type = 1;
M_.aux_vars(10).orig_index = 83;
M_.aux_vars(10).orig_lead_lag = -1;
M_.aux_vars(11).endo_index = 96;
M_.aux_vars(11).type = 1;
M_.aux_vars(11).orig_index = 83;
M_.aux_vars(11).orig_lead_lag = -2;
M_.aux_vars(12).endo_index = 97;
M_.aux_vars(12).type = 1;
M_.aux_vars(12).orig_index = 85;
M_.aux_vars(12).orig_lead_lag = -1;
M_.aux_vars(13).endo_index = 98;
M_.aux_vars(13).type = 1;
M_.aux_vars(13).orig_index = 85;
M_.aux_vars(13).orig_lead_lag = -2;
M_.aux_vars(14).endo_index = 99;
M_.aux_vars(14).type = 1;
M_.aux_vars(14).orig_index = 85;
M_.aux_vars(14).orig_lead_lag = -3;
M_.aux_vars(15).endo_index = 100;
M_.aux_vars(15).type = 1;
M_.aux_vars(15).orig_index = 84;
M_.aux_vars(15).orig_lead_lag = -1;
M_.aux_vars(16).endo_index = 101;
M_.aux_vars(16).type = 1;
M_.aux_vars(16).orig_index = 84;
M_.aux_vars(16).orig_lead_lag = -2;
M_.aux_vars(17).endo_index = 102;
M_.aux_vars(17).type = 1;
M_.aux_vars(17).orig_index = 84;
M_.aux_vars(17).orig_lead_lag = -3;
M_.aux_vars(18).endo_index = 103;
M_.aux_vars(18).type = 1;
M_.aux_vars(18).orig_index = 81;
M_.aux_vars(18).orig_lead_lag = -1;
M_.aux_vars(19).endo_index = 104;
M_.aux_vars(19).type = 1;
M_.aux_vars(19).orig_index = 81;
M_.aux_vars(19).orig_lead_lag = -2;
M_.aux_vars(20).endo_index = 105;
M_.aux_vars(20).type = 1;
M_.aux_vars(20).orig_index = 81;
M_.aux_vars(20).orig_lead_lag = -3;
M_.aux_vars(21).endo_index = 106;
M_.aux_vars(21).type = 1;
M_.aux_vars(21).orig_index = 83;
M_.aux_vars(21).orig_lead_lag = -3;
M_.Sigma_e = zeros(1, 1);
M_.Correlation_matrix = eye(1, 1);
M_.H = 0;
M_.Correlation_matrix_ME = 1;
M_.sigma_e_is_diagonal = 1;
M_.det_shocks = [];
options_.block=0;
options_.bytecode=0;
options_.use_dll=0;
M_.hessian_eq_zero = 0;
erase_compiled_function('US_VMDno_static');
erase_compiled_function('US_VMDno_dynamic');
M_.orig_eq_nbr = 85;
M_.eq_nbr = 106;
M_.ramsey_eq_nbr = 0;
M_.set_auxiliary_variables = exist(['./' M_.fname '_set_auxiliary_variables.m'], 'file') == 2;
M_.lead_lag_incidence = [
 1 41 147;
 2 42 148;
 0 43 149;
 0 44 150;
 3 45 0;
 4 46 151;
 5 47 152;
 6 48 153;
 0 49 154;
 7 50 0;
 0 51 0;
 8 52 0;
 9 53 0;
 0 54 155;
 0 55 156;
 10 56 0;
 0 57 157;
 0 58 158;
 0 59 159;
 0 60 160;
 11 61 0;
 0 62 0;
 12 63 0;
 0 64 0;
 0 65 0;
 0 66 0;
 13 67 0;
 0 68 0;
 0 69 0;
 0 70 0;
 0 71 0;
 0 72 0;
 0 73 0;
 0 74 0;
 0 75 0;
 0 76 0;
 0 77 0;
 0 78 0;
 0 79 161;
 0 80 0;
 0 81 162;
 14 82 163;
 0 83 164;
 0 84 165;
 15 85 0;
 16 86 166;
 17 87 167;
 0 88 0;
 0 89 168;
 18 90 0;
 0 91 0;
 19 92 0;
 20 93 0;
 0 94 0;
 0 95 0;
 21 96 0;
 0 97 169;
 0 98 170;
 0 99 0;
 0 100 0;
 22 101 0;
 0 102 0;
 23 103 0;
 0 104 0;
 0 105 0;
 0 106 0;
 24 107 0;
 0 108 0;
 0 109 0;
 0 110 0;
 0 111 0;
 0 112 0;
 0 113 0;
 0 114 0;
 0 115 0;
 0 116 0;
 0 117 0;
 0 118 0;
 0 119 171;
 0 120 0;
 25 121 0;
 0 122 0;
 26 123 172;
 27 124 173;
 28 125 174;
 0 126 175;
 0 127 176;
 0 128 177;
 0 129 178;
 0 130 179;
 0 131 180;
 0 132 181;
 0 133 182;
 0 134 183;
 29 135 0;
 30 136 0;
 31 137 0;
 32 138 0;
 33 139 0;
 34 140 0;
 35 141 0;
 36 142 0;
 37 143 0;
 38 144 0;
 39 145 0;
 40 146 0;]';
M_.nstatic = 40;
M_.nfwrd   = 26;
M_.npred   = 29;
M_.nboth   = 11;
M_.nsfwrd   = 37;
M_.nspred   = 40;
M_.ndynamic   = 66;
M_.equations_tags = {
};
M_.static_and_dynamic_models_differ = 0;
M_.exo_names_orig_ord = [1:1];
M_.maximum_lag = 1;
M_.maximum_lead = 1;
M_.maximum_endo_lag = 1;
M_.maximum_endo_lead = 1;
oo_.steady_state = zeros(106, 1);
M_.maximum_exo_lag = 0;
M_.maximum_exo_lead = 0;
oo_.exo_steady_state = zeros(1, 1);
M_.params = NaN(114, 1);
M_.NNZDerivatives = [484; 1160; -1];
std1_xpU=0.25;
M_.params( 76 ) = 0;
alpha3 = M_.params( 76 );
M_.params( 77 ) = 30000;
alpha4 = M_.params( 77 );
thispath = cd;                                                       
cd('..');                                                            
load policy_param.mat; 
qq=load('policy_param.mat');
for i=1:M_.param_nbr;
name = deblank(M_.param_names(i,:));
if isfield(qq,name);
M_.params(i) = eval(['qq.' name]);
end;
end;                                         
cd(thispath);    
M_.params( 113 ) = 100;
std_r_ = M_.params( 113 );
pp=load('FIMSteadyStateMMB');
for i=1:M_.param_nbr;
name = deblank(M_.param_names(i,:));
if isfield(pp,name);
M_.params(i) = eval(['pp.' name]);
end;
end;
M_.params(76)=alpha3;
M_.params(75)=0;
%
% INITVAL instructions
%
options_.initval_file = 0;
oo_.steady_state( 1 ) = M_.params(11);
oo_.steady_state( 9 ) = M_.params(13);
oo_.steady_state( 2 ) = M_.params(15);
oo_.steady_state( 3 ) = M_.params(18);
oo_.steady_state( 4 ) = M_.params(19);
oo_.steady_state( 5 ) = M_.params(21);
oo_.steady_state( 6 ) = M_.params(23);
oo_.steady_state( 7 ) = M_.params(25);
oo_.steady_state( 8 ) = M_.params(26);
oo_.steady_state( 11 ) = M_.params(27);
oo_.steady_state( 12 ) = M_.params(28);
oo_.steady_state( 10 ) = M_.params(29);
oo_.steady_state( 13 ) = M_.params(30);
oo_.steady_state( 14 ) = M_.params(31);
oo_.steady_state( 15 ) = M_.params(32);
oo_.steady_state( 19 ) = M_.params(3);
oo_.steady_state( 20 ) = M_.params(4);
oo_.steady_state( 16 ) = M_.params(5);
oo_.steady_state( 21 ) = 0;
oo_.steady_state( 22 ) = M_.params(1);
oo_.steady_state( 23 ) = M_.params(34);
oo_.steady_state( 24 ) = M_.params(35);
oo_.steady_state( 25 ) = M_.params(6);
oo_.steady_state( 26 ) = M_.params(36);
oo_.steady_state( 27 ) = M_.params(22);
oo_.steady_state( 28 ) = M_.params(48);
oo_.steady_state( 29 ) = M_.params(2);
oo_.steady_state( 17 ) = M_.params(16);
oo_.steady_state( 18 ) = M_.params(17);
oo_.steady_state( 30 ) = M_.params(20);
oo_.steady_state( 35 ) = M_.params(7);
oo_.steady_state( 36 ) = M_.params(10);
oo_.steady_state( 32 ) = M_.params(8);
oo_.steady_state( 33 ) = M_.params(9);
oo_.steady_state( 34 ) = M_.params(44);
oo_.steady_state( 31 ) = M_.params(45);
oo_.steady_state( 37 ) = M_.params(46);
oo_.steady_state( 38 ) = M_.params(47);
oo_.steady_state( 39 ) = M_.params(24);
oo_.steady_state( 40 ) = M_.params(33);
oo_.steady_state( 41 ) = M_.params(11);
oo_.steady_state( 49 ) = M_.params(13);
oo_.steady_state( 42 ) = M_.params(15);
oo_.steady_state( 43 ) = M_.params(18);
oo_.steady_state( 44 ) = M_.params(19);
oo_.steady_state( 45 ) = M_.params(21);
oo_.steady_state( 46 ) = M_.params(23);
oo_.steady_state( 47 ) = M_.params(25);
oo_.steady_state( 48 ) = M_.params(26);
oo_.steady_state( 51 ) = M_.params(27);
oo_.steady_state( 52 ) = M_.params(28);
oo_.steady_state( 50 ) = M_.params(29);
oo_.steady_state( 53 ) = M_.params(30);
oo_.steady_state( 54 ) = M_.params(80);
oo_.steady_state( 55 ) = M_.params(81);
oo_.steady_state( 59 ) = M_.params(78);
oo_.steady_state( 60 ) = M_.params(79);
oo_.steady_state( 56 ) = M_.params(5);
oo_.steady_state( 61 ) = 0;
oo_.steady_state( 62 ) = M_.params(1);
oo_.steady_state( 63 ) = M_.params(34);
oo_.steady_state( 64 ) = M_.params(35);
oo_.steady_state( 65 ) = M_.params(6);
oo_.steady_state( 66 ) = M_.params(36);
oo_.steady_state( 67 ) = M_.params(22);
oo_.steady_state( 68 ) = M_.params(48);
oo_.steady_state( 69 ) = M_.params(2);
oo_.steady_state( 57 ) = M_.params(16);
oo_.steady_state( 58 ) = M_.params(17);
oo_.steady_state( 70 ) = M_.params(20);
oo_.steady_state( 75 ) = M_.params(7);
oo_.steady_state( 76 ) = M_.params(10);
oo_.steady_state( 72 ) = M_.params(8);
oo_.steady_state( 73 ) = M_.params(9);
oo_.steady_state( 74 ) = M_.params(44);
oo_.steady_state( 71 ) = M_.params(45);
oo_.steady_state( 77 ) = M_.params(46);
oo_.steady_state( 78 ) = M_.params(47);
oo_.steady_state( 79 ) = M_.params(24);
oo_.steady_state( 80 ) = M_.params(33);
oo_.steady_state( 81 ) = 0;
oo_.steady_state( 82 ) = 0;
oo_.steady_state( 83 ) = 0;
oo_.steady_state( 84 ) = 0;
oo_.steady_state( 85 ) = 0;
oo_.steady_state(86)=oo_.steady_state(83);
oo_.steady_state(87)=oo_.steady_state(86);
oo_.steady_state(88)=oo_.steady_state(87);
oo_.steady_state(89)=oo_.steady_state(84);
oo_.steady_state(90)=oo_.steady_state(89);
oo_.steady_state(91)=oo_.steady_state(90);
oo_.steady_state(92)=oo_.steady_state(85);
oo_.steady_state(93)=oo_.steady_state(92);
oo_.steady_state(94)=oo_.steady_state(93);
oo_.steady_state(95)=oo_.steady_state(83);
oo_.steady_state(96)=oo_.steady_state(95);
oo_.steady_state(97)=oo_.steady_state(85);
oo_.steady_state(98)=oo_.steady_state(97);
oo_.steady_state(99)=oo_.steady_state(98);
oo_.steady_state(100)=oo_.steady_state(84);
oo_.steady_state(101)=oo_.steady_state(100);
oo_.steady_state(102)=oo_.steady_state(101);
oo_.steady_state(103)=oo_.steady_state(81);
oo_.steady_state(104)=oo_.steady_state(103);
oo_.steady_state(105)=oo_.steady_state(104);
oo_.steady_state(106)=oo_.steady_state(96);
if M_.exo_nbr > 0
	oo_.exo_simul = ones(M_.maximum_lag,1)*oo_.exo_steady_state';
end
if M_.exo_det_nbr > 0
	oo_.exo_det_simul = ones(M_.maximum_lag,1)*oo_.exo_det_steady_state';
end
%
% SHOCKS instructions
%
M_.exo_det_length = 0;
M_.Sigma_e(1, 1) = (0.01)^2;
save('US_VMDno_results.mat', 'oo_', 'M_', 'options_');
if exist('estim_params_', 'var') == 1
  save('US_VMDno_results.mat', 'estim_params_', '-append');
end
if exist('bayestopt_', 'var') == 1
  save('US_VMDno_results.mat', 'bayestopt_', '-append');
end
if exist('dataset_', 'var') == 1
  save('US_VMDno_results.mat', 'dataset_', '-append');
end
if exist('estimation_info', 'var') == 1
  save('US_VMDno_results.mat', 'estimation_info', '-append');
end
if exist('dataset_info', 'var') == 1
  save('US_VMDno_results.mat', 'dataset_info', '-append');
end
if exist('oo_recursive_', 'var') == 1
  save('US_VMDno_results.mat', 'oo_recursive_', '-append');
end


disp(['Total computing time : ' dynsec2hms(toc(tic0)) ]);
if ~isempty(lastwarn)
  disp('Note: warning(s) encountered in MATLAB/Octave code')
end
diary off
