%
% Status : main Dynare file
%
% Warning : this file is generated automatically by Dynare
%           from model file (.mod)

tic0 = tic;
% Save empty dates and dseries objects in memory.
dates('initialize');
dseries('initialize');
% Define global variables.
global M_ options_ oo_ estim_params_ bayestopt_ dataset_ dataset_info estimation_info ys0_ ex0_
options_ = [];
M_.fname = 'NK_PSV16';
M_.dynare_version = '4.5.4';
oo_.dynare_version = '4.5.4';
options_.dynare_version = '4.5.4';
%
% Some global variables initialization
%
global_initialization;
diary off;
diary('NK_PSV16.log');
M_.exo_names = 'eA';
M_.exo_names_tex = 'eA';
M_.exo_names_long = 'eA';
M_.exo_names = char(M_.exo_names, 'interest_');
M_.exo_names_tex = char(M_.exo_names_tex, 'interest\_');
M_.exo_names_long = char(M_.exo_names_long, 'interest_');
M_.exo_names = char(M_.exo_names, 'fiscal_');
M_.exo_names_tex = char(M_.exo_names_tex, 'fiscal\_');
M_.exo_names_long = char(M_.exo_names_long, 'fiscal_');
M_.endo_names = 'y';
M_.endo_names_tex = 'y';
M_.endo_names_long = 'y';
M_.endo_names = char(M_.endo_names, 'c');
M_.endo_names_tex = char(M_.endo_names_tex, 'c');
M_.endo_names_long = char(M_.endo_names_long, 'c');
M_.endo_names = char(M_.endo_names, 'i');
M_.endo_names_tex = char(M_.endo_names_tex, 'i');
M_.endo_names_long = char(M_.endo_names_long, 'i');
M_.endo_names = char(M_.endo_names, 'g');
M_.endo_names_tex = char(M_.endo_names_tex, 'g');
M_.endo_names_long = char(M_.endo_names_long, 'g');
M_.endo_names = char(M_.endo_names, 'ce');
M_.endo_names_tex = char(M_.endo_names_tex, 'ce');
M_.endo_names_long = char(M_.endo_names_long, 'ce');
M_.endo_names = char(M_.endo_names, 'n');
M_.endo_names_tex = char(M_.endo_names_tex, 'n');
M_.endo_names_long = char(M_.endo_names_long, 'n');
M_.endo_names = char(M_.endo_names, 'rk');
M_.endo_names_tex = char(M_.endo_names_tex, 'rk');
M_.endo_names_long = char(M_.endo_names_long, 'rk');
M_.endo_names = char(M_.endo_names, 'r');
M_.endo_names_tex = char(M_.endo_names_tex, 'r');
M_.endo_names_long = char(M_.endo_names_long, 'r');
M_.endo_names = char(M_.endo_names, 'q');
M_.endo_names_tex = char(M_.endo_names_tex, 'q');
M_.endo_names_long = char(M_.endo_names_long, 'q');
M_.endo_names = char(M_.endo_names, 'k');
M_.endo_names_tex = char(M_.endo_names_tex, 'k');
M_.endo_names_long = char(M_.endo_names_long, 'k');
M_.endo_names = char(M_.endo_names, 'x');
M_.endo_names_tex = char(M_.endo_names_tex, 'x');
M_.endo_names_long = char(M_.endo_names_long, 'x');
M_.endo_names = char(M_.endo_names, 'a');
M_.endo_names_tex = char(M_.endo_names_tex, 'a');
M_.endo_names_long = char(M_.endo_names_long, 'a');
M_.endo_names = char(M_.endo_names, 'h');
M_.endo_names_tex = char(M_.endo_names_tex, 'h');
M_.endo_names_long = char(M_.endo_names_long, 'h');
M_.endo_names = char(M_.endo_names, 'pi');
M_.endo_names_tex = char(M_.endo_names_tex, 'pi');
M_.endo_names_long = char(M_.endo_names_long, 'pi');
M_.endo_names = char(M_.endo_names, 'rn');
M_.endo_names_tex = char(M_.endo_names_tex, 'rn');
M_.endo_names_long = char(M_.endo_names_long, 'rn');
M_.endo_names = char(M_.endo_names, 'qtilde');
M_.endo_names_tex = char(M_.endo_names_tex, 'qtilde');
M_.endo_names_long = char(M_.endo_names_long, 'qtilde');
M_.endo_names = char(M_.endo_names, 'eG');
M_.endo_names_tex = char(M_.endo_names_tex, 'eG');
M_.endo_names_long = char(M_.endo_names_long, 'eG');
M_.endo_names = char(M_.endo_names, 'yf');
M_.endo_names_tex = char(M_.endo_names_tex, 'yf');
M_.endo_names_long = char(M_.endo_names_long, 'yf');
M_.endo_names = char(M_.endo_names, 'kf');
M_.endo_names_tex = char(M_.endo_names_tex, 'kf');
M_.endo_names_long = char(M_.endo_names_long, 'kf');
M_.endo_names = char(M_.endo_names, 'if');
M_.endo_names_tex = char(M_.endo_names_tex, 'if');
M_.endo_names_long = char(M_.endo_names_long, 'if');
M_.endo_names = char(M_.endo_names, 'rf');
M_.endo_names_tex = char(M_.endo_names_tex, 'rf');
M_.endo_names_long = char(M_.endo_names_long, 'rf');
M_.endo_names = char(M_.endo_names, 'rkf');
M_.endo_names_tex = char(M_.endo_names_tex, 'rkf');
M_.endo_names_long = char(M_.endo_names_long, 'rkf');
M_.endo_names = char(M_.endo_names, 'nf');
M_.endo_names_tex = char(M_.endo_names_tex, 'nf');
M_.endo_names_long = char(M_.endo_names_long, 'nf');
M_.endo_names = char(M_.endo_names, 'cf');
M_.endo_names_tex = char(M_.endo_names_tex, 'cf');
M_.endo_names_long = char(M_.endo_names_long, 'cf');
M_.endo_names = char(M_.endo_names, 'cef');
M_.endo_names_tex = char(M_.endo_names_tex, 'cef');
M_.endo_names_long = char(M_.endo_names_long, 'cef');
M_.endo_names = char(M_.endo_names, 'qf');
M_.endo_names_tex = char(M_.endo_names_tex, 'qf');
M_.endo_names_long = char(M_.endo_names_long, 'qf');
M_.endo_names = char(M_.endo_names, 'hf');
M_.endo_names_tex = char(M_.endo_names_tex, 'hf');
M_.endo_names_long = char(M_.endo_names_long, 'hf');
M_.endo_names = char(M_.endo_names, 'qtildef');
M_.endo_names_tex = char(M_.endo_names_tex, 'qtildef');
M_.endo_names_long = char(M_.endo_names_long, 'qtildef');
M_.endo_names = char(M_.endo_names, 'interest');
M_.endo_names_tex = char(M_.endo_names_tex, 'interest');
M_.endo_names_long = char(M_.endo_names_long, 'interest');
M_.endo_names = char(M_.endo_names, 'inflation');
M_.endo_names_tex = char(M_.endo_names_tex, 'inflation');
M_.endo_names_long = char(M_.endo_names_long, 'inflation');
M_.endo_names = char(M_.endo_names, 'inflationq');
M_.endo_names_tex = char(M_.endo_names_tex, 'inflationq');
M_.endo_names_long = char(M_.endo_names_long, 'inflationq');
M_.endo_names = char(M_.endo_names, 'outputgap');
M_.endo_names_tex = char(M_.endo_names_tex, 'outputgap');
M_.endo_names_long = char(M_.endo_names_long, 'outputgap');
M_.endo_names = char(M_.endo_names, 'output');
M_.endo_names_tex = char(M_.endo_names_tex, 'output');
M_.endo_names_long = char(M_.endo_names_long, 'output');
M_.endo_names = char(M_.endo_names, 'fispol');
M_.endo_names_tex = char(M_.endo_names_tex, 'fispol');
M_.endo_names_long = char(M_.endo_names_long, 'fispol');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_80');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_80');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_80');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_84');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_84');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_84');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_88');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_88');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_88');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_115');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_115');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_115');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_119');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_119');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_119');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_123');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_123');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_123');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_150');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_150');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_150');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_154');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_154');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_154');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_158');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_158');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_158');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_13_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_13\_1');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_13_1');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_13_2');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_13\_2');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_13_2');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_32_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_32\_1');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_32_1');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_32_2');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_32\_2');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_32_2');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_32_3');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_32\_3');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_32_3');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_31_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_31\_1');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_31_1');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_31_2');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_31\_2');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_31_2');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_31_3');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_31\_3');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_31_3');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_28_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_28\_1');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_28_1');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_28_2');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_28\_2');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_28_2');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_28_3');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_28\_3');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_28_3');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_30_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_30\_1');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_30_1');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_30_2');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_30\_2');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_30_2');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_30_3');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_30\_3');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_30_3');
M_.endo_partitions = struct();
M_.param_names = 'cofintintb1';
M_.param_names_tex = 'cofintintb1';
M_.param_names_long = 'cofintintb1';
M_.param_names = char(M_.param_names, 'cofintintb2');
M_.param_names_tex = char(M_.param_names_tex, 'cofintintb2');
M_.param_names_long = char(M_.param_names_long, 'cofintintb2');
M_.param_names = char(M_.param_names, 'cofintintb3');
M_.param_names_tex = char(M_.param_names_tex, 'cofintintb3');
M_.param_names_long = char(M_.param_names_long, 'cofintintb3');
M_.param_names = char(M_.param_names, 'cofintintb4');
M_.param_names_tex = char(M_.param_names_tex, 'cofintintb4');
M_.param_names_long = char(M_.param_names_long, 'cofintintb4');
M_.param_names = char(M_.param_names, 'cofintinf0');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinf0');
M_.param_names_long = char(M_.param_names_long, 'cofintinf0');
M_.param_names = char(M_.param_names, 'cofintinfb1');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinfb1');
M_.param_names_long = char(M_.param_names_long, 'cofintinfb1');
M_.param_names = char(M_.param_names, 'cofintinfb2');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinfb2');
M_.param_names_long = char(M_.param_names_long, 'cofintinfb2');
M_.param_names = char(M_.param_names, 'cofintinfb3');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinfb3');
M_.param_names_long = char(M_.param_names_long, 'cofintinfb3');
M_.param_names = char(M_.param_names, 'cofintinfb4');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinfb4');
M_.param_names_long = char(M_.param_names_long, 'cofintinfb4');
M_.param_names = char(M_.param_names, 'cofintinff1');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinff1');
M_.param_names_long = char(M_.param_names_long, 'cofintinff1');
M_.param_names = char(M_.param_names, 'cofintinff2');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinff2');
M_.param_names_long = char(M_.param_names_long, 'cofintinff2');
M_.param_names = char(M_.param_names, 'cofintinff3');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinff3');
M_.param_names_long = char(M_.param_names_long, 'cofintinff3');
M_.param_names = char(M_.param_names, 'cofintinff4');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinff4');
M_.param_names_long = char(M_.param_names_long, 'cofintinff4');
M_.param_names = char(M_.param_names, 'cofintout');
M_.param_names_tex = char(M_.param_names_tex, 'cofintout');
M_.param_names_long = char(M_.param_names_long, 'cofintout');
M_.param_names = char(M_.param_names, 'cofintoutb1');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutb1');
M_.param_names_long = char(M_.param_names_long, 'cofintoutb1');
M_.param_names = char(M_.param_names, 'cofintoutb2');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutb2');
M_.param_names_long = char(M_.param_names_long, 'cofintoutb2');
M_.param_names = char(M_.param_names, 'cofintoutb3');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutb3');
M_.param_names_long = char(M_.param_names_long, 'cofintoutb3');
M_.param_names = char(M_.param_names, 'cofintoutb4');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutb4');
M_.param_names_long = char(M_.param_names_long, 'cofintoutb4');
M_.param_names = char(M_.param_names, 'cofintoutf1');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutf1');
M_.param_names_long = char(M_.param_names_long, 'cofintoutf1');
M_.param_names = char(M_.param_names, 'cofintoutf2');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutf2');
M_.param_names_long = char(M_.param_names_long, 'cofintoutf2');
M_.param_names = char(M_.param_names, 'cofintoutf3');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutf3');
M_.param_names_long = char(M_.param_names_long, 'cofintoutf3');
M_.param_names = char(M_.param_names, 'cofintoutf4');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutf4');
M_.param_names_long = char(M_.param_names_long, 'cofintoutf4');
M_.param_names = char(M_.param_names, 'cofintoutp');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutp');
M_.param_names_long = char(M_.param_names_long, 'cofintoutp');
M_.param_names = char(M_.param_names, 'cofintoutpb1');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpb1');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpb1');
M_.param_names = char(M_.param_names, 'cofintoutpb2');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpb2');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpb2');
M_.param_names = char(M_.param_names, 'cofintoutpb3');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpb3');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpb3');
M_.param_names = char(M_.param_names, 'cofintoutpb4');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpb4');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpb4');
M_.param_names = char(M_.param_names, 'cofintoutpf1');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpf1');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpf1');
M_.param_names = char(M_.param_names, 'cofintoutpf2');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpf2');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpf2');
M_.param_names = char(M_.param_names, 'cofintoutpf3');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpf3');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpf3');
M_.param_names = char(M_.param_names, 'cofintoutpf4');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpf4');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpf4');
M_.param_names = char(M_.param_names, 'std_r_');
M_.param_names_tex = char(M_.param_names_tex, 'std\_r\_');
M_.param_names_long = char(M_.param_names_long, 'std_r_');
M_.param_names = char(M_.param_names, 'std_r_quart');
M_.param_names_tex = char(M_.param_names_tex, 'std\_r\_quart');
M_.param_names_long = char(M_.param_names_long, 'std_r_quart');
M_.param_names = char(M_.param_names, 'coffispol');
M_.param_names_tex = char(M_.param_names_tex, 'coffispol');
M_.param_names_long = char(M_.param_names_long, 'coffispol');
M_.param_names = char(M_.param_names, 'beta');
M_.param_names_tex = char(M_.param_names_tex, 'beta');
M_.param_names_long = char(M_.param_names_long, 'beta');
M_.param_names = char(M_.param_names, 'eta');
M_.param_names_tex = char(M_.param_names_tex, 'eta');
M_.param_names_long = char(M_.param_names_long, 'eta');
M_.param_names = char(M_.param_names, 'alpha');
M_.param_names_tex = char(M_.param_names_tex, 'alpha');
M_.param_names_long = char(M_.param_names_long, 'alpha');
M_.param_names = char(M_.param_names, 'delta');
M_.param_names_tex = char(M_.param_names_tex, 'delta');
M_.param_names_long = char(M_.param_names_long, 'delta');
M_.param_names = char(M_.param_names, 'omega');
M_.param_names_tex = char(M_.param_names_tex, 'omega');
M_.param_names_long = char(M_.param_names_long, 'omega');
M_.param_names = char(M_.param_names, 'eps');
M_.param_names_tex = char(M_.param_names_tex, 'eps');
M_.param_names_long = char(M_.param_names_long, 'eps');
M_.param_names = char(M_.param_names, 'G_Y');
M_.param_names_tex = char(M_.param_names_tex, 'G\_Y');
M_.param_names_long = char(M_.param_names_long, 'G_Y');
M_.param_names = char(M_.param_names, 'C_Y');
M_.param_names_tex = char(M_.param_names_tex, 'C\_Y');
M_.param_names_long = char(M_.param_names_long, 'C_Y');
M_.param_names = char(M_.param_names, 'I_Y');
M_.param_names_tex = char(M_.param_names_tex, 'I\_Y');
M_.param_names_long = char(M_.param_names_long, 'I_Y');
M_.param_names = char(M_.param_names, 'Ce_Y');
M_.param_names_tex = char(M_.param_names_tex, 'Ce\_Y');
M_.param_names_long = char(M_.param_names_long, 'Ce_Y');
M_.param_names = char(M_.param_names, 'Y_N');
M_.param_names_tex = char(M_.param_names_tex, 'Y\_N');
M_.param_names_long = char(M_.param_names_long, 'Y_N');
M_.param_names = char(M_.param_names, 'X');
M_.param_names_tex = char(M_.param_names_tex, 'X');
M_.param_names_long = char(M_.param_names_long, 'X');
M_.param_names = char(M_.param_names, 'rhoA');
M_.param_names_tex = char(M_.param_names_tex, 'rhoA');
M_.param_names_long = char(M_.param_names_long, 'rhoA');
M_.param_names = char(M_.param_names, 'rhoG');
M_.param_names_tex = char(M_.param_names_tex, 'rhoG');
M_.param_names_long = char(M_.param_names_long, 'rhoG');
M_.param_names = char(M_.param_names, 'psi');
M_.param_names_tex = char(M_.param_names_tex, 'psi');
M_.param_names_long = char(M_.param_names_long, 'psi');
M_.param_names = char(M_.param_names, 'K_N');
M_.param_names_tex = char(M_.param_names_tex, 'K\_N');
M_.param_names_long = char(M_.param_names_long, 'K_N');
M_.param_names = char(M_.param_names, 'R');
M_.param_names_tex = char(M_.param_names_tex, 'R');
M_.param_names_long = char(M_.param_names_long, 'R');
M_.param_names = char(M_.param_names, 'gamma');
M_.param_names_tex = char(M_.param_names_tex, 'gamma');
M_.param_names_long = char(M_.param_names_long, 'gamma');
M_.param_names = char(M_.param_names, 'mu');
M_.param_names_tex = char(M_.param_names_tex, 'mu');
M_.param_names_long = char(M_.param_names_long, 'mu');
M_.param_names = char(M_.param_names, 'nu');
M_.param_names_tex = char(M_.param_names_tex, 'nu');
M_.param_names_long = char(M_.param_names_long, 'nu');
M_.param_names = char(M_.param_names, 'theta');
M_.param_names_tex = char(M_.param_names_tex, 'theta');
M_.param_names_long = char(M_.param_names_long, 'theta');
M_.param_names = char(M_.param_names, 'rho');
M_.param_names_tex = char(M_.param_names_tex, 'rho');
M_.param_names_long = char(M_.param_names_long, 'rho');
M_.param_names = char(M_.param_names, 'S');
M_.param_names_tex = char(M_.param_names_tex, 'S');
M_.param_names_long = char(M_.param_names_long, 'S');
M_.param_names = char(M_.param_names, 'kappa');
M_.param_names_tex = char(M_.param_names_tex, 'kappa');
M_.param_names_long = char(M_.param_names_long, 'kappa');
M_.param_partitions = struct();
M_.exo_det_nbr = 0;
M_.exo_nbr = 3;
M_.endo_nbr = 57;
M_.param_nbr = 58;
M_.orig_endo_nbr = 34;
M_.aux_vars(1).endo_index = 35;
M_.aux_vars(1).type = 0;
M_.aux_vars(2).endo_index = 36;
M_.aux_vars(2).type = 0;
M_.aux_vars(3).endo_index = 37;
M_.aux_vars(3).type = 0;
M_.aux_vars(4).endo_index = 38;
M_.aux_vars(4).type = 0;
M_.aux_vars(5).endo_index = 39;
M_.aux_vars(5).type = 0;
M_.aux_vars(6).endo_index = 40;
M_.aux_vars(6).type = 0;
M_.aux_vars(7).endo_index = 41;
M_.aux_vars(7).type = 0;
M_.aux_vars(8).endo_index = 42;
M_.aux_vars(8).type = 0;
M_.aux_vars(9).endo_index = 43;
M_.aux_vars(9).type = 0;
M_.aux_vars(10).endo_index = 44;
M_.aux_vars(10).type = 1;
M_.aux_vars(10).orig_index = 14;
M_.aux_vars(10).orig_lead_lag = -1;
M_.aux_vars(11).endo_index = 45;
M_.aux_vars(11).type = 1;
M_.aux_vars(11).orig_index = 14;
M_.aux_vars(11).orig_lead_lag = -2;
M_.aux_vars(12).endo_index = 46;
M_.aux_vars(12).type = 1;
M_.aux_vars(12).orig_index = 33;
M_.aux_vars(12).orig_lead_lag = -1;
M_.aux_vars(13).endo_index = 47;
M_.aux_vars(13).type = 1;
M_.aux_vars(13).orig_index = 33;
M_.aux_vars(13).orig_lead_lag = -2;
M_.aux_vars(14).endo_index = 48;
M_.aux_vars(14).type = 1;
M_.aux_vars(14).orig_index = 33;
M_.aux_vars(14).orig_lead_lag = -3;
M_.aux_vars(15).endo_index = 49;
M_.aux_vars(15).type = 1;
M_.aux_vars(15).orig_index = 32;
M_.aux_vars(15).orig_lead_lag = -1;
M_.aux_vars(16).endo_index = 50;
M_.aux_vars(16).type = 1;
M_.aux_vars(16).orig_index = 32;
M_.aux_vars(16).orig_lead_lag = -2;
M_.aux_vars(17).endo_index = 51;
M_.aux_vars(17).type = 1;
M_.aux_vars(17).orig_index = 32;
M_.aux_vars(17).orig_lead_lag = -3;
M_.aux_vars(18).endo_index = 52;
M_.aux_vars(18).type = 1;
M_.aux_vars(18).orig_index = 29;
M_.aux_vars(18).orig_lead_lag = -1;
M_.aux_vars(19).endo_index = 53;
M_.aux_vars(19).type = 1;
M_.aux_vars(19).orig_index = 29;
M_.aux_vars(19).orig_lead_lag = -2;
M_.aux_vars(20).endo_index = 54;
M_.aux_vars(20).type = 1;
M_.aux_vars(20).orig_index = 29;
M_.aux_vars(20).orig_lead_lag = -3;
M_.aux_vars(21).endo_index = 55;
M_.aux_vars(21).type = 1;
M_.aux_vars(21).orig_index = 31;
M_.aux_vars(21).orig_lead_lag = -1;
M_.aux_vars(22).endo_index = 56;
M_.aux_vars(22).type = 1;
M_.aux_vars(22).orig_index = 31;
M_.aux_vars(22).orig_lead_lag = -2;
M_.aux_vars(23).endo_index = 57;
M_.aux_vars(23).type = 1;
M_.aux_vars(23).orig_index = 31;
M_.aux_vars(23).orig_lead_lag = -3;
M_.Sigma_e = zeros(3, 3);
M_.Correlation_matrix = eye(3, 3);
M_.H = 0;
M_.Correlation_matrix_ME = 1;
M_.sigma_e_is_diagonal = 1;
M_.det_shocks = [];
options_.block=0;
options_.bytecode=0;
options_.use_dll=0;
M_.hessian_eq_zero = 1;
erase_compiled_function('NK_PSV16_static');
erase_compiled_function('NK_PSV16_dynamic');
M_.orig_eq_nbr = 34;
M_.eq_nbr = 57;
M_.ramsey_eq_nbr = 0;
M_.set_auxiliary_variables = exist(['./' M_.fname '_set_auxiliary_variables.m'], 'file') == 2;
M_.lead_lag_incidence = [
 0 30 0;
 0 31 87;
 0 32 0;
 1 33 0;
 0 34 0;
 2 35 0;
 0 36 88;
 3 37 0;
 4 38 0;
 5 39 0;
 0 40 0;
 6 41 0;
 0 42 0;
 7 43 89;
 0 44 0;
 0 45 0;
 0 46 0;
 0 47 0;
 8 48 0;
 0 49 0;
 9 50 0;
 0 51 90;
 10 52 0;
 0 53 91;
 0 54 0;
 11 55 0;
 0 56 0;
 0 57 0;
 12 58 0;
 0 59 0;
 13 60 92;
 14 61 93;
 15 62 94;
 0 63 0;
 0 64 95;
 0 65 96;
 0 66 97;
 0 67 98;
 0 68 99;
 0 69 100;
 0 70 101;
 0 71 102;
 0 72 103;
 16 73 0;
 17 74 0;
 18 75 0;
 19 76 0;
 20 77 0;
 21 78 0;
 22 79 0;
 23 80 0;
 24 81 0;
 25 82 0;
 26 83 0;
 27 84 0;
 28 85 0;
 29 86 0;]';
M_.nstatic = 15;
M_.nfwrd   = 13;
M_.npred   = 25;
M_.nboth   = 4;
M_.nsfwrd   = 17;
M_.nspred   = 29;
M_.ndynamic   = 42;
M_.equations_tags = {
};
M_.static_and_dynamic_models_differ = 0;
M_.exo_names_orig_ord = [1:3];
M_.maximum_lag = 1;
M_.maximum_lead = 1;
M_.maximum_endo_lag = 1;
M_.maximum_endo_lead = 1;
oo_.steady_state = zeros(57, 1);
M_.maximum_exo_lag = 0;
M_.maximum_exo_lead = 0;
oo_.exo_steady_state = zeros(3, 1);
M_.params = NaN(58, 1);
M_.NNZDerivatives = [193; 0; -1];
M_.params( 42 ) = 0.61;
C_Y = M_.params( 42 );
M_.params( 44 ) = 0.01;
Ce_Y = M_.params( 44 );
M_.params( 43 ) = 0.18;
I_Y = M_.params( 43 );
M_.params( 41 ) = 0.20;
G_Y = M_.params( 41 );
M_.params( 50 ) = 2.00;
K_N = M_.params( 50 );
M_.params( 45 ) = 0.28;
Y_N = M_.params( 45 );
M_.params( 46 ) = 1.10;
X = M_.params( 46 );
M_.params( 35 ) = 0.99;
beta = M_.params( 35 );
M_.params( 51 ) = 1/M_.params(35);
R = M_.params( 51 );
M_.params( 37 ) = 0.35;
alpha = M_.params( 37 );
M_.params( 36 ) = 3;
eta = M_.params( 36 );
M_.params( 39 ) = 0.99;
omega = M_.params( 39 );
M_.params( 38 ) = 0.025;
delta = M_.params( 38 );
M_.params( 47 ) = 0.999;
rhoA = M_.params( 47 );
M_.params( 48 ) = 0.95;
rhoG = M_.params( 48 );
M_.params( 49 ) = 0.25;
psi = M_.params( 49 );
Rk        = R + 0.02    ;   
M_.params( 52 ) = 0.9728;
gamma = M_.params( 52 );
M_.params( 53 ) = 0.12;
mu = M_.params( 53 );
M_.params( 55 ) = 0.75;
theta = M_.params( 55 );
M_.params( 56 ) = 0.90;
rho = M_.params( 56 );
M_.params( 57 ) = 0.11;
S = M_.params( 57 );
M_.params( 58 ) = (1-M_.params(55))/M_.params(55)*(1-M_.params(35)*M_.params(55));
kappa = M_.params( 58 );
M_.params( 40 ) = (1-M_.params(38))/(1-M_.params(38)+M_.params(37)/M_.params(46)*M_.params(45)/M_.params(50));
eps = M_.params( 40 );
M_.params( 54 ) = 0.5;
nu = M_.params( 54 );
thispath = cd;                                                           
cd('..');                                                                
load policy_param.mat;                                                   
for i=1:33                                                               
deep_parameter_name = M_.param_names(i,:);                           
eval(['M_.params(i)  = ' deep_parameter_name ' ;'])                  
end                                                                      
cd(thispath);   
M_.params( 34 ) = 1/M_.params(41);
coffispol = M_.params( 34 );
%
% SHOCKS instructions
%
M_.exo_det_length = 0;
M_.Sigma_e(1, 1) = (0)^2;
M_.Sigma_e(2, 2) = (0)^2;
M_.Sigma_e(3, 3) = (0)^2;
save('NK_PSV16_results.mat', 'oo_', 'M_', 'options_');
if exist('estim_params_', 'var') == 1
  save('NK_PSV16_results.mat', 'estim_params_', '-append');
end
if exist('bayestopt_', 'var') == 1
  save('NK_PSV16_results.mat', 'bayestopt_', '-append');
end
if exist('dataset_', 'var') == 1
  save('NK_PSV16_results.mat', 'dataset_', '-append');
end
if exist('estimation_info', 'var') == 1
  save('NK_PSV16_results.mat', 'estimation_info', '-append');
end
if exist('dataset_info', 'var') == 1
  save('NK_PSV16_results.mat', 'dataset_info', '-append');
end
if exist('oo_recursive_', 'var') == 1
  save('NK_PSV16_results.mat', 'oo_recursive_', '-append');
end


disp(['Total computing time : ' dynsec2hms(toc(tic0)) ]);
if ~isempty(lastwarn)
  disp('Note: warning(s) encountered in MATLAB/Octave code')
end
diary off
