%
% Status : main Dynare file 
%
% Warning : this file is generated automatically by Dynare
%           from model file (.mod)

tic;
global M_ oo_ options_ ys0_ ex0_ estimation_info
options_ = [];
M_.fname = 'EA_PV15';
%
% Some global variables initialization
%
global_initialization;
diary off;
diary('EA_PV15.log');
M_.exo_names = 'e_a_h';
M_.exo_names_tex = 'e\_a\_h';
M_.exo_names_long = 'e_a_h';
M_.exo_names = char(M_.exo_names, 'e_g_h');
M_.exo_names_tex = char(M_.exo_names_tex, 'e\_g\_h');
M_.exo_names_long = char(M_.exo_names_long, 'e_g_h');
M_.exo_names = char(M_.exo_names, 'e_beta_h');
M_.exo_names_tex = char(M_.exo_names_tex, 'e\_beta\_h');
M_.exo_names_long = char(M_.exo_names_long, 'e_beta_h');
M_.exo_names = char(M_.exo_names, 'e_a_f');
M_.exo_names_tex = char(M_.exo_names_tex, 'e\_a\_f');
M_.exo_names_long = char(M_.exo_names_long, 'e_a_f');
M_.exo_names = char(M_.exo_names, 'e_g_f');
M_.exo_names_tex = char(M_.exo_names_tex, 'e\_g\_f');
M_.exo_names_long = char(M_.exo_names_long, 'e_g_f');
M_.exo_names = char(M_.exo_names, 'e_beta_f');
M_.exo_names_tex = char(M_.exo_names_tex, 'e\_beta\_f');
M_.exo_names_long = char(M_.exo_names_long, 'e_beta_f');
M_.exo_names = char(M_.exo_names, 'e_n_h');
M_.exo_names_tex = char(M_.exo_names_tex, 'e\_n\_h');
M_.exo_names_long = char(M_.exo_names_long, 'e_n_h');
M_.exo_names = char(M_.exo_names, 'e_n_f');
M_.exo_names_tex = char(M_.exo_names_tex, 'e\_n\_f');
M_.exo_names_long = char(M_.exo_names_long, 'e_n_f');
M_.exo_names = char(M_.exo_names, 'e_q_h');
M_.exo_names_tex = char(M_.exo_names_tex, 'e\_q\_h');
M_.exo_names_long = char(M_.exo_names_long, 'e_q_h');
M_.exo_names = char(M_.exo_names, 'e_q_f');
M_.exo_names_tex = char(M_.exo_names_tex, 'e\_q\_f');
M_.exo_names_long = char(M_.exo_names_long, 'e_q_f');
M_.exo_names = char(M_.exo_names, 'e_rL_h');
M_.exo_names_tex = char(M_.exo_names_tex, 'e\_rL\_h');
M_.exo_names_long = char(M_.exo_names_long, 'e_rL_h');
M_.exo_names = char(M_.exo_names, 'e_rL_f');
M_.exo_names_tex = char(M_.exo_names_tex, 'e\_rL\_f');
M_.exo_names_long = char(M_.exo_names_long, 'e_rL_f');
M_.exo_names = char(M_.exo_names, 'e_w_h');
M_.exo_names_tex = char(M_.exo_names_tex, 'e\_w\_h');
M_.exo_names_long = char(M_.exo_names_long, 'e_w_h');
M_.exo_names = char(M_.exo_names, 'e_w_f');
M_.exo_names_tex = char(M_.exo_names_tex, 'e\_w\_f');
M_.exo_names_long = char(M_.exo_names_long, 'e_w_f');
M_.exo_names = char(M_.exo_names, 'e_ib_h');
M_.exo_names_tex = char(M_.exo_names_tex, 'e\_ib\_h');
M_.exo_names_long = char(M_.exo_names_long, 'e_ib_h');
M_.exo_names = char(M_.exo_names, 'e_ib_f');
M_.exo_names_tex = char(M_.exo_names_tex, 'e\_ib\_f');
M_.exo_names_long = char(M_.exo_names_long, 'e_ib_f');
M_.exo_names = char(M_.exo_names, 'e_a');
M_.exo_names_tex = char(M_.exo_names_tex, 'e\_a');
M_.exo_names_long = char(M_.exo_names_long, 'e_a');
M_.exo_names = char(M_.exo_names, 'e_g');
M_.exo_names_tex = char(M_.exo_names_tex, 'e\_g');
M_.exo_names_long = char(M_.exo_names_long, 'e_g');
M_.exo_names = char(M_.exo_names, 'e_beta');
M_.exo_names_tex = char(M_.exo_names_tex, 'e\_beta');
M_.exo_names_long = char(M_.exo_names_long, 'e_beta');
M_.exo_names = char(M_.exo_names, 'e_n');
M_.exo_names_tex = char(M_.exo_names_tex, 'e\_n');
M_.exo_names_long = char(M_.exo_names_long, 'e_n');
M_.exo_names = char(M_.exo_names, 'e_q');
M_.exo_names_tex = char(M_.exo_names_tex, 'e\_q');
M_.exo_names_long = char(M_.exo_names_long, 'e_q');
M_.exo_names = char(M_.exo_names, 'e_rL');
M_.exo_names_tex = char(M_.exo_names_tex, 'e\_rL');
M_.exo_names_long = char(M_.exo_names_long, 'e_rL');
M_.exo_names = char(M_.exo_names, 'e_w');
M_.exo_names_tex = char(M_.exo_names_tex, 'e\_w');
M_.exo_names_long = char(M_.exo_names_long, 'e_w');
M_.exo_names = char(M_.exo_names, 'e_ib');
M_.exo_names_tex = char(M_.exo_names_tex, 'e\_ib');
M_.exo_names_long = char(M_.exo_names_long, 'e_ib');
M_.exo_names = char(M_.exo_names, 'e_r');
M_.exo_names_tex = char(M_.exo_names_tex, 'e\_r');
M_.exo_names_long = char(M_.exo_names_long, 'e_r');
M_.exo_names = char(M_.exo_names, 'interest_');
M_.exo_names_tex = char(M_.exo_names_tex, 'interest\_');
M_.exo_names_long = char(M_.exo_names_long, 'interest_');
M_.endo_names = 'y_h';
M_.endo_names_tex = 'y\_h';
M_.endo_names_long = 'y_h';
M_.endo_names = char(M_.endo_names, 'y_f');
M_.endo_names_tex = char(M_.endo_names_tex, 'y\_f');
M_.endo_names_long = char(M_.endo_names_long, 'y_f');
M_.endo_names = char(M_.endo_names, 'y_ea');
M_.endo_names_tex = char(M_.endo_names_tex, 'y\_ea');
M_.endo_names_long = char(M_.endo_names_long, 'y_ea');
M_.endo_names = char(M_.endo_names, 'c_h');
M_.endo_names_tex = char(M_.endo_names_tex, 'c\_h');
M_.endo_names_long = char(M_.endo_names_long, 'c_h');
M_.endo_names = char(M_.endo_names, 'c_f');
M_.endo_names_tex = char(M_.endo_names_tex, 'c\_f');
M_.endo_names_long = char(M_.endo_names_long, 'c_f');
M_.endo_names = char(M_.endo_names, 'c_ea');
M_.endo_names_tex = char(M_.endo_names_tex, 'c\_ea');
M_.endo_names_long = char(M_.endo_names_long, 'c_ea');
M_.endo_names = char(M_.endo_names, 'r');
M_.endo_names_tex = char(M_.endo_names_tex, 'r');
M_.endo_names_long = char(M_.endo_names_long, 'r');
M_.endo_names = char(M_.endo_names, 'pi_h');
M_.endo_names_tex = char(M_.endo_names_tex, 'pi\_h');
M_.endo_names_long = char(M_.endo_names_long, 'pi_h');
M_.endo_names = char(M_.endo_names, 'pi_f');
M_.endo_names_tex = char(M_.endo_names_tex, 'pi\_f');
M_.endo_names_long = char(M_.endo_names_long, 'pi_f');
M_.endo_names = char(M_.endo_names, 'pi_ea');
M_.endo_names_tex = char(M_.endo_names_tex, 'pi\_ea');
M_.endo_names_long = char(M_.endo_names_long, 'pi_ea');
M_.endo_names = char(M_.endo_names, 'pic_h');
M_.endo_names_tex = char(M_.endo_names_tex, 'pic\_h');
M_.endo_names_long = char(M_.endo_names_long, 'pic_h');
M_.endo_names = char(M_.endo_names, 'pic_f');
M_.endo_names_tex = char(M_.endo_names_tex, 'pic\_f');
M_.endo_names_long = char(M_.endo_names_long, 'pic_f');
M_.endo_names = char(M_.endo_names, 'w_h');
M_.endo_names_tex = char(M_.endo_names_tex, 'w\_h');
M_.endo_names_long = char(M_.endo_names_long, 'w_h');
M_.endo_names = char(M_.endo_names, 'w_f');
M_.endo_names_tex = char(M_.endo_names_tex, 'w\_f');
M_.endo_names_long = char(M_.endo_names_long, 'w_f');
M_.endo_names = char(M_.endo_names, 'wh_h');
M_.endo_names_tex = char(M_.endo_names_tex, 'wh\_h');
M_.endo_names_long = char(M_.endo_names_long, 'wh_h');
M_.endo_names = char(M_.endo_names, 'wh_f');
M_.endo_names_tex = char(M_.endo_names_tex, 'wh\_f');
M_.endo_names_long = char(M_.endo_names_long, 'wh_f');
M_.endo_names = char(M_.endo_names, 'h_h');
M_.endo_names_tex = char(M_.endo_names_tex, 'h\_h');
M_.endo_names_long = char(M_.endo_names_long, 'h_h');
M_.endo_names = char(M_.endo_names, 'h_f');
M_.endo_names_tex = char(M_.endo_names_tex, 'h\_f');
M_.endo_names_long = char(M_.endo_names_long, 'h_f');
M_.endo_names = char(M_.endo_names, 'mc_h');
M_.endo_names_tex = char(M_.endo_names_tex, 'mc\_h');
M_.endo_names_long = char(M_.endo_names_long, 'mc_h');
M_.endo_names = char(M_.endo_names, 'mc_f');
M_.endo_names_tex = char(M_.endo_names_tex, 'mc\_f');
M_.endo_names_long = char(M_.endo_names_long, 'mc_f');
M_.endo_names = char(M_.endo_names, 'k_h');
M_.endo_names_tex = char(M_.endo_names_tex, 'k\_h');
M_.endo_names_long = char(M_.endo_names_long, 'k_h');
M_.endo_names = char(M_.endo_names, 'k_f');
M_.endo_names_tex = char(M_.endo_names_tex, 'k\_f');
M_.endo_names_long = char(M_.endo_names_long, 'k_f');
M_.endo_names = char(M_.endo_names, 'i_h');
M_.endo_names_tex = char(M_.endo_names_tex, 'i\_h');
M_.endo_names_long = char(M_.endo_names_long, 'i_h');
M_.endo_names = char(M_.endo_names, 'i_f');
M_.endo_names_tex = char(M_.endo_names_tex, 'i\_f');
M_.endo_names_long = char(M_.endo_names_long, 'i_f');
M_.endo_names = char(M_.endo_names, 'i_ea');
M_.endo_names_tex = char(M_.endo_names_tex, 'i\_ea');
M_.endo_names_long = char(M_.endo_names_long, 'i_ea');
M_.endo_names = char(M_.endo_names, 'z_h');
M_.endo_names_tex = char(M_.endo_names_tex, 'z\_h');
M_.endo_names_long = char(M_.endo_names_long, 'z_h');
M_.endo_names = char(M_.endo_names, 'z_f');
M_.endo_names_tex = char(M_.endo_names_tex, 'z\_f');
M_.endo_names_long = char(M_.endo_names_long, 'z_f');
M_.endo_names = char(M_.endo_names, 'q_h');
M_.endo_names_tex = char(M_.endo_names_tex, 'q\_h');
M_.endo_names_long = char(M_.endo_names_long, 'q_h');
M_.endo_names = char(M_.endo_names, 'q_f');
M_.endo_names_tex = char(M_.endo_names_tex, 'q\_f');
M_.endo_names_long = char(M_.endo_names_long, 'q_f');
M_.endo_names = char(M_.endo_names, 'ToT');
M_.endo_names_tex = char(M_.endo_names_tex, 'ToT');
M_.endo_names_long = char(M_.endo_names_long, 'ToT');
M_.endo_names = char(M_.endo_names, 'b_h');
M_.endo_names_tex = char(M_.endo_names_tex, 'b\_h');
M_.endo_names_long = char(M_.endo_names_long, 'b_h');
M_.endo_names = char(M_.endo_names, 'ku_h');
M_.endo_names_tex = char(M_.endo_names_tex, 'ku\_h');
M_.endo_names_long = char(M_.endo_names_long, 'ku_h');
M_.endo_names = char(M_.endo_names, 'ku_f');
M_.endo_names_tex = char(M_.endo_names_tex, 'ku\_f');
M_.endo_names_long = char(M_.endo_names_long, 'ku_f');
M_.endo_names = char(M_.endo_names, 'u_h');
M_.endo_names_tex = char(M_.endo_names_tex, 'u\_h');
M_.endo_names_long = char(M_.endo_names_long, 'u_h');
M_.endo_names = char(M_.endo_names, 'u_f');
M_.endo_names_tex = char(M_.endo_names_tex, 'u\_f');
M_.endo_names_long = char(M_.endo_names_long, 'u_f');
M_.endo_names = char(M_.endo_names, 'CA');
M_.endo_names_tex = char(M_.endo_names_tex, 'CA');
M_.endo_names_long = char(M_.endo_names_long, 'CA');
M_.endo_names = char(M_.endo_names, 'omega_h');
M_.endo_names_tex = char(M_.endo_names_tex, 'omega\_h');
M_.endo_names_long = char(M_.endo_names_long, 'omega_h');
M_.endo_names = char(M_.endo_names, 'omega_f');
M_.endo_names_tex = char(M_.endo_names_tex, 'omega\_f');
M_.endo_names_long = char(M_.endo_names_long, 'omega_f');
M_.endo_names = char(M_.endo_names, 'n_E_h');
M_.endo_names_tex = char(M_.endo_names_tex, 'n\_E\_h');
M_.endo_names_long = char(M_.endo_names_long, 'n_E_h');
M_.endo_names = char(M_.endo_names, 'n_E_f');
M_.endo_names_tex = char(M_.endo_names_tex, 'n\_E\_f');
M_.endo_names_long = char(M_.endo_names_long, 'n_E_f');
M_.endo_names = char(M_.endo_names, 'r_K_h');
M_.endo_names_tex = char(M_.endo_names_tex, 'r\_K\_h');
M_.endo_names_long = char(M_.endo_names_long, 'r_K_h');
M_.endo_names = char(M_.endo_names, 'r_K_f');
M_.endo_names_tex = char(M_.endo_names_tex, 'r\_K\_f');
M_.endo_names_long = char(M_.endo_names_long, 'r_K_f');
M_.endo_names = char(M_.endo_names, 'ld_h');
M_.endo_names_tex = char(M_.endo_names_tex, 'ld\_h');
M_.endo_names_long = char(M_.endo_names_long, 'ld_h');
M_.endo_names = char(M_.endo_names, 'ld_f');
M_.endo_names_tex = char(M_.endo_names_tex, 'ld\_f');
M_.endo_names_long = char(M_.endo_names_long, 'ld_f');
M_.endo_names = char(M_.endo_names, 'rr_h');
M_.endo_names_tex = char(M_.endo_names_tex, 'rr\_h');
M_.endo_names_long = char(M_.endo_names_long, 'rr_h');
M_.endo_names = char(M_.endo_names, 'rr_f');
M_.endo_names_tex = char(M_.endo_names_tex, 'rr\_f');
M_.endo_names_long = char(M_.endo_names_long, 'rr_f');
M_.endo_names = char(M_.endo_names, 's_h');
M_.endo_names_tex = char(M_.endo_names_tex, 's\_h');
M_.endo_names_long = char(M_.endo_names_long, 's_h');
M_.endo_names = char(M_.endo_names, 's_f');
M_.endo_names_tex = char(M_.endo_names_tex, 's\_f');
M_.endo_names_long = char(M_.endo_names_long, 's_f');
M_.endo_names = char(M_.endo_names, 'nk_h');
M_.endo_names_tex = char(M_.endo_names_tex, 'nk\_h');
M_.endo_names_long = char(M_.endo_names_long, 'nk_h');
M_.endo_names = char(M_.endo_names, 'nk_f');
M_.endo_names_tex = char(M_.endo_names_tex, 'nk\_f');
M_.endo_names_long = char(M_.endo_names_long, 'nk_f');
M_.endo_names = char(M_.endo_names, 'v_E_h');
M_.endo_names_tex = char(M_.endo_names_tex, 'v\_E\_h');
M_.endo_names_long = char(M_.endo_names_long, 'v_E_h');
M_.endo_names = char(M_.endo_names, 'v_E_f');
M_.endo_names_tex = char(M_.endo_names_tex, 'v\_E\_f');
M_.endo_names_long = char(M_.endo_names_long, 'v_E_f');
M_.endo_names = char(M_.endo_names, 'mcL_h');
M_.endo_names_tex = char(M_.endo_names_tex, 'mcL\_h');
M_.endo_names_long = char(M_.endo_names_long, 'mcL_h');
M_.endo_names = char(M_.endo_names, 'mcL_f');
M_.endo_names_tex = char(M_.endo_names_tex, 'mcL\_f');
M_.endo_names_long = char(M_.endo_names_long, 'mcL_f');
M_.endo_names = char(M_.endo_names, 'ls_h');
M_.endo_names_tex = char(M_.endo_names_tex, 'ls\_h');
M_.endo_names_long = char(M_.endo_names_long, 'ls_h');
M_.endo_names = char(M_.endo_names, 'ls_f');
M_.endo_names_tex = char(M_.endo_names_tex, 'ls\_f');
M_.endo_names_long = char(M_.endo_names_long, 'ls_f');
M_.endo_names = char(M_.endo_names, 'ls_ea');
M_.endo_names_tex = char(M_.endo_names_tex, 'ls\_ea');
M_.endo_names_long = char(M_.endo_names_long, 'ls_ea');
M_.endo_names = char(M_.endo_names, 'r_L_h');
M_.endo_names_tex = char(M_.endo_names_tex, 'r\_L\_h');
M_.endo_names_long = char(M_.endo_names_long, 'r_L_h');
M_.endo_names = char(M_.endo_names, 'r_L_f');
M_.endo_names_tex = char(M_.endo_names_tex, 'r\_L\_f');
M_.endo_names_long = char(M_.endo_names_long, 'r_L_f');
M_.endo_names = char(M_.endo_names, 's_B_h');
M_.endo_names_tex = char(M_.endo_names_tex, 's\_B\_h');
M_.endo_names_long = char(M_.endo_names_long, 's_B_h');
M_.endo_names = char(M_.endo_names, 's_B_f');
M_.endo_names_tex = char(M_.endo_names_tex, 's\_B\_f');
M_.endo_names_long = char(M_.endo_names_long, 's_B_f');
M_.endo_names = char(M_.endo_names, 'pl_h');
M_.endo_names_tex = char(M_.endo_names_tex, 'pl\_h');
M_.endo_names_long = char(M_.endo_names_long, 'pl_h');
M_.endo_names = char(M_.endo_names, 'pl_f');
M_.endo_names_tex = char(M_.endo_names_tex, 'pl\_f');
M_.endo_names_long = char(M_.endo_names_long, 'pl_f');
M_.endo_names = char(M_.endo_names, 'bk_h');
M_.endo_names_tex = char(M_.endo_names_tex, 'bk\_h');
M_.endo_names_long = char(M_.endo_names_long, 'bk_h');
M_.endo_names = char(M_.endo_names, 'bk_f');
M_.endo_names_tex = char(M_.endo_names_tex, 'bk\_f');
M_.endo_names_long = char(M_.endo_names_long, 'bk_f');
M_.endo_names = char(M_.endo_names, 'ibn_h');
M_.endo_names_tex = char(M_.endo_names_tex, 'ibn\_h');
M_.endo_names_long = char(M_.endo_names_long, 'ibn_h');
M_.endo_names = char(M_.endo_names, 'ibn_f');
M_.endo_names_tex = char(M_.endo_names_tex, 'ibn\_f');
M_.endo_names_long = char(M_.endo_names_long, 'ibn_f');
M_.endo_names = char(M_.endo_names, 'IBs_h');
M_.endo_names_tex = char(M_.endo_names_tex, 'IBs\_h');
M_.endo_names_long = char(M_.endo_names_long, 'IBs_h');
M_.endo_names = char(M_.endo_names, 'IBs_f');
M_.endo_names_tex = char(M_.endo_names_tex, 'IBs\_f');
M_.endo_names_long = char(M_.endo_names_long, 'IBs_f');
M_.endo_names = char(M_.endo_names, 'IB_ea');
M_.endo_names_tex = char(M_.endo_names_tex, 'IB\_ea');
M_.endo_names_long = char(M_.endo_names_long, 'IB_ea');
M_.endo_names = char(M_.endo_names, 'r_IB_h');
M_.endo_names_tex = char(M_.endo_names_tex, 'r\_IB\_h');
M_.endo_names_long = char(M_.endo_names_long, 'r_IB_h');
M_.endo_names = char(M_.endo_names, 'r_IB_f');
M_.endo_names_tex = char(M_.endo_names_tex, 'r\_IB\_f');
M_.endo_names_long = char(M_.endo_names_long, 'r_IB_f');
M_.endo_names = char(M_.endo_names, 'p_IB_h');
M_.endo_names_tex = char(M_.endo_names_tex, 'p\_IB\_h');
M_.endo_names_long = char(M_.endo_names_long, 'p_IB_h');
M_.endo_names = char(M_.endo_names, 'p_IB_f');
M_.endo_names_tex = char(M_.endo_names_tex, 'p\_IB\_f');
M_.endo_names_long = char(M_.endo_names_long, 'p_IB_f');
M_.endo_names = char(M_.endo_names, 'IBd_h');
M_.endo_names_tex = char(M_.endo_names_tex, 'IBd\_h');
M_.endo_names_long = char(M_.endo_names_long, 'IBd_h');
M_.endo_names = char(M_.endo_names, 'IBd_f');
M_.endo_names_tex = char(M_.endo_names_tex, 'IBd\_f');
M_.endo_names_long = char(M_.endo_names_long, 'IBd_f');
M_.endo_names = char(M_.endo_names, 'a_h');
M_.endo_names_tex = char(M_.endo_names_tex, 'a\_h');
M_.endo_names_long = char(M_.endo_names_long, 'a_h');
M_.endo_names = char(M_.endo_names, 'a_f');
M_.endo_names_tex = char(M_.endo_names_tex, 'a\_f');
M_.endo_names_long = char(M_.endo_names_long, 'a_f');
M_.endo_names = char(M_.endo_names, 'g_h');
M_.endo_names_tex = char(M_.endo_names_tex, 'g\_h');
M_.endo_names_long = char(M_.endo_names_long, 'g_h');
M_.endo_names = char(M_.endo_names, 'g_f');
M_.endo_names_tex = char(M_.endo_names_tex, 'g\_f');
M_.endo_names_long = char(M_.endo_names_long, 'g_f');
M_.endo_names = char(M_.endo_names, 'beta_shock_h');
M_.endo_names_tex = char(M_.endo_names_tex, 'beta\_shock\_h');
M_.endo_names_long = char(M_.endo_names_long, 'beta_shock_h');
M_.endo_names = char(M_.endo_names, 'beta_shock_f');
M_.endo_names_tex = char(M_.endo_names_tex, 'beta\_shock\_f');
M_.endo_names_long = char(M_.endo_names_long, 'beta_shock_f');
M_.endo_names = char(M_.endo_names, 'n_shock_h');
M_.endo_names_tex = char(M_.endo_names_tex, 'n\_shock\_h');
M_.endo_names_long = char(M_.endo_names_long, 'n_shock_h');
M_.endo_names = char(M_.endo_names, 'n_shock_f');
M_.endo_names_tex = char(M_.endo_names_tex, 'n\_shock\_f');
M_.endo_names_long = char(M_.endo_names_long, 'n_shock_f');
M_.endo_names = char(M_.endo_names, 'q_shock_h');
M_.endo_names_tex = char(M_.endo_names_tex, 'q\_shock\_h');
M_.endo_names_long = char(M_.endo_names_long, 'q_shock_h');
M_.endo_names = char(M_.endo_names, 'q_shock_f');
M_.endo_names_tex = char(M_.endo_names_tex, 'q\_shock\_f');
M_.endo_names_long = char(M_.endo_names_long, 'q_shock_f');
M_.endo_names = char(M_.endo_names, 'rL_shock_h');
M_.endo_names_tex = char(M_.endo_names_tex, 'rL\_shock\_h');
M_.endo_names_long = char(M_.endo_names_long, 'rL_shock_h');
M_.endo_names = char(M_.endo_names, 'rL_shock_f');
M_.endo_names_tex = char(M_.endo_names_tex, 'rL\_shock\_f');
M_.endo_names_long = char(M_.endo_names_long, 'rL_shock_f');
M_.endo_names = char(M_.endo_names, 'w_shock_h');
M_.endo_names_tex = char(M_.endo_names_tex, 'w\_shock\_h');
M_.endo_names_long = char(M_.endo_names_long, 'w_shock_h');
M_.endo_names = char(M_.endo_names, 'w_shock_f');
M_.endo_names_tex = char(M_.endo_names_tex, 'w\_shock\_f');
M_.endo_names_long = char(M_.endo_names_long, 'w_shock_f');
M_.endo_names = char(M_.endo_names, 'ib_shock_h');
M_.endo_names_tex = char(M_.endo_names_tex, 'ib\_shock\_h');
M_.endo_names_long = char(M_.endo_names_long, 'ib_shock_h');
M_.endo_names = char(M_.endo_names, 'ib_shock_f');
M_.endo_names_tex = char(M_.endo_names_tex, 'ib\_shock\_f');
M_.endo_names_long = char(M_.endo_names_long, 'ib_shock_f');
M_.endo_names = char(M_.endo_names, 'r_shock');
M_.endo_names_tex = char(M_.endo_names_tex, 'r\_shock');
M_.endo_names_long = char(M_.endo_names_long, 'r_shock');
M_.endo_names = char(M_.endo_names, 'y_hfp');
M_.endo_names_tex = char(M_.endo_names_tex, 'y\_hfp');
M_.endo_names_long = char(M_.endo_names_long, 'y_hfp');
M_.endo_names = char(M_.endo_names, 'y_ffp');
M_.endo_names_tex = char(M_.endo_names_tex, 'y\_ffp');
M_.endo_names_long = char(M_.endo_names_long, 'y_ffp');
M_.endo_names = char(M_.endo_names, 'y_eafp');
M_.endo_names_tex = char(M_.endo_names_tex, 'y\_eafp');
M_.endo_names_long = char(M_.endo_names_long, 'y_eafp');
M_.endo_names = char(M_.endo_names, 'c_hfp');
M_.endo_names_tex = char(M_.endo_names_tex, 'c\_hfp');
M_.endo_names_long = char(M_.endo_names_long, 'c_hfp');
M_.endo_names = char(M_.endo_names, 'c_ffp');
M_.endo_names_tex = char(M_.endo_names_tex, 'c\_ffp');
M_.endo_names_long = char(M_.endo_names_long, 'c_ffp');
M_.endo_names = char(M_.endo_names, 'c_eafp');
M_.endo_names_tex = char(M_.endo_names_tex, 'c\_eafp');
M_.endo_names_long = char(M_.endo_names_long, 'c_eafp');
M_.endo_names = char(M_.endo_names, 'pi_hfp');
M_.endo_names_tex = char(M_.endo_names_tex, 'pi\_hfp');
M_.endo_names_long = char(M_.endo_names_long, 'pi_hfp');
M_.endo_names = char(M_.endo_names, 'pi_ffp');
M_.endo_names_tex = char(M_.endo_names_tex, 'pi\_ffp');
M_.endo_names_long = char(M_.endo_names_long, 'pi_ffp');
M_.endo_names = char(M_.endo_names, 'pi_eafp');
M_.endo_names_tex = char(M_.endo_names_tex, 'pi\_eafp');
M_.endo_names_long = char(M_.endo_names_long, 'pi_eafp');
M_.endo_names = char(M_.endo_names, 'pic_hfp');
M_.endo_names_tex = char(M_.endo_names_tex, 'pic\_hfp');
M_.endo_names_long = char(M_.endo_names_long, 'pic_hfp');
M_.endo_names = char(M_.endo_names, 'pic_ffp');
M_.endo_names_tex = char(M_.endo_names_tex, 'pic\_ffp');
M_.endo_names_long = char(M_.endo_names_long, 'pic_ffp');
M_.endo_names = char(M_.endo_names, 'w_hfp');
M_.endo_names_tex = char(M_.endo_names_tex, 'w\_hfp');
M_.endo_names_long = char(M_.endo_names_long, 'w_hfp');
M_.endo_names = char(M_.endo_names, 'w_ffp');
M_.endo_names_tex = char(M_.endo_names_tex, 'w\_ffp');
M_.endo_names_long = char(M_.endo_names_long, 'w_ffp');
M_.endo_names = char(M_.endo_names, 'wh_hfp');
M_.endo_names_tex = char(M_.endo_names_tex, 'wh\_hfp');
M_.endo_names_long = char(M_.endo_names_long, 'wh_hfp');
M_.endo_names = char(M_.endo_names, 'wh_ffp');
M_.endo_names_tex = char(M_.endo_names_tex, 'wh\_ffp');
M_.endo_names_long = char(M_.endo_names_long, 'wh_ffp');
M_.endo_names = char(M_.endo_names, 'h_hfp');
M_.endo_names_tex = char(M_.endo_names_tex, 'h\_hfp');
M_.endo_names_long = char(M_.endo_names_long, 'h_hfp');
M_.endo_names = char(M_.endo_names, 'h_ffp');
M_.endo_names_tex = char(M_.endo_names_tex, 'h\_ffp');
M_.endo_names_long = char(M_.endo_names_long, 'h_ffp');
M_.endo_names = char(M_.endo_names, 'mc_hfp');
M_.endo_names_tex = char(M_.endo_names_tex, 'mc\_hfp');
M_.endo_names_long = char(M_.endo_names_long, 'mc_hfp');
M_.endo_names = char(M_.endo_names, 'mc_ffp');
M_.endo_names_tex = char(M_.endo_names_tex, 'mc\_ffp');
M_.endo_names_long = char(M_.endo_names_long, 'mc_ffp');
M_.endo_names = char(M_.endo_names, 'k_hfp');
M_.endo_names_tex = char(M_.endo_names_tex, 'k\_hfp');
M_.endo_names_long = char(M_.endo_names_long, 'k_hfp');
M_.endo_names = char(M_.endo_names, 'k_ffp');
M_.endo_names_tex = char(M_.endo_names_tex, 'k\_ffp');
M_.endo_names_long = char(M_.endo_names_long, 'k_ffp');
M_.endo_names = char(M_.endo_names, 'i_hfp');
M_.endo_names_tex = char(M_.endo_names_tex, 'i\_hfp');
M_.endo_names_long = char(M_.endo_names_long, 'i_hfp');
M_.endo_names = char(M_.endo_names, 'i_ffp');
M_.endo_names_tex = char(M_.endo_names_tex, 'i\_ffp');
M_.endo_names_long = char(M_.endo_names_long, 'i_ffp');
M_.endo_names = char(M_.endo_names, 'i_eafp');
M_.endo_names_tex = char(M_.endo_names_tex, 'i\_eafp');
M_.endo_names_long = char(M_.endo_names_long, 'i_eafp');
M_.endo_names = char(M_.endo_names, 'z_hfp');
M_.endo_names_tex = char(M_.endo_names_tex, 'z\_hfp');
M_.endo_names_long = char(M_.endo_names_long, 'z_hfp');
M_.endo_names = char(M_.endo_names, 'z_ffp');
M_.endo_names_tex = char(M_.endo_names_tex, 'z\_ffp');
M_.endo_names_long = char(M_.endo_names_long, 'z_ffp');
M_.endo_names = char(M_.endo_names, 'q_hfp');
M_.endo_names_tex = char(M_.endo_names_tex, 'q\_hfp');
M_.endo_names_long = char(M_.endo_names_long, 'q_hfp');
M_.endo_names = char(M_.endo_names, 'q_ffp');
M_.endo_names_tex = char(M_.endo_names_tex, 'q\_ffp');
M_.endo_names_long = char(M_.endo_names_long, 'q_ffp');
M_.endo_names = char(M_.endo_names, 'ToTfp');
M_.endo_names_tex = char(M_.endo_names_tex, 'ToTfp');
M_.endo_names_long = char(M_.endo_names_long, 'ToTfp');
M_.endo_names = char(M_.endo_names, 'b_hfp');
M_.endo_names_tex = char(M_.endo_names_tex, 'b\_hfp');
M_.endo_names_long = char(M_.endo_names_long, 'b_hfp');
M_.endo_names = char(M_.endo_names, 'ku_hfp');
M_.endo_names_tex = char(M_.endo_names_tex, 'ku\_hfp');
M_.endo_names_long = char(M_.endo_names_long, 'ku_hfp');
M_.endo_names = char(M_.endo_names, 'ku_ffp');
M_.endo_names_tex = char(M_.endo_names_tex, 'ku\_ffp');
M_.endo_names_long = char(M_.endo_names_long, 'ku_ffp');
M_.endo_names = char(M_.endo_names, 'u_hfp');
M_.endo_names_tex = char(M_.endo_names_tex, 'u\_hfp');
M_.endo_names_long = char(M_.endo_names_long, 'u_hfp');
M_.endo_names = char(M_.endo_names, 'u_ffp');
M_.endo_names_tex = char(M_.endo_names_tex, 'u\_ffp');
M_.endo_names_long = char(M_.endo_names_long, 'u_ffp');
M_.endo_names = char(M_.endo_names, 'CAfp');
M_.endo_names_tex = char(M_.endo_names_tex, 'CAfp');
M_.endo_names_long = char(M_.endo_names_long, 'CAfp');
M_.endo_names = char(M_.endo_names, 'p_Hfp');
M_.endo_names_tex = char(M_.endo_names_tex, 'p\_Hfp');
M_.endo_names_long = char(M_.endo_names_long, 'p_Hfp');
M_.endo_names = char(M_.endo_names, 'p_Ffp');
M_.endo_names_tex = char(M_.endo_names_tex, 'p\_Ffp');
M_.endo_names_long = char(M_.endo_names_long, 'p_Ffp');
M_.endo_names = char(M_.endo_names, 'omega_hfp');
M_.endo_names_tex = char(M_.endo_names_tex, 'omega\_hfp');
M_.endo_names_long = char(M_.endo_names_long, 'omega_hfp');
M_.endo_names = char(M_.endo_names, 'omega_ffp');
M_.endo_names_tex = char(M_.endo_names_tex, 'omega\_ffp');
M_.endo_names_long = char(M_.endo_names_long, 'omega_ffp');
M_.endo_names = char(M_.endo_names, 'n_E_hfp');
M_.endo_names_tex = char(M_.endo_names_tex, 'n\_E\_hfp');
M_.endo_names_long = char(M_.endo_names_long, 'n_E_hfp');
M_.endo_names = char(M_.endo_names, 'n_E_ffp');
M_.endo_names_tex = char(M_.endo_names_tex, 'n\_E\_ffp');
M_.endo_names_long = char(M_.endo_names_long, 'n_E_ffp');
M_.endo_names = char(M_.endo_names, 'r_K_hfp');
M_.endo_names_tex = char(M_.endo_names_tex, 'r\_K\_hfp');
M_.endo_names_long = char(M_.endo_names_long, 'r_K_hfp');
M_.endo_names = char(M_.endo_names, 'r_K_ffp');
M_.endo_names_tex = char(M_.endo_names_tex, 'r\_K\_ffp');
M_.endo_names_long = char(M_.endo_names_long, 'r_K_ffp');
M_.endo_names = char(M_.endo_names, 'ld_hfp');
M_.endo_names_tex = char(M_.endo_names_tex, 'ld\_hfp');
M_.endo_names_long = char(M_.endo_names_long, 'ld_hfp');
M_.endo_names = char(M_.endo_names, 'ld_ffp');
M_.endo_names_tex = char(M_.endo_names_tex, 'ld\_ffp');
M_.endo_names_long = char(M_.endo_names_long, 'ld_ffp');
M_.endo_names = char(M_.endo_names, 'rr_hfp');
M_.endo_names_tex = char(M_.endo_names_tex, 'rr\_hfp');
M_.endo_names_long = char(M_.endo_names_long, 'rr_hfp');
M_.endo_names = char(M_.endo_names, 'rr_ffp');
M_.endo_names_tex = char(M_.endo_names_tex, 'rr\_ffp');
M_.endo_names_long = char(M_.endo_names_long, 'rr_ffp');
M_.endo_names = char(M_.endo_names, 's_hfp');
M_.endo_names_tex = char(M_.endo_names_tex, 's\_hfp');
M_.endo_names_long = char(M_.endo_names_long, 's_hfp');
M_.endo_names = char(M_.endo_names, 's_ffp');
M_.endo_names_tex = char(M_.endo_names_tex, 's\_ffp');
M_.endo_names_long = char(M_.endo_names_long, 's_ffp');
M_.endo_names = char(M_.endo_names, 'nk_hfp');
M_.endo_names_tex = char(M_.endo_names_tex, 'nk\_hfp');
M_.endo_names_long = char(M_.endo_names_long, 'nk_hfp');
M_.endo_names = char(M_.endo_names, 'nk_ffp');
M_.endo_names_tex = char(M_.endo_names_tex, 'nk\_ffp');
M_.endo_names_long = char(M_.endo_names_long, 'nk_ffp');
M_.endo_names = char(M_.endo_names, 'v_E_hfp');
M_.endo_names_tex = char(M_.endo_names_tex, 'v\_E\_hfp');
M_.endo_names_long = char(M_.endo_names_long, 'v_E_hfp');
M_.endo_names = char(M_.endo_names, 'v_E_ffp');
M_.endo_names_tex = char(M_.endo_names_tex, 'v\_E\_ffp');
M_.endo_names_long = char(M_.endo_names_long, 'v_E_ffp');
M_.endo_names = char(M_.endo_names, 'mcL_hfp');
M_.endo_names_tex = char(M_.endo_names_tex, 'mcL\_hfp');
M_.endo_names_long = char(M_.endo_names_long, 'mcL_hfp');
M_.endo_names = char(M_.endo_names, 'mcL_ffp');
M_.endo_names_tex = char(M_.endo_names_tex, 'mcL\_ffp');
M_.endo_names_long = char(M_.endo_names_long, 'mcL_ffp');
M_.endo_names = char(M_.endo_names, 'ls_hfp');
M_.endo_names_tex = char(M_.endo_names_tex, 'ls\_hfp');
M_.endo_names_long = char(M_.endo_names_long, 'ls_hfp');
M_.endo_names = char(M_.endo_names, 'ls_ffp');
M_.endo_names_tex = char(M_.endo_names_tex, 'ls\_ffp');
M_.endo_names_long = char(M_.endo_names_long, 'ls_ffp');
M_.endo_names = char(M_.endo_names, 'ls_eafp');
M_.endo_names_tex = char(M_.endo_names_tex, 'ls\_eafp');
M_.endo_names_long = char(M_.endo_names_long, 'ls_eafp');
M_.endo_names = char(M_.endo_names, 'r_L_hfp');
M_.endo_names_tex = char(M_.endo_names_tex, 'r\_L\_hfp');
M_.endo_names_long = char(M_.endo_names_long, 'r_L_hfp');
M_.endo_names = char(M_.endo_names, 'r_L_ffp');
M_.endo_names_tex = char(M_.endo_names_tex, 'r\_L\_ffp');
M_.endo_names_long = char(M_.endo_names_long, 'r_L_ffp');
M_.endo_names = char(M_.endo_names, 's_B_hfp');
M_.endo_names_tex = char(M_.endo_names_tex, 's\_B\_hfp');
M_.endo_names_long = char(M_.endo_names_long, 's_B_hfp');
M_.endo_names = char(M_.endo_names, 's_B_ffp');
M_.endo_names_tex = char(M_.endo_names_tex, 's\_B\_ffp');
M_.endo_names_long = char(M_.endo_names_long, 's_B_ffp');
M_.endo_names = char(M_.endo_names, 'pl_hfp');
M_.endo_names_tex = char(M_.endo_names_tex, 'pl\_hfp');
M_.endo_names_long = char(M_.endo_names_long, 'pl_hfp');
M_.endo_names = char(M_.endo_names, 'pl_ffp');
M_.endo_names_tex = char(M_.endo_names_tex, 'pl\_ffp');
M_.endo_names_long = char(M_.endo_names_long, 'pl_ffp');
M_.endo_names = char(M_.endo_names, 'bk_hfp');
M_.endo_names_tex = char(M_.endo_names_tex, 'bk\_hfp');
M_.endo_names_long = char(M_.endo_names_long, 'bk_hfp');
M_.endo_names = char(M_.endo_names, 'bk_ffp');
M_.endo_names_tex = char(M_.endo_names_tex, 'bk\_ffp');
M_.endo_names_long = char(M_.endo_names_long, 'bk_ffp');
M_.endo_names = char(M_.endo_names, 'ibn_hfp');
M_.endo_names_tex = char(M_.endo_names_tex, 'ibn\_hfp');
M_.endo_names_long = char(M_.endo_names_long, 'ibn_hfp');
M_.endo_names = char(M_.endo_names, 'ibn_ffp');
M_.endo_names_tex = char(M_.endo_names_tex, 'ibn\_ffp');
M_.endo_names_long = char(M_.endo_names_long, 'ibn_ffp');
M_.endo_names = char(M_.endo_names, 'IBs_hfp');
M_.endo_names_tex = char(M_.endo_names_tex, 'IBs\_hfp');
M_.endo_names_long = char(M_.endo_names_long, 'IBs_hfp');
M_.endo_names = char(M_.endo_names, 'IBs_ffp');
M_.endo_names_tex = char(M_.endo_names_tex, 'IBs\_ffp');
M_.endo_names_long = char(M_.endo_names_long, 'IBs_ffp');
M_.endo_names = char(M_.endo_names, 'IB_eafp');
M_.endo_names_tex = char(M_.endo_names_tex, 'IB\_eafp');
M_.endo_names_long = char(M_.endo_names_long, 'IB_eafp');
M_.endo_names = char(M_.endo_names, 'r_IB_hfp');
M_.endo_names_tex = char(M_.endo_names_tex, 'r\_IB\_hfp');
M_.endo_names_long = char(M_.endo_names_long, 'r_IB_hfp');
M_.endo_names = char(M_.endo_names, 'r_IB_ffp');
M_.endo_names_tex = char(M_.endo_names_tex, 'r\_IB\_ffp');
M_.endo_names_long = char(M_.endo_names_long, 'r_IB_ffp');
M_.endo_names = char(M_.endo_names, 'p_IB_hfp');
M_.endo_names_tex = char(M_.endo_names_tex, 'p\_IB\_hfp');
M_.endo_names_long = char(M_.endo_names_long, 'p_IB_hfp');
M_.endo_names = char(M_.endo_names, 'p_IB_ffp');
M_.endo_names_tex = char(M_.endo_names_tex, 'p\_IB\_ffp');
M_.endo_names_long = char(M_.endo_names_long, 'p_IB_ffp');
M_.endo_names = char(M_.endo_names, 'IBd_hfp');
M_.endo_names_tex = char(M_.endo_names_tex, 'IBd\_hfp');
M_.endo_names_long = char(M_.endo_names_long, 'IBd_hfp');
M_.endo_names = char(M_.endo_names, 'IBd_ffp');
M_.endo_names_tex = char(M_.endo_names_tex, 'IBd\_ffp');
M_.endo_names_long = char(M_.endo_names_long, 'IBd_ffp');
M_.endo_names = char(M_.endo_names, 'interest');
M_.endo_names_tex = char(M_.endo_names_tex, 'interest');
M_.endo_names_long = char(M_.endo_names_long, 'interest');
M_.endo_names = char(M_.endo_names, 'inflation');
M_.endo_names_tex = char(M_.endo_names_tex, 'inflation');
M_.endo_names_long = char(M_.endo_names_long, 'inflation');
M_.endo_names = char(M_.endo_names, 'inflationq');
M_.endo_names_tex = char(M_.endo_names_tex, 'inflationq');
M_.endo_names_long = char(M_.endo_names_long, 'inflationq');
M_.endo_names = char(M_.endo_names, 'outputgap');
M_.endo_names_tex = char(M_.endo_names_tex, 'outputgap');
M_.endo_names_long = char(M_.endo_names_long, 'outputgap');
M_.endo_names = char(M_.endo_names, 'output');
M_.endo_names_tex = char(M_.endo_names_tex, 'output');
M_.endo_names_long = char(M_.endo_names_long, 'output');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_75');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_75');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_75');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_79');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_79');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_79');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_83');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_83');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_83');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_110');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_110');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_110');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_114');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_114');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_114');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_118');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_118');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_118');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_145');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_145');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_145');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_149');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_149');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_149');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_153');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_153');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_153');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_642');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_642');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_642');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_676');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_676');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_676');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_9_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_9\_1');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_9_1');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_9_2');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_9\_2');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_9_2');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_174_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_174\_1');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_174_1');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_174_2');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_174\_2');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_174_2');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_174_3');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_174\_3');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_174_3');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_173_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_173\_1');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_173_1');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_173_2');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_173\_2');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_173_2');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_173_3');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_173\_3');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_173_3');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_170_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_170\_1');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_170_1');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_170_2');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_170\_2');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_170_2');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_170_3');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_170\_3');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_170_3');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_172_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_172\_1');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_172_1');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_172_2');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_172\_2');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_172_2');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_172_3');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_172\_3');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_172_3');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_42_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_42\_1');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_42_1');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_43_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_43\_1');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_43_1');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_57_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_57\_1');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_57_1');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_58_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_58\_1');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_58_1');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_74_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_74\_1');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_74_1');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_75_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_75\_1');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_75_1');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_136_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_136\_1');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_136_1');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_137_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_137\_1');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_137_1');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_168_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_168\_1');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_168_1');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_169_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_169\_1');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_169_1');
M_.param_names = 'cofintintb1';
M_.param_names_tex = 'cofintintb1';
M_.param_names_long = 'cofintintb1';
M_.param_names = char(M_.param_names, 'cofintintb2');
M_.param_names_tex = char(M_.param_names_tex, 'cofintintb2');
M_.param_names_long = char(M_.param_names_long, 'cofintintb2');
M_.param_names = char(M_.param_names, 'cofintintb3');
M_.param_names_tex = char(M_.param_names_tex, 'cofintintb3');
M_.param_names_long = char(M_.param_names_long, 'cofintintb3');
M_.param_names = char(M_.param_names, 'cofintintb4');
M_.param_names_tex = char(M_.param_names_tex, 'cofintintb4');
M_.param_names_long = char(M_.param_names_long, 'cofintintb4');
M_.param_names = char(M_.param_names, 'cofintinf0');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinf0');
M_.param_names_long = char(M_.param_names_long, 'cofintinf0');
M_.param_names = char(M_.param_names, 'cofintinfb1');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinfb1');
M_.param_names_long = char(M_.param_names_long, 'cofintinfb1');
M_.param_names = char(M_.param_names, 'cofintinfb2');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinfb2');
M_.param_names_long = char(M_.param_names_long, 'cofintinfb2');
M_.param_names = char(M_.param_names, 'cofintinfb3');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinfb3');
M_.param_names_long = char(M_.param_names_long, 'cofintinfb3');
M_.param_names = char(M_.param_names, 'cofintinfb4');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinfb4');
M_.param_names_long = char(M_.param_names_long, 'cofintinfb4');
M_.param_names = char(M_.param_names, 'cofintinff1');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinff1');
M_.param_names_long = char(M_.param_names_long, 'cofintinff1');
M_.param_names = char(M_.param_names, 'cofintinff2');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinff2');
M_.param_names_long = char(M_.param_names_long, 'cofintinff2');
M_.param_names = char(M_.param_names, 'cofintinff3');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinff3');
M_.param_names_long = char(M_.param_names_long, 'cofintinff3');
M_.param_names = char(M_.param_names, 'cofintinff4');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinff4');
M_.param_names_long = char(M_.param_names_long, 'cofintinff4');
M_.param_names = char(M_.param_names, 'cofintout');
M_.param_names_tex = char(M_.param_names_tex, 'cofintout');
M_.param_names_long = char(M_.param_names_long, 'cofintout');
M_.param_names = char(M_.param_names, 'cofintoutb1');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutb1');
M_.param_names_long = char(M_.param_names_long, 'cofintoutb1');
M_.param_names = char(M_.param_names, 'cofintoutb2');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutb2');
M_.param_names_long = char(M_.param_names_long, 'cofintoutb2');
M_.param_names = char(M_.param_names, 'cofintoutb3');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutb3');
M_.param_names_long = char(M_.param_names_long, 'cofintoutb3');
M_.param_names = char(M_.param_names, 'cofintoutb4');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutb4');
M_.param_names_long = char(M_.param_names_long, 'cofintoutb4');
M_.param_names = char(M_.param_names, 'cofintoutf1');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutf1');
M_.param_names_long = char(M_.param_names_long, 'cofintoutf1');
M_.param_names = char(M_.param_names, 'cofintoutf2');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutf2');
M_.param_names_long = char(M_.param_names_long, 'cofintoutf2');
M_.param_names = char(M_.param_names, 'cofintoutf3');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutf3');
M_.param_names_long = char(M_.param_names_long, 'cofintoutf3');
M_.param_names = char(M_.param_names, 'cofintoutf4');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutf4');
M_.param_names_long = char(M_.param_names_long, 'cofintoutf4');
M_.param_names = char(M_.param_names, 'cofintoutp');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutp');
M_.param_names_long = char(M_.param_names_long, 'cofintoutp');
M_.param_names = char(M_.param_names, 'cofintoutpb1');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpb1');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpb1');
M_.param_names = char(M_.param_names, 'cofintoutpb2');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpb2');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpb2');
M_.param_names = char(M_.param_names, 'cofintoutpb3');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpb3');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpb3');
M_.param_names = char(M_.param_names, 'cofintoutpb4');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpb4');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpb4');
M_.param_names = char(M_.param_names, 'cofintoutpf1');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpf1');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpf1');
M_.param_names = char(M_.param_names, 'cofintoutpf2');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpf2');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpf2');
M_.param_names = char(M_.param_names, 'cofintoutpf3');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpf3');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpf3');
M_.param_names = char(M_.param_names, 'cofintoutpf4');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpf4');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpf4');
M_.param_names = char(M_.param_names, 'std_r_');
M_.param_names_tex = char(M_.param_names_tex, 'std\_r\_');
M_.param_names_long = char(M_.param_names_long, 'std_r_');
M_.param_names = char(M_.param_names, 'std_r_quart');
M_.param_names_tex = char(M_.param_names_tex, 'std\_r\_quart');
M_.param_names_long = char(M_.param_names_long, 'std_r_quart');
M_.param_names = char(M_.param_names, 'beta');
M_.param_names_tex = char(M_.param_names_tex, 'beta');
M_.param_names_long = char(M_.param_names_long, 'beta');
M_.param_names = char(M_.param_names, 'alpha');
M_.param_names_tex = char(M_.param_names_tex, 'alpha');
M_.param_names_long = char(M_.param_names_long, 'alpha');
M_.param_names = char(M_.param_names, 'delta');
M_.param_names_tex = char(M_.param_names_tex, 'delta');
M_.param_names_long = char(M_.param_names_long, 'delta');
M_.param_names = char(M_.param_names, 'thetap_h');
M_.param_names_tex = char(M_.param_names_tex, 'thetap\_h');
M_.param_names_long = char(M_.param_names_long, 'thetap_h');
M_.param_names = char(M_.param_names, 'thetap_f');
M_.param_names_tex = char(M_.param_names_tex, 'thetap\_f');
M_.param_names_long = char(M_.param_names_long, 'thetap_f');
M_.param_names = char(M_.param_names, 'xi_B');
M_.param_names_tex = char(M_.param_names_tex, 'xi\_B');
M_.param_names_long = char(M_.param_names_long, 'xi_B');
M_.param_names = char(M_.param_names, 'xi_I_h');
M_.param_names_tex = char(M_.param_names_tex, 'xi\_I\_h');
M_.param_names_long = char(M_.param_names_long, 'xi_I_h');
M_.param_names = char(M_.param_names, 'xi_I_f');
M_.param_names_tex = char(M_.param_names_tex, 'xi\_I\_f');
M_.param_names_long = char(M_.param_names_long, 'xi_I_f');
M_.param_names = char(M_.param_names, 'GYss');
M_.param_names_tex = char(M_.param_names_tex, 'GYss');
M_.param_names_long = char(M_.param_names_long, 'GYss');
M_.param_names = char(M_.param_names, 'rho_a_h');
M_.param_names_tex = char(M_.param_names_tex, 'rho\_a\_h');
M_.param_names_long = char(M_.param_names_long, 'rho_a_h');
M_.param_names = char(M_.param_names, 'rho_g_h');
M_.param_names_tex = char(M_.param_names_tex, 'rho\_g\_h');
M_.param_names_long = char(M_.param_names_long, 'rho_g_h');
M_.param_names = char(M_.param_names, 'rho_a_f');
M_.param_names_tex = char(M_.param_names_tex, 'rho\_a\_f');
M_.param_names_long = char(M_.param_names_long, 'rho_a_f');
M_.param_names = char(M_.param_names, 'rho_g_f');
M_.param_names_tex = char(M_.param_names_tex, 'rho\_g\_f');
M_.param_names_long = char(M_.param_names_long, 'rho_g_f');
M_.param_names = char(M_.param_names, 'rho_beta_f');
M_.param_names_tex = char(M_.param_names_tex, 'rho\_beta\_f');
M_.param_names_long = char(M_.param_names_long, 'rho_beta_f');
M_.param_names = char(M_.param_names, 'rho_beta_h');
M_.param_names_tex = char(M_.param_names_tex, 'rho\_beta\_h');
M_.param_names_long = char(M_.param_names_long, 'rho_beta_h');
M_.param_names = char(M_.param_names, 'rho_n_h');
M_.param_names_tex = char(M_.param_names_tex, 'rho\_n\_h');
M_.param_names_long = char(M_.param_names_long, 'rho_n_h');
M_.param_names = char(M_.param_names, 'rho_n_f');
M_.param_names_tex = char(M_.param_names_tex, 'rho\_n\_f');
M_.param_names_long = char(M_.param_names_long, 'rho_n_f');
M_.param_names = char(M_.param_names, 'rho_q_h');
M_.param_names_tex = char(M_.param_names_tex, 'rho\_q\_h');
M_.param_names_long = char(M_.param_names_long, 'rho_q_h');
M_.param_names = char(M_.param_names, 'rho_q_f');
M_.param_names_tex = char(M_.param_names_tex, 'rho\_q\_f');
M_.param_names_long = char(M_.param_names_long, 'rho_q_f');
M_.param_names = char(M_.param_names, 'rho_L_h');
M_.param_names_tex = char(M_.param_names_tex, 'rho\_L\_h');
M_.param_names_long = char(M_.param_names_long, 'rho_L_h');
M_.param_names = char(M_.param_names, 'rho_L_f');
M_.param_names_tex = char(M_.param_names_tex, 'rho\_L\_f');
M_.param_names_long = char(M_.param_names_long, 'rho_L_f');
M_.param_names = char(M_.param_names, 'rho_W_h');
M_.param_names_tex = char(M_.param_names_tex, 'rho\_W\_h');
M_.param_names_long = char(M_.param_names_long, 'rho_W_h');
M_.param_names = char(M_.param_names, 'rho_W_f');
M_.param_names_tex = char(M_.param_names_tex, 'rho\_W\_f');
M_.param_names_long = char(M_.param_names_long, 'rho_W_f');
M_.param_names = char(M_.param_names, 'rho_B_h');
M_.param_names_tex = char(M_.param_names_tex, 'rho\_B\_h');
M_.param_names_long = char(M_.param_names_long, 'rho_B_h');
M_.param_names = char(M_.param_names, 'rho_B_f');
M_.param_names_tex = char(M_.param_names_tex, 'rho\_B\_f');
M_.param_names_long = char(M_.param_names_long, 'rho_B_f');
M_.param_names = char(M_.param_names, 'u_W_h');
M_.param_names_tex = char(M_.param_names_tex, 'u\_W\_h');
M_.param_names_long = char(M_.param_names_long, 'u_W_h');
M_.param_names = char(M_.param_names, 'u_W_f');
M_.param_names_tex = char(M_.param_names_tex, 'u\_W\_f');
M_.param_names_long = char(M_.param_names_long, 'u_W_f');
M_.param_names = char(M_.param_names, 'rho_ag_h');
M_.param_names_tex = char(M_.param_names_tex, 'rho\_ag\_h');
M_.param_names_long = char(M_.param_names_long, 'rho_ag_h');
M_.param_names = char(M_.param_names, 'rho_ag_f');
M_.param_names_tex = char(M_.param_names_tex, 'rho\_ag\_f');
M_.param_names_long = char(M_.param_names_long, 'rho_ag_f');
M_.param_names = char(M_.param_names, 'phi_pi');
M_.param_names_tex = char(M_.param_names_tex, 'phi\_pi');
M_.param_names_long = char(M_.param_names_long, 'phi_pi');
M_.param_names = char(M_.param_names, 'phi_dy');
M_.param_names_tex = char(M_.param_names_tex, 'phi\_dy');
M_.param_names_long = char(M_.param_names_long, 'phi_dy');
M_.param_names = char(M_.param_names, 'rho_R');
M_.param_names_tex = char(M_.param_names_tex, 'rho\_R');
M_.param_names_long = char(M_.param_names_long, 'rho_R');
M_.param_names = char(M_.param_names, 'rho');
M_.param_names_tex = char(M_.param_names_tex, 'rho');
M_.param_names_long = char(M_.param_names_long, 'rho');
M_.param_names = char(M_.param_names, 'sigmaC_h');
M_.param_names_tex = char(M_.param_names_tex, 'sigmaC\_h');
M_.param_names_long = char(M_.param_names_long, 'sigmaC_h');
M_.param_names = char(M_.param_names, 'sigmaC_f');
M_.param_names_tex = char(M_.param_names_tex, 'sigmaC\_f');
M_.param_names_long = char(M_.param_names_long, 'sigmaC_f');
M_.param_names = char(M_.param_names, 'mu');
M_.param_names_tex = char(M_.param_names_tex, 'mu');
M_.param_names_long = char(M_.param_names_long, 'mu');
M_.param_names = char(M_.param_names, 'sigmaL_h');
M_.param_names_tex = char(M_.param_names_tex, 'sigmaL\_h');
M_.param_names_long = char(M_.param_names_long, 'sigmaL_h');
M_.param_names = char(M_.param_names, 'sigmaL_f');
M_.param_names_tex = char(M_.param_names_tex, 'sigmaL\_f');
M_.param_names_long = char(M_.param_names_long, 'sigmaL_f');
M_.param_names = char(M_.param_names, 'xiL_h');
M_.param_names_tex = char(M_.param_names_tex, 'xiL\_h');
M_.param_names_long = char(M_.param_names_long, 'xiL_h');
M_.param_names = char(M_.param_names, 'xiL_f');
M_.param_names_tex = char(M_.param_names_tex, 'xiL\_f');
M_.param_names_long = char(M_.param_names_long, 'xiL_f');
M_.param_names = char(M_.param_names, 'thetaL_h');
M_.param_names_tex = char(M_.param_names_tex, 'thetaL\_h');
M_.param_names_long = char(M_.param_names_long, 'thetaL_h');
M_.param_names = char(M_.param_names, 'thetaL_f');
M_.param_names_tex = char(M_.param_names_tex, 'thetaL\_f');
M_.param_names_long = char(M_.param_names_long, 'thetaL_f');
M_.param_names = char(M_.param_names, 'xiw_h');
M_.param_names_tex = char(M_.param_names_tex, 'xiw\_h');
M_.param_names_long = char(M_.param_names_long, 'xiw_h');
M_.param_names = char(M_.param_names, 'xiw_f');
M_.param_names_tex = char(M_.param_names_tex, 'xiw\_f');
M_.param_names_long = char(M_.param_names_long, 'xiw_f');
M_.param_names = char(M_.param_names, 'thetaw_h');
M_.param_names_tex = char(M_.param_names_tex, 'thetaw\_h');
M_.param_names_long = char(M_.param_names_long, 'thetaw_h');
M_.param_names = char(M_.param_names, 'thetaw_f');
M_.param_names_tex = char(M_.param_names_tex, 'thetaw\_f');
M_.param_names_long = char(M_.param_names_long, 'thetaw_f');
M_.param_names = char(M_.param_names, 'alpha_I');
M_.param_names_tex = char(M_.param_names_tex, 'alpha\_I');
M_.param_names_long = char(M_.param_names_long, 'alpha_I');
M_.param_names = char(M_.param_names, 'alpha_C');
M_.param_names_tex = char(M_.param_names_tex, 'alpha\_C');
M_.param_names_long = char(M_.param_names_long, 'alpha_C');
M_.param_names = char(M_.param_names, 'Rss');
M_.param_names_tex = char(M_.param_names_tex, 'Rss');
M_.param_names_long = char(M_.param_names_long, 'Rss');
M_.param_names = char(M_.param_names, 'Hss');
M_.param_names_tex = char(M_.param_names_tex, 'Hss');
M_.param_names_long = char(M_.param_names_long, 'Hss');
M_.param_names = char(M_.param_names, 'Zss');
M_.param_names_tex = char(M_.param_names_tex, 'Zss');
M_.param_names_long = char(M_.param_names_long, 'Zss');
M_.param_names = char(M_.param_names, 'Iss');
M_.param_names_tex = char(M_.param_names_tex, 'Iss');
M_.param_names_long = char(M_.param_names_long, 'Iss');
M_.param_names = char(M_.param_names, 'Qss');
M_.param_names_tex = char(M_.param_names_tex, 'Qss');
M_.param_names_long = char(M_.param_names_long, 'Qss');
M_.param_names = char(M_.param_names, 'Kss');
M_.param_names_tex = char(M_.param_names_tex, 'Kss');
M_.param_names_long = char(M_.param_names_long, 'Kss');
M_.param_names = char(M_.param_names, 'Yss');
M_.param_names_tex = char(M_.param_names_tex, 'Yss');
M_.param_names_long = char(M_.param_names_long, 'Yss');
M_.param_names = char(M_.param_names, 'Css');
M_.param_names_tex = char(M_.param_names_tex, 'Css');
M_.param_names_long = char(M_.param_names_long, 'Css');
M_.param_names = char(M_.param_names, 'Wss');
M_.param_names_tex = char(M_.param_names_tex, 'Wss');
M_.param_names_long = char(M_.param_names_long, 'Wss');
M_.param_names = char(M_.param_names, 'xip_h');
M_.param_names_tex = char(M_.param_names_tex, 'xip\_h');
M_.param_names_long = char(M_.param_names_long, 'xip_h');
M_.param_names = char(M_.param_names, 'xip_f');
M_.param_names_tex = char(M_.param_names_tex, 'xip\_f');
M_.param_names_long = char(M_.param_names_long, 'xip_f');
M_.param_names = char(M_.param_names, 'hc_h');
M_.param_names_tex = char(M_.param_names_tex, 'hc\_h');
M_.param_names_long = char(M_.param_names_long, 'hc_h');
M_.param_names = char(M_.param_names, 'hc_f');
M_.param_names_tex = char(M_.param_names_tex, 'hc\_f');
M_.param_names_long = char(M_.param_names_long, 'hc_f');
M_.param_names = char(M_.param_names, 'psi_h');
M_.param_names_tex = char(M_.param_names_tex, 'psi\_h');
M_.param_names_long = char(M_.param_names_long, 'psi_h');
M_.param_names = char(M_.param_names, 'psi_f');
M_.param_names_tex = char(M_.param_names_tex, 'psi\_f');
M_.param_names_long = char(M_.param_names_long, 'psi_f');
M_.param_names = char(M_.param_names, 'ETA_Sss');
M_.param_names_tex = char(M_.param_names_tex, 'ETA\_Sss');
M_.param_names_long = char(M_.param_names_long, 'ETA_Sss');
M_.param_names = char(M_.param_names, 'gamma_E');
M_.param_names_tex = char(M_.param_names_tex, 'gamma\_E');
M_.param_names_long = char(M_.param_names_long, 'gamma_E');
M_.param_names = char(M_.param_names, 'RKss');
M_.param_names_tex = char(M_.param_names_tex, 'RKss');
M_.param_names_long = char(M_.param_names_long, 'RKss');
M_.param_names = char(M_.param_names, 'RRLss');
M_.param_names_tex = char(M_.param_names_tex, 'RRLss');
M_.param_names_long = char(M_.param_names_long, 'RRLss');
M_.param_names = char(M_.param_names, 'Nss');
M_.param_names_tex = char(M_.param_names_tex, 'Nss');
M_.param_names_long = char(M_.param_names_long, 'Nss');
M_.param_names = char(M_.param_names, 'Lss');
M_.param_names_tex = char(M_.param_names_tex, 'Lss');
M_.param_names_long = char(M_.param_names_long, 'Lss');
M_.param_names = char(M_.param_names, 'NKss');
M_.param_names_tex = char(M_.param_names_tex, 'NKss');
M_.param_names_long = char(M_.param_names_long, 'NKss');
M_.param_names = char(M_.param_names, 'OMEGAss');
M_.param_names_tex = char(M_.param_names_tex, 'OMEGAss');
M_.param_names_long = char(M_.param_names_long, 'OMEGAss');
M_.param_names = char(M_.param_names, 'ka');
M_.param_names_tex = char(M_.param_names_tex, 'ka');
M_.param_names_long = char(M_.param_names_long, 'ka');
M_.param_names = char(M_.param_names, 'wmin');
M_.param_names_tex = char(M_.param_names_tex, 'wmin');
M_.param_names_long = char(M_.param_names_long, 'wmin');
M_.param_names = char(M_.param_names, 'w_sup');
M_.param_names_tex = char(M_.param_names_tex, 'w\_sup');
M_.param_names_long = char(M_.param_names_long, 'w_sup');
M_.param_names = char(M_.param_names, 'w_inf');
M_.param_names_tex = char(M_.param_names_tex, 'w\_inf');
M_.param_names_long = char(M_.param_names_long, 'w_inf');
M_.param_names = char(M_.param_names, 'varkappa_h');
M_.param_names_tex = char(M_.param_names_tex, 'varkappa\_h');
M_.param_names_long = char(M_.param_names_long, 'varkappa_h');
M_.param_names = char(M_.param_names, 'varkappa_f');
M_.param_names_tex = char(M_.param_names_tex, 'varkappa\_f');
M_.param_names_long = char(M_.param_names_long, 'varkappa_f');
M_.param_names = char(M_.param_names, 'chi_IB_h');
M_.param_names_tex = char(M_.param_names_tex, 'chi\_IB\_h');
M_.param_names_long = char(M_.param_names_long, 'chi_IB_h');
M_.param_names = char(M_.param_names, 'chi_IB_f');
M_.param_names_tex = char(M_.param_names_tex, 'chi\_IB\_f');
M_.param_names_long = char(M_.param_names_long, 'chi_IB_f');
M_.param_names = char(M_.param_names, 'gammatild_E');
M_.param_names_tex = char(M_.param_names_tex, 'gammatild\_E');
M_.param_names_long = char(M_.param_names_long, 'gammatild_E');
M_.param_names = char(M_.param_names, 'gamma_B');
M_.param_names_tex = char(M_.param_names_tex, 'gamma\_B');
M_.param_names_long = char(M_.param_names_long, 'gamma_B');
M_.param_names = char(M_.param_names, 'hL_h');
M_.param_names_tex = char(M_.param_names_tex, 'hL\_h');
M_.param_names_long = char(M_.param_names_long, 'hL_h');
M_.param_names = char(M_.param_names, 'hL_f');
M_.param_names_tex = char(M_.param_names_tex, 'hL\_f');
M_.param_names_long = char(M_.param_names_long, 'hL_f');
M_.param_names = char(M_.param_names, 'alpha_L');
M_.param_names_tex = char(M_.param_names_tex, 'alpha\_L');
M_.param_names_long = char(M_.param_names_long, 'alpha_L');
M_.param_names = char(M_.param_names, 'alpha_IB');
M_.param_names_tex = char(M_.param_names_tex, 'alpha\_IB');
M_.param_names_long = char(M_.param_names_long, 'alpha_IB');
M_.param_names = char(M_.param_names, 'nu');
M_.param_names_tex = char(M_.param_names_tex, 'nu');
M_.param_names_long = char(M_.param_names_long, 'nu');
M_.param_names = char(M_.param_names, 'xi');
M_.param_names_tex = char(M_.param_names_tex, 'xi');
M_.param_names_long = char(M_.param_names_long, 'xi');
M_.param_names = char(M_.param_names, 'Vss');
M_.param_names_tex = char(M_.param_names_tex, 'Vss');
M_.param_names_long = char(M_.param_names_long, 'Vss');
M_.param_names = char(M_.param_names, 'BKss');
M_.param_names_tex = char(M_.param_names_tex, 'BKss');
M_.param_names_long = char(M_.param_names_long, 'BKss');
M_.param_names = char(M_.param_names, 'IBss');
M_.param_names_tex = char(M_.param_names_tex, 'IBss');
M_.param_names_long = char(M_.param_names_long, 'IBss');
M_.param_names = char(M_.param_names, 'RFss');
M_.param_names_tex = char(M_.param_names_tex, 'RFss');
M_.param_names_long = char(M_.param_names_long, 'RFss');
M_.param_names = char(M_.param_names, 'lambda');
M_.param_names_tex = char(M_.param_names_tex, 'lambda');
M_.param_names_long = char(M_.param_names_long, 'lambda');
M_.param_names = char(M_.param_names, 'hib_h');
M_.param_names_tex = char(M_.param_names_tex, 'hib\_h');
M_.param_names_long = char(M_.param_names_long, 'hib_h');
M_.param_names = char(M_.param_names, 'hib_f');
M_.param_names_tex = char(M_.param_names_tex, 'hib\_f');
M_.param_names_long = char(M_.param_names_long, 'hib_f');
M_.exo_det_nbr = 0;
M_.exo_nbr = 26;
M_.endo_nbr = 210;
M_.param_nbr = 127;
M_.orig_endo_nbr = 175;
M_.aux_vars(1).endo_index = 176;
M_.aux_vars(1).type = 0;
M_.aux_vars(2).endo_index = 177;
M_.aux_vars(2).type = 0;
M_.aux_vars(3).endo_index = 178;
M_.aux_vars(3).type = 0;
M_.aux_vars(4).endo_index = 179;
M_.aux_vars(4).type = 0;
M_.aux_vars(5).endo_index = 180;
M_.aux_vars(5).type = 0;
M_.aux_vars(6).endo_index = 181;
M_.aux_vars(6).type = 0;
M_.aux_vars(7).endo_index = 182;
M_.aux_vars(7).type = 0;
M_.aux_vars(8).endo_index = 183;
M_.aux_vars(8).type = 0;
M_.aux_vars(9).endo_index = 184;
M_.aux_vars(9).type = 0;
M_.aux_vars(10).endo_index = 185;
M_.aux_vars(10).type = 0;
M_.aux_vars(11).endo_index = 186;
M_.aux_vars(11).type = 0;
M_.aux_vars(12).endo_index = 187;
M_.aux_vars(12).type = 1;
M_.aux_vars(12).orig_index = 10;
M_.aux_vars(12).orig_lead_lag = -1;
M_.aux_vars(13).endo_index = 188;
M_.aux_vars(13).type = 1;
M_.aux_vars(13).orig_index = 10;
M_.aux_vars(13).orig_lead_lag = -2;
M_.aux_vars(14).endo_index = 189;
M_.aux_vars(14).type = 1;
M_.aux_vars(14).orig_index = 175;
M_.aux_vars(14).orig_lead_lag = -1;
M_.aux_vars(15).endo_index = 190;
M_.aux_vars(15).type = 1;
M_.aux_vars(15).orig_index = 175;
M_.aux_vars(15).orig_lead_lag = -2;
M_.aux_vars(16).endo_index = 191;
M_.aux_vars(16).type = 1;
M_.aux_vars(16).orig_index = 175;
M_.aux_vars(16).orig_lead_lag = -3;
M_.aux_vars(17).endo_index = 192;
M_.aux_vars(17).type = 1;
M_.aux_vars(17).orig_index = 174;
M_.aux_vars(17).orig_lead_lag = -1;
M_.aux_vars(18).endo_index = 193;
M_.aux_vars(18).type = 1;
M_.aux_vars(18).orig_index = 174;
M_.aux_vars(18).orig_lead_lag = -2;
M_.aux_vars(19).endo_index = 194;
M_.aux_vars(19).type = 1;
M_.aux_vars(19).orig_index = 174;
M_.aux_vars(19).orig_lead_lag = -3;
M_.aux_vars(20).endo_index = 195;
M_.aux_vars(20).type = 1;
M_.aux_vars(20).orig_index = 171;
M_.aux_vars(20).orig_lead_lag = -1;
M_.aux_vars(21).endo_index = 196;
M_.aux_vars(21).type = 1;
M_.aux_vars(21).orig_index = 171;
M_.aux_vars(21).orig_lead_lag = -2;
M_.aux_vars(22).endo_index = 197;
M_.aux_vars(22).type = 1;
M_.aux_vars(22).orig_index = 171;
M_.aux_vars(22).orig_lead_lag = -3;
M_.aux_vars(23).endo_index = 198;
M_.aux_vars(23).type = 1;
M_.aux_vars(23).orig_index = 173;
M_.aux_vars(23).orig_lead_lag = -1;
M_.aux_vars(24).endo_index = 199;
M_.aux_vars(24).type = 1;
M_.aux_vars(24).orig_index = 173;
M_.aux_vars(24).orig_lead_lag = -2;
M_.aux_vars(25).endo_index = 200;
M_.aux_vars(25).type = 1;
M_.aux_vars(25).orig_index = 173;
M_.aux_vars(25).orig_lead_lag = -3;
M_.aux_vars(26).endo_index = 201;
M_.aux_vars(26).type = 1;
M_.aux_vars(26).orig_index = 43;
M_.aux_vars(26).orig_lead_lag = -1;
M_.aux_vars(27).endo_index = 202;
M_.aux_vars(27).type = 1;
M_.aux_vars(27).orig_index = 44;
M_.aux_vars(27).orig_lead_lag = -1;
M_.aux_vars(28).endo_index = 203;
M_.aux_vars(28).type = 1;
M_.aux_vars(28).orig_index = 58;
M_.aux_vars(28).orig_lead_lag = -1;
M_.aux_vars(29).endo_index = 204;
M_.aux_vars(29).type = 1;
M_.aux_vars(29).orig_index = 59;
M_.aux_vars(29).orig_lead_lag = -1;
M_.aux_vars(30).endo_index = 205;
M_.aux_vars(30).type = 1;
M_.aux_vars(30).orig_index = 75;
M_.aux_vars(30).orig_lead_lag = -1;
M_.aux_vars(31).endo_index = 206;
M_.aux_vars(31).type = 1;
M_.aux_vars(31).orig_index = 76;
M_.aux_vars(31).orig_lead_lag = -1;
M_.aux_vars(32).endo_index = 207;
M_.aux_vars(32).type = 1;
M_.aux_vars(32).orig_index = 137;
M_.aux_vars(32).orig_lead_lag = -1;
M_.aux_vars(33).endo_index = 208;
M_.aux_vars(33).type = 1;
M_.aux_vars(33).orig_index = 138;
M_.aux_vars(33).orig_lead_lag = -1;
M_.aux_vars(34).endo_index = 209;
M_.aux_vars(34).type = 1;
M_.aux_vars(34).orig_index = 169;
M_.aux_vars(34).orig_lead_lag = -1;
M_.aux_vars(35).endo_index = 210;
M_.aux_vars(35).type = 1;
M_.aux_vars(35).orig_index = 170;
M_.aux_vars(35).orig_lead_lag = -1;
M_.Sigma_e = zeros(26, 26);
M_.Correlation_matrix = eye(26, 26);
M_.H = 0;
M_.Correlation_matrix_ME = 1;
M_.sigma_e_is_diagonal = 1;
options_.linear = 1;
options_.block=0;
options_.bytecode=0;
options_.use_dll=0;
erase_compiled_function('EA_PV15_static');
erase_compiled_function('EA_PV15_dynamic');
M_.lead_lag_incidence = [
 0 104 0;
 0 105 0;
 0 106 0;
 1 107 314;
 2 108 315;
 0 109 0;
 0 110 0;
 3 111 316;
 4 112 317;
 5 113 0;
 6 114 318;
 7 115 319;
 8 116 320;
 9 117 321;
 0 118 0;
 0 119 0;
 0 120 0;
 0 121 0;
 0 122 0;
 0 123 0;
 10 124 0;
 11 125 0;
 12 126 322;
 13 127 323;
 0 128 0;
 0 129 0;
 0 130 0;
 14 131 0;
 15 132 0;
 16 133 0;
 17 134 0;
 0 135 0;
 0 136 0;
 0 137 0;
 0 138 0;
 0 139 0;
 0 140 0;
 0 141 0;
 0 142 0;
 0 143 0;
 0 144 324;
 0 145 325;
 18 146 0;
 19 147 0;
 0 148 0;
 0 149 0;
 0 150 0;
 0 151 0;
 20 152 0;
 21 153 0;
 0 154 0;
 0 155 0;
 0 156 0;
 0 157 0;
 22 158 0;
 23 159 0;
 0 160 0;
 24 161 326;
 25 162 327;
 0 163 0;
 0 164 0;
 26 165 0;
 27 166 0;
 0 167 0;
 0 168 0;
 0 169 0;
 0 170 0;
 0 171 0;
 0 172 0;
 0 173 0;
 28 174 0;
 29 175 0;
 30 176 0;
 31 177 0;
 32 178 0;
 33 179 0;
 34 180 0;
 35 181 0;
 36 182 0;
 37 183 0;
 38 184 328;
 39 185 329;
 40 186 0;
 41 187 0;
 42 188 0;
 43 189 0;
 44 190 0;
 45 191 0;
 46 192 0;
 47 193 0;
 48 194 0;
 49 195 0;
 50 196 0;
 0 197 0;
 0 198 0;
 0 199 0;
 51 200 330;
 52 201 331;
 0 202 0;
 0 203 0;
 0 204 0;
 0 205 0;
 0 206 332;
 0 207 333;
 0 208 0;
 0 209 0;
 0 210 0;
 0 211 0;
 0 212 0;
 0 213 0;
 0 214 0;
 0 215 0;
 53 216 0;
 54 217 0;
 55 218 334;
 56 219 335;
 0 220 0;
 0 221 0;
 0 222 0;
 57 223 0;
 58 224 0;
 0 225 336;
 59 226 0;
 0 227 0;
 0 228 0;
 0 229 0;
 0 230 0;
 0 231 0;
 0 232 337;
 0 233 338;
 0 234 0;
 0 235 0;
 0 236 0;
 0 237 0;
 0 238 339;
 0 239 340;
 60 240 0;
 61 241 0;
 0 242 0;
 0 243 0;
 0 244 0;
 0 245 0;
 62 246 0;
 63 247 0;
 0 248 0;
 0 249 0;
 0 250 0;
 0 251 0;
 64 252 0;
 65 253 0;
 0 254 0;
 66 255 0;
 67 256 0;
 0 257 0;
 0 258 0;
 68 259 0;
 69 260 0;
 0 261 0;
 0 262 0;
 0 263 0;
 0 264 0;
 0 265 0;
 0 266 0;
 0 267 0;
 70 268 0;
 71 269 0;
 72 270 0;
 73 271 0;
 74 272 0;
 75 273 0;
 76 274 0;
 0 275 0;
 77 276 341;
 78 277 342;
 79 278 343;
 0 279 344;
 0 280 345;
 0 281 346;
 0 282 347;
 0 283 348;
 0 284 349;
 0 285 350;
 0 286 351;
 0 287 352;
 0 288 353;
 0 289 354;
 80 290 0;
 81 291 0;
 82 292 0;
 83 293 0;
 84 294 0;
 85 295 0;
 86 296 0;
 87 297 0;
 88 298 0;
 89 299 0;
 90 300 0;
 91 301 0;
 92 302 0;
 93 303 0;
 94 304 0;
 95 305 0;
 96 306 0;
 97 307 0;
 98 308 0;
 99 309 0;
 100 310 0;
 101 311 0;
 102 312 0;
 103 313 0;]';
M_.nstatic = 87;
M_.nfwrd   = 20;
M_.npred   = 82;
M_.nboth   = 21;
M_.nsfwrd   = 41;
M_.nspred   = 103;
M_.ndynamic   = 123;
M_.equations_tags = {
};
M_.static_and_dynamic_models_differ = 0;
M_.exo_names_orig_ord = [1:26];
M_.maximum_lag = 1;
M_.maximum_lead = 1;
M_.maximum_endo_lag = 1;
M_.maximum_endo_lead = 1;
oo_.steady_state = zeros(210, 1);
M_.maximum_exo_lag = 1;
M_.maximum_exo_lead = 0;
oo_.exo_steady_state = zeros(26, 1);
M_.params = NaN(127, 1);
M_.NNZDerivatives = zeros(3, 1);
M_.NNZDerivatives(1) = 892;
M_.NNZDerivatives(2) = 0;
M_.NNZDerivatives(3) = -1;
thispath = cd;                                                           
cd('..');                                                                
load policy_param.mat;                                                   
for i=1:33                                                               
deep_parameter_name = M_.param_names(i,:);                           
eval(['M_.params(i)  = ' deep_parameter_name ' ;'])                  
end                                                                      
cd(thispath);                                                                         
M_.params( 34 ) = 0.995;
beta = M_.params( 34 );
M_.params( 36 ) = 0.02;
delta = M_.params( 36 );
M_.params( 35 ) = 0.25;
alpha = M_.params( 35 );
M_.params( 42 ) = 0.24;
GYss = M_.params( 42 );
M_.params( 39 ) = 0.0007;
xi_B = M_.params( 39 );
M_.params( 103 ) = 0.40;
NKss = M_.params( 103 );
SLss		= 2/400;	
M_.params( 83 ) = 0.3333333333333333;
Hss = M_.params( 83 );
M_.params( 67 ) = 2;
sigmaC_h = M_.params( 67 );
M_.params( 68 ) = 2.04;
sigmaC_f = M_.params( 68 );
M_.params( 93 ) = 0.32;
hc_h = M_.params( 93 );
M_.params( 94 ) = 0.57;
hc_f = M_.params( 94 );
M_.params( 70 ) = .59;
sigmaL_h = M_.params( 70 );
M_.params( 71 ) = .66;
sigmaL_f = M_.params( 71 );
M_.params( 37 ) = 0.56;
thetap_h = M_.params( 37 );
M_.params( 38 ) = 0.56;
thetap_f = M_.params( 38 );
M_.params( 91 ) = 0.07;
xip_h = M_.params( 91 );
M_.params( 92 ) = 0.08;
xip_f = M_.params( 92 );
M_.params( 78 ) = 0.67;
thetaw_h = M_.params( 78 );
M_.params( 79 ) = 0.6;
thetaw_f = M_.params( 79 );
M_.params( 76 ) = 0.46;
xiw_h = M_.params( 76 );
M_.params( 77 ) = 0.36;
xiw_f = M_.params( 77 );
M_.params( 74 ) = 0.29;
thetaL_h = M_.params( 74 );
M_.params( 75 ) = 0.31;
thetaL_f = M_.params( 75 );
M_.params( 72 ) = 0.12;
xiL_h = M_.params( 72 );
M_.params( 73 ) = 0.21;
xiL_f = M_.params( 73 );
M_.params( 40 ) = 0.63;
xi_I_h = M_.params( 40 );
M_.params( 41 ) = 1.87;
xi_I_f = M_.params( 41 );
M_.params( 111 ) = 0.48;
chi_IB_h = M_.params( 111 );
M_.params( 112 ) = 0.23;
chi_IB_f = M_.params( 112 );
M_.params( 95 ) = 0.66;
psi_h = M_.params( 95 );
M_.params( 96 ) = 0.68;
psi_f = M_.params( 96 );
M_.params( 109 ) = 0.05;
varkappa_h = M_.params( 109 );
M_.params( 110 ) = 0.08;
varkappa_f = M_.params( 110 );
M_.params( 115 ) = 0.96;
hL_h = M_.params( 115 );
M_.params( 116 ) = 0.95;
hL_f = M_.params( 116 );
M_.params( 126 ) = 0.20;
hib_h = M_.params( 126 );
M_.params( 127 ) = 0.21;
hib_f = M_.params( 127 );
M_.params( 125 ) = 0.25;
lambda = M_.params( 125 );
M_.params( 63 ) = 1.85;
phi_pi = M_.params( 63 );
M_.params( 64 ) = 0.15;
phi_dy = M_.params( 64 );
M_.params( 66 ) = 0.84;
rho = M_.params( 66 );
M_.params( 81 ) = 0.17;
alpha_C = M_.params( 81 );
M_.params( 80 ) = 0.06;
alpha_I = M_.params( 80 );
M_.params( 117 ) = 0.09;
alpha_L = M_.params( 117 );
M_.params( 118 ) = 0.11;
alpha_IB = M_.params( 118 );
M_.params( 69 ) = 4.43;
mu = M_.params( 69 );
M_.params( 119 ) = 2.02;
nu = M_.params( 119 );
M_.params( 120 ) = 0.87;
xi = M_.params( 120 );
M_.params( 43 ) = 0.99;
rho_a_h = M_.params( 43 );
M_.params( 45 ) = 0.99;
rho_a_f = M_.params( 45 );
M_.params( 44 ) = 0.93;
rho_g_h = M_.params( 44 );
M_.params( 46 ) = 0.91;
rho_g_f = M_.params( 46 );
M_.params( 48 ) = 0.81;
rho_beta_h = M_.params( 48 );
M_.params( 47 ) = 0.54;
rho_beta_f = M_.params( 47 );
M_.params( 49 ) = 0.96;
rho_n_h = M_.params( 49 );
M_.params( 50 ) = 0.96;
rho_n_f = M_.params( 50 );
M_.params( 51 ) = 0.47;
rho_q_h = M_.params( 51 );
M_.params( 52 ) = 0.59;
rho_q_f = M_.params( 52 );
M_.params( 53 ) = 0.99;
rho_L_h = M_.params( 53 );
M_.params( 54 ) = 0.90;
rho_L_f = M_.params( 54 );
M_.params( 57 ) = 0.90;
rho_B_h = M_.params( 57 );
M_.params( 58 ) = 0.93;
rho_B_f = M_.params( 58 );
M_.params( 55 ) = 0.99;
rho_W_h = M_.params( 55 );
M_.params( 56 ) = 0.99;
rho_W_f = M_.params( 56 );
M_.params( 59 ) = 0.51;
u_W_h = M_.params( 59 );
M_.params( 60 ) = 0.28;
u_W_f = M_.params( 60 );
M_.params( 65 ) = 0.41;
rho_R = M_.params( 65 );
M_.params( 61 ) = 0.84;
rho_ag_h = M_.params( 61 );
M_.params( 62 ) = 0.83;
rho_ag_f = M_.params( 62 );
M_.params( 82 ) = 1/M_.params(34);
Rss = M_.params( 82 );
M_.params( 100 ) = M_.params(82)+SLss;
RRLss = M_.params( 100 );
M_.params( 106 ) = 1-M_.params(103);
wmin = M_.params( 106 );
M_.params( 105 ) = 1/M_.params(103);
ka = M_.params( 105 );
M_.params( 104 ) = M_.params(106)*(M_.params(100)/M_.params(82))^(1/M_.params(105));
OMEGAss = M_.params( 104 );
M_.params( 99 ) = (1-M_.params(103))*M_.params(100)/M_.params(104);
RKss = M_.params( 99 );
Gw			= 1-((wmin/OMEGAss)^(ka-1));
ETA_Dss 	= 1-(wmin/OMEGAss)^ka;
M_.params( 97 ) = (M_.params(106)/M_.params(104))^M_.params(105);
ETA_Sss = M_.params( 97 );
M_.params( 107 ) = M_.params(104)*M_.params(105)/(M_.params(105)-1);
w_sup = M_.params( 107 );
M_.params( 108 ) = M_.params(105)/(M_.params(105)-1)*(M_.params(104)^(1-M_.params(105))-M_.params(106)^(1-M_.params(105)))/(M_.params(104)^(-M_.params(105))-M_.params(106)^(-M_.params(105)));
w_inf = M_.params( 108 );
M_.params( 86 ) = 1;
Qss = M_.params( 86 );
M_.params( 87 ) = ((M_.params(99)*M_.params(86)-M_.params(86)*(1-M_.params(36)))/(M_.params(35)*M_.params(83)^(1-M_.params(35))))^(1/(M_.params(35)-1));
Kss = M_.params( 87 );
M_.params( 101 ) = M_.params(103)*M_.params(86)*M_.params(87);
Nss = M_.params( 101 );
M_.params( 102 ) = M_.params(86)*M_.params(87)-M_.params(101);
Lss = M_.params( 102 );
gammatild_E_h=w_sup^(1-varkappa_h);
gammatild_E_f=w_sup^(1-varkappa_f);
M_.params( 121 ) = M_.params(99)*M_.params(87)*M_.params(104)*M_.params(97)/(M_.params(105)-1);
Vss = M_.params( 121 );
M_.params( 98 ) = M_.params(101)/M_.params(121);
gamma_E = M_.params( 98 );
M_.params( 84 ) = M_.params(99)*M_.params(86)-M_.params(86)*(1-M_.params(36));
Zss = M_.params( 84 );
M_.params( 88 ) = M_.params(87)*M_.params(84)/M_.params(35);
Yss = M_.params( 88 );
M_.params( 90 ) = (1-M_.params(35))*M_.params(88)/M_.params(83);
Wss = M_.params( 90 );
M_.params( 89 ) = M_.params(88)*(1-M_.params(42))-M_.params(36)*M_.params(87);
Css = M_.params( 89 );
M_.params( 85 ) = M_.params(36)*M_.params(87);
Iss = M_.params( 85 );
M_.params( 122 ) = 0.11*M_.params(102);
BKss = M_.params( 122 );
M_.params( 123 ) = M_.params(102)*0.2;
IBss = M_.params( 123 );
M_.params( 124 ) = M_.params(102)-M_.params(122)-M_.params(123);
RFss = M_.params( 124 );
PI_Bss 		= (ETA_Sss*RRLss*Lss - Rss*IBss);
M_.params( 114 ) = 1-M_.params(122)/PI_Bss;
gamma_B = M_.params( 114 );
%
% SHOCKS instructions
%
make_ex_;
M_.exo_det_length = 0;
M_.Sigma_e(1, 1) = (.88)^2;
M_.Sigma_e(7, 7) = (0.14)^2;
M_.Sigma_e(15, 15) = (2.28)^2;
save('EA_PV15_results.mat', 'oo_', 'M_', 'options_');
if exist('estim_params_', 'var') == 1
  save('EA_PV15_results.mat', 'estim_params_', '-append');
end
if exist('bayestopt_', 'var') == 1
  save('EA_PV15_results.mat', 'bayestopt_', '-append');
end
if exist('dataset_', 'var') == 1
  save('EA_PV15_results.mat', 'dataset_', '-append');
end
if exist('estimation_info', 'var') == 1
  save('EA_PV15_results.mat', 'estimation_info', '-append');
end


disp(['Total computing time : ' dynsec2hms(toc) ]);
if ~isempty(lastwarn)
  disp('Note: warning(s) encountered in MATLAB/Octave code')
end
diary off
