%
% Status : main Dynare file
%
% Warning : this file is generated automatically by Dynare
%           from model file (.mod)

tic0 = tic;
% Save empty dates and dseries objects in memory.
dates('initialize');
dseries('initialize');
% Define global variables.
global M_ options_ oo_ estim_params_ bayestopt_ dataset_ dataset_info estimation_info ys0_ ex0_
options_ = [];
M_.fname = 'NK_KW16';
M_.dynare_version = '4.5.4';
oo_.dynare_version = '4.5.4';
options_.dynare_version = '4.5.4';
%
% Some global variables initialization
%
global_initialization;
diary off;
diary('NK_KW16.log');
M_.exo_names = 'e_ksi';
M_.exo_names_tex = 'e\_ksi';
M_.exo_names_long = 'e_ksi';
M_.exo_names = char(M_.exo_names, 'e_a');
M_.exo_names_tex = char(M_.exo_names_tex, 'e\_a');
M_.exo_names_long = char(M_.exo_names_long, 'e_a');
M_.exo_names = char(M_.exo_names, 'interest_');
M_.exo_names_tex = char(M_.exo_names_tex, 'interest\_');
M_.exo_names_long = char(M_.exo_names_long, 'interest_');
M_.exo_names = char(M_.exo_names, 'fiscal_');
M_.exo_names_tex = char(M_.exo_names_tex, 'fiscal\_');
M_.exo_names_long = char(M_.exo_names_long, 'fiscal_');
M_.endo_names = 'interest';
M_.endo_names_tex = 'interest';
M_.endo_names_long = 'interest';
M_.endo_names = char(M_.endo_names, 'inflation');
M_.endo_names_tex = char(M_.endo_names_tex, 'inflation');
M_.endo_names_long = char(M_.endo_names_long, 'inflation');
M_.endo_names = char(M_.endo_names, 'inflationq');
M_.endo_names_tex = char(M_.endo_names_tex, 'inflationq');
M_.endo_names_long = char(M_.endo_names_long, 'inflationq');
M_.endo_names = char(M_.endo_names, 'outputgap');
M_.endo_names_tex = char(M_.endo_names_tex, 'outputgap');
M_.endo_names_long = char(M_.endo_names_long, 'outputgap');
M_.endo_names = char(M_.endo_names, 'output');
M_.endo_names_tex = char(M_.endo_names_tex, 'output');
M_.endo_names_long = char(M_.endo_names_long, 'output');
M_.endo_names = char(M_.endo_names, 'fispol');
M_.endo_names_tex = char(M_.endo_names_tex, 'fispol');
M_.endo_names_long = char(M_.endo_names_long, 'fispol');
M_.endo_names = char(M_.endo_names, 'Y');
M_.endo_names_tex = char(M_.endo_names_tex, 'Y');
M_.endo_names_long = char(M_.endo_names_long, 'Y');
M_.endo_names = char(M_.endo_names, 'Ym');
M_.endo_names_tex = char(M_.endo_names_tex, 'Ym');
M_.endo_names_long = char(M_.endo_names_long, 'Ym');
M_.endo_names = char(M_.endo_names, 'L');
M_.endo_names_tex = char(M_.endo_names_tex, 'L');
M_.endo_names_long = char(M_.endo_names_long, 'L');
M_.endo_names = char(M_.endo_names, 'w');
M_.endo_names_tex = char(M_.endo_names_tex, 'w');
M_.endo_names_long = char(M_.endo_names_long, 'w');
M_.endo_names = char(M_.endo_names, 'C');
M_.endo_names_tex = char(M_.endo_names_tex, 'C');
M_.endo_names_long = char(M_.endo_names_long, 'C');
M_.endo_names = char(M_.endo_names, 'U_c');
M_.endo_names_tex = char(M_.endo_names_tex, 'U\_c');
M_.endo_names_long = char(M_.endo_names_long, 'U_c');
M_.endo_names = char(M_.endo_names, 'Lambda');
M_.endo_names_tex = char(M_.endo_names_tex, 'Lambda');
M_.endo_names_long = char(M_.endo_names_long, 'Lambda');
M_.endo_names = char(M_.endo_names, 'I');
M_.endo_names_tex = char(M_.endo_names_tex, 'I');
M_.endo_names_long = char(M_.endo_names_long, 'I');
M_.endo_names = char(M_.endo_names, 'K');
M_.endo_names_tex = char(M_.endo_names_tex, 'K');
M_.endo_names_long = char(M_.endo_names_long, 'K');
M_.endo_names = char(M_.endo_names, 'Q');
M_.endo_names_tex = char(M_.endo_names_tex, 'Q');
M_.endo_names_long = char(M_.endo_names_long, 'Q');
M_.endo_names = char(M_.endo_names, 'a');
M_.endo_names_tex = char(M_.endo_names_tex, 'a');
M_.endo_names_long = char(M_.endo_names_long, 'a');
M_.endo_names = char(M_.endo_names, 'ksi');
M_.endo_names_tex = char(M_.endo_names_tex, 'ksi');
M_.endo_names_long = char(M_.endo_names_long, 'ksi');
M_.endo_names = char(M_.endo_names, 'Pm');
M_.endo_names_tex = char(M_.endo_names_tex, 'Pm');
M_.endo_names_long = char(M_.endo_names_long, 'Pm');
M_.endo_names = char(M_.endo_names, 'infl');
M_.endo_names_tex = char(M_.endo_names_tex, 'infl');
M_.endo_names_long = char(M_.endo_names_long, 'infl');
M_.endo_names = char(M_.endo_names, 'inflstar');
M_.endo_names_tex = char(M_.endo_names_tex, 'inflstar');
M_.endo_names_long = char(M_.endo_names_long, 'inflstar');
M_.endo_names = char(M_.endo_names, 'F');
M_.endo_names_tex = char(M_.endo_names_tex, 'F');
M_.endo_names_long = char(M_.endo_names_long, 'F');
M_.endo_names = char(M_.endo_names, 'Z');
M_.endo_names_tex = char(M_.endo_names_tex, 'Z');
M_.endo_names_long = char(M_.endo_names_long, 'Z');
M_.endo_names = char(M_.endo_names, 'Dis');
M_.endo_names_tex = char(M_.endo_names_tex, 'Dis');
M_.endo_names_long = char(M_.endo_names_long, 'Dis');
M_.endo_names = char(M_.endo_names, 'Rd');
M_.endo_names_tex = char(M_.endo_names_tex, 'Rd');
M_.endo_names_long = char(M_.endo_names_long, 'Rd');
M_.endo_names = char(M_.endo_names, 'i');
M_.endo_names_tex = char(M_.endo_names_tex, 'i');
M_.endo_names_long = char(M_.endo_names_long, 'i');
M_.endo_names = char(M_.endo_names, 'Rk');
M_.endo_names_tex = char(M_.endo_names_tex, 'Rk');
M_.endo_names_long = char(M_.endo_names_long, 'Rk');
M_.endo_names = char(M_.endo_names, 'Rb');
M_.endo_names_tex = char(M_.endo_names_tex, 'Rb');
M_.endo_names_long = char(M_.endo_names_long, 'Rb');
M_.endo_names = char(M_.endo_names, 'Rp');
M_.endo_names_tex = char(M_.endo_names_tex, 'Rp');
M_.endo_names_long = char(M_.endo_names_long, 'Rp');
M_.endo_names = char(M_.endo_names, 'ERk');
M_.endo_names_tex = char(M_.endo_names_tex, 'ERk');
M_.endo_names_long = char(M_.endo_names_long, 'ERk');
M_.endo_names = char(M_.endo_names, 'ERb');
M_.endo_names_tex = char(M_.endo_names_tex, 'ERb');
M_.endo_names_long = char(M_.endo_names_long, 'ERb');
M_.endo_names = char(M_.endo_names, 'prem');
M_.endo_names_tex = char(M_.endo_names_tex, 'prem');
M_.endo_names_long = char(M_.endo_names_long, 'prem');
M_.endo_names = char(M_.endo_names, 'prem2');
M_.endo_names_tex = char(M_.endo_names_tex, 'prem2');
M_.endo_names_long = char(M_.endo_names_long, 'prem2');
M_.endo_names = char(M_.endo_names, 'Phi');
M_.endo_names_tex = char(M_.endo_names_tex, 'Phi');
M_.endo_names_long = char(M_.endo_names_long, 'Phi');
M_.endo_names = char(M_.endo_names, 'portf_B');
M_.endo_names_tex = char(M_.endo_names_tex, 'portf\_B');
M_.endo_names_long = char(M_.endo_names_long, 'portf_B');
M_.endo_names = char(M_.endo_names, 'N');
M_.endo_names_tex = char(M_.endo_names_tex, 'N');
M_.endo_names_long = char(M_.endo_names_long, 'N');
M_.endo_names = char(M_.endo_names, 'Om');
M_.endo_names_tex = char(M_.endo_names_tex, 'Om');
M_.endo_names_long = char(M_.endo_names_long, 'Om');
M_.endo_names = char(M_.endo_names, 'D');
M_.endo_names_tex = char(M_.endo_names_tex, 'D');
M_.endo_names_long = char(M_.endo_names_long, 'D');
M_.endo_names = char(M_.endo_names, 'nu_k');
M_.endo_names_tex = char(M_.endo_names_tex, 'nu\_k');
M_.endo_names_long = char(M_.endo_names_long, 'nu_k');
M_.endo_names = char(M_.endo_names, 'nu_b');
M_.endo_names_tex = char(M_.endo_names_tex, 'nu\_b');
M_.endo_names_long = char(M_.endo_names_long, 'nu_b');
M_.endo_names = char(M_.endo_names, 'nu_n');
M_.endo_names_tex = char(M_.endo_names_tex, 'nu\_n');
M_.endo_names_long = char(M_.endo_names_long, 'nu_n');
M_.endo_names = char(M_.endo_names, 'G');
M_.endo_names_tex = char(M_.endo_names_tex, 'G');
M_.endo_names_long = char(M_.endo_names_long, 'G');
M_.endo_names = char(M_.endo_names, 'g');
M_.endo_names_tex = char(M_.endo_names_tex, 'g');
M_.endo_names_long = char(M_.endo_names_long, 'g');
M_.endo_names = char(M_.endo_names, 'Gy');
M_.endo_names_tex = char(M_.endo_names_tex, 'Gy');
M_.endo_names_long = char(M_.endo_names_long, 'Gy');
M_.endo_names = char(M_.endo_names, 'T');
M_.endo_names_tex = char(M_.endo_names_tex, 'T');
M_.endo_names_long = char(M_.endo_names_long, 'T');
M_.endo_names = char(M_.endo_names, 'B');
M_.endo_names_tex = char(M_.endo_names_tex, 'B');
M_.endo_names_long = char(M_.endo_names_long, 'B');
M_.endo_names = char(M_.endo_names, 'Y_fe');
M_.endo_names_tex = char(M_.endo_names_tex, 'Y\_fe');
M_.endo_names_long = char(M_.endo_names_long, 'Y_fe');
M_.endo_names = char(M_.endo_names, 'Ym_fe');
M_.endo_names_tex = char(M_.endo_names_tex, 'Ym\_fe');
M_.endo_names_long = char(M_.endo_names_long, 'Ym_fe');
M_.endo_names = char(M_.endo_names, 'L_fe');
M_.endo_names_tex = char(M_.endo_names_tex, 'L\_fe');
M_.endo_names_long = char(M_.endo_names_long, 'L_fe');
M_.endo_names = char(M_.endo_names, 'w_fe');
M_.endo_names_tex = char(M_.endo_names_tex, 'w\_fe');
M_.endo_names_long = char(M_.endo_names_long, 'w_fe');
M_.endo_names = char(M_.endo_names, 'C_fe');
M_.endo_names_tex = char(M_.endo_names_tex, 'C\_fe');
M_.endo_names_long = char(M_.endo_names_long, 'C_fe');
M_.endo_names = char(M_.endo_names, 'U_c_fe');
M_.endo_names_tex = char(M_.endo_names_tex, 'U\_c\_fe');
M_.endo_names_long = char(M_.endo_names_long, 'U_c_fe');
M_.endo_names = char(M_.endo_names, 'Lambda_fe');
M_.endo_names_tex = char(M_.endo_names_tex, 'Lambda\_fe');
M_.endo_names_long = char(M_.endo_names_long, 'Lambda_fe');
M_.endo_names = char(M_.endo_names, 'I_fe');
M_.endo_names_tex = char(M_.endo_names_tex, 'I\_fe');
M_.endo_names_long = char(M_.endo_names_long, 'I_fe');
M_.endo_names = char(M_.endo_names, 'K_fe');
M_.endo_names_tex = char(M_.endo_names_tex, 'K\_fe');
M_.endo_names_long = char(M_.endo_names_long, 'K_fe');
M_.endo_names = char(M_.endo_names, 'Q_fe');
M_.endo_names_tex = char(M_.endo_names_tex, 'Q\_fe');
M_.endo_names_long = char(M_.endo_names_long, 'Q_fe');
M_.endo_names = char(M_.endo_names, 'Pm_fe');
M_.endo_names_tex = char(M_.endo_names_tex, 'Pm\_fe');
M_.endo_names_long = char(M_.endo_names_long, 'Pm_fe');
M_.endo_names = char(M_.endo_names, 'Rd_fe');
M_.endo_names_tex = char(M_.endo_names_tex, 'Rd\_fe');
M_.endo_names_long = char(M_.endo_names_long, 'Rd_fe');
M_.endo_names = char(M_.endo_names, 'Rk_fe');
M_.endo_names_tex = char(M_.endo_names_tex, 'Rk\_fe');
M_.endo_names_long = char(M_.endo_names_long, 'Rk_fe');
M_.endo_names = char(M_.endo_names, 'Rb_fe');
M_.endo_names_tex = char(M_.endo_names_tex, 'Rb\_fe');
M_.endo_names_long = char(M_.endo_names_long, 'Rb_fe');
M_.endo_names = char(M_.endo_names, 'Rp_fe');
M_.endo_names_tex = char(M_.endo_names_tex, 'Rp\_fe');
M_.endo_names_long = char(M_.endo_names_long, 'Rp_fe');
M_.endo_names = char(M_.endo_names, 'ERk_fe');
M_.endo_names_tex = char(M_.endo_names_tex, 'ERk\_fe');
M_.endo_names_long = char(M_.endo_names_long, 'ERk_fe');
M_.endo_names = char(M_.endo_names, 'ERb_fe');
M_.endo_names_tex = char(M_.endo_names_tex, 'ERb\_fe');
M_.endo_names_long = char(M_.endo_names_long, 'ERb_fe');
M_.endo_names = char(M_.endo_names, 'Phi_fe');
M_.endo_names_tex = char(M_.endo_names_tex, 'Phi\_fe');
M_.endo_names_long = char(M_.endo_names_long, 'Phi_fe');
M_.endo_names = char(M_.endo_names, 'portf_B_fe');
M_.endo_names_tex = char(M_.endo_names_tex, 'portf\_B\_fe');
M_.endo_names_long = char(M_.endo_names_long, 'portf_B_fe');
M_.endo_names = char(M_.endo_names, 'N_fe');
M_.endo_names_tex = char(M_.endo_names_tex, 'N\_fe');
M_.endo_names_long = char(M_.endo_names_long, 'N_fe');
M_.endo_names = char(M_.endo_names, 'Om_fe');
M_.endo_names_tex = char(M_.endo_names_tex, 'Om\_fe');
M_.endo_names_long = char(M_.endo_names_long, 'Om_fe');
M_.endo_names = char(M_.endo_names, 'D_fe');
M_.endo_names_tex = char(M_.endo_names_tex, 'D\_fe');
M_.endo_names_long = char(M_.endo_names_long, 'D_fe');
M_.endo_names = char(M_.endo_names, 'nu_k_fe');
M_.endo_names_tex = char(M_.endo_names_tex, 'nu\_k\_fe');
M_.endo_names_long = char(M_.endo_names_long, 'nu_k_fe');
M_.endo_names = char(M_.endo_names, 'nu_b_fe');
M_.endo_names_tex = char(M_.endo_names_tex, 'nu\_b\_fe');
M_.endo_names_long = char(M_.endo_names_long, 'nu_b_fe');
M_.endo_names = char(M_.endo_names, 'nu_n_fe');
M_.endo_names_tex = char(M_.endo_names_tex, 'nu\_n\_fe');
M_.endo_names_long = char(M_.endo_names_long, 'nu_n_fe');
M_.endo_names = char(M_.endo_names, 'Gy_fe');
M_.endo_names_tex = char(M_.endo_names_tex, 'Gy\_fe');
M_.endo_names_long = char(M_.endo_names_long, 'Gy_fe');
M_.endo_names = char(M_.endo_names, 'T_fe');
M_.endo_names_tex = char(M_.endo_names_tex, 'T\_fe');
M_.endo_names_long = char(M_.endo_names_long, 'T_fe');
M_.endo_names = char(M_.endo_names, 'infl_fe');
M_.endo_names_tex = char(M_.endo_names_tex, 'infl\_fe');
M_.endo_names_long = char(M_.endo_names_long, 'infl_fe');
M_.endo_names = char(M_.endo_names, 'inflstar_fe');
M_.endo_names_tex = char(M_.endo_names_tex, 'inflstar\_fe');
M_.endo_names_long = char(M_.endo_names_long, 'inflstar_fe');
M_.endo_names = char(M_.endo_names, 'F_fe');
M_.endo_names_tex = char(M_.endo_names_tex, 'F\_fe');
M_.endo_names_long = char(M_.endo_names_long, 'F_fe');
M_.endo_names = char(M_.endo_names, 'Z_fe');
M_.endo_names_tex = char(M_.endo_names_tex, 'Z\_fe');
M_.endo_names_long = char(M_.endo_names_long, 'Z_fe');
M_.endo_names = char(M_.endo_names, 'Dis_fe');
M_.endo_names_tex = char(M_.endo_names_tex, 'Dis\_fe');
M_.endo_names_long = char(M_.endo_names_long, 'Dis_fe');
M_.endo_names = char(M_.endo_names, 'i_fe');
M_.endo_names_tex = char(M_.endo_names_tex, 'i\_fe');
M_.endo_names_long = char(M_.endo_names_long, 'i_fe');
M_.endo_names = char(M_.endo_names, 'B_fe');
M_.endo_names_tex = char(M_.endo_names_tex, 'B\_fe');
M_.endo_names_long = char(M_.endo_names_long, 'B_fe');
M_.endo_names = char(M_.endo_names, 'e_g');
M_.endo_names_tex = char(M_.endo_names_tex, 'e\_g');
M_.endo_names_long = char(M_.endo_names_long, 'e_g');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_91');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_91');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_91');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_95');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_95');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_95');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_99');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_99');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_99');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_126');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_126');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_126');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_130');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_130');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_130');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_134');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_134');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_134');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_161');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_161');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_161');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_165');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_165');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_165');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_169');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_169');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_169');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_2_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_2\_1');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_2_1');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_2_2');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_2\_2');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_2_2');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_4_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_4\_1');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_4_1');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_4_2');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_4\_2');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_4_2');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_4_3');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_4\_3');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_4_3');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_3_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_3\_1');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_3_1');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_3_2');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_3\_2');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_3_2');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_3_3');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_3\_3');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_3_3');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_0_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_0\_1');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_0_1');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_0_2');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_0\_2');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_0_2');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_0_3');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_0\_3');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_0_3');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_2_3');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_2\_3');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_2_3');
M_.endo_partitions = struct();
M_.param_names = 'cofintintb1';
M_.param_names_tex = 'cofintintb1';
M_.param_names_long = 'cofintintb1';
M_.param_names = char(M_.param_names, 'cofintintb2');
M_.param_names_tex = char(M_.param_names_tex, 'cofintintb2');
M_.param_names_long = char(M_.param_names_long, 'cofintintb2');
M_.param_names = char(M_.param_names, 'cofintintb3');
M_.param_names_tex = char(M_.param_names_tex, 'cofintintb3');
M_.param_names_long = char(M_.param_names_long, 'cofintintb3');
M_.param_names = char(M_.param_names, 'cofintintb4');
M_.param_names_tex = char(M_.param_names_tex, 'cofintintb4');
M_.param_names_long = char(M_.param_names_long, 'cofintintb4');
M_.param_names = char(M_.param_names, 'cofintinf0');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinf0');
M_.param_names_long = char(M_.param_names_long, 'cofintinf0');
M_.param_names = char(M_.param_names, 'cofintinfb1');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinfb1');
M_.param_names_long = char(M_.param_names_long, 'cofintinfb1');
M_.param_names = char(M_.param_names, 'cofintinfb2');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinfb2');
M_.param_names_long = char(M_.param_names_long, 'cofintinfb2');
M_.param_names = char(M_.param_names, 'cofintinfb3');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinfb3');
M_.param_names_long = char(M_.param_names_long, 'cofintinfb3');
M_.param_names = char(M_.param_names, 'cofintinfb4');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinfb4');
M_.param_names_long = char(M_.param_names_long, 'cofintinfb4');
M_.param_names = char(M_.param_names, 'cofintinff1');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinff1');
M_.param_names_long = char(M_.param_names_long, 'cofintinff1');
M_.param_names = char(M_.param_names, 'cofintinff2');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinff2');
M_.param_names_long = char(M_.param_names_long, 'cofintinff2');
M_.param_names = char(M_.param_names, 'cofintinff3');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinff3');
M_.param_names_long = char(M_.param_names_long, 'cofintinff3');
M_.param_names = char(M_.param_names, 'cofintinff4');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinff4');
M_.param_names_long = char(M_.param_names_long, 'cofintinff4');
M_.param_names = char(M_.param_names, 'cofintout');
M_.param_names_tex = char(M_.param_names_tex, 'cofintout');
M_.param_names_long = char(M_.param_names_long, 'cofintout');
M_.param_names = char(M_.param_names, 'cofintoutb1');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutb1');
M_.param_names_long = char(M_.param_names_long, 'cofintoutb1');
M_.param_names = char(M_.param_names, 'cofintoutb2');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutb2');
M_.param_names_long = char(M_.param_names_long, 'cofintoutb2');
M_.param_names = char(M_.param_names, 'cofintoutb3');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutb3');
M_.param_names_long = char(M_.param_names_long, 'cofintoutb3');
M_.param_names = char(M_.param_names, 'cofintoutb4');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutb4');
M_.param_names_long = char(M_.param_names_long, 'cofintoutb4');
M_.param_names = char(M_.param_names, 'cofintoutf1');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutf1');
M_.param_names_long = char(M_.param_names_long, 'cofintoutf1');
M_.param_names = char(M_.param_names, 'cofintoutf2');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutf2');
M_.param_names_long = char(M_.param_names_long, 'cofintoutf2');
M_.param_names = char(M_.param_names, 'cofintoutf3');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutf3');
M_.param_names_long = char(M_.param_names_long, 'cofintoutf3');
M_.param_names = char(M_.param_names, 'cofintoutf4');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutf4');
M_.param_names_long = char(M_.param_names_long, 'cofintoutf4');
M_.param_names = char(M_.param_names, 'cofintoutp');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutp');
M_.param_names_long = char(M_.param_names_long, 'cofintoutp');
M_.param_names = char(M_.param_names, 'cofintoutpb1');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpb1');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpb1');
M_.param_names = char(M_.param_names, 'cofintoutpb2');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpb2');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpb2');
M_.param_names = char(M_.param_names, 'cofintoutpb3');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpb3');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpb3');
M_.param_names = char(M_.param_names, 'cofintoutpb4');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpb4');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpb4');
M_.param_names = char(M_.param_names, 'cofintoutpf1');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpf1');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpf1');
M_.param_names = char(M_.param_names, 'cofintoutpf2');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpf2');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpf2');
M_.param_names = char(M_.param_names, 'cofintoutpf3');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpf3');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpf3');
M_.param_names = char(M_.param_names, 'cofintoutpf4');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpf4');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpf4');
M_.param_names = char(M_.param_names, 'std_r_');
M_.param_names_tex = char(M_.param_names_tex, 'std\_r\_');
M_.param_names_long = char(M_.param_names_long, 'std_r_');
M_.param_names = char(M_.param_names, 'std_r_quart');
M_.param_names_tex = char(M_.param_names_tex, 'std\_r\_quart');
M_.param_names_long = char(M_.param_names_long, 'std_r_quart');
M_.param_names = char(M_.param_names, 'coffispol');
M_.param_names_tex = char(M_.param_names_tex, 'coffispol');
M_.param_names_long = char(M_.param_names_long, 'coffispol');
M_.param_names = char(M_.param_names, 'beta');
M_.param_names_tex = char(M_.param_names_tex, 'beta');
M_.param_names_long = char(M_.param_names_long, 'beta');
M_.param_names = char(M_.param_names, 'hh');
M_.param_names_tex = char(M_.param_names_tex, 'hh');
M_.param_names_long = char(M_.param_names_long, 'hh');
M_.param_names = char(M_.param_names, 'delta');
M_.param_names_tex = char(M_.param_names_tex, 'delta');
M_.param_names_long = char(M_.param_names_long, 'delta');
M_.param_names = char(M_.param_names, 'varphi');
M_.param_names_tex = char(M_.param_names_tex, 'varphi');
M_.param_names_long = char(M_.param_names_long, 'varphi');
M_.param_names = char(M_.param_names, 'eta_i');
M_.param_names_tex = char(M_.param_names_tex, 'eta\_i');
M_.param_names_long = char(M_.param_names_long, 'eta_i');
M_.param_names = char(M_.param_names, 'alpha');
M_.param_names_tex = char(M_.param_names_tex, 'alpha');
M_.param_names_long = char(M_.param_names_long, 'alpha');
M_.param_names = char(M_.param_names, 'gam');
M_.param_names_tex = char(M_.param_names_tex, 'gam');
M_.param_names_long = char(M_.param_names_long, 'gam');
M_.param_names = char(M_.param_names, 'epsilon');
M_.param_names_tex = char(M_.param_names_tex, 'epsilon');
M_.param_names_long = char(M_.param_names_long, 'epsilon');
M_.param_names = char(M_.param_names, 'kappa_pi');
M_.param_names_tex = char(M_.param_names_tex, 'kappa\_pi');
M_.param_names_long = char(M_.param_names_long, 'kappa_pi');
M_.param_names = char(M_.param_names, 'kappa_y');
M_.param_names_tex = char(M_.param_names_tex, 'kappa\_y');
M_.param_names_long = char(M_.param_names_long, 'kappa_y');
M_.param_names = char(M_.param_names, 'G_over_Y');
M_.param_names_tex = char(M_.param_names_tex, 'G\_over\_Y');
M_.param_names_long = char(M_.param_names_long, 'G_over_Y');
M_.param_names = char(M_.param_names, 'B_over_Y');
M_.param_names_tex = char(M_.param_names_tex, 'B\_over\_Y');
M_.param_names_long = char(M_.param_names_long, 'B_over_Y');
M_.param_names = char(M_.param_names, 'theta');
M_.param_names_tex = char(M_.param_names_tex, 'theta');
M_.param_names_long = char(M_.param_names_long, 'theta');
M_.param_names = char(M_.param_names, 'lambda');
M_.param_names_tex = char(M_.param_names_tex, 'lambda');
M_.param_names_long = char(M_.param_names_long, 'lambda');
M_.param_names = char(M_.param_names, 'chi');
M_.param_names_tex = char(M_.param_names_tex, 'chi');
M_.param_names_long = char(M_.param_names_long, 'chi');
M_.param_names = char(M_.param_names, 'rho_i');
M_.param_names_tex = char(M_.param_names_tex, 'rho\_i');
M_.param_names_long = char(M_.param_names_long, 'rho_i');
M_.param_names = char(M_.param_names, 'rho_ksi');
M_.param_names_tex = char(M_.param_names_tex, 'rho\_ksi');
M_.param_names_long = char(M_.param_names_long, 'rho_ksi');
M_.param_names = char(M_.param_names, 'rho_a');
M_.param_names_tex = char(M_.param_names_tex, 'rho\_a');
M_.param_names_long = char(M_.param_names_long, 'rho_a');
M_.param_names = char(M_.param_names, 'rho_g');
M_.param_names_tex = char(M_.param_names_tex, 'rho\_g');
M_.param_names_long = char(M_.param_names_long, 'rho_g');
M_.param_names = char(M_.param_names, 'sigma_i');
M_.param_names_tex = char(M_.param_names_tex, 'sigma\_i');
M_.param_names_long = char(M_.param_names_long, 'sigma_i');
M_.param_names = char(M_.param_names, 'sigma_ksi');
M_.param_names_tex = char(M_.param_names_tex, 'sigma\_ksi');
M_.param_names_long = char(M_.param_names_long, 'sigma_ksi');
M_.param_names = char(M_.param_names, 'sigma_a');
M_.param_names_tex = char(M_.param_names_tex, 'sigma\_a');
M_.param_names_long = char(M_.param_names_long, 'sigma_a');
M_.param_names = char(M_.param_names, 'sigma_g');
M_.param_names_tex = char(M_.param_names_tex, 'sigma\_g');
M_.param_names_long = char(M_.param_names_long, 'sigma_g');
M_.param_names = char(M_.param_names, 'sigma_n');
M_.param_names_tex = char(M_.param_names_tex, 'sigma\_n');
M_.param_names_long = char(M_.param_names_long, 'sigma_n');
M_.param_names = char(M_.param_names, 'gam_fe');
M_.param_names_tex = char(M_.param_names_tex, 'gam\_fe');
M_.param_names_long = char(M_.param_names_long, 'gam_fe');
M_.param_names = char(M_.param_names, 'Y_ss');
M_.param_names_tex = char(M_.param_names_tex, 'Y\_ss');
M_.param_names_long = char(M_.param_names_long, 'Y_ss');
M_.param_names = char(M_.param_names, 'L_ss');
M_.param_names_tex = char(M_.param_names_tex, 'L\_ss');
M_.param_names_long = char(M_.param_names_long, 'L_ss');
M_.param_names = char(M_.param_names, 'w_ss');
M_.param_names_tex = char(M_.param_names_tex, 'w\_ss');
M_.param_names_long = char(M_.param_names_long, 'w_ss');
M_.param_names = char(M_.param_names, 'U_c_ss');
M_.param_names_tex = char(M_.param_names_tex, 'U\_c\_ss');
M_.param_names_long = char(M_.param_names_long, 'U_c_ss');
M_.param_names = char(M_.param_names, 'Y_over_K');
M_.param_names_tex = char(M_.param_names_tex, 'Y\_over\_K');
M_.param_names_long = char(M_.param_names_long, 'Y_over_K');
M_.param_names = char(M_.param_names, 'L_over_K');
M_.param_names_tex = char(M_.param_names_tex, 'L\_over\_K');
M_.param_names_long = char(M_.param_names_long, 'L_over_K');
M_.param_names = char(M_.param_names, 'K_ss');
M_.param_names_tex = char(M_.param_names_tex, 'K\_ss');
M_.param_names_long = char(M_.param_names_long, 'K_ss');
M_.param_names = char(M_.param_names, 'Ym_ss');
M_.param_names_tex = char(M_.param_names_tex, 'Ym\_ss');
M_.param_names_long = char(M_.param_names_long, 'Ym_ss');
M_.param_names = char(M_.param_names, 'G_ss');
M_.param_names_tex = char(M_.param_names_tex, 'G\_ss');
M_.param_names_long = char(M_.param_names_long, 'G_ss');
M_.param_names = char(M_.param_names, 'I_ss');
M_.param_names_tex = char(M_.param_names_tex, 'I\_ss');
M_.param_names_long = char(M_.param_names_long, 'I_ss');
M_.param_names = char(M_.param_names, 'C_ss');
M_.param_names_tex = char(M_.param_names_tex, 'C\_ss');
M_.param_names_long = char(M_.param_names_long, 'C_ss');
M_.param_names = char(M_.param_names, 'Z_ss');
M_.param_names_tex = char(M_.param_names_tex, 'Z\_ss');
M_.param_names_long = char(M_.param_names_long, 'Z_ss');
M_.param_names = char(M_.param_names, 'F_ss');
M_.param_names_tex = char(M_.param_names_tex, 'F\_ss');
M_.param_names_long = char(M_.param_names_long, 'F_ss');
M_.param_names = char(M_.param_names, 'B_ss');
M_.param_names_tex = char(M_.param_names_tex, 'B\_ss');
M_.param_names_long = char(M_.param_names_long, 'B_ss');
M_.param_names = char(M_.param_names, 'N_ss');
M_.param_names_tex = char(M_.param_names_tex, 'N\_ss');
M_.param_names_long = char(M_.param_names_long, 'N_ss');
M_.param_names = char(M_.param_names, 'D_ss');
M_.param_names_tex = char(M_.param_names_tex, 'D\_ss');
M_.param_names_long = char(M_.param_names_long, 'D_ss');
M_.param_names = char(M_.param_names, 'T_ss');
M_.param_names_tex = char(M_.param_names_tex, 'T\_ss');
M_.param_names_long = char(M_.param_names_long, 'T_ss');
M_.param_names = char(M_.param_names, 'a_ss');
M_.param_names_tex = char(M_.param_names_tex, 'a\_ss');
M_.param_names_long = char(M_.param_names_long, 'a_ss');
M_.param_names = char(M_.param_names, 'ksi_ss');
M_.param_names_tex = char(M_.param_names_tex, 'ksi\_ss');
M_.param_names_long = char(M_.param_names_long, 'ksi_ss');
M_.param_names = char(M_.param_names, 'g_ss');
M_.param_names_tex = char(M_.param_names_tex, 'g\_ss');
M_.param_names_long = char(M_.param_names_long, 'g_ss');
M_.param_names = char(M_.param_names, 'Lambda_ss');
M_.param_names_tex = char(M_.param_names_tex, 'Lambda\_ss');
M_.param_names_long = char(M_.param_names_long, 'Lambda_ss');
M_.param_names = char(M_.param_names, 'Pm_ss');
M_.param_names_tex = char(M_.param_names_tex, 'Pm\_ss');
M_.param_names_long = char(M_.param_names_long, 'Pm_ss');
M_.param_names = char(M_.param_names, 'Phi_ss');
M_.param_names_tex = char(M_.param_names_tex, 'Phi\_ss');
M_.param_names_long = char(M_.param_names_long, 'Phi_ss');
M_.param_names = char(M_.param_names, 'Q_ss');
M_.param_names_tex = char(M_.param_names_tex, 'Q\_ss');
M_.param_names_long = char(M_.param_names_long, 'Q_ss');
M_.param_names = char(M_.param_names, 'Dis_ss');
M_.param_names_tex = char(M_.param_names_tex, 'Dis\_ss');
M_.param_names_long = char(M_.param_names_long, 'Dis_ss');
M_.param_names = char(M_.param_names, 'infl_ss');
M_.param_names_tex = char(M_.param_names_tex, 'infl\_ss');
M_.param_names_long = char(M_.param_names_long, 'infl_ss');
M_.param_names = char(M_.param_names, 'inflstar_ss');
M_.param_names_tex = char(M_.param_names_tex, 'inflstar\_ss');
M_.param_names_long = char(M_.param_names_long, 'inflstar_ss');
M_.param_names = char(M_.param_names, 'Rd_ss');
M_.param_names_tex = char(M_.param_names_tex, 'Rd\_ss');
M_.param_names_long = char(M_.param_names_long, 'Rd_ss');
M_.param_names = char(M_.param_names, 'Rp_ss');
M_.param_names_tex = char(M_.param_names_tex, 'Rp\_ss');
M_.param_names_long = char(M_.param_names_long, 'Rp_ss');
M_.param_names = char(M_.param_names, 'Rb_ss');
M_.param_names_tex = char(M_.param_names_tex, 'Rb\_ss');
M_.param_names_long = char(M_.param_names_long, 'Rb_ss');
M_.param_names = char(M_.param_names, 'Rk_ss');
M_.param_names_tex = char(M_.param_names_tex, 'Rk\_ss');
M_.param_names_long = char(M_.param_names_long, 'Rk_ss');
M_.param_names = char(M_.param_names, 'i_ss');
M_.param_names_tex = char(M_.param_names_tex, 'i\_ss');
M_.param_names_long = char(M_.param_names_long, 'i_ss');
M_.param_names = char(M_.param_names, 'prem_ss');
M_.param_names_tex = char(M_.param_names_tex, 'prem\_ss');
M_.param_names_long = char(M_.param_names_long, 'prem_ss');
M_.param_names = char(M_.param_names, 'nu_b_ss');
M_.param_names_tex = char(M_.param_names_tex, 'nu\_b\_ss');
M_.param_names_long = char(M_.param_names_long, 'nu_b_ss');
M_.param_names = char(M_.param_names, 'nu_n_ss');
M_.param_names_tex = char(M_.param_names_tex, 'nu\_n\_ss');
M_.param_names_long = char(M_.param_names_long, 'nu_n_ss');
M_.param_names = char(M_.param_names, 'nu_k_ss');
M_.param_names_tex = char(M_.param_names_tex, 'nu\_k\_ss');
M_.param_names_long = char(M_.param_names_long, 'nu_k_ss');
M_.param_names = char(M_.param_names, 'portf_B_ss');
M_.param_names_tex = char(M_.param_names_tex, 'portf\_B\_ss');
M_.param_names_long = char(M_.param_names_long, 'portf_B_ss');
M_.param_names = char(M_.param_names, 'Om_ss');
M_.param_names_tex = char(M_.param_names_tex, 'Om\_ss');
M_.param_names_long = char(M_.param_names_long, 'Om_ss');
M_.param_names = char(M_.param_names, 'Gy_ss');
M_.param_names_tex = char(M_.param_names_tex, 'Gy\_ss');
M_.param_names_long = char(M_.param_names_long, 'Gy_ss');
M_.param_partitions = struct();
M_.exo_det_nbr = 0;
M_.exo_nbr = 4;
M_.endo_nbr = 102;
M_.param_nbr = 98;
M_.orig_endo_nbr = 81;
M_.aux_vars(1).endo_index = 82;
M_.aux_vars(1).type = 0;
M_.aux_vars(2).endo_index = 83;
M_.aux_vars(2).type = 0;
M_.aux_vars(3).endo_index = 84;
M_.aux_vars(3).type = 0;
M_.aux_vars(4).endo_index = 85;
M_.aux_vars(4).type = 0;
M_.aux_vars(5).endo_index = 86;
M_.aux_vars(5).type = 0;
M_.aux_vars(6).endo_index = 87;
M_.aux_vars(6).type = 0;
M_.aux_vars(7).endo_index = 88;
M_.aux_vars(7).type = 0;
M_.aux_vars(8).endo_index = 89;
M_.aux_vars(8).type = 0;
M_.aux_vars(9).endo_index = 90;
M_.aux_vars(9).type = 0;
M_.aux_vars(10).endo_index = 91;
M_.aux_vars(10).type = 1;
M_.aux_vars(10).orig_index = 3;
M_.aux_vars(10).orig_lead_lag = -1;
M_.aux_vars(11).endo_index = 92;
M_.aux_vars(11).type = 1;
M_.aux_vars(11).orig_index = 3;
M_.aux_vars(11).orig_lead_lag = -2;
M_.aux_vars(12).endo_index = 93;
M_.aux_vars(12).type = 1;
M_.aux_vars(12).orig_index = 5;
M_.aux_vars(12).orig_lead_lag = -1;
M_.aux_vars(13).endo_index = 94;
M_.aux_vars(13).type = 1;
M_.aux_vars(13).orig_index = 5;
M_.aux_vars(13).orig_lead_lag = -2;
M_.aux_vars(14).endo_index = 95;
M_.aux_vars(14).type = 1;
M_.aux_vars(14).orig_index = 5;
M_.aux_vars(14).orig_lead_lag = -3;
M_.aux_vars(15).endo_index = 96;
M_.aux_vars(15).type = 1;
M_.aux_vars(15).orig_index = 4;
M_.aux_vars(15).orig_lead_lag = -1;
M_.aux_vars(16).endo_index = 97;
M_.aux_vars(16).type = 1;
M_.aux_vars(16).orig_index = 4;
M_.aux_vars(16).orig_lead_lag = -2;
M_.aux_vars(17).endo_index = 98;
M_.aux_vars(17).type = 1;
M_.aux_vars(17).orig_index = 4;
M_.aux_vars(17).orig_lead_lag = -3;
M_.aux_vars(18).endo_index = 99;
M_.aux_vars(18).type = 1;
M_.aux_vars(18).orig_index = 1;
M_.aux_vars(18).orig_lead_lag = -1;
M_.aux_vars(19).endo_index = 100;
M_.aux_vars(19).type = 1;
M_.aux_vars(19).orig_index = 1;
M_.aux_vars(19).orig_lead_lag = -2;
M_.aux_vars(20).endo_index = 101;
M_.aux_vars(20).type = 1;
M_.aux_vars(20).orig_index = 1;
M_.aux_vars(20).orig_lead_lag = -3;
M_.aux_vars(21).endo_index = 102;
M_.aux_vars(21).type = 1;
M_.aux_vars(21).orig_index = 3;
M_.aux_vars(21).orig_lead_lag = -3;
M_.Sigma_e = zeros(4, 4);
M_.Correlation_matrix = eye(4, 4);
M_.H = 0;
M_.Correlation_matrix_ME = 1;
M_.sigma_e_is_diagonal = 1;
M_.det_shocks = [];
options_.block=0;
options_.bytecode=0;
options_.use_dll=0;
M_.hessian_eq_zero = 0;
erase_compiled_function('NK_KW16_static');
erase_compiled_function('NK_KW16_dynamic');
M_.orig_eq_nbr = 81;
M_.eq_nbr = 102;
M_.ramsey_eq_nbr = 0;
M_.set_auxiliary_variables = exist(['./' M_.fname '_set_auxiliary_variables.m'], 'file') == 2;
M_.lead_lag_incidence = [
 1 43 0;
 0 44 0;
 2 45 145;
 3 46 146;
 4 47 147;
 0 48 0;
 0 49 0;
 0 50 0;
 0 51 0;
 0 52 0;
 5 53 148;
 6 54 0;
 0 55 149;
 7 56 150;
 8 57 151;
 9 58 152;
 10 59 0;
 11 60 0;
 0 61 0;
 0 62 153;
 0 63 0;
 0 64 154;
 0 65 155;
 12 66 0;
 0 67 156;
 13 68 0;
 0 69 157;
 0 70 158;
 0 71 0;
 0 72 0;
 0 73 0;
 0 74 0;
 0 75 0;
 14 76 0;
 0 77 0;
 15 78 159;
 16 79 0;
 0 80 0;
 0 81 160;
 0 82 161;
 0 83 162;
 0 84 0;
 17 85 0;
 0 86 0;
 0 87 0;
 18 88 163;
 19 89 0;
 0 90 0;
 0 91 0;
 0 92 0;
 20 93 164;
 21 94 0;
 0 95 165;
 22 96 166;
 23 97 167;
 24 98 168;
 0 99 0;
 0 100 169;
 0 101 170;
 0 102 171;
 0 103 0;
 0 104 0;
 0 105 0;
 25 106 0;
 0 107 0;
 26 108 172;
 27 109 0;
 0 110 0;
 0 111 173;
 0 112 174;
 0 113 175;
 0 114 0;
 0 115 0;
 0 116 176;
 0 117 0;
 0 118 177;
 0 119 178;
 28 120 0;
 29 121 0;
 30 122 179;
 0 123 0;
 0 124 180;
 0 125 181;
 0 126 182;
 0 127 183;
 0 128 184;
 0 129 185;
 0 130 186;
 0 131 187;
 0 132 188;
 31 133 0;
 32 134 0;
 33 135 0;
 34 136 0;
 35 137 0;
 36 138 0;
 37 139 0;
 38 140 0;
 39 141 0;
 40 142 0;
 41 143 0;
 42 144 0;]';
M_.nstatic = 31;
M_.nfwrd   = 29;
M_.npred   = 27;
M_.nboth   = 15;
M_.nsfwrd   = 44;
M_.nspred   = 42;
M_.ndynamic   = 71;
M_.equations_tags = {
};
M_.static_and_dynamic_models_differ = 0;
M_.exo_names_orig_ord = [1:4];
M_.maximum_lag = 1;
M_.maximum_lead = 1;
M_.maximum_endo_lag = 1;
M_.maximum_endo_lead = 1;
oo_.steady_state = zeros(102, 1);
M_.maximum_exo_lag = 0;
M_.maximum_exo_lead = 0;
oo_.exo_steady_state = zeros(4, 1);
M_.params = NaN(98, 1);
M_.NNZDerivatives = [384; 481; -1];
thispath = cd;                                                           
cd('..');                                                                
load policy_param.mat;                                                   
for i=1:33                                                               
deep_parameter_name = M_.param_names(i,:);                           
eval(['M_.params(i)  = ' deep_parameter_name ' ;'])                  
end                                                                      
cd(thispath);   
M_.params( 32 ) = 100;
std_r_ = M_.params( 32 );
M_.params( 34 ) = 5;
coffispol = M_.params( 34 );
M_.params( 35 ) = 0.99;
beta = M_.params( 35 );
M_.params( 36 ) = 0.815;
hh = M_.params( 36 );
M_.params( 37 ) = 0.025;
delta = M_.params( 37 );
M_.params( 38 ) = 0.276;
varphi = M_.params( 38 );
M_.params( 39 ) = 1.728;
eta_i = M_.params( 39 );
M_.params( 40 ) = 0.33;
alpha = M_.params( 40 );
M_.params( 41 ) = 0.779;
gam = M_.params( 41 );
M_.params( 59 ) = 0.00001;
gam_fe = M_.params( 59 );
M_.params( 42 ) = 4.167;
epsilon = M_.params( 42 );
M_.params( 45 ) = 0.2;
G_over_Y = M_.params( 45 );
M_.params( 46 ) = 2.4;
B_over_Y = M_.params( 46 );
M_.params( 82 ) = 4;
Phi_ss = M_.params( 82 );
M_.params( 47 ) = 0.9375;
theta = M_.params( 47 );
M_.params( 43 ) = 1.50000000;
kappa_pi = M_.params( 43 );
M_.params( 44 ) = 0.12500000;
kappa_y = M_.params( 44 );
M_.params( 50 ) = 0.8;
rho_i = M_.params( 50 );
M_.params( 51 ) = 0.66;
rho_ksi = M_.params( 51 );
M_.params( 52 ) = 0.95;
rho_a = M_.params( 52 );
M_.params( 53 ) = 0.80;
rho_g = M_.params( 53 );
M_.params( 55 ) = 0.05;
sigma_ksi = M_.params( 55 );
M_.params( 56 ) = 0.01;
sigma_a = M_.params( 56 );
M_.params( 57 ) = 0.05;
sigma_g = M_.params( 57 );
M_.params( 54 ) = 0.0025;
sigma_i = M_.params( 54 );
M_.params( 58 ) = 0.01;
sigma_n = M_.params( 58 );
M_.params( 80 ) = 1;
Lambda_ss = M_.params( 80 );
M_.params( 83 ) = 1;
Q_ss = M_.params( 83 );
M_.params( 84 ) = 1;
Dis_ss = M_.params( 84 );
M_.params( 85 ) = 1;
infl_ss = M_.params( 85 );
M_.params( 86 ) = 1;
inflstar_ss = M_.params( 86 );
M_.params( 77 ) = 1;
a_ss = M_.params( 77 );
M_.params( 79 ) = 1;
g_ss = M_.params( 79 );
M_.params( 78 ) = 1;
ksi_ss = M_.params( 78 );
M_.params( 81 ) = (M_.params(42)-1)/M_.params(42);
Pm_ss = M_.params( 81 );
M_.params( 92 ) = 0.0025;
prem_ss = M_.params( 92 );
prem2_ss = prem_ss;
M_.params( 82 ) = 4;
Phi_ss = M_.params( 82 );
M_.params( 87 ) = 1/M_.params(35);
Rd_ss = M_.params( 87 );
M_.params( 91 ) = M_.params(87);
i_ss = M_.params( 91 );
M_.params( 90 ) = M_.params(87)+M_.params(92);
Rk_ss = M_.params( 90 );
M_.params( 89 ) = M_.params(90);
Rb_ss = M_.params( 89 );
M_.params( 88 ) = M_.params(90);
Rp_ss = M_.params( 88 );
ERk_ss=Rk_ss;
ERb_ss=Rk_ss;
M_.params( 94 ) = M_.params(87)*M_.params(35)*(1-M_.params(47))/(1-M_.params(35)*M_.params(47));
nu_n_ss = M_.params( 94 );
M_.params( 95 ) = M_.params(35)*(1-M_.params(47))*(M_.params(90)-M_.params(87))/(1-M_.params(35)*M_.params(47));
nu_k_ss = M_.params( 95 );
M_.params( 93 ) = M_.params(95);
nu_b_ss = M_.params( 93 );
M_.params( 48 ) = M_.params(95)+M_.params(94)/M_.params(82);
lambda = M_.params( 48 );
M_.params( 49 ) = 1-M_.params(47)*(M_.params(87)+(M_.params(90)-M_.params(87))*M_.params(82));
chi = M_.params( 49 );
M_.params( 62 ) = (M_.params(40)^M_.params(40)*(1-M_.params(40))^(1-M_.params(40))*M_.params(81)*(M_.params(90)-1+M_.params(37))^(-M_.params(40)))^(1/(1-M_.params(40)));
w_ss = M_.params( 62 );
M_.params( 64 ) = (M_.params(90)-1+M_.params(37))/(M_.params(40)*M_.params(81));
Y_over_K = M_.params( 64 );
M_.params( 65 ) = M_.params(64)^(1/(1-M_.params(40)));
L_over_K = M_.params( 65 );
I_over_Y = delta*(Y_over_K)^(-1);
C_over_Y = 1-G_over_Y-I_over_Y;
habit = (1-beta*hh)/(1-hh);
M_.params( 60 ) = M_.params(65)^((-M_.params(40))*M_.params(38)/(1+M_.params(38)))*(habit*M_.params(62)*C_over_Y^(-1))^(1/(1+M_.params(38)));
Y_ss = M_.params( 60 );
M_.params( 67 ) = M_.params(60);
Ym_ss = M_.params( 67 );
M_.params( 70 ) = C_over_Y*M_.params(60);
C_ss = M_.params( 70 );
M_.params( 68 ) = M_.params(60)*M_.params(45);
G_ss = M_.params( 68 );
M_.params( 98 ) = M_.params(45);
Gy_ss = M_.params( 98 );
M_.params( 69 ) = M_.params(60)*I_over_Y;
I_ss = M_.params( 69 );
M_.params( 66 ) = M_.params(69)/M_.params(37);
K_ss = M_.params( 66 );
M_.params( 61 ) = M_.params(65)*M_.params(66);
L_ss = M_.params( 61 );
M_.params( 63 ) = habit/M_.params(70);
U_c_ss = M_.params( 63 );
M_.params( 71 ) = M_.params(60)*1/(1-M_.params(35)*M_.params(41));
Z_ss = M_.params( 71 );
M_.params( 72 ) = M_.params(81)*M_.params(71);
F_ss = M_.params( 72 );
M_.params( 73 ) = M_.params(60)*M_.params(46);
B_ss = M_.params( 73 );
M_.params( 74 ) = (M_.params(66)+M_.params(73))/M_.params(82);
N_ss = M_.params( 74 );
M_.params( 97 ) = M_.params(66)/(M_.params(66)+M_.params(73));
Om_ss = M_.params( 97 );
M_.params( 88 ) = M_.params(90)*M_.params(97)+(1-M_.params(97))*M_.params(89);
Rp_ss = M_.params( 88 );
M_.params( 76 ) = M_.params(73)*(M_.params(89)-1)+M_.params(68);
T_ss = M_.params( 76 );
M_.params( 96 ) = M_.params(82)*M_.params(74);
portf_B_ss = M_.params( 96 );
M_.params( 75 ) = M_.params(66)+M_.params(73)-M_.params(74);
D_ss = M_.params( 75 );
%
% INITVAL instructions
%
options_.initval_file = 0;
oo_.steady_state( 7 ) = M_.params(60);
oo_.steady_state( 8 ) = M_.params(67);
oo_.steady_state( 15 ) = M_.params(66);
oo_.steady_state( 9 ) = M_.params(61);
oo_.steady_state( 14 ) = M_.params(69);
oo_.steady_state( 11 ) = M_.params(70);
oo_.steady_state( 42 ) = M_.params(68);
oo_.steady_state( 16 ) = M_.params(83);
oo_.steady_state( 12 ) = M_.params(63);
oo_.steady_state( 13 ) = M_.params(80);
oo_.steady_state( 27 ) = M_.params(90);
oo_.steady_state( 25 ) = M_.params(87);
oo_.steady_state( 36 ) = M_.params(74);
oo_.steady_state( 19 ) = M_.params(81);
oo_.steady_state( 10 ) = M_.params(62);
oo_.steady_state( 24 ) = M_.params(84);
oo_.steady_state( 22 ) = M_.params(72);
oo_.steady_state( 23 ) = M_.params(71);
oo_.steady_state( 26 ) = M_.params(91);
oo_.steady_state( 32 ) = M_.params(92);
oo_.steady_state( 17 ) = 1;
oo_.steady_state( 18 ) = 1;
oo_.steady_state( 43 ) = 1;
oo_.steady_state( 20 ) = 1;
oo_.steady_state( 21 ) = 1;
oo_.exo_steady_state( 2 ) = 0.00000000;
oo_.exo_steady_state( 1 ) = 0.00000000;
oo_.steady_state( 81 ) = 0.00000000;
oo_.steady_state( 46 ) = M_.params(73);
oo_.steady_state( 38 ) = M_.params(75);
oo_.steady_state( 45 ) = M_.params(76);
oo_.steady_state( 34 ) = M_.params(82);
oo_.steady_state( 28 ) = M_.params(89);
oo_.steady_state( 39 ) = M_.params(95);
oo_.steady_state( 40 ) = M_.params(93);
oo_.steady_state( 41 ) = M_.params(94);
oo_.steady_state( 33 ) = prem2_ss;
oo_.steady_state( 30 ) = M_.params(90);
oo_.steady_state( 31 ) = M_.params(89);
oo_.steady_state( 29 ) = M_.params(88);
oo_.steady_state( 35 ) = M_.params(96);
oo_.steady_state( 37 ) = M_.params(97);
oo_.steady_state( 44 ) = M_.params(98);
oo_.steady_state( 74 ) = 1;
oo_.steady_state( 75 ) = 1;
oo_.steady_state( 78 ) = M_.params(84);
oo_.steady_state( 76 ) = M_.params(72);
oo_.steady_state( 77 ) = M_.params(71);
oo_.steady_state( 79 ) = M_.params(91);
oo_.steady_state( 47 ) = M_.params(60);
oo_.steady_state( 48 ) = M_.params(67);
oo_.steady_state( 55 ) = M_.params(66);
oo_.steady_state( 49 ) = M_.params(61);
oo_.steady_state( 54 ) = M_.params(69);
oo_.steady_state( 51 ) = M_.params(70);
oo_.steady_state( 56 ) = M_.params(83);
oo_.steady_state( 52 ) = M_.params(63);
oo_.steady_state( 53 ) = M_.params(80);
oo_.steady_state( 59 ) = M_.params(90);
oo_.steady_state( 58 ) = M_.params(87);
oo_.steady_state( 66 ) = M_.params(74);
oo_.steady_state( 57 ) = M_.params(81);
oo_.steady_state( 50 ) = M_.params(62);
oo_.steady_state( 80 ) = M_.params(73);
oo_.steady_state( 68 ) = M_.params(75);
oo_.steady_state( 73 ) = M_.params(76);
oo_.steady_state( 64 ) = M_.params(82);
oo_.steady_state( 60 ) = M_.params(89);
oo_.steady_state( 69 ) = M_.params(95);
oo_.steady_state( 70 ) = M_.params(93);
oo_.steady_state( 71 ) = M_.params(94);
oo_.steady_state( 62 ) = M_.params(90);
oo_.steady_state( 63 ) = M_.params(89);
oo_.steady_state( 61 ) = M_.params(88);
oo_.steady_state( 65 ) = M_.params(96);
oo_.steady_state( 67 ) = M_.params(97);
oo_.steady_state( 72 ) = M_.params(98);
oo_.steady_state(82)=oo_.steady_state(3);
oo_.steady_state(83)=oo_.steady_state(82);
oo_.steady_state(84)=oo_.steady_state(83);
oo_.steady_state(85)=oo_.steady_state(4);
oo_.steady_state(86)=oo_.steady_state(85);
oo_.steady_state(87)=oo_.steady_state(86);
oo_.steady_state(88)=oo_.steady_state(5);
oo_.steady_state(89)=oo_.steady_state(88);
oo_.steady_state(90)=oo_.steady_state(89);
oo_.steady_state(91)=oo_.steady_state(3);
oo_.steady_state(92)=oo_.steady_state(91);
oo_.steady_state(93)=oo_.steady_state(5);
oo_.steady_state(94)=oo_.steady_state(93);
oo_.steady_state(95)=oo_.steady_state(94);
oo_.steady_state(96)=oo_.steady_state(4);
oo_.steady_state(97)=oo_.steady_state(96);
oo_.steady_state(98)=oo_.steady_state(97);
oo_.steady_state(99)=oo_.steady_state(1);
oo_.steady_state(100)=oo_.steady_state(99);
oo_.steady_state(101)=oo_.steady_state(100);
oo_.steady_state(102)=oo_.steady_state(92);
if M_.exo_nbr > 0
	oo_.exo_simul = ones(M_.maximum_lag,1)*oo_.exo_steady_state';
end
if M_.exo_det_nbr > 0
	oo_.exo_det_simul = ones(M_.maximum_lag,1)*oo_.exo_det_steady_state';
end
%
% SHOCKS instructions
%
M_.exo_det_length = 0;
M_.Sigma_e(1, 1) = (M_.params(55))^2;
M_.Sigma_e(2, 2) = (M_.params(56))^2;
M_.Sigma_e(3, 3) = (1)^2;
M_.Sigma_e(4, 4) = (1)^2;
save('NK_KW16_results.mat', 'oo_', 'M_', 'options_');
if exist('estim_params_', 'var') == 1
  save('NK_KW16_results.mat', 'estim_params_', '-append');
end
if exist('bayestopt_', 'var') == 1
  save('NK_KW16_results.mat', 'bayestopt_', '-append');
end
if exist('dataset_', 'var') == 1
  save('NK_KW16_results.mat', 'dataset_', '-append');
end
if exist('estimation_info', 'var') == 1
  save('NK_KW16_results.mat', 'estimation_info', '-append');
end
if exist('dataset_info', 'var') == 1
  save('NK_KW16_results.mat', 'dataset_info', '-append');
end
if exist('oo_recursive_', 'var') == 1
  save('NK_KW16_results.mat', 'oo_recursive_', '-append');
end


disp(['Total computing time : ' dynsec2hms(toc(tic0)) ]);
if ~isempty(lastwarn)
  disp('Note: warning(s) encountered in MATLAB/Octave code')
end
diary off
