%
% Status : main Dynare file
%
% Warning : this file is generated automatically by Dynare
%           from model file (.mod)

tic0 = tic;
% Save empty dates and dseries objects in memory.
dates('initialize');
dseries('initialize');
% Define global variables.
global M_ options_ oo_ estim_params_ bayestopt_ dataset_ dataset_info estimation_info ys0_ ex0_
options_ = [];
M_.fname = 'NK_GLSV07';
M_.dynare_version = '4.5.4';
oo_.dynare_version = '4.5.4';
options_.dynare_version = '4.5.4';
%
% Some global variables initialization
%
global_initialization;
diary off;
diary('NK_GLSV07.log');
M_.exo_names = 'interest_';
M_.exo_names_tex = 'interest\_';
M_.exo_names_long = 'interest_';
M_.exo_names = char(M_.exo_names, 'fiscal_');
M_.exo_names_tex = char(M_.exo_names_tex, 'fiscal\_');
M_.exo_names_long = char(M_.exo_names_long, 'fiscal_');
M_.endo_names = 'n';
M_.endo_names_tex = 'n';
M_.endo_names_long = 'n';
M_.endo_names = char(M_.endo_names, 'c');
M_.endo_names_tex = char(M_.endo_names_tex, 'c');
M_.endo_names_long = char(M_.endo_names_long, 'c');
M_.endo_names = char(M_.endo_names, 'r');
M_.endo_names_tex = char(M_.endo_names_tex, 'r');
M_.endo_names_long = char(M_.endo_names_long, 'r');
M_.endo_names = char(M_.endo_names, 'pi');
M_.endo_names_tex = char(M_.endo_names_tex, 'pi');
M_.endo_names_long = char(M_.endo_names_long, 'pi');
M_.endo_names = char(M_.endo_names, 'k');
M_.endo_names_tex = char(M_.endo_names_tex, 'k');
M_.endo_names_long = char(M_.endo_names_long, 'k');
M_.endo_names = char(M_.endo_names, 'b');
M_.endo_names_tex = char(M_.endo_names_tex, 'b');
M_.endo_names_long = char(M_.endo_names_long, 'b');
M_.endo_names = char(M_.endo_names, 'g');
M_.endo_names_tex = char(M_.endo_names_tex, 'g');
M_.endo_names_long = char(M_.endo_names_long, 'g');
M_.endo_names = char(M_.endo_names, 'y');
M_.endo_names_tex = char(M_.endo_names_tex, 'y');
M_.endo_names_long = char(M_.endo_names_long, 'y');
M_.endo_names = char(M_.endo_names, 'e_g');
M_.endo_names_tex = char(M_.endo_names_tex, 'e\_g');
M_.endo_names_long = char(M_.endo_names_long, 'e_g');
M_.endo_names = char(M_.endo_names, 'nf');
M_.endo_names_tex = char(M_.endo_names_tex, 'nf');
M_.endo_names_long = char(M_.endo_names_long, 'nf');
M_.endo_names = char(M_.endo_names, 'cf');
M_.endo_names_tex = char(M_.endo_names_tex, 'cf');
M_.endo_names_long = char(M_.endo_names_long, 'cf');
M_.endo_names = char(M_.endo_names, 'kf');
M_.endo_names_tex = char(M_.endo_names_tex, 'kf');
M_.endo_names_long = char(M_.endo_names_long, 'kf');
M_.endo_names = char(M_.endo_names, 'bf');
M_.endo_names_tex = char(M_.endo_names_tex, 'bf');
M_.endo_names_long = char(M_.endo_names_long, 'bf');
M_.endo_names = char(M_.endo_names, 'yf');
M_.endo_names_tex = char(M_.endo_names_tex, 'yf');
M_.endo_names_long = char(M_.endo_names_long, 'yf');
M_.endo_names = char(M_.endo_names, 'rf');
M_.endo_names_tex = char(M_.endo_names_tex, 'rf');
M_.endo_names_long = char(M_.endo_names_long, 'rf');
M_.endo_names = char(M_.endo_names, 'interest');
M_.endo_names_tex = char(M_.endo_names_tex, 'interest');
M_.endo_names_long = char(M_.endo_names_long, 'interest');
M_.endo_names = char(M_.endo_names, 'inflation');
M_.endo_names_tex = char(M_.endo_names_tex, 'inflation');
M_.endo_names_long = char(M_.endo_names_long, 'inflation');
M_.endo_names = char(M_.endo_names, 'inflationq');
M_.endo_names_tex = char(M_.endo_names_tex, 'inflationq');
M_.endo_names_long = char(M_.endo_names_long, 'inflationq');
M_.endo_names = char(M_.endo_names, 'outputgap');
M_.endo_names_tex = char(M_.endo_names_tex, 'outputgap');
M_.endo_names_long = char(M_.endo_names_long, 'outputgap');
M_.endo_names = char(M_.endo_names, 'output');
M_.endo_names_tex = char(M_.endo_names_tex, 'output');
M_.endo_names_long = char(M_.endo_names_long, 'output');
M_.endo_names = char(M_.endo_names, 'fispol');
M_.endo_names_tex = char(M_.endo_names_tex, 'fispol');
M_.endo_names_long = char(M_.endo_names_long, 'fispol');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_78');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_78');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_78');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_82');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_82');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_82');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_86');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_86');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_86');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_113');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_113');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_113');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_117');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_117');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_117');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_121');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_121');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_121');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_148');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_148');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_148');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_152');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_152');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_152');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_156');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_156');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_156');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_3_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_3\_1');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_3_1');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_3_2');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_3\_2');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_3_2');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_19_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_19\_1');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_19_1');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_19_2');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_19\_2');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_19_2');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_19_3');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_19\_3');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_19_3');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_18_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_18\_1');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_18_1');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_18_2');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_18\_2');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_18_2');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_18_3');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_18\_3');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_18_3');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_15_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_15\_1');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_15_1');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_15_2');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_15\_2');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_15_2');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_15_3');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_15\_3');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_15_3');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_17_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_17\_1');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_17_1');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_17_2');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_17\_2');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_17_2');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_17_3');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_17\_3');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_17_3');
M_.endo_partitions = struct();
M_.param_names = 'cofintintb1';
M_.param_names_tex = 'cofintintb1';
M_.param_names_long = 'cofintintb1';
M_.param_names = char(M_.param_names, 'cofintintb2');
M_.param_names_tex = char(M_.param_names_tex, 'cofintintb2');
M_.param_names_long = char(M_.param_names_long, 'cofintintb2');
M_.param_names = char(M_.param_names, 'cofintintb3');
M_.param_names_tex = char(M_.param_names_tex, 'cofintintb3');
M_.param_names_long = char(M_.param_names_long, 'cofintintb3');
M_.param_names = char(M_.param_names, 'cofintintb4');
M_.param_names_tex = char(M_.param_names_tex, 'cofintintb4');
M_.param_names_long = char(M_.param_names_long, 'cofintintb4');
M_.param_names = char(M_.param_names, 'cofintinf0');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinf0');
M_.param_names_long = char(M_.param_names_long, 'cofintinf0');
M_.param_names = char(M_.param_names, 'cofintinfb1');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinfb1');
M_.param_names_long = char(M_.param_names_long, 'cofintinfb1');
M_.param_names = char(M_.param_names, 'cofintinfb2');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinfb2');
M_.param_names_long = char(M_.param_names_long, 'cofintinfb2');
M_.param_names = char(M_.param_names, 'cofintinfb3');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinfb3');
M_.param_names_long = char(M_.param_names_long, 'cofintinfb3');
M_.param_names = char(M_.param_names, 'cofintinfb4');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinfb4');
M_.param_names_long = char(M_.param_names_long, 'cofintinfb4');
M_.param_names = char(M_.param_names, 'cofintinff1');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinff1');
M_.param_names_long = char(M_.param_names_long, 'cofintinff1');
M_.param_names = char(M_.param_names, 'cofintinff2');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinff2');
M_.param_names_long = char(M_.param_names_long, 'cofintinff2');
M_.param_names = char(M_.param_names, 'cofintinff3');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinff3');
M_.param_names_long = char(M_.param_names_long, 'cofintinff3');
M_.param_names = char(M_.param_names, 'cofintinff4');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinff4');
M_.param_names_long = char(M_.param_names_long, 'cofintinff4');
M_.param_names = char(M_.param_names, 'cofintout');
M_.param_names_tex = char(M_.param_names_tex, 'cofintout');
M_.param_names_long = char(M_.param_names_long, 'cofintout');
M_.param_names = char(M_.param_names, 'cofintoutb1');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutb1');
M_.param_names_long = char(M_.param_names_long, 'cofintoutb1');
M_.param_names = char(M_.param_names, 'cofintoutb2');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutb2');
M_.param_names_long = char(M_.param_names_long, 'cofintoutb2');
M_.param_names = char(M_.param_names, 'cofintoutb3');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutb3');
M_.param_names_long = char(M_.param_names_long, 'cofintoutb3');
M_.param_names = char(M_.param_names, 'cofintoutb4');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutb4');
M_.param_names_long = char(M_.param_names_long, 'cofintoutb4');
M_.param_names = char(M_.param_names, 'cofintoutf1');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutf1');
M_.param_names_long = char(M_.param_names_long, 'cofintoutf1');
M_.param_names = char(M_.param_names, 'cofintoutf2');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutf2');
M_.param_names_long = char(M_.param_names_long, 'cofintoutf2');
M_.param_names = char(M_.param_names, 'cofintoutf3');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutf3');
M_.param_names_long = char(M_.param_names_long, 'cofintoutf3');
M_.param_names = char(M_.param_names, 'cofintoutf4');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutf4');
M_.param_names_long = char(M_.param_names_long, 'cofintoutf4');
M_.param_names = char(M_.param_names, 'cofintoutp');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutp');
M_.param_names_long = char(M_.param_names_long, 'cofintoutp');
M_.param_names = char(M_.param_names, 'cofintoutpb1');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpb1');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpb1');
M_.param_names = char(M_.param_names, 'cofintoutpb2');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpb2');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpb2');
M_.param_names = char(M_.param_names, 'cofintoutpb3');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpb3');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpb3');
M_.param_names = char(M_.param_names, 'cofintoutpb4');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpb4');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpb4');
M_.param_names = char(M_.param_names, 'cofintoutpf1');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpf1');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpf1');
M_.param_names = char(M_.param_names, 'cofintoutpf2');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpf2');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpf2');
M_.param_names = char(M_.param_names, 'cofintoutpf3');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpf3');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpf3');
M_.param_names = char(M_.param_names, 'cofintoutpf4');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpf4');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpf4');
M_.param_names = char(M_.param_names, 'std_r_');
M_.param_names_tex = char(M_.param_names_tex, 'std\_r\_');
M_.param_names_long = char(M_.param_names_long, 'std_r_');
M_.param_names = char(M_.param_names, 'std_r_quart');
M_.param_names_tex = char(M_.param_names_tex, 'std\_r\_quart');
M_.param_names_long = char(M_.param_names_long, 'std_r_quart');
M_.param_names = char(M_.param_names, 'coffispol');
M_.param_names_tex = char(M_.param_names_tex, 'coffispol');
M_.param_names_long = char(M_.param_names_long, 'coffispol');
M_.param_names = char(M_.param_names, 'alpha');
M_.param_names_tex = char(M_.param_names_tex, 'alpha');
M_.param_names_long = char(M_.param_names_long, 'alpha');
M_.param_names = char(M_.param_names, 'beta');
M_.param_names_tex = char(M_.param_names_tex, 'beta');
M_.param_names_long = char(M_.param_names_long, 'beta');
M_.param_names = char(M_.param_names, 'gamma_c');
M_.param_names_tex = char(M_.param_names_tex, 'gamma\_c');
M_.param_names_long = char(M_.param_names_long, 'gamma_c');
M_.param_names = char(M_.param_names, 'gamma_c_bar');
M_.param_names_tex = char(M_.param_names_tex, 'gamma\_c\_bar');
M_.param_names_long = char(M_.param_names_long, 'gamma_c_bar');
M_.param_names = char(M_.param_names, 'gamma_g');
M_.param_names_tex = char(M_.param_names_tex, 'gamma\_g');
M_.param_names_long = char(M_.param_names_long, 'gamma_g');
M_.param_names = char(M_.param_names, 'delta');
M_.param_names_tex = char(M_.param_names_tex, 'delta');
M_.param_names_long = char(M_.param_names_long, 'delta');
M_.param_names = char(M_.param_names, 'eta');
M_.param_names_tex = char(M_.param_names_tex, 'eta');
M_.param_names_long = char(M_.param_names_long, 'eta');
M_.param_names = char(M_.param_names, 'theta');
M_.param_names_tex = char(M_.param_names_tex, 'theta');
M_.param_names_long = char(M_.param_names_long, 'theta');
M_.param_names = char(M_.param_names, 'theta_n');
M_.param_names_tex = char(M_.param_names_tex, 'theta\_n');
M_.param_names_long = char(M_.param_names_long, 'theta_n');
M_.param_names = char(M_.param_names, 'theta_tau');
M_.param_names_tex = char(M_.param_names_tex, 'theta\_tau');
M_.param_names_long = char(M_.param_names_long, 'theta_tau');
M_.param_names = char(M_.param_names, 'lambda');
M_.param_names_tex = char(M_.param_names_tex, 'lambda');
M_.param_names_long = char(M_.param_names_long, 'lambda');
M_.param_names = char(M_.param_names, 'lambda_p');
M_.param_names_tex = char(M_.param_names_tex, 'lambda\_p');
M_.param_names_long = char(M_.param_names_long, 'lambda_p');
M_.param_names = char(M_.param_names, 'my_p');
M_.param_names_tex = char(M_.param_names_tex, 'my\_p');
M_.param_names_long = char(M_.param_names_long, 'my_p');
M_.param_names = char(M_.param_names, 'rho');
M_.param_names_tex = char(M_.param_names_tex, 'rho');
M_.param_names_long = char(M_.param_names_long, 'rho');
M_.param_names = char(M_.param_names, 'rho_g');
M_.param_names_tex = char(M_.param_names_tex, 'rho\_g');
M_.param_names_long = char(M_.param_names_long, 'rho_g');
M_.param_names = char(M_.param_names, 'sigma_bar');
M_.param_names_tex = char(M_.param_names_tex, 'sigma\_bar');
M_.param_names_long = char(M_.param_names_long, 'sigma_bar');
M_.param_names = char(M_.param_names, 'phi_b');
M_.param_names_tex = char(M_.param_names_tex, 'phi\_b');
M_.param_names_long = char(M_.param_names_long, 'phi_b');
M_.param_names = char(M_.param_names, 'phi_g');
M_.param_names_tex = char(M_.param_names_tex, 'phi\_g');
M_.param_names_long = char(M_.param_names_long, 'phi_g');
M_.param_names = char(M_.param_names, 'phi_pi');
M_.param_names_tex = char(M_.param_names_tex, 'phi\_pi');
M_.param_names_long = char(M_.param_names_long, 'phi_pi');
M_.param_names = char(M_.param_names, 'omega');
M_.param_names_tex = char(M_.param_names_tex, 'omega');
M_.param_names_long = char(M_.param_names_long, 'omega');
M_.param_names = char(M_.param_names, 'psi');
M_.param_names_tex = char(M_.param_names_tex, 'psi');
M_.param_names_long = char(M_.param_names_long, 'psi');
M_.param_names = char(M_.param_names, 'phicap');
M_.param_names_tex = char(M_.param_names_tex, 'phicap');
M_.param_names_long = char(M_.param_names_long, 'phicap');
M_.param_partitions = struct();
M_.exo_det_nbr = 0;
M_.exo_nbr = 2;
M_.endo_nbr = 44;
M_.param_nbr = 56;
M_.orig_endo_nbr = 21;
M_.aux_vars(1).endo_index = 22;
M_.aux_vars(1).type = 0;
M_.aux_vars(2).endo_index = 23;
M_.aux_vars(2).type = 0;
M_.aux_vars(3).endo_index = 24;
M_.aux_vars(3).type = 0;
M_.aux_vars(4).endo_index = 25;
M_.aux_vars(4).type = 0;
M_.aux_vars(5).endo_index = 26;
M_.aux_vars(5).type = 0;
M_.aux_vars(6).endo_index = 27;
M_.aux_vars(6).type = 0;
M_.aux_vars(7).endo_index = 28;
M_.aux_vars(7).type = 0;
M_.aux_vars(8).endo_index = 29;
M_.aux_vars(8).type = 0;
M_.aux_vars(9).endo_index = 30;
M_.aux_vars(9).type = 0;
M_.aux_vars(10).endo_index = 31;
M_.aux_vars(10).type = 1;
M_.aux_vars(10).orig_index = 4;
M_.aux_vars(10).orig_lead_lag = -1;
M_.aux_vars(11).endo_index = 32;
M_.aux_vars(11).type = 1;
M_.aux_vars(11).orig_index = 4;
M_.aux_vars(11).orig_lead_lag = -2;
M_.aux_vars(12).endo_index = 33;
M_.aux_vars(12).type = 1;
M_.aux_vars(12).orig_index = 20;
M_.aux_vars(12).orig_lead_lag = -1;
M_.aux_vars(13).endo_index = 34;
M_.aux_vars(13).type = 1;
M_.aux_vars(13).orig_index = 20;
M_.aux_vars(13).orig_lead_lag = -2;
M_.aux_vars(14).endo_index = 35;
M_.aux_vars(14).type = 1;
M_.aux_vars(14).orig_index = 20;
M_.aux_vars(14).orig_lead_lag = -3;
M_.aux_vars(15).endo_index = 36;
M_.aux_vars(15).type = 1;
M_.aux_vars(15).orig_index = 19;
M_.aux_vars(15).orig_lead_lag = -1;
M_.aux_vars(16).endo_index = 37;
M_.aux_vars(16).type = 1;
M_.aux_vars(16).orig_index = 19;
M_.aux_vars(16).orig_lead_lag = -2;
M_.aux_vars(17).endo_index = 38;
M_.aux_vars(17).type = 1;
M_.aux_vars(17).orig_index = 19;
M_.aux_vars(17).orig_lead_lag = -3;
M_.aux_vars(18).endo_index = 39;
M_.aux_vars(18).type = 1;
M_.aux_vars(18).orig_index = 16;
M_.aux_vars(18).orig_lead_lag = -1;
M_.aux_vars(19).endo_index = 40;
M_.aux_vars(19).type = 1;
M_.aux_vars(19).orig_index = 16;
M_.aux_vars(19).orig_lead_lag = -2;
M_.aux_vars(20).endo_index = 41;
M_.aux_vars(20).type = 1;
M_.aux_vars(20).orig_index = 16;
M_.aux_vars(20).orig_lead_lag = -3;
M_.aux_vars(21).endo_index = 42;
M_.aux_vars(21).type = 1;
M_.aux_vars(21).orig_index = 18;
M_.aux_vars(21).orig_lead_lag = -1;
M_.aux_vars(22).endo_index = 43;
M_.aux_vars(22).type = 1;
M_.aux_vars(22).orig_index = 18;
M_.aux_vars(22).orig_lead_lag = -2;
M_.aux_vars(23).endo_index = 44;
M_.aux_vars(23).type = 1;
M_.aux_vars(23).orig_index = 18;
M_.aux_vars(23).orig_lead_lag = -3;
M_.predetermined_variables = [ 5 6 12 13 ];
M_.Sigma_e = zeros(2, 2);
M_.Correlation_matrix = eye(2, 2);
M_.H = 0;
M_.Correlation_matrix_ME = 1;
M_.sigma_e_is_diagonal = 1;
M_.det_shocks = [];
options_.block=0;
options_.bytecode=0;
options_.use_dll=0;
M_.hessian_eq_zero = 1;
erase_compiled_function('NK_GLSV07_static');
erase_compiled_function('NK_GLSV07_dynamic');
M_.orig_eq_nbr = 21;
M_.eq_nbr = 44;
M_.ramsey_eq_nbr = 0;
M_.set_auxiliary_variables = exist(['./' M_.fname '_set_auxiliary_variables.m'], 'file') == 2;
M_.lead_lag_incidence = [
 0 25 69;
 0 26 70;
 0 27 0;
 1 28 71;
 2 29 0;
 3 30 0;
 4 31 0;
 0 32 0;
 0 33 0;
 0 34 72;
 0 35 73;
 5 36 0;
 6 37 0;
 0 38 0;
 0 39 0;
 7 40 0;
 0 41 0;
 8 42 74;
 9 43 75;
 10 44 76;
 0 45 0;
 0 46 77;
 0 47 78;
 0 48 79;
 0 49 80;
 0 50 81;
 0 51 82;
 0 52 83;
 0 53 84;
 0 54 85;
 11 55 0;
 12 56 0;
 13 57 0;
 14 58 0;
 15 59 0;
 16 60 0;
 17 61 0;
 18 62 0;
 19 63 0;
 20 64 0;
 21 65 0;
 22 66 0;
 23 67 0;
 24 68 0;]';
M_.nstatic = 7;
M_.nfwrd   = 13;
M_.npred   = 20;
M_.nboth   = 4;
M_.nsfwrd   = 17;
M_.nspred   = 24;
M_.ndynamic   = 37;
M_.equations_tags = {
};
M_.static_and_dynamic_models_differ = 0;
M_.exo_names_orig_ord = [1:2];
M_.maximum_lag = 1;
M_.maximum_lead = 1;
M_.maximum_endo_lag = 1;
M_.maximum_endo_lead = 1;
oo_.steady_state = zeros(44, 1);
M_.maximum_exo_lag = 0;
M_.maximum_exo_lead = 0;
oo_.exo_steady_state = zeros(2, 1);
M_.params = NaN(56, 1);
M_.NNZDerivatives = [164; 0; -1];
thispath = cd;                                                           
cd('..');                                                                
load policy_param.mat;                                                   
for i=1:33                                                               
deep_parameter_name = M_.param_names(i,:);                           
eval(['M_.params(i)  = ' deep_parameter_name ' ;'])                  
end                                                                      
cd(thispath);                                                                         
M_.params( 34 ) = 1;
coffispol = M_.params( 34 );
M_.params( 35 ) = 0.33;
alpha = M_.params( 35 );
M_.params( 36 ) = 0.99;
beta = M_.params( 36 );
M_.params( 39 ) = 0.2;
gamma_g = M_.params( 39 );
M_.params( 40 ) = 0.025;
delta = M_.params( 40 );
M_.params( 41 ) = 1;
eta = M_.params( 41 );
M_.params( 42 ) = 0.75;
theta = M_.params( 42 );
M_.params( 45 ) = 0.5;
lambda = M_.params( 45 );
M_.params( 47 ) = 1.2;
my_p = M_.params( 47 );
M_.params( 55 ) = 0.2;
psi = M_.params( 55 );
M_.params( 53 ) = 1.5;
phi_pi = M_.params( 53 );
M_.params( 48 ) = M_.params(36)^(-1)-1;
rho = M_.params( 48 );
M_.params( 37 ) = 1-M_.params(39)-M_.params(40)*M_.params(35)/((M_.params(40)+M_.params(48))*M_.params(47));
gamma_c = M_.params( 37 );
M_.params( 38 ) = M_.params(39)+M_.params(37);
gamma_c_bar = M_.params( 38 );
M_.params( 46 ) = (1-M_.params(36)*M_.params(42))*(1-M_.params(42))/M_.params(42);
lambda_p = M_.params( 46 );
M_.params( 51 ) = 0.33;
phi_b = M_.params( 51 );
M_.params( 52 ) = 0.10;
phi_g = M_.params( 52 );
M_.params( 49 ) = 0.9;
rho_g = M_.params( 49 );
M_.params( 56 ) = 1/(M_.params(47)*M_.params(37)-M_.params(45)*(1-M_.params(35)));
phicap = M_.params( 56 );
M_.params( 50 ) = 1/(M_.params(47)*M_.params(37)*(1-M_.params(45))*M_.params(56));
sigma_bar = M_.params( 50 );
M_.params( 54 ) = M_.params(41)*(1-M_.params(36)*(1-M_.params(40)))*(1-M_.params(38));
omega = M_.params( 54 );
M_.params( 44 ) = M_.params(47)*M_.params(45)*M_.params(56);
theta_tau = M_.params( 44 );
M_.params( 43 ) = (1-M_.params(35))*M_.params(45)*M_.params(56)*(1+M_.params(55));
theta_n = M_.params( 43 );
%
% SHOCKS instructions
%
M_.exo_det_length = 0;
M_.Sigma_e(2, 2) = (0)^2;
save('NK_GLSV07_results.mat', 'oo_', 'M_', 'options_');
if exist('estim_params_', 'var') == 1
  save('NK_GLSV07_results.mat', 'estim_params_', '-append');
end
if exist('bayestopt_', 'var') == 1
  save('NK_GLSV07_results.mat', 'bayestopt_', '-append');
end
if exist('dataset_', 'var') == 1
  save('NK_GLSV07_results.mat', 'dataset_', '-append');
end
if exist('estimation_info', 'var') == 1
  save('NK_GLSV07_results.mat', 'estimation_info', '-append');
end
if exist('dataset_info', 'var') == 1
  save('NK_GLSV07_results.mat', 'dataset_info', '-append');
end
if exist('oo_recursive_', 'var') == 1
  save('NK_GLSV07_results.mat', 'oo_recursive_', '-append');
end


disp(['Total computing time : ' dynsec2hms(toc(tic0)) ]);
if ~isempty(lastwarn)
  disp('Note: warning(s) encountered in MATLAB/Octave code')
end
diary off
