%
% Status : main Dynare file 
%
% Warning : this file is generated automatically by Dynare
%           from model file (.mod)

tic;
global M_ oo_ options_ ys0_ ex0_ estimation_info
options_ = [];
M_.fname = 'EA_QR14';
%
% Some global variables initialization
%
global_initialization;
diary off;
diary('EA_QR14.log');
M_.exo_names = 'e_premium';
M_.exo_names_tex = 'e\_premium';
M_.exo_names_long = 'e_premium';
M_.exo_names = char(M_.exo_names, 'e_risk');
M_.exo_names_tex = char(M_.exo_names_tex, 'e\_risk');
M_.exo_names_long = char(M_.exo_names_long, 'e_risk');
M_.exo_names = char(M_.exo_names, 'e_risk_s');
M_.exo_names_tex = char(M_.exo_names_tex, 'e\_risk\_s');
M_.exo_names_long = char(M_.exo_names_long, 'e_risk_s');
M_.exo_names = char(M_.exo_names, 'e_prefd');
M_.exo_names_tex = char(M_.exo_names_tex, 'e\_prefd');
M_.exo_names_long = char(M_.exo_names_long, 'e_prefd');
M_.exo_names = char(M_.exo_names, 'e_prefd_s');
M_.exo_names_tex = char(M_.exo_names_tex, 'e\_prefd\_s');
M_.exo_names_long = char(M_.exo_names_long, 'e_prefd_s');
M_.exo_names = char(M_.exo_names, 'e_prefc');
M_.exo_names_tex = char(M_.exo_names_tex, 'e\_prefc');
M_.exo_names_long = char(M_.exo_names_long, 'e_prefc');
M_.exo_names = char(M_.exo_names, 'e_prefc_s');
M_.exo_names_tex = char(M_.exo_names_tex, 'e\_prefc\_s');
M_.exo_names_long = char(M_.exo_names_long, 'e_prefc_s');
M_.exo_names = char(M_.exo_names, 'e_techc');
M_.exo_names_tex = char(M_.exo_names_tex, 'e\_techc');
M_.exo_names_long = char(M_.exo_names_long, 'e_techc');
M_.exo_names = char(M_.exo_names, 'e_techd');
M_.exo_names_tex = char(M_.exo_names_tex, 'e\_techd');
M_.exo_names_long = char(M_.exo_names_long, 'e_techd');
M_.exo_names = char(M_.exo_names, 'e_techc_s');
M_.exo_names_tex = char(M_.exo_names_tex, 'e\_techc\_s');
M_.exo_names_long = char(M_.exo_names_long, 'e_techc_s');
M_.exo_names = char(M_.exo_names, 'e_techd_s');
M_.exo_names_tex = char(M_.exo_names_tex, 'e\_techd\_s');
M_.exo_names_long = char(M_.exo_names_long, 'e_techd_s');
M_.exo_names = char(M_.exo_names, 'e_tech');
M_.exo_names_tex = char(M_.exo_names_tex, 'e\_tech');
M_.exo_names_long = char(M_.exo_names_long, 'e_tech');
M_.exo_names = char(M_.exo_names, 'e_prefd_com');
M_.exo_names_tex = char(M_.exo_names_tex, 'e\_prefd\_com');
M_.exo_names_long = char(M_.exo_names_long, 'e_prefd_com');
M_.exo_names = char(M_.exo_names, 'e_techc_com');
M_.exo_names_tex = char(M_.exo_names_tex, 'e\_techc\_com');
M_.exo_names_long = char(M_.exo_names_long, 'e_techc_com');
M_.exo_names = char(M_.exo_names, 'interest_');
M_.exo_names_tex = char(M_.exo_names_tex, 'interest\_');
M_.exo_names_long = char(M_.exo_names_long, 'interest_');
M_.endo_names = 'q';
M_.endo_names_tex = 'q';
M_.endo_names_long = 'q';
M_.endo_names = char(M_.endo_names, 'c');
M_.endo_names_tex = char(M_.endo_names_tex, 'c');
M_.endo_names_long = char(M_.endo_names_long, 'c');
M_.endo_names = char(M_.endo_names, 'd');
M_.endo_names_tex = char(M_.endo_names_tex, 'd');
M_.endo_names_long = char(M_.endo_names_long, 'd');
M_.endo_names = char(M_.endo_names, 'c_borr');
M_.endo_names_tex = char(M_.endo_names_tex, 'c\_borr');
M_.endo_names_long = char(M_.endo_names_long, 'c_borr');
M_.endo_names = char(M_.endo_names, 'd_borr');
M_.endo_names_tex = char(M_.endo_names_tex, 'd\_borr');
M_.endo_names_long = char(M_.endo_names_long, 'd_borr');
M_.endo_names = char(M_.endo_names, 'dpd');
M_.endo_names_tex = char(M_.endo_names_tex, 'dpd');
M_.endo_names_long = char(M_.endo_names_long, 'dpd');
M_.endo_names = char(M_.endo_names, 'dpc');
M_.endo_names_tex = char(M_.endo_names_tex, 'dpc');
M_.endo_names_long = char(M_.endo_names_long, 'dpc');
M_.endo_names = char(M_.endo_names, 'dph');
M_.endo_names_tex = char(M_.endo_names_tex, 'dph');
M_.endo_names_long = char(M_.endo_names_long, 'dph');
M_.endo_names = char(M_.endo_names, 'lc_tot');
M_.endo_names_tex = char(M_.endo_names_tex, 'lc\_tot');
M_.endo_names_long = char(M_.endo_names_long, 'lc_tot');
M_.endo_names = char(M_.endo_names, 'ld_tot');
M_.endo_names_tex = char(M_.endo_names_tex, 'ld\_tot');
M_.endo_names_long = char(M_.endo_names_long, 'ld_tot');
M_.endo_names = char(M_.endo_names, 'l');
M_.endo_names_tex = char(M_.endo_names_tex, 'l');
M_.endo_names_long = char(M_.endo_names_long, 'l');
M_.endo_names = char(M_.endo_names, 'l_borr');
M_.endo_names_tex = char(M_.endo_names_tex, 'l\_borr');
M_.endo_names_long = char(M_.endo_names_long, 'l_borr');
M_.endo_names = char(M_.endo_names, 'lc');
M_.endo_names_tex = char(M_.endo_names_tex, 'lc');
M_.endo_names_long = char(M_.endo_names_long, 'lc');
M_.endo_names = char(M_.endo_names, 'ld');
M_.endo_names_tex = char(M_.endo_names_tex, 'ld');
M_.endo_names_long = char(M_.endo_names_long, 'ld');
M_.endo_names = char(M_.endo_names, 'lc_borr');
M_.endo_names_tex = char(M_.endo_names_tex, 'lc\_borr');
M_.endo_names_long = char(M_.endo_names_long, 'lc_borr');
M_.endo_names = char(M_.endo_names, 'ld_borr');
M_.endo_names_tex = char(M_.endo_names_tex, 'ld\_borr');
M_.endo_names_long = char(M_.endo_names_long, 'ld_borr');
M_.endo_names = char(M_.endo_names, 'wc');
M_.endo_names_tex = char(M_.endo_names_tex, 'wc');
M_.endo_names_long = char(M_.endo_names_long, 'wc');
M_.endo_names = char(M_.endo_names, 'wd');
M_.endo_names_tex = char(M_.endo_names_tex, 'wd');
M_.endo_names_long = char(M_.endo_names_long, 'wd');
M_.endo_names = char(M_.endo_names, 'yc');
M_.endo_names_tex = char(M_.endo_names_tex, 'yc');
M_.endo_names_long = char(M_.endo_names_long, 'yc');
M_.endo_names = char(M_.endo_names, 'yd');
M_.endo_names_tex = char(M_.endo_names_tex, 'yd');
M_.endo_names_long = char(M_.endo_names_long, 'yd');
M_.endo_names = char(M_.endo_names, 'varrho');
M_.endo_names_tex = char(M_.endo_names_tex, 'varrho');
M_.endo_names_long = char(M_.endo_names_long, 'varrho');
M_.endo_names = char(M_.endo_names, 'inv');
M_.endo_names_tex = char(M_.endo_names_tex, 'inv');
M_.endo_names_long = char(M_.endo_names_long, 'inv');
M_.endo_names = char(M_.endo_names, 'varrho_borr');
M_.endo_names_tex = char(M_.endo_names_tex, 'varrho\_borr');
M_.endo_names_long = char(M_.endo_names_long, 'varrho_borr');
M_.endo_names = char(M_.endo_names, 'inv_borr');
M_.endo_names_tex = char(M_.endo_names_tex, 'inv\_borr');
M_.endo_names_long = char(M_.endo_names_long, 'inv_borr');
M_.endo_names = char(M_.endo_names, 'q_s');
M_.endo_names_tex = char(M_.endo_names_tex, 'q\_s');
M_.endo_names_long = char(M_.endo_names_long, 'q_s');
M_.endo_names = char(M_.endo_names, 'c_s');
M_.endo_names_tex = char(M_.endo_names_tex, 'c\_s');
M_.endo_names_long = char(M_.endo_names_long, 'c_s');
M_.endo_names = char(M_.endo_names, 'd_s');
M_.endo_names_tex = char(M_.endo_names_tex, 'd\_s');
M_.endo_names_long = char(M_.endo_names_long, 'd_s');
M_.endo_names = char(M_.endo_names, 'c_s_borr');
M_.endo_names_tex = char(M_.endo_names_tex, 'c\_s\_borr');
M_.endo_names_long = char(M_.endo_names_long, 'c_s_borr');
M_.endo_names = char(M_.endo_names, 'd_s_borr');
M_.endo_names_tex = char(M_.endo_names_tex, 'd\_s\_borr');
M_.endo_names_long = char(M_.endo_names_long, 'd_s_borr');
M_.endo_names = char(M_.endo_names, 'dpd_s');
M_.endo_names_tex = char(M_.endo_names_tex, 'dpd\_s');
M_.endo_names_long = char(M_.endo_names_long, 'dpd_s');
M_.endo_names = char(M_.endo_names, 'dpc_s');
M_.endo_names_tex = char(M_.endo_names_tex, 'dpc\_s');
M_.endo_names_long = char(M_.endo_names_long, 'dpc_s');
M_.endo_names = char(M_.endo_names, 'dpf');
M_.endo_names_tex = char(M_.endo_names_tex, 'dpf');
M_.endo_names_long = char(M_.endo_names_long, 'dpf');
M_.endo_names = char(M_.endo_names, 'lc_s_tot');
M_.endo_names_tex = char(M_.endo_names_tex, 'lc\_s\_tot');
M_.endo_names_long = char(M_.endo_names_long, 'lc_s_tot');
M_.endo_names = char(M_.endo_names, 'ld_s_tot');
M_.endo_names_tex = char(M_.endo_names_tex, 'ld\_s\_tot');
M_.endo_names_long = char(M_.endo_names_long, 'ld_s_tot');
M_.endo_names = char(M_.endo_names, 'l_s');
M_.endo_names_tex = char(M_.endo_names_tex, 'l\_s');
M_.endo_names_long = char(M_.endo_names_long, 'l_s');
M_.endo_names = char(M_.endo_names, 'l_s_borr');
M_.endo_names_tex = char(M_.endo_names_tex, 'l\_s\_borr');
M_.endo_names_long = char(M_.endo_names_long, 'l_s_borr');
M_.endo_names = char(M_.endo_names, 'lc_s');
M_.endo_names_tex = char(M_.endo_names_tex, 'lc\_s');
M_.endo_names_long = char(M_.endo_names_long, 'lc_s');
M_.endo_names = char(M_.endo_names, 'ld_s');
M_.endo_names_tex = char(M_.endo_names_tex, 'ld\_s');
M_.endo_names_long = char(M_.endo_names_long, 'ld_s');
M_.endo_names = char(M_.endo_names, 'lc_s_borr');
M_.endo_names_tex = char(M_.endo_names_tex, 'lc\_s\_borr');
M_.endo_names_long = char(M_.endo_names_long, 'lc_s_borr');
M_.endo_names = char(M_.endo_names, 'ld_s_borr');
M_.endo_names_tex = char(M_.endo_names_tex, 'ld\_s\_borr');
M_.endo_names_long = char(M_.endo_names_long, 'ld_s_borr');
M_.endo_names = char(M_.endo_names, 'wc_s');
M_.endo_names_tex = char(M_.endo_names_tex, 'wc\_s');
M_.endo_names_long = char(M_.endo_names_long, 'wc_s');
M_.endo_names = char(M_.endo_names, 'wd_s');
M_.endo_names_tex = char(M_.endo_names_tex, 'wd\_s');
M_.endo_names_long = char(M_.endo_names_long, 'wd_s');
M_.endo_names = char(M_.endo_names, 'yc_s');
M_.endo_names_tex = char(M_.endo_names_tex, 'yc\_s');
M_.endo_names_long = char(M_.endo_names_long, 'yc_s');
M_.endo_names = char(M_.endo_names, 'yd_s');
M_.endo_names_tex = char(M_.endo_names_tex, 'yd\_s');
M_.endo_names_long = char(M_.endo_names_long, 'yd_s');
M_.endo_names = char(M_.endo_names, 'varrho_s');
M_.endo_names_tex = char(M_.endo_names_tex, 'varrho\_s');
M_.endo_names_long = char(M_.endo_names_long, 'varrho_s');
M_.endo_names = char(M_.endo_names, 'inv_s');
M_.endo_names_tex = char(M_.endo_names_tex, 'inv\_s');
M_.endo_names_long = char(M_.endo_names_long, 'inv_s');
M_.endo_names = char(M_.endo_names, 'varrho_s_borr');
M_.endo_names_tex = char(M_.endo_names_tex, 'varrho\_s\_borr');
M_.endo_names_long = char(M_.endo_names_long, 'varrho_s_borr');
M_.endo_names = char(M_.endo_names, 'inv_s_borr');
M_.endo_names_tex = char(M_.endo_names_tex, 'inv\_s\_borr');
M_.endo_names_long = char(M_.endo_names_long, 'inv_s_borr');
M_.endo_names = char(M_.endo_names, 'ch');
M_.endo_names_tex = char(M_.endo_names_tex, 'ch');
M_.endo_names_long = char(M_.endo_names_long, 'ch');
M_.endo_names = char(M_.endo_names, 'cf');
M_.endo_names_tex = char(M_.endo_names_tex, 'cf');
M_.endo_names_long = char(M_.endo_names_long, 'cf');
M_.endo_names = char(M_.endo_names, 'c_tot');
M_.endo_names_tex = char(M_.endo_names_tex, 'c\_tot');
M_.endo_names_long = char(M_.endo_names_long, 'c_tot');
M_.endo_names = char(M_.endo_names, 'ch_s');
M_.endo_names_tex = char(M_.endo_names_tex, 'ch\_s');
M_.endo_names_long = char(M_.endo_names_long, 'ch_s');
M_.endo_names = char(M_.endo_names, 'cf_s');
M_.endo_names_tex = char(M_.endo_names_tex, 'cf\_s');
M_.endo_names_long = char(M_.endo_names_long, 'cf_s');
M_.endo_names = char(M_.endo_names, 'c_s_tot');
M_.endo_names_tex = char(M_.endo_names_tex, 'c\_s\_tot');
M_.endo_names_long = char(M_.endo_names_long, 'c_s_tot');
M_.endo_names = char(M_.endo_names, 's_s_borr');
M_.endo_names_tex = char(M_.endo_names_tex, 's\_s\_borr');
M_.endo_names_long = char(M_.endo_names_long, 's_s_borr');
M_.endo_names = char(M_.endo_names, 's_borr');
M_.endo_names_tex = char(M_.endo_names_tex, 's\_borr');
M_.endo_names_long = char(M_.endo_names_long, 's_borr');
M_.endo_names = char(M_.endo_names, 'r');
M_.endo_names_tex = char(M_.endo_names_tex, 'r');
M_.endo_names_long = char(M_.endo_names_long, 'r');
M_.endo_names = char(M_.endo_names, 'r_s');
M_.endo_names_tex = char(M_.endo_names_tex, 'r\_s');
M_.endo_names_long = char(M_.endo_names_long, 'r_s');
M_.endo_names = char(M_.endo_names, 'omegaa');
M_.endo_names_tex = char(M_.endo_names_tex, 'omegaa');
M_.endo_names_long = char(M_.endo_names_long, 'omegaa');
M_.endo_names = char(M_.endo_names, 'omegaa_s');
M_.endo_names_tex = char(M_.endo_names_tex, 'omegaa\_s');
M_.endo_names_long = char(M_.endo_names_long, 'omegaa_s');
M_.endo_names = char(M_.endo_names, 'omegap');
M_.endo_names_tex = char(M_.endo_names_tex, 'omegap');
M_.endo_names_long = char(M_.endo_names_long, 'omegap');
M_.endo_names = char(M_.endo_names, 'omegap_s');
M_.endo_names_tex = char(M_.endo_names_tex, 'omegap\_s');
M_.endo_names_long = char(M_.endo_names_long, 'omegap_s');
M_.endo_names = char(M_.endo_names, 'Fa');
M_.endo_names_tex = char(M_.endo_names_tex, 'Fa');
M_.endo_names_long = char(M_.endo_names_long, 'Fa');
M_.endo_names = char(M_.endo_names, 'Fa_s');
M_.endo_names_tex = char(M_.endo_names_tex, 'Fa\_s');
M_.endo_names_long = char(M_.endo_names_long, 'Fa_s');
M_.endo_names = char(M_.endo_names, 'Fp');
M_.endo_names_tex = char(M_.endo_names_tex, 'Fp');
M_.endo_names_long = char(M_.endo_names_long, 'Fp');
M_.endo_names = char(M_.endo_names, 'Fp_s');
M_.endo_names_tex = char(M_.endo_names_tex, 'Fp\_s');
M_.endo_names_long = char(M_.endo_names_long, 'Fp_s');
M_.endo_names = char(M_.endo_names, 'Ga');
M_.endo_names_tex = char(M_.endo_names_tex, 'Ga');
M_.endo_names_long = char(M_.endo_names_long, 'Ga');
M_.endo_names = char(M_.endo_names, 'Ga_s');
M_.endo_names_tex = char(M_.endo_names_tex, 'Ga\_s');
M_.endo_names_long = char(M_.endo_names_long, 'Ga_s');
M_.endo_names = char(M_.endo_names, 'Gp');
M_.endo_names_tex = char(M_.endo_names_tex, 'Gp');
M_.endo_names_long = char(M_.endo_names_long, 'Gp');
M_.endo_names = char(M_.endo_names, 'Gp_s');
M_.endo_names_tex = char(M_.endo_names_tex, 'Gp\_s');
M_.endo_names_long = char(M_.endo_names_long, 'Gp_s');
M_.endo_names = char(M_.endo_names, 'terms');
M_.endo_names_tex = char(M_.endo_names_tex, 'terms');
M_.endo_names_long = char(M_.endo_names_long, 'terms');
M_.endo_names = char(M_.endo_names, 'dpemu');
M_.endo_names_tex = char(M_.endo_names_tex, 'dpemu');
M_.endo_names_long = char(M_.endo_names_long, 'dpemu');
M_.endo_names = char(M_.endo_names, 'b');
M_.endo_names_tex = char(M_.endo_names_tex, 'b');
M_.endo_names_long = char(M_.endo_names_long, 'b');
M_.endo_names = char(M_.endo_names, 'rl');
M_.endo_names_tex = char(M_.endo_names_tex, 'rl');
M_.endo_names_long = char(M_.endo_names_long, 'rl');
M_.endo_names = char(M_.endo_names, 'rl_s');
M_.endo_names_tex = char(M_.endo_names_tex, 'rl\_s');
M_.endo_names_long = char(M_.endo_names_long, 'rl_s');
M_.endo_names = char(M_.endo_names, 'rd');
M_.endo_names_tex = char(M_.endo_names_tex, 'rd');
M_.endo_names_long = char(M_.endo_names_long, 'rd');
M_.endo_names = char(M_.endo_names, 'rd_s');
M_.endo_names_tex = char(M_.endo_names_tex, 'rd\_s');
M_.endo_names_long = char(M_.endo_names_long, 'rd_s');
M_.endo_names = char(M_.endo_names, 'y');
M_.endo_names_tex = char(M_.endo_names_tex, 'y');
M_.endo_names_long = char(M_.endo_names_long, 'y');
M_.endo_names = char(M_.endo_names, 'y_s');
M_.endo_names_tex = char(M_.endo_names_tex, 'y\_s');
M_.endo_names_long = char(M_.endo_names_long, 'y_s');
M_.endo_names = char(M_.endo_names, 'y_emu');
M_.endo_names_tex = char(M_.endo_names_tex, 'y\_emu');
M_.endo_names_long = char(M_.endo_names_long, 'y_emu');
M_.endo_names = char(M_.endo_names, 'yctilde');
M_.endo_names_tex = char(M_.endo_names_tex, 'yctilde');
M_.endo_names_long = char(M_.endo_names_long, 'yctilde');
M_.endo_names = char(M_.endo_names, 'yctilde_s');
M_.endo_names_tex = char(M_.endo_names_tex, 'yctilde\_s');
M_.endo_names_long = char(M_.endo_names_long, 'yctilde_s');
M_.endo_names = char(M_.endo_names, 'ydtilde');
M_.endo_names_tex = char(M_.endo_names_tex, 'ydtilde');
M_.endo_names_long = char(M_.endo_names_long, 'ydtilde');
M_.endo_names = char(M_.endo_names, 'ydtilde_s');
M_.endo_names_tex = char(M_.endo_names_tex, 'ydtilde\_s');
M_.endo_names_long = char(M_.endo_names_long, 'ydtilde_s');
M_.endo_names = char(M_.endo_names, 'phtilde');
M_.endo_names_tex = char(M_.endo_names_tex, 'phtilde');
M_.endo_names_long = char(M_.endo_names_long, 'phtilde');
M_.endo_names = char(M_.endo_names, 'pftilde');
M_.endo_names_tex = char(M_.endo_names_tex, 'pftilde');
M_.endo_names_long = char(M_.endo_names_long, 'pftilde');
M_.endo_names = char(M_.endo_names, 'pdtilde');
M_.endo_names_tex = char(M_.endo_names_tex, 'pdtilde');
M_.endo_names_long = char(M_.endo_names_long, 'pdtilde');
M_.endo_names = char(M_.endo_names, 'pdtilde_s');
M_.endo_names_tex = char(M_.endo_names_tex, 'pdtilde\_s');
M_.endo_names_long = char(M_.endo_names_long, 'pdtilde_s');
M_.endo_names = char(M_.endo_names, 'XC1');
M_.endo_names_tex = char(M_.endo_names_tex, 'XC1');
M_.endo_names_long = char(M_.endo_names_long, 'XC1');
M_.endo_names = char(M_.endo_names, 'XC2');
M_.endo_names_tex = char(M_.endo_names_tex, 'XC2');
M_.endo_names_long = char(M_.endo_names_long, 'XC2');
M_.endo_names = char(M_.endo_names, 'XC1_s');
M_.endo_names_tex = char(M_.endo_names_tex, 'XC1\_s');
M_.endo_names_long = char(M_.endo_names_long, 'XC1_s');
M_.endo_names = char(M_.endo_names, 'XC2_s');
M_.endo_names_tex = char(M_.endo_names_tex, 'XC2\_s');
M_.endo_names_long = char(M_.endo_names_long, 'XC2_s');
M_.endo_names = char(M_.endo_names, 'XD1');
M_.endo_names_tex = char(M_.endo_names_tex, 'XD1');
M_.endo_names_long = char(M_.endo_names_long, 'XD1');
M_.endo_names = char(M_.endo_names, 'XD2');
M_.endo_names_tex = char(M_.endo_names_tex, 'XD2');
M_.endo_names_long = char(M_.endo_names_long, 'XD2');
M_.endo_names = char(M_.endo_names, 'XD1_s');
M_.endo_names_tex = char(M_.endo_names_tex, 'XD1\_s');
M_.endo_names_long = char(M_.endo_names_long, 'XD1_s');
M_.endo_names = char(M_.endo_names, 'XD2_s');
M_.endo_names_tex = char(M_.endo_names_tex, 'XD2\_s');
M_.endo_names_long = char(M_.endo_names_long, 'XD2_s');
M_.endo_names = char(M_.endo_names, 'mcc');
M_.endo_names_tex = char(M_.endo_names_tex, 'mcc');
M_.endo_names_long = char(M_.endo_names_long, 'mcc');
M_.endo_names = char(M_.endo_names, 'mcc_s');
M_.endo_names_tex = char(M_.endo_names_tex, 'mcc\_s');
M_.endo_names_long = char(M_.endo_names_long, 'mcc_s');
M_.endo_names = char(M_.endo_names, 'mcd');
M_.endo_names_tex = char(M_.endo_names_tex, 'mcd');
M_.endo_names_long = char(M_.endo_names_long, 'mcd');
M_.endo_names = char(M_.endo_names, 'mcd_s');
M_.endo_names_tex = char(M_.endo_names_tex, 'mcd\_s');
M_.endo_names_long = char(M_.endo_names_long, 'mcd_s');
M_.endo_names = char(M_.endo_names, 'mautil');
M_.endo_names_tex = char(M_.endo_names_tex, 'mautil');
M_.endo_names_long = char(M_.endo_names_long, 'mautil');
M_.endo_names = char(M_.endo_names, 'mautil_s');
M_.endo_names_tex = char(M_.endo_names_tex, 'mautil\_s');
M_.endo_names_long = char(M_.endo_names_long, 'mautil_s');
M_.endo_names = char(M_.endo_names, 'vc');
M_.endo_names_tex = char(M_.endo_names_tex, 'vc');
M_.endo_names_long = char(M_.endo_names_long, 'vc');
M_.endo_names = char(M_.endo_names, 'vc_s');
M_.endo_names_tex = char(M_.endo_names_tex, 'vc\_s');
M_.endo_names_long = char(M_.endo_names_long, 'vc_s');
M_.endo_names = char(M_.endo_names, 'vd');
M_.endo_names_tex = char(M_.endo_names_tex, 'vd');
M_.endo_names_long = char(M_.endo_names_long, 'vd');
M_.endo_names = char(M_.endo_names, 'vd_s');
M_.endo_names_tex = char(M_.endo_names_tex, 'vd\_s');
M_.endo_names_long = char(M_.endo_names_long, 'vd_s');
M_.endo_names = char(M_.endo_names, 'util');
M_.endo_names_tex = char(M_.endo_names_tex, 'util');
M_.endo_names_long = char(M_.endo_names_long, 'util');
M_.endo_names = char(M_.endo_names, 'util_borr');
M_.endo_names_tex = char(M_.endo_names_tex, 'util\_borr');
M_.endo_names_long = char(M_.endo_names_long, 'util_borr');
M_.endo_names = char(M_.endo_names, 'welf');
M_.endo_names_tex = char(M_.endo_names_tex, 'welf');
M_.endo_names_long = char(M_.endo_names_long, 'welf');
M_.endo_names = char(M_.endo_names, 'welf_borr');
M_.endo_names_tex = char(M_.endo_names_tex, 'welf\_borr');
M_.endo_names_long = char(M_.endo_names_long, 'welf_borr');
M_.endo_names = char(M_.endo_names, 'util_s');
M_.endo_names_tex = char(M_.endo_names_tex, 'util\_s');
M_.endo_names_long = char(M_.endo_names_long, 'util_s');
M_.endo_names = char(M_.endo_names, 'util_s_borr');
M_.endo_names_tex = char(M_.endo_names_tex, 'util\_s\_borr');
M_.endo_names_long = char(M_.endo_names_long, 'util_s_borr');
M_.endo_names = char(M_.endo_names, 'welf_s');
M_.endo_names_tex = char(M_.endo_names_tex, 'welf\_s');
M_.endo_names_long = char(M_.endo_names_long, 'welf_s');
M_.endo_names = char(M_.endo_names, 'welf_s_borr');
M_.endo_names_tex = char(M_.endo_names_tex, 'welf\_s\_borr');
M_.endo_names_long = char(M_.endo_names_long, 'welf_s_borr');
M_.endo_names = char(M_.endo_names, 'welf_cor');
M_.endo_names_tex = char(M_.endo_names_tex, 'welf\_cor');
M_.endo_names_long = char(M_.endo_names_long, 'welf_cor');
M_.endo_names = char(M_.endo_names, 'welf_per');
M_.endo_names_tex = char(M_.endo_names_tex, 'welf\_per');
M_.endo_names_long = char(M_.endo_names_long, 'welf_per');
M_.endo_names = char(M_.endo_names, 'welf_emu');
M_.endo_names_tex = char(M_.endo_names_tex, 'welf\_emu');
M_.endo_names_long = char(M_.endo_names_long, 'welf_emu');
M_.endo_names = char(M_.endo_names, 'eta');
M_.endo_names_tex = char(M_.endo_names_tex, 'eta');
M_.endo_names_long = char(M_.endo_names_long, 'eta');
M_.endo_names = char(M_.endo_names, 'eta_s');
M_.endo_names_tex = char(M_.endo_names_tex, 'eta\_s');
M_.endo_names_long = char(M_.endo_names_long, 'eta_s');
M_.endo_names = char(M_.endo_names, 'return_default');
M_.endo_names_tex = char(M_.endo_names_tex, 'return\_default');
M_.endo_names_long = char(M_.endo_names_long, 'return_default');
M_.endo_names = char(M_.endo_names, 'return_nondefault');
M_.endo_names_tex = char(M_.endo_names_tex, 'return\_nondefault');
M_.endo_names_long = char(M_.endo_names_long, 'return_nondefault');
M_.endo_names = char(M_.endo_names, 'return_default_s');
M_.endo_names_tex = char(M_.endo_names_tex, 'return\_default\_s');
M_.endo_names_long = char(M_.endo_names_long, 'return_default_s');
M_.endo_names = char(M_.endo_names, 'return_nondefault_s');
M_.endo_names_tex = char(M_.endo_names_tex, 'return\_nondefault\_s');
M_.endo_names_long = char(M_.endo_names_long, 'return_nondefault_s');
M_.endo_names = char(M_.endo_names, 'prefd');
M_.endo_names_tex = char(M_.endo_names_tex, 'prefd');
M_.endo_names_long = char(M_.endo_names_long, 'prefd');
M_.endo_names = char(M_.endo_names, 'prefd_s');
M_.endo_names_tex = char(M_.endo_names_tex, 'prefd\_s');
M_.endo_names_long = char(M_.endo_names_long, 'prefd_s');
M_.endo_names = char(M_.endo_names, 'premium');
M_.endo_names_tex = char(M_.endo_names_tex, 'premium');
M_.endo_names_long = char(M_.endo_names_long, 'premium');
M_.endo_names = char(M_.endo_names, 'risk');
M_.endo_names_tex = char(M_.endo_names_tex, 'risk');
M_.endo_names_long = char(M_.endo_names_long, 'risk');
M_.endo_names = char(M_.endo_names, 'risk_s');
M_.endo_names_tex = char(M_.endo_names_tex, 'risk\_s');
M_.endo_names_long = char(M_.endo_names_long, 'risk_s');
M_.endo_names = char(M_.endo_names, 'prefc');
M_.endo_names_tex = char(M_.endo_names_tex, 'prefc');
M_.endo_names_long = char(M_.endo_names_long, 'prefc');
M_.endo_names = char(M_.endo_names, 'prefc_s');
M_.endo_names_tex = char(M_.endo_names_tex, 'prefc\_s');
M_.endo_names_long = char(M_.endo_names_long, 'prefc_s');
M_.endo_names = char(M_.endo_names, 'techc');
M_.endo_names_tex = char(M_.endo_names_tex, 'techc');
M_.endo_names_long = char(M_.endo_names_long, 'techc');
M_.endo_names = char(M_.endo_names, 'techd');
M_.endo_names_tex = char(M_.endo_names_tex, 'techd');
M_.endo_names_long = char(M_.endo_names_long, 'techd');
M_.endo_names = char(M_.endo_names, 'techc_s');
M_.endo_names_tex = char(M_.endo_names_tex, 'techc\_s');
M_.endo_names_long = char(M_.endo_names_long, 'techc_s');
M_.endo_names = char(M_.endo_names, 'techd_s');
M_.endo_names_tex = char(M_.endo_names_tex, 'techd\_s');
M_.endo_names_long = char(M_.endo_names_long, 'techd_s');
M_.endo_names = char(M_.endo_names, 'cff');
M_.endo_names_tex = char(M_.endo_names_tex, 'cff');
M_.endo_names_long = char(M_.endo_names_long, 'cff');
M_.endo_names = char(M_.endo_names, 'qf');
M_.endo_names_tex = char(M_.endo_names_tex, 'qf');
M_.endo_names_long = char(M_.endo_names_long, 'qf');
M_.endo_names = char(M_.endo_names, 'varrhof');
M_.endo_names_tex = char(M_.endo_names_tex, 'varrhof');
M_.endo_names_long = char(M_.endo_names_long, 'varrhof');
M_.endo_names = char(M_.endo_names, 'invf');
M_.endo_names_tex = char(M_.endo_names_tex, 'invf');
M_.endo_names_long = char(M_.endo_names_long, 'invf');
M_.endo_names = char(M_.endo_names, 'df');
M_.endo_names_tex = char(M_.endo_names_tex, 'df');
M_.endo_names_long = char(M_.endo_names_long, 'df');
M_.endo_names = char(M_.endo_names, 'rf');
M_.endo_names_tex = char(M_.endo_names_tex, 'rf');
M_.endo_names_long = char(M_.endo_names_long, 'rf');
M_.endo_names = char(M_.endo_names, 'lf');
M_.endo_names_tex = char(M_.endo_names_tex, 'lf');
M_.endo_names_long = char(M_.endo_names_long, 'lf');
M_.endo_names = char(M_.endo_names, 'lcf');
M_.endo_names_tex = char(M_.endo_names_tex, 'lcf');
M_.endo_names_long = char(M_.endo_names_long, 'lcf');
M_.endo_names = char(M_.endo_names, 'wcf');
M_.endo_names_tex = char(M_.endo_names_tex, 'wcf');
M_.endo_names_long = char(M_.endo_names_long, 'wcf');
M_.endo_names = char(M_.endo_names, 'ldf');
M_.endo_names_tex = char(M_.endo_names_tex, 'ldf');
M_.endo_names_long = char(M_.endo_names_long, 'ldf');
M_.endo_names = char(M_.endo_names, 'wdf');
M_.endo_names_tex = char(M_.endo_names_tex, 'wdf');
M_.endo_names_long = char(M_.endo_names_long, 'wdf');
M_.endo_names = char(M_.endo_names, 'cff_s');
M_.endo_names_tex = char(M_.endo_names_tex, 'cff\_s');
M_.endo_names_long = char(M_.endo_names_long, 'cff_s');
M_.endo_names = char(M_.endo_names, 'qf_s');
M_.endo_names_tex = char(M_.endo_names_tex, 'qf\_s');
M_.endo_names_long = char(M_.endo_names_long, 'qf_s');
M_.endo_names = char(M_.endo_names, 'varrhof_s');
M_.endo_names_tex = char(M_.endo_names_tex, 'varrhof\_s');
M_.endo_names_long = char(M_.endo_names_long, 'varrhof_s');
M_.endo_names = char(M_.endo_names, 'invf_s');
M_.endo_names_tex = char(M_.endo_names_tex, 'invf\_s');
M_.endo_names_long = char(M_.endo_names_long, 'invf_s');
M_.endo_names = char(M_.endo_names, 'df_s');
M_.endo_names_tex = char(M_.endo_names_tex, 'df\_s');
M_.endo_names_long = char(M_.endo_names_long, 'df_s');
M_.endo_names = char(M_.endo_names, 'rf_s');
M_.endo_names_tex = char(M_.endo_names_tex, 'rf\_s');
M_.endo_names_long = char(M_.endo_names_long, 'rf_s');
M_.endo_names = char(M_.endo_names, 'lf_s');
M_.endo_names_tex = char(M_.endo_names_tex, 'lf\_s');
M_.endo_names_long = char(M_.endo_names_long, 'lf_s');
M_.endo_names = char(M_.endo_names, 'lcf_s');
M_.endo_names_tex = char(M_.endo_names_tex, 'lcf\_s');
M_.endo_names_long = char(M_.endo_names_long, 'lcf_s');
M_.endo_names = char(M_.endo_names, 'wcf_s');
M_.endo_names_tex = char(M_.endo_names_tex, 'wcf\_s');
M_.endo_names_long = char(M_.endo_names_long, 'wcf_s');
M_.endo_names = char(M_.endo_names, 'ldf_s');
M_.endo_names_tex = char(M_.endo_names_tex, 'ldf\_s');
M_.endo_names_long = char(M_.endo_names_long, 'ldf_s');
M_.endo_names = char(M_.endo_names, 'wdf_s');
M_.endo_names_tex = char(M_.endo_names_tex, 'wdf\_s');
M_.endo_names_long = char(M_.endo_names_long, 'wdf_s');
M_.endo_names = char(M_.endo_names, 'ycf');
M_.endo_names_tex = char(M_.endo_names_tex, 'ycf');
M_.endo_names_long = char(M_.endo_names_long, 'ycf');
M_.endo_names = char(M_.endo_names, 'ydf');
M_.endo_names_tex = char(M_.endo_names_tex, 'ydf');
M_.endo_names_long = char(M_.endo_names_long, 'ydf');
M_.endo_names = char(M_.endo_names, 'yf');
M_.endo_names_tex = char(M_.endo_names_tex, 'yf');
M_.endo_names_long = char(M_.endo_names_long, 'yf');
M_.endo_names = char(M_.endo_names, 'y_emuf');
M_.endo_names_tex = char(M_.endo_names_tex, 'y\_emuf');
M_.endo_names_long = char(M_.endo_names_long, 'y_emuf');
M_.endo_names = char(M_.endo_names, 'ycf_s');
M_.endo_names_tex = char(M_.endo_names_tex, 'ycf\_s');
M_.endo_names_long = char(M_.endo_names_long, 'ycf_s');
M_.endo_names = char(M_.endo_names, 'ydf_s');
M_.endo_names_tex = char(M_.endo_names_tex, 'ydf\_s');
M_.endo_names_long = char(M_.endo_names_long, 'ydf_s');
M_.endo_names = char(M_.endo_names, 'yf_s');
M_.endo_names_tex = char(M_.endo_names_tex, 'yf\_s');
M_.endo_names_long = char(M_.endo_names_long, 'yf_s');
M_.endo_names = char(M_.endo_names, 'cff_borr');
M_.endo_names_tex = char(M_.endo_names_tex, 'cff\_borr');
M_.endo_names_long = char(M_.endo_names_long, 'cff_borr');
M_.endo_names = char(M_.endo_names, 'cff_s_borr');
M_.endo_names_tex = char(M_.endo_names_tex, 'cff\_s\_borr');
M_.endo_names_long = char(M_.endo_names_long, 'cff_s_borr');
M_.endo_names = char(M_.endo_names, 'varrhof_borr');
M_.endo_names_tex = char(M_.endo_names_tex, 'varrhof\_borr');
M_.endo_names_long = char(M_.endo_names_long, 'varrhof_borr');
M_.endo_names = char(M_.endo_names, 'varrhof_s_borr');
M_.endo_names_tex = char(M_.endo_names_tex, 'varrhof\_s\_borr');
M_.endo_names_long = char(M_.endo_names_long, 'varrhof_s_borr');
M_.endo_names = char(M_.endo_names, 'invf_borr');
M_.endo_names_tex = char(M_.endo_names_tex, 'invf\_borr');
M_.endo_names_long = char(M_.endo_names_long, 'invf_borr');
M_.endo_names = char(M_.endo_names, 'invf_s_borr');
M_.endo_names_tex = char(M_.endo_names_tex, 'invf\_s\_borr');
M_.endo_names_long = char(M_.endo_names_long, 'invf_s_borr');
M_.endo_names = char(M_.endo_names, 'df_borr');
M_.endo_names_tex = char(M_.endo_names_tex, 'df\_borr');
M_.endo_names_long = char(M_.endo_names_long, 'df_borr');
M_.endo_names = char(M_.endo_names, 'df_s_borr');
M_.endo_names_tex = char(M_.endo_names_tex, 'df\_s\_borr');
M_.endo_names_long = char(M_.endo_names_long, 'df_s_borr');
M_.endo_names = char(M_.endo_names, 'lf_borr');
M_.endo_names_tex = char(M_.endo_names_tex, 'lf\_borr');
M_.endo_names_long = char(M_.endo_names_long, 'lf_borr');
M_.endo_names = char(M_.endo_names, 'lcf_borr');
M_.endo_names_tex = char(M_.endo_names_tex, 'lcf\_borr');
M_.endo_names_long = char(M_.endo_names_long, 'lcf_borr');
M_.endo_names = char(M_.endo_names, 'ldf_borr');
M_.endo_names_tex = char(M_.endo_names_tex, 'ldf\_borr');
M_.endo_names_long = char(M_.endo_names_long, 'ldf_borr');
M_.endo_names = char(M_.endo_names, 'lf_s_borr');
M_.endo_names_tex = char(M_.endo_names_tex, 'lf\_s\_borr');
M_.endo_names_long = char(M_.endo_names_long, 'lf_s_borr');
M_.endo_names = char(M_.endo_names, 'lcf_s_borr');
M_.endo_names_tex = char(M_.endo_names_tex, 'lcf\_s\_borr');
M_.endo_names_long = char(M_.endo_names_long, 'lcf_s_borr');
M_.endo_names = char(M_.endo_names, 'ldf_s_borr');
M_.endo_names_tex = char(M_.endo_names_tex, 'ldf\_s\_borr');
M_.endo_names_long = char(M_.endo_names_long, 'ldf_s_borr');
M_.endo_names = char(M_.endo_names, 'sf_borr');
M_.endo_names_tex = char(M_.endo_names_tex, 'sf\_borr');
M_.endo_names_long = char(M_.endo_names_long, 'sf_borr');
M_.endo_names = char(M_.endo_names, 'sf_s_borr');
M_.endo_names_tex = char(M_.endo_names_tex, 'sf\_s\_borr');
M_.endo_names_long = char(M_.endo_names_long, 'sf_s_borr');
M_.endo_names = char(M_.endo_names, 'lcf_tot');
M_.endo_names_tex = char(M_.endo_names_tex, 'lcf\_tot');
M_.endo_names_long = char(M_.endo_names_long, 'lcf_tot');
M_.endo_names = char(M_.endo_names, 'lcf_s_tot');
M_.endo_names_tex = char(M_.endo_names_tex, 'lcf\_s\_tot');
M_.endo_names_long = char(M_.endo_names_long, 'lcf_s_tot');
M_.endo_names = char(M_.endo_names, 'ldf_tot');
M_.endo_names_tex = char(M_.endo_names_tex, 'ldf\_tot');
M_.endo_names_long = char(M_.endo_names_long, 'ldf_tot');
M_.endo_names = char(M_.endo_names, 'ldf_s_tot');
M_.endo_names_tex = char(M_.endo_names_tex, 'ldf\_s\_tot');
M_.endo_names_long = char(M_.endo_names_long, 'ldf_s_tot');
M_.endo_names = char(M_.endo_names, 'cff_tot');
M_.endo_names_tex = char(M_.endo_names_tex, 'cff\_tot');
M_.endo_names_long = char(M_.endo_names_long, 'cff_tot');
M_.endo_names = char(M_.endo_names, 'cff_s_tot');
M_.endo_names_tex = char(M_.endo_names_tex, 'cff\_s\_tot');
M_.endo_names_long = char(M_.endo_names_long, 'cff_s_tot');
M_.endo_names = char(M_.endo_names, 'rdf');
M_.endo_names_tex = char(M_.endo_names_tex, 'rdf');
M_.endo_names_long = char(M_.endo_names_long, 'rdf');
M_.endo_names = char(M_.endo_names, 'rdf_s');
M_.endo_names_tex = char(M_.endo_names_tex, 'rdf\_s');
M_.endo_names_long = char(M_.endo_names_long, 'rdf_s');
M_.endo_names = char(M_.endo_names, 'rlf');
M_.endo_names_tex = char(M_.endo_names_tex, 'rlf');
M_.endo_names_long = char(M_.endo_names_long, 'rlf');
M_.endo_names = char(M_.endo_names, 'rlf_s');
M_.endo_names_tex = char(M_.endo_names_tex, 'rlf\_s');
M_.endo_names_long = char(M_.endo_names_long, 'rlf_s');
M_.endo_names = char(M_.endo_names, 'Faf');
M_.endo_names_tex = char(M_.endo_names_tex, 'Faf');
M_.endo_names_long = char(M_.endo_names_long, 'Faf');
M_.endo_names = char(M_.endo_names, 'Fpf');
M_.endo_names_tex = char(M_.endo_names_tex, 'Fpf');
M_.endo_names_long = char(M_.endo_names_long, 'Fpf');
M_.endo_names = char(M_.endo_names, 'return_defaultf');
M_.endo_names_tex = char(M_.endo_names_tex, 'return\_defaultf');
M_.endo_names_long = char(M_.endo_names_long, 'return_defaultf');
M_.endo_names = char(M_.endo_names, 'return_nondefaultf');
M_.endo_names_tex = char(M_.endo_names_tex, 'return\_nondefaultf');
M_.endo_names_long = char(M_.endo_names_long, 'return_nondefaultf');
M_.endo_names = char(M_.endo_names, 'Gpf');
M_.endo_names_tex = char(M_.endo_names_tex, 'Gpf');
M_.endo_names_long = char(M_.endo_names_long, 'Gpf');
M_.endo_names = char(M_.endo_names, 'Gaf');
M_.endo_names_tex = char(M_.endo_names_tex, 'Gaf');
M_.endo_names_long = char(M_.endo_names_long, 'Gaf');
M_.endo_names = char(M_.endo_names, 'omegaaf');
M_.endo_names_tex = char(M_.endo_names_tex, 'omegaaf');
M_.endo_names_long = char(M_.endo_names_long, 'omegaaf');
M_.endo_names = char(M_.endo_names, 'omegapf');
M_.endo_names_tex = char(M_.endo_names_tex, 'omegapf');
M_.endo_names_long = char(M_.endo_names_long, 'omegapf');
M_.endo_names = char(M_.endo_names, 'Faf_s');
M_.endo_names_tex = char(M_.endo_names_tex, 'Faf\_s');
M_.endo_names_long = char(M_.endo_names_long, 'Faf_s');
M_.endo_names = char(M_.endo_names, 'Fpf_s');
M_.endo_names_tex = char(M_.endo_names_tex, 'Fpf\_s');
M_.endo_names_long = char(M_.endo_names_long, 'Fpf_s');
M_.endo_names = char(M_.endo_names, 'return_defaultf_s');
M_.endo_names_tex = char(M_.endo_names_tex, 'return\_defaultf\_s');
M_.endo_names_long = char(M_.endo_names_long, 'return_defaultf_s');
M_.endo_names = char(M_.endo_names, 'return_nondefaultf_s');
M_.endo_names_tex = char(M_.endo_names_tex, 'return\_nondefaultf\_s');
M_.endo_names_long = char(M_.endo_names_long, 'return_nondefaultf_s');
M_.endo_names = char(M_.endo_names, 'Gpf_s');
M_.endo_names_tex = char(M_.endo_names_tex, 'Gpf\_s');
M_.endo_names_long = char(M_.endo_names_long, 'Gpf_s');
M_.endo_names = char(M_.endo_names, 'Gaf_s');
M_.endo_names_tex = char(M_.endo_names_tex, 'Gaf\_s');
M_.endo_names_long = char(M_.endo_names_long, 'Gaf_s');
M_.endo_names = char(M_.endo_names, 'omegaaf_s');
M_.endo_names_tex = char(M_.endo_names_tex, 'omegaaf\_s');
M_.endo_names_long = char(M_.endo_names_long, 'omegaaf_s');
M_.endo_names = char(M_.endo_names, 'omegapf_s');
M_.endo_names_tex = char(M_.endo_names_tex, 'omegapf\_s');
M_.endo_names_long = char(M_.endo_names_long, 'omegapf_s');
M_.endo_names = char(M_.endo_names, 'interest');
M_.endo_names_tex = char(M_.endo_names_tex, 'interest');
M_.endo_names_long = char(M_.endo_names_long, 'interest');
M_.endo_names = char(M_.endo_names, 'inflation');
M_.endo_names_tex = char(M_.endo_names_tex, 'inflation');
M_.endo_names_long = char(M_.endo_names_long, 'inflation');
M_.endo_names = char(M_.endo_names, 'inflationq');
M_.endo_names_tex = char(M_.endo_names_tex, 'inflationq');
M_.endo_names_long = char(M_.endo_names_long, 'inflationq');
M_.endo_names = char(M_.endo_names, 'output');
M_.endo_names_tex = char(M_.endo_names_tex, 'output');
M_.endo_names_long = char(M_.endo_names_long, 'output');
M_.endo_names = char(M_.endo_names, 'outputgap');
M_.endo_names_tex = char(M_.endo_names_tex, 'outputgap');
M_.endo_names_long = char(M_.endo_names_long, 'outputgap');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_86');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_86');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_86');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_90');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_90');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_90');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_94');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_94');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_94');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_121');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_121');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_121');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_125');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_125');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_125');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_129');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_129');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_129');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_156');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_156');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_156');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_160');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_160');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_160');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_164');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_164');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_164');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_213');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_213');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_213');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_260');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_260');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_260');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_625');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_625');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_625');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_666');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_666');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_666');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_990');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_990');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_990');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_1033');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_1033');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_1033');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_1375');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_1375');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_1375');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_1416');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_1416');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_1416');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_71_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_71\_1');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_71_1');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_71_2');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_71\_2');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_71_2');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_208_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_208\_1');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_208_1');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_208_2');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_208\_2');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_208_2');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_208_3');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_208\_3');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_208_3');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_209_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_209\_1');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_209_1');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_209_2');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_209\_2');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_209_2');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_209_3');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_209\_3');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_209_3');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_205_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_205\_1');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_205_1');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_205_2');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_205\_2');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_205_2');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_205_3');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_205\_3');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_205_3');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_207_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_207\_1');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_207_1');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_207_2');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_207\_2');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_207_2');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_207_3');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_207\_3');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_207_3');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_167_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_167\_1');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_167_1');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_168_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_168\_1');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_168_1');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_137_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_137\_1');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_137_1');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_148_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_148\_1');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_148_1');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_23_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_23\_1');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_23_1');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_47_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_47\_1');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_47_1');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_21_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_21\_1');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_21_1');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_45_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_45\_1');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_45_1');
M_.param_names = 'cofintintb1';
M_.param_names_tex = 'cofintintb1';
M_.param_names_long = 'cofintintb1';
M_.param_names = char(M_.param_names, 'cofintintb2');
M_.param_names_tex = char(M_.param_names_tex, 'cofintintb2');
M_.param_names_long = char(M_.param_names_long, 'cofintintb2');
M_.param_names = char(M_.param_names, 'cofintintb3');
M_.param_names_tex = char(M_.param_names_tex, 'cofintintb3');
M_.param_names_long = char(M_.param_names_long, 'cofintintb3');
M_.param_names = char(M_.param_names, 'cofintintb4');
M_.param_names_tex = char(M_.param_names_tex, 'cofintintb4');
M_.param_names_long = char(M_.param_names_long, 'cofintintb4');
M_.param_names = char(M_.param_names, 'cofintinf0');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinf0');
M_.param_names_long = char(M_.param_names_long, 'cofintinf0');
M_.param_names = char(M_.param_names, 'cofintinfb1');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinfb1');
M_.param_names_long = char(M_.param_names_long, 'cofintinfb1');
M_.param_names = char(M_.param_names, 'cofintinfb2');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinfb2');
M_.param_names_long = char(M_.param_names_long, 'cofintinfb2');
M_.param_names = char(M_.param_names, 'cofintinfb3');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinfb3');
M_.param_names_long = char(M_.param_names_long, 'cofintinfb3');
M_.param_names = char(M_.param_names, 'cofintinfb4');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinfb4');
M_.param_names_long = char(M_.param_names_long, 'cofintinfb4');
M_.param_names = char(M_.param_names, 'cofintinff1');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinff1');
M_.param_names_long = char(M_.param_names_long, 'cofintinff1');
M_.param_names = char(M_.param_names, 'cofintinff2');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinff2');
M_.param_names_long = char(M_.param_names_long, 'cofintinff2');
M_.param_names = char(M_.param_names, 'cofintinff3');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinff3');
M_.param_names_long = char(M_.param_names_long, 'cofintinff3');
M_.param_names = char(M_.param_names, 'cofintinff4');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinff4');
M_.param_names_long = char(M_.param_names_long, 'cofintinff4');
M_.param_names = char(M_.param_names, 'cofintout');
M_.param_names_tex = char(M_.param_names_tex, 'cofintout');
M_.param_names_long = char(M_.param_names_long, 'cofintout');
M_.param_names = char(M_.param_names, 'cofintoutb1');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutb1');
M_.param_names_long = char(M_.param_names_long, 'cofintoutb1');
M_.param_names = char(M_.param_names, 'cofintoutb2');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutb2');
M_.param_names_long = char(M_.param_names_long, 'cofintoutb2');
M_.param_names = char(M_.param_names, 'cofintoutb3');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutb3');
M_.param_names_long = char(M_.param_names_long, 'cofintoutb3');
M_.param_names = char(M_.param_names, 'cofintoutb4');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutb4');
M_.param_names_long = char(M_.param_names_long, 'cofintoutb4');
M_.param_names = char(M_.param_names, 'cofintoutf1');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutf1');
M_.param_names_long = char(M_.param_names_long, 'cofintoutf1');
M_.param_names = char(M_.param_names, 'cofintoutf2');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutf2');
M_.param_names_long = char(M_.param_names_long, 'cofintoutf2');
M_.param_names = char(M_.param_names, 'cofintoutf3');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutf3');
M_.param_names_long = char(M_.param_names_long, 'cofintoutf3');
M_.param_names = char(M_.param_names, 'cofintoutf4');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutf4');
M_.param_names_long = char(M_.param_names_long, 'cofintoutf4');
M_.param_names = char(M_.param_names, 'cofintoutp');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutp');
M_.param_names_long = char(M_.param_names_long, 'cofintoutp');
M_.param_names = char(M_.param_names, 'cofintoutpb1');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpb1');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpb1');
M_.param_names = char(M_.param_names, 'cofintoutpb2');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpb2');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpb2');
M_.param_names = char(M_.param_names, 'cofintoutpb3');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpb3');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpb3');
M_.param_names = char(M_.param_names, 'cofintoutpb4');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpb4');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpb4');
M_.param_names = char(M_.param_names, 'cofintoutpf1');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpf1');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpf1');
M_.param_names = char(M_.param_names, 'cofintoutpf2');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpf2');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpf2');
M_.param_names = char(M_.param_names, 'cofintoutpf3');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpf3');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpf3');
M_.param_names = char(M_.param_names, 'cofintoutpf4');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpf4');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpf4');
M_.param_names = char(M_.param_names, 'std_r_');
M_.param_names_tex = char(M_.param_names_tex, 'std\_r\_');
M_.param_names_long = char(M_.param_names_long, 'std_r_');
M_.param_names = char(M_.param_names, 'std_r_quart');
M_.param_names_tex = char(M_.param_names_tex, 'std\_r\_quart');
M_.param_names_long = char(M_.param_names_long, 'std_r_quart');
M_.param_names = char(M_.param_names, 'beta');
M_.param_names_tex = char(M_.param_names_tex, 'beta');
M_.param_names_long = char(M_.param_names_long, 'beta');
M_.param_names = char(M_.param_names, 'beta_borr');
M_.param_names_tex = char(M_.param_names_tex, 'beta\_borr');
M_.param_names_long = char(M_.param_names_long, 'beta_borr');
M_.param_names = char(M_.param_names, 'lambda');
M_.param_names_tex = char(M_.param_names_tex, 'lambda');
M_.param_names_long = char(M_.param_names_long, 'lambda');
M_.param_names = char(M_.param_names, 'delta');
M_.param_names_tex = char(M_.param_names_tex, 'delta');
M_.param_names_long = char(M_.param_names_long, 'delta');
M_.param_names = char(M_.param_names, 'chi');
M_.param_names_tex = char(M_.param_names_tex, 'chi');
M_.param_names_long = char(M_.param_names_long, 'chi');
M_.param_names = char(M_.param_names, 'sigma');
M_.param_names_tex = char(M_.param_names_tex, 'sigma');
M_.param_names_long = char(M_.param_names_long, 'sigma');
M_.param_names = char(M_.param_names, 'kappa_b');
M_.param_names_tex = char(M_.param_names_tex, 'kappa\_b');
M_.param_names_long = char(M_.param_names_long, 'kappa_b');
M_.param_names = char(M_.param_names, 'gamma');
M_.param_names_tex = char(M_.param_names_tex, 'gamma');
M_.param_names_long = char(M_.param_names_long, 'gamma');
M_.param_names = char(M_.param_names, 'alpha');
M_.param_names_tex = char(M_.param_names_tex, 'alpha');
M_.param_names_long = char(M_.param_names_long, 'alpha');
M_.param_names = char(M_.param_names, 'phi');
M_.param_names_tex = char(M_.param_names_tex, 'phi');
M_.param_names_long = char(M_.param_names_long, 'phi');
M_.param_names = char(M_.param_names, 'tau');
M_.param_names_tex = char(M_.param_names_tex, 'tau');
M_.param_names_long = char(M_.param_names_long, 'tau');
M_.param_names = char(M_.param_names, 'epsilon');
M_.param_names_tex = char(M_.param_names_tex, 'epsilon');
M_.param_names_long = char(M_.param_names_long, 'epsilon');
M_.param_names = char(M_.param_names, 'epsilon_borr');
M_.param_names_tex = char(M_.param_names_tex, 'epsilon\_borr');
M_.param_names_long = char(M_.param_names_long, 'epsilon_borr');
M_.param_names = char(M_.param_names, 'psi');
M_.param_names_tex = char(M_.param_names_tex, 'psi');
M_.param_names_long = char(M_.param_names_long, 'psi');
M_.param_names = char(M_.param_names, 'theta_c');
M_.param_names_tex = char(M_.param_names_tex, 'theta\_c');
M_.param_names_long = char(M_.param_names_long, 'theta_c');
M_.param_names = char(M_.param_names, 'phi_c');
M_.param_names_tex = char(M_.param_names_tex, 'phi\_c');
M_.param_names_long = char(M_.param_names_long, 'phi_c');
M_.param_names = char(M_.param_names, 'theta_d');
M_.param_names_tex = char(M_.param_names_tex, 'theta\_d');
M_.param_names_long = char(M_.param_names_long, 'theta_d');
M_.param_names = char(M_.param_names, 'phi_d');
M_.param_names_tex = char(M_.param_names_tex, 'phi\_d');
M_.param_names_long = char(M_.param_names_long, 'phi_d');
M_.param_names = char(M_.param_names, 'gamma_s');
M_.param_names_tex = char(M_.param_names_tex, 'gamma\_s');
M_.param_names_long = char(M_.param_names_long, 'gamma_s');
M_.param_names = char(M_.param_names, 'alpha_s');
M_.param_names_tex = char(M_.param_names_tex, 'alpha\_s');
M_.param_names_long = char(M_.param_names_long, 'alpha_s');
M_.param_names = char(M_.param_names, 'tau_s');
M_.param_names_tex = char(M_.param_names_tex, 'tau\_s');
M_.param_names_long = char(M_.param_names_long, 'tau_s');
M_.param_names = char(M_.param_names, 'theta_c_s');
M_.param_names_tex = char(M_.param_names_tex, 'theta\_c\_s');
M_.param_names_long = char(M_.param_names_long, 'theta_c_s');
M_.param_names = char(M_.param_names, 'phi_c_s');
M_.param_names_tex = char(M_.param_names_tex, 'phi\_c\_s');
M_.param_names_long = char(M_.param_names_long, 'phi_c_s');
M_.param_names = char(M_.param_names, 'theta_d_s');
M_.param_names_tex = char(M_.param_names_tex, 'theta\_d\_s');
M_.param_names_long = char(M_.param_names_long, 'theta_d_s');
M_.param_names = char(M_.param_names, 'phi_d_s');
M_.param_names_tex = char(M_.param_names_tex, 'phi\_d\_s');
M_.param_names_long = char(M_.param_names_long, 'phi_d_s');
M_.param_names = char(M_.param_names, 'gamma_r');
M_.param_names_tex = char(M_.param_names_tex, 'gamma\_r');
M_.param_names_long = char(M_.param_names_long, 'gamma_r');
M_.param_names = char(M_.param_names, 'gamma_pi');
M_.param_names_tex = char(M_.param_names_tex, 'gamma\_pi');
M_.param_names_long = char(M_.param_names_long, 'gamma_pi');
M_.param_names = char(M_.param_names, 'iota_C');
M_.param_names_tex = char(M_.param_names_tex, 'iota\_C');
M_.param_names_long = char(M_.param_names_long, 'iota_C');
M_.param_names = char(M_.param_names, 'iota_L');
M_.param_names_tex = char(M_.param_names_tex, 'iota\_L');
M_.param_names_long = char(M_.param_names_long, 'iota_L');
M_.param_names = char(M_.param_names, 'RR_bar');
M_.param_names_tex = char(M_.param_names_tex, 'RR\_bar');
M_.param_names_long = char(M_.param_names_long, 'RR_bar');
M_.param_names = char(M_.param_names, 'RL_bar');
M_.param_names_tex = char(M_.param_names_tex, 'RL\_bar');
M_.param_names_long = char(M_.param_names_long, 'RL_bar');
M_.param_names = char(M_.param_names, 'upsilon');
M_.param_names_tex = char(M_.param_names_tex, 'upsilon');
M_.param_names_long = char(M_.param_names_long, 'upsilon');
M_.param_names = char(M_.param_names, 'upsilon_borr');
M_.param_names_tex = char(M_.param_names_tex, 'upsilon\_borr');
M_.param_names_long = char(M_.param_names_long, 'upsilon_borr');
M_.param_names = char(M_.param_names, 'upsilon_s');
M_.param_names_tex = char(M_.param_names_tex, 'upsilon\_s');
M_.param_names_long = char(M_.param_names_long, 'upsilon_s');
M_.param_names = char(M_.param_names, 'upsilon_borr_s');
M_.param_names_tex = char(M_.param_names_tex, 'upsilon\_borr\_s');
M_.param_names_long = char(M_.param_names_long, 'upsilon_borr_s');
M_.param_names = char(M_.param_names, 'rho_premium');
M_.param_names_tex = char(M_.param_names_tex, 'rho\_premium');
M_.param_names_long = char(M_.param_names_long, 'rho_premium');
M_.param_names = char(M_.param_names, 'rho_risk');
M_.param_names_tex = char(M_.param_names_tex, 'rho\_risk');
M_.param_names_long = char(M_.param_names_long, 'rho_risk');
M_.param_names = char(M_.param_names, 'rho_risk_s');
M_.param_names_tex = char(M_.param_names_tex, 'rho\_risk\_s');
M_.param_names_long = char(M_.param_names_long, 'rho_risk_s');
M_.param_names = char(M_.param_names, 'rho_prefd');
M_.param_names_tex = char(M_.param_names_tex, 'rho\_prefd');
M_.param_names_long = char(M_.param_names_long, 'rho_prefd');
M_.param_names = char(M_.param_names, 'rho_prefd_s');
M_.param_names_tex = char(M_.param_names_tex, 'rho\_prefd\_s');
M_.param_names_long = char(M_.param_names_long, 'rho_prefd_s');
M_.param_names = char(M_.param_names, 'rho_prefc');
M_.param_names_tex = char(M_.param_names_tex, 'rho\_prefc');
M_.param_names_long = char(M_.param_names_long, 'rho_prefc');
M_.param_names = char(M_.param_names, 'rho_prefc_s');
M_.param_names_tex = char(M_.param_names_tex, 'rho\_prefc\_s');
M_.param_names_long = char(M_.param_names_long, 'rho_prefc_s');
M_.param_names = char(M_.param_names, 'rho_techc');
M_.param_names_tex = char(M_.param_names_tex, 'rho\_techc');
M_.param_names_long = char(M_.param_names_long, 'rho_techc');
M_.param_names = char(M_.param_names, 'rho_techc_s');
M_.param_names_tex = char(M_.param_names_tex, 'rho\_techc\_s');
M_.param_names_long = char(M_.param_names_long, 'rho_techc_s');
M_.param_names = char(M_.param_names, 'rho_techd');
M_.param_names_tex = char(M_.param_names_tex, 'rho\_techd');
M_.param_names_long = char(M_.param_names_long, 'rho_techd');
M_.param_names = char(M_.param_names, 'rho_techd_s');
M_.param_names_tex = char(M_.param_names_tex, 'rho\_techd\_s');
M_.param_names_long = char(M_.param_names_long, 'rho_techd_s');
M_.param_names = char(M_.param_names, 'W_bar');
M_.param_names_tex = char(M_.param_names_tex, 'W\_bar');
M_.param_names_long = char(M_.param_names_long, 'W_bar');
M_.param_names = char(M_.param_names, 'L_total_bar');
M_.param_names_tex = char(M_.param_names_tex, 'L\_total\_bar');
M_.param_names_long = char(M_.param_names_long, 'L_total_bar');
M_.param_names = char(M_.param_names, 'L_bar');
M_.param_names_tex = char(M_.param_names_tex, 'L\_bar');
M_.param_names_long = char(M_.param_names_long, 'L_bar');
M_.param_names = char(M_.param_names, 'L_borr_bar');
M_.param_names_tex = char(M_.param_names_tex, 'L\_borr\_bar');
M_.param_names_long = char(M_.param_names_long, 'L_borr_bar');
M_.param_names = char(M_.param_names, 'C_bar');
M_.param_names_tex = char(M_.param_names_tex, 'C\_bar');
M_.param_names_long = char(M_.param_names_long, 'C_bar');
M_.param_names = char(M_.param_names, 'D_bar');
M_.param_names_tex = char(M_.param_names_tex, 'D\_bar');
M_.param_names_long = char(M_.param_names_long, 'D_bar');
M_.param_names = char(M_.param_names, 'S_borr_bar');
M_.param_names_tex = char(M_.param_names_tex, 'S\_borr\_bar');
M_.param_names_long = char(M_.param_names_long, 'S_borr_bar');
M_.param_names = char(M_.param_names, 'Z_bar');
M_.param_names_tex = char(M_.param_names_tex, 'Z\_bar');
M_.param_names_long = char(M_.param_names_long, 'Z_bar');
M_.param_names = char(M_.param_names, 'D_borr_bar');
M_.param_names_tex = char(M_.param_names_tex, 'D\_borr\_bar');
M_.param_names_long = char(M_.param_names_long, 'D_borr_bar');
M_.param_names = char(M_.param_names, 'C_borr_bar');
M_.param_names_tex = char(M_.param_names_tex, 'C\_borr\_bar');
M_.param_names_long = char(M_.param_names_long, 'C_borr_bar');
M_.param_names = char(M_.param_names, 'L_s_total_bar');
M_.param_names_tex = char(M_.param_names_tex, 'L\_s\_total\_bar');
M_.param_names_long = char(M_.param_names_long, 'L_s_total_bar');
M_.param_names = char(M_.param_names, 'L_s_bar');
M_.param_names_tex = char(M_.param_names_tex, 'L\_s\_bar');
M_.param_names_long = char(M_.param_names_long, 'L_s_bar');
M_.param_names = char(M_.param_names, 'L_s_borr_bar');
M_.param_names_tex = char(M_.param_names_tex, 'L\_s\_borr\_bar');
M_.param_names_long = char(M_.param_names_long, 'L_s_borr_bar');
M_.param_names = char(M_.param_names, 'C_s_bar');
M_.param_names_tex = char(M_.param_names_tex, 'C\_s\_bar');
M_.param_names_long = char(M_.param_names_long, 'C_s_bar');
M_.param_names = char(M_.param_names, 'D_s_bar');
M_.param_names_tex = char(M_.param_names_tex, 'D\_s\_bar');
M_.param_names_long = char(M_.param_names_long, 'D_s_bar');
M_.param_names = char(M_.param_names, 'S_s_borr_bar');
M_.param_names_tex = char(M_.param_names_tex, 'S\_s\_borr\_bar');
M_.param_names_long = char(M_.param_names_long, 'S_s_borr_bar');
M_.param_names = char(M_.param_names, 'Z_s_bar');
M_.param_names_tex = char(M_.param_names_tex, 'Z\_s\_bar');
M_.param_names_long = char(M_.param_names_long, 'Z_s_bar');
M_.param_names = char(M_.param_names, 'D_s_borr_bar');
M_.param_names_tex = char(M_.param_names_tex, 'D\_s\_borr\_bar');
M_.param_names_long = char(M_.param_names_long, 'D_s_borr_bar');
M_.param_names = char(M_.param_names, 'C_s_borr_bar');
M_.param_names_tex = char(M_.param_names_tex, 'C\_s\_borr\_bar');
M_.param_names_long = char(M_.param_names_long, 'C_s_borr_bar');
M_.param_names = char(M_.param_names, 'n');
M_.param_names_tex = char(M_.param_names_tex, 'n');
M_.param_names_long = char(M_.param_names_long, 'n');
M_.param_names = char(M_.param_names, 'gamma_y');
M_.param_names_tex = char(M_.param_names_tex, 'gamma\_y');
M_.param_names_long = char(M_.param_names_long, 'gamma_y');
M_.param_names = char(M_.param_names, 'gamma_eta');
M_.param_names_tex = char(M_.param_names_tex, 'gamma\_eta');
M_.param_names_long = char(M_.param_names_long, 'gamma_eta');
M_.param_names = char(M_.param_names, 'gamma_eta_s');
M_.param_names_tex = char(M_.param_names_tex, 'gamma\_eta\_s');
M_.param_names_long = char(M_.param_names_long, 'gamma_eta_s');
M_.param_names = char(M_.param_names, 'RL_s_bar');
M_.param_names_tex = char(M_.param_names_tex, 'RL\_s\_bar');
M_.param_names_long = char(M_.param_names_long, 'RL_s_bar');
M_.param_names = char(M_.param_names, 'RD_bar');
M_.param_names_tex = char(M_.param_names_tex, 'RD\_bar');
M_.param_names_long = char(M_.param_names_long, 'RD_bar');
M_.param_names = char(M_.param_names, 'F_bar');
M_.param_names_tex = char(M_.param_names_tex, 'F\_bar');
M_.param_names_long = char(M_.param_names_long, 'F_bar');
M_.param_names = char(M_.param_names, 'G_bar');
M_.param_names_tex = char(M_.param_names_tex, 'G\_bar');
M_.param_names_long = char(M_.param_names_long, 'G_bar');
M_.param_names = char(M_.param_names, 'sigma_bar');
M_.param_names_tex = char(M_.param_names_tex, 'sigma\_bar');
M_.param_names_long = char(M_.param_names_long, 'sigma_bar');
M_.param_names = char(M_.param_names, 'mu');
M_.param_names_tex = char(M_.param_names_tex, 'mu');
M_.param_names_long = char(M_.param_names_long, 'mu');
M_.param_names = char(M_.param_names, 'omega_bar');
M_.param_names_tex = char(M_.param_names_tex, 'omega\_bar');
M_.param_names_long = char(M_.param_names_long, 'omega_bar');
M_.exo_det_nbr = 0;
M_.exo_nbr = 15;
M_.endo_nbr = 249;
M_.param_nbr = 109;
M_.orig_endo_nbr = 210;
M_.aux_vars(1).endo_index = 211;
M_.aux_vars(1).type = 0;
M_.aux_vars(2).endo_index = 212;
M_.aux_vars(2).type = 0;
M_.aux_vars(3).endo_index = 213;
M_.aux_vars(3).type = 0;
M_.aux_vars(4).endo_index = 214;
M_.aux_vars(4).type = 0;
M_.aux_vars(5).endo_index = 215;
M_.aux_vars(5).type = 0;
M_.aux_vars(6).endo_index = 216;
M_.aux_vars(6).type = 0;
M_.aux_vars(7).endo_index = 217;
M_.aux_vars(7).type = 0;
M_.aux_vars(8).endo_index = 218;
M_.aux_vars(8).type = 0;
M_.aux_vars(9).endo_index = 219;
M_.aux_vars(9).type = 0;
M_.aux_vars(10).endo_index = 220;
M_.aux_vars(10).type = 0;
M_.aux_vars(11).endo_index = 221;
M_.aux_vars(11).type = 0;
M_.aux_vars(12).endo_index = 222;
M_.aux_vars(12).type = 0;
M_.aux_vars(13).endo_index = 223;
M_.aux_vars(13).type = 0;
M_.aux_vars(14).endo_index = 224;
M_.aux_vars(14).type = 0;
M_.aux_vars(15).endo_index = 225;
M_.aux_vars(15).type = 0;
M_.aux_vars(16).endo_index = 226;
M_.aux_vars(16).type = 0;
M_.aux_vars(17).endo_index = 227;
M_.aux_vars(17).type = 0;
M_.aux_vars(18).endo_index = 228;
M_.aux_vars(18).type = 1;
M_.aux_vars(18).orig_index = 72;
M_.aux_vars(18).orig_lead_lag = -1;
M_.aux_vars(19).endo_index = 229;
M_.aux_vars(19).type = 1;
M_.aux_vars(19).orig_index = 72;
M_.aux_vars(19).orig_lead_lag = -2;
M_.aux_vars(20).endo_index = 230;
M_.aux_vars(20).type = 1;
M_.aux_vars(20).orig_index = 209;
M_.aux_vars(20).orig_lead_lag = -1;
M_.aux_vars(21).endo_index = 231;
M_.aux_vars(21).type = 1;
M_.aux_vars(21).orig_index = 209;
M_.aux_vars(21).orig_lead_lag = -2;
M_.aux_vars(22).endo_index = 232;
M_.aux_vars(22).type = 1;
M_.aux_vars(22).orig_index = 209;
M_.aux_vars(22).orig_lead_lag = -3;
M_.aux_vars(23).endo_index = 233;
M_.aux_vars(23).type = 1;
M_.aux_vars(23).orig_index = 210;
M_.aux_vars(23).orig_lead_lag = -1;
M_.aux_vars(24).endo_index = 234;
M_.aux_vars(24).type = 1;
M_.aux_vars(24).orig_index = 210;
M_.aux_vars(24).orig_lead_lag = -2;
M_.aux_vars(25).endo_index = 235;
M_.aux_vars(25).type = 1;
M_.aux_vars(25).orig_index = 210;
M_.aux_vars(25).orig_lead_lag = -3;
M_.aux_vars(26).endo_index = 236;
M_.aux_vars(26).type = 1;
M_.aux_vars(26).orig_index = 206;
M_.aux_vars(26).orig_lead_lag = -1;
M_.aux_vars(27).endo_index = 237;
M_.aux_vars(27).type = 1;
M_.aux_vars(27).orig_index = 206;
M_.aux_vars(27).orig_lead_lag = -2;
M_.aux_vars(28).endo_index = 238;
M_.aux_vars(28).type = 1;
M_.aux_vars(28).orig_index = 206;
M_.aux_vars(28).orig_lead_lag = -3;
M_.aux_vars(29).endo_index = 239;
M_.aux_vars(29).type = 1;
M_.aux_vars(29).orig_index = 208;
M_.aux_vars(29).orig_lead_lag = -1;
M_.aux_vars(30).endo_index = 240;
M_.aux_vars(30).type = 1;
M_.aux_vars(30).orig_index = 208;
M_.aux_vars(30).orig_lead_lag = -2;
M_.aux_vars(31).endo_index = 241;
M_.aux_vars(31).type = 1;
M_.aux_vars(31).orig_index = 208;
M_.aux_vars(31).orig_lead_lag = -3;
M_.aux_vars(32).endo_index = 242;
M_.aux_vars(32).type = 1;
M_.aux_vars(32).orig_index = 168;
M_.aux_vars(32).orig_lead_lag = -1;
M_.aux_vars(33).endo_index = 243;
M_.aux_vars(33).type = 1;
M_.aux_vars(33).orig_index = 169;
M_.aux_vars(33).orig_lead_lag = -1;
M_.aux_vars(34).endo_index = 244;
M_.aux_vars(34).type = 1;
M_.aux_vars(34).orig_index = 138;
M_.aux_vars(34).orig_lead_lag = -1;
M_.aux_vars(35).endo_index = 245;
M_.aux_vars(35).type = 1;
M_.aux_vars(35).orig_index = 149;
M_.aux_vars(35).orig_lead_lag = -1;
M_.aux_vars(36).endo_index = 246;
M_.aux_vars(36).type = 1;
M_.aux_vars(36).orig_index = 24;
M_.aux_vars(36).orig_lead_lag = -1;
M_.aux_vars(37).endo_index = 247;
M_.aux_vars(37).type = 1;
M_.aux_vars(37).orig_index = 48;
M_.aux_vars(37).orig_lead_lag = -1;
M_.aux_vars(38).endo_index = 248;
M_.aux_vars(38).type = 1;
M_.aux_vars(38).orig_index = 22;
M_.aux_vars(38).orig_lead_lag = -1;
M_.aux_vars(39).endo_index = 249;
M_.aux_vars(39).type = 1;
M_.aux_vars(39).orig_index = 46;
M_.aux_vars(39).orig_lead_lag = -1;
M_.Sigma_e = zeros(15, 15);
M_.Correlation_matrix = eye(15, 15);
M_.H = 0;
M_.Correlation_matrix_ME = 1;
M_.sigma_e_is_diagonal = 1;
options_.block=0;
options_.bytecode=0;
options_.use_dll=0;
erase_compiled_function('EA_QR14_static');
erase_compiled_function('EA_QR14_dynamic');
M_.lead_lag_incidence = [
 1 84 333;
 2 85 334;
 3 86 0;
 4 87 335;
 5 88 336;
 6 89 337;
 0 90 338;
 7 91 339;
 0 92 0;
 0 93 0;
 0 94 0;
 0 95 0;
 0 96 0;
 0 97 0;
 0 98 0;
 0 99 0;
 0 100 0;
 0 101 0;
 0 102 0;
 0 103 0;
 0 104 340;
 8 105 341;
 0 106 342;
 9 107 343;
 10 108 344;
 11 109 345;
 12 110 0;
 13 111 346;
 14 112 347;
 15 113 348;
 0 114 349;
 16 115 350;
 0 116 0;
 0 117 0;
 0 118 0;
 0 119 0;
 0 120 0;
 0 121 0;
 0 122 0;
 0 123 0;
 0 124 0;
 0 125 0;
 0 126 0;
 0 127 0;
 0 128 351;
 17 129 352;
 0 130 353;
 18 131 354;
 0 132 0;
 0 133 0;
 0 134 0;
 0 135 0;
 0 136 0;
 0 137 0;
 19 138 0;
 20 139 0;
 21 140 0;
 0 141 0;
 0 142 0;
 0 143 0;
 0 144 0;
 0 145 0;
 0 146 0;
 0 147 0;
 0 148 0;
 0 149 0;
 0 150 0;
 0 151 0;
 0 152 0;
 0 153 0;
 22 154 0;
 23 155 0;
 24 156 0;
 25 157 0;
 26 158 0;
 0 159 355;
 0 160 356;
 0 161 0;
 0 162 0;
 0 163 0;
 0 164 0;
 0 165 0;
 0 166 0;
 0 167 0;
 0 168 357;
 0 169 358;
 0 170 359;
 0 171 360;
 0 172 361;
 0 173 362;
 0 174 363;
 0 175 364;
 0 176 365;
 0 177 366;
 0 178 367;
 0 179 368;
 0 180 0;
 0 181 0;
 0 182 0;
 0 183 0;
 0 184 0;
 0 185 0;
 27 186 0;
 28 187 0;
 29 188 0;
 30 189 0;
 0 190 0;
 0 191 0;
 0 192 369;
 0 193 370;
 0 194 0;
 0 195 0;
 0 196 371;
 0 197 372;
 0 198 0;
 0 199 0;
 0 200 0;
 0 201 0;
 0 202 0;
 0 203 373;
 0 204 374;
 0 205 375;
 0 206 376;
 31 207 0;
 32 208 0;
 33 209 0;
 34 210 0;
 35 211 0;
 36 212 377;
 37 213 378;
 38 214 0;
 39 215 0;
 40 216 0;
 41 217 0;
 42 218 379;
 0 219 380;
 0 220 381;
 43 221 382;
 44 222 0;
 0 223 0;
 0 224 0;
 0 225 0;
 0 226 0;
 0 227 0;
 0 228 0;
 45 229 383;
 0 230 384;
 0 231 385;
 46 232 386;
 47 233 0;
 0 234 0;
 0 235 0;
 0 236 0;
 0 237 0;
 0 238 0;
 0 239 0;
 0 240 0;
 0 241 0;
 0 242 0;
 0 243 0;
 0 244 0;
 0 245 0;
 0 246 0;
 48 247 387;
 49 248 388;
 0 249 389;
 0 250 390;
 50 251 391;
 51 252 392;
 52 253 393;
 53 254 394;
 0 255 0;
 0 256 0;
 0 257 0;
 0 258 0;
 0 259 0;
 0 260 0;
 54 261 0;
 55 262 0;
 0 263 0;
 0 264 0;
 0 265 0;
 0 266 0;
 0 267 0;
 0 268 0;
 0 269 395;
 0 270 396;
 56 271 0;
 57 272 0;
 0 273 0;
 0 274 0;
 0 275 397;
 0 276 398;
 0 277 0;
 0 278 0;
 0 279 0;
 0 280 0;
 0 281 0;
 0 282 0;
 0 283 399;
 0 284 400;
 0 285 0;
 0 286 0;
 0 287 0;
 0 288 0;
 58 289 0;
 0 290 0;
 59 291 401;
 60 292 402;
 61 293 403;
 0 294 404;
 0 295 405;
 0 296 406;
 0 297 407;
 0 298 408;
 0 299 409;
 0 300 410;
 0 301 411;
 0 302 412;
 0 303 413;
 0 304 414;
 0 305 415;
 0 306 416;
 0 307 417;
 0 308 418;
 0 309 419;
 0 310 420;
 62 311 0;
 63 312 0;
 64 313 0;
 65 314 0;
 66 315 0;
 67 316 0;
 68 317 0;
 69 318 0;
 70 319 0;
 71 320 0;
 72 321 0;
 73 322 0;
 74 323 0;
 75 324 0;
 76 325 0;
 77 326 0;
 78 327 0;
 79 328 0;
 80 329 0;
 81 330 0;
 82 331 0;
 83 332 0;]';
M_.nstatic = 109;
M_.nfwrd   = 57;
M_.npred   = 52;
M_.nboth   = 31;
M_.nsfwrd   = 88;
M_.nspred   = 83;
M_.ndynamic   = 140;
M_.equations_tags = {
};
M_.static_and_dynamic_models_differ = 0;
M_.exo_names_orig_ord = [1:15];
M_.maximum_lag = 1;
M_.maximum_lead = 1;
M_.maximum_endo_lag = 1;
M_.maximum_endo_lead = 1;
oo_.steady_state = zeros(249, 1);
M_.maximum_exo_lag = 1;
M_.maximum_exo_lead = 0;
oo_.exo_steady_state = zeros(15, 1);
M_.params = NaN(109, 1);
M_.NNZDerivatives = zeros(3, 1);
M_.NNZDerivatives(1) = 1115;
M_.NNZDerivatives(2) = 3080;
M_.NNZDerivatives(3) = -1;
close all
thispath = cd;                                                           
cd('..');                                                                
load policy_param.mat;                                                   
for i=1:33                                                               
deep_parameter_name = M_.param_names(i,:);                           
eval(['M_.params(i)  = ' deep_parameter_name ' ;'])                  
end                                                                      
cd(thispath);
M_.params( 32 ) = 100;
std_r_ = M_.params( 32 );
M_.params( 34 ) = 0.99;
beta = M_.params( 34 );
M_.params( 37 ) = .015;
delta = M_.params( 37 );
M_.params( 36 ) = 0.6085;
lambda = M_.params( 36 );
M_.params( 38 ) = 0.3;
chi = M_.params( 38 );
M_.params( 39 ) = 10;
sigma = M_.params( 39 );
M_.params( 40 ) = 0.0043;
kappa_b = M_.params( 40 );
M_.params( 99 ) = .6;
n = M_.params( 99 );
M_.params( 62 ) = 0.7174;
iota_L = M_.params( 62 );
M_.params( 61 ) = 1.9003;
iota_C = M_.params( 61 );
M_.params( 45 ) = 0.7187;
epsilon = M_.params( 45 );
M_.params( 46 ) = 0.4550;
epsilon_borr = M_.params( 46 );
M_.params( 43 ) = 0.3702;
phi = M_.params( 43 );
M_.params( 47 ) = 1.7490;
psi = M_.params( 47 );
M_.params( 105 ) = 0.025;
F_bar = M_.params( 105 );
M_.params( 108 ) = 0.2;
mu = M_.params( 108 );
M_.params( 42 ) = 0.94;
alpha = M_.params( 42 );
M_.params( 44 ) = .94;
tau = M_.params( 44 );
M_.params( 53 ) = 0.94;
alpha_s = M_.params( 53 );
M_.params( 54 ) = 1-M_.params(99)*(1-M_.params(44))/(1-M_.params(99));
tau_s = M_.params( 54 );
M_.params( 48 ) = 0.6252;
theta_c = M_.params( 48 );
M_.params( 50 ) = 0.6449;
theta_d = M_.params( 50 );
M_.params( 49 ) = 0.1510;
phi_c = M_.params( 49 );
M_.params( 51 ) = 0.2515;
phi_d = M_.params( 51 );
M_.params( 55 ) = 0.7241;
theta_c_s = M_.params( 55 );
M_.params( 57 ) = 0.5935;
theta_d_s = M_.params( 57 );
M_.params( 56 ) = 0.1276;
phi_c_s = M_.params( 56 );
M_.params( 58 ) = 0.4335;
phi_d_s = M_.params( 58 );
M_.params( 60 ) = 1.5579;
gamma_pi = M_.params( 60 );
M_.params( 59 ) = 0.8016;
gamma_r = M_.params( 59 );
M_.params( 100 ) = 0.2023;
gamma_y = M_.params( 100 );
M_.params( 101 ) = 0;
gamma_eta = M_.params( 101 );
M_.params( 102 ) = 0;
gamma_eta_s = M_.params( 102 );
M_.params( 69 ) = 0.7846;
rho_premium = M_.params( 69 );
M_.params( 70 ) = 0.8431;
rho_risk = M_.params( 70 );
M_.params( 71 ) = M_.params(70);
rho_risk_s = M_.params( 71 );
M_.params( 72 ) = 0.9836;
rho_prefd = M_.params( 72 );
M_.params( 73 ) = M_.params(72);
rho_prefd_s = M_.params( 73 );
M_.params( 74 ) = 0.6649;
rho_prefc = M_.params( 74 );
M_.params( 75 ) = M_.params(74);
rho_prefc_s = M_.params( 75 );
M_.params( 76 ) = 0.7936;
rho_techc = M_.params( 76 );
M_.params( 77 ) = M_.params(76);
rho_techc_s = M_.params( 77 );
M_.params( 78 ) = 0.8624;
rho_techd = M_.params( 78 );
M_.params( 79 ) = M_.params(78);
rho_techd_s = M_.params( 79 );
M_.params( 41 ) = call_csolve1_timingI(M_.params(37),M_.params(36),M_.params(45),M_.params(46),M_.params(38),M_.params(34),M_.params(39),M_.params(43),M_.params(42),M_.params(108),M_.params(105));
gamma = M_.params( 41 );
M_.params( 52 ) = call_csolve1_timingI(M_.params(37),M_.params(36),M_.params(45),M_.params(46),M_.params(38),M_.params(34),M_.params(39),M_.params(43),M_.params(53),M_.params(108),M_.params(105));
gamma_s = M_.params( 52 );
M_.params( 63 ) = 1/M_.params(34);
RR_bar = M_.params( 63 );
M_.params( 109 ) = 1-M_.params(38);
omega_bar = M_.params( 109 );
M_.params( 107 ) = call_csolve2(M_.params(105),M_.params(109));
sigma_bar = M_.params( 107 );
M_.params( 106 ) = 1-normcdf((0.5*M_.params(107)^2-log(M_.params(109)))/M_.params(107),0,1);
G_bar = M_.params( 106 );
M_.params( 64 ) = M_.params(63)/(1+(1-M_.params(108))*M_.params(106)/M_.params(109)-M_.params(105));
RL_bar = M_.params( 64 );
M_.params( 103 ) = M_.params(64);
RL_s_bar = M_.params( 103 );
M_.params( 35 ) = (M_.params(64)*(1-M_.params(105)+M_.params(106)/M_.params(109)))^(-1);
beta_borr = M_.params( 35 );
M_.params( 104 ) = M_.params(106)*M_.params(103)/M_.params(109);
RD_bar = M_.params( 104 );
M_.params( 66 ) = M_.params(41)*(1-M_.params(35)*(1-M_.params(37)))/(M_.params(35)*(1-M_.params(41))*(1-M_.params(46)));
upsilon_borr = M_.params( 66 );
M_.params( 65 ) = M_.params(41)*(1-M_.params(34)*(1-M_.params(37)))/(M_.params(34)*(1-M_.params(41))*(1-M_.params(45)));
upsilon = M_.params( 65 );
M_.params( 68 ) = (1-M_.params(35)*(1-M_.params(37)))*M_.params(52)/((1-M_.params(46))*M_.params(35)*(1-M_.params(52)));
upsilon_borr_s = M_.params( 68 );
M_.params( 67 ) = (1-M_.params(34)*(1-M_.params(37)))*M_.params(52)/((1-M_.params(45))*M_.params(34)*(1-M_.params(52)));
upsilon_s = M_.params( 67 );
M_.params( 83 ) = (M_.params(41)/(1-M_.params(46))*(1+(M_.params(37)+M_.params(106)+M_.params(109)*(1-M_.params(105)-1/M_.params(64)))/M_.params(66)))^(1/(1+M_.params(43)));
L_borr_bar = M_.params( 83 );
M_.params( 89 ) = M_.params(41)/(1-M_.params(46))*(1-1/M_.params(39))*M_.params(83)^(-M_.params(43));
C_borr_bar = M_.params( 89 );
M_.params( 80 ) = 1-1/M_.params(39);
W_bar = M_.params( 80 );
M_.params( 88 ) = M_.params(89)/M_.params(66);
D_borr_bar = M_.params( 88 );
M_.params( 86 ) = M_.params(109)*M_.params(88)/M_.params(64);
S_borr_bar = M_.params( 86 );
M_.params( 92 ) = (M_.params(52)/(1-M_.params(46))*(1+(M_.params(37)+M_.params(106)+M_.params(109)*(1-M_.params(105)-1/M_.params(64)))/M_.params(68)))^(1/(1+M_.params(43)));
L_s_borr_bar = M_.params( 92 );
M_.params( 98 ) = (1-1/M_.params(39))*M_.params(52)/(1-M_.params(46))*M_.params(92)^(-M_.params(43));
C_s_borr_bar = M_.params( 98 );
M_.params( 97 ) = M_.params(98)/M_.params(68);
D_s_borr_bar = M_.params( 97 );
M_.params( 95 ) = M_.params(109)*M_.params(97)/M_.params(103);
S_s_borr_bar = M_.params( 95 );
M_.params( 87 ) = (1-M_.params(36))/M_.params(36)*(M_.params(83)*(1-(M_.params(39)-1)/M_.params(39))+(M_.params(63)-1)*M_.params(86)+M_.params(88)*M_.params(108)*M_.params(106));
Z_bar = M_.params( 87 );
M_.params( 82 ) = call_csolve3(M_.params(37),M_.params(65),M_.params(43),M_.params(80),M_.params(87),M_.params(41),M_.params(45),M_.params(42));
L_bar = M_.params( 82 );
M_.params( 84 ) = M_.params(41)*M_.params(80)/(1-M_.params(45))*M_.params(82)^(-M_.params(43));
C_bar = M_.params( 84 );
M_.params( 85 ) = M_.params(84)/M_.params(65);
D_bar = M_.params( 85 );
M_.params( 96 ) = (1-M_.params(36))/M_.params(36)*(M_.params(92)*(1-(M_.params(39)-1)/M_.params(39))+(M_.params(63)-1)*M_.params(95)+M_.params(97)*M_.params(108)*M_.params(106));
Z_s_bar = M_.params( 96 );
M_.params( 91 ) = call_csolve3(M_.params(37),M_.params(67),M_.params(43),M_.params(80),M_.params(96),M_.params(52),M_.params(45),M_.params(53));
L_s_bar = M_.params( 91 );
M_.params( 93 ) = M_.params(52)*M_.params(80)/(1-M_.params(45))*M_.params(91)^(-M_.params(43));
C_s_bar = M_.params( 93 );
M_.params( 94 ) = M_.params(93)/M_.params(67);
D_s_bar = M_.params( 94 );
M_.params( 81 ) = M_.params(36)*M_.params(82)+M_.params(83)*(1-M_.params(36));
L_total_bar = M_.params( 81 );
M_.params( 90 ) = M_.params(36)*M_.params(91)+M_.params(92)*(1-M_.params(36));
L_s_total_bar = M_.params( 90 );
%
% INITVAL instructions
%
options_.initval_file = 0;
oo_.steady_state( 1 ) = 0;
oo_.steady_state( 2 ) = log(M_.params(84));
oo_.steady_state( 3 ) = log(M_.params(85));
oo_.steady_state( 4 ) = log(M_.params(89));
oo_.steady_state( 5 ) = log(M_.params(88));
oo_.steady_state( 6 ) = 0;
oo_.steady_state( 7 ) = 0;
oo_.steady_state( 8 ) = 0;
oo_.steady_state( 9 ) = log(M_.params(42)*M_.params(81));
oo_.steady_state( 10 ) = log(M_.params(81)*(1-M_.params(42)));
oo_.steady_state( 11 ) = log(M_.params(82));
oo_.steady_state( 12 ) = log(M_.params(83));
oo_.steady_state( 13 ) = log(M_.params(42)*M_.params(82));
oo_.steady_state( 14 ) = log(M_.params(82)*(1-M_.params(42)));
oo_.steady_state( 15 ) = log(M_.params(42)*M_.params(83));
oo_.steady_state( 16 ) = log(M_.params(83)*(1-M_.params(42)));
oo_.steady_state( 17 ) = log(M_.params(80));
oo_.steady_state( 18 ) = log(M_.params(80));
oo_.steady_state( 19 ) = log(M_.params(42)*M_.params(81));
oo_.steady_state( 20 ) = log(M_.params(81)*(1-M_.params(42)));
oo_.steady_state( 21 ) = log(M_.params(41)/(M_.params(84)*M_.params(34)*(1-M_.params(45))));
oo_.steady_state( 22 ) = log(M_.params(37)*M_.params(85));
oo_.steady_state( 23 ) = log(M_.params(41)/(M_.params(89)*M_.params(35)*(1-M_.params(46))));
oo_.steady_state( 24 ) = log(M_.params(37)*M_.params(88));
oo_.steady_state( 49 ) = log(M_.params(44)*(M_.params(36)*M_.params(84)+M_.params(89)*(1-M_.params(36))));
oo_.steady_state( 50 ) = log((1-M_.params(44))*(M_.params(36)*M_.params(84)+M_.params(89)*(1-M_.params(36))));
oo_.steady_state( 51 ) = log(M_.params(36)*M_.params(84)+M_.params(89)*(1-M_.params(36)));
oo_.steady_state( 56 ) = log(M_.params(86));
oo_.steady_state( 78 ) = log(M_.params(81));
oo_.steady_state( 25 ) = 0;
oo_.steady_state( 26 ) = log(M_.params(93));
oo_.steady_state( 27 ) = log(M_.params(94));
oo_.steady_state( 28 ) = log(M_.params(98));
oo_.steady_state( 29 ) = log(M_.params(97));
oo_.steady_state( 30 ) = 0;
oo_.steady_state( 31 ) = 0;
oo_.steady_state( 32 ) = 0;
oo_.steady_state( 33 ) = log(M_.params(53)*M_.params(90));
oo_.steady_state( 34 ) = log(M_.params(90)*(1-M_.params(53)));
oo_.steady_state( 35 ) = log(M_.params(91));
oo_.steady_state( 36 ) = log(M_.params(92));
oo_.steady_state( 37 ) = log(M_.params(53)*M_.params(91));
oo_.steady_state( 38 ) = log(M_.params(91)*(1-M_.params(53)));
oo_.steady_state( 39 ) = log(M_.params(53)*M_.params(92));
oo_.steady_state( 40 ) = log(M_.params(92)*(1-M_.params(53)));
oo_.steady_state( 41 ) = log(M_.params(80));
oo_.steady_state( 42 ) = log(M_.params(80));
oo_.steady_state( 43 ) = log(M_.params(53)*M_.params(90));
oo_.steady_state( 44 ) = log(M_.params(90)*(1-M_.params(53)));
oo_.steady_state( 45 ) = log(M_.params(52)/(M_.params(93)*M_.params(34)*(1-M_.params(45))));
oo_.steady_state( 46 ) = log(M_.params(37)*M_.params(94));
oo_.steady_state( 47 ) = log(M_.params(52)/(M_.params(98)*M_.params(35)*(1-M_.params(46))));
oo_.steady_state( 48 ) = log(M_.params(37)*M_.params(97));
oo_.steady_state( 52 ) = log((1-M_.params(54))*(M_.params(36)*M_.params(93)+M_.params(98)*(1-M_.params(36))));
oo_.steady_state( 53 ) = log(M_.params(54)*(M_.params(36)*M_.params(93)+M_.params(98)*(1-M_.params(36))));
oo_.steady_state( 54 ) = log(M_.params(36)*M_.params(93)+M_.params(98)*(1-M_.params(36)));
oo_.steady_state( 55 ) = log(M_.params(95));
oo_.steady_state( 79 ) = log(M_.params(90));
oo_.steady_state( 57 ) = log(M_.params(63));
oo_.steady_state( 58 ) = log(M_.params(63));
oo_.steady_state( 59 ) = log(1-M_.params(38));
oo_.steady_state( 60 ) = log(1-M_.params(38));
oo_.steady_state( 61 ) = log(1-M_.params(38));
oo_.steady_state( 62 ) = log(1-M_.params(38));
oo_.steady_state( 63 ) = log(M_.params(105));
oo_.steady_state( 64 ) = log(M_.params(105));
oo_.steady_state( 65 ) = log(M_.params(105));
oo_.steady_state( 66 ) = log(M_.params(105));
oo_.steady_state( 67 ) = log(M_.params(106));
oo_.steady_state( 68 ) = log(M_.params(106));
oo_.steady_state( 69 ) = log(M_.params(106));
oo_.steady_state( 70 ) = log(M_.params(106));
oo_.steady_state( 71 ) = 0;
oo_.steady_state( 72 ) = 0;
oo_.steady_state( 80 ) = log(M_.params(81));
oo_.steady_state( 73 ) = 0;
oo_.steady_state( 74 ) = log(M_.params(64));
oo_.steady_state( 75 ) = log(M_.params(103));
oo_.steady_state( 76 ) = log(M_.params(104));
oo_.steady_state( 77 ) = log(M_.params(104));
oo_.steady_state( 127 ) = log(M_.params(107));
oo_.steady_state( 128 ) = log(M_.params(107));
oo_.steady_state( 89 ) = log(M_.params(81)*M_.params(42)*M_.params(80)/((1-M_.params(45))*M_.params(84)*(1-M_.params(34)*M_.params(48))));
oo_.steady_state( 90 ) = log(M_.params(42)*M_.params(81)/((1-M_.params(45))*M_.params(84)*(1-M_.params(34)*M_.params(48))));
oo_.steady_state( 91 ) = log(M_.params(90)*M_.params(53)*M_.params(80)/((1-M_.params(45))*M_.params(93)*(1-M_.params(34)*M_.params(55))));
oo_.steady_state( 92 ) = log(M_.params(53)*M_.params(90)/((1-M_.params(45))*M_.params(93)*(1-M_.params(34)*M_.params(55))));
oo_.steady_state( 93 ) = log(M_.params(81)*M_.params(80)*(1-M_.params(42))/((1-M_.params(45))*M_.params(84)*(1-M_.params(34)*M_.params(50))));
oo_.steady_state( 94 ) = log(M_.params(81)*(1-M_.params(42))/((1-M_.params(45))*M_.params(84)*(1-M_.params(34)*M_.params(50))));
oo_.steady_state( 95 ) = log(M_.params(90)*M_.params(80)*(1-M_.params(53))/((1-M_.params(45))*M_.params(93)*(1-M_.params(34)*M_.params(57))));
oo_.steady_state( 96 ) = log(M_.params(90)*(1-M_.params(53))/((1-M_.params(45))*M_.params(93)*(1-M_.params(34)*M_.params(57))));
oo_.steady_state( 81 ) = log(M_.params(42)*M_.params(81));
oo_.steady_state( 82 ) = log(M_.params(53)*M_.params(90));
oo_.steady_state( 83 ) = log(M_.params(81)*(1-M_.params(42)));
oo_.steady_state( 84 ) = log(M_.params(90)*(1-M_.params(53)));
oo_.steady_state( 97 ) = log(M_.params(80));
oo_.steady_state( 98 ) = log(M_.params(80));
oo_.steady_state( 99 ) = log(M_.params(80));
oo_.steady_state( 100 ) = log(M_.params(80));
oo_.steady_state( 101 ) = log(1/((1-M_.params(45))*M_.params(84)));
oo_.steady_state( 102 ) = log(1/((1-M_.params(45))*M_.params(93)));
oo_.steady_state( 85 ) = 0;
oo_.steady_state( 86 ) = 0;
oo_.steady_state( 87 ) = 0;
oo_.steady_state( 88 ) = 0;
oo_.steady_state( 103 ) = 0;
oo_.steady_state( 104 ) = 0;
oo_.steady_state( 105 ) = 0;
oo_.steady_state( 106 ) = 0;
oo_.steady_state( 120 ) = log((1-M_.params(108))*M_.params(106)*M_.params(88)/M_.params(86));
oo_.steady_state( 121 ) = log(M_.params(64)*(1-M_.params(105)));
oo_.steady_state( 122 ) = log((1-M_.params(108))*M_.params(106)*M_.params(97)/M_.params(95));
oo_.steady_state( 123 ) = log((1-M_.params(105))*M_.params(103));
oo_.steady_state( 107 ) = M_.params(41)*log((1-M_.params(45))*M_.params(84))+(1-M_.params(41))*log(M_.params(85))-M_.params(82)^(1+M_.params(43))/(1+M_.params(43));
oo_.steady_state( 108 ) = M_.params(41)*log((1-M_.params(46))*M_.params(89))+(1-M_.params(41))*log(M_.params(88))-M_.params(83)^(1+M_.params(43))/(1+M_.params(43));
oo_.steady_state( 109 ) = (M_.params(41)*log((1-M_.params(45))*M_.params(84))+(1-M_.params(41))*log(M_.params(85))-M_.params(82)^(1+M_.params(43))/(1+M_.params(43)))/(1-M_.params(34));
oo_.steady_state( 110 ) = (M_.params(41)*log((1-M_.params(46))*M_.params(89))+(1-M_.params(41))*log(M_.params(88))-M_.params(83)^(1+M_.params(43))/(1+M_.params(43)))/(1-M_.params(35));
oo_.steady_state( 111 ) = M_.params(52)*log((1-M_.params(45))*M_.params(93))+(1-M_.params(52))*log(M_.params(94))-M_.params(91)^(1+M_.params(43))/(1+M_.params(43));
oo_.steady_state( 112 ) = M_.params(52)*log((1-M_.params(46))*M_.params(98))+(1-M_.params(52))*log(M_.params(97))-M_.params(92)^(1+M_.params(43))/(1+M_.params(43));
oo_.steady_state( 113 ) = (M_.params(52)*log((1-M_.params(45))*M_.params(93))+(1-M_.params(52))*log(M_.params(94))-M_.params(91)^(1+M_.params(43))/(1+M_.params(43)))/(1-M_.params(34));
oo_.steady_state( 114 ) = (M_.params(52)*log((1-M_.params(46))*M_.params(98))+(1-M_.params(52))*log(M_.params(97))-M_.params(92)^(1+M_.params(43))/(1+M_.params(43)))/(1-M_.params(35));
oo_.steady_state( 115 ) = M_.params(36)*(M_.params(41)*log((1-M_.params(45))*M_.params(84))+(1-M_.params(41))*log(M_.params(85))-M_.params(82)^(1+M_.params(43))/(1+M_.params(43)))/(1-M_.params(34))+(1-M_.params(36))*(M_.params(41)*log((1-M_.params(46))*M_.params(89))+(1-M_.params(41))*log(M_.params(88))-M_.params(83)^(1+M_.params(43))/(1+M_.params(43)))/(1-M_.params(35));
oo_.steady_state( 116 ) = M_.params(36)*(M_.params(52)*log((1-M_.params(45))*M_.params(93))+(1-M_.params(52))*log(M_.params(94))-M_.params(91)^(1+M_.params(43))/(1+M_.params(43)))/(1-M_.params(34))+(1-M_.params(36))*(M_.params(52)*log((1-M_.params(46))*M_.params(98))+(1-M_.params(52))*log(M_.params(97))-M_.params(92)^(1+M_.params(43))/(1+M_.params(43)))/(1-M_.params(35));
oo_.steady_state( 117 ) = M_.params(99)*(M_.params(36)*(M_.params(41)*log((1-M_.params(45))*M_.params(84))+(1-M_.params(41))*log(M_.params(85))-M_.params(82)^(1+M_.params(43))/(1+M_.params(43)))/(1-M_.params(34))+(1-M_.params(36))*(M_.params(41)*log((1-M_.params(46))*M_.params(89))+(1-M_.params(41))*log(M_.params(88))-M_.params(83)^(1+M_.params(43))/(1+M_.params(43)))/(1-M_.params(35)))+(1-M_.params(99))*(M_.params(36)*(M_.params(52)*log((1-M_.params(45))*M_.params(93))+(1-M_.params(52))*log(M_.params(94))-M_.params(91)^(1+M_.params(43))/(1+M_.params(43)))/(1-M_.params(34))+(1-M_.params(36))*(M_.params(52)*log((1-M_.params(46))*M_.params(98))+(1-M_.params(52))*log(M_.params(97))-M_.params(92)^(1+M_.params(43))/(1+M_.params(43)))/(1-M_.params(35)));
oo_.steady_state( 118 ) = 0;
oo_.steady_state( 119 ) = 0;
oo_.steady_state( 135 ) = log(M_.params(84));
oo_.steady_state( 136 ) = 0;
oo_.steady_state( 137 ) = log(M_.params(41)/(M_.params(84)*M_.params(34)*(1-M_.params(45))));
oo_.steady_state( 138 ) = log(M_.params(37)*M_.params(85));
oo_.steady_state( 139 ) = log(M_.params(85));
oo_.steady_state( 140 ) = log(M_.params(63));
oo_.steady_state( 141 ) = log(M_.params(82));
oo_.steady_state( 142 ) = log(M_.params(42)*M_.params(82));
oo_.steady_state( 143 ) = log(M_.params(80));
oo_.steady_state( 144 ) = log(M_.params(82)*(1-M_.params(42)));
oo_.steady_state( 145 ) = log(M_.params(80));
oo_.steady_state( 146 ) = log(M_.params(93));
oo_.steady_state( 147 ) = 0;
oo_.steady_state( 148 ) = log(M_.params(52)/(M_.params(93)*M_.params(34)*(1-M_.params(45))));
oo_.steady_state( 149 ) = log(M_.params(37)*M_.params(94));
oo_.steady_state( 150 ) = log(M_.params(94));
oo_.steady_state( 151 ) = log(M_.params(63));
oo_.steady_state( 152 ) = log(M_.params(91));
oo_.steady_state( 153 ) = log(M_.params(53)*M_.params(91));
oo_.steady_state( 154 ) = log(M_.params(80));
oo_.steady_state( 155 ) = log(M_.params(91)*(1-M_.params(53)));
oo_.steady_state( 156 ) = log(M_.params(80));
oo_.steady_state( 157 ) = log(M_.params(42)*M_.params(81));
oo_.steady_state( 158 ) = log(M_.params(81)*(1-M_.params(42)));
oo_.steady_state( 159 ) = log(M_.params(81));
oo_.steady_state( 160 ) = log(M_.params(81));
oo_.steady_state( 161 ) = log(M_.params(53)*M_.params(90));
oo_.steady_state( 162 ) = log(M_.params(90)*(1-M_.params(53)));
oo_.steady_state( 163 ) = log(M_.params(90));
oo_.steady_state( 164 ) = log(M_.params(89));
oo_.steady_state( 166 ) = log(M_.params(41)/(M_.params(89)*M_.params(35)*(1-M_.params(46))));
oo_.steady_state( 168 ) = log(M_.params(37)*M_.params(88));
oo_.steady_state( 170 ) = log(M_.params(88));
oo_.steady_state( 172 ) = log(M_.params(83));
oo_.steady_state( 173 ) = log(M_.params(42)*M_.params(83));
oo_.steady_state( 174 ) = log(M_.params(83)*(1-M_.params(42)));
oo_.steady_state( 178 ) = log(M_.params(86));
oo_.steady_state( 180 ) = log(M_.params(42)*M_.params(81));
oo_.steady_state( 182 ) = log(M_.params(81)*(1-M_.params(42)));
oo_.steady_state( 184 ) = log(M_.params(36)*M_.params(84)+M_.params(89)*(1-M_.params(36)));
oo_.steady_state( 165 ) = log(M_.params(98));
oo_.steady_state( 167 ) = log(M_.params(52)/(M_.params(98)*M_.params(35)*(1-M_.params(46))));
oo_.steady_state( 169 ) = log(M_.params(37)*M_.params(97));
oo_.steady_state( 171 ) = log(M_.params(97));
oo_.steady_state( 175 ) = log(M_.params(92));
oo_.steady_state( 176 ) = log(M_.params(53)*M_.params(92));
oo_.steady_state( 177 ) = log(M_.params(92)*(1-M_.params(53)));
oo_.steady_state( 179 ) = log(M_.params(95));
oo_.steady_state( 181 ) = log(M_.params(53)*M_.params(90));
oo_.steady_state( 183 ) = log(M_.params(90)*(1-M_.params(53)));
oo_.steady_state( 185 ) = log(M_.params(36)*M_.params(93)+M_.params(98)*(1-M_.params(36)));
oo_.steady_state( 186 ) = log(M_.params(104));
oo_.steady_state( 187 ) = log(M_.params(104));
oo_.steady_state( 188 ) = log(M_.params(64));
oo_.steady_state( 189 ) = log(M_.params(103));
oo_.steady_state( 190 ) = log(M_.params(105));
oo_.steady_state( 191 ) = log(M_.params(105));
oo_.steady_state( 192 ) = log((1-M_.params(108))*M_.params(106)*M_.params(88)/M_.params(86));
oo_.steady_state( 193 ) = log(M_.params(64)*(1-M_.params(105)));
oo_.steady_state( 194 ) = log(M_.params(106));
oo_.steady_state( 195 ) = log(M_.params(106));
oo_.steady_state( 196 ) = log(1-M_.params(38));
oo_.steady_state( 197 ) = log(1-M_.params(38));
oo_.steady_state( 198 ) = log(M_.params(105));
oo_.steady_state( 199 ) = log(M_.params(105));
oo_.steady_state( 200 ) = log((1-M_.params(108))*M_.params(106)*M_.params(97)/M_.params(95));
oo_.steady_state( 201 ) = log((1-M_.params(105))*M_.params(103));
oo_.steady_state( 202 ) = log(M_.params(106));
oo_.steady_state( 203 ) = log(M_.params(106));
oo_.steady_state( 204 ) = log(1-M_.params(38));
oo_.steady_state( 205 ) = log(1-M_.params(38));
oo_.steady_state( 206 ) = 0;
oo_.steady_state( 207 ) = 0;
oo_.steady_state( 208 ) = 0;
oo_.steady_state( 210 ) = 0;
oo_.steady_state( 209 ) = 0;
oo_.steady_state(211)=oo_.steady_state(208);
oo_.steady_state(212)=oo_.steady_state(211);
oo_.steady_state(213)=oo_.steady_state(212);
oo_.steady_state(214)=oo_.steady_state(210);
oo_.steady_state(215)=oo_.steady_state(214);
oo_.steady_state(216)=oo_.steady_state(215);
oo_.steady_state(217)=oo_.steady_state(209);
oo_.steady_state(218)=oo_.steady_state(217);
oo_.steady_state(219)=oo_.steady_state(218);
oo_.steady_state(220)=oo_.steady_state(166);
oo_.steady_state(221)=oo_.steady_state(167);
oo_.steady_state(222)=oo_.steady_state(137);
oo_.steady_state(223)=oo_.steady_state(148);
oo_.steady_state(224)=oo_.steady_state(23);
oo_.steady_state(225)=oo_.steady_state(47);
oo_.steady_state(226)=oo_.steady_state(21);
oo_.steady_state(227)=oo_.steady_state(45);
oo_.steady_state(228)=oo_.steady_state(72);
oo_.steady_state(229)=oo_.steady_state(228);
oo_.steady_state(230)=oo_.steady_state(209);
oo_.steady_state(231)=oo_.steady_state(230);
oo_.steady_state(232)=oo_.steady_state(231);
oo_.steady_state(233)=oo_.steady_state(210);
oo_.steady_state(234)=oo_.steady_state(233);
oo_.steady_state(235)=oo_.steady_state(234);
oo_.steady_state(236)=oo_.steady_state(206);
oo_.steady_state(237)=oo_.steady_state(236);
oo_.steady_state(238)=oo_.steady_state(237);
oo_.steady_state(239)=oo_.steady_state(208);
oo_.steady_state(240)=oo_.steady_state(239);
oo_.steady_state(241)=oo_.steady_state(240);
oo_.steady_state(242)=oo_.steady_state(168);
oo_.steady_state(243)=oo_.steady_state(169);
oo_.steady_state(244)=oo_.steady_state(138);
oo_.steady_state(245)=oo_.steady_state(149);
oo_.steady_state(246)=oo_.steady_state(24);
oo_.steady_state(247)=oo_.steady_state(48);
oo_.steady_state(248)=oo_.steady_state(22);
oo_.steady_state(249)=oo_.steady_state(46);
if M_.exo_nbr > 0;
	oo_.exo_simul = [ones(M_.maximum_lag,1)*oo_.exo_steady_state'];
end;
if M_.exo_det_nbr > 0;
	oo_.exo_det_simul = [ones(M_.maximum_lag,1)*oo_.exo_det_steady_state'];
end;
%
% SHOCKS instructions
%
make_ex_;
M_.exo_det_length = 0;
M_.Sigma_e(1, 1) = (0.0020)^2;
M_.Sigma_e(2, 2) = (0.1179)^2;
M_.Sigma_e(3, 3) = (0.2306)^2;
M_.Sigma_e(4, 4) = (0.0309)^2;
M_.Sigma_e(5, 5) = (0.0325)^2;
M_.Sigma_e(6, 6) = (0.0187)^2;
M_.Sigma_e(7, 7) = (0.0141)^2;
M_.Sigma_e(8, 8) = (0.0062)^2;
M_.Sigma_e(9, 9) = (0.0162)^2;
M_.Sigma_e(10, 10) = (0.0066)^2;
M_.Sigma_e(11, 11) = (0.0143)^2;
M_.Sigma_e(12, 12) = (0.0083)^2;
M_.Sigma_e(13, 13) = (0.0146)^2;
M_.Sigma_e(14, 14) = (0.0074)^2;
save('EA_QR14_results.mat', 'oo_', 'M_', 'options_');
if exist('estim_params_', 'var') == 1
  save('EA_QR14_results.mat', 'estim_params_', '-append');
end
if exist('bayestopt_', 'var') == 1
  save('EA_QR14_results.mat', 'bayestopt_', '-append');
end
if exist('dataset_', 'var') == 1
  save('EA_QR14_results.mat', 'dataset_', '-append');
end
if exist('estimation_info', 'var') == 1
  save('EA_QR14_results.mat', 'estimation_info', '-append');
end


disp(['Total computing time : ' dynsec2hms(toc) ]);
if ~isempty(lastwarn)
  disp('Note: warning(s) encountered in MATLAB/Octave code')
end
diary off
