%
% Status : main Dynare file 
%
% Warning : this file is generated automatically by Dynare
%           from model file (.mod)

tic;
global M_ oo_ options_ ys0_ ex0_ estimation_info
options_ = [];
M_.fname = 'US_IN10';
%
% Some global variables initialization
%
global_initialization;
diary off;
diary('US_IN10.log');
M_.exo_names = 'eps_c';
M_.exo_names_tex = 'eps\_c';
M_.exo_names_long = 'eps_c';
M_.exo_names = char(M_.exo_names, 'eps_h');
M_.exo_names_tex = char(M_.exo_names_tex, 'eps\_h');
M_.exo_names_long = char(M_.exo_names_long, 'eps_h');
M_.exo_names = char(M_.exo_names, 'eps_j');
M_.exo_names_tex = char(M_.exo_names_tex, 'eps\_j');
M_.exo_names_long = char(M_.exo_names_long, 'eps_j');
M_.exo_names = char(M_.exo_names, 'eps_k');
M_.exo_names_tex = char(M_.exo_names_tex, 'eps\_k');
M_.exo_names_long = char(M_.exo_names_long, 'eps_k');
M_.exo_names = char(M_.exo_names, 'eps_p');
M_.exo_names_tex = char(M_.exo_names_tex, 'eps\_p');
M_.exo_names_long = char(M_.exo_names_long, 'eps_p');
M_.exo_names = char(M_.exo_names, 'eps_s');
M_.exo_names_tex = char(M_.exo_names_tex, 'eps\_s');
M_.exo_names_long = char(M_.exo_names_long, 'eps_s');
M_.exo_names = char(M_.exo_names, 'eps_t');
M_.exo_names_tex = char(M_.exo_names_tex, 'eps\_t');
M_.exo_names_long = char(M_.exo_names_long, 'eps_t');
M_.exo_names = char(M_.exo_names, 'eps_z');
M_.exo_names_tex = char(M_.exo_names_tex, 'eps\_z');
M_.exo_names_long = char(M_.exo_names_long, 'eps_z');
M_.exo_names = char(M_.exo_names, 'interest_');
M_.exo_names_tex = char(M_.exo_names_tex, 'interest\_');
M_.exo_names_long = char(M_.exo_names_long, 'interest_');
M_.endo_names = 'a_c';
M_.endo_names_tex = 'a\_c';
M_.endo_names_long = 'a_c';
M_.endo_names = char(M_.endo_names, 'a_h');
M_.endo_names_tex = char(M_.endo_names_tex, 'a\_h');
M_.endo_names_long = char(M_.endo_names_long, 'a_h');
M_.endo_names = char(M_.endo_names, 'a_j');
M_.endo_names_tex = char(M_.endo_names_tex, 'a\_j');
M_.endo_names_long = char(M_.endo_names_long, 'a_j');
M_.endo_names = char(M_.endo_names, 'a_k');
M_.endo_names_tex = char(M_.endo_names_tex, 'a\_k');
M_.endo_names_long = char(M_.endo_names_long, 'a_k');
M_.endo_names = char(M_.endo_names, 'a_s');
M_.endo_names_tex = char(M_.endo_names_tex, 'a\_s');
M_.endo_names_long = char(M_.endo_names_long, 'a_s');
M_.endo_names = char(M_.endo_names, 'a_t');
M_.endo_names_tex = char(M_.endo_names_tex, 'a\_t');
M_.endo_names_long = char(M_.endo_names_long, 'a_t');
M_.endo_names = char(M_.endo_names, 'a_z');
M_.endo_names_tex = char(M_.endo_names_tex, 'a\_z');
M_.endo_names_long = char(M_.endo_names_long, 'a_z');
M_.endo_names = char(M_.endo_names, 'b');
M_.endo_names_tex = char(M_.endo_names_tex, 'b');
M_.endo_names_long = char(M_.endo_names_long, 'b');
M_.endo_names = char(M_.endo_names, 'c');
M_.endo_names_tex = char(M_.endo_names_tex, 'c');
M_.endo_names_long = char(M_.endo_names_long, 'c');
M_.endo_names = char(M_.endo_names, 'c1');
M_.endo_names_tex = char(M_.endo_names_tex, 'c1');
M_.endo_names_long = char(M_.endo_names_long, 'c1');
M_.endo_names = char(M_.endo_names, 'data_CC');
M_.endo_names_tex = char(M_.endo_names_tex, 'data\_CC');
M_.endo_names_long = char(M_.endo_names_long, 'data_CC');
M_.endo_names = char(M_.endo_names, 'data_DP');
M_.endo_names_tex = char(M_.endo_names_tex, 'data\_DP');
M_.endo_names_long = char(M_.endo_names_long, 'data_DP');
M_.endo_names = char(M_.endo_names, 'data_IH');
M_.endo_names_tex = char(M_.endo_names_tex, 'data\_IH');
M_.endo_names_long = char(M_.endo_names_long, 'data_IH');
M_.endo_names = char(M_.endo_names, 'data_IK');
M_.endo_names_tex = char(M_.endo_names_tex, 'data\_IK');
M_.endo_names_long = char(M_.endo_names_long, 'data_IK');
M_.endo_names = char(M_.endo_names, 'data_NC');
M_.endo_names_tex = char(M_.endo_names_tex, 'data\_NC');
M_.endo_names_long = char(M_.endo_names_long, 'data_NC');
M_.endo_names = char(M_.endo_names, 'data_NH');
M_.endo_names_tex = char(M_.endo_names_tex, 'data\_NH');
M_.endo_names_long = char(M_.endo_names_long, 'data_NH');
M_.endo_names = char(M_.endo_names, 'data_QQ');
M_.endo_names_tex = char(M_.endo_names_tex, 'data\_QQ');
M_.endo_names_long = char(M_.endo_names_long, 'data_QQ');
M_.endo_names = char(M_.endo_names, 'data_RR');
M_.endo_names_tex = char(M_.endo_names_tex, 'data\_RR');
M_.endo_names_long = char(M_.endo_names_long, 'data_RR');
M_.endo_names = char(M_.endo_names, 'data_WC');
M_.endo_names_tex = char(M_.endo_names_tex, 'data\_WC');
M_.endo_names_long = char(M_.endo_names_long, 'data_WC');
M_.endo_names = char(M_.endo_names, 'data_WH');
M_.endo_names_tex = char(M_.endo_names_tex, 'data\_WH');
M_.endo_names_long = char(M_.endo_names_long, 'data_WH');
M_.endo_names = char(M_.endo_names, 'dp');
M_.endo_names_tex = char(M_.endo_names_tex, 'dp');
M_.endo_names_long = char(M_.endo_names_long, 'dp');
M_.endo_names = char(M_.endo_names, 'h');
M_.endo_names_tex = char(M_.endo_names_tex, 'h');
M_.endo_names_long = char(M_.endo_names_long, 'h');
M_.endo_names = char(M_.endo_names, 'h1');
M_.endo_names_tex = char(M_.endo_names_tex, 'h1');
M_.endo_names_long = char(M_.endo_names_long, 'h1');
M_.endo_names = char(M_.endo_names, 'I');
M_.endo_names_tex = char(M_.endo_names_tex, 'I');
M_.endo_names_long = char(M_.endo_names_long, 'I');
M_.endo_names = char(M_.endo_names, 'kc');
M_.endo_names_tex = char(M_.endo_names_tex, 'kc');
M_.endo_names_long = char(M_.endo_names_long, 'kc');
M_.endo_names = char(M_.endo_names, 'kh');
M_.endo_names_tex = char(M_.endo_names_tex, 'kh');
M_.endo_names_long = char(M_.endo_names_long, 'kh');
M_.endo_names = char(M_.endo_names, 'lm');
M_.endo_names_tex = char(M_.endo_names_tex, 'lm');
M_.endo_names_long = char(M_.endo_names_long, 'lm');
M_.endo_names = char(M_.endo_names, 'nc');
M_.endo_names_tex = char(M_.endo_names_tex, 'nc');
M_.endo_names_long = char(M_.endo_names_long, 'nc');
M_.endo_names = char(M_.endo_names, 'nc1');
M_.endo_names_tex = char(M_.endo_names_tex, 'nc1');
M_.endo_names_long = char(M_.endo_names_long, 'nc1');
M_.endo_names = char(M_.endo_names, 'nh');
M_.endo_names_tex = char(M_.endo_names_tex, 'nh');
M_.endo_names_long = char(M_.endo_names_long, 'nh');
M_.endo_names = char(M_.endo_names, 'nh1');
M_.endo_names_tex = char(M_.endo_names_tex, 'nh1');
M_.endo_names_long = char(M_.endo_names_long, 'nh1');
M_.endo_names = char(M_.endo_names, 'q');
M_.endo_names_tex = char(M_.endo_names_tex, 'q');
M_.endo_names_long = char(M_.endo_names_long, 'q');
M_.endo_names = char(M_.endo_names, 'r');
M_.endo_names_tex = char(M_.endo_names_tex, 'r');
M_.endo_names_long = char(M_.endo_names_long, 'r');
M_.endo_names = char(M_.endo_names, 'rkc');
M_.endo_names_tex = char(M_.endo_names_tex, 'rkc');
M_.endo_names_long = char(M_.endo_names_long, 'rkc');
M_.endo_names = char(M_.endo_names, 'rkh');
M_.endo_names_tex = char(M_.endo_names_tex, 'rkh');
M_.endo_names_long = char(M_.endo_names_long, 'rkh');
M_.endo_names = char(M_.endo_names, 'uc');
M_.endo_names_tex = char(M_.endo_names_tex, 'uc');
M_.endo_names_long = char(M_.endo_names_long, 'uc');
M_.endo_names = char(M_.endo_names, 'uc1');
M_.endo_names_tex = char(M_.endo_names_tex, 'uc1');
M_.endo_names_long = char(M_.endo_names_long, 'uc1');
M_.endo_names = char(M_.endo_names, 'wc');
M_.endo_names_tex = char(M_.endo_names_tex, 'wc');
M_.endo_names_long = char(M_.endo_names_long, 'wc');
M_.endo_names = char(M_.endo_names, 'wc1');
M_.endo_names_tex = char(M_.endo_names_tex, 'wc1');
M_.endo_names_long = char(M_.endo_names_long, 'wc1');
M_.endo_names = char(M_.endo_names, 'wh');
M_.endo_names_tex = char(M_.endo_names_tex, 'wh');
M_.endo_names_long = char(M_.endo_names_long, 'wh');
M_.endo_names = char(M_.endo_names, 'wh1');
M_.endo_names_tex = char(M_.endo_names_tex, 'wh1');
M_.endo_names_long = char(M_.endo_names_long, 'wh1');
M_.endo_names = char(M_.endo_names, 'X');
M_.endo_names_tex = char(M_.endo_names_tex, 'X');
M_.endo_names_long = char(M_.endo_names_long, 'X');
M_.endo_names = char(M_.endo_names, 'xwc');
M_.endo_names_tex = char(M_.endo_names_tex, 'xwc');
M_.endo_names_long = char(M_.endo_names_long, 'xwc');
M_.endo_names = char(M_.endo_names, 'xwc1');
M_.endo_names_tex = char(M_.endo_names_tex, 'xwc1');
M_.endo_names_long = char(M_.endo_names_long, 'xwc1');
M_.endo_names = char(M_.endo_names, 'xwh');
M_.endo_names_tex = char(M_.endo_names_tex, 'xwh');
M_.endo_names_long = char(M_.endo_names_long, 'xwh');
M_.endo_names = char(M_.endo_names, 'xwh1');
M_.endo_names_tex = char(M_.endo_names_tex, 'xwh1');
M_.endo_names_long = char(M_.endo_names_long, 'xwh1');
M_.endo_names = char(M_.endo_names, 'Y');
M_.endo_names_tex = char(M_.endo_names_tex, 'Y');
M_.endo_names_long = char(M_.endo_names_long, 'Y');
M_.endo_names = char(M_.endo_names, 'zata_GDP');
M_.endo_names_tex = char(M_.endo_names_tex, 'zata\_GDP');
M_.endo_names_long = char(M_.endo_names_long, 'zata_GDP');
M_.endo_names = char(M_.endo_names, 'zkc');
M_.endo_names_tex = char(M_.endo_names_tex, 'zkc');
M_.endo_names_long = char(M_.endo_names_long, 'zkc');
M_.endo_names = char(M_.endo_names, 'zkh');
M_.endo_names_tex = char(M_.endo_names_tex, 'zkh');
M_.endo_names_long = char(M_.endo_names_long, 'zkh');
M_.endo_names = char(M_.endo_names, 'bf');
M_.endo_names_tex = char(M_.endo_names_tex, 'bf');
M_.endo_names_long = char(M_.endo_names_long, 'bf');
M_.endo_names = char(M_.endo_names, 'cf');
M_.endo_names_tex = char(M_.endo_names_tex, 'cf');
M_.endo_names_long = char(M_.endo_names_long, 'cf');
M_.endo_names = char(M_.endo_names, 'c1f');
M_.endo_names_tex = char(M_.endo_names_tex, 'c1f');
M_.endo_names_long = char(M_.endo_names_long, 'c1f');
M_.endo_names = char(M_.endo_names, 'hf');
M_.endo_names_tex = char(M_.endo_names_tex, 'hf');
M_.endo_names_long = char(M_.endo_names_long, 'hf');
M_.endo_names = char(M_.endo_names, 'h1f');
M_.endo_names_tex = char(M_.endo_names_tex, 'h1f');
M_.endo_names_long = char(M_.endo_names_long, 'h1f');
M_.endo_names = char(M_.endo_names, 'If');
M_.endo_names_tex = char(M_.endo_names_tex, 'If');
M_.endo_names_long = char(M_.endo_names_long, 'If');
M_.endo_names = char(M_.endo_names, 'kcf');
M_.endo_names_tex = char(M_.endo_names_tex, 'kcf');
M_.endo_names_long = char(M_.endo_names_long, 'kcf');
M_.endo_names = char(M_.endo_names, 'khf');
M_.endo_names_tex = char(M_.endo_names_tex, 'khf');
M_.endo_names_long = char(M_.endo_names_long, 'khf');
M_.endo_names = char(M_.endo_names, 'lmf');
M_.endo_names_tex = char(M_.endo_names_tex, 'lmf');
M_.endo_names_long = char(M_.endo_names_long, 'lmf');
M_.endo_names = char(M_.endo_names, 'ncf');
M_.endo_names_tex = char(M_.endo_names_tex, 'ncf');
M_.endo_names_long = char(M_.endo_names_long, 'ncf');
M_.endo_names = char(M_.endo_names, 'nc1f');
M_.endo_names_tex = char(M_.endo_names_tex, 'nc1f');
M_.endo_names_long = char(M_.endo_names_long, 'nc1f');
M_.endo_names = char(M_.endo_names, 'nhf');
M_.endo_names_tex = char(M_.endo_names_tex, 'nhf');
M_.endo_names_long = char(M_.endo_names_long, 'nhf');
M_.endo_names = char(M_.endo_names, 'nh1f');
M_.endo_names_tex = char(M_.endo_names_tex, 'nh1f');
M_.endo_names_long = char(M_.endo_names_long, 'nh1f');
M_.endo_names = char(M_.endo_names, 'qf');
M_.endo_names_tex = char(M_.endo_names_tex, 'qf');
M_.endo_names_long = char(M_.endo_names_long, 'qf');
M_.endo_names = char(M_.endo_names, 'rf');
M_.endo_names_tex = char(M_.endo_names_tex, 'rf');
M_.endo_names_long = char(M_.endo_names_long, 'rf');
M_.endo_names = char(M_.endo_names, 'rkcf');
M_.endo_names_tex = char(M_.endo_names_tex, 'rkcf');
M_.endo_names_long = char(M_.endo_names_long, 'rkcf');
M_.endo_names = char(M_.endo_names, 'rkhf');
M_.endo_names_tex = char(M_.endo_names_tex, 'rkhf');
M_.endo_names_long = char(M_.endo_names_long, 'rkhf');
M_.endo_names = char(M_.endo_names, 'ucf');
M_.endo_names_tex = char(M_.endo_names_tex, 'ucf');
M_.endo_names_long = char(M_.endo_names_long, 'ucf');
M_.endo_names = char(M_.endo_names, 'uc1f');
M_.endo_names_tex = char(M_.endo_names_tex, 'uc1f');
M_.endo_names_long = char(M_.endo_names_long, 'uc1f');
M_.endo_names = char(M_.endo_names, 'wcf');
M_.endo_names_tex = char(M_.endo_names_tex, 'wcf');
M_.endo_names_long = char(M_.endo_names_long, 'wcf');
M_.endo_names = char(M_.endo_names, 'wc1f');
M_.endo_names_tex = char(M_.endo_names_tex, 'wc1f');
M_.endo_names_long = char(M_.endo_names_long, 'wc1f');
M_.endo_names = char(M_.endo_names, 'whf');
M_.endo_names_tex = char(M_.endo_names_tex, 'whf');
M_.endo_names_long = char(M_.endo_names_long, 'whf');
M_.endo_names = char(M_.endo_names, 'wh1f');
M_.endo_names_tex = char(M_.endo_names_tex, 'wh1f');
M_.endo_names_long = char(M_.endo_names_long, 'wh1f');
M_.endo_names = char(M_.endo_names, 'Yf');
M_.endo_names_tex = char(M_.endo_names_tex, 'Yf');
M_.endo_names_long = char(M_.endo_names_long, 'Yf');
M_.endo_names = char(M_.endo_names, 'zkcf');
M_.endo_names_tex = char(M_.endo_names_tex, 'zkcf');
M_.endo_names_long = char(M_.endo_names_long, 'zkcf');
M_.endo_names = char(M_.endo_names, 'zkhf');
M_.endo_names_tex = char(M_.endo_names_tex, 'zkhf');
M_.endo_names_long = char(M_.endo_names_long, 'zkhf');
M_.endo_names = char(M_.endo_names, 'data_CCf');
M_.endo_names_tex = char(M_.endo_names_tex, 'data\_CCf');
M_.endo_names_long = char(M_.endo_names_long, 'data_CCf');
M_.endo_names = char(M_.endo_names, 'data_IHf');
M_.endo_names_tex = char(M_.endo_names_tex, 'data\_IHf');
M_.endo_names_long = char(M_.endo_names_long, 'data_IHf');
M_.endo_names = char(M_.endo_names, 'data_IKf');
M_.endo_names_tex = char(M_.endo_names_tex, 'data\_IKf');
M_.endo_names_long = char(M_.endo_names_long, 'data_IKf');
M_.endo_names = char(M_.endo_names, 'zata_GDPf');
M_.endo_names_tex = char(M_.endo_names_tex, 'zata\_GDPf');
M_.endo_names_long = char(M_.endo_names_long, 'zata_GDPf');
M_.endo_names = char(M_.endo_names, 'interest');
M_.endo_names_tex = char(M_.endo_names_tex, 'interest');
M_.endo_names_long = char(M_.endo_names_long, 'interest');
M_.endo_names = char(M_.endo_names, 'inflation');
M_.endo_names_tex = char(M_.endo_names_tex, 'inflation');
M_.endo_names_long = char(M_.endo_names_long, 'inflation');
M_.endo_names = char(M_.endo_names, 'inflationq');
M_.endo_names_tex = char(M_.endo_names_tex, 'inflationq');
M_.endo_names_long = char(M_.endo_names_long, 'inflationq');
M_.endo_names = char(M_.endo_names, 'outputgap');
M_.endo_names_tex = char(M_.endo_names_tex, 'outputgap');
M_.endo_names_long = char(M_.endo_names_long, 'outputgap');
M_.endo_names = char(M_.endo_names, 'output');
M_.endo_names_tex = char(M_.endo_names_tex, 'output');
M_.endo_names_long = char(M_.endo_names_long, 'output');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_86');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_86');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_86');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_90');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_90');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_90');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_94');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_94');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_94');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_121');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_121');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_121');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_125');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_125');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_125');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_129');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_129');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_129');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_156');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_156');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_156');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_160');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_160');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_160');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_164');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_164');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_164');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_20_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_20\_1');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_20_1');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_20_2');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_20\_2');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_20_2');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_84_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_84\_1');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_84_1');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_84_2');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_84\_2');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_84_2');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_84_3');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_84\_3');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_84_3');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_83_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_83\_1');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_83_1');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_83_2');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_83\_2');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_83_2');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_83_3');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_83\_3');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_83_3');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_80_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_80\_1');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_80_1');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_80_2');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_80\_2');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_80_2');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_80_3');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_80\_3');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_80_3');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_82_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_82\_1');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_82_1');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_82_2');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_82\_2');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_82_2');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_82_3');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_82\_3');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_82_3');
M_.param_names = 'cofintintb1';
M_.param_names_tex = 'cofintintb1';
M_.param_names_long = 'cofintintb1';
M_.param_names = char(M_.param_names, 'cofintintb2');
M_.param_names_tex = char(M_.param_names_tex, 'cofintintb2');
M_.param_names_long = char(M_.param_names_long, 'cofintintb2');
M_.param_names = char(M_.param_names, 'cofintintb3');
M_.param_names_tex = char(M_.param_names_tex, 'cofintintb3');
M_.param_names_long = char(M_.param_names_long, 'cofintintb3');
M_.param_names = char(M_.param_names, 'cofintintb4');
M_.param_names_tex = char(M_.param_names_tex, 'cofintintb4');
M_.param_names_long = char(M_.param_names_long, 'cofintintb4');
M_.param_names = char(M_.param_names, 'cofintinf0');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinf0');
M_.param_names_long = char(M_.param_names_long, 'cofintinf0');
M_.param_names = char(M_.param_names, 'cofintinfb1');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinfb1');
M_.param_names_long = char(M_.param_names_long, 'cofintinfb1');
M_.param_names = char(M_.param_names, 'cofintinfb2');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinfb2');
M_.param_names_long = char(M_.param_names_long, 'cofintinfb2');
M_.param_names = char(M_.param_names, 'cofintinfb3');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinfb3');
M_.param_names_long = char(M_.param_names_long, 'cofintinfb3');
M_.param_names = char(M_.param_names, 'cofintinfb4');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinfb4');
M_.param_names_long = char(M_.param_names_long, 'cofintinfb4');
M_.param_names = char(M_.param_names, 'cofintinff1');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinff1');
M_.param_names_long = char(M_.param_names_long, 'cofintinff1');
M_.param_names = char(M_.param_names, 'cofintinff2');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinff2');
M_.param_names_long = char(M_.param_names_long, 'cofintinff2');
M_.param_names = char(M_.param_names, 'cofintinff3');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinff3');
M_.param_names_long = char(M_.param_names_long, 'cofintinff3');
M_.param_names = char(M_.param_names, 'cofintinff4');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinff4');
M_.param_names_long = char(M_.param_names_long, 'cofintinff4');
M_.param_names = char(M_.param_names, 'cofintout');
M_.param_names_tex = char(M_.param_names_tex, 'cofintout');
M_.param_names_long = char(M_.param_names_long, 'cofintout');
M_.param_names = char(M_.param_names, 'cofintoutb1');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutb1');
M_.param_names_long = char(M_.param_names_long, 'cofintoutb1');
M_.param_names = char(M_.param_names, 'cofintoutb2');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutb2');
M_.param_names_long = char(M_.param_names_long, 'cofintoutb2');
M_.param_names = char(M_.param_names, 'cofintoutb3');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutb3');
M_.param_names_long = char(M_.param_names_long, 'cofintoutb3');
M_.param_names = char(M_.param_names, 'cofintoutb4');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutb4');
M_.param_names_long = char(M_.param_names_long, 'cofintoutb4');
M_.param_names = char(M_.param_names, 'cofintoutf1');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutf1');
M_.param_names_long = char(M_.param_names_long, 'cofintoutf1');
M_.param_names = char(M_.param_names, 'cofintoutf2');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutf2');
M_.param_names_long = char(M_.param_names_long, 'cofintoutf2');
M_.param_names = char(M_.param_names, 'cofintoutf3');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutf3');
M_.param_names_long = char(M_.param_names_long, 'cofintoutf3');
M_.param_names = char(M_.param_names, 'cofintoutf4');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutf4');
M_.param_names_long = char(M_.param_names_long, 'cofintoutf4');
M_.param_names = char(M_.param_names, 'cofintoutp');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutp');
M_.param_names_long = char(M_.param_names_long, 'cofintoutp');
M_.param_names = char(M_.param_names, 'cofintoutpb1');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpb1');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpb1');
M_.param_names = char(M_.param_names, 'cofintoutpb2');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpb2');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpb2');
M_.param_names = char(M_.param_names, 'cofintoutpb3');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpb3');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpb3');
M_.param_names = char(M_.param_names, 'cofintoutpb4');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpb4');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpb4');
M_.param_names = char(M_.param_names, 'cofintoutpf1');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpf1');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpf1');
M_.param_names = char(M_.param_names, 'cofintoutpf2');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpf2');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpf2');
M_.param_names = char(M_.param_names, 'cofintoutpf3');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpf3');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpf3');
M_.param_names = char(M_.param_names, 'cofintoutpf4');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpf4');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpf4');
M_.param_names = char(M_.param_names, 'std_r_');
M_.param_names_tex = char(M_.param_names_tex, 'std\_r\_');
M_.param_names_long = char(M_.param_names_long, 'std_r_');
M_.param_names = char(M_.param_names, 'std_r_quart');
M_.param_names_tex = char(M_.param_names_tex, 'std\_r\_quart');
M_.param_names_long = char(M_.param_names_long, 'std_r_quart');
M_.param_names = char(M_.param_names, 'BETA');
M_.param_names_tex = char(M_.param_names_tex, 'BETA');
M_.param_names_long = char(M_.param_names_long, 'BETA');
M_.param_names = char(M_.param_names, 'BETA1');
M_.param_names_tex = char(M_.param_names_tex, 'BETA1');
M_.param_names_long = char(M_.param_names_long, 'BETA1');
M_.param_names = char(M_.param_names, 'M');
M_.param_names_tex = char(M_.param_names_tex, 'M');
M_.param_names_long = char(M_.param_names_long, 'M');
M_.param_names = char(M_.param_names, 'JEI');
M_.param_names_tex = char(M_.param_names_tex, 'JEI');
M_.param_names_long = char(M_.param_names_long, 'JEI');
M_.param_names = char(M_.param_names, 'MUC');
M_.param_names_tex = char(M_.param_names_tex, 'MUC');
M_.param_names_long = char(M_.param_names_long, 'MUC');
M_.param_names = char(M_.param_names, 'MUH');
M_.param_names_tex = char(M_.param_names_tex, 'MUH');
M_.param_names_long = char(M_.param_names_long, 'MUH');
M_.param_names = char(M_.param_names, 'DKC');
M_.param_names_tex = char(M_.param_names_tex, 'DKC');
M_.param_names_long = char(M_.param_names_long, 'DKC');
M_.param_names = char(M_.param_names, 'DKH');
M_.param_names_tex = char(M_.param_names_tex, 'DKH');
M_.param_names_long = char(M_.param_names_long, 'DKH');
M_.param_names = char(M_.param_names, 'DH');
M_.param_names_tex = char(M_.param_names_tex, 'DH');
M_.param_names_long = char(M_.param_names_long, 'DH');
M_.param_names = char(M_.param_names, 'ETA');
M_.param_names_tex = char(M_.param_names_tex, 'ETA');
M_.param_names_long = char(M_.param_names_long, 'ETA');
M_.param_names = char(M_.param_names, 'ETA1');
M_.param_names_tex = char(M_.param_names_tex, 'ETA1');
M_.param_names_long = char(M_.param_names_long, 'ETA1');
M_.param_names = char(M_.param_names, 'EC');
M_.param_names_tex = char(M_.param_names_tex, 'EC');
M_.param_names_long = char(M_.param_names_long, 'EC');
M_.param_names = char(M_.param_names, 'EC1');
M_.param_names_tex = char(M_.param_names_tex, 'EC1');
M_.param_names_long = char(M_.param_names_long, 'EC1');
M_.param_names = char(M_.param_names, 'FIKC');
M_.param_names_tex = char(M_.param_names_tex, 'FIKC');
M_.param_names_long = char(M_.param_names_long, 'FIKC');
M_.param_names = char(M_.param_names, 'FIKH');
M_.param_names_tex = char(M_.param_names_tex, 'FIKH');
M_.param_names_long = char(M_.param_names_long, 'FIKH');
M_.param_names = char(M_.param_names, 'ALPHA');
M_.param_names_tex = char(M_.param_names_tex, 'ALPHA');
M_.param_names_long = char(M_.param_names_long, 'ALPHA');
M_.param_names = char(M_.param_names, 'TETA');
M_.param_names_tex = char(M_.param_names_tex, 'TETA');
M_.param_names_long = char(M_.param_names_long, 'TETA');
M_.param_names = char(M_.param_names, 'TAYLOR_R');
M_.param_names_tex = char(M_.param_names_tex, 'TAYLOR\_R');
M_.param_names_long = char(M_.param_names_long, 'TAYLOR_R');
M_.param_names = char(M_.param_names, 'TAYLOR_Y');
M_.param_names_tex = char(M_.param_names_tex, 'TAYLOR\_Y');
M_.param_names_long = char(M_.param_names_long, 'TAYLOR_Y');
M_.param_names = char(M_.param_names, 'TAYLOR_P');
M_.param_names_tex = char(M_.param_names_tex, 'TAYLOR\_P');
M_.param_names_long = char(M_.param_names_long, 'TAYLOR_P');
M_.param_names = char(M_.param_names, 'X_SS');
M_.param_names_tex = char(M_.param_names_tex, 'X\_SS');
M_.param_names_long = char(M_.param_names_long, 'X_SS');
M_.param_names = char(M_.param_names, 'LAGP');
M_.param_names_tex = char(M_.param_names_tex, 'LAGP');
M_.param_names_long = char(M_.param_names_long, 'LAGP');
M_.param_names = char(M_.param_names, 'RHO_AC');
M_.param_names_tex = char(M_.param_names_tex, 'RHO\_AC');
M_.param_names_long = char(M_.param_names_long, 'RHO_AC');
M_.param_names = char(M_.param_names, 'RHO_AH');
M_.param_names_tex = char(M_.param_names_tex, 'RHO\_AH');
M_.param_names_long = char(M_.param_names_long, 'RHO_AH');
M_.param_names = char(M_.param_names, 'RHO_AJ');
M_.param_names_tex = char(M_.param_names_tex, 'RHO\_AJ');
M_.param_names_long = char(M_.param_names_long, 'RHO_AJ');
M_.param_names = char(M_.param_names, 'RHO_AK');
M_.param_names_tex = char(M_.param_names_tex, 'RHO\_AK');
M_.param_names_long = char(M_.param_names_long, 'RHO_AK');
M_.param_names = char(M_.param_names, 'RHO_AM');
M_.param_names_tex = char(M_.param_names_tex, 'RHO\_AM');
M_.param_names_long = char(M_.param_names_long, 'RHO_AM');
M_.param_names = char(M_.param_names, 'RHO_AT');
M_.param_names_tex = char(M_.param_names_tex, 'RHO\_AT');
M_.param_names_long = char(M_.param_names_long, 'RHO_AT');
M_.param_names = char(M_.param_names, 'RHO_AZ');
M_.param_names_tex = char(M_.param_names_tex, 'RHO\_AZ');
M_.param_names_long = char(M_.param_names_long, 'RHO_AZ');
M_.param_names = char(M_.param_names, 'RHO_AS');
M_.param_names_tex = char(M_.param_names_tex, 'RHO\_AS');
M_.param_names_long = char(M_.param_names_long, 'RHO_AS');
M_.param_names = char(M_.param_names, 'NU');
M_.param_names_tex = char(M_.param_names_tex, 'NU');
M_.param_names_long = char(M_.param_names_long, 'NU');
M_.param_names = char(M_.param_names, 'NU1');
M_.param_names_tex = char(M_.param_names_tex, 'NU1');
M_.param_names_long = char(M_.param_names_long, 'NU1');
M_.param_names = char(M_.param_names, 'KAPPA');
M_.param_names_tex = char(M_.param_names_tex, 'KAPPA');
M_.param_names_long = char(M_.param_names_long, 'KAPPA');
M_.param_names = char(M_.param_names, 'XW_SS');
M_.param_names_tex = char(M_.param_names_tex, 'XW\_SS');
M_.param_names_long = char(M_.param_names_long, 'XW_SS');
M_.param_names = char(M_.param_names, 'TETAWC');
M_.param_names_tex = char(M_.param_names_tex, 'TETAWC');
M_.param_names_long = char(M_.param_names_long, 'TETAWC');
M_.param_names = char(M_.param_names, 'TETAWH');
M_.param_names_tex = char(M_.param_names_tex, 'TETAWH');
M_.param_names_long = char(M_.param_names_long, 'TETAWH');
M_.param_names = char(M_.param_names, 'LAGWC');
M_.param_names_tex = char(M_.param_names_tex, 'LAGWC');
M_.param_names_long = char(M_.param_names_long, 'LAGWC');
M_.param_names = char(M_.param_names, 'LAGWH');
M_.param_names_tex = char(M_.param_names_tex, 'LAGWH');
M_.param_names_long = char(M_.param_names_long, 'LAGWH');
M_.param_names = char(M_.param_names, 'ZETAKC');
M_.param_names_tex = char(M_.param_names_tex, 'ZETAKC');
M_.param_names_long = char(M_.param_names_long, 'ZETAKC');
M_.param_names = char(M_.param_names, 'TREND_AC');
M_.param_names_tex = char(M_.param_names_tex, 'TREND\_AC');
M_.param_names_long = char(M_.param_names_long, 'TREND_AC');
M_.param_names = char(M_.param_names, 'TREND_AH');
M_.param_names_tex = char(M_.param_names_tex, 'TREND\_AH');
M_.param_names_long = char(M_.param_names_long, 'TREND_AH');
M_.param_names = char(M_.param_names, 'TREND_AK');
M_.param_names_tex = char(M_.param_names_tex, 'TREND\_AK');
M_.param_names_long = char(M_.param_names_long, 'TREND_AK');
M_.param_names = char(M_.param_names, 'MUBB');
M_.param_names_tex = char(M_.param_names_tex, 'MUBB');
M_.param_names_long = char(M_.param_names_long, 'MUBB');
M_.param_names = char(M_.param_names, 'Xf');
M_.param_names_tex = char(M_.param_names_tex, 'Xf');
M_.param_names_long = char(M_.param_names_long, 'Xf');
M_.param_names = char(M_.param_names, 'xwcf');
M_.param_names_tex = char(M_.param_names_tex, 'xwcf');
M_.param_names_long = char(M_.param_names_long, 'xwcf');
M_.param_names = char(M_.param_names, 'xwc1f');
M_.param_names_tex = char(M_.param_names_tex, 'xwc1f');
M_.param_names_long = char(M_.param_names_long, 'xwc1f');
M_.param_names = char(M_.param_names, 'xwhf');
M_.param_names_tex = char(M_.param_names_tex, 'xwhf');
M_.param_names_long = char(M_.param_names_long, 'xwhf');
M_.param_names = char(M_.param_names, 'xwh1f');
M_.param_names_tex = char(M_.param_names_tex, 'xwh1f');
M_.param_names_long = char(M_.param_names_long, 'xwh1f');
M_.exo_det_nbr = 0;
M_.exo_nbr = 9;
M_.endo_nbr = 108;
M_.param_nbr = 81;
M_.orig_endo_nbr = 85;
M_.aux_vars(1).endo_index = 86;
M_.aux_vars(1).type = 0;
M_.aux_vars(2).endo_index = 87;
M_.aux_vars(2).type = 0;
M_.aux_vars(3).endo_index = 88;
M_.aux_vars(3).type = 0;
M_.aux_vars(4).endo_index = 89;
M_.aux_vars(4).type = 0;
M_.aux_vars(5).endo_index = 90;
M_.aux_vars(5).type = 0;
M_.aux_vars(6).endo_index = 91;
M_.aux_vars(6).type = 0;
M_.aux_vars(7).endo_index = 92;
M_.aux_vars(7).type = 0;
M_.aux_vars(8).endo_index = 93;
M_.aux_vars(8).type = 0;
M_.aux_vars(9).endo_index = 94;
M_.aux_vars(9).type = 0;
M_.aux_vars(10).endo_index = 95;
M_.aux_vars(10).type = 1;
M_.aux_vars(10).orig_index = 21;
M_.aux_vars(10).orig_lead_lag = -1;
M_.aux_vars(11).endo_index = 96;
M_.aux_vars(11).type = 1;
M_.aux_vars(11).orig_index = 21;
M_.aux_vars(11).orig_lead_lag = -2;
M_.aux_vars(12).endo_index = 97;
M_.aux_vars(12).type = 1;
M_.aux_vars(12).orig_index = 85;
M_.aux_vars(12).orig_lead_lag = -1;
M_.aux_vars(13).endo_index = 98;
M_.aux_vars(13).type = 1;
M_.aux_vars(13).orig_index = 85;
M_.aux_vars(13).orig_lead_lag = -2;
M_.aux_vars(14).endo_index = 99;
M_.aux_vars(14).type = 1;
M_.aux_vars(14).orig_index = 85;
M_.aux_vars(14).orig_lead_lag = -3;
M_.aux_vars(15).endo_index = 100;
M_.aux_vars(15).type = 1;
M_.aux_vars(15).orig_index = 84;
M_.aux_vars(15).orig_lead_lag = -1;
M_.aux_vars(16).endo_index = 101;
M_.aux_vars(16).type = 1;
M_.aux_vars(16).orig_index = 84;
M_.aux_vars(16).orig_lead_lag = -2;
M_.aux_vars(17).endo_index = 102;
M_.aux_vars(17).type = 1;
M_.aux_vars(17).orig_index = 84;
M_.aux_vars(17).orig_lead_lag = -3;
M_.aux_vars(18).endo_index = 103;
M_.aux_vars(18).type = 1;
M_.aux_vars(18).orig_index = 81;
M_.aux_vars(18).orig_lead_lag = -1;
M_.aux_vars(19).endo_index = 104;
M_.aux_vars(19).type = 1;
M_.aux_vars(19).orig_index = 81;
M_.aux_vars(19).orig_lead_lag = -2;
M_.aux_vars(20).endo_index = 105;
M_.aux_vars(20).type = 1;
M_.aux_vars(20).orig_index = 81;
M_.aux_vars(20).orig_lead_lag = -3;
M_.aux_vars(21).endo_index = 106;
M_.aux_vars(21).type = 1;
M_.aux_vars(21).orig_index = 83;
M_.aux_vars(21).orig_lead_lag = -1;
M_.aux_vars(22).endo_index = 107;
M_.aux_vars(22).type = 1;
M_.aux_vars(22).orig_index = 83;
M_.aux_vars(22).orig_lead_lag = -2;
M_.aux_vars(23).endo_index = 108;
M_.aux_vars(23).type = 1;
M_.aux_vars(23).orig_index = 83;
M_.aux_vars(23).orig_lead_lag = -3;
M_.Sigma_e = zeros(9, 9);
M_.Correlation_matrix = eye(9, 9);
M_.H = 0;
M_.Correlation_matrix_ME = 1;
M_.sigma_e_is_diagonal = 1;
options_.block=0;
options_.bytecode=0;
options_.use_dll=0;
erase_compiled_function('US_IN10_static');
erase_compiled_function('US_IN10_dynamic');
M_.lead_lag_incidence = [
 1 47 0;
 2 48 0;
 3 49 0;
 4 50 155;
 5 51 0;
 6 52 0;
 7 53 0;
 8 54 0;
 9 55 156;
 10 56 157;
 0 57 0;
 0 58 0;
 0 59 0;
 0 60 0;
 0 61 0;
 0 62 0;
 0 63 0;
 0 64 0;
 0 65 0;
 0 66 0;
 11 67 158;
 12 68 0;
 13 69 0;
 0 70 0;
 14 71 159;
 15 72 160;
 0 73 0;
 0 74 0;
 0 75 0;
 0 76 0;
 0 77 0;
 0 78 161;
 16 79 0;
 0 80 162;
 0 81 163;
 0 82 164;
 0 83 165;
 17 84 166;
 18 85 167;
 19 86 168;
 20 87 169;
 0 88 0;
 0 89 0;
 0 90 0;
 0 91 0;
 0 92 0;
 0 93 0;
 0 94 0;
 0 95 170;
 0 96 171;
 21 97 0;
 22 98 172;
 23 99 173;
 24 100 0;
 25 101 0;
 0 102 0;
 26 103 174;
 27 104 175;
 0 105 0;
 0 106 0;
 0 107 0;
 0 108 0;
 0 109 0;
 0 110 176;
 28 111 0;
 0 112 177;
 0 113 178;
 0 114 179;
 0 115 180;
 0 116 0;
 0 117 0;
 0 118 0;
 0 119 0;
 0 120 0;
 0 121 181;
 0 122 182;
 0 123 0;
 0 124 0;
 0 125 0;
 0 126 0;
 29 127 0;
 0 128 0;
 30 129 183;
 31 130 184;
 32 131 185;
 0 132 186;
 0 133 187;
 0 134 188;
 0 135 189;
 0 136 190;
 0 137 191;
 0 138 192;
 0 139 193;
 0 140 194;
 33 141 0;
 34 142 0;
 35 143 0;
 36 144 0;
 37 145 0;
 38 146 0;
 39 147 0;
 40 148 0;
 41 149 0;
 42 150 0;
 43 151 0;
 44 152 0;
 45 153 0;
 46 154 0;]';
M_.nstatic = 39;
M_.nfwrd   = 23;
M_.npred   = 29;
M_.nboth   = 17;
M_.nsfwrd   = 40;
M_.nspred   = 46;
M_.ndynamic   = 69;
M_.equations_tags = {
};
M_.static_and_dynamic_models_differ = 0;
M_.exo_names_orig_ord = [1:9];
M_.maximum_lag = 1;
M_.maximum_lead = 1;
M_.maximum_endo_lag = 1;
M_.maximum_endo_lead = 1;
oo_.steady_state = zeros(108, 1);
M_.maximum_exo_lag = 0;
M_.maximum_exo_lead = 0;
oo_.exo_steady_state = zeros(9, 1);
M_.params = NaN(81, 1);
M_.NNZDerivatives = zeros(3, 1);
M_.NNZDerivatives(1) = 525;
M_.NNZDerivatives(2) = 718;
M_.NNZDerivatives(3) = -1;
thispath = cd;                                                           
cd('..');                                                                
load policy_param.mat;                                                   
for i=1:33                                                               
deep_parameter_name = M_.param_names(i,:);                           
eval(['M_.params(i)  = ' deep_parameter_name ' ;'])                  
end                                                                      
cd(thispath);
M_.params( 32 ) = 100;
std_r_ = M_.params( 32 );
M_.params( 54 ) = 1.15;
X_SS = M_.params( 54 );
M_.params( 67 ) = 1.15;
XW_SS = M_.params( 67 );
M_.params( 34 ) = 0.9925;
BETA = M_.params( 34 );
M_.params( 35 ) = 0.97;
BETA1 = M_.params( 35 );
M_.params( 37 ) = 0.12;
JEI = M_.params( 37 );
M_.params( 38 ) = 0.35;
MUC = M_.params( 38 );
M_.params( 39 ) = 0.10;
MUH = M_.params( 39 );
M_.params( 66 ) = 0.10;
KAPPA = M_.params( 66 );
M_.params( 76 ) = 0.10;
MUBB = M_.params( 76 );
M_.params( 40 ) = 0.025;
DKC = M_.params( 40 );
M_.params( 41 ) = 0.03;
DKH = M_.params( 41 );
M_.params( 42 ) = 0.01;
DH = M_.params( 42 );
M_.params( 36 ) = 0.85;
M = M_.params( 36 );
M_.params( 63 ) = 0.975;
RHO_AS = M_.params( 63 );
M_.params( 77 ) = log(M_.params(54));
Xf = M_.params( 77 );
M_.params( 78 ) = log(M_.params(67));
xwcf = M_.params( 78 );
M_.params( 79 ) = log(M_.params(67));
xwc1f = M_.params( 79 );
M_.params( 80 ) = log(M_.params(67));
xwhf = M_.params( 80 );
M_.params( 81 ) = log(M_.params(67));
xwh1f = M_.params( 81 );
M_.params( 49 ) = 0.79343;
ALPHA = M_.params( 49 );
M_.params( 45 ) = 0.31423;
EC = M_.params( 45 );
M_.params( 46 ) = 0.56897;
EC1 = M_.params( 46 );
M_.params( 43 ) = 0.52381;
ETA = M_.params( 43 );
M_.params( 44 ) = 0.50602;
ETA1 = M_.params( 44 );
M_.params( 47 ) = 14.47013;
FIKC = M_.params( 47 );
M_.params( 48 ) = 11.02808;
FIKH = M_.params( 48 );
M_.params( 55 ) = 0.69106;
LAGP = M_.params( 55 );
M_.params( 70 ) = 0.08301;
LAGWC = M_.params( 70 );
M_.params( 71 ) = 0.41186;
LAGWH = M_.params( 71 );
M_.params( 64 ) = (-0.6833);
NU = M_.params( 64 );
M_.params( 65 ) = (-0.96538);
NU1 = M_.params( 65 );
M_.params( 53 ) = 1.40444;
TAYLOR_P = M_.params( 53 );
M_.params( 51 ) = 0.59913;
TAYLOR_R = M_.params( 51 );
M_.params( 52 ) = 0.51261;
TAYLOR_Y = M_.params( 52 );
M_.params( 50 ) = 0.83671;
TETA = M_.params( 50 );
M_.params( 68 ) = 0.79204;
TETAWC = M_.params( 68 );
M_.params( 69 ) = 0.91181;
TETAWH = M_.params( 69 );
M_.params( 73 ) = 0.0032;
TREND_AC = M_.params( 73 );
M_.params( 74 ) = 0.0008;
TREND_AH = M_.params( 74 );
M_.params( 75 ) = 0.00275;
TREND_AK = M_.params( 75 );
M_.params( 72 ) = 0.70394;
ZETAKC = M_.params( 72 );
M_.params( 56 ) = 0.94265;
RHO_AC = M_.params( 56 );
M_.params( 57 ) = 0.99713;
RHO_AH = M_.params( 57 );
M_.params( 58 ) = 0.95875;
RHO_AJ = M_.params( 58 );
M_.params( 59 ) = 0.92384;
RHO_AK = M_.params( 59 );
M_.params( 61 ) = 0.92158;
RHO_AT = M_.params( 61 );
M_.params( 62 ) = 0.96439;
RHO_AZ = M_.params( 62 );
STDERR_AC	=	0.01011	;
STDERR_AE	=	0.00336	;
STDERR_AH	=	0.01942	;
STDERR_AJ	=	0.04094	;
STDERR_AK	=	0.01068	;
STDERR_AP	=	0.00457	;
STDERR_AS	=	0.00034*100	;
STDERR_AT	=	0.0252	;
STDERR_AZ	=	0.01711	;
%
% SHOCKS instructions
%
make_ex_;
M_.exo_det_length = 0;
M_.Sigma_e(1, 1) = (STDERR_AC)^2;
M_.Sigma_e(2, 2) = (STDERR_AH)^2;
M_.Sigma_e(3, 3) = (STDERR_AJ)^2;
M_.Sigma_e(4, 4) = (STDERR_AK)^2;
M_.Sigma_e(5, 5) = (STDERR_AP)^2;
M_.Sigma_e(6, 6) = (STDERR_AS)^2;
M_.Sigma_e(7, 7) = (STDERR_AT)^2;
M_.Sigma_e(8, 8) = (STDERR_AZ)^2;
save('US_IN10_results.mat', 'oo_', 'M_', 'options_');
if exist('estim_params_', 'var') == 1
  save('US_IN10_results.mat', 'estim_params_', '-append');
end
if exist('bayestopt_', 'var') == 1
  save('US_IN10_results.mat', 'bayestopt_', '-append');
end
if exist('dataset_', 'var') == 1
  save('US_IN10_results.mat', 'dataset_', '-append');
end
if exist('estimation_info', 'var') == 1
  save('US_IN10_results.mat', 'estimation_info', '-append');
end


disp(['Total computing time : ' dynsec2hms(toc) ]);
if ~isempty(lastwarn)
  disp('Note: warning(s) encountered in MATLAB/Octave code')
end
diary off
