%
% Status : main Dynare file
%
% Warning : this file is generated automatically by Dynare
%           from model file (.mod)

tic0 = tic;
% Save empty dates and dseries objects in memory.
dates('initialize');
dseries('initialize');
% Define global variables.
global M_ options_ oo_ estim_params_ bayestopt_ dataset_ dataset_info estimation_info ys0_ ex0_
options_ = [];
M_.fname = 'US_OW98';
M_.dynare_version = '4.5.5';
oo_.dynare_version = '4.5.5';
options_.dynare_version = '4.5.5';
%
% Some global variables initialization
%
global_initialization;
diary off;
diary('US_OW98.log');
M_.exo_names = 'ecsh';
M_.exo_names_tex = 'ecsh';
M_.exo_names_long = 'ecsh';
M_.exo_names = char(M_.exo_names, 'efish');
M_.exo_names_tex = char(M_.exo_names_tex, 'efish');
M_.exo_names_long = char(M_.exo_names_long, 'efish');
M_.exo_names = char(M_.exo_names, 'eiish');
M_.exo_names_tex = char(M_.exo_names_tex, 'eiish');
M_.exo_names_long = char(M_.exo_names_long, 'eiish');
M_.exo_names = char(M_.exo_names, 'exsh');
M_.exo_names_tex = char(M_.exo_names_tex, 'exsh');
M_.exo_names_long = char(M_.exo_names_long, 'exsh');
M_.exo_names = char(M_.exo_names, 'cwsh');
M_.exo_names_tex = char(M_.exo_names_tex, 'cwsh');
M_.exo_names_long = char(M_.exo_names_long, 'cwsh');
M_.exo_names = char(M_.exo_names, 'interest_');
M_.exo_names_tex = char(M_.exo_names_tex, 'interest\_');
M_.exo_names_long = char(M_.exo_names_long, 'interest_');
M_.exo_names = char(M_.exo_names, 'fiscal_');
M_.exo_names_tex = char(M_.exo_names_tex, 'fiscal\_');
M_.exo_names_long = char(M_.exo_names_long, 'fiscal_');
M_.endo_names = 'ygap';
M_.endo_names_tex = 'ygap';
M_.endo_names_long = 'ygap';
M_.endo_names = char(M_.endo_names, 'pdot');
M_.endo_names_tex = char(M_.endo_names_tex, 'pdot');
M_.endo_names_long = char(M_.endo_names_long, 'pdot');
M_.endo_names = char(M_.endo_names, 'rff');
M_.endo_names_tex = char(M_.endo_names_tex, 'rff');
M_.endo_names_long = char(M_.endo_names_long, 'rff');
M_.endo_names = char(M_.endo_names, 'drff');
M_.endo_names_tex = char(M_.endo_names_tex, 'drff');
M_.endo_names_long = char(M_.endo_names_long, 'drff');
M_.endo_names = char(M_.endo_names, 'pinf');
M_.endo_names_tex = char(M_.endo_names_tex, 'pinf');
M_.endo_names_long = char(M_.endo_names_long, 'pinf');
M_.endo_names = char(M_.endo_names, 'plevel');
M_.endo_names_tex = char(M_.endo_names_tex, 'plevel');
M_.endo_names_long = char(M_.endo_names_long, 'plevel');
M_.endo_names = char(M_.endo_names, 'rl');
M_.endo_names_tex = char(M_.endo_names_tex, 'rl');
M_.endo_names_long = char(M_.endo_names_long, 'rl');
M_.endo_names = char(M_.endo_names, 'rrl');
M_.endo_names_tex = char(M_.endo_names_tex, 'rrl');
M_.endo_names_long = char(M_.endo_names_long, 'rrl');
M_.endo_names = char(M_.endo_names, 'ec');
M_.endo_names_tex = char(M_.endo_names_tex, 'ec');
M_.endo_names_long = char(M_.endo_names_long, 'ec');
M_.endo_names = char(M_.endo_names, 'efi');
M_.endo_names_tex = char(M_.endo_names_tex, 'efi');
M_.endo_names_long = char(M_.endo_names_long, 'efi');
M_.endo_names = char(M_.endo_names, 'eii');
M_.endo_names_tex = char(M_.endo_names_tex, 'eii');
M_.endo_names_long = char(M_.endo_names_long, 'eii');
M_.endo_names = char(M_.endo_names, 'eg');
M_.endo_names_tex = char(M_.endo_names_tex, 'eg');
M_.endo_names_long = char(M_.endo_names_long, 'eg');
M_.endo_names = char(M_.endo_names, 'ex');
M_.endo_names_tex = char(M_.endo_names_tex, 'ex');
M_.endo_names_long = char(M_.endo_names_long, 'ex');
M_.endo_names = char(M_.endo_names, 'yp');
M_.endo_names_tex = char(M_.endo_names_tex, 'yp');
M_.endo_names_long = char(M_.endo_names_long, 'yp');
M_.endo_names = char(M_.endo_names, 'cwage');
M_.endo_names_tex = char(M_.endo_names_tex, 'cwage');
M_.endo_names_long = char(M_.endo_names_long, 'cwage');
M_.endo_names = char(M_.endo_names, 'vindex');
M_.endo_names_tex = char(M_.endo_names_tex, 'vindex');
M_.endo_names_long = char(M_.endo_names_long, 'vindex');
M_.endo_names = char(M_.endo_names, 'pitarg');
M_.endo_names_tex = char(M_.endo_names_tex, 'pitarg');
M_.endo_names_long = char(M_.endo_names_long, 'pitarg');
M_.endo_names = char(M_.endo_names, 'rho1');
M_.endo_names_tex = char(M_.endo_names_tex, 'rho1');
M_.endo_names_long = char(M_.endo_names_long, 'rho1');
M_.endo_names = char(M_.endo_names, 'rho16');
M_.endo_names_tex = char(M_.endo_names_tex, 'rho16');
M_.endo_names_long = char(M_.endo_names_long, 'rho16');
M_.endo_names = char(M_.endo_names, 'rho28');
M_.endo_names_tex = char(M_.endo_names_tex, 'rho28');
M_.endo_names_long = char(M_.endo_names_long, 'rho28');
M_.endo_names = char(M_.endo_names, 'rho40');
M_.endo_names_tex = char(M_.endo_names_tex, 'rho40');
M_.endo_names_long = char(M_.endo_names_long, 'rho40');
M_.endo_names = char(M_.endo_names, 'dygap');
M_.endo_names_tex = char(M_.endo_names_tex, 'dygap');
M_.endo_names_long = char(M_.endo_names_long, 'dygap');
M_.endo_names = char(M_.endo_names, 'cwage1');
M_.endo_names_tex = char(M_.endo_names_tex, 'cwage1');
M_.endo_names_long = char(M_.endo_names_long, 'cwage1');
M_.endo_names = char(M_.endo_names, 'cwage2');
M_.endo_names_tex = char(M_.endo_names_tex, 'cwage2');
M_.endo_names_long = char(M_.endo_names_long, 'cwage2');
M_.endo_names = char(M_.endo_names, 'plevel1');
M_.endo_names_tex = char(M_.endo_names_tex, 'plevel1');
M_.endo_names_long = char(M_.endo_names_long, 'plevel1');
M_.endo_names = char(M_.endo_names, 'plevel2');
M_.endo_names_tex = char(M_.endo_names_tex, 'plevel2');
M_.endo_names_long = char(M_.endo_names_long, 'plevel2');
M_.endo_names = char(M_.endo_names, 'plevel3');
M_.endo_names_tex = char(M_.endo_names_tex, 'plevel3');
M_.endo_names_long = char(M_.endo_names_long, 'plevel3');
M_.endo_names = char(M_.endo_names, 'rff1');
M_.endo_names_tex = char(M_.endo_names_tex, 'rff1');
M_.endo_names_long = char(M_.endo_names_long, 'rff1');
M_.endo_names = char(M_.endo_names, 'efi1');
M_.endo_names_tex = char(M_.endo_names_tex, 'efi1');
M_.endo_names_long = char(M_.endo_names_long, 'efi1');
M_.endo_names = char(M_.endo_names, 'efi2');
M_.endo_names_tex = char(M_.endo_names_tex, 'efi2');
M_.endo_names_long = char(M_.endo_names_long, 'efi2');
M_.endo_names = char(M_.endo_names, 'eii1');
M_.endo_names_tex = char(M_.endo_names_tex, 'eii1');
M_.endo_names_long = char(M_.endo_names_long, 'eii1');
M_.endo_names = char(M_.endo_names, 'eii2');
M_.endo_names_tex = char(M_.endo_names_tex, 'eii2');
M_.endo_names_long = char(M_.endo_names_long, 'eii2');
M_.endo_names = char(M_.endo_names, 'ygap1');
M_.endo_names_tex = char(M_.endo_names_tex, 'ygap1');
M_.endo_names_long = char(M_.endo_names_long, 'ygap1');
M_.endo_names = char(M_.endo_names, 'ygap2');
M_.endo_names_tex = char(M_.endo_names_tex, 'ygap2');
M_.endo_names_long = char(M_.endo_names_long, 'ygap2');
M_.endo_names = char(M_.endo_names, 'egsh');
M_.endo_names_tex = char(M_.endo_names_tex, 'egsh');
M_.endo_names_long = char(M_.endo_names_long, 'egsh');
M_.endo_names = char(M_.endo_names, 'interest');
M_.endo_names_tex = char(M_.endo_names_tex, 'interest');
M_.endo_names_long = char(M_.endo_names_long, 'interest');
M_.endo_names = char(M_.endo_names, 'inflation');
M_.endo_names_tex = char(M_.endo_names_tex, 'inflation');
M_.endo_names_long = char(M_.endo_names_long, 'inflation');
M_.endo_names = char(M_.endo_names, 'inflationq');
M_.endo_names_tex = char(M_.endo_names_tex, 'inflationq');
M_.endo_names_long = char(M_.endo_names_long, 'inflationq');
M_.endo_names = char(M_.endo_names, 'outputgap');
M_.endo_names_tex = char(M_.endo_names_tex, 'outputgap');
M_.endo_names_long = char(M_.endo_names_long, 'outputgap');
M_.endo_names = char(M_.endo_names, 'output');
M_.endo_names_tex = char(M_.endo_names_tex, 'output');
M_.endo_names_long = char(M_.endo_names_long, 'output');
M_.endo_names = char(M_.endo_names, 'fispol');
M_.endo_names_tex = char(M_.endo_names_tex, 'fispol');
M_.endo_names_long = char(M_.endo_names_long, 'fispol');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_84');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_84');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_84');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_88');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_88');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_88');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_92');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_92');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_92');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_119');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_119');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_119');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_123');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_123');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_123');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_127');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_127');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_127');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_154');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_154');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_154');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_158');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_158');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_158');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_162');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_162');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_162');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_230');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_230');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_230');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_232');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_232');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_232');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_234');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_234');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_234');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_237');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_237');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_237');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_240');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_240');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_240');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_243');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_243');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_243');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_545');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_545');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_545');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_549');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_549');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_549');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_553');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_553');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_553');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_557');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_557');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_557');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_561');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_561');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_561');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_565');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_565');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_565');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_249');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_249');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_249');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_340');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_340');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_340');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_344');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_344');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_344');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_348');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_348');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_348');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_352');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_352');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_352');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_356');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_356');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_356');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_360');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_360');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_360');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_364');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_364');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_364');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_389');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_389');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_389');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_393');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_393');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_393');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_1_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_1\_1');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_1_1');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_1_2');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_1\_2');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_1_2');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_39_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_39\_1');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_39_1');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_39_2');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_39\_2');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_39_2');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_39_3');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_39\_3');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_39_3');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_38_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_38\_1');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_38_1');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_38_2');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_38\_2');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_38_2');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_38_3');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_38\_3');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_38_3');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_35_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_35\_1');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_35_1');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_35_2');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_35\_2');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_35_2');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_35_3');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_35\_3');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_35_3');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_37_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_37\_1');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_37_1');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_37_2');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_37\_2');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_37_2');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_37_3');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_37\_3');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_37_3');
M_.endo_partitions = struct();
M_.param_names = 'cofintintb1';
M_.param_names_tex = 'cofintintb1';
M_.param_names_long = 'cofintintb1';
M_.param_names = char(M_.param_names, 'cofintintb2');
M_.param_names_tex = char(M_.param_names_tex, 'cofintintb2');
M_.param_names_long = char(M_.param_names_long, 'cofintintb2');
M_.param_names = char(M_.param_names, 'cofintintb3');
M_.param_names_tex = char(M_.param_names_tex, 'cofintintb3');
M_.param_names_long = char(M_.param_names_long, 'cofintintb3');
M_.param_names = char(M_.param_names, 'cofintintb4');
M_.param_names_tex = char(M_.param_names_tex, 'cofintintb4');
M_.param_names_long = char(M_.param_names_long, 'cofintintb4');
M_.param_names = char(M_.param_names, 'cofintinf0');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinf0');
M_.param_names_long = char(M_.param_names_long, 'cofintinf0');
M_.param_names = char(M_.param_names, 'cofintinfb1');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinfb1');
M_.param_names_long = char(M_.param_names_long, 'cofintinfb1');
M_.param_names = char(M_.param_names, 'cofintinfb2');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinfb2');
M_.param_names_long = char(M_.param_names_long, 'cofintinfb2');
M_.param_names = char(M_.param_names, 'cofintinfb3');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinfb3');
M_.param_names_long = char(M_.param_names_long, 'cofintinfb3');
M_.param_names = char(M_.param_names, 'cofintinfb4');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinfb4');
M_.param_names_long = char(M_.param_names_long, 'cofintinfb4');
M_.param_names = char(M_.param_names, 'cofintinff1');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinff1');
M_.param_names_long = char(M_.param_names_long, 'cofintinff1');
M_.param_names = char(M_.param_names, 'cofintinff2');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinff2');
M_.param_names_long = char(M_.param_names_long, 'cofintinff2');
M_.param_names = char(M_.param_names, 'cofintinff3');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinff3');
M_.param_names_long = char(M_.param_names_long, 'cofintinff3');
M_.param_names = char(M_.param_names, 'cofintinff4');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinff4');
M_.param_names_long = char(M_.param_names_long, 'cofintinff4');
M_.param_names = char(M_.param_names, 'cofintout');
M_.param_names_tex = char(M_.param_names_tex, 'cofintout');
M_.param_names_long = char(M_.param_names_long, 'cofintout');
M_.param_names = char(M_.param_names, 'cofintoutb1');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutb1');
M_.param_names_long = char(M_.param_names_long, 'cofintoutb1');
M_.param_names = char(M_.param_names, 'cofintoutb2');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutb2');
M_.param_names_long = char(M_.param_names_long, 'cofintoutb2');
M_.param_names = char(M_.param_names, 'cofintoutb3');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutb3');
M_.param_names_long = char(M_.param_names_long, 'cofintoutb3');
M_.param_names = char(M_.param_names, 'cofintoutb4');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutb4');
M_.param_names_long = char(M_.param_names_long, 'cofintoutb4');
M_.param_names = char(M_.param_names, 'cofintoutf1');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutf1');
M_.param_names_long = char(M_.param_names_long, 'cofintoutf1');
M_.param_names = char(M_.param_names, 'cofintoutf2');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutf2');
M_.param_names_long = char(M_.param_names_long, 'cofintoutf2');
M_.param_names = char(M_.param_names, 'cofintoutf3');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutf3');
M_.param_names_long = char(M_.param_names_long, 'cofintoutf3');
M_.param_names = char(M_.param_names, 'cofintoutf4');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutf4');
M_.param_names_long = char(M_.param_names_long, 'cofintoutf4');
M_.param_names = char(M_.param_names, 'cofintoutp');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutp');
M_.param_names_long = char(M_.param_names_long, 'cofintoutp');
M_.param_names = char(M_.param_names, 'cofintoutpb1');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpb1');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpb1');
M_.param_names = char(M_.param_names, 'cofintoutpb2');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpb2');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpb2');
M_.param_names = char(M_.param_names, 'cofintoutpb3');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpb3');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpb3');
M_.param_names = char(M_.param_names, 'cofintoutpb4');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpb4');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpb4');
M_.param_names = char(M_.param_names, 'cofintoutpf1');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpf1');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpf1');
M_.param_names = char(M_.param_names, 'cofintoutpf2');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpf2');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpf2');
M_.param_names = char(M_.param_names, 'cofintoutpf3');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpf3');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpf3');
M_.param_names = char(M_.param_names, 'cofintoutpf4');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpf4');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpf4');
M_.param_names = char(M_.param_names, 'std_r_');
M_.param_names_tex = char(M_.param_names_tex, 'std\_r\_');
M_.param_names_long = char(M_.param_names_long, 'std_r_');
M_.param_names = char(M_.param_names, 'std_r_quart');
M_.param_names_tex = char(M_.param_names_tex, 'std\_r\_quart');
M_.param_names_long = char(M_.param_names_long, 'std_r_quart');
M_.param_names = char(M_.param_names, 'coffispol');
M_.param_names_tex = char(M_.param_names_tex, 'coffispol');
M_.param_names_long = char(M_.param_names_long, 'coffispol');
M_.param_names = char(M_.param_names, 'ecbar');
M_.param_names_tex = char(M_.param_names_tex, 'ecbar');
M_.param_names_long = char(M_.param_names_long, 'ecbar');
M_.param_names = char(M_.param_names, 'efibar');
M_.param_names_tex = char(M_.param_names_tex, 'efibar');
M_.param_names_long = char(M_.param_names_long, 'efibar');
M_.param_names = char(M_.param_names, 'eiibar');
M_.param_names_tex = char(M_.param_names_tex, 'eiibar');
M_.param_names_long = char(M_.param_names_long, 'eiibar');
M_.param_names = char(M_.param_names, 'exbar');
M_.param_names_tex = char(M_.param_names_tex, 'exbar');
M_.param_names_long = char(M_.param_names_long, 'exbar');
M_.param_names = char(M_.param_names, 'egbar');
M_.param_names_tex = char(M_.param_names_tex, 'egbar');
M_.param_names_long = char(M_.param_names_long, 'egbar');
M_.param_names = char(M_.param_names, 'pinfbar');
M_.param_names_tex = char(M_.param_names_tex, 'pinfbar');
M_.param_names_long = char(M_.param_names_long, 'pinfbar');
M_.param_names = char(M_.param_names, 'rffbar');
M_.param_names_tex = char(M_.param_names_tex, 'rffbar');
M_.param_names_long = char(M_.param_names_long, 'rffbar');
M_.param_names = char(M_.param_names, 'rrlbar');
M_.param_names_tex = char(M_.param_names_tex, 'rrlbar');
M_.param_names_long = char(M_.param_names_long, 'rrlbar');
M_.param_partitions = struct();
M_.exo_det_nbr = 0;
M_.exo_nbr = 7;
M_.endo_nbr = 86;
M_.param_nbr = 42;
M_.orig_endo_nbr = 41;
M_.aux_vars(1).endo_index = 42;
M_.aux_vars(1).type = 0;
M_.aux_vars(2).endo_index = 43;
M_.aux_vars(2).type = 0;
M_.aux_vars(3).endo_index = 44;
M_.aux_vars(3).type = 0;
M_.aux_vars(4).endo_index = 45;
M_.aux_vars(4).type = 0;
M_.aux_vars(5).endo_index = 46;
M_.aux_vars(5).type = 0;
M_.aux_vars(6).endo_index = 47;
M_.aux_vars(6).type = 0;
M_.aux_vars(7).endo_index = 48;
M_.aux_vars(7).type = 0;
M_.aux_vars(8).endo_index = 49;
M_.aux_vars(8).type = 0;
M_.aux_vars(9).endo_index = 50;
M_.aux_vars(9).type = 0;
M_.aux_vars(10).endo_index = 51;
M_.aux_vars(10).type = 0;
M_.aux_vars(11).endo_index = 52;
M_.aux_vars(11).type = 0;
M_.aux_vars(12).endo_index = 53;
M_.aux_vars(12).type = 0;
M_.aux_vars(13).endo_index = 54;
M_.aux_vars(13).type = 0;
M_.aux_vars(14).endo_index = 55;
M_.aux_vars(14).type = 0;
M_.aux_vars(15).endo_index = 56;
M_.aux_vars(15).type = 0;
M_.aux_vars(16).endo_index = 57;
M_.aux_vars(16).type = 0;
M_.aux_vars(17).endo_index = 58;
M_.aux_vars(17).type = 0;
M_.aux_vars(18).endo_index = 59;
M_.aux_vars(18).type = 0;
M_.aux_vars(19).endo_index = 60;
M_.aux_vars(19).type = 0;
M_.aux_vars(20).endo_index = 61;
M_.aux_vars(20).type = 0;
M_.aux_vars(21).endo_index = 62;
M_.aux_vars(21).type = 0;
M_.aux_vars(22).endo_index = 63;
M_.aux_vars(22).type = 0;
M_.aux_vars(23).endo_index = 64;
M_.aux_vars(23).type = 0;
M_.aux_vars(24).endo_index = 65;
M_.aux_vars(24).type = 0;
M_.aux_vars(25).endo_index = 66;
M_.aux_vars(25).type = 0;
M_.aux_vars(26).endo_index = 67;
M_.aux_vars(26).type = 0;
M_.aux_vars(27).endo_index = 68;
M_.aux_vars(27).type = 0;
M_.aux_vars(28).endo_index = 69;
M_.aux_vars(28).type = 0;
M_.aux_vars(29).endo_index = 70;
M_.aux_vars(29).type = 0;
M_.aux_vars(30).endo_index = 71;
M_.aux_vars(30).type = 0;
M_.aux_vars(31).endo_index = 72;
M_.aux_vars(31).type = 0;
M_.aux_vars(32).endo_index = 73;
M_.aux_vars(32).type = 1;
M_.aux_vars(32).orig_index = 2;
M_.aux_vars(32).orig_lead_lag = -1;
M_.aux_vars(33).endo_index = 74;
M_.aux_vars(33).type = 1;
M_.aux_vars(33).orig_index = 2;
M_.aux_vars(33).orig_lead_lag = -2;
M_.aux_vars(34).endo_index = 75;
M_.aux_vars(34).type = 1;
M_.aux_vars(34).orig_index = 40;
M_.aux_vars(34).orig_lead_lag = -1;
M_.aux_vars(35).endo_index = 76;
M_.aux_vars(35).type = 1;
M_.aux_vars(35).orig_index = 40;
M_.aux_vars(35).orig_lead_lag = -2;
M_.aux_vars(36).endo_index = 77;
M_.aux_vars(36).type = 1;
M_.aux_vars(36).orig_index = 40;
M_.aux_vars(36).orig_lead_lag = -3;
M_.aux_vars(37).endo_index = 78;
M_.aux_vars(37).type = 1;
M_.aux_vars(37).orig_index = 39;
M_.aux_vars(37).orig_lead_lag = -1;
M_.aux_vars(38).endo_index = 79;
M_.aux_vars(38).type = 1;
M_.aux_vars(38).orig_index = 39;
M_.aux_vars(38).orig_lead_lag = -2;
M_.aux_vars(39).endo_index = 80;
M_.aux_vars(39).type = 1;
M_.aux_vars(39).orig_index = 39;
M_.aux_vars(39).orig_lead_lag = -3;
M_.aux_vars(40).endo_index = 81;
M_.aux_vars(40).type = 1;
M_.aux_vars(40).orig_index = 36;
M_.aux_vars(40).orig_lead_lag = -1;
M_.aux_vars(41).endo_index = 82;
M_.aux_vars(41).type = 1;
M_.aux_vars(41).orig_index = 36;
M_.aux_vars(41).orig_lead_lag = -2;
M_.aux_vars(42).endo_index = 83;
M_.aux_vars(42).type = 1;
M_.aux_vars(42).orig_index = 36;
M_.aux_vars(42).orig_lead_lag = -3;
M_.aux_vars(43).endo_index = 84;
M_.aux_vars(43).type = 1;
M_.aux_vars(43).orig_index = 38;
M_.aux_vars(43).orig_lead_lag = -1;
M_.aux_vars(44).endo_index = 85;
M_.aux_vars(44).type = 1;
M_.aux_vars(44).orig_index = 38;
M_.aux_vars(44).orig_lead_lag = -2;
M_.aux_vars(45).endo_index = 86;
M_.aux_vars(45).type = 1;
M_.aux_vars(45).orig_index = 38;
M_.aux_vars(45).orig_lead_lag = -3;
M_.Sigma_e = zeros(7, 7);
M_.Correlation_matrix = eye(7, 7);
M_.H = 0;
M_.Correlation_matrix_ME = 1;
M_.sigma_e_is_diagonal = 1;
M_.det_shocks = [];
options_.linear = 1;
options_.block=0;
options_.bytecode=0;
options_.use_dll=0;
M_.hessian_eq_zero = 1;
erase_compiled_function('US_OW98_static');
erase_compiled_function('US_OW98_dynamic');
M_.orig_eq_nbr = 41;
M_.eq_nbr = 86;
M_.ramsey_eq_nbr = 0;
M_.set_auxiliary_variables = exist(['./' M_.fname '_set_auxiliary_variables.m'], 'file') == 2;
M_.lead_lag_incidence = [
 1 38 124;
 2 39 125;
 3 40 126;
 0 41 0;
 0 42 0;
 4 43 127;
 0 44 0;
 0 45 0;
 5 46 0;
 6 47 0;
 7 48 0;
 8 49 0;
 0 50 0;
 0 51 0;
 9 52 0;
 0 53 128;
 0 54 0;
 0 55 0;
 0 56 129;
 0 57 130;
 0 58 131;
 0 59 0;
 10 60 0;
 11 61 0;
 12 62 0;
 13 63 0;
 14 64 0;
 0 65 0;
 15 66 0;
 16 67 0;
 17 68 0;
 18 69 0;
 19 70 0;
 0 71 0;
 0 72 0;
 20 73 0;
 0 74 0;
 21 75 132;
 22 76 133;
 23 77 134;
 0 78 0;
 0 79 135;
 0 80 136;
 0 81 137;
 0 82 138;
 0 83 139;
 0 84 140;
 0 85 141;
 0 86 142;
 0 87 143;
 0 88 144;
 0 89 145;
 0 90 146;
 0 91 147;
 0 92 148;
 0 93 149;
 0 94 150;
 0 95 151;
 0 96 152;
 0 97 153;
 0 98 154;
 0 99 155;
 0 100 156;
 0 101 157;
 0 102 158;
 0 103 159;
 0 104 160;
 0 105 161;
 0 106 162;
 0 107 163;
 0 108 164;
 0 109 165;
 24 110 0;
 25 111 0;
 26 112 0;
 27 113 0;
 28 114 0;
 29 115 0;
 30 116 0;
 31 117 0;
 32 118 0;
 33 119 0;
 34 120 0;
 35 121 0;
 36 122 0;
 37 123 0;]';
M_.nstatic = 14;
M_.nfwrd   = 35;
M_.npred   = 30;
M_.nboth   = 7;
M_.nsfwrd   = 42;
M_.nspred   = 37;
M_.ndynamic   = 72;
M_.equations_tags = {
};
M_.static_and_dynamic_models_differ = 0;
M_.exo_names_orig_ord = [1:7];
M_.maximum_lag = 1;
M_.maximum_lead = 1;
M_.maximum_endo_lag = 1;
M_.maximum_endo_lead = 1;
oo_.steady_state = zeros(86, 1);
M_.maximum_exo_lag = 0;
M_.maximum_exo_lead = 0;
oo_.exo_steady_state = zeros(7, 1);
M_.params = NaN(42, 1);
M_.NNZDerivatives = [273; 0; -1];
M_.params( 35 ) = 6.8355548687555923e-01;
ecbar = M_.params( 35 );
M_.params( 36 ) = 1.4661885394578772e-01;
efibar = M_.params( 36 );
M_.params( 37 ) = 3.9412501642005875e-03;
eiibar = M_.params( 37 );
M_.params( 38 ) = (-2.0844600536418095e-02);
exbar = M_.params( 38 );
M_.params( 39 ) = 1.8672901279611806e-01;
egbar = M_.params( 39 );
M_.params( 40 ) = 1.7383970534932569e-02;
pinfbar = M_.params( 40 );
M_.params( 41 ) = 2.7673575521404148e-02;
rffbar = M_.params( 41 );
M_.params( 42 ) = 1.0289616884640973e-02;
rrlbar = M_.params( 42 );
thispath = cd;                                                           
cd('..');                                                                
load policy_param.mat;                                                   
for i=1:33                                                               
deep_parameter_name = M_.param_names(i,:);                           
eval(['M_.params(i)  = ' deep_parameter_name ' ;'])                  
end                                                                      
cd(thispath);  
M_.params( 34 ) = 1;
coffispol = M_.params( 34 );
%
% INITVAL instructions
%
options_.initval_file = 0;
oo_.steady_state( 1 ) = 0;
oo_.steady_state( 2 ) = 1.7383970534932569e-02;
oo_.steady_state( 3 ) = 2.7673575521404148e-02;
oo_.steady_state( 4 ) = 0;
oo_.steady_state( 5 ) = 1.7383970534932569e-02;
oo_.steady_state( 7 ) = 2.7673575521404148e-02;
oo_.steady_state( 8 ) = 1.0289616884640973e-02;
oo_.steady_state( 9 ) = 6.8355548687555923e-01;
oo_.steady_state( 10 ) = 1.4661885394578772e-01;
oo_.steady_state( 11 ) = 3.9412501642005875e-03;
oo_.steady_state( 13 ) = (-2.0844600536418095e-02);
oo_.steady_state( 12 ) = 1.8672901279611806e-01;
oo_.steady_state(42)=oo_.steady_state(38);
oo_.steady_state(43)=oo_.steady_state(42);
oo_.steady_state(44)=oo_.steady_state(43);
oo_.steady_state(45)=oo_.steady_state(39);
oo_.steady_state(46)=oo_.steady_state(45);
oo_.steady_state(47)=oo_.steady_state(46);
oo_.steady_state(48)=oo_.steady_state(40);
oo_.steady_state(49)=oo_.steady_state(48);
oo_.steady_state(50)=oo_.steady_state(49);
oo_.steady_state(51)=oo_.steady_state(3);
oo_.steady_state(52)=oo_.steady_state(51);
oo_.steady_state(53)=oo_.steady_state(52);
oo_.steady_state(54)=oo_.steady_state(53);
oo_.steady_state(55)=oo_.steady_state(54);
oo_.steady_state(56)=oo_.steady_state(55);
oo_.steady_state(57)=oo_.steady_state(6);
oo_.steady_state(58)=oo_.steady_state(57);
oo_.steady_state(59)=oo_.steady_state(58);
oo_.steady_state(60)=oo_.steady_state(59);
oo_.steady_state(61)=oo_.steady_state(60);
oo_.steady_state(62)=oo_.steady_state(61);
oo_.steady_state(63)=oo_.steady_state(62);
oo_.steady_state(64)=oo_.steady_state(1);
oo_.steady_state(65)=oo_.steady_state(64);
oo_.steady_state(66)=oo_.steady_state(65);
oo_.steady_state(67)=oo_.steady_state(66);
oo_.steady_state(68)=oo_.steady_state(67);
oo_.steady_state(69)=oo_.steady_state(68);
oo_.steady_state(70)=oo_.steady_state(69);
oo_.steady_state(71)=oo_.steady_state(16);
oo_.steady_state(72)=oo_.steady_state(71);
oo_.steady_state(73)=oo_.steady_state(2);
oo_.steady_state(74)=oo_.steady_state(73);
oo_.steady_state(75)=oo_.steady_state(40);
oo_.steady_state(76)=oo_.steady_state(75);
oo_.steady_state(77)=oo_.steady_state(76);
oo_.steady_state(78)=oo_.steady_state(39);
oo_.steady_state(79)=oo_.steady_state(78);
oo_.steady_state(80)=oo_.steady_state(79);
oo_.steady_state(81)=oo_.steady_state(36);
oo_.steady_state(82)=oo_.steady_state(81);
oo_.steady_state(83)=oo_.steady_state(82);
oo_.steady_state(84)=oo_.steady_state(38);
oo_.steady_state(85)=oo_.steady_state(84);
oo_.steady_state(86)=oo_.steady_state(85);
if M_.exo_nbr > 0
	oo_.exo_simul = ones(M_.maximum_lag,1)*oo_.exo_steady_state';
end
if M_.exo_det_nbr > 0
	oo_.exo_det_simul = ones(M_.maximum_lag,1)*oo_.exo_det_steady_state';
end
resid(1);
%
% SHOCKS instructions
%
M_.exo_det_length = 0;
M_.Sigma_e(1, 1) = 0.0245105432212782;
M_.Sigma_e(2, 2) = 0.0121088247371104;
M_.Sigma_e(3, 3) = 0.0252368905045492;
M_.Sigma_e(4, 4) = 0.009059864201557719;
M_.Sigma_e(5, 5) = 0.00304717660977982;
M_.Sigma_e(6, 6) = 0;
M_.Sigma_e(7, 7) = 0.00807080286146075;
M_.Sigma_e(1, 2) = 0.00762469240533302;
M_.Sigma_e(2, 1) = M_.Sigma_e(1, 2);
M_.Sigma_e(1, 3) = (-0.00590629883332327);
M_.Sigma_e(3, 1) = M_.Sigma_e(1, 3);
M_.Sigma_e(1, 4) = (-0.00141362462520144);
M_.Sigma_e(4, 1) = M_.Sigma_e(1, 4);
M_.Sigma_e(1, 5) = (-0.00349609855147809);
M_.Sigma_e(5, 1) = M_.Sigma_e(1, 5);
M_.Sigma_e(1, 7) = 0.000868855343396095;
M_.Sigma_e(7, 1) = M_.Sigma_e(1, 7);
M_.Sigma_e(2, 3) = (-0.00238405721647661);
M_.Sigma_e(3, 2) = M_.Sigma_e(2, 3);
M_.Sigma_e(2, 4) = (-0.0007766145992529081);
M_.Sigma_e(4, 2) = M_.Sigma_e(2, 4);
M_.Sigma_e(2, 5) = (-0.000803846938996685);
M_.Sigma_e(5, 2) = M_.Sigma_e(2, 5);
M_.Sigma_e(2, 7) = (-0.00138239167190924);
M_.Sigma_e(7, 2) = M_.Sigma_e(2, 7);
M_.Sigma_e(3, 4) = 0.000124592513572702;
M_.Sigma_e(4, 3) = M_.Sigma_e(3, 4);
M_.Sigma_e(3, 5) = 0.00205962361259062;
M_.Sigma_e(5, 3) = M_.Sigma_e(3, 5);
M_.Sigma_e(3, 7) = (-0.00267524897907621);
M_.Sigma_e(7, 3) = M_.Sigma_e(3, 7);
M_.Sigma_e(4, 5) = 0.000639353499797624;
M_.Sigma_e(5, 4) = M_.Sigma_e(4, 5);
M_.Sigma_e(6, 1) = 0;
M_.Sigma_e(1, 6) = M_.Sigma_e(6, 1);
M_.Sigma_e(6, 2) = 0;
M_.Sigma_e(2, 6) = M_.Sigma_e(6, 2);
M_.Sigma_e(6, 3) = 0;
M_.Sigma_e(3, 6) = M_.Sigma_e(6, 3);
M_.Sigma_e(6, 4) = 0;
M_.Sigma_e(4, 6) = M_.Sigma_e(6, 4);
M_.Sigma_e(6, 5) = 0;
M_.Sigma_e(5, 6) = M_.Sigma_e(6, 5);
M_.Sigma_e(6, 7) = 0;
M_.Sigma_e(7, 6) = M_.Sigma_e(6, 7);
M_.Sigma_e(7, 4) = (-0.00128555415697415);
M_.Sigma_e(4, 7) = M_.Sigma_e(7, 4);
M_.Sigma_e(7, 5) = (-0.000785205142464003);
M_.Sigma_e(5, 7) = M_.Sigma_e(7, 5);
M_.sigma_e_is_diagonal = 0;
options_.Schur_vec_tol = 1e-6;  
save('US_OW98_results.mat', 'oo_', 'M_', 'options_');
if exist('estim_params_', 'var') == 1
  save('US_OW98_results.mat', 'estim_params_', '-append');
end
if exist('bayestopt_', 'var') == 1
  save('US_OW98_results.mat', 'bayestopt_', '-append');
end
if exist('dataset_', 'var') == 1
  save('US_OW98_results.mat', 'dataset_', '-append');
end
if exist('estimation_info', 'var') == 1
  save('US_OW98_results.mat', 'estimation_info', '-append');
end
if exist('dataset_info', 'var') == 1
  save('US_OW98_results.mat', 'dataset_info', '-append');
end
if exist('oo_recursive_', 'var') == 1
  save('US_OW98_results.mat', 'oo_recursive_', '-append');
end


disp(['Total computing time : ' dynsec2hms(toc(tic0)) ]);
if ~isempty(lastwarn)
  disp('Note: warning(s) encountered in MATLAB/Octave code')
end
diary off
