%
% Status : main Dynare file
%
% Warning : this file is generated automatically by Dynare
%           from model file (.mod)

tic0 = tic;
% Save empty dates and dseries objects in memory.
dates('initialize');
dseries('initialize');
% Define global variables.
global M_ options_ oo_ estim_params_ bayestopt_ dataset_ dataset_info estimation_info ys0_ ex0_
options_ = [];
M_.fname = 'NK_GK11';
M_.dynare_version = '4.5.4';
oo_.dynare_version = '4.5.4';
options_.dynare_version = '4.5.4';
%
% Some global variables initialization
%
global_initialization;
diary off;
diary('NK_GK11.log');
M_.exo_names = 'e_a';
M_.exo_names_tex = 'e\_a';
M_.exo_names_long = 'e_a';
M_.exo_names = char(M_.exo_names, 'e_ksi');
M_.exo_names_tex = char(M_.exo_names_tex, 'e\_ksi');
M_.exo_names_long = char(M_.exo_names_long, 'e_ksi');
M_.exo_names = char(M_.exo_names, 'e_Ne');
M_.exo_names_tex = char(M_.exo_names_tex, 'e\_Ne');
M_.exo_names_long = char(M_.exo_names_long, 'e_Ne');
M_.exo_names = char(M_.exo_names, 'interest_');
M_.exo_names_tex = char(M_.exo_names_tex, 'interest\_');
M_.exo_names_long = char(M_.exo_names_long, 'interest_');
M_.exo_names = char(M_.exo_names, 'fiscal_');
M_.exo_names_tex = char(M_.exo_names_tex, 'fiscal\_');
M_.exo_names_long = char(M_.exo_names_long, 'fiscal_');
M_.endo_names = 'Y';
M_.endo_names_tex = 'Y';
M_.endo_names_long = 'Y';
M_.endo_names = char(M_.endo_names, 'Ym');
M_.endo_names_tex = char(M_.endo_names_tex, 'Ym');
M_.endo_names_long = char(M_.endo_names_long, 'Ym');
M_.endo_names = char(M_.endo_names, 'K');
M_.endo_names_tex = char(M_.endo_names_tex, 'K');
M_.endo_names_long = char(M_.endo_names_long, 'K');
M_.endo_names = char(M_.endo_names, 'Keff');
M_.endo_names_tex = char(M_.endo_names_tex, 'Keff');
M_.endo_names_long = char(M_.endo_names_long, 'Keff');
M_.endo_names = char(M_.endo_names, 'L');
M_.endo_names_tex = char(M_.endo_names_tex, 'L');
M_.endo_names_long = char(M_.endo_names_long, 'L');
M_.endo_names = char(M_.endo_names, 'I');
M_.endo_names_tex = char(M_.endo_names_tex, 'I');
M_.endo_names_long = char(M_.endo_names_long, 'I');
M_.endo_names = char(M_.endo_names, 'C');
M_.endo_names_tex = char(M_.endo_names_tex, 'C');
M_.endo_names_long = char(M_.endo_names_long, 'C');
M_.endo_names = char(M_.endo_names, 'G');
M_.endo_names_tex = char(M_.endo_names_tex, 'G');
M_.endo_names_long = char(M_.endo_names_long, 'G');
M_.endo_names = char(M_.endo_names, 'Q');
M_.endo_names_tex = char(M_.endo_names_tex, 'Q');
M_.endo_names_long = char(M_.endo_names_long, 'Q');
M_.endo_names = char(M_.endo_names, 'varrho');
M_.endo_names_tex = char(M_.endo_names_tex, 'varrho');
M_.endo_names_long = char(M_.endo_names_long, 'varrho');
M_.endo_names = char(M_.endo_names, 'Lambda');
M_.endo_names_tex = char(M_.endo_names_tex, 'Lambda');
M_.endo_names_long = char(M_.endo_names_long, 'Lambda');
M_.endo_names = char(M_.endo_names, 'Rk');
M_.endo_names_tex = char(M_.endo_names_tex, 'Rk');
M_.endo_names_long = char(M_.endo_names_long, 'Rk');
M_.endo_names = char(M_.endo_names, 'R');
M_.endo_names_tex = char(M_.endo_names_tex, 'R');
M_.endo_names_long = char(M_.endo_names_long, 'R');
M_.endo_names = char(M_.endo_names, 'N');
M_.endo_names_tex = char(M_.endo_names_tex, 'N');
M_.endo_names_long = char(M_.endo_names_long, 'N');
M_.endo_names = char(M_.endo_names, 'Ne');
M_.endo_names_tex = char(M_.endo_names_tex, 'Ne');
M_.endo_names_long = char(M_.endo_names_long, 'Ne');
M_.endo_names = char(M_.endo_names, 'Nn');
M_.endo_names_tex = char(M_.endo_names_tex, 'Nn');
M_.endo_names_long = char(M_.endo_names_long, 'Nn');
M_.endo_names = char(M_.endo_names, 'nu');
M_.endo_names_tex = char(M_.endo_names_tex, 'nu');
M_.endo_names_long = char(M_.endo_names_long, 'nu');
M_.endo_names = char(M_.endo_names, 'eta');
M_.endo_names_tex = char(M_.endo_names_tex, 'eta');
M_.endo_names_long = char(M_.endo_names_long, 'eta');
M_.endo_names = char(M_.endo_names, 'phi');
M_.endo_names_tex = char(M_.endo_names_tex, 'phi');
M_.endo_names_long = char(M_.endo_names_long, 'phi');
M_.endo_names = char(M_.endo_names, 'z');
M_.endo_names_tex = char(M_.endo_names_tex, 'z');
M_.endo_names_long = char(M_.endo_names_long, 'z');
M_.endo_names = char(M_.endo_names, 'x');
M_.endo_names_tex = char(M_.endo_names_tex, 'x');
M_.endo_names_long = char(M_.endo_names_long, 'x');
M_.endo_names = char(M_.endo_names, 'Pm');
M_.endo_names_tex = char(M_.endo_names_tex, 'Pm');
M_.endo_names_long = char(M_.endo_names_long, 'Pm');
M_.endo_names = char(M_.endo_names, 'w');
M_.endo_names_tex = char(M_.endo_names_tex, 'w');
M_.endo_names_long = char(M_.endo_names_long, 'w');
M_.endo_names = char(M_.endo_names, 'VMPK');
M_.endo_names_tex = char(M_.endo_names_tex, 'VMPK');
M_.endo_names_long = char(M_.endo_names_long, 'VMPK');
M_.endo_names = char(M_.endo_names, 'U');
M_.endo_names_tex = char(M_.endo_names_tex, 'U');
M_.endo_names_long = char(M_.endo_names_long, 'U');
M_.endo_names = char(M_.endo_names, 'X');
M_.endo_names_tex = char(M_.endo_names_tex, 'X');
M_.endo_names_long = char(M_.endo_names_long, 'X');
M_.endo_names = char(M_.endo_names, 'D');
M_.endo_names_tex = char(M_.endo_names_tex, 'D');
M_.endo_names_long = char(M_.endo_names_long, 'D');
M_.endo_names = char(M_.endo_names, 'F');
M_.endo_names_tex = char(M_.endo_names_tex, 'F');
M_.endo_names_long = char(M_.endo_names_long, 'F');
M_.endo_names = char(M_.endo_names, 'Z');
M_.endo_names_tex = char(M_.endo_names_tex, 'Z');
M_.endo_names_long = char(M_.endo_names_long, 'Z');
M_.endo_names = char(M_.endo_names, 'i');
M_.endo_names_tex = char(M_.endo_names_tex, 'i');
M_.endo_names_long = char(M_.endo_names_long, 'i');
M_.endo_names = char(M_.endo_names, 'prem');
M_.endo_names_tex = char(M_.endo_names_tex, 'prem');
M_.endo_names_long = char(M_.endo_names_long, 'prem');
M_.endo_names = char(M_.endo_names, 'delta');
M_.endo_names_tex = char(M_.endo_names_tex, 'delta');
M_.endo_names_long = char(M_.endo_names_long, 'delta');
M_.endo_names = char(M_.endo_names, 'In');
M_.endo_names_tex = char(M_.endo_names_tex, 'In');
M_.endo_names_long = char(M_.endo_names_long, 'In');
M_.endo_names = char(M_.endo_names, 'Welf');
M_.endo_names_tex = char(M_.endo_names_tex, 'Welf');
M_.endo_names_long = char(M_.endo_names_long, 'Welf');
M_.endo_names = char(M_.endo_names, 'infl');
M_.endo_names_tex = char(M_.endo_names_tex, 'infl');
M_.endo_names_long = char(M_.endo_names_long, 'infl');
M_.endo_names = char(M_.endo_names, 'inflstar');
M_.endo_names_tex = char(M_.endo_names_tex, 'inflstar');
M_.endo_names_long = char(M_.endo_names_long, 'inflstar');
M_.endo_names = char(M_.endo_names, 'Yf');
M_.endo_names_tex = char(M_.endo_names_tex, 'Yf');
M_.endo_names_long = char(M_.endo_names_long, 'Yf');
M_.endo_names = char(M_.endo_names, 'Ymf');
M_.endo_names_tex = char(M_.endo_names_tex, 'Ymf');
M_.endo_names_long = char(M_.endo_names_long, 'Ymf');
M_.endo_names = char(M_.endo_names, 'Kf');
M_.endo_names_tex = char(M_.endo_names_tex, 'Kf');
M_.endo_names_long = char(M_.endo_names_long, 'Kf');
M_.endo_names = char(M_.endo_names, 'Kefff');
M_.endo_names_tex = char(M_.endo_names_tex, 'Kefff');
M_.endo_names_long = char(M_.endo_names_long, 'Kefff');
M_.endo_names = char(M_.endo_names, 'Lf');
M_.endo_names_tex = char(M_.endo_names_tex, 'Lf');
M_.endo_names_long = char(M_.endo_names_long, 'Lf');
M_.endo_names = char(M_.endo_names, 'If');
M_.endo_names_tex = char(M_.endo_names_tex, 'If');
M_.endo_names_long = char(M_.endo_names_long, 'If');
M_.endo_names = char(M_.endo_names, 'Cf');
M_.endo_names_tex = char(M_.endo_names_tex, 'Cf');
M_.endo_names_long = char(M_.endo_names_long, 'Cf');
M_.endo_names = char(M_.endo_names, 'Gf');
M_.endo_names_tex = char(M_.endo_names_tex, 'Gf');
M_.endo_names_long = char(M_.endo_names_long, 'Gf');
M_.endo_names = char(M_.endo_names, 'Qf');
M_.endo_names_tex = char(M_.endo_names_tex, 'Qf');
M_.endo_names_long = char(M_.endo_names_long, 'Qf');
M_.endo_names = char(M_.endo_names, 'varrhof');
M_.endo_names_tex = char(M_.endo_names_tex, 'varrhof');
M_.endo_names_long = char(M_.endo_names_long, 'varrhof');
M_.endo_names = char(M_.endo_names, 'Lambdaf');
M_.endo_names_tex = char(M_.endo_names_tex, 'Lambdaf');
M_.endo_names_long = char(M_.endo_names_long, 'Lambdaf');
M_.endo_names = char(M_.endo_names, 'Rkf');
M_.endo_names_tex = char(M_.endo_names_tex, 'Rkf');
M_.endo_names_long = char(M_.endo_names_long, 'Rkf');
M_.endo_names = char(M_.endo_names, 'Rf');
M_.endo_names_tex = char(M_.endo_names_tex, 'Rf');
M_.endo_names_long = char(M_.endo_names_long, 'Rf');
M_.endo_names = char(M_.endo_names, 'Nf');
M_.endo_names_tex = char(M_.endo_names_tex, 'Nf');
M_.endo_names_long = char(M_.endo_names_long, 'Nf');
M_.endo_names = char(M_.endo_names, 'Nef');
M_.endo_names_tex = char(M_.endo_names_tex, 'Nef');
M_.endo_names_long = char(M_.endo_names_long, 'Nef');
M_.endo_names = char(M_.endo_names, 'Nnf');
M_.endo_names_tex = char(M_.endo_names_tex, 'Nnf');
M_.endo_names_long = char(M_.endo_names_long, 'Nnf');
M_.endo_names = char(M_.endo_names, 'nuf');
M_.endo_names_tex = char(M_.endo_names_tex, 'nuf');
M_.endo_names_long = char(M_.endo_names_long, 'nuf');
M_.endo_names = char(M_.endo_names, 'etaf');
M_.endo_names_tex = char(M_.endo_names_tex, 'etaf');
M_.endo_names_long = char(M_.endo_names_long, 'etaf');
M_.endo_names = char(M_.endo_names, 'phif');
M_.endo_names_tex = char(M_.endo_names_tex, 'phif');
M_.endo_names_long = char(M_.endo_names_long, 'phif');
M_.endo_names = char(M_.endo_names, 'zf');
M_.endo_names_tex = char(M_.endo_names_tex, 'zf');
M_.endo_names_long = char(M_.endo_names_long, 'zf');
M_.endo_names = char(M_.endo_names, 'xf');
M_.endo_names_tex = char(M_.endo_names_tex, 'xf');
M_.endo_names_long = char(M_.endo_names_long, 'xf');
M_.endo_names = char(M_.endo_names, 'wf');
M_.endo_names_tex = char(M_.endo_names_tex, 'wf');
M_.endo_names_long = char(M_.endo_names_long, 'wf');
M_.endo_names = char(M_.endo_names, 'VMPKf');
M_.endo_names_tex = char(M_.endo_names_tex, 'VMPKf');
M_.endo_names_long = char(M_.endo_names_long, 'VMPKf');
M_.endo_names = char(M_.endo_names, 'Uf');
M_.endo_names_tex = char(M_.endo_names_tex, 'Uf');
M_.endo_names_long = char(M_.endo_names_long, 'Uf');
M_.endo_names = char(M_.endo_names, 'premf');
M_.endo_names_tex = char(M_.endo_names_tex, 'premf');
M_.endo_names_long = char(M_.endo_names_long, 'premf');
M_.endo_names = char(M_.endo_names, 'deltaf');
M_.endo_names_tex = char(M_.endo_names_tex, 'deltaf');
M_.endo_names_long = char(M_.endo_names_long, 'deltaf');
M_.endo_names = char(M_.endo_names, 'In_f');
M_.endo_names_tex = char(M_.endo_names_tex, 'In\_f');
M_.endo_names_long = char(M_.endo_names_long, 'In_f');
M_.endo_names = char(M_.endo_names, 'Welff');
M_.endo_names_tex = char(M_.endo_names_tex, 'Welff');
M_.endo_names_long = char(M_.endo_names_long, 'Welff');
M_.endo_names = char(M_.endo_names, 'a');
M_.endo_names_tex = char(M_.endo_names_tex, 'a');
M_.endo_names_long = char(M_.endo_names_long, 'a');
M_.endo_names = char(M_.endo_names, 'ksi');
M_.endo_names_tex = char(M_.endo_names_tex, 'ksi');
M_.endo_names_long = char(M_.endo_names_long, 'ksi');
M_.endo_names = char(M_.endo_names, 'g');
M_.endo_names_tex = char(M_.endo_names_tex, 'g');
M_.endo_names_long = char(M_.endo_names_long, 'g');
M_.endo_names = char(M_.endo_names, 'e_g');
M_.endo_names_tex = char(M_.endo_names_tex, 'e\_g');
M_.endo_names_long = char(M_.endo_names_long, 'e_g');
M_.endo_names = char(M_.endo_names, 'interest');
M_.endo_names_tex = char(M_.endo_names_tex, 'interest');
M_.endo_names_long = char(M_.endo_names_long, 'interest');
M_.endo_names = char(M_.endo_names, 'inflation');
M_.endo_names_tex = char(M_.endo_names_tex, 'inflation');
M_.endo_names_long = char(M_.endo_names_long, 'inflation');
M_.endo_names = char(M_.endo_names, 'inflationq');
M_.endo_names_tex = char(M_.endo_names_tex, 'inflationq');
M_.endo_names_long = char(M_.endo_names_long, 'inflationq');
M_.endo_names = char(M_.endo_names, 'outputgap');
M_.endo_names_tex = char(M_.endo_names_tex, 'outputgap');
M_.endo_names_long = char(M_.endo_names_long, 'outputgap');
M_.endo_names = char(M_.endo_names, 'output');
M_.endo_names_tex = char(M_.endo_names_tex, 'output');
M_.endo_names_long = char(M_.endo_names_long, 'output');
M_.endo_names = char(M_.endo_names, 'fispol');
M_.endo_names_tex = char(M_.endo_names_tex, 'fispol');
M_.endo_names_long = char(M_.endo_names_long, 'fispol');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_89');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_89');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_89');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_93');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_93');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_93');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_97');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_97');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_97');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_124');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_124');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_124');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_128');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_128');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_128');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_132');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_132');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_132');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_159');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_159');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_159');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_163');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_163');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_163');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_167');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_167');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_167');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_34_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_34\_1');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_34_1');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_34_2');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_34\_2');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_34_2');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_72_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_72\_1');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_72_1');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_72_2');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_72\_2');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_72_2');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_72_3');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_72\_3');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_72_3');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_71_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_71\_1');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_71_1');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_71_2');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_71\_2');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_71_2');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_71_3');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_71\_3');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_71_3');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_68_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_68\_1');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_68_1');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_68_2');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_68\_2');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_68_2');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_68_3');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_68\_3');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_68_3');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_70_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_70\_1');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_70_1');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_70_2');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_70\_2');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_70_2');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_70_3');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_70\_3');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_70_3');
M_.endo_partitions = struct();
M_.param_names = 'cofintintb1';
M_.param_names_tex = 'cofintintb1';
M_.param_names_long = 'cofintintb1';
M_.param_names = char(M_.param_names, 'cofintintb2');
M_.param_names_tex = char(M_.param_names_tex, 'cofintintb2');
M_.param_names_long = char(M_.param_names_long, 'cofintintb2');
M_.param_names = char(M_.param_names, 'cofintintb3');
M_.param_names_tex = char(M_.param_names_tex, 'cofintintb3');
M_.param_names_long = char(M_.param_names_long, 'cofintintb3');
M_.param_names = char(M_.param_names, 'cofintintb4');
M_.param_names_tex = char(M_.param_names_tex, 'cofintintb4');
M_.param_names_long = char(M_.param_names_long, 'cofintintb4');
M_.param_names = char(M_.param_names, 'cofintinf0');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinf0');
M_.param_names_long = char(M_.param_names_long, 'cofintinf0');
M_.param_names = char(M_.param_names, 'cofintinfb1');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinfb1');
M_.param_names_long = char(M_.param_names_long, 'cofintinfb1');
M_.param_names = char(M_.param_names, 'cofintinfb2');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinfb2');
M_.param_names_long = char(M_.param_names_long, 'cofintinfb2');
M_.param_names = char(M_.param_names, 'cofintinfb3');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinfb3');
M_.param_names_long = char(M_.param_names_long, 'cofintinfb3');
M_.param_names = char(M_.param_names, 'cofintinfb4');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinfb4');
M_.param_names_long = char(M_.param_names_long, 'cofintinfb4');
M_.param_names = char(M_.param_names, 'cofintinff1');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinff1');
M_.param_names_long = char(M_.param_names_long, 'cofintinff1');
M_.param_names = char(M_.param_names, 'cofintinff2');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinff2');
M_.param_names_long = char(M_.param_names_long, 'cofintinff2');
M_.param_names = char(M_.param_names, 'cofintinff3');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinff3');
M_.param_names_long = char(M_.param_names_long, 'cofintinff3');
M_.param_names = char(M_.param_names, 'cofintinff4');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinff4');
M_.param_names_long = char(M_.param_names_long, 'cofintinff4');
M_.param_names = char(M_.param_names, 'cofintout');
M_.param_names_tex = char(M_.param_names_tex, 'cofintout');
M_.param_names_long = char(M_.param_names_long, 'cofintout');
M_.param_names = char(M_.param_names, 'cofintoutb1');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutb1');
M_.param_names_long = char(M_.param_names_long, 'cofintoutb1');
M_.param_names = char(M_.param_names, 'cofintoutb2');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutb2');
M_.param_names_long = char(M_.param_names_long, 'cofintoutb2');
M_.param_names = char(M_.param_names, 'cofintoutb3');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutb3');
M_.param_names_long = char(M_.param_names_long, 'cofintoutb3');
M_.param_names = char(M_.param_names, 'cofintoutb4');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutb4');
M_.param_names_long = char(M_.param_names_long, 'cofintoutb4');
M_.param_names = char(M_.param_names, 'cofintoutf1');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutf1');
M_.param_names_long = char(M_.param_names_long, 'cofintoutf1');
M_.param_names = char(M_.param_names, 'cofintoutf2');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutf2');
M_.param_names_long = char(M_.param_names_long, 'cofintoutf2');
M_.param_names = char(M_.param_names, 'cofintoutf3');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutf3');
M_.param_names_long = char(M_.param_names_long, 'cofintoutf3');
M_.param_names = char(M_.param_names, 'cofintoutf4');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutf4');
M_.param_names_long = char(M_.param_names_long, 'cofintoutf4');
M_.param_names = char(M_.param_names, 'cofintoutp');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutp');
M_.param_names_long = char(M_.param_names_long, 'cofintoutp');
M_.param_names = char(M_.param_names, 'cofintoutpb1');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpb1');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpb1');
M_.param_names = char(M_.param_names, 'cofintoutpb2');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpb2');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpb2');
M_.param_names = char(M_.param_names, 'cofintoutpb3');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpb3');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpb3');
M_.param_names = char(M_.param_names, 'cofintoutpb4');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpb4');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpb4');
M_.param_names = char(M_.param_names, 'cofintoutpf1');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpf1');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpf1');
M_.param_names = char(M_.param_names, 'cofintoutpf2');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpf2');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpf2');
M_.param_names = char(M_.param_names, 'cofintoutpf3');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpf3');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpf3');
M_.param_names = char(M_.param_names, 'cofintoutpf4');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpf4');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpf4');
M_.param_names = char(M_.param_names, 'std_r_');
M_.param_names_tex = char(M_.param_names_tex, 'std\_r\_');
M_.param_names_long = char(M_.param_names_long, 'std_r_');
M_.param_names = char(M_.param_names, 'std_r_quart');
M_.param_names_tex = char(M_.param_names_tex, 'std\_r\_quart');
M_.param_names_long = char(M_.param_names_long, 'std_r_quart');
M_.param_names = char(M_.param_names, 'coffispol');
M_.param_names_tex = char(M_.param_names_tex, 'coffispol');
M_.param_names_long = char(M_.param_names_long, 'coffispol');
M_.param_names = char(M_.param_names, 'betta');
M_.param_names_tex = char(M_.param_names_tex, 'betta');
M_.param_names_long = char(M_.param_names_long, 'betta');
M_.param_names = char(M_.param_names, 'sig');
M_.param_names_tex = char(M_.param_names_tex, 'sig');
M_.param_names_long = char(M_.param_names_long, 'sig');
M_.param_names = char(M_.param_names, 'hh');
M_.param_names_tex = char(M_.param_names_tex, 'hh');
M_.param_names_long = char(M_.param_names_long, 'hh');
M_.param_names = char(M_.param_names, 'varphi');
M_.param_names_tex = char(M_.param_names_tex, 'varphi');
M_.param_names_long = char(M_.param_names_long, 'varphi');
M_.param_names = char(M_.param_names, 'zetta');
M_.param_names_tex = char(M_.param_names_tex, 'zetta');
M_.param_names_long = char(M_.param_names_long, 'zetta');
M_.param_names = char(M_.param_names, 'theta');
M_.param_names_tex = char(M_.param_names_tex, 'theta');
M_.param_names_long = char(M_.param_names_long, 'theta');
M_.param_names = char(M_.param_names, 'alfa');
M_.param_names_tex = char(M_.param_names_tex, 'alfa');
M_.param_names_long = char(M_.param_names_long, 'alfa');
M_.param_names = char(M_.param_names, 'G_over_Y');
M_.param_names_tex = char(M_.param_names_tex, 'G\_over\_Y');
M_.param_names_long = char(M_.param_names_long, 'G_over_Y');
M_.param_names = char(M_.param_names, 'eta_i');
M_.param_names_tex = char(M_.param_names_tex, 'eta\_i');
M_.param_names_long = char(M_.param_names_long, 'eta_i');
M_.param_names = char(M_.param_names, 'epsilon');
M_.param_names_tex = char(M_.param_names_tex, 'epsilon');
M_.param_names_long = char(M_.param_names_long, 'epsilon');
M_.param_names = char(M_.param_names, 'gam');
M_.param_names_tex = char(M_.param_names_tex, 'gam');
M_.param_names_long = char(M_.param_names_long, 'gam');
M_.param_names = char(M_.param_names, 'gam_P');
M_.param_names_tex = char(M_.param_names_tex, 'gam\_P');
M_.param_names_long = char(M_.param_names_long, 'gam_P');
M_.param_names = char(M_.param_names, 'kappa_pi');
M_.param_names_tex = char(M_.param_names_tex, 'kappa\_pi');
M_.param_names_long = char(M_.param_names_long, 'kappa_pi');
M_.param_names = char(M_.param_names, 'kappa_y');
M_.param_names_tex = char(M_.param_names_tex, 'kappa\_y');
M_.param_names_long = char(M_.param_names_long, 'kappa_y');
M_.param_names = char(M_.param_names, 'rho_i');
M_.param_names_tex = char(M_.param_names_tex, 'rho\_i');
M_.param_names_long = char(M_.param_names_long, 'rho_i');
M_.param_names = char(M_.param_names, 'rho_ksi');
M_.param_names_tex = char(M_.param_names_tex, 'rho\_ksi');
M_.param_names_long = char(M_.param_names_long, 'rho_ksi');
M_.param_names = char(M_.param_names, 'sigma_ksi');
M_.param_names_tex = char(M_.param_names_tex, 'sigma\_ksi');
M_.param_names_long = char(M_.param_names_long, 'sigma_ksi');
M_.param_names = char(M_.param_names, 'rho_a');
M_.param_names_tex = char(M_.param_names_tex, 'rho\_a');
M_.param_names_long = char(M_.param_names_long, 'rho_a');
M_.param_names = char(M_.param_names, 'sigma_a');
M_.param_names_tex = char(M_.param_names_tex, 'sigma\_a');
M_.param_names_long = char(M_.param_names_long, 'sigma_a');
M_.param_names = char(M_.param_names, 'rho_g');
M_.param_names_tex = char(M_.param_names_tex, 'rho\_g');
M_.param_names_long = char(M_.param_names_long, 'rho_g');
M_.param_names = char(M_.param_names, 'sigma_g');
M_.param_names_tex = char(M_.param_names_tex, 'sigma\_g');
M_.param_names_long = char(M_.param_names_long, 'sigma_g');
M_.param_names = char(M_.param_names, 'sigma_Ne');
M_.param_names_tex = char(M_.param_names_tex, 'sigma\_Ne');
M_.param_names_long = char(M_.param_names_long, 'sigma_Ne');
M_.param_names = char(M_.param_names, 'sigma_i');
M_.param_names_tex = char(M_.param_names_tex, 'sigma\_i');
M_.param_names_long = char(M_.param_names_long, 'sigma_i');
M_.param_names = char(M_.param_names, 'rho_shock_psi');
M_.param_names_tex = char(M_.param_names_tex, 'rho\_shock\_psi');
M_.param_names_long = char(M_.param_names_long, 'rho_shock_psi');
M_.param_names = char(M_.param_names, 'sigma_psi');
M_.param_names_tex = char(M_.param_names_tex, 'sigma\_psi');
M_.param_names_long = char(M_.param_names_long, 'sigma_psi');
M_.param_names = char(M_.param_names, 'kappa');
M_.param_names_tex = char(M_.param_names_tex, 'kappa');
M_.param_names_long = char(M_.param_names_long, 'kappa');
M_.param_names = char(M_.param_names, 'tau');
M_.param_names_tex = char(M_.param_names_tex, 'tau');
M_.param_names_long = char(M_.param_names_long, 'tau');
M_.param_names = char(M_.param_names, 'omega');
M_.param_names_tex = char(M_.param_names_tex, 'omega');
M_.param_names_long = char(M_.param_names_long, 'omega');
M_.param_names = char(M_.param_names, 'lambda');
M_.param_names_tex = char(M_.param_names_tex, 'lambda');
M_.param_names_long = char(M_.param_names_long, 'lambda');
M_.param_names = char(M_.param_names, 'chi');
M_.param_names_tex = char(M_.param_names_tex, 'chi');
M_.param_names_long = char(M_.param_names_long, 'chi');
M_.param_names = char(M_.param_names, 'b');
M_.param_names_tex = char(M_.param_names_tex, 'b');
M_.param_names_long = char(M_.param_names_long, 'b');
M_.param_names = char(M_.param_names, 'delta_c');
M_.param_names_tex = char(M_.param_names_tex, 'delta\_c');
M_.param_names_long = char(M_.param_names_long, 'delta_c');
M_.param_names = char(M_.param_names, 'G_ss');
M_.param_names_tex = char(M_.param_names_tex, 'G\_ss');
M_.param_names_long = char(M_.param_names_long, 'G_ss');
M_.param_names = char(M_.param_names, 'I_ss');
M_.param_names_tex = char(M_.param_names_tex, 'I\_ss');
M_.param_names_long = char(M_.param_names_long, 'I_ss');
M_.param_names = char(M_.param_names, 'Pmf');
M_.param_names_tex = char(M_.param_names_tex, 'Pmf');
M_.param_names_long = char(M_.param_names_long, 'Pmf');
M_.param_names = char(M_.param_names, 'L_mom');
M_.param_names_tex = char(M_.param_names_tex, 'L\_mom');
M_.param_names_long = char(M_.param_names_long, 'L_mom');
M_.param_names = char(M_.param_names, 'RkmR_mom');
M_.param_names_tex = char(M_.param_names_tex, 'RkmR\_mom');
M_.param_names_long = char(M_.param_names_long, 'RkmR_mom');
M_.param_names = char(M_.param_names, 'phi_mom');
M_.param_names_tex = char(M_.param_names_tex, 'phi\_mom');
M_.param_names_long = char(M_.param_names_long, 'phi_mom');
M_.param_names = char(M_.param_names, 'L0');
M_.param_names_tex = char(M_.param_names_tex, 'L0');
M_.param_names_long = char(M_.param_names_long, 'L0');
M_.param_names = char(M_.param_names, 'K0');
M_.param_names_tex = char(M_.param_names_tex, 'K0');
M_.param_names_long = char(M_.param_names_long, 'K0');
M_.param_names = char(M_.param_names, 'chi0');
M_.param_names_tex = char(M_.param_names_tex, 'chi0');
M_.param_names_long = char(M_.param_names_long, 'chi0');
M_.param_names = char(M_.param_names, 'lambda0');
M_.param_names_tex = char(M_.param_names_tex, 'lambda0');
M_.param_names_long = char(M_.param_names_long, 'lambda0');
M_.param_names = char(M_.param_names, 'omega0');
M_.param_names_tex = char(M_.param_names_tex, 'omega0');
M_.param_names_long = char(M_.param_names_long, 'omega0');
M_.param_names = char(M_.param_names, 'deltai');
M_.param_names_tex = char(M_.param_names_tex, 'deltai');
M_.param_names_long = char(M_.param_names_long, 'deltai');
M_.param_names = char(M_.param_names, 'Y_ss');
M_.param_names_tex = char(M_.param_names_tex, 'Y\_ss');
M_.param_names_long = char(M_.param_names_long, 'Y_ss');
M_.param_partitions = struct();
M_.exo_det_nbr = 0;
M_.exo_nbr = 5;
M_.endo_nbr = 97;
M_.param_nbr = 79;
M_.orig_endo_nbr = 74;
M_.aux_vars(1).endo_index = 75;
M_.aux_vars(1).type = 0;
M_.aux_vars(2).endo_index = 76;
M_.aux_vars(2).type = 0;
M_.aux_vars(3).endo_index = 77;
M_.aux_vars(3).type = 0;
M_.aux_vars(4).endo_index = 78;
M_.aux_vars(4).type = 0;
M_.aux_vars(5).endo_index = 79;
M_.aux_vars(5).type = 0;
M_.aux_vars(6).endo_index = 80;
M_.aux_vars(6).type = 0;
M_.aux_vars(7).endo_index = 81;
M_.aux_vars(7).type = 0;
M_.aux_vars(8).endo_index = 82;
M_.aux_vars(8).type = 0;
M_.aux_vars(9).endo_index = 83;
M_.aux_vars(9).type = 0;
M_.aux_vars(10).endo_index = 84;
M_.aux_vars(10).type = 1;
M_.aux_vars(10).orig_index = 35;
M_.aux_vars(10).orig_lead_lag = -1;
M_.aux_vars(11).endo_index = 85;
M_.aux_vars(11).type = 1;
M_.aux_vars(11).orig_index = 35;
M_.aux_vars(11).orig_lead_lag = -2;
M_.aux_vars(12).endo_index = 86;
M_.aux_vars(12).type = 1;
M_.aux_vars(12).orig_index = 73;
M_.aux_vars(12).orig_lead_lag = -1;
M_.aux_vars(13).endo_index = 87;
M_.aux_vars(13).type = 1;
M_.aux_vars(13).orig_index = 73;
M_.aux_vars(13).orig_lead_lag = -2;
M_.aux_vars(14).endo_index = 88;
M_.aux_vars(14).type = 1;
M_.aux_vars(14).orig_index = 73;
M_.aux_vars(14).orig_lead_lag = -3;
M_.aux_vars(15).endo_index = 89;
M_.aux_vars(15).type = 1;
M_.aux_vars(15).orig_index = 72;
M_.aux_vars(15).orig_lead_lag = -1;
M_.aux_vars(16).endo_index = 90;
M_.aux_vars(16).type = 1;
M_.aux_vars(16).orig_index = 72;
M_.aux_vars(16).orig_lead_lag = -2;
M_.aux_vars(17).endo_index = 91;
M_.aux_vars(17).type = 1;
M_.aux_vars(17).orig_index = 72;
M_.aux_vars(17).orig_lead_lag = -3;
M_.aux_vars(18).endo_index = 92;
M_.aux_vars(18).type = 1;
M_.aux_vars(18).orig_index = 69;
M_.aux_vars(18).orig_lead_lag = -1;
M_.aux_vars(19).endo_index = 93;
M_.aux_vars(19).type = 1;
M_.aux_vars(19).orig_index = 69;
M_.aux_vars(19).orig_lead_lag = -2;
M_.aux_vars(20).endo_index = 94;
M_.aux_vars(20).type = 1;
M_.aux_vars(20).orig_index = 69;
M_.aux_vars(20).orig_lead_lag = -3;
M_.aux_vars(21).endo_index = 95;
M_.aux_vars(21).type = 1;
M_.aux_vars(21).orig_index = 71;
M_.aux_vars(21).orig_lead_lag = -1;
M_.aux_vars(22).endo_index = 96;
M_.aux_vars(22).type = 1;
M_.aux_vars(22).orig_index = 71;
M_.aux_vars(22).orig_lead_lag = -2;
M_.aux_vars(23).endo_index = 97;
M_.aux_vars(23).type = 1;
M_.aux_vars(23).orig_index = 71;
M_.aux_vars(23).orig_lead_lag = -3;
M_.Sigma_e = zeros(5, 5);
M_.Correlation_matrix = eye(5, 5);
M_.H = 0;
M_.Correlation_matrix_ME = 1;
M_.sigma_e_is_diagonal = 1;
M_.det_shocks = [];
options_.block=0;
options_.bytecode=0;
options_.use_dll=0;
M_.hessian_eq_zero = 0;
erase_compiled_function('NK_GK11_static');
erase_compiled_function('NK_GK11_dynamic');
M_.orig_eq_nbr = 74;
M_.eq_nbr = 97;
M_.ramsey_eq_nbr = 0;
M_.set_auxiliary_variables = exist(['./' M_.fname '_set_auxiliary_variables.m'], 'file') == 2;
M_.lead_lag_incidence = [
 0 40 0;
 0 41 0;
 1 42 0;
 0 43 0;
 0 44 0;
 0 45 0;
 2 46 137;
 0 47 0;
 3 48 0;
 4 49 0;
 0 50 138;
 0 51 139;
 5 52 0;
 6 53 0;
 0 54 0;
 0 55 0;
 0 56 140;
 0 57 141;
 7 58 0;
 0 59 142;
 0 60 143;
 0 61 0;
 0 62 0;
 0 63 0;
 0 64 0;
 0 65 0;
 8 66 0;
 0 67 144;
 0 68 145;
 0 69 0;
 0 70 0;
 0 71 0;
 9 72 146;
 0 73 147;
 10 74 148;
 0 75 0;
 0 76 0;
 0 77 0;
 11 78 0;
 0 79 0;
 0 80 0;
 0 81 0;
 12 82 149;
 0 83 0;
 13 84 0;
 14 85 0;
 0 86 150;
 0 87 151;
 15 88 0;
 16 89 0;
 0 90 0;
 0 91 0;
 0 92 152;
 0 93 153;
 17 94 0;
 0 95 154;
 0 96 155;
 0 97 0;
 0 98 0;
 0 99 0;
 0 100 0;
 0 101 0;
 18 102 156;
 0 103 157;
 19 104 0;
 20 105 0;
 21 106 0;
 0 107 0;
 22 108 0;
 0 109 0;
 23 110 158;
 24 111 159;
 25 112 160;
 0 113 0;
 0 114 161;
 0 115 162;
 0 116 163;
 0 117 164;
 0 118 165;
 0 119 166;
 0 120 167;
 0 121 168;
 0 122 169;
 26 123 0;
 27 124 0;
 28 125 0;
 29 126 0;
 30 127 0;
 31 128 0;
 32 129 0;
 33 130 0;
 34 131 0;
 35 132 0;
 36 133 0;
 37 134 0;
 38 135 0;
 39 136 0;]';
M_.nstatic = 33;
M_.nfwrd   = 25;
M_.npred   = 31;
M_.nboth   = 8;
M_.nsfwrd   = 33;
M_.nspred   = 39;
M_.ndynamic   = 64;
M_.equations_tags = {
};
M_.static_and_dynamic_models_differ = 0;
M_.exo_names_orig_ord = [1:5];
M_.maximum_lag = 1;
M_.maximum_lead = 1;
M_.maximum_endo_lag = 1;
M_.maximum_endo_lead = 1;
oo_.steady_state = zeros(97, 1);
M_.maximum_exo_lag = 0;
M_.maximum_exo_lead = 0;
oo_.exo_steady_state = zeros(5, 1);
M_.params = NaN(79, 1);
M_.NNZDerivatives = [359; 581; -1];
M_.params( 35 ) = 0.99;
betta = M_.params( 35 );
M_.params( 36 ) = 1;
sig = M_.params( 36 );
M_.params( 37 ) = 0.815;
hh = M_.params( 37 );
M_.params( 75 ) = 3.4;
chi0 = M_.params( 75 );
M_.params( 38 ) = 0.276;
varphi = M_.params( 38 );
M_.params( 39 ) = 7.2;
zetta = M_.params( 39 );
M_.params( 76 ) = 0.3815;
lambda0 = M_.params( 76 );
M_.params( 77 ) = 0.002;
omega0 = M_.params( 77 );
M_.params( 40 ) = 0.97155955;
theta = M_.params( 40 );
M_.params( 41 ) = 0.33;
alfa = M_.params( 41 );
M_.params( 78 ) = 0.025;
deltai = M_.params( 78 );
M_.params( 42 ) = 0.2;
G_over_Y = M_.params( 42 );
M_.params( 43 ) = 1.728;
eta_i = M_.params( 43 );
M_.params( 44 ) = 4.167;
epsilon = M_.params( 44 );
M_.params( 45 ) = 0.779;
gam = M_.params( 45 );
M_.params( 46 ) = 0.241;
gam_P = M_.params( 46 );
M_.params( 69 ) = log((M_.params(44)-1)/M_.params(44));
Pmf = M_.params( 69 );
M_.params( 49 ) = 0;
rho_i = M_.params( 49 );
M_.params( 47 ) = 1.5;
kappa_pi = M_.params( 47 );
M_.params( 48 ) = (-0.125);
kappa_y = M_.params( 48 );
M_.params( 51 ) = 0.05;
sigma_ksi = M_.params( 51 );
M_.params( 50 ) = 0.66;
rho_ksi = M_.params( 50 );
M_.params( 53 ) = 0.01;
sigma_a = M_.params( 53 );
M_.params( 52 ) = 0.95;
rho_a = M_.params( 52 );
M_.params( 55 ) = 0.01;
sigma_g = M_.params( 55 );
M_.params( 54 ) = 0.95;
rho_g = M_.params( 54 );
M_.params( 56 ) = 0.01;
sigma_Ne = M_.params( 56 );
M_.params( 57 ) = 0.01;
sigma_i = M_.params( 57 );
M_.params( 58 ) = 0.66;
rho_shock_psi = M_.params( 58 );
M_.params( 59 ) = 0.072;
sigma_psi = M_.params( 59 );
M_.params( 60 ) = 10.00000000;
kappa = M_.params( 60 );
M_.params( 61 ) = 0.00100000;
tau = M_.params( 61 );
M_.params( 78 ) = 0.025;
deltai = M_.params( 78 );
M_.params( 70 ) = 0.5;
L_mom = M_.params( 70 );
M_.params( 71 ) = 0.0025;
RkmR_mom = M_.params( 71 );
M_.params( 72 ) = 4;
phi_mom = M_.params( 72 );
M_.params( 60 ) = 10;
kappa = M_.params( 60 );
M_.params( 61 ) = 0.001;
tau = M_.params( 61 );
M_.params( 73 ) = M_.params(70);
L0 = M_.params( 73 );
M_.params( 74 ) = 9.5;
K0 = M_.params( 74 );
thispath = cd;                                                           
cd('..');                                                                
load policy_param.mat;                                                   
for i=1:33                                                               
deep_parameter_name = M_.param_names(i,:);                           
eval(['M_.params(i)  = ' deep_parameter_name ' ;'])                  
end  
M_.params( 32 ) = 100;
std_r_ = M_.params( 32 );
cd(thispath);  
M_.params( 34 ) = 1/M_.params(42);
coffispol = M_.params( 34 );
%
% SHOCKS instructions
%
M_.exo_det_length = 0;
M_.Sigma_e(1, 1) = 0;
M_.Sigma_e(2, 2) = 0;
M_.Sigma_e(3, 3) = 0;
M_.Sigma_e(5, 5) = (M_.params(55)/M_.params(34))^2;
save('NK_GK11_results.mat', 'oo_', 'M_', 'options_');
if exist('estim_params_', 'var') == 1
  save('NK_GK11_results.mat', 'estim_params_', '-append');
end
if exist('bayestopt_', 'var') == 1
  save('NK_GK11_results.mat', 'bayestopt_', '-append');
end
if exist('dataset_', 'var') == 1
  save('NK_GK11_results.mat', 'dataset_', '-append');
end
if exist('estimation_info', 'var') == 1
  save('NK_GK11_results.mat', 'estimation_info', '-append');
end
if exist('dataset_info', 'var') == 1
  save('NK_GK11_results.mat', 'dataset_info', '-append');
end
if exist('oo_recursive_', 'var') == 1
  save('NK_GK11_results.mat', 'oo_recursive_', '-append');
end


disp(['Total computing time : ' dynsec2hms(toc(tic0)) ]);
if ~isempty(lastwarn)
  disp('Note: warning(s) encountered in MATLAB/Octave code')
end
diary off
