%
% Status : main Dynare file
%
% Warning : this file is generated automatically by Dynare
%           from model file (.mod)

if isoctave || matlab_ver_less_than('8.6')
    clear all
else
    clearvars -global
    clear_persistent_variables(fileparts(which('dynare')), false)
end
tic0 = tic;
% Save empty dates and dseries objects in memory.
dates('initialize');
dseries('initialize');
% Define global variables.
global M_ options_ oo_ estim_params_ bayestopt_ dataset_ dataset_info estimation_info ys0_ ex0_
options_ = [];
M_.fname = 'EA_QUEST3';
M_.dynare_version = '4.5.6';
oo_.dynare_version = '4.5.6';
options_.dynare_version = '4.5.6';
%
% Some global variables initialization
%
global_initialization;
diary off;
diary('EA_QUEST3.log');
M_.exo_names = 'E_EPS_C';
M_.exo_names_tex = 'E\_EPS\_C';
M_.exo_names_long = 'E_EPS_C';
M_.exo_names = char(M_.exo_names, 'E_EPS_ETA');
M_.exo_names_tex = char(M_.exo_names_tex, 'E\_EPS\_ETA');
M_.exo_names_long = char(M_.exo_names_long, 'E_EPS_ETA');
M_.exo_names = char(M_.exo_names, 'E_EPS_ETAM');
M_.exo_names_tex = char(M_.exo_names_tex, 'E\_EPS\_ETAM');
M_.exo_names_long = char(M_.exo_names_long, 'E_EPS_ETAM');
M_.exo_names = char(M_.exo_names, 'E_EPS_ETAX');
M_.exo_names_tex = char(M_.exo_names_tex, 'E\_EPS\_ETAX');
M_.exo_names_long = char(M_.exo_names_long, 'E_EPS_ETAX');
M_.exo_names = char(M_.exo_names, 'E_EPS_EX');
M_.exo_names_tex = char(M_.exo_names_tex, 'E\_EPS\_EX');
M_.exo_names_long = char(M_.exo_names_long, 'E_EPS_EX');
M_.exo_names = char(M_.exo_names, 'E_EPS_IG');
M_.exo_names_tex = char(M_.exo_names_tex, 'E\_EPS\_IG');
M_.exo_names_long = char(M_.exo_names_long, 'E_EPS_IG');
M_.exo_names = char(M_.exo_names, 'E_EPS_INOMW');
M_.exo_names_tex = char(M_.exo_names_tex, 'E\_EPS\_INOMW');
M_.exo_names_long = char(M_.exo_names_long, 'E_EPS_INOMW');
M_.exo_names = char(M_.exo_names, 'E_EPS_L');
M_.exo_names_tex = char(M_.exo_names_tex, 'E\_EPS\_L');
M_.exo_names_long = char(M_.exo_names_long, 'E_EPS_L');
M_.exo_names = char(M_.exo_names, 'E_EPS_LOL');
M_.exo_names_tex = char(M_.exo_names_tex, 'E\_EPS\_LOL');
M_.exo_names_long = char(M_.exo_names_long, 'E_EPS_LOL');
M_.exo_names = char(M_.exo_names, 'E_EPS_M');
M_.exo_names_tex = char(M_.exo_names_tex, 'E\_EPS\_M');
M_.exo_names_long = char(M_.exo_names_long, 'E_EPS_M');
M_.exo_names = char(M_.exo_names, 'E_EPS_PPI');
M_.exo_names_tex = char(M_.exo_names_tex, 'E\_EPS\_PPI');
M_.exo_names_long = char(M_.exo_names_long, 'E_EPS_PPI');
M_.exo_names = char(M_.exo_names, 'E_EPS_PW');
M_.exo_names_tex = char(M_.exo_names_tex, 'E\_EPS\_PW');
M_.exo_names_long = char(M_.exo_names_long, 'E_EPS_PW');
M_.exo_names = char(M_.exo_names, 'E_EPS_RPREME');
M_.exo_names_tex = char(M_.exo_names_tex, 'E\_EPS\_RPREME');
M_.exo_names_long = char(M_.exo_names_long, 'E_EPS_RPREME');
M_.exo_names = char(M_.exo_names, 'E_EPS_RPREMK');
M_.exo_names_tex = char(M_.exo_names_tex, 'E\_EPS\_RPREMK');
M_.exo_names_long = char(M_.exo_names_long, 'E_EPS_RPREMK');
M_.exo_names = char(M_.exo_names, 'E_EPS_TR');
M_.exo_names_tex = char(M_.exo_names_tex, 'E\_EPS\_TR');
M_.exo_names_long = char(M_.exo_names_long, 'E_EPS_TR');
M_.exo_names = char(M_.exo_names, 'E_EPS_W');
M_.exo_names_tex = char(M_.exo_names_tex, 'E\_EPS\_W');
M_.exo_names_long = char(M_.exo_names_long, 'E_EPS_W');
M_.exo_names = char(M_.exo_names, 'E_EPS_Y');
M_.exo_names_tex = char(M_.exo_names_tex, 'E\_EPS\_Y');
M_.exo_names_long = char(M_.exo_names_long, 'E_EPS_Y');
M_.exo_names = char(M_.exo_names, 'E_EPS_YW');
M_.exo_names_tex = char(M_.exo_names_tex, 'E\_EPS\_YW');
M_.exo_names_long = char(M_.exo_names_long, 'E_EPS_YW');
M_.exo_names = char(M_.exo_names, 'interest_');
M_.exo_names_tex = char(M_.exo_names_tex, 'interest\_');
M_.exo_names_long = char(M_.exo_names_long, 'interest_');
M_.exo_names = char(M_.exo_names, 'fiscal_');
M_.exo_names_tex = char(M_.exo_names_tex, 'fiscal\_');
M_.exo_names_long = char(M_.exo_names_long, 'fiscal_');
M_.endo_names = 'E_BGYN';
M_.endo_names_tex = 'E\_BGYN';
M_.endo_names_long = 'E_BGYN';
M_.endo_names = char(M_.endo_names, 'E_BWRY');
M_.endo_names_tex = char(M_.endo_names_tex, 'E\_BWRY');
M_.endo_names_long = char(M_.endo_names_long, 'E_BWRY');
M_.endo_names = char(M_.endo_names, 'E_CLCSN');
M_.endo_names_tex = char(M_.endo_names_tex, 'E\_CLCSN');
M_.endo_names_long = char(M_.endo_names_long, 'E_CLCSN');
M_.endo_names = char(M_.endo_names, 'E_DBGYN');
M_.endo_names_tex = char(M_.endo_names_tex, 'E\_DBGYN');
M_.endo_names_long = char(M_.endo_names_long, 'E_DBGYN');
M_.endo_names = char(M_.endo_names, 'E_LER');
M_.endo_names_tex = char(M_.endo_names_tex, 'E\_LER');
M_.endo_names_long = char(M_.endo_names_long, 'E_LER');
M_.endo_names = char(M_.endo_names, 'E_ETA');
M_.endo_names_tex = char(M_.endo_names_tex, 'E\_ETA');
M_.endo_names_long = char(M_.endo_names_long, 'E_ETA');
M_.endo_names = char(M_.endo_names, 'E_GC');
M_.endo_names_tex = char(M_.endo_names_tex, 'E\_GC');
M_.endo_names_long = char(M_.endo_names_long, 'E_GC');
M_.endo_names = char(M_.endo_names, 'E_GCL');
M_.endo_names_tex = char(M_.endo_names_tex, 'E\_GCL');
M_.endo_names_long = char(M_.endo_names_long, 'E_GCL');
M_.endo_names = char(M_.endo_names, 'E_GCLC');
M_.endo_names_tex = char(M_.endo_names_tex, 'E\_GCLC');
M_.endo_names_long = char(M_.endo_names_long, 'E_GCLC');
M_.endo_names = char(M_.endo_names, 'E_GCNLC');
M_.endo_names_tex = char(M_.endo_names_tex, 'E\_GCNLC');
M_.endo_names_long = char(M_.endo_names_long, 'E_GCNLC');
M_.endo_names = char(M_.endo_names, 'E_GE');
M_.endo_names_tex = char(M_.endo_names_tex, 'E\_GE');
M_.endo_names_long = char(M_.endo_names_long, 'E_GE');
M_.endo_names = char(M_.endo_names, 'E_GEX');
M_.endo_names_tex = char(M_.endo_names_tex, 'E\_GEX');
M_.endo_names_long = char(M_.endo_names_long, 'E_GEX');
M_.endo_names = char(M_.endo_names, 'E_GEXL');
M_.endo_names_tex = char(M_.endo_names_tex, 'E\_GEXL');
M_.endo_names_long = char(M_.endo_names_long, 'E_GEXL');
M_.endo_names = char(M_.endo_names, 'E_GG');
M_.endo_names_tex = char(M_.endo_names_tex, 'E\_GG');
M_.endo_names_long = char(M_.endo_names_long, 'E_GG');
M_.endo_names = char(M_.endo_names, 'E_GGL');
M_.endo_names_tex = char(M_.endo_names_tex, 'E\_GGL');
M_.endo_names_long = char(M_.endo_names_long, 'E_GGL');
M_.endo_names = char(M_.endo_names, 'E_GI');
M_.endo_names_tex = char(M_.endo_names_tex, 'E\_GI');
M_.endo_names_long = char(M_.endo_names_long, 'E_GI');
M_.endo_names = char(M_.endo_names, 'E_GIG');
M_.endo_names_tex = char(M_.endo_names_tex, 'E\_GIG');
M_.endo_names_long = char(M_.endo_names_long, 'E_GIG');
M_.endo_names = char(M_.endo_names, 'E_GIL');
M_.endo_names_tex = char(M_.endo_names_tex, 'E\_GIL');
M_.endo_names_long = char(M_.endo_names_long, 'E_GIL');
M_.endo_names = char(M_.endo_names, 'E_GIM');
M_.endo_names_tex = char(M_.endo_names_tex, 'E\_GIM');
M_.endo_names_long = char(M_.endo_names_long, 'E_GIM');
M_.endo_names = char(M_.endo_names, 'E_GIML');
M_.endo_names_tex = char(M_.endo_names_tex, 'E\_GIML');
M_.endo_names_long = char(M_.endo_names_long, 'E_GIML');
M_.endo_names = char(M_.endo_names, 'E_GK');
M_.endo_names_tex = char(M_.endo_names_tex, 'E\_GK');
M_.endo_names_long = char(M_.endo_names_long, 'E_GK');
M_.endo_names = char(M_.endo_names, 'E_GKG');
M_.endo_names_tex = char(M_.endo_names_tex, 'E\_GKG');
M_.endo_names_long = char(M_.endo_names_long, 'E_GKG');
M_.endo_names = char(M_.endo_names, 'E_GL');
M_.endo_names_tex = char(M_.endo_names_tex, 'E\_GL');
M_.endo_names_long = char(M_.endo_names_long, 'E_GL');
M_.endo_names = char(M_.endo_names, 'E_GSN');
M_.endo_names_tex = char(M_.endo_names_tex, 'E\_GSN');
M_.endo_names_long = char(M_.endo_names_long, 'E_GSN');
M_.endo_names = char(M_.endo_names, 'E_GTAX');
M_.endo_names_tex = char(M_.endo_names_tex, 'E\_GTAX');
M_.endo_names_long = char(M_.endo_names_long, 'E_GTAX');
M_.endo_names = char(M_.endo_names, 'E_GTFP');
M_.endo_names_tex = char(M_.endo_names_tex, 'E\_GTFP');
M_.endo_names_long = char(M_.endo_names_long, 'E_GTFP');
M_.endo_names = char(M_.endo_names, 'E_GTFPUCAP');
M_.endo_names_tex = char(M_.endo_names_tex, 'E\_GTFPUCAP');
M_.endo_names_long = char(M_.endo_names_long, 'E_GTFPUCAP');
M_.endo_names = char(M_.endo_names, 'E_GTR');
M_.endo_names_tex = char(M_.endo_names_tex, 'E\_GTR');
M_.endo_names_long = char(M_.endo_names_long, 'E_GTR');
M_.endo_names = char(M_.endo_names, 'E_GUC');
M_.endo_names_tex = char(M_.endo_names_tex, 'E\_GUC');
M_.endo_names_long = char(M_.endo_names_long, 'E_GUC');
M_.endo_names = char(M_.endo_names, 'E_GUCAP');
M_.endo_names_tex = char(M_.endo_names_tex, 'E\_GUCAP');
M_.endo_names_long = char(M_.endo_names_long, 'E_GUCAP');
M_.endo_names = char(M_.endo_names, 'E_GWRY');
M_.endo_names_tex = char(M_.endo_names_tex, 'E\_GWRY');
M_.endo_names_long = char(M_.endo_names_long, 'E_GWRY');
M_.endo_names = char(M_.endo_names, 'E_GY');
M_.endo_names_tex = char(M_.endo_names_tex, 'E\_GY');
M_.endo_names_long = char(M_.endo_names_long, 'E_GY');
M_.endo_names = char(M_.endo_names, 'E_GYL');
M_.endo_names_tex = char(M_.endo_names_tex, 'E\_GYL');
M_.endo_names_long = char(M_.endo_names_long, 'E_GYL');
M_.endo_names = char(M_.endo_names, 'E_GYPOT');
M_.endo_names_tex = char(M_.endo_names_tex, 'E\_GYPOT');
M_.endo_names_long = char(M_.endo_names_long, 'E_GYPOT');
M_.endo_names = char(M_.endo_names, 'E_GYW');
M_.endo_names_tex = char(M_.endo_names_tex, 'E\_GYW');
M_.endo_names_long = char(M_.endo_names_long, 'E_GYW');
M_.endo_names = char(M_.endo_names, 'E_INOM');
M_.endo_names_tex = char(M_.endo_names_tex, 'E\_INOM');
M_.endo_names_long = char(M_.endo_names_long, 'E_INOM');
M_.endo_names = char(M_.endo_names, 'E_INOMW');
M_.endo_names_tex = char(M_.endo_names_tex, 'E\_INOMW');
M_.endo_names_long = char(M_.endo_names_long, 'E_INOMW');
M_.endo_names = char(M_.endo_names, 'E_LL');
M_.endo_names_tex = char(M_.endo_names_tex, 'E\_LL');
M_.endo_names_long = char(M_.endo_names_long, 'E_LL');
M_.endo_names = char(M_.endo_names, 'E_LL0');
M_.endo_names_tex = char(M_.endo_names_tex, 'E\_LL0');
M_.endo_names_long = char(M_.endo_names_long, 'E_LL0');
M_.endo_names = char(M_.endo_names, 'E_LBGYN');
M_.endo_names_tex = char(M_.endo_names_tex, 'E\_LBGYN');
M_.endo_names_long = char(M_.endo_names_long, 'E_LBGYN');
M_.endo_names = char(M_.endo_names, 'E_LCSN');
M_.endo_names_tex = char(M_.endo_names_tex, 'E\_LCSN');
M_.endo_names_long = char(M_.endo_names_long, 'E_LCSN');
M_.endo_names = char(M_.endo_names, 'E_LCLCSN');
M_.endo_names_tex = char(M_.endo_names_tex, 'E\_LCLCSN');
M_.endo_names_long = char(M_.endo_names_long, 'E_LCLCSN');
M_.endo_names = char(M_.endo_names, 'E_LCNLCSN');
M_.endo_names_tex = char(M_.endo_names_tex, 'E\_LCNLCSN');
M_.endo_names_long = char(M_.endo_names_long, 'E_LCNLCSN');
M_.endo_names = char(M_.endo_names, 'E_LEXYN');
M_.endo_names_tex = char(M_.endo_names_tex, 'E\_LEXYN');
M_.endo_names_long = char(M_.endo_names_long, 'E_LEXYN');
M_.endo_names = char(M_.endo_names, 'E_LGSN');
M_.endo_names_tex = char(M_.endo_names_tex, 'E\_LGSN');
M_.endo_names_long = char(M_.endo_names_long, 'E_LGSN');
M_.endo_names = char(M_.endo_names, 'E_LIGSN');
M_.endo_names_tex = char(M_.endo_names_tex, 'E\_LIGSN');
M_.endo_names_long = char(M_.endo_names_long, 'E_LIGSN');
M_.endo_names = char(M_.endo_names, 'E_LIMYN');
M_.endo_names_tex = char(M_.endo_names_tex, 'E\_LIMYN');
M_.endo_names_long = char(M_.endo_names_long, 'E_LIMYN');
M_.endo_names = char(M_.endo_names, 'E_LIK');
M_.endo_names_tex = char(M_.endo_names_tex, 'E\_LIK');
M_.endo_names_long = char(M_.endo_names_long, 'E_LIK');
M_.endo_names = char(M_.endo_names, 'E_LIKG');
M_.endo_names_tex = char(M_.endo_names_tex, 'E\_LIKG');
M_.endo_names_long = char(M_.endo_names_long, 'E_LIKG');
M_.endo_names = char(M_.endo_names, 'E_LISN');
M_.endo_names_tex = char(M_.endo_names_tex, 'E\_LISN');
M_.endo_names_long = char(M_.endo_names_long, 'E_LISN');
M_.endo_names = char(M_.endo_names, 'E_LOL');
M_.endo_names_tex = char(M_.endo_names_tex, 'E\_LOL');
M_.endo_names_long = char(M_.endo_names_long, 'E_LOL');
M_.endo_names = char(M_.endo_names, 'E_LPCP');
M_.endo_names_tex = char(M_.endo_names_tex, 'E\_LPCP');
M_.endo_names_long = char(M_.endo_names_long, 'E_LPCP');
M_.endo_names = char(M_.endo_names, 'E_LPMP');
M_.endo_names_tex = char(M_.endo_names_tex, 'E\_LPMP');
M_.endo_names_long = char(M_.endo_names_long, 'E_LPMP');
M_.endo_names = char(M_.endo_names, 'E_LPXP');
M_.endo_names_tex = char(M_.endo_names_tex, 'E\_LPXP');
M_.endo_names_long = char(M_.endo_names_long, 'E_LPXP');
M_.endo_names = char(M_.endo_names, 'E_LTRYN');
M_.endo_names_tex = char(M_.endo_names_tex, 'E\_LTRYN');
M_.endo_names_long = char(M_.endo_names_long, 'E_LTRYN');
M_.endo_names = char(M_.endo_names, 'E_LUCYN');
M_.endo_names_tex = char(M_.endo_names_tex, 'E\_LUCYN');
M_.endo_names_long = char(M_.endo_names_long, 'E_LUCYN');
M_.endo_names = char(M_.endo_names, 'E_LUCLCYN');
M_.endo_names_tex = char(M_.endo_names_tex, 'E\_LUCLCYN');
M_.endo_names_long = char(M_.endo_names_long, 'E_LUCLCYN');
M_.endo_names = char(M_.endo_names, 'E_LYGAP');
M_.endo_names_tex = char(M_.endo_names_tex, 'E\_LYGAP');
M_.endo_names_long = char(M_.endo_names_long, 'E_LYGAP');
M_.endo_names = char(M_.endo_names, 'E_LYKPPI');
M_.endo_names_tex = char(M_.endo_names_tex, 'E\_LYKPPI');
M_.endo_names_long = char(M_.endo_names_long, 'E_LYKPPI');
M_.endo_names = char(M_.endo_names, 'E_LYWR');
M_.endo_names_tex = char(M_.endo_names_tex, 'E\_LYWR');
M_.endo_names_long = char(M_.endo_names_long, 'E_LYWR');
M_.endo_names = char(M_.endo_names, 'E_LYWY');
M_.endo_names_tex = char(M_.endo_names_tex, 'E\_LYWY');
M_.endo_names_long = char(M_.endo_names_long, 'E_LYWY');
M_.endo_names = char(M_.endo_names, 'E_MRY');
M_.endo_names_tex = char(M_.endo_names_tex, 'E\_MRY');
M_.endo_names_long = char(M_.endo_names_long, 'E_MRY');
M_.endo_names = char(M_.endo_names, 'E_PHI');
M_.endo_names_tex = char(M_.endo_names_tex, 'E\_PHI');
M_.endo_names_long = char(M_.endo_names_long, 'E_PHI');
M_.endo_names = char(M_.endo_names, 'E_PHIC');
M_.endo_names_tex = char(M_.endo_names_tex, 'E\_PHIC');
M_.endo_names_long = char(M_.endo_names_long, 'E_PHIC');
M_.endo_names = char(M_.endo_names, 'E_PHIPI');
M_.endo_names_tex = char(M_.endo_names_tex, 'E\_PHIPI');
M_.endo_names_long = char(M_.endo_names_long, 'E_PHIPI');
M_.endo_names = char(M_.endo_names, 'E_PHIM');
M_.endo_names_tex = char(M_.endo_names_tex, 'E\_PHIM');
M_.endo_names_long = char(M_.endo_names_long, 'E_PHIM');
M_.endo_names = char(M_.endo_names, 'E_PHIML');
M_.endo_names_tex = char(M_.endo_names_tex, 'E\_PHIML');
M_.endo_names_long = char(M_.endo_names_long, 'E_PHIML');
M_.endo_names = char(M_.endo_names, 'E_PHIW');
M_.endo_names_tex = char(M_.endo_names_tex, 'E\_PHIW');
M_.endo_names_long = char(M_.endo_names_long, 'E_PHIW');
M_.endo_names = char(M_.endo_names, 'E_PHIX');
M_.endo_names_tex = char(M_.endo_names_tex, 'E\_PHIX');
M_.endo_names_long = char(M_.endo_names_long, 'E_PHIX');
M_.endo_names = char(M_.endo_names, 'E_PHIXL');
M_.endo_names_tex = char(M_.endo_names_tex, 'E\_PHIXL');
M_.endo_names_long = char(M_.endo_names_long, 'E_PHIXL');
M_.endo_names = char(M_.endo_names, 'E_Q');
M_.endo_names_tex = char(M_.endo_names_tex, 'E\_Q');
M_.endo_names_long = char(M_.endo_names_long, 'E_Q');
M_.endo_names = char(M_.endo_names, 'E_R');
M_.endo_names_tex = char(M_.endo_names_tex, 'E\_R');
M_.endo_names_long = char(M_.endo_names_long, 'E_R');
M_.endo_names = char(M_.endo_names, 'E_TAXYN');
M_.endo_names_tex = char(M_.endo_names_tex, 'E\_TAXYN');
M_.endo_names_long = char(M_.endo_names_long, 'E_TAXYN');
M_.endo_names = char(M_.endo_names, 'E_TBYN');
M_.endo_names_tex = char(M_.endo_names_tex, 'E\_TBYN');
M_.endo_names_long = char(M_.endo_names_long, 'E_TBYN');
M_.endo_names = char(M_.endo_names, 'E_TRTAXYN');
M_.endo_names_tex = char(M_.endo_names_tex, 'E\_TRTAXYN');
M_.endo_names_long = char(M_.endo_names_long, 'E_TRTAXYN');
M_.endo_names = char(M_.endo_names, 'E_TRW');
M_.endo_names_tex = char(M_.endo_names_tex, 'E\_TRW');
M_.endo_names_long = char(M_.endo_names_long, 'E_TRW');
M_.endo_names = char(M_.endo_names, 'E_TRYN');
M_.endo_names_tex = char(M_.endo_names_tex, 'E\_TRYN');
M_.endo_names_long = char(M_.endo_names_long, 'E_TRYN');
M_.endo_names = char(M_.endo_names, 'E_TW');
M_.endo_names_tex = char(M_.endo_names_tex, 'E\_TW');
M_.endo_names_long = char(M_.endo_names_long, 'E_TW');
M_.endo_names = char(M_.endo_names, 'E_UCAP');
M_.endo_names_tex = char(M_.endo_names_tex, 'E\_UCAP');
M_.endo_names_long = char(M_.endo_names_long, 'E_UCAP');
M_.endo_names = char(M_.endo_names, 'E_UCAP0');
M_.endo_names_tex = char(M_.endo_names_tex, 'E\_UCAP0');
M_.endo_names_long = char(M_.endo_names_long, 'E_UCAP0');
M_.endo_names = char(M_.endo_names, 'E_VL');
M_.endo_names_tex = char(M_.endo_names_tex, 'E\_VL');
M_.endo_names_long = char(M_.endo_names_long, 'E_VL');
M_.endo_names = char(M_.endo_names, 'E_VLLC');
M_.endo_names_tex = char(M_.endo_names_tex, 'E\_VLLC');
M_.endo_names_long = char(M_.endo_names_long, 'E_VLLC');
M_.endo_names = char(M_.endo_names, 'E_WPHI');
M_.endo_names_tex = char(M_.endo_names_tex, 'E\_WPHI');
M_.endo_names_long = char(M_.endo_names_long, 'E_WPHI');
M_.endo_names = char(M_.endo_names, 'E_WRPHI');
M_.endo_names_tex = char(M_.endo_names_tex, 'E\_WRPHI');
M_.endo_names_long = char(M_.endo_names_long, 'E_WRPHI');
M_.endo_names = char(M_.endo_names, 'E_WS');
M_.endo_names_tex = char(M_.endo_names_tex, 'E\_WS');
M_.endo_names_long = char(M_.endo_names_long, 'E_WS');
M_.endo_names = char(M_.endo_names, 'E_WSW');
M_.endo_names_tex = char(M_.endo_names_tex, 'E\_WSW');
M_.endo_names_long = char(M_.endo_names_long, 'E_WSW');
M_.endo_names = char(M_.endo_names, 'E_ZEPS_C');
M_.endo_names_tex = char(M_.endo_names_tex, 'E\_ZEPS\_C');
M_.endo_names_long = char(M_.endo_names_long, 'E_ZEPS_C');
M_.endo_names = char(M_.endo_names, 'E_ZEPS_ETA');
M_.endo_names_tex = char(M_.endo_names_tex, 'E\_ZEPS\_ETA');
M_.endo_names_long = char(M_.endo_names_long, 'E_ZEPS_ETA');
M_.endo_names = char(M_.endo_names, 'E_ZEPS_ETAM');
M_.endo_names_tex = char(M_.endo_names_tex, 'E\_ZEPS\_ETAM');
M_.endo_names_long = char(M_.endo_names_long, 'E_ZEPS_ETAM');
M_.endo_names = char(M_.endo_names, 'E_ZEPS_ETAX');
M_.endo_names_tex = char(M_.endo_names_tex, 'E\_ZEPS\_ETAX');
M_.endo_names_long = char(M_.endo_names_long, 'E_ZEPS_ETAX');
M_.endo_names = char(M_.endo_names, 'E_ZEPS_EX');
M_.endo_names_tex = char(M_.endo_names_tex, 'E\_ZEPS\_EX');
M_.endo_names_long = char(M_.endo_names_long, 'E_ZEPS_EX');
M_.endo_names = char(M_.endo_names, 'E_ZEPS_G');
M_.endo_names_tex = char(M_.endo_names_tex, 'E\_ZEPS\_G');
M_.endo_names_long = char(M_.endo_names_long, 'E_ZEPS_G');
M_.endo_names = char(M_.endo_names, 'E_ZEPS_IG');
M_.endo_names_tex = char(M_.endo_names_tex, 'E\_ZEPS\_IG');
M_.endo_names_long = char(M_.endo_names_long, 'E_ZEPS_IG');
M_.endo_names = char(M_.endo_names, 'E_ZEPS_L');
M_.endo_names_tex = char(M_.endo_names_tex, 'E\_ZEPS\_L');
M_.endo_names_long = char(M_.endo_names_long, 'E_ZEPS_L');
M_.endo_names = char(M_.endo_names, 'E_ZEPS_M');
M_.endo_names_tex = char(M_.endo_names_tex, 'E\_ZEPS\_M');
M_.endo_names_long = char(M_.endo_names_long, 'E_ZEPS_M');
M_.endo_names = char(M_.endo_names, 'E_ZEPS_PPI');
M_.endo_names_tex = char(M_.endo_names_tex, 'E\_ZEPS\_PPI');
M_.endo_names_long = char(M_.endo_names_long, 'E_ZEPS_PPI');
M_.endo_names = char(M_.endo_names, 'E_ZEPS_RPREME');
M_.endo_names_tex = char(M_.endo_names_tex, 'E\_ZEPS\_RPREME');
M_.endo_names_long = char(M_.endo_names_long, 'E_ZEPS_RPREME');
M_.endo_names = char(M_.endo_names, 'E_ZEPS_RPREMK');
M_.endo_names_tex = char(M_.endo_names_tex, 'E\_ZEPS\_RPREMK');
M_.endo_names_long = char(M_.endo_names_long, 'E_ZEPS_RPREMK');
M_.endo_names = char(M_.endo_names, 'E_ZEPS_TR');
M_.endo_names_tex = char(M_.endo_names_tex, 'E\_ZEPS\_TR');
M_.endo_names_long = char(M_.endo_names_long, 'E_ZEPS_TR');
M_.endo_names = char(M_.endo_names, 'E_ZEPS_W');
M_.endo_names_tex = char(M_.endo_names_tex, 'E\_ZEPS\_W');
M_.endo_names_long = char(M_.endo_names_long, 'E_ZEPS_W');
M_.endo_names = char(M_.endo_names, 'E_ZPHIT');
M_.endo_names_tex = char(M_.endo_names_tex, 'E\_ZPHIT');
M_.endo_names_long = char(M_.endo_names_long, 'E_ZPHIT');
M_.endo_names = char(M_.endo_names, 'E_LCY');
M_.endo_names_tex = char(M_.endo_names_tex, 'E\_LCY');
M_.endo_names_long = char(M_.endo_names_long, 'E_LCY');
M_.endo_names = char(M_.endo_names, 'E_LGY');
M_.endo_names_tex = char(M_.endo_names_tex, 'E\_LGY');
M_.endo_names_long = char(M_.endo_names_long, 'E_LGY');
M_.endo_names = char(M_.endo_names, 'E_LWS');
M_.endo_names_tex = char(M_.endo_names_tex, 'E\_LWS');
M_.endo_names_long = char(M_.endo_names_long, 'E_LWS');
M_.endo_names = char(M_.endo_names, 'E_EPS_G');
M_.endo_names_tex = char(M_.endo_names_tex, 'E\_EPS\_G');
M_.endo_names_long = char(M_.endo_names_long, 'E_EPS_G');
M_.endo_names = char(M_.endo_names, 'interest');
M_.endo_names_tex = char(M_.endo_names_tex, 'interest');
M_.endo_names_long = char(M_.endo_names_long, 'interest');
M_.endo_names = char(M_.endo_names, 'inflation');
M_.endo_names_tex = char(M_.endo_names_tex, 'inflation');
M_.endo_names_long = char(M_.endo_names_long, 'inflation');
M_.endo_names = char(M_.endo_names, 'inflationq');
M_.endo_names_tex = char(M_.endo_names_tex, 'inflationq');
M_.endo_names_long = char(M_.endo_names_long, 'inflationq');
M_.endo_names = char(M_.endo_names, 'outputgap');
M_.endo_names_tex = char(M_.endo_names_tex, 'outputgap');
M_.endo_names_long = char(M_.endo_names_long, 'outputgap');
M_.endo_names = char(M_.endo_names, 'fispol');
M_.endo_names_tex = char(M_.endo_names_tex, 'fispol');
M_.endo_names_long = char(M_.endo_names_long, 'fispol');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_86');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_86');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_86');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_90');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_90');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_90');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_94');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_94');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_94');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_121');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_121');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_121');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_125');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_125');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_125');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_129');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_129');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_129');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_107_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_107\_1');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_107_1');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_107_2');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_107\_2');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_107_2');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_108_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_108\_1');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_108_1');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_108_2');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_108\_2');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_108_2');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_108_3');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_108\_3');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_108_3');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_105_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_105\_1');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_105_1');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_105_2');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_105\_2');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_105_2');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_105_3');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_105\_3');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_105_3');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_107_3');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_107\_3');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_107_3');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_95_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_95\_1');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_95_1');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_95_2');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_95\_2');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_95_2');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_95_3');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_95\_3');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_95_3');
M_.endo_partitions = struct();
M_.param_names = 'cofintintb1';
M_.param_names_tex = 'cofintintb1';
M_.param_names_long = 'cofintintb1';
M_.param_names = char(M_.param_names, 'cofintintb2');
M_.param_names_tex = char(M_.param_names_tex, 'cofintintb2');
M_.param_names_long = char(M_.param_names_long, 'cofintintb2');
M_.param_names = char(M_.param_names, 'cofintintb3');
M_.param_names_tex = char(M_.param_names_tex, 'cofintintb3');
M_.param_names_long = char(M_.param_names_long, 'cofintintb3');
M_.param_names = char(M_.param_names, 'cofintintb4');
M_.param_names_tex = char(M_.param_names_tex, 'cofintintb4');
M_.param_names_long = char(M_.param_names_long, 'cofintintb4');
M_.param_names = char(M_.param_names, 'cofintinf0');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinf0');
M_.param_names_long = char(M_.param_names_long, 'cofintinf0');
M_.param_names = char(M_.param_names, 'cofintinfb1');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinfb1');
M_.param_names_long = char(M_.param_names_long, 'cofintinfb1');
M_.param_names = char(M_.param_names, 'cofintinfb2');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinfb2');
M_.param_names_long = char(M_.param_names_long, 'cofintinfb2');
M_.param_names = char(M_.param_names, 'cofintinfb3');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinfb3');
M_.param_names_long = char(M_.param_names_long, 'cofintinfb3');
M_.param_names = char(M_.param_names, 'cofintinfb4');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinfb4');
M_.param_names_long = char(M_.param_names_long, 'cofintinfb4');
M_.param_names = char(M_.param_names, 'cofintinff1');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinff1');
M_.param_names_long = char(M_.param_names_long, 'cofintinff1');
M_.param_names = char(M_.param_names, 'cofintinff2');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinff2');
M_.param_names_long = char(M_.param_names_long, 'cofintinff2');
M_.param_names = char(M_.param_names, 'cofintinff3');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinff3');
M_.param_names_long = char(M_.param_names_long, 'cofintinff3');
M_.param_names = char(M_.param_names, 'cofintinff4');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinff4');
M_.param_names_long = char(M_.param_names_long, 'cofintinff4');
M_.param_names = char(M_.param_names, 'cofintout');
M_.param_names_tex = char(M_.param_names_tex, 'cofintout');
M_.param_names_long = char(M_.param_names_long, 'cofintout');
M_.param_names = char(M_.param_names, 'cofintoutb1');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutb1');
M_.param_names_long = char(M_.param_names_long, 'cofintoutb1');
M_.param_names = char(M_.param_names, 'cofintoutb2');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutb2');
M_.param_names_long = char(M_.param_names_long, 'cofintoutb2');
M_.param_names = char(M_.param_names, 'cofintoutb3');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutb3');
M_.param_names_long = char(M_.param_names_long, 'cofintoutb3');
M_.param_names = char(M_.param_names, 'cofintoutb4');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutb4');
M_.param_names_long = char(M_.param_names_long, 'cofintoutb4');
M_.param_names = char(M_.param_names, 'cofintoutf1');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutf1');
M_.param_names_long = char(M_.param_names_long, 'cofintoutf1');
M_.param_names = char(M_.param_names, 'cofintoutf2');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutf2');
M_.param_names_long = char(M_.param_names_long, 'cofintoutf2');
M_.param_names = char(M_.param_names, 'cofintoutf3');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutf3');
M_.param_names_long = char(M_.param_names_long, 'cofintoutf3');
M_.param_names = char(M_.param_names, 'cofintoutf4');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutf4');
M_.param_names_long = char(M_.param_names_long, 'cofintoutf4');
M_.param_names = char(M_.param_names, 'cofintoutp');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutp');
M_.param_names_long = char(M_.param_names_long, 'cofintoutp');
M_.param_names = char(M_.param_names, 'cofintoutpb1');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpb1');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpb1');
M_.param_names = char(M_.param_names, 'cofintoutpb2');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpb2');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpb2');
M_.param_names = char(M_.param_names, 'cofintoutpb3');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpb3');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpb3');
M_.param_names = char(M_.param_names, 'cofintoutpb4');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpb4');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpb4');
M_.param_names = char(M_.param_names, 'cofintoutpf1');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpf1');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpf1');
M_.param_names = char(M_.param_names, 'cofintoutpf2');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpf2');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpf2');
M_.param_names = char(M_.param_names, 'cofintoutpf3');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpf3');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpf3');
M_.param_names = char(M_.param_names, 'cofintoutpf4');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpf4');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpf4');
M_.param_names = char(M_.param_names, 'std_r_');
M_.param_names_tex = char(M_.param_names_tex, 'std\_r\_');
M_.param_names_long = char(M_.param_names_long, 'std_r_');
M_.param_names = char(M_.param_names, 'std_r_quart');
M_.param_names_tex = char(M_.param_names_tex, 'std\_r\_quart');
M_.param_names_long = char(M_.param_names_long, 'std_r_quart');
M_.param_names = char(M_.param_names, 'coffispol');
M_.param_names_tex = char(M_.param_names_tex, 'coffispol');
M_.param_names_long = char(M_.param_names_long, 'coffispol');
M_.param_names = char(M_.param_names, 'A1E');
M_.param_names_tex = char(M_.param_names_tex, 'A1E');
M_.param_names_long = char(M_.param_names_long, 'A1E');
M_.param_names = char(M_.param_names, 'A2E');
M_.param_names_tex = char(M_.param_names_tex, 'A2E');
M_.param_names_long = char(M_.param_names_long, 'A2E');
M_.param_names = char(M_.param_names, 'ALPHAX');
M_.param_names_tex = char(M_.param_names_tex, 'ALPHAX');
M_.param_names_long = char(M_.param_names_long, 'ALPHAX');
M_.param_names = char(M_.param_names, 'ALPHAE');
M_.param_names_tex = char(M_.param_names_tex, 'ALPHAE');
M_.param_names_long = char(M_.param_names_long, 'ALPHAE');
M_.param_names = char(M_.param_names, 'ALPHAGE');
M_.param_names_tex = char(M_.param_names_tex, 'ALPHAGE');
M_.param_names_long = char(M_.param_names_long, 'ALPHAGE');
M_.param_names = char(M_.param_names, 'BETAE');
M_.param_names_tex = char(M_.param_names_tex, 'BETAE');
M_.param_names_long = char(M_.param_names_long, 'BETAE');
M_.param_names = char(M_.param_names, 'BGADJ1');
M_.param_names_tex = char(M_.param_names_tex, 'BGADJ1');
M_.param_names_long = char(M_.param_names_long, 'BGADJ1');
M_.param_names = char(M_.param_names, 'BGADJ2');
M_.param_names_tex = char(M_.param_names_tex, 'BGADJ2');
M_.param_names_long = char(M_.param_names_long, 'BGADJ2');
M_.param_names = char(M_.param_names, 'BGTAR');
M_.param_names_tex = char(M_.param_names_tex, 'BGTAR');
M_.param_names_long = char(M_.param_names_long, 'BGTAR');
M_.param_names = char(M_.param_names, 'DELTAE');
M_.param_names_tex = char(M_.param_names_tex, 'DELTAE');
M_.param_names_long = char(M_.param_names_long, 'DELTAE');
M_.param_names = char(M_.param_names, 'DELTAGE');
M_.param_names_tex = char(M_.param_names_tex, 'DELTAGE');
M_.param_names_long = char(M_.param_names_long, 'DELTAGE');
M_.param_names = char(M_.param_names, 'DGEX');
M_.param_names_tex = char(M_.param_names_tex, 'DGEX');
M_.param_names_long = char(M_.param_names_long, 'DGEX');
M_.param_names = char(M_.param_names, 'DGIM');
M_.param_names_tex = char(M_.param_names_tex, 'DGIM');
M_.param_names_long = char(M_.param_names_long, 'DGIM');
M_.param_names = char(M_.param_names, 'DGPM');
M_.param_names_tex = char(M_.param_names_tex, 'DGPM');
M_.param_names_long = char(M_.param_names_long, 'DGPM');
M_.param_names = char(M_.param_names, 'DGPX');
M_.param_names_tex = char(M_.param_names_tex, 'DGPX');
M_.param_names_long = char(M_.param_names_long, 'DGPX');
M_.param_names = char(M_.param_names, 'DDYN');
M_.param_names_tex = char(M_.param_names_tex, 'DDYN');
M_.param_names_long = char(M_.param_names_long, 'DDYN');
M_.param_names = char(M_.param_names, 'E_EX_INOMW');
M_.param_names_tex = char(M_.param_names_tex, 'E\_EX\_INOMW');
M_.param_names_long = char(M_.param_names_long, 'E_EX_INOMW');
M_.param_names = char(M_.param_names, 'E_EX_R');
M_.param_names_tex = char(M_.param_names_tex, 'E\_EX\_R');
M_.param_names_long = char(M_.param_names_long, 'E_EX_R');
M_.param_names = char(M_.param_names, 'E_EX_RW');
M_.param_names_tex = char(M_.param_names_tex, 'E\_EX\_RW');
M_.param_names_long = char(M_.param_names_long, 'E_EX_RW');
M_.param_names = char(M_.param_names, 'G1E');
M_.param_names_tex = char(M_.param_names_tex, 'G1E');
M_.param_names_long = char(M_.param_names_long, 'G1E');
M_.param_names = char(M_.param_names, 'GAMI2E');
M_.param_names_tex = char(M_.param_names_tex, 'GAMI2E');
M_.param_names_long = char(M_.param_names_long, 'GAMI2E');
M_.param_names = char(M_.param_names, 'GAMIE');
M_.param_names_tex = char(M_.param_names_tex, 'GAMIE');
M_.param_names_long = char(M_.param_names_long, 'GAMIE');
M_.param_names = char(M_.param_names, 'GAMLE');
M_.param_names_tex = char(M_.param_names_tex, 'GAMLE');
M_.param_names_long = char(M_.param_names_long, 'GAMLE');
M_.param_names = char(M_.param_names, 'GAMPE');
M_.param_names_tex = char(M_.param_names_tex, 'GAMPE');
M_.param_names_long = char(M_.param_names_long, 'GAMPE');
M_.param_names = char(M_.param_names, 'GAMPME');
M_.param_names_tex = char(M_.param_names_tex, 'GAMPME');
M_.param_names_long = char(M_.param_names_long, 'GAMPME');
M_.param_names = char(M_.param_names, 'GAMPXE');
M_.param_names_tex = char(M_.param_names_tex, 'GAMPXE');
M_.param_names_long = char(M_.param_names_long, 'GAMPXE');
M_.param_names = char(M_.param_names, 'GAMWE');
M_.param_names_tex = char(M_.param_names_tex, 'GAMWE');
M_.param_names_long = char(M_.param_names_long, 'GAMWE');
M_.param_names = char(M_.param_names, 'GP0');
M_.param_names_tex = char(M_.param_names_tex, 'GP0');
M_.param_names_long = char(M_.param_names_long, 'GP0');
M_.param_names = char(M_.param_names, 'GPCPI0');
M_.param_names_tex = char(M_.param_names_tex, 'GPCPI0');
M_.param_names_long = char(M_.param_names_long, 'GPCPI0');
M_.param_names = char(M_.param_names, 'GPOP0');
M_.param_names_tex = char(M_.param_names_tex, 'GPOP0');
M_.param_names_long = char(M_.param_names_long, 'GPOP0');
M_.param_names = char(M_.param_names, 'GPW0');
M_.param_names_tex = char(M_.param_names_tex, 'GPW0');
M_.param_names_long = char(M_.param_names_long, 'GPW0');
M_.param_names = char(M_.param_names, 'GSLAG');
M_.param_names_tex = char(M_.param_names_tex, 'GSLAG');
M_.param_names_long = char(M_.param_names_long, 'GSLAG');
M_.param_names = char(M_.param_names, 'GVECM');
M_.param_names_tex = char(M_.param_names_tex, 'GVECM');
M_.param_names_long = char(M_.param_names_long, 'GVECM');
M_.param_names = char(M_.param_names, 'GFLAG');
M_.param_names_tex = char(M_.param_names_tex, 'GFLAG');
M_.param_names_long = char(M_.param_names_long, 'GFLAG');
M_.param_names = char(M_.param_names, 'GLAGFLAG');
M_.param_names_tex = char(M_.param_names_tex, 'GLAGFLAG');
M_.param_names_long = char(M_.param_names_long, 'GLAGFLAG');
M_.param_names = char(M_.param_names, 'IGLAGFLAG');
M_.param_names_tex = char(M_.param_names_tex, 'IGLAGFLAG');
M_.param_names_long = char(M_.param_names_long, 'IGLAGFLAG');
M_.param_names = char(M_.param_names, 'IGFLAG');
M_.param_names_tex = char(M_.param_names_tex, 'IGFLAG');
M_.param_names_long = char(M_.param_names_long, 'IGFLAG');
M_.param_names = char(M_.param_names, 'TRFLAG');
M_.param_names_tex = char(M_.param_names_tex, 'TRFLAG');
M_.param_names_long = char(M_.param_names_long, 'TRFLAG');
M_.param_names = char(M_.param_names, 'TWFLAG');
M_.param_names_tex = char(M_.param_names_tex, 'TWFLAG');
M_.param_names_long = char(M_.param_names_long, 'TWFLAG');
M_.param_names = char(M_.param_names, 'GEXOFLAG');
M_.param_names_tex = char(M_.param_names_tex, 'GEXOFLAG');
M_.param_names_long = char(M_.param_names_long, 'GEXOFLAG');
M_.param_names = char(M_.param_names, 'IGEXOFLAG');
M_.param_names_tex = char(M_.param_names_tex, 'IGEXOFLAG');
M_.param_names_long = char(M_.param_names_long, 'IGEXOFLAG');
M_.param_names = char(M_.param_names, 'TREXOFLAG');
M_.param_names_tex = char(M_.param_names_tex, 'TREXOFLAG');
M_.param_names_long = char(M_.param_names_long, 'TREXOFLAG');
M_.param_names = char(M_.param_names, 'GAMIFLAG');
M_.param_names_tex = char(M_.param_names_tex, 'GAMIFLAG');
M_.param_names_long = char(M_.param_names_long, 'GAMIFLAG');
M_.param_names = char(M_.param_names, 'SLCFLAG');
M_.param_names_tex = char(M_.param_names_tex, 'SLCFLAG');
M_.param_names_long = char(M_.param_names_long, 'SLCFLAG');
M_.param_names = char(M_.param_names, 'GSN');
M_.param_names_tex = char(M_.param_names_tex, 'GSN');
M_.param_names_long = char(M_.param_names_long, 'GSN');
M_.param_names = char(M_.param_names, 'GTFP0');
M_.param_names_tex = char(M_.param_names_tex, 'GTFP0');
M_.param_names_long = char(M_.param_names_long, 'GTFP0');
M_.param_names = char(M_.param_names, 'GY0');
M_.param_names_tex = char(M_.param_names_tex, 'GY0');
M_.param_names_long = char(M_.param_names_long, 'GY0');
M_.param_names = char(M_.param_names, 'GYW0');
M_.param_names_tex = char(M_.param_names_tex, 'GYW0');
M_.param_names_long = char(M_.param_names_long, 'GYW0');
M_.param_names = char(M_.param_names, 'HABE');
M_.param_names_tex = char(M_.param_names_tex, 'HABE');
M_.param_names_long = char(M_.param_names_long, 'HABE');
M_.param_names = char(M_.param_names, 'HABLE');
M_.param_names_tex = char(M_.param_names_tex, 'HABLE');
M_.param_names_long = char(M_.param_names_long, 'HABLE');
M_.param_names = char(M_.param_names, 'IGSLAG');
M_.param_names_tex = char(M_.param_names_tex, 'IGSLAG');
M_.param_names_long = char(M_.param_names_long, 'IGSLAG');
M_.param_names = char(M_.param_names, 'IGVECM');
M_.param_names_tex = char(M_.param_names_tex, 'IGVECM');
M_.param_names_long = char(M_.param_names_long, 'IGVECM');
M_.param_names = char(M_.param_names, 'ILAGE');
M_.param_names_tex = char(M_.param_names_tex, 'ILAGE');
M_.param_names_long = char(M_.param_names_long, 'ILAGE');
M_.param_names = char(M_.param_names, 'INFLAGE');
M_.param_names_tex = char(M_.param_names_tex, 'INFLAGE');
M_.param_names_long = char(M_.param_names_long, 'INFLAGE');
M_.param_names = char(M_.param_names, 'IG1E');
M_.param_names_tex = char(M_.param_names_tex, 'IG1E');
M_.param_names_long = char(M_.param_names_long, 'IG1E');
M_.param_names = char(M_.param_names, 'IGSN');
M_.param_names_tex = char(M_.param_names_tex, 'IGSN');
M_.param_names_long = char(M_.param_names_long, 'IGSN');
M_.param_names = char(M_.param_names, 'ISN');
M_.param_names_tex = char(M_.param_names_tex, 'ISN');
M_.param_names_long = char(M_.param_names_long, 'ISN');
M_.param_names = char(M_.param_names, 'KAPPAE');
M_.param_names_tex = char(M_.param_names_tex, 'KAPPAE');
M_.param_names_long = char(M_.param_names_long, 'KAPPAE');
M_.param_names = char(M_.param_names, 'L0');
M_.param_names_tex = char(M_.param_names_tex, 'L0');
M_.param_names_long = char(M_.param_names_long, 'L0');
M_.param_names = char(M_.param_names, 'LOL');
M_.param_names_tex = char(M_.param_names_tex, 'LOL');
M_.param_names_long = char(M_.param_names_long, 'LOL');
M_.param_names = char(M_.param_names, 'LYWY0');
M_.param_names_tex = char(M_.param_names_tex, 'LYWY0');
M_.param_names_long = char(M_.param_names_long, 'LYWY0');
M_.param_names = char(M_.param_names, 'OMEGE');
M_.param_names_tex = char(M_.param_names_tex, 'OMEGE');
M_.param_names_long = char(M_.param_names_long, 'OMEGE');
M_.param_names = char(M_.param_names, 'RHOCE');
M_.param_names_tex = char(M_.param_names_tex, 'RHOCE');
M_.param_names_long = char(M_.param_names_long, 'RHOCE');
M_.param_names = char(M_.param_names, 'RHOETA');
M_.param_names_tex = char(M_.param_names_tex, 'RHOETA');
M_.param_names_long = char(M_.param_names_long, 'RHOETA');
M_.param_names = char(M_.param_names, 'RHOETAM');
M_.param_names_tex = char(M_.param_names_tex, 'RHOETAM');
M_.param_names_long = char(M_.param_names_long, 'RHOETAM');
M_.param_names = char(M_.param_names, 'RHOETAX');
M_.param_names_tex = char(M_.param_names_tex, 'RHOETAX');
M_.param_names_long = char(M_.param_names_long, 'RHOETAX');
M_.param_names = char(M_.param_names, 'RHOEXE');
M_.param_names_tex = char(M_.param_names_tex, 'RHOEXE');
M_.param_names_long = char(M_.param_names_long, 'RHOEXE');
M_.param_names = char(M_.param_names, 'RHOGE');
M_.param_names_tex = char(M_.param_names_tex, 'RHOGE');
M_.param_names_long = char(M_.param_names_long, 'RHOGE');
M_.param_names = char(M_.param_names, 'RHOIG');
M_.param_names_tex = char(M_.param_names_tex, 'RHOIG');
M_.param_names_long = char(M_.param_names_long, 'RHOIG');
M_.param_names = char(M_.param_names, 'RHOL0');
M_.param_names_tex = char(M_.param_names_tex, 'RHOL0');
M_.param_names_long = char(M_.param_names_long, 'RHOL0');
M_.param_names = char(M_.param_names, 'RHOLE');
M_.param_names_tex = char(M_.param_names_tex, 'RHOLE');
M_.param_names_long = char(M_.param_names_long, 'RHOLE');
M_.param_names = char(M_.param_names, 'RHOLOL');
M_.param_names_tex = char(M_.param_names_tex, 'RHOLOL');
M_.param_names_long = char(M_.param_names_long, 'RHOLOL');
M_.param_names = char(M_.param_names, 'RHOPPI1');
M_.param_names_tex = char(M_.param_names_tex, 'RHOPPI1');
M_.param_names_long = char(M_.param_names_long, 'RHOPPI1');
M_.param_names = char(M_.param_names, 'RHOPPI2');
M_.param_names_tex = char(M_.param_names_tex, 'RHOPPI2');
M_.param_names_long = char(M_.param_names_long, 'RHOPPI2');
M_.param_names = char(M_.param_names, 'RHOPPI3');
M_.param_names_tex = char(M_.param_names_tex, 'RHOPPI3');
M_.param_names_long = char(M_.param_names_long, 'RHOPPI3');
M_.param_names = char(M_.param_names, 'RHOPPI4');
M_.param_names_tex = char(M_.param_names_tex, 'RHOPPI4');
M_.param_names_long = char(M_.param_names_long, 'RHOPPI4');
M_.param_names = char(M_.param_names, 'RHOPCPM');
M_.param_names_tex = char(M_.param_names_tex, 'RHOPCPM');
M_.param_names_long = char(M_.param_names_long, 'RHOPCPM');
M_.param_names = char(M_.param_names, 'RHOPWPX');
M_.param_names_tex = char(M_.param_names_tex, 'RHOPWPX');
M_.param_names_long = char(M_.param_names_long, 'RHOPWPX');
M_.param_names = char(M_.param_names, 'RHORPE');
M_.param_names_tex = char(M_.param_names_tex, 'RHORPE');
M_.param_names_long = char(M_.param_names_long, 'RHORPE');
M_.param_names = char(M_.param_names, 'RHORPK');
M_.param_names_tex = char(M_.param_names_tex, 'RHORPK');
M_.param_names_long = char(M_.param_names_long, 'RHORPK');
M_.param_names = char(M_.param_names, 'RHOUCAP0');
M_.param_names_tex = char(M_.param_names_tex, 'RHOUCAP0');
M_.param_names_long = char(M_.param_names_long, 'RHOUCAP0');
M_.param_names = char(M_.param_names, 'RII');
M_.param_names_tex = char(M_.param_names_tex, 'RII');
M_.param_names_long = char(M_.param_names_long, 'RII');
M_.param_names = char(M_.param_names, 'RIP');
M_.param_names_tex = char(M_.param_names_tex, 'RIP');
M_.param_names_long = char(M_.param_names_long, 'RIP');
M_.param_names = char(M_.param_names, 'RIX');
M_.param_names_tex = char(M_.param_names_tex, 'RIX');
M_.param_names_long = char(M_.param_names_long, 'RIX');
M_.param_names = char(M_.param_names, 'RPI');
M_.param_names_tex = char(M_.param_names_tex, 'RPI');
M_.param_names_long = char(M_.param_names_long, 'RPI');
M_.param_names = char(M_.param_names, 'RPP');
M_.param_names_tex = char(M_.param_names_tex, 'RPP');
M_.param_names_long = char(M_.param_names_long, 'RPP');
M_.param_names = char(M_.param_names, 'RPX');
M_.param_names_tex = char(M_.param_names_tex, 'RPX');
M_.param_names_long = char(M_.param_names_long, 'RPX');
M_.param_names = char(M_.param_names, 'RXI');
M_.param_names_tex = char(M_.param_names_tex, 'RXI');
M_.param_names_long = char(M_.param_names_long, 'RXI');
M_.param_names = char(M_.param_names, 'RXP');
M_.param_names_tex = char(M_.param_names_tex, 'RXP');
M_.param_names_long = char(M_.param_names_long, 'RXP');
M_.param_names = char(M_.param_names, 'RXX');
M_.param_names_tex = char(M_.param_names_tex, 'RXX');
M_.param_names_long = char(M_.param_names_long, 'RXX');
M_.param_names = char(M_.param_names, 'RXY');
M_.param_names_tex = char(M_.param_names_tex, 'RXY');
M_.param_names_long = char(M_.param_names_long, 'RXY');
M_.param_names = char(M_.param_names, 'RPREME');
M_.param_names_tex = char(M_.param_names_tex, 'RPREME');
M_.param_names_long = char(M_.param_names_long, 'RPREME');
M_.param_names = char(M_.param_names, 'RPREMK');
M_.param_names_tex = char(M_.param_names_tex, 'RPREMK');
M_.param_names_long = char(M_.param_names_long, 'RPREMK');
M_.param_names = char(M_.param_names, 'SE');
M_.param_names_tex = char(M_.param_names_tex, 'SE');
M_.param_names_long = char(M_.param_names_long, 'SE');
M_.param_names = char(M_.param_names, 'SFPE');
M_.param_names_tex = char(M_.param_names_tex, 'SFPE');
M_.param_names_long = char(M_.param_names_long, 'SFPE');
M_.param_names = char(M_.param_names, 'SFPME');
M_.param_names_tex = char(M_.param_names_tex, 'SFPME');
M_.param_names_long = char(M_.param_names_long, 'SFPME');
M_.param_names = char(M_.param_names, 'SFPXE');
M_.param_names_tex = char(M_.param_names_tex, 'SFPXE');
M_.param_names_long = char(M_.param_names_long, 'SFPXE');
M_.param_names = char(M_.param_names, 'SFWE');
M_.param_names_tex = char(M_.param_names_tex, 'SFWE');
M_.param_names_long = char(M_.param_names_long, 'SFWE');
M_.param_names = char(M_.param_names, 'SIGC');
M_.param_names_tex = char(M_.param_names_tex, 'SIGC');
M_.param_names_long = char(M_.param_names_long, 'SIGC');
M_.param_names = char(M_.param_names, 'SIGEXE');
M_.param_names_tex = char(M_.param_names_tex, 'SIGEXE');
M_.param_names_long = char(M_.param_names_long, 'SIGEXE');
M_.param_names = char(M_.param_names, 'SIGIME');
M_.param_names_tex = char(M_.param_names_tex, 'SIGIME');
M_.param_names_long = char(M_.param_names_long, 'SIGIME');
M_.param_names = char(M_.param_names, 'SLC');
M_.param_names_tex = char(M_.param_names_tex, 'SLC');
M_.param_names_long = char(M_.param_names_long, 'SLC');
M_.param_names = char(M_.param_names, 'SSC');
M_.param_names_tex = char(M_.param_names_tex, 'SSC');
M_.param_names_long = char(M_.param_names_long, 'SSC');
M_.param_names = char(M_.param_names, 'TAUE');
M_.param_names_tex = char(M_.param_names_tex, 'TAUE');
M_.param_names_long = char(M_.param_names_long, 'TAUE');
M_.param_names = char(M_.param_names, 'TP');
M_.param_names_tex = char(M_.param_names_tex, 'TP');
M_.param_names_long = char(M_.param_names_long, 'TP');
M_.param_names = char(M_.param_names, 'THETAE');
M_.param_names_tex = char(M_.param_names_tex, 'THETAE');
M_.param_names_long = char(M_.param_names_long, 'THETAE');
M_.param_names = char(M_.param_names, 'TINFE');
M_.param_names_tex = char(M_.param_names_tex, 'TINFE');
M_.param_names_long = char(M_.param_names_long, 'TINFE');
M_.param_names = char(M_.param_names, 'TR1E');
M_.param_names_tex = char(M_.param_names_tex, 'TR1E');
M_.param_names_long = char(M_.param_names_long, 'TR1E');
M_.param_names = char(M_.param_names, 'TRSN');
M_.param_names_tex = char(M_.param_names_tex, 'TRSN');
M_.param_names_long = char(M_.param_names_long, 'TRSN');
M_.param_names = char(M_.param_names, 'RHOTR');
M_.param_names_tex = char(M_.param_names_tex, 'RHOTR');
M_.param_names_long = char(M_.param_names_long, 'RHOTR');
M_.param_names = char(M_.param_names, 'TYE1');
M_.param_names_tex = char(M_.param_names_tex, 'TYE1');
M_.param_names_long = char(M_.param_names_long, 'TYE1');
M_.param_names = char(M_.param_names, 'TYE2');
M_.param_names_tex = char(M_.param_names_tex, 'TYE2');
M_.param_names_long = char(M_.param_names_long, 'TYE2');
M_.param_names = char(M_.param_names, 'TVAT');
M_.param_names_tex = char(M_.param_names_tex, 'TVAT');
M_.param_names_long = char(M_.param_names_long, 'TVAT');
M_.param_names = char(M_.param_names, 'TW0');
M_.param_names_tex = char(M_.param_names_tex, 'TW0');
M_.param_names_long = char(M_.param_names_long, 'TW0');
M_.param_names = char(M_.param_names, 'TW1');
M_.param_names_tex = char(M_.param_names_tex, 'TW1');
M_.param_names_long = char(M_.param_names_long, 'TW1');
M_.param_names = char(M_.param_names, 'UCAP0');
M_.param_names_tex = char(M_.param_names_tex, 'UCAP0');
M_.param_names_long = char(M_.param_names_long, 'UCAP0');
M_.param_names = char(M_.param_names, 'WRLAG');
M_.param_names_tex = char(M_.param_names_tex, 'WRLAG');
M_.param_names_long = char(M_.param_names_long, 'WRLAG');
M_.param_names = char(M_.param_names, 'ZETE');
M_.param_names_tex = char(M_.param_names_tex, 'ZETE');
M_.param_names_long = char(M_.param_names_long, 'ZETE');
M_.param_names = char(M_.param_names, 'interestq_exog');
M_.param_names_tex = char(M_.param_names_tex, 'interestq\_exog');
M_.param_names_long = char(M_.param_names_long, 'interestq_exog');
M_.param_names = char(M_.param_names, 'inflationannual_exog');
M_.param_names_tex = char(M_.param_names_tex, 'inflationannual\_exog');
M_.param_names_long = char(M_.param_names_long, 'inflationannual_exog');
M_.param_partitions = struct();
M_.exo_det_nbr = 0;
M_.exo_nbr = 20;
M_.endo_nbr = 128;
M_.param_nbr = 154;
M_.orig_endo_nbr = 110;
M_.aux_vars(1).endo_index = 111;
M_.aux_vars(1).type = 0;
M_.aux_vars(2).endo_index = 112;
M_.aux_vars(2).type = 0;
M_.aux_vars(3).endo_index = 113;
M_.aux_vars(3).type = 0;
M_.aux_vars(4).endo_index = 114;
M_.aux_vars(4).type = 0;
M_.aux_vars(5).endo_index = 115;
M_.aux_vars(5).type = 0;
M_.aux_vars(6).endo_index = 116;
M_.aux_vars(6).type = 0;
M_.aux_vars(7).endo_index = 117;
M_.aux_vars(7).type = 1;
M_.aux_vars(7).orig_index = 108;
M_.aux_vars(7).orig_lead_lag = -1;
M_.aux_vars(8).endo_index = 118;
M_.aux_vars(8).type = 1;
M_.aux_vars(8).orig_index = 108;
M_.aux_vars(8).orig_lead_lag = -2;
M_.aux_vars(9).endo_index = 119;
M_.aux_vars(9).type = 1;
M_.aux_vars(9).orig_index = 109;
M_.aux_vars(9).orig_lead_lag = -1;
M_.aux_vars(10).endo_index = 120;
M_.aux_vars(10).type = 1;
M_.aux_vars(10).orig_index = 109;
M_.aux_vars(10).orig_lead_lag = -2;
M_.aux_vars(11).endo_index = 121;
M_.aux_vars(11).type = 1;
M_.aux_vars(11).orig_index = 109;
M_.aux_vars(11).orig_lead_lag = -3;
M_.aux_vars(12).endo_index = 122;
M_.aux_vars(12).type = 1;
M_.aux_vars(12).orig_index = 106;
M_.aux_vars(12).orig_lead_lag = -1;
M_.aux_vars(13).endo_index = 123;
M_.aux_vars(13).type = 1;
M_.aux_vars(13).orig_index = 106;
M_.aux_vars(13).orig_lead_lag = -2;
M_.aux_vars(14).endo_index = 124;
M_.aux_vars(14).type = 1;
M_.aux_vars(14).orig_index = 106;
M_.aux_vars(14).orig_lead_lag = -3;
M_.aux_vars(15).endo_index = 125;
M_.aux_vars(15).type = 1;
M_.aux_vars(15).orig_index = 108;
M_.aux_vars(15).orig_lead_lag = -3;
M_.aux_vars(16).endo_index = 126;
M_.aux_vars(16).type = 1;
M_.aux_vars(16).orig_index = 96;
M_.aux_vars(16).orig_lead_lag = -1;
M_.aux_vars(17).endo_index = 127;
M_.aux_vars(17).type = 1;
M_.aux_vars(17).orig_index = 96;
M_.aux_vars(17).orig_lead_lag = -2;
M_.aux_vars(18).endo_index = 128;
M_.aux_vars(18).type = 1;
M_.aux_vars(18).orig_index = 96;
M_.aux_vars(18).orig_lead_lag = -3;
M_.Sigma_e = zeros(20, 20);
M_.Correlation_matrix = eye(20, 20);
M_.H = 0;
M_.Correlation_matrix_ME = 1;
M_.sigma_e_is_diagonal = 1;
M_.det_shocks = [];
options_.block=0;
options_.bytecode=0;
options_.use_dll=0;
M_.hessian_eq_zero = 0;
erase_compiled_function('EA_QUEST3_static');
erase_compiled_function('EA_QUEST3_dynamic');
M_.orig_eq_nbr = 110;
M_.eq_nbr = 128;
M_.ramsey_eq_nbr = 0;
M_.set_auxiliary_variables = exist(['./' M_.fname '_set_auxiliary_variables.m'], 'file') == 2;
M_.lead_lag_incidence = [
 1 67 0;
 2 68 0;
 0 69 0;
 0 70 0;
 3 71 0;
 0 72 0;
 0 73 0;
 0 74 0;
 0 75 0;
 0 76 0;
 0 77 195;
 0 78 0;
 0 79 0;
 4 80 0;
 0 81 0;
 0 82 196;
 5 83 0;
 0 84 0;
 0 85 0;
 0 86 0;
 6 87 0;
 7 88 0;
 0 89 0;
 0 90 0;
 0 91 0;
 0 92 0;
 0 93 0;
 0 94 0;
 0 95 197;
 0 96 0;
 0 97 0;
 0 98 198;
 0 99 0;
 0 100 0;
 8 101 0;
 0 102 0;
 9 103 0;
 10 104 199;
 11 105 0;
 12 106 0;
 13 107 0;
 14 108 0;
 15 109 0;
 16 110 0;
 17 111 0;
 18 112 0;
 19 113 0;
 20 114 0;
 21 115 0;
 22 116 0;
 23 117 0;
 24 118 0;
 25 119 0;
 26 120 0;
 0 121 0;
 27 122 0;
 0 123 0;
 28 124 0;
 29 125 0;
 30 126 200;
 31 127 0;
 0 128 0;
 32 129 201;
 0 130 202;
 0 131 203;
 33 132 204;
 0 133 0;
 34 134 0;
 35 135 205;
 0 136 0;
 0 137 206;
 0 138 0;
 36 139 0;
 0 140 0;
 0 141 0;
 37 142 0;
 0 143 0;
 0 144 0;
 38 145 0;
 39 146 0;
 0 147 0;
 0 148 0;
 0 149 207;
 0 150 0;
 0 151 0;
 0 152 0;
 40 153 0;
 41 154 0;
 42 155 0;
 43 156 0;
 44 157 0;
 45 158 0;
 46 159 0;
 47 160 0;
 0 161 0;
 48 162 0;
 49 163 0;
 50 164 0;
 51 165 0;
 0 166 0;
 0 167 0;
 0 168 0;
 0 169 0;
 0 170 0;
 0 171 0;
 52 172 0;
 0 173 0;
 53 174 208;
 54 175 209;
 0 176 0;
 0 177 210;
 0 178 211;
 0 179 212;
 0 180 213;
 0 181 214;
 0 182 215;
 55 183 0;
 56 184 0;
 57 185 0;
 58 186 0;
 59 187 0;
 60 188 0;
 61 189 0;
 62 190 0;
 63 191 0;
 64 192 0;
 65 193 0;
 66 194 0;]';
M_.nstatic = 48;
M_.nfwrd   = 14;
M_.npred   = 59;
M_.nboth   = 7;
M_.nsfwrd   = 21;
M_.nspred   = 66;
M_.ndynamic   = 80;
M_.equations_tags = {
};
M_.static_and_dynamic_models_differ = 0;
M_.exo_names_orig_ord = [1:20];
M_.maximum_lag = 1;
M_.maximum_lead = 1;
M_.maximum_endo_lag = 1;
M_.maximum_endo_lead = 1;
oo_.steady_state = zeros(128, 1);
M_.maximum_exo_lag = 0;
M_.maximum_exo_lead = 0;
oo_.exo_steady_state = zeros(20, 1);
M_.params = NaN(154, 1);
M_.NNZDerivatives = [501; 390; -1];
M_.params( 36 ) = 0.0453;
A2E = M_.params( 36 );
M_.params( 54 ) = (-0.0754);
G1E = M_.params( 54 );
M_.params( 56 ) = 76.0366;
GAMIE = M_.params( 56 );
M_.params( 55 ) = 1.1216;
GAMI2E = M_.params( 55 );
M_.params( 57 ) = 58.2083;
GAMLE = M_.params( 57 );
M_.params( 58 ) = 61.4415;
GAMPE = M_.params( 58 );
M_.params( 59 ) = 1.6782;
GAMPME = M_.params( 59 );
M_.params( 60 ) = 26.1294;
GAMPXE = M_.params( 60 );
M_.params( 61 ) = 1.2919;
GAMWE = M_.params( 61 );
M_.params( 66 ) = (-0.4227);
GSLAG = M_.params( 66 );
M_.params( 67 ) = (-0.1567);
GVECM = M_.params( 67 );
M_.params( 83 ) = 0.5634;
HABE = M_.params( 83 );
M_.params( 84 ) = 0.8089;
HABLE = M_.params( 84 );
M_.params( 89 ) = 0.1497;
IG1E = M_.params( 89 );
M_.params( 85 ) = 0.4475;
IGSLAG = M_.params( 85 );
M_.params( 86 ) = (-0.1222);
IGVECM = M_.params( 86 );
M_.params( 87 ) = 0.9009;
ILAGE = M_.params( 87 );
M_.params( 92 ) = 1.9224;
KAPPAE = M_.params( 92 );
M_.params( 97 ) = 0.9144;
RHOCE = M_.params( 97 );
M_.params( 98 ) = 0.1095;
RHOETA = M_.params( 98 );
M_.params( 99 ) = 0.9557;
RHOETAM = M_.params( 99 );
M_.params( 100 ) = 0.8109;
RHOETAX = M_.params( 100 );
M_.params( 102 ) = 0.2983;
RHOGE = M_.params( 102 );
M_.params( 103 ) = 0.8530;
RHOIG = M_.params( 103 );
M_.params( 105 ) = 0.9750;
RHOLE = M_.params( 105 );
M_.params( 104 ) = 0.9334;
RHOL0 = M_.params( 104 );
M_.params( 111 ) = 0.6652;
RHOPCPM = M_.params( 111 );
M_.params( 112 ) = 0.2159;
RHOPWPX = M_.params( 112 );
M_.params( 113 ) = 0.9842;
RHORPE = M_.params( 113 );
M_.params( 114 ) = 0.9148;
RHORPK = M_.params( 114 );
M_.params( 115 ) = 0.9517;
RHOUCAP0 = M_.params( 115 );
M_.params( 126 ) = 0.0200;
RPREME = M_.params( 126 );
M_.params( 127 ) = 0.0245;
RPREMK = M_.params( 127 );
M_.params( 128 ) = 0.8588;
SE = M_.params( 128 );
M_.params( 129 ) = 0.8714;
SFPE = M_.params( 129 );
M_.params( 130 ) = 0.7361;
SFPME = M_.params( 130 );
M_.params( 131 ) = 0.9180;
SFPXE = M_.params( 131 );
M_.params( 132 ) = 0.7736;
SFWE = M_.params( 132 );
M_.params( 133 ) = 4.0962;
SIGC = M_.params( 133 );
M_.params( 134 ) = 2.5358;
SIGEXE = M_.params( 134 );
M_.params( 135 ) = 1.1724;
SIGIME = M_.params( 135 );
M_.params( 136 ) = 0.3507;
SLC = M_.params( 136 );
M_.params( 141 ) = 1.9590;
TINFE = M_.params( 141 );
M_.params( 142 ) = 0.9183;
TR1E = M_.params( 142 );
M_.params( 144 ) = 0.8636;
RHOTR = M_.params( 144 );
M_.params( 145 ) = 0.4274;
TYE1 = M_.params( 145 );
M_.params( 146 ) = 0.0783;
TYE2 = M_.params( 146 );
M_.params( 151 ) = 0.2653;
WRLAG = M_.params( 151 );
M_.params( 37 ) = 0.5;
ALPHAX = M_.params( 37 );
M_.params( 40 ) = 0.996;
BETAE = M_.params( 40 );
M_.params( 38 ) = 0.52;
ALPHAE = M_.params( 38 );
M_.params( 39 ) = 0.9;
ALPHAGE = M_.params( 39 );
M_.params( 42 ) = 0.004;
BGADJ2 = M_.params( 42 );
M_.params( 41 ) = 0.001*M_.params(42);
BGADJ1 = M_.params( 41 );
M_.params( 43 ) = 2.4;
BGTAR = M_.params( 43 );
M_.params( 44 ) = 0.025;
DELTAE = M_.params( 44 );
M_.params( 45 ) = 0.0125;
DELTAGE = M_.params( 45 );
M_.params( 47 ) = 0.00738619107021;
DGIM = M_.params( 47 );
M_.params( 46 ) = 0.00738619107021;
DGEX = M_.params( 46 );
M_.params( 48 ) = (-0.00396650612294);
DGPM = M_.params( 48 );
M_.params( 49 ) = (-0.00396650612294);
DGPX = M_.params( 49 );
M_.params( 88 ) = 0.98;
INFLAGE = M_.params( 88 );
M_.params( 94 ) = 0;
LOL = M_.params( 94 );
M_.params( 101 ) = 0.975;
RHOEXE = M_.params( 101 );
M_.params( 106 ) = 0.99;
RHOLOL = M_.params( 106 );
M_.params( 137 ) = 0.2;
SSC = M_.params( 137 );
M_.params( 138 ) = 0.1000;
TAUE = M_.params( 138 );
M_.params( 140 ) = 1.6;
THETAE = M_.params( 140 );
M_.params( 139 ) = 0.2;
TP = M_.params( 139 );
M_.params( 143 ) = 0.36;
TRSN = M_.params( 143 );
M_.params( 147 ) = 0.2;
TVAT = M_.params( 147 );
M_.params( 148 ) = 0.2;
TW0 = M_.params( 148 );
M_.params( 149 ) = 0.8;
TW1 = M_.params( 149 );
M_.params( 152 ) = 0.4000;
ZETE = M_.params( 152 );
M_.params( 50 ) = 1;
DDYN = M_.params( 50 );
M_.params( 68 ) = 1;
GFLAG = M_.params( 68 );
M_.params( 69 ) = 1;
GLAGFLAG = M_.params( 69 );
M_.params( 70 ) = 1;
IGLAGFLAG = M_.params( 70 );
M_.params( 71 ) = 1;
IGFLAG = M_.params( 71 );
M_.params( 72 ) = 1;
TRFLAG = M_.params( 72 );
M_.params( 73 ) = 1;
TWFLAG = M_.params( 73 );
M_.params( 74 ) = 1;
GEXOFLAG = M_.params( 74 );
M_.params( 75 ) = 1;
IGEXOFLAG = M_.params( 75 );
M_.params( 76 ) = 1;
TREXOFLAG = M_.params( 76 );
M_.params( 78 ) = 1;
SLCFLAG = M_.params( 78 );
M_.params( 77 ) = 1;
GAMIFLAG = M_.params( 77 );
M_.params( 35 ) = 0.0669;
A1E = M_.params( 35 );
M_.params( 96 ) = 1.4836;
OMEGE = M_.params( 96 );
M_.params( 79 ) = 0.203;
GSN = M_.params( 79 );
M_.params( 90 ) = 0.025;
IGSN = M_.params( 90 );
M_.params( 63 ) = 0;
GPCPI0 = M_.params( 63 );
M_.params( 62 ) = 0.005;
GP0 = M_.params( 62 );
M_.params( 65 ) = M_.params(62);
GPW0 = M_.params( 65 );
M_.params( 64 ) = 0.00113377677398;
GPOP0 = M_.params( 64 );
M_.params( 81 ) = 0.003;
GY0 = M_.params( 81 );
M_.params( 80 ) = (M_.params(38)+M_.params(39)-1)/M_.params(38)*M_.params(81)-(2-M_.params(38)-M_.params(39))/M_.params(38)*M_.params(63);
GTFP0 = M_.params( 80 );
M_.params( 82 ) = M_.params(81);
GYW0 = M_.params( 82 );
M_.params( 150 ) = 1;
UCAP0 = M_.params( 150 );
M_.params( 93 ) = 0.65;
L0 = M_.params( 93 );
M_.params( 52 ) = 1/M_.params(40)-1;
E_EX_R = M_.params( 52 );
-log(BETAE);
M_.params( 51 ) = M_.params(62)+M_.params(52);
E_EX_INOMW = M_.params( 51 );
M_.params( 53 ) = M_.params(51)-M_.params(65);
E_EX_RW = M_.params( 53 );
M_.params( 95 ) = 0;
LYWY0 = M_.params( 95 );
M_.params( 125 ) = (-0.0001);
RXY = M_.params( 125 );
M_.params( 116 ) = 0.887131978334279;
RII = M_.params( 116 );
M_.params( 117 ) = 0.147455589872832;
RIP = M_.params( 117 );
M_.params( 118 ) = 0.120095599681076;
RIX = M_.params( 118 );
M_.params( 119 ) = 0.112067224979767;
RPI = M_.params( 119 );
M_.params( 120 ) = 0.502758194258928;
RPP = M_.params( 120 );
M_.params( 121 ) = 0.082535400836409;
RPX = M_.params( 121 );
M_.params( 122 ) = 0.073730131176521;
RXI = M_.params( 122 );
M_.params( 123 ) = (-0.302655015002645);
RXP = M_.params( 123 );
M_.params( 124 ) = 0.495000246553550;
RXX = M_.params( 124 );
M_.params( 107 ) = 0.24797097628284;
RHOPPI1 = M_.params( 107 );
M_.params( 108 ) = 0.13739098460472;
RHOPPI2 = M_.params( 108 );
M_.params( 109 ) = 0.10483962746747;
RHOPPI3 = M_.params( 109 );
M_.params( 110 ) = 0.09282876044442;
RHOPPI4 = M_.params( 110 );
M_.params( 153 ) = 1.00901606;
interestq_exog = M_.params( 153 );
M_.params( 154 ) = 1.02;
inflationannual_exog = M_.params( 154 );
thispath = cd;                                                           
cd('..');                                                                
load policy_param.mat;                                                   
for i=1:33                                                               
deep_parameter_name = M_.param_names(i,:);                           
eval(['M_.params(i)  = ' deep_parameter_name ' ;'])                  
end                                                                      
cd(thispath);
M_.params( 32 ) = 100;
std_r_ = M_.params( 32 );
M_.params( 34 ) = 1/M_.params(79);
coffispol = M_.params( 34 );
%
% INITVAL instructions
%
options_.initval_file = 0;
oo_.steady_state( 1 ) = 2.4000;
oo_.steady_state( 2 ) = 0;
oo_.steady_state( 3 ) = 0.3862;
oo_.steady_state( 4 ) = 0;
oo_.steady_state( 5 ) = 0;
oo_.steady_state( 6 ) = 0.9000;
oo_.steady_state( 7 ) = 0.0030;
oo_.steady_state( 8 ) = 0.0041;
oo_.steady_state( 9 ) = 0.0030;
oo_.steady_state( 10 ) = 0.0030;
oo_.steady_state( 11 ) = 0;
oo_.steady_state( 12 ) = 0.0030;
oo_.steady_state( 13 ) = 0.0115;
oo_.steady_state( 14 ) = 0.0030;
oo_.steady_state( 15 ) = 0.0041;
oo_.steady_state( 16 ) = 0.0030;
oo_.steady_state( 17 ) = 0.0030;
oo_.steady_state( 18 ) = 0.0041;
oo_.steady_state( 19 ) = 0.0030;
oo_.steady_state( 20 ) = 0.0115;
oo_.steady_state( 21 ) = 0.0030;
oo_.steady_state( 22 ) = 0.0030;
oo_.steady_state( 23 ) = 0;
oo_.steady_state( 24 ) = 0.2030;
oo_.steady_state( 25 ) = 0.0080;
oo_.steady_state( 26 ) = 0.0024;
oo_.steady_state( 27 ) = 0.0013;
oo_.steady_state( 28 ) = 0.0030;
oo_.steady_state( 29 ) = 0;
oo_.steady_state( 30 ) = 0;
oo_.steady_state( 31 ) = 0;
oo_.steady_state( 32 ) = 0.0030;
oo_.steady_state( 33 ) = 0.0041;
oo_.steady_state( 34 ) = 0.0030;
oo_.steady_state( 35 ) = 0.0030;
oo_.steady_state( 36 ) = 0.0090;
oo_.steady_state( 37 ) = 0.0090;
oo_.steady_state( 38 ) = (-0.4308);
oo_.steady_state( 39 ) = (-0.4308);
oo_.steady_state( 40 ) = 0.8755;
oo_.steady_state( 41 ) = (-0.5381);
oo_.steady_state( 42 ) = (-0.9514);
oo_.steady_state( 43 ) = (-0.3702);
oo_.steady_state( 44 ) = (-1.9576);
oo_.steady_state( 45 ) = (-1.5945);
oo_.steady_state( 46 ) = (-3.6889);
oo_.steady_state( 47 ) = (-1.9576);
oo_.steady_state( 48 ) = (-3.5359);
oo_.steady_state( 49 ) = (-4.0963);
oo_.steady_state( 50 ) = (-1.6706);
oo_.steady_state( 51 ) = 0;
oo_.steady_state( 52 ) = 0;
oo_.steady_state( 53 ) = 0;
oo_.steady_state( 54 ) = 0;
oo_.steady_state( 55 ) = (-1.7809);
oo_.steady_state( 56 ) = 4.9955;
oo_.steady_state( 57 ) = 3.9815;
oo_.steady_state( 58 ) = 0;
oo_.steady_state( 59 ) = (-1.8653);
oo_.steady_state( 60 ) = 0.3285;
oo_.steady_state( 61 ) = 0;
oo_.steady_state( 62 ) = 0.9964;
oo_.steady_state( 63 ) = 0.0050;
oo_.steady_state( 64 ) = 0.0050;
oo_.steady_state( 65 ) = 0;
oo_.steady_state( 66 ) = 0.0050;
oo_.steady_state( 67 ) = 0.0010;
oo_.steady_state( 68 ) = 0.0050;
oo_.steady_state( 69 ) = 0.0050;
oo_.steady_state( 70 ) = 0.0010;
oo_.steady_state( 71 ) = 1.0000;
oo_.steady_state( 72 ) = 0.0040;
oo_.steady_state( 73 ) = (-0.0142);
oo_.steady_state( 74 ) = 0;
oo_.steady_state( 75 ) = 0.1827;
oo_.steady_state( 76 ) = 0.3600;
oo_.steady_state( 77 ) = 0.1685;
oo_.steady_state( 78 ) = 0.2000;
oo_.steady_state( 79 ) = 1.0000;
oo_.steady_state( 80 ) = 1.0000;
oo_.steady_state( 81 ) = 19.0679;
oo_.steady_state( 82 ) = 8.8600;
oo_.steady_state( 83 ) = 0.0080;
oo_.steady_state( 84 ) = 0.0030;
oo_.steady_state( 85 ) = 0.4680;
oo_.steady_state( 86 ) = 0.2808;
oo_.steady_state( 87 ) = 0;
oo_.steady_state( 88 ) = 0;
oo_.steady_state( 89 ) = 0;
oo_.steady_state( 90 ) = 0;
oo_.steady_state( 91 ) = 0;
oo_.steady_state( 92 ) = 0;
oo_.steady_state( 93 ) = 0;
oo_.steady_state( 94 ) = 0;
oo_.steady_state( 95 ) = 0;
oo_.steady_state( 96 ) = 0;
oo_.steady_state( 97 ) = 0;
oo_.steady_state( 98 ) = 0;
oo_.steady_state( 99 ) = 0;
oo_.steady_state( 100 ) = 0;
oo_.steady_state( 101 ) = 0.0050;
oo_.steady_state( 102 ) = (-0.5381);
oo_.steady_state( 103 ) = (-1.5945);
oo_.steady_state( 104 ) = (-0.7593);
oo_.steady_state( 106 ) = 0;
oo_.steady_state( 107 ) = 0;
oo_.steady_state( 109 ) = 0;
oo_.steady_state(111)=oo_.steady_state(108);
oo_.steady_state(112)=oo_.steady_state(111);
oo_.steady_state(113)=oo_.steady_state(112);
oo_.steady_state(114)=oo_.steady_state(109);
oo_.steady_state(115)=oo_.steady_state(114);
oo_.steady_state(116)=oo_.steady_state(115);
oo_.steady_state(117)=oo_.steady_state(108);
oo_.steady_state(118)=oo_.steady_state(117);
oo_.steady_state(119)=oo_.steady_state(109);
oo_.steady_state(120)=oo_.steady_state(119);
oo_.steady_state(121)=oo_.steady_state(120);
oo_.steady_state(122)=oo_.steady_state(106);
oo_.steady_state(123)=oo_.steady_state(122);
oo_.steady_state(124)=oo_.steady_state(123);
oo_.steady_state(125)=oo_.steady_state(118);
oo_.steady_state(126)=oo_.steady_state(96);
oo_.steady_state(127)=oo_.steady_state(126);
oo_.steady_state(128)=oo_.steady_state(127);
if M_.exo_nbr > 0
	oo_.exo_simul = ones(M_.maximum_lag,1)*oo_.exo_steady_state';
end
if M_.exo_det_nbr > 0
	oo_.exo_det_simul = ones(M_.maximum_lag,1)*oo_.exo_det_steady_state';
end
%
% SHOCKS instructions
%
M_.exo_det_length = 0;
M_.Sigma_e(1, 1) = (0.0597)^2;
M_.Sigma_e(2, 2) = (0.1500)^2;
M_.Sigma_e(3, 3) = (0.0202)^2;
M_.Sigma_e(4, 4) = (0.0648)^2;
M_.Sigma_e(5, 5) = (0.0044)^2;
M_.Sigma_e(6, 6) = (0.0056)^2;
M_.Sigma_e(7, 7) = (0.0023)^2;
M_.Sigma_e(8, 8) = (0.0283)^2;
M_.Sigma_e(9, 9) = (0.0048)^2;
M_.Sigma_e(10, 10) = (0.0013)^2;
M_.Sigma_e(11, 11) = (0.00312216772065)^2;
M_.Sigma_e(12, 12) = (0.0029)^2;
M_.Sigma_e(13, 13) = (0.0017)^2;
M_.Sigma_e(14, 14) = (0.0070)^2;
M_.Sigma_e(15, 15) = (0.0022)^2;
M_.Sigma_e(16, 16) = (0.0437)^2;
M_.Sigma_e(17, 17) = (0.0121)^2;
M_.Sigma_e(18, 18) = (0.0044)^2;
M_.Sigma_e(20, 20) = (0.0048)^2;
save('EA_QUEST3_results.mat', 'oo_', 'M_', 'options_');
if exist('estim_params_', 'var') == 1
  save('EA_QUEST3_results.mat', 'estim_params_', '-append');
end
if exist('bayestopt_', 'var') == 1
  save('EA_QUEST3_results.mat', 'bayestopt_', '-append');
end
if exist('dataset_', 'var') == 1
  save('EA_QUEST3_results.mat', 'dataset_', '-append');
end
if exist('estimation_info', 'var') == 1
  save('EA_QUEST3_results.mat', 'estimation_info', '-append');
end
if exist('dataset_info', 'var') == 1
  save('EA_QUEST3_results.mat', 'dataset_info', '-append');
end
if exist('oo_recursive_', 'var') == 1
  save('EA_QUEST3_results.mat', 'oo_recursive_', '-append');
end


disp(['Total computing time : ' dynsec2hms(toc(tic0)) ]);
if ~isempty(lastwarn)
  disp('Note: warning(s) encountered in MATLAB/Octave code')
end
diary off
