%
% Status : main Dynare file
%
% Warning : this file is generated automatically by Dynare
%           from model file (.mod)

if isoctave || matlab_ver_less_than('8.6')
    clear all
else
    clearvars -global
    clear_persistent_variables(fileparts(which('dynare')), false)
end
tic0 = tic;
% Save empty dates and dseries objects in memory.
dates('initialize');
dseries('initialize');
% Define global variables.
global M_ options_ oo_ estim_params_ bayestopt_ dataset_ dataset_info estimation_info ys0_ ex0_
options_ = [];
M_.fname = 'NK_CFP10';
M_.dynare_version = '4.5.6';
oo_.dynare_version = '4.5.6';
options_.dynare_version = '4.5.6';
%
% Some global variables initialization
%
global_initialization;
diary off;
diary('NK_CFP10.log');
M_.exo_names = 'eta_a';
M_.exo_names_tex = 'eta\_a';
M_.exo_names_long = 'eta_a';
M_.exo_names = char(M_.exo_names, 'eta_pi');
M_.exo_names_tex = char(M_.exo_names_tex, 'eta\_pi');
M_.exo_names_long = char(M_.exo_names_long, 'eta_pi');
M_.exo_names = char(M_.exo_names, 'eta_n');
M_.exo_names_tex = char(M_.exo_names_tex, 'eta\_n');
M_.exo_names_long = char(M_.exo_names_long, 'eta_n');
M_.exo_names = char(M_.exo_names, 'interest_');
M_.exo_names_tex = char(M_.exo_names_tex, 'interest\_');
M_.exo_names_long = char(M_.exo_names_long, 'interest_');
M_.endo_names = 'y';
M_.endo_names_tex = 'y';
M_.endo_names_long = 'y';
M_.endo_names = char(M_.endo_names, 'yeff');
M_.endo_names_tex = char(M_.endo_names_tex, 'yeff');
M_.endo_names_long = char(M_.endo_names_long, 'yeff');
M_.endo_names = char(M_.endo_names, 'yg');
M_.endo_names_tex = char(M_.endo_names_tex, 'yg');
M_.endo_names_long = char(M_.endo_names_long, 'yg');
M_.endo_names = char(M_.endo_names, 'R');
M_.endo_names_tex = char(M_.endo_names_tex, 'R');
M_.endo_names_long = char(M_.endo_names_long, 'R');
M_.endo_names = char(M_.endo_names, 'pi');
M_.endo_names_tex = char(M_.endo_names_tex, 'pi');
M_.endo_names_long = char(M_.endo_names_long, 'pi');
M_.endo_names = char(M_.endo_names, 'z');
M_.endo_names_tex = char(M_.endo_names_tex, 'z');
M_.endo_names_long = char(M_.endo_names_long, 'z');
M_.endo_names = char(M_.endo_names, 'phi');
M_.endo_names_tex = char(M_.endo_names_tex, 'phi');
M_.endo_names_long = char(M_.endo_names_long, 'phi');
M_.endo_names = char(M_.endo_names, 'e');
M_.endo_names_tex = char(M_.endo_names_tex, 'e');
M_.endo_names_long = char(M_.endo_names_long, 'e');
M_.endo_names = char(M_.endo_names, 'q');
M_.endo_names_tex = char(M_.endo_names_tex, 'q');
M_.endo_names_long = char(M_.endo_names_long, 'q');
M_.endo_names = char(M_.endo_names, 'd');
M_.endo_names_tex = char(M_.endo_names_tex, 'd');
M_.endo_names_long = char(M_.endo_names_long, 'd');
M_.endo_names = char(M_.endo_names, 'L');
M_.endo_names_tex = char(M_.endo_names_tex, 'L');
M_.endo_names_long = char(M_.endo_names_long, 'L');
M_.endo_names = char(M_.endo_names, 'u');
M_.endo_names_tex = char(M_.endo_names_tex, 'u');
M_.endo_names_long = char(M_.endo_names_long, 'u');
M_.endo_names = char(M_.endo_names, 'r');
M_.endo_names_tex = char(M_.endo_names_tex, 'r');
M_.endo_names_long = char(M_.endo_names_long, 'r');
M_.endo_names = char(M_.endo_names, 'w');
M_.endo_names_tex = char(M_.endo_names_tex, 'w');
M_.endo_names_long = char(M_.endo_names_long, 'w');
M_.endo_names = char(M_.endo_names, 'yf');
M_.endo_names_tex = char(M_.endo_names_tex, 'yf');
M_.endo_names_long = char(M_.endo_names_long, 'yf');
M_.endo_names = char(M_.endo_names, 'ygf');
M_.endo_names_tex = char(M_.endo_names_tex, 'ygf');
M_.endo_names_long = char(M_.endo_names_long, 'ygf');
M_.endo_names = char(M_.endo_names, 'Rf');
M_.endo_names_tex = char(M_.endo_names_tex, 'Rf');
M_.endo_names_long = char(M_.endo_names_long, 'Rf');
M_.endo_names = char(M_.endo_names, 'zf');
M_.endo_names_tex = char(M_.endo_names_tex, 'zf');
M_.endo_names_long = char(M_.endo_names_long, 'zf');
M_.endo_names = char(M_.endo_names, 'phif');
M_.endo_names_tex = char(M_.endo_names_tex, 'phif');
M_.endo_names_long = char(M_.endo_names_long, 'phif');
M_.endo_names = char(M_.endo_names, 'ef');
M_.endo_names_tex = char(M_.endo_names_tex, 'ef');
M_.endo_names_long = char(M_.endo_names_long, 'ef');
M_.endo_names = char(M_.endo_names, 'qf');
M_.endo_names_tex = char(M_.endo_names_tex, 'qf');
M_.endo_names_long = char(M_.endo_names_long, 'qf');
M_.endo_names = char(M_.endo_names, 'df');
M_.endo_names_tex = char(M_.endo_names_tex, 'df');
M_.endo_names_long = char(M_.endo_names_long, 'df');
M_.endo_names = char(M_.endo_names, 'Lf');
M_.endo_names_tex = char(M_.endo_names_tex, 'Lf');
M_.endo_names_long = char(M_.endo_names_long, 'Lf');
M_.endo_names = char(M_.endo_names, 'uf');
M_.endo_names_tex = char(M_.endo_names_tex, 'uf');
M_.endo_names_long = char(M_.endo_names_long, 'uf');
M_.endo_names = char(M_.endo_names, 'rf');
M_.endo_names_tex = char(M_.endo_names_tex, 'rf');
M_.endo_names_long = char(M_.endo_names_long, 'rf');
M_.endo_names = char(M_.endo_names, 'wf');
M_.endo_names_tex = char(M_.endo_names_tex, 'wf');
M_.endo_names_long = char(M_.endo_names_long, 'wf');
M_.endo_names = char(M_.endo_names, 'a');
M_.endo_names_tex = char(M_.endo_names_tex, 'a');
M_.endo_names_long = char(M_.endo_names_long, 'a');
M_.endo_names = char(M_.endo_names, 'eps_pi');
M_.endo_names_tex = char(M_.endo_names_tex, 'eps\_pi');
M_.endo_names_long = char(M_.endo_names_long, 'eps_pi');
M_.endo_names = char(M_.endo_names, 'n');
M_.endo_names_tex = char(M_.endo_names_tex, 'n');
M_.endo_names_long = char(M_.endo_names_long, 'n');
M_.endo_names = char(M_.endo_names, 'interest');
M_.endo_names_tex = char(M_.endo_names_tex, 'interest');
M_.endo_names_long = char(M_.endo_names_long, 'interest');
M_.endo_names = char(M_.endo_names, 'inflation');
M_.endo_names_tex = char(M_.endo_names_tex, 'inflation');
M_.endo_names_long = char(M_.endo_names_long, 'inflation');
M_.endo_names = char(M_.endo_names, 'inflationq');
M_.endo_names_tex = char(M_.endo_names_tex, 'inflationq');
M_.endo_names_long = char(M_.endo_names_long, 'inflationq');
M_.endo_names = char(M_.endo_names, 'outputgap');
M_.endo_names_tex = char(M_.endo_names_tex, 'outputgap');
M_.endo_names_long = char(M_.endo_names_long, 'outputgap');
M_.endo_names = char(M_.endo_names, 'output');
M_.endo_names_tex = char(M_.endo_names_tex, 'output');
M_.endo_names_long = char(M_.endo_names_long, 'output');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_75');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_75');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_75');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_79');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_79');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_79');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_83');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_83');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_83');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_110');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_110');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_110');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_114');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_114');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_114');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_118');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_118');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_118');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_145');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_145');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_145');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_149');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_149');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_149');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_153');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_153');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_153');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_4_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_4\_1');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_4_1');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_4_2');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_4\_2');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_4_2');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_33_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_33\_1');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_33_1');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_33_2');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_33\_2');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_33_2');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_33_3');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_33\_3');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_33_3');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_32_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_32\_1');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_32_1');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_32_2');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_32\_2');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_32_2');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_32_3');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_32\_3');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_32_3');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_29_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_29\_1');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_29_1');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_29_2');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_29\_2');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_29_2');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_29_3');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_29\_3');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_29_3');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_31_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_31\_1');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_31_1');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_31_2');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_31\_2');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_31_2');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_31_3');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_31\_3');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_31_3');
M_.endo_partitions = struct();
M_.param_names = 'cofintintb1';
M_.param_names_tex = 'cofintintb1';
M_.param_names_long = 'cofintintb1';
M_.param_names = char(M_.param_names, 'cofintintb2');
M_.param_names_tex = char(M_.param_names_tex, 'cofintintb2');
M_.param_names_long = char(M_.param_names_long, 'cofintintb2');
M_.param_names = char(M_.param_names, 'cofintintb3');
M_.param_names_tex = char(M_.param_names_tex, 'cofintintb3');
M_.param_names_long = char(M_.param_names_long, 'cofintintb3');
M_.param_names = char(M_.param_names, 'cofintintb4');
M_.param_names_tex = char(M_.param_names_tex, 'cofintintb4');
M_.param_names_long = char(M_.param_names_long, 'cofintintb4');
M_.param_names = char(M_.param_names, 'cofintinf0');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinf0');
M_.param_names_long = char(M_.param_names_long, 'cofintinf0');
M_.param_names = char(M_.param_names, 'cofintinfb1');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinfb1');
M_.param_names_long = char(M_.param_names_long, 'cofintinfb1');
M_.param_names = char(M_.param_names, 'cofintinfb2');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinfb2');
M_.param_names_long = char(M_.param_names_long, 'cofintinfb2');
M_.param_names = char(M_.param_names, 'cofintinfb3');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinfb3');
M_.param_names_long = char(M_.param_names_long, 'cofintinfb3');
M_.param_names = char(M_.param_names, 'cofintinfb4');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinfb4');
M_.param_names_long = char(M_.param_names_long, 'cofintinfb4');
M_.param_names = char(M_.param_names, 'cofintinff1');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinff1');
M_.param_names_long = char(M_.param_names_long, 'cofintinff1');
M_.param_names = char(M_.param_names, 'cofintinff2');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinff2');
M_.param_names_long = char(M_.param_names_long, 'cofintinff2');
M_.param_names = char(M_.param_names, 'cofintinff3');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinff3');
M_.param_names_long = char(M_.param_names_long, 'cofintinff3');
M_.param_names = char(M_.param_names, 'cofintinff4');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinff4');
M_.param_names_long = char(M_.param_names_long, 'cofintinff4');
M_.param_names = char(M_.param_names, 'cofintout');
M_.param_names_tex = char(M_.param_names_tex, 'cofintout');
M_.param_names_long = char(M_.param_names_long, 'cofintout');
M_.param_names = char(M_.param_names, 'cofintoutb1');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutb1');
M_.param_names_long = char(M_.param_names_long, 'cofintoutb1');
M_.param_names = char(M_.param_names, 'cofintoutb2');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutb2');
M_.param_names_long = char(M_.param_names_long, 'cofintoutb2');
M_.param_names = char(M_.param_names, 'cofintoutb3');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutb3');
M_.param_names_long = char(M_.param_names_long, 'cofintoutb3');
M_.param_names = char(M_.param_names, 'cofintoutb4');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutb4');
M_.param_names_long = char(M_.param_names_long, 'cofintoutb4');
M_.param_names = char(M_.param_names, 'cofintoutf1');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutf1');
M_.param_names_long = char(M_.param_names_long, 'cofintoutf1');
M_.param_names = char(M_.param_names, 'cofintoutf2');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutf2');
M_.param_names_long = char(M_.param_names_long, 'cofintoutf2');
M_.param_names = char(M_.param_names, 'cofintoutf3');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutf3');
M_.param_names_long = char(M_.param_names_long, 'cofintoutf3');
M_.param_names = char(M_.param_names, 'cofintoutf4');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutf4');
M_.param_names_long = char(M_.param_names_long, 'cofintoutf4');
M_.param_names = char(M_.param_names, 'cofintoutp');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutp');
M_.param_names_long = char(M_.param_names_long, 'cofintoutp');
M_.param_names = char(M_.param_names, 'cofintoutpb1');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpb1');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpb1');
M_.param_names = char(M_.param_names, 'cofintoutpb2');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpb2');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpb2');
M_.param_names = char(M_.param_names, 'cofintoutpb3');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpb3');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpb3');
M_.param_names = char(M_.param_names, 'cofintoutpb4');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpb4');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpb4');
M_.param_names = char(M_.param_names, 'cofintoutpf1');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpf1');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpf1');
M_.param_names = char(M_.param_names, 'cofintoutpf2');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpf2');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpf2');
M_.param_names = char(M_.param_names, 'cofintoutpf3');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpf3');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpf3');
M_.param_names = char(M_.param_names, 'cofintoutpf4');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpf4');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpf4');
M_.param_names = char(M_.param_names, 'std_r_');
M_.param_names_tex = char(M_.param_names_tex, 'std\_r\_');
M_.param_names_long = char(M_.param_names_long, 'std_r_');
M_.param_names = char(M_.param_names, 'std_r_quart');
M_.param_names_tex = char(M_.param_names_tex, 'std\_r\_quart');
M_.param_names_long = char(M_.param_names_long, 'std_r_quart');
M_.param_names = char(M_.param_names, 'coffispol');
M_.param_names_tex = char(M_.param_names_tex, 'coffispol');
M_.param_names_long = char(M_.param_names_long, 'coffispol');
M_.param_names = char(M_.param_names, 'betta');
M_.param_names_tex = char(M_.param_names_tex, '\beta');
M_.param_names_long = char(M_.param_names_long, 'betta');
M_.param_names = char(M_.param_names, 'sig');
M_.param_names_tex = char(M_.param_names_tex, '\sigma');
M_.param_names_long = char(M_.param_names_long, 'sig');
M_.param_names = char(M_.param_names, 'thet');
M_.param_names_tex = char(M_.param_names_tex, '\thet');
M_.param_names_long = char(M_.param_names_long, 'thet');
M_.param_names = char(M_.param_names, 'eps');
M_.param_names_tex = char(M_.param_names_tex, '\epsilon');
M_.param_names_long = char(M_.param_names_long, 'eps');
M_.param_names = char(M_.param_names, 'alfa');
M_.param_names_tex = char(M_.param_names_tex, '\alpha');
M_.param_names_long = char(M_.param_names_long, 'alfa');
M_.param_names = char(M_.param_names, 'b');
M_.param_names_tex = char(M_.param_names_tex, 'b');
M_.param_names_long = char(M_.param_names_long, 'b');
M_.param_names = char(M_.param_names, 'Lam');
M_.param_names_tex = char(M_.param_names_tex, '\Lambda');
M_.param_names_long = char(M_.param_names_long, 'Lam');
M_.param_names = char(M_.param_names, 'varphi');
M_.param_names_tex = char(M_.param_names_tex, '\varphi');
M_.param_names_long = char(M_.param_names_long, 'varphi');
M_.param_names = char(M_.param_names, 'lam');
M_.param_names_tex = char(M_.param_names_tex, '\lambda');
M_.param_names_long = char(M_.param_names_long, 'lam');
M_.param_names = char(M_.param_names, 'rho_a');
M_.param_names_tex = char(M_.param_names_tex, '\rho_a');
M_.param_names_long = char(M_.param_names_long, 'rho_a');
M_.param_names = char(M_.param_names, 'rho_R');
M_.param_names_tex = char(M_.param_names_tex, '\rho_R');
M_.param_names_long = char(M_.param_names_long, 'rho_R');
M_.param_names = char(M_.param_names, 'rho_pi');
M_.param_names_tex = char(M_.param_names_tex, '\rho_\pi');
M_.param_names_long = char(M_.param_names_long, 'rho_pi');
M_.param_names = char(M_.param_names, 'rho_n');
M_.param_names_tex = char(M_.param_names_tex, '\rho_n');
M_.param_names_long = char(M_.param_names_long, 'rho_n');
M_.param_names = char(M_.param_names, 'tau');
M_.param_names_tex = char(M_.param_names_tex, '\tau');
M_.param_names_long = char(M_.param_names_long, 'tau');
M_.param_names = char(M_.param_names, 'tau_g');
M_.param_names_tex = char(M_.param_names_tex, '\tau_g');
M_.param_names_long = char(M_.param_names_long, 'tau_g');
M_.param_partitions = struct();
M_.exo_det_nbr = 0;
M_.exo_nbr = 4;
M_.endo_nbr = 57;
M_.param_nbr = 49;
M_.orig_endo_nbr = 34;
M_.aux_vars(1).endo_index = 35;
M_.aux_vars(1).type = 0;
M_.aux_vars(2).endo_index = 36;
M_.aux_vars(2).type = 0;
M_.aux_vars(3).endo_index = 37;
M_.aux_vars(3).type = 0;
M_.aux_vars(4).endo_index = 38;
M_.aux_vars(4).type = 0;
M_.aux_vars(5).endo_index = 39;
M_.aux_vars(5).type = 0;
M_.aux_vars(6).endo_index = 40;
M_.aux_vars(6).type = 0;
M_.aux_vars(7).endo_index = 41;
M_.aux_vars(7).type = 0;
M_.aux_vars(8).endo_index = 42;
M_.aux_vars(8).type = 0;
M_.aux_vars(9).endo_index = 43;
M_.aux_vars(9).type = 0;
M_.aux_vars(10).endo_index = 44;
M_.aux_vars(10).type = 1;
M_.aux_vars(10).orig_index = 5;
M_.aux_vars(10).orig_lead_lag = -1;
M_.aux_vars(11).endo_index = 45;
M_.aux_vars(11).type = 1;
M_.aux_vars(11).orig_index = 5;
M_.aux_vars(11).orig_lead_lag = -2;
M_.aux_vars(12).endo_index = 46;
M_.aux_vars(12).type = 1;
M_.aux_vars(12).orig_index = 34;
M_.aux_vars(12).orig_lead_lag = -1;
M_.aux_vars(13).endo_index = 47;
M_.aux_vars(13).type = 1;
M_.aux_vars(13).orig_index = 34;
M_.aux_vars(13).orig_lead_lag = -2;
M_.aux_vars(14).endo_index = 48;
M_.aux_vars(14).type = 1;
M_.aux_vars(14).orig_index = 34;
M_.aux_vars(14).orig_lead_lag = -3;
M_.aux_vars(15).endo_index = 49;
M_.aux_vars(15).type = 1;
M_.aux_vars(15).orig_index = 33;
M_.aux_vars(15).orig_lead_lag = -1;
M_.aux_vars(16).endo_index = 50;
M_.aux_vars(16).type = 1;
M_.aux_vars(16).orig_index = 33;
M_.aux_vars(16).orig_lead_lag = -2;
M_.aux_vars(17).endo_index = 51;
M_.aux_vars(17).type = 1;
M_.aux_vars(17).orig_index = 33;
M_.aux_vars(17).orig_lead_lag = -3;
M_.aux_vars(18).endo_index = 52;
M_.aux_vars(18).type = 1;
M_.aux_vars(18).orig_index = 30;
M_.aux_vars(18).orig_lead_lag = -1;
M_.aux_vars(19).endo_index = 53;
M_.aux_vars(19).type = 1;
M_.aux_vars(19).orig_index = 30;
M_.aux_vars(19).orig_lead_lag = -2;
M_.aux_vars(20).endo_index = 54;
M_.aux_vars(20).type = 1;
M_.aux_vars(20).orig_index = 30;
M_.aux_vars(20).orig_lead_lag = -3;
M_.aux_vars(21).endo_index = 55;
M_.aux_vars(21).type = 1;
M_.aux_vars(21).orig_index = 32;
M_.aux_vars(21).orig_lead_lag = -1;
M_.aux_vars(22).endo_index = 56;
M_.aux_vars(22).type = 1;
M_.aux_vars(22).orig_index = 32;
M_.aux_vars(22).orig_lead_lag = -2;
M_.aux_vars(23).endo_index = 57;
M_.aux_vars(23).type = 1;
M_.aux_vars(23).orig_index = 32;
M_.aux_vars(23).orig_lead_lag = -3;
M_.Sigma_e = zeros(4, 4);
M_.Correlation_matrix = eye(4, 4);
M_.H = 0;
M_.Correlation_matrix_ME = 1;
M_.sigma_e_is_diagonal = 1;
M_.det_shocks = [];
options_.linear = 1;
options_.block=0;
options_.bytecode=0;
options_.use_dll=0;
M_.hessian_eq_zero = 1;
erase_compiled_function('NK_CFP10_static');
erase_compiled_function('NK_CFP10_dynamic');
M_.orig_eq_nbr = 34;
M_.eq_nbr = 57;
M_.ramsey_eq_nbr = 0;
M_.set_auxiliary_variables = exist(['./' M_.fname '_set_auxiliary_variables.m'], 'file') == 2;
M_.lead_lag_incidence = [
 0 25 82;
 0 26 0;
 0 27 83;
 0 28 0;
 1 29 84;
 0 30 0;
 0 31 85;
 2 32 0;
 0 33 0;
 0 34 0;
 0 35 0;
 0 36 0;
 0 37 0;
 0 38 0;
 0 39 86;
 0 40 87;
 0 41 0;
 0 42 0;
 0 43 88;
 3 44 0;
 0 45 0;
 0 46 0;
 0 47 0;
 0 48 0;
 0 49 0;
 0 50 0;
 4 51 89;
 5 52 0;
 6 53 90;
 7 54 0;
 0 55 0;
 8 56 91;
 9 57 92;
 10 58 93;
 0 59 94;
 0 60 95;
 0 61 96;
 0 62 97;
 0 63 98;
 0 64 99;
 0 65 100;
 0 66 101;
 0 67 102;
 11 68 0;
 12 69 0;
 13 70 0;
 14 71 0;
 15 72 0;
 16 73 0;
 17 74 0;
 18 75 0;
 19 76 0;
 20 77 0;
 21 78 0;
 22 79 0;
 23 80 0;
 24 81 0;]';
M_.nstatic = 18;
M_.nfwrd   = 15;
M_.npred   = 18;
M_.nboth   = 6;
M_.nsfwrd   = 21;
M_.nspred   = 24;
M_.ndynamic   = 39;
M_.equations_tags = {
  7 , 'name' , '(A1)' ;
  8 , 'name' , '(A2)' ;
  9 , 'name' , '(A3)' ;
  10 , 'name' , '(A4) rewritten as in (35)' ;
  11 , 'name' , '(A5)' ;
  12 , 'name' , '(A6) rewritten as in (34)' ;
  13 , 'name' , '(A7) rewritten as in (19)' ;
  14 , 'name' , '(A8)' ;
  15 , 'name' , '(A9)' ;
  16 , 'name' , '(A10)' ;
  17 , 'name' , '(A11)' ;
  18 , 'name' , 'Output without price and credit frictions' ;
  19 , 'name' , 'Output gap' ;
  20 , 'name' , '(A1f)' ;
  21 , 'name' , '(A2f)' ;
  22 , 'name' , '(A3f)' ;
  23 , 'name' , '(A4) rewritten as in (35)' ;
  24 , 'name' , '(A5)' ;
  25 , 'name' , '(A6) rewritten as in (34)' ;
  26 , 'name' , '(A7) rewritten as in (19)' ;
  27 , 'name' , '(A8)' ;
  28 , 'name' , '(A9)' ;
  29 , 'name' , '(A10)' ;
  30 , 'name' , '(A11)' ;
  31 , 'name' , 'Output gap' ;
  32 , 'name' , 'Technology' ;
  33 , 'name' , 'Mark-up shock' ;
  34 , 'name' , 'Net worth shock' ;
};
M_.static_and_dynamic_models_differ = 0;
M_.exo_names_orig_ord = [1:4];
M_.maximum_lag = 1;
M_.maximum_lead = 1;
M_.maximum_endo_lag = 1;
M_.maximum_endo_lead = 1;
oo_.steady_state = zeros(57, 1);
M_.maximum_exo_lag = 0;
M_.maximum_exo_lead = 0;
oo_.exo_steady_state = zeros(4, 1);
M_.params = NaN(49, 1);
M_.NNZDerivatives = [198; 0; -1];
M_.params( 35 ) = 0.99;
betta = M_.params( 35 );
M_.params( 36 ) = 0.16;
sig = M_.params( 36 );
M_.params( 37 ) = 0.47;
thet = M_.params( 37 );
M_.params( 38 ) = 10;
eps = M_.params( 38 );
M_.params( 39 ) = 0.50;
alfa = M_.params( 39 );
M_.params( 40 ) = 0.20;
b = M_.params( 40 );
M_.params( 41 ) = M_.params(40)-1;
Lam = M_.params( 41 );
M_.params( 42 ) = 173.08;
varphi = M_.params( 42 );
M_.params( 43 ) = (M_.params(38)-1)/M_.params(42);
lam = M_.params( 43 );
M_.params( 44 ) = 0.95;
rho_a = M_.params( 44 );
M_.params( 47 ) = 0.90;
rho_n = M_.params( 47 );
M_.params( 46 ) = 0.90;
rho_pi = M_.params( 46 );
M_.params( 45 ) = 0.40;
rho_R = M_.params( 45 );
M_.params( 48 ) = 1.5;
tau = M_.params( 48 );
M_.params( 49 ) = 0.5;
tau_g = M_.params( 49 );
thispath = cd;                                                           
cd('..');                                                                
load policy_param.mat;                                                   
for i=1:33                                                               
deep_parameter_name = M_.param_names(i,:);                           
eval(['M_.params(i)  = ' deep_parameter_name ' ;'])                  
end                                                                      
cd(thispath);  
M_.params( 32 ) = 100;
std_r_ = M_.params( 32 );
M_.params( 34 ) = 1;
coffispol = M_.params( 34 );
%
% SHOCKS instructions
%
M_.exo_det_length = 0;
M_.Sigma_e(1, 1) = (1)^2;
M_.Sigma_e(2, 2) = (1)^2;
M_.Sigma_e(3, 3) = (1)^2;
M_.Sigma_e(4, 4) = (1)^2;
save('NK_CFP10_results.mat', 'oo_', 'M_', 'options_');
if exist('estim_params_', 'var') == 1
  save('NK_CFP10_results.mat', 'estim_params_', '-append');
end
if exist('bayestopt_', 'var') == 1
  save('NK_CFP10_results.mat', 'bayestopt_', '-append');
end
if exist('dataset_', 'var') == 1
  save('NK_CFP10_results.mat', 'dataset_', '-append');
end
if exist('estimation_info', 'var') == 1
  save('NK_CFP10_results.mat', 'estimation_info', '-append');
end
if exist('dataset_info', 'var') == 1
  save('NK_CFP10_results.mat', 'dataset_info', '-append');
end
if exist('oo_recursive_', 'var') == 1
  save('NK_CFP10_results.mat', 'oo_recursive_', '-append');
end


disp(['Total computing time : ' dynsec2hms(toc(tic0)) ]);
if ~isempty(lastwarn)
  disp('Note: warning(s) encountered in MATLAB/Octave code')
end
diary off
