%
% Status : main Dynare file
%
% Warning : this file is generated automatically by Dynare
%           from model file (.mod)

if isoctave || matlab_ver_less_than('8.6')
    clear all
else
    clearvars -global
    clear_persistent_variables(fileparts(which('dynare')), false)
end
tic0 = tic;
% Save empty dates and dseries objects in memory.
dates('initialize');
dseries('initialize');
% Define global variables.
global M_ options_ oo_ estim_params_ bayestopt_ dataset_ dataset_info estimation_info ys0_ ex0_
options_ = [];
M_.fname = 'EAES_RA09';
M_.dynare_version = '4.5.6';
oo_.dynare_version = '4.5.6';
options_.dynare_version = '4.5.6';
%
% Some global variables initialization
%
global_initialization;
diary off;
diary('EAES_RA09.log');
M_.exo_names = 'eps_ZT';
M_.exo_names_tex = 'eps\_ZT';
M_.exo_names_long = 'eps_ZT';
M_.exo_names = char(M_.exo_names, 'eps_ZN');
M_.exo_names_tex = char(M_.exo_names_tex, 'eps\_ZN');
M_.exo_names_long = char(M_.exo_names_long, 'eps_ZN');
M_.exo_names = char(M_.exo_names, 'eps_ZT_star');
M_.exo_names_tex = char(M_.exo_names_tex, 'eps\_ZT\_star');
M_.exo_names_long = char(M_.exo_names_long, 'eps_ZT_star');
M_.exo_names = char(M_.exo_names, 'eps_Z');
M_.exo_names_tex = char(M_.exo_names_tex, 'eps\_Z');
M_.exo_names_long = char(M_.exo_names_long, 'eps_Z');
M_.exo_names = char(M_.exo_names, 'eps_ZN_star');
M_.exo_names_tex = char(M_.exo_names_tex, 'eps\_ZN\_star');
M_.exo_names_long = char(M_.exo_names_long, 'eps_ZN_star');
M_.exo_names = char(M_.exo_names, 'eps_GT');
M_.exo_names_tex = char(M_.exo_names_tex, 'eps\_GT');
M_.exo_names_long = char(M_.exo_names_long, 'eps_GT');
M_.exo_names = char(M_.exo_names, 'eps_GN');
M_.exo_names_tex = char(M_.exo_names_tex, 'eps\_GN');
M_.exo_names_long = char(M_.exo_names_long, 'eps_GN');
M_.exo_names = char(M_.exo_names, 'eps_GT_star');
M_.exo_names_tex = char(M_.exo_names_tex, 'eps\_GT\_star');
M_.exo_names_long = char(M_.exo_names_long, 'eps_GT_star');
M_.exo_names = char(M_.exo_names, 'eps_GN_star');
M_.exo_names_tex = char(M_.exo_names_tex, 'eps\_GN\_star');
M_.exo_names_long = char(M_.exo_names_long, 'eps_GN_star');
M_.exo_names = char(M_.exo_names, 'interest_');
M_.exo_names_tex = char(M_.exo_names_tex, 'interest\_');
M_.exo_names_long = char(M_.exo_names_long, 'interest_');
M_.endo_names = 'dy';
M_.endo_names_tex = 'dy';
M_.endo_names_long = 'dy';
M_.endo_names = char(M_.endo_names, 'dy_star');
M_.endo_names_tex = char(M_.endo_names_tex, 'dy\_star');
M_.endo_names_long = char(M_.endo_names_long, 'dy_star');
M_.endo_names = char(M_.endo_names, 'mu');
M_.endo_names_tex = char(M_.endo_names_tex, 'mu');
M_.endo_names_long = char(M_.endo_names_long, 'mu');
M_.endo_names = char(M_.endo_names, 'r');
M_.endo_names_tex = char(M_.endo_names_tex, 'r');
M_.endo_names_long = char(M_.endo_names_long, 'r');
M_.endo_names = char(M_.endo_names, 'pi');
M_.endo_names_tex = char(M_.endo_names_tex, 'pi');
M_.endo_names_long = char(M_.endo_names_long, 'pi');
M_.endo_names = char(M_.endo_names, 'c');
M_.endo_names_tex = char(M_.endo_names_tex, 'c');
M_.endo_names_long = char(M_.endo_names_long, 'c');
M_.endo_names = char(M_.endo_names, 'mu_star');
M_.endo_names_tex = char(M_.endo_names_tex, 'mu\_star');
M_.endo_names_long = char(M_.endo_names_long, 'mu_star');
M_.endo_names = char(M_.endo_names, 'c_star');
M_.endo_names_tex = char(M_.endo_names_tex, 'c\_star');
M_.endo_names_long = char(M_.endo_names_long, 'c_star');
M_.endo_names = char(M_.endo_names, 'rer');
M_.endo_names_tex = char(M_.endo_names_tex, 'rer');
M_.endo_names_long = char(M_.endo_names_long, 'rer');
M_.endo_names = char(M_.endo_names, 't_N');
M_.endo_names_tex = char(M_.endo_names_tex, 't\_N');
M_.endo_names_long = char(M_.endo_names_long, 't_N');
M_.endo_names = char(M_.endo_names, 't_H');
M_.endo_names_tex = char(M_.endo_names_tex, 't\_H');
M_.endo_names_long = char(M_.endo_names_long, 't_H');
M_.endo_names = char(M_.endo_names, 't_F');
M_.endo_names_tex = char(M_.endo_names_tex, 't\_F');
M_.endo_names_long = char(M_.endo_names_long, 't_F');
M_.endo_names = char(M_.endo_names, 't_T');
M_.endo_names_tex = char(M_.endo_names_tex, 't\_T');
M_.endo_names_long = char(M_.endo_names_long, 't_T');
M_.endo_names = char(M_.endo_names, 't_N_star');
M_.endo_names_tex = char(M_.endo_names_tex, 't\_N\_star');
M_.endo_names_long = char(M_.endo_names_long, 't_N_star');
M_.endo_names = char(M_.endo_names, 't_H_star');
M_.endo_names_tex = char(M_.endo_names_tex, 't\_H\_star');
M_.endo_names_long = char(M_.endo_names_long, 't_H_star');
M_.endo_names = char(M_.endo_names, 't_F_star');
M_.endo_names_tex = char(M_.endo_names_tex, 't\_F\_star');
M_.endo_names_long = char(M_.endo_names_long, 't_F_star');
M_.endo_names = char(M_.endo_names, 't_T_star');
M_.endo_names_tex = char(M_.endo_names_tex, 't\_T\_star');
M_.endo_names_long = char(M_.endo_names_long, 't_T_star');
M_.endo_names = char(M_.endo_names, 'c_H');
M_.endo_names_tex = char(M_.endo_names_tex, 'c\_H');
M_.endo_names_long = char(M_.endo_names_long, 'c_H');
M_.endo_names = char(M_.endo_names, 'c_F');
M_.endo_names_tex = char(M_.endo_names_tex, 'c\_F');
M_.endo_names_long = char(M_.endo_names_long, 'c_F');
M_.endo_names = char(M_.endo_names, 'c_N');
M_.endo_names_tex = char(M_.endo_names_tex, 'c\_N');
M_.endo_names_long = char(M_.endo_names_long, 'c_N');
M_.endo_names = char(M_.endo_names, 'c_H_star');
M_.endo_names_tex = char(M_.endo_names_tex, 'c\_H\_star');
M_.endo_names_long = char(M_.endo_names_long, 'c_H_star');
M_.endo_names = char(M_.endo_names, 'c_F_star');
M_.endo_names_tex = char(M_.endo_names_tex, 'c\_F\_star');
M_.endo_names_long = char(M_.endo_names_long, 'c_F_star');
M_.endo_names = char(M_.endo_names, 'c_N_star');
M_.endo_names_tex = char(M_.endo_names_tex, 'c\_N\_star');
M_.endo_names_long = char(M_.endo_names_long, 'c_N_star');
M_.endo_names = char(M_.endo_names, 'l');
M_.endo_names_tex = char(M_.endo_names_tex, 'l');
M_.endo_names_long = char(M_.endo_names_long, 'l');
M_.endo_names = char(M_.endo_names, 'w');
M_.endo_names_tex = char(M_.endo_names_tex, 'w');
M_.endo_names_long = char(M_.endo_names_long, 'w');
M_.endo_names = char(M_.endo_names, 'l_star');
M_.endo_names_tex = char(M_.endo_names_tex, 'l\_star');
M_.endo_names_long = char(M_.endo_names_long, 'l_star');
M_.endo_names = char(M_.endo_names, 'w_star');
M_.endo_names_tex = char(M_.endo_names_tex, 'w\_star');
M_.endo_names_long = char(M_.endo_names_long, 'w_star');
M_.endo_names = char(M_.endo_names, 'l_N');
M_.endo_names_tex = char(M_.endo_names_tex, 'l\_N');
M_.endo_names_long = char(M_.endo_names_long, 'l_N');
M_.endo_names = char(M_.endo_names, 'l_T');
M_.endo_names_tex = char(M_.endo_names_tex, 'l\_T');
M_.endo_names_long = char(M_.endo_names_long, 'l_T');
M_.endo_names = char(M_.endo_names, 'l_N_star');
M_.endo_names_tex = char(M_.endo_names_tex, 'l\_N\_star');
M_.endo_names_long = char(M_.endo_names_long, 'l_N_star');
M_.endo_names = char(M_.endo_names, 'l_T_star');
M_.endo_names_tex = char(M_.endo_names_tex, 'l\_T\_star');
M_.endo_names_long = char(M_.endo_names_long, 'l_T_star');
M_.endo_names = char(M_.endo_names, 'y_N');
M_.endo_names_tex = char(M_.endo_names_tex, 'y\_N');
M_.endo_names_long = char(M_.endo_names_long, 'y_N');
M_.endo_names = char(M_.endo_names, 'z_N');
M_.endo_names_tex = char(M_.endo_names_tex, 'z\_N');
M_.endo_names_long = char(M_.endo_names_long, 'z_N');
M_.endo_names = char(M_.endo_names, 'y_H');
M_.endo_names_tex = char(M_.endo_names_tex, 'y\_H');
M_.endo_names_long = char(M_.endo_names_long, 'y_H');
M_.endo_names = char(M_.endo_names, 'z_T');
M_.endo_names_tex = char(M_.endo_names_tex, 'z\_T');
M_.endo_names_long = char(M_.endo_names_long, 'z_T');
M_.endo_names = char(M_.endo_names, 'y_N_star');
M_.endo_names_tex = char(M_.endo_names_tex, 'y\_N\_star');
M_.endo_names_long = char(M_.endo_names_long, 'y_N_star');
M_.endo_names = char(M_.endo_names, 'z_N_star');
M_.endo_names_tex = char(M_.endo_names_tex, 'z\_N\_star');
M_.endo_names_long = char(M_.endo_names_long, 'z_N_star');
M_.endo_names = char(M_.endo_names, 'y_F_star');
M_.endo_names_tex = char(M_.endo_names_tex, 'y\_F\_star');
M_.endo_names_long = char(M_.endo_names_long, 'y_F_star');
M_.endo_names = char(M_.endo_names, 'z_T_star');
M_.endo_names_tex = char(M_.endo_names_tex, 'z\_T\_star');
M_.endo_names_long = char(M_.endo_names_long, 'z_T_star');
M_.endo_names = char(M_.endo_names, 'pi_H');
M_.endo_names_tex = char(M_.endo_names_tex, 'pi\_H');
M_.endo_names_long = char(M_.endo_names_long, 'pi_H');
M_.endo_names = char(M_.endo_names, 'pi_N');
M_.endo_names_tex = char(M_.endo_names_tex, 'pi\_N');
M_.endo_names_long = char(M_.endo_names_long, 'pi_N');
M_.endo_names = char(M_.endo_names, 'pi_N_star');
M_.endo_names_tex = char(M_.endo_names_tex, 'pi\_N\_star');
M_.endo_names_long = char(M_.endo_names_long, 'pi_N_star');
M_.endo_names = char(M_.endo_names, 'pi_F');
M_.endo_names_tex = char(M_.endo_names_tex, 'pi\_F');
M_.endo_names_long = char(M_.endo_names_long, 'pi_F');
M_.endo_names = char(M_.endo_names, 'pi_star');
M_.endo_names_tex = char(M_.endo_names_tex, 'pi\_star');
M_.endo_names_long = char(M_.endo_names_long, 'pi_star');
M_.endo_names = char(M_.endo_names, 'pi_EMU');
M_.endo_names_tex = char(M_.endo_names_tex, 'pi\_EMU');
M_.endo_names_long = char(M_.endo_names_long, 'pi_EMU');
M_.endo_names = char(M_.endo_names, 'g_N');
M_.endo_names_tex = char(M_.endo_names_tex, 'g\_N');
M_.endo_names_long = char(M_.endo_names_long, 'g_N');
M_.endo_names = char(M_.endo_names, 'g_T');
M_.endo_names_tex = char(M_.endo_names_tex, 'g\_T');
M_.endo_names_long = char(M_.endo_names_long, 'g_T');
M_.endo_names = char(M_.endo_names, 'g_N_star');
M_.endo_names_tex = char(M_.endo_names_tex, 'g\_N\_star');
M_.endo_names_long = char(M_.endo_names_long, 'g_N_star');
M_.endo_names = char(M_.endo_names, 'g_T_star');
M_.endo_names_tex = char(M_.endo_names_tex, 'g\_T\_star');
M_.endo_names_long = char(M_.endo_names_long, 'g_T_star');
M_.endo_names = char(M_.endo_names, 'y');
M_.endo_names_tex = char(M_.endo_names_tex, 'y');
M_.endo_names_long = char(M_.endo_names_long, 'y');
M_.endo_names = char(M_.endo_names, 'y_star');
M_.endo_names_tex = char(M_.endo_names_tex, 'y\_star');
M_.endo_names_long = char(M_.endo_names_long, 'y_star');
M_.endo_names = char(M_.endo_names, 'y_EMU');
M_.endo_names_tex = char(M_.endo_names_tex, 'y\_EMU');
M_.endo_names_long = char(M_.endo_names_long, 'y_EMU');
M_.endo_names = char(M_.endo_names, 'interest');
M_.endo_names_tex = char(M_.endo_names_tex, 'interest');
M_.endo_names_long = char(M_.endo_names_long, 'interest');
M_.endo_names = char(M_.endo_names, 'inflation');
M_.endo_names_tex = char(M_.endo_names_tex, 'inflation');
M_.endo_names_long = char(M_.endo_names_long, 'inflation');
M_.endo_names = char(M_.endo_names, 'inflationq');
M_.endo_names_tex = char(M_.endo_names_tex, 'inflationq');
M_.endo_names_long = char(M_.endo_names_long, 'inflationq');
M_.endo_names = char(M_.endo_names, 'output');
M_.endo_names_tex = char(M_.endo_names_tex, 'output');
M_.endo_names_long = char(M_.endo_names_long, 'output');
M_.endo_names = char(M_.endo_names, 'outputgap');
M_.endo_names_tex = char(M_.endo_names_tex, 'outputgap');
M_.endo_names_long = char(M_.endo_names_long, 'outputgap');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_73');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_73');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_73');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_77');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_77');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_77');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_81');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_81');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_81');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_108');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_108');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_108');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_112');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_112');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_112');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_116');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_116');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_116');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_143');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_143');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_143');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_147');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_147');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_147');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_151');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_151');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_151');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_44_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_44\_1');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_44_1');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_44_2');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_44\_2');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_44_2');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_55_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_55\_1');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_55_1');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_55_2');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_55\_2');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_55_2');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_55_3');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_55\_3');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_55_3');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_56_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_56\_1');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_56_1');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_56_2');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_56\_2');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_56_2');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_56_3');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_56\_3');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_56_3');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_52_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_52\_1');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_52_1');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_52_2');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_52\_2');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_52_2');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_52_3');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_52\_3');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_52_3');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_54_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_54\_1');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_54_1');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_54_2');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_54\_2');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_54_2');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_54_3');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_54\_3');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_54_3');
M_.endo_partitions = struct();
M_.param_names = 'cofintintb1';
M_.param_names_tex = 'cofintintb1';
M_.param_names_long = 'cofintintb1';
M_.param_names = char(M_.param_names, 'cofintintb2');
M_.param_names_tex = char(M_.param_names_tex, 'cofintintb2');
M_.param_names_long = char(M_.param_names_long, 'cofintintb2');
M_.param_names = char(M_.param_names, 'cofintintb3');
M_.param_names_tex = char(M_.param_names_tex, 'cofintintb3');
M_.param_names_long = char(M_.param_names_long, 'cofintintb3');
M_.param_names = char(M_.param_names, 'cofintintb4');
M_.param_names_tex = char(M_.param_names_tex, 'cofintintb4');
M_.param_names_long = char(M_.param_names_long, 'cofintintb4');
M_.param_names = char(M_.param_names, 'cofintinf0');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinf0');
M_.param_names_long = char(M_.param_names_long, 'cofintinf0');
M_.param_names = char(M_.param_names, 'cofintinfb1');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinfb1');
M_.param_names_long = char(M_.param_names_long, 'cofintinfb1');
M_.param_names = char(M_.param_names, 'cofintinfb2');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinfb2');
M_.param_names_long = char(M_.param_names_long, 'cofintinfb2');
M_.param_names = char(M_.param_names, 'cofintinfb3');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinfb3');
M_.param_names_long = char(M_.param_names_long, 'cofintinfb3');
M_.param_names = char(M_.param_names, 'cofintinfb4');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinfb4');
M_.param_names_long = char(M_.param_names_long, 'cofintinfb4');
M_.param_names = char(M_.param_names, 'cofintinff1');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinff1');
M_.param_names_long = char(M_.param_names_long, 'cofintinff1');
M_.param_names = char(M_.param_names, 'cofintinff2');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinff2');
M_.param_names_long = char(M_.param_names_long, 'cofintinff2');
M_.param_names = char(M_.param_names, 'cofintinff3');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinff3');
M_.param_names_long = char(M_.param_names_long, 'cofintinff3');
M_.param_names = char(M_.param_names, 'cofintinff4');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinff4');
M_.param_names_long = char(M_.param_names_long, 'cofintinff4');
M_.param_names = char(M_.param_names, 'cofintout');
M_.param_names_tex = char(M_.param_names_tex, 'cofintout');
M_.param_names_long = char(M_.param_names_long, 'cofintout');
M_.param_names = char(M_.param_names, 'cofintoutb1');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutb1');
M_.param_names_long = char(M_.param_names_long, 'cofintoutb1');
M_.param_names = char(M_.param_names, 'cofintoutb2');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutb2');
M_.param_names_long = char(M_.param_names_long, 'cofintoutb2');
M_.param_names = char(M_.param_names, 'cofintoutb3');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutb3');
M_.param_names_long = char(M_.param_names_long, 'cofintoutb3');
M_.param_names = char(M_.param_names, 'cofintoutb4');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutb4');
M_.param_names_long = char(M_.param_names_long, 'cofintoutb4');
M_.param_names = char(M_.param_names, 'cofintoutf1');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutf1');
M_.param_names_long = char(M_.param_names_long, 'cofintoutf1');
M_.param_names = char(M_.param_names, 'cofintoutf2');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutf2');
M_.param_names_long = char(M_.param_names_long, 'cofintoutf2');
M_.param_names = char(M_.param_names, 'cofintoutf3');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutf3');
M_.param_names_long = char(M_.param_names_long, 'cofintoutf3');
M_.param_names = char(M_.param_names, 'cofintoutf4');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutf4');
M_.param_names_long = char(M_.param_names_long, 'cofintoutf4');
M_.param_names = char(M_.param_names, 'cofintoutp');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutp');
M_.param_names_long = char(M_.param_names_long, 'cofintoutp');
M_.param_names = char(M_.param_names, 'cofintoutpb1');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpb1');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpb1');
M_.param_names = char(M_.param_names, 'cofintoutpb2');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpb2');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpb2');
M_.param_names = char(M_.param_names, 'cofintoutpb3');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpb3');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpb3');
M_.param_names = char(M_.param_names, 'cofintoutpb4');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpb4');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpb4');
M_.param_names = char(M_.param_names, 'cofintoutpf1');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpf1');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpf1');
M_.param_names = char(M_.param_names, 'cofintoutpf2');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpf2');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpf2');
M_.param_names = char(M_.param_names, 'cofintoutpf3');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpf3');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpf3');
M_.param_names = char(M_.param_names, 'cofintoutpf4');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpf4');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpf4');
M_.param_names = char(M_.param_names, 'std_r_');
M_.param_names_tex = char(M_.param_names_tex, 'std\_r\_');
M_.param_names_long = char(M_.param_names_long, 'std_r_');
M_.param_names = char(M_.param_names, 'std_r_quart');
M_.param_names_tex = char(M_.param_names_tex, 'std\_r\_quart');
M_.param_names_long = char(M_.param_names_long, 'std_r_quart');
M_.param_names = char(M_.param_names, 'coffispol');
M_.param_names_tex = char(M_.param_names_tex, 'coffispol');
M_.param_names_long = char(M_.param_names_long, 'coffispol');
M_.param_names = char(M_.param_names, 'b');
M_.param_names_tex = char(M_.param_names_tex, 'b');
M_.param_names_long = char(M_.param_names_long, 'b');
M_.param_names = char(M_.param_names, 'x');
M_.param_names_tex = char(M_.param_names_tex, 'x');
M_.param_names_long = char(M_.param_names_long, 'x');
M_.param_names = char(M_.param_names, 'alfa_T');
M_.param_names_tex = char(M_.param_names_tex, 'alfa\_T');
M_.param_names_long = char(M_.param_names_long, 'alfa_T');
M_.param_names = char(M_.param_names, 'b_star');
M_.param_names_tex = char(M_.param_names_tex, 'b\_star');
M_.param_names_long = char(M_.param_names_long, 'b_star');
M_.param_names = char(M_.param_names, 'alfa_T_star');
M_.param_names_tex = char(M_.param_names_tex, 'alfa\_T\_star');
M_.param_names_long = char(M_.param_names_long, 'alfa_T_star');
M_.param_names = char(M_.param_names, 'nu');
M_.param_names_tex = char(M_.param_names_tex, 'nu');
M_.param_names_long = char(M_.param_names_long, 'nu');
M_.param_names = char(M_.param_names, 'eps');
M_.param_names_tex = char(M_.param_names_tex, 'eps');
M_.param_names_long = char(M_.param_names_long, 'eps');
M_.param_names = char(M_.param_names, 'w_bar');
M_.param_names_tex = char(M_.param_names_tex, 'w\_bar');
M_.param_names_long = char(M_.param_names_long, 'w_bar');
M_.param_names = char(M_.param_names, 'w_bar_star');
M_.param_names_tex = char(M_.param_names_tex, 'w\_bar\_star');
M_.param_names_long = char(M_.param_names_long, 'w_bar_star');
M_.param_names = char(M_.param_names, 'gamma');
M_.param_names_tex = char(M_.param_names_tex, 'gamma');
M_.param_names_long = char(M_.param_names_long, 'gamma');
M_.param_names = char(M_.param_names, 'gamma_star');
M_.param_names_tex = char(M_.param_names_tex, 'gamma\_star');
M_.param_names_long = char(M_.param_names_long, 'gamma_star');
M_.param_names = char(M_.param_names, 'vaphi_N');
M_.param_names_tex = char(M_.param_names_tex, 'vaphi\_N');
M_.param_names_long = char(M_.param_names_long, 'vaphi_N');
M_.param_names = char(M_.param_names, 'theta_N');
M_.param_names_tex = char(M_.param_names_tex, 'theta\_N');
M_.param_names_long = char(M_.param_names_long, 'theta_N');
M_.param_names = char(M_.param_names, 'beta');
M_.param_names_tex = char(M_.param_names_tex, 'beta');
M_.param_names_long = char(M_.param_names_long, 'beta');
M_.param_names = char(M_.param_names, 'alfa_N');
M_.param_names_tex = char(M_.param_names_tex, 'alfa\_N');
M_.param_names_long = char(M_.param_names_long, 'alfa_N');
M_.param_names = char(M_.param_names, 'vaphi_H');
M_.param_names_tex = char(M_.param_names_tex, 'vaphi\_H');
M_.param_names_long = char(M_.param_names_long, 'vaphi_H');
M_.param_names = char(M_.param_names, 'theta_H');
M_.param_names_tex = char(M_.param_names_tex, 'theta\_H');
M_.param_names_long = char(M_.param_names_long, 'theta_H');
M_.param_names = char(M_.param_names, 'vaphi_N_star');
M_.param_names_tex = char(M_.param_names_tex, 'vaphi\_N\_star');
M_.param_names_long = char(M_.param_names_long, 'vaphi_N_star');
M_.param_names = char(M_.param_names, 'theta_N_star');
M_.param_names_tex = char(M_.param_names_tex, 'theta\_N\_star');
M_.param_names_long = char(M_.param_names_long, 'theta_N_star');
M_.param_names = char(M_.param_names, 'alfa_N_star');
M_.param_names_tex = char(M_.param_names_tex, 'alfa\_N\_star');
M_.param_names_long = char(M_.param_names_long, 'alfa_N_star');
M_.param_names = char(M_.param_names, 'vaphi_F_star');
M_.param_names_tex = char(M_.param_names_tex, 'vaphi\_F\_star');
M_.param_names_long = char(M_.param_names_long, 'vaphi_F_star');
M_.param_names = char(M_.param_names, 'theta_F_star');
M_.param_names_tex = char(M_.param_names_tex, 'theta\_F\_star');
M_.param_names_long = char(M_.param_names_long, 'theta_F_star');
M_.param_names = char(M_.param_names, 'lambda');
M_.param_names_tex = char(M_.param_names_tex, 'lambda');
M_.param_names_long = char(M_.param_names_long, 'lambda');
M_.param_names = char(M_.param_names, 'lambda_star');
M_.param_names_tex = char(M_.param_names_tex, 'lambda\_star');
M_.param_names_long = char(M_.param_names_long, 'lambda_star');
M_.param_names = char(M_.param_names, 's');
M_.param_names_tex = char(M_.param_names_tex, 's');
M_.param_names_long = char(M_.param_names_long, 's');
M_.param_names = char(M_.param_names, 'eta');
M_.param_names_tex = char(M_.param_names_tex, 'eta');
M_.param_names_long = char(M_.param_names_long, 'eta');
M_.param_names = char(M_.param_names, 'eta_star');
M_.param_names_tex = char(M_.param_names_tex, 'eta\_star');
M_.param_names_long = char(M_.param_names_long, 'eta_star');
M_.param_names = char(M_.param_names, 'rho_r');
M_.param_names_tex = char(M_.param_names_tex, 'rho\_r');
M_.param_names_long = char(M_.param_names_long, 'rho_r');
M_.param_names = char(M_.param_names, 'gamma_pi');
M_.param_names_tex = char(M_.param_names_tex, 'gamma\_pi');
M_.param_names_long = char(M_.param_names_long, 'gamma_pi');
M_.param_names = char(M_.param_names, 'rho_ZT');
M_.param_names_tex = char(M_.param_names_tex, 'rho\_ZT');
M_.param_names_long = char(M_.param_names_long, 'rho_ZT');
M_.param_names = char(M_.param_names, 'rho_ZN');
M_.param_names_tex = char(M_.param_names_tex, 'rho\_ZN');
M_.param_names_long = char(M_.param_names_long, 'rho_ZN');
M_.param_names = char(M_.param_names, 'rho_ZT_star');
M_.param_names_tex = char(M_.param_names_tex, 'rho\_ZT\_star');
M_.param_names_long = char(M_.param_names_long, 'rho_ZT_star');
M_.param_names = char(M_.param_names, 'rho_ZN_star');
M_.param_names_tex = char(M_.param_names_tex, 'rho\_ZN\_star');
M_.param_names_long = char(M_.param_names_long, 'rho_ZN_star');
M_.param_names = char(M_.param_names, 'rho_GT');
M_.param_names_tex = char(M_.param_names_tex, 'rho\_GT');
M_.param_names_long = char(M_.param_names_long, 'rho_GT');
M_.param_names = char(M_.param_names, 'rho_GN');
M_.param_names_tex = char(M_.param_names_tex, 'rho\_GN');
M_.param_names_long = char(M_.param_names_long, 'rho_GN');
M_.param_names = char(M_.param_names, 'rho_GT_star');
M_.param_names_tex = char(M_.param_names_tex, 'rho\_GT\_star');
M_.param_names_long = char(M_.param_names_long, 'rho_GT_star');
M_.param_names = char(M_.param_names, 'rho_GN_star');
M_.param_names_tex = char(M_.param_names_tex, 'rho\_GN\_star');
M_.param_names_long = char(M_.param_names_long, 'rho_GN_star');
M_.param_partitions = struct();
M_.exo_det_nbr = 0;
M_.exo_nbr = 10;
M_.endo_nbr = 80;
M_.param_nbr = 71;
M_.orig_endo_nbr = 57;
M_.aux_vars(1).endo_index = 58;
M_.aux_vars(1).type = 0;
M_.aux_vars(2).endo_index = 59;
M_.aux_vars(2).type = 0;
M_.aux_vars(3).endo_index = 60;
M_.aux_vars(3).type = 0;
M_.aux_vars(4).endo_index = 61;
M_.aux_vars(4).type = 0;
M_.aux_vars(5).endo_index = 62;
M_.aux_vars(5).type = 0;
M_.aux_vars(6).endo_index = 63;
M_.aux_vars(6).type = 0;
M_.aux_vars(7).endo_index = 64;
M_.aux_vars(7).type = 0;
M_.aux_vars(8).endo_index = 65;
M_.aux_vars(8).type = 0;
M_.aux_vars(9).endo_index = 66;
M_.aux_vars(9).type = 0;
M_.aux_vars(10).endo_index = 67;
M_.aux_vars(10).type = 1;
M_.aux_vars(10).orig_index = 45;
M_.aux_vars(10).orig_lead_lag = -1;
M_.aux_vars(11).endo_index = 68;
M_.aux_vars(11).type = 1;
M_.aux_vars(11).orig_index = 45;
M_.aux_vars(11).orig_lead_lag = -2;
M_.aux_vars(12).endo_index = 69;
M_.aux_vars(12).type = 1;
M_.aux_vars(12).orig_index = 56;
M_.aux_vars(12).orig_lead_lag = -1;
M_.aux_vars(13).endo_index = 70;
M_.aux_vars(13).type = 1;
M_.aux_vars(13).orig_index = 56;
M_.aux_vars(13).orig_lead_lag = -2;
M_.aux_vars(14).endo_index = 71;
M_.aux_vars(14).type = 1;
M_.aux_vars(14).orig_index = 56;
M_.aux_vars(14).orig_lead_lag = -3;
M_.aux_vars(15).endo_index = 72;
M_.aux_vars(15).type = 1;
M_.aux_vars(15).orig_index = 57;
M_.aux_vars(15).orig_lead_lag = -1;
M_.aux_vars(16).endo_index = 73;
M_.aux_vars(16).type = 1;
M_.aux_vars(16).orig_index = 57;
M_.aux_vars(16).orig_lead_lag = -2;
M_.aux_vars(17).endo_index = 74;
M_.aux_vars(17).type = 1;
M_.aux_vars(17).orig_index = 57;
M_.aux_vars(17).orig_lead_lag = -3;
M_.aux_vars(18).endo_index = 75;
M_.aux_vars(18).type = 1;
M_.aux_vars(18).orig_index = 53;
M_.aux_vars(18).orig_lead_lag = -1;
M_.aux_vars(19).endo_index = 76;
M_.aux_vars(19).type = 1;
M_.aux_vars(19).orig_index = 53;
M_.aux_vars(19).orig_lead_lag = -2;
M_.aux_vars(20).endo_index = 77;
M_.aux_vars(20).type = 1;
M_.aux_vars(20).orig_index = 53;
M_.aux_vars(20).orig_lead_lag = -3;
M_.aux_vars(21).endo_index = 78;
M_.aux_vars(21).type = 1;
M_.aux_vars(21).orig_index = 55;
M_.aux_vars(21).orig_lead_lag = -1;
M_.aux_vars(22).endo_index = 79;
M_.aux_vars(22).type = 1;
M_.aux_vars(22).orig_index = 55;
M_.aux_vars(22).orig_lead_lag = -2;
M_.aux_vars(23).endo_index = 80;
M_.aux_vars(23).type = 1;
M_.aux_vars(23).orig_index = 55;
M_.aux_vars(23).orig_lead_lag = -3;
M_.Sigma_e = zeros(10, 10);
M_.Correlation_matrix = eye(10, 10);
M_.H = 0;
M_.Correlation_matrix_ME = 1;
M_.sigma_e_is_diagonal = 1;
M_.det_shocks = [];
options_.linear = 1;
options_.block=0;
options_.bytecode=0;
options_.use_dll=0;
M_.hessian_eq_zero = 1;
erase_compiled_function('EAES_RA09_static');
erase_compiled_function('EAES_RA09_dynamic');
M_.orig_eq_nbr = 57;
M_.eq_nbr = 80;
M_.ramsey_eq_nbr = 0;
M_.set_auxiliary_variables = exist(['./' M_.fname '_set_auxiliary_variables.m'], 'file') == 2;
M_.lead_lag_incidence = [
 0 41 0;
 0 42 0;
 0 43 121;
 0 44 0;
 0 45 122;
 1 46 0;
 0 47 0;
 2 48 0;
 0 49 0;
 0 50 0;
 3 51 0;
 4 52 0;
 0 53 0;
 5 54 0;
 6 55 0;
 7 56 0;
 0 57 0;
 0 58 0;
 0 59 0;
 0 60 0;
 0 61 0;
 0 62 0;
 0 63 0;
 0 64 0;
 0 65 0;
 0 66 0;
 0 67 0;
 0 68 0;
 0 69 0;
 0 70 0;
 0 71 0;
 0 72 0;
 8 73 0;
 0 74 0;
 9 75 0;
 0 76 0;
 10 77 0;
 0 78 0;
 11 79 0;
 12 80 123;
 13 81 124;
 14 82 125;
 15 83 126;
 0 84 0;
 16 85 0;
 17 86 0;
 18 87 0;
 19 88 0;
 20 89 0;
 21 90 0;
 22 91 0;
 0 92 0;
 23 93 0;
 0 94 0;
 24 95 127;
 25 96 128;
 26 97 129;
 0 98 130;
 0 99 131;
 0 100 132;
 0 101 133;
 0 102 134;
 0 103 135;
 0 104 136;
 0 105 137;
 0 106 138;
 27 107 0;
 28 108 0;
 29 109 0;
 30 110 0;
 31 111 0;
 32 112 0;
 33 113 0;
 34 114 0;
 35 115 0;
 36 116 0;
 37 117 0;
 38 118 0;
 39 119 0;
 40 120 0;]';
M_.nstatic = 29;
M_.nfwrd   = 11;
M_.npred   = 33;
M_.nboth   = 7;
M_.nsfwrd   = 18;
M_.nspred   = 40;
M_.ndynamic   = 51;
M_.equations_tags = {
};
M_.static_and_dynamic_models_differ = 0;
M_.exo_names_orig_ord = [1:10];
M_.maximum_lag = 1;
M_.maximum_lead = 1;
M_.maximum_endo_lag = 1;
M_.maximum_endo_lead = 1;
oo_.steady_state = zeros(80, 1);
M_.maximum_exo_lag = 0;
M_.maximum_exo_lead = 0;
oo_.exo_steady_state = zeros(10, 1);
M_.params = NaN(71, 1);
M_.NNZDerivatives = [280; 0; -1];
M_.params( 35 ) = 0.6;
b = M_.params( 35 );
M_.params( 36 ) = 0;
x = M_.params( 36 );
M_.params( 37 ) = 0;
alfa_T = M_.params( 37 );
M_.params( 38 ) = 0.6;
b_star = M_.params( 38 );
M_.params( 39 ) = 0;
alfa_T_star = M_.params( 39 );
M_.params( 40 ) = 0.52;
nu = M_.params( 40 );
M_.params( 41 ) = 0.51;
eps = M_.params( 41 );
M_.params( 42 ) = 1;
w_bar = M_.params( 42 );
M_.params( 43 ) = 1;
w_bar_star = M_.params( 43 );
M_.params( 44 ) = 0.66;
gamma = M_.params( 44 );
M_.params( 45 ) = 0.61;
gamma_star = M_.params( 45 );
M_.params( 46 ) = 0.28;
vaphi_N = M_.params( 46 );
M_.params( 47 ) = 0.66;
theta_N = M_.params( 47 );
M_.params( 48 ) = 0.99;
beta = M_.params( 48 );
M_.params( 49 ) = 0;
alfa_N = M_.params( 49 );
M_.params( 50 ) = 0.44;
vaphi_H = M_.params( 50 );
M_.params( 51 ) = 0.35;
theta_H = M_.params( 51 );
M_.params( 52 ) = 0.46;
vaphi_N_star = M_.params( 52 );
M_.params( 53 ) = 0.85;
theta_N_star = M_.params( 53 );
M_.params( 54 ) = 0;
alfa_N_star = M_.params( 54 );
M_.params( 55 ) = 0.37;
vaphi_F_star = M_.params( 55 );
M_.params( 56 ) = 0.43;
theta_F_star = M_.params( 56 );
M_.params( 60 ) = 0.18;
eta = M_.params( 60 );
M_.params( 61 ) = 0.20;
eta_star = M_.params( 61 );
M_.params( 62 ) = 0.73;
rho_r = M_.params( 62 );
M_.params( 63 ) = 1.43;
gamma_pi = M_.params( 63 );
M_.params( 64 ) = 0.65;
rho_ZT = M_.params( 64 );
M_.params( 65 ) = 0.77;
rho_ZN = M_.params( 65 );
M_.params( 66 ) = 0.65;
rho_ZT_star = M_.params( 66 );
M_.params( 67 ) = 0.77;
rho_ZN_star = M_.params( 67 );
M_.params( 68 ) = 0.96;
rho_GT = M_.params( 68 );
M_.params( 69 ) = 0.98;
rho_GN = M_.params( 69 );
M_.params( 70 ) = 0.96;
rho_GT_star = M_.params( 70 );
M_.params( 71 ) = 0.98;
rho_GN_star = M_.params( 71 );
M_.params( 57 ) = 0.85;
lambda = M_.params( 57 );
M_.params( 58 ) = 0.98;
lambda_star = M_.params( 58 );
M_.params( 59 ) = (1+(1-M_.params(57))*M_.params(44)*(1-M_.params(60))/((1-M_.params(58))*M_.params(45)*(1-M_.params(61))))^(-1);
s = M_.params( 59 );
thispath = cd;                                                           
cd('..');                                                                
load policy_param.mat;                                                   
for i=1:33                                                               
deep_parameter_name = M_.param_names(i,:);                           
eval(['M_.params(i)  = ' deep_parameter_name ' ;'])                  
end                                                                      
cd(thispath);       
M_.params( 34 ) = 0;
coffispol = M_.params( 34 );
%
% SHOCKS instructions
%
M_.exo_det_length = 0;
M_.Sigma_e(10, 10) = 0;
M_.Sigma_e(1, 1) = (0.59)^2;
M_.Sigma_e(2, 2) = (0.72)^2;
M_.Sigma_e(3, 3) = (0.46)^2;
M_.Sigma_e(4, 4) = (0.54)^2;
M_.Sigma_e(5, 5) = (0.88)^2;
M_.Sigma_e(6, 6) = (3.07)^2;
M_.Sigma_e(7, 7) = (4.58)^2;
M_.Sigma_e(8, 8) = (3.26)^2;
M_.Sigma_e(9, 9) = (2.34)^2;
options_.Schur_vec_tol = 1e-6;
save('EAES_RA09_results.mat', 'oo_', 'M_', 'options_');
if exist('estim_params_', 'var') == 1
  save('EAES_RA09_results.mat', 'estim_params_', '-append');
end
if exist('bayestopt_', 'var') == 1
  save('EAES_RA09_results.mat', 'bayestopt_', '-append');
end
if exist('dataset_', 'var') == 1
  save('EAES_RA09_results.mat', 'dataset_', '-append');
end
if exist('estimation_info', 'var') == 1
  save('EAES_RA09_results.mat', 'estimation_info', '-append');
end
if exist('dataset_info', 'var') == 1
  save('EAES_RA09_results.mat', 'dataset_info', '-append');
end
if exist('oo_recursive_', 'var') == 1
  save('EAES_RA09_results.mat', 'oo_recursive_', '-append');
end


disp(['Total computing time : ' dynsec2hms(toc(tic0)) ]);
if ~isempty(lastwarn)
  disp('Note: warning(s) encountered in MATLAB/Octave code')
end
diary off
