%
% Status : main Dynare file 
%
% Warning : this file is generated automatically by Dynare
%           from model file (.mod)

tic;
global M_ oo_ options_ ys0_ ex0_ estimation_info
options_ = [];
M_.fname = 'US_CFOP14';
%
% Some global variables initialization
%
global_initialization;
diary off;
diary('US_CFOP14.log');
M_.exo_names = 'Rs';
M_.exo_names_tex = 'Rs';
M_.exo_names_long = 'Rs';
M_.exo_names = char(M_.exo_names, 'zs');
M_.exo_names_tex = char(M_.exo_names_tex, 'zs');
M_.exo_names_long = char(M_.exo_names_long, 'zs');
M_.exo_names = char(M_.exo_names, 'mius');
M_.exo_names_tex = char(M_.exo_names_tex, 'mius');
M_.exo_names_long = char(M_.exo_names_long, 'mius');
M_.exo_names = char(M_.exo_names, 'lambdaps');
M_.exo_names_tex = char(M_.exo_names_tex, 'lambdaps');
M_.exo_names_long = char(M_.exo_names_long, 'lambdaps');
M_.exo_names = char(M_.exo_names, 'lambdaws');
M_.exo_names_tex = char(M_.exo_names_tex, 'lambdaws');
M_.exo_names_long = char(M_.exo_names_long, 'lambdaws');
M_.exo_names = char(M_.exo_names, 'bs');
M_.exo_names_tex = char(M_.exo_names_tex, 'bs');
M_.exo_names_long = char(M_.exo_names_long, 'bs');
M_.exo_names = char(M_.exo_names, 'efps');
M_.exo_names_tex = char(M_.exo_names_tex, 'efps');
M_.exo_names_long = char(M_.exo_names_long, 'efps');
M_.exo_names = char(M_.exo_names, 'upsilons');
M_.exo_names_tex = char(M_.exo_names_tex, 'upsilons');
M_.exo_names_long = char(M_.exo_names_long, 'upsilons');
M_.exo_names = char(M_.exo_names, 'nws');
M_.exo_names_tex = char(M_.exo_names_tex, 'nws');
M_.exo_names_long = char(M_.exo_names_long, 'nws');
M_.exo_names = char(M_.exo_names, 'interest_');
M_.exo_names_tex = char(M_.exo_names_tex, 'interest\_');
M_.exo_names_long = char(M_.exo_names_long, 'interest_');
M_.exo_names = char(M_.exo_names, 'fiscal_');
M_.exo_names_tex = char(M_.exo_names_tex, 'fiscal\_');
M_.exo_names_long = char(M_.exo_names_long, 'fiscal_');
M_.endo_names = 'y';
M_.endo_names_tex = 'y';
M_.endo_names_long = 'y';
M_.endo_names = char(M_.endo_names, 'k');
M_.endo_names_tex = char(M_.endo_names_tex, 'k');
M_.endo_names_long = char(M_.endo_names_long, 'k');
M_.endo_names = char(M_.endo_names, 'L');
M_.endo_names_tex = char(M_.endo_names_tex, 'L');
M_.endo_names_long = char(M_.endo_names_long, 'L');
M_.endo_names = char(M_.endo_names, 'mpk');
M_.endo_names_tex = char(M_.endo_names_tex, 'mpk');
M_.endo_names_long = char(M_.endo_names_long, 'mpk');
M_.endo_names = char(M_.endo_names, 'w');
M_.endo_names_tex = char(M_.endo_names_tex, 'w');
M_.endo_names_long = char(M_.endo_names_long, 'w');
M_.endo_names = char(M_.endo_names, 'p');
M_.endo_names_tex = char(M_.endo_names_tex, 'p');
M_.endo_names_long = char(M_.endo_names_long, 'p');
M_.endo_names = char(M_.endo_names, 's');
M_.endo_names_tex = char(M_.endo_names_tex, 's');
M_.endo_names_long = char(M_.endo_names_long, 's');
M_.endo_names = char(M_.endo_names, 'lambda');
M_.endo_names_tex = char(M_.endo_names_tex, 'lambda');
M_.endo_names_long = char(M_.endo_names_long, 'lambda');
M_.endo_names = char(M_.endo_names, 'c');
M_.endo_names_tex = char(M_.endo_names_tex, 'c');
M_.endo_names_long = char(M_.endo_names_long, 'c');
M_.endo_names = char(M_.endo_names, 'R');
M_.endo_names_tex = char(M_.endo_names_tex, 'R');
M_.endo_names_long = char(M_.endo_names_long, 'R');
M_.endo_names = char(M_.endo_names, 'u');
M_.endo_names_tex = char(M_.endo_names_tex, 'u');
M_.endo_names_long = char(M_.endo_names_long, 'u');
M_.endo_names = char(M_.endo_names, 'i');
M_.endo_names_tex = char(M_.endo_names_tex, 'i');
M_.endo_names_long = char(M_.endo_names_long, 'i');
M_.endo_names = char(M_.endo_names, 'kbar');
M_.endo_names_tex = char(M_.endo_names_tex, 'kbar');
M_.endo_names_long = char(M_.endo_names_long, 'kbar');
M_.endo_names = char(M_.endo_names, 'wgap');
M_.endo_names_tex = char(M_.endo_names_tex, 'wgap');
M_.endo_names_long = char(M_.endo_names_long, 'wgap');
M_.endo_names = char(M_.endo_names, 'gdp');
M_.endo_names_tex = char(M_.endo_names_tex, 'gdp');
M_.endo_names_long = char(M_.endo_names_long, 'gdp');
M_.endo_names = char(M_.endo_names, 'z');
M_.endo_names_tex = char(M_.endo_names_tex, 'z');
M_.endo_names_long = char(M_.endo_names_long, 'z');
M_.endo_names = char(M_.endo_names, 'g');
M_.endo_names_tex = char(M_.endo_names_tex, 'g');
M_.endo_names_long = char(M_.endo_names_long, 'g');
M_.endo_names = char(M_.endo_names, 'miu');
M_.endo_names_tex = char(M_.endo_names_tex, 'miu');
M_.endo_names_long = char(M_.endo_names_long, 'miu');
M_.endo_names = char(M_.endo_names, 'lambdap');
M_.endo_names_tex = char(M_.endo_names_tex, 'lambdap');
M_.endo_names_long = char(M_.endo_names_long, 'lambdap');
M_.endo_names = char(M_.endo_names, 'lambdaw');
M_.endo_names_tex = char(M_.endo_names_tex, 'lambdaw');
M_.endo_names_long = char(M_.endo_names_long, 'lambdaw');
M_.endo_names = char(M_.endo_names, 'b');
M_.endo_names_tex = char(M_.endo_names_tex, 'b');
M_.endo_names_long = char(M_.endo_names_long, 'b');
M_.endo_names = char(M_.endo_names, 'mp');
M_.endo_names_tex = char(M_.endo_names_tex, 'mp');
M_.endo_names_long = char(M_.endo_names_long, 'mp');
M_.endo_names = char(M_.endo_names, 'ARMAlambdap');
M_.endo_names_tex = char(M_.endo_names_tex, 'ARMAlambdap');
M_.endo_names_long = char(M_.endo_names_long, 'ARMAlambdap');
M_.endo_names = char(M_.endo_names, 'ARMAlambdaw');
M_.endo_names_tex = char(M_.endo_names_tex, 'ARMAlambdaw');
M_.endo_names_long = char(M_.endo_names_long, 'ARMAlambdaw');
M_.endo_names = char(M_.endo_names, 'ystar');
M_.endo_names_tex = char(M_.endo_names_tex, 'ystar');
M_.endo_names_long = char(M_.endo_names_long, 'ystar');
M_.endo_names = char(M_.endo_names, 'kstar');
M_.endo_names_tex = char(M_.endo_names_tex, 'kstar');
M_.endo_names_long = char(M_.endo_names_long, 'kstar');
M_.endo_names = char(M_.endo_names, 'Lstar');
M_.endo_names_tex = char(M_.endo_names_tex, 'Lstar');
M_.endo_names_long = char(M_.endo_names_long, 'Lstar');
M_.endo_names = char(M_.endo_names, 'mpkstar');
M_.endo_names_tex = char(M_.endo_names_tex, 'mpkstar');
M_.endo_names_long = char(M_.endo_names_long, 'mpkstar');
M_.endo_names = char(M_.endo_names, 'wstar');
M_.endo_names_tex = char(M_.endo_names_tex, 'wstar');
M_.endo_names_long = char(M_.endo_names_long, 'wstar');
M_.endo_names = char(M_.endo_names, 'sstar');
M_.endo_names_tex = char(M_.endo_names_tex, 'sstar');
M_.endo_names_long = char(M_.endo_names_long, 'sstar');
M_.endo_names = char(M_.endo_names, 'lambdastar');
M_.endo_names_tex = char(M_.endo_names_tex, 'lambdastar');
M_.endo_names_long = char(M_.endo_names_long, 'lambdastar');
M_.endo_names = char(M_.endo_names, 'cstar');
M_.endo_names_tex = char(M_.endo_names_tex, 'cstar');
M_.endo_names_long = char(M_.endo_names_long, 'cstar');
M_.endo_names = char(M_.endo_names, 'Rstar');
M_.endo_names_tex = char(M_.endo_names_tex, 'Rstar');
M_.endo_names_long = char(M_.endo_names_long, 'Rstar');
M_.endo_names = char(M_.endo_names, 'ustar');
M_.endo_names_tex = char(M_.endo_names_tex, 'ustar');
M_.endo_names_long = char(M_.endo_names_long, 'ustar');
M_.endo_names = char(M_.endo_names, 'istar');
M_.endo_names_tex = char(M_.endo_names_tex, 'istar');
M_.endo_names_long = char(M_.endo_names_long, 'istar');
M_.endo_names = char(M_.endo_names, 'kbarstar');
M_.endo_names_tex = char(M_.endo_names_tex, 'kbarstar');
M_.endo_names_long = char(M_.endo_names_long, 'kbarstar');
M_.endo_names = char(M_.endo_names, 'wgapstar');
M_.endo_names_tex = char(M_.endo_names_tex, 'wgapstar');
M_.endo_names_long = char(M_.endo_names_long, 'wgapstar');
M_.endo_names = char(M_.endo_names, 'gdpstar');
M_.endo_names_tex = char(M_.endo_names_tex, 'gdpstar');
M_.endo_names_long = char(M_.endo_names_long, 'gdpstar');
M_.endo_names = char(M_.endo_names, 'Rk');
M_.endo_names_tex = char(M_.endo_names_tex, 'Rk');
M_.endo_names_long = char(M_.endo_names_long, 'Rk');
M_.endo_names = char(M_.endo_names, 'Rkstar');
M_.endo_names_tex = char(M_.endo_names_tex, 'Rkstar');
M_.endo_names_long = char(M_.endo_names_long, 'Rkstar');
M_.endo_names = char(M_.endo_names, 'q');
M_.endo_names_tex = char(M_.endo_names_tex, 'q');
M_.endo_names_long = char(M_.endo_names_long, 'q');
M_.endo_names = char(M_.endo_names, 'qstar');
M_.endo_names_tex = char(M_.endo_names_tex, 'qstar');
M_.endo_names_long = char(M_.endo_names_long, 'qstar');
M_.endo_names = char(M_.endo_names, 'Rl');
M_.endo_names_tex = char(M_.endo_names_tex, 'Rl');
M_.endo_names_long = char(M_.endo_names_long, 'Rl');
M_.endo_names = char(M_.endo_names, 'Rlstar');
M_.endo_names_tex = char(M_.endo_names_tex, 'Rlstar');
M_.endo_names_long = char(M_.endo_names_long, 'Rlstar');
M_.endo_names = char(M_.endo_names, 'Rd');
M_.endo_names_tex = char(M_.endo_names_tex, 'Rd');
M_.endo_names_long = char(M_.endo_names_long, 'Rd');
M_.endo_names = char(M_.endo_names, 'Rdstar');
M_.endo_names_tex = char(M_.endo_names_tex, 'Rdstar');
M_.endo_names_long = char(M_.endo_names_long, 'Rdstar');
M_.endo_names = char(M_.endo_names, 'Rke');
M_.endo_names_tex = char(M_.endo_names_tex, 'Rke');
M_.endo_names_long = char(M_.endo_names_long, 'Rke');
M_.endo_names = char(M_.endo_names, 'Rkestar');
M_.endo_names_tex = char(M_.endo_names_tex, 'Rkestar');
M_.endo_names_long = char(M_.endo_names_long, 'Rkestar');
M_.endo_names = char(M_.endo_names, 'nw');
M_.endo_names_tex = char(M_.endo_names_tex, 'nw');
M_.endo_names_long = char(M_.endo_names_long, 'nw');
M_.endo_names = char(M_.endo_names, 'nwstar');
M_.endo_names_tex = char(M_.endo_names_tex, 'nwstar');
M_.endo_names_long = char(M_.endo_names_long, 'nwstar');
M_.endo_names = char(M_.endo_names, 'lamefp');
M_.endo_names_tex = char(M_.endo_names_tex, 'lamefp');
M_.endo_names_long = char(M_.endo_names_long, 'lamefp');
M_.endo_names = char(M_.endo_names, 'spr');
M_.endo_names_tex = char(M_.endo_names_tex, 'spr');
M_.endo_names_long = char(M_.endo_names_long, 'spr');
M_.endo_names = char(M_.endo_names, 'sprstar');
M_.endo_names_tex = char(M_.endo_names_tex, 'sprstar');
M_.endo_names_long = char(M_.endo_names_long, 'sprstar');
M_.endo_names = char(M_.endo_names, 'promz');
M_.endo_names_tex = char(M_.endo_names_tex, 'promz');
M_.endo_names_long = char(M_.endo_names_long, 'promz');
M_.endo_names = char(M_.endo_names, 'promzstar');
M_.endo_names_tex = char(M_.endo_names_tex, 'promzstar');
M_.endo_names_long = char(M_.endo_names_long, 'promzstar');
M_.endo_names = char(M_.endo_names, 'upsilon');
M_.endo_names_tex = char(M_.endo_names_tex, 'upsilon');
M_.endo_names_long = char(M_.endo_names_long, 'upsilon');
M_.endo_names = char(M_.endo_names, 'lamnw');
M_.endo_names_tex = char(M_.endo_names_tex, 'lamnw');
M_.endo_names_long = char(M_.endo_names_long, 'lamnw');
M_.endo_names = char(M_.endo_names, 'lambdae');
M_.endo_names_tex = char(M_.endo_names_tex, 'lambdae');
M_.endo_names_long = char(M_.endo_names_long, 'lambdae');
M_.endo_names = char(M_.endo_names, 'lambdaestar');
M_.endo_names_tex = char(M_.endo_names_tex, 'lambdaestar');
M_.endo_names_long = char(M_.endo_names_long, 'lambdaestar');
M_.endo_names = char(M_.endo_names, 'credit');
M_.endo_names_tex = char(M_.endo_names_tex, 'credit');
M_.endo_names_long = char(M_.endo_names_long, 'credit');
M_.endo_names = char(M_.endo_names, 'gs');
M_.endo_names_tex = char(M_.endo_names_tex, 'gs');
M_.endo_names_long = char(M_.endo_names_long, 'gs');
M_.endo_names = char(M_.endo_names, 'interest');
M_.endo_names_tex = char(M_.endo_names_tex, 'interest');
M_.endo_names_long = char(M_.endo_names_long, 'interest');
M_.endo_names = char(M_.endo_names, 'inflation');
M_.endo_names_tex = char(M_.endo_names_tex, 'inflation');
M_.endo_names_long = char(M_.endo_names_long, 'inflation');
M_.endo_names = char(M_.endo_names, 'inflationq');
M_.endo_names_tex = char(M_.endo_names_tex, 'inflationq');
M_.endo_names_long = char(M_.endo_names_long, 'inflationq');
M_.endo_names = char(M_.endo_names, 'outputgap');
M_.endo_names_tex = char(M_.endo_names_tex, 'outputgap');
M_.endo_names_long = char(M_.endo_names_long, 'outputgap');
M_.endo_names = char(M_.endo_names, 'output');
M_.endo_names_tex = char(M_.endo_names_tex, 'output');
M_.endo_names_long = char(M_.endo_names_long, 'output');
M_.endo_names = char(M_.endo_names, 'fispol');
M_.endo_names_tex = char(M_.endo_names_tex, 'fispol');
M_.endo_names_long = char(M_.endo_names_long, 'fispol');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_165');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_165');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_165');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_169');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_169');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_169');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_173');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_173');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_173');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_200');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_200');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_200');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_204');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_204');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_204');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_208');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_208');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_208');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_235');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_235');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_235');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_239');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_239');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_239');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_243');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_243');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_243');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_5_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_5\_1');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_5_1');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_5_2');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_5\_2');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_5_2');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_65_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_65\_1');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_65_1');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_65_2');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_65\_2');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_65_2');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_65_3');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_65\_3');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_65_3');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_64_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_64\_1');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_64_1');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_64_2');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_64\_2');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_64_2');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_64_3');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_64\_3');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_64_3');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_61_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_61\_1');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_61_1');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_61_2');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_61\_2');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_61_2');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_61_3');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_61\_3');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_61_3');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_63_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_63\_1');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_63_1');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_63_2');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_63\_2');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_63_2');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_63_3');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_63\_3');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_63_3');
M_.param_names = 'cofintintb1';
M_.param_names_tex = 'cofintintb1';
M_.param_names_long = 'cofintintb1';
M_.param_names = char(M_.param_names, 'cofintintb2');
M_.param_names_tex = char(M_.param_names_tex, 'cofintintb2');
M_.param_names_long = char(M_.param_names_long, 'cofintintb2');
M_.param_names = char(M_.param_names, 'cofintintb3');
M_.param_names_tex = char(M_.param_names_tex, 'cofintintb3');
M_.param_names_long = char(M_.param_names_long, 'cofintintb3');
M_.param_names = char(M_.param_names, 'cofintintb4');
M_.param_names_tex = char(M_.param_names_tex, 'cofintintb4');
M_.param_names_long = char(M_.param_names_long, 'cofintintb4');
M_.param_names = char(M_.param_names, 'cofintinf0');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinf0');
M_.param_names_long = char(M_.param_names_long, 'cofintinf0');
M_.param_names = char(M_.param_names, 'cofintinfb1');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinfb1');
M_.param_names_long = char(M_.param_names_long, 'cofintinfb1');
M_.param_names = char(M_.param_names, 'cofintinfb2');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinfb2');
M_.param_names_long = char(M_.param_names_long, 'cofintinfb2');
M_.param_names = char(M_.param_names, 'cofintinfb3');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinfb3');
M_.param_names_long = char(M_.param_names_long, 'cofintinfb3');
M_.param_names = char(M_.param_names, 'cofintinfb4');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinfb4');
M_.param_names_long = char(M_.param_names_long, 'cofintinfb4');
M_.param_names = char(M_.param_names, 'cofintinff1');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinff1');
M_.param_names_long = char(M_.param_names_long, 'cofintinff1');
M_.param_names = char(M_.param_names, 'cofintinff2');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinff2');
M_.param_names_long = char(M_.param_names_long, 'cofintinff2');
M_.param_names = char(M_.param_names, 'cofintinff3');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinff3');
M_.param_names_long = char(M_.param_names_long, 'cofintinff3');
M_.param_names = char(M_.param_names, 'cofintinff4');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinff4');
M_.param_names_long = char(M_.param_names_long, 'cofintinff4');
M_.param_names = char(M_.param_names, 'cofintout');
M_.param_names_tex = char(M_.param_names_tex, 'cofintout');
M_.param_names_long = char(M_.param_names_long, 'cofintout');
M_.param_names = char(M_.param_names, 'cofintoutb1');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutb1');
M_.param_names_long = char(M_.param_names_long, 'cofintoutb1');
M_.param_names = char(M_.param_names, 'cofintoutb2');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutb2');
M_.param_names_long = char(M_.param_names_long, 'cofintoutb2');
M_.param_names = char(M_.param_names, 'cofintoutb3');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutb3');
M_.param_names_long = char(M_.param_names_long, 'cofintoutb3');
M_.param_names = char(M_.param_names, 'cofintoutb4');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutb4');
M_.param_names_long = char(M_.param_names_long, 'cofintoutb4');
M_.param_names = char(M_.param_names, 'cofintoutf1');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutf1');
M_.param_names_long = char(M_.param_names_long, 'cofintoutf1');
M_.param_names = char(M_.param_names, 'cofintoutf2');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutf2');
M_.param_names_long = char(M_.param_names_long, 'cofintoutf2');
M_.param_names = char(M_.param_names, 'cofintoutf3');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutf3');
M_.param_names_long = char(M_.param_names_long, 'cofintoutf3');
M_.param_names = char(M_.param_names, 'cofintoutf4');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutf4');
M_.param_names_long = char(M_.param_names_long, 'cofintoutf4');
M_.param_names = char(M_.param_names, 'cofintoutp');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutp');
M_.param_names_long = char(M_.param_names_long, 'cofintoutp');
M_.param_names = char(M_.param_names, 'cofintoutpb1');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpb1');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpb1');
M_.param_names = char(M_.param_names, 'cofintoutpb2');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpb2');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpb2');
M_.param_names = char(M_.param_names, 'cofintoutpb3');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpb3');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpb3');
M_.param_names = char(M_.param_names, 'cofintoutpb4');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpb4');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpb4');
M_.param_names = char(M_.param_names, 'cofintoutpf1');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpf1');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpf1');
M_.param_names = char(M_.param_names, 'cofintoutpf2');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpf2');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpf2');
M_.param_names = char(M_.param_names, 'cofintoutpf3');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpf3');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpf3');
M_.param_names = char(M_.param_names, 'cofintoutpf4');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpf4');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpf4');
M_.param_names = char(M_.param_names, 'std_r_');
M_.param_names_tex = char(M_.param_names_tex, 'std\_r\_');
M_.param_names_long = char(M_.param_names_long, 'std_r_');
M_.param_names = char(M_.param_names, 'std_r_quart');
M_.param_names_tex = char(M_.param_names_tex, 'std\_r\_quart');
M_.param_names_long = char(M_.param_names_long, 'std_r_quart');
M_.param_names = char(M_.param_names, 'coffispol');
M_.param_names_tex = char(M_.param_names_tex, 'coffispol');
M_.param_names_long = char(M_.param_names_long, 'coffispol');
M_.param_names = char(M_.param_names, 'alpha');
M_.param_names_tex = char(M_.param_names_tex, 'alpha');
M_.param_names_long = char(M_.param_names_long, 'alpha');
M_.param_names = char(M_.param_names, 'delta');
M_.param_names_tex = char(M_.param_names_tex, 'delta');
M_.param_names_long = char(M_.param_names_long, 'delta');
M_.param_names = char(M_.param_names, 'iotap');
M_.param_names_tex = char(M_.param_names_tex, 'iotap');
M_.param_names_long = char(M_.param_names_long, 'iotap');
M_.param_names = char(M_.param_names, 'iotaw');
M_.param_names_tex = char(M_.param_names_tex, 'iotaw');
M_.param_names_long = char(M_.param_names_long, 'iotaw');
M_.param_names = char(M_.param_names, 'gamma100');
M_.param_names_tex = char(M_.param_names_tex, 'gamma100');
M_.param_names_long = char(M_.param_names_long, 'gamma100');
M_.param_names = char(M_.param_names, 'h');
M_.param_names_tex = char(M_.param_names_tex, 'h');
M_.param_names_long = char(M_.param_names_long, 'h');
M_.param_names = char(M_.param_names, 'lambdapss');
M_.param_names_tex = char(M_.param_names_tex, 'lambdapss');
M_.param_names_long = char(M_.param_names_long, 'lambdapss');
M_.param_names = char(M_.param_names, 'lambdawss');
M_.param_names_tex = char(M_.param_names_tex, 'lambdawss');
M_.param_names_long = char(M_.param_names_long, 'lambdawss');
M_.param_names = char(M_.param_names, 'Lss');
M_.param_names_tex = char(M_.param_names_tex, 'Lss');
M_.param_names_long = char(M_.param_names_long, 'Lss');
M_.param_names = char(M_.param_names, 'pss100');
M_.param_names_tex = char(M_.param_names_tex, 'pss100');
M_.param_names_long = char(M_.param_names_long, 'pss100');
M_.param_names = char(M_.param_names, 'Fbeta');
M_.param_names_tex = char(M_.param_names_tex, 'Fbeta');
M_.param_names_long = char(M_.param_names_long, 'Fbeta');
M_.param_names = char(M_.param_names, 'gss');
M_.param_names_tex = char(M_.param_names_tex, 'gss');
M_.param_names_long = char(M_.param_names_long, 'gss');
M_.param_names = char(M_.param_names, 'niu');
M_.param_names_tex = char(M_.param_names_tex, 'niu');
M_.param_names_long = char(M_.param_names_long, 'niu');
M_.param_names = char(M_.param_names, 'xip');
M_.param_names_tex = char(M_.param_names_tex, 'xip');
M_.param_names_long = char(M_.param_names_long, 'xip');
M_.param_names = char(M_.param_names, 'xiw');
M_.param_names_tex = char(M_.param_names_tex, 'xiw');
M_.param_names_long = char(M_.param_names_long, 'xiw');
M_.param_names = char(M_.param_names, 'chi');
M_.param_names_tex = char(M_.param_names_tex, 'chi');
M_.param_names_long = char(M_.param_names_long, 'chi');
M_.param_names = char(M_.param_names, 'Sadj');
M_.param_names_tex = char(M_.param_names_tex, 'Sadj');
M_.param_names_long = char(M_.param_names_long, 'Sadj');
M_.param_names = char(M_.param_names, 'fp');
M_.param_names_tex = char(M_.param_names_tex, 'fp');
M_.param_names_long = char(M_.param_names_long, 'fp');
M_.param_names = char(M_.param_names, 'fy');
M_.param_names_tex = char(M_.param_names_tex, 'fy');
M_.param_names_long = char(M_.param_names_long, 'fy');
M_.param_names = char(M_.param_names, 'fdy');
M_.param_names_tex = char(M_.param_names_tex, 'fdy');
M_.param_names_long = char(M_.param_names_long, 'fdy');
M_.param_names = char(M_.param_names, 'rhoR');
M_.param_names_tex = char(M_.param_names_tex, 'rhoR');
M_.param_names_long = char(M_.param_names_long, 'rhoR');
M_.param_names = char(M_.param_names, 'rhoz');
M_.param_names_tex = char(M_.param_names_tex, 'rhoz');
M_.param_names_long = char(M_.param_names_long, 'rhoz');
M_.param_names = char(M_.param_names, 'rhog');
M_.param_names_tex = char(M_.param_names_tex, 'rhog');
M_.param_names_long = char(M_.param_names_long, 'rhog');
M_.param_names = char(M_.param_names, 'rhomiu');
M_.param_names_tex = char(M_.param_names_tex, 'rhomiu');
M_.param_names_long = char(M_.param_names_long, 'rhomiu');
M_.param_names = char(M_.param_names, 'rholambdap');
M_.param_names_tex = char(M_.param_names_tex, 'rholambdap');
M_.param_names_long = char(M_.param_names_long, 'rholambdap');
M_.param_names = char(M_.param_names, 'rholambdaw');
M_.param_names_tex = char(M_.param_names_tex, 'rholambdaw');
M_.param_names_long = char(M_.param_names_long, 'rholambdaw');
M_.param_names = char(M_.param_names, 'rhob');
M_.param_names_tex = char(M_.param_names_tex, 'rhob');
M_.param_names_long = char(M_.param_names_long, 'rhob');
M_.param_names = char(M_.param_names, 'rhomp');
M_.param_names_tex = char(M_.param_names_tex, 'rhomp');
M_.param_names_long = char(M_.param_names_long, 'rhomp');
M_.param_names = char(M_.param_names, 'rhoARMAlambdap');
M_.param_names_tex = char(M_.param_names_tex, 'rhoARMAlambdap');
M_.param_names_long = char(M_.param_names_long, 'rhoARMAlambdap');
M_.param_names = char(M_.param_names, 'rhoARMAlambdaw');
M_.param_names_tex = char(M_.param_names_tex, 'rhoARMAlambdaw');
M_.param_names_long = char(M_.param_names_long, 'rhoARMAlambdaw');
M_.param_names = char(M_.param_names, 'cnu');
M_.param_names_tex = char(M_.param_names_tex, 'cnu');
M_.param_names_long = char(M_.param_names_long, 'cnu');
M_.param_names = char(M_.param_names, 'cnustar');
M_.param_names_tex = char(M_.param_names_tex, 'cnustar');
M_.param_names_long = char(M_.param_names_long, 'cnustar');
M_.param_names = char(M_.param_names, 'cgamma');
M_.param_names_tex = char(M_.param_names_tex, 'cgamma');
M_.param_names_long = char(M_.param_names_long, 'cgamma');
M_.param_names = char(M_.param_names, 'crp');
M_.param_names_tex = char(M_.param_names_tex, 'crp');
M_.param_names_long = char(M_.param_names_long, 'crp');
M_.param_names = char(M_.param_names, 'crpstar');
M_.param_names_tex = char(M_.param_names_tex, 'crpstar');
M_.param_names_long = char(M_.param_names_long, 'crpstar');
M_.param_names = char(M_.param_names, 'ckappa');
M_.param_names_tex = char(M_.param_names_tex, 'ckappa');
M_.param_names_long = char(M_.param_names_long, 'ckappa');
M_.param_names = char(M_.param_names, 'ctheta');
M_.param_names_tex = char(M_.param_names_tex, 'ctheta');
M_.param_names_long = char(M_.param_names_long, 'ctheta');
M_.param_names = char(M_.param_names, 'cchi');
M_.param_names_tex = char(M_.param_names_tex, 'cchi');
M_.param_names_long = char(M_.param_names_long, 'cchi');
M_.param_names = char(M_.param_names, 'rhoefp');
M_.param_names_tex = char(M_.param_names_tex, 'rhoefp');
M_.param_names_long = char(M_.param_names_long, 'rhoefp');
M_.param_names = char(M_.param_names, 'rhonw');
M_.param_names_tex = char(M_.param_names_tex, 'rhonw');
M_.param_names_long = char(M_.param_names_long, 'rhonw');
M_.param_names = char(M_.param_names, 'rhoupsilon');
M_.param_names_tex = char(M_.param_names_tex, 'rhoupsilon');
M_.param_names_long = char(M_.param_names_long, 'rhoupsilon');
M_.param_names = char(M_.param_names, 'gammamiu100');
M_.param_names_tex = char(M_.param_names_tex, 'gammamiu100');
M_.param_names_long = char(M_.param_names_long, 'gammamiu100');
M_.param_names = char(M_.param_names, 'cb');
M_.param_names_tex = char(M_.param_names_tex, 'cb');
M_.param_names_long = char(M_.param_names_long, 'cb');
M_.exo_det_nbr = 0;
M_.exo_nbr = 11;
M_.endo_nbr = 90;
M_.param_nbr = 77;
M_.orig_endo_nbr = 67;
M_.aux_vars(1).endo_index = 68;
M_.aux_vars(1).type = 0;
M_.aux_vars(2).endo_index = 69;
M_.aux_vars(2).type = 0;
M_.aux_vars(3).endo_index = 70;
M_.aux_vars(3).type = 0;
M_.aux_vars(4).endo_index = 71;
M_.aux_vars(4).type = 0;
M_.aux_vars(5).endo_index = 72;
M_.aux_vars(5).type = 0;
M_.aux_vars(6).endo_index = 73;
M_.aux_vars(6).type = 0;
M_.aux_vars(7).endo_index = 74;
M_.aux_vars(7).type = 0;
M_.aux_vars(8).endo_index = 75;
M_.aux_vars(8).type = 0;
M_.aux_vars(9).endo_index = 76;
M_.aux_vars(9).type = 0;
M_.aux_vars(10).endo_index = 77;
M_.aux_vars(10).type = 1;
M_.aux_vars(10).orig_index = 6;
M_.aux_vars(10).orig_lead_lag = -1;
M_.aux_vars(11).endo_index = 78;
M_.aux_vars(11).type = 1;
M_.aux_vars(11).orig_index = 6;
M_.aux_vars(11).orig_lead_lag = -2;
M_.aux_vars(12).endo_index = 79;
M_.aux_vars(12).type = 1;
M_.aux_vars(12).orig_index = 66;
M_.aux_vars(12).orig_lead_lag = -1;
M_.aux_vars(13).endo_index = 80;
M_.aux_vars(13).type = 1;
M_.aux_vars(13).orig_index = 66;
M_.aux_vars(13).orig_lead_lag = -2;
M_.aux_vars(14).endo_index = 81;
M_.aux_vars(14).type = 1;
M_.aux_vars(14).orig_index = 66;
M_.aux_vars(14).orig_lead_lag = -3;
M_.aux_vars(15).endo_index = 82;
M_.aux_vars(15).type = 1;
M_.aux_vars(15).orig_index = 65;
M_.aux_vars(15).orig_lead_lag = -1;
M_.aux_vars(16).endo_index = 83;
M_.aux_vars(16).type = 1;
M_.aux_vars(16).orig_index = 65;
M_.aux_vars(16).orig_lead_lag = -2;
M_.aux_vars(17).endo_index = 84;
M_.aux_vars(17).type = 1;
M_.aux_vars(17).orig_index = 65;
M_.aux_vars(17).orig_lead_lag = -3;
M_.aux_vars(18).endo_index = 85;
M_.aux_vars(18).type = 1;
M_.aux_vars(18).orig_index = 62;
M_.aux_vars(18).orig_lead_lag = -1;
M_.aux_vars(19).endo_index = 86;
M_.aux_vars(19).type = 1;
M_.aux_vars(19).orig_index = 62;
M_.aux_vars(19).orig_lead_lag = -2;
M_.aux_vars(20).endo_index = 87;
M_.aux_vars(20).type = 1;
M_.aux_vars(20).orig_index = 62;
M_.aux_vars(20).orig_lead_lag = -3;
M_.aux_vars(21).endo_index = 88;
M_.aux_vars(21).type = 1;
M_.aux_vars(21).orig_index = 64;
M_.aux_vars(21).orig_lead_lag = -1;
M_.aux_vars(22).endo_index = 89;
M_.aux_vars(22).type = 1;
M_.aux_vars(22).orig_index = 64;
M_.aux_vars(22).orig_lead_lag = -2;
M_.aux_vars(23).endo_index = 90;
M_.aux_vars(23).type = 1;
M_.aux_vars(23).orig_index = 64;
M_.aux_vars(23).orig_lead_lag = -3;
M_.Sigma_e = zeros(11, 11);
M_.Correlation_matrix = eye(11, 11);
M_.H = 0;
M_.Correlation_matrix_ME = 1;
M_.sigma_e_is_diagonal = 1;
options_.linear = 1;
options_.block=0;
options_.bytecode=0;
options_.use_dll=0;
erase_compiled_function('US_CFOP14_static');
erase_compiled_function('US_CFOP14_dynamic');
M_.lead_lag_incidence = [
 0 49 0;
 0 50 0;
 0 51 0;
 0 52 0;
 1 53 139;
 2 54 140;
 0 55 0;
 0 56 141;
 3 57 142;
 0 58 0;
 0 59 0;
 4 60 143;
 5 61 0;
 0 62 0;
 0 63 0;
 6 64 0;
 7 65 0;
 8 66 0;
 9 67 0;
 10 68 0;
 11 69 0;
 12 70 0;
 13 71 0;
 14 72 0;
 0 73 0;
 0 74 0;
 0 75 0;
 0 76 0;
 0 77 0;
 0 78 0;
 0 79 144;
 15 80 145;
 0 81 0;
 0 82 0;
 16 83 146;
 17 84 0;
 0 85 0;
 0 86 0;
 0 87 147;
 0 88 148;
 18 89 0;
 19 90 0;
 0 91 0;
 0 92 0;
 20 93 0;
 21 94 0;
 22 95 0;
 23 96 0;
 24 97 0;
 25 98 0;
 26 99 0;
 0 100 0;
 0 101 0;
 0 102 0;
 0 103 0;
 27 104 0;
 28 105 0;
 29 106 0;
 30 107 0;
 0 108 0;
 0 109 0;
 31 110 0;
 0 111 0;
 32 112 149;
 33 113 150;
 34 114 151;
 0 115 0;
 0 116 152;
 0 117 153;
 0 118 154;
 0 119 155;
 0 120 156;
 0 121 157;
 0 122 158;
 0 123 159;
 0 124 160;
 35 125 0;
 36 126 0;
 37 127 0;
 38 128 0;
 39 129 0;
 40 130 0;
 41 131 0;
 42 132 0;
 43 133 0;
 44 134 0;
 45 135 0;
 46 136 0;
 47 137 0;
 48 138 0;]';
M_.nstatic = 29;
M_.nfwrd   = 13;
M_.npred   = 39;
M_.nboth   = 9;
M_.nsfwrd   = 22;
M_.nspred   = 48;
M_.ndynamic   = 61;
M_.equations_tags = {
};
M_.static_and_dynamic_models_differ = 0;
M_.exo_names_orig_ord = [1:11];
M_.maximum_lag = 1;
M_.maximum_lead = 1;
M_.maximum_endo_lag = 1;
M_.maximum_endo_lead = 1;
oo_.steady_state = zeros(90, 1);
M_.maximum_exo_lag = 0;
M_.maximum_exo_lead = 0;
oo_.exo_steady_state = zeros(11, 1);
M_.params = NaN(77, 1);
M_.NNZDerivatives = zeros(3, 1);
M_.NNZDerivatives(1) = 358;
M_.NNZDerivatives(2) = 0;
M_.NNZDerivatives(3) = -1;
M_.params( 35 ) = 0.16;
alpha = M_.params( 35 );
M_.params( 36 ) = 0.025;
delta = M_.params( 36 );
M_.params( 37 ) = 0.15;
iotap = M_.params( 37 );
M_.params( 38 ) = 0.17;
iotaw = M_.params( 38 );
M_.params( 39 ) = 0.49;
gamma100 = M_.params( 39 );
M_.params( 40 ) = 0.88;
h = M_.params( 40 );
M_.params( 41 ) = 0.18;
lambdapss = M_.params( 41 );
M_.params( 42 ) = 0.08;
lambdawss = M_.params( 42 );
M_.params( 43 ) = 1.39096812846378;
Lss = M_.params( 43 );
M_.params( 44 ) = 1.0072;
pss100 = M_.params( 44 );
M_.params( 45 ) = 0.14;
Fbeta = M_.params( 45 );
M_.params( 46 ) = 1.282051282051282;
gss = M_.params( 46 );
M_.params( 47 ) = 3.39;
niu = M_.params( 47 );
M_.params( 48 ) = 0.74;
xip = M_.params( 48 );
M_.params( 49 ) = 0.66;
xiw = M_.params( 49 );
M_.params( 50 ) = 5.17;
chi = M_.params( 50 );
M_.params( 51 ) = 2.43;
Sadj = M_.params( 51 );
M_.params( 52 ) = 2.11;
fp = M_.params( 52 );
M_.params( 53 ) = 0.11;
fy = M_.params( 53 );
M_.params( 54 ) = 0.2;
fdy = M_.params( 54 );
M_.params( 55 ) = 0.86;
rhoR = M_.params( 55 );
M_.params( 56 ) = 0.37;
rhoz = M_.params( 56 );
M_.params( 57 ) = 0.99;
rhog = M_.params( 57 );
M_.params( 58 ) = 0.35;
rhomiu = M_.params( 58 );
M_.params( 59 ) = 0.95;
rholambdap = M_.params( 59 );
M_.params( 60 ) = 0.96;
rholambdaw = M_.params( 60 );
M_.params( 61 ) = 0.58;
rhob = M_.params( 61 );
M_.params( 62 ) = 0.05;
rhomp = M_.params( 62 );
M_.params( 63 ) = 0.71;
rhoARMAlambdap = M_.params( 63 );
M_.params( 64 ) = 0.99;
rhoARMAlambdaw = M_.params( 64 );
M_.params( 76 ) = 0.51;
gammamiu100 = M_.params( 76 );
M_.params( 75 ) = 0.89;
rhoupsilon = M_.params( 75 );
M_.params( 65 ) = 0.19;
cnu = M_.params( 65 );
M_.params( 66 ) = 0;
cnustar = M_.params( 66 );
M_.params( 67 ) = 0.94;
cgamma = M_.params( 67 );
M_.params( 68 ) = 0.005;
crp = M_.params( 68 );
M_.params( 69 ) = 0;
crpstar = M_.params( 69 );
M_.params( 70 ) = 1.95;
ckappa = M_.params( 70 );
M_.params( 71 ) = 0.95;
ctheta = M_.params( 71 );
M_.params( 72 ) = 2.42;
cchi = M_.params( 72 );
M_.params( 73 ) = 0.87;
rhoefp = M_.params( 73 );
M_.params( 74 ) = 0.78;
rhonw = M_.params( 74 );
M_.params( 77 ) = 0;
cb = M_.params( 77 );
thispath = cd;                                                           
cd('..');                                                                
load policy_param.mat;                                                   
for i=1:33                                                               
deep_parameter_name = M_.param_names(i,:);                           
eval(['M_.params(i)  = ' deep_parameter_name ' ;'])                  
end                                                                      
cd(thispath);
M_.params( 34 ) = 1;
coffispol = M_.params( 34 );
%
% SHOCKS instructions
%
make_ex_;
M_.exo_det_length = 0;
M_.Sigma_e(2, 2) = 0.7921;
M_.Sigma_e(3, 3) = 0.3481;
M_.Sigma_e(4, 4) = 0.07290000000000001;
M_.Sigma_e(5, 5) = 0.09610000000000001;
M_.Sigma_e(6, 6) = 0.0009;
M_.Sigma_e(7, 7) = 0.0064;
M_.Sigma_e(8, 8) = 5.7121;
M_.Sigma_e(9, 9) = 0.7569;
M_.Sigma_e(11, 11) = 0.1296;
save('US_CFOP14_results.mat', 'oo_', 'M_', 'options_');
if exist('estim_params_', 'var') == 1
  save('US_CFOP14_results.mat', 'estim_params_', '-append');
end
if exist('bayestopt_', 'var') == 1
  save('US_CFOP14_results.mat', 'bayestopt_', '-append');
end
if exist('dataset_', 'var') == 1
  save('US_CFOP14_results.mat', 'dataset_', '-append');
end
if exist('estimation_info', 'var') == 1
  save('US_CFOP14_results.mat', 'estimation_info', '-append');
end


disp(['Total computing time : ' dynsec2hms(toc) ]);
if ~isempty(lastwarn)
  disp('Note: warning(s) encountered in MATLAB/Octave code')
end
diary off
