%
% Status : main Dynare file 
%
% Warning : this file is generated automatically by Dynare
%           from model file (.mod)

tic;
global M_ oo_ options_ ys0_ ex0_ estimation_info
options_ = [];
M_.fname = 'US_OR03';
%
% Some global variables initialization
%
global_initialization;
diary off;
diary('US_OR03.log');
M_.exo_names = 'e';
M_.exo_names_tex = 'e';
M_.exo_names_long = 'e';
M_.exo_names = char(M_.exo_names, 'u');
M_.exo_names_tex = char(M_.exo_names_tex, 'u');
M_.exo_names_long = char(M_.exo_names_long, 'u');
M_.exo_names = char(M_.exo_names, 'interest_');
M_.exo_names_tex = char(M_.exo_names_tex, 'interest\_');
M_.exo_names_long = char(M_.exo_names_long, 'interest_');
M_.endo_names = 'y';
M_.endo_names_tex = 'y';
M_.endo_names_long = 'y';
M_.endo_names = char(M_.endo_names, 'pi');
M_.endo_names_tex = char(M_.endo_names_tex, 'pi');
M_.endo_names_long = char(M_.endo_names_long, 'pi');
M_.endo_names = char(M_.endo_names, 'f');
M_.endo_names_tex = char(M_.endo_names_tex, 'f');
M_.endo_names_long = char(M_.endo_names_long, 'f');
M_.endo_names = char(M_.endo_names, 'interest');
M_.endo_names_tex = char(M_.endo_names_tex, 'interest');
M_.endo_names_long = char(M_.endo_names_long, 'interest');
M_.endo_names = char(M_.endo_names, 'inflation');
M_.endo_names_tex = char(M_.endo_names_tex, 'inflation');
M_.endo_names_long = char(M_.endo_names_long, 'inflation');
M_.endo_names = char(M_.endo_names, 'inflationq');
M_.endo_names_tex = char(M_.endo_names_tex, 'inflationq');
M_.endo_names_long = char(M_.endo_names_long, 'inflationq');
M_.endo_names = char(M_.endo_names, 'outputgap');
M_.endo_names_tex = char(M_.endo_names_tex, 'outputgap');
M_.endo_names_long = char(M_.endo_names_long, 'outputgap');
M_.endo_names = char(M_.endo_names, 'output');
M_.endo_names_tex = char(M_.endo_names_tex, 'output');
M_.endo_names_long = char(M_.endo_names_long, 'output');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_73');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_73');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_73');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_77');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_77');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_77');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_81');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_81');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_81');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_108');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_108');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_108');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_112');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_112');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_112');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_116');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_116');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_116');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_143');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_143');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_143');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_147');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_147');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_147');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_151');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_151');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_151');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_1_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_1\_1');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_1_1');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_1_2');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_1\_2');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_1_2');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_7_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_7\_1');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_7_1');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_7_2');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_7\_2');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_7_2');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_7_3');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_7\_3');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_7_3');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_6_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_6\_1');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_6_1');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_6_2');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_6\_2');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_6_2');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_6_3');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_6\_3');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_6_3');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_3_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_3\_1');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_3_1');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_3_2');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_3\_2');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_3_2');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_3_3');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_3\_3');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_3_3');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_5_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_5\_1');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_5_1');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_5_2');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_5\_2');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_5_2');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_5_3');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_5\_3');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_5_3');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_1_3');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_1\_3');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_1_3');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_0_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_0\_1');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_0_1');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_0_2');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_0\_2');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_0_2');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_0_3');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_0\_3');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_0_3');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_2_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_2\_1');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_2_1');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_2_2');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_2\_2');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_2_2');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_2_3');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_2\_3');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_2_3');
M_.param_names = 'cofintintb1';
M_.param_names_tex = 'cofintintb1';
M_.param_names_long = 'cofintintb1';
M_.param_names = char(M_.param_names, 'cofintintb2');
M_.param_names_tex = char(M_.param_names_tex, 'cofintintb2');
M_.param_names_long = char(M_.param_names_long, 'cofintintb2');
M_.param_names = char(M_.param_names, 'cofintintb3');
M_.param_names_tex = char(M_.param_names_tex, 'cofintintb3');
M_.param_names_long = char(M_.param_names_long, 'cofintintb3');
M_.param_names = char(M_.param_names, 'cofintintb4');
M_.param_names_tex = char(M_.param_names_tex, 'cofintintb4');
M_.param_names_long = char(M_.param_names_long, 'cofintintb4');
M_.param_names = char(M_.param_names, 'cofintinf0');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinf0');
M_.param_names_long = char(M_.param_names_long, 'cofintinf0');
M_.param_names = char(M_.param_names, 'cofintinfb1');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinfb1');
M_.param_names_long = char(M_.param_names_long, 'cofintinfb1');
M_.param_names = char(M_.param_names, 'cofintinfb2');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinfb2');
M_.param_names_long = char(M_.param_names_long, 'cofintinfb2');
M_.param_names = char(M_.param_names, 'cofintinfb3');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinfb3');
M_.param_names_long = char(M_.param_names_long, 'cofintinfb3');
M_.param_names = char(M_.param_names, 'cofintinfb4');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinfb4');
M_.param_names_long = char(M_.param_names_long, 'cofintinfb4');
M_.param_names = char(M_.param_names, 'cofintinff1');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinff1');
M_.param_names_long = char(M_.param_names_long, 'cofintinff1');
M_.param_names = char(M_.param_names, 'cofintinff2');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinff2');
M_.param_names_long = char(M_.param_names_long, 'cofintinff2');
M_.param_names = char(M_.param_names, 'cofintinff3');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinff3');
M_.param_names_long = char(M_.param_names_long, 'cofintinff3');
M_.param_names = char(M_.param_names, 'cofintinff4');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinff4');
M_.param_names_long = char(M_.param_names_long, 'cofintinff4');
M_.param_names = char(M_.param_names, 'cofintout');
M_.param_names_tex = char(M_.param_names_tex, 'cofintout');
M_.param_names_long = char(M_.param_names_long, 'cofintout');
M_.param_names = char(M_.param_names, 'cofintoutb1');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutb1');
M_.param_names_long = char(M_.param_names_long, 'cofintoutb1');
M_.param_names = char(M_.param_names, 'cofintoutb2');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutb2');
M_.param_names_long = char(M_.param_names_long, 'cofintoutb2');
M_.param_names = char(M_.param_names, 'cofintoutb3');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutb3');
M_.param_names_long = char(M_.param_names_long, 'cofintoutb3');
M_.param_names = char(M_.param_names, 'cofintoutb4');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutb4');
M_.param_names_long = char(M_.param_names_long, 'cofintoutb4');
M_.param_names = char(M_.param_names, 'cofintoutf1');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutf1');
M_.param_names_long = char(M_.param_names_long, 'cofintoutf1');
M_.param_names = char(M_.param_names, 'cofintoutf2');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutf2');
M_.param_names_long = char(M_.param_names_long, 'cofintoutf2');
M_.param_names = char(M_.param_names, 'cofintoutf3');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutf3');
M_.param_names_long = char(M_.param_names_long, 'cofintoutf3');
M_.param_names = char(M_.param_names, 'cofintoutf4');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutf4');
M_.param_names_long = char(M_.param_names_long, 'cofintoutf4');
M_.param_names = char(M_.param_names, 'cofintoutp');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutp');
M_.param_names_long = char(M_.param_names_long, 'cofintoutp');
M_.param_names = char(M_.param_names, 'cofintoutpb1');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpb1');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpb1');
M_.param_names = char(M_.param_names, 'cofintoutpb2');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpb2');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpb2');
M_.param_names = char(M_.param_names, 'cofintoutpb3');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpb3');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpb3');
M_.param_names = char(M_.param_names, 'cofintoutpb4');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpb4');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpb4');
M_.param_names = char(M_.param_names, 'cofintoutpf1');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpf1');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpf1');
M_.param_names = char(M_.param_names, 'cofintoutpf2');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpf2');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpf2');
M_.param_names = char(M_.param_names, 'cofintoutpf3');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpf3');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpf3');
M_.param_names = char(M_.param_names, 'cofintoutpf4');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpf4');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpf4');
M_.param_names = char(M_.param_names, 'std_r_');
M_.param_names_tex = char(M_.param_names_tex, 'std\_r\_');
M_.param_names_long = char(M_.param_names_long, 'std_r_');
M_.param_names = char(M_.param_names, 'std_r_quart');
M_.param_names_tex = char(M_.param_names_tex, 'std\_r\_quart');
M_.param_names_long = char(M_.param_names_long, 'std_r_quart');
M_.param_names = char(M_.param_names, 'coffispol');
M_.param_names_tex = char(M_.param_names_tex, 'coffispol');
M_.param_names_long = char(M_.param_names_long, 'coffispol');
M_.param_names = char(M_.param_names, 'b0');
M_.param_names_tex = char(M_.param_names_tex, 'b0');
M_.param_names_long = char(M_.param_names_long, 'b0');
M_.param_names = char(M_.param_names, 'bpi1');
M_.param_names_tex = char(M_.param_names_tex, 'bpi1');
M_.param_names_long = char(M_.param_names_long, 'bpi1');
M_.param_names = char(M_.param_names, 'bpi2');
M_.param_names_tex = char(M_.param_names_tex, 'bpi2');
M_.param_names_long = char(M_.param_names_long, 'bpi2');
M_.param_names = char(M_.param_names, 'bpi3');
M_.param_names_tex = char(M_.param_names_tex, 'bpi3');
M_.param_names_long = char(M_.param_names_long, 'bpi3');
M_.param_names = char(M_.param_names, 'bpi4');
M_.param_names_tex = char(M_.param_names_tex, 'bpi4');
M_.param_names_long = char(M_.param_names_long, 'bpi4');
M_.param_names = char(M_.param_names, 'by1');
M_.param_names_tex = char(M_.param_names_tex, 'by1');
M_.param_names_long = char(M_.param_names_long, 'by1');
M_.param_names = char(M_.param_names, 'by2');
M_.param_names_tex = char(M_.param_names_tex, 'by2');
M_.param_names_long = char(M_.param_names_long, 'by2');
M_.param_names = char(M_.param_names, 'by3');
M_.param_names_tex = char(M_.param_names_tex, 'by3');
M_.param_names_long = char(M_.param_names_long, 'by3');
M_.param_names = char(M_.param_names, 'by4');
M_.param_names_tex = char(M_.param_names_tex, 'by4');
M_.param_names_long = char(M_.param_names_long, 'by4');
M_.param_names = char(M_.param_names, 'bf1');
M_.param_names_tex = char(M_.param_names_tex, 'bf1');
M_.param_names_long = char(M_.param_names_long, 'bf1');
M_.param_names = char(M_.param_names, 'bf2');
M_.param_names_tex = char(M_.param_names_tex, 'bf2');
M_.param_names_long = char(M_.param_names_long, 'bf2');
M_.param_names = char(M_.param_names, 'bf3');
M_.param_names_tex = char(M_.param_names_tex, 'bf3');
M_.param_names_long = char(M_.param_names_long, 'bf3');
M_.param_names = char(M_.param_names, 'bf4');
M_.param_names_tex = char(M_.param_names_tex, 'bf4');
M_.param_names_long = char(M_.param_names_long, 'bf4');
M_.param_names = char(M_.param_names, 'api1');
M_.param_names_tex = char(M_.param_names_tex, 'api1');
M_.param_names_long = char(M_.param_names_long, 'api1');
M_.param_names = char(M_.param_names, 'api2');
M_.param_names_tex = char(M_.param_names_tex, 'api2');
M_.param_names_long = char(M_.param_names_long, 'api2');
M_.param_names = char(M_.param_names, 'api3');
M_.param_names_tex = char(M_.param_names_tex, 'api3');
M_.param_names_long = char(M_.param_names_long, 'api3');
M_.param_names = char(M_.param_names, 'api4');
M_.param_names_tex = char(M_.param_names_tex, 'api4');
M_.param_names_long = char(M_.param_names_long, 'api4');
M_.param_names = char(M_.param_names, 'ay0');
M_.param_names_tex = char(M_.param_names_tex, 'ay0');
M_.param_names_long = char(M_.param_names_long, 'ay0');
M_.param_names = char(M_.param_names, 'ay1');
M_.param_names_tex = char(M_.param_names_tex, 'ay1');
M_.param_names_long = char(M_.param_names_long, 'ay1');
M_.param_names = char(M_.param_names, 'ay2');
M_.param_names_tex = char(M_.param_names_tex, 'ay2');
M_.param_names_long = char(M_.param_names_long, 'ay2');
M_.param_names = char(M_.param_names, 'ay3');
M_.param_names_tex = char(M_.param_names_tex, 'ay3');
M_.param_names_long = char(M_.param_names_long, 'ay3');
M_.param_names = char(M_.param_names, 'ay4');
M_.param_names_tex = char(M_.param_names_tex, 'ay4');
M_.param_names_long = char(M_.param_names_long, 'ay4');
M_.exo_det_nbr = 0;
M_.exo_nbr = 3;
M_.endo_nbr = 38;
M_.param_nbr = 56;
M_.orig_endo_nbr = 8;
M_.aux_vars(1).endo_index = 9;
M_.aux_vars(1).type = 0;
M_.aux_vars(2).endo_index = 10;
M_.aux_vars(2).type = 0;
M_.aux_vars(3).endo_index = 11;
M_.aux_vars(3).type = 0;
M_.aux_vars(4).endo_index = 12;
M_.aux_vars(4).type = 0;
M_.aux_vars(5).endo_index = 13;
M_.aux_vars(5).type = 0;
M_.aux_vars(6).endo_index = 14;
M_.aux_vars(6).type = 0;
M_.aux_vars(7).endo_index = 15;
M_.aux_vars(7).type = 0;
M_.aux_vars(8).endo_index = 16;
M_.aux_vars(8).type = 0;
M_.aux_vars(9).endo_index = 17;
M_.aux_vars(9).type = 0;
M_.aux_vars(10).endo_index = 18;
M_.aux_vars(10).type = 1;
M_.aux_vars(10).orig_index = 2;
M_.aux_vars(10).orig_lead_lag = -1;
M_.aux_vars(11).endo_index = 19;
M_.aux_vars(11).type = 1;
M_.aux_vars(11).orig_index = 2;
M_.aux_vars(11).orig_lead_lag = -2;
M_.aux_vars(12).endo_index = 20;
M_.aux_vars(12).type = 1;
M_.aux_vars(12).orig_index = 8;
M_.aux_vars(12).orig_lead_lag = -1;
M_.aux_vars(13).endo_index = 21;
M_.aux_vars(13).type = 1;
M_.aux_vars(13).orig_index = 8;
M_.aux_vars(13).orig_lead_lag = -2;
M_.aux_vars(14).endo_index = 22;
M_.aux_vars(14).type = 1;
M_.aux_vars(14).orig_index = 8;
M_.aux_vars(14).orig_lead_lag = -3;
M_.aux_vars(15).endo_index = 23;
M_.aux_vars(15).type = 1;
M_.aux_vars(15).orig_index = 7;
M_.aux_vars(15).orig_lead_lag = -1;
M_.aux_vars(16).endo_index = 24;
M_.aux_vars(16).type = 1;
M_.aux_vars(16).orig_index = 7;
M_.aux_vars(16).orig_lead_lag = -2;
M_.aux_vars(17).endo_index = 25;
M_.aux_vars(17).type = 1;
M_.aux_vars(17).orig_index = 7;
M_.aux_vars(17).orig_lead_lag = -3;
M_.aux_vars(18).endo_index = 26;
M_.aux_vars(18).type = 1;
M_.aux_vars(18).orig_index = 4;
M_.aux_vars(18).orig_lead_lag = -1;
M_.aux_vars(19).endo_index = 27;
M_.aux_vars(19).type = 1;
M_.aux_vars(19).orig_index = 4;
M_.aux_vars(19).orig_lead_lag = -2;
M_.aux_vars(20).endo_index = 28;
M_.aux_vars(20).type = 1;
M_.aux_vars(20).orig_index = 4;
M_.aux_vars(20).orig_lead_lag = -3;
M_.aux_vars(21).endo_index = 29;
M_.aux_vars(21).type = 1;
M_.aux_vars(21).orig_index = 6;
M_.aux_vars(21).orig_lead_lag = -1;
M_.aux_vars(22).endo_index = 30;
M_.aux_vars(22).type = 1;
M_.aux_vars(22).orig_index = 6;
M_.aux_vars(22).orig_lead_lag = -2;
M_.aux_vars(23).endo_index = 31;
M_.aux_vars(23).type = 1;
M_.aux_vars(23).orig_index = 6;
M_.aux_vars(23).orig_lead_lag = -3;
M_.aux_vars(24).endo_index = 32;
M_.aux_vars(24).type = 1;
M_.aux_vars(24).orig_index = 2;
M_.aux_vars(24).orig_lead_lag = -3;
M_.aux_vars(25).endo_index = 33;
M_.aux_vars(25).type = 1;
M_.aux_vars(25).orig_index = 1;
M_.aux_vars(25).orig_lead_lag = -1;
M_.aux_vars(26).endo_index = 34;
M_.aux_vars(26).type = 1;
M_.aux_vars(26).orig_index = 1;
M_.aux_vars(26).orig_lead_lag = -2;
M_.aux_vars(27).endo_index = 35;
M_.aux_vars(27).type = 1;
M_.aux_vars(27).orig_index = 1;
M_.aux_vars(27).orig_lead_lag = -3;
M_.aux_vars(28).endo_index = 36;
M_.aux_vars(28).type = 1;
M_.aux_vars(28).orig_index = 3;
M_.aux_vars(28).orig_lead_lag = -1;
M_.aux_vars(29).endo_index = 37;
M_.aux_vars(29).type = 1;
M_.aux_vars(29).orig_index = 3;
M_.aux_vars(29).orig_lead_lag = -2;
M_.aux_vars(30).endo_index = 38;
M_.aux_vars(30).type = 1;
M_.aux_vars(30).orig_index = 3;
M_.aux_vars(30).orig_lead_lag = -3;
M_.Sigma_e = zeros(3, 3);
M_.Correlation_matrix = eye(3, 3);
M_.H = 0;
M_.Correlation_matrix_ME = 1;
M_.sigma_e_is_diagonal = 1;
options_.linear = 1;
options_.block=0;
options_.bytecode=0;
options_.use_dll=0;
erase_compiled_function('US_OR03_static');
erase_compiled_function('US_OR03_dynamic');
M_.lead_lag_incidence = [
 1 29 0;
 2 30 0;
 3 31 0;
 4 32 0;
 0 33 0;
 5 34 67;
 6 35 68;
 7 36 69;
 0 37 70;
 0 38 71;
 0 39 72;
 0 40 73;
 0 41 74;
 0 42 75;
 0 43 76;
 0 44 77;
 0 45 78;
 8 46 0;
 9 47 0;
 10 48 0;
 11 49 0;
 12 50 0;
 13 51 0;
 14 52 0;
 15 53 0;
 16 54 0;
 17 55 0;
 18 56 0;
 19 57 0;
 20 58 0;
 21 59 0;
 22 60 0;
 23 61 0;
 24 62 0;
 25 63 0;
 26 64 0;
 27 65 0;
 28 66 0;]';
M_.nstatic = 1;
M_.nfwrd   = 9;
M_.npred   = 25;
M_.nboth   = 3;
M_.nsfwrd   = 12;
M_.nspred   = 28;
M_.ndynamic   = 37;
M_.equations_tags = {
};
M_.static_and_dynamic_models_differ = 0;
M_.exo_names_orig_ord = [1:3];
M_.maximum_lag = 1;
M_.maximum_lead = 1;
M_.maximum_endo_lag = 1;
M_.maximum_endo_lead = 1;
oo_.steady_state = zeros(38, 1);
M_.maximum_exo_lag = 0;
M_.maximum_exo_lead = 0;
oo_.exo_steady_state = zeros(3, 1);
M_.params = NaN(56, 1);
M_.NNZDerivatives = zeros(3, 1);
M_.NNZDerivatives(1) = 131;
M_.NNZDerivatives(2) = 0;
M_.NNZDerivatives(3) = -1;
M_.params( 35 ) = 0.175638173;
b0 = M_.params( 35 );
M_.params( 36 ) = 0.023509403;
bpi1 = M_.params( 36 );
M_.params( 37 ) = (-0.018273476);
bpi2 = M_.params( 37 );
M_.params( 38 ) = (-0.009214318);
bpi3 = M_.params( 38 );
M_.params( 39 ) = 0.085793876;
bpi4 = M_.params( 39 );
M_.params( 40 ) = 1.108346534;
by1 = M_.params( 40 );
M_.params( 41 ) = 0.111102286;
by2 = M_.params( 41 );
M_.params( 42 ) = (-0.184403424);
by3 = M_.params( 42 );
M_.params( 43 ) = (-0.090084761);
by4 = M_.params( 43 );
M_.params( 44 ) = (-0.021894643);
bf1 = M_.params( 44 );
M_.params( 45 ) = (-0.325769155);
bf2 = M_.params( 45 );
M_.params( 46 ) = 0.261153539;
bf3 = M_.params( 46 );
M_.params( 47 ) = 0.004694774;
bf4 = M_.params( 47 );
M_.params( 48 ) = 0.3280;
api1 = M_.params( 48 );
M_.params( 49 ) = 0.3034;
api2 = M_.params( 49 );
M_.params( 50 ) = 0.2584;
api3 = M_.params( 50 );
M_.params( 51 ) = 0.1102;
api4 = M_.params( 51 );
M_.params( 52 ) = 0.2835;
ay0 = M_.params( 52 );
M_.params( 53 ) = 0.0273;
ay1 = M_.params( 53 );
M_.params( 54 ) = (-0.3418);
ay2 = M_.params( 54 );
M_.params( 55 ) = 0.2986;
ay3 = M_.params( 55 );
M_.params( 56 ) = (-0.1245);
ay4 = M_.params( 56 );
thispath = cd;                                                           
cd('..');                                                                
load policy_param.mat;                                                   
for i=1:33                                                               
deep_parameter_name = M_.param_names(i,:);                           
eval(['M_.params(i)  = ' deep_parameter_name ' ;'])                  
end                                                                      
cd(thispath);    
%
% SHOCKS instructions
%
make_ex_;
M_.exo_det_length = 0;
M_.Sigma_e(1, 1) = 1.97962275897416;
M_.Sigma_e(2, 2) = 0.5944797803904721;
M_.Sigma_e(3, 3) = 0;
save('US_OR03_results.mat', 'oo_', 'M_', 'options_');
if exist('estim_params_', 'var') == 1
  save('US_OR03_results.mat', 'estim_params_', '-append');
end
if exist('bayestopt_', 'var') == 1
  save('US_OR03_results.mat', 'bayestopt_', '-append');
end
if exist('dataset_', 'var') == 1
  save('US_OR03_results.mat', 'dataset_', '-append');
end
if exist('estimation_info', 'var') == 1
  save('US_OR03_results.mat', 'estimation_info', '-append');
end


disp(['Total computing time : ' dynsec2hms(toc) ]);
if ~isempty(lastwarn)
  disp('Note: warning(s) encountered in MATLAB/Octave code')
end
diary off
