%
% Status : main Dynare file
%
% Warning : this file is generated automatically by Dynare
%           from model file (.mod)

if isoctave || matlab_ver_less_than('8.6')
    clear all
else
    clearvars -global
    clear_persistent_variables(fileparts(which('dynare')), false)
end
tic0 = tic;
% Save empty dates and dseries objects in memory.
dates('initialize');
dseries('initialize');
% Define global variables.
global M_ options_ oo_ estim_params_ bayestopt_ dataset_ dataset_info estimation_info ys0_ ex0_
options_ = [];
M_.fname = 'US_IR15';
M_.dynare_version = '4.5.4';
oo_.dynare_version = '4.5.4';
options_.dynare_version = '4.5.4';
%
% Some global variables initialization
%
global_initialization;
diary off;
diary('US_IR15.log');
M_.exo_names = 'epsilon_pi';
M_.exo_names_tex = 'epsilon\_pi';
M_.exo_names_long = 'epsilon_pi';
M_.exo_names = char(M_.exo_names, 'epsilon_y');
M_.exo_names_tex = char(M_.exo_names_tex, 'epsilon\_y');
M_.exo_names_long = char(M_.exo_names_long, 'epsilon_y');
M_.exo_names = char(M_.exo_names, 'epsilon_tau');
M_.exo_names_tex = char(M_.exo_names_tex, 'epsilon\_tau');
M_.exo_names_long = char(M_.exo_names_long, 'epsilon_tau');
M_.exo_names = char(M_.exo_names, 'epsilon_v');
M_.exo_names_tex = char(M_.exo_names_tex, 'epsilon\_v');
M_.exo_names_long = char(M_.exo_names_long, 'epsilon_v');
M_.exo_names = char(M_.exo_names, 'eta_4');
M_.exo_names_tex = char(M_.exo_names_tex, 'eta\_4');
M_.exo_names_long = char(M_.exo_names_long, 'eta_4');
M_.exo_names = char(M_.exo_names, 'eta_8');
M_.exo_names_tex = char(M_.exo_names_tex, 'eta\_8');
M_.exo_names_long = char(M_.exo_names_long, 'eta_8');
M_.exo_names = char(M_.exo_names, 'eta_16');
M_.exo_names_tex = char(M_.exo_names_tex, 'eta\_16');
M_.exo_names_long = char(M_.exo_names_long, 'eta_16');
M_.exo_names = char(M_.exo_names, 'interest_');
M_.exo_names_tex = char(M_.exo_names_tex, 'interest\_');
M_.exo_names_long = char(M_.exo_names_long, 'interest_');
M_.endo_names = 'g_r';
M_.endo_names_tex = 'g\_r';
M_.endo_names_long = 'g_r';
M_.endo_names = char(M_.endo_names, 'g_pi');
M_.endo_names_tex = char(M_.endo_names_tex, 'g\_pi');
M_.endo_names_long = char(M_.endo_names_long, 'g_pi');
M_.endo_names = char(M_.endo_names, 'g_y');
M_.endo_names_tex = char(M_.endo_names_tex, 'g\_y');
M_.endo_names_long = char(M_.endo_names_long, 'g_y');
M_.endo_names = char(M_.endo_names, 'tau');
M_.endo_names_tex = char(M_.endo_names_tex, 'tau');
M_.endo_names_long = char(M_.endo_names_long, 'tau');
M_.endo_names = char(M_.endo_names, 'v');
M_.endo_names_tex = char(M_.endo_names_tex, 'v');
M_.endo_names_long = char(M_.endo_names_long, 'v');
M_.endo_names = char(M_.endo_names, 'r');
M_.endo_names_tex = char(M_.endo_names_tex, 'r');
M_.endo_names_long = char(M_.endo_names_long, 'r');
M_.endo_names = char(M_.endo_names, 'pi');
M_.endo_names_tex = char(M_.endo_names_tex, 'pi');
M_.endo_names_long = char(M_.endo_names_long, 'pi');
M_.endo_names = char(M_.endo_names, 'g_y_obs');
M_.endo_names_tex = char(M_.endo_names_tex, 'g\_y\_obs');
M_.endo_names_long = char(M_.endo_names_long, 'g_y_obs');
M_.endo_names = char(M_.endo_names, 'y_4');
M_.endo_names_tex = char(M_.endo_names_tex, 'y\_4');
M_.endo_names_long = char(M_.endo_names_long, 'y_4');
M_.endo_names = char(M_.endo_names, 'y_8');
M_.endo_names_tex = char(M_.endo_names_tex, 'y\_8');
M_.endo_names_long = char(M_.endo_names_long, 'y_8');
M_.endo_names = char(M_.endo_names, 'y_12');
M_.endo_names_tex = char(M_.endo_names_tex, 'y\_12');
M_.endo_names_long = char(M_.endo_names_long, 'y_12');
M_.endo_names = char(M_.endo_names, 'y_16');
M_.endo_names_tex = char(M_.endo_names_tex, 'y\_16');
M_.endo_names_long = char(M_.endo_names_long, 'y_16');
M_.endo_names = char(M_.endo_names, 'y_20');
M_.endo_names_tex = char(M_.endo_names_tex, 'y\_20');
M_.endo_names_long = char(M_.endo_names_long, 'y_20');
M_.endo_names = char(M_.endo_names, 'P_y_4');
M_.endo_names_tex = char(M_.endo_names_tex, 'P\_y\_4');
M_.endo_names_long = char(M_.endo_names_long, 'P_y_4');
M_.endo_names = char(M_.endo_names, 'P_y_8');
M_.endo_names_tex = char(M_.endo_names_tex, 'P\_y\_8');
M_.endo_names_long = char(M_.endo_names_long, 'P_y_8');
M_.endo_names = char(M_.endo_names, 'P_y_12');
M_.endo_names_tex = char(M_.endo_names_tex, 'P\_y\_12');
M_.endo_names_long = char(M_.endo_names_long, 'P_y_12');
M_.endo_names = char(M_.endo_names, 'P_y_16');
M_.endo_names_tex = char(M_.endo_names_tex, 'P\_y\_16');
M_.endo_names_long = char(M_.endo_names_long, 'P_y_16');
M_.endo_names = char(M_.endo_names, 'P_y_20');
M_.endo_names_tex = char(M_.endo_names_tex, 'P\_y\_20');
M_.endo_names_long = char(M_.endo_names_long, 'P_y_20');
M_.endo_names = char(M_.endo_names, 'y_4_a');
M_.endo_names_tex = char(M_.endo_names_tex, 'y\_4\_a');
M_.endo_names_long = char(M_.endo_names_long, 'y_4_a');
M_.endo_names = char(M_.endo_names, 'P_y_4_a');
M_.endo_names_tex = char(M_.endo_names_tex, 'P\_y\_4\_a');
M_.endo_names_long = char(M_.endo_names_long, 'P_y_4_a');
M_.endo_names = char(M_.endo_names, 'g_pi_a');
M_.endo_names_tex = char(M_.endo_names_tex, 'g\_pi\_a');
M_.endo_names_long = char(M_.endo_names_long, 'g_pi_a');
M_.endo_names = char(M_.endo_names, 'y_8_a');
M_.endo_names_tex = char(M_.endo_names_tex, 'y\_8\_a');
M_.endo_names_long = char(M_.endo_names_long, 'y_8_a');
M_.endo_names = char(M_.endo_names, 'P_y_8_a');
M_.endo_names_tex = char(M_.endo_names_tex, 'P\_y\_8\_a');
M_.endo_names_long = char(M_.endo_names_long, 'P_y_8_a');
M_.endo_names = char(M_.endo_names, 'r_a');
M_.endo_names_tex = char(M_.endo_names_tex, 'r\_a');
M_.endo_names_long = char(M_.endo_names_long, 'r_a');
M_.endo_names = char(M_.endo_names, 'y_12_a');
M_.endo_names_tex = char(M_.endo_names_tex, 'y\_12\_a');
M_.endo_names_long = char(M_.endo_names_long, 'y_12_a');
M_.endo_names = char(M_.endo_names, 'P_y_12_a');
M_.endo_names_tex = char(M_.endo_names_tex, 'P\_y\_12\_a');
M_.endo_names_long = char(M_.endo_names_long, 'P_y_12_a');
M_.endo_names = char(M_.endo_names, 'y_16_a');
M_.endo_names_tex = char(M_.endo_names_tex, 'y\_16\_a');
M_.endo_names_long = char(M_.endo_names_long, 'y_16_a');
M_.endo_names = char(M_.endo_names, 'P_y_16_a');
M_.endo_names_tex = char(M_.endo_names_tex, 'P\_y\_16\_a');
M_.endo_names_long = char(M_.endo_names_long, 'P_y_16_a');
M_.endo_names = char(M_.endo_names, 'y_20_a');
M_.endo_names_tex = char(M_.endo_names_tex, 'y\_20\_a');
M_.endo_names_long = char(M_.endo_names_long, 'y_20_a');
M_.endo_names = char(M_.endo_names, 'P_y_20_a');
M_.endo_names_tex = char(M_.endo_names_tex, 'P\_y\_20\_a');
M_.endo_names_long = char(M_.endo_names_long, 'P_y_20_a');
M_.endo_names = char(M_.endo_names, 'epsilon_r');
M_.endo_names_tex = char(M_.endo_names_tex, 'epsilon\_r');
M_.endo_names_long = char(M_.endo_names_long, 'epsilon_r');
M_.endo_names = char(M_.endo_names, 'interest');
M_.endo_names_tex = char(M_.endo_names_tex, 'interest');
M_.endo_names_long = char(M_.endo_names_long, 'interest');
M_.endo_names = char(M_.endo_names, 'inflation');
M_.endo_names_tex = char(M_.endo_names_tex, 'inflation');
M_.endo_names_long = char(M_.endo_names_long, 'inflation');
M_.endo_names = char(M_.endo_names, 'inflationq');
M_.endo_names_tex = char(M_.endo_names_tex, 'inflationq');
M_.endo_names_long = char(M_.endo_names_long, 'inflationq');
M_.endo_names = char(M_.endo_names, 'outputgap');
M_.endo_names_tex = char(M_.endo_names_tex, 'outputgap');
M_.endo_names_long = char(M_.endo_names_long, 'outputgap');
M_.endo_names = char(M_.endo_names, 'output');
M_.endo_names_tex = char(M_.endo_names_tex, 'output');
M_.endo_names_long = char(M_.endo_names_long, 'output');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_73');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_73');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_73');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_77');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_77');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_77');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_81');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_81');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_81');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_108');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_108');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_108');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_112');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_112');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_112');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_116');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_116');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_116');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_143');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_143');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_143');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_147');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_147');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_147');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_151');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_151');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_151');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_1_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_1\_1');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_1_1');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_1_2');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_1\_2');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_1_2');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_35_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_35\_1');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_35_1');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_35_2');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_35\_2');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_35_2');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_35_3');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_35\_3');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_35_3');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_34_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_34\_1');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_34_1');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_34_2');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_34\_2');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_34_2');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_34_3');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_34\_3');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_34_3');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_31_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_31\_1');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_31_1');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_31_2');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_31\_2');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_31_2');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_31_3');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_31\_3');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_31_3');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_33_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_33\_1');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_33_1');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_33_2');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_33\_2');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_33_2');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_33_3');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_33\_3');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_33_3');
M_.endo_partitions = struct();
M_.param_names = 'cofintintb1';
M_.param_names_tex = 'cofintintb1';
M_.param_names_long = 'cofintintb1';
M_.param_names = char(M_.param_names, 'cofintintb2');
M_.param_names_tex = char(M_.param_names_tex, 'cofintintb2');
M_.param_names_long = char(M_.param_names_long, 'cofintintb2');
M_.param_names = char(M_.param_names, 'cofintintb3');
M_.param_names_tex = char(M_.param_names_tex, 'cofintintb3');
M_.param_names_long = char(M_.param_names_long, 'cofintintb3');
M_.param_names = char(M_.param_names, 'cofintintb4');
M_.param_names_tex = char(M_.param_names_tex, 'cofintintb4');
M_.param_names_long = char(M_.param_names_long, 'cofintintb4');
M_.param_names = char(M_.param_names, 'cofintinf0');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinf0');
M_.param_names_long = char(M_.param_names_long, 'cofintinf0');
M_.param_names = char(M_.param_names, 'cofintinfb1');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinfb1');
M_.param_names_long = char(M_.param_names_long, 'cofintinfb1');
M_.param_names = char(M_.param_names, 'cofintinfb2');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinfb2');
M_.param_names_long = char(M_.param_names_long, 'cofintinfb2');
M_.param_names = char(M_.param_names, 'cofintinfb3');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinfb3');
M_.param_names_long = char(M_.param_names_long, 'cofintinfb3');
M_.param_names = char(M_.param_names, 'cofintinfb4');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinfb4');
M_.param_names_long = char(M_.param_names_long, 'cofintinfb4');
M_.param_names = char(M_.param_names, 'cofintinff1');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinff1');
M_.param_names_long = char(M_.param_names_long, 'cofintinff1');
M_.param_names = char(M_.param_names, 'cofintinff2');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinff2');
M_.param_names_long = char(M_.param_names_long, 'cofintinff2');
M_.param_names = char(M_.param_names, 'cofintinff3');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinff3');
M_.param_names_long = char(M_.param_names_long, 'cofintinff3');
M_.param_names = char(M_.param_names, 'cofintinff4');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinff4');
M_.param_names_long = char(M_.param_names_long, 'cofintinff4');
M_.param_names = char(M_.param_names, 'cofintout');
M_.param_names_tex = char(M_.param_names_tex, 'cofintout');
M_.param_names_long = char(M_.param_names_long, 'cofintout');
M_.param_names = char(M_.param_names, 'cofintoutb1');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutb1');
M_.param_names_long = char(M_.param_names_long, 'cofintoutb1');
M_.param_names = char(M_.param_names, 'cofintoutb2');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutb2');
M_.param_names_long = char(M_.param_names_long, 'cofintoutb2');
M_.param_names = char(M_.param_names, 'cofintoutb3');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutb3');
M_.param_names_long = char(M_.param_names_long, 'cofintoutb3');
M_.param_names = char(M_.param_names, 'cofintoutb4');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutb4');
M_.param_names_long = char(M_.param_names_long, 'cofintoutb4');
M_.param_names = char(M_.param_names, 'cofintoutf1');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutf1');
M_.param_names_long = char(M_.param_names_long, 'cofintoutf1');
M_.param_names = char(M_.param_names, 'cofintoutf2');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutf2');
M_.param_names_long = char(M_.param_names_long, 'cofintoutf2');
M_.param_names = char(M_.param_names, 'cofintoutf3');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutf3');
M_.param_names_long = char(M_.param_names_long, 'cofintoutf3');
M_.param_names = char(M_.param_names, 'cofintoutf4');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutf4');
M_.param_names_long = char(M_.param_names_long, 'cofintoutf4');
M_.param_names = char(M_.param_names, 'cofintoutp');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutp');
M_.param_names_long = char(M_.param_names_long, 'cofintoutp');
M_.param_names = char(M_.param_names, 'cofintoutpb1');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpb1');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpb1');
M_.param_names = char(M_.param_names, 'cofintoutpb2');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpb2');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpb2');
M_.param_names = char(M_.param_names, 'cofintoutpb3');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpb3');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpb3');
M_.param_names = char(M_.param_names, 'cofintoutpb4');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpb4');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpb4');
M_.param_names = char(M_.param_names, 'cofintoutpf1');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpf1');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpf1');
M_.param_names = char(M_.param_names, 'cofintoutpf2');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpf2');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpf2');
M_.param_names = char(M_.param_names, 'cofintoutpf3');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpf3');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpf3');
M_.param_names = char(M_.param_names, 'cofintoutpf4');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpf4');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpf4');
M_.param_names = char(M_.param_names, 'std_r_');
M_.param_names_tex = char(M_.param_names_tex, 'std\_r\_');
M_.param_names_long = char(M_.param_names_long, 'std_r_');
M_.param_names = char(M_.param_names, 'std_r_quart');
M_.param_names_tex = char(M_.param_names_tex, 'std\_r\_quart');
M_.param_names_long = char(M_.param_names_long, 'std_r_quart');
M_.param_names = char(M_.param_names, 'coffispol');
M_.param_names_tex = char(M_.param_names_tex, 'coffispol');
M_.param_names_long = char(M_.param_names_long, 'coffispol');
M_.param_names = char(M_.param_names, 'rhor');
M_.param_names_tex = char(M_.param_names_tex, 'rhor');
M_.param_names_long = char(M_.param_names_long, 'rhor');
M_.param_names = char(M_.param_names, 'rhopi');
M_.param_names_tex = char(M_.param_names_tex, 'rhopi');
M_.param_names_long = char(M_.param_names_long, 'rhopi');
M_.param_names = char(M_.param_names, 'rhoy');
M_.param_names_tex = char(M_.param_names_tex, 'rhoy');
M_.param_names_long = char(M_.param_names_long, 'rhoy');
M_.param_names = char(M_.param_names, 'rhov');
M_.param_names_tex = char(M_.param_names_tex, 'rhov');
M_.param_names_long = char(M_.param_names_long, 'rhov');
M_.param_names = char(M_.param_names, 'rhotau');
M_.param_names_tex = char(M_.param_names_tex, 'rhotau');
M_.param_names_long = char(M_.param_names_long, 'rhotau');
M_.param_names = char(M_.param_names, 'rhopir');
M_.param_names_tex = char(M_.param_names_tex, 'rhopir');
M_.param_names_long = char(M_.param_names_long, 'rhopir');
M_.param_names = char(M_.param_names, 'rhopipi');
M_.param_names_tex = char(M_.param_names_tex, 'rhopipi');
M_.param_names_long = char(M_.param_names_long, 'rhopipi');
M_.param_names = char(M_.param_names, 'rhopiy');
M_.param_names_tex = char(M_.param_names_tex, 'rhopiy');
M_.param_names_long = char(M_.param_names_long, 'rhopiy');
M_.param_names = char(M_.param_names, 'rhopiv');
M_.param_names_tex = char(M_.param_names_tex, 'rhopiv');
M_.param_names_long = char(M_.param_names_long, 'rhopiv');
M_.param_names = char(M_.param_names, 'rhoyr');
M_.param_names_tex = char(M_.param_names_tex, 'rhoyr');
M_.param_names_long = char(M_.param_names_long, 'rhoyr');
M_.param_names = char(M_.param_names, 'rhoypi');
M_.param_names_tex = char(M_.param_names_tex, 'rhoypi');
M_.param_names_long = char(M_.param_names_long, 'rhoypi');
M_.param_names = char(M_.param_names, 'rhoyy');
M_.param_names_tex = char(M_.param_names_tex, 'rhoyy');
M_.param_names_long = char(M_.param_names_long, 'rhoyy');
M_.param_names = char(M_.param_names, 'rhoyv');
M_.param_names_tex = char(M_.param_names_tex, 'rhoyv');
M_.param_names_long = char(M_.param_names_long, 'rhoyv');
M_.param_names = char(M_.param_names, 'rhovv');
M_.param_names_tex = char(M_.param_names_tex, 'rhovv');
M_.param_names_long = char(M_.param_names_long, 'rhovv');
M_.param_names = char(M_.param_names, 'sigtau');
M_.param_names_tex = char(M_.param_names_tex, 'sigtau');
M_.param_names_long = char(M_.param_names_long, 'sigtau');
M_.param_names = char(M_.param_names, 'sigr');
M_.param_names_tex = char(M_.param_names_tex, 'sigr');
M_.param_names_long = char(M_.param_names_long, 'sigr');
M_.param_names = char(M_.param_names, 'sigpi');
M_.param_names_tex = char(M_.param_names_tex, 'sigpi');
M_.param_names_long = char(M_.param_names_long, 'sigpi');
M_.param_names = char(M_.param_names, 'sigy');
M_.param_names_tex = char(M_.param_names_tex, 'sigy');
M_.param_names_long = char(M_.param_names_long, 'sigy');
M_.param_names = char(M_.param_names, 'sigv');
M_.param_names_tex = char(M_.param_names_tex, 'sigv');
M_.param_names_long = char(M_.param_names_long, 'sigv');
M_.param_names = char(M_.param_names, 'sigpitau');
M_.param_names_tex = char(M_.param_names_tex, 'sigpitau');
M_.param_names_long = char(M_.param_names_long, 'sigpitau');
M_.param_names = char(M_.param_names, 'sigypi');
M_.param_names_tex = char(M_.param_names_tex, 'sigypi');
M_.param_names_long = char(M_.param_names_long, 'sigypi');
M_.param_names = char(M_.param_names, 'sigytau');
M_.param_names_tex = char(M_.param_names_tex, 'sigytau');
M_.param_names_long = char(M_.param_names_long, 'sigytau');
M_.param_names = char(M_.param_names, 'sigvr');
M_.param_names_tex = char(M_.param_names_tex, 'sigvr');
M_.param_names_long = char(M_.param_names_long, 'sigvr');
M_.param_names = char(M_.param_names, 'sigvpi');
M_.param_names_tex = char(M_.param_names_tex, 'sigvpi');
M_.param_names_long = char(M_.param_names_long, 'sigvpi');
M_.param_names = char(M_.param_names, 'sigvy');
M_.param_names_tex = char(M_.param_names_tex, 'sigvy');
M_.param_names_long = char(M_.param_names_long, 'sigvy');
M_.param_names = char(M_.param_names, 'sigvtau');
M_.param_names_tex = char(M_.param_names_tex, 'sigvtau');
M_.param_names_long = char(M_.param_names_long, 'sigvtau');
M_.param_names = char(M_.param_names, 'Lambdar');
M_.param_names_tex = char(M_.param_names_tex, 'Lambdar');
M_.param_names_long = char(M_.param_names_long, 'Lambdar');
M_.param_names = char(M_.param_names, 'Lambdapi');
M_.param_names_tex = char(M_.param_names_tex, 'Lambdapi');
M_.param_names_long = char(M_.param_names_long, 'Lambdapi');
M_.param_names = char(M_.param_names, 'Lambday');
M_.param_names_tex = char(M_.param_names_tex, 'Lambday');
M_.param_names_long = char(M_.param_names_long, 'Lambday');
M_.param_names = char(M_.param_names, 'Lambdatau');
M_.param_names_tex = char(M_.param_names_tex, 'Lambdatau');
M_.param_names_long = char(M_.param_names_long, 'Lambdatau');
M_.param_names = char(M_.param_names, 'Lambdav');
M_.param_names_tex = char(M_.param_names_tex, 'Lambdav');
M_.param_names_long = char(M_.param_names_long, 'Lambdav');
M_.param_names = char(M_.param_names, 'sig4');
M_.param_names_tex = char(M_.param_names_tex, 'sig4');
M_.param_names_long = char(M_.param_names_long, 'sig4');
M_.param_names = char(M_.param_names, 'sig8');
M_.param_names_tex = char(M_.param_names_tex, 'sig8');
M_.param_names_long = char(M_.param_names_long, 'sig8');
M_.param_names = char(M_.param_names, 'sig16');
M_.param_names_tex = char(M_.param_names_tex, 'sig16');
M_.param_names_long = char(M_.param_names_long, 'sig16');
M_.param_names = char(M_.param_names, 'tauSS');
M_.param_names_tex = char(M_.param_names_tex, 'tauSS');
M_.param_names_long = char(M_.param_names_long, 'tauSS');
M_.param_names = char(M_.param_names, 'piSS');
M_.param_names_tex = char(M_.param_names_tex, 'piSS');
M_.param_names_long = char(M_.param_names_long, 'piSS');
M_.param_names = char(M_.param_names, 'rSS');
M_.param_names_tex = char(M_.param_names_tex, 'rSS');
M_.param_names_long = char(M_.param_names_long, 'rSS');
M_.param_names = char(M_.param_names, 'gySS');
M_.param_names_tex = char(M_.param_names_tex, 'gySS');
M_.param_names_long = char(M_.param_names_long, 'gySS');
M_.param_names = char(M_.param_names, 'grSS');
M_.param_names_tex = char(M_.param_names_tex, 'grSS');
M_.param_names_long = char(M_.param_names_long, 'grSS');
M_.param_names = char(M_.param_names, 'y_4SS');
M_.param_names_tex = char(M_.param_names_tex, 'y\_4SS');
M_.param_names_long = char(M_.param_names_long, 'y_4SS');
M_.param_names = char(M_.param_names, 'y_8SS');
M_.param_names_tex = char(M_.param_names_tex, 'y\_8SS');
M_.param_names_long = char(M_.param_names_long, 'y_8SS');
M_.param_names = char(M_.param_names, 'y_12SS');
M_.param_names_tex = char(M_.param_names_tex, 'y\_12SS');
M_.param_names_long = char(M_.param_names_long, 'y_12SS');
M_.param_names = char(M_.param_names, 'y_16SS');
M_.param_names_tex = char(M_.param_names_tex, 'y\_16SS');
M_.param_names_long = char(M_.param_names_long, 'y_16SS');
M_.param_names = char(M_.param_names, 'y_20SS');
M_.param_names_tex = char(M_.param_names_tex, 'y\_20SS');
M_.param_names_long = char(M_.param_names_long, 'y_20SS');
M_.param_names = char(M_.param_names, 'U11');
M_.param_names_tex = char(M_.param_names_tex, 'U11');
M_.param_names_long = char(M_.param_names_long, 'U11');
M_.param_names = char(M_.param_names, 'U12');
M_.param_names_tex = char(M_.param_names_tex, 'U12');
M_.param_names_long = char(M_.param_names_long, 'U12');
M_.param_names = char(M_.param_names, 'U13');
M_.param_names_tex = char(M_.param_names_tex, 'U13');
M_.param_names_long = char(M_.param_names_long, 'U13');
M_.param_names = char(M_.param_names, 'U14');
M_.param_names_tex = char(M_.param_names_tex, 'U14');
M_.param_names_long = char(M_.param_names_long, 'U14');
M_.param_names = char(M_.param_names, 'U15');
M_.param_names_tex = char(M_.param_names_tex, 'U15');
M_.param_names_long = char(M_.param_names_long, 'U15');
M_.param_names = char(M_.param_names, 'U21');
M_.param_names_tex = char(M_.param_names_tex, 'U21');
M_.param_names_long = char(M_.param_names_long, 'U21');
M_.param_names = char(M_.param_names, 'U22');
M_.param_names_tex = char(M_.param_names_tex, 'U22');
M_.param_names_long = char(M_.param_names_long, 'U22');
M_.param_names = char(M_.param_names, 'U23');
M_.param_names_tex = char(M_.param_names_tex, 'U23');
M_.param_names_long = char(M_.param_names_long, 'U23');
M_.param_names = char(M_.param_names, 'U24');
M_.param_names_tex = char(M_.param_names_tex, 'U24');
M_.param_names_long = char(M_.param_names_long, 'U24');
M_.param_names = char(M_.param_names, 'U25');
M_.param_names_tex = char(M_.param_names_tex, 'U25');
M_.param_names_long = char(M_.param_names_long, 'U25');
M_.param_names = char(M_.param_names, 'U31');
M_.param_names_tex = char(M_.param_names_tex, 'U31');
M_.param_names_long = char(M_.param_names_long, 'U31');
M_.param_names = char(M_.param_names, 'U32');
M_.param_names_tex = char(M_.param_names_tex, 'U32');
M_.param_names_long = char(M_.param_names_long, 'U32');
M_.param_names = char(M_.param_names, 'U33');
M_.param_names_tex = char(M_.param_names_tex, 'U33');
M_.param_names_long = char(M_.param_names_long, 'U33');
M_.param_names = char(M_.param_names, 'U34');
M_.param_names_tex = char(M_.param_names_tex, 'U34');
M_.param_names_long = char(M_.param_names_long, 'U34');
M_.param_names = char(M_.param_names, 'U35');
M_.param_names_tex = char(M_.param_names_tex, 'U35');
M_.param_names_long = char(M_.param_names_long, 'U35');
M_.param_names = char(M_.param_names, 'U41');
M_.param_names_tex = char(M_.param_names_tex, 'U41');
M_.param_names_long = char(M_.param_names_long, 'U41');
M_.param_names = char(M_.param_names, 'U42');
M_.param_names_tex = char(M_.param_names_tex, 'U42');
M_.param_names_long = char(M_.param_names_long, 'U42');
M_.param_names = char(M_.param_names, 'U43');
M_.param_names_tex = char(M_.param_names_tex, 'U43');
M_.param_names_long = char(M_.param_names_long, 'U43');
M_.param_names = char(M_.param_names, 'U44');
M_.param_names_tex = char(M_.param_names_tex, 'U44');
M_.param_names_long = char(M_.param_names_long, 'U44');
M_.param_names = char(M_.param_names, 'U45');
M_.param_names_tex = char(M_.param_names_tex, 'U45');
M_.param_names_long = char(M_.param_names_long, 'U45');
M_.param_names = char(M_.param_names, 'U51');
M_.param_names_tex = char(M_.param_names_tex, 'U51');
M_.param_names_long = char(M_.param_names_long, 'U51');
M_.param_names = char(M_.param_names, 'U52');
M_.param_names_tex = char(M_.param_names_tex, 'U52');
M_.param_names_long = char(M_.param_names_long, 'U52');
M_.param_names = char(M_.param_names, 'U53');
M_.param_names_tex = char(M_.param_names_tex, 'U53');
M_.param_names_long = char(M_.param_names_long, 'U53');
M_.param_names = char(M_.param_names, 'U54');
M_.param_names_tex = char(M_.param_names_tex, 'U54');
M_.param_names_long = char(M_.param_names_long, 'U54');
M_.param_names = char(M_.param_names, 'U55');
M_.param_names_tex = char(M_.param_names_tex, 'U55');
M_.param_names_long = char(M_.param_names_long, 'U55');
M_.param_names = char(M_.param_names, 'U61');
M_.param_names_tex = char(M_.param_names_tex, 'U61');
M_.param_names_long = char(M_.param_names_long, 'U61');
M_.param_names = char(M_.param_names, 'U62');
M_.param_names_tex = char(M_.param_names_tex, 'U62');
M_.param_names_long = char(M_.param_names_long, 'U62');
M_.param_names = char(M_.param_names, 'U63');
M_.param_names_tex = char(M_.param_names_tex, 'U63');
M_.param_names_long = char(M_.param_names_long, 'U63');
M_.param_names = char(M_.param_names, 'U64');
M_.param_names_tex = char(M_.param_names_tex, 'U64');
M_.param_names_long = char(M_.param_names_long, 'U64');
M_.param_names = char(M_.param_names, 'U65');
M_.param_names_tex = char(M_.param_names_tex, 'U65');
M_.param_names_long = char(M_.param_names_long, 'U65');
M_.param_names = char(M_.param_names, 'U71');
M_.param_names_tex = char(M_.param_names_tex, 'U71');
M_.param_names_long = char(M_.param_names_long, 'U71');
M_.param_names = char(M_.param_names, 'U72');
M_.param_names_tex = char(M_.param_names_tex, 'U72');
M_.param_names_long = char(M_.param_names_long, 'U72');
M_.param_names = char(M_.param_names, 'U73');
M_.param_names_tex = char(M_.param_names_tex, 'U73');
M_.param_names_long = char(M_.param_names_long, 'U73');
M_.param_names = char(M_.param_names, 'U74');
M_.param_names_tex = char(M_.param_names_tex, 'U74');
M_.param_names_long = char(M_.param_names_long, 'U74');
M_.param_names = char(M_.param_names, 'U75');
M_.param_names_tex = char(M_.param_names_tex, 'U75');
M_.param_names_long = char(M_.param_names_long, 'U75');
M_.param_names = char(M_.param_names, 'U81');
M_.param_names_tex = char(M_.param_names_tex, 'U81');
M_.param_names_long = char(M_.param_names_long, 'U81');
M_.param_names = char(M_.param_names, 'U82');
M_.param_names_tex = char(M_.param_names_tex, 'U82');
M_.param_names_long = char(M_.param_names_long, 'U82');
M_.param_names = char(M_.param_names, 'U83');
M_.param_names_tex = char(M_.param_names_tex, 'U83');
M_.param_names_long = char(M_.param_names_long, 'U83');
M_.param_names = char(M_.param_names, 'U84');
M_.param_names_tex = char(M_.param_names_tex, 'U84');
M_.param_names_long = char(M_.param_names_long, 'U84');
M_.param_names = char(M_.param_names, 'U85');
M_.param_names_tex = char(M_.param_names_tex, 'U85');
M_.param_names_long = char(M_.param_names_long, 'U85');
M_.param_names = char(M_.param_names, 'P11');
M_.param_names_tex = char(M_.param_names_tex, 'P11');
M_.param_names_long = char(M_.param_names_long, 'P11');
M_.param_names = char(M_.param_names, 'P12');
M_.param_names_tex = char(M_.param_names_tex, 'P12');
M_.param_names_long = char(M_.param_names_long, 'P12');
M_.param_names = char(M_.param_names, 'P13');
M_.param_names_tex = char(M_.param_names_tex, 'P13');
M_.param_names_long = char(M_.param_names_long, 'P13');
M_.param_names = char(M_.param_names, 'P14');
M_.param_names_tex = char(M_.param_names_tex, 'P14');
M_.param_names_long = char(M_.param_names_long, 'P14');
M_.param_names = char(M_.param_names, 'P15');
M_.param_names_tex = char(M_.param_names_tex, 'P15');
M_.param_names_long = char(M_.param_names_long, 'P15');
M_.param_names = char(M_.param_names, 'P21');
M_.param_names_tex = char(M_.param_names_tex, 'P21');
M_.param_names_long = char(M_.param_names_long, 'P21');
M_.param_names = char(M_.param_names, 'P22');
M_.param_names_tex = char(M_.param_names_tex, 'P22');
M_.param_names_long = char(M_.param_names_long, 'P22');
M_.param_names = char(M_.param_names, 'P23');
M_.param_names_tex = char(M_.param_names_tex, 'P23');
M_.param_names_long = char(M_.param_names_long, 'P23');
M_.param_names = char(M_.param_names, 'P24');
M_.param_names_tex = char(M_.param_names_tex, 'P24');
M_.param_names_long = char(M_.param_names_long, 'P24');
M_.param_names = char(M_.param_names, 'P25');
M_.param_names_tex = char(M_.param_names_tex, 'P25');
M_.param_names_long = char(M_.param_names_long, 'P25');
M_.param_names = char(M_.param_names, 'P31');
M_.param_names_tex = char(M_.param_names_tex, 'P31');
M_.param_names_long = char(M_.param_names_long, 'P31');
M_.param_names = char(M_.param_names, 'P32');
M_.param_names_tex = char(M_.param_names_tex, 'P32');
M_.param_names_long = char(M_.param_names_long, 'P32');
M_.param_names = char(M_.param_names, 'P33');
M_.param_names_tex = char(M_.param_names_tex, 'P33');
M_.param_names_long = char(M_.param_names_long, 'P33');
M_.param_names = char(M_.param_names, 'P34');
M_.param_names_tex = char(M_.param_names_tex, 'P34');
M_.param_names_long = char(M_.param_names_long, 'P34');
M_.param_names = char(M_.param_names, 'P35');
M_.param_names_tex = char(M_.param_names_tex, 'P35');
M_.param_names_long = char(M_.param_names_long, 'P35');
M_.param_names = char(M_.param_names, 'P41');
M_.param_names_tex = char(M_.param_names_tex, 'P41');
M_.param_names_long = char(M_.param_names_long, 'P41');
M_.param_names = char(M_.param_names, 'P42');
M_.param_names_tex = char(M_.param_names_tex, 'P42');
M_.param_names_long = char(M_.param_names_long, 'P42');
M_.param_names = char(M_.param_names, 'P43');
M_.param_names_tex = char(M_.param_names_tex, 'P43');
M_.param_names_long = char(M_.param_names_long, 'P43');
M_.param_names = char(M_.param_names, 'P44');
M_.param_names_tex = char(M_.param_names_tex, 'P44');
M_.param_names_long = char(M_.param_names_long, 'P44');
M_.param_names = char(M_.param_names, 'P45');
M_.param_names_tex = char(M_.param_names_tex, 'P45');
M_.param_names_long = char(M_.param_names_long, 'P45');
M_.param_names = char(M_.param_names, 'P51');
M_.param_names_tex = char(M_.param_names_tex, 'P51');
M_.param_names_long = char(M_.param_names_long, 'P51');
M_.param_names = char(M_.param_names, 'P52');
M_.param_names_tex = char(M_.param_names_tex, 'P52');
M_.param_names_long = char(M_.param_names_long, 'P52');
M_.param_names = char(M_.param_names, 'P53');
M_.param_names_tex = char(M_.param_names_tex, 'P53');
M_.param_names_long = char(M_.param_names_long, 'P53');
M_.param_names = char(M_.param_names, 'P54');
M_.param_names_tex = char(M_.param_names_tex, 'P54');
M_.param_names_long = char(M_.param_names_long, 'P54');
M_.param_names = char(M_.param_names, 'P55');
M_.param_names_tex = char(M_.param_names_tex, 'P55');
M_.param_names_long = char(M_.param_names_long, 'P55');
M_.param_names = char(M_.param_names, 'Q11');
M_.param_names_tex = char(M_.param_names_tex, 'Q11');
M_.param_names_long = char(M_.param_names_long, 'Q11');
M_.param_names = char(M_.param_names, 'Q12');
M_.param_names_tex = char(M_.param_names_tex, 'Q12');
M_.param_names_long = char(M_.param_names_long, 'Q12');
M_.param_names = char(M_.param_names, 'Q13');
M_.param_names_tex = char(M_.param_names_tex, 'Q13');
M_.param_names_long = char(M_.param_names_long, 'Q13');
M_.param_names = char(M_.param_names, 'Q14');
M_.param_names_tex = char(M_.param_names_tex, 'Q14');
M_.param_names_long = char(M_.param_names_long, 'Q14');
M_.param_names = char(M_.param_names, 'Q15');
M_.param_names_tex = char(M_.param_names_tex, 'Q15');
M_.param_names_long = char(M_.param_names_long, 'Q15');
M_.param_names = char(M_.param_names, 'Q21');
M_.param_names_tex = char(M_.param_names_tex, 'Q21');
M_.param_names_long = char(M_.param_names_long, 'Q21');
M_.param_names = char(M_.param_names, 'Q22');
M_.param_names_tex = char(M_.param_names_tex, 'Q22');
M_.param_names_long = char(M_.param_names_long, 'Q22');
M_.param_names = char(M_.param_names, 'Q23');
M_.param_names_tex = char(M_.param_names_tex, 'Q23');
M_.param_names_long = char(M_.param_names_long, 'Q23');
M_.param_names = char(M_.param_names, 'Q24');
M_.param_names_tex = char(M_.param_names_tex, 'Q24');
M_.param_names_long = char(M_.param_names_long, 'Q24');
M_.param_names = char(M_.param_names, 'Q25');
M_.param_names_tex = char(M_.param_names_tex, 'Q25');
M_.param_names_long = char(M_.param_names_long, 'Q25');
M_.param_names = char(M_.param_names, 'Q31');
M_.param_names_tex = char(M_.param_names_tex, 'Q31');
M_.param_names_long = char(M_.param_names_long, 'Q31');
M_.param_names = char(M_.param_names, 'Q32');
M_.param_names_tex = char(M_.param_names_tex, 'Q32');
M_.param_names_long = char(M_.param_names_long, 'Q32');
M_.param_names = char(M_.param_names, 'Q33');
M_.param_names_tex = char(M_.param_names_tex, 'Q33');
M_.param_names_long = char(M_.param_names_long, 'Q33');
M_.param_names = char(M_.param_names, 'Q34');
M_.param_names_tex = char(M_.param_names_tex, 'Q34');
M_.param_names_long = char(M_.param_names_long, 'Q34');
M_.param_names = char(M_.param_names, 'Q35');
M_.param_names_tex = char(M_.param_names_tex, 'Q35');
M_.param_names_long = char(M_.param_names_long, 'Q35');
M_.param_names = char(M_.param_names, 'Q41');
M_.param_names_tex = char(M_.param_names_tex, 'Q41');
M_.param_names_long = char(M_.param_names_long, 'Q41');
M_.param_names = char(M_.param_names, 'Q42');
M_.param_names_tex = char(M_.param_names_tex, 'Q42');
M_.param_names_long = char(M_.param_names_long, 'Q42');
M_.param_names = char(M_.param_names, 'Q43');
M_.param_names_tex = char(M_.param_names_tex, 'Q43');
M_.param_names_long = char(M_.param_names_long, 'Q43');
M_.param_names = char(M_.param_names, 'Q44');
M_.param_names_tex = char(M_.param_names_tex, 'Q44');
M_.param_names_long = char(M_.param_names_long, 'Q44');
M_.param_names = char(M_.param_names, 'Q45');
M_.param_names_tex = char(M_.param_names_tex, 'Q45');
M_.param_names_long = char(M_.param_names_long, 'Q45');
M_.param_names = char(M_.param_names, 'Q51');
M_.param_names_tex = char(M_.param_names_tex, 'Q51');
M_.param_names_long = char(M_.param_names_long, 'Q51');
M_.param_names = char(M_.param_names, 'Q52');
M_.param_names_tex = char(M_.param_names_tex, 'Q52');
M_.param_names_long = char(M_.param_names_long, 'Q52');
M_.param_names = char(M_.param_names, 'Q53');
M_.param_names_tex = char(M_.param_names_tex, 'Q53');
M_.param_names_long = char(M_.param_names_long, 'Q53');
M_.param_names = char(M_.param_names, 'Q54');
M_.param_names_tex = char(M_.param_names_tex, 'Q54');
M_.param_names_long = char(M_.param_names_long, 'Q54');
M_.param_names = char(M_.param_names, 'Q55');
M_.param_names_tex = char(M_.param_names_tex, 'Q55');
M_.param_names_long = char(M_.param_names_long, 'Q55');
M_.param_names = char(M_.param_names, 'S11');
M_.param_names_tex = char(M_.param_names_tex, 'S11');
M_.param_names_long = char(M_.param_names_long, 'S11');
M_.param_names = char(M_.param_names, 'S12');
M_.param_names_tex = char(M_.param_names_tex, 'S12');
M_.param_names_long = char(M_.param_names_long, 'S12');
M_.param_names = char(M_.param_names, 'S13');
M_.param_names_tex = char(M_.param_names_tex, 'S13');
M_.param_names_long = char(M_.param_names_long, 'S13');
M_.param_names = char(M_.param_names, 'S14');
M_.param_names_tex = char(M_.param_names_tex, 'S14');
M_.param_names_long = char(M_.param_names_long, 'S14');
M_.param_names = char(M_.param_names, 'S15');
M_.param_names_tex = char(M_.param_names_tex, 'S15');
M_.param_names_long = char(M_.param_names_long, 'S15');
M_.param_names = char(M_.param_names, 'S21');
M_.param_names_tex = char(M_.param_names_tex, 'S21');
M_.param_names_long = char(M_.param_names_long, 'S21');
M_.param_names = char(M_.param_names, 'S22');
M_.param_names_tex = char(M_.param_names_tex, 'S22');
M_.param_names_long = char(M_.param_names_long, 'S22');
M_.param_names = char(M_.param_names, 'S23');
M_.param_names_tex = char(M_.param_names_tex, 'S23');
M_.param_names_long = char(M_.param_names_long, 'S23');
M_.param_names = char(M_.param_names, 'S24');
M_.param_names_tex = char(M_.param_names_tex, 'S24');
M_.param_names_long = char(M_.param_names_long, 'S24');
M_.param_names = char(M_.param_names, 'S25');
M_.param_names_tex = char(M_.param_names_tex, 'S25');
M_.param_names_long = char(M_.param_names_long, 'S25');
M_.param_names = char(M_.param_names, 'S31');
M_.param_names_tex = char(M_.param_names_tex, 'S31');
M_.param_names_long = char(M_.param_names_long, 'S31');
M_.param_names = char(M_.param_names, 'S32');
M_.param_names_tex = char(M_.param_names_tex, 'S32');
M_.param_names_long = char(M_.param_names_long, 'S32');
M_.param_names = char(M_.param_names, 'S33');
M_.param_names_tex = char(M_.param_names_tex, 'S33');
M_.param_names_long = char(M_.param_names_long, 'S33');
M_.param_names = char(M_.param_names, 'S34');
M_.param_names_tex = char(M_.param_names_tex, 'S34');
M_.param_names_long = char(M_.param_names_long, 'S34');
M_.param_names = char(M_.param_names, 'S35');
M_.param_names_tex = char(M_.param_names_tex, 'S35');
M_.param_names_long = char(M_.param_names_long, 'S35');
M_.param_names = char(M_.param_names, 'S41');
M_.param_names_tex = char(M_.param_names_tex, 'S41');
M_.param_names_long = char(M_.param_names_long, 'S41');
M_.param_names = char(M_.param_names, 'S42');
M_.param_names_tex = char(M_.param_names_tex, 'S42');
M_.param_names_long = char(M_.param_names_long, 'S42');
M_.param_names = char(M_.param_names, 'S43');
M_.param_names_tex = char(M_.param_names_tex, 'S43');
M_.param_names_long = char(M_.param_names_long, 'S43');
M_.param_names = char(M_.param_names, 'S44');
M_.param_names_tex = char(M_.param_names_tex, 'S44');
M_.param_names_long = char(M_.param_names_long, 'S44');
M_.param_names = char(M_.param_names, 'S45');
M_.param_names_tex = char(M_.param_names_tex, 'S45');
M_.param_names_long = char(M_.param_names_long, 'S45');
M_.param_names = char(M_.param_names, 'S51');
M_.param_names_tex = char(M_.param_names_tex, 'S51');
M_.param_names_long = char(M_.param_names_long, 'S51');
M_.param_names = char(M_.param_names, 'S52');
M_.param_names_tex = char(M_.param_names_tex, 'S52');
M_.param_names_long = char(M_.param_names_long, 'S52');
M_.param_names = char(M_.param_names, 'S53');
M_.param_names_tex = char(M_.param_names_tex, 'S53');
M_.param_names_long = char(M_.param_names_long, 'S53');
M_.param_names = char(M_.param_names, 'S54');
M_.param_names_tex = char(M_.param_names_tex, 'S54');
M_.param_names_long = char(M_.param_names_long, 'S54');
M_.param_names = char(M_.param_names, 'S55');
M_.param_names_tex = char(M_.param_names_tex, 'S55');
M_.param_names_long = char(M_.param_names_long, 'S55');
M_.param_partitions = struct();
M_.exo_det_nbr = 0;
M_.exo_nbr = 8;
M_.endo_nbr = 59;
M_.param_nbr = 193;
M_.orig_endo_nbr = 36;
M_.aux_vars(1).endo_index = 37;
M_.aux_vars(1).type = 0;
M_.aux_vars(2).endo_index = 38;
M_.aux_vars(2).type = 0;
M_.aux_vars(3).endo_index = 39;
M_.aux_vars(3).type = 0;
M_.aux_vars(4).endo_index = 40;
M_.aux_vars(4).type = 0;
M_.aux_vars(5).endo_index = 41;
M_.aux_vars(5).type = 0;
M_.aux_vars(6).endo_index = 42;
M_.aux_vars(6).type = 0;
M_.aux_vars(7).endo_index = 43;
M_.aux_vars(7).type = 0;
M_.aux_vars(8).endo_index = 44;
M_.aux_vars(8).type = 0;
M_.aux_vars(9).endo_index = 45;
M_.aux_vars(9).type = 0;
M_.aux_vars(10).endo_index = 46;
M_.aux_vars(10).type = 1;
M_.aux_vars(10).orig_index = 2;
M_.aux_vars(10).orig_lead_lag = -1;
M_.aux_vars(11).endo_index = 47;
M_.aux_vars(11).type = 1;
M_.aux_vars(11).orig_index = 2;
M_.aux_vars(11).orig_lead_lag = -2;
M_.aux_vars(12).endo_index = 48;
M_.aux_vars(12).type = 1;
M_.aux_vars(12).orig_index = 36;
M_.aux_vars(12).orig_lead_lag = -1;
M_.aux_vars(13).endo_index = 49;
M_.aux_vars(13).type = 1;
M_.aux_vars(13).orig_index = 36;
M_.aux_vars(13).orig_lead_lag = -2;
M_.aux_vars(14).endo_index = 50;
M_.aux_vars(14).type = 1;
M_.aux_vars(14).orig_index = 36;
M_.aux_vars(14).orig_lead_lag = -3;
M_.aux_vars(15).endo_index = 51;
M_.aux_vars(15).type = 1;
M_.aux_vars(15).orig_index = 35;
M_.aux_vars(15).orig_lead_lag = -1;
M_.aux_vars(16).endo_index = 52;
M_.aux_vars(16).type = 1;
M_.aux_vars(16).orig_index = 35;
M_.aux_vars(16).orig_lead_lag = -2;
M_.aux_vars(17).endo_index = 53;
M_.aux_vars(17).type = 1;
M_.aux_vars(17).orig_index = 35;
M_.aux_vars(17).orig_lead_lag = -3;
M_.aux_vars(18).endo_index = 54;
M_.aux_vars(18).type = 1;
M_.aux_vars(18).orig_index = 32;
M_.aux_vars(18).orig_lead_lag = -1;
M_.aux_vars(19).endo_index = 55;
M_.aux_vars(19).type = 1;
M_.aux_vars(19).orig_index = 32;
M_.aux_vars(19).orig_lead_lag = -2;
M_.aux_vars(20).endo_index = 56;
M_.aux_vars(20).type = 1;
M_.aux_vars(20).orig_index = 32;
M_.aux_vars(20).orig_lead_lag = -3;
M_.aux_vars(21).endo_index = 57;
M_.aux_vars(21).type = 1;
M_.aux_vars(21).orig_index = 34;
M_.aux_vars(21).orig_lead_lag = -1;
M_.aux_vars(22).endo_index = 58;
M_.aux_vars(22).type = 1;
M_.aux_vars(22).orig_index = 34;
M_.aux_vars(22).orig_lead_lag = -2;
M_.aux_vars(23).endo_index = 59;
M_.aux_vars(23).type = 1;
M_.aux_vars(23).orig_index = 34;
M_.aux_vars(23).orig_lead_lag = -3;
M_.Sigma_e = zeros(8, 8);
M_.Correlation_matrix = eye(8, 8);
M_.H = 0;
M_.Correlation_matrix_ME = 1;
M_.sigma_e_is_diagonal = 1;
M_.det_shocks = [];
options_.linear = 1;
options_.block=0;
options_.bytecode=0;
options_.use_dll=0;
M_.hessian_eq_zero = 1;
erase_compiled_function('US_IR15_static');
erase_compiled_function('US_IR15_dynamic');
M_.orig_eq_nbr = 36;
M_.eq_nbr = 59;
M_.ramsey_eq_nbr = 0;
M_.set_auxiliary_variables = exist(['./' M_.fname '_set_auxiliary_variables.m'], 'file') == 2;
M_.lead_lag_incidence = [
 1 24 0;
 2 25 0;
 3 26 0;
 4 27 0;
 5 28 0;
 0 29 0;
 0 30 0;
 0 31 0;
 0 32 0;
 0 33 0;
 0 34 0;
 0 35 0;
 0 36 0;
 0 37 0;
 0 38 0;
 0 39 0;
 0 40 0;
 0 41 0;
 0 42 0;
 0 43 0;
 0 44 0;
 0 45 0;
 0 46 0;
 0 47 0;
 0 48 0;
 0 49 0;
 0 50 0;
 0 51 0;
 0 52 0;
 0 53 0;
 0 54 0;
 6 55 0;
 0 56 0;
 7 57 83;
 8 58 84;
 9 59 85;
 0 60 86;
 0 61 87;
 0 62 88;
 0 63 89;
 0 64 90;
 0 65 91;
 0 66 92;
 0 67 93;
 0 68 94;
 10 69 0;
 11 70 0;
 12 71 0;
 13 72 0;
 14 73 0;
 15 74 0;
 16 75 0;
 17 76 0;
 18 77 0;
 19 78 0;
 20 79 0;
 21 80 0;
 22 81 0;
 23 82 0;]';
M_.nstatic = 27;
M_.nfwrd   = 9;
M_.npred   = 20;
M_.nboth   = 3;
M_.nsfwrd   = 12;
M_.nspred   = 23;
M_.ndynamic   = 32;
M_.equations_tags = {
};
M_.static_and_dynamic_models_differ = 0;
M_.exo_names_orig_ord = [1:8];
M_.maximum_lag = 1;
M_.maximum_lead = 1;
M_.maximum_endo_lag = 1;
M_.maximum_endo_lead = 1;
oo_.steady_state = zeros(59, 1);
M_.maximum_exo_lag = 0;
M_.maximum_exo_lead = 0;
oo_.exo_steady_state = zeros(8, 1);
M_.params = NaN(193, 1);
M_.NNZDerivatives = [248; 0; -1];
warning off;
M_.params( 70 ) = .89;
piSS = M_.params( 70 );
M_.params( 71 ) = 5.47;
rSS = M_.params( 71 );
M_.params( 69 ) = M_.params(70);
tauSS = M_.params( 69 );
M_.params( 73 ) = M_.params(71)-M_.params(70);
grSS = M_.params( 73 );
M_.params( 72 ) = (-.526);
gySS = M_.params( 72 );
M_.params( 74 ) = 5.96;
y_4SS = M_.params( 74 );
M_.params( 75 ) = 6.166;
y_8SS = M_.params( 75 );
M_.params( 76 ) = 6.337;
y_12SS = M_.params( 76 );
M_.params( 77 ) = 6.4683;
y_16SS = M_.params( 77 );
M_.params( 78 ) = 6.5447;
y_20SS = M_.params( 78 );
M_.params( 35 ) = 0.6211;
rhor = M_.params( 35 );
M_.params( 36 ) = 0.1922;
rhopi = M_.params( 36 );
M_.params( 37 ) = 0.1563;
rhoy = M_.params( 37 );
M_.params( 38 ) = 0.0874;
rhov = M_.params( 38 );
M_.params( 39 ) = 0.999;
rhotau = M_.params( 39 );
M_.params( 40 ) = 0.1325;
rhopir = M_.params( 40 );
M_.params( 41 ) = 0.8537;
rhopipi = M_.params( 41 );
M_.params( 42 ) = (-0.001);
rhopiy = M_.params( 42 );
M_.params( 43 ) = (-0.0213);
rhopiv = M_.params( 43 );
M_.params( 44 ) = (-0.9646);
rhoyr = M_.params( 44 );
M_.params( 45 ) = 0.0459;
rhoypi = M_.params( 45 );
M_.params( 46 ) = 1.0128;
rhoyy = M_.params( 46 );
M_.params( 47 ) = 0.0250;
rhoyv = M_.params( 47 );
M_.params( 48 ) = 0.9001;
rhovv = M_.params( 48 );
M_.params( 49 ) = 0.0012;
sigtau = M_.params( 49 );
M_.params( 50 ) = 0.0013;
sigr = M_.params( 50 );
M_.params( 51 ) = 0.0026;
sigpi = M_.params( 51 );
M_.params( 52 ) = 0.0077;
sigy = M_.params( 52 );
M_.params( 53 ) = 0.01;
sigv = M_.params( 53 );
M_.params( 54 ) = (-0.4437);
sigpitau = M_.params( 54 );
M_.params( 55 ) = (-0.2267);
sigypi = M_.params( 55 );
M_.params( 56 ) = 0.9585;
sigytau = M_.params( 56 );
M_.params( 57 ) = 4.6064;
sigvr = M_.params( 57 );
M_.params( 58 ) = (-0.9421);
sigvpi = M_.params( 58 );
M_.params( 59 ) = (-0.8876);
sigvy = M_.params( 59 );
M_.params( 60 ) = (-0.0945);
sigvtau = M_.params( 60 );
M_.params( 61 ) = (-7.2018);
Lambdar = M_.params( 61 );
M_.params( 62 ) = (-16.7834);
Lambdapi = M_.params( 62 );
M_.params( 63 ) = (-26.3763);
Lambday = M_.params( 63 );
M_.params( 64 ) = (-0.0103);
Lambdatau = M_.params( 64 );
M_.params( 65 ) = 0;
Lambdav = M_.params( 65 );
M_.params( 66 ) = 0.0004;
sig4 = M_.params( 66 );
M_.params( 67 ) = 0.0002;
sig8 = M_.params( 67 );
M_.params( 68 ) = 0.0001;
sig16 = M_.params( 68 );
thispath = cd;                                                           
cd('..');                                                                
load policy_param.mat;                                                   
for i=1:33                                                               
deep_parameter_name = M_.param_names(i,:);                           
eval(['M_.params(i)  = ' deep_parameter_name ' ;'])                  
end                                                                      
cd(thispath);       
M_.params( 34 ) = 1;
coffispol = M_.params( 34 );
%
% SHOCKS instructions
%
M_.exo_det_length = 0;
M_.Sigma_e(1, 1) = 10000;
M_.Sigma_e(2, 2) = 10000;
M_.Sigma_e(3, 3) = 10000;
M_.Sigma_e(4, 4) = 10000;
M_.Sigma_e(5, 5) = 10000;
M_.Sigma_e(6, 6) = 10000;
M_.Sigma_e(7, 7) = 10000;
save('US_IR15_results.mat', 'oo_', 'M_', 'options_');
if exist('estim_params_', 'var') == 1
  save('US_IR15_results.mat', 'estim_params_', '-append');
end
if exist('bayestopt_', 'var') == 1
  save('US_IR15_results.mat', 'bayestopt_', '-append');
end
if exist('dataset_', 'var') == 1
  save('US_IR15_results.mat', 'dataset_', '-append');
end
if exist('estimation_info', 'var') == 1
  save('US_IR15_results.mat', 'estimation_info', '-append');
end
if exist('dataset_info', 'var') == 1
  save('US_IR15_results.mat', 'dataset_info', '-append');
end
if exist('oo_recursive_', 'var') == 1
  save('US_IR15_results.mat', 'oo_recursive_', '-append');
end


disp(['Total computing time : ' dynsec2hms(toc(tic0)) ]);
if ~isempty(lastwarn)
  disp('Note: warning(s) encountered in MATLAB/Octave code')
end
diary off
