%
% Status : main Dynare file
%
% Warning : this file is generated automatically by Dynare
%           from model file (.mod)

if isoctave || matlab_ver_less_than('8.6')
    clear all
else
    clearvars -global
    clear_persistent_variables(fileparts(which('dynare')), false)
end
tic0 = tic;
% Save empty dates and dseries objects in memory.
dates('initialize');
dseries('initialize');
% Define global variables.
global M_ options_ oo_ estim_params_ bayestopt_ dataset_ dataset_info estimation_info ys0_ ex0_
options_ = [];
M_.fname = 'US_CCTW10';
M_.dynare_version = '4.5.6';
oo_.dynare_version = '4.5.6';
options_.dynare_version = '4.5.6';
%
% Some global variables initialization
%
global_initialization;
diary off;
diary('US_CCTW10.log');
M_.exo_names = 'ea';
M_.exo_names_tex = 'ea';
M_.exo_names_long = 'ea';
M_.exo_names = char(M_.exo_names, 'eb');
M_.exo_names_tex = char(M_.exo_names_tex, 'eb');
M_.exo_names_long = char(M_.exo_names_long, 'eb');
M_.exo_names = char(M_.exo_names, 'eqs');
M_.exo_names_tex = char(M_.exo_names_tex, 'eqs');
M_.exo_names_long = char(M_.exo_names_long, 'eqs');
M_.exo_names = char(M_.exo_names, 'em');
M_.exo_names_tex = char(M_.exo_names_tex, 'em');
M_.exo_names_long = char(M_.exo_names_long, 'em');
M_.exo_names = char(M_.exo_names, 'epinf');
M_.exo_names_tex = char(M_.exo_names_tex, 'epinf');
M_.exo_names_long = char(M_.exo_names_long, 'epinf');
M_.exo_names = char(M_.exo_names, 'ew');
M_.exo_names_tex = char(M_.exo_names_tex, 'ew');
M_.exo_names_long = char(M_.exo_names_long, 'ew');
M_.exo_names = char(M_.exo_names, 'fiscal_');
M_.exo_names_tex = char(M_.exo_names_tex, 'fiscal\_');
M_.exo_names_long = char(M_.exo_names_long, 'fiscal_');
M_.exo_names = char(M_.exo_names, 'interest_');
M_.exo_names_tex = char(M_.exo_names_tex, 'interest\_');
M_.exo_names_long = char(M_.exo_names_long, 'interest_');
M_.endo_names = 'labobs';
M_.endo_names_tex = 'labobs';
M_.endo_names_long = 'labobs';
M_.endo_names = char(M_.endo_names, 'robs');
M_.endo_names_tex = char(M_.endo_names_tex, 'robs');
M_.endo_names_long = char(M_.endo_names_long, 'robs');
M_.endo_names = char(M_.endo_names, 'pinfobs');
M_.endo_names_tex = char(M_.endo_names_tex, 'pinfobs');
M_.endo_names_long = char(M_.endo_names_long, 'pinfobs');
M_.endo_names = char(M_.endo_names, 'dy');
M_.endo_names_tex = char(M_.endo_names_tex, 'dy');
M_.endo_names_long = char(M_.endo_names_long, 'dy');
M_.endo_names = char(M_.endo_names, 'dc');
M_.endo_names_tex = char(M_.endo_names_tex, 'dc');
M_.endo_names_long = char(M_.endo_names_long, 'dc');
M_.endo_names = char(M_.endo_names, 'dinve');
M_.endo_names_tex = char(M_.endo_names_tex, 'dinve');
M_.endo_names_long = char(M_.endo_names_long, 'dinve');
M_.endo_names = char(M_.endo_names, 'dw');
M_.endo_names_tex = char(M_.endo_names_tex, 'dw');
M_.endo_names_long = char(M_.endo_names_long, 'dw');
M_.endo_names = char(M_.endo_names, 'ewma');
M_.endo_names_tex = char(M_.endo_names_tex, 'ewma');
M_.endo_names_long = char(M_.endo_names_long, 'ewma');
M_.endo_names = char(M_.endo_names, 'epinfma');
M_.endo_names_tex = char(M_.endo_names_tex, 'epinfma');
M_.endo_names_long = char(M_.endo_names_long, 'epinfma');
M_.endo_names = char(M_.endo_names, 'zcapf');
M_.endo_names_tex = char(M_.endo_names_tex, 'zcapf');
M_.endo_names_long = char(M_.endo_names_long, 'zcapf');
M_.endo_names = char(M_.endo_names, 'rkf');
M_.endo_names_tex = char(M_.endo_names_tex, 'rkf');
M_.endo_names_long = char(M_.endo_names_long, 'rkf');
M_.endo_names = char(M_.endo_names, 'kf');
M_.endo_names_tex = char(M_.endo_names_tex, 'kf');
M_.endo_names_long = char(M_.endo_names_long, 'kf');
M_.endo_names = char(M_.endo_names, 'pkf');
M_.endo_names_tex = char(M_.endo_names_tex, 'pkf');
M_.endo_names_long = char(M_.endo_names_long, 'pkf');
M_.endo_names = char(M_.endo_names, 'cf');
M_.endo_names_tex = char(M_.endo_names_tex, 'cf');
M_.endo_names_long = char(M_.endo_names_long, 'cf');
M_.endo_names = char(M_.endo_names, 'invef');
M_.endo_names_tex = char(M_.endo_names_tex, 'invef');
M_.endo_names_long = char(M_.endo_names_long, 'invef');
M_.endo_names = char(M_.endo_names, 'yf');
M_.endo_names_tex = char(M_.endo_names_tex, 'yf');
M_.endo_names_long = char(M_.endo_names_long, 'yf');
M_.endo_names = char(M_.endo_names, 'labf');
M_.endo_names_tex = char(M_.endo_names_tex, 'labf');
M_.endo_names_long = char(M_.endo_names_long, 'labf');
M_.endo_names = char(M_.endo_names, 'wf');
M_.endo_names_tex = char(M_.endo_names_tex, 'wf');
M_.endo_names_long = char(M_.endo_names_long, 'wf');
M_.endo_names = char(M_.endo_names, 'rrf');
M_.endo_names_tex = char(M_.endo_names_tex, 'rrf');
M_.endo_names_long = char(M_.endo_names_long, 'rrf');
M_.endo_names = char(M_.endo_names, 'mc');
M_.endo_names_tex = char(M_.endo_names_tex, 'mc');
M_.endo_names_long = char(M_.endo_names_long, 'mc');
M_.endo_names = char(M_.endo_names, 'zcap');
M_.endo_names_tex = char(M_.endo_names_tex, 'zcap');
M_.endo_names_long = char(M_.endo_names_long, 'zcap');
M_.endo_names = char(M_.endo_names, 'rk');
M_.endo_names_tex = char(M_.endo_names_tex, 'rk');
M_.endo_names_long = char(M_.endo_names_long, 'rk');
M_.endo_names = char(M_.endo_names, 'k');
M_.endo_names_tex = char(M_.endo_names_tex, 'k');
M_.endo_names_long = char(M_.endo_names_long, 'k');
M_.endo_names = char(M_.endo_names, 'pk');
M_.endo_names_tex = char(M_.endo_names_tex, 'pk');
M_.endo_names_long = char(M_.endo_names_long, 'pk');
M_.endo_names = char(M_.endo_names, 'c');
M_.endo_names_tex = char(M_.endo_names_tex, 'c');
M_.endo_names_long = char(M_.endo_names_long, 'c');
M_.endo_names = char(M_.endo_names, 'inve');
M_.endo_names_tex = char(M_.endo_names_tex, 'inve');
M_.endo_names_long = char(M_.endo_names_long, 'inve');
M_.endo_names = char(M_.endo_names, 'y');
M_.endo_names_tex = char(M_.endo_names_tex, 'y');
M_.endo_names_long = char(M_.endo_names_long, 'y');
M_.endo_names = char(M_.endo_names, 'lab');
M_.endo_names_tex = char(M_.endo_names_tex, 'lab');
M_.endo_names_long = char(M_.endo_names_long, 'lab');
M_.endo_names = char(M_.endo_names, 'pinf');
M_.endo_names_tex = char(M_.endo_names_tex, 'pinf');
M_.endo_names_long = char(M_.endo_names_long, 'pinf');
M_.endo_names = char(M_.endo_names, 'w');
M_.endo_names_tex = char(M_.endo_names_tex, 'w');
M_.endo_names_long = char(M_.endo_names_long, 'w');
M_.endo_names = char(M_.endo_names, 'r');
M_.endo_names_tex = char(M_.endo_names_tex, 'r');
M_.endo_names_long = char(M_.endo_names_long, 'r');
M_.endo_names = char(M_.endo_names, 'a');
M_.endo_names_tex = char(M_.endo_names_tex, 'a');
M_.endo_names_long = char(M_.endo_names_long, 'a');
M_.endo_names = char(M_.endo_names, 'b');
M_.endo_names_tex = char(M_.endo_names_tex, 'b');
M_.endo_names_long = char(M_.endo_names_long, 'b');
M_.endo_names = char(M_.endo_names, 'g');
M_.endo_names_tex = char(M_.endo_names_tex, 'g');
M_.endo_names_long = char(M_.endo_names_long, 'g');
M_.endo_names = char(M_.endo_names, 'qs');
M_.endo_names_tex = char(M_.endo_names_tex, 'qs');
M_.endo_names_long = char(M_.endo_names_long, 'qs');
M_.endo_names = char(M_.endo_names, 'ms');
M_.endo_names_tex = char(M_.endo_names_tex, 'ms');
M_.endo_names_long = char(M_.endo_names_long, 'ms');
M_.endo_names = char(M_.endo_names, 'spinf');
M_.endo_names_tex = char(M_.endo_names_tex, 'spinf');
M_.endo_names_long = char(M_.endo_names_long, 'spinf');
M_.endo_names = char(M_.endo_names, 'sw');
M_.endo_names_tex = char(M_.endo_names_tex, 'sw');
M_.endo_names_long = char(M_.endo_names_long, 'sw');
M_.endo_names = char(M_.endo_names, 'kpf');
M_.endo_names_tex = char(M_.endo_names_tex, 'kpf');
M_.endo_names_long = char(M_.endo_names_long, 'kpf');
M_.endo_names = char(M_.endo_names, 'kp');
M_.endo_names_tex = char(M_.endo_names_tex, 'kp');
M_.endo_names_long = char(M_.endo_names_long, 'kp');
M_.endo_names = char(M_.endo_names, 'pinf4');
M_.endo_names_tex = char(M_.endo_names_tex, 'pinf4');
M_.endo_names_long = char(M_.endo_names_long, 'pinf4');
M_.endo_names = char(M_.endo_names, 'c_lc');
M_.endo_names_tex = char(M_.endo_names_tex, 'c\_lc');
M_.endo_names_long = char(M_.endo_names_long, 'c_lc');
M_.endo_names = char(M_.endo_names, 'c_nlc');
M_.endo_names_tex = char(M_.endo_names_tex, 'c\_nlc');
M_.endo_names_long = char(M_.endo_names_long, 'c_nlc');
M_.endo_names = char(M_.endo_names, 'debt');
M_.endo_names_tex = char(M_.endo_names_tex, 'debt');
M_.endo_names_long = char(M_.endo_names_long, 'debt');
M_.endo_names = char(M_.endo_names, 't');
M_.endo_names_tex = char(M_.endo_names_tex, 't');
M_.endo_names_long = char(M_.endo_names_long, 't');
M_.endo_names = char(M_.endo_names, 'c_lcf');
M_.endo_names_tex = char(M_.endo_names_tex, 'c\_lcf');
M_.endo_names_long = char(M_.endo_names_long, 'c_lcf');
M_.endo_names = char(M_.endo_names, 'c_nlcf');
M_.endo_names_tex = char(M_.endo_names_tex, 'c\_nlcf');
M_.endo_names_long = char(M_.endo_names_long, 'c_nlcf');
M_.endo_names = char(M_.endo_names, 'debtf');
M_.endo_names_tex = char(M_.endo_names_tex, 'debtf');
M_.endo_names_long = char(M_.endo_names_long, 'debtf');
M_.endo_names = char(M_.endo_names, 'tf');
M_.endo_names_tex = char(M_.endo_names_tex, 'tf');
M_.endo_names_long = char(M_.endo_names_long, 'tf');
M_.endo_names = char(M_.endo_names, 'eg');
M_.endo_names_tex = char(M_.endo_names_tex, 'eg');
M_.endo_names_long = char(M_.endo_names_long, 'eg');
M_.endo_names = char(M_.endo_names, 'pinflag1');
M_.endo_names_tex = char(M_.endo_names_tex, 'pinflag1');
M_.endo_names_long = char(M_.endo_names_long, 'pinflag1');
M_.endo_names = char(M_.endo_names, 'pinflag2');
M_.endo_names_tex = char(M_.endo_names_tex, 'pinflag2');
M_.endo_names_long = char(M_.endo_names_long, 'pinflag2');
M_.endo_names = char(M_.endo_names, 'dlab');
M_.endo_names_tex = char(M_.endo_names_tex, 'dlab');
M_.endo_names_long = char(M_.endo_names_long, 'dlab');
M_.endo_names = char(M_.endo_names, 'realinterest');
M_.endo_names_tex = char(M_.endo_names_tex, 'realinterest');
M_.endo_names_long = char(M_.endo_names_long, 'realinterest');
M_.endo_names = char(M_.endo_names, 'mcf');
M_.endo_names_tex = char(M_.endo_names_tex, 'mcf');
M_.endo_names_long = char(M_.endo_names_long, 'mcf');
M_.endo_names = char(M_.endo_names, 'pinfobs4');
M_.endo_names_tex = char(M_.endo_names_tex, 'pinfobs4');
M_.endo_names_long = char(M_.endo_names_long, 'pinfobs4');
M_.endo_names = char(M_.endo_names, 'gry');
M_.endo_names_tex = char(M_.endo_names_tex, 'gry');
M_.endo_names_long = char(M_.endo_names_long, 'gry');
M_.endo_names = char(M_.endo_names, 'robs4');
M_.endo_names_tex = char(M_.endo_names_tex, 'robs4');
M_.endo_names_long = char(M_.endo_names_long, 'robs4');
M_.endo_names = char(M_.endo_names, 'interest');
M_.endo_names_tex = char(M_.endo_names_tex, 'interest');
M_.endo_names_long = char(M_.endo_names_long, 'interest');
M_.endo_names = char(M_.endo_names, 'inflation');
M_.endo_names_tex = char(M_.endo_names_tex, 'inflation');
M_.endo_names_long = char(M_.endo_names_long, 'inflation');
M_.endo_names = char(M_.endo_names, 'inflationq');
M_.endo_names_tex = char(M_.endo_names_tex, 'inflationq');
M_.endo_names_long = char(M_.endo_names_long, 'inflationq');
M_.endo_names = char(M_.endo_names, 'outputgap');
M_.endo_names_tex = char(M_.endo_names_tex, 'outputgap');
M_.endo_names_long = char(M_.endo_names_long, 'outputgap');
M_.endo_names = char(M_.endo_names, 'output');
M_.endo_names_tex = char(M_.endo_names_tex, 'output');
M_.endo_names_long = char(M_.endo_names_long, 'output');
M_.endo_names = char(M_.endo_names, 'fispol');
M_.endo_names_tex = char(M_.endo_names_tex, 'fispol');
M_.endo_names_long = char(M_.endo_names_long, 'fispol');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_73');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_73');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_73');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_77');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_77');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_77');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_81');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_81');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_81');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_108');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_108');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_108');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_112');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_112');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_112');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_116');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_116');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_116');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_143');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_143');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_143');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_147');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_147');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_147');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_151');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_151');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_151');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_62_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_62\_1');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_62_1');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_62_2');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_62\_2');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_62_2');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_62_3');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_62\_3');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_62_3');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_61_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_61\_1');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_61_1');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_61_2');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_61\_2');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_61_2');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_61_3');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_61\_3');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_61_3');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_58_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_58\_1');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_58_1');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_58_2');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_58\_2');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_58_2');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_58_3');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_58\_3');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_58_3');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_60_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_60\_1');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_60_1');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_60_2');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_60\_2');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_60_2');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_60_3');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_60\_3');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_60_3');
M_.endo_partitions = struct();
M_.param_names = 'cofintintb1';
M_.param_names_tex = 'cofintintb1';
M_.param_names_long = 'cofintintb1';
M_.param_names = char(M_.param_names, 'cofintintb2');
M_.param_names_tex = char(M_.param_names_tex, 'cofintintb2');
M_.param_names_long = char(M_.param_names_long, 'cofintintb2');
M_.param_names = char(M_.param_names, 'cofintintb3');
M_.param_names_tex = char(M_.param_names_tex, 'cofintintb3');
M_.param_names_long = char(M_.param_names_long, 'cofintintb3');
M_.param_names = char(M_.param_names, 'cofintintb4');
M_.param_names_tex = char(M_.param_names_tex, 'cofintintb4');
M_.param_names_long = char(M_.param_names_long, 'cofintintb4');
M_.param_names = char(M_.param_names, 'cofintinf0');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinf0');
M_.param_names_long = char(M_.param_names_long, 'cofintinf0');
M_.param_names = char(M_.param_names, 'cofintinfb1');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinfb1');
M_.param_names_long = char(M_.param_names_long, 'cofintinfb1');
M_.param_names = char(M_.param_names, 'cofintinfb2');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinfb2');
M_.param_names_long = char(M_.param_names_long, 'cofintinfb2');
M_.param_names = char(M_.param_names, 'cofintinfb3');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinfb3');
M_.param_names_long = char(M_.param_names_long, 'cofintinfb3');
M_.param_names = char(M_.param_names, 'cofintinfb4');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinfb4');
M_.param_names_long = char(M_.param_names_long, 'cofintinfb4');
M_.param_names = char(M_.param_names, 'cofintinff1');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinff1');
M_.param_names_long = char(M_.param_names_long, 'cofintinff1');
M_.param_names = char(M_.param_names, 'cofintinff2');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinff2');
M_.param_names_long = char(M_.param_names_long, 'cofintinff2');
M_.param_names = char(M_.param_names, 'cofintinff3');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinff3');
M_.param_names_long = char(M_.param_names_long, 'cofintinff3');
M_.param_names = char(M_.param_names, 'cofintinff4');
M_.param_names_tex = char(M_.param_names_tex, 'cofintinff4');
M_.param_names_long = char(M_.param_names_long, 'cofintinff4');
M_.param_names = char(M_.param_names, 'cofintout');
M_.param_names_tex = char(M_.param_names_tex, 'cofintout');
M_.param_names_long = char(M_.param_names_long, 'cofintout');
M_.param_names = char(M_.param_names, 'cofintoutb1');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutb1');
M_.param_names_long = char(M_.param_names_long, 'cofintoutb1');
M_.param_names = char(M_.param_names, 'cofintoutb2');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutb2');
M_.param_names_long = char(M_.param_names_long, 'cofintoutb2');
M_.param_names = char(M_.param_names, 'cofintoutb3');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutb3');
M_.param_names_long = char(M_.param_names_long, 'cofintoutb3');
M_.param_names = char(M_.param_names, 'cofintoutb4');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutb4');
M_.param_names_long = char(M_.param_names_long, 'cofintoutb4');
M_.param_names = char(M_.param_names, 'cofintoutf1');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutf1');
M_.param_names_long = char(M_.param_names_long, 'cofintoutf1');
M_.param_names = char(M_.param_names, 'cofintoutf2');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutf2');
M_.param_names_long = char(M_.param_names_long, 'cofintoutf2');
M_.param_names = char(M_.param_names, 'cofintoutf3');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutf3');
M_.param_names_long = char(M_.param_names_long, 'cofintoutf3');
M_.param_names = char(M_.param_names, 'cofintoutf4');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutf4');
M_.param_names_long = char(M_.param_names_long, 'cofintoutf4');
M_.param_names = char(M_.param_names, 'cofintoutp');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutp');
M_.param_names_long = char(M_.param_names_long, 'cofintoutp');
M_.param_names = char(M_.param_names, 'cofintoutpb1');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpb1');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpb1');
M_.param_names = char(M_.param_names, 'cofintoutpb2');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpb2');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpb2');
M_.param_names = char(M_.param_names, 'cofintoutpb3');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpb3');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpb3');
M_.param_names = char(M_.param_names, 'cofintoutpb4');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpb4');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpb4');
M_.param_names = char(M_.param_names, 'cofintoutpf1');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpf1');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpf1');
M_.param_names = char(M_.param_names, 'cofintoutpf2');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpf2');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpf2');
M_.param_names = char(M_.param_names, 'cofintoutpf3');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpf3');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpf3');
M_.param_names = char(M_.param_names, 'cofintoutpf4');
M_.param_names_tex = char(M_.param_names_tex, 'cofintoutpf4');
M_.param_names_long = char(M_.param_names_long, 'cofintoutpf4');
M_.param_names = char(M_.param_names, 'std_r_');
M_.param_names_tex = char(M_.param_names_tex, 'std\_r\_');
M_.param_names_long = char(M_.param_names_long, 'std_r_');
M_.param_names = char(M_.param_names, 'std_r_quart');
M_.param_names_tex = char(M_.param_names_tex, 'std\_r\_quart');
M_.param_names_long = char(M_.param_names_long, 'std_r_quart');
M_.param_names = char(M_.param_names, 'coffispol');
M_.param_names_tex = char(M_.param_names_tex, 'coffispol');
M_.param_names_long = char(M_.param_names_long, 'coffispol');
M_.param_names = char(M_.param_names, 'curvw');
M_.param_names_tex = char(M_.param_names_tex, 'curvw');
M_.param_names_long = char(M_.param_names_long, 'curvw');
M_.param_names = char(M_.param_names, 'cgy');
M_.param_names_tex = char(M_.param_names_tex, 'cgy');
M_.param_names_long = char(M_.param_names_long, 'cgy');
M_.param_names = char(M_.param_names, 'curvp');
M_.param_names_tex = char(M_.param_names_tex, 'curvp');
M_.param_names_long = char(M_.param_names_long, 'curvp');
M_.param_names = char(M_.param_names, 'constelab');
M_.param_names_tex = char(M_.param_names_tex, 'constelab');
M_.param_names_long = char(M_.param_names_long, 'constelab');
M_.param_names = char(M_.param_names, 'constepinf');
M_.param_names_tex = char(M_.param_names_tex, 'constepinf');
M_.param_names_long = char(M_.param_names_long, 'constepinf');
M_.param_names = char(M_.param_names, 'constebeta');
M_.param_names_tex = char(M_.param_names_tex, 'constebeta');
M_.param_names_long = char(M_.param_names_long, 'constebeta');
M_.param_names = char(M_.param_names, 'cmaw');
M_.param_names_tex = char(M_.param_names_tex, 'cmaw');
M_.param_names_long = char(M_.param_names_long, 'cmaw');
M_.param_names = char(M_.param_names, 'cmap');
M_.param_names_tex = char(M_.param_names_tex, 'cmap');
M_.param_names_long = char(M_.param_names_long, 'cmap');
M_.param_names = char(M_.param_names, 'calfa');
M_.param_names_tex = char(M_.param_names_tex, 'calfa');
M_.param_names_long = char(M_.param_names_long, 'calfa');
M_.param_names = char(M_.param_names, 'czcap');
M_.param_names_tex = char(M_.param_names_tex, 'czcap');
M_.param_names_long = char(M_.param_names_long, 'czcap');
M_.param_names = char(M_.param_names, 'cbeta');
M_.param_names_tex = char(M_.param_names_tex, 'cbeta');
M_.param_names_long = char(M_.param_names_long, 'cbeta');
M_.param_names = char(M_.param_names, 'csadjcost');
M_.param_names_tex = char(M_.param_names_tex, 'csadjcost');
M_.param_names_long = char(M_.param_names_long, 'csadjcost');
M_.param_names = char(M_.param_names, 'ctou');
M_.param_names_tex = char(M_.param_names_tex, 'ctou');
M_.param_names_long = char(M_.param_names_long, 'ctou');
M_.param_names = char(M_.param_names, 'csigma');
M_.param_names_tex = char(M_.param_names_tex, 'csigma');
M_.param_names_long = char(M_.param_names_long, 'csigma');
M_.param_names = char(M_.param_names, 'chabb');
M_.param_names_tex = char(M_.param_names_tex, 'chabb');
M_.param_names_long = char(M_.param_names_long, 'chabb');
M_.param_names = char(M_.param_names, 'ccs');
M_.param_names_tex = char(M_.param_names_tex, 'ccs');
M_.param_names_long = char(M_.param_names_long, 'ccs');
M_.param_names = char(M_.param_names, 'cinvs');
M_.param_names_tex = char(M_.param_names_tex, 'cinvs');
M_.param_names_long = char(M_.param_names_long, 'cinvs');
M_.param_names = char(M_.param_names, 'cfc');
M_.param_names_tex = char(M_.param_names_tex, 'cfc');
M_.param_names_long = char(M_.param_names_long, 'cfc');
M_.param_names = char(M_.param_names, 'cindw');
M_.param_names_tex = char(M_.param_names_tex, 'cindw');
M_.param_names_long = char(M_.param_names_long, 'cindw');
M_.param_names = char(M_.param_names, 'cprobw');
M_.param_names_tex = char(M_.param_names_tex, 'cprobw');
M_.param_names_long = char(M_.param_names_long, 'cprobw');
M_.param_names = char(M_.param_names, 'cindp');
M_.param_names_tex = char(M_.param_names_tex, 'cindp');
M_.param_names_long = char(M_.param_names_long, 'cindp');
M_.param_names = char(M_.param_names, 'cprobp');
M_.param_names_tex = char(M_.param_names_tex, 'cprobp');
M_.param_names_long = char(M_.param_names_long, 'cprobp');
M_.param_names = char(M_.param_names, 'csigl');
M_.param_names_tex = char(M_.param_names_tex, 'csigl');
M_.param_names_long = char(M_.param_names_long, 'csigl');
M_.param_names = char(M_.param_names, 'clandaw');
M_.param_names_tex = char(M_.param_names_tex, 'clandaw');
M_.param_names_long = char(M_.param_names_long, 'clandaw');
M_.param_names = char(M_.param_names, 'crdpi');
M_.param_names_tex = char(M_.param_names_tex, 'crdpi');
M_.param_names_long = char(M_.param_names_long, 'crdpi');
M_.param_names = char(M_.param_names, 'crpi');
M_.param_names_tex = char(M_.param_names_tex, 'crpi');
M_.param_names_long = char(M_.param_names_long, 'crpi');
M_.param_names = char(M_.param_names, 'crdy');
M_.param_names_tex = char(M_.param_names_tex, 'crdy');
M_.param_names_long = char(M_.param_names_long, 'crdy');
M_.param_names = char(M_.param_names, 'cry');
M_.param_names_tex = char(M_.param_names_tex, 'cry');
M_.param_names_long = char(M_.param_names_long, 'cry');
M_.param_names = char(M_.param_names, 'crr');
M_.param_names_tex = char(M_.param_names_tex, 'crr');
M_.param_names_long = char(M_.param_names_long, 'crr');
M_.param_names = char(M_.param_names, 'crhoa');
M_.param_names_tex = char(M_.param_names_tex, 'crhoa');
M_.param_names_long = char(M_.param_names_long, 'crhoa');
M_.param_names = char(M_.param_names, 'crhob');
M_.param_names_tex = char(M_.param_names_tex, 'crhob');
M_.param_names_long = char(M_.param_names_long, 'crhob');
M_.param_names = char(M_.param_names, 'crhog');
M_.param_names_tex = char(M_.param_names_tex, 'crhog');
M_.param_names_long = char(M_.param_names_long, 'crhog');
M_.param_names = char(M_.param_names, 'crhoqs');
M_.param_names_tex = char(M_.param_names_tex, 'crhoqs');
M_.param_names_long = char(M_.param_names_long, 'crhoqs');
M_.param_names = char(M_.param_names, 'crhoms');
M_.param_names_tex = char(M_.param_names_tex, 'crhoms');
M_.param_names_long = char(M_.param_names_long, 'crhoms');
M_.param_names = char(M_.param_names, 'crhopinf');
M_.param_names_tex = char(M_.param_names_tex, 'crhopinf');
M_.param_names_long = char(M_.param_names_long, 'crhopinf');
M_.param_names = char(M_.param_names, 'crhow');
M_.param_names_tex = char(M_.param_names_tex, 'crhow');
M_.param_names_long = char(M_.param_names_long, 'crhow');
M_.param_names = char(M_.param_names, 'ctrend');
M_.param_names_tex = char(M_.param_names_tex, 'ctrend');
M_.param_names_long = char(M_.param_names_long, 'ctrend');
M_.param_names = char(M_.param_names, 'cg');
M_.param_names_tex = char(M_.param_names_tex, 'cg');
M_.param_names_long = char(M_.param_names_long, 'cg');
M_.param_names = char(M_.param_names, 'cgamma');
M_.param_names_tex = char(M_.param_names_tex, 'cgamma');
M_.param_names_long = char(M_.param_names_long, 'cgamma');
M_.param_names = char(M_.param_names, 'clandap');
M_.param_names_tex = char(M_.param_names_tex, 'clandap');
M_.param_names_long = char(M_.param_names_long, 'clandap');
M_.param_names = char(M_.param_names, 'cbetabar');
M_.param_names_tex = char(M_.param_names_tex, 'cbetabar');
M_.param_names_long = char(M_.param_names_long, 'cbetabar');
M_.param_names = char(M_.param_names, 'cr');
M_.param_names_tex = char(M_.param_names_tex, 'cr');
M_.param_names_long = char(M_.param_names_long, 'cr');
M_.param_names = char(M_.param_names, 'cpie');
M_.param_names_tex = char(M_.param_names_tex, 'cpie');
M_.param_names_long = char(M_.param_names_long, 'cpie');
M_.param_names = char(M_.param_names, 'crk');
M_.param_names_tex = char(M_.param_names_tex, 'crk');
M_.param_names_long = char(M_.param_names_long, 'crk');
M_.param_names = char(M_.param_names, 'cw');
M_.param_names_tex = char(M_.param_names_tex, 'cw');
M_.param_names_long = char(M_.param_names_long, 'cw');
M_.param_names = char(M_.param_names, 'cikbar');
M_.param_names_tex = char(M_.param_names_tex, 'cikbar');
M_.param_names_long = char(M_.param_names_long, 'cikbar');
M_.param_names = char(M_.param_names, 'cik');
M_.param_names_tex = char(M_.param_names_tex, 'cik');
M_.param_names_long = char(M_.param_names_long, 'cik');
M_.param_names = char(M_.param_names, 'clk');
M_.param_names_tex = char(M_.param_names_tex, 'clk');
M_.param_names_long = char(M_.param_names_long, 'clk');
M_.param_names = char(M_.param_names, 'cky');
M_.param_names_tex = char(M_.param_names_tex, 'cky');
M_.param_names_long = char(M_.param_names_long, 'cky');
M_.param_names = char(M_.param_names, 'ciy');
M_.param_names_tex = char(M_.param_names_tex, 'ciy');
M_.param_names_long = char(M_.param_names_long, 'ciy');
M_.param_names = char(M_.param_names, 'ccy');
M_.param_names_tex = char(M_.param_names_tex, 'ccy');
M_.param_names_long = char(M_.param_names_long, 'ccy');
M_.param_names = char(M_.param_names, 'crkky');
M_.param_names_tex = char(M_.param_names_tex, 'crkky');
M_.param_names_long = char(M_.param_names_long, 'crkky');
M_.param_names = char(M_.param_names, 'cwhlc');
M_.param_names_tex = char(M_.param_names_tex, 'cwhlc');
M_.param_names_long = char(M_.param_names_long, 'cwhlc');
M_.param_names = char(M_.param_names, 'cwly');
M_.param_names_tex = char(M_.param_names_tex, 'cwly');
M_.param_names_long = char(M_.param_names_long, 'cwly');
M_.param_names = char(M_.param_names, 'conster');
M_.param_names_tex = char(M_.param_names_tex, 'conster');
M_.param_names_long = char(M_.param_names_long, 'conster');
M_.param_names = char(M_.param_names, 'rstar');
M_.param_names_tex = char(M_.param_names_tex, 'rstar');
M_.param_names_long = char(M_.param_names_long, 'rstar');
M_.param_names = char(M_.param_names, 'phi_b');
M_.param_names_tex = char(M_.param_names_tex, 'phi\_b');
M_.param_names_long = char(M_.param_names_long, 'phi_b');
M_.param_names = char(M_.param_names, 'phi_g');
M_.param_names_tex = char(M_.param_names_tex, 'phi\_g');
M_.param_names_long = char(M_.param_names_long, 'phi_g');
M_.param_names = char(M_.param_names, 'omega');
M_.param_names_tex = char(M_.param_names_tex, 'omega');
M_.param_names_long = char(M_.param_names_long, 'omega');
M_.param_partitions = struct();
M_.exo_det_nbr = 0;
M_.exo_nbr = 8;
M_.endo_nbr = 85;
M_.param_nbr = 93;
M_.orig_endo_nbr = 64;
M_.aux_vars(1).endo_index = 65;
M_.aux_vars(1).type = 0;
M_.aux_vars(2).endo_index = 66;
M_.aux_vars(2).type = 0;
M_.aux_vars(3).endo_index = 67;
M_.aux_vars(3).type = 0;
M_.aux_vars(4).endo_index = 68;
M_.aux_vars(4).type = 0;
M_.aux_vars(5).endo_index = 69;
M_.aux_vars(5).type = 0;
M_.aux_vars(6).endo_index = 70;
M_.aux_vars(6).type = 0;
M_.aux_vars(7).endo_index = 71;
M_.aux_vars(7).type = 0;
M_.aux_vars(8).endo_index = 72;
M_.aux_vars(8).type = 0;
M_.aux_vars(9).endo_index = 73;
M_.aux_vars(9).type = 0;
M_.aux_vars(10).endo_index = 74;
M_.aux_vars(10).type = 1;
M_.aux_vars(10).orig_index = 63;
M_.aux_vars(10).orig_lead_lag = -1;
M_.aux_vars(11).endo_index = 75;
M_.aux_vars(11).type = 1;
M_.aux_vars(11).orig_index = 63;
M_.aux_vars(11).orig_lead_lag = -2;
M_.aux_vars(12).endo_index = 76;
M_.aux_vars(12).type = 1;
M_.aux_vars(12).orig_index = 63;
M_.aux_vars(12).orig_lead_lag = -3;
M_.aux_vars(13).endo_index = 77;
M_.aux_vars(13).type = 1;
M_.aux_vars(13).orig_index = 62;
M_.aux_vars(13).orig_lead_lag = -1;
M_.aux_vars(14).endo_index = 78;
M_.aux_vars(14).type = 1;
M_.aux_vars(14).orig_index = 62;
M_.aux_vars(14).orig_lead_lag = -2;
M_.aux_vars(15).endo_index = 79;
M_.aux_vars(15).type = 1;
M_.aux_vars(15).orig_index = 62;
M_.aux_vars(15).orig_lead_lag = -3;
M_.aux_vars(16).endo_index = 80;
M_.aux_vars(16).type = 1;
M_.aux_vars(16).orig_index = 59;
M_.aux_vars(16).orig_lead_lag = -1;
M_.aux_vars(17).endo_index = 81;
M_.aux_vars(17).type = 1;
M_.aux_vars(17).orig_index = 59;
M_.aux_vars(17).orig_lead_lag = -2;
M_.aux_vars(18).endo_index = 82;
M_.aux_vars(18).type = 1;
M_.aux_vars(18).orig_index = 59;
M_.aux_vars(18).orig_lead_lag = -3;
M_.aux_vars(19).endo_index = 83;
M_.aux_vars(19).type = 1;
M_.aux_vars(19).orig_index = 61;
M_.aux_vars(19).orig_lead_lag = -1;
M_.aux_vars(20).endo_index = 84;
M_.aux_vars(20).type = 1;
M_.aux_vars(20).orig_index = 61;
M_.aux_vars(20).orig_lead_lag = -2;
M_.aux_vars(21).endo_index = 85;
M_.aux_vars(21).type = 1;
M_.aux_vars(21).orig_index = 61;
M_.aux_vars(21).orig_lead_lag = -3;
M_.Sigma_e = zeros(8, 8);
M_.Correlation_matrix = eye(8, 8);
M_.H = 0;
M_.Correlation_matrix_ME = 1;
M_.sigma_e_is_diagonal = 1;
M_.det_shocks = [];
options_.block=0;
options_.bytecode=0;
options_.use_dll=0;
M_.hessian_eq_zero = 1;
erase_compiled_function('US_CCTW10_static');
erase_compiled_function('US_CCTW10_dynamic');
M_.orig_eq_nbr = 64;
M_.eq_nbr = 85;
M_.ramsey_eq_nbr = 0;
M_.set_auxiliary_variables = exist(['./' M_.fname '_set_auxiliary_variables.m'], 'file') == 2;
M_.lead_lag_incidence = [
 0 40 0;
 0 41 0;
 0 42 0;
 0 43 0;
 0 44 0;
 0 45 0;
 0 46 0;
 1 47 0;
 2 48 0;
 0 49 0;
 0 50 125;
 0 51 0;
 0 52 126;
 0 53 0;
 3 54 127;
 0 55 0;
 0 56 128;
 0 57 0;
 0 58 0;
 0 59 0;
 0 60 0;
 0 61 129;
 0 62 0;
 0 63 130;
 4 64 0;
 5 65 131;
 6 66 0;
 0 67 132;
 7 68 133;
 8 69 134;
 0 70 0;
 9 71 0;
 10 72 0;
 11 73 0;
 12 74 0;
 13 75 0;
 14 76 0;
 15 77 0;
 16 78 0;
 17 79 0;
 0 80 0;
 0 81 0;
 18 82 135;
 19 83 0;
 0 84 0;
 0 85 0;
 20 86 136;
 21 87 0;
 0 88 0;
 0 89 0;
 22 90 0;
 23 91 0;
 0 92 0;
 0 93 0;
 0 94 0;
 0 95 0;
 0 96 0;
 0 97 0;
 24 98 0;
 0 99 0;
 25 100 137;
 26 101 138;
 27 102 139;
 0 103 0;
 0 104 140;
 0 105 141;
 0 106 142;
 0 107 143;
 0 108 144;
 0 109 145;
 0 110 146;
 0 111 147;
 0 112 148;
 28 113 0;
 29 114 0;
 30 115 0;
 31 116 0;
 32 117 0;
 33 118 0;
 34 119 0;
 35 120 0;
 36 121 0;
 37 122 0;
 38 123 0;
 39 124 0;]';
M_.nstatic = 31;
M_.nfwrd   = 15;
M_.npred   = 30;
M_.nboth   = 9;
M_.nsfwrd   = 24;
M_.nspred   = 39;
M_.ndynamic   = 54;
M_.equations_tags = {
};
M_.static_and_dynamic_models_differ = 0;
M_.exo_names_orig_ord = [1:8];
M_.maximum_lag = 1;
M_.maximum_lead = 1;
M_.maximum_endo_lag = 1;
M_.maximum_endo_lead = 1;
oo_.steady_state = zeros(85, 1);
M_.maximum_exo_lag = 0;
M_.maximum_exo_lead = 0;
oo_.exo_steady_state = zeros(8, 1);
M_.params = NaN(93, 1);
M_.NNZDerivatives = [294; 0; -1];
M_.params( 47 ) = .025;
ctou = M_.params( 47 );
M_.params( 58 ) = 1.5;
clandaw = M_.params( 58 );
M_.params( 72 ) = 0.18;
cg = M_.params( 72 );
M_.params( 37 ) = 10;
curvp = M_.params( 37 );
M_.params( 35 ) = 10;
curvw = M_.params( 35 );
M_.params( 64 ) = 0.9602;
crhoa = M_.params( 64 );
M_.params( 65 ) = 0.2222;
crhob = M_.params( 65 );
M_.params( 66 ) = 0.9776;
crhog = M_.params( 66 );
M_.params( 67 ) = 0.7054;
crhoqs = M_.params( 67 );
M_.params( 68 ) = 0.1409;
crhoms = M_.params( 68 );
M_.params( 69 ) = 0.9076;
crhopinf = M_.params( 69 );
M_.params( 70 ) = 0.9800;
crhow = M_.params( 70 );
M_.params( 42 ) = 0.7029;
cmap = M_.params( 42 );
M_.params( 41 ) = 0.8945;
cmaw = M_.params( 41 );
M_.params( 46 ) = 5.8809;
csadjcost = M_.params( 46 );
M_.params( 48 ) = 1.2855;
csigma = M_.params( 48 );
M_.params( 49 ) = 0.6733;
chabb = M_.params( 49 );
M_.params( 54 ) = 0.7304;
cprobw = M_.params( 54 );
M_.params( 57 ) = 1.8688;
csigl = M_.params( 57 );
M_.params( 56 ) = 0.6448;
cprobp = M_.params( 56 );
M_.params( 53 ) = 0.6170;
cindw = M_.params( 53 );
M_.params( 55 ) = 0.2211;
cindp = M_.params( 55 );
M_.params( 44 ) = 0.5146;
czcap = M_.params( 44 );
M_.params( 52 ) = 1.6503;
cfc = M_.params( 52 );
M_.params( 60 ) = 2.0520;
crpi = M_.params( 60 );
M_.params( 63 ) = 0.8180;
crr = M_.params( 63 );
M_.params( 62 ) = 0.0830;
cry = M_.params( 62 );
M_.params( 61 ) = 0.2321;
crdy = M_.params( 61 );
M_.params( 39 ) = 0.8034;
constepinf = M_.params( 39 );
M_.params( 40 ) = 0.1855;
constebeta = M_.params( 40 );
M_.params( 38 ) = 0.5839;
constelab = M_.params( 38 );
M_.params( 71 ) = 0.4444;
ctrend = M_.params( 71 );
M_.params( 36 ) = 0.5223;
cgy = M_.params( 36 );
M_.params( 43 ) = 0.1914;
calfa = M_.params( 43 );
M_.params( 93 ) = 0.5;
omega = M_.params( 93 );
M_.params( 91 ) = 0.0531;
phi_b = M_.params( 91 );
M_.params( 92 ) = 0.1242;
phi_g = M_.params( 92 );
M_.params( 77 ) = 1+M_.params(39)/100;
cpie = M_.params( 77 );
M_.params( 73 ) = 1+M_.params(71)/100;
cgamma = M_.params( 73 );
M_.params( 45 ) = 1/(1+M_.params(40)/100);
cbeta = M_.params( 45 );
M_.params( 74 ) = M_.params(52);
clandap = M_.params( 74 );
M_.params( 75 ) = M_.params(45)*M_.params(73)^(-M_.params(48));
cbetabar = M_.params( 75 );
M_.params( 76 ) = M_.params(77)/(M_.params(45)*M_.params(73)^(-M_.params(48)));
cr = M_.params( 76 );
M_.params( 78 ) = M_.params(45)^(-1)*M_.params(73)^M_.params(48)-(1-M_.params(47));
crk = M_.params( 78 );
M_.params( 79 ) = (M_.params(43)^M_.params(43)*(1-M_.params(43))^(1-M_.params(43))/(M_.params(74)*M_.params(78)^M_.params(43)))^(1/(1-M_.params(43)));
cw = M_.params( 79 );
M_.params( 80 ) = 1-(1-M_.params(47))/M_.params(73);
cikbar = M_.params( 80 );
M_.params( 81 ) = M_.params(73)*(1-(1-M_.params(47))/M_.params(73));
cik = M_.params( 81 );
M_.params( 82 ) = (1-M_.params(43))/M_.params(43)*M_.params(78)/M_.params(79);
clk = M_.params( 82 );
M_.params( 83 ) = M_.params(52)*M_.params(82)^(M_.params(43)-1);
cky = M_.params( 83 );
M_.params( 84 ) = M_.params(81)*M_.params(83);
ciy = M_.params( 84 );
M_.params( 85 ) = 1-M_.params(72)-M_.params(81)*M_.params(83);
ccy = M_.params( 85 );
M_.params( 86 ) = M_.params(78)*M_.params(83);
crkky = M_.params( 86 );
M_.params( 87 ) = M_.params(83)*M_.params(78)*(1-M_.params(43))*1/M_.params(58)/M_.params(43)/M_.params(85);
cwhlc = M_.params( 87 );
M_.params( 88 ) = 1-M_.params(78)*M_.params(83);
cwly = M_.params( 88 );
M_.params( 89 ) = 100*(M_.params(76)-1);
conster = M_.params( 89 );
thispath = cd;                                                           
cd('..');                                                                
load policy_param.mat;                                                   
for i=1:33                                                               
deep_parameter_name = M_.param_names(i,:);                           
eval(['M_.params(i)  = ' deep_parameter_name ' ;'])                  
end                                                                      
cd(thispath);  
M_.params( 34 ) = 1;
coffispol = M_.params( 34 );
%
% SHOCKS instructions
%
M_.exo_det_length = 0;
M_.Sigma_e(1, 1) = (0.4558)^2;
M_.Sigma_e(2, 2) = (0.3007)^2;
M_.Sigma_e(3, 3) = (0.4620)^2;
M_.Sigma_e(4, 4) = (0.2434)^2;
M_.Sigma_e(5, 5) = (0.1356)^2;
M_.Sigma_e(6, 6) = (0.2527)^2;
M_.Sigma_e(7, 7) = (0.5324)^2;
save('US_CCTW10_results.mat', 'oo_', 'M_', 'options_');
if exist('estim_params_', 'var') == 1
  save('US_CCTW10_results.mat', 'estim_params_', '-append');
end
if exist('bayestopt_', 'var') == 1
  save('US_CCTW10_results.mat', 'bayestopt_', '-append');
end
if exist('dataset_', 'var') == 1
  save('US_CCTW10_results.mat', 'dataset_', '-append');
end
if exist('estimation_info', 'var') == 1
  save('US_CCTW10_results.mat', 'estimation_info', '-append');
end
if exist('dataset_info', 'var') == 1
  save('US_CCTW10_results.mat', 'dataset_info', '-append');
end
if exist('oo_recursive_', 'var') == 1
  save('US_CCTW10_results.mat', 'oo_recursive_', '-append');
end


disp(['Total computing time : ' dynsec2hms(toc(tic0)) ]);
if ~isempty(lastwarn)
  disp('Note: warning(s) encountered in MATLAB/Octave code')
end
diary off
